; EarthBound D0 table split ENEMY_PLACEMENT_GROUPS_TABLE.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d0-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D0:BBAC..D0:C60D EnemyPlacementGroupsTable

; ---------------------------------------------------------------------------
; D0:C60D

; EnemyPlacementGroupsTableEnd
D0C60D_EnemyPlacementGroupsTableEnd:
