; EarthBound CB asset BATTLE_BACKGROUND_PALETTE_85.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:CEF4..CB:CF14 AssetBattleBackgroundPalette85

; ---------------------------------------------------------------------------
; CB:CF14

; AssetBattleBackgroundPalette85End
CBCF14_AssetBattleBackgroundPalette85End:
