; EarthBound CB asset BATTLE_BACKGROUND_GFX_49.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:D72E..CB:D73D AssetBattleBackgroundGfx49

; ---------------------------------------------------------------------------
; CB:D73D

; AssetBattleBackgroundGfx49End
CBD73D_AssetBattleBackgroundGfx49End:
