; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_gfx_54.asm

hirom
org $CBAB1E

!CBABF5_AssetBattleBackgroundGfx54End = BATTLE_BACKGROUND_GFX_99

; Original terminal data gap ending at $CBABF5
db $0F,$00,$0F,$00,$1F,$00,$3F,$78,$7F,$F8,$FE,$18,$1C,$18,$18,$90
db $10,$29,$00,$04,$E0,$00,$E0,$00,$E0,$2E,$00,$AB,$00,$1E,$04,$01
db $00,$03,$00,$07,$E4,$2A,$00,$04,$01,$00,$01,$00,$01,$90,$00,$2F
db $22,$0C,$1B,$1C,$0F,$3F,$4F,$3F,$C0,$3E,$C0,$3C,$F8,$00,$F0,$00
db $0C,$03,$1C,$03,$3F,$00,$7F,$00,$FE,$00,$FC,$00,$F8,$00,$F0,$85
db $00,$35,$00,$01,$A3,$00,$36,$A6,$00,$6A,$03,$07,$00,$03,$01,$B4
db $00,$35,$00,$01,$CE,$00,$6A,$01,$01,$00,$91,$00,$3B,$01,$04,$04
db $8D,$00,$2F,$0B,$04,$03,$06,$0E,$07,$1F,$27,$1F,$60,$1F,$E0,$1E
db $85,$00,$9A,$00,$01,$83,$00,$01,$8C,$00,$94,$01,$03,$03,$89,$00
db $CA,$02,$20,$20,$07,$C9,$00,$3E,$A4,$00,$FB,$01,$00,$00,$CB,$01
db $2D,$8E,$00,$CD,$01,$03,$07,$8C,$00,$3E,$03,$02,$02,$06,$06,$8B
db $00,$C0,$02,$01,$03,$01,$84,$00,$2E,$03,$3C,$00,$3E,$00,$41,$30
db $0F,$13,$10,$0F,$00,$0F,$F0,$F0,$F8,$F8,$FC,$FC,$FE,$FE,$7F,$7F
db $3F,$3F,$1F,$1F,$0F,$0F,$FF
