; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_arr_27.asm

hirom
org $CBAFED

!CBB0AD_AssetBattleBackgroundArr27End = BATTLE_BACKGROUND_GFX_101

; Original terminal data gap ending at $CBB0AD
db $0D,$00,$E0,$01,$A0,$02,$A0,$03,$20,$04,$60,$05,$A0,$06,$60,$43
db $07,$20,$09,$08,$20,$09,$E0,$0A,$20,$0B,$20,$0C,$A0,$9F,$00,$00
db $43,$07,$20,$17,$0D,$A0,$0E,$60,$0F,$A0,$10,$A0,$11,$A0,$12,$20
db $13,$E0,$14,$E0,$15,$20,$16,$E0,$0A,$E0,$07,$20,$9F,$00,$40,$89
db $00,$1E,$01,$17,$20,$8D,$00,$0C,$04,$07,$20,$0A,$20,$0B,$9F,$00
db $7F,$00,$20,$8B,$00,$5E,$01,$18,$E0,$89,$00,$4E,$01,$07,$20,$85
db $00,$58,$9F,$00,$C0,$00,$0B,$F0,$3E,$00,$7F,$01,$0A,$E0,$F0,$3D
db $00,$C0,$83,$00,$1C,$F0,$3B,$00,$00,$83,$00,$5C,$F0,$37,$00,$40
db $F0,$7F,$01,$7C,$83,$00,$58,$8B,$00,$1E,$01,$07,$20,$8D,$00,$0A
db $03,$19,$A0,$0B,$20,$9F,$02,$80,$8D,$00,$5E,$01,$07,$20,$89,$00
db $4C,$00,$1A,$84,$00,$59,$9F,$02,$C0,$F0,$3D,$02,$82,$01,$0C,$A0
db $F0,$3D,$02,$C2,$01,$07,$20,$F0,$7F,$00,$00,$F3,$FF,$00,$00,$FF
