; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_21.asm

hirom
org $CBD414

!CBD434_AssetBattleBackgroundPalette21End = BATTLE_BACKGROUND_PALETTE_20

; Original terminal data gap ending at $CBD434
db $00,$00,$00,$02,$55,$1C,$75,$18,$95,$18,$D5,$14,$15,$19,$55,$1D
db $95,$21,$D5,$25,$15,$2A,$35,$2E,$75,$32,$95,$36,$B5,$3A,$D6,$42
