; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_81.asm

hirom
org $CBD76A

!CBD772_AssetBattleBackgroundPalette81End = BATTLE_BACKGROUND_PALETTE_80

; Original terminal data gap ending at $CBD772
db $00,$00,$88,$28,$0C,$39,$D0,$41
