; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_61.asm

hirom
org $CBD7EA

!CBD7F2_AssetBattleBackgroundPalette61End = BATTLE_BACKGROUND_PALETTE_60

; Original terminal data gap ending at $CBD7F2
db $00,$00,$D0,$68,$0A,$51,$8C,$40
