; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_45.asm

hirom
org $CBD134

!CBD154_AssetBattleBackgroundPalette45End = BATTLE_BACKGROUND_PALETTE_44

; Original terminal data gap ending at $CBD154
db $00,$00,$DE,$7B,$DC,$73,$D8,$73,$D6,$73,$96,$6B,$94,$6B,$94,$6B
db $52,$6B,$50,$6B,$50,$6B,$10,$6B,$D0,$62,$90,$62,$90,$62,$50,$62
