; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_77.asm

hirom
org $CBCF94

!CBCFB4_AssetBattleBackgroundPalette77End = BATTLE_BACKGROUND_PALETTE_73

; Original terminal data gap ending at $CBCFB4
db $00,$00,$94,$52,$C6,$08,$E8,$0C,$29,$11,$6B,$15,$AD,$1D,$EF,$25
db $31,$2E,$73,$36,$B5,$3E,$F7,$4A,$39,$57,$7B,$63,$9C,$6B,$BD,$6F
