; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_arr_3.asm

hirom
org $CBB22A

!CBB2E1_AssetBattleBackgroundArr3End = BATTLE_BACKGROUND_ARR_70

; Original terminal data gap ending at $CBB2E1
db $0F,$00,$A0,$01,$A0,$02,$60,$03,$A0,$04,$E0,$05,$20,$06,$E0,$00
db $20,$8F,$00,$00,$9F,$00,$00,$0F,$06,$60,$07,$A0,$08,$60,$09,$60
db $0A,$E0,$0B,$E0,$0C,$E0,$0D,$E0,$8F,$00,$40,$9F,$00,$40,$0F,$05
db $A0,$0E,$60,$0F,$A0,$10,$A0,$11,$20,$12,$20,$13,$E0,$14,$20,$8F
db $00,$80,$9F,$00,$80,$0E,$15,$60,$16,$A0,$17,$A0,$18,$60,$19,$E0
db $1A,$20,$1B,$E0,$1C,$8F,$00,$BF,$9F,$00,$BF,$C7,$00,$CF,$08,$20
db $18,$A0,$17,$60,$16,$60,$15,$A0,$8F,$01,$00,$9F,$01,$00,$C4,$00
db $8E,$04,$E0,$11,$E0,$10,$60,$C4,$00,$84,$00,$60,$8F,$01,$40,$9F
db $01,$40,$09,$0D,$20,$0C,$20,$0B,$20,$0A,$20,$09,$A0,$C4,$00,$44
db $00,$A0,$8F,$01,$80,$9F,$01,$80,$C6,$00,$0E,$00,$20,$C4,$00,$06
db $02,$60,$00,$60,$8F,$01,$C0,$9F,$01,$C0,$F1,$FF,$00,$00,$F2,$FF
db $00,$00,$F0,$FF,$00,$00,$FF
