; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cb/asset_battle_background_palette_107.asm

hirom
org $CBCC94

!CBCCB4_AssetBattleBackgroundPalette107End = BATTLE_BACKGROUND_PALETTE_106

; Original terminal data gap ending at $CBCCB4
db $00,$00,$C0,$35,$A0,$39,$C0,$31,$62,$31,$88,$3D,$64,$2D,$64,$2D
db $86,$39,$68,$41,$4B,$49,$64,$2D,$86,$35,$46,$39,$87,$41,$A8,$49
