; EarthBound CB asset BATTLE_BACKGROUND_GFX_98.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:9CC8..CB:9DE3 AssetBattleBackgroundGfx98

; ---------------------------------------------------------------------------
; CB:9DE3

; AssetBattleBackgroundGfx98End
CB9DE3_AssetBattleBackgroundGfx98End:
