; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d5/asset_sprite_1117.asm

hirom
org $D53740

!D537C0_AssetSprite1117End = SPRITE_1118

; Original terminal data gap ending at $D537C0
db $03,$03,$04,$05,$0C,$0E,$0C,$0F,$17,$17,$1D,$15,$29,$29,$26,$2F
db $03,$03,$05,$06,$0E,$09,$0F,$08,$17,$1A,$15,$1A,$29,$36,$2F,$30
db $C0,$C0,$A0,$A0,$D0,$10,$50,$D0,$E8,$E8,$E8,$E8,$EC,$E4,$9E,$82
db $C0,$C0,$A0,$60,$10,$F0,$D0,$30,$E8,$D8,$E8,$98,$E4,$9C,$82,$FE
db $69,$4D,$7C,$58,$7E,$5A,$7E,$5A,$DE,$DA,$DE,$DA,$FE,$EA,$7D,$74
db $4D,$7B,$58,$6F,$5A,$6D,$5A,$6D,$DA,$6D,$DA,$6D,$EA,$3D,$74,$0B
db $9E,$82,$3E,$26,$FE,$26,$FF,$2F,$FF,$2F,$FE,$2C,$FD,$29,$FA,$32
db $82,$FE,$26,$FE,$26,$FE,$2F,$FE,$2F,$FE,$2C,$FF,$29,$FE,$32,$FC
