; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d5/asset_sprite_1038.asm

hirom
org $D50580

!D50600_AssetSprite1038End = SPRITE_1039

; Original terminal data gap ending at $D50600
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$07,$07
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$07,$07
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$C0,$00
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$C0,$00
db $07,$04,$03,$02,$07,$07,$0F,$0B,$0F,$09,$0F,$09,$1F,$05,$07,$07
db $07,$07,$03,$03,$07,$07,$0F,$0F,$0B,$0B,$09,$09,$1D,$05,$03,$07
db $C0,$C0,$A0,$60,$E0,$E0,$A0,$E0,$20,$E0,$30,$F0,$70,$D0,$E0,$E0
db $C0,$C0,$E0,$E0,$E0,$E0,$E0,$E0,$E0,$E0,$E0,$F0,$E0,$D0,$80,$E0
