; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d5/table_stats_growth_vars.asm

hirom
org $D5EA5B


; Original data gap before D5EA77_StatsGrowthVarsEnd:
db $12,$05,$04,$07,$05,$05,$06,$0C,$03,$08,$05,$02,$07,$05,$0A,$06
db $05,$05,$03,$09,$04,$15,$12,$07,$03,$04,$04,$03

D5EA77_StatsGrowthVarsEnd:
