; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d2/asset_sprite_0329.asm

hirom
org $D2ED80

!D2EE40_AssetSprite0329End = SPRITE_0330

; Original terminal data gap ending at $D2EE40
db $07,$07,$18,$18,$17,$10,$2F,$2B,$38,$30,$2F,$2F,$57,$57,$7F,$5F
db $07,$07,$1F,$1F,$1F,$1F,$3F,$3F,$38,$3F,$3F,$38,$77,$7A,$7F,$72
db $70,$70,$88,$88,$46,$06,$F9,$91,$7D,$71,$8F,$8D,$FA,$FA,$F5,$F1
db $70,$70,$F8,$F8,$FE,$FE,$FF,$FF,$7F,$FF,$8F,$7F,$FE,$2E,$F7,$2F
db $7F,$5F,$6F,$43,$7E,$4B,$7F,$6F,$A7,$A7,$9B,$8F,$7B,$7F,$2B,$3F
db $7F,$70,$73,$7C,$7A,$75,$7F,$78,$FF,$FC,$FE,$FA,$75,$71,$35,$21
db $FD,$F9,$FF,$E3,$BA,$EA,$79,$F9,$F7,$F3,$ED,$F9,$E6,$7E,$EE,$7E
db $FF,$07,$E7,$1F,$AE,$56,$7F,$8F,$FF,$1F,$BF,$AF,$5E,$46,$52,$42
db $77,$5F,$7F,$7F,$37,$37,$0F,$0F,$04,$04,$07,$3F,$0F,$FF,$1E,$3F
db $5D,$45,$7F,$4F,$37,$37,$0F,$0F,$04,$07,$3F,$05,$FF,$09,$3F,$1E
db $EF,$FB,$FE,$FE,$FC,$FC,$F8,$F8,$A0,$A0,$F0,$FC,$78,$FF,$00,$FC
db $DB,$C9,$FE,$FA,$FC,$FC,$F8,$F8,$A0,$E0,$FC,$90,$FF,$78,$FC,$00
