; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d2/asset_sprite_0296.asm

hirom
org $D2D4C0

!D2D580_AssetSprite0296End = SPRITE_0297

; Original terminal data gap ending at $D2D580
db $03,$03,$0F,$0F,$1F,$1F,$3F,$3F,$7F,$7F,$7F,$7B,$BF,$BF,$BF,$BF
db $03,$03,$0F,$0F,$1F,$10,$3F,$20,$67,$40,$7B,$40,$BB,$D8,$BF,$D0
db $80,$80,$E0,$E0,$90,$90,$E8,$E8,$F8,$F8,$F8,$F8,$DC,$FC,$FC,$FC
db $80,$80,$E0,$E0,$90,$70,$E8,$18,$F8,$08,$F8,$78,$FC,$DC,$FC,$7C
db $BF,$BF,$67,$61,$7F,$41,$79,$51,$38,$30,$1F,$17,$0F,$0D,$0F,$0A
db $BF,$D0,$61,$7E,$41,$46,$51,$56,$30,$27,$17,$16,$0D,$0D,$0A,$0A
db $FC,$FC,$FC,$FC,$EA,$EA,$D9,$D9,$29,$29,$DC,$DC,$E8,$28,$F0,$10
db $FC,$7C,$FC,$9C,$EA,$1A,$D9,$39,$29,$E9,$DC,$DC,$28,$28,$10,$10
db $0C,$0B,$1F,$17,$1F,$15,$3F,$33,$3F,$3F,$7F,$5F,$34,$FF,$18,$3F
db $08,$08,$17,$17,$15,$15,$20,$20,$30,$30,$5F,$5F,$EF,$24,$3F,$18
db $68,$D8,$EC,$FC,$FC,$3C,$C8,$38,$F4,$BC,$FC,$FC,$78,$EF,$10,$FC
db $48,$48,$EC,$E4,$3C,$34,$08,$08,$1C,$14,$94,$94,$EF,$68,$FC,$10
