; EarthBound D2 asset SPRITE_0220.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:8300..D2:83C0 AssetSprite0220

; ---------------------------------------------------------------------------
; D2:83C0

; AssetSprite0220End
D283C0_AssetSprite0220End:
