; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d2/asset_sprite_0305.asm

hirom
org $D2DB80

!D2DC40_AssetSprite0305End = SPRITE_0306

; Original terminal data gap ending at $D2DC40
db $01,$01,$03,$02,$07,$07,$3D,$3F,$6A,$7F,$6F,$7F,$7F,$7F,$7F,$7F
db $01,$01,$03,$02,$07,$07,$38,$3F,$42,$7F,$47,$7D,$4F,$78,$5F,$72
db $C0,$C0,$E0,$60,$F0,$F0,$5E,$FE,$EB,$FF,$7F,$7F,$FF,$FF,$FF,$FF
db $C0,$C0,$A0,$20,$F0,$F0,$0E,$FE,$A1,$FF,$71,$DF,$F9,$0F,$FD,$27
db $7F,$7F,$7F,$67,$5F,$57,$0F,$0F,$07,$07,$0F,$0B,$15,$1A,$26,$39
db $5F,$72,$67,$78,$77,$78,$2F,$28,$07,$04,$0B,$0F,$10,$1F,$20,$3F
db $FF,$FF,$FF,$F3,$FD,$F5,$78,$F8,$F0,$F0,$F8,$E8,$D4,$2C,$32,$CE
db $FD,$27,$F3,$0F,$F7,$0F,$7A,$8A,$F0,$10,$E8,$78,$04,$FC,$02,$FE
db $7B,$5C,$78,$7F,$30,$3F,$17,$1F,$0F,$0F,$0F,$3F,$11,$FF,$0E,$3F
db $58,$4F,$7C,$4B,$3D,$30,$18,$10,$0C,$0C,$38,$0F,$F1,$17,$3F,$0E
db $EF,$1B,$0F,$FF,$FE,$FE,$44,$FC,$84,$FC,$84,$FC,$48,$FF,$38,$FC
db $0B,$F9,$1F,$E9,$3E,$3E,$44,$4C,$84,$BC,$84,$BC,$CF,$78,$FC,$38
