; EarthBound D2 asset SPRITE_0224.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:8600..D2:86C0 AssetSprite0224

; ---------------------------------------------------------------------------
; D2:86C0

; AssetSprite0224End
D286C0_AssetSprite0224End:
