; EarthBound D2 asset SPRITE_0281.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:C980..D2:CA40 AssetSprite0281

; ---------------------------------------------------------------------------
; D2:CA40

; AssetSprite0281End
D2CA40_AssetSprite0281End:
