; EarthBound D2 asset SPRITE_0125.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:0180..D2:0240 AssetSprite0125

; ---------------------------------------------------------------------------
; D2:0240

; AssetSprite0125End
D20240_AssetSprite0125End:
