; EarthBound D2 asset SPRITE_0132.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:06C0..D2:0780 AssetSprite0132

; ---------------------------------------------------------------------------
; D2:0780

; AssetSprite0132End
D20780_AssetSprite0132End:
