; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d2/asset_sprite_0196.asm

hirom
org $D27100

!D271C0_AssetSprite0196End = SPRITE_0197

; Original terminal data gap ending at $D271C0
db $1F,$1F,$11,$1F,$0B,$0F,$0D,$0F,$0F,$0F,$1F,$10,$3F,$3F,$7F,$47
db $1F,$1F,$1E,$10,$0F,$0B,$0E,$0C,$0F,$0F,$10,$1F,$3F,$3F,$47,$7F
db $FC,$FC,$04,$3C,$E8,$F8,$98,$F8,$F8,$F8,$FC,$04,$FE,$FE,$FF,$F1
db $FC,$FC,$FC,$C4,$F8,$E8,$78,$18,$F8,$F8,$04,$FC,$FE,$FE,$F1,$7F
db $7F,$40,$3F,$36,$1F,$13,$0F,$09,$06,$04,$1B,$1E,$2B,$3E,$2B,$3F
db $40,$7F,$36,$3F,$13,$1F,$09,$0F,$05,$07,$1A,$1E,$2B,$3F,$2B,$3F
db $FF,$81,$FE,$36,$FC,$E4,$78,$48,$F0,$90,$EC,$FC,$AA,$FE,$FA,$1E
db $81,$FF,$36,$FE,$E4,$FC,$C8,$F8,$90,$F0,$EC,$FC,$AA,$FE,$1A,$FE
db $3F,$3E,$3F,$33,$13,$12,$09,$08,$0C,$0C,$1F,$3F,$1B,$FF,$0E,$3F
db $3E,$3E,$3F,$3E,$1F,$1F,$0F,$0F,$0F,$0F,$3F,$1F,$F7,$13,$3F,$0E
db $FA,$9E,$7E,$7E,$58,$78,$78,$78,$FC,$FC,$6C,$FC,$38,$FF,$00,$FC
db $9A,$FE,$FE,$FE,$D8,$F8,$F8,$F8,$FC,$FC,$F4,$64,$FF,$38,$FC,$00
