; EarthBound ED asset AUDIO_PACK_86.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ed-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - ED:8B21..ED:91AF AssetAudioPack86

; ---------------------------------------------------------------------------
; ED:91AF

; AssetAudioPack86End
ED91AF_AssetAudioPack86End:
