; EarthBound D9 asset MAP_DATA_TILE_ARRANGEMENT_2.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d9-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D9:34E9..D9:68AB AssetMapDataTileArrangement2

; ---------------------------------------------------------------------------
; D9:68AB

; AssetMapDataTileArrangement2End
D968AB_AssetMapDataTileArrangement2End:
