; EarthBound C4 current-slot anchor staging helpers.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:6C45..C4:6D4B CurrentSlotAnchorStagingHelpers

; ---------------------------------------------------------------------------
; External contracts used by this module

C08E9A_GetRandom16                                    = $C08E9A
C46028_FindEntitySlotByCachedPoseDescriptorId         = $C46028
C4608C_ResolveEntitySlotFromOverworldTypeRegistryCode = $C4608C
CurrentSlotIndex                                      = $1A42
LiveEntityWorldXTable                                 = $0B8E
LiveEntityWorldYTable                                 = $0BCA
CurrentSlotTargetXTable                               = $0FC6
CurrentSlotTargetYTable                               = $1002
CurrentSlotStagedXTable                               = $0E5E
CurrentSlotStagedYTable                               = $0E9A
CameraOriginX                                         = $0031
CameraOriginY                                         = $0033
CameraRelativeFlag0C7ETable                           = $0C7E
CameraRelativeFlag0C42Table                           = $0C42
CameraRelativeFlagValue                               = $8000
RandomCameraXOffset                                   = $0070

; ---------------------------------------------------------------------------
; C4:6C45

C46C45_SnapshotCurrentSlotAnchorToStagedPosition:
    ; Snapshot the current slot's live anchor into the local staged-position
    ; words used by nearby movement/action-script helpers.
    rep #$31
    lda CurrentSlotIndex
    asl A
    tax
    lda LiveEntityWorldXTable,X
    sta CurrentSlotStagedXTable,X
    lda CurrentSlotIndex
    asl A
    tax
    lda LiveEntityWorldYTable,X
    sta CurrentSlotStagedYTable,X
    rtl
C46C5E_SetStagedPositionOffsetFromCurrentAnchor:
    ; X/Y offsets from the caller are added to the current slot's live anchor
    ; and written into the staged-position words.
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sta $0E
    lda CurrentSlotIndex
    asl A
    tay
    txa
    clc
    adc LiveEntityWorldXTable,Y
    sta CurrentSlotStagedXTable,Y
    lda CurrentSlotIndex
    asl A
    tax
    lda $0E
    clc
    adc LiveEntityWorldYTable,X
    sta CurrentSlotStagedYTable,X
    pld
    rtl
C46C87_RestoreCurrentSlotAnchorFromCachedTarget:
    ; Restore current live anchor from the cached target pair.
    rep #$31
    lda CurrentSlotIndex
    asl A
    tax
    lda CurrentSlotTargetXTable,X
    sta LiveEntityWorldXTable,X
    lda CurrentSlotTargetYTable,X
    sta LiveEntityWorldYTable,X
    rtl
C46C9B_CopyRegistrySlotAnchorToCurrentSlot:
    ; Resolve a registry code and copy that slot's live anchor into the
    ; current slot's live anchor.
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    ldx CurrentSlotIndex
    stx $10
    jsl C4608C_ResolveEntitySlotFromOverworldTypeRegistryCode
    sta $0E
    ldx $10
    txa
    asl A
    tay
    lda $0E
    asl A
    tax
    lda LiveEntityWorldXTable,X
    sta LiveEntityWorldXTable,Y
    lda LiveEntityWorldYTable,X
    sta LiveEntityWorldYTable,Y
    pld
    rtl
C46CC7_CopyPoseDescriptorSlotAnchorToCurrentSlot:
    ; Cached pose-descriptor keyed sibling of C46C9B.
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    tax
    ldy CurrentSlotIndex
    sty $10
    txa
    jsl C46028_FindEntitySlotByCachedPoseDescriptorId
    sta $0E
    ldy $10
    tya
    asl A
    tay
    lda $0E
    asl A
    tax
    lda LiveEntityWorldXTable,X
    sta LiveEntityWorldXTable,Y
    lda LiveEntityWorldYTable,X
    sta LiveEntityWorldYTable,Y
    pld
    rtl
C46CF5_SetCurrentSlotCameraRelativeAnchorWithFlags:
    ; Place the current slot relative to the camera origin and mark the paired
    ; camera-relative flag words. Keep these flag names local to this helper.
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF2
    tcd
    pla
    stx $02
    tay
    lda CurrentSlotIndex
    asl A
    tax
    lda $02
    clc
    adc CameraOriginX
    sta LiveEntityWorldXTable,X
    tya
    clc
    adc CameraOriginY
    sta LiveEntityWorldYTable,X
    lda.w #CameraRelativeFlagValue
    sta CameraRelativeFlag0C7ETable,X
    sta CameraRelativeFlag0C42Table,X
    pld
    rtl
C46D23_PlaceCurrentSlotAtRandomCameraXPlus70Y:
    ; Random camera-relative X placement used by screen-edge/scripted spawn
    ; setup. Y is the camera origin Y without an added random component.
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda CurrentSlotIndex
    asl A
    tax
    stx $0E
    jsl C08E9A_GetRandom16
    clc
    adc CameraOriginX
    clc
    adc.w #RandomCameraXOffset
    ldx $0E
    sta LiveEntityWorldXTable,X
    lda CameraOriginY
    sta LiveEntityWorldYTable,X
    pld
    rtl
