; EarthBound D4 asset SPRITE_0978.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:DFE0..D4:E060 AssetSprite0978

; ---------------------------------------------------------------------------
; D4:E060

; AssetSprite0978End
D4E060_AssetSprite0978End:
