; EarthBound D4 asset SPRITE_0927.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:BC20..D4:BCE0 AssetSprite0927

; ---------------------------------------------------------------------------
; D4:BCE0

; AssetSprite0927End
D4BCE0_AssetSprite0927End:
