; EarthBound D4 asset SPRITE_0913.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:B4E0..D4:B560 AssetSprite0913

; ---------------------------------------------------------------------------
; D4:B560

; AssetSprite0913End
D4B560_AssetSprite0913End:
