; EarthBound D4 asset SPRITE_0945.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:C8E0..D4:C9A0 AssetSprite0945

; ---------------------------------------------------------------------------
; D4:C9A0

; AssetSprite0945End
D4C9A0_AssetSprite0945End:
