; EarthBound D4 asset SPRITE_0882.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:9DE0..D4:9E60 AssetSprite0882

; ---------------------------------------------------------------------------
; D4:9E60

; AssetSprite0882End
D49E60_AssetSprite0882End:
