; EarthBound C1 Classify equipped item offensive defensive and statistic selector text commands.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:7708..C1:7796 c1_7708_classify_equipped_item_offensive_defensive

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7
C1045D_InstallPrimaryInteractionContextPointer = $045D
C103DC_ReadTextCommandArgumentWord = $03DC
C3EE7A_ResolveStatisticSelectorValue = $C3EE7A

TextCommandArgumentValueLo = $06
TextCommandArgumentValueHi = $08
TextContextSourcePointerLo = $0E
TextContextSourcePointerHi = $10
ProcessorStatus16BitAIndexCarryClear = $31
FarCallerFrameAliasOffset = $FFEE
ItemRecordPointerIndex = $0027
ItemEquipSlotFamilyOffset = $0019
ItemDataBase = $D55000
LowByteMask = $00FF
EquipmentFamilyMask = $000C
EquipmentFamilyWeapon = $0000
EquipmentFamilyBody = $0004
EquipmentFamilyArms = $0008
EquipmentFamilyOther = $000C
TextResultNotEquipment = $0000
TextResultOffensiveEquipment = $0001
TextResultDefensiveEquipment = $0002
ZeroWord = $0000

; ---------------------------------------------------------------------------
; C1:7708

CC_1D_23:
C17708_ClassifyEquippedItemOffensiveDefensive = CC_1D_23
    rep #ProcessorStatus16BitAIndexCarryClear
    phd
    pha
    tdc
    adc.w #FarCallerFrameAliasOffset
    tcd
    pla
    txa
    beq C1771B_ReadEquipmentItemArgumentFromTextCommand
    sta TextCommandArgumentValueLo
    stz TextCommandArgumentValueHi
    bra C1771E_ClassifyEquipmentSlotFamily
C1771B_ReadEquipmentItemArgumentFromTextCommand:
    jsr C103DC_ReadTextCommandArgumentWord
C1771E_ClassifyEquipmentSlotFamily:
    lda TextCommandArgumentValueLo
    ldy.w #ItemRecordPointerIndex
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #ItemEquipSlotFamilyOffset
    tax
    lda ItemDataBase,X
    and.w #LowByteMask
    and.w #EquipmentFamilyMask
    beq C17749_ReturnOffensiveEquipmentClass
    cmp.w #EquipmentFamilyBody
    beq C1774E_ReturnDefensiveEquipmentClass
    cmp.w #EquipmentFamilyArms
    beq C1774E_ReturnDefensiveEquipmentClass
    cmp.w #EquipmentFamilyOther
    beq C1774E_ReturnDefensiveEquipmentClass
    bra C17753_ReturnNoEquipmentClass
C17749_ReturnOffensiveEquipmentClass:
    lda.w #TextResultOffensiveEquipment
    bra C17756_StageEquipmentClassTextResult
C1774E_ReturnDefensiveEquipmentClass:
    lda.w #TextResultDefensiveEquipment
    bra C17756_StageEquipmentClassTextResult
C17753_ReturnNoEquipmentClass:
    lda.w #TextResultNotEquipment
C17756_StageEquipmentClassTextResult:
    sta TextCommandArgumentValueLo
    stz TextCommandArgumentValueHi
    lda TextCommandArgumentValueLo
    sta TextContextSourcePointerLo
    lda TextCommandArgumentValueHi
    sta TextContextSourcePointerHi
    jsr C1045D_InstallPrimaryInteractionContextPointer
    lda.w #ZeroWord
    pld
    rts
CC_19_27:
C1776A_StageStatisticSelectorValueTextCommand = CC_19_27
    rep #ProcessorStatus16BitAIndexCarryClear
    phd
    pha
    tdc
    adc.w #FarCallerFrameAliasOffset
    tcd
    pla
    txa
    beq C1777D_ReadStatisticSelectorArgumentFromTextCommand
    sta TextCommandArgumentValueLo
    stz TextCommandArgumentValueHi
    bra C17780_ResolveStatisticSelectorTextValue
C1777D_ReadStatisticSelectorArgumentFromTextCommand:
    jsr C103DC_ReadTextCommandArgumentWord
C17780_ResolveStatisticSelectorTextValue:
    lda TextCommandArgumentValueLo
    jsl C3EE7A_ResolveStatisticSelectorValue
    lda TextCommandArgumentValueLo
    sta TextContextSourcePointerLo
    lda TextCommandArgumentValueHi
    sta TextContextSourcePointerHi
    jsr C1045D_InstallPrimaryInteractionContextPointer
    lda.w #ZeroWord
    pld
    rts
