; EarthBound D0 table split BTL_ENTRY_PTR_TABLE.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d0-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D0:C60D..D0:D52D BtlEntryPtrTable

; ---------------------------------------------------------------------------
; D0:D52D

; BtlEntryPtrTableEnd
D0D52D_BtlEntryPtrTableEnd:
