; EarthBound EE asset AUDIO_PACK_49.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ee-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - EE:87CB..EE:894F AssetAudioPack49

; ---------------------------------------------------------------------------
; EE:894F

; AssetAudioPack49End
EE894F_AssetAudioPack49End:
