; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_119.asm

hirom
org $CED5F0

!CED77B_AssetSwirlData119End = SWIRL_DATA_120

; Original terminal data gap ending at $CED77B
db $01,$01,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF
db $FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
db $03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00
db $FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85
db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00
db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF
db $FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00
db $00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF
db $FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
db $03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00
db $FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85
db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00
db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF
db $FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00
db $00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF
db $FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
db $03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00
db $FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85
db $FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00
db $00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF
db $FF,$00,$00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00
db $00,$FF,$FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF
db $FF,$00,$03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00
db $03,$00,$FF,$85,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$FF,$00,$03,$00
db $FF,$84,$FF,$00,$00,$FF,$FF,$00,$00,$FF,$00
