; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_battle_sprites_palettes_14_pal.asm

hirom
org $CE66D4


; Original data gap before CE66F4_AssetBattleSpritesPalettes14PalEnd:
db $37,$01,$1F,$77,$59,$6E,$B3,$41,$ED,$5C,$47,$1D,$05,$1D,$DE,$5B
db $98,$36,$0C,$26,$90,$21,$0A,$15,$DE,$7B,$39,$67,$31,$46,$86,$10

CE66F4_AssetBattleSpritesPalettes14PalEnd:
