; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_5.asm

hirom
org $CE6A9D

!CE6B48_AssetSwirlData5End = SWIRL_DATA_6

; Original terminal data gap ending at $CE6B48
db $04,$5E,$FF,$00,$FF,$00,$8A,$82,$8C,$FF,$00,$7D,$90,$FF,$00,$7B
db $93,$FF,$00,$79,$95,$FF,$00,$77,$97,$FF,$00,$75,$99,$FF,$00,$74
db $9A,$FF,$00,$73,$9B,$FF,$00,$72,$9C,$FF,$00,$72,$9D,$FF,$00,$02
db $71,$9E,$FF,$00,$02,$70,$9F,$FF,$00,$02,$70,$A0,$FF,$00,$03,$70
db $A1,$FF,$00,$02,$71,$A2,$FF,$00,$97,$72,$A2,$FF,$00,$73,$A2,$FF
db $00,$74,$A2,$FF,$00,$75,$A2,$FF,$00,$77,$A2,$FF,$00,$79,$8F,$90
db $A2,$7B,$8D,$91,$A1,$7F,$8A,$92,$A1,$93,$A1,$FF,$00,$94,$A0,$FF
db $00,$93,$A0,$FF,$00,$76,$78,$92,$9F,$75,$7B,$90,$9F,$74,$7F,$8C
db $9E,$73,$9D,$FF,$00,$72,$9C,$FF,$00,$71,$9B,$FF,$00,$70,$9A,$FF
db $00,$71,$99,$FF,$00,$74,$97,$FF,$00,$77,$95,$FF,$00,$7A,$92,$FF
db $00,$7F,$8E,$FF,$00,$56,$FF,$00,$FF,$00,$00
