; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_4.asm

hirom
org $CE6A05

!CE6A9D_AssetSwirlData4End = SWIRL_DATA_5

; Original terminal data gap ending at $CE6A9D
db $04,$5E,$FF,$00,$FF,$00,$91,$82,$8C,$FF,$00,$7D,$90,$FF,$00,$7B
db $93,$FF,$00,$79,$95,$FF,$00,$77,$97,$FF,$00,$75,$98,$FF,$00,$74
db $9A,$FF,$00,$73,$9B,$FF,$00,$72,$89,$8C,$9C,$72,$89,$90,$9D,$71
db $88,$93,$9E,$71,$88,$95,$9E,$70,$88,$96,$9F,$70,$8A,$97,$9F,$70
db $8D,$98,$A0,$70,$8F,$99,$A0,$70,$90,$99,$A1,$02,$70,$91,$9A,$A1
db $02,$71,$92,$9B,$A2,$8F,$72,$92,$9B,$A2,$73,$92,$9B,$A2,$74,$92
db $9B,$A2,$75,$91,$9A,$A2,$77,$90,$9A,$A2,$79,$8F,$99,$A2,$7B,$8D
db $99,$A1,$7F,$8A,$98,$A1,$97,$A1,$FF,$00,$98,$A0,$FF,$00,$99,$A0
db $FF,$00,$9A,$9F,$FF,$00,$9B,$9F,$FF,$00,$9C,$9E,$FF,$00,$9C,$9D
db $FF,$00,$5E,$FF,$00,$FF,$00,$00
