; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_21.asm

hirom
org $CE8523

!CE85B9_AssetSwirlData21End = SWIRL_DATA_22

; Original terminal data gap ending at $CE85B9
db $01,$98,$40,$FF,$3D,$FF,$3B,$FF,$39,$FF,$37,$FF,$36,$FF,$34,$FF
db $33,$FF,$31,$FF,$30,$FF,$2F,$FF,$2D,$FF,$2C,$FF,$2B,$FF,$2A,$FF
db $29,$FF,$28,$FF,$27,$FF,$26,$FF,$25,$FF,$24,$FF,$23,$FF,$22,$FF
db $21,$FF,$02,$20,$FF,$83,$1F,$FF,$1E,$FF,$1D,$FF,$02,$1C,$FF,$82
db $1B,$FF,$1A,$FF,$02,$19,$FF,$01,$18,$FF,$02,$17,$FF,$01,$16,$FF
db $02,$15,$FF,$01,$14,$FF,$02,$13,$FF,$02,$12,$FF,$01,$11,$FF,$02
db $10,$FF,$02,$0F,$FF,$02,$0E,$FF,$02,$0D,$FF,$02,$0C,$FF,$02,$0B
db $FF,$02,$0A,$FF,$03,$09,$FF,$02,$08,$FF,$03,$07,$FF,$03,$06,$FF
db $03,$05,$FF,$03,$04,$FF,$04,$03,$FF,$04,$02,$FF,$06,$01,$FF,$7F
db $00,$FF,$05,$00,$FF,$00
