; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_95.asm

hirom
org $CECA13

!CECA1E_AssetSwirlData95End = SWIRL_DATA_96

; Original terminal data gap ending at $CECA1E
db $01,$6F,$FF,$00,$03,$7E,$81,$6E,$FF,$00,$00
