; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ce/asset_swirl_data_16.asm

hirom
org $CE78DF

!CE7B3C_AssetSwirlData16End = SWIRL_DATA_17

; Original terminal data gap ending at $CE7B3C
db $04,$17,$FF,$00,$FF,$00,$C5,$82,$8F,$FF,$00,$77,$9A,$FF,$00,$71
db $A1,$FF,$00,$6D,$A7,$FF,$00,$6A,$AB,$FF,$00,$67,$AE,$FF,$00,$64
db $B2,$FF,$00,$62,$B4,$FF,$00,$60,$B7,$FF,$00,$5E,$B9,$FF,$00,$5C
db $BC,$FF,$00,$5A,$BE,$FF,$00,$58,$C0,$FF,$00,$57,$C2,$FF,$00,$55
db $C3,$FF,$00,$53,$C5,$FF,$00,$52,$C7,$FF,$00,$50,$C8,$FF,$00,$4F
db $C9,$FF,$00,$4E,$CB,$FF,$00,$4C,$CC,$FF,$00,$4B,$CD,$FF,$00,$4A
db $CE,$FF,$00,$49,$D0,$FF,$00,$47,$D1,$FF,$00,$46,$D3,$FF,$00,$45
db $D4,$FF,$00,$44,$D5,$FF,$00,$43,$D7,$FF,$00,$42,$D8,$FF,$00,$41
db $D9,$FF,$00,$40,$DA,$FF,$00,$3F,$DB,$FF,$00,$3E,$DC,$FF,$00,$3D
db $DD,$FF,$00,$3C,$DE,$FF,$00,$3B,$BE,$C1,$DF,$3B,$BD,$C2,$E0,$3A
db $BC,$C3,$E1,$39,$BB,$C4,$E2,$38,$BA,$C5,$E3,$37,$B9,$C7,$E3,$37
db $B8,$C8,$E4,$36,$B7,$C9,$E5,$35,$B8,$CA,$E6,$35,$B9,$CB,$E6,$34
db $BA,$CC,$E7,$33,$BC,$CD,$E8,$33,$BD,$CE,$E8,$32,$BE,$CF,$E9,$31
db $BF,$D0,$EA,$31,$C0,$D1,$EA,$30,$C1,$D2,$EB,$30,$C2,$D2,$EB,$2F
db $C3,$D3,$EC,$2F,$C4,$D4,$EC,$2E,$C4,$D4,$ED,$2E,$C5,$D5,$ED,$2E
db $C6,$D6,$EE,$2D,$C6,$D6,$EE,$2D,$C7,$D7,$EF,$2D,$C8,$D7,$EF,$2D
db $C8,$D8,$F0,$2C,$C9,$D8,$F0,$2C,$C9,$D9,$F0,$2C,$CA,$D9,$F1,$2C
db $CA,$DA,$F1,$2C,$CB,$DA,$F1,$2B,$CB,$DB,$F2,$02,$2B,$CC,$DB,$F2
db $02,$2B,$CD,$DC,$F3,$84,$2A,$CE,$DC,$F3,$2A,$CE,$DD,$F3,$2A,$CE
db $DD,$F4,$2A,$CF,$DD,$F4,$02,$2A,$CF,$DE,$F4,$02,$2A,$CF,$DE,$F5
db $04,$2A,$D0,$DF,$F5,$01,$2A,$D1,$DF,$F5,$02,$2A,$D1,$DF,$F6,$02
db $2A,$D1,$E0,$F6,$04,$2A,$D2,$E0,$F6,$01,$2A,$D2,$E0,$F7,$04,$2B
db $D2,$E0,$F7,$01,$2C,$D2,$E0,$F7,$03,$2C,$D1,$E0,$F7,$02,$2D,$D1
db $E0,$F7,$01,$2D,$D1,$DF,$F7,$02,$2E,$D0,$DF,$F7,$01,$2F,$D0,$DF
db $F7,$02,$2F,$CF,$DF,$F6,$B4,$30,$CF,$DE,$F6,$30,$CE,$DE,$F6,$31
db $CE,$DE,$F6,$31,$CE,$DE,$F5,$32,$CD,$DD,$F5,$33,$CD,$DD,$F5,$33
db $CC,$DD,$F5,$34,$CC,$DD,$F4,$34,$CB,$DC,$F4,$35,$CB,$DC,$F4,$36
db $CA,$DB,$F3,$36,$C9,$DB,$F3,$37,$C9,$DB,$F3,$38,$C8,$DA,$F2,$39
db $C7,$DA,$F2,$3A,$C7,$D9,$F2,$3A,$C6,$D9,$F1,$3B,$C5,$D8,$F1,$3C
db $C4,$D8,$F0,$3D,$C4,$D7,$F0,$3E,$C3,$D7,$EF,$3F,$C2,$D6,$EF,$40
db $C1,$D5,$EE,$41,$C0,$D5,$EE,$42,$BF,$D4,$ED,$43,$BE,$D4,$ED,$44
db $BD,$D3,$EC,$45,$BC,$D2,$EC,$46,$BB,$D1,$EB,$47,$BA,$D0,$EA,$49
db $B9,$CF,$EA,$4A,$B8,$CE,$E9,$4B,$B7,$CD,$E9,$4C,$B5,$CC,$E8,$4E
db $B4,$CB,$E7,$4F,$B3,$CB,$E7,$51,$B1,$CC,$E6,$52,$B0,$CD,$E5,$54
db $AE,$CF,$E4,$56,$AD,$D0,$E4,$57,$AB,$D1,$E3,$59,$A9,$D2,$E2,$5B
db $A7,$D3,$E1,$5D,$A5,$D4,$E0,$5F,$A3,$D5,$DF,$62,$A1,$D6,$DE,$64
db $9E,$D7,$DE,$67,$9B,$D8,$DD,$6A,$98,$D9,$DC,$6E,$94,$FF,$00,$72
db $90,$FF,$00,$79,$8A,$FF,$00,$26,$FF,$00,$FF,$00,$00
