; EarthBound CE asset SWIRL_DATA_49.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ce-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CE:9481..CE:9509 AssetSwirlData49

; ---------------------------------------------------------------------------
; CE:9509

; AssetSwirlData49End
CE9509_AssetSwirlData49End:
