; EarthBound DA asset bank DA tailpadding.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/da-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - DA:FFEE..DA:10000 AssetBankDAGap1TailPadding

; ---------------------------------------------------------------------------
; DA:10000

; AssetBankDAGap1TailPadding has no terminal label because the range ends at the next bank boundary.
