; EarthBound CE asset BATTLE_SPRITE_76.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ce-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CE:4745..CE:48C8 AssetBattleSprite76

; ---------------------------------------------------------------------------
; CE:48C8

; AssetBattleSprite76End
CE48C8_AssetBattleSprite76End:
