; EarthBound CE asset SWIRL_DATA_75.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ce-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CE:C002..CE:C386 AssetSwirlData75

; ---------------------------------------------------------------------------
; CE:C386

; AssetSwirlData75End
CEC386_AssetSwirlData75End:
