; EarthBound DC asset AUDIO_PACK_79.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/dc-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - DC:F8BF..DC:FF92 AssetAudioPack79

; ---------------------------------------------------------------------------
; DC:FF92

; AssetAudioPack79End
DCFF92_AssetAudioPack79End:
