; EarthBound C3 battle visual table corridor C3:F2B1..C3:F5F9.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_c3_classified_data_to_source_scaffold.py.
; - The byte payloads remain opaque for now, but the labels below preserve
;   C3 source-data-map boundaries for later event/actionscript decoding.
;
; Source units covered:
; - C3:F2B1..C3:F2B5 LevelUpStatGrowthVarianceTable [mixed-data-source-row]
; - C3:F2B5..C3:F3C5 VisualSelectorPoseRowTable [contract-backed-data]

; ---------------------------------------------------------------------------
; C3:F2B1..C3:F2B5
; class: mixed-data-source-row
; source: data/unknown/C3F2B1.asm
; evidence: notes/c3-battle-visual-data-and-file-select-transition-split.md:55
; evidence: C3:F3C5 RunFileSelectVisualTransition

C3F2B5_LevelUpStatGrowthVarianceTableEnd:
    ; data bytes: C3:F2B1..C3:F2B5
    db $08,$04,$04,$04

; ---------------------------------------------------------------------------
; C3:F2B5..C3:F3C5
; class: contract-backed-data
; source: data-contract
; evidence: notes/c3-battle-visual-data-and-file-select-transition-split.md:56

C3F3C5_VisualSelectorPoseRowTableEnd:
    ; data bytes: C3:F2B5..C3:F3C5
    db $01,$00,$08,$00,$11,$00,$15,$00,$1B,$00,$22,$00,$05,$00,$FF,$FF
    db $02,$00,$09,$00,$12,$00,$16,$00,$1C,$00,$22,$00,$19,$00,$FF,$FF
    db $03,$00,$0A,$00,$13,$00,$17,$00,$1D,$00,$22,$00,$19,$00,$FF,$FF
    db $04,$00,$0B,$00,$14,$00,$18,$00,$1E,$00,$22,$00,$19,$00,$FF,$FF
    db $2C,$00,$2C,$00,$2C,$00,$2C,$00,$2C,$00,$2C,$00,$2C,$00,$FF,$FF
    db $2D,$00,$2D,$00,$2D,$00,$2D,$00,$2D,$00,$2D,$00,$2D,$00,$FF,$FF
    db $28,$00,$28,$00,$2A,$00,$2B,$00,$28,$00,$28,$00,$28,$00,$FF,$FF
    db $B6,$00,$B6,$00,$B6,$00,$B6,$00,$B6,$00,$B6,$00,$B6,$00,$FF,$FF
    db $2E,$00,$2E,$00,$2E,$00,$2F,$00,$2E,$00,$2E,$00,$2E,$00,$FF,$FF
    db $29,$00,$29,$00,$29,$00,$29,$00,$29,$00,$29,$00,$29,$00,$FF,$FF
    db $27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$FF,$FF
    db $27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$FF,$FF
    db $27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$FF,$FF
    db $27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$FF,$FF
    db $27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$27,$00,$FF,$FF
    db $33,$00,$33,$00,$33,$00,$33,$00,$23,$00,$23,$00,$33,$00,$FF,$FF
    db $33,$00,$33,$00,$33,$00,$33,$00,$23,$00,$23,$00,$33,$00,$FF,$FF
