; EarthBound C2 battle letterbox HDMA table builder.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:D0AC..C2:D121 BuildBattleLetterboxHdmaTable
;
; Runtime contract:
; - Builds the battle letterbox HDMA table at `$ADB8` from top/end values in
;   `$ADB2/$ADB4` and visible/nonvisible screen words in `$ADAE/$ADB0`.
; - Emits nonvisible top segment, one or more visible segments capped at
;   `0x7F` scanlines, a one-line nonvisible bottom segment, and a terminator.

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C2:D0AC

C2D0AC_BuildBattleLetterboxHdmaTable:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    ldx.w #$ADB8
    sep #$20
    ; Top nonvisible segment line count.
    lda $ADB2
    sta $0000,X
    inx
    rep #$20
    lda $ADB0
    sta $0000,X
    inx
    inx
    lda $ADB4
    sec
    sbc $ADB2
    sta $0E
    bra C2D0EF_BuildBattleLetterboxHdmaTable_LD0EF
C2D0D5_BuildBattleLetterboxHdmaTable_LD0D5:
    sep #$20
    ; SNES HDMA line-count chunks are byte-sized, so large windows split here.
    lda.b #$7F
    sta $0000,X
    inx
    rep #$20
    lda $ADAE
    sta $0000,X
    inx
    inx
    lda $0E
    sec
    sbc.w #$007F
    sta $0E
C2D0EF_BuildBattleLetterboxHdmaTable_LD0EF:
    cmp.w #$0080
    bcs C2D0D5_BuildBattleLetterboxHdmaTable_LD0D5
    sep #$20
    sta $0000,X
    inx
    rep #$20
    lda $ADAE
    sta $0000,X
    inx
    inx
    sep #$20
    lda.b #$01
    sta $0000,X
    inx
    rep #$20
    lda $ADB0
    sta $0000,X
    inx
    inx
    sep #$20
    lda.b #$00
    sta $0000,X
    rep #$20
    pld
    rtl
