;@Habitat:オネット／フィールド／街の至る所		
;@Person:街の人Ｃ
;@Figure:ボロ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_D
MSG_ONET_D;
◆Ｔｈｅ　ｐｏｉｎｔ　ｏｖｅｒｌｏｏｋｉｎｇ　ｔｈｅ　ｓｅａ　ｈａｓ　ｂｅａｕｔｉｆｕｌ　ｓｃｅｎｅｒｙ．@WI(15)　　Ｉｔ’ｓ　ｏｖｅｒ　ｔｈａｔａｗａｙ．
◆Ｓｕｃｈ　ａ　ｂｅａｕｔｉｆｕｌ　ｐｌａｃｅ　ｇｅｔｓ　ｍｅ　ａｌｌ　ｃｈｏｋｅｄ　ｕｐ．
;jpn:◆このさきの　みさきは↓
;jpn:　けしきが　よくってさぁ。@KEY()↓
;jpn:◆おれも　あんなところで↓
;jpn:　ふられてみたいよ。
@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:街の人Ｄ
;@Figure:サラリーマンＢ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_B
MSG_ONET_B;＃
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_B_END)
◆Ｙｏｕ　ｌｏｏｋ　ｓｏ　ｈｅｌｐｌｅｓｓ．@WI(15)　　Ａｒｅ　ｙｏｕ　ｏｋａｙ？
;jpn:　たよりないかお　してるなあ。↓
;jpn:　だいじょうぶかな。
@KEYNP()
』
_ONET_B_END;＆
◆Ｙｏｕ　ｕｓｅｄ　ｔｏ　ｌｏｏｋ　ｍｕｃｈ　ｍｏｒｅ　ｈｅｌｐｌｅｓｓ．
;jpn:◆おまえ　むかしは　もっと↓
;jpn:　たよりないかお　してたよな。
@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:街の人Ｅ
;@Figure:少年Ａ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_A
MSG_ONET_A;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_A_END)
@CHKFGOTO(FLG_POWR_GIAN,_ONET_A_LATER)
◆Ｒｕｍｏｒ　ｈａｓ　ｉｔ　ｔｈａｔ　ｔｈｅ　Ｓｈａｒｋｓ’　ｂｏｓｓ　ｉｓ　ｈａｎｇｉｎｇ　ｏｕｔ　ｎｅａｒ　ｔｈｅ　Ｇｉａｎｔ　Ｓｔｅｐ．
;jpn:◆シャークだんの　ボスが↓
;jpn:　ジャイアントステップの　あたりを↓
;jpn:　よく　うろついてるらしいんだ。
@KEYNP()
』
_ONET_A_LATER;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　Ｆｒａｎｋ’ｓ　ａ　ｒｅｇｕｌａｒ　ｃｒａｚｙ　ａｎｄ　ｗｉｌｄ－ｔｙｐｅ　ｇｕｙ．
;jpn:◆フランクさんって↓
;jpn:　ただの　らんぼうもの↓
;jpn:　‥‥じゃ　ないんだよな。
@KEYNP()
』
_ONET_A_END;＆
◆Ｆｒａｎｋ’ｓ　ｎｏｔ　ｉｎ　ｔｈｅ　ａｒｃａｄｅ．@KEY()↓
◆Ｈｅ’ｓ　ｉｎ　ｔｈｅ　ｈａｍｂｕｒｇｅｒ　ｓｈｏｐ　ｓｍｉｌｉｎｇ　ａｗａｙ．．．
@KEYNP()
;jpn:◆フランクさんは↓
;jpn:　ゲームセンターには　いないよ。@KEY()↓
;jpn:◆ハンバーガーショップで↓
;jpn:　スマイルしてるんだ。@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:街の人Ｆ
;@Figure:おばさんＡ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_E
MSG_ONET_E;
;@Q_HAVE( PC_ALL, GDS_TOOL_BICYCLE )
;@TRUE_GOTO( _ONET_E_BICYCLE )		;ＣＥＳデモ用自転車説明分岐
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_E_END)
@CHKFGOTO(FLG_TLPT_TWSN,_ONET_E_LATER)
◆Ｔｈｉｓ　ｔｏｗｎ　ｉｓ　ｏｕｔ　ｏｆ　ｃｏｎｔｒｏｌ．@KEY()↓
◆Ｔｈｅ　ｗｉｌｄ　ｂｏｙｓ　ａｒｅ　ｈａｎｇｉｎｇ　ｏｕｔ　ｉｎ　ｔｈｅ　ｔｏｗｎ@KEY()↓
◆ａｎｄ　ｔｈｅ　ｃｏｐｓ　ｈａｖｅ　ｒｅａｌｌｙ　ｂｅｅｎ　ｃｒａｃｋｉｎｇ　ｄｏｗｎ　ｏｎ　ｅｖｅｒｙｏｎｅ．@KEY()↓
◆Ｉ’ｍ　ｃｏｎｓｉｄｅｒｉｎｇ　ｍｏｖｉｎｇ　ｔｏ　Ｔｗｏｓｏｎ，@WI(15)　ａ　ｔｏｗｎ　ｉｎ　ｔｈｅ　ｓｏｕｔｈ．
;jpn:◆まーったく　このまちは↓
;jpn:　けいさつが　いばってるし↓
;jpn:　ふりょうどもが　のさばってるし@KEY()↓
;jpn:◆みなみの　ツーソンのまちに↓
;jpn:　ひっこそうかと　おもってるのよ。
@KEYNP()
』
_ONET_E_LATER;
◆Ｔｈｅ　ｗｉｌｄ　ｐｕｎｋｓ　ｈａｖｅ　ｃａｌｍｅｄ　ｄｏｗｎ，@WI(15)　ｂｕｔ　Ｉ　ｓｔｉｌｌ　ｄｏｎ’ｔ　ｆｅｅｌ　ｖｅｒｙ　ｓａｆｅ．
;jpn:◆ふりょうどもは↓
;jpn:　おとなしくなったみたいだけど↓
;jpn:　まだまだ　きけんをかんじるわ。
@KEYNP()
』
_ONET_E_END;＆
◆Ｉｎ　ｔｈｉｓ　ｔｏｗｎ，　ｙｏｕ’ｒｅ　ｆａｍｏｕｓ．@KEY()↓
◆Ｉ　ｈｅａｒｄ　ｙｏｕ　ａｓｋｅｄ　ａ　Ｔｗｏｓｏｎ　ｇｉｒｌ　ｏｕｔ　ｏｎ　ａ　ｄａｔｅ．@WI(20)　　Ｗｈａｔ’ｓ　ｈｅｒ　ｎａｍｅ？@KEY()↓
◆Ｙｏｕ　ｋｎｏｗ，　ｙｏｕ　ｈａｖｅ　ｏｎｅ　ｏｆ　ｔｈｏｓｅ　ｂａｂｙ　ｆａｃｅｓ　ｔｈａｔ　ｒｅａｌｌｙ　ａｔｔｒａｃｔｓ　ｔｈｅ　ｇｉｒｌｓ，@KEY()↓
◆ｙｏｕ　ｌｕｃｋｙ　ｂｏｙ．

;jpn:◆あなた　このまちじゃ↓
;jpn:　ちょっと　ゆうめいよ。@KEY()↓
;jpn:◆ツーソンの　なんとかちゃんって↓
;jpn:　おんなのコを↓
;jpn:　ナンパした　らしいじゃないの。@KEY()↓
;jpn:◆コドモっぽいかおして↓
;jpn:　やるときゃやるんだから。@WI(20)↓
;jpn:　まーったく。
@KEYNP()
』
;_ONET_E_BICYCLE;
;◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａ　ｂｉｃｙｃｌｅ　ｉｎ　ｙｏｕｒ　ｂａｃｋ－ｐａｋ？@KEY()↓
;◆Ｆｉｒｓｔ，@WI(15)　ｓｅｌｅｃｔ　”Ｇｏｏｄｓ，”@WI(20)　ｔｈｅｎ　”Ｂｉｃｙｃｌｅ”　ａｎｄ　ｙｏｕ　ｗｉｌｌ　ｒｉｄｅ　ｔｈｅ　ｂｉｋｅ．@KEY()↓
;◆Ｄｉｄ　ｙｏｕ　ｋｎｏｗ　ｔｈａｔ？@KEY()↓
;◆Ｙｏｕ　ｃａｎ　ａｌｓｏ　ｒｉｎｇ　ｔｈｅ　ｂｅｌｌ　ｗｉｔｈ　ｔｈｅ　Ｒ　Ｂｕｔｔｏｎ！@WI(20)　　Ｗｏｗ！@WI(10)　　Ｃｏｏｌ！！@KEYNP()
;』
;;jpn:◆リュックのなかに　じてんしゃを
;;jpn:　もってるんだろ？
;;jpn:◆「グッズ」「じてんしゃ」で
;;jpn:　のれるってこと　しってたかい？
;;jpn:◆Ｒボタンで　ベルも
;;jpn:　ならせるんだよね。いいなぁ。


;@Habitat:オネット／フィールド／街の至る所
;@Person:蘇生解説お婆さん
;@Figure:おばあさん
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_OLDWOMAN
MSG_ONET_OLDWOMAN;
◆Ｉｆ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｆｒｉｅｎｄｓ　ｂｅｃｏｍｅｓ　ｕｎｃｏｎｓｃｉｏｕｓ，@KEY()↓
◆ｙｏｕ　ｓｈｏｕｌｄ　ｖｉｓｉｔ　ｔｈｅｍ　ａｔ　ｔｈｅ　ｈｏｓｐｉｔａｌ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｃｈｅｃｋ　ｗｉｔｈ　ｔｈｅ　ｎｕｒｓｅ　ｒｅｃｅｐｔｉｏｎｉｓｔ，　ａｎｄ　ｓｈｅ　ｗｉｌｌ　ｒｅｌｅａｓｅ　ｙｏｕｒ　ｆｒｉｅｎｄ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｎｉｃｅ　ｔｈｉｎｇ　ｔｏ　ｒｅｍｅｍｂｅｒ，@WI(15)　ｂｕｔ　ｉｔ’ｓ　ａｌｌ　ｒｉｇｈｔ　ｉｆ　ｙｏｕ　ｆｏｒｇｅｔ．
;jpn:◆きずつき　たおれたひととは↓
;jpn:　びょういんで　あえる。@KEY()↓
;jpn:◆こういうことは↓
;jpn:　おぼえておくと　いいよ。@KEY()↓
;jpn:◆わすれても　かまわないけど。
@KEYNP()
』


;@Habitat:オネット／フィールド／街の至る所
;@Person:街の犬
;@Figure:チリドッグ
;@AppearanceKey:0
;@ActionScript:＊広範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_STRAYDOG
MSG_ONET_STRAYDOG;
@CHKFGOTO(FLG_TLPT_THRK,_ONET_STRAYDOG_LATER)
◆Ｂｏｗ－ｗｏｗ！@WI(20)　　（Ｄｏｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｙｏｕ’ｌｌ　ｂｅ　ｎｅｅｄｉｎｇ　ａ　ｗｅａｐｏｎ？@KEY()↓
◆Ｄｉｄ　ｙｏｕ　ｋｎｏｗ　ｔｈｅ　ｄｒｕｇ　ｓｔｏｒｅ　ｓｅｌｌｓ　ｔｈｉｎｇｓ　ｙｏｕ　ｃａｎ　ｕｓｅ？@KEY()↓
◆．．．Ｉ　ｋｎｅｗ　ａｂｏｕｔ　ｉｔ．）

;jpn:◆バウワウ！@WI(30)↓
;jpn:　（たたかいの　ぶきがなくて↓
;jpn:　こまってたりはしないか？@KEY()↓
;jpn:◆ドラッグストアに↓
;jpn:　やくにたちそうなものが↓
;jpn:　うってるのを　しってるか？@KEY()↓
;jpn:◆‥‥おれは　しってる）
@KEYNP()
』
_ONET_STRAYDOG_LATER;
◆Ｂｏｗ－Ｗｏｗ！@KEYNP()
;jpn:◆バウワウ！@KEYNP()
』


;◆Ｗｈｏｏｐｓ！　
;	（Ｔｈｉｓ　ｄｏｇ　ｃａｎ’ｔ　ｔａｌｋ．）　
;◆Ｙｏｕ　ｓｈｏｕｌｄｎ’ｔ　ｈａｖｅ　ｌｏｎｇ　ｃｏｖｅｒｓａｔｉｏｎｓ
;　　ｗｉｔｈ　ｄｏｇｓ．　
;	Ｉｔ　ｗｉｌｌ　ｍａｋｅ　ｙｏｕ　ｌｏｏｋ　ｓｉｌｌｙ．　
;◆Ｄｏ　ｙｏｕ　ｔｈｉｎｋ　Ｉ　ａｍ　ｊｕｓｔ　ａ　ｔｉｒｅｄ，　ｗｉｌｄ　ｄｏｇ？　
;	<Ｙｅｓ>　<Ｎｏ>　
;◆ハズレ！@WI(20)↓
;　（このイヌは　しゃべらない）@KEYNP()
;』
;◆（イヌと
;　ながばなしするのは
;　やめなさい。
;◆いみないから）
;
;◆きっと　おまえは　おれのことを↓
;　くたびれた　ただの　のらイヌだと↓
;　おもっているだろう？@KEY()↓
;　　<はい>　　<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_ONET_STRAYDOG_YES,_ONET_STRAYDOG_NO)
;』
;
;_ONET_STRAYDOG_NO;@MaltaAppended
;◆Ｈｅｈ　ｈｅｈ．．．　
;◆Ｔｈａｔ’ｓ　ｉｔ．　
;◆ふふ‥‥。@KEY()↓
;
;_ONET_STRAYDOG_YES;@MaltaAppended
;◆ま　そんなところだ。@KEY()
;』


;@Habitat:オネット／フィールド／岬
;@Person:ドア前の不動産屋
;@Figure:おじさんＡ
;@AppearanceKey:FLG_GOT_CAPEESTATE/off
;@ActionScript:＊演出コンテ#1.8.5
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_CAPEESTATE
MSG_ONET_CAPEESTATE;@MaltaAdapted
@CHKFGOTO(FLG_GOT_CAPEESTATE,_ONET_CAPEESTATE_BOUGHT)
◆Ｄｏｅｓｎ’ｔ　ｔｈｉｓ　ｈｏｕｓｅ　ｌｏｏｋ　ｇｏｏｄ？@WI(20)　　Ｙｏｕ　ｃａｎ　ｂｕｙ　ｉｔ　ｆｏｒ　ｏｎｌｙ　＄７５００！@KEY()↓
◆Ｉｔ　ｈａｓ　ａｎ　ｏｃｅａｎ　ｖｉｅｗ，@WI(15)　ａｎｄ　ｔｈｅ　ｓｕｎｓｅｔｓ　ａｒｅ　ｂｅａｕｔｉｆｕｌ．@KEY()↓
◆Ｆｏｌｋｓ　ｓｈｏｕｌｄ　ｈａｖｅ　ａ　ｐｌａｃｅ　ｏｆ　ｔｈｅｉｒ　ｏｗｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？↓
<Ｙｅｓ>　<Ｎｏ>

;jpn:◆ちょっと　いいでしょ。↓
;jpn:　このいえ。↓
;jpn:　うりますよ。@KEY()↓
;jpn:◆たった　７５００ドル！@KEY()↓
;jpn:◆うみはみえるし　ゆうひはキレイ。@WI(15)↓
;jpn:　おとこのしろは　ひつようですよ。@KEY()
;jpn:◆かってみませんか？↓
@WINR_MONEY()
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_CAPEESTATE_YES,_ONET_CAPEESTATE_NO)

_ONET_CAPEESTATE_NO;@MaltaAdapted
◆Ｙｏｕ　ｃａｎ’ｔ　ａｆｆｏｒｄ　＄７５００？@WI(20)　　Ｉｔ　ｗａｓ　ａ　ｗａｓｔｅ　ｏｆ　ｔｉｍｅ　ｔａｌｋｉｎｇ　ｔｏ　ｙｏｕ．
;jpn:◆たった　７５００ドルをはらえない@WI(15)↓
;jpn:　そんなあなたに　はなした↓
;jpn:　わたしが　バカだった。
@KEYNP()
』

_ONET_CAPEESTATE_YES;@MaltaAdapted
@Q_MONEY(7500)
@TRUE_GOTO(_ONET_CAPEESTATE_NO)
@SE(SE_se76_my_give)
@MONEYOUT(7500)
@WINR_MONEY()
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓
◆Ｉｔ’ｓ　ａｌｌ　ｙｏｕｒｓ　ｎｏｗ．@WI(20)　　Ｔａｋｅ　ｓｏｍｅ　ｔｉｍｅ　ａｎｄ　ｒｅｌａｘ．
@KEYNP()
;jpn:◆ありがとう　ございます。@KEY()↓
;jpn:◆いまからここは↓
;jpn:　あなたのものです。@WI(15)↓
;jpn:　ごゆっくり　どうぞ。@KEYNP()
@SETF(FLG_GOT_CAPEESTATE)
@SETF(FLG_ONET_ESTATE_DOOR_OPEN)	;ドア開く
@HIDE_CHAR(PRSN_ONET_FIELD_P,OBJFX_HIDE_NONE)
;逃げるアニメーション
@MOVE_CHAR(PRSN_ONET_FIELD_Q,ANIM_PEOPLEWALK1,OBJFX_SHOW_NONE)
』

_ONET_CAPEESTATE_BOUGHT
◆Ｈｅｙ！@WI(15)　　Ｙｏｕ’ｖｅ　ｇｏｔ　ｙｏｕｒ　ｏｗｎ　ｐｌａｃｅ　ｎｏｗ！
;jpn:◆おきゃくさん↓
;jpn:　おとこのしろは　ひつようですよ。
@KEYNP()
』


;@Habitat:オネット／フィールド／岬
;@Person:にげる不動産屋
;@Figure:おじさんＡ
;@AppearanceKey:FLG_GOT_CAPEESTATE/on
;@ActionScript:＊演出コンテ#1.8.5
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_REALTOR
MSG_ONET_REALTOR;@MaltaAdapted
@CHKFGOTO(FLG_STEP_CAPEESTATE,_ONET_REALTOR2)
◆Ｈｅｙ！@WI(15)　　Ｙｏｕ’ｖｅ　ｇｏｔ　ｙｏｕｒ　ｏｗｎ　ｐｌａｃｅ　ｎｏｗ！
;jpn:◆おきゃくさん↓
;jpn:　おとこのしろは　ひつようですよ。
@KEYNP()
』

_ONET_REALTOR2;
◆Ａ　ｈｏｕｓｅ　ｉｎ　ｓｕｃｈ　ｇｏｏｄ　ｃｏｎｄｉｔｉｏｎ　ｃａｎ’ｔ　ｂｅ　ｔｈａｔ　ｃｈｅａｐ．
;jpn:◆ちゃんとした　いえなら↓
;jpn:　そんなにやすく　うれるわけが↓
;jpn:　ないでしょ。
@KEYNP()
』


;@Habitat:オネット／フィールド／岬
;@Person:トランペッター
;@Figure:トランペッター
;@AppearanceKey:0
;@ActionScript:＊左向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_TRUMPETER
MSG_ONET_TRUMPETER;
◆Ｉ　ｍｕｓｔ　ｂｅ　ｔｈｅ　ｈａｐｐｉｅｓｔ　ｍａｎ　ｉｎ　ｔｈｅ　ｗｏｒｌｄ．@KEY()↓
◆Ｉ　ｃａｎ　ｐｒａｃｔｉｃｅ　ｍｙ　ｔｒｕｍｐｅｔ　ｉｎ　ｔｈｉｓ　ｓｃｅｎｉｃ　ｓｐｏｔ．@KEY()↓
◆Ｉ’ｌｌ　ｓｅｎｄ　ｍｙ　ｈａｕｎｔｉｎｇ　ｍｅｌｏｄｙ　ｔｈｒｏｕｇｈｏｕｔ　ｔｈｅ　ｔｏｗｎ！
;jpn:◆こんな　みはらしのいい　ばしょで↓
;jpn:　トランペットの　れんしゅうが↓
;jpn:　できるなんて@KEY()↓
;jpn:◆おれは　しあわせものだ。@KEY()↓
;jpn:◆まちじゅうに　ひびけ↓
;jpn:　おれのうつくしい　メロディー！
@KEY()
@SE(SE_se16_tp_man)
』


;@Habitat:オネット／フィールド／街をうろついている
;@Person:シャーク団Ａ
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_A
MSG_ONET_SHARK_A;
@CHKFGOTO(FLG_ONET_SHARK_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_A2)
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｔａｒｔ　ａ　ｆｉｇｈｔ，@WI(15)　ｏｒ　ｗｈａｔ？
;jpn:◆おまえ　シャークだんに↓
;jpn:　ケンカうろうと　してるな！
@KEY()
@GOSUB(MSG_BATTLE_SHARK_A)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_ONET_FIELD_S,ANIM_BLINK_SUICIDE)
@SETF(FLG_ONET_SHARK_A_DISAPPEAR)
』

_ONET_SHARK_A2;
◆Ｉ　ｗｏｎ’ｔ　ｆｉｇｈｔ　ｙｏｕ　ｓｉｎｃｅ　ｙｏｕ’ｒｅ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　ｍｅ．
;jpn:◆もう　ケンカは　しねぇよ。↓
;jpn:　おまえ　つよいんだもん。
@KEYNP()
』


;@Habitat:オネット／フィールド／街をうろついている
;@Person:シャーク団Ｂ
;@Figure:シャーク団
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_SHARK_B
MSG_ONET_SHARK_B;
@CHKFGOTO(FLG_ONET_SHARK_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_SHARK_B2)
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｍｅｅｔ　Ｆｒａｎｋ？@WI(15)　　Ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　Ｆｒａｎｋ　ｔｏ　ｂｅａｔ　ｙｏｕ　ｕｐ，@WI(15)　ｄｏ　ｙｏｕ？
;jpn:◆フランクさんに　あいたいのか。@WI(15)↓
;jpn:　フランクさんに　たたきのめして↓
;jpn:　もらいたいんだな。
@KEY()
@GOSUB(MSG_BATTLE_SHARK_B)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_ONET_FIELD_T,ANIM_BLINK_SUICIDE)
@SETF(FLG_ONET_SHARK_B_DISAPPEAR)
』

_ONET_SHARK_B2;
◆Ｙｏｕ　ｌｏｏｋ　ｐｒｅｔｔｙ　ｈｅａｌｔｈｙ．
@KEYNP()
;jpn:◆やぁ　げんきそうだね。@KEYNP()
』


;@Habitat:オネット／フィールド／道路封鎖前
;@Person:封鎖警官Ａ
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:＊演出コンテ#1.11
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_GATE_A
MSG_ONET_GATE_B;
@CHKFGOTO(FLG_ONET_GATEOPEN,_ONET_GATE_B2)
◆Ｄｏｎ’ｔ　ｔａｌｋ　ｔｏ　ｍｅ！@WI(15)　　Ｉ’ｍ　ｏｎ　ｄｕｔｙ．@KEY()↓
◆Ｕｎｔｉｌ　Ｉ　ｈａｖｅ　Ｃｈｉｅｆ　Ｓｔｒｏｎｇ’ｓ　ａｐｐｒｏｖａｌ，@WI(15)　Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｇｏ！
;jpn:◆はなしかけるな！↓
;jpn:　きんむちゅうだ。@KEY()↓
;jpn:◆ストロングしょちょうの↓
;jpn:　きょかがでるまで↓
;jpn:　ここを　とおすわけには　いかん！
@KEYNP()
』

_ONET_GATE_B2;
◆Ｙｏｕ’ｒｅ　ｄｏｉｎｇ　ｗｅｌｌ．@WI(20)　　Ｋｅｅｐ　ｉｔ　ｕｐ．@KEY()↓
◆Ｔｈｅ　”Ｔｏｗｎ　Ｍａｐ”　ｃａｎ　ｂｅ　ｃｈｅｃｋｅｄ　ｏｕｔ　ａｔ　ｔｈｅ　ｌｉｂｒａｒｙ．@KEY()↓
◆Ｙｏｕ　ｃａｎ　ａｌｓｏ　ｕｓｅ　ｔｈｅ　ｍａｐ　ｉｎ　Ｔｗｏｓｏｎ．@WI(20)　　Ｉｔ’ｓ　ｒｅａｌｌｙ　ｕｓｅｆｕｌ．
;jpn:◆がんばるんだぞ。@KEY()↓
;jpn:◆としょかんで　かりられる↓
;jpn:　「まちのちず」は　ツーソンでも↓
;jpn:　もちろんつかえるから@KEY()↓
;jpn:◆やくにたてるといいぞ。
@KEYNP()
』


;@Habitat:オネット／フィールド／道路封鎖前
;@Person:封鎖警官Ｂ
;@Figure:警官
;@AppearanceKey:0
;@ActionScript:＊演出コンテ#1.11
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_GATE_B
MSG_ONET_GATE_A;
@CHKFGOTO(FLG_ONET_GATEOPEN,_ONET_GATE_A2)
◆Ｔｈｅ　ｒｏａｄ　ｔｏ　Ｔｗｏｓｏｎ　ｉｓ　ｃｌｏｓｅｄ．@KEY()↓
◆Ｙｏｕ　ｃａｎ’ｔ　ｗａｌｋ　ｔｈｒｏｕｇｈ　ａ　ｒｏａｄ　ｂｌｏｃｋ，@WI(15)　ｅｉｔｈｅｒ！@KEY()↓
◆Ｏｎｅｔｔ　ｉｓ　ｆａｍｏｕｓ　ｆｏｒ　ｒｏａｄｂｌｏｃｋｓ！
;jpn:◆ツーソンへの　みちは@WI(15)↓
;jpn:　オネットめいぶつの↓
;jpn:　どうろふうさちゅうだ！@KEY()↓
;jpn:◆ぜったいに　とおれないんだ！
@KEYNP()
』

_ONET_GATE_A2;
◆Ｈｅｙ，@WI(15)　ａｒｅｎ’ｔ　ｙｏｕ　@DSP_NAME(PC_NESS)？@KEY()↓
◆Ｗｅｌｌ，@WI(15)　Ｉ　ｇｏｔ　ｔｈｅ　ｏｋａｙ　ｆｒｏｍ　Ｃｈｉｅｆ　Ｓｔｒｏｎｇ　ｔｏ　ｌｅｔ　ｙｏｕ　ｔｈｒｏｕｇｈ．@KEY()↓
◆Ｔａｋｅ　ｃａｒｅ　ｏｆ　ｙｏｕｒｓｅｌｆ．
;jpn:◆あ@WI(15)　ストロングしょちょうから↓
;jpn:　れんらくを　うけております。@KEY()↓
;jpn:◆‥‥@DSP_STS(STS_PC_NAME_NES)さん　でしたね？@WI(20)↓
;jpn:　おきをつけて　いってらっしゃい。
@KEYNP()
』


;@Habitat:オネット／フィールド／ゲームセンター裏
;@Person:フランク
;@Figure:フランク
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_FRANK
MSG_ONET_FRANK;
@CHKFGOTO(FLG_TEMP_1,_ONET_FRANK2_NO)
@CHKFGOTO(FLG_WIN_FRANK,_ONET_FRANK2)
@CHKFGOTO(FLG_WIN_FRANK_ONLY,_ONET_FRANK_TRYAGAIN)
◆．．．@KEY()↓
◆．．．Ｉ’ｍ　Ｆｒａｎｋ．@WI(30)　　Ｙｏｕ　ａｒｅ？@KEY()↓
◆@WI(30)Ｃ’ｍｏｎ，@WI(15)　ｃａｎ’ｔ　ｙｏｕ　ａｔ　ｌｅａｓｔ　ｓａｙ　ｙｏｕｒ　ｎａｍｅ？
;jpn:◆‥‥‥@KEY()↓
;jpn:◆‥‥‥↓
;jpn:　フランクだ。@WI(15)↓
;jpn:　おまえは？@KEY()↓
;jpn:◆じぶんのなまえくらい　なのれよ！@WI(15)↓
;jpn:　ふざけるなーっ！
@KEY()
@GOSUB(MSG_BATTLE_FRANK)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@BGMSTOP( 0 )
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@OPEN(1)

MSG_ONET_FRANK_WIN;
◆”Ｆａｉｌ－ｐｒｏｏｆ”　Ｆｒａｎｋ　ｃａｎ’ｔ　ｂｅ　ｂｅａｔｅｎ．@KEY()↓
◆Ｐｕｆｆ，@WI(10)　ｐｕｆｆ，@WI(10)　ｐｕｆｆ↓
　　Ａｎｄ　ｔｈｉｓ　ｉｓ@WI(15)　”Ｆｒａｎｋｙｓｔｅｉｎ　ｔｈｅ　２ｎｄ．”
;jpn:◆むてきのフランクが↓
;jpn:　まけるわけには　いかねぇんだ。@WI(15)↓
;jpn:　ハァ@WI(10)　ハァ@WI(10)　ハァ@KEY()↓
;jpn:◆「フランキースタイン２ごう」だ！
@KEY()
@SETF(FLG_WIN_FRANK_ONLY)
@GOSUB(MSG_BATTLE_STEIN2)
@TRUE_GOTO(MSG_BATTLE_LOSE)
;２号さん消滅
@REMOVE_CHAR( PRSN_ONET_FIELD_4J, ANIM_BLINK_SUICIDE )
@WI( 30 )	;消滅待ち
@SETF( FLG_WIN_FRANK )	;２度と出さないぜ
@OPEN(1)

MSG_ONET_STEIN2_WIN;
←
◆．．．Ｔｈｉｓ　ｉｓ　ｍｙ　ｆｉｒｓｔ　ｄｅｆｅａｔ．@KEY()↓
◆”Ｆａｉｌ－ｐｒｏｏｆ”　Ｆｒａｎｋ　ｉｓ　ｎｏｗ　ｊｕｓｔ　”ｆａｉｌｕｒｅ”　Ｆｒａｎｋ．@KEY()↓
◆Ｉ　ｋｎｏｗ　ｙｏｕ’ｖｅ　ｂｅｅｎ　ａｓｋｉｎｇ　ａｒｏｕｎｄ，@WI(15)　ｓｏ　Ｉ’ｌｌ　ｔｅｌｌ　ｙｏｕ　ａｂｏｕｔ　ＧＩａｎｔ　Ｓｔｅｐ．@KEY()↓
◆Ｉｔ．．．↓
　　ｓｅｅｍｓ．．．↓
　　ｔｏ　ｂｅ　ｑｕｉｔｅ　ａ　ｐｏｗｅｒｆｕｌ　ｓｐｏｔ．@KEY()↓
◆Ｓｏｍｅ　ｋｉｎｄ　ｏｆ　ｓｐｅｃｉａｌ　ｐｏｗｅｒ　ｉｓ　ｓｔｏｒｅｄ　ｔｈｅｒｅ@KEY()↓
◆ｔｈａｔ　ａｌｌｏｗｓ　ｃｅｒｔａｉｎ　ｐｅｏｐｌｅ　ｔｏ　ｐｅｒｆｏｒｍ　ｗｏｎｄｒｏｕｓ　ｆｅａｔｓ．@KEY()↓
◆Ｈｏｗｅｖｅｒ．．．ａ　ｍｏｎｓｔｅｒ　ｓｕｃｋｅｄ　ｕｐ　ａｌｌ　ｔｈｅ　ｅｎｅｒｇｙ　ａｔ　ｔｈａｔ　ｓｐｏｔ．@KEY()↓
◆Ｉｔ’ｓ　ｄｉｆｆｉｃｕｌｔ　ｔｏ　ｇｅｔ　ｔｏ　Ｇｉａｎｔ　Ｓｔｅｐ．@WI(20)　　Ｔｈａｔ’ｓ　ａｌｌ　Ｉ　ｋｎｏｗ．．．@KEY()↓
◆Ｉ　ｓｕｇｇｅｓｔ　ｙｏｕ　ｃｏｌｌｅｃｔ　ｍｏｒｅ　ｉｎｆｏｒｍａｔｉｏｎ　ｏｎ　ｙｏｕｒ　ｏｗｎ．@KEY()↓
◆Ｔｈｅ　ｅｎｔｒａｎｃｅ　ｔｏ　ｔｈｅ　ｐａｔｈ　ｌｅａｄｉｎｇ　ｔｏ　Ｇｉａｎｔ　Ｓｔｅｐ　ｉｓ@KEY()↓
◆ｂｅｈｉｎｄ　ｔｈｅ　ｔｏｕｒｉｎｇ　ｅｎｔｅｒｔａｉｎｅｒｓ’　ｓｈａｃｋ．@KEY()↓
◆Ｐｉｒｋｌｅ，@WI(15)　ｔｈｅ　Ｍａｙｏｒ　ｏｆ　Ｏｎｅｔｔ，@WI(15)　ｈａｓ　ａ　ｋｅｙ　ｔｏ　ｔｈｅ　ｓｈａｃｋ．@KEY()↓
◆@DSP_NAME(PC_NESS)，@WI(15)　ｙｏｕ’ｖｅ　ｂｅｃｏｍｅ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　Ｉ！@WI(20)　　Ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ　ｉｓ　ｊｕｓｔ　ｂｅｇｉｎｎｉｎｇ．．．
;jpn:◆‥‥はじめて　まけた。@WI(20)↓
;jpn:　むてきのフランクも↓
;jpn:　ただのフランクに　なっちまった。@KEY()↓
;jpn:◆おまえの　しりたがっている↓
;jpn:　ジャイアントステップの　ひみつを↓
;jpn:　おしえてやろう。@KEY()↓
;jpn:◆あそこは‥‥@WI(15)↓
;jpn:　どうやら‥‥@WI(15)あるしゅの↓
;jpn:　パワースポットらしい。@KEY()↓
;jpn:◆とくていの　にんげんに↓
;jpn:　なにかを　もたらすような↓
;jpn:　エナジーが　あるんだ。@KEY()↓
;jpn:◆‥‥ただ　あそこには@KEY()↓
;jpn:◆パワースポットのエナジーを↓
;jpn:　すいとった　バケモノが↓
;jpn:　すみついちまってる。@KEY()↓
;jpn:◆ジャイアントステップの↓
;jpn:　ちゅうしんに　たどりつくのは↓
;jpn:　むつかしい。@KEY()↓
;jpn:◆‥‥しっているのは　これだけだ。@WI(15)↓
;jpn:　それいじょうのことは↓
;jpn:　じぶんで　しらべるんだな。@KEY()↓
;jpn:◆ジャイアントステップへの↓
;jpn:　ぬけみちは↓
;jpn:　たびげいにんのこやのなかだ。@KEY()↓
;jpn:◆こやのカギは‥‥@KEY()↓
;jpn:◆オネットしちょうの↓
;jpn:　ゲーハー・ピカールが↓
;jpn:　かくしてるはずだ。@KEY()↓
;jpn:◆おれよりつよい　@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;jpn:　けんとうを　いのるぜ！
@KEYNP()
@SETF(FLG_WIN_FRANK)
@SETF(FLG_ONET_SHARK_2F_DISAPPEAR)
@SETF(FLG_ONET_SHARK_A_DISAPPEAR)
@SETF(FLG_ONET_SHARK_B_DISAPPEAR)
@CLRF(FLG_ONET_SHARK_C_DISAPPEAR)
@SETF(FLG_TEMP_1)
;@SET_HIT_RECT(2,HRECT_PHOTO_2_FRANK,MSG_GLOBAL_PHOTO_2)
』

_ONET_FRANK2;
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_ONET_FRANK2_NESS_DEAD)
◆Ｙｏｕ　ｌｏｏｋ　ｍｕｃｈ　ｓｔｒｏｎｇｅｒ．@WI(20)　　Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｒｅｓｔ？↓
<Ｙｅｓ>　<Ｎｏ>
;◆@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;;jpn:　また　たくましくなったな。@KEY()↓
;;jpn:◆よかったら　やすんでいきな。↓
;;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_FRANK2_YES,_ONET_FRANK2_NO)

_ONET_FRANK2_NO;
◆@DSP_NAME(PC_NESS)，@WI(15)　ｙｏｕ’ｖｅ　ｂｅｃｏｍｅ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　Ｉ！@WI(20)　　Ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ　ｉｓ　ｊｕｓｔ　ｂｅｇｉｎｎｉｎｇ．．．
;jpn:◆おれよりつよい　@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;jpn:　けんとうを　いのるぜ！
@KEYNP()
』

_ONET_FRANK2_YES;
;体力回復（暗転ワープなし、ＢＧＭあり、夜鍋なし、セリフ替えなし）
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
←
◆@DSP_NAME(PC_NESS)，@WI(15)　ｙｏｕ’ｒｅ　ｎｏｗ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　Ｉ！@WI(20)　　Ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ　ｉｓ　ｊｕｓｔ　ｂｅｇｉｎｎｉｎｇ．
;jpn:◆おれよりつよい　@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;jpn:　けんとうを　いのるぜ！
@KEYNP()
』

_ONET_FRANK2_NESS_DEAD;
◆Ｗｈａｔ？@WI(20)　　Ｙｏｕ’ｒｅ　ａ　ｆｒｉｅｎｄ　ｏｆ　@DSP_NAME(PC_NESS)’ｓ？@KEY()↓
◆@DSP_NAME(PC_NESS)　ｉｓ　ｍｙ　ｆｒｉｅｎｄ，@KEY()↓
◆ｈｏｗｅｖｅｒ　Ｉ　ｃａｎ’ｔ　ｒｅｍｅｍｂｅｒ　ｂｅｃｏｍｉｎｇ　ａ　ｆｒｉｅｎｄ　ｏｆ　ａ　ｆｒｉｅｎｄ　ｏｆ　@DSP_NAME(PC_NESS)’ｓ．@KEY()↓
◆Ｑｕｉｔ　ｊｏｋｉｎｇ　ａｂｏｕｔ　ａ　”Ｃｉｒｃｌｅ　ｏｆ　Ｆｒｉｅｎｄｓ”　ａｎｄ　ｇｏ　ｈｏｍｅ！
;jpn:◆なーにー？↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)の↓
;jpn:　ともだちだって？@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)は↓
;jpn:　おれの　ともだちだが@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)の↓
;jpn:　ともだちと　ともだちになった↓
;jpn:　おぼえは　ねぇ！@KEY()↓
;jpn:◆ともだちは↓
;jpn:　わ　じゃねぇんだ@KEY()↓
;jpn:◆かえれ！
@KEYNP()
』
;◆Ｔｈａｔ’ｓ　ｍｙ　ｉｄｅａ．　
;◆@DSP_STS(STS_PC_NAME_NES)！
;	Ｓｏｍｅｔｈｉｎｇ　ｔｅｒｒｉｂｌｅ　ｍｕｓｔ　ｈａｖｅ　ｈａｐｐｅｎｅｄ
;　　ｔｏ　ｙｏｕ！
;　　Ｉ’ｌｌ　ｈｅａｌ　ｙｏｕ！
;◆それが　おれの↓
;　かんがえだ。@KEY()↓

;◆@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;　ひどいめに　あったようだな！
;　おれがなおしてやるぜ！@KEYNP()
;@SET_SPECIAL(PC_NESS,1,1)
;@SET_SPECIAL(PC_NESS,2,1)
;@SET_SPECIAL(PC_NESS,6,1)
;@GOTO(_ONET_FRANK2_YES)

_ONET_FRANK_TRYAGAIN;
◆Ｉｔ’ｓ　ｙｏｕ　ａｇａｉｎ．．．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｒｅａｌｌｙ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｂｅａｔ　Ｆｒａｎｋｙ’ｓ　”Ｆｒａｎｋｙｓｔｅｉｎ　ｔｈｅ　２ｎｄ”？@KEY()↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆また　おまえか‥‥@WI(20)↓
;jpn:　このフランキーさまの↓
;jpn:　「フランキースタイン２ごう」に@KEY()↓
;jpn:◆かてると　おもってるのか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_FRANK_AGAIN_YES,_ONET_FRANK_AGAIN_NO)
_ONET_FRANK_AGAIN_NO;
◆Ｄｉｄ　ｙｏｕ　ｃｏｍｅ　ｈｅｒｅ　ｆｅｅｌｉｎｇ　ｎｏｔ－ｓｏ－ｆｉｔ？@KEY()↓
◆Ｄｏｎ’ｔ　ｅｖｅｎ　ｔｈｉｎｋ　ｏｆ　ｌｏｏｋｉｎｇ　ｂｅｙｏｎｄ　ｍｅ，@WI(15)　ｃｈｕｍｐ．@KEY()↓
;jpn:◆まけると　わかってて↓
;jpn:　また　やってきたのか？@KEY()↓
;jpn:◆なめたまねしやがって‥‥@KEY()↓
_ONET_FRANK_AGAIN_MAIN;
◆Ｇｏ！@WI(20)　　”Ｆｒａｎｋｙｓｔｅｉｎ　ｔｈｅ　２ｎｄ”！@KEY()↓
;jpn:◆いけ！@WI(60)↓
;jpn:　「フランキースタイン２ごう」！@KEY()↓
@GOSUB(MSG_BATTLE_STEIN2)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@OPEN(1)
@GOTO(MSG_ONET_STEIN2_WIN)

_ONET_FRANK_AGAIN_YES;
◆Ａｒｅｎ’ｔ　ｙｏｕ　ｏｖｅｒｃｏｎｆｉｄｅｎｔ？@KEY()↓
;jpn:◆じょうとうじゃねえか‥‥@KEY()↓
@GOTO(_ONET_FRANK_AGAIN_MAIN)

;-------------------------------------------------

MSG_ONET_FRANK_LATER;＆最終戦闘後のフランク
@CHKFGOTO(FLG_TEMP_3,_ONET_FRANK_LATER_MAIN)
◆Ｈｅｌｌｏ　ｓｉｒ，　ｈｏｗ　ｍａｙ　Ｉ　ｈｅｌｐ　ｙｏｕ？@WI(30)　　．．．Ｕｈ．．．@WI(20)Ａｒｅｎ’ｔ　ｙｏｕ　@DSP_NAME(PC_NESS)？@KEY()↓
◆Ａｆｔｅｒ　ｏｕｒ　ｂａｔｔｌｅ　Ｉ　ｂｅｃａｍｅ　ｓｅｒｉｏｕｓ，@WI(15)　ａｎｄ　ｈａｖｅ　ｂｅｅｎ　ｗｏｒｋｉｎｇ　ｖｅｒｙ　ｈａｒｄ．@KEY()↓
◆Ｉ’ｖｅ　ｅｖｅｎ　ｂｅｅｎ　ｄｏｉｎｇ　ｓｏｍｅ　ｔｒａｉｎｉｎｇ　ｆｏｒ．．．@WI(15)ｆｏｒ．．．@KEY()↓
◆Ｗｅｌｌ，@WI(15)　ａ　ｌｉｔｔｌｅ　ｂｉｔ　ｏｆ　ｐｒｏ　ｗｒａｓｓｌｉｎ’．@WI(20)　　Ｉｔ’ｓ　ｔｈｅ　ｒｉｎｇ　ｆｏｒ　ｍｅ，@WI(15)　ｂａｂｙ．．．
;jpn:◆いらっしゃいませー。@WI(30)↓
;jpn:　‥‥なんだ　@DSP_STS(STS_PC_NAME_NES)じゃないか。@KEY()↓
;jpn:◆おれ　あれから　すっかり↓
;jpn:　まじめになって@KEY()↓
;jpn:◆ここで　じみちに↓
;jpn:　バイトしてるんだ。@WI(30)↓
;jpn:　トレーニングをつんで‥‥@KEY()↓
;jpn:◆マエダ・アキラの↓
;jpn:　「ＲＩＮＧＳ」に↓
;jpn:　にゅうもんしようとおもってさ。
@KEY()↓
_ONET_FRANK_LATER_MAIN;
◆Ｓｏ　ｙｏｕ　ｍａｄｅ　ｉｔ　ｂａｃｋ　ａｌｉｖｅ．@WI(20)　　Ｙｏｕ　ｍｕｓｔ　ｈａｖｅ　ｍａｎｙ　ｓｔｏｒｉｅｓ　ｔｏ　ｔｅｌｌ．@KEY()↓
◆Ｌｅｔ’ｓ　ｇｅｔ　ｔｏｇｅｔｈｅｒ　ｆｏｒ　ａ　ｄｒｉｎｋ，@WI(15)　ｗｈｅｎ　ｙｏｕ　ｈａｖｅ　ａ　ｃｈａｎｃｅ　ｓｏ　Ｉ　ｃａｎ　ｈｅａｒ　ｙｏｕｒ　ｓｔｏｒｉｅｓ．@KEY()↓
◆．．．Ｉ’ｍ　ｔａｌｋｉｎｇ　ａｂｏｕｔ　ｄｒｉｎｋｉｎｇ　ｍｉｎｅｒａｌ　ｗａｔｅｒ．@WI(15)　　Ｉ’ｍ　ｓｔｉｌｌ　ｕｎｄｅｒ　ａｇｅ，@WI(15)　ｙｏｕ　ｋｎｏｗ．
;jpn:◆‥‥@DSP_STS(STS_PC_NAME_NES)@WI(20)↓
;jpn:　いきてかえったんだなぁ。@KEY()↓
;jpn:◆さぞかし　いろんなことが↓
;jpn:　あったんだろうよ。@KEY()↓
;jpn:◆こんど　ゆっくり↓
;jpn:　いっぱい　のみながら↓
;jpn:　きかせてくれよ。@KEY()↓
;jpn:◆‥‥いっぱいのむってのは↓
;jpn:　ミネラルウォーターだよ。@WI(20)↓
;jpn:　おれも　まだ　みせいねんだしさ。
@KEYNP()
@SETF(FLG_TEMP_3)
』
;----------------

;@Habitat:オネット／フィールド／ジャイアントステップ
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_GIAN_BOSS/off
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_ONET_GIAN_BOSS
MSG_ONET_GIAN_BOSS;
@CHKFGOTO(FLG_WIN_GIAN_BOSS,MSG_SYS_HANASU_NG)
;◆（Ａ　ｈｕｇｅ　ａｎｔ　ｌｉｖｅｓ　ｉｎ　Ｇｉａｎｔ　Ｓｔｅｐ．）
;◆（ジャイアントステップには↓
;　きょだいな　アリが↓
;　すみついていた）@KEY()↓
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆Ｙｏｕ　ｆｉｎａｌｌｙ　ｇｏｔ　ｈｅｒｅ．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ｔｈｅ　ｆｉｒｓｔ　”Ｙｏｕｒ　Ｓａｎｃｔｕａｒｙ”　ｌｏｃａｔｉｏｎ．@WI(20)　　Ｂｕｔ　ｉｔ’ｓ　ｍｉｎｅ　ｎｏｗ．@KEY()↓
◆Ｔａｋｅ　ｉｔ　ｆｒｏｍ　ｍｅ，@WI(30)　ｉｆ　ｙｏｕ　ｄａｒｅ．．．
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは　１ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし　いまは↓
;jpn:　わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_GIAN_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_ONET_GIANT_6_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_GIAN_BOSS)
』

;1２３４５６７８９０１２３４５６７

;▼▲▼▲▼▲▼▲　オネット　▼▲▼▲▼▲▼▲

;^^^^^^^^オネット：水野家の地下洞窟^^^^^^^^

;@Habitat:オネット／水野家の地下洞窟／洞窟２
;@Person:水野さん
;@Figure:水野さん
;@AppearanceKey:FLG_B1MIZUNO_APPEAR/on
;@ActionScript:＊右向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_INSEKI_MIZUNO_B1
MSG_INSEKI_MIZUNO_B1;
@OPEN(1)
◆．．．Ｓｏ　@DSP_NAME(PC_NESS)　ｂｕｄｄｙ，@WI(15)　Ｉ’ｖｅ　ｆｏｕｎｄ　ｐｒｏｏｆ　ｏｆ　ａ　ｇｒｅａｔ　ｔｒｅａｓｕｒｅ．．．ａ　ｈｕｇｅ　ｈａｕｌ．．．@KEY()↓
◆ｙａｈ，@WI(15)　ｈａｈ，@WI(10)　ｈａｈ．．．@WI(20)↓
　　Ｉ’ｌｌ　ｓｈｏｗ　ｙｏｕ，@WI(15)　ｂｕｔ　ｙｏｕ’ｒｅ　ｔｈｅ　ｏｎｌｙ　ｏｎｅ．@WI(20)　　Ｃ’ｍｏｎ．
;jpn:◆‥‥でもね　@DSP_STS(STS_PC_NAME_NES)ちゃん。@WI(15)↓
;jpn:　おれは　じつは　すでに↓
;jpn:　すっごいたからものが　あるという@KEY()↓
;jpn:◆しょうこの　しなものを↓
;jpn:　みつけてるんだよ。↓
;jpn:　‥‥‥@KEY()↓
;jpn:◆ふふふ‥‥@WI(15)あんたには↓
;jpn:　みせてやろう。@WI(20)↓
;jpn:　こっちだ。
@KEY()
@CLOSEALL()
@GOSUB(MSG_EVT_13_MIZUNO_2_A);マニマニを見せる水野さん
@CLRF(FLG_B3MIZUNO_B_APPEAR)
@SETF(FLG_B4MIZUNO_APPEAR)
』


;@Habitat:オネット／水野家の地下洞窟／洞窟４
;@Person:水野さん
;@Figure:水野さん
;@AppearanceKey:FLG_B2MIZUNO_APPEAR/on
;@ActionScript:＊右向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_INSEKI_MIZUNO_B2
MSG_INSEKI_MIZUNO_B2;
@CHKFGOTO(FLG_WIN_GIEGU,MSG_ONET_MIZUNO_END)
@CHKFGOTO(FLG_TLPT_TWSN,_INSEKI_MIZUNO_B2_LATER)
◆Ｉｆ　ｔｈｉｓ　ｉｓ　ａ　ｓｉｇｎ　ｏｆ　ｗｈａｔ　ｌｉｅｓ　ｂｅｌｏｗ，@WI(15)　ｉｔ’ｓ　ｊｕｓｔ　ａ　ｍａｔｔｅｒ　ｏｆ　ｔｉｍｅ．@KEY()↓
◆Ｍｙ　ｄｅｓｔｉｎｙ　ｉｓ　ｔｏ　ｄｉｇ　ｕｐ　ｔｈｅ　ｂｕｒｉｅｄ　ｔｒｅａｓｕｒｅ．@KEY()↓
◆Ｉ’ｌｌ　ｅａｔ　ｇａｒｌｉｃ　ａｎｄ　ｗｏｒｋｏｕｔ　ｔｏ　ｈｅｌｐ　ｓｔｒｅｎｇｔｈｅｎ　ｍｙｓｅｌｆ．@KEY()↓
◆Ｇｏ　ｈｏｍｅ　ｎｏｗ．@WI(20)　　Ｙｏｕ’ｒｅ　ｇｅｔｔｉｎｇ　ｉｎ　ｔｈｅ　ｗａｙ　ｏｆ　ｍｙ　ｗｏｒｋ．@KEY()↓
◆Ｙｏｕ　ｍａｙ　ｓｔａｒｔ　ｔｏ　ｇｅｔ　ｇｒｅｅｄｙ　ｔｈｏｕｇｈｔｓ．．．
;jpn:◆こんなものが　でてしまったら↓
;jpn:　あとは　もうじかんのもんだいだ。@KEY()↓
;jpn:◆おれには　ここのたからを↓
;jpn:　ほりだすという　しめいがある。@WI(15)↓
;jpn:　ニンニクをくって　がんばるぞ。@KEY()↓
;jpn:◆じゃ　しごとのじゃまになるから↓
;jpn:　かえってくれ。@KEY()↓
;jpn:◆あんただって　よからぬことを↓
;jpn:　かんがえないとも　いえないし‥。
@KEYNP()
』

_INSEKI_MIZUNO_B2_LATER;
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_MIZUNO_B2_LATER_NESS_DEAD)
@CHKFGOTO(FLG_TEMP_1,_INSEKI_MIZUNO_B2_LATER_TEMP)
@CHKFGOTO(FLG_INSEKI_MIZUNO_B2,_INSEKI_MIZUNO_B2_LATER2)
◆Ｈｅｙ　@DSP_NAME(PC_NESS)，@WI(15)　ｐａｌ．@KEY()↓
◆Ｔｈｅｒｅ　ｗａｓ　ａ　ｍａｎ　ｗｈｏ　ｉｎｓｉｓｔｅｄ　ｔｈａｔ　ｈｅ　ｂｕｙ　ｔｈｅ　ｇｏｌｄｅｎ　ｓｔａｔｕｅ，@WI(15)　ｓｏ　Ｉ　ｓｏｌｄ　ｉｔ　ｔｏ　ｈｉｍ．@KEY()↓
◆Ｉｔ’ｓ　ｎｏｔ　ｔｈａｔ　Ｉ　ｎｅｅｄｅｄ　ｔｈｅ　ｍｏｎｅｙ．．．@KEY()↓
◆Ｉｔ’ｓ　ｊｕｓｔ　ｔｈａｔ　ｈｉｓ　ｕｎｂｒｉｄｌｅｄ　ｍａｎｉａ　ａｆｆｅｃｔｅｄ　ｍｅ．@KEY()↓
◆Ａｓ　ｙｏｕ　ｋｎｏｗ，@WI(15)　Ｉ’ｍ　ａ　ｓｕｃｋｅｒ　ｆｏｒ　ｓｅｎｔｉｍｅｎｔ．@KEY()↓
◆Ｂｙｅ，　ｆｏｒ　ｎｏｗ．
;jpn:◆やぁ　@DSP_STS(STS_PC_NAME_NES)ちゃん。@KEY()↓
;jpn:◆あの　おうごんのぞうは↓
;jpn:　どうしてもってひとが　あらわれて↓
;jpn:　うってしまったんだ。@KEY()↓
;jpn:◆おれは　はしたがねが↓
;jpn:　ほしかったんじゃないけど‥‥　@KEY()↓
;jpn:◆おとこの　ねついに↓
;jpn:　ほだされてね。@KEY()↓
;jpn:◆おれって　おとこは↓
;jpn:　なさけにゃ　よわいだろ。↓
;jpn:　‥‥あんたも　しってのとおり。@KEY()↓
;jpn:◆じゃ　またね。
@KEYNP()
@SETF(FLG_INSEKI_MIZUNO_B2)
@SETF(FLG_TEMP_1)
』

_INSEKI_MIZUNO_B2_LATER_TEMP;
◆Ｈｅｙ　@DSP_NAME(PC_NESS)，@WI(15)　ｐａｌ．@KEY()↓
◆Ｔｈｅｒｅ　ｗａｓ　ａ　ｍａｎ　ｗｈｏ　ｉｎｓｉｓｔｅｄ　ｔｈａｔ　ｈｅ　ｂｕｙ　ｔｈｅ　ｇｏｌｄｅｎ　ｓｔａｔｕｅ，@WI(15)　ｓｏ　Ｉ　ｓｏｌｄ　ｉｔ　ｔｏ　ｈｉｍ．@KEY()↓
◆Ｉｔ’ｓ　ｎｏｔ　ｔｈａｔ　Ｉ　ｎｅｅｄｅｄ　ｔｈｅ　ｍｏｎｅｙ．．．@KEY()↓
◆Ｉｔ’ｓ　ｊｕｓｔ　ｔｈａｔ　ｈｉｓ　ｍａｎｉａ　ａｆｆｅｃｔｅｄ　ｍｅ．@KEY()↓
◆Ａｓ　ｙｏｕ　ｋｎｏｗ，@WI(15)　Ｉ’ｍ　ａ　ｓｕｃｋｅｒ　ｆｏｒ　ｓｅｎｔｉｍｅｎｔ．@KEY()↓
◆Ｂｙｅ，　ｆｏｒ　ｎｏｗ．

;jpn:◆やぁ　@DSP_STS(STS_PC_NAME_NES)ちゃん。@KEY()↓
;jpn:◆あの　おうごんのぞうは↓
;jpn:　どうしてもってひとが　あらわれて↓
;jpn:　うってしまったんだ。@KEY()↓
;jpn:◆おれは　はしたがねが↓
;jpn:　ほしかったんじゃないけど‥‥@KEY()↓
;jpn:◆おとこの　ねついに↓
;jpn:　ほだされてね。@KEY()↓
;jpn:◆おれって　おとこは↓
;jpn:　なさけにゃ　よわいだろ。↓
;jpn:　‥‥あんたも　しってのとおり。@KEY()↓
;jpn:◆じゃ　またね。
@KEYNP()
』

_INSEKI_MIZUNO_B2_LATER2;
◆Ｉ　ｈａｖｅｎ’ｔ　ｂｅｅｎ　ａｂｌｅ　ｔｏ　ｇｅｔ　ｍｙ　ｈａｎｄｓ　ｏｎ　ｔｈｅ　ｔｒｅａｓｕｒｅ．．．@KEY()↓
◆Ｂｕｔ　ｗｈｅｎ　Ｉ　ｄｏ　ａ　ｊｏｂ，@WI(15)　Ｉ　ｄｏ　ｉｔ　ｗｅｌｌ．@WI(20)　　Ｉ’ｍ　ａ@WI(10)　ｍａｎ@WI(5)’ｓ　ｍａｎ．@KEY()↓
◆Ｗｈｅｎ　ｔｈｅ　ｇａｍｅ　ｉｓ　ｏｖｅｒ，@WI(15)　Ｉ　ｍａｙ　ｂｅ　ａ　ｈｅｒｏ．@KEY()↓
◆Ｙｏｕ　ｍｉｇｈｔ　ｉｇｎｏｒｅ　ｍｅ　ｎｏｗ，@WI(15)　ｂｕｔ　ｙｏｕ’ｌｌ　ｓｅｅ　ｌａｔｅｒ．．．
;jpn:◆まだ　ほんめいの　おたからは↓
;jpn:　てにしてないが‥‥↓
;jpn:　なにせ　おれは@KEY()↓
;jpn:◆やるときゃやる！@WI(20)　おとこだ。↓
;jpn:　ゲームがおわったころには↓
;jpn:　ヒーローになってるかもしれんよ。@KEY()↓
;jpn:◆せいぜい　いまは↓
;jpn:　むししているが　いいさ。
@KEYNP()
』

_MIZUNO_B2_LATER_NESS_DEAD;
◆Ｇｏ　ａｈｅａｄ　ａｎｄ　ｌａｕｇｈ　ａｔ　ｍｅ．@KEY()↓
◆Ｂｕｔ　ｗｈｅｎ　Ｉ　ｄｏ　ａ　ｊｏｂ，@WI(15)　Ｉ　ｄｏ　ｉｔ　ｗｅｌｌ．@WI(20)　　Ｉ’ｍ　ａ@WI(10)　ｍａｎ@WI(5)’ｓ　ｍａｎ．@KEY()↓
◆Ｗｈｅｎ　ｔｈｅ　ｇａｍｅ　ｉｓ　ｏｖｅｒ，@WI(15)　Ｉ　ｍａｙ　ｂｅ　ａ　ｈｅｒｏ．@KEY()↓
◆Ｙｏｕ　ｍｉｇｈｔ　ｉｇｎｏｒｅ　ｍｅ　ｎｏｗ，@WI(15)　ｂｕｔ　ｙｏｕ’ｌｌ　ｓｅｅ　ｌａｔｅｒ．．．
;jpn:◆あんたは　ばかにして↓
;jpn:　いるかもしれないが↓
;jpn:◆なにせ　おれは@WI(20)
;jpn:　やるときゃやる！@WI(20)　おとこだ。@KEY()↓
;jpn:◆ゲームがおわったころには↓
;jpn:　ヒーローになってるかもしれんよ。@KEYNP()
;jpn:◆せいぜい　いまは↓
;jpn:　むししているが　いいさ。
@KEY()↓
』

;@Habitat:オネット／水野家の地下洞窟／洞窟４
;@Person:黄金の像
;@Figure:黄金のオスカー
;@AppearanceKey:FLG_B2MIZUNO_APPEAR/on
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:MSG_ONET_CHECK_MANIMANI
;@Message:0
MSG_ONET_CHECK_MANIMANI;
◆（Ｔｈｅ　Ｇｏｌｄｅｎ　Ｓｔａｔｕｅ　ｉｓ　ｇｌｏｗｉｎｇ　ｓｔｒａｎｇｅｌｙ．．．）
;jpn:◆（おうごんの　ぞうは↓
;jpn:　あやしくかがやいている‥‥）
@SE(SE_se71_bunboon_stop);怪しく光っている音
@KEYNP()
』

;-------------------------------------------------
;トレーシー
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_TRACY;トレーシーの部屋のトレーシー
@CHKFGOTO(FLG_WIN_GIEGU,MSG_MYHOME_TRACY_END)
;落とし物検査
@CHKFGOTO(FLG_GLOBAL_LOST_TAKOKESHI,_YAZIUMA_TRACY_LOSTITEM_TACO)
@CHKFGOTO(FLG_GLOBAL_LOST_TAKANOME,_YAZIUMA_TRACY_LOSTITEM_TAKA)
;
@CHKFGOTO(FLG_ONET_DOOR_CLOSE,_MYHOME_TRACY_XYZ)
@CHKFGOTO(FLG_MYHOME_POKEY_ENTER,MSG_MYHOME_TRACY)
@CHKFGOTO(FLG_YAZIUMA_TRACY,_YAZIUMA_TRACY_LATER)
◆Ｈｅｙ，@WI(10)　ｂｒｏ．@WI(20)　　Ｄｉｄ　ｔｈｅ　ｓｏｕｎｄ　ｗａｋｅ　ｙｏｕ　ｕｐ？@KEY()↓
◆Ｗｅｒｅ　ｙｏｕ　ｆｒｅａｋｅｄ　ｏｕｔ？
;jpn:◆おにいちゃんも　いまのおとで↓
;jpn:　めが　さめちゃったの？@KEY()↓
;jpn:◆こわかったねー。
@KEYNP()
@SETF(FLG_YAZIUMA_TRACY)
』
_YAZIUMA_TRACY_LATER;
◆Ｃａｎ　Ｉ　ｓｔａｙ　ｕｐ　ｌａｔｅ　ｔｏｎｉｇｈｔ？@WI(20)　　Ｉ　ｃａｎ’ｔ　ｓｅｅｍ　ｔｏ　ｆａｌｌ　ｂａｃｋ　ａｓｌｅｅｐ．
;jpn:◆このまま　よふかし↓
;jpn:　しちゃおうかなっ。@KEY()↓
;jpn:◆めが　さめちゃった。
@KEYNP()
』
_MYHOME_TRACY_XYZ;
◆Ｉ　ｃａｎ　ｏｎｌｙ　ｈｅｌｐ　ｂｙ　ｋｅｅｐｉｎｇ　ｙｏｕｒ　ｉｔｅｍｓ　ｈｅｒｅ．．．@KEY()↓
◆Ｉ　ｓｕｐｐｏｒｔ　ｙｏｕ　ｗｈｏｌｅ－ｈｅａｒｔｅｄｌｙ．@WI(20)　　Ｄｏｎ’ｔ　ｇｅｔ　ｙｏｕｒｓｅｌｆ　ｋｎｏｃｋｅｄ　ｏｆｆ．@KEY()↓
◆．．．Ｉ　ｗｉｌｌ　ｂｅ　ｓｔｒｏｎｇ　ｗｈｉｌｅ　ｙｏｕ’ｒｅ　ｇｏｎｅ．
;jpn:◆わたし　にもつの↓
;jpn:　おあずかりくらいしか↓
;jpn:　てつだえないけど‥‥@KEY()↓
;jpn:◆こころから　おうえんしてるわ。@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆しんじゃ　いやよ！@KEY()↓
;jpn:◆‥‥わたしも　しっかりしなきゃ。
@KEY()↓
@GOTO(MSG_TRACY)

;階段のトレーシー
;FLG_KAIDAN_TRACY_APPEAR/onで出現
MSG_KAIDAN_TRACY;ポーキーのノック後登場する階段近くのトレーシー
◆Ｓｏｍｅｏｎｅ’ｓ　ｋｎｏｃｋｉｎｇ　ａｔ　ｔｈｅ　ｄｏｏｒ．@WI(20)　　Ｗｈａｔ　ａｎ　ａｎｎｏｙｉｎｇ　ｋｎｏｃｋ！
;jpn:◆だれか　ノックしてるみたい。↓
;jpn:　げひんな　たたきかただなあ。
@KEYNP()
』

_YAZIUMA_TRACY_LOSTITEM_TACO;落とし物検査
◆Ｈｅｙ　ｂｒｏ．．．ｙｏｕ’ｒｅ　ｈｅｒｅ　ｆｏｒ　ｔｈｅ　@DSP_GOODS(GDS_TOOL_KEY_TAKOKESHI)，@WI(15)　ａｒｅｎ’ｔ　ｙｏｕ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆あ@WI(15)　「タコけしマシン」を↓
;jpn:　とりにきたのね？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_TRACY_LOSTITEM_TACO_YES,_TRACY_LOSTITEM_NO)
_TRACY_LOSTITEM_NO;
◆Ｏｈ，@WI(15)　ｙｏｕ　ａｒｅｎ’ｔ？@WI(20)　　．．．Ｉ　ｗａｓ　ｒｅａｄｙ　ｔｏ　ｇｉｖｅ　ｉｔ　ｔｏ　ｙｏｕ．．．
;jpn:◆なーんだ　ちがうのかぁ。@WI(20)↓
;jpn:　‥‥でも　もう　わたすつもりで↓
;jpn:　じゅんびしてたのに。
@KEYNP()
』
_TRACY_LOSTITEM_TACO_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TRACY_LOSTITEM_FULL)
◆Ｈｅｒｅ’ｓ　ｔｈｅ　@DSP_GOODS(GDS_TOOL_KEY_TAKOKESHI)．@WI(20)　　Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｕｓｅ　ｉｔ　ｆｏｒ？@KEY()↓
◆Ｓｏｒｒｙ．．．@WI(15)　　Ｉ　ｒｅａｌｌｙ　ｓｈｏｕｌｄｎ’ｔ　ｉｎｑｕｉｒｅ　ａｂｏｕｔ　ａ　ｃｕｓｔｏｍｅｒ’ｓ　ｐｒｉｖａｔｅ　ｍａｔｔｅｒｓ．
;jpn:◆はい　「タコけしマシン」@WI(20)↓
;jpn:　なんにつかうのかしら。↓
;jpn:◆あ　おきゃくさまの↓
;jpn:　プライベートに　かかわっちゃ↓
;jpn:　いけないんだったわ。@KEY()↓
;jpn:◆ごめーん。
@KEY()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TAKOKESHI)
@SE(SE_se74_my_get)
@WI(60)
@CLRF(FLG_GLOBAL_LOST_TAKOKESHI)
』

_YAZIUMA_TRACY_LOSTITEM_TAKA;落とし物検査
◆Ｈｅｙ，@WI(10)　ｂｒｏ．@WI(20)　　Ｙｏｕ’ｒｅ　ｈｅｒｅ　ｆｏｒ　ｔｈｅ　”@DSP_GOODS(GDS_TOOL_EAGLE_EYE)，”@WI(15)　ａｒｅｎ’ｔ　ｙｏｕ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆あ@WI(15)　「タカのめ」を↓
;jpn:　とりにきたのね？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_TRACY_LOSTITEM_TAKA_YES,_TRACY_LOSTITEM_NO)
@GOTO(_TRACY_LOSTITEM_NO)

_TRACY_LOSTITEM_TAKA_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_TRACY_LOSTITEM_FULL)
◆Ｈｅｒｅ’ｓ　ｔｈｅ　”@DSP_GOODS(GDS_TOOL_EAGLE_EYE)．”@WI(20)　　Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｕｓｅ　ｉｔ　ｆｏｒ？@KEY()↓
◆Ｓｏｒｒｙ．@WI(20)　　Ｉ’ｍ　ｎｏｔ　ｓｕｐｐｏｓｅｄ　ｔｏ　ｉｎｑｕｉｒｅ　ａｂｏｕｔ　ａ　ｃｕｓｔｏｍｅｒ’ｓ　ｐｒｉｖａｔｅ　ｍａｔｔｅｒｓ．
;jpn:◆はい　「タカのめ」@WI(20)↓
;jpn:　なんにつかうのかしら。↓
;jpn:◆あ　おきゃくさまの↓
;jpn:　プライベートに　かかわっちゃ↓
;jpn:　いけないんだったわ。@KEY()↓
;jpn:◆ごめーん。
@KEY()
@GOODSIN_PLAYER(0,GDS_TOOL_EAGLE_EYE)
@SE(SE_se74_my_get)
@WI(60)
@CLRF(FLG_GLOBAL_LOST_TAKANOME)
』

_TRACY_LOSTITEM_FULL;
◆Ｉｔ　ｓｅｅｍｓ　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｉｔｅｍｓ　ｔｏ　ｃａｒｒｙ！
;jpn:◆でも　もちものが↓
;jpn:　いっぱいみたいよ！
@KEYNP()
』
;-------------------------------------------------
;ママ
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_MAMA;
@CHKFGOTO(FLG_STEP_ONET,_YAZIUMA_MAMA_AFTER);外に出てたらセリフ替え
@CHKFGOTO(FLG_YAZIUMA_MAMA,_YAZIUMA_MAMA_LATER)
◆Ｗｈａｔ　ｗａｓ　ｔｈａｔ　ｎｏｉｓｅ？@KEY()↓
◆@DSP_NAME(PC_NESS)，@WI(15)　ｙｏｕ　ｄｏｎ’ｔ　ｓｅｅｍ　ｓｃａｒｅｄ．@WI(20)　　Ａｒｅ　ｙｏｕ　ｎｕｔｓ？@KEY()↓
◆Ａｎｄ　ｎｏｗ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ　ｃｈｅｃｋ　ｉｔ　ｏｕｔ？@WI(15)　　．．．ｏｈ@WI(15)．．．ｏｋａｙ．@KEY()↓
◆Ｙｏｕ’ｌｌ　ｓｎｅａｋ　ｏｕｔ　ｏｆ　ｙｏｕｒ　ｒｏｏｍ　ａｎｙｗａｙ，@WI(15)　ｅｖｅｎ　ｉｆ　Ｉ　ａｓｋｅｄ　ｙｏｕ　ｎｏｔ　ｔｏ．@KEY()↓
◆Ａｔ　ｌｅａｓｔ　ｃｈａｎｇｅ　ｏｕｔ　ｏｆ　ｙｏｕｒ　ｊａｍｍｉｅｓ　ｂｅｆｏｒｅ　ｙｏｕ　ｇｏ．
;jpn:◆なーんだったのかしら↓
;jpn:　あのおと！@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn:　あなた　ちっとも↓
;jpn:　こわがってないみたいね。@KEY()↓
;jpn:◆まさか　そとへ↓
;jpn:　ようすを　みにいきたいなんて↓
;jpn:　いうんじゃ　ないでしょうね？@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆わかったわ。@KEY()↓
;jpn:◆ママがとめても↓
;jpn:　へやを　ぬけだして↓
;jpn:　みにいくんでしょうから@KEY()↓
;jpn:◆せめて　ちゃんときがえて↓
;jpn:　いってらっしゃい。
@KEY()
@CLOSEALL()
@WI(1)
@SETF(FLG_YAZIUMA_MAMA)
@CLRF(FLG_MYHOME_NES_CHANGE)
@WARP(WARP_MYHOME_2ND);着替えてベッドから
』

_YAZIUMA_MAMA_LATER;その後
◆Ｂｅ　ｃａｒｅｆｕｌ！@WI(20)　　Ｃｏｍｅ　ｈｏｍｅ　ａｓ　ｓｏｏｎ　ａｓ　ｙｏｕ　ｃａｎ．
;jpn:◆じゃあ　きをつけて。@WI(30)↓
;jpn:　なるべくはやく↓
;jpn:　かえってくるのよ。
@KEYNP()
』
_YAZIUMA_MAMA_AFTER;外に出たら
◆Ｗｈａｔ　ｗａｓ　ｔｈａｔ　ｎｏｉｓｅ？@KEY()↓
◆Ｙｏｕ　ｄｏｎ’ｔ　ｓｅｅｍ　ｓｃａｒｅｄ　ａｔ　ａｌｌ．@WI(20)　　Ｂｅ　ｃａｒｅｆｕｌ！
;jpn:◆なーんだったのかしら↓
;jpn:　あのおと！@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn:　あなた　ちっとも↓
;jpn:　こわがってないみたいね。
@KEYNP()
』

;◆Ｓｏｍｅｈｏｗ，　Ｉ’ｍ　ａｗａｋｅ．　
;◆ママもなんだか↓
;　めが　さえちゃったわ。@KEYNP()
;』
;
;◆Ｔａｋｅ　ｃａｒｅ．．．　
;◆Ａｎｄ　ｃｏｍｅ　ｈｏｍｅ　ａｓ　ｓｏｏｎ　ａｓ　ｙｏｕ　ｃａｎ．　
;◆きをつけて↓
;　いってらっしゃい‥‥。@KEY()↓
;◆なるべく　すぐ↓
;　かえってくるんですよ。@KEY()↓
;』
;◆Ｅｖｅｎ　ｉｆ　Ｉ　ｔｒｙ　ｔｏ　ｓｔｏｐ　ｙｏｕ，　ｙｏｕ’ｌｌ　ｇｏ　ｃｈｅｃｋ
;　　ｉｔ　ｏｕｔ　ａｎｙｗａｙ．　　Ｇｏ　ａｈｅａｄ．　
;◆Ｂ－Ｅ　　　Ｃ－Ａ－Ｒ－Ｅ－Ｆ－Ｕ－Ｌ！！　
;◆ママがとめても↓
;　みにいくんでしょうから↓
;　はやく　いってらっしゃい。@KEY()↓
;◆音@WI(10)キ・@WI(20)オ・@WI(20)ツ・@WI(20)ケ・@WI(20)テ！@KEYNP()


MSG_GENKAN_MAMA;ポーキーと話すと玄関に出現している
;FLG_GENKAN_MAMA_APPEAR/on
◆Ｗｅｌｃｏｍｅ　ｈｏｍｅ，@WI(15)　@DSP_NAME(PC_NESS)．@KEY()↓
◆Ｉｔ’ｓ　ｎｏｔ　ｎｅｃｅｓｓａｒｙ　ｔｏ　ｔａｌｋ　ａｂｏｕｔ　ｉｔ　ｔｏｎｉｇｈｔ．@KEY()↓
◆Ｉｔ’ｓ　ｌａｔｅ，@WI(20)　ｓｃｏｏｔ　ｏｆｆ　ｔｏ　ｂｅｄ　ｎｏｗ．↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆おかえり　@DSP_STS(STS_PC_NAME_NES)@KEY()↓
;jpn:◆なにもいわなくても　いいの。↓
;jpn:　ママは　わかってるつもりよ。@KEY()↓
;jpn:◆きょうは　もうおそいから↓
;jpn:　はやく　おやすみなさい。↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_GENKAN_MAMA_YES,_GENKAN_MAMA_NO)
_GENKAN_MAMA_NO;
◆Ｏｈ，@WI(15)　@DSP_NAME(PC_NESS)．@WI(20)　　Ｙｏｕ　ｄｏｎ’ｔ　ｕｎｄｅｒｓｔａｎｄ　ｔｈｅ　ｉｍｐｏｒｔａｎｃｅ　ｏｆ　ａ　ｇｏｏｄ　ｎｉｇｈｔ’ｓ　ｓｌｅｅｐ！
;jpn:◆まあ　@DSP_STS(STS_PC_NAME_NES)ったら。↓
;jpn:　すいみんの　たいせつさを↓
;jpn:　しらないのね！
@KEYNP()
』
_GENKAN_MAMA_YES;
@CLOSEALL()
@BGM_EFFECT( 3 )	;長いフェードアウト
@SETF(FLG_MYHOME_KNOCK_APPEAR)
@SETF(FLG_YAZIUMA_DISAPPEAR)
@SETF(FLG_MYHOME_TRACY_DISAPPEAR)
@CLRF(FLG_GENKAN_MAMA_APPEAR)	;お迎えママ消す ＆ 暗闇でノック音鳴らす(MUSI)
@SETF(FLG_KAIDAN_TRACY_APPEAR)
@SETF(FLG_ONET_POKEY_DOOR_CLOSE)
@SETF(FLG_MYHOME_NES_CHANGE)			;パジャマ着る
@RESF(FLG_SYS_MONSTER_OFF)			;モンスターの出現を許可
@CLRF(FLG_MYHOME_LIGHT_ON)			;ネスの部屋を暗くする
@MOVE_GOM_CHAR( GOM_HIT_CHR,ANIM_INTO_NIGHT,OBJFX_SHOW_NONE )	;フェードアウト
@WAITSYS()
@WI( 120 )
@HIDE_PLAYER( PC_ALL, OBJFX_HIDE_NONE )		;パーティ消す
;「さらに夜もふけて…」表示
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_KANJI_AT_THE_NIGHT, OBJFX_SHOW_NONE )
@WAITSYS()
;真っ暗画面へワープ（暗闇でポーキーの「扉どんどん」ＢＧＭを鳴らすため）
@WARP( WARP_PUBLIC_BLACKSCREEN )
@WI( 180 )
;ネスの寝室へワープ
@MOVE_GOM_CHAR( GOM_NES_PAZYAMA, ANIM_SEAL_PC_ALL_DIRLEFT, OBJFX_AFTER_WARP )
@WARP(WARP_MYHOME_2ND);パジャマに着替えてベッドから
@COLD_PLAYER( PC_ALL )
@WI( 1 )
@HIDE_GOM_CHAR( GOM_NES_PAZYAMA, OBJFX_HIDE_NONE )
@SHOW_PLAYER( PC_ALL, OBJFX_SHOW_NONE )		;パーティ表示
』
;-------------------------------------------------
;犬→本文中に追加した
;◆（Ａｌｌ　ｔｈｉｓ　ｒａｃｋｅｔ．．．　ｓｏｕｎｄｓ　ｌｉｋｅ　ｄａｙ　ｔｉｍｅ．
;　　Ｂｕｔ　ｉｔ’ｓ　ｄａｒｋ　ｏｕｔｓｉｄｅ．．．）　
;◆（まるで　ひるまみたいな↓
;　さわぎだけど　でも↓
;　よるなんだよね。　いまは）@KEYNP()
;』
;
;-------------------------------------------------
;警官１
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP1;
◆Ｄｏｎ’ｔ　ｙｏｕ　ｋｎｏｗ　ｗｈａｔ　ｔｉｍｅ　ｉｔ　ｉｓ？！@WI(20)　　Ｇｅｔ　ｙｅｒ　ｂｕｔｔ　ｈｏｍｅ，@WI(15)　ｐｒｏｎｔｏ！
;jpn:◆いま　なんじだと↓
;jpn:　おもっているんだ！@KEY()↓
;jpn:◆さっさと　いえにかえるんだ！
@KEYNP()
』

;-------------------------------------------------
;男１
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_MAN1;
◆Ｉ　ｗａｎｔ　ｔｏ　ｒｅｔｕｒｎ　ｈｏｍｅ，@WI(15)　ｂｕｔ　ｔｈｅ　ｒｏａｄ　ｉｓ　ｃｌｏｓｅｄ．@KEY()↓
◆Ｐｅｏｐｌｅ　ａｒｅ　ｔａｋｉｎｇ　ｔｈｉｓ　ｍｅｔｅｏｒｉｔｅ　ｓｉｔｕａｔｉｏｎ　ｔｏｏ　ｓｅｒｉｏｕｓｌｙ！
;jpn:◆まちにかえりたいのに↓
;jpn:　どうろが　つうこうどめなんだ。@KEY()↓
;jpn:◆いんせきが　おちたくらいで↓
;jpn:　おおさわぎしすぎだよ！
@KEYNP()
』

;-------------------------------------------------
;警官２
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP2;
◆Ｄｏｎ’ｔ　ｐａｎｉｃ！@WI(20)　　Ｉｔ’ｓ　ｊｕｓｔ　ａ．．．@WI(20)ｗｈａｔ？！．．．ｍｅｔｅｏｒｉｔｅ　ｔｈａｔ．．．@WI(20)ｗｈｏ？！．．．ｆｅｌｌ．@KEY()↓
◆Ｉ　ｊｕｓｔ　ｗａｎｎａ．．．@WI(15)ｗｈａｔ？！@WI(20)．．．ｇｏ　ｈｏｍｅ．．．
;jpn:◆い　いんせきが↓
;jpn:　おち　おち　おちたくらいで↓
;jpn:　パ　パニックになるんじゃない！@KEY()↓
;jpn:◆は　はやく　じぶんのおうちに↓
;jpn:　かえ@WI(15)　かえ@WI(15)　かえ@KEY()↓
;jpn:◆かえりたいよー！
@KEYNP()
』

;-------------------------------------------------
;警官３
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP3;
◆Ｏｎｅｔｔ　ｐｏｌｉｃｅ　ａｒｅ　ｉｎｆａｍｏｕｓ　ｆｏｒ　ｃｌｏｓｉｎｇ　ｒｏａｄｓ　ｉｆ　ｓｏｍｅｔｈｉｎｇ　ｉｓ　ｇｏｉｎｇ　ｏｎ．@KEY()↓
◆Ｗｅ　ａｒｅ　ｇｏｉｎｇ　ｆｏｒ　ｔｈｅ　Ｇｕｉｎｎｅｓｓ　Ｗｏｒｌｄ　Ｒｅｃｏｒｄ．．．
;jpn:◆オネットけいさつは↓
;jpn:　なにかあると　すぐに@KEY()↓
;jpn:◆どうろをふうさするので↓
;jpn:　ゆうめいなんだ。@KEY()↓
;jpn:◆ギネスに　ちょうせんしてるんだ。
@KEYNP()
』

;-------------------------------------------------
;男２
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_MAN2;
◆Ｄｉｄ　ｙｏｕ　ｈｅａｒ　ｔｈｅ　ｂｉｇ　ｂａｎｇ？@WI(20)　　Ｉ　ｔｈｉｎｋ　ａ　ｍｅｔｅｏｒｉｔｅ　ｌａｎｄｅｄ　ｎｅａｒｂｙ．@KEY()↓
◆Ｉ　ｗａｎｔ　ｔｏ　ｂｅ　ｔｈｅ　ｆｉｒｓｔ　ｔｏ　ｓｅｅ　ｉｔ．@WI(15)　　Ｏｋａｙ？@KEY()↓
◆Ｉ　ａｍ　ｇｏｉｎｇ　ｔｏ　ｔｒｙ　ｔｏ　ｂｅ　ｔｈｅ　ｆｉｒｓｔ　ｔｏ　ｇｅｔ　ｔｈｅｒｅ．．．
;jpn:◆さっきのおとを　きいただろ？↓
;jpn:　このきんじょに　いんせきが↓
;jpn:　おちたらしいんだ。@KEY()↓
;jpn:◆おれが　いちばんに↓
;jpn:　みにきたんだ！@KEY()↓
;jpn:◆なっ@KEY()↓
;jpn:◆おれが　いちばんに↓
;jpn:　みにきたんだぞ。
@KEYNP()
』

;-------------------------------------------------
;警官４
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP4;
◆Ａ　ｍｅｔｅｏｒｉｔｅ　ｈａｓ　ｌａｎｄｅｄ，@WI(15)　ｔｈｅ　Ｓｈａｒｋｓ　ａｒｅ　ｒｕｎｎｉｎｇ　ｗｉｌｄ　ｉｎ　ｔｏｗｎ，@KEY()↓
◆ｙｏｕ　ｋｉｄｓ　ａｒｅ　ｗａｎｄｅｒｉｎｇ　ａｒｏｕｎｄ，@WI(15)　ａｎｄ，@WI(15)　Ｉ’ｍ　ｈｕｎｇｒｙ．．．@WI(20)　　Ｉ　ｈａｔｅ　ｍｙ　ｊｏｂ！
;jpn:◆こっちにゃ　いんせきが↓
;jpn:　おっこちるし@KEY()↓
;jpn:◆まちでは　シャークだんの↓
;jpn:　れんちゅうが↓
;jpn:　あばれだしてるっていうし@KEY()↓
;jpn:◆おまえらみたいな　コドモが↓
;jpn:　うろうろするし@KEY()↓
;jpn:◆はらは　ペコペコだし‥‥↓
;jpn:　いやんなっちゃうよなあ。
@KEYNP()
』

;-------------------------------------------------
;警官５
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP5;
@CHKFGOTO(FLG_YAZIUMA_POKEY,_YAZIUMA_COP5_B)
◆Ｉｔ’ｓ　ｄａｎｇｅｒｏｕｓ　ｔｏ　ｇｏ　ｔｏ　ｔｈｅ　ｈｉｌｌｔｏｐ．@KEY()↓
◆Ｅｖｅｎ　ｉｆ　Ｉ　ａｄｖｉｓｅ　ｙｏｕ　ｎｏｔ　ｔｏ　ｇｏ，@WI(15)　ｉｔ　ｗｏｎ’ｔ　ｓｔｏｐ　ｙｏｕ，@WI(15)　ｗｉｌｌ　ｉｔ？
;jpn:◆やまのほうは　いんせきがおちて↓
;jpn:　きけんだから@KEY()↓
;jpn:◆‥‥と　ちゅういしたら↓
;jpn:　おまえは　いくのを↓
;jpn:　やめるだろうか。
@KEYNP()
』

_YAZIUMA_COP5_B;	;ポーキーと話した後
◆Ａ@WI(5)ａ@WI(5)ａ@WI(5)ａ@WI(5)ａ@WI(5)ｈ@WI(15)－－ｈ．．．@KEY()↓
◆Ｉｆ　Ｉ　ｙａｗｎ　ｌｉｋｅ　ｔｈｉｓ．．．@WI(20)　ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　Ｉ’ｍ　ｇｏｏｆｉｎｇ　ｏｆｆ．@KEY()↓
◆Ａ@WI(5)ａ@WI(5)ａ@WI(5)ａ@WI(5)ａ@WI(5)ｈ@WI(15)－－ｈ．．．↓
　　．．．ｙｅｓ，@WI(15)　ｉｔ　ｄｏｅｓ．．．
;jpn:◆ふぁ@WI(10)～@WI(10)～@WI(10)～@WI(10)あ@WI(10)‥‥@KEY()↓
;jpn:◆‥‥@WI(20)と　@WI(20)あくびをしたら↓
;jpn:　おれが　さぼってるみたいに@KEY()↓
;jpn:◆ふぁ@WI(10)～@WI(10)～@WI(10)～@WI(10)あ@WI(10)‥‥@KEY()↓
;jpn:◆‥‥みえちゃうな。
@KEYNP()
』


;-------------------------------------------------
;警官６
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP6;
◆Ｈｅｙ，　ｙｏｕ！@WI(15)　　Ｄｏｎ’ｔ　ｙｏｕ　ｋｎｏｗ　ｗｈａｔ　ｔｉｍｅ　ｉｔ　ｉｓ？
;jpn:◆おい　コラ！↓
;jpn:　いま　なんじだとおもってる！
@KEYNP()
』

;-------------------------------------------------
;警官７
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP7;
◆Ｃｌｅａｒ　ｏｕｔ．　Ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｗａｙ．@KEY()↓
◆Ｃｌｅａｒ　ｏｕｔ．　Ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｗａｙ．@KEY()↓
◆Ｃｌｅａｒ　ｏｕｔ．　Ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｗａｙ．@KEY()↓
◆Ｃｌｅａｒ　ｏｕｔ．　Ｏｕｔ　ｇｅｔ　ｏｆ　ｗａｙ　ｍｙ．@WI(15)　　Ｗｈｏｏｐｓ，@WI(15)　ｍｙ　ｍｉｓｔａｋｅ．．．@KEY()↓
◆Ｉ　ｍｅａｎ　”ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｗａｙ！”
;jpn:◆じゃまだ　じゃまだ↓
;jpn:　じゃまだ　じゃまだ↓
;jpn:　じゃまだ　じゃまだ@KEY()↓
;jpn:◆だまじゃ@WI(20)　おっと@WI(20)↓
;jpn:　じゃまだっていってるんだ！
@KEYNP()
』

;-------------------------------------------------
;警官８
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP8;
◆Ｓｈｈ．@WI(15)　　Ｓｈｈ！
;jpn:◆しっしっ！
@KEYNP()
』

;-------------------------------------------------
;警官９
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP9;
◆Ｎｉｃｅ　ｔｉｍｉｎｇ，@WI(15)　@DSP_NAME(PC_NESS)．@WI(20)　　Ｗｉｌｌ　ｙｏｕ　ｄｏ　ｓｏｍｅｔｈｉｎｇ　ａｂｏｕｔ　Ｐｏｋｅｙ？@KEY()↓
◆Ｈｅ’ｓ　ｄｒｉｖｉｎｇ　ｍｅ　ｎｕｔｓ．@WI(20)　　Ａｒｅ　ｙｏｕ　ｔｗｏ　ｆｒｉｅｎｄｓ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆@DSP_STS(STS_PC_NAME_NES)　いいところにきた。@KEY()↓
;jpn:◆ポーキーを↓
;jpn:　なんとかしてくれよ。@KEY()↓
;jpn:◆うるさくて　まいってるんだ。@KEY()↓
;jpn:◆おまえら　ともだちなんだろ？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_YAZIUMA_COP9_YES,_YAZIUMA_COP9_NO)
_YAZIUMA_COP9_NO;
◆Ｙｏｕ’ｒｅ　ｎｏｔ　ｆｒｉｅｎｄｓ，@WI(15)　ｂｕｔ　ａｒｅｎ’ｔ　ｙｏｕ　ｎｅｉｇｈｂｏｒｓ？@KEY()↓
◆Ｃ’ｍｏｎ，@WI(15)　ｈｅｌｐ　ｍｅ　ｏｕｔ　ｈｅｒｅ！
;jpn:◆ともだちじゃなくたって↓
;jpn:　いえが　となりどうしなんだろ？@KEY()↓
;jpn:◆たのむよ！
@KEYNP()
』
_YAZIUMA_COP9_YES;
◆Ａｎｄ　ｙｏｕ　ｌｉｖｅ　ｉｎ　ｔｈｅ　ｈｏｕｓｅ　ｎｅｘｔ　ｔｏ　ｈｉｓ．．．@WI(20)　　Ｉ　ｓｅｅ．．．
;jpn:◆そのうえ↓
;jpn:　いえが　となりどうしだしな。
@KEYNP()
』

;-------------------------------------------------
;警官１０
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_COP10;
◆Ｔｈａｔ　ｍｅｔｅｏｒｉｔｅ　ｌｏｏｋｓ　ｄｉｆｆｅｒｅｎｔ　ｔｈａｎ　ｕｓｕａｌ．@KEY()↓
◆Ｉｔ’ｓ　ｓｔｒａｎｇｅ　ａｎｄ　ｍａｒｖｅｌｏｕｓ．．．@WI(20)ａｓ　ｗｅｌｌ　ａｓ　ｍｙｓｔｅｒｉｏｕｓ．．．@WI(20)ｏ@WI(5)ｏ@WI(5)ｏ@WI(5)ｏ@WI(5)ｏ！．．．
;jpn:◆どうも　あのいんせきは↓
;jpn:　ふつうじゃないな。@KEY()↓
;jpn:◆ストレンジというか↓
;jpn:　マーベラスというか‥‥。@KEY()↓
;jpn:◆‥‥ミステリアスというか。
@KEYNP()
』

;-------------------------------------------------
;ポーキー
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_YAZIUMA_POKEY;
@CHKFGOTO(FLG_YAZIUMA_POKEY,_YAZIUMA_POKEY_LATER)
◆Ｈｅｙ，@WI(15)　@DSP_NAME(PC_NESS)．@KEY()↓
◆Ｄｏｎ’ｔ　ｂｅ　ｒｕｂｂｅｒｎｅｃｋｉｎ’．@WI(20)　　Ｙｏｕ’ｒｅ　ｇｅｔｔｉｎ’　ｉｎ　ｔｈｅ　ｃｏｐｓ，@WI(15)　ｏｏｐｓ．．．@KEY()↓
◆Ｉ　ｍｅａｎ　ｏｆｆｉｃｅｒ’ｓ　ｗａｙ！
;jpn:◆なんだ　@DSP_STS(STS_PC_NAME_NES)じゃないか。@KEY()↓
;jpn:◆やじうまは↓
;jpn:　けいさつのみなさんの↓
;jpn:　じゃまになるんだぞ！
@KEY()↓
@SETF(FLG_YAZIUMA_POKEY)
@SETF(FLG_GENKAN_MAMA_APPEAR)
_YAZIUMA_POKEY_LATER;
◆Ｙｏｕ　ｃａｎ　ｇｏ　ｈｏｍｅ　ｎｏｗ．@KEY()↓
◆Ｔｏｍｏｒｒｏｗ@WI(5)　Ｉ，@WI(15)　Ｐｏｋｅｙ，@WI(15)　ｗｉｌｌ　ｔｅｌｌ　ｙｏｕ　ｍｏｒｅ　ａｂｏｕｔ　ｔｈｅ　ｓｔｒａｎｇｅ　ｍｅｔｅｏｒｉｔｅ．@KEY()↓
◆Ｉ’ｍ　ｆｉｎｅ　ｈｅｒｅ，@WI(15)　ｂｕｔ　ｙｏｕ’ｒｅ　ｂｕｇｇｉｎｇ　ｔｈｅ　ｏｆｆｉｃｅｒｓ！
;jpn:◆おまえ　もう↓
;jpn:　うちにかえれよ。@KEY()↓
;jpn:◆なぞのいんせきのことなら↓
;jpn:　このポーキーさまが　あした↓
;jpn:　くわしく　おしえてやるからさ。@KEY()↓
;jpn:◆おれはいいけど↓
;jpn:　おまえは　じゃまになってるんだ！
@KEYNP()
』
;-------------------------------------------------
;ピッキー
;FLG_YAZIUMA_DISAPPEAR/offで出現
MSG_RUSUBAN_PICKEY;
@CHKFGOTO(FLG_YAZIUMA_POKEY,_RUSUBAN_PICKEY_LATER)
@CHKFGOTO(FLG_TEMP_1,_RUSUBAN_PICKEY_MAIN)
◆Ｏｈ，@WI(15)　ｈｉ．
;jpn:◆あ　こんばんわ。
@KEY()↓
_RUSUBAN_PICKEY_MAIN;
◆Ｐｏｋｅｙ，@WI(5)　ｍｙ　ｂｒｏｔｈｅｒ　ｒａｎ　ｏｕｔ　ｏｆ　ｈｅｒｅ　ｔｏ　ｃｈａｓｅ　ａｆｔｅｒ　ａ　ｐｏｌｉｃｅ　ｃａｒ．@KEY()↓
◆Ｈｅ　ｓａｉｄ@WI(5)　”Ｐｉｃｋｅｙ，@WI(15)　ｙｏｕ　ｓｈｏｕｌｄ　ｓｔａｙ　ｈｏｍｅ．”@WI(15)　　Ｓｏ　Ｉ’ｍ　ｈｏｍｅ　ｗａｔｃｈｉｎｇ　ｏｕｒ　ｈｏｕｓｅ．@KEY()↓
◆Ｍｏｍ　ａｎｄ　ｄａｄ　ａｒｅｎ’ｔ　ｈｏｍｅ　ｙｅｔ．@WI(20)　　Ｔｈｅｙ　ｗｅｎｔ　ｏｕｔ　ｔｏ　ａｎ　ｅｌｅｇａｎｔ　ｒｅｓｔａｕｒａｎｔ．
;jpn:◆ポーキーにいちゃんなら↓
;jpn:　パトカーのあとをおっかけて↓
;jpn:　とびだしていっちゃったよ。@KEY()↓
;jpn:◆ピッキーは　うちにいろって‥‥@KEY()↓
;jpn:◆ぼくは　るすばん。@KEY()↓
;jpn:◆パパとママは　そとに↓
;jpn:　おいしいものを↓
;jpn:　たべにいってて@KEY()↓
;jpn:◆まだ　かえってこないんだ。
@KEYNP()
@SETF(FLG_TEMP_1)
』
_RUSUBAN_PICKEY_LATER;
◆Ｉ’ｍ　ｓｏ　ｓｌｅｅｐｙ．．．@KEY()↓
◆Ｍｏｍ　ａｎｄ　ｄａｄ　ｈａｖｅｎ’ｔ　ｇｏｔｔｅｎ　ｂａｃｋ　ｆｒｏｍ　ｔｏｗｎ　ｙｅｔ．@KEY()↓
◆Ｐｏｋｅｙ　ｒａｎ　ｏｕｔ，@WI(15)　ａｎｄ　ｈｅ　ｈａｓｎ’ｔ　ｒｅｔｕｒｎｅｄ．@WI(20)　　Ｉ’ｍ　ｔｈｉｎｋｉｎｇ　ａｂｏｕｔ　ｇｏｉｎｇ　ｔｏ　ｂｅｄ．
;jpn:◆あー　ねむい‥‥。@KEY()↓
;jpn:◆パパとママは　まだ↓
;jpn:　まちから　かえってこないし@KEY()↓
;jpn:◆ポーキーにいちゃんは↓
;jpn:　とびだしたっきりだし‥‥@KEY()↓
;jpn:◆もう　ねようかとおもってるんだ。
@KEYNP()
』

;-------------------------------------------------

MSG_INSEKI_STARMAN;松
@BGMSTART(0,BGM_msc6)		;スターマン登場音（ＰＫサンダー）
;@WI(1)
;@SE(SE_se3e_b_pk_thunder3)
;@WI(120)
@MOVE_GOM_CHAR( GOM_STARMAN, ANIM_INSEKI_STARMAN, OBJFX_SHOW_NONE )
@WAITSYS()
;@HIDE_GOM_CHAR( GOM_HIT_CHR, OBJFX_HIDE_NONE )			   ;
;@MOVE_GOM_CHAR( GOM_STARMAN, ANIM_MAPOBJSTILL, OBJFX_SHOW_NONE );星男登場
@WI(30)
@OPEN(1)
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆Ｉｔ’ｓ　ｂｅｅｎ　ａ　ｌｏｎｇ　ｔｉｍｅ，@WI(15)　Ｂｕｚｚ　Ｂｕｚｚ．　@KEY()↓
◆Ｙｏｕ’ｖｅ　ｂｅｅｎ　ｓｕｃｃｅｓｓｆｕｌ　ａｔ　ｆｏｉｌｉｎｇ　Ｍａｓｔｅｒ　Ｇｉｙｇａｓ’　ｐｌａｎｓ．@KEY()↓
◆Ｂｕｔ．．．@WI(20)　　Ｂｕｚｚ　Ｂｕｚｚ，@WI(15)　ｙｏｕ　ｍｕｓｔ　ｎｏｗ　ｓｕｒｒｅｎｄｅｒ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｎｏ　ｌｏｎｇｅｒ　ａ　ｈｅｒｏ，@WI(15)　ｂｕｔ　ｊｕｓｔ　ａ　ｕｓｅｌｅｓｓ　ｉｎｓｅｃｔ．@KEY()↓
◆Ｉ’ｌｌ　ｓｔｏｍｐ　ｙｏｕ　ｈａｒｄ！
;jpn:◆ヒサシブリダナ↓
;jpn:　ブンブーン。@KEY()↓
;jpn:◆ギーグサマノ　ケイカクヲ↓
;jpn:　ジャマスルコトニ　オマエハ↓
;jpn:　ムカシカラ　ネッシンダッタ。@KEY()↓
;jpn:◆シカシ‥‥@WI(60)↓
;jpn:　ブンブーン↓
;jpn:　モウ　アキラメロ。@KEY()↓
;jpn:◆オマエハ　エイユウデハナク↓
;jpn:　タダノ　ムシケラ　ナノダ！@KEY()↓
;jpn:◆タタキツブシテヤル！
@KEY()↓
@CLOSEALL()
@GOSUB(MSG_BATTLE_INSEKI_STARMAN)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI( 1 )
@REMOVE_GOM_CHAR( GOM_STARMAN ,ANIM_BLINK_SUICIDE )	;星男消滅
@WI(60)
@FRESH_GOM_CHAR(GOM_BUN)
@OPEN(1)					;ブンブーンのセリフ
◆Ｗｈｅｗ！．．．@WI(20)　　Ｉ　ｗａｓ　ｔａｋｉｎｇ　ａ　ｂｉｇ　ｃｈａｎｃｅ　ｔｈｅｒｅ．．．@KEY()↓
◆Ｈｅ　ｃａｍｅ　ｆｒｏｍ　１０－ｙｅａｒｓ　ｉｎ　ｔｈｅ　ｆｕｔｕｒｅ　ｔｏ　ｋｉｌｌ　ｍｅ，@WI(15)　ｓｏ　ｗｅ　ｃａｎ’ｔ　ｒｅｌａｘ　ｙｅｔ！@KEY()↓
◆Ｆｒｏｍ　ｎｏｗ　ｏｎ，@WI(15)　ｙｏｕ’ｌｌ　ｂｅ　ｆｉｇｈｔｉｎｇ　ｅｎｅｍｉｅｓ　ｓｅｎｔ　ｂｙ　Ｇｉｙｇａｓ，@KEY()↓
◆ａｓ　ｗｅｌｌ　ａｓ　ｈｕｍａｎｓ　ｗｈｏ　ｔｈｉｎｋ　ｅｖｉｌ　ｔｈｏｕｇｈｔｓ．@KEY()↓
◆Ｔｈｅｙ’ｌｌ　ｄｅｆｉｎｉｔｅｌｙ　ｍａｋｅ　ｔｒｏｕｂｌｅ　ｄｕｒｉｎｇ　ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ！@KEY()↓
◆Ａｎｉｍａｌｓ　ａｒｅ　ａｌｓｏ　ｂｅｃｏｍｉｎｇ　ｖｉｏｌｅｎｔ@KEY()↓
◆ｄｕｅ　ｔｏ　Ｇｉｙｇａｓ’　ｉｎｆｌｕｅｎｃｅ　ｏｖｅｒ　ｔｈｅ　ｅｖｉｌ　ｉｎ　ｔｈｅｉｒ　ｍｉｎｄｓ！@KEY()↓
◆Ｉｔ　ｉｓ　ｔｈｅ　ｔｒｕｔｈ，@WI(15)　ｓｏ　ｌｉｓｔｅｎ！
;jpn:◆ふう‥‥@WI(30)↓
;jpn:　あぶないところじゃった。@KEY()↓
;jpn:◆やつは　わしをけすために↓
;jpn:　１０ねんごのみらいから↓
;jpn:　やってきた　ころしや@KEY()↓
;jpn:◆じゃ！@KEY()↓
;jpn:◆だが　まだ↓
;jpn:　あんしんは　できん。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)よ！↓;ここから
;jpn:　あんたが　たたかうのは@KEY()↓
;jpn:◆ギーグの　おくりこんだ　てきたち↓
;jpn:　ばかりでは　ない。@KEY()↓
;jpn:◆おなじ　ちきゅうのなかの↓
;jpn:　あしきこころの　にんげんたちも@KEY()↓
;jpn:◆あんたの　ぼうけんのたびを↓
;jpn:　ぼうがいするじゃろう。@KEY()↓;ここまで挿入
;jpn:◆どうぶつたちが　こうげきてきに↓
;jpn:　なっているのも　おそらく↓
;jpn:　ギーグのちからが@KEY()↓
;jpn:◆かれらの　あくのこころを↓
;jpn:　しげきしているからに↓
;jpn:　ちがいないの@KEY()↓
;jpn:◆じゃ！
@KEYNP()
@CLOSEALL()
;@CLRF(FLG_SYS_MONSTER_OFF);スターマンを倒すまではモンスターを出さない
』
;-------------------------------------------------

;あなぬけねずみ

MSG_ONET_NHOUSE_MOUSE_MOTHER;
◆（Ｐｌｅａｓｅ　ｔａｋｅ　ｍｙ　ｓｏｎ　ａｌｏｎｇ．@KEY()↓
◆Ｈｅ　ｍａｙ　ｌｏｏｋ　ｌｉｋｅ　ｒｅｇｕｌａｒ，@WI(15)　ｓｍａｌｌ　ｍｏｕｓｅ，@KEY()↓
◆ｂｕｔ　ｈｅ　ｃａｎ　ｌｅａｄ　ｙｏｕ　ｔｏ　ａｎ　ｅｘｉｔ　ｉｆ　ｙｏｕ’ｒｅ　ｌｏｓｔ　ｉｎ　ａ　ｍａｚｅ．）
;jpn:　つれてってください。@KEY()↓
;jpn:◆ただの　こねずみに　みえますが↓
;jpn:　めいろで　みちにまよったとき↓
;jpn:　でぐちまで　あんないしますよ）
@KEY()↓
@CHKFGOTO(FLG_ITEM_ESCAPE_MOUSE,MSG_NHOUSE_MOUSE_MOTHER_ALREADY)
◆（Ｗｉｌｌ　ｙｏｕ　ｔａｋｅ　ｏｎｅ　ｏｆ　ｍｙ　ｓｏｎｓ　ａｌｏｎｇ？）↓
<Ｙｅｓ>　<Ｎｏ>

;jpn:◆（ひとり　つれていきますか？）↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_ONET_NHOUSE_MOUSE_MOTHER_YES,MSG_NHOUSE_MOUSE_MOTHER_NO)

MSG_NHOUSE_MOUSE_MOTHER_NO;
◆（Ｉ　ｃａｎ’ｔ　ａｃｃｅｐｔ　ａｎｙ　ｍｏｎｅｙ．）
;jpn:◆（おかねは　いただきませんよ）
@KEYNP()
@!

_ONET_NHOUSE_MOUSE_MOTHER_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_NHOUSE_MOUSE_MOTHER_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_ESCAPE_MOUSE)
◆（Ｈｅ’ｓ　ａ　ｔｏｕｇｈ　ｂｏｙ．@WI(20)　　Ｙｏｕ　ｃａｎ　ｔｒｅａｔ　ｈｉｍ　ａｓ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｉｔｅｍｓ．）
;jpn:◆（じょうぶなこですから↓
;jpn:　グッズあつかいしてくれて↓
;jpn:　けっこうです）
@KEY()↓
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
@CLOSEALL()
@REMOVE_CHAR(PRSN_ONET_HOUSEJ_B,ANIM_MOUSE_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_ONET_HOUSEJ_B,OBJFX_HIDE_NONE)
@SETF(FLG_ITEM_ESCAPE_MOUSE)
』

MSG_NHOUSE_MOUSE_MOTHER_ALREADY;
@Q_HAVE(PC_ALL,GDS_TOOL_ESCAPE_MOUSE)
@FALSE_GOTO(MSG_NHOUSE_MOUSE_MOTHER_AZUKARI)
◆（Ｏｈ，@WI(15)　ｙｏｕ　ｈａｖｅ　ｈｉｍ　ａｌｒｅａｄｙ．）
;jpn:◆（あら。もう↓
;jpn:　つれてるじゃありませんか）
@KEYNP()
』
MSG_NHOUSE_MOUSE_MOTHER_AZUKARI;
◆（Ｄｉｄｎ’ｔ　ｙｏｕ　ｌｅａｖｅ　ｍｙ　ｓｏｎ　ｗｉｔｈ　ｓｏｍｅｏｎｅ？）
;jpn:◆（あなた↓
;jpn:　うちのこを　だれかに↓
;jpn:　あずけているんじゃなかった？）
@KEYNP()
』

MSG_NHOUSE_MOUSE_MOTHER_GOODSFULL;
◆（Ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｉｔｅｍｓ．@WI(20)　　Ｙｏｕ　ｃａｎ’ｔ　ｔａｋｅ　ｍｙ　ｓｏｎ．）
;jpn:◆（あなたの　にもつは↓
;jpn:　いっぱいなんですね。@KEY()↓
;jpn:◆うちのこは↓
;jpn:　つれていけないみたい）
@KEYNP()
』

MSG_ONET_NHOUSE_MOUSE_CHILD1;
◆（Ｔｒｕｓｔ　ｍｅ　ｏｎ　ｔｈｅ　ｄａｒｋ　ｒｏａｄ．）
;jpn:◆（くらいみちなら↓
;jpn:　まかせとけ！）
@KEYNP()
』

MSG_ONET_NHOUSE_MOUSE_CHILD2;
◆（Ｏ@WI(15)ｏ@WI(10)ｏ@WI(5)ｏ．@WI(20)　　Ｄｏ　Ｉ　ｇｅｔ　ｔｏ　ｃｏｍｅ　ａｌｏｎｇ　ｔｏｏ？）
;jpn:◆（ぼくも　つれていって↓
;jpn:　ほしいよう）
@KEYNP()
』
;-------------------------------------------------

MSG_DSRT_NHOUSE_MOUSE_MOTHER;
◆（Ｐｌｅａｓｅ　ｔａｋｅ　ｍｙ　ｓｏｎ　ａｌｏｎｇ．@KEY()↓
◆Ｈｅ　ｍａｙ　ｌｏｏｋ　ｌｉｋｅ　ａ　ｒｅｇｕｌａｒ，@WI(15)　ｓｍａｌｌ　ｍｏｕｓｅ，@KEY()↓
◆ｂｕｔ　ｈｅ　ｃａｎ　ｌｅａｄ　ｙｏｕ　ｔｏ　ａｎ　ｅｘｉｔ　ｉｆ　ｙｏｕ’ｒｅ　ｌｏｓｔ　ｉｎ　ａ　ｍａｚｅ．）
;jpn:◆（うちのこを↓
;jpn:　つれてってください。@KEY()↓
;jpn:◆ただの　こねずみに　みえますが↓
;jpn:　めいろで　みちにまよったとき↓
;jpn:　でぐちまで　あんないしますよ）
@KEY()↓
@CHKFGOTO(FLG_ITEM_ESCAPE_MOUSE,MSG_NHOUSE_MOUSE_MOTHER_ALREADY)
◆（Ｗｉｌｌ　ｙｏｕ　ｔａｋｅ　ｏｎｅ　ｏｆ　ｍｙ　ｓｏｎｓ　ａｌｏｎｇ？）↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆（ひとり　つれていきますか？）↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_DSRT_NHOUSE_MOUSE_MOTHER_YES,MSG_NHOUSE_MOUSE_MOTHER_NO)
@GOTO(MSG_NHOUSE_MOUSE_MOTHER_NO)

_DSRT_NHOUSE_MOUSE_MOTHER_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_NHOUSE_MOUSE_MOTHER_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_ESCAPE_MOUSE)
◆（Ｈｅ’ｓ　ａ　ｔｏｕｇｈ　ｂｏｙ．　　Ｙｏｕ　ｃａｎ　ｔｒｅａｔ　ｈｉｍ　ａｓ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｉｔｅｍｓ．）
;jpn:◆（じょうぶなこですから↓
;jpn:　グッズあつかいしてくれて↓
;jpn:　けっこうです）
@KEY()↓
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
@CLOSEALL()
@REMOVE_CHAR(PRSN_DEST_MOCHY_1_F,ANIM_MOUSE_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_DEST_MOCHY_1_F,OBJFX_HIDE_NONE)
@SETF(FLG_ITEM_ESCAPE_MOUSE)
』

MSG_WINS_NHOUSE_MOUSE_MOTHER;
◆（Ｐｌｅａｓｅ　ｔａｋｅ　ｍｙ　ｓｏｎ　ａｌｏｎｇ．@KEY()↓
◆Ｈｅ　ｍａｙ　ｌｏｏｋ　ｌｉｋｅ　ａ　ｒｅｇｕｌａｒ，@WI(15)　ｓｍａｌｌ　ｍｏｕｓｅ，@KEY()↓
◆ｂｕｔ　ｈｅ　ｃａｎ　ｌｅａｄ　ｙｏｕ　ｔｏ　ａｎ　ｅｘｉｔ　ｉｆ　ｙｏｕ’ｒｅ　ｌｏｓｔ　ｉｎ　ａ　ｍａｚｅ．）
;jpn:◆（うちのこを↓
;jpn:　つれてってください。@KEY()↓
;jpn:◆ただの　こねずみに　みえますが↓
;jpn:　めいろで　みちにまよったとき↓
;jpn:　でぐちまで　あんないしますよ）
@KEY()↓
@CHKFGOTO(FLG_ITEM_ESCAPE_MOUSE,MSG_NHOUSE_MOUSE_MOTHER_ALREADY)
◆（Ｗｉｌｌ　ｙｏｕ　ｔａｋｅ　ｏｎｅ　ｏｆ　ｍｙ　ｓｏｎｓ　ａｌｏｎｇ？）↓
<Ｙｅｓ>　　<Ｎｏ>
;jpn:◆（ひとり　つれていきますか？）↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_WINS_NHOUSE_MOUSE_MOTHER_YES,MSG_NHOUSE_MOUSE_MOTHER_NO)
@GOTO(MSG_NHOUSE_MOUSE_MOTHER_NO)

_WINS_NHOUSE_MOUSE_MOTHER_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(MSG_NHOUSE_MOUSE_MOTHER_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_ESCAPE_MOUSE)
◆（Ｈｅ’ｓ　ａ　ｔｏｕｇｈ　ｂｏｙ．　@WI(15)　Ｙｏｕ　ｃａｎ　ｔｒｅａｔ　ｈｉｍ　ａｓ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｉｔｅｍｓ．）
;jpn:◆（じょうぶなこですから↓
;jpn:　グッズあつかいしてくれて↓
;jpn:　けっこうです）
@KEY()↓
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
@CLOSEALL()
@REMOVE_CHAR(PRSN_WINS_STONE_8_B,ANIM_MOUSE_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_WINS_STONE_8_B,OBJFX_HIDE_NONE)
@SETF(FLG_ITEM_ESCAPE_MOUSE)
』
;-------------------------------------------------

MSG_ONET_HPTL_ROOM1_A;
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｏｎｅｔｔ　Ｈｏｓｐｉｔａｌ．@WI(20)　　Ｉ　ｒｕｎ　ｔｈｅ　ｐｌａｃｅ．
;jpn:◆わたしの　けいえいする↓
;jpn:　この　オネット・ホスピタルに↓
;jpn:　ようこそ　おいでくださいました。
@KEY()↓
@CHKFGOTO(FLG_TEMP_1,_ONET_HPTL_ROOM1_A_TMP)
@CHKFGOTO(FLG_ONET_HPTL_A,_ONET_HPTL_ROOM1_A_LATER)
;
_ONET_HPTL_ROOM1_A_TMP;
◆Ａｈ．．．@WI(5)ｇｏｔｃｈａ！！@WI(15)　　Ｓｏｒｒｙ．@WI(20)　　Ｉ’ｍ　ｊｕｓｔ　ａ　ｐａｔｉｅｎｔ　ｈｅｒｅ．
;jpn:◆あ‥‥@WI(15)しんじてるの？↓
;jpn:　ごめんね。@WI(20)ぼく　ただの↓
;jpn:　にゅういんかんじゃ。
@KEYNP()
@SETF(FLG_ONET_HPTL_A)
@SETF(FLG_TEMP_1)
』
_ONET_HPTL_ROOM1_A_LATER;
◆Ｈａｖｅ　Ｉ　ｔｏｌｄ　ｙｏｕ　ｔｈｉｓ　ｊｏｋｅ　ａｌｒｅａｄｙ？@WI(15)　　Ｈａ，@WI(10)　ｈａ，@WI(5)　ｈａ．
;jpn:◆‥‥このじょうだん↓
;jpn:　まえに　いったっけね？@WI(20)↓
;jpn:　ごめん　ごめん。
@KEYNP()
』

MSG_ONET_HPTL_ROOM2_A;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_HPTL_ROOM2_A_END)
◆Ｉ　ｗａｓ　ＳＭＡＡＡＡＡＳＨ@WI(10)ＥＤ　ｂｙ　ａ　ｍｏｕｓｅ．
;jpn:◆わたし　ネズミに@WI(30)↓
;jpn:　「ＳＭＡＡＡＡＳＨ！！」って↓
;jpn:　されちゃったの。
@KEYNP()
』
_ONET_HPTL_ROOM2_A_END;
◆Ｍｙ　ＳＭＡＡＡＡＡＳＨ　ｗｏｕｎｄ　ｗｉｌｌ　ｓｏｏｎ　ｈｅａｌ．
;jpn:◆ネズミに@WI(30)↓
;jpn:　「ＳＭＡＡＡＡＳＨ！！」って↓
;jpn:　されちゃったところも@KEY()↓
;jpn:◆もうすぐ　なおるのよ。
@KEYNP()
』

MSG_ONET_HPTL_ROOM2_B;
@CHKFGOTO(FLG_TEMP_1,_ONET_HPTL_ROOM2_B_TMP)
@CHKFGOTO(FLG_ONET_HPTL_B,_ONET_HPTL_ROOM2_B_LATER)
_ONET_HPTL_ROOM2_B_TMP;
◆Ｗｈａｔ？@WI(20)　　Ｙｏｕ’ｒｅ　ｈｅｒｅ　ｔｏ　ｖｉｓｉｔ　ｍｙ　ｄａｕｇｈｔｅｒ？@KEY()↓
◆Ｓｏ　ｙｏｕ’ｒｅ　ｔｈｅ　ｏｎｅ　ｗｈｏ　ｃａｌｌｓ　ｈｅｒ　ｉｎ　ｔｈｅ　ｍｉｄｄｌｅ　ｏｆ　ｔｈｅ　ｎｉｇｈｔ　ａｎｄ　ｔａｌｋｓ　ｆｏｒ　ｈｏｕｒｓ！@KEY()↓
◆．．．ｏｈ，@WI(15)　ｉｔ’ｓ　ｎｏｔ　ｙｏｕ．@WI(20)　　Ｔｈｅｎ　ｗｈｙ　ｄｉｄ　ｙｏｕ　ｃｏｍｅ　ｔｏ　ｔｈｉｓ　ｒｏｏｍ？
;jpn:◆え？@WI(10)　うちのコのおみまい？@WI(20)↓
;jpn:　あなたね　よなかに↓
;jpn:　うちの　むすめにでんわしてきて@KEY()↓
;jpn:◆ながながと　しゃべってるのは！@WI(30)↓
;jpn:　‥‥あ　ちがうの。@KEY()↓
;jpn:◆じゃあ　なんでこのへやに↓
;jpn:　はいってきたの？！
@KEYNP()
@SETF(FLG_ONET_HPTL_B)
@SETF(FLG_TEMP_1)
』
_ONET_HPTL_ROOM2_B_LATER;
◆Ｉｔ’ｓ　ｙｏｕ　ａｇａｉｎ．
@KEYNP()
;jpn:◆‥‥また　きたのね。@KEYNP()
』
;-------------------------------------------------

MSG_ONET_CHECK_MIZUNO;
◆（Ｔｒｅａｓｕｒｅ　Ｈｕｎｔｅｒ！@WI(20)　　Ｔｈｉｓ　ｉｓ　Ｌｉｅｒ　Ｘ．　Ａｇｅｒａｔｅ’ｓ　ｈｏｕｓｅ！）
@KEYNP()
;jpn:◆（トレジャー・ハンター！@WI(20)↓
;jpn:　ライヤー・ホーランドのいえは↓
;jpn:　ここです！）@KEYNP()
』
;-------------------------------------------------

MSG_ONET_CHECK_STEIN2;
◆（Ｌｏｏｋｓ　ｌｉｋｅ　ｑｕｉｔｅ　ａ　ｐｉｅｃｅ　ｏｆ　ｗｏｒｋ．．．）
@KEYNP()
;jpn:◆なんだか　たいへんな↓
;jpn:　「へいき」らしい。@KEYNP()
』
;-------------------------------------------------
MSG_ONET_CHECK_DONTENTER;
◆Ｄｏ　Ｎｏｔ　Ｅｎｔｅｒ．@KEYNP()
;jpn:◆たちいりきんし@KEYNP()
』
;-------------------------------------------------
MSG_ONET_G;
◆Ｉ　ｈｅａｒｄ　ｔｈｅｒｅ’ｓ　ａ　ｇｕｙ　ｗｈｏ　ｓｔｏｐｓ　ｔｏ　ｒｅａｄ　ｅａｃｈ　ｂｕｌｌｅｔｉｎ　ｂｏａｒｄ　ｈｅ　ｅｎｃｏｕｎｔｅｒｓ．@KEY()↓
◆Ｔｈｅｎ　ｈｅ　ｓａｙｓ，@WI(15)　”ｃｈｅｃｋ－ａ－ｒｏｏｎｙ！”@WI(20)　　Ｉｓ　ｔｈａｔ　ｙｏｕ？
;jpn:◆カンバンを　みつけるたびに↓
;jpn:　たちどまって　よむひとが↓
;jpn:　いるらしいわね。@KEY()↓
;jpn:◆チェーーック！@WI(20)　とか↓
;jpn:　いいながら‥‥。@KEY()↓
;jpn:◆もしかして@WI(15)　それ↓
;jpn:　あなたのことかしら？
@KEYNP()
』
;◆Ｔｈｉｓ　ｒｏａｄ　ｌｅａｄｓ　ｔｏ　Ｓｈｅｌｉｎ．　
;	．．．ｄｏｅｓ　ｉｔ　ｓａｙ　ｓｏ？　
;	<ＹＥＳ>　<ＮＯ>　
;◆このみち　@WI(30)シーリンに　@WI(30)つづく。↓
;　@WI(40)‥‥って　かいてあるんでしょ？↓
;　　<はい>　　<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_ONET_G_YES,_ONET_G_NO)
;_ONET_G_NO;
;◆Ｃｏｕｌｄ　ｙｏｕ　ｒｅａｄ　ｉｔ　ＯＫ？　
;◆ちゃんと　よめたね。@KEYNP()
;』
;_ONET_G_YES;
;◆Ｄｏｎ’ｔ　ｃｏｎｆｕｓｅ　ｙｏｕｒ　ｐ’ｓ　ａｎｄ　ｑ’ｓ．　
;	Ａｌｓｏ，　ｄｏｎ’ｔ　ｍｉｘ　ｕｐ　ｄ　ａｎｄ　ｂ．　
;　　Ｉｔ’ｓ　ｅａｓｙ　ｔｏ　ｍａｋｅ　
;　ｍｉｓｔａｋｅｓ　ｗｈｅｎ　ｒｅａｄｉｎｇ．　
;◆「ツ」と「シ」‥‥それから↓
;　‥‥「ソ」と「リ」は↓
;　よみまちがえない　ようにね。@KEYNP()
;』
;
;（上記の女の子と話す位置で以下の男が画面内に入る）
MSG_ONET_H;
◆Ｏｈ，@WI(15)　ｏｈ．．．@WI(20)　　Ｔｈｅ　ｒｏａｄ’ｓ　ｃｌｏｓｅｄ　ａｇａｉｎ．@KEY()↓
◆Ｉｔ’ｓ　Ｏｎｅｔｔ’ｓ　ｃｌａｉｍ　ｔｏ　ｆａｍｅ！
;jpn:◆あ～あ‥‥↓
;jpn:　またやってるよ。@KEY()↓
;jpn:◆どうにかならんもんかね↓
;jpn:　オネットめいぶつの↓
;jpn:　どうろふうさ！！
@KEYNP()
』
;-------------------------------------------------

MSG_CHECK_FUDOUSAN_SHELF;
◆Ｙｏｕ’ｖｅ　ｆｏｕｎｄ　ｔｈｅ　ｏｌｄ　ｍａｇａｚｉｎｅ．@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｒｅａｄ　ｉｔ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆ふるいざっしを　みつけた。@WI(20)↓
;jpn:　よみますか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_CHECK_FUDOUSAN_SHELF_YES,_CHECK_FUDOUSAN_SHELF_NO)
_CHECK_FUDOUSAN_SHELF_NO;（いいえの場合）
◆Ｇｏｏｄ．@WI(20)　　Ｔｈａｔ　ｍａｙ　ｂｅ　ｔｈｅ　ｂｅｓｔ　ｃｈｏｉｃｅ．
;jpn:◆そうですね。@WI(20)↓
;jpn:　それがいいかも　しれませんね。
@KEYNP()
』

_CHECK_FUDOUSAN_SHELF_YES;（はいの場合）
;jpn:◆「わが　ひみつの　しょうがい」↓
;jpn:　だい３しょう。↓
@KEY()↓
◆”Ｍｙ　Ｓｅｃｒｅｔ　Ｌｉｆｅ，@WI(15)　ｃｈａｐｔｅｒ　ｔｈｒｅｅ．”@WI(20)　（Ｓｔｏｒｙ　ｆｒｏｍ　ｔｈｅ　ｐｒｅｖｉｏｕｓ　ｃｈａｐｔｅｒ．）@KEY()↓
◆Ｉ　ｗａｓ　ｎｅｉｔｈｅｒ　ａ　ｍｕｒｄｅｒ　ｓｕｓｐｅｃｔ，@KEY()↓
◆ｎｏｒ　ａ　ｔａｒｇｅｔ　ｆｏｒ　ａｎ　ｉｎｔｅｒｎａｔｉｏｎａｌ　ｓｐｙ　ｏｒｇａｎｉｚａｔｉｏｎ．@KEY()↓
◆Ｂｕｔ　Ｉ　ｄｒｏｖｅ　ａ　ｃａｒ　ｄｏｗｎ　ｔｈｅ　Ｊｅｒｓｅｙ　Ｔｕｒｎｐｉｋｅ　ａｔ　８０　ｍｐｈ．@KEY()↓
◆．．．Ａ　ｐｏｌｉｃｅ　ｏｆｆｉｃｅｒ　ｐｕｌｌｅｄ　ｍｅ　ｏｖｅｒ　ａｎｄ　ａｓｋｅｄ　ｆｏｒ　ｍｙ　ｄｒｉｖｅｒ’ｓ　ｌｉｃｅｎｓｅ．@KEY()↓
◆Ｈｅ　ｓａｉｄ　Ｉ　ｗａｓ　ｇｏｉｎｇ　２０　ｍｐｈ　ｏｖｅｒ　ｔｈｅ　ｓｐｅｅｄ　ｌｉｍｉｔ．@KEY()↓
◆Ｉ　ｉｎｓｔａｎｔｌｙ　ｐｏｉｎｔｅｄ　ｔｏ　ｍｙ　ｗｉｆｅ　ａｎｄ　ｓａｉｄ　”Ｉ’ｍ　ｉｎ　ａ　ｈｕｒｒｙ，@WI(15)　ｍｙ　ｗｉｆｅ　ｉｓ　ｉｎ　ｌａｂｏｒ．”@KEY()↓
◆Ｆｏｒｔｕｎａｔｅｌｙ，@WI(15)　ｍｙ　ｗｉｆｅ　ａｃｔｕａｌｌｙ　ｈａｄ　ａ　ｂｉｇ　ｓｔｏｍａｃｈ．@KEY()↓
◆Ｉ　ｈｏｐｅｄ　ｈｅ’ｄ　ｌｅｔ　ｍｅ　ｇｏ　ｗｉｔｈ　ｔｈｉｓ　ｅｘｃｕｓｅ．@KEY()↓
◆”Ｏｈ，@WI(15)　ｓｉｎｃｅ　ｉｔ’ｓ　ａｎ　ｅｍｅｒｇｅｎｃｙ．@KEY()↓
◆Ｉ’ｌｌ　ｌｅａｄ　ｙｏｕ　ｔｏ　ｔｈｅ　ｈｏｓｐｉｔａｌ　ｗｉｔｈ　ｍｙ　ｐｏｌｉｃｅ　ｃａｒ，”@WI(15)　ｈｅ　ｓａｉｄ．@KEY()↓
◆”Ｎｏ，@WI(15)　ｉｔ’ｓ　ｎｏｔ　ｎｅｃｅｓｓａｒｙ．”@WI(20)　”Ｗｈｙ　ｎｏｔ？”@WI(15)　ａｓｋｅｄ　ｔｈｅ　ｏｆｆｉｃｅｒ．@KEY()↓
◆”Ｕｈ．．．@WI(15)ｗｅｌｌ．．．”@WI(30)　”Ｌｅｔ’ｓ　ｇｅｔ　ｇｏｉｎｇ，”@WI(15)　ｓａｉｄ　ｔｈｅ　ｏｆｆｉｃｅｒ．．．@KEY()↓
◆”Ｎｏ，@WI(15)　ｎｏ！@WI(20)　　Ｗｅ　ｃａｎ’ｔ！@WI(30)　　Ｔｈｉｓ　ｂａｂｙ　ｉｓ　ａ　ｄｅｍｏｎ　ｃｈｉｌｄ！”
;jpn:◆（ぜんごうまでの　あらすじ）↓
;jpn:　さつじんじけんの　ようぎしゃ↓
;jpn:　でもなく@KEY()↓
;jpn:◆こくさいスパイそしきに↓
;jpn:　いのちを　ねらわれている↓
;jpn:　わけでもない　わたしは@KEY()↓
;jpn:◆こうしゅうかいどうを↓
;jpn:　じそく８０キロで　はしっていた。@KEY()↓
;jpn:◆‥‥パトカーから　おりてきた↓
;jpn:　けいかんは　めんきょしょうの↓
;jpn:　ていじを　もとめ@KEY()↓
;jpn:◆わたしの　はしっていた　そくどが↓
;jpn:　２０キロの　スピードいはんで↓
;jpn:　あることを　つげた。@KEY()↓
;jpn:◆わたしは　とっさに↓
;jpn:　じょしゅせきの　つまを↓
;jpn:　さして　いった。@KEY()↓
;jpn:◆「か　かないが　きゅうに↓
;jpn:　さんけづきまして‥‥↓
;jpn:　いそいでいるんです」@KEY()↓
;jpn:◆たしかに　つまのはらは↓
;jpn:　でていた。@KEY()↓
;jpn:◆これで　みのがしてくれるかも↓
;jpn:　しれない。@KEY()↓
;jpn:◆「そうですか　‥‥それは↓
;jpn:　おこまりでしょう。@KEY()↓
;jpn:◆パトカーで　せんどうします」@KEY()↓
;jpn:◆「いえ　けっこうです。↓
;jpn:　いけません」@KEY()↓
;jpn:◆「どうして？」けいかんは　いう。@KEY()↓
;jpn:◆「‥‥そ　それは‥‥」@KEY()↓
;jpn:◆「じゃ　いきましょう」↓
;jpn:　「だめです！　うまれてくる↓
;jpn:　こどもは‥‥@KEY()↓
;jpn:◆オニのこ　なんです！」
@KEYNP()
』
;-------------------------------------------------
