;-------------------------------------
;@Habitat:Ｇデッド谷／谷の小屋／監視室
;@Person:鉄格子越しのポーラ
;@Figure:ドア
;@AppearanceKey:MSG_POLA_GRFD/off
;@ActionScript:◆正面向いて固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POLA
MSG_GRFD_POLA;
;ポーラ
;幼いころから、「ふしぎなちからを持つ少女」として、ツーソンの
;まちでは有名。幼稚園を経営する両親の手伝いをしているが、「ＮＥＳ」
;に助けられて後、共に冒険の旅に出る。
@CHKFGOTO(FLG_WIN_CARPAINTER,_GRFD_POLA_LATER)
@CHKFGOTO(FLG_ITEM_FRANKLINBADGE,_GRFD_POLA_1)
@CHKFGOTO(FLG_TEMP_9,_GRFD_POLA_TMP)
◆．．．Ｗｈｏ？．．．@KEY()↓
◆．．．Ａｒｅ　ｙｏｕ　@DSP_NAME(PC_NESS)？@KEY()↓

◆@DSP_NAME(PC_NESS)！　　Ｉ’ｍ　ｓｏ　ｇｌａｄ　ｉｔ’ｓ　ｙｏｕ．@KEY()↓
◆Ｉ　ｈａｄ　ａ　ｄｒｅａｍ　ｔｈａｔ　ａ　ｂｏｙ　ｎａｍｅｄ　@DSP_NAME(PC_NESS)　ｗａｓ　ｍｙ　ｄｅｓｔｉｎｙ．@KEY()↓
◆Ｉ　ｋｎｏｗ　ｉｔ’ｓ　ｈａｒｄ　ｔｏ　ｂｅｌｉｅｖｅ．
@KEY()↓
;jpn:◆‥@WI(20)‥@WI(20)だれ？@KEY()↓
;jpn:◆‥@WI(20)‥@WI(20)@DSP_STS(STS_PC_NAME_NES)じゃない？@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)ね！@WI(30)↓
;jpn:　ああ　よかった。↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)というなの　ひとが@KEY()↓
;jpn:◆わたしと　うんめいを↓
;jpn:　ともにするって‥‥@WI(30)そんなゆめを↓
;jpn:　たしかに　みたの。@KEY()↓
_GRFD_POLA_TMP;
◆Ｔｈａｎｋ　ｙｏｕ．@WI(15)　　Ｉ　ｋｎｅｗ　ｙｏｕ　ｗｏｕｌｄ　ｒｅｓｃｕｅ　ｍｅ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｄｉｄｎ’ｔ　ｃｏｍｅ，@WI(15)　Ｉ　ｗｏｕｌｄ　ｈａｖｅ　ｈａｄ　ｔｏ　ｔｒｙ　ｔｏ　ｂｕｓｔ　ｏｕｔ　ｏｆ　ｈｅｒｅ．
@KEY()↓
;jpn:◆ありがとう‥‥@WI(20)↓
;jpn:　やっぱり↓
;jpn:　たすけにきてくれたのね。@KEY()↓
;jpn:◆あなたが　きてくれなかったら@WI(20)↓
;jpn:　わたし‥‥@WI(60)↓
;jpn:　なきだしちゃうところだった。@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
◆Ｙｏｕ　ｃａｎ’ｔ　ｏｐｅｎ　ｔｈｅ　ｄｏｏｒ．@KEY()↓
◆Ｙｏｕ’ｌｌ　ｈａｖｅ　ｔｏ　ｇｅｔ　ｔｈｅ　ｋｅｙ　ｆｒｏｍ　Ｃａｒｐａｉｎｔｅｒ．　　Ｈｅ’ｓ　ｇｏｔ　ｉｔ　ｈｉｄｄｅｎ　ａｗａｙ．@KEY()↓
◆Ｉ　ｈｅａｒｄ　Ｃａｒｐａｉｎｔｅｒ　ｃａｎ　ｃｏｎｔｒｏｌ　ｌｉｇｈｔｎｉｎｇ．@KEY()↓
◆Ｉｎ　ｔｈａｔ　ｃａｓｅ，@WI(15)　ｙｏｕ　ｓｈｏｕｌｄ　ｗｅａｒ　ｔｈｉｓ　@DSP_GOODS(GDS_HAVE_FRANKLIN_BADGE)，　ｏｋａｙ？
;◆ここのカギをもった↓;こちらに変更したいけど複雑
;　わるいひとが↓
;　さっき　あわててでていったわ。@KEY()↓
;◆まだ　そのへんに↓
;　いるかもしれない。@WI(20)↓
;　きをつけて！@KEYNP()
;』
;jpn:◆ここのカギは↓
;jpn:　いまの　わたしたちじゃ↓
;jpn:　あけられないわ。@KEY()↓
;jpn:◆カーペインターが↓
;jpn:　かくしもっているカギを↓
;jpn:　とってこないと‥‥。@KEY()↓
;jpn:◆でも　カーペインターは↓
;jpn:　カミナリを　あやつるらしいの。@KEY()↓
;jpn:◆このフランクリンバッジを↓
;jpn:　つけていくと　いいわ。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_GRFD_POLA_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_HAVE_FRANKLIN_BADGE)
@GOSUB(MSG_SUB_GETGOODS_S)
@KEY()↓
@SETF(FLG_ITEM_FRANKLINBADGE)
@SETF(FLG_GRFD_POKEY_APPEAR)
@CLRF(FLG_ONET_POLA_TELEPATHY);ポーラに会ったらテレパシーは聞けない
@CLRF(FLG_TWSN_POLA_TELEPATHY)
◆Ｉ’ｌｌ　ｗａｉｔ　ｈｅｒｅ　ｕｎｔｉｌ　ｙｏｕ　ｒｅｔｕｒｎ．@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ｈｅｒｅ　ａｎｄ　ｇｅｔ　ｍｅ　ｏｕｔ　ｏｎｃｅ　ｙｏｕ　ｄｅｆｅａｔ　Ｃａｒｐａｉｎｔｅｒ．@KEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｒｙ　ａｂｏｕｔ　ｍｅ，　ｊｕｓｔ　ｋｉｃｋ　ｂｕｔｔ　ｌｉｋｅ　Ｉ　ｋｎｏｗ　ｙｏｕ　ｃａｎ！
@KEYNP()
;jpn:◆わたし　ここでまってるから@KEY()↓
;jpn:◆きっと　あいつをたおして↓
;jpn:　むかえにきてね。@KEY()↓
;jpn:◆わたし　いつまでだって↓
;jpn:　まっていられるわ。@KEY()↓
;jpn:◆あなたのちから↓
;jpn:　しんじているもの。@KEY()↓
;jpn:◆しんぱいしないで↓
;jpn:　がんばってね。@KEYNP()
@SETF( FLG_SYS_MONSTER_OFF )	;モンスター出現禁止
@FUNC(5)			;マップ上での全滅禁止
』

_GRFD_POLA_ITEMFULL;
@SE(SE_se05_undo)
◆Ｗｈａｔ－－@WI(15)ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｆｒｉｅｄ　ｂｙ　ｌｉｇｈｔｎｉｎｇ？@KEY()↓
◆Ｇｅｔ　ｒｉｄ　ｏｆ　ｓｏｍｅｔｈｉｎｇ　ｓｏ　Ｉ　ｃａｎ　ｇｉｖｅ　ｙｏｕ　ｔｈｅ　@DSP_GOODS(GDS_HAVE_FRANKLIN_BADGE)．
@KEYNP()↓
;jpn:◆もちものが　いっぱいで↓
;jpn:　「フランクリンバッジ」を↓
;jpn:　もてないのね。@KEY()↓
;jpn:◆なにか　うるか　つかうかして↓
;jpn:　もちものを　へらしてくると↓
;jpn:　いいとおもう。@KEYNP()
@SETF(FLG_TEMP_9)
』

_GRFD_POLA_1;
◆Ｉｆ　ｙｏｕ　ｄｉｄｎ’ｔ　ｃｏｍｅ，@WI(15)　Ｉ　ｗｏｕｌｄ　ｈａｖｅ　ｈａｄ　ｔｏ　ｔｒｙ　ｔｏ　ｂｕｓｔ　ｏｕｔ　ｏｆ　ｈｅｒｅ．@KEY()↓
;jpn:◆あなたが　きてくれなかったら@WI(20)↓
;jpn:　わたし‥‥@WI(60)↓
;jpn:　なきだしちゃうところだった。@KEY()↓
;jpn:◆‥‥‥。@KEYNP()
;
;◆Ｔｈｅｒｅ　ｗａｓ　ａ　ｂａｄ　ｌｏｏｋｉｎｇ　ｐｅｒｓｏｎ
;　　ｒｕｓｈｉｎｇ　ｏｕｔ　ｏｆ　ｈｅｒｅ　ｗｉｔｈ　
;　　ａ　ｋｅｙ　ｏｆ　ｔｈｉｓ　ｒｏｏｍ．
;◆Ｈｅ　ｍｉｇｈｔ　ｂｅ　ｓｔｉｌｌ　ａｒｏｕｎｄ　ｈｅｒｅ．
;　　Ｂｅ　ｃａｒｅｆｕｌ！

;◆ここのカギをもった↓
;　わるいひとが↓
;　さっき　あわててでていったわ。@KEY()↓
;◆まだ　そのへんに↓
;　いるかもしれない。@WI(20)↓
;　きをつけて！@KEYNP()
』

_GRFD_POLA_LATER;
;◆@DSP_STS(STS_PC_NAME_NES)！
;
;◆@DSP_STS(STS_PC_NAME_NES)↓
;jpn:　カギを　とってきてくれたのね！@KEY()↓
_GRFD_POLA_LATER_TMP;
◆@DSP_NAME(PC_NESS)！　　Ｙｏｕ　ｇｏｔ　ｔｈｅ　ｋｅｙ！@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｈｕｒｔ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆けがは　ない？@WI(20)↓
;jpn:　だいじょうぶ？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_GRFD_POLA_LATER_YES,_GRFD_POLA_LATER_NO)

_GRFD_POLA_LATER_NO;
_GRFD_POLA_LATER_YES;
◆Ｉ’ｍ　ｓｏｒｒｙ　ｆｏｒ　ａｌｌ　ｔｈｅ　ｔｒｏｕｂｌｅ　Ｉ’ｖｅ　ｃａｕｓｅｄ　ｙｏｕ．
@KEYNP()
;jpn:◆わたしのために‥‥↓
;jpn:　ごめんなさい。@KEYNP()
』
;◆Ｇｒｅａｔ！
;◆Ｉ’ｖｅ　ｂｅｅｎ　ｂｅｌｉｅｖｉｎｇ　ｙｏｕ．
;◆Ｓｏ，　ｌｅｔ　ｍｅ　ｏｕｔ　ｏｆ　ｈｅｒｅ　ｑｕｉｃｋｌｙ！
;◆やったー！@WI(15)↓
;　わたし　しんじてたわ。@WI(15)↓
;　はやくここから　だして！@KEYNP()
;』


;@Habitat:Ｇデッド谷／谷の小屋／牢や
;@Person:ポーラ
;@Figure:ポーラ
;@AppearanceKey:MSG_POLA_GRFD/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POLA_LATER_USEKEY
;MSG_GRFD_POLA_LATER_USEKEY;
;牢内のポーラ
;◆Ｉ’ｍ　ｓｏ　ｈａｐｐｙ！
;◆Ｙｏｕ’ｒｅ　ｓｏｍｅｏｎｅ　ａｓ　Ｉ　ｅｘｐｅｃｔｅｄ．
;◆Ｌｅｔ’ｓ　ｒｅｔｕｒｎ　ｔｏ　Ｔｗｏｓｏｎ．
;◆うれしいっ！@WI(15)↓
;　わたしの　おもったとおりの↓
;　ひとだった。@KEY()↓
;◆さぁ　ツーソンに　もどりましょ。@KEY()
;@SETF(FLG_POLA_GRFD)
;@SE(SE_se10_present_open)
;@GOSUB(MSG_ADD_PAULA)
;』


；----------------------------------------

;@Habitat:Ｇデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー
;@Figure:ポーキー
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ネスに近寄ってセリフ発行
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_POKEY

;@Habitat:Ｇデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー子分Ａ
;@Figure:HH教信者
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ポーキーの合図でネスにケンカ売る
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0

;@Habitat:Ｇデッド谷／フィールド／谷の小屋の前
;@Person:ポーキー子分Ｂ
;@Figure:HH教信者
;@AppearanceKey:FLG_GRFD_POKEY_APPEAR/on
;@ActionScript:◆ポーキーの合図でネスにケンカ売る
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0

;-------------------------------------------------

MSG_GRFD_SIGNPOST_A;
;ポーキーがセットした偽標識
;フランクリンバッジを手に入れた後は消滅する
◆（Ｃｒｏｓｓ　ｂｒｉｄｇｅ　ｔｏ　Ｈａｐｐｙ－Ｈａｐｐｙ　Ｖｉｌｌａｇｅ）
@KEYNP()
;jpn:◆（ハッピーハッピーむらへ↓
;jpn:　おいでのかたは　このはしを↓
;jpn:　わたってください）@KEYNP()

;◆Ｌｅｆｔ
;　　Ｓｈｏｒｔ　ｃｕｔ．
;◆（Ｉｔ　ａｐｐｅａｒｓ　ｔｏ　ｂｅ
;　　ｖｅｒｙ　ｂａｄ　ｈａｎｄ　ｗｒｉｔｉｎｇ．）

;◆ひだり↓
;　ちかみちでございませ。@KEY()↓
;◆（なにやら　ずいぶん↓
;　　ヘタクソな　もじだ）@KEYNP()
』

;@Habitat:Ｇデッド谷／リリパットステップのダンジョン／大広間
;@Person:ジャイアントステップのボス
;@Figure:ガーディアン
;@AppearanceKey:FLG_WIN_LLPT_BOSS/off
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GRFD_LLPT_BOSS
MSG_GRFD_LLPT_BOSS;
@CHKFGOTO(FLG_WIN_LLPT_BOSS,MSG_SYS_HANASU_NG)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(MSG_GLOBAL_BOSS_NG);ネス死んでたらダメ
@BGMSTART(0,BGM_msc24);ボスのセリフ曲
◆Ｙｏｕ　ｆｉｎａｌｌｙ　ｇｏｔ　ｈｅｒｅ．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ｔｈｅ　ｓｅｃｏｎｄ　”Ｙｏｕｒ　Ｓａｎｃｔｕａｒｙ”　ｌｏｃａｔｉｏｎ．@WI(20)　　Ｂｕｔ　ｉｔ’ｓ　ｍｉｎｅ　ｎｏｗ．@KEY()↓
◆Ｔａｋｅ　ｉｔ　ｆｒｏｍ　ｍｅ，@WI(30)　ｉｆ　ｙｏｕ　ｄａｒｅ．．．
;jpn:◆よくきた。@KEY()↓
;jpn:◆ここは　２ばんめの↓
;jpn:「おまえのばしょ」だ。@KEY()↓
;jpn:◆しかし　いまは↓
;jpn:　わたしのばしょだ。@KEY()↓
;jpn:◆うばいかえせばよい。@KEY()↓
;jpn:◆‥‥できるものなら。
@KEY()
@GOSUB(MSG_BATTLE_LLPT_BOSS)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_GRFD_LILIPUT_1_A,OBJFX_HIDE_HSTRIPE)
@WI(120)
@SETF(FLG_WIN_LLPT_BOSS)
』

MSG_GRFD_KINOKO_GIRL;
@GOSUB(MSG_SUB_GRFD_KINOKOGIRL)
@!
;---------------------------------------------------

MSG_GRFD_SHINTO_A;壊れた橋の信者
◆Ｉ　ｗｏｎｄｅｒ　ｗｈｏ　ｍａｄｅ　ｔｈｅ　ｂｒｉｄｇｅ　ｉｍｐａｓｓａｂｌｅ？@KEY()↓
◆Ｗｈｙ　ｗｏｕｌｄ　ｓｏｍｅｏｎｅ　ｄｏ　ｔｈｉｓ？@WI(15)　　Ｃｒｕｄ．．．
@KEYNP()
;jpn:◆だれかが　はしを↓
;jpn:　とおれなくしちまったんだよぅ。@KEY()↓
;jpn:◆どーして　こんなことを↓
;jpn:　するんだろう‥‥まったく。@KEYNP()
』
;---------------------------------------------------

MSG_GRFD_SYSMSG_GUTS;＄β
◆（Ｉ’ｍ　ｎｏｔ　ａｎ　ｅｎｅｍｙ．@KEY()↓
◆Ｉ’ｍ　ｊｕｓｔ　ａ　ｒｅｇｕｌａｒ　ｍｏｌｅ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｋｎｏｗ　ａｂｏｕｔ　ｈｏｗ　ｔｏ　ｓｕｒｖｉｖｅ　ｂａｔｔｌｅｓ．）@KEY()↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆（おれは　てきじゃない。↓
;jpn:　ただの　もぐらさ。@KEY()↓
;jpn:◆「ガッツ」について↓
;jpn:　おれのしってることを↓
;jpn:　ぜんぶ　はなそうか？）@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_GRFD_SYSMSG_GUTS_YES,_GRFD_SYSMSG_GUTS_NO)
_GRFD_SYSMSG_GUTS_NO;
◆（Ｗｅｌｌ，　ｙｏｕ　ｓｅｅｍ　ｔｏ　ｋｎｏｗ　ａ　ｌｏｔ　ａｌｒｅａｄｙ，　ｅｖｅｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｌｏｏｋ　ｌｉｋｅ　ｉｔ．）
@KEYNP()
;jpn:◆（おまえって　いがいと↓
;jpn:　ガッツありそうだもんな）@KEYNP()
』
_GRFD_SYSMSG_GUTS_YES;
◆（Ｙｏｕ　ｍａｙ　ｈａｖｅ　ｎｏｔｉｃｅｄ　ｔｈａｔ，　ｗｈｅｎ　ｙｏｕ　ｈａｖｅ　ｂｅｅｎ　ｂａｄｌｙ　ｈｕｒｔ　ｉｎ　ｂａｔｔｌｅ，@KEY()↓
◆ｙｏｕ　ｍａｙ　ｓｕｒｖｉｖｅ　ａ　ｍｏｒｔａｌ　ａｔｔａｃｋ　ａｎｄ　ｓｔｉｌｌ　ｈａｖｅ　１　ＨＰ．　　Ｉｆ　ｔｈｉｓ　ｈａｓ　ｈａｐｐｅｎｅｄ，@KEY()↓
◆ｉｔ　ｗａｓ　ｂｅｃａｕｓｅ　ｏｆ　ｙｏｕｒ　Ｇｕｔｓ．　　Ｙｏｕｒ　ｓｕｒｖｉｖａｌ　ｍａｙ　ｄｅｐｅｎｄ　ｏｎ　ｙｏｕｒ　Ｇｕｔｓ　ｌｅｖｅｌ．@KEY()↓
◆Ａｌｓｏ，　ｍｏｒｅ　Ｇｕｔｓ　ｈｅｌｐｓ　ｙｏｕ　ｇｅｔ　ｍｏｒｅ　ＳＭＡＡＡＡＡＳＨｉｎｇ　ｈｉｔｓ．@KEY()↓
◆Ｂｅｙｏｎｄ　Ｇｕｔｓ，　ｙｏｕ　ｓｈｏｕｌｄ　ｈａｖｅ　ｎｏｔｉｃｅｄ　ｔｈａｔ　ｉｔ　ｔａｋｅｓ　ｓｏｍｅ　ｔｉｍｅ@KEY()↓
◆ｆｏｒ　ｄａｍａｇｅ　ｔｏ　ｂｅ　ｔａｋｅｎ　ｆｒｏｍ　ｙｏｕ．
◆Ｔｈｉｓ　ｉｓ　ｂｅｃａｕｓｅ　ｏｆ　ｔｈｅ　ｒｏｌｌｉｎｇ　ａｃｔｉｏｎ　ｏｆ　ｙｏｕｒ　ＨＰ　ｍｅｔｅｒ．　　Ｏｏｐｓ！　Ｉ　ｍｅａｎ　ｙｏｕｒ　ｌｉｆｅ．
◆Ｉｆ　ａｎ　ｅｎｅｍｙ　ｄｅａｌｓ　ｍｏｒｔａｌ　ｄａｍａｇｅ　ｔｏ　ｙｏｕ，　ｂｕｔ　ｙｏｕ　ｄｅｆｅａｔ　ａｌｌ　ｅｎｅｍｉｅｓ@KEY()↓
◆ｂｅｆｏｒｅ　ｙｏｕｒ　ｌｉｆｅ　ｉｓ　ｇｏｎｅ，　ｙｏｕ　ｓｕｒｖｉｖｅ．　　Ｔｈｉｓ　ｉｓ　ａｌｌ　Ｉ　ｋｎｏｗ．）
@KEYNP()
;jpn:◆（たたかいのなかで↓
;jpn:　きぜつするほどの↓
;jpn:　ダメージをうけたはずなのに@KEY()↓
;jpn:◆たいりょくが「１」で↓
;jpn:　ふみとどまった　‥‥なんて↓
;jpn:　けいけん　あるかい？@KEY()↓
;jpn:◆もし　あったとしたら↓
;jpn:　それは　おまえの「ガッツ」が↓
;jpn:　すごかったからだよ。@KEY()↓
;jpn:◆どたんばで↓
;jpn:　ふんばりがきくかどうか。↓
;jpn:　それは「ガッツ」しだいってこと。@KEY()↓
;jpn:◆それとね　「ガッツ」が↓
;jpn:　たくさんあるやつは‥‥@KEY()↓
;◆@WI(20)ＳＭＡＡＡＡＡＳＨ！！↓
;jpn:　@WI(30)‥‥が　でやすくなるんだ。@KEY()↓
;jpn:◆しってることは　それだけさ）@KEYNP()
』
;---------------------------------------------------
