;-----------------------------------------------------

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客Ａ
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:DMSG_SUMS_CLUB_A
MSG_SUMS_CLUB_A;
◆Ｄｉｄａｃｔｉｃａｌｌｙ　ｓｐｅａｋｉｎｇ，　ｓｅｍｉｎａｌ　ｅｖｉｄｅｎｃｅ　ｓｅｅｍｓ　ｔｏ　ｅｘｐｌｉｃａｔｅ　ｔｈｅ　ｆａｃｔ　ｔｈａｔ@KEY()↓
◆ｙｏｕｒ　ｒｅｐｕｄｉａｔｉｏｎ　ｏｆ　ｅｎｔｒｏｐｙ　ｓｕｐｐｏｒｔｓ　ｍｙ　ｔｈｅｏｒｙ　ｏｆ　ｓｐａｃｅ－ｔｉｍｅ　ｓｙｎｔｈｅｓｉｓ．@KEY()↓
◆Ｏｆ　ｔｈｉｓ，　Ｉ　ａｍ　ｉｒｒｅｆｕｔａｂｌｙ　ｃｏｎｆｉｄｅｎｔ．
;jpn:◆つまり　いまのせかいでは↓
;jpn:　エントロピーの　ぞうだいっていう↓
;jpn:　ながれに　あらがうことは@KEY()↓
;jpn:◆ぼうちょうする　うちゅうを↓
;jpn:　ひていしつづける　いしが↓
;jpn:　ひょうめいされているってこと‥‥
@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客Ｂ♀
;@Figure:ＯＬＣ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_B
MSG_SUMS_CLUB_B;
◆Ｍｍｍｍｍ．@KEY()↓
◆Ｉ　ｔｈｉｎｋ　ｉｔ’ｓ　ａ　ｖｅｒｙ　ｃｏｍｐｌｉｃａｔｅｄ　ｉｓｓｕｅ．@KEY()↓
;jpn:◆うーん。↓
;jpn:　わたしが　かんがえるに↓
;jpn:　それは　むつかしいもんだいね。@KEY()↓
@WI(60)↓
◆．．．．．．Ｏｈ，　ｓｏｒｒｙ！@KEY()↓
◆Ｉ　ｗａｓ　ｓｌｅｅｐｉｎｇ．．．
@KEYNP()
;jpn:◆‥@WI(30)‥@WI(30)あ@WI(15)　ごめんなさい。@WI(20)↓
;jpn:　ねむってたわ。@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客Ｃ
;@Figure:青年
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_C
MSG_SUMS_CLUB_C;
◆Ｙｏｕ　ｇｕｙｓ　ｃａｎ’ｔ　ｅｎｖｉｓｉｏｎ　ｔｈｅ　ｆｉｎａｌ　ｃｏｌｌａｐｓｅ　ｏｆ　ｃａｐｉｔａｌｉｓｍ？@KEY()↓
◆Ｉｎｃｒｅｄｉｂｌｅ！
@KEYNP()
;jpn:◆えっ　きみたちって↓
;jpn:　しほんしゅぎの↓
;jpn:　さいしゅうイメージを@KEY()↓
;jpn:◆そうぞうすることさえも↓
;jpn:　しないで↓
;jpn:　いきてるわけ？！@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:客Ｄ
;@Figure:おじさんＤ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_D
MSG_SUMS_CLUB_D;
@CHKFGOTO(FLG_SUMS_STOIC_WIFE_DISAPPEAR,_SUMS_CLUB_B_LATER)
◆Ｙｏｕ　ｋｎｏｗ，　Ｉ　ｒｅａｌｌｙ　ｗａｎｔ　ｔｏ　ｅａｔ　ｓｏｍｅ　Ｍａｇｉｃ　ｃａｋｅ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｍｙｓｔｅｒｉｏｕｓ　ｗｏｒｋ　ｏｆ　ａｒｔ．．．@KEY()↓
◆Ｉ　ｃａｎ’ｔ　ｇｅｔ　ｔｈａｔ　ｃａｋｅ　ｏｆｆ　ｍｙ　ｍｉｎｄ．@KEY()↓
◆Ｔｈｅｒｅ’ｓ　ｏｎｌｙ　ｏｎｅ　ｗｏｍａｎ　ｗｈｏ　ｃａｎ　ｍａｋｅ　Ｍａｇｉｃ　ｃａｋｅ．．．@KEY()↓
◆Ｓｈｅ’ｓ　ｈａｎｇｉｎｇ　ｏｕｔ　ｉｎ　ｔｈｉｓ　ｃｌｕｂ．@KEY()↓
◆Ｙｅａｈ，　ｓｈｅ’ｓ　ｏｖｅｒ　ｔｈｅｒｅ　ａｔ　ｔｈｅ　ｅｎｔｒａｎｃｅ．．．@KEY()↓
◆Ａｎｙｗａｙ，　ｔｈｅ　ａｂｓｏｌｕｔｅ　ｉｒｏｎｙ　ａｎｄ　ｓｔｕｄｙ　ｏｆ　ｓｅｌｆ－ｉｄｅｎｔｉｆｉｃａｔｉｏｎ　ｉｓ．．．@KEY()↓
◆Ｂｌａｈ，　ｂｌａｈ，　ｂｌａｈ．．．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈａｔ　ｔｏ　ｄｏ！
@KEYNP()
;jpn:◆ボクはねぇ@WI(20)　キミ↓
;jpn:　あの　げんそうてきで　かんびな↓
;jpn:　げいじゅつひんともいえるところの@KEY()↓
;jpn:◆マジックケーキ‥‥を@WI(20)↓
;jpn:　もういちど　しょくしてみたいと@KEY()↓
;jpn:◆こころから↓
;jpn:　ねがってやまないんだよ。@KEY()↓
;jpn:◆しかし‥‥@KEY()↓
;jpn:◆マジックケーキをつくる↓
;jpn:　せかいで　ゆいいつともいえる↓
;jpn:　じょせいがね‥‥@KEY()↓
;jpn:◆このクラブに　いりびたりで@WI(30)↓
;jpn:　つくろうと　しないんだよ。@KEY()↓
;jpn:◆あの　いりぐちのところに↓
;jpn:　いるんだが‥‥@KEY()↓
;jpn:◆この　ぜったいむじゅんてき↓
;jpn:　じこどういつせいというか↓
;jpn:　‥‥クドクド‥‥@KEY()↓
;jpn:◆こまっちゃうんだよね　ボク。@KEYNP()
@CHKFGOTO(FLG_PU,MSG_END)
@SETF(FLG_SUMS_MASSAGE_APPEAR);この人と女房のセリフ替え用。夕焼けはヤメ
;@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させなくする
』
_SUMS_CLUB_B_LATER;
◆Ｔｈｅ　ｗｏｍａｎ　ｗｈｏ　ｓｅｌｌｓ　ｍａｇｉｃ　ｃａｋｅ@KEY()↓
◆ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｂｅｅｎ　ｒｅｍｏｖｅｄ　ｆｒｏｍ　ｔｈｅ　ｍｅｍｂｅｒｓ　ｌｉｓｔ．
@KEYNP()
;jpn:◆マジックケーキうりの　カノジョ↓
;jpn:　どうやら　ボクらの　メンバーから↓
;jpn:　はずれたようだね。@KEYNP()
』
;◆カリヨンビーチにはねぇ　キミ↓
;　なかなかおもしろい↓
;　マッサージをしてくれる@KEY()↓
;◆ジルって　じょせいが　いてね‥‥@KEY()↓
;◆いいゆめを　みせてくれるらしい。↓
;　いいゆめ‥‥だよ‥‥キミ。↓
;　すてきじゃないか‥‥ねぇ。@KEYNP()
;@CHKFGOTO(FLG_PU,MSG_END)
;@SETF(FLG_SUMS_MASSAGE_APPEAR)
;@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させなくする
;』


;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:オーナー(アーシー)
;@Figure:モヒカン
;@AppearanceKey:0
;@ActionScript:◆
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_OWNER
MSG_SUMS_CLUB_OWNER;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｕｎｄｅｒｓｔａｎｄ　ｗｈａｔ　ｔｈｅ　ｈｅｙ　ｅｖｅｒｙｏｎｅ　ｉｓ　ｔａｌｋｉｎｇ　ａｂｏｕｔ，　ｄｏ　ｙｏｕ？@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｅｉｔｈｅｒ，　ｂｕｔ　Ｉ　ｔｒｙ　ｔｏ　ｂｅ　ｐａｔｉｅｎｔ　ｗｉｔｈ　ｔｈｅ　ｃｕｓｔｏｍｅｒｓ．@KEY()↓
◆Ｔｈｅｙ　ｐａｙ　ｈｉｇｈ　ｐｒｉｃｅｓ　ｊｕｓｔ　ｆｏｒ　ａ　ｇｌａｓｓ　ｏｆ　ｗａｔｅｒ@KEY()↓
◆ａｎｄ　ｔｈｅ　ｃｈａｎｃｅ　ｔｏ　ｈａｖｅ　ｓｅｒｉｏｕｓ，　ｉｎｔｅｌｌｅｃｔｕａｌ　ｄｉｓｃｕｓｓｉｏｎｓ．@KEY()↓
◆Ａｃｔｕａｌｌｙ，　ｉｔ’ｓ　ａｎ　ｅａｓｙ　ｂｕｓｉｎｅｓｓ．@KEY()↓
◆Ｙｏｕ　ｗａｎｔ　ａ　ｄｒｉｎｋ？@KEY()↓
◆Ｗｅ　ｏｎｌｙ　ｓｅｒｖｅ　ｗａｔｅｒ，　ｔｈｏｕｇｈ．．．
@KEYNP()
;jpn:◆きゃくたちが　なにいってるのか↓
;jpn:　わかんないだろ。@WI(20)↓
;jpn:　がまんしてるんだ　おれも。@KEY()↓
;jpn:◆たかいかねはらって↓
;jpn:　みずだけのんで　ペチャクチャと↓
;jpn:　こむずかしいこと　しゃべってさ。@KEY()↓
;jpn:◆でも　いいしょうばいだよ。@WI(20)↓
;jpn:　あんたも　なにか？@WI(10)↓
;jpn:　メニューは　みずだけだけど‥‥。@KEYNP()
』

;@Habitat:サマーズ／クラブストイック／クラブストイック
;@Person:ウェイトレス（ジョシー）
;@Figure:ウェートレスＢ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_CLUB_WAITRESS
MSG_SUMS_CLUB_WAITRESS;
;クラブストイックは、
;表の看板に
;「水あります」と記されている
◆Ｔｈｅ　ｓｈｏｗ？@KEY()↓
◆Ｉｔ’ｓ　ａｌｒｅａｄｙ　ｓｔａｒｔｅｄ．@KEY()↓
◆Ｅｖｅｒｙｏｎｅ　ｓｔａｒｅｓ　ａｔ　ｔｈｅ　ｓｔｏｎｅ　ｏｎ　ｓｔａｇｅ　ａｎｄ　ｐｈｉｌｏｓｏｐｈｉｚｅｓ．@KEY()↓
◆．．．Ｄｏｅｓｎ’ｔ　ｉｔ　ｓｏｕｎｄ　ｓｔｕｐｉｄ？
;jpn:◆ショー？@WI(20)　もうはじまってるわよ。↓
;jpn:　ステージのいしを　みつめて↓
;jpn:　いろいろてつがくするのよ。@KEY()↓
;jpn:◆‥‥バカらしいでしょ。
@CHKFGOTO(FLG_PU,_SUMS_CLUB_WAITRESS_PU)
@KEYNP()
』

_SUMS_CLUB_WAITRESS_PU;
@KEY()↓
◆Ｉｆ　ｙｏｕ　ｊｕｓｔ　ｗａｎｔ　ｗａｔｅｒ，　ｇｏ　ｔｏ　ｔｈｅ　ｄｒｕｇ　ｓｔｏｒｅ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｌｏｔ　ｃｈｅａｐｅｒ　ｔｈｅｒｅ．
@KEYNP()
;jpn:◆みずだけ　ほんとに　ほしいなら↓
;jpn:　ドラッグストアで↓
;jpn:　やすく　うってるわよ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅Ａ／トトの住宅Ａ
;@Person:住人
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_A
MSG_TOTO_HOUSE_A;
◆Ａｃｒｏｓｓ　ｔｈｅ　ｓｅａ，　ｔｈｅｒｅ’ｓ　ａ　ｔｏｗｎ　ｃａｌｌｅｄ　Ｓｃａｒａｂａ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｍｙｓｔｅｒｉｏｕｓ　ｔｏｗｎ．@KEY()↓
◆Ｉｔ’ｓ　ｍｙ　ｄｒｅａｍ　ｔｏｗｎ．
@KEYNP()
;jpn:◆うみのかなたには↓
;jpn:　スカラビという　まちがある。@WI(20)↓
;jpn:　しんぴのまち。あこがれのまち。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅Ｃ／トトの住宅Ｃ
;@Person:街の人Ｂ
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_B
MSG_TOTO_B;
◆Ｉ’ｍ　ａ　ｇｒａｖｅ　ｒｏｂｂｅｒ．@KEY()↓
◆Ｉ　ｗａｓ　ｓｃａｒｅｄ　ｏｆ　ｔｈｅ　ｐｙｒａｍｉｄ　ｉｎ　Ｓｃａｒａｂａ．．．@KEY()↓
◆ｓｏ，　Ｉ　ｄｉｄｎ’ｔ　ｇｏ　ｉｎ．．．@KEY()↓
◆ｂｕｔ　Ｉ　ｔｅｌｌ　ｐｅｏｐｌｅ　ｔｈａｔ　Ｉ　ｓａｗ　ｍｕｍｍｙ－ｔｙｐｅ　ｍｏｎｓｔｅｒｓ　ｗｉｔｈ　ｍｙ　ｖｅｒｙ　ｏｗｎ　ｅｙｅｓ！
@KEYNP()
;jpn:◆わたしは　はかドロボーなんだわ。@WI(20)↓
;jpn:　スカラビのピラミッドは↓
;jpn:　あんまりこわくて‥‥@KEY()↓
;jpn:◆はいれなかったんだわ。↓
;jpn:　だけどね　ミイラのばけもんとか↓
;jpn:　このめでみたのは　じまんでしょ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／トトの住宅Ｄ／トトの住宅Ｄ
;@Person:住人
;@Figure:レゲエ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_D
MSG_TOTO_D;＃
@CHKFGOTO(FLG_SUMS_STOIC_WIFE_DISAPPEAR,_TOTO_D_LATER)
◆Ｄｏ　ｙｏｕ　ｋｎｏｗ　ｔｈｅ　Ｓｔｏｉｃ　Ｃｌｕｂ，　ｉｎ　Ｓｕｍｍｅｒｓ？@KEY()↓
◆Ｙｏｕ　ｎｅｅｄ　ｔｏ　ｃａｌｌ　ａ　ｓｅｃｒｅｔ　ｎｕｍｂｅｒ　ｆｏｒ　ａ　ｒｅｓｅｒｖａｔｉｏｎ　ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｉｎ．@KEY()↓
◆Ｗｈａｔ？@KEY()↓
◆Ｙｅａｈ，　Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　ｔｈｅ　ｓｅｃｒｅｔ　ｎｕｍｂｅｒ．@KEY()↓
◆Ｉ　ｗａｒｎ　ｙｏｕ　ｔｈｏｕｇｈ，　ｉｔ’ｓ　ａ　ｓｔｒａｎｇｅ　ｐｌａｃｅ．．．
@KEYNP()
;jpn:◆サマーズのまちの↓
;jpn:　ストイッククラブってあるだろ。@WI(20)↓
;jpn:　あそこって@KEY()↓
;jpn:◆ひみつの　でんわで↓
;jpn:　よやくしないと　はいれないんだ。@WI(20)↓
;jpn:　え　おれ？@KEY()↓
;jpn:◆おれは　しってるよ。↓
;jpn:　でんわばんごうくらい↓
;jpn:　おしえてやるさ。@KEY()↓
;jpn:◆へんなみせだけどな。@KEYNP()
@SE(SE_se74_my_get)
@SETF(FLG_SYS_PHONE_STOIC)
@FUNC(5)			;毒死配達禁止
』
_TOTO_D_LATER;＆
◆Ｉ　ｔｈｉｎｋ　ｔｈｉｓ　ｉｓ　ａ　ｎｉｃｅ　ｔｏｗｎ．@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ｗｈｅｎ　ｙｏｕ　ｇｒｏｗ　ｕｐ！
@KEYNP()
;jpn:◆おれは　このまちが　すきだなぁ@WI(30)↓
;jpn:　おとなになったら　また↓
;jpn:　このまちに　こいよ　な。@KEYNP()
』

;----------------------------------------
;@Habitat:サマーズ／トトの住宅Ｇ／トトの住宅Ｇ
;@Person:住人
;@Figure:トランペッター
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_G
MSG_TOTO_HOUSE_G;
◆Ｉｆ　ｙｏｕ　ｃｏｍｅ　ｃｌｏｓｅｒ，　Ｉ’ｌｌ　ｐｌａｙ　ｔｈｅ　ｔｒｕｍｐｅｔ！@KEY()↓
◆．．．．．@KEY()↓
◆Ｕｈｈｈ，　Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｈｏｗ　ｔｏ　ｐｌａｙ　ｙｅｔ．
@KEYNP()
;jpn:◆ちかよると　ふくぞ！@WI(20)↓
;jpn:　‥‥‥↓
;jpn:　まだ　ふけないんだけどさ。@KEYNP()
』

;@Habitat:サマーズ／トトの住宅Ｇ／トトの住宅Ｇ
;@Person:ペット
;@Figure:チリドッグ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_HOUSE_GDOG
MSG_TOTO_HOUSE_GDOG;
◆Ｂｏｗ．．．@KEY()↓
◆．．．ｎｏｗ　ｂｒｏｗｎ　ｃｏｗ？
@KEYNP()
;jpn:◆ウーーー‥‥@KEY()↓
;jpn:◆マンボ！@KEYNP()
』
;◆ハズレ！@WI(20)↓
;　（このイヌは　しゃべらない）@KEYNP()
;』

;----------------------------------------
;@Habitat:サマーズ／雑貨屋／雑貨屋
;@Person:店員
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_GROCER
MSG_SUMS_GROCER;
@GOSUB(MSG_SHOP_SUMS_GROCER)
』

；----------------------------------------
;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:店員
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_DRUGSTORE
MSG_SUMS_DRUGSTORE;@MiuraAppended
@GOSUB(MSG_SHOP_SUMS_DRUG)
』

;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:客Ａ
;@Figure:Ｔシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SOUVENIR_A
MSG_SUMS_SOUVENIR_A;
;サマーズのお土産屋客Ａ
◆Ｔｈｅｒｅ’ｓ　ａ　ｂｉｇ　ｍｏｎｓｔｅｒ　ｌｉｖｉｎｇ　ｉｎ　ｔｈｅ　ｓｅａ　ｂｅｔｗｅｅｎ　ｈｅｒｅ　ａｎｄ　Ｓｃａｒａｂａ．@KEY()↓
◆Ｉ’ｖｅ　ｓｅｅｎ　ａ　ｐｉｃｔｕｒｅ　ｏｆ　ｉｔ．
@KEYNP()
;jpn:◆スカラビにわたる　うみには↓
;jpn:　どえらいバケモノが　いるのよね。@WI(15)↓
;jpn:　しゃしんでみたことあるのよね。@KEYNP()
』

;@Habitat:サマーズ／ドラッグストア／ドラッグストア
;@Person:客Ｂ
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:◆足踏み＆方向転換
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SOUVENIR_B
MSG_SUMS_SOUVENIR_B;
;サマーズのお土産屋客Ｂ
@CHKFGOTO(FLG_PU,_SUMS_SOUVENIR_B_TMP)
_SUMS_SOUVENIR_B_MAIN;
◆Ｈｏｗ　ａｎｎｏｙｉｎｇ！@KEY()↓
◆Ｗｈｙ　ａｒｅ　ｙｏｕ　ａｒｅ　ｗａｎｄｅｒｉｎｇ　ａｒｏｕｎｄ？@KEY()↓
◆Ｓｕｍｍｅｒｓ　ｉｓ　ａ　ｐｏｓｈ　ｒｅｓｏｒｔ，　ｍａｄｅ　ｆｏｒ　ａｄｕｌｔｓ．
@KEYNP()
;jpn:◆なんだか　こどもが↓
;jpn:　うろうろしてて↓
;jpn:　じゃまねぇ。@KEY()↓
;jpn:◆サマーズは　おとなのための↓
;jpn:　こうきゅうリゾートち　なのに。@KEYNP()
』
_SUMS_SOUVENIR_B_TMP;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_SOUVENIR_B_MAIN);プーと別れていたら
@SET_LOOPREG(PC_POO)			;プーのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_SOUVENIR_B_MAIN)
◆Ｔｈａｔ　Ｋｕｎｇ　Ｆｕ－ｌｉｋｅ　ｈａｉｒｓｔｙｌｅ！@KEY()↓
◆Ｙｏｕ　ｌｏｏｋ　ｓｏ　ｃｏｏｌ！@KEY()↓
◆Ｉ　ｍａｙ　ｆａｌｌ　ｉｎ　ｌｏｖｅ　ｗｉｔｈ　ｙｏｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｔｈｉｎｋ　Ｉ’ｍ　ｔｏｏ　ｆｏｒｗａｒｄ？
@KEYNP()
;jpn:◆そちらの　べんぱつのかた↓
;jpn:　なんだか　すっごくステキ！@KEY()↓
;jpn:◆すきに　なっちゃいそう。@WI(20)↓
;jpn:　わたしったら↓
;jpn:　いけない　おんなかしら。@KEYNP()
』
;◆ちかごろ　かたがこって‥‥。↓
;　うでのいいマッサージしが↓
;　いたんだけど　みつからなくて。@KEYNP()
;』

；----------------------------------------
;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客Ａ
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_A
MSG_SUMS_HOTEL_A;
◆Ｄｏｎ’ｔ　ｇｅｔ　ｔｏｏ　ｅｘｃｉｔｅｄ　ａｂｏｕｔ　ｔｈｉｓ　ｔｏｗｎ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｔｏｕｒｉｓｔ　ｔｒａｐ．@KEY()↓
◆Ｅｖｅｒｙｏｎｅ　ｓｅｅｍｓ　ｔｏ　ｂｅ　ｎｉｃｅ，　ｂｕｔ　ｔｈｅｙ’ｒｅ　ｊｕｓｔ　ｄｏｉｎｇ　ｉｔ　ｆｏｒ　ｔｈｅ　ｍｏｎｅｙ．@KEY()↓
◆Ｉ　ｋｎｏｗ　ｆｒｏｍ　ｅｘｐｅｒｉｅｎｃｅ．
@KEYNP()
;jpn:◆このまちで　うかれていては↓
;jpn:　いけません。↓
;jpn:　ここは　かんこうち　なんです。@KEY()↓
;jpn:◆みんな　しんせつぶってるけど↓
;jpn:　しょうばいで　しんせつに↓
;jpn:　してるんですよ。　きっと。@KEYNP()
』

;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客Ｂ
;@Figure:ＯＬＣ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_B
MSG_SUMS_HOTEL_B;
◆Ｅｘｃｕｓｅ　ｍｅ．
;jpn:◆エクスキューズ　ミー。
@KEYNP()
』

;@Habitat:サマーズ／ホテル／廊下ロビー
;@Person:客Ｃ
;@Figure:おばさんＢ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_C
MSG_SUMS_HOTEL_C;＃
@CHKFGOTO(FLG_ITEM_HIEROGLYPH,_SUMS_HOTEL_C_END)
◆Ｉ　ｈｅａｒｄ　ｔｈｅ　ｓｅｃｕｒｉｔｙ　ｇｕａｒｄ　ｉｎ　ｔｈｅ　Ｓｃａｒａｂａ　Ｃｕｌｔｕｒａｌ　Ｍｕｓｅｕｍ　ｉｓｎ’ｔ　ｖｅｒｙ　ｎｉｃｅ．@KEY()↓
◆Ｂｕｔ　ｈｅ　ｃａｎ　ｂｅ　ｈｅｌｐｆｕｌ．
@KEYNP()
;jpn:◆「スカラビぶんかはくぶつかん」↓
;jpn:　にいる　ガードマンって‥‥@KEY()↓
;jpn:◆あんまり　たちが↓
;jpn:　よくないって　はなしだけど@WI(20)↓
;jpn:　りようできるおとこ　らしいわ。@KEYNP()
』
_SUMS_HOTEL_C_END;＆
◆Ｆｏｒｇｅｔ　ａｂｏｕｔ　ｔｈｅ　ａｄｖｅｎｔｕｒｅ，@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ａｇａｉｎ！
@KEYNP()
;jpn:◆いつかまた↓
;jpn:　ぼうけんなんか　わすれて↓
;jpn:　あそびにきてね。@KEYNP()
』


;◆ビーチにいた　マッサージさん↓
;　すっごく　じょうずだったわ。↓
;　ゆめごこちよ。@KEYNP()
』


;■サマーズホテル西の部屋■■■■■■■■■■■■■■■■■■■■■■■■■
;added 0717 toda -> ueno
MSG_SUMS_HOTEL_D
◆Ｉ　ｃａｎ’ｔ　ｂｅｌｉｅｖｅ　ｙｏｕ　ｐｒｏｎｏｕｎｃｅ　Ｈｏｔｅｌ　ａｓ　”Ｈｏｔｅｌ．”@KEY()↓
◆Ｉｎ　ｔｈｉｓ　ｃｏｕｎｔｒｙ，　Ｈｏｔｅｌ　ｉｓ　ｐｒｏｎｏｕｎｃｅｄ　”ｏｔｅｌ．”@KEY()↓
◆．．．Ｗｈａｔ？@KEY()↓
◆Ｓｏ　ｔｈｅｎ　ｉｎ　ｙｏｕｒ　ｃｏｕｎｔｒｙ，　ｉｓ　ｏｔｔｅｒ　ｐｒｏｎｏｕｎｃｅｄ　ａｓ　”Ｈｏｔｔｅｒ”？@KEY()↓
◆’Ｏｗ　ｓｈｏｕｌｄ　Ｉ　ｋｎｏｗ　ｔｈｅｓｅ　ｔｈｉｎｇｓ？．
@KEYNP()
;jpn:◆ホテルを　ホテルと↓
;jpn:　はつおんしてるようじゃ↓
;jpn:　おさとが　しれるね。@KEY()↓
;jpn:◆このくにでは↓
;jpn:　ホテルは　オテルなのさ。@KEY()↓
;jpn:◆‥‥え？↓
;jpn:　じゃ　ホタルはオタルかって？@KEY()↓
;jpn:◆そんなことは↓
;jpn:　シラーヌ・ド・ゾンゼーヌ。@KEYNP()
』



;@Habitat:サマーズ／ホテル／受付
;@Person:フロントマン
;@Figure:おじさんＢ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTEL_DESK
MSG_SUMS_HOTEL_DESK;@MiuraAppended
;◆サマーズホテルにようこそ。@KEY()↓
@GOSUB(MSG_GLOBAL_HOTEL)
』

;@Habitat:サマーズ／ホテル／受付
;@Person:ボーイ
;@Figure:ホテルボーイ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOTELPORTER
MSG_SUMS_HOTELPORTER;
;jpn:◆いつも　どうも　ポーキ‥‥@WI(20)↓
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Ｔｈａｎｋ　ｙｏｕ　ａｇａｉｎ，　Ｐｏｋｅ．．．@KEY()↓
◆Ｕｈｈｈ，　Ｍｒ．　@DSP_NAME(0)．
@KEYNP()
;＠ポーラだったら変える「Ｍｉｓｓ」
;jpn:　いえ　@WI(20)@DSP_NAME(0)さま。@KEYNP()
』

;@Habitat:サマーズ／ホテル／キャッシュディスペンサ
;@Person:キャッシュディスペンサ
;@Figure:ＣＤ
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

；----------------------------------------
;@Habitat:サマーズ／レストラン／レストラン
;@Person:店員
;@Figure:コック
;@AppearanceKey:0
;@ActionScript:◆正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_DINER
MSG_SUMS_DINER;
;
@GOSUB(MSG_SHOP_SUMS_DINER)
;
;処理後
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:ウェートレス
;@Figure:ウェートレスＢ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_WAITRESS
MSG_SUMS_RESTAURANT_WAITRESS;
◆@DSP_STS(STS_PARTY_FAVORITE_FOODS)？@KEY()↓
◆Ｐｌｅａｓｅ．．．ｗｅ　ｄｏ　ｎｏｔ　ｈａｖｅ　ｓｕｃｈ　ｔｒａｓｈ　ｏｎ　ｏｕｒ　ｍｅｎｕ．
@KEYNP()
;◆@DSP_STS(STS_PARTY_FAVORITE_FOODS)？@WI(20)↓
;jpn:　うちのメニューには　ないわ。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客Ａ
;@Figure:おじさんＢ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_A
MSG_SUMS_RESTAURANT_A;
◆Ｈｅｙ，　ｔａｌｋｉｎｇ　ｔｏ　ｐｅｏｐｌｅ　ａｔ　ａｎｏｔｈｅｒ　ｔａｂｌｅ　ｉｎ　ａ　ｒｅｓｔａｕｒａｎｔ　ｉｓ　ｌｉｋｅ．．．@KEY()↓
◆ｂｒｅａｋｉｎｇ　ｉｎｔｏ　ｔｈｅｉｒ　ｒｏｏｍ　ａｎｄ　ｃｈｅｃｋｉｎｇ　ｔｈｅｉｒ　ｄｒａｗｅｒｓ　ｆｏｒ　ｖａｌｕａｂｌｅｓ．@KEY()↓
◆Ｙｅａｈ，　ｏｔｈｅｒ　ｐｅｏｐｌｅ　ｏｎ　ｉｍｐｏｒｔａｎｔ　ａｄｖｅｎｔｕｒｅｓ　ｄｏ　ｓｕｃｈ　ｔｈｉｎｇｓ，@KEY()↓
◆ｂｕｔ　ｙｏｕ　ｈａｖｅ　ｔｏ　ａｄｍｉｔ　ｔｈａｔ　ｉｔ’ｓ　ｂｉｚａｒｒｅ！
@KEYNP()
;jpn:◆きみ　レストランの↓
;jpn:　べつのテーブルのきゃくに↓
;jpn:　やたらに　はなしかけることは‥‥@KEY()↓
;jpn:◆こんやくしゃの　へやに　はいって↓
;jpn:　ものもいわずに↓
;jpn:　タンスのひきだしを　しらべて‥‥@KEY()↓
;jpn:◆ちいさなメダルを　さがすような↓
;jpn:　いじょうな　こういだよ。@WI(20)↓
;jpn:　ま‥‥@KEY()↓
;jpn:◆じじょうがあるなら↓
;jpn:　しかたがないけど　ね。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客Ｂ
;@Figure:おばさんＡ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_B
MSG_SUMS_RESTAURANT_B;
◆Ｉ　ｌｉｋｅ　ｔｈｅ　ａｔｍｏｓｐｈｅｒｅ　ｉｎ　ｔｈｉｓ　ｒｅｓｔａｕｒａｎｔ．@KEY()↓
◆Ｔｈｅｙ　ｈａｖｅ　ｇｏｏｄ　ｆｏｏｄ，　ｔｏｏ．
@KEYNP()
;jpn:◆このみせって↓
;jpn:　ふんいきもいいけど↓
;jpn:　おりょうりが　すばらしいわ。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客Ｃ
;@Figure:おじさんＤ
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_C
MSG_SUMS_RESTAURANT_C;
◆Ｉ’ｌｌ　ｈａｖｅ　ｔｈｅ　Ｂｒａｉｓｅｄ　Ｂｏａ　Ｏｖｅｒ　Ｍｉｎｃｅｄ　Ｂａｂｙ　Ｌｅｅｋｓ．．．@KEY()↓
◆Ｏｈ，　ｙｏｕ’ｒｅ　ｎｏｔ　ｔｈｅ　ｗａｉｔｅｒ．
@KEYNP()
;jpn:◆チャバネヘビの↓
;jpn:　おにがらやきを　くれ。↓
;jpn:　おっと　みせのひとじゃないのか。@KEYNP()
』

;@Habitat:サマーズ／レストラン／レストラン
;@Person:客Ｄ
;@Figure:おばあさん
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESTAURANT_D
MSG_SUMS_RESTAURANT_D;
◆Ｉ　ｈａｖｅ　ｆａｋｅ　ｔｅｅｔｈ，@KEY()↓
◆ｓｏ　Ｉ　ｌｉｋｅ　ｓｏｆｔ　ｆｏｏｄｓ．@KEY()↓
◆Ｎｏｔ　ｌｉｋｅ　ｒｏｃｋｓ　ｏｒ　ｓｔｏｎｅｓ．@KEY()↓
◆Ｔｈｅｙ’ｒｅ　ｔｏｏ　ｈａｒｄ．
@KEYNP()
;jpn:◆わたしは　いればなので↓
;jpn:　やわらかいものが　すきなの。@WI(20)↓
;jpn:　いわとか　いしは　かたくって。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／博物館／受付
;@Person:受付嬢(オードリー)
;@Figure:ＯＬＧ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_AUDREY
MSG_SUMS_MUSEUM_AUDREY;
@CHKFGOTO(FLG_GLOBAL_MUSEUM_PAID,_SUMS_MUSEUM_PAID)
◆Ｒｉｇｈｔ　ｎｏｗ，　ｐａｒｔ　ｏｆ　ｔｈｅ　Ｓｃａｒａｂａ　Ｃｕｌｔｕｒａｌ　Ｍｕｓｅｕｍ　ｉｓ　ｂｅｉｎｇ　ｒｅｍｏｄｅｌｉｎｇ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｅｎｔｅｒ？↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆いま↓
;jpn:　「スカラビぶんかはくぶつかん」は↓
;jpn:　いちぶ　かいそうちゅうですが@KEY()↓
;jpn:◆それでも　いいですか？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_AUDREY_YES,_SUMS_MUSEUM_AUDREY_NO)

_SUMS_MUSEUM_AUDREY_NO;
◆Ｓｉｎｃｅ　ｔｈｅ　Ｈｉｅｒｏｇｌｙｐｈ　ｄｉｓｐｌａｙ　ｉｓ　ｃｌｏｓｅｄ，　ｐｅｏｐｌｅ　ｈａｖｅｎ’ｔ　ｗａｎｔｅｄ　ｔｏ　ｖｉｓｉｔ．
@KEYNP()
;jpn:◆ヒエログリフが　みられないので↓
;jpn:　おきゃくさまが　ほとんど↓
;jpn:　はいらないんですよ。@KEYNP()
』

_SUMS_MUSEUM_AUDREY_YES;
◆Ｔｈｒｅｅ　ｄｏｌｌａｒｓ　ｐｅｒ　ｐｅｒｓｏｎ．@KEY()↓
◆Ｓｔｕｄｙ　ｈａｒｄ．↓
;jpn:◆では　おひとり３ドルです。↓
;jpn:　しっかり　べんきょうしてね。↓
@WINR_MONEY()
<Ｙｅｓ>
<Ｎｏ>
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_AUDREY_YESYES,_SUMS_MUSEUM_AUDREY_NO)
@GOTO(_SUMS_MUSEUM_AUDREY_NO)

_SUMS_MUSEUM_AUDREY_YESYES;
@MUL_ACTIVE_PLAYER(3)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_SUMS_MUSEUM_AUDREY_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(0)
@WINR_MONEY()
@SETF(FLG_GLOBAL_MUSEUM_PAID)
@CHKFGOTO(FLG_WIN_GIEGU,MSG_END)	;別れのＨＲＥＣＴを保つ為
@RES_HIT_RECT(1)			;お金を払ったら包囲網を解く
』

_SUMS_MUSEUM_AUDREY_NOMONEY;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｒｉｇｈｔ？@KEY()↓
◆Ｏｋａｙ，　ｓｉｎｃｅ　ｙｏｕ　ｋｉｄｓ　ｌｏｏｋ　ｌｉｋｅ　ｙｏｕ　ｗｏｕｌｄ　ｓｔｕｄｙ　ｈａｒｄ，　ｙｏｕ　ｍａｙ　ｅｎｔｅｒ，@KEY()↓
◆ｆｒｅｅ　ｏｆ　ｃｈａｒｇｅ！@KEY()↓
◆Ｏｈ　ｗａｉｔ．．．Ｉ　ｃａｎ’ｔ　ｄｏ　ｔｈａｔ！@KEY()↓
◆Ｇｏｏｄ　ｂｙｅ．
@KEYNP()
;jpn:◆おかねがないんですね？@KEY()↓
;jpn:◆それじゃあ↓
;jpn:　べんきょうねっしんな↓
;jpn:　こども@GOSUB(MSG_SUB_TATI)だから@KEY()↓
;jpn:◆ただ！@KEY()↓
;jpn:◆むりょう！@KEY()↓
;jpn:◆に　するわけにいかないのよ。↓
;jpn:　さよなら。@KEYNP()
』
_SUMS_MUSEUM_PAID;
◆Ｓｉｎｃｅ　ｔｈｅ　Ｈｉｅｒｏｇｌｙｐｈ　ｄｉｓｐｌａｙ　ｉｓ　ｃｌｏｓｅｄ，　ｐｅｏｐｌｅ　ｈａｖｅｎ’ｔ　ｗａｎｔｅｄ　ｔｏ　ｖｉｓｉｔ．
@KEYNP()
;jpn:◆ヒエログリフが　みられないので↓
;jpn:　おきゃくさまが　ほとんど↓
;jpn:　はいらないんですよ。@KEYNP()
』

;@Habitat:サマーズ／博物館／展示室大
;@Person:係員（オマール）
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆西を向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_OMAR
MSG_SUMS_MUSEUM_OMAR;
◆Ｔｈｉｓ　ｒｏｏｍ　ｉｓ　ｂｅｉｎｇ　ｒｅｍｏｄｅｌｅｄ，　ｓｏ　Ｉ　ｃａｎ’ｔ　ｓｈｏｗ　ｉｔ　ｔｏ　ｙｏｕ．．．@KEY()↓
;jpn:◆このへやは　かいそうちゅうで↓
;jpn:　みせるわけには　いかないが‥‥@KEY()↓
@CHKFGOTO(FLG_PU,MSG_SUMS_MUSEUM_OMAR_PU)
_SUMS_MUSEUM_OMAR_PU_DEAD;
◆Ｉ　ｃａｎ’ｔ．．．ｗｅｌｌ，　Ｉ　ｕｓｕａｌｌｙ　ｄｏｎ’ｔ．．．@KEY()↓
◆ｓｈｏｗ　ｔｈｉｓ　ｒｏｏｍ．．．@KEY()↓
◆Ｏｎｃｅ　ｙｏｕ　ｈｉｔ　ａｄｕｌｔｈｏｏｄ，　ｙｏｕ’ｌｌ　ｕｎｄｅｒｓｔａｎｄ．@KEY()↓
◆Ｉ　ｄｏ，　ｈｏｗｅｖｅｒ，　ｌｉｋｅ　ｊｅｗｅｌｒｙ．@KEY()↓
◆Ｐｅｒｈａｐｓ　ａ　ｌｉｔｔｌｅ，　ｓｈａｌｌ　ｗｅ　ｓａｙ，　”ｕｎｄｅｒ　ｔｈｅ　ｔａｂｌｅ　ｄｅａｌ”　ｗｏｕｌｄ　ｂｅ　ｉｎ　ｏｒｄｅｒ．．．
@KEYNP()
;jpn:◆いかないが‥‥いや↓
;jpn:　なんでもない。↓
;jpn:　ふつうは　みせない‥‥と。@KEY()↓
;jpn:◆ま　おとななら↓
;jpn:　わかってもらえるんだろうが@KEY()↓
;jpn:◆わたしは　ほうせきに↓
;jpn:　きょうみが　あってねぇ。@KEY()↓
;jpn:◆うーむ　そでのしたのほうが↓
;jpn:　なんか　スースーするなぁ。↓
;jpn:　コホン@KEYNP()
』
MSG_SUMS_MUSEUM_OMAR_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_TINY_RUBY)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
@SET_LOOPREG(PC_POO)			;プーのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(MSG_SYS_GOODS_USE_NG)
@GOTO(MSG_SUMS_MUSEUM_OMAR_PU)
』

MSG_SUMS_MUSEUM_OMAR_PU;
@SET_LOOPREG(PC_POO)			;プーのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_MUSEUM_OMAR_PU_DEAD)
◆Ｏｈ，　ｔｈｅ　ｓａｍｕｒａｉ　ｋｉｄ　ｉｓ　ｈｅｒｅ．@KEY()↓
◆Ｗｉｌｌ　ｈｅ　ｂｅ　ｇｉｖｉｎｇ　ｍｅ　ｔｈａｔ　ｇｅｍ？↓
;＠プーだけだったら「ｙｏｕ」
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆おっと　そっちのべんぱつのひと↓
;jpn:　その　ほうせきを　わたしに？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_MUSEUM_OMAR_PU_YES,_SUMS_MUSEUM_OMAR_PU_NO)

_SUMS_MUSEUM_OMAR_PU_NO;
@SE(SE_se76_my_give)
◆Ｅｘｃｕｓｅ　ｍｅ？@KEY()↓
◆Ｓｏ，　ｗｈａｔ　ｈｅ　ｊｕｓｔ　ｈａｎｄｅｄ　ｍｅ　ｉｓ　ｎｏｔ　ａ　ｇｅｍ．@KEY()↓
;＠プーだけだったら「ｙｏｕ」
◆Ｈａｈ　ｈａ　ｈａ．@KEY()↓
◆Ｉ’ｍ　ｇｏｉｎｇ　ｔｏ　ｒｅａｌｌｙ　ｅｎｊｏｙ　ｔｈｅ　”ｃｏｏｋｉｅ”　ｔｈａｔ　Ｉ　ｊｕｓｔ　ｇｏｔ．@KEY()↓
◆Ｌｅｔ’ｓ　ｐｒｅｔｅｎｄ　ｔｈｉｓ　ｃｏｎｖｅｒｓａｔｉｏｎ　ｎｅｖｅｒ　ｔｏｏｋ　ｐｌａｃｅ．．．@KEY()↓
◆Ｗｈｉｌｅ　Ｉ’ｍ　ｐｒｅｔｅｎｄｉｎｇ，　ｙｏｕ　ｇｏ　ｏｎ　ｉｎ．．．
@KEY()
;jpn:◆えっ　ほうせきじゃないけど‥‥@KEY()↓
;jpn:◆エッヘッヘ↓
;jpn:　わたしの　そでのしたに↓
;jpn:　おもりを　つけろって　ですか。@KEY()↓
;◆えっ　それでハナをかむ？↓
;　ハナをかんだら　そのカミクズは↓
;　わたしに　くれると？！　おお！@KEY()↓
;jpn:◆わたし‥‥みてみぬふりを↓
;jpn:　しますから　そのすきに↓
;jpn:　はいっていいです。へっへっへ。@KEY()
@GOTO(MSG_EVT_SUMS_OMAR)
』

_SUMS_MUSEUM_OMAR_PU_YES;
@SE(SE_se76_my_give)
◆Ｙｏｕ’ｒｅ　ｓｕｃｈ　ａ　ｇｏｏｄ　ｓｔｕｄｅｎｔ．@KEY()↓
◆Ｉ’ｍ　ｉｍｐｒｅｓｓｅｄ　ｂｙ　ｙｏｕｒ　ｐａｓｓｉｏｎ　ｆｏｒ　ｌｅａｒｎｉｎｇ．@KEY()↓
◆Ｃｏｍｅ　ｉｎ．
@KEY()
;jpn:◆よほどべんきょうねっしんなかた。↓
;jpn:　そのきもちに　うたれました。↓
;jpn:　どうぞ　おはいりください。@KEY()
@GOTO(MSG_EVT_SUMS_OMAR)
』

MSG_EVT_SUMS_OMAR;
@SET_CHAR_DIR(PRSN_SUMS_HIERO_PASS_A,DIR_M_UP)
@WI(30)
@SE(SE_se08_door_in)
@HIDE_CHAR(PRSN_SUMS_HIERO_PASS_A,OBJFX_HIDE_NONE)
@GOODSOUT(PC_ALL,GDS_TOOL_TINY_RUBY)
@SETF(FLG_SUMS_OMAR_B_APPEAR)
』

MSG_SUMS_OMAR_B;
@CHKFGOTO(FLG_TEMP_9,MSG_SUMS_OMAR_B_TEMP)
◆Ｅｘｃｅｌｌｅｎｔ！@KEY()↓
◆Ｄｏ　ｙｏｕ　ｆｅｅｌ　ｌｉｋｅ　ｙｏｕ’ｒｅ　ｒｅａｌｌｙ　ｅｘｐｅｒｉｅｎｃｉｎｇ　ｔｈｉｓ　ｇｒｅａｔ　ｈｉｓｔｏｒｉｃａｌ　ｐｅｒｉｏｄ？@KEY()↓
◆Ｔｈｅ　ｅｘｐｅｒｉｅｎｃｅ　ｉｓ　ｍｏｒｅ　ｖａｌｕａｂｌｅ　ｔｈａｎ　ａ　ｓｍａｌｌ　ｇｅｍ．．．@KEY()↓
◆Ｈａ　ｈａ　ｈａ！@KEY()↓
◆Ｔｈｅ　ｏｔｈｅｒ　ｄａｙ，　ａ　ｒｉｃｈ　ｋｉｄ　ｃａｍｅ　ｔｏ　Ｓｕｍｍｅｒｓ　ｂｙ　ｈｅｌｉｃｏｐｔｅｒ．．．@KEY()↓
◆Ｈｅ　ａｌｓｏ　ｔｏｏｋ　ａ　ｐｉｃｔｕｒｅ　ｏｆ　ｔｈｅ　Ｈｉｅｒｏｇｌｙｐｈｓ．@KEY()↓
◆Ｉ　ｇｏｔ　ｌｏｔｓ　ｏｆ　ｍｏｎｅｙ　ｆｒｏｍ　ｈｉｍ．@KEY()↓
◆Ｈｅｈ　ｈｅｈ　ｈｅｈ．
@KEYNP()
;jpn:◆すばらしい！@KEY()↓
;jpn:◆いだいなる　れきしを↓
;jpn:　かんじるでしょう？@KEY()↓
;jpn:◆この　ちいさな↓
;jpn:　ほうせき　いじょうの↓
;jpn:　かちのある‥‥@KEY()↓
;jpn:◆ワッハッハ！@KEY()↓
;jpn:◆こないだも　ヘリコプターで↓
;jpn:　サマーズにやってきた↓
;jpn:　ふごうの　しょうねんがね‥‥@KEY()↓
;jpn:◆ヒエログリフを↓
;jpn:　しゃしんにとって↓
;jpn:　いきましたよ。@KEY()↓
;jpn:◆あんときゃ　げんきんを↓
;jpn:　たっぷり　もらったっけなぁ↓
;jpn:　ヘッヘッヘ。@KEYNP()
』

MSG_SUMS_OMAR_B_TEMP;
◆Ｈｅｒｅ’ｓ　ａ　ｐｉｃｔｕｒｅ　ｏｆ　ｔｈｅ　ｈｉｅｒｏｇｌｙｐｈｓ，　ｊｕｓｔ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｒｅｗａｒｄ　ｆｏｒ　ｓｔｕｄｙｉｎｇ　ｓｏ　ｈａｒｄ．@KEY()↓
;jpn:◆べんきょうねっしんな　かたに↓
;jpn:　「ヒエログリフのうつし」を↓
;jpn:　とくべつに　さしあげましょう。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_OMAR_B_ITEMFULL_TEMP)
@GOODSIN_PLAYER(0,GDS_TOOL_HIEROGLYPH_COPY)
@GOSUB(MSG_SUB_GETGOODS)@KEY()↓
◆Ｕｓｅ　ｉｔ　ｉｎ　ｙｏｕｒ　Ｈｕｍａｎ　Ｃｉｖｉｌｉｚａｔｉｏｎ　ｃｌａｓｓ．@KEY()↓
◆Ｈａ　ｈａ　ｈａ！
@KEYNP()
;jpn:◆じんるいの　ぶんかのために↓
;jpn:　やくだててください。@KEY()↓
;jpn:◆ワッハッハ！@KEYNP()
@SETF(FLG_ITEM_HIEROGLYPH)
@CLRF(FLG_TEMP_9)
@CHKFGOTO(FLG_FOUR_KOMORITA,MSG_END)	;ライスボウルの話しを聞いてなければ
@SETF(FLG_SUMS_MUSEUM_PHONE_RING)	;電話鳴る
』
_SUMS_OMAR_B_ITEMFULL_TEMP;
@SE(SE_se05_undo)
◆Ｏｈ，　ｙｏｕ　ｃａｎ’ｔ　ｃａｒｒｙ　ｉｔ　’ｃａｕｓｅ　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｐｉｔｙ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｓｕｃｈ　ａ　ｈａｒｄ　ｗｏｒｋｅｒ．@KEY()↓
◆Ｈａ　ｈａ　ｈａ！
@KEYNP()
;jpn:◆おお　にもつが
;jpn:　いっぱいで　もてない！@KEY()↓
;jpn:◆べんきょうねっしんなかたなのに↓
;jpn:　もてないとは　ざんねんですな。@KEY()↓
;jpn:◆ワッハッハ！@KEYNP()
@SETF(FLG_TEMP_9)
』

MSG_SUMS_OMAR_B_EVT;
;オマールに漫符出す
@SET_CHAR_DIR( PRSN_SUMS_HIERO_EXHI2_A, DIR_M_LEFT )
@SHOW_MANPU_CHAR( PRSN_SUMS_HIERO_EXHI2_A, MANPU_BIKKURI )
@WI( 60 )
@HIDE_MANPU_CHAR( PRSN_SUMS_HIERO_EXHI2_A )
;パーティに近寄るオマール
@REMOVE_CHAR( PRSN_SUMS_HIERO_EXHI2_A, ANIM_OMAR_GIVE_HIEROGRIPH )
@WAITSYS()
@COLD_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」凍結
@OPEN(1)
◆Ｗａｉｔ　ｏｎｅ　ｓｅｃｏｎｄ．@KEY()↓
◆Ｈｅｒｅ’ｓ　ａ　ｐｉｃｔｕｒｅ　ｏｆ　ｔｈｅ　ｈｉｅｒｏｇｌｙｐｈｓ　ｊｕｓｔ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｒｅｗａｒｄ　ｆｏｒ　ｓｔｕｄｙｉｎｇ　ｓｏ　ｈａｒｄ．@KEY()↓
;jpn:◆ちょっと　おまちを。@KEY()↓
;jpn:◆べんきょうねっしんな　かたに↓
;jpn:　「ヒエログリフのうつし」を↓
;jpn:　とくべつに　さしあげましょう。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_OMAR_B_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_HIEROGLYPH_COPY)
@GOSUB(MSG_SUB_GETGOODS)@KEY()↓
◆Ｕｓｅ　ｉｔ　ｉｎ　ｙｏｕｒ　Ｈｕｍａｎ　Ｃｉｖｉｌｉｚａｔｉｏｎ　ｃｌａｓｓ．@KEY()↓
◆Ｈａ　ｈａ　ｈａ！
@KEYNP()
;jpn:◆じんるいの　ぶんかのために↓
;jpn:　やくだててください。@KEY()↓
;jpn:◆ワッハッハ！@KEYNP()
@CLOSEALL()
@FRESH_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」
@WAITSYS()
@SETF(FLG_ITEM_HIEROGLYPH)
@CHKFGOTO(FLG_FOUR_KOMORITA,MSG_END)	;ライスボウルの話しを聞いてなければ
@SETF(FLG_SUMS_MUSEUM_PHONE_RING)	;電話鳴る
』
_SUMS_OMAR_B_ITEMFULL;
@SE(SE_se05_undo)
◆Ｏｈ，　ｙｏｕ　ｃａｎ’ｔ　ｃａｒｒｙ　ｉｔ　’ｃａｕｓｅ　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｉｔ’ｓ　ａ　ｐｉｔｙ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｓｕｃｈ　ａ　ｈａｒｄ　ｗｏｒｋｅｒ．@KEY()↓
◆Ｈａ　ｈａ　ｈａ！
@KEYNP()
;jpn:◆おお　にもつが
;jpn:　いっぱいで　もてない！@KEY()↓
;jpn:◆べんきょうねっしんなかたなのに↓
;jpn:　もてないとは　ざんねんですな。@KEY()↓
;jpn:◆ワッハッハ！@KEYNP()
@CLOSEALL()
@FRESH_CHAR( PRSN_SUMS_HIERO_EXHI2_A )	;「去るオマール」
@WAITSYS()
@SETF(FLG_TEMP_9)
』


;@Habitat:サマーズ／博物館／展示室大
;@Person:学芸員
;@Figure:サラリーマンＤ
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_KOMORITA
MSG_SUMS_MUSEUM_KOMORITA;＃
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_MUSEUM_KOMORITA_END)
@CHKFGOTO(FLG_FOUR_KOMORITA_APPEAR,_SUMS_MUSEUM_KOMORITA_LATER)
◆Ｗｈａｔ？　　Ｍｒ．　Ｓｐｏｏｎ　ｉｓ　ｃａｌｌｉｎｇ　ｆｒｏｍ　ｔｈｅ　Ｆｏｕｒｓｉｄｅ　ｍｕｓｅｕｍ？@KEY()↓
◆Ｈｅ’ｓ　ｊｕｓｔ　ｂｒａｇｇｉｎｇ　ａｂｏｕｔ　ｓｏｍｅｔｈｉｎｇ．．．@KEY()↓
◆Ｌｅｔ　ｈｉｍ　ｓａｙ　ｗｈａｔ　ｈｅ　ｗａｎｔｓ！@KEY()↓
◆Ｉ　ｗｏｎｄｅｒ　ｗｈａｔ　ｈｅ　ｗａｎｔｓ　ｔｏ　ｔｅｌｌ　ｍｅ？@KEY()↓
◆Ｉ　ｄａｒｅ　ｈｉｍ　ｔｏ　ｔｒｙ　ａｎｄ　ｕｐｓｔａｇｅ　ｍｅ．．．@KEY()↓
◆Ｏｈ，　ｓｏｒｒｙ．．．Ｉ　ｗａｓ　ｊｕｓｔ　ｔａｌｋｉｎｇ　ｔｏ　ｍｙｓｅｌｆ．．．＊ｃｏｕｇｈ＊
@KEYNP()
;jpn:◆「フォーサイド↓
;jpn:　しぜんはくぶつかん」の↓
;jpn:　ライスボウルくんが@KEY()↓
;jpn:◆なにか　じまんそうなでんわを↓
;jpn:　かけてきてるらしいんだが‥‥@KEY()↓
;jpn:◆‥‥なんなんだろう？@WI(20)↓
;jpn:　あー　しりたい！@WI(15)↓
;jpn:　あー　くやしい！@KEY()↓
;jpn:◆‥‥あ　いまのは　ひとりごとさ。@WI(20)↓
;jpn:　きに　しないで　くれたまえね。@WI(15)↓
;jpn:　コホン。@KEYNP()
@SE(SE_se72);あやしい音
@KEYNP()
』
_SUMS_MUSEUM_KOMORITA_LATER;
◆Ｉｔ　ｍｕｓｔ　ｂｅ　ｓｏｍｅｔｈｉｎｇ　ｔｅｅｎｙ　ｗｅｅｎｙ　ｔｈａｔ　Ｍｒ．　Ｓｐｏｏｎ　ｈａｓ　ｆｏｕｎｄ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｎｅｅｄ　ｔｏ　ｋｎｏｗ　ｔｈｅ　ｓｐｅｃｉｆｉｃｓ．
@KEYNP()
;jpn:◆ライスボウルくんの↓
;jpn:　はっけんなんて@WI(20)↓
;jpn:　どうせ　たいしたことなかったろ？@KEY()↓
;jpn:◆ぼくは　あんまり↓
;jpn:　しりたくないな。@KEYNP()
』
_SUMS_MUSEUM_KOMORITA_END;＆
◆Ｙｏｕ　ｈａｖｅ　ａ　ｇｏｏｄ　ｒｅｐｕｔａｉｔｏｎ．@KEY()↓
◆Ｗｏｕｌｄｎ’ｔ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｆｏｃｕｓ　ｙｏｕｒ　ｈａｒｄ　ｗｏｒｋｉｎｇ　ｅｎｅｒｇｙ@KEY()↓
◆ｉｎ　ｔｈｅ　ｅｘｃｉｔｉｎｇ　ｆｉｅｌｄ　ｏｆ　ａｒｃｈａｅｏｌｏｇｙ？
@KEYNP()
;jpn:◆きみの　いいうわさは↓
;jpn:　いろいろ　きいてるよ。@KEY()↓
;jpn:◆その　こんじょうを↓
;jpn:　これから　こうこがくの↓
;jpn:　けんきゅうに　いかさないか？@KEYNP()
』


;@Habitat:サマーズ／博物館／展示室大
;@Person:客
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_MUSEUM_A
MSG_SUMS_MUSEUM_A;＃
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_MUSEUM_A_END)
◆Ｉ　ｓａｗ　ａ　ｃｈｕｂｂｙ　ｋｉｄ　ａｂｏｕｔ　ｙｏｕｒ　ａｇｅ　ｈｅｒｅ．@KEY()↓
◆Ｈｅ　ｌｏｏｋｅｄ　ｌｉｋｅ　ｈｅ　ｗａｓ　ａｗｆｕｌｌｙ　ｗｅａｌｔｈｙ．　　Ｈｅ　ｗａｓ　ｂｅｉｎｇ　ｅｘｔｒａｖａｇａｎｔ！
@KEYNP()
;jpn:◆ちょうど　おまえらと↓
;jpn:　おないどしくらいの　デブが↓
;jpn:　さっきまで　いたぜ。@KEY()↓
;jpn:◆やたらに　かねまわりの↓
;jpn:　よさそうな　ガキだった。@KEYNP()
』
_SUMS_MUSEUM_A_END;＆
◆Ｉｔ’ｓ　ｎｉｃｅ　ｓｅｅｉｎｇ　ｙｏｕ　ｉｎ　ｓｕｃｈ　ｇｏｏｄ　ｓｈａｐｅ．@KEY()↓
◆Ｉ　ｗｏｎｄｅｒ　ｗｈａｔ　ｐｏｒｋｙ　Ｐｏｋｅｙ’ｓ　ｄｏｉｎｇ．@KEY()↓
◆Ｙｅａｈ，　ｔｈａｔ’ｓ　ｔｈｅ　ｂｏｙ　Ｉ　ｍｅｔ　ｂｅｆｏｒｅ．
@KEYNP()
;jpn:◆きみは　げんきそうでよかったけど@WI(20)↓
;jpn:　まえに　あった　あの↓
;jpn:　ポーキーとかいう　デブは@KEY()↓
;jpn:◆どうしてるだろうなぁ。@KEYNP()
』
;----------------------------------------
;@Habitat:サマーズ／病院／受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSPITAL_USHER
MSG_SUMS_HOSPITAL_USHER;@MiuraAppended
;◆どなたに　ごめんかいですか？@KEY()
@GOSUB(MSG_NURSE_SUMS)
;@GOSUB(MSG_SHOP_SUMS_HOSPITAL)
』

;@Habitat:サマーズ／病院／診察室
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSPITAL_DOCTOR
MSG_SUMS_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
;　だれだね？@KEY()
@GOSUB(MSG_DOCTOR_SUMS)
』

;@Habitat:サマーズ／病院／診察室
;@Person:付き添い
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_HOSP_GIRL
MSG_SUMS_HOSP_GIRL;
◆Ｍｙ　ｃｏｕｓｉｎ　ｉｓ　ａ　ｎｕｒｓｅ　ｉｎ　Ｔｗｏｓｏｎ．@KEY()↓
◆Ｓｈｅ’ｓ　ｎｏｔ　ｇｏｏｄ　ａｔ　ａｄｍｉｎｉｓｔｅｒｉｎｇ　ｓｈｏｔｓ．@KEY()↓
◆Ｔｈｅ　ｏｎｅ　ｓｈｅ　ｇａｖｅ　ｍｅ　ｗａｓ　ｐａｉｎｆｕｌ．
@KEYNP()
;jpn:◆わたしのいとこが　ツーソンで↓
;jpn:　かんごふをしてるんだけど↓
;jpn:　ちゅうしゃがへたで　いたいのよ。@KEYNP()
』

；----------------------------------------
;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男Ａ
;@Figure:海パンＢ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_A
MSG_SUMS_SWIMSUITMAN_A;
◆Ｗａｋｅ　ｕｐ　ｉｎ　ｔｈｅ　ｍｏｒｎｉｎｇ，　ｆａｌｌ　ｉｎ　ｌｏｖｅ．@KEY()↓
◆Ｅａｔ　ｌｕｎｃｈ，　ｆａｌｌ　ｉｎ　ｌｏｖｅ．．．@KEY()↓
◆Ａｎｄ　ａｔ　ｎｉｇｈｔ，　ｆａｌｌ　ｉｎ　ｌｏｖｅ　ａｇａｉｎ．．．@KEY()↓
◆Ｔｈａｔ’ｓ　ｍｙ　ｄｒｅａｍ　ｌｉｆｅ．
@KEYNP()
;jpn:◆あさおきて　こいをして↓
;jpn:　ランチをたべて　こいをして‥‥↓
;jpn:　よるになったら　こいをして‥‥。@KEY()↓
;jpn:◆そういうじんせいが↓
;jpn:　ぼくの　のぞみ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の女Ａ
;@Figure:ビキニＡ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITGAL_A
MSG_SUMS_SWIMSUITGAL_A;
◆Ｔｈｅ　ｇｕｙ　ｎｅｘｔ　ｔｏ　ｍｅ　ｉｓ　ｒｅａｌｌｙ　ｂｕｇｇｉｎｇ　ｍｅ．@KEY()↓
◆Ｈｅ　ｋｅｅｐｓ　ｆｏｌｌｏｗｉｎｇ　ｍｅ　ａｒｏｕｎｄ．
@KEYNP()
;jpn:◆となりのおとこ↓
;jpn:　うるさくて　しかたないのよ。↓
;jpn:　しつこく　ついてくるの。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男Ｂ
;@Figure:海パンＡ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_B
MSG_SUMS_SWIMSUITMAN_B;
◆Ｉ　ｗｏｎｄｅｒ　ｗｈｙ　ｓｕｃｈ　ｓｅｒｉｏｕｓ　ｌｏｏｋｉｎｇ　ｋｉｄｓ@KEY()↓
◆ａｓ　ｙｏｕ　ｗｏｕｌｄ　ｃｏｍｅ　ｔｏ　ｔｈｉｓ　ｒｅｓｏｒｔ　ｔｏｗｎ．．．@KEY()↓
◆Ｙｏｕ　ｇｕｙｓ　ａｒｅ　ｓｐｏｉｌｉｎｇ　ｔｈｅ　ａｔｍｏｓｐｈｅｒｅ．．．
@KEYNP()
;jpn:◆きみたちみたいな↓
;jpn:　せっぱつまった　かおつきの↓
;jpn:　ひとびとが‥‥@KEY()↓
;jpn:◆どうして　こんなリゾートちに↓
;jpn:　きているんだろうねぇ。↓
;jpn:　ふんいき　こわしちゃうなぁ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:水着の男Ｃ（元サーファー）
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_C
MSG_SUMS_SWIMSUITMAN_C;
◆Ｉ’ｍ　ａｃｔｕａｌｌｙ　ａ　ｓｕｒｆｅｒ．@KEY()↓
◆Ｂｕｔ　ｙｏｕ　ｃａｎ’ｔ　ｓｕｒｆ　ａｔ　ｔｈｉｓ　Ｓｕｍｍｅｒ’ｓ　ｂｅａｃｈ．@KEY()↓
◆Ｓｈｏｕｌｄ　Ｉ　ｂｅｃｏｍｅ　ａ　ｐｏｒｔｅｒ　ｓｏ　ｔｈａｔ　Ｉ　ｃａｎ　ｇｅｔ　ｔｉｐｓ　ｆｒｏｍ　ａｌｌ　ｔｈｅ　ｏｌｄ　ｆｏｌｋｓ？
@KEYNP()
;jpn:◆おれは　もともとサーファーだけど↓
;jpn:　このサマーズのビーチじゃ↓
;jpn:　なみのりは　むりだね。@KEY()↓
;jpn:◆ジーさん　バーさんから↓
;jpn:　チップをもらって↓
;jpn:　にもつはこびでも　やるか。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の男Ｄ
;@Figure:海パンＢ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITMAN_D
MSG_SUMS_SWIMSUITMAN_D;
◆Ａｒｅ　ｙｏｕ　ｆｒｏｍ　ＥａｇｌｅＬａｎｄ？@KEY()↓
◆Ｉｆ　ｙｏｕ　ｌｉｋｅ　ａｄｖｅｎｔｕｒｅ，　ｔｈｉｓ　ｉｓｎ’ｔ　ｙｏｕｒ　ｋｉｎｄ　ｏｆ　ｐｌａｃｅ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｔｒａｖｅｌ　ａｃｒｏｓｓ　ｔｈｅ　ｓｅａ　ｔｏ　Ｓｃａｒａｂａ　ｆｒｏｍ　Ｔｏｔｏ，　ｔｈｅ　ｐｏｒｔ　ｔｏｗｎ．
@KEYNP()
;jpn:◆イーグルランドから　きたのかい。↓
;jpn:　ぼうけんずきなら↓
;jpn:　このまちは　あわないとおもうよ。@KEY()↓
;jpn:◆トトっていう　みなとまちから↓
;jpn:　ふねで　スカラビに↓
;jpn:　わたるんだな。@KEYNP()
』

;@Habitat:サマーズ／フィールド／ビーチ
;@Person:水着の女Ｂ
;@Figure:ビキニＢ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_SWIMSUITGAL_B
MSG_SUMS_SWIMSUITGAL_B;
@CHKFGOTO(FLG_PU,_SUMS_SWIMSUITGAL_B_TMP)
_SUMS_SWIMSUITGAL_B_MAIN;
◆Ｄｏｎ’ｔ　ｔａｌｋ　ｔｏ　ｍｅ．@KEY()↓
◆Ｍｙ　ｍｉｎｄ　ｉｓ　ａ　ｃｏｍｐｌｅｔｅ　ｂｌａｎｋ．
@KEYNP()
;jpn:◆はなしかけるの　やめてよね@WI(15)↓
;jpn:　あたし　なーんにも↓
;jpn:　かんがえてないんだから。@KEYNP()
』
_SUMS_SWIMSUITGAL_B_TMP;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_SWIMSUITGAL_B_MAIN);プーと別れていたら
@SET_LOOPREG(PC_POO)			;プーのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SUMS_SWIMSUITGAL_B_MAIN)
◆Ａｓｉａｎ　ｂｏｙ，　ｙｏｕ’ｒｅ　ｓｏ　ｃｏｏｌ．．．@KEY()↓
◆Ｄｏｎ’ｔ　ｌｏｏｋ　ａｔ　ｍｅ　ｌｉｋｅ　ｔｈａｔ．．．
@KEYNP()
;jpn:◆あら　オリエンタルで↓
;jpn:　クールで　すてきな　おとこ‥‥@KEY()↓
;jpn:◆そんなめで　みつめないで‥‥@WI(20)↓
;jpn:　すてきすぎるー音@KEYNP()
』


;@Habitat:サマーズ／フィールド／ビーチ
;@Person:オイルマッサージ
;@Figure:マッサージ師
;@AppearanceKey:FLG_SUMS_MASSAGE_APPEAR/on
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_OILMASSAGE
MSG_SUMS_OILMASSAGE;
@CHKFGOTO(FLG_WIN_GIEGU,_SUMS_WIFE_END)
@CHKFGOTO(FLG_PU,MSG_SUMS_WIFE);ランマに行ってたらマジックタルト売りに
@FUNC(5)			;配達禁止
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈｏ　ｔｏｌｄ　ｙｏｕ．@KEY()↓
◆Ｙｏｕ　ｃａｍｅ　ｆｒｏｍ　ｆａｒ　ｏｆｆ　ｊｕｓｔ　ｔｏ　ｅａｔ　ｍｙ　Ｍａｇｉｃ　ｃａｋｅ？．．．@KEY()↓
◆Ｉ　ｔｈｏｕｇｈｔ　ｍａｋｉｎｇ　ｃａｋｅｓ　ｗｏｕｌｄ　ｂｅ　ｔｈｅ　ｂｅｓｔ　ｃａｒｅｅｒ　ｆｏｒ　ｍｅ．@KEY()↓
◆Ｄｉｇ　ｉｎ！@KEY()↓
◆Ｉ　ｕｓｅｄ　ａｌｌ　ｌｅｆｔｏｖｅｒ　ｍａｔｅｒｉａｌｓ．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ａ　ｖｅｒｙ　ｓｐｅｃｉａｌ　Ｍａｇｉｃ　ｃａｋｅ！
@KEY()
;jpn:◆だれにきいたか　しらないけれど@KEY()↓
;jpn:◆とおいくにから　わざわざ↓
;jpn:　わたしの　マジックケーキを↓
;jpn:　たべにきてくれたなんて‥‥@KEY()↓
;jpn:◆やっぱり　わたし　ケーキづくりが↓
;jpn:　いちばん　じぶんに　あってる。@WI(30)↓
;jpn:　そう　おもったの。@KEY()↓
;jpn:◆さあ　たくさんたべて！@KEY()↓
;jpn:◆さいごの　ざいりょうを↓
;jpn:　ぜんぶつかった　スペシャルな↓
;jpn:　マジックケーキよ！@KEY()↓
@CLOSEALL()
@CLRF(FLG_SUMS_MASSAGE_APPEAR)
@GOTO(MSG_EVT_78_GIL)
』
_SUMS_WIFE_END;
◆Ｉ　ｃａｎ’ｔ　ｍａｋｅ　ａｎｙｍｏｒｅ　Ｍａｇｉｃ　ｃａｋｅｓ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｒｙ　ｓｏｍｅｔｈｉｎｇ　ｔａｓｔｉｅｒ．．．@KEY()↓
◆Ｉ　ｈａｖｅ　ａ　”@DSP_GOODS(GDS_FOOD_MAGIC_TORTE)．”@KEY()↓
◆Ｔｒｙ　ｉｔ．@KEY()↓
@KEYNP()
;jpn:◆マジックケーキは↓
;jpn:　もうつくれないけど↓
;jpn:　おいしさなら　それいじょうの‥‥@KEY()↓
;jpn:◆「マジックタルト」を↓
;jpn:　うってるのよ。@KEY()↓
;jpn:◆あじみ　してね。@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SUMS_WIFE_GOODSFULL)
@GOODSIN_PLAYER(PC_ALL,GDS_FOOD_MAGIC_TORTE)
@SE(SE_se74_my_get)
◆．．．Ｉ　ｃｏｕｌｄ　ｍａｋｅ　ｏｎｅ　ｅｘｔｒａ　ｇｏｏｄ　ｔｏｄａｙ．
;jpn:◆‥‥きょうは　また↓
;jpn:　おいしくできたのよ。
@KEYNP()
@!
_SUMS_WIFE_GOODSFULL;
◆Ｙｏｕ　ｓｅｅｍ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ｔｏ　ｃａｒｒｙ．@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ａｆｔｅｒ　ｙｏｕ　ｇｅｔ　ｒｉｄ　ｏｆ　ｓｏｍｅｔｈｉｎｇ．
@KEYNP()
;jpn:◆もちものが　いっぱいよ↓
;jpn:　にもつを　へらしてから↓
;jpn:　またきてね。@KEYNP()
@!

;オイルマッサージの女（マーサ）
;◆とろけるような　ゆめごこち。@WI(20)↓
;　オイルマッサージは　いかが。@KEY()↓
;◆ためしてみる？↓
;　　<はい>　　<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_SUMS_OILMASSAGE_YES,_SUMS_OILMASSAGE_NO)
;_SUMS_OILMASSAGE_NO;
;◆じゃ　また　こんどね。バーイ。@KEYNP()
;』
;_SUMS_OILMASSAGE_YES;
;◆じゃ　こっちのひかげでね。@KEY()
;@CLOSEALL()
;@CLRF(FLG_SUMS_MASSAGE_APPEAR)
;@GOTO(MSG_EVT_78_GIL)
;』


;@Habitat:サマーズ／フィールド／ビーチ（スカイウォーカーそば）
;@Person:リゾート客Ａ
;@Figure:リゾート女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESORT_A
MSG_SUMS_RESORT_A;
◆Ｙｏｕ　ｌｏｏｋ　ｓｏ　ｓｅｒｉｏｕｓ．．．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｉｎ　Ｓｕｍｍｅｒｓ，　ａ　ｄｒｅａｍ　ｐａｒａｄｉｓｅ．@KEY()↓
◆Ｒｅｌａｘ，　ａｎｄ　ｈａｖｅ　ｓｏｍｅ　ｆｕｎ．
@KEYNP()
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)　ずいぶん↓
;jpn:　きんちょうしたかお　してるね。@KEY()↓
;jpn:◆ここは　サマーズ。@WI(20)↓
;jpn:　ゆめのパラダイスだよ。@KEY()↓
;jpn:◆もっと　リゾートっぽく↓
;jpn:　らくに　しなさいよ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:リゾート客Ｂ
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_RESORT_B
MSG_SUMS_RESORT_B;
◆Ｔｈｅ　ｓｋｙ’ｓ　ｂｌｕｅ　ａｎｄ　ｔｈｅ　ｓｕｎ　ｉｓ　ｈｉｇｈ．@KEY()↓
◆Ｔｈｅ　ｐｒｉｃｅｓ　ｈｅｒｅ　ａｒｅ　ｓｏ　ｈｉｇｈ，　ｉｔ’ｌｌ　ｍａｋｅ　ｙｏｕｒ　ｆａｃｅ　ｔｕｒｎ　ｂｌｕｅ！@KEY()↓
◆Ｔｈａｔ’ｓ　Ｓｕｍｍｅｒｓ！
@KEYNP()
;jpn:◆そらは　あおくて　たかいし↓
;jpn:　ぶっかも　あおくなるほど↓
;jpn:　たかい！　サマーズって　まちは。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:街の人１
;@Figure:Ｔシャツ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_1
MSG_SUMS_1;
◆Ｉｆ　ｙｏｕ’ｒｅ　ｂｏｒｅｄ，　ｇｏ　ｃｈｅｃｋ　ｏｕｔ　ｔｈｅ　”Ｓｃａｒａｂａ　Ｃｕｌｔｕｒａｌ　Ｍｕｓｅｕｍ．”@KEY()↓
◆Ｉｔ　ｍａｙ　ｂｅ　ｈｅｌｐｆｕｌ　ｔｏ　ｙｏｕ．@KEY()↓
◆Ｔｈｅｙ　ｈａｖｅ　ａ　ｈｉｅｒｏｇｌｙｐｈ　ｆｒｏｍ　ａ　ｐｙｒａｍｉｄ．
@KEYNP()
;jpn:◆たいくつしてるなら↓
;jpn:　「スカラビぶんかはくぶつかん」↓
;jpn:　にでも　いったら　どうだい。@KEY()↓
;jpn:◆ためになるよ。↓
;jpn:　ピラミッドのヒエログリフとかが↓
;jpn:　あるらしいしさ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:街の人２
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_2
MSG_SUMS_2;
◆Ａｎｏｔｈｅｒ　ｎｉｃｅ　ｄａｙ．@KEY()↓
◆Ｓｕｍｍｅｒｓ　ａｌｗａｙｓ　ｈａｓ　ｓｕｎｎｙ　ｄａｙｓ．
@KEYNP()
;jpn:◆きょうも　いいてんきね。@KEY()↓
;jpn:◆サマーズの　かいがんって↓
;jpn:　いつも　いいおてんきなのよ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／道路
;@Person:アイス売り
;@Figure:スロットブラザース
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_ICELOLLY
MSG_SUMS_ICELOLLY;
;◆Ｗａｎｔ　ａ　ｐｏｐｓｉｃｌｅ？
;jpn:◆アイスキャンディーは↓;
;jpn:　いかがっすか？@KEY()↓
@GOSUB(MSG_SUMS_ICE)
』


;@Habitat:サマーズ／フィールド／街の至るところ
;@Person:九官鳥
;@Figure:九官鳥
;@AppearanceKey:0
;@ActionScript:◆中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SUMS_BIRD
MSG_SUMS_BIRD;
;この九官鳥は、サマーズのまちのあちこちを
;適当にとびまわっています。そして、サマーズの人々の
;セリフをアトランダムにしゃべるのです。
◆（Ｉｔ’ｓ　ａ　Ｍｙｎａ　ｂｉｒｄ！）@KEY()↓
;jpn:◆キューカンチョーッ！@KEY()↓
@RAND(5)
@ONGOTO(MSG_SUMS_SWIMSUITGAL_A,MSG_SUMS_SWIMSUITGAL_B,MSG_SUMS_SWIMSUITMAN_D,MSG_SUMS_1,MSG_TOTO_A)
@GOTO(MSG_SUMS_SWIMSUITMAN_A)
』


;@Habitat:サマーズ／フィールド／トトの街の辺り
;@Person:街の人Ａ
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_A
MSG_TOTO_A;＃
@CHKFGOTO(FLG_TLPT_SKRB,_TOTO_A_LATER)
◆Ｔｏ　ｇｏ　ｔｏ　Ｓｃａｒａｂａ，　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｃｒｏｓｓ　ｔｈｅ　ｓｅａ．@KEY()↓
◆Ｈｏｗｅｖｅｒ　ａ　ｍｏｎｓｔｅｒ　ｎａｍｅｄ　Ｋｒａｋｅｎ　ｌｉｖｅｓ　ｉｎ　ｔｈｅ　ｏｐｅｎ　ｓｅａ．@KEY()↓
◆Ｈｅ　ａｔｔａｃｋｓ　ｓｈｉｐｓ　ｔｈａｔ　ｐａｓｓ　ｔｈｒｏｕｇｈ．@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｓｃａｒｅｄ？
@KEYNP()
;jpn:◆スカラビには　うみをわたらねば↓
;jpn:　ならないんだわな。@KEY()↓
;jpn:◆とはいえ↓
;jpn:　あれたうみには↓
;jpn:　クラーケンたらいう　バケモンが@KEY()↓
;jpn:◆げんきに　ふねを↓
;jpn:　おそってくれるんだわー。@KEY()↓
;jpn:◆こわいっしょ？@KEYNP()
』
_TOTO_A_LATER;
◆Ｉ’ｍ　ａ　ｍｉｇｈｔｙ　ｓａｉｌｏｒ　ｍａｎ@KEY()↓
◆Ａ　ｍｏｕｎｔａｉｎ　ｍａｎ　Ｉ’ｍ　ｎｏｔ@KEY()↓
◆Ｔｈｅ　ｏｐｅｎ　ｓｅａ　ｉｓ　ｈｏｍｅ　ｆｏｒ　ｍｅ@KEY()↓
◆Ａｎｄ　ｍｏｕｎｔａｉｎｓ　ａｒｅｎ’ｔ　ｗｏｒｔｈ　ｓｎｏｔ@KEY()↓
◆．．．Ｉ’ｍ　ｗｒｉｔｉｎｇ　ａ　ｓｏｎｇ　ｆｏｒ　ｓａｉｌｏｒｓ．
@KEYNP()
;jpn:◆音うみの　おとこはよー@WI(20)↓
;jpn:　やまの　おとことはよー@WI(20)↓
;jpn:　ちょと@WI(15)　ちがうよー音@KEY()↓
;jpn:◆‥‥いま　うみのおとこのうたを↓
;jpn:　つくってるところなんだ。@KEYNP()
』

;@Habitat:サマーズ／フィールド／トトの街の辺り
;@Person:街の人Ｃ
;@Figure:スペイン人
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_C
MSG_TOTO_C;
◆Ｄｉｎｏｓａｕｒｓ　ｅｘｉｓｔｅｄ！@KEY()↓
◆Ｉ　ｓａｗ　ｏｎｅ！@KEY()↓
◆Ｉｔ　ｈａｄ　ｂｅｅｎ　ｏｕｔ　ｏｆ　ｔｈｅ　ｕｎｄｅｒｇｒｏｕｎｄ　ｗｈｅｎ　ｉｔ　ｄｒｉｅｄ　ｏｕｔ．@KEY()↓
◆Ｏｆ　ｃｏｕｒｓｅ，　ｉｔ　ｗａｓ　ｄｅａｄ！@KEY()↓
◆Ｂｅｌｉｅｖｅ　ｗｈａｔ　Ｉ’ｍ　ｓａｙｉｎｇ！
@KEYNP()
;jpn:◆きょうりゅうは　いる！↓
;jpn:　おれは　みたんだってば！@KEY()↓
;jpn:◆じめんのしたから↓
;jpn:　はいあがってきて↓
;jpn:　ひからびて　しんでたんだわ！@KEY()↓
;jpn:◆おれの　いうことを↓
;jpn:　しんじてくでーっ！@KEYNP()
』

;@Habitat:サマーズ／フィールド／トトの波止場
;@Person:船乗りＡ
;@Figure:若い船乗り
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_TOTO_SAILOR_A
MSG_TOTO_SAILOR_A;
@CHKFGOTO(FLG_TLPT_SKRB,_TOTO_SAILOR_LATER)
@CHKFGOTO(FLG_PU,_TOTO_SAILOR_AFTER)
@CHKFGOTO(FLG_TEMP_9,_TOTO_SAILOR_TMP)
_TOTO_SAILOR_A_START;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ａ　ｂｏａｔ　ｒｉｄｅ？↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆ふねに　のりたいのかい？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_YES,_TOTO_SAILOR_A_NO)
_TOTO_SAILOR_A_NO;
◆Ｏｋ，　Ｉ　ｕｎｄｅｒｓｔａｎｄ．
;jpn:◆そうか　そんなら　いいんだ。
@CHKF(FLG_TEMP_9)@FALSE_GOTO(_TOTO_SAILOR_A_YES_A)
@KEYNP()
』
_TOTO_SAILOR_A_YES_A;
@KEY()↓
_TOTO_SAILOR_A_YES;
◆Ｉ　ｄｏｎ’ｔ　ｆｅｅｌ　ｌｉｋｅ　ｓｅｎｄｉｎｇ　ａ　ｓｈｉｐ　ｏｕｔ．@KEY()↓
◆Ｉ’ｍ　ｗｏｒｒｉｅｄ　ａｂｏｕｔ　ｍｙ　ｗｉｆｅ．．．@KEY()↓
◆Ｉ’ｍ　ｎｏｔ　ａｆｒａｉｄ　ｏｆ　ｔｈｅ　Ｋｒａｋｅｎ！@KEY()↓
◆．．．．．@KEY()↓
;jpn:◆ふねをだす　きに↓
;jpn:　なれねぇんだよ。@KEY()↓
;jpn:◆にょうぼの　ことで↓
;jpn:　なやんでてね‥‥。@KEY()↓
;jpn:◆クラーケンが↓
;jpn:　こわいわけじゃねぇんだ。@KEY()↓
@WI(60)↓
◆Ｍｙ　ｗｉｆｅ’ｓ　ｔｏｔａｌｌｙ　ｉｇｎｏｒｉｎｇ　ｈｅｒ　Ｍａｇｉｃ　ｃａｋｅ　ｂｕｓｉｎｅｓｓ．@KEY()↓
◆Ｔｈｅｓｅ　ｄａｙｓ　ｓｈｅ　ｓｐｅｎｄｓ　ｈｅｒ　ｔｉｍｅ　ｈａｎｇｉｎｇ　ｏｕｔ　ｉｎ　ａ　ｓｔｒａｎｇｅ　ｃｌｕｂ．@KEY()↓
◆Ｗｅ　ｎｏ　ｌｏｎｇｅｒ　ｈａｖｅ　ａｎｙ　ｍｕｔｕａｌ　ｉｎｔｅｒｅｓｔｓ　ｔｏ　ｄｉｓｃｕｓｓ．@KEY()↓
◆Ｉｓ　ｏｕｒ　ｒｅｌａｔｉｏｎｓｈｉｐ　ｏｖｅｒ？@KEY()↓
◆．．．＊Ｓｉｇｈ＊
@KEYNP()
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆にょうぼが↓
;jpn:　「マジックケーキ」うりの↓
;jpn:　しょうばい　そっちのけで@KEY()↓
;jpn:◆おかしな　みせに↓
;jpn:　いりびたっててよう。@KEY()↓
;jpn:◆はなしが　ぜんぜん↓
;jpn:　あわなくなっちまったんだ。@KEY()↓
;jpn:◆おれたち　もう　おしまいかなぁ。↓
;jpn:　‥‥フー。@KEYNP()
@SETF(FLG_TEMP_9)
』
_TOTO_SAILOR_TMP;
◆Ｄｏ　ｙｏｕ　ｗａｎｎａ　ｈｅａｒ　ｔｈｅ　ｓａｍｅ　ｓｔｏｒｙ　ａｇａｉｎ？↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆なんども　おんなじはなしを↓
;jpn:　きくんだな？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_YES,_TOTO_SAILOR_A_NO)
@GOTO(_TOTO_SAILOR_A_NO)

_TOTO_SAILOR_AFTER;
@CHKFGOTO(FLG_TOTO_SAILOR_MSGCHG,_TOTO_SAILOR_AFTER_MAIN)
◆Ｔｈａｎｋ　ｙｏｕ！@KEY()↓
◆Ｙｏｕ　ｍａｄｅ　ｍｙ　ｗｉｆｅ　ｗａｋｅ　ｕｐ．@KEY()↓
◆Ｓｈｅ　ｑｕｉｔ　ｔａｌｋｉｎｇ　ａｂｏｕｔ　ａｌｌ　ｔｈａｔ　ｓｅｒｉｏｕｓ　ｃｒａｐ．．．@KEY()↓
◆Ｙｅａｈ！@KEY()↓
◆Ｌｅｔ’ｓ　ｗｏｒｋ　ｈａｒｄ！@KEY()↓
;jpn:◆あんたたちの　おかげで↓
;jpn:　にょうぼが↓
;jpn:　めを　さましてくれた。@KEY()↓
;jpn:◆ぜんっぜん　ムツカシイことも↓
;jpn:　いわなくなったし‥‥。@KEY()↓
;jpn:◆さぁ！@WI(15)　おれも　はりきるぞ！@KEY()↓
@SETF(FLG_TOTO_SAILOR_MSGCHG)
;
_TOTO_SAILOR_AFTER_MAIN;２度目以降
◆Ｉｆ　ｙｏｕ’ｒｅ　ｃｏｕｒａｇｅｏｕｓ，　ｇｅｔ　ｏｎ　ｔｈｉｓ　ｂｏａｔ．@KEY()↓
◆Ｙｏｕ’ｌｌ　ｐｒｏｂａｂｌｙ　ｓｅｅ　ｔｈｅ　Ｋｒａｋｅｎ　ａｎｄ　ｅｘｐｅｒｉｅｎｃｅ　ｇｅｔｔｉｎｇ　ｓｅａｓｉｃｋ！@KEY()↓
◆Ａｆｔｅｒ　ａｌｌ，　ｉｔ　ｃｏｕｌｄ　ｏｎｌｙ　ｃｏｓｔ　ｙｏｕ　ｙｏｕｒ　ｌｉｆｅ，　ａｎｄ　ｙｏｕ　ｇｏｔ　ｔｈａｔ　ｆｏｒ　ｆｒｅｅ！@KEY()↓
◆Ｌｕｃｋ　ｗｉｌｌ　ｄｅｔｅｒｍｉｎｅ　ｔｈｅ　ｏｕｔｃｏｍｅ　ｏｆ　ｔｈｉｓ　ｖｏｙａｇｅ．@KEY()↓
◆Ｓｏ，　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓａｉｌ　ｔｈｅ　ｓｅａｓ　ｔｏ　Ｓｃａｒａｂａ？@KEY()↓
;jpn:◆ゆうきのあるやつなら↓
;jpn:　ふねに　のんなよ。@KEY()↓
;jpn:◆クラーケンも　みられるし↓
;jpn:　ふなよいも　けいけんできるぜ。@KEY()↓
;jpn:◆どうせ　ただでもらった　いのち。↓
;jpn:　ひろうも　おとすも　うんしだい。↓
;jpn:　スカラビに　わたるかね？@KEY()↓
_TOTO_SAILOR_LATER_MAIN;;
◆Ｔｗｅｎｔｙ　ｂｕｃｋｓ　ｐｅｒ　ｐｅｒｓｏｎ　ｉｓ　ｆｉｎｅ　ｗｉｔｈ　ｍｅ．↓
;jpn:◆ひとり　２０ドルで　いいぜ。↓
@WINR_MONEY()
<Ｙｅｓ>
<Ｎｏ>

;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_TOTO_SAILOR_A_AFTER_YES,_TOTO_SAILOR_A_AFTER_NO)

_TOTO_SAILOR_A_AFTER_NO;
◆Ｉ　ｕｎｄｅｒｓｔａｎｄ．@KEY()↓
◆Ｓｔａｙ　ｈｅｒｅ　ａｎｄ　ｓｈｉｖｅｒ　ｉｎ　ｆｅａｒ　ｆｏｒ　ｙｏｕｒ　ｆｕｔｕｒｅ！@KEY()↓
◆Ｈａ　ｈａ　ｈａ　ｈａ　ｈａ　ｈａ！
@KEYNP()
;jpn:◆そうか　むりもないな。↓
;jpn:　そのへんで　ぶるぶるふるえてな。@WI(20)↓
;jpn:　ハハハハハ！@KEYNP()
』

_TOTO_SAILOR_A_AFTER_YES;
@MUL_ACTIVE_PLAYER(20)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_TOTO_SAILOR_A_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(0)
@WINR_MONEY()
◆Ｒｅａｄｙ！@KEY()↓
◆Ｗｅ’ｒｅ　ｒｅｃｋｌｅｓｓ，　ｂａｂｙ！@KEY()↓
◆Ｂｏｎ　Ｖｏｙａｇｅ！
@KEYNP()
;jpn:◆ようし！↓
;jpn:　いのちしらずたちよ！↓
;jpn:　ヨーソロー！@KEY()
@CLOSEALL()
@GOTO(MSG_EVT_85_ONBOARD)
』

_TOTO_SAILOR_A_NOMONEY;
◆Ｗｈａｔ？@KEY()↓
◆Ｙｏｕ　ｈａｖｅ　ｎｏ　ｍｏｎｅｙ？！@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ａｆｔｅｒ　ｙｏｕ　ｍａｋｅ　ｓｏｍｅ　ｍｏｎｅｙ．
@KEYNP()
;jpn:◆えっ　かねがない？！↓
;jpn:　どっかで　かせいで　またおいで。@KEYNP()
』
_TOTO_SAILOR_LATER;
◆Ｃｏｍｐａｒｅｄ　ｔｏ　ｔｈｅ　ｏｌｄｅｎ　ｄａｙｓ，　ｔｈｉｓ　ｂｏａｔ　ｒｉｄｅ　ｉｓ　ｌｉｋｅ　ｂｅｉｎｇ　ｏｎ　ａ　ｌｕｘｕｒｙ　ｌｉｎｅｒ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ａｎｏｔｈｅｒ　ｒｉｄｅ？@KEY()↓
◆Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　ａ　ｒｉｄｅ　ｉｆ　ｙｏｕ　ｗａｎｔ，　ｓｉｎｃｅ　ｙｏｕ　ｄｅｓｔｒｏｙｅｄ　ｔｈｅ　Ｋｒａｋｅｎ．@KEY()↓
;jpn:◆むかしにくらべりゃ↓
;jpn:　この　ふねのたびも↓
;jpn:　まるで　ゆうらんせんさ。@KEY()↓
;jpn:◆おまえたちが　クラーケンを↓
;jpn:　たいじしてくれたから‥‥@WI(30)↓
;jpn:　また　のるかい？@KEY()↓
@GOTO(_TOTO_SAILOR_LATER_MAIN)

MSG_CAT_1;ネコ
◆Ｆｓｓｔ　Ｆｓｓｔ．
@KEYNP()
;DAN: Just ask me.
;jpn:◆ゴロゴロ@KEYNP()
』
MSG_CAT_2;やなぎのネコ
◆Ｍｅｏｗ．
@KEYNP()
;jpn:◆ニャア@KEYNP()
』
;-------------------------------------------------

MSG_SUMS_STOIC_WIFE;マジックケーキ売り（ストイック）
◆Ｉ’ｖｅ　ｆｉｎａｌｌｙ　ａｗａｋｅｎｅｄ　ｔｈｅ　ｉｎｎｅｒ　ｍｅ，　ｔｈｅ　ｔｒｕｅ　ｓｅｌｆ．@KEY()↓
◆Ｔｈｅ　ｐａｔｒｏｎｓ　ｏｆ　ｔｈｉｓ　ｃｌｕｂ　ａｒｅ　ａｂｌｅ　ｔｏ　ｓｔａｒｅ　ｉｎｔｏ　ｔｈｅｉｒ　ｏｗｎ　ｓｏｕｌ　ｈａｒｄ@KEY()↓
◆ｅｎｏｕｇｈ　ｔｏ　ｂｕｒｎ　ａ　ｈｏｌｅ　ｉｎ　ｔｈｅｉｒ　ｐｓｙｃｈｅ．@KEY()↓
◆Ｉ’ｍ　ｎｏｗ　ｃｏｍｆｏｒｔａｂｌｅ　ｅｎｏｕｇｈ　ｔｏ　ｓｔａｒｅ　ａｔ　ｔｈｅ　ｒｅａｌ　ｍｅ，　ｔｈｅ　ｔｒｕｅ　ｓｅｌｆ，@KEY()↓
◆ａｎｄ　ｂｕｒｎ　ｔｈｅ　ｉｍｐｒｅｓｓｉｏｎ　ｉｎｔｏ　ｍｙ　ｓｕｐｅｒ－ｅｇｏ．@KEY()↓
◆Ｉ　ｗａｎｔ　ｔｏ　ｂｅ　ｉｎ　ｔｈｉｓ　ｃｏｍｆｏｒｔ　ｚｏｎｅ　ａｔ　ａｎｙ　ｔｉｍｅ，　ａｌｌ　ｔｈｅ　ｔｉｍｅ　ｏｒ　ａｔ　ｎｏ　ｔｉｍｅ．@KEY()↓
◆Ｍｙ　ｉｄ　ｉｓ　ｔｅｌｌｉｎｇ　ｍｅ．．．
;jpn:◆わたし　やっと　このごろ↓
;jpn:　じいしきに　めざめたと↓
;jpn:　いっていいとおもうの。@KEY()↓
;jpn:◆このクラブの　ひとたちって@KEY()↓
;jpn:◆じこの　そんざいを↓
;jpn:　あなが　あくほど↓
;jpn:　みつめていて‥‥@KEY()↓
;jpn:◆わたし　あながあきそうに↓
;jpn:　ここちいい　じこよ。@KEY()↓
;jpn:◆しろくじちゅうも↓
;jpn:　ごろくじちゅうも@KEY()↓
;jpn:◆このみせに↓
;jpn:　そんざいしていたいわ。
@CHKFGOTO(FLG_SUMS_MASSAGE_APPEAR,_SUMS_STOIC_WIFE_TMP)
@KEYNP()
』
_SUMS_STOIC_WIFE_TMP;
@KEY()↓
◆Ｗｈａｔ？　　Ｗｈａｔ？@WI(15)　　Ｍａｇｉｃ　Ｃａｋｅ？@KEY()↓
◆Ｙｏｕ　ｃａｍｅ　ａｌｌ　ｔｈｉｓ　ｗａｙ　ｊｕｓｔ　ｔｏ　ｅａｔ　ｍｙ　Ｍａｇｉｃ　Ｃａｋｅ？↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆えっ@WI(20)　マジックケーキですって？↓
;jpn:　わたしの　マジックケーキを↓
;jpn:　たべたくて　わざわざ　ここまで？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SUMS_STOIC_WIFE_YES,_SUMS_STOIC_WIFE_NO)
_SUMS_STOIC_WIFE_NO;
◆Ｏｋａｙ　ｔｈｅｎ，　ｄｏｎ’ｔ　ｇｅｔ　ｉｎ　ｍｙ　ｗａｙ　ｗｈｉｌｅ　Ｉ　ｓｅａｒｃｈ　ｆｏｒ　ｔｈｅ　ｌｉｔｔｌｅ　ｇｉｒｌ　ｗｉｔｈｉｎ　ｍｅ．．．
@KEYNP()
;jpn:◆そう‥‥じゃ　わたしの↓
;jpn:　なんかいのだいぼうけんというか↓
;jpn:　むつかしばなしというか‥‥の@KEY()↓
;jpn:◆じゃまな　きんしを　しないで。@KEYNP()
』
_SUMS_STOIC_WIFE_YES;
◆Ｉ　ｓｅｅ．．．ｏｋａｙ．．．@KEY()↓
◆Ｗｈｙ　ｄｏｎ’ｔ　ｙｏｕ　ｓｔｏｐ　ｂｙ　ａ　ｌｉｔｔｌｅ　ｃａｒｔ　ｏｕｔ　ｏｎ　ｔｈｅ　ｂｅａｃｈ　ｌａｔｅｒ？
@KEYNP()
;jpn:◆‥‥そ@WI(15)　そう。↓
@WI(60)↓
;jpn:　‥‥‥。@KEY()↓
;jpn:◆じゃ　あとで　ビーチの↓
;jpn:　ワゴンまで　いらっしゃい。@KEY()
@CLOSEALL()
;ケーキ妻を階段に消えるアニメと交換
@REMOVE_CHAR( PRSN_SUMS_STOIC_G, ANIM_GO_OUT_CAKEWIFE )
@WAITSYS()	;ケーキ妻が階段に消えるのをじっと待つ
@SETF(FLG_SUMS_STOIC_WIFE_DISAPPEAR)
』
;-------------------------------------------------

;更に追加分

MSG_SUMS_SWIMSUITMAN_E;
◆Ｏｎｌｙ　ａ　ｔａｎｎｉｎｇ　ｐｒｏ　ｌｉｋｅ　ｍｅ　ｉｓ　ａｂｌｅ　ｔｏ　ｇｅｔ　ａｎ　ａｃｔｕａｌ　ｓｕｎｔａｎ　ｏｎ　ｔｈｅ　ｐａｌｍｓ　ｏｆ　ｈｉｓ　ｈａｎｄｓ！
@KEYNP()
;jpn:◆（おれみたいな　ひやけのプロは@WI(20)↓
;jpn:　こうして　てのひらもやくもんだ）@KEYNP()
』
MSG_SUMS_SWIMSUITGAL_C;
◆Ｉ’ｍ　ｊｕｓｔ　ｔｒｙｉｎｇ　ｔｏ　ｔａｋｅ　ａ　ｎａｐ　ｉｎ　ｔｈｅ　ｓｈａｄｅ．　　Ｄｏｎ’ｔ　ｂｏｔｈｅｒ　ｍｅ！
@KEYNP()
;jpn:◆（ひかげで　ひるねしてるの。@WI(20)↓
;jpn:　じゃましないでね）@KEYNP()
』
;-------------------------------------------------

MSG_SUMS_RESTAURANT_E;
◆Ｐｏｏｏｏｗｅｅｅｅｔ！@WI(60)↓
　　Ｏｏｏｏ．．．ｓｏｒｒｙ．．．@KEY()↓
◆Ｙ’ｋｎｏｗ，　Ｉ　ｃａｎ’ｔ　ｑｕｉｔｅ　ｄｅｓｃｒｉｂｅ　ｉｔ．．．@KEY()↓
◆Ｄｒｉｎｋｉｎｇ　ｇｌａｓｓ　ａｆｔｅｒ　ｇｌａｓｓ　ｏｆ　ｉｃｅ　ｃｏｆｆｅｅ　ｉｓ．．．ｗｅｌｌ．．．@KEY()↓
◆Ｂｕｕｕｕｒｐ！@WI(90)↓
　　Ｏｏｏｏ．．．’ｓｃｕｓｅ　ｍｅ．．．
@KEYNP()
;jpn:◆プハーーーーッ！@WI(90)↓
;jpn:　いや　しっけいしっけい。@KEY()↓
;jpn:◆なんちゅうか　この↓
;jpn:　ひるまのビールっちゅうのは↓
;jpn:　じつに　なんちゅうか‥‥@KEY()↓
;jpn:◆ゲフーッ！@WI(90)↓
;jpn:　いや　しっけいしっけい。@KEYNP()
』
;-------------------------------------------------

;それに輪をかけて追加分
;0717

MSG_TOTO_WELCOME
◆（Ｅａｓｔ　ｏｆ　ｈｅｒｅ　ｉｓ　ｔｈｅ　ｐｏｒｔ　ｔｏｗｎ　ｏｆ　Ｔｏｔｏ）@KEY()↓
◆．．．Ｎｏ，　ｎｏ．．．↓
　　Ｉ’ｍ　ｎｏｔ　ａ　ｂｉｌｌｂｏａｒｄ．．．
@KEYNP()

;jpn:◆（ここから　ひがしは↓
;jpn:　みなとのあるまち「トト」）↓
@KEY()↓
;jpn:◆@WI(10)‥‥わ　@WI(20)わしは↓
;jpn:　かんばんじゃ　ないぞ。@KEYNP()
』


;《ストイッククラブの近く》
MSG_READ_SUMMERS_SIGN3
◆（Ｈａｖｅ　ａ　ｆａｎｔａｓｔｉｃ　ｖａｃａｔｉｏｎ！@KEY()↓
◆Ａｔ　ｌｅａｓｔ　ｕｎｔｉｌ　ｙｏｕ　ｒｕｎ　ｏｕｔ　ｏｆ　ｍｏｎｅｙ．↓
　　　　　　Ｈｏｔｅｌ　Ｄｕ　Ｓｕｍｍｅｒｓ）
@KEYNP()
;jpn:◆（よいバカンスを！@WI(20)↓
;jpn:　あなたの　おかねのつづくかぎり）↓
;jpn:　　　　　「オテル・ド・サマーズ」@KEYNP()
』


;《病院の近く》
MSG_READ_SUMMERS_SIGN5
◆Ｔｈｅｒｅ　ｉｓ　ｇｒａｆｆｉｔｉ　ｏｎ　ｔｈｅ　ｂｏａｒｄ．．．Ｔｈｅ　ｈａｎｄｗｒｉｔｉｎｇ　ｉｓ　ｈａｒｄ　ｔｏ　ｒｅａｄ．．．@KEY()↓
◆（@DSP_NAME(PC_NESS)　ｃａｎ　ｅａｔ　ｍｙ　ｓｈｏｒｔｓ！@WI(20)↓
　　Ｆｏｒ　ａ　ｎｅｉｇｈｂｏｒ，　ｈｅ’ｓ　ａ　ｌｏｓｅｒ！）
@KEYNP()
;jpn:◆かんばんには　へたなもじで↓
;jpn:　らくがきが　されていた。@KEY()↓
;jpn:◆（ボンジュール　@DSP_STS(STS_PC_NAME_NES)！@WI(20)↓
;jpn:　おまえが　これをよんでるころ↓
;jpn:　おれは　もう　へっへっへ！）@KEYNP()
』
;-------------------------------------------------
