;-------------------------------------------------

;@Habitat:スカラビ／ドラッグストア／ドラッグストア
;@Person:店員
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_DRUG
MSG_SKRB_DRUG;@MiuraAppended
@GOSUB(MSG_SHOP_SKRB_DRUG)
』

；----------------------------------------
;@Habitat:スカラビ／ホテル／ホテル
;@Person:フロント
;@Figure:スカラビ男Ａ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOTEL
;MSG_SKRB_HOTEL;
;◆「グレート・サザーン・ホテル」へ↓
;　ようこそ！@KEY()↓
;@GOSUB(MSG_GLOBAL_HOTEL)
;』

;@Habitat:スカラビ／ホテル／ホテル
;@Person:キャッシュディスペンサ
;@Figure:ＣＤ
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:MSG_GLOBAL_CD_RECEIVE
;@CheckMessage:MSG_GLOBAL_CASHDISPENSER
;@Message:0

;@Habitat:スカラビ／ホテル／ホテル
;@Person:武器専門男
;@Figure:武器男
;@AppearanceKey:0
;@ActionScript:◆きょろきょろ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_WEAPON
MSG_SKRB_WEAPON;@MiuraAppended
@GOSUB(MSG_SHOP_SKRB_WEAPON)
』

；----------------------------------------
;@Habitat:スカラビ／住人の家Ｂ／住人の家Ｂ
;@Person:住人
;@Figure:スカラビ女
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOUSE_B
MSG_SKRB_HOUSE_B;
◆Ｎｏ，　Ｉ　ｄｏｎ’ｔ　ｗａｎｔ　ａｎｙ　ｍｕｍｍｙ　ｂａｎｄａｇｅｓ！@KEY()↓
◆Ｎｏ　ｓｏｌｉｃｉｔｉｎｇ　ａｌｌｏｗｅｄ　ｐｌｅａｓｅ！
@KEYNP()
;jpn:◆ミイラのほうたいなんか↓
;jpn:　いらないよ！↓
;jpn:　おしうりおことわり！@KEYNP()
』

;@Habitat:スカラビ／住人の家Ｃ／住人の家Ｃ
;@Person:住人
;@Figure:おじいさん
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOUSE_C
MSG_SKRB_HOUSE_C;
◆Ｉ’ｖｅ　ｎｅｖｅｒ　ｓｅｅｎ　ｙｏｕ　ａｒｏｕｎｄ　ｈｅｒｅ．@KEY()↓
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ？@KEY()↓
◆Ｉ　ｄｏ　ｎｏｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｙｏｕ　ｗｏｕｌｄ　ｗａｎｔ．
@KEYNP()
;jpn:◆このへんじゃ　みかけないかおだ。↓
;jpn:　なにかようかな。↓
;jpn:　わしのほうからは　ようはないよ。@KEYNP()
』

；----------------------------------------
;@Habitat:スカラビ／病院／受付
;@Person:受付嬢
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOSPITAL_USHER
MSG_SKRB_HOSPITAL_USHER;@MiuraAppended
;◆どなたに　ごめんかいですか？@KEY()
@GOSUB(MSG_NURSE_SKRB)
;@GOSUB(MSG_SHOP_SKRB_HOSPITAL)
』

;@Habitat:スカラビ／病院／病院
;@Person:医者
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HOSPITAL_DOCTOR
MSG_SKRB_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
;　だれだね？@KEY()
@GOSUB(MSG_DOCTOR_SKRB)
』

；----------------------------------------
;@Habitat:スカラビ／フィールド／港の付近
;@Person:港の人
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_HARBOR
MSG_SKRB_HARBOR;
◆Ｄｉｄ　ｙｏｕ　ｃｏｍｅ　ｆｒｏｍ　Ｔｏｔｏ　ｂｙ　ｓｈｉｐ？@KEY()↓
◆Ｔｈｅｒｅ’ｓ　ａ　ｓｃａｒｙ　ｍｏｎｓｔｅｒ　ｉｎ　ｔｈｅ　ｓｅａ．．．@KEY()↓
◆．．．Ｄｉｄ　ｙｏｕ　ｂｅａｔ　ｈｉｍ？@KEY()↓
◆Ｏｒ　ｄｉｄ　ｙｏｕ　ｅｓｃａｐｅ？@KEY()↓
◆Ｅｉｔｈｅｒ　ｗａｙ，　ｙｏｕ　ａｒｅ　ｆａｎｔａｓｔｉｃ！
@KEYNP()
;jpn:◆あんたがた　トトから　ふねで？！↓
;jpn:　うみには　おそろしいばけものが↓
;jpn:　いたっていうのに‥‥@KEY()↓
;jpn:◆‥‥やっつけたのか。↓
;jpn:　うまく　にげられたのか？↓
;jpn:　どっちにしても　たいしたものだ。@KEYNP()
』

;@Habitat:スカラビ／フィールド／蛇屋付近
;@Person:蛇屋の人集りＡ
;@Figure:スカラビ男Ａ
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_A
MSG_SKRB_SNAKESHOP_A;
◆Ｓｎａｋｅｓ　ａｒｅ　ｓｏ　ｕｎｐｌｅａｓａｎｔ，　ｂｕｔ　ｓｏ　ｃｕｔｅ．．．@KEY()↓
◆Ｏｈ，　Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈａｔ　Ｉ　ｍａｙ　ｂｅ　ｓａｙｉｎｇ．
@KEYNP()
;jpn:◆へびは　きもちわるいけど↓
;jpn:　けっこう　かわいい‥けど↓
;jpn:　ああ@KEY()↓
;jpn:◆おれ　なにいってるのか↓
;jpn:　わかんないや。@KEYNP()
』

;@Habitat:スカラビ／フィールド／蛇屋付近
;@Person:蛇屋の人集りＢ
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_B
MSG_SKRB_SNAKESHOP_B;
◆Ｓｈｏｕｌｄ　Ｉ　ｋｅｅｐ　ａ　ｓｎａｋｅ　ａｔ　ｈｏｍｅ？@KEY()↓
◆Ｐｅｒｈａｐｓ　Ｉ　ｓｈｏｕｌｄ　”ａｓｐ”　ａｎ　ｅｘｐｅｒｔ．
@KEYNP()
;jpn:◆へび　かおうかなぁ↓
;jpn:　うちでかうには↓
;jpn:　ちょっと　ヘビーかな。@KEYNP()
』

;@Habitat:スカラビ／フィールド／蛇屋付近
;@Person:蛇屋の人集りＣ
;@Figure:スカラビ女
;@AppearanceKey:0
;@ActionScript:◆背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_C
MSG_SKRB_SNAKESHOP_C;
◆Ｐｏｉｓｏｎｏｕｓ　ｓｎａｋｅｓ　ｃｏｓｔ　ｍｏｒｅ．@KEY()↓
◆Ｗｈｙ　ｗｏｕｌｄ　ａ　ｆｉｎｅ　ｙｏｕｎｇ　ｍａｎ　ｌｉｋｅ　ｙｏｕ　ｎｅｅｄ　ｏｎｅ？
;＠ポーラだったら「ｌａｄｙ」
@KEYNP()
;jpn:◆どくへびのほうが↓
;jpn:　ねだんが　たかいのねぇ↓
;jpn:　なんにつかうのかしら。@KEYNP()
』

;@Habitat:スカラビ／フィールド／蛇屋付近
;@Person:へび袋売り
;@Figure:スカラビ男Ｂ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_D
MSG_SKRB_SNAKESHOP_D;
◆Ｔｈｅ　@DSP_GOODS(GDS_TOOL_SNAKE_BAG)　ｃａｎ　ｈｏｌｄ　ｌｉｖｅ　ｓｎａｋｅｓ！@WI(20)　　Ｔｈｅｒｅ　ａｒｅ　ｓｎａｋｅｓ　ｉｎ　ｔｈｅ　ｓａｃｋ！@KEY()↓
◆Ｐｌｅａｓｅ，　ｉｔ　ｉｓ　ａ　ｖｅｒｙ　ｕｓｅｆｕｌ　ｉｔｅｍ！@KEY()↓
◆Ｓｈａｌｌ　ｙｏｕ　ｂｕｙ　ｏｎｅ？　　Ｉ　ａｍ　ｈｕｍｂｌｙ　ｏｆｆｅｒｉｎｇ　ｉｔ　ｔｏ　ｙｏｕ．．．↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆へびのはいった　へびぶくろ。↓
;jpn:　ふくろのなかには　へびがいる。↓
;jpn:　やくにたつよ。　かうか？@KEY()↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_SNAKESHOP_D_YES,_SKRB_SNAKESHOP_D_NO)

_SKRB_SNAKESHOP_D_NO;
◆Ｙｏｕ　ａｒｅ　ａｆｒａｉｄ　ｏｆ　ｓｎａｋｅｓ，　ａｒｅ　ｙｏｕ　ｎｏｔ？@KEY()↓
◆Ｈｅｈ　ｈｅｈ　ｈｅｈ．
@KEYNP()
;jpn:◆へびが　こわいんだろ↓
;jpn:　へっへっへ。@KEYNP()
』

_SKRB_SNAKESHOP_D_YES;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SKRB_SNAKESHOP_D_ITEMFULL)
◆Ｔｈａｔ　ｉｓ　２９０　ｄｏｌｌａｒｓ，　ｋｉｎｄ　@XCHG()@GOSUB(MSG_ESUB_SIR_MAAM)．↓
@WINR_MONEY()
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆２９０ドルだ。↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_SNAKESHOP_D_BUY,_SKRB_SNAKESHOP_D_NO)
@GOTO(_SKRB_SNAKESHOP_D_NO)

_SKRB_SNAKESHOP_D_BUY;
@Q_MONEY(290)
@TRUE_GOTO(_SKRB_SNAKESHOP_D_NOMONEY)
@Q_GOODSFULL(PC_ALL)
@GOODSIN_PLAYER(0,GDS_TOOL_SNAKE_BAG)
@SE(SE_se76_my_give)
@MONEYOUT(98)
@WINR_MONEY()
@SE(SE_se78_my_open_rock)
◆Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　ａ　ｄｉｓｃｏｕｎｔ　ａｓ　ｔｈｅ　ｓａｃｋ　ｈａｓ　ａ　ｈｏｌｅ　ｉｎ　ｉｔ．@KEY()↓
◆（Ｓｎａｋｅ　ｓａｃｋ　ｄｅａｌｅｒ　ｍａｒｋｅｄ　ｔｈｅ　ｐｒｉｃｅ　ｄｏｗｎ　ｔｏ　９８　ｄｏｌｌａｒｓ　ｆｒｏｍ　２９０　ｄｏｌｌａｒｓ．）
@KEYNP()
;jpn:◆あなが　あいてるから↓
;jpn:　やすくしておいたよ。@KEY()↓
;jpn:◆（ヘビぶくろうりは↓
;jpn:　２９０ドルを↓
;jpn:　９８ドルにしてくれた）
@KEYNP()
』

_SKRB_SNAKESHOP_D_NOMONEY;
◆Ｗｉｔｈｏｕｔ　ａｎｙ　ｍｏｎｅｙ，　Ｉ　ｃａｎｎｏｔ　ｓｅｌｌ　ｔｏ　ｙｏｕ．．
@KEYNP()
;jpn:◆かねがなくちゃあ↓
;jpn:　かえねえな。@KEYNP()
』

_SKRB_SNAKESHOP_D_ITEMFULL;
◆Ｓｉｎｃｅ　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｉｔｅｍｓ，　Ｉ　ｈｕｍｂｌｙ　ｋｅｅｐ　ｔｈｉｓ　ｉｍｐｏｒｔａｎｔ　@DSP_GOODS(GDS_TOOL_SNAKE_BAG)．
@KEYNP()
;jpn:◆ガラクタばっかり↓
;jpn:　かかえこんでるから@KEY()↓
;jpn:◆たいせつな　へびぶくろが↓
;jpn:　もてねえようだぜ。@KEYNP()
』



;@Habitat:スカラビ／フィールド／蛇屋
;@Person:へび屋（パンチョ）
;@Figure:へび屋のパンチョ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_SNAKESHOP_PANCHO
MSG_SKRB_SNAKESHOP_PANCHO;
;◆ハイ　レッドスネーク・カモン！↓
;　キッス　オブ　ファイア。↓
;　わきげのエサ‥‥はくしゅー！@KEY()
@GOSUB(MSG_SHOP_SKRB_SNAKE)
』

;@Habitat:スカラビ／フィールド／バザールの場
;@Person:バザールの男（ゴザールさん）
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_GOZAR
MSG_SKRB_GOZAR;
;◆めずらしいもの　いろいろあるよ。↓
;　あったら　べんり↓
;　なければ　たいへん！@KEY()↓
;◆メニューみて　きめなはれ。@KEY()
@GOSUB(MSG_SHOP_SKRB_BAZAR)
』

;@Habitat:スカラビ／フィールド／バザールの場
;@Person:バザールのヤジ馬Ａ
;@Figure:スカラビ男Ａ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_BAZAR_A
MSG_SKRB_BAZAR_A;＄β
◆Ｉ　ｂｏｕｇｈｔ　ａ　”@DSP_GOODS(GDS_TOOL_NOSE_PIG)．”@KEY()↓
◆Ｔｈｉｓ　ｗｉｌｌ　ｈｅｌｐ　ｏｕｔ　ａ　ｌａｒｇｅ　ａｍｏｕｎｔ@KEY()↓
◆ｗｈｉｌｅ　Ｉ　ａｍ　ｈｕｍｂｌｙ　ｓｅａｒｃｈｉｎｇ　ｆｏｒ　ｔｈｅ　Ｍａｇｉｃ　ｔｒｕｆｆｌｅ　ｉｎ　ｔｈｅ　Ｄｅｅｐ　Ｄａｒｋｎｅｓｓ．@KEY()↓
◆Ｙｏｕ　ｔｏｏ　ｃａｎ　ｌｅａｒｎ　ｈｏｗ　ｔｏ　ｕｓｅ　ａ　@DSP_GOODS(GDS_TOOL_NOSE_PIG)　ｗｉｔｈ　ｔｈｅ　”Ｕｓｅ”　ｃｏｍｍａｎｄ　ｕｎｄｅｒ　”Ｇｏｏｄｓ．”@KEY()↓
◆Ｓｏ　ｐｌｅａｓｅ　ｒｅｓｔ　ｅａｓｙ．
@KEYNP()
;jpn:◆ぼく「ブタのはな」を↓
;jpn:　かったんだよ。@KEY()↓
;jpn:◆まきょうに　はえている↓
;jpn:　マジックトリフを↓
;jpn:　みつけるのには　これはべんりさ。@KEY()↓
;jpn:◆「ブタのはな」の　つかいかたは↓
;jpn:　「せつめい」で↓
;jpn:　わかるらしいから@KEY()↓
;jpn:◆あんしんだね。@KEYNP()
;◆なんのことだか↓
;　ぼく　わかんないや。@KEYNP()
』
;◆ぼく「ぶたのはな」を↓
;　かったんだよ。@KEY()↓
;◆マジックトリフを↓
;　みつけるのには　これはべんりさ。@KEYNP()
;』

;@Habitat:スカラビ／フィールド／バザールの場
;@Person:占師
;@Figure:ロープマジック男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_FORTUNETELLER
MSG_SKRB_FORTUNETELLER;＃
@CHKFGOTO(FLG_WIN_GIEGU,_SKRB_FORTUNETELLER_END)
◆Ｏｈ，　ｙｏｕ　ｈａｖｅ　ｔｈｅ　ｍａｒｋ　ｏｆ　ｂａｄ　ｌｕｃｋ　ｏｎ　ｙｏｕｒ　ｆａｃｅ．．．@KEY()↓
◆Ｎｏ．．．Ｄｏｎ’ｔ　ｗｏｒｒｙ．．．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｋｎｏｗ，　Ｉ’ｌｌ　ｈｕｍｂｌｙ　ｔｅｌｌ　ｙｏｕ．@KEY()↓
◆”Ｙｏｕ　ｓｈａｌｌ　ｃｏｍｅ　ｂａｃｋ　ｈｅｒｅ．．．@KEY()↓
◆Ａｆｔｅｒ　ｙｏｕ　ｈａｖｅ　ｅｎｃｏｕｎｔｅｒｅｄ　ａ　ｄａｎｇｅｒｏｕｓ　ｓｉｔｕａｔｉｏｎ．”@KEY()↓
◆Ｈｏｗｅｖｅｒ，　Ｉ　ｍａｙ　ｂｅ　ｗｒｏｎｇ，　ａｎｄ　ｉｆ　ｓｏ．．．ａ　ｔｈｏｕｓａｎｄ　ｐａｒｄｏｎｓ．
@KEYNP()
;jpn:◆おっ@WI(20)　あんたのかおには↓
;jpn:　ふきつな　かげが‥‥@WI(60)↓
;jpn:　いや‥‥き@WI(15)　きにせんでもいい‥‥@KEY()↓
;jpn:◆どうしても　ききたいなら　いう。@WI(30)↓
;jpn:　あんたは　ひどいめにあって↓
;jpn:　ここに　もどってくる‥‥。@KEY()↓
;jpn:◆しかし　そんなことは↓
;jpn:　ぜーんぜん　ないかも　しれない。@KEYNP()
』
_SKRB_FORTUNETELLER_END;＆
◆Ｏｈ！@KEY()↓
◆Ｙｏｕ　ｈａｖｅ　ｔｈｅ　ｍａｒｋ　ｏｆ　ｂａｄ　ｌｕｃｋ　ｏｎ　ｙｏｕｒ　ｆａｃｅ．．．@KEY()↓
◆Ｙｅｔ，　Ｉ　ｃｏｕｌｄ　ｂｅ　ｗｒｏｎｇ，　ａｓ　ｙｏｕ　ｄｉｄｎ’ｔ　ｗａｓｈ　ｙｏｕｒ　ｆａｃｅ　ｌａｔｅｌｙ．
@KEYNP()
;jpn:◆あらま！@WI(20)　あんたのかおには↓
;jpn:　ふけつなかげが‥‥@WI(60)↓
;jpn:　たぶん　よごれてるだけだろうが。@KEYNP()
』

;@Habitat:スカラビ／フィールド／街のなか
;@Person:いい夢情報の人
;@Figure:スカラビ女
;@AppearanceKey:FLG_PU/off
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_C
MSG_SKRB_C;
◆Ｉｎ　ｔｈｅ　ｐｙｒａｍｉｄ　ｔｈｅｒｅ’ｓ　ｈｉｄｄｅｎ　ｔｒｅａｓｕｒｅ．@KEY()↓
◆Ｍｙ　ｈｕｓｂａｎｄ　ｗａｓ　ｌｏｏｋｉｎｇ　ｆｏｒ　ｉｔ．@KEY()↓
◆Ｂｅｆｏｒｅ　ｈｅ　ｆｏｕｎｄ　ｉｔ．．．ｈｅ　ｓｌｉｐｐｅｄ　ｏｎ　ａ　ｂａｎａｎａ　ｐｅｅｌ．@KEY()↓
◆．．．Ｓｏ　ｈｅ　ｇａｖｅ　ｕｐ　ｔｈｅ　ｓｅａｒｃｈ．
@KEYNP()
;jpn:◆ピラミッドのなかには↓
;jpn:　まだ　たからものが↓
;jpn:　かくされているそうよ。@KEY()↓
;jpn:◆わたしの　おっとは↓
;jpn:　それをねらっていたんだけど↓
;jpn:　こころざしなかばで‥‥@KEY()↓
;jpn:◆‥‥バナナのかわですべって@KEY()↓
;jpn:◆‥‥めげたの。@KEYNP()
』


;プーを仲間にしないでスカラビに来たときのみ出現。
;◆「グレート・サザーン・ホテル」に↓
;　とまると　いいゆめが↓
;　みられるんですって。@KEY()↓
;◆わたしは　じもとのにんげんだから↓
;　なかなかチャンスがないのよ。@KEYNP()
;』

;@Habitat:スカラビ／フィールド／街のなか
;@Person:町の人Ａ
;@Figure:スカラビ男Ｃ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_A
MSG_SKRB_A;
◆Ｔｈｅ　Ｔｅｎｄａ　ｔｒｉｂｅ　ｕｓｅｄ　ｔｏ　ｌｉｖｅ　ｈｅｒｅ．@KEY()↓
◆Ｔｈｅｙ　ｗｅｎｔ　ｔｏ　ｔｈｅ　ｂａｃｋ　ｏｆ　ｔｈｅ　Ｄｅｅｐ　Ｄａｒｋｎｅｓｓ　ａｓ　ｔｈｅｙ　ｗｅｒｅ　ｔｏｏ　ｉｎｎｏｃｅｎｔ．@KEY()↓
◆Ｉ　ｗｏｎｄｅｒ　ｉｆ　ｔｈｅｙ　ａｒｅ　ｓｔｉｌｌ　ａｌｉｖｅ．
@KEYNP()
;jpn:◆むかし　グミぞくって　ひとびとが↓
;jpn:　いたらしいんだけど↓
;jpn:　あんまり　ひとのいいやつらなんで@KEY()↓
;jpn:◆まきょうの　おくへ↓
;jpn:　おいやられちゃったんだよ。↓
;jpn:　まだ　いるんだろうかねぇ。@KEYNP()
』

;@Habitat:スカラビ／フィールド／街を出たところ
;@Person:町の人Ｂ
;@Figure:スカラビ男Ａ
;@AppearanceKey:0
;@ActionScript:◆小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_B
MSG_SKRB_B;
◆Ｉｆ　ｙｏｕ’ｒｅ　ｇｏｉｎｇ　ｔｏ　ｔｈｅ　Ｐｙｒａｍｉｄ，　ｐｒｅｐａｒｅ　ｗｅｌｌ，@KEY()↓
◆ａｎｄ　ｂｅ　ｒｅａｄｙ　ｆｏｒ　ｗｈａｔｅｖｅｒ　ｍａｙ　ｏｃｃｕｒ．
@KEYNP()
;jpn:◆ピラミッドに　いくんだったら↓
;jpn:　かなり　かくごして　いきなよ。@KEYNP()
』

;@Habitat:スカラビ／フィールド／スフィンクス付近
;@Person:水売り
;@Figure:スカラビ男Ｂ
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_WATERSHOP
MSG_SKRB_WATERSHOP;
@GOSUB(MSG_SKRB_WATER)
』
;◆のどの　かわいたたびびとに↓
;　みずを　うってあげましょう。↓
;　たかいよ　１００ドル。@KEY()
;』

;@Habitat:スカラビ／フィールド／ピラミッド出口
;@Person:幻の老人
;@Figure:幻の老人
;@AppearanceKey:FLG_PU_0/off
;@ActionScript:◆プレイヤーが接近したら竜巻から登場
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_OLDMAN
MSG_SKRB_OLDMAN;
;ピラミッドで「たかのめ」をとって帰ると、こんなふうな
;ものがいる。はなしかけると
;１５００才くらいの老人があらわれる。
@OPEN(1)
◆Ｗｅｌｌ　ｄｏｎｅ．@KEY()↓
◆Ｙｏｕ　ｈａｖｅ　ｍａｄｅ　ｉｔ！@KEY()
;jpn:◆よくぞ　ここまで↓
;jpn:　たどりついた！@KEY()
@CLOSEALL()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@OPEN(1)
◆Ｗｅ　ｆｉｎａｌｌｙ　ｍｅｅｔ，　Ｐｒｉｎｃｅ　@DSP_STS(STS_PC_NAME_POO)．
@KEY()
;jpn:◆とうとう　あえたのう。↓
;jpn:　@DSP_STS(STS_PC_NAME_POO)おうじ。@KEY()
@CLOSEALL()
』
MSG_SKRB_OLDMAN_0;
@OPEN(1)
◆Ｔｈｅ　ｓｔａｒｓ　ｆｏｒｅｔｏｌｄ　ｔｈａｔ　Ｉ　ｗｏｕｌｄ　ｍｅｅｔ　ｙｏｕ　ｈｅｒｅ．．．@KEY()↓
◆Ｓｏ，　ｎｏｗ　ｉｔ’ｓ　ｔｈｅ　ｔｉｍｅ　ｔｏ　ｓｈｏｗ　ｙｏｕ　ｔｈｅ　ｗａｙ　ｏｆ　ｔｈｅ　Ｓｔａｒｓｔｏｒｍ．．．@KEY()↓
;jpn:◆ほしのいちが↓
;jpn:　おまえに　であうことを↓
;jpn:　つたえておったが‥‥やはり。@KEY()↓
;jpn:◆いまこそ↓
;jpn:　「ほしを　おとす　ほうほう」を↓
;jpn:　でんじゅするとき。@KEY()↓
;@CHKFGOTO(FLG_POWR_PINK,_SKRB_OLDMAN_JEFF)
;◆しかしじゃ。そのまえに↓
;　ランマのくにに@KEY()↓
;◆まだ　ゆかねばならぬばしょが↓
;　あろう？　ピンクのくものうえ‥。@KEY()
;@CHKFGOTO(FLG_POWR_RAIN,_SKRB_OLDMAN_GO)
;◆@DSP_STS(STS_PC_NAME_JEFF)！↓
;　あめのふる　なぞのばしょを↓
;　おぼえておろう？@KEY()↓
;◆そこに　ゆくことが↓
;　いま　ひつようなのじゃ。@KEY()↓
;◆そこにゆき　そしてもういちど↓
;　ここに　もどってくるのじゃ！↓
;　カーーッツ！@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』
;_SKRB_OLDMAN_JEFF;
;@CHKFGOTO(FLG_POWR_RAIN,_SKRB_OLDMAN_OK)
;◆しかしじゃ。そのまえに@KEY()↓
;◆@DSP_STS(STS_PC_NAME_JEFF)！↓
;　あめのふる　なぞのばしょを↓
;　おぼえておろう？@KEY()↓
;◆そこに　ゆくことが↓
;　いま　ひつようなのじゃ。@KEY()
;◆そこにゆき　そしてもういちど↓
;　ここに　もどってくるのじゃ！↓
;　カーーッツ！@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』
;
;_SKRB_OLDMAN_OK;
◆Ｆｏｒ　ａ　ｗｈｉｌｅ，　ｙｏｕ　ｍｕｓｔ　ｌｉｖｅ　ｆａｒ　ａｗａｙ　ｆｒｏｍ　ｙｏｕｒ　ｆｒｉｅｎｄｓ　ａｎｄ　ｌｉｖｅ　ｗｉｔｈ　ｍｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｕｎｄｅｒｓｔａｎｄ？@KEY()↓
◆．．．Ｔｈｅｒｅ’ｓ　ｏｎｌｙ　ｏｎｅ　ａｎｓｗｅｒ．@KEY()↓
◆Ｉ　ｍｕｓｔ　ｓｔｏｐ　ｙｏｕ　ｈｅｒｅ　ｅｖｅｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ．@KEY()↓
◆Ｓｔａｙ　ｆｏｒ　ａ　ｗｈｉｌｅ，　ｄｏ　ｙｏｕ　ｕｎｄｅｒｓｔａｎｄ？！
;jpn:◆しばらくは　なかまとはなれて↓
;jpn:　わしと　ともに↓
;jpn:　くらさねばならぬが@KEY()↓
;jpn:◆よいな？@KEY()↓
;jpn:◆‥‥へんじは　ひとつ。↓
;jpn:　むりにでも　ひきとめねばならぬ。↓
;jpn:　しばし　ここに　とどまるのだ。@KEY()↓
;jpn:◆よいな！！
;ビカビカっとフラッシュ
@KEY()
@CLOSEALL()
@WI(30)
@GOTO(MSG_EVT_88_MABOROSHI_PU)

MSG_SKRB_OLDMAN_OK_1;
@OPEN(1)
◆Ｉｔ　ｄｅｐｅｎｄｓ　ｏｎ　@DSP_NAME(PC_POO)’ｓ　ｅｆｆｏｒｔｓ．　　Ｔｈａｔ　ｗｉｌｌ　ｄｅｔｅｒｍｉｎｅ　ｔｈｅ　ｒｅｕｎｉｔｉｎｇ　ｏｆ　ｔｈｅ　ｇｒｏｕｐ．@KEY()↓
◆Ｂｅ　ｆａｉｔｈｆｕｌ，　ａｎｄ　ｗａｉｔ　ｕｎｔｉｌ　ｔｈｅ　ｔｉｍｅ　ｃｏｍｅｓ！
@KEYNP()
;◆Ｄｅｐｅｎｄｉｎｇ　ｏｎ　@DSP_STS(STS_PC_NAME_POO)’ｓ　ｅｆｆｏｒｔｓ，
;　　ｙｏｕ　ｃａｎ　ｇｏ　ｂａｃｋ　ｔｏ　ｙｏｕｒ　ｆｒｉｅｎｄｓ．
;◆Ｂｅｌｉｅｖｅ　ｙｏｕｒｓｅｌｆ　ａｎｄ　ｗａｉｔ　ｕｎｔｉｌ　ｔｈｅ　ｔｉｍｅ　ｃｏｍｅｓ！
;@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_POO)の　どりょくしだいでは↓
;jpn:　はやく　おまえたちのもとに↓
;jpn:　もどることが　できる。@KEY()↓
;jpn:◆しんじて　そのときを　まて！@KEY()
@CLOSEALL()
』

;_SKRB_OLDMAN_GO;
;◆そこにゆき　そしてもういちど↓
;　ここに　もどってくるのじゃ！↓
;　カーーッツ！@KEY()
;@CLOSEALL()
;@WI(1)
;@WARP(WARP_SKRB_FORTUNETELLER)
;@ADD_PARTY(PC_POO)
;』


;@Habitat:スカラビ／フィールド／街のなか
;@Person:ロープの上の男ププカ
;@Figure:ロープマジック男
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_PUPUKA
MSG_SKRB_PUPUKA;
@CHKFGOTO(FLG_ITEM_KEY_PUPUKA,_SKRB_PUPUKA_AFTER)
◆Ｉ’ｍ　ｄｏｉｎｇ　ｔｈｉｓ　ａｓ　ａ　ｈｏｂｂｙ．@KEY()↓
◆Ｉｓｎ’ｔ　ｉｔ　ｃｏｏｌ？@KEY()↓
◆Ｉ　ｒｅｃｅｎｔｌｙ　ｍａｄｅ　ａ　ｆｒｉｅｎｄ．@KEY()↓
◆Ｈｅ　ｕｓｅｄ　ｔｏ　ｂｅ　ａ　Ｄｕｎｇｅｏｎ　Ｍａｋｅｒ．@KEY()↓
◆Ａｎｄ　ｎｏｗ　ｈｅ’ｓ　ａ　”Ｄｕｎｇｅｏｎ　Ｍａｎ．”@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｍｅｅｔ　ｈｉｍ？↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆わたしは　しゅみで↓
;jpn:　こういうことを　やっているんだ。↓
;jpn:　カッコイイだろ。@KEY()↓
;jpn:◆さいきん　ともだちができてね。↓
;jpn:　ダンジョンづくりのしょくにんで↓
;jpn:　とうとう‥‥フッフッフ@KEY()↓
;jpn:◆「ダンジョンおとこ」に↓
;jpn:　なってしまったやつさ。@KEY()↓
;jpn:◆あってみたいかい？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_PUPUKA_YES,_SKRB_PUPUKA_NO)

_SKRB_PUPUKA_NO;
◆Ｉ　ｕｎｄｅｒｓｔａｎｄ，　ｈｅ　ｉｓ　ａ　ｖｅｒｙ　ｓｔｒａｎｇｅ　ｆｅｌｌｏｗ．
@KEYNP()
;jpn:◆そうかぁ‥‥↓
;jpn:　かわりものだからなぁ　あいつ。↓
;jpn:　しょうがないな。@KEYNP()
』

_SKRB_PUPUKA_YES;
;@Q_GOODSFULL(PC_ALL)
;@FALSE_GOTO(_SKRB_PUPUKA_ITEMFULL)
◆Ａｌｌ　ｒｉｇｈｔｙ　ｔｈｅｎ，　Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　ｔｈｅ　ｋｅｙ　ｓｏ　ｔｈａｔ　ｙｏｕ　ｃａｎ　ｅｎｔｅｒ　ｈｉｍ．@KEY()↓
◆Ｏｈ　ｎｏ．．．Ｉ　ｄｏｎ’ｔ　ｈａｖｅ　ｉｔ！@KEY()↓
◆Ｉ　ｍｕｓｔ　ｈａｖｅ　ｌｏｓｔ　ｉｔ　ｓｏｍｅｗｈｅｒｅ．@KEY()↓
◆Ｉ’ｍ　ｓｏｒｒｙ，　Ｉ　ｄｏｎ’ｔ　ｗｏｒｒｙ　ａｂｏｕｔ　ｓｍａｌｌ　ｔｈｉｎｇｓ．
@KEYNP()
;jpn:◆そうか。それじゃ↓
;jpn:　かれのへやの　カギをあげよう。↓
;jpn:◆あ‥‥@WI(15)ない！@WI(20)↓
;jpn:　あらら　どっかで↓
;jpn:　おとしちゃったかな。@KEY()↓
;jpn:◆ごめん　ごめん。↓
;jpn:　ちいさいことには　わたしは↓
;jpn:　こだわらないんだよ。@KEYNP()
』

;　よろしく　つたえてくれ。@KEY()
;@SE(SE_se74_my_get)
;@GOODSIN(PC_ALL,GDS_TOOL_KEY_DUNGEONMAN)
;@SETF(FLG_ITEM_KEY_PUPUKA)
;』
;
;_SKRB_PUPUKA_ITEMFULL;
;◆こりゃこまった。↓
;　あんたら　にもつがおおすぎて↓
;　カギがわたせんぞ。@KEYNP()
;』
;
_SKRB_PUPUKA_AFTER;
◆Ｉ　ｓｔａｙｅｄ　ｈｅｒｅ　ｔｈｅ　ｗｈｏｌｅ　ｔｉｍｅ　ｙｏｕ　ｗｅｒｅ　ｇｏｎｅ．@KEY()↓
◆Ｂｕｔ　ｎｏｗ　Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈｙ　Ｉ　ｄｉｄ．@KEYNP()
;jpn:◆みえはって　ずっと↓
;jpn:　こんなところに　いるけど‥‥@KEY()↓
;jpn:◆なんか　むなしいなぁ。@KEYNP()
』
;◆わたしは　しゅみで↓
;　こういうことを　やっているんだ。↓
;　カッコイイだろ。@KEY()↓
;◆うーん@WI(30)↓
;　‥‥カッコイイ。@KEYNP()
;』


;@Habitat:スカラビ／フィールド／ピラミッド出口付近
;@Person:ヤリを持った男
;@Figure:ヤリ男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_YARIMAN
MSG_SKRB_YARIMAN;
@CHKFGOTO(FLG_ITEM_KEY_PUPUKA,_SKRB_YARIMAN_AFTER)
;ヤリ男
◆Ｉ　ａｍ　ｎｏｔ　ｓｕｒｅ　ｉｆ　ｉｔ　ｗａｓ　ｔｈｅ　”Ｄｕｎｇｅｏｎ　Ｍａｎ，”　ｂｕｔ．．．@KEY()↓
◆ｔｈｅｒｅ　ｉｓ　ａ　ｓｔｒａｎｇｅ　ｌｏｏｋｉｎｇ　ｔｏｗｅｒ　ｔｏ　ｔｈｅ　ｎｏｒｔｈｗｅｓｔ．@KEY()↓
◆．．．Ｔｈｉｓ　ｋｅｙ　Ｉ　ｐｉｃｋｅｄ　ｕｐ　ａ　ｌｉｔｔｌｅ　ｗｈｉｌｅ　ａｇｏ　ｓｈａｌｌ　ｍａｙｂｅ　ｏｐｅｎ　ｔｈｅ　ｔｏｗｅｒ．@KEY()↓
◆Ｙｏｕ　ｍａｙ　ｈａｖｅ　ｉｔ，　Ｉ　ｄｏ　ｎｏｔ　ｎｅｅｄ　ｉｔ．
;jpn:◆「ダンジョンおとこ」かどうかは↓
;jpn:　しらねぇけど‥‥↓
;jpn:　おかしなとうなら@KEY()↓
;jpn:◆ほくせいの　ほうがくに↓
;jpn:　たってるぜ。@KEY()↓
;jpn:◆‥‥もしかすると↓
;jpn:　さっきひろったカギは@KEY()↓
;jpn:◆あのとうの　いりぐちのカギ↓
;jpn:　かもしれねぇな。@KEY()↓
;jpn:◆おれは　いらんから↓
;jpn:　おまえさんに　やるよ。
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SKRB_YARIMAN_GOODSFULL)
@KEY()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_DUNGEONMAN)
@SAVE_GLOBAL_REG()
@GOSUB(MSG_SUB_GETGOODS_S)
@SETF(FLG_ITEM_KEY_PUPUKA)
@KEYNP()
@CLOSEALL()
;タカのめをプーが持ってったら電話
@CHKF(FLG_SKRB_PU_TAKANOME)@FALSE_GOTO(MSG_END)
@WI(60)
@GOSUB(MSG_GLOBAL_PHONE_TRACY_LOSTITEM)
』
_SKRB_YARIMAN_AFTER;グッズプレゼント後
◆Ｉ’ｍ　ｎｏｔ　ｓｕｒｅ　ｉｆ　ｉｔ　ｗａｓ　ｔｈｅ　”Ｄｕｎｇｅｏｎ　Ｍａｎ”．．．@KEY()↓
◆Ｔｈｅｒｅ’ｓ　ａ　ｓｔｒａｎｇｅ　ｌｏｏｋｉｎｇ　ｔｏｗｅｒ　ｔｏ　ｔｈｅ　ｎｏｒｔｈｗｅｓｔ．
@KEYNP()
;jpn:◆「ダンジョンおとこ」かどうかは↓
;jpn:　しらねぇけど‥‥↓
;jpn:　おかしなとうなら@KEY()↓
;jpn:◆ほくせいの　ほうがくに↓
;jpn:　たってるぜ。@KEYNP()
』

_SKRB_YARIMAN_GOODSFULL;
@KEY()↓
◆．．．Ｂｕｔ　ｉｔ　ｓｅｅｍｓ　ｔｈａｔ　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．
@KEYNP()
;jpn:◆‥‥って　いっても↓
;jpn:　もちものが　いっぱいか。@KEYNP()
』

;@Habitat:スカラビ／フィールド／砂漠南部
;@Person:ダンジョン男
;@Figure:ダンジョン男
;@AppearanceKey:FLG_SKRB_BRICKROAD_DISAPPEAR/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:0
MSG_SKRB_FIELD_DUNGEONMAN;
@CHKFGOTO(FLG_SKRB_DUNGEONMAN_OPEN,_SKRB_DMAN_2)
◆（Ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｃｏｕｌｄ　ｅｎｔｅｒ，　ｂｕｔ　ｉｔ’ｓ　ｌｏｃｋｅｄ．）
@KEYNP()
;jpn:◆（なかに　はいれるらしいが↓
;jpn:　カギが　かかっている）@KEYNP()
』

_SKRB_DMAN_2;チェックしたら即ワープ
;◆いりぐちがあります。↓
;　なかに　はいりますか？↓
;<はい>
;<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(_DMAN_2_YES,_DMAN_2_NO)
;_DMAN_2_NO;
;◆なかにはいるのをやめました。
;@KEYNP()
;@!
;_DMAN_2_YES;
;◆なかにはいります。
;@KEYNP()
@CLOSEALL()
@WI(1)
@WARP(WARP_SKRB_DMAN_BODY)
@GOSUB(MSG_SAVE_MOUSE)
@!


MSG_SKRB_FIELD_DUNGEONMAN_RECEIVE;
@SAVE_REG()
@CHKFGOTO(FLG_SKRB_DUNGEONMAN_OPEN,_SKRB_DMAN_ALREADY)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_DUNGEONMAN)
@FALSE_GOTO(_SKRB_DMAN_KEY_NG)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_TUKATTA)
←
◆（Ｔｈｅ　ｋｅｙ　ｗｏｒｋｅｄ　ｔｏ　ｏｐｅｎ　ｔｈｅ　ｄｏｏｒ．@KEY()↓
◆Ｙｏｕ　ｍａｙ　ｅｎｔｅｒ．）
@KEYNP()
;jpn:◆（カギがあいて↓
;jpn:　なかにはいれるようになった）
@KEYNP()
@SETF(FLG_SKRB_DUNGEONMAN_OPEN)
@SE(SE_se77_my_open_locker)
@CLOSEALL()
@WARP(WARP_SKRB_DMAN_BODY)
@GOSUB(MSG_SAVE_MOUSE)
@!

_SKRB_DMAN_KEY_NG;
◆（Ｔｈｅ　ｋｅｙ　ｄｏｅｓｎ’ｔ　ｆｉｔ！）
;jpn:◆（カギが　あわない！）
@KEYNP()
@!

_SKRB_DMAN_ALREADY;
◆（Ｔｈｅ　ｄｏｏｒ’ｓ　ａｌｒｅａｄｙ　ｏｐｅｎｅｄ．）
;jpn:◆（すでに　とびらはあいている）
@KEYNP()
@!

;@Habitat:スカラビ／フィールド／最南部
;@Person:潜水艦情報の人
;@Figure:ヤリ男
;@AppearanceKey:0
;@ActionScript:◆正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_SKRB_YARIMAN_2
MSG_SKRB_YARIMAN_2;
@CHKFGOTO(FLG_TLPT_MAKY,_SKRB_YARIMAN_2_LATER)
◆Ａ　ｓｃａｒｙ　ｐｌａｃｅ　ｃａｌｌｅｄ　Ｄｅｅｐ　Ｄａｒｋｎｅｓｓ　ｉｓ　ｏｎ　ｔｈｅ　ｏｔｈｅｒ　ｓｉｄｅ　ｏｆ　ｔｈｅ　ｒｉｖｅｒ．@KEY()↓
◆Ｔｈｅ　ｍｏｎｓｔｅｒｓ　ａｒｅ　ｖｅｒｙ　ｓｔｒｏｎｇ　ａｎｄ　ｙｏｕ　ｃａｎ　ｌｏｓｅ　ｙｏｕｒ　ｈｅａｌｔｈ@KEY()↓
◆ｊｕｓｔ　ｂｙ　ｗａｎｄｅｒｉｎｇ　ｉｎ　ｔｈｅ　ｓｗａｍｐ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｃｒｏｓｓ　ｔｈｅ　ｒｉｖｅｒ，　ｅｖｅｎ　ｔｈｏｕｇｈ　ｙｏｕ　ｋｎｏｗ　ｉｔ’ｓ　ａ　ｓｔｕｐｉｄ　ｉｄｅａ？@KEY()↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆この　かわの　むこうは↓
;jpn:　「まきょう」とよばれる↓
;jpn:　おそろしいところだ。@KEY()↓
;jpn:◆かいぶつは　つよいし↓
;jpn:　どくのぬまは　あるくだけで↓
;jpn:　たいりょくがへるぞ。@KEY()↓
;jpn:◆かわを　わたりたいのか？↓
;jpn:　ばかを　しょうちで。↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_YARIMAN_2_YES,_SKRB_YARIMAN_2_NO)

_SKRB_YARIMAN_2_NO;
◆Ｉｔ　ｗａｓ　ｓｔｕｐｉｄ　ｏｆ　ｍｅ　ｔｏ　ａｓｋ．@KEY()↓
◆Ｌｅｔ’ｓ　ｔｏｇｅｔｈｅｒ　ｗａｔｃｈ　ｔｈｅ　ｓｕｎｓｅｔ　ｏｖｅｒ　Ｄｅｅｐ　Ｄａｒｋｎｅｓｓ　ｆｒｏｍ　ｈｅｒｅ．
@KEYNP()
;jpn:◆きいてみた　おれがばかだった。@KEY()↓
;jpn:◆いっしょに↓
;jpn:　「まきょう」にしずむ↓
;jpn:　ゆうひでも　みよう。@KEYNP()
』
_SKRB_YARIMAN_2_YES;＃
◆Ｔｈｅ　ｓｗａｍｐ　ｉｓ　ｂｏｔｔｏｍｌｅｓｓ．@KEY()↓
◆Ｅｖｅｎ　ｉｆ　ｙｏｕ’ｒｅ　ｓｗｉｍｍｉｎｇ，　ｙｏｕ’ｌｌ　ｂｅ　ｄｒａｇｇｅｄ　ｉｎ．@KEY()↓
◆Ｉｔ　ｉｓ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｔｏｒｙ　ｉｆ　ｙｏｕ　ｈａｖｅ　ａ　ｓｕｂｍａｒｉｎｅ．
@KEYNP()
;jpn:◆ぬまはそこなし。@WI(20)↓
;jpn:　およいでいっても↓
;jpn:　ひきずりこまれちまうぜ。@KEY()↓
;jpn:◆サブマリンでもあれば↓
;jpn:　はなしはべつだが。@KEYNP()
@SETF(FLG_SKRB_YARIMAN)
@SETF(FLG_DSRT_KANBAN_44_MOVE);カンバン移動サブマリンコースオープン
』
_SKRB_YARIMAN_2_LATER;＆
◆Ｙｏｕ　ｒｅｔｕｒｎｅｄ　ｆｒｏｍ　ｅｘｐｌｏｒｉｎｇ　ｔｈｅ　Ｄｅｅｐ　Ｄａｒｋｎｅｓｓ？@KEY()↓
◆Ｉ　ｃａｎｎｏｔ　ｂｅｌｉｅｖｅ　ｙｏｕ　ｍａｄｅ　ｉｔ　ｂａｃｋ　ａｌｉｖｅ．
@KEYNP()
;jpn:◆あの　おそろしい「まきょう」を↓
;jpn:　たんけんしてきたんだってね。@KEY()↓
;jpn:◆いきてかえったなんて↓
;jpn:　しんじられん。@KEYNP()
』

;▼▲▼▲▼▲▼▲　スカラビ　▼▲▼▲▼▲▼▲

;^^^^^^^^ダンジョン男内部：４階^^^^^^^^

;@Habitat:スカラビ／ダンジョン男内部／洞窟４Ｆ最北部
;@Person:ブリックの顔
;@Figure:ダンジョン職人の顔
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICKROAD
MSG_SKRB_BRICKROAD;
;ダンジョンの中のカクレ部屋にいる。入口はあいているが
;部屋はしまっているからカギがないとダメですよね。
@CHKFGOTO(FLG_TLPT_MAKY,_SKRB_BRICKROAD_MAIN)
@CHKFGOTO(FLG_SKRB_YARIMAN,_SKRB_BRICKROAD_MAKYO_2)
_SKRB_BRICKROAD_MAIN;
◆Ｗｅｌｃｏｍｅ！
@KEY()
;jpn:◆ウーェルカム！@KEY()
@CLOSEALL()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@OPEN(1)
@CHKFGOTO(FLG_TLPT_MAKY,MSG_SKRB_DUNGEONMAN_END)
◆Ｌｏｎｇ　ｔｉｍｅ，　ｎｏ　ｓｅｅ．@KEY()↓
◆Ｍｒ．　@DSP_NAME(PC_JEFF)，　ｗｅ　ｍｅｔ　ｉｎ　Ｗｉｎｔｅｒｓ　ａ　ｌｏｎｇ　ｔｉｍｅ　ａｇｏ．@KEY()↓
◆Ｉ’ｍ　Ｂｒｉｃｋ　Ｒｏａｄ．@KEY()↓
◆Ｄｒ．　Ａｎｄｏｎｕｔｓ　ｆｉｎａｌｌｙ　ｍａｄｅ　ｍｅ　Ｄｕｎｇｅｏｎ　Ｍａｎ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗａｎｔ，　Ｉ’ｌｌ　ｃｏｍｅ　ｗｉｔｈ　ｙｏｕ　ｇｕｙｓ　ｆｏｒ　ａ　ｗｈｉｌｅ．@KEY()↓
◆Ｔｈｅ　”Ｒｅｔｕｒｎ　Ｈｏｌｅ”　ｉｓ　ｏｖｅｒ　ｔｈｅｒｅ．
◆Ｊｕｍｐ　ｉｎ　ｔｈａｔ　ｈｏｌｅ　ａｎｄ　ｔｈｅｎ　ｗａｌｋ　ｏｕｔ．
@KEYNP()
;jpn:◆ひさしぶりでやんす。@WI(20)↓
;jpn:　@DSP_STS(STS_PC_NAME_JEFF)さん　ずっとまえに↓
;jpn:　ウィンターズで　あいやした@KEY()↓
;jpn:◆ブリックロードで　ござんす。@KEY()↓
;jpn:◆アンドーナッツはかせの　おかげで↓
;jpn:　ついに　ダンジョンおとこに↓
;jpn:　なれたんでやす。@KEY()↓
;jpn:◆あんたがたさえ　よかったら↓
;jpn:　しばらく　いっしょに↓
;jpn:　ついていきやす。@KEY()↓
;jpn:◆そこにある「おかえりあな」↓
;jpn:　‥‥という　あなから↓
;jpn:　したに　おっこちて@KEY()↓
;jpn:◆そとにでて　あるいてみて↓
;jpn:　おくんなさい。@KEYNP()
;◆はいってきた　とびらをでて↓
;　あるいてみて　おくんなさい。@KEYNP()
@SETF(FLG_BRICKROAD)
@SETF(FLG_SKRB_YARIMAN_B_APPEAR)
@SET_HIT_RECT(1,HRECT_SKRB_DM_HAMARI,MSG_EVT_90_DM_HAMARI)
@SETF(FLG_PHOTO_DUNGEONMAN);撮り頃フラグ
』
_SKRB_BRICKROAD_MAKYO_2;
◆Ｔｈｅｒｅ’ｓ　ａｎ　ｏｌｄ　ｓｕｂｍａｒｉｎｅ　ａｔ　ｔｈｅ　ｂａｃｋ　ｏｆ　ｔｈｅ　ｄｕｎｇｅｏｎ．@KEY()↓
◆Ｉｔ　ｃａｎ　ｂｅ　ｕｓｅｄ　ｔｏ　ｃｒｏｓｓ　ｔｈｅ　ｒｉｖｅｒ．@KEY()↓
◆Ｔｈｅｒｅ’ｓ　ａ　”Ｇｏｏｄｂｙｅ　Ｅｘｉｔ”．．．ｏｖｅｒ　ｔｈｅｒｅ．@KEY()↓
◆Ｉｔ　ｗｉｌｌ　ｔａｋｅ　ｙｏｕ　ｔｏ　ｔｈｅ　ｓｕｂｍａｒｉｎｅ．@KEY()↓
◆Ｄｏｎ’ｔ　ｍａｋｅ　ａ　ｍｉｓｔａｋｅ　ｏｎ　ｗｈｉｃｈ　ｅｘｉｔ　ｙｏｕ　ｔａｋｅ．@KEY()↓
◆Ｙｏｕ　ｎｅｅｄ　ｔｏ　ｔａｋｅ　ｔｈｅ　”Ｇｏｏｄｂｙｅ　Ｅｘｉｔ！”@KEY()↓
◆Ｈｏｐｅ　ｔｏ　ｓｅｅ　ｙｏｕ　ａｇａｉｎ！
@KEYNP()
;jpn:◆このダンジョンの　おくに↓
;jpn:　くたびれたサブマリンが↓
;jpn:　ありやす。@KEY()↓
;jpn:◆そいつで　むこうぎしに↓
;jpn:　わたってくだせえやし。@KEY()↓
;jpn:◆このおくにある「さらばあな」@KEY()↓;＄追加
;jpn:◆‥‥という　なまえのあなが↓
;jpn:　サブマリンのばしょへ↓
;jpn:　つうじているでやんす。@KEY()↓
;jpn:◆くれぐれも　おちるあなを↓
;jpn:　まちがえないでおくんなさい。@WI(20)↓
;jpn:　「さらばあな」でやんすよ。@KEY()↓
;jpn:◆えんが　あったら↓
;jpn:　また　あいやしょう！@KEYNP()
』
MSG_SKRB_DUNGEONMAN_END;＆動けなくなったままのダンジョン男
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｈｏｗ，　ｂｕｔ　ｍｙ　ｈｏｍｅｍａｄｅ　ｄｕｎｇｅｏｎ　ｈｅｌｐｅｄ　ｙｏｕ　ｏｕｔ．@KEY()↓
◆Ｉ’ｍ　ｇｌａｄ．
@KEYNP()
;jpn:◆どんなふうにか　しらないけれど@WI(20)↓
;jpn:　わしの　てづくりダンジョンが↓
;jpn:　やくにたって　うれしいでやんす。@KEYNP()
@CLOSEALL()
』
;-------------------------------------------------


;@Habitat:スカラビ／ダンジョン男内部／洞窟４Ｆ南東
;@Person:看板４４
;@Figure:立札
;@AppearanceKey:FLG_SKRB_YARIMAN/off
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICKROAD
MSG_BRICK_SIGN_44;
;２回目の帰路（潜水艦の場所へ）
;１回目クリア前は看板で通路を封じ、クリア後は看板を消す
@CHKFGOTO(FLG_TLPT_MAKY,_BRICK_SIGN_44_LATER)
◆”Ｇｏｏｄｂｙｅ　Ｅｘｉｔ”@KEY()↓
◆Ｓｏｍｅ　ｄａｙ，　ｙｏｕ　ｓｈｏｕｌｄ　ｅｎｔｅｒ　ｗｉｔｈ　ｃｏｕｒａｇｅ．@KEY()↓
◆．．．Ｂｒｉｃｋ　Ｒｏａｄ．
@KEYNP()
;jpn:◆「さらばあな」↓
;jpn:　いずれ　ゆうきをだして↓
;jpn:　とびこむべし。‥ブリック・ロード@KEYNP()
』
_BRICK_SIGN_44_LATER;後に
◆Ｔｈｉｓ　ｐａｔｈ　ｉｓ　ｃｌｏｓｅｄ．@KEY()↓
◆．．．Ｂｒｉｃｋ　Ｒｏａｄ．
@KEYNP()
;jpn:◆こちらの　コースはへいさした。↓
↓
;jpn:　　　　　　　　‥ブリック・ロード@KEYNP()
』


;回復ベンチ
MSG_SKRB_DMAN_BENCH_1A;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_2)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_1B;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_1)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_2;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_3)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

MSG_SKRB_DMAN_BENCH_3;
@GOSUB(_DMAN_BENCH_MES)
@GOSUB(MSG_SUB_SYUKUHAKU)
;@GOSUB(MSG_GLOBAL_MYHOME)
@GOSUB(_DMAN_BENCH_MES_2)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@WARP(WARP_DMAN_BENCH_4)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!
_DMAN_BENCH_MES;
◆”Ｇｏｏｄ　Ｎｉｇｈｔ　Ｂｅｎｃｈ．”@KEY()↓
◆Ｍａｙ　ｙｏｕ　ｒｅｌａｘ　ａｎｄ　ｒｅｃｏｖｅｒ　ｙｏｕｒ　ｈｅａｌｔｈ　ａｎｄ　ｓｐｉｒｉｔｓ．
@KEYNP()
;jpn:◆「おやすみベンチ」↓
;jpn:　つかれが　すっかりとれ@KEY()↓
;jpn:◆きりょく　たいりょくが↓
;jpn:　かいふくします。
@KEYNP()
@!

_DMAN_BENCH_MES_2;
;@COLD_PLAYER(PC_ALL)
@OPEN(1)
◆@GOSUB(MSG_ESUB_DSP_PARTY)’ｓ　ｈｅａｌｔｈ　ｉｓ　ｒｅｓｔｏｒｅｄ．
;jpn:◆@DSP_LCNAME()は↓
;jpn:　すっかり　げんきになった。
@KEYNP()
@CLOSEALL()
;@FRESH_PLAYER(PC_ALL)
@!


;^^^^^^^^ダンジョン男内部：１階^^^^^^^^

;@Habitat:スカラビ／ダンジョン男内部／洞窟中２階最北部
;@Person:壊れたサブマリン
;@Figure:潜水艦
;@AppearanceKey:0
;@ActionScript:◆固定
;@GoodsMessage:0
;@CheckMessage;0
;@Message:MSG_SKRB_BRICK_SUBMARINE
MSG_SKRB_BRICK_SUBMARINE;
;潜水艦をチェックしたときのメッセージ
@SET_LOOPREG(PC_JEFF)			;ジェフのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_SKRB_BRICK_SUBMARINE_DEAD)
◆（@DSP_NAME(PC_JEFF)　ｃｈｅｃｋｅｄ　ｔｈｅ　ｂｒｏｋｅｎ　ｓｕｂｍａｒｉｎｅ．）@KEY()↓
◆Ｙｅｓ！@KEY()↓
◆Ｉｔ　ｃａｎ　ｓｔｉｌｌ　ｗｏｒｋ．
@KEYNP()
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)は↓
;jpn:　こわれたサブマリンを↓
;jpn:　チェックした。@KEY()↓
;jpn:◆よし！↓
;jpn:　これは　まだうごくぞ。@KEY()
@CLOSEALL()
@GOTO(MSG_EVT_92_SUBMARINE)

_SKRB_BRICK_SUBMARINE_DEAD;
◆（Ｎｏ　ｏｎｅ　ｃａｎ　ｒｅｐａｉｒ　ｔｈｅ　ｓｕｂｍａｒｉｎｅ　ｅｘｃｅｐｔ　@DSP_NAME(PC_JEFF)．）
@KEYNP()
;jpn:◆（@DSP_STS(STS_PC_NAME_JEFF)　いがいのものには↓
;jpn:　サブマリンの↓
;jpn:　しゅうりは　できない）@KEYNP()
』
;------------------------------------------------------------------

;この後増補

MSG_SKRB_INFO_POKEY;
◆Ｏｈ，　ｂｅ　ｃａｒｅｆｕｌ　ｗｈｅｒｅ　ｙｏｕ　ｗａｌｋ．@KEY()↓
◆Ｉｔ’ｓ　ｆｉｌｔｈｙ．@KEY()↓
◆Ａ　ｃｈｕｂｂｙ　ｋｉｄ　ｄｉｄ　ｈｉｓ　ｂｕｓｉｎｅｓｓ　ｏｕｔ　ｈｅｒｅ　ｓｏｍｅｗｈｅｒｅ．．．
@KEYNP()
;jpn:◆あ　そのへんあるくと↓
;jpn:　バッチイよ。@KEY()↓
;jpn:◆がいこくから　きたとかいう↓
;jpn:　ふとった　ガキが↓
;jpn:　ノグソしてったから。@KEYNP()
』
MSG_SKRB_UNKO_POKEY;チェックすると
◆（Ｐｏｋｅｙ’ｓ　ｓｔｉｎｋ　ｓｔｉｌｌ　ｈａｎｇｓ　ｉｎ　ｔｈｅ　ａｉｒ．．．）
@KEYNP()
;jpn:◆（ポーキーがいた↓
;jpn:　なごりがある‥‥）@KEYNP()
』

MSG_SKRB_INFO_HIERO;
◆Ｙｏｕ　ｎｅｅｄ　ｔｏ　ｂｅ　ａｂｌｅ　ｔｏ　ｒｅａｄ　ｈｉｅｒｏｇｌｙｐｈｓ　ｔｏ　ｓｏｌｖｅ　ｔｈｅ　ｍｙｓｔｅｒｙ　ｏｆ　ｔｈｅ　Ｐｙｒａｍｉｄ．@KEY()↓
◆．．．Ｉ　ｃｏｕｌｄｎ’ｔ　ｓｏｌｖｅ　ｉｔ，　ａｌｔｈｏｕｇｈ　Ｉ　ｒｅａｄ　ｉｔ．@KEY()↓
◆Ｄｉｄｎ’ｔ　ｙｏｕ　ｒｅａｄ　ｔｈｅ　ｈｉｅｒｏｇｌｙｐｈｓ　ａｔ　ｔｈｅ　ｍｕｓｅｕｍ　ｉｎ　Ｓｕｍｍｅｒｓ？@KEY()↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:◆ヒエログリフをよんで↓
;jpn:　りかいしないと↓
;jpn:　ピラミッドのなぞは　とけない。@KEYNP()
;jpn:◆‥‥おれは　よんでも↓
;jpn:　とけなかったんだけど@KEY()↓
;jpn:◆きみ@GOSUB(MSG_SUB_TATI)↓
;jpn:　サマーズのはくぶつかんで↓
;jpn:　よんできたんだろ？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SKRB_INFO_HIERO_YES,_SKRB_INFO_HIERO_NO)
_SKRB_INFO_HIERO_NO;
◆Ｗｅｌｌ，　ｔｈａｔ　ｍｅａｎｓ　ｔｈａｔ　ｙｏｕ　ｍｕｓｔ　ｇｏ　ｂａｃｋ，　ｒｅａｄ　ｉｔ　ａｎｄ　ｔｈｅｎ　ｃｏｍｅ　ｂａｃｋ　ｈｅｒｅ．
@KEYNP()
;jpn:◆そりゃあ　サマーズに↓
;jpn:　ひきかえしてでも↓
;jpn:　しっかり　よんでこなきゃ。@KEYNP()
』
_SKRB_INFO_HIERO_YES;
◆Ｔｈｅｎ，　ｙｏｕ　ｓｈｏｕｌｄ　ｂｅ　ａｂｌｅ　ｔｏ　ｓｏｌｖｅ　ｔｈｅ　ｍｙｓｔｅｒｙ　ｓｏｍｅｄａｙ．
@KEYNP()
;jpn:◆じゃあ　いずれ↓
;jpn:　なぞは　とけるだろうよ。@KEYNP()
』
;-------------------------------------------------

MSG_SKRB_CHECK_SHOP;スカラビショップのカンバン
◆Ｈａｓｓａｎ’ｓ　Ｓｈｏｐ@KEY()↓
◆（＄　ｄｏｌｌａｒｓ　ａｃｃｅｐｔａｂｌｅ．）
@KEYNP()
;jpn:◆ハッサンさんの　みせ↓
;jpn:　（＄ドルも　つかえるよ）@KEYNP()
』
;-------------------------------------------------

MSG_BRICK_SIGN_FACE;
◆Ｔｈａｔ　ｆａｃｅ　ｉｓ　ｍｉｎｅ．@KEY()↓
◆（Ｆｅｅｌ　ｆｒｅｅ　ｔｏ　ｔａｌｋ　ｔｏ　ｉｔ．）@KEY()↓
◆．．．Ｂｒｉｃｋ　Ｒｏａｄ．
@KEYNP()
;jpn:◆そこのかおは　わたしのである。↓
;jpn:　（きがるに　はなしかけてみよう）↓
;jpn:　　　　　　　　‥ブリック・ロード@KEYNP()
』
;-------------------------------------------------
