;-------------------------------------------------------------------

;「ボルヘスの酒場」を出ると、ムーンサイドの「怪しい酒場」の裏に出る。

;@Habitat:ムーンサイド／フィールド／ムーンサイドボルヘス近く
;@Person:通行人Ａ
;@Figure:サラリーマンＣ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_A
MSG_MOON_A;
;最初に話しかけるであろう「通行人」。
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｍｏｏｎｓｉｄｅ．@KEY()↓
◆Ｗｅｌ　　ｃｏｍｅ　　ｔｏ　ｍｏｏ　　　ｎｓｉ　　ｎｓ　　ｄｅｍ　ｏｏｎｓ　ｉｄｅ．

;jpn:◆ようこそ　ムーンサイドへ。@KEY()↓
;jpn:◆よう@WI(15)　こそムー@WI(15)　そムー@WI(15)↓
;jpn:　ンサイ@WI(15)　ンサイ@WI(15)　ンサイ@KEY()↓
;jpn:◆‥‥ドへ。
@KEYNP()
』

；----------------------------------------
;「怪しい酒場」の中
;「マスターもどき」「ママもどき」「客１」「客２」の４人がいる。

;@Habitat:ムーンサイド／ムーンサイドボルヘス／ムーンサイドボルヘス
;@Person:マスターもどき
;@Figure:酒場のマスター
;@AppearanceKey:0
;@ActionScript:＊止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_BAR_MASTER
MSG_MOON_BAR_MASTER;
◆Ｎｏ，　ｔｈａｔ’ｓ　ｒｉｇｈｔ．↓
　　Ｉ　ａｍ　ｔｈｅ　ｈｏｓｔ　ｈｅｒｅ．
;DAN:"master" here means bartender.

;jpn:◆いいえ　そのとおり。↓
;jpn:　わたしは　ここのマスターだ。
@KEYNP()
』


;@Habitat:ムーンサイド／ムーンサイドボルヘス／ムーンサイドボルヘス
;@Person:ママもどき
;@Figure:おばさんＣ
;@AppearanceKey:0
;@ActionScript:＊中範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_BAR_BETTY
MSG_MOON_BAR_BETTY;
◆Ｙｅｓ，　ｔｈａｔ’ｓ　ｗｒｏｎｇ．↓
　　Ｉ　ａｍ　ｔｈｅ　ｈｏｓｔｅｓｓ　ｈｅｒｅ．
;DAN:I mean "hostess" who is in charge of this bar.

;jpn:◆はい　ちがうわよ。↓
;jpn:　わたしは　ここのママなのよ。
@KEYNP()
』


;@Habitat:ムーンサイド／ムーンサイドボルヘス／ムーンサイドボルヘス
;@Person:客Ａ
;@Figure:酒場の客
;@AppearanceKey:0
;@ActionScript:＊背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_BAR_A
MSG_MOON_BAR_A;
◆Ｗｈａｔ？↓
　　Ｆｏｕｒｓｉｄｅ？↓
　　Ａｒｅ　ｙｏｕ　ｓｔｉｌｌ　ｓｌｅｅｐｉｎｇ？@KEY()↓
◆Ｔｈｉｓ　ｉｓ　Ｍｏｏｎｓｉｄｅ．

;jpn:◆え？@WI(20)　フォーサイド？@KEY()↓
;jpn:◆なに　ねぼけてるんだ？@WI(20)↓
;jpn:　ここは　ムーンサイドだぜ。
@KEYNP()
』


;@Habitat:ムーンサイド／ムーンサイドボルヘス／ムーンサイドボルヘス
;@Person:客Ｂ
;@Figure:ＯＬＣ
;@AppearanceKey:0
;@ActionScript:＊背面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_BAR_B
MSG_MOON_BAR_B;
◆”Ｙｅｓ”　ｉｓ　”Ｎｏ”　ａｎｄ↓
　　”Ｎｏ”　ｉｓ　”Ｙｅｓ．”@KEY()↓
◆Ｉｔ　ｍａｋｅｓ　ｐｅｒｆｅｃｔ　ｓｅｎｓｅ　ｉｎ　Ｍｏｏｎｓｉｄｅ．
;jpn:◆「はい」が「いいえ」で↓
;jpn:　「いいえ」が「はい」。@KEY()↓
;jpn:◆ここ　ムーンサイドじゃ↓
;jpn:　それが　じょうしき。
@KEYNP()
』


;以上の「酒場の人たち」のセリフにより
;ムーンサイドでの受け応え（はいor いいえ）は
;「逆さまが正しい」ことがわかる。
；----------------------------------------
;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｂ
;@Figure:リゾート男
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_B
MSG_MOON_B;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！
@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_B)
』
MSG_MOON_S;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_S)
』
MSG_MOON_T;
MSG_MOON_U;
MSG_MOON_V;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_T)
』
MSG_MOON_W;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_W)
』
MSG_MOON_X;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@CHKFGOTO(FLG_MOON_WARP_X,_MOON_X_ROOM)
;船頭の近くに戻される
@WARP(WARP_MOON_XX)
』
_MOON_X_ROOM;正しく部屋へ
@WARP(WARP_MOON_X)
』

MSG_MOON_Y;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_Y)
』
MSG_MOON_Z;
;（このセリフは数人がしゃべる。ワープ先が違う）
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ！@KEY()

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ！@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_Z)
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｃ
;@Figure:リゾート女
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_C
MSG_MOON_C;
◆Ｂｅｆｏｒｅ　ｔｈｅ　ｓｏｕｐ　ｇｅｔｓ　ｃｏｌｄ，　ｗｅ　ｍｕｓｔ　ｃａｒｅ　ｆｏｒ　Ｍａｎｉ　Ｍａｎｉ．@KEY()↓
◆Ｂｅｆｏｒｅ　ｔｈｅ　ｋｎｉｆｅ　ｇｅｔｓ　ｒｕｓｔｙ，　ｗｅ　ｍｕｓｔ　ｃａｒｅ　ｆｏｒ　Ｍａｎｉ　Ｍａｎｉ．

;jpn:◆スープが　さめないうちに↓
;jpn:　マニマニを　なんとかしないと。@KEY()↓
;jpn:◆ナイフが　さびないうちに↓
;jpn:　マニマニを　なんとかしないと。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｄ
;@Figure:ツッパリ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_D
MSG_MOON_D;
◆Ｉ’ｌｌ　ｔｅｌｌ　ｙａ　ｗｈａｔ　Ｉ　ｈａｔｅ　ｉｎ　ｔｈｉｓ　ｗｏｒｌｄ．@KEY()↓
◆Ｔｈａｔ’ｓ　@DSP_STS(STS_PARTY_FAVORITE_FOODS)．@KEY()↓
◆Ｔｈｅ　ｃｏｌｏｒ，　ｔｈｅ　ｓｍｅｌｌ，　ｔｈｅ　ｔａｓｔｅ，　ｔｈｅ　ｔｅｘｔｕｒｅ．．．@KEY()↓
◆Ｈｅｙ　ｙｏｕ，　ｙｏｕ’ｒｅ　ｄｒｏｏｌｉｎｇ！

;jpn:◆おれの　いっちばん↓
;jpn:　きらいなもの　おしえてやろう。@KEY()↓
;jpn:◆それは　@DSP_STS(STS_PARTY_FAVORITE_FOODS)さ。@KEY()↓
;jpn:◆あのいろ@WI(15)　あのにおい@WI(15)　あのあじ@WI(15)↓
;jpn:　あのしたざわり‥‥@KEY()↓
;jpn:◆おまえ　よだれがでてるぞ？！
@KEYNP()
』


;@Habitat:ムーンサイド／病院／部屋
;@Person:通行人Ｅ
;@Figure:ＯＬＧ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_E
MSG_MOON_E;
◆”Ｙｅｓ”　ｍｅａｎｓ　”Ｎｏ”↓
　　”Ｎｏ”　ｍｅａｎｓ　”Ｙｅｓ．”@KEY()↓
◆Ｏｒ　ｄｉｄ　ｙｏｕ　ａｌｒｅａｄｙ　ｋｎｏｗ　ｔｈｉｓ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆「はい」が「いいえ」で↓
;jpn:　「いいえ」が「はい」ってこと↓
;jpn:　とうぜん　しってるわよね？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_E_YES,_MOON_E_NO)

_MOON_E_NO;
◆Ａｈ！　　Ｙｏｕ　ｋｎｅｗ　ｉｔ．　　Ｔｈａｔ’ｓ　ｇｏｏｄ．↓
　　Ｉ　ｗａｓ　ｊｕｓｔ　ｗｏｎｄｅｒｉｎｇ．
;jpn:◆しってるなら　いいのよ。↓
;jpn:　ただ　きいてみただけなの。
@KEYNP()
』

_MOON_E_YES;
◆Ｏｈ　ｙｅａｈ？↓
　　Ｙｏｕ　ｄｉｄｎ’ｔ　ｋｎｏｗ？
;jpn:◆えっ　しらないの？！
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｆ
;@Figure:サラリーマンＢ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_F
MSG_MOON_F;
◆Ｈｅｌｌｏ！@KEY()↓
◆Ａｎｄ．．．ｇｏｏｄ－ｂｙｅ．．．@KEY()↓
◆Ｓｈａｌｌ　Ｉ．．．？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆ハロー！@WI(20)↓
;jpn:　そして‥‥@KEY()↓
;jpn:◆グッドバイ‥‥↓
;jpn:　するかい？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_F_YES,_MOON_F_NO)

_MOON_F_NO;
;出口の無い部屋にワープ
◆Ｔｈｅｎ．．．@WI(20)↓
　　ｇｏｏｄ－ｂｙｅ！
;jpn:◆では‥‥@WI(20)↓
;jpn:　グッドバイ！
@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_ROOM)
』

_MOON_F_YES;
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｍｏｏｎｓｉｄｅ．@KEY()↓
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｍｏｏ　　　Ｍｏｏ　　Ｍｏｏ　　ｎｓｉ　　　ｎｓｉ　　　ｎｓｉ　　　ｎｓｉ．．．ｎｓｉｄｅ．

;jpn:◆ようこそ　ムーンサイドへ。@KEY()↓
;jpn:◆ようこそ　ムー@WI(15)　ムー@WI(15)　ムー@WI(15)↓
;jpn:　ンサ@WI(15)　ンサ@WI(15)　ンサ@WI(15)　ンサ@KEY()↓
;jpn:◆‥‥ンサイドへ。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｇ
;@Figure:ジミな男
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_G
MSG_MOON_G;
◆Ｉ’ｍ　ｐｒｅｔｔｙ　ｆｏｒｇｅｔｆｕｌ．↓
　　Ｉ　ｅｖｅｎ　ｆｏｒｇｏｔ　ｗｈｙ　Ｉ’ｍ　ｈｅｒｅ．@KEY()↓
◆Ｈｍｍ．．．@KEY()↓
◆Ｉ　ｊｕｓｔ　ｆｏｒｇｏｔ　ｓｏｍｅｔｈｉｎｇ．．．@KEY()↓
◆Ｗｈｏ　ａｍ　Ｉ？@KEY()↓
◆Ａｍ　Ｉ　ａ　ｍａｎ？

;jpn:◆おれは　わすれやすい　おとこ。@WI(20)↓
;jpn:　なぜ　おれが　ここにいるのか↓
;jpn:　わすれてしまった。@KEY()↓
;jpn:◆‥‥‥いま　おれは　なにを↓
;jpn:　わすれてしまったんだっけ？@KEY()↓
;jpn:◆‥‥‥‥‥‥‥おれは↓
;jpn:　どんなおとこだった？@KEY()↓
;jpn:◆‥‥おれは　おとこか？
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｈ
;@Figure:サラリーマンＤ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_H
MSG_MOON_H;
◆Ｄｏ　ｙｏｕ　ｕｎｄｅｒｓｔａｎｄ　ａｌｌ　ｔｈｉｓ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆わかるかい？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_H_YES,_MOON_H_NO)

_MOON_H_NO;
◆Ｇｏｏｄ，@WI(20)↓
　　Ｉ’ｍ　ｇｌａｄ　ｙｏｕ　ｇｅｔ　ｉｔ．

;jpn:◆わかるのか。@WI(20)↓
;jpn:　それなら　よかった。
@KEYNP()
』

_MOON_H_YES;
◆Ｎｏ？　　Ｙｏｕ　ｄｏｎ’ｔ？@WI(20)↓
　　Ｔｏ　ｔｅｌｌ　ｙｏｕ　ｔｈｅ　ｔｒｕｔｈ，　ｎｅｉｔｈｅｒ　ｄｏ　Ｉ．

;jpn:◆わからないのか。@WI(20)↓
;jpn:　じつは　おれにも↓
;jpn:　よく　わからないんだ。
@KEYNP()
』


;@Habitat:ムーンサイド／ホテル／受け付け
;@Person:通行人Ｉ
;@Figure:レゲエ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_I
MSG_MOON_I;
◆Ｉｆ　Ｉ　ｓｔａｙ　ｈｅｒｅ　ｔｏｏ　ｌｏｎｇ，　Ｉ’ｌｌ　ｅｎｄ　ｕｐ　ｆｒｙｉｎｇ　ｍｙ　ｂｒａｉｎ．@KEY()↓
◆Ｙｅｓ，　Ｉ　ｗｉｌｌ．↓
　　Ｎｏ，　Ｉ　ｗｉｌｌ．．．ｎｏｔ．↓
　　Ｙｅｓｎｏ，　Ｉ　ｗｉｌｌ　ｗｏｎ’ｔ．

;jpn:◆ずっとここに　いると↓
;jpn:　あたまが↓
;jpn:　ぼんよよよんに@KEY()↓
;jpn:◆なる。@WI(20)↓
;jpn:　ならない。@WI(20)↓
;jpn:　なるない。
@KEYNP()
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｊ（数字男Ｂ案）
;@Figure:ボロ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_J_NUMBERMAN_B
MSG_MOON_J_NUMBERMAN_B;
@CHKFGOTO(FLG_MOON_NUMBERMAN_B3,_MOON_I_NUMBERMAN_B_AFTER3)
@CHKFGOTO(FLG_MOON_NUMBERMAN_B2,_MOON_I_NUMBERMAN_B_AFTER2)
@CHKFGOTO(FLG_MOON_NUMBERMAN_B1,_MOON_I_NUMBERMAN_B_AFTER1)
◆２５７　　２５６　　２５５　　２５４　　２５３．．．@KEY()↓
◆Ｓｏ　ｗｈａｔ’ｓ　ｙｏｕｒ　ｐｒｏｂｌｅｍ？↓
　　Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ａｎｙｔｈｉｎｇ，　ｇｅｔ　ｏｕｔｔａ　ｈｅｒｅ．@KEY()↓
◆Ｉ’ｍ　ｃｏｕｎｔｉｎｇ　ｂａｃｋｗａｒｄｓ．@KEY()↓
◆２５２　　２５１　　２５０．．．

;◆２５７@WI(20)　２５６@WI(20)　２５５@WI(20)↓
;jpn:　２５４@WI(20)　２５３‥‥@KEY()↓
;jpn:◆なにか　ようか？@WI(20)↓
;jpn:　なにも　ようじがないんなら↓
;jpn:　あっち　いけ。@KEY()↓
;jpn:◆いま　おれは　すうじを↓
;jpn:　へらしているところなんだ。@KEY()↓
;jpn:◆２５２@WI(20)　２５１@WI(20)　２５０‥‥
@KEYNP()
@SETF(FLG_MOON_NUMBERMAN_B1)
』

_MOON_I_NUMBERMAN_B_AFTER1;
◆６９　　６８　　６７　　６６　　６５　　６４　　６３．．．@KEY()↓
◆Ｗｈａｔ？　　Ｉｓ　ｔｈｉｓ　ａ　ｓｐｅｃｉａｌ　ｈｏｂｂｙ　ｏｆ　ｙｏｕｒｓ？　　Ｙｏｕ　ｌｉｋｅ　ｗａｔｃｈｉｎｇ　ｐｅｏｐｌｅ　ｃｏｕｎｔ　ｂａｃｋｗａｒｄｓ？@KEY()↓
◆６２　　６１　　６０　　５９．．．

◆６９@WI(15)　６８@WI(15)　６７@WI(15)　６６@WI(15)↓
;jpn:　６５@WI(15)　６４@WI(15)　６３‥‥@KEY()↓
;jpn:◆おまえは　すうじを↓
;jpn:　へらしているとこを　みるのが↓
;jpn:　しゅみなのか？@KEY()↓
;jpn:◆６２@WI(15)　６１@WI(15)　６０@WI(15)　５９‥‥
@KEYNP()
@SETF(FLG_MOON_NUMBERMAN_B2)
』

_MOON_I_NUMBERMAN_B_AFTER2;
◆９　　８　　７　　６　　５　　４　　３　　２　　１　　０．．．↓
　　Ｂａｂｏｏｏｏｏｏｏｏｍ！！@KEY()↓
◆Ｗｏｗ！　　Ｉ　ｓｃａｒｅｄ　ｍｙｓｅｌｆ．

;◆９　８　７　６　５　４↓
;jpn:　３　２　１　０‥‥↓
;jpn:　ドッカアーーーーン！！@KEY()↓
;jpn:◆‥‥ああ@WI(20)　びっくりした！
@KEYNP()
@SETF(FLG_MOON_NUMBERMAN_B3)
』

_MOON_I_NUMBERMAN_B_AFTER3;
◆Ｉ　ｇｏｔ　ｓｕｒｐｒｉｓｅｄ．
;jpn:◆さっきは　びっくりしたよな。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｋ
;@Figure:ランマ女
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_K
MSG_MOON_K;
◆Ｉ　ｓｐｙ　ｗｉｔｈ　ｍｙ　ｌｉｔｔｌｅ　ｅｙｅ．．．↓
　　Ａｌｌａｋａｚａｍ！@KEY()↓
◆Ｉ　ｓｅｅ　ａ　ｃｏｕｎｔｒｙ　ｉｎ　ｓｕｍｍｅｒ　ａｎｄ　ａ　ｂｉｇ　ｓｉｌｖｅｒ　ｂａｌｌ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｂｕｒｎｔ，　ｂｕｔ　ｙｏｕ’ｒｅ　ｆｉｎｅ．@KEY()↓
◆．．．Ｔｈａｔ　ｉｓ　ｗｈａｔ　Ｉ　ｓｅｅ．

;jpn:◆ケッハ　モルタア！@WI(20)↓
;jpn:　ケッハ　モヌラタア！@KEY()↓
;jpn:◆ぎんいろの　おおきなたまで↓
;jpn:　なつのくに@KEY()↓
;jpn:◆くろこげの　あなたは↓
;jpn:　どっこい　だいじょうぶ@KEY()↓
;jpn:◆‥‥わたしには　みえるのです。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｌ
;@Figure:パンク青年
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_L
MSG_MOON_L;
◆Ｈａ！　ｅｖｅｒｙｏｎｅ　ｉｓ　ｓｏｍｅｏｎｅ！@KEY()↓
◆Ｄｏｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｓｏ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆どいつも　こいつもだ！@KEY()↓
;jpn:◆‥‥そう　おもわないか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_L_YES,_MOON_L_NO)

_MOON_L_NO;
◆Ｗａ　ｈａ　ｈａ！@KEY()↓
◆．．．Ｈｅ　ｈｅ　ｈｅ．．．！

;jpn:◆アッハッハ！@KEY()↓
;jpn:◆‥‥イヒヒ！
@KEYNP()
』

_MOON_L_YES;
◆Ｍｏｏ　ｎｓｉ　ｄｅｍ　ｏｏｎｓ　ｉｄｅ．

;jpn:◆ムーンサ@WI(15)　ムーンサ@WI(15)　ンサイ@WI(15)↓
;jpn:　ンサイ@WI(15)　ンサイ@WI(15)　ムーンサ。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｍ
;@Figure:用心棒
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_M
MSG_MOON_M;
;（病院に飛ばされる。親切？）
◆Ｉ　ｗｉｌｌ　ｓｅｎｄ　ｔｈｅ　ｆｉｒｓｔ　ａｎｄ　ｔｈｅ　ｓｅｃｏｎｄ．．．@KEY()↓
◆ｔｏ　ｔｈｅ　ｈｏｓｐｉｔａｌ．

;jpn:◆おまえ　その１と↓
;jpn:　おまえ　その２を‥‥@KEY()↓
;jpn:◆びょういんおくりに　してやる！
@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_HOSPITAL)
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｎ
;@Figure:マスク
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_N
MSG_MOON_N;
;（驚かすだけ。ＨＰはそのまま）
◆@DSP_STS(STS_PC_NAME_NES)’ｓ　ＨＰ　ｄｒｏｐｓ　ｔｏ　０！@KEY()↓
◆@DSP_STS(STS_PC_NAME_JEFF)’ｓ　ＨＰ　ｄｒｏｐｓ　ｔｏ　０！

;jpn:◆@DSP_STS(STS_PC_NAME_NES)のＨＰは↓
;jpn:　０になった！@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)のＨＰは↓
;jpn:　０になった！
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｏ
;@Figure:サラリーマンＡ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_O
MSG_MOON_O;
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｍｏｏｎｓｉｄｅ．@KEY()↓
◆Ｗｅｃｏｍｅｌ　ｔｏ　Ｓｏｏｎｍｉｄｅ．@KEY()↓
◆Ｍｏｏｎｗｅｌ　ｏｔ　ｃｏｓｉｄｍｅ．
;jpn:◆ようこそ　ムーンサイドへ。@KEY()↓
;jpn:◆よムうこ　そーンサイドへ。@KEY()↓
;jpn:◆ムよーン　サうイこドそへ。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｐ
;@Figure:ゴロツキ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_P
MSG_MOON_P;
◆Ｈｏｗ　ａｂｏｕｔ　Ｉ　ｓｈａｒｐｅｎ　ｙｏｕ？@KEY()↓
◆Ｉ　ｊｕｓｔ　ｌｏｖｅ　ｓｈａｒｐｅｎｉｎｇ．↓
　　Ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｍｅ　ｔｏ　ｓｈａｒｐｅｎ？@KEY()↓
◆Ｓｉｄｅｍ　ｏｏｎｓｉ　ｄｅｍｏｏｎ．↓
　　Ｗｅｌｃ　ｗｅｌｃ　ｏｍｅｗｅｌｃ　ｏｍｅｏｍｅ．

;jpn:◆けずって　あげようか？@WI(20)↓
;jpn:　おれは　けずるの　すきだな。@WI(20)↓
;jpn:　きみたち　けずられたいんだろ？@KEY()↓
;◆きみたち　エンピツだもんな。@KEY()↓
;jpn:◆ンサイ@WI(15)　ンサイ@WI(15)　ンサイドムー@WI(15)↓
;jpn:　こそよう@WI(15)　こそよう@WI(15)　こそよう。
@KEYNP()
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｑ
;@Figure:アーティスト
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_Q
MSG_MOON_Q;
◆Ｈｅｙ！　　Ｐａｒｋｉｎｇ　ｍｅｔｅｒｓ！↓
　　Ａｎｄ　ｙｏｕ’ｒｅ　ｗａｌｋｉｎｇ　ａｒｏｕｎｄ！@KEY()↓
◆Ｈａ　ｈａ　ｈａ．．．Ｔｈａｔ’ｓ　ｓｏ　ｆｕｎｎｙ@KEY()↓
◆Ｗｗｗｗｅｅｅｌｃｏｍｅ　ｃｏｍｅ　ｔｏ　Ｍｍｍｍｍｏｏｏｏｎｓｉｄｄｅｅｅ．

;jpn:◆あんたたちったら↓
;jpn:　ゆうびんポストのくせして↓
;jpn:　ふらふら　あるきまわったりして。@KEY()
;jpn:◆おかしいったら　ありゃしない。@KEY()↓
;jpn:◆ムムーーンンササイイドドへへ↓
;jpn:　よよううここそそ。
@KEYNP()
』

；----------------------------------------
;@Habitat:ムーンサイド／ドアのない部屋／どこか
;@Person:不透明人間
;@Figure:モヒカン
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_VISIBLEMAN
MSG_MOON_VISIBLEMAN;
;「不透明人間」
;（ある「通行人」から飛ばされる先が「ドアのない部屋」で、彼はそこの住人）
@CHKFGOTO(FLG_MOON_INVISIBLEMAN,_MOON_VISIBLEMAN_AFTER)
◆Ｉ’ｍ　ｒｅａｌｌｙ　ｂｕｓｙ　ｄｏｉｎｇ　ｎｏｔｈｉｎｇ，　ｓｏ　Ｉ　ｄｏｎ’ｔ　ｈａｖｅ　ｔｉｍｅ　ｔｏ　ｔａｌｋ　ｔｏ　ｙｏｕ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｎｅｅｄ　ｓｏｍｅｔｈｉｎｇ，　ｔａｌｋ　ｔｏ　ｍｙ　ｐａｒｔｎｅｒ．@KEY()↓
◆Ｈｅ’ｓ　ｒｉｇｈｔ　ｏｖｅｒ　ｔｈｅｒｅ．．．ｓｅｅ？@KEY()↓
◆Ｙｏｕ　ｍｅａｎ　ｙｏｕ　ｃａｎ’ｔ　ｓｅｅ　ｈｉｍ？
;jpn:◆おれは　いま　ヒマでヒマで↓
;jpn:　てが　はなせねえのよ。@KEY()↓
;jpn:◆ようじが　あるんなら↓
;jpn:　そこにいる　おれの　あいぼうに↓
;jpn:　はなしかけてみちゃ　どうだ？@KEY()↓
;jpn:◆ほら　そこに　いるだろうよ。

@KEYNP()
』

_MOON_VISIBLEMAN_AFTER;
;（室外に飛ばされる。つまり脱出できる）
◆Ｗｈａｔ　ｔｈｅ．．．？↓
　　Ｙｏｕ’ｒｅ　ｌｏｏｋｉｎｇ　ｆｏｒ　ｓｏｍｅ　ｋｉｎｄ　ｏｆ　ｄｏｏｒ？@KEY()↓
◆Ｗｅｌｌ，　ｙｏｕ’ｒｅ　ｎｏｔ　ｇｏｎｎａ　ｆｉｎｄ　ｏｎｅ！@KEY()↓
◆Ｓｏ，　ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｆａｃｅ，　ｌｏｓｅｒ．．．@KEY()↓
◆Ｉ　ｈａｖｅ　ｎｏ　ｐａｔｉｅｎｃｅ　ｗｈｅｎ　ｐｅｏｐｌｅ　ｉｎｔｅｒｒｕｐｔ　ｍｅ　ｗｈｉｌｅ　Ｉ’ｍ　ｂｕｓｙ　ｄｏｉｎｇ　ｎｏｔｈｉｎｇ．
;jpn:◆あんだって？@WI(20)↓
;jpn:　ドアを　さがしてる？@KEY()↓
;jpn:◆そんなもな　ここにゃ　ねえよ！@KEY()↓
;jpn:◆おれのヒマを　じゃまするやつぁ↓
;jpn:　こっから　でてけっ！
@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_MOON_FIELD_SOMEWHERE)
』


;@Habitat:ムーンサイド／ドアのない部屋／どこか
;@Person:透明人間
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLEMAN/off
;@ActionScript:＊固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLEMAN
MSG_MOON_INVISIBLEMAN;
;「透明人間」（「ドアのない部屋」にいる。見えないがヒットする）
◆Ｃａｎ　ｙｏｕ　ｓｅｅ　ｍｅ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆あんたら　おいらが　みえるのか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_INVISIBLEMAN_YES,_MOON_INVISIBLEMAN_NO)

_MOON_INVISIBLEMAN_NO;
◆Ｈａ　ｈａ．↓
　　Ｙｏｕ　ｃａｎ，　ｈｕｈ？@KEY()↓
◆Ｈｅ　ｈｅ．↓
　　Ｙｏｕ’ｖｅ　ｂｅｃｏｍｅ　ａ　ｒｅａｌ　Ｍｏｏｎｓｉｄｉａｎ，　ｈａｖｅｎ’ｔ　ｙｏｕ？

;jpn:◆ヒッヒ。@WI(15)↓
;jpn:　おいらが　みえるってか。@KEY()↓
;jpn:◆ヒッヒ@WI(15)　あんたら　りっぱな↓
;jpn:　ムーンサイドびとだぁよ。
@KEYNP()
@SETF(FLG_MOON_INVISIBLEMAN)
@SET_HIT_RECT(1,HRECT_MOON_A,MSG_MOON_INVISIBLE_1)
@FUNC(5)                ;毒死禁止
@SETF(FLG_SYS_MONSTER_OFF)
』

_MOON_INVISIBLEMAN_YES;
◆Ｈａ　ｈａ．↓
　　Ｙｏｕ　ｃａｎ’ｔ？@KEY()↓
◆Ｙｏｕ’ｒｅ　ｄｅｆｉｎｉｔｅｌｙ　ｎｏｔ　ｆｒｏｍ　ａｒｏｕｎｄ　ｈｅｒｅ．@KEY()↓
◆Ｈｅｅ　ｈｅｅ．↓
　　Ｇｅｔ　ｇｏｉｎｇ　ｎｏｗ．　　Ｈｅｒｅ’ｓ　ｙｏｕｒ　ｈａｔ，　ｗｈａｔ’ｓ　ｙｏｕｒ　ｈｕｒｒｙ．．．
;jpn:◆ヒッヒ。@WI(15)↓
;jpn:　おいらが　みえねえってか。@KEY()↓
;jpn:◆あんたら　ムーンサイドびとじゃ↓
;jpn:　ねえようだな@WI(15)　ヒッヒ。@KEY()↓
;jpn:◆はええとこ　でていきな@WI(15)　ヒッヒ。
@KEYNP()
』


；----------------------------------------
;@Habitat:ムーンサイド／フィールド／どこか
;@Person:透明人間の声１
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLE_1/on
;@ActionScript:＊オートメッセージ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLE_1
MSG_MOON_INVISIBLE_1;
;ドアのない部屋から脱出後
;ネスたちが歩いていると数秒おき
;あるいは数歩おきに出てくるセリフ
@OPEN(1)
◆Ｈｅ　ｈｅ　ｈａ！　　Ｉｔ’ｓ　ｍｅ！↓
　　Ｙｏｕ　ｃａｎ　ｓｅｅ　ｍｅ，　ｒｉｇｈｔ？@KEY()↓
◆Ｔｈｅｒｅ’ｓ　ｓｏｍｅｔｈｉｎｇ　ｉｎｔｅｒｅｓｔｉｎｇ　ａｂｏｕｔ　ｙｏｕ，　ｓｏ　Ｉ’ｍ　ｇｏｉｎｇ　ｔｏ　ｆｏｌｌｏｗ　ｙｏｕ．@KEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｒｙ，　ｔｈｏｕｇｈ．．．↓
　　Ｈｅｈ　ｈｅｈ．．．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｇｅｔ　ｉｎｔｏ　ａ　ｆｉｇｈｔ，　Ｉ’ｌｌ　ｓｔａｙ　ｏｕｔ　ｏｆ　ｉｔ．．．

;jpn:◆ヒッヒ@WI(15)　おいらだよ　おいら。↓
;jpn:　あんたらには　おいらのすがたが↓
;jpn:　みえている‥‥@WI(15)と。@KEY()↓
;jpn:◆なんだか　おもしろそうだから↓
;jpn:　おいらもいっしょに　ついていく。@KEY()↓
;jpn:◆しんぱい　すんなって@WI(15)　ヒッヒ。↓
;jpn:　あんたらが　バトルになっても↓
;jpn:　おいら@WI(15)　なーんも　しねえから。
@KEYNP()
@SET_HIT_RECT(1,HRECT_MOON_B,MSG_MOON_INVISIBLE_2)
@CLOSE()
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:透明人間の声２
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLE_2/on
;@ActionScript:＊オートメッセージ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLE_2
MSG_MOON_INVISIBLE_2;
@OPEN(1)
◆Ｈｅｈ　ｈｅｈ．↓
　　Ｙｏｕ　ｃａｎ’ｔ　ｓｅｅ　ｍｅ．．．ｒｉｇｈｔ？

;jpn:◆ヒッヒ。@KEY()↓
;jpn:◆あんたらには　おいらのすがたが↓
;jpn:　みえている‥‥@WI(15)と。
@KEYNP()
@SET_HIT_RECT(1,HRECT_MOON_C,MSG_MOON_INVISIBLE_3)
@CLOSE()
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:透明人間の声３
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLE_3/on
;@ActionScript:＊オートメッセージ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLE_3
MSG_MOON_INVISIBLE_3;
@OPEN(1)
◆Ｈｙｕｋ　ｈｕｙｋ．↓
　　Ｈｅｙ！@KEY()↓
◆Ｄｏｎ’ｔ　ｙｏｕ　ｗｉｓｈ　ｙｏｕ　ｈａｄ　ａ　ｇｏｌｄ　ｔｏｏｔｈ　ｌｉｋｅ　ｍｉｎｅ？@KEY()↓
◆Ｇｉｖｅ　ｍｅ　ａ　ｓｍｉｌｅ！↓
　　Ｈｅｈ　ｈｅｈ
;jpn:◆ヒッヒ。↓
;jpn:　なぁ　おい　あんたら‥‥@KEY()↓
;jpn:◆おいらの　この　きんば@WI(15)↓
;jpn:　うらやましいだろう？@KEY()↓
;jpn:◆にかっ　にかっ。
@KEYNP()
@SET_HIT_RECT(1,HRECT_MOON_D1,MSG_MOON_INVISIBLE_4_A)
@SET_HIT_RECT(2,HRECT_MOON_D2,MSG_MOON_INVISIBLE_4_B)
@CLOSE()
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:透明人間の声４
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLE_4/on
;@ActionScript:＊オートメッセージ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLE_4
MSG_MOON_INVISIBLE_4;
MSG_MOON_INVISIBLE_4_A;
@OPEN(1)
◆＊Ｇｒｉｎ＊Ｇｒｉｎ＊．@KEY()↓
◆Ｈｅｈ　ｈｅｈ．

;jpn:◆にかっ　にかっ。@KEY()↓
;jpn:◆ヒッヒ。
@KEYNP()
@RES_HIT_RECT(2)
@SET_HIT_RECT(1,HRECT_MOON_E1,MSG_MOON_INVISIBLE_5)
@CLOSE()
』

MSG_MOON_INVISIBLE_4_B;
@OPEN(1)
◆＊Ｓｍｉｌｅ＊Ｓｍｉｌｅ＊@KEY()↓
◆Ｈｅｈ　ｈｅｈ．

;jpn:◆にかっ　にかっ。@KEY()↓
;jpn:◆ヒッヒ。
@KEYNP()
@RES_HIT_RECT(1)
@SET_HIT_RECT(1,HRECT_MOON_E2,MSG_MOON_INVISIBLE_5)
@CLOSE()
』

;@Habitat:ムーンサイド／フィールド／どこか
;@Person:透明人間の声５
;@Figure:ヒットくん
;@AppearanceKey:FLG_MOON_INVISIBLE_5/on
;@ActionScript:＊オートメッセージ
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_INVISIBLE_5
MSG_MOON_INVISIBLE_5;
@OPEN(1)
◆Ｕｈ．．．Ｈｅｈ　ｈｅｈ．．．↓
　　Ｙｏ！@KEY()↓
◆Ｄｏｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｍｙ　ｅｙｅｂｒｏｗｓ　ｒｏｃｋ？@KEY()↓
◆Ｃｈｅｃｋ’ｅｍ　ｏｕｔ．．．ｔｈｅｙ’ｒｅ　ｃｏｎｎｅｃｔｅｄ！
 
;jpn:◆ヒッヒ。↓
;jpn:　なぁ　おい　あんたら‥‥@KEY()↓
;jpn:◆おいらの　この　まゆげ@WI(15)↓
;jpn:　つながってて　カッコエエだろ？
@KEYNP()
@CLOSE()
@FUNC(6)                ;毒死許可
@CLRF(FLG_SYS_MONSTER_OFF)
』


;@Habitat:ムーンサイド／フィールド／どこか
;@Person:通行人Ｒ
;@Figure:若い船乗り
;@AppearanceKey:FLG_MOON_R_DISAPPEAR/off
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_R
MSG_MOON_R;
;（彼がジャマで「マニマニ」のエリアに入ることができない）
@CHKFGOTO(FLG_MOON_INVISIBLEMAN,_MOON_R_AFTER)
◆Ｔｈｅ　Ｍａｎｉ　Ｍａｎｉ　Ｓｔａｔｕｅ　ｉｓ　ｕｐ　ａｈｅａｄ，　ｂｕｔ　Ｉ’ｍ　ｇｏｉｎｇ　ｔｏ　ｓｔｏｐ　ｙｏｕ　ｒｉｇｈｔ　ｈｅｒｅ．@KEY()↓
◆Ｄｏｎ’ｔ　ｅｖｅｎ　ｔｈｉｎｋ　ａｂｏｕｔ　ｇｅｔｔｉｎｇ　ｐａｓｔ　ｍｅ，@KEY()↓
◆’ｃａｕｓｅ　ｙｏｕ　ａｒｅｎ’ｔ　ｗｉｔｈ　ａ　ｇｕｙ@KEY()↓
◆ｗｈｏｓｅ　ｅｙｅｂｒｏｗｓ　ａｒｅ　ｃｏｎｎｅｃｔｅｄ　ａｎｄ　ｗｈｏ　ａｌｓｏ　ｈａｓ　ａ　ｇｏｌｄ　ｔｏｏｔｈ．

;jpn:◆マニマニのぞうなら↓
;jpn:　この　すぐさきに　ある。@WI(20)↓
;jpn:　だけど　おれが　じゃましてる。@KEY()↓
;jpn:◆まゆげがつながってて↓
;jpn:　きんばのおとこの　ひとりも↓
;jpn:　つれていないようなやつに@KEY()↓
;jpn:◆ここをとおる　しかくが↓
;jpn:　あるとおもうなよ！
@KEYNP()
@SETF(FLG_MOON_WARP_X)
』

_MOON_R_AFTER;
◆Ｔｈｅ　Ｍａｎｉ　Ｍａｎｉ　Ｓｔａｔｕｅ　ｉｓ　ｕｐ　ａｈｅａｄ，　ｂｕｔ　Ｉ’ｍ　ｇｏｉｎｇ　ｔｏ　ｓｔｏｐ　ｙｏｕ　ｒｉｇｈｔ　ｈｅｒｅ．@KEY()↓
◆Ｈｕｚｚａｈ！↓
　　Ｙｏｕ　ｒｅａｌｌｙ　ｓｕｒｐｒｉｓｅｄ　ｍｅ！@KEY()↓
◆Ｙｏｕ’ｒｅ　ｔｈｅ　ｍａｎ　ｗｈｏｓｅ　ｅｙｅｂｒｏｗｓ　ａｒｅ　ｃｏｎｎｅｃｔｅｄ　ａｎｄ　ｗｈｏ　ｈａｓ　ａ　ｇｏｌｄ　ｔｏｏｔｈ！@KEY()↓
◆Ｈｏｗ　ａｂｏｕｔ　ｗｅ　ｄｕｍｐ　ｔｈｅｓｅ　ｋｉｄｓ　ａｎｄ　ｇｏ　ｇｅｔ　ｓｏｍｅｔｈｉｎｇ　ｔｏ　ｄｒｉｎｋ！？
 
;jpn:◆マニマニのぞうなら↓
;jpn:　この　すぐさきに　ある。↓
;jpn:　だけど　おれが　じゃまして‥‥@KEY()↓
;jpn:◆おやおや　これは　おどろいた！@WI(20)↓
;jpn:　まゆげつながりの　きんばさん！@KEY()↓
;jpn:◆こんなガキども　ほっといて↓
;jpn:　バーボンでも　ひっかけに↓
;jpn:　さあ　いきましょうぜ！
@KEY()
@REMOVE_CHAR(PRSN_MNSD_FIELD_R,ANIM_MONO_R_MAN)
@WAITSYS()
@SETF(FLG_MOON_R_DISAPPEAR)
』

;@Habitat:ムーンサイド／フィールド／モノトリービル前
;@Person:幻影マシン
;@Figure:黄金のオスカー
;@AppearanceKey:0
;@ActionScript:＊正面向いて止ったまま
;@GoodsMessage:0
;@CheckMessage:MSG_MOON_MANIMANI
;@Message:0
MSG_MOON_MANIMANI;
◆（Ｉｔ　ｉｓ　ａ　ｇｏｌｄｅｎ　ｓｔａｔｕｅ　ｔｈａｔ　ｙｏｕ　ｈａｖｅ　ｓｅｅｎ　ｂｅｆｏｒｅ．）

;jpn:◆（まえに　みたことのある↓
;jpn:　おうごんぞうだった）
@KEY()
@GOSUB(MSG_BATTLE_MANIMANI)
@TRUE_GOTO(MSG_BATTLE_LOSE)
@WI(1)
;-----
@GOSUB(MSG_GLOBAL_DELIVERY_RESET)       ;場面転換時に配達を中止
;-----
@REMOVE_CHAR(PRSN_MNSD_FIELD_4A,ANIM_BLINK_SUICIDE)
@SETF(FLG_FOUR_MAID_APPEAR)
@SETF(FLG_WIN_MANIMANI)
@WARP(WARP_FOUR_BRGS_WAREHOUSE)
@FUNC(5)                ;マップ上での全滅禁止
@COLD_PLAYER(PC_ALL)
@WI(20)
MSG_CHECK_FOUR_MANIMANI;壊れたマニマニチェック時
@OPEN(1)
◆（Ｔｈｅ　Ｍａｎｉ　Ｍａｎｉ　ｓｔａｔｕｅ　ｗａｓ　ａｃｔｕａｌｌｙ　ａ　ｄｅｖｉｃｅ　ｔｈａｔ　ｃｒｅａｔｅｄ　ｉｌｌｕｓｉｏｎｓ．@KEY()↓
◆Ｔｈｅ　ｉｌｌｕｓｉｏｎ　ｄｅｖｉｃｅ　ｗａｓ　ｄｅｓｔｒｏｙｅｄ．）

;jpn:◆（「マニマニのあくま」は↓
;jpn:　げんえいマシーンだった。@KEY()↓
;jpn:◆げんえいマシーンは↓
;jpn:　はかいされた）
@KEYNP()
@CLOSEALL()
@SET_COMEBACK_POS(TLPT_FOURSIDE)
@FRESH_PLAYER(PC_ALL)
』

;-------------------------------------------------
;@Habitat:ムーンサイド／ムーンサイド博物館／どこか
;@Person:館員Ａ
;@Figure:サラリーマンＤ
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_MUSEUM_A
MSG_MOON_MUSEUM_A;
◆Ｂｏｎｅｓ　ａｒｅ　ｇｒｅａｔ！↓
　　Ｄｏ　ｙｏｕ　ｌｉｋｅ　ｂｏｎｅｓ，　ｔｏｏ？↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆ほねは　すばらしいです。@KEY()↓
;jpn:◆あなたも　ほねが↓
;jpn:　おすきなんですか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_MOON_MUSEUM_A_YES,_MOON_MUSEUM_A_NO)

_MOON_MUSEUM_A_NO;
◆Ｙｏｕ　ｌｉｋｅ　ｂｏｎｅｓ？↓
　　Ｂｏｎｅ　ｂｏｎｅ　ｂｏｎｅ．

;jpn:◆ほねが　おすきなんですね。↓
;jpn:　ほね@WI(15)　ほね@WI(15)　ほね。
@KEYNP()
』

_MOON_MUSEUM_A_YES;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｌｉｋｅ　ｂｏｎｅｓ？↓
　　Ｂｏｎｅ　Ｂｏｎｅ　Ｂｏｎｅ．

;jpn:◆ほねが　おきらいですか。↓
;jpn:　ほね@WI(15)　ほね@WI(15)　ほね。
@KEYNP()
』


;@Habitat:ムーンサイド／ムーンサイド博物館／どこか
;@Person:館員Ｂ
;@Figure:コモリター
;@AppearanceKey:0
;@ActionScript:＊小範囲うろつき
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_MUSEUM_B
MSG_MOON_MUSEUM_B;
◆Ｄｏ　ｙｏｕ　ｋｎｏｗ　ｗｈｏｓｅ　ｂｏｎｅｓ　ａｒｅ　ｏｎ　ｄｉｓｐｌａｙ　ｈｅｒｅ？@KEY()↓
◆Ｔｈｅ　ａｎｓｗｅｒ　ｉｓ．．．ｙｏｕｒ　ｂｏｎｅｓ．@KEY()↓
◆Ｍｙ　ｂｏｎｅｓ．@KEY()↓
◆Ｂｏｎｅ’ｓ　ｂｏｎｅｓ．@KEY()↓
◆Ｂｏｎｅ　ｂｏｎｅ　ｂｏｎｅ．

;jpn:◆ここに　てんじちゅうの　ほね@WI(15)↓
;jpn:　なんのほねか　わかりますか？↓
;jpn:　こたえはですね‥‥@KEY()↓
;jpn:◆あなたのほね。@KEY()↓
;jpn:◆わたしのほね。@KEY()↓
;jpn:◆ほねのほね。@KEY()↓
;jpn:◆ほね@WI(15)　ほね@WI(15)　ほね。
@KEYNP()
』

；----------------------------------------
;@Habitat:ムーンサイドホテル／フロント
;@Person:フロントマン
;@Figure:おじさんＢ
;@AppearanceKey:0
;@ActionScript:＊正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_HOTEL_DESK
MSG_MOON_HOTEL_DESK;
;◆おとまりでございますか。@KEY()↓;
@GOSUB(MSG_GLOBAL_HOTEL)
』

;@Habitat:ムーンサイド／ホテル／フロント
;@Person:ボーイ
;@Figure:ホテルボーイ
;@AppearanceKey:0
;@ActionScript:＊正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_HOTELPORTER
MSG_MOON_HOTELPORTER;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｔａｙ　ｏｖｅｒｎｉｇｈｔ？
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ａｌｗａｙｓ　ｇｉｖｉｎｇ　ｓｕｃｈ　ｇｅｎｅｒｏｕｓ　ｔｉｐｓ！@KEY()↓
◆．．．Ｏｈ，　Ｅｘｃｕｓｅ　ｍｅ，　Ｉ　ｈａｖｅｎ’ｔ　ｇｏｔｔｅｎ　ａｎｙ　ｔｉｐｓ　ｆｒｏｍ　ｙｏｕ．

;jpn:◆@DSP_NAME(0)さま‥‥@WI(15)↓
;jpn:　こんやも　おとまりですか。@KEY()↓
;jpn:◆いつもチップを↓
;jpn:　ありがとうございます。@KEY()↓
;jpn:◆‥‥あ@WI(15)　もらってなかったでした。↓
;jpn:　しつれいしました。
@KEYNP()
』

;@Habitat:ムーンサイド／ホテル／フロント
;@Person:電話
;@Figure:電話
;@AppearanceKey:0
;@ActionScript:＊固定
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_GLOBAL_TELEPHONE

;----------------------------------------
;@Habitat:ムーンサイド／病院／受付
;@Person:受付係
;@Figure:看護婦
;@AppearanceKey:0
;@ActionScript:＊正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_HOSPITAL_USHER
MSG_MOON_HOSPITAL_USHER;@MiuraAppended
;◆どなたに　ごめんかいですか？@KEY()
@GOSUB(MSG_NURSE_MOON)
』

;@Habitat:ムーンサイド／病院／診察室
;@Person:お医者さん
;@Figure:医者
;@AppearanceKey:0
;@ActionScript:＊正面向いて止まったまま
;@GoodsMessage:0
;@CheckMessage:0
;@Message:MSG_MOON_HOSPITAL_DOCTOR
MSG_MOON_HOSPITAL_DOCTOR;@MiuraAppended
;◆みてもらいたいのは↓
;　だれだね？@KEY()
@GOSUB(MSG_DOCTOR_MOON)
』
;------------------------------------------------

MSG_MOON_MONOTOLY;ムーンサイドのモノトリー
◆Ｄｏｎ’ｔ　ｄｏ　ａｎｙｔｈｉｎｇ　ｔｏ　ｍｅ！↓
　　Ｉ　ａｍ．．．Ｉ　ａｍ　ｎｏｔ　Ｍｏｎｏｔｏｌｉ！

;jpn:◆つきまとうな！@WI(30)↓
;jpn:　わ‥わたしは↓
;jpn:　モノトリーなんかじゃない！
@KEY()
@HIDE_CHAR(PRSN_MNSD_FIELD_Q,OBJFX_HIDE_VSTRIPE)
@WI(120)
@SETF(FLG_MOON_MONOTOLY_DISAPPEAR)
』
;------------------------------------------------

MSG_MOON_MUSEUM_PLATE;
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｍｏｏｎｓｉｄｅ！
　　Ｗｈｙ　ｄｉｄ　ｙｏｕ　ｃｏｍｅ　ｔｏ　Ｍｏｏｎｓｉｄｅ？
　　Ｈｏｗ　ｌｏｎｇ　ａｒｅ　ｙｏｕ　ｓｔａｙｉｎｇ　ｉｎ　Ｍｏｏｎｓｉｄｅ？

;jpn:◆ようこそ　ムーンサイドへ！↓
;jpn:　どうして　ムーンサイドを？↓
;jpn:　いつまで　ムーンサイドに？
@KEYNP()
』
;------------------------------------------------
;{ＰＡＧＥ}


