;//////////////////////////パラメータ変化/////////////////////////////////

MSG_BTL_OFFENSE_UP;
←
◆@DSP_OBJECT()’ｓ　ｏｆｆｅｎｓｅ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　オフェンスが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_DEFENSE_UP;
←
◆@DSP_OBJECT()’ｓ　ｄｅｆｅｎｓｅ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　ディフェンスが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_IQ_UP;
←
◆@DSP_OBJECT()’ｓ　ＩＱ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　ＩＱが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_GUTS_UP;
←
◆@DSP_OBJECT()’ｓ　ｇｕｔｓ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　ガッツが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_GUTS_DOWN;
←
◆@DSP_OBJECT()’ｓ　ｇｕｔｓ↓
　　ｗｅｎｔ　ｄｏｗｎ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()のガッツが↓
;jpn:　@DSP_CNUM()さがった！
@SE(SE_se29_b_defense_down)
@KEY()
@!

MSG_BTL_2GUTS_UP;
←
◆Ａｍａｚｉｎｇｌｙ　ｅｎｏｕｇｈ，　@DSP_OBJECT()’ｓ　ｇｕｔｓ↓
　　ｂｅｃａｍｅ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　ガッツが↓
;jpn:　なんと　@DSP_CNUM()になった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_SPEED_UP;
←
◆@DSP_OBJECT()’ｓ　ｓｐｅｅｄ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　スピードが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_VITA_UP;
←
◆@DSP_OBJECT()’ｓ　ｖｉｔａｌｉｔｙ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　バイタリティが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_LUCK_UP;
←
◆@DSP_OBJECT()’ｓ　ｌｕｃｋ↓
　　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　ラックが↓
;jpn:　@DSP_CNUM()あがった！
@SE(SE_se28_b_offence_up)
@KEY()
@!

MSG_BTL_OFFENSE_DOWN;
←
◆@DSP_OBJECT()’ｓ　ｏｆｆｅｎｓｅ↓
　　ｗｅｎｔ　ｄｏｗｎ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()のオフェンスが↓
;jpn:　@DSP_CNUM()さがった！
@SE(SE_se29_b_defense_down)
@KEY()
@!

MSG_BTL_DEFENSE_DOWN;
←
◆@DSP_OBJECT()’ｓ　ｄｅｆｅｎｓｅ↓
　　ｗｅｎｔ　ｄｏｗｎ　ｂｙ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()のディフェンスが↓
;jpn:　@DSP_CNUM()さがった！
@SE(SE_se29_b_defense_down)
@KEY()
@!

;/////////////////////////////特殊グッズ//////////////////////////

MSG_BTL_G_HAEMITU_G;
←
◆@DSP_ACTOR()　ｏｐｅｎｅｄ↓
　　ｔｈｅ　ｊａｒ　ｏｆ　”Ｆｌｙ　Ｈｏｎｅｙ”！
;jpn:　@DSP_ACTOR()は↓
;jpn:　はえみつのびんを　あけてみた！
@KEY()↓
◆Ｍａｓｔｅｒ　Ｂｅｌｃｈ　ｇｒａｂｂｅｄ↓
　　ｔｈｅ　”Ｆｌｙ　Ｈｏｎｅｙ”！
;jpn:　ゲップーは↓
;jpn:　はえみつを　うばいとった！
;@SE((ばしっ))
@KEY()
@!

MSG_BTL_G_HAEMITU_NG;
←
◆@DSP_ACTOR()　ｏｐｅｎｅｄ↓
　　ｔｈｅ　ｊａｒ　ｏｆ　”Ｆｌｙ　Ｈｏｎｅｙ”！
;jpn:　@DSP_ACTOR()は↓
;jpn:　はえみつのびんを　あけてみた！
@KEY()↓
◆Ｉｔ　ｄｉｄｎ’ｔ　ｓｍｅｌｌ　ｌｉｋｅ↓
　　ｓｏｍｅｔｈｉｎｇ　@GOSUB(MSG_ESUB_HE_SHE_GACT)　ｗｏｕｌｄ　ｌｉｋｅ！
;jpn:　すきになりにくい　においがした！
@KEY()
@!

;////////////////////////////いのる///////////////////////////////

MSG_BTL_INORU_1;●(akm0616 w/itoi)
←
◆Ａ　ｍｙｓｔｅｒｉｏｕｓ　ｌｉｇｈｔ　ｅｎｖｅｌｏｐｅｄ↓
　　@GOSUB(MSG_ESUB_DSP_PARTY)！
;jpn:　ふしぎなひかりが↓
;jpn:　@DSP_LCNAME()を　つつんだ！
@KEY()
@!

MSG_BTL_INORU_2;
←
;@SE((ほわーん))
◆Ａ　ｗａｒｍ　ｌｉｇｈｔ　ｓｕｒｒｏｕｎｄｅｄ↓
　　@GOSUB(MSG_ESUB_DSP_PARTY)！
;jpn:　あたたかいひかりが↓
;jpn:　@DSP_LCNAME()を　つつんだ！
@KEY()
@!

MSG_BTL_INORU_3;
←
;@SE((ぶしししっ))
◆Ａ　ｄａｚｚｌｉｎｇ　ｌｉｇｈｔ　ｅｎｖｅｌｏｐｅｄ↓
　　@GOSUB(MSG_ESUB_DSP_PARTY)！
;jpn:　まぶしいひかりが↓
;jpn:　あたりに　ふりそそいだ！
@KEY()
@!

MSG_BTL_INORU_4;
←
;@SE((どよーん))
◆Ｓｏｍｅ　ｈｅａｖｙ　ａｉｒ　ｆｌｏｗｅｄ↓
　　ｉｎｔｏ　ｔｈｅ　ａｒｅａ！
;jpn:　おもいくうきが↓
;jpn:　あたりを　つつみこんだ！
@KEY()
@!

MSG_BTL_INORU_5;
←
;@SE((ばっしーん))
◆Ｔｈｅ　ｄａｚｚｌｉｎｇ　ｌｉｇｈｔ　ｃｈａｓｅｄ↓
　　ｔｈｅ　ｅｎｅｍｙ！
;jpn:　まばゆいひかりが↓
;jpn:　てきを　おいかけた！
@KEY()
@!

MSG_BTL_INORU_6;●(akm0616 w/itoi)
←
◆Ａ　ｖｅｒｙ　ｓｕｂｔｌｅ　ｌｉｇｈｔ　ｅｎｇｕｌｆｅｄ↓
　　@GOSUB(MSG_ESUB_DSP_PARTY)！
;jpn:　ほのかなひかりが↓
;jpn:　@DSP_LCNAME()を　つつんだ！
@KEY()
@!


MSG_BTL_INORU_7;
←
;@SE((ほわーん))
◆Ａ　ｇｏｌｄｅｎ　ｌｉｇｈｔ　ｐｏｕｒｅｄ↓
　　ｏｖｅｒ　ｔｈｅ　ａｒｅａ！
;jpn:　きんいろのひかりが↓
;jpn:　あたりに　ふりそそいだ！
@KEY()
@!

MSG_BTL_INORU_8;●(akm0616 w/itoi)
←
◆Ｒａｉｎｂｏｗ　ｃｏｌｏｒｅｄ　ｌｉｇｈｔ↓
　　ｓｈｏｎｅ　ｉｎｔｏ　ｔｈｅ　ａｒｅａ！
;jpn:　なないろのひかりが↓
;jpn:　あたりに　ふりそそいだ！
@KEY()
@!

MSG_BTL_INORU_9;●(akm0616 w/itoi)
←
◆Ａ　ｍｙｓｔｅｒｉｏｕｓ　ａｒｏｍａ　ｗａｆｔｅｄ↓
　　ｉｎｔｏ　ｔｈｅ　ａｒｅａ！
;jpn:　あやしいかおりが↓
;jpn:　あたりに　ただよった！
@KEY()
@!

MSG_BTL_INORU_10;●(akm0616 w/itoi)
←
◆Ａ　ｔｅｒｒｉｂｌｅ，　ｈｅａｖｅｎ　ｒｅｎｄｉｎｇ　ｓｏｕｎｄ，↓
　　ｅｃｈｏｅｄ　ｉｎ　ｔｈｅ　ａｒｅａ！
;jpn:　くうきをきりさくような　おとが↓
;jpn:　とどろきわたった！
@KEY()
@!

MSG_BTL_PP_ZERO;何人でも「ｔｈｅｉｒ」はＯＫ
←
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｌｏｓｔ　ｔｈｅｉｒ　ＰＰ！
;jpn:　ぜんいんの　ＰＰが↓
;jpn:　なくなって　しまった！
@KEY()
@!

MSG_BTL_ZENKAI;
←
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｒｅｃｏｖｅｒｅｄ↓
　　ｃｏｍｐｌｅｔｅｌｙ！
;jpn:　@DSP_LCNAME()は↓
;jpn:　かんぜんに　かいふくした！
@KEY()
@!

;////////////////////////////////ＰＳＩ///////////////////////////////////

MSG_BTL_PSI_CANNOT_MENU;
←
◆Ｎｏｔ　ｅｎｏｕｇｈ　ＰＰ！
;jpn:◆ＰＰがたりない！
@KEY()
@!

MSG_BTL_PSI_CANNOT;
←
@FUNC(8)	; 行動者サイドを返す。0ならばプレーヤー側
@FALSE_GOTO(_PSI_CANNOT_PLAYER_SIDE)
;; モンスターサイド SE
@SE(SE_se37_b_pk_fire4)
@GOTO(_SIDE_QUIT3)
;
_PSI_CANNOT_PLAYER_SIDE
;; プレーヤーサイド SE
@SE(SE_se1d_b_my_psi)
;
_SIDE_QUIT3
◆@DSP_ACTOR()
;jpn:　@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
　ｔｒｉｅｄ↓
　　@DSP_PSI(0)！
;jpn:　@DSP_PSI(0)をこころみた！
@KEY()↓
◆Ｂｕｔ，　@GOSUB(MSG_ESUB_HE_SHE_GACT)　ｄｉｄｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ＰＰ．
;jpn:　しかし　ＰＰがたりなかった！
@KEY()
@!

MSG_BTL_KAMINARI_HAZURE;
←
;　しかし↓
◆Ｉｔ　ｄｉｄｎ’ｔ　ｈｉｔ　ａｎｙｏｎｅ！
;jpn:　だれにも　あたらなかった！
@KEY()
@!

MSG_BTL_PPSUCK_ZERO;
←
◆@DSP_OBJECT()　ｄｏｅｓ　ｎｏｔ↓
　　ｈａｖｅ　ａｎｙ　ＰＰ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　ＰＰを　もっていなかった！
@KEY()
@!


;///////////////////////////最終戦闘のポーキー////////////////////////////

MSG_BTL_MECHPOKEY_1_TALK;
;悪魔のマシンのスイッチを切る
@CLOSE()
@WI(40)
@OPEN(1)
←
@SET_BTL_MSG(0)		;バトルメッセージ機能をリセットする
;@MESSAGE_SOUND(2)
◆Ｉ　ｕｎｄｅｒｓｔａｎｄ　ｙｏｕ　ｇｕｙｓ　ａｒｅ　ａｌｒｅａｄｙ　ｃｌａｉｍｉｎｇ　ｔｏ　ｂｅ　ｈｅｒｏｅｓ．@FKEY()↓
◆Ｗｅｌｌ，　ｉｔ　ｉｓ　ａ　ｇａｚｉｌｌｉｏｎ　ｙｅａｒｓ　ｔｏｏ　ｅａｒｌｙ　ｆｏｒ　ｙｏｕ　ｔｏ　ｏｐｐｏｓｅ　Ｇｉｙｇａｓ！@FKEY()↓
◆Ｙｏｕ　ｍｕｓｔ　ｆｅｅｌ　ｐｒｅｔｔｙ　ｓｔｕｐｉｄ　ｔｏ　ｋｅｅｐ　ｆｉｇｈｔｉｎｇ　ｗｉｔｈｏｕｔ　ｅｖｅｎ　ｋｎｏｗｉｎｇ@FKEY()↓
◆ｗｈａｔ　Ｇｉｙｇａｓ　ｌｏｏｋｓ　ｌｉｋｅ！@FKEY()↓
◆Ｉｆ　ｙｏｕ　ｗｅｒｅ　ｔｏ　ｅｖｅｒ　ｓｅｅ　Ｇｉｙｇａｓ，　ｙｏｕ’ｄ　ｂｅ　ｓｏ　ｐｅｔｒｉｆｉｅｄ　ｗｉｔｈ　ｆｅａｒ，@FKEY()↓
◆ｙｏｕ’ｄ　ｎｅｖｅｒ　ｂｅ　ａｂｌｅ　ｔｏ　ｒｕｎ　ａｗａｙ！@FKEY()↓
◆．．．Ｔｈａｔ’ｓ　ｈｏｗ　ｓｃａｒｙ　ｉｔ　ｉｓ！@FKEY()↓
◆Ｓｏ，　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔｕｒｎ　ｏｆｆ　ｔｈｅ　”Ｄｅｖｉｌ’ｓ↓　Ｍａｃｈｉｎｅ？”@FKEY()↓
◆Ｗｅｌｌ，　ｐｒｅｐａｒｅ　ｔｏ　ｂｅ　ａｍａｚｅｄ！
;jpn:◆おまえたちは↓
;jpn:　すっかり　えいゆうきどりで↓
;jpn:　いるらしいけど@FKEY()↓
;jpn:◆ギーグさまに　はむかうなんて↓
;jpn:　８まんねん　はやいや！@FKEY()↓
;jpn:◆だいたい　ギーグさまの↓
;jpn:　おすがたさえ　みえないで↓
;jpn:　たたかってるなんて@FKEY()↓
;jpn:◆むなしいだろ！　ハハハハ！@FKEY()↓
;jpn:◆この　すがたを　みたら↓
;jpn:　それだけで　こしをぬかすぜ！@FKEY()↓
;jpn:◆‥‥ほっんとに　こわいんだから。@FKEY()↓
;jpn:◆ちょっとだけ「あくまのマシン」の↓
;jpn:　スイッチをきって↓
;jpn:　みせてやろうか。@FKEY()↓
;jpn:　おどろけよ！
@SE(SE_se4a_foe_explosion)
@WI(150);←わざとです。
;@KEYNP()
;@MESSAGE_SOUND(1)
@CLOSE()
;@SET_BTL_MES(1)	;バトルメッセージ機能を復活させる
@!

MSG_BTL_MECHPOKEY_1_TALK_B;
←
@WI(80)
@OPEN(1)
@SET_BTL_MSG(0)		;バトルメッセージ機能をリセットする
;@MESSAGE_SOUND(2)
◆Ｓｏ，　ｉｓｎ’ｔ　ｔｈｉｓ　ｔｅｒｒｉｆｙｉｎｇ？@WI(30)↓
　　Ｉ’ｍ　ｔｅｒｒｉｆｉｅｄ，　ｔｏｏ．@FKEY()↓
◆Ｇｉｙｇａｓ　ｃａｎｎｏｔ　ｔｈｉｎｋ　ｒａｔｉｏｎａｌｌｙ　ａｎｙ　ｍｏｒｅ，@FKEY()↓
◆ａｎｄ　ｈｅ　ｉｓｎ’ｔ　ｅｖｅｎ　ａｗａｒｅ　ｏｆ　ｗｈａｔ　ｈｅ　ｉｓ　ｄｏｉｎｇ　ｎｏｗ．@FKEY()↓
◆Ｈｉｓ　ｏｗｎ　ｍｉｎｄ　ｗａｓ　ｄｅｓｔｒｏｙｅｄ　ｂｙ　ｈｉｓ　ｉｎｃｒｅｄｉｂｌｅ　ｐｏｗｅｒ．@FKEY()↓
◆Ｗｈａｔ　ａｎ　ａｌｌ－ｍｉｇｈｔｙ　ｉｄｉｏｔ！@WI(30)@FKEY()↓
◆Ｙｅｐ，　ｔｈａｔ’ｓ　ｗｈａｔ　ｈｅ　ｉｓ！@FKEY()↓
◆Ｈｅｈ　ｈｅｈ　ｈｅｈ　ｈｅｈ．．．@WI(30)↓
　　ａｎｄ　ｙｏｕ．．．ｙｏｕ　ｗｉｌｌ　ｂｅ．．．@WI(30)↓
　　ｊｕｓｔ　ａｎｏｔｈｅｒ　ｍｅａｌ　ｔｏ　ｈｉｍ！
;jpn:◆こわいだろ！@WI(30)↓
;jpn:　おれだって　こわいよ。@FKEY()↓
;jpn:◆ギーグは　もう↓
;jpn:　かんがえることすら　できないし@FKEY()↓
;jpn:◆じぶんが　なにをしているのかも↓
;jpn:　もう　わからないんだ。@FKEY()↓
;jpn:◆ギーグは　じぶんの　ちからの↓
;jpn:　あまりのつよさで@FKEY()↓
;jpn:◆じぶんの　じんかくさえ↓
;jpn:　はかいしてしまったのさ。@FKEY()↓
;jpn:◆とんでもない　ちからの↓
;jpn:　おおばかやろうさ！@WI(30)ギーグは！@FKEY()↓
;jpn:◆けっ　けっ　けっ！@DSP_STS(STS_PC_NAME_NES)↓
;jpn:　エサに　なれよ‥‥@WI(30)ギーグの！
;@MESSAGE_SOUND(1)
@WI(150);←わざとです。
;@KEYNP()
;@SE(SE_se5d)
@CLOSE()
@OPEN(14)
;@SET_BTL_MES(1)	;バトルメッセージ機能を復活させる
@!

MSG_BTL_MECHPOKEY_2_TALK_2;
@CLOSE()
@WI(60)
@OPEN(1)
@SET_BTL_MSG(0)		;バトルメッセージ機能をリセットする
;@MESSAGE_SOUND(2)
←
◆Ｈｅｈ　ｈｅｈ　ｈｅｈ　ｈｅｈ．@WI(30)↓
　　Ｙｏｕ　ｍｕｓｔ　ｒｅａｌｌｙ　ｂｅ↓
　　ａｔ　ｔｈｅ　ｅｎｄ　ｏｆ　ｙｏｕｒ　ｒｏｐｅ．@FKEY()↓
◆Ｉｎ　ｔｈｉｓ　ｂｉｚａｒｒｅ　ｄｉｍｅｎｓｉｏｎ，↓
　　ｙｏｕ　ｆｏｕｒ　ａｒｅ　ｔｈｅ　ｏｎｌｙ　ｆｏｒｃｅ　ｆｉｇｈｔｉｎｇ　ｆｏｒ　ｊｕｓｔｉｃｅ．．．@FKEY()↓
◆Ａｎｄ　ｈｅｒｅ　ｙｏｕ　ｓｔａｎｄ，@FKEY()↓
◆ｗａｉｔｉｎｇ　ｔｏ　ｂｅ　ｂｕｒｎｅｄ　ｕｐ　ｗｉｔｈ　ａｌｌ　ｔｈｅ　ｒｅｓｔ　ｏｆ　ｔｈｅ　ｇａｒｂａｇｅ　ｏｆ　ｔｈｉｓ　ｕｎｉｖｅｒｓｅ．．．@FKEY()↓
◆Ｈａａａａａｈ！@WI(30)↓
　　Ｔｈａｔ’ｓ　ｓｏ　ｓａｄ．　Ｉ　ｃａｎ’ｔ　ｈｅｌｐ↓
　　ｂｕｔ　ｓｈｅｄ　ａ　ｔｅａｒ．@FKEY()↓
◆Ｙｏｕ　ｋｎｏｗ，　ｍｙ　ｈｅａｒｔ　ｉｓ　ｂｅａｔｉｎｇ　ｉｎｃｒｅｄｉｂｌｙ　ｆａｓｔ，@WI(30)↓
@FKEY()↓
◆．．．Ｉ　ｍｕｓｔ　ｂｅ　ｅｘｐｅｒｉｅｎｃｉｎｇ　ａｂｓｏｌｕｔｅ　ｔｅｒｒｏｒ！@FKEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｃｒｅａｍ　ｆｏｒ　ｈｅｌｐ↓
　　ｈｅｒｅ　ｉｎ　ｔｈｅ　ｄａｒｋ？！@FKEY()↓
◆Ｈａ　ｈａ　ｈａ　ｈａ　ｈａ！@FKEY()↓
◆Ｗｈｙ　ｎｏｔ　ｃａｌｌ　ｙｏｕｒ　ｍｏｍｍｙ，↓
　　@DSP_STS(STS_PC_NAME_NES)！@FKEY()↓
◆Ｓａｙ，　”Ｍｏｍｍｙ！　　Ｄａｄｄｙ！↓
　　Ｉ’ｍ　ｓｏ　ｆｒｉｇｈｔｅｎｅｄ！　@WI(30)Ｉ　ｔｈｉｎｋ↓
　　Ｉ’ｍ　ｇｏｎｎａ　ｗｅｔ　ｍｙ　ｐａｎｔｓ！”@FKEY()↓
◆Ｉ　ｋｎｏｗ　ｙｏｕ　ｈａｖｅ　ｔｅｌｅｐａｔｈｙ，　ｏｒ　ｓｏｍｅｔｈｉｎｇ，　ｓｏ　ｊｕｓｔ　ｔｒｙ　ａｎｄ　ｃａｌｌ　ｆｏｒ　ｈｅｌｐ，@FKEY()↓
◆ｙｏｕ　ｐａｔｈｅｔｉｃａｌｌｙ　ｗｅａｋ↓
　　ｈｅｒｏｅｓ　ｏｆ　ｓｏ－ｃａｌｌｅｄ　ｊｕｓｔｉｃｅ！@FKEY()↓
◆Ｎｏ　ｏｎｅ　ｗｉｌｌ　ｈｅｌｐ　ｙｏｕ　ｎｏｗ！@FKEY()↓
◆Ｈａ　ｈａ　ｈａ　ｈａａｈ．．．@FKEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｒｙ，　ｙｏｕｒ　ｐｉｔｉｆｕｌ　ｓｕｆｆｅｒｉｎｇ↓
　　ｗｉｌｌ　ｂｅ　ｏｖｅｒ　ｓｏｏｎ！
;jpn:◆けっ　けっ　けっ　けっ。@WI(30)↓
;jpn:　おまえたちの　ちからも↓
;jpn:　そんなもんで　せいいっぱいだろ。@FKEY()↓
;jpn:◆この　いじげんくうかんに↓
;jpn:　せいぎのみかたとやらは↓
;jpn:　おまえら　よにんだけ‥‥。@FKEY()↓
;jpn:◆だれにも　しられず↓
;jpn:　うちゅうのゴミになって↓
;jpn:　きえるのを　まつばかり‥‥。@FKEY()↓
;jpn:◆くーっ@WI(30)↓
;jpn:　かなしいはなしだよ。↓
;jpn:　なみだが　でるね。@FKEY()↓
;jpn:◆おれも　ドキドキしてるんだよ。@WI(30)↓
;jpn:　‥‥こわくてさ。@FKEY()↓
;jpn:◆この　まっくらやみに　むかって↓
;jpn:　たすけを　よんでみるかい。@FKEY()↓
;jpn:◆ハハハハハ。@FKEY()↓
;jpn:◆ママーッ！　@WI(20)って↓
;jpn:　さけんで　みろよ↓
　@DSP_STS(STS_PC_NAME_NES)！@FKEY()↓
;jpn:◆ママーッ！　パパーッ！↓
;jpn:　おしっこもれちゃいそうに↓
;jpn:　こわいよう！　@WI(30)ってか。@FKEY()↓
;jpn:◆テレパシーでもなんでも↓
;jpn:　つかえるもんなら↓
;jpn:　たすけをよんでみれば　いいさ。@FKEY()↓
;jpn:◆よわむしけむしの↓
;jpn:　せいぎのみかたさん！@FKEY()↓
;jpn:◆だーれも　きちゃ　くれないぞ。@FKEY()↓
;jpn:◆けっけっけっけっ‥‥。@FKEY()↓
;jpn:◆はやく　らくになりなっ！
;@MESSAGE_SOUND(1)
@WI(150);←わざとです。
;@KEYNP()
;@SE(SE_se5d)
@CLOSE()
@OPEN(14)
;@SET_BTL_MES(1)	;バトルメッセージ機能を復活させる
@!

MSG_BTL_POKEY_RUN_AWAY;
;捨てぜりふ
@CLOSE()
@WI(60)
@OPEN(1)
@SET_BTL_MSG(0)		;バトルメッセージ機能をリセットする
;@MESSAGE_SOUND(2)
◆@DSP_STS(STS_PC_NAME_NES)！@WI(30)　Ｎｏｗ，　Ｉ．．．↓
　　ｗｅｌｌ．．．　@WI(20)Ｉｔ’ｓ　ｇｏｉｎｇ　ｔｏ　ｓｅｅｍ　ｌｉｋｅ↓
　　Ｉ’ｍ　ｒｕｎｎｉｎｇ　ａｗａｙ．@FKEY()↓
◆Ｂｕｔ　ｐｅｒｈａｐｓ　Ｉ’ｌｌ　ｊｕｓｔ　ｓｎｅａｋ　ａｗａｙ　ｔｏ　ａｎｏｔｈｅｒ　ｅｒａ　ｔｏ　ｔｈｉｎｋ　ａｂｏｕｔ　ｍｙ　ｎｅｘｔ　ｐｌａｎ．@FKEY()↓
◆Ｉｔ’ｓ　ａ　ｇｏｏｄ　ｂｅｔ　ｔｈａｔ　ｗｅ　ｗｉｌｌ　ｓｅｅ　ｅａｃｈ↓
　　ｏｔｈｅｒ　ａｇａｉｎ．．．．@WI(30)↓
　　Ａｌｌ　ｒｉｇｈｔ！　　Ｉ’ｌｌ　ｂｅ　ｓｅｅｉｎｇ　ｙｏｕ！@FKEY()↓
◆Ｓｏ　ｎｏｗ　ｗｈｉｃｈ　ｏｎｅ　ｏｆ　ｕｓ　ｄｏ　ｙｏｕ　ｔｈｉｎｋ　ｉｓ　ｔｈｅ　ｃｏｏｌ　ｇｕｙ？！
;jpn:◆@DSP_STS(STS_PC_NAME_NES)！@WI(30)　ぼくは　いまは↓
;jpn:　つまり　その@WI(20)　あえて↓
;jpn:　にげるような　こうどうをとる。@FKEY()↓
;jpn:◆どこかのじだいに　もぐりこんで↓
;jpn:　ひとまず　つぎのプランを↓
;jpn:　ねるつもりさ。@FKEY()↓
;jpn:◆えんがあったら　また　あうさ。↓
;jpn:　シー　ユー　アゲイン！@FKEY()↓
;jpn:◆ほんとに　カッコイイのは↓
;jpn:　どっちかな？！
;@MESSAGE_SOUND(1)
@WI(150);←わざとです。
;@KEYNP()
@SE(SE_se41_b_pk_starstorm2)
@CLOSE()
;@SET_BTL_MES(1)	;バトルメッセージ機能を復活させる
@!

