;
;
;
;
;///////////////////////////特殊状態////////////////////////////////////

MSG_BTL_DAIYA_STAT;
←
◆@DSP_ACTOR()　ｃａｎｎｏｔ　ｍｏｖｅ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　うごくことが　できない！
@KEY()
@!

MSG_BTL_SHIBIRE_STAT;
←
◆@DSP_ACTOR()’ｓ　ｂｏｄｙ　ｉｓ↓
　　ｎｕｍｂ　ａｎｄ　@GOSUB(MSG_ESUB_HE_SHE_GACT)　ｃａｎ’ｔ　ｍｏｖｅ！
;jpn:　@DSP_ACTOR()の　からだは↓
;jpn:　しびれて　うごけない！
@KEY()
@!

MSG_BTL_KIMOCHI_STAT;
←
◆@DSP_ACTOR()　ｆｅｅｌｓ↓
　　ｔｏｏ　ｓｉｃｋ　ｔｏ　ｍｏｖｅ．．．
;jpn:　@DSP_ACTOR()は↓
;jpn:　きもちがわるくて　うごけない‥‥。
@KEY()
@!

MSG_BTL_MODOKU_STAT;
←
◆@DSP_ACTOR()↓
　　ｉｓ　ｐｏｉｓｏｎｅｄ！
;jpn:　@DSP_OBJECT()の　からだは↓
;jpn:　どくに　おかされている！
@KEY()
@!

MSG_BTL_NEMURI_STAT;
←
◆@DSP_ACTOR()　ｈａｓ↓
　　ｆａｌｌｅｎ　ａｓｌｅｅｐ！
;jpn:　@DSP_ACTOR()は　ねむっている！
@KEY()
@!

MSG_BTL_SHIBARA_STAT;
←
◆@DSP_ACTOR()　ｃａｎｎｏｔ↓
　　ｍｏｖｅ　ａｒｏｕｎｄ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　みうごきが　できない！
@KEY()
@!

MSG_BTL_FUUIN_STAT;
MSG_BTL_PSI_NO;
←
@FUNC(8)	; 行動者サイドを返す。0ならばプレーヤー側
@FALSE_GOTO(_PSI_FUUIN_PLAYER_SIDE)
;; モンスターサイド SE
@SE(SE_se37_b_pk_fire4)
@GOTO(_SIDE_QUIT2)
;
_PSI_FUUIN_PLAYER_SIDE
;; プレーヤーサイド SE
@SE(SE_se1d_b_my_psi)
;
_SIDE_QUIT2
◆@DSP_ACTOR()
;jpn:　@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
　ｔｒｉｅｄ↓
　　@DSP_PSI(0)！
;jpn:　@DSP_PSI(0)を　こころみた！
@SE(SE_se57_foe_ferformance)
@KEY()↓
◆Ｂｕｔ　ｉｔ　ｄｉｄｎ’ｔ　ｗｏｒｋ　ｖｅｒｙ　ｗｅｌｌ！
;jpn:　しかし　うまくいかない！
@KEY()
@!

MSG_BTL_GARD_ON;
←
◆@DSP_OBJECT()　ｉｓ↓
　　ｏｎ　ｇｕａｒｄ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　ガードしている！
@KEY()
@!

MSG_BTL_HAEMITU_KUU;
←
◆@DSP_OBJECT()　ｌｏｓｔ↓
　　ｈｉｓ　ｍｉｎｄ　ｂｙ　ｗｏｌｆｉｎｇ　ｄｏｗｎ　”Ｆｌｙ　Ｈｏｎｅｙ”！
;NOTE: Mr. Fukuda said "Haemitsu" might mean honey. DAN
;jpn:　@DSP_ACTOR()は　すべてを　わすれて↓
;jpn:　はえみつを　むさぼりくっている！
@KEY()
@!

;
;

;93.12.23
;-------------------------------------------------------------------
;ホームシック時にバトルで表示されるメッセージの変更

MSG_BTL_HOME_STAT;
;以下の_A～_Dのうち、どれかをランダムに表示するようにして下さい。
@RAND(3)
@ONGOTO(MSG_BTL_HOME_STAT_B,MSG_BTL_HOME_STAT_C,MSG_BTL_HOME_STAT_D)
MSG_BTL_HOME_STAT_A;
←
◆@DSP_ACTOR()　ｍｉｓｓｅｓ　ｈｏｍｅ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　いえが　こいしくなった。
@KEY()
@!

MSG_BTL_HOME_STAT_B;
←
◆@DSP_ACTOR()　ｓｕｄｄｅｎｌｙ　ｔｈｏｕｇｈｔ　ａｂｏｕｔ　ｈｉｓ　Ｍｏｍ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　ママを　おもいだしてしまった。
@KEY()
@!

MSG_BTL_HOME_STAT_C;
←
◆@DSP_ACTOR()　ｔｈｏｕｇｈｔ　ａｂｏｕｔ　ｅａｔｉｎｇ　ｓｏｍｅ　@DSP_STS(STS_PARTY_FAVORITE_FOODS)↓
　　ａｎｄ　ｓｔａｒｔｅｄ　ｃｒａｖｉｎｇ　ｉｔ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　@DSP_STS(STS_PARTY_FAVORITE_FOODS)が　たべたくなった。
@KEY()
@!

MSG_BTL_HOME_STAT_D;
←
◆@DSP_ACTOR()　ｌｏｓｔ　ａｌｌ　ｍｏｔｉｖａｔｉｏｎ↓
　　ｉｎ　ｂａｔｔｌｅ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　たたかうのが　むなしくなった。
@KEY()
@!

;///////////////////////特殊イベント////////////////////////////////////

;ユダンロボの死亡時の行動
;「ガタピシ」が誤解されるおそれがあるため削除
MSG_BTL_TONZURA_BREAK_IN;
;@SE(SE_)
;←
;　@DSP_ACTOR()の　からだが↓
;　ガタピシと　おとを　たてはじめた！
;@FKEY()
@!

;ユダンロボの死亡時の行動 続き (トンズラを助けていない場合)
MSG_BTL_TONZURA_BREAK_IN_NG;
←
◆Ｂｌａｃｋ　ｓｍｏｋｅ　ｐｏｕｒｅｄ　ｆｒｏｍ↓
　　@DSP_ACTOR()’ｓ　ｂｏｄｙ！
;jpn:　@DSP_ACTOR()の　ボディから↓
;jpn:　まっくろなけむりが↓
@FKEY()
;↓
;;jpn:　もくもくと　たちのぼった！
;@FKEY()
↓
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｗａｓ↓
　　ｏｖｅｒｃｏｍｅ　ｂｙ　ｔｈｅ　ｓｍｏｋｅ！
;jpn:　@DSP_LCNAME()は↓
;jpn:　けむりに　まきこまれてしまった！
@FKEY()
↓
◆Ｙｏｕ　ｃａｎ’ｔ　ｓｅｅ　ａ　ｔｈｉｎｇ！
;jpn:　なにも　みえない！
@FKEY()
;【ここでグッズテレポートが実行されます】
@!

;ユダンロボの死亡時の行動 続き (トンズラを助けている場合)
MSG_BTL_TONZURA_BREAK_IN_OK;
;@SE(SE_)
←
◆Ａｌｌ　ｏｆ　ａ　ｓｕｄｄｅｎ，↓
　　ｓｏｍｅ　ｇｕｙｓ　ｒｕｓｈｅｄ　ｉｎｔｏ　ｔｈｅ　ｒｏｏｍ！
;jpn:　とつぜん！↓
;jpn:　おとこたちが　へやに　なだれこんできた！
@FKEY()
@BGMSTART(0,BGM_msc18)
@WI(60)
←
◆Ｉｔ　ｗａｓ　ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ！
;jpn:　トンズラブラザーズ！@WI(30)　だった！@WI(10)
@FKEY()
@CLOSE()
@WI(30)
@OPEN(1)
←
@SET_BTL_MSG(0)		;バトルメッセージ機能をリセットする
;@MESSAGE_SOUND(2)
◆Ｌｕｃｋｙ　ｑｕｉｃｋｌｙ　ｄｕｃｋｅｄ　ｂｅｈｉｎｄ　ｔｈｅ　ｒｏｂｏｔ！
;jpn:◆ラッキーは　ユダンロボのうしろに↓
;jpn:　すばやく　まわりこんだ！@WI(40)
@FKEY()
@SE(SE_se0b_tel_put)
@WI(60)
@CLS()
◆”Ｉ　ｆｌｉｐｐｅｄ　ｔｈｅ　ｓｗｉｔｃｈ，　ａｎｄ　ｉｔ　ｓｔｏｐｐｅｄ．　”@KEY()↓
◆”Ｈａ　ｈａ　ｈａ　ｈａｈ．．．↓
　　Ｇｅｅｚ，　ｗｈａｔ　ａ　ｌｏｓｅｒ　ｒｏｂｏｔ．　　Ｉｔ　ｗａｓ　ｓｏ　ｅａｓｙ　ｔｏ　ｓｔｏｐ！”
;jpn:◆スイッチを　きったら↓
;jpn:　とまったぜ！@FKEY()↓
;jpn:◆ははははは‥‥↓
;jpn:　わかりやすいやつだ！
@WI(20)
@FKEY()
@CLS()
◆”Ｔｈａｔ　ｗａｓ　ｑｕｉｃｋ　ｔｈｉｎｋｉｎｇ！”
；jpn:◆おまえ　あたまいいな。
@FKEY()
@WI(60)
;@MESSAGE_SOUND(1)
@SET_BTL_MSG(1)		;バトルメッセージ機能を復活させる
@CLOSE()
@OPEN(14)
@SETF(FLG_FOUR_BLDG_TONZURA_APPEAR);ユダンロボ消える
@!

;ゲロップの死亡時の行動
;これを実行後、バトルは終了する。
MSG_BTL_POO_BREAK_IN;
;@SE(SE_)
@ADD_PSI(PC_POO,2)
←
◆Ｓｕｄｄｅｎｌｙ，　@DSP_NAME(PC_POO)　ｓｗｏｏｐｅｄ　ｄｏｗｎ↓
　　ｆｒｏｍ　ｔｈｅ　ｓｋｙ！
;jpn:　とつぜん↓
;jpn:　@DSP_NAME(PC_POO)が　そらから　まいおりてきた！@FKEY()
@!

MSG_BTL_POO_BREAK_IN_2;
;【メッセージコマンドでプーをパーティに参加させ、プーのステイタスパネルを表示する】
←
◆@DSP_NAME(PC_POO)　ｕｓｅｄ　ｈｉｓ　ｎｅｗ　ｐｏｗｅｒ，@FKEY()↓
　　ＰＳＩ　Ｓｔａｒｓｔｏｒｍ！
;jpn:　@DSP_NAME(PC_POO)は　みにつけた↓
;jpn:　ほしをおとす　ほうほうを　ためした！
@FKEY()
↓
@!


;////////////////////////////////ＮＰＣ/////////////////////////////////////

MSG_BTL_POKEY_TALK_A;
@RAND(8)
@ONGOTO(MSG_BTL_POKEY_TALK_B,MSG_BTL_POKEY_TALK_C,MSG_BTL_POKEY_TALK_D,MSG_BTL_POKEY_TALK_E,MSG_BTL_POKEY_TALK_F,MSG_BTL_POKEY_TALK_G,MSG_BTL_POKEY_TALK_H,MSG_BTL_POKEY_TALK_I)
←
◆Ｐｏｋｅｙ　ｕｓｅｄ　@DSP_STS(STS_PC_NAME_NES)↓
　　ａｓ　ａ　ｓｈｉｅｌｄ！
;jpn:　ポーキーは　@DSP_STS(STS_PC_NAME_NES)を　たてにした！
;　ポーキーは　わめいている！↓
;@MESSAGE_SOUND(2)
;　「ひー@DSP_STS(STS_PC_NAME_NES)！　なんとか　しておくれよー！」
;@MESSAGE_SOUND(1)
@KEY()
@!
MSG_BTL_POKEY_TALK_B;
←
◆Ｐｏｋｅｙ　ｐｌａｙｅｄ　ｄｅａｄ！
;jpn:　ポーキーは　しんだふりをした！
@KEY()
;　ポーキーは　わめいている！↓
;@MESSAGE_SOUND(2)
;　「だれか　たすけてくれぇ！」
;@MESSAGE_SOUND(1)
@!
MSG_BTL_POKEY_TALK_C;
←
◆Ｐｏｋｅｙ　ｐｒｅｔｅｎｄｅｄ↓
　　ｔｏ　ｃｒｙ！
;jpn:　ポーキーは　なきまねをした！
;　ポーキーは　わめいている！↓
;@MESSAGE_SOUND(2)
;　「わー！　わー！　わー！」
;@MESSAGE_SOUND(1)
@KEY()
@!
MSG_BTL_POKEY_TALK_D;
←
◆Ｐｏｋｅｙ　ａｐｏｌｏｇｉｚｅｄ↓
　　ｐｒｏｆｕｓｅｌｙ！
;jpn:　ポーキーは　とにかくあやまった！
;　ポーキーは　わめいている！↓
;@MESSAGE_SOUND(2)
;　「うひー！　かんべんしてくれぇ！」
;@MESSAGE_SOUND(1)
@KEY()
@!
MSG_BTL_POKEY_TALK_E;
←
◆Ｐｏｋｅｙ　ｔｈｏｕｇｈｔ↓
　　ｔｏ　ｈｉｍｓｅｌｆ！
;jpn:　ポーキーは　とにかくはんせいした！
@KEY()
』
MSG_BTL_POKEY_TALK_F;
←
◆Ｐｏｋｅｙ　ａｃｔｅｄ↓
　　ａｌｌ　ｉｎｎｏｃｅｎｔ！
;jpn:　ポーキーは　むかんけいを　よそおった！
@KEY()
』
MSG_BTL_POKEY_TALK_G;
←
◆Ｐｏｋｅｙ　ｓｍｉｌｅｄ↓
　　ｉｎｓｉｎｃｅｒｅｌｙ！
;jpn:　ポーキーは　おあいそわらいをした！
@KEY()
』
MSG_BTL_POKEY_TALK_H;
←
◆Ｐｏｋｅｙ　ｃｏｍｐｌａｉｎｅｄ↓
　　ｔｏ　@DSP_STS(STS_PC_NAME_NES)！
;jpn:　ポーキーは　@DSP_STS(STS_PC_NAME_NES)に　もんくをいった！
@KEY()
』
MSG_BTL_POKEY_TALK_I;
←
◆Ｐｏｋｅｙ　ｔｒｉｅｄ　ｔｏ↓
　　ｅｄｇｅ　ｃｌｏｓｅｒ　ｔｏ　ｔｈｅ　ｅｎｅｍｙ！
;jpn:　ポーキーは　てきの　みかたになろうとした！
@KEY()
』


MSG_BTL_MYDOG_HOWLING;
←
◆@DSP_ACTOR()　ｉｓ↓
　　ｂａｒｋｉｎｇ！
;jpn:　@DSP_ACTOR()は　ほえている！↓
;@MESSAGE_SOUND(2)
;　「ワンワンワンワン！」
;@MESSAGE_SOUND(1)
@KEY()
@!


MSG_BTL_PICKEY_TALK;
←
◆@DSP_ACTOR()　ｉｓ↓
　　ｃｈａｎｔｉｎｇ　ａ　ｍａｇｉｃ　ｓｐｅｌｌ！
;jpn:　@DSP_ACTOR()は　おまじないを　となえている！
;　@DSP_ACTOR()は　おおごえでさけんだ！↓
;@MESSAGE_SOUND(2)
;　「おいポーキー！　ちゃんと　たたかえよ！」
;@MESSAGE_SOUND(1)
@KEY()
@!

MSG_BTL_TONY_TALK;
←
;　@DSP_ACTOR()は　さけんだ！↓
;@MESSAGE_SOUND(2)
;　「@DSP_STS(STS_PC_NAME_JEFF)！　だいじょうぶかい？」
;@MESSAGE_SOUND(1)
;@KEY()
@!

MSG_BTL_BALMON_TALK;
←
◆@DSP_ACTOR()　ｉｓ↓
　　ｐａｔｔｉｎｇ　ｈｉｓ　ｂｅｈｉｎｄ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　おしりペンペンを　している！
@KEY()
@!

;		バトル用メッセージスクリプト（効果時）

;/////////////////////////////直接タメージ///////////////////////////////////

;プレイヤーがダメージを受けた
MSG_BTL_DAMAGE;
←
@SE(SE_se2e_b_my_damage1)
◆@DSP_CNUM()　ＨＰ　ｏｆ　ｄａｍａｇｅ↓
　　ｔｏ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()に↓
;jpn:　@DSP_CNUM()のダメージ！
@KEY()
@!

;モンスターがダメージを受けた
MSG_BTL_DAMAGE_M;
←
@SE(SE_se1e_b_foe_damage1)
◆@DSP_CNUM()　ＨＰ　ｏｆ　ｄａｍａｇｅ↓
　　ｔｏ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()に↓
;jpn:　@DSP_CNUM()のダメージ！
@KEY()
@!

;プレイヤーがスマッシュでダメージを受けた
MSG_BTL_DAMAGE_SMASH;
←
@SE(SE_se2e_b_my_damage1)
◆@DSP_CNUM()　ＨＰ　ｏｆ　ｄａｍａｇｅ↓
　　ｔｏ　@DSP_OBJECT()！
;@SE(SE_se2f_b_my_damage2)
;jpn:　@DSP_OBJECT()に↓
;jpn:　@DSP_CNUM()のダメージ！
@KEY()
@!

;モンスターがスマッシュでダメージを受けた
MSG_BTL_DAMAGE_SMASH_M;

@SE(SE_se1e_b_foe_damage1)
;@SE(SE_se1f_b_foe_damage2)
◆@DSP_CNUM()　ＨＰ　ｏｆ　ｄａｍａｇｅ↓
　　ｔｏ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()に↓
;jpn:　@DSP_CNUM()のダメージ！
@KEY()
@!

;プレイヤーが致命的なダメージを受けた
MSG_BTL_DAMAGE_TO_DEATH;
←
@SE(SE_se2f_b_my_damage2)
◆@DSP_CNUM()　ＨＰ　ｏｆ　ｍｏｒｔａｌ　ｄａｍａｇｅ↓
　　ｔｏ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()に↓
;jpn:　@DSP_CNUM()のちめいてきな　ダメージ！
@KEY()
@!

MSG_BTL_SMASH_PLAYER;
←
@SE(SE_se1f_b_foe_damage2)
@KMOJI(1)
@KEY()
@!

MSG_BTL_SMASH_MONSTER;
←
@KMOJI(1)
@SE(SE_se2f_b_my_damage2)
@KEY()
@!

MSG_BTL_UTU_YOKETA;
←
@SE(SE_se23_b_hit_dodge)
◆@DSP_OBJECT()　ｄｏｄｇｅｄ↓
　　ｑｕｉｃｋｌｙ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　すばやく　よけた！
@KEY()
@!

MSG_BTL_TATAKU_YOKETA;
←
@SE(SE_se23_b_hit_dodge)
◆@DSP_OBJECT()　ｄｏｄｇｅｄ↓
　　ｑｕｉｃｋｌｙ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　すばやく　よけた！
@KEY()
@!

MSG_BTL_KIKANAI;
←
◆Ｉｔ　ｄｉｄ　ｎｏｔ　ｗｏｒｋ↓
　　ｏｎ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()には↓
;jpn:　こうかが　なかった！
@KEY()
@!

MSG_BTL_KIKANAI_B;（仮）
←
◆Ｉｔ　ｄｉｄ　ｎｏｔ　ｗｏｒｋ↓
　　ｏｎ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()には↓
;jpn:　こうかが　なかった！
@KEY()
@!

MSG_BTL_HEAL_NG;
←
◆Ｉｔ　ｈａｄ　ｎｏ　ｖｉｓｉｂｌｅ　ｅｆｆｅｃｔ↓
　　ｏｎ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()には↓
;jpn:　こうかが　あらわれなかった！
@KEY()
@!

MSG_BTL_KIKANAI_C;（仮）
←
　Ｉｔ　ｄｉｄ　ｎｏｔ　ｗｏｒｋ↓
　　ｏｎ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()には↓
;jpn:　こうかが　なかった！
@KEY()
@!

MSG_BTL_KARABURI;
←
@SE(SE_se22_b_hit_miss)
◆Ｊｕｓｔ　ｍｉｓｓｅｄ！
;jpn:　からぶりー！
@KEY()
@!

MSG_BTL_KARABURI_UTSU;
←
@SE(SE_se22_b_hit_miss)
◆．．．ｎａｒｒｏｗｌｙ　ｍｉｓｓｅｄ↓
　　ｈｉｔｔｉｎｇ　ｔｈｅ　ｔａｒｇｅｔ！
;jpn:　‥‥はずれた！
@KEY()
@!

MSG_BTL_NOT_EXIST;
←
◆Ｂｕｔ　@DSP_OBJECT()　ｗａｓ↓
　　ａｌｒｅａｄｙ　ｇｏｎｅ．．．
;jpn:　しかし　@DSP_OBJECT()は↓
;jpn:　すでに　いなかった‥‥。
@KEY()
@!


;///////////////////////////////吸い取りダメージ//////////////////////////////

MSG_BTL_HPSUCK_ME;
←
◆@DSP_ACTOR()　ｄｒａｉｎｅｄ　@GOSUB(MSG_ESUB_HIS_HER_GACT)　ｏｗｎ　ＨＰ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　じぶんのＨＰを　すいとった！
@KEY()
@!

MSG_BTL_HPSUCK_ON;
←
◆Ｄｒａｉｎｅｄ　@DSP_CNUM()　ＨＰ↓
　　ｆｒｏｍ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()から↓
;jpn:　@DSP_CNUM()のＨＰを　すいとった！
@KEY()
@!

MSG_BTL_PPSUCK;
←
◆Ｄｒａｉｎｅｄ　@DSP_CNUM()　ＰＰ↓
　　ｆｒｏｍ　@DSP_OBJECT()！
;jpn:　@DSP_OBJECT()のＰＰを↓
;jpn:　@DSP_CNUM()すいとった！
@KEY()
@!

MSG_BTL_PPSUCK_OBJ;
←
◆@DSP_OBJECT()　ｄｒａｉｎｅｄ↓
　　@DSP_CNUM()　ＰＰ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　@DSP_CNUM()のＰＰを　すいとられた！
@KEY()
』

MSG_BTL_KIMOCHI_DAMAGE;
←
◆@DSP_ACTOR()　ｆｅｌｔ　ｓｉｃｋ↓
　　ａｎｄ　ｔｏｏｋ　@DSP_CNUM()　ＨＰ　ｄａｍａｇｅ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　きもちがわるくて　@DSP_CNUM()のダメージ！
@KEY()
@!

;「猛毒」状態のとき
MSG_BTL_MODOKU_DAMAGE;
←
◆@DSP_ACTOR()　ｆｅｌｔ　ｐａｉｎ　ｆｒｏｍ　ｔｈｅ　ｐｏｉｓｏｎ↓
　　ａｎｄ　ｔｏｏｋ　@DSP_CNUM()　ＨＰ　ｄａｍａｇｅ．
;jpn:　@DSP_OBJECT()は↓
;jpn:　どくで　@DSP_CNUM()のダメージ！
@KEY()
@!

;「日射病」のとき
MSG_BTL_NISSHA_DAMAGE;
←
◆@DSP_ACTOR()　ｆｅｌｔ　ｄｉｚｚｙ　ａｎｄ　ｗｅａｋ↓
　　ａｎｄ　ｒｅｃｅｉｖｅｄ　@DSP_CNUM()　ＨＰ　ｄａｍａｇｅ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　にっしゃびょうで　@DSP_CNUM()のダメージ！
@KEY()
@!

;「かぜ」のとき
MSG_BTL_KAZE_DAMAGE;
←
◆@DSP_ACTOR()　ｓｎｅｅｚｅｄ↓
　　ａｎｄ　ｒｅｃｅｉｖｅｄ　@DSP_CNUM()　ＨＰ　ｄａｍａｇｅ！
;jpn:　@DSP_OBJECT()は↓
;jpn:　かぜで　@DSP_CNUM()のダメージ！
@KEY()
@!


