;
;
;
;
;1 2 3 4 5 6 7 8 91011121314151617
;1 2 3 4 5 6 7 8 910111213141516171819202122
;------------------------------------------------------------------------
;		バトル用メッセージスクリプト（行動時）

;##### 先頭開始時のモンスター特殊状態お知らせメッセージ #####
;	1: サイコシールド状態に
;	2: サイパワーシールド状態に
;	3: シールド状態に
;	4: パワーシールド状態に
;	5: ねむり状態に
;	6: 封印状態に
;	7: へん状態に

MSG_BTL_AT_START_NEMURI; *for_force_param=5
@GOTO(MSG_BTL_NEMURI_STAT)

MSG_BTL_AT_START_FUUIN; *for_force_param=6
;くれさんの要望により、変更。0713
;←
;　@DSP_OBJECT()は↓
;　コンセントレーションできなくなっている！
;@KEY()
@!

MSG_BTL_AT_START_HEN; *for_force_param=7
←
◆@DSP_OBJECT()　ｉｓ　ａｃｔｉｎｇ↓
　　ａ　ｌｉｔｔｌｅ　ｂｉｔ　ｓｔｒａｎｇｅ．
;jpn:　@DSP_OBJECT()は↓
;jpn:　すこし　ヘンになっている‥‥。
@KEY()
@!

;##### ランダムターゲット選択時のお知らせメッセージ #####
MSG_BTL_RND_ACT_HEN;
←
◆@DSP_ACTOR()　ｉｓ　ａｃｔｉｎｇ↓
　　ａ　ｂｉｔ　ｕｎｕｓｕａｌ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　すこし　ヘンになっている‥‥。
@KEY()
@!

MSG_BTL_RND_ACT_KINOKO;
←
◆@DSP_ACTOR()　ｉｓ↓
　　ｆｅｅｌｉｎｇ　ｆｕｎｋｙ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　ふしぎな　きもちになっている‥‥。
@KEY()
@!


;///////////////////////////直接攻撃/////////////////////////////////////

;#打撃系攻撃
MSG_BTL_TATAKU;
←
@FUNC(8)	; 行動者サイドを返す。0ならばプレーヤー側
@FALSE_GOTO(_TATAKU_PLAYER_SIDE)

;#モンスター側攻撃
@SE(SE_se19_b_foe_hitsign)
◆@DSP_ACTOR()　ｉｓ　ａｔｔａｃｋｉｎｇ！
;jpn:　@DSP_ACTOR()のこうげき！
@SE(SE_se1a_b_my_hit)
@KEY()
;@WI(1)
@!

;#プレーヤー側打撃系攻撃
_TATAKU_PLAYER_SIDE;
@SE(SE_se18_b_my_hitsign)
◆@DSP_ACTOR()　ａｔｔａｃｋｓ！
;jpn:　@DSP_ACTOR()のこうげき！
@SE(SE_se1a_b_my_hit)
@KEY()
;@WI(1)
@!

;#プレーヤー側銃系攻撃
MSG_BTL_UTU;
←
@SE(SE_se18_b_my_hitsign)
◆@DSP_ACTOR()　ａｔｔａｃｋｓ！
;jpn:　@DSP_ACTOR()のこうげき！
@SE(SE_se1b_b_my_shot)
@KEY()
;@WI(1)
@!

;#「ガード」
MSG_BTL_MAMORU;
←
◆@DSP_ACTOR()　ｉｓ　ｏｎ　ｇｕａｒｄ．
;jpn:　@DSP_ACTOR()は↓
;jpn:　ガードしている@KEY()
@!


MSG_BTL_METAMORPHOSE;●(akm0616 w/itoi)
←
◆@DSP_ACTOR()　ｒｅｌａｘｅｄ↓
　　ａｎｄ　ｔｏｏｋ　ａ　ｄｅｅｐ　ｂｒｅａｔｈ．
;jpn:　@DSP_ACTOR()は　ぜんしんの　ちからをぬき↓
;jpn:　すべてのいきを　はきだした！
@KEY()
@!

MSG_BTL_PLAYER_FLEE;●(akm0616 w/itoi)
←
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｔｒｉｅｄ　ｔｏ　ｇｅｔ　ａｗａｙ，
;jpn:　@DSP_LCNAME()は↓
;jpn:　にげだした！
@WI(60)
@KEY()↓
◆ａｎｄ　ｄｉｄ！
;jpn:　うまくいった！
@KEY()
@!

MSG_BTL_PLAYER_FLEE_NG;●(akm0616 w/itoi)
←
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｔｒｉｅｄ　ｔｏ　ｇｅｔ　ａｗａｙ，
;jpn:　@DSP_LCNAME()は↓
;jpn:　にげだした！
@WI(60)
@KEY()↓
◆ｂｕｔ　ｃｏｕｌｄｎ’ｔ！
;jpn:　しっぱいした！
@KEY()
@!

;//////////////////////////////ＰＳＩ系////////////////////////////////

;#モンスターの能力チェック
MSG_BTL_CHECK;
←
◆@DSP_ACTOR()　ｓｐｉｅｓ　ｏｎ　↓
　　@DSP_OBJECT()！
;jpn:　@DSP_ACTOR()は↓
;jpn:　@DSP_OBJECT()を　チェックした！
@KEY()
@!

;#ＰＳＩを試みる
MSG_BTL_PSI;
←
;;
;; yamazaki sample
;;
@FUNC(8)	; 行動者サイドを返す。0ならばプレーヤー側
@FALSE_GOTO(_PSI_PLAYER_SIDE)
;; モンスターサイド SE
@SE(SE_se37_b_pk_fire4)
◆@DSP_ACTOR()　ｔｒｉｅｄ↓
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
;jpn:　@DSP_PSI(0)をこころみた！
　　@DSP_PSI(0)！
@KEY()
@GOTO(_SIDE_QUIT)
;
_PSI_PLAYER_SIDE
;; プレーヤーサイド SE
@SE(SE_se1d_b_my_psi)
◆@DSP_ACTOR()　ｔｒｉｅｄ↓
;jpn:◆@DSP_ACTOR()は↓
@GET_CITEM()
@XCHG()
　　@DSP_PSI(0)！
;jpn:　@DSP_PSI(0)をこころみた！
@KEY()
;
_SIDE_QUIT
;;;
@XCHG()
@ONGOSUB(_PBFX_1,_PBFX_2,_PBFX_3,_PBFX_4,_PBFX_5,_PBFX_6,_PBFX_7,_PBFX_8,_PBFX_9,_PBFX_10,_PBFX_11,_PBFX_12,_PBFX_13,_PBFX_14,_PBFX_15,_PBFX_16,_PBFX_17,_PBFX_18,_PBFX_19,_PBFX_20,_PBFX_21,_PBFX_22,_PBFX_23,_PBFX_24,_PBFX_25,_PBFX_26,_PBFX_27,_PBFX_28,_PBFX_29,_PBFX_30,_PBFX_31,_PBFX_32,_PBFX_33,_PBFX_34,_PBFX_35,_PBFX_36,_PBFX_37,_PBFX_38,_PBFX_39,_PBFX_40,_PBFX_41,_PBFX_42,_PBFX_43,_PBFX_44,_PBFX_45,_PBFX_46,_PBFX_47,_PBFX_48,_PBFX_49,_PBFX_50)
@!

;------- (akimiura) -------
;◆ＰＫひっさつα
_PBFX_1;
@BTLFX(BFX_NULL,BFX_PSI_HISSATSU_ALFA)
@WI(10)
@SE(SE_se30_b_pk_miso1)
@WI(32)
@SE(SE_se4a_foe_explosion)
@WI(2)
@SE(SE_se30_b_pk_miso1)
@BTLFX(BFX_PSI_HISSATSU_M,BFX_NULL)
@WI(32)
@SE(SE_se4a_foe_explosion)
@WI(14)
@SE(SE_se5b)
@!

;◆ＰＫひっさつβ
_PBFX_2;
@SE(SE_se30_b_pk_miso1)
@BTLFX(BFX_NULL,BFX_PSI_HISSATSU_BETA)
@WI(32)
@SE(SE_se4a_foe_explosion)
@WI(2)
@SE(SE_se30_b_pk_miso1)
@WI(29)
@SE(SE_se4a_foe_explosion)
@WI(2)
@SE(SE_se31_b_pk_miso2)
@BTLFX(BFX_PSI_HISSATSU_M,BFX_NULL)
@WI(29)
@SE(SE_se31_b_pk_miso2)
@WI(25)
@SE(SE_se5b)
@!

;◆ＰＫひっさつγ
_PBFX_3;
@BTLFX(BFX_NULL,BFX_PSI_HISSATSU_GAMMA)
@WI(5)
@SE(SE_se31_b_pk_miso2)
@WI(32)
@SE(SE_se32_b_pk_miso3)
@WI(26)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(7)
@BTLFX(BFX_PSI_HISSATSU_M,BFX_NULL)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(7)
@SE(SE_se47_b_spray)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(5)
@SE(SE_se5b)
@!

;◆ＰＫひっさつΩ
_PBFX_4;
@BTLFX(BFX_NULL,BFX_PSI_HISSATSU_OMEGA)
@WI(30)
@SE(SE_se31_b_pk_miso2)
@WI(34)
@SE(SE_se31_b_pk_miso2)
@WI(34)
@SE(SE_se31_b_pk_miso2)
@WI(34)

@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)

@SE(SE_se5b)
@WI(11)
@SE(SE_se5b)
@WI(11)
@SE(SE_se5b)
@WI(11)

@BTLFX(BFX_PSI_HISSATSU_M,BFX_NULL)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@WI(3)
@SE(SE_se5b)
@!

;◆ＰＫファイアα
_PBFX_5;
@SE(SE_se33_b_pk_miso4)
@BTLFX(BFX_NULL,BFX_PSI_FIRE_ALFA)
@WI(28)
@SE(SE_se35_b_pk_fire2)
@WI(6)
@BTLFX(BFX_PSI_FIRE_M,BFX_NULL)
@WI(30)
@!

;◆ＰＫファイアβ
_PBFX_6;
@SE(SE_se33_b_pk_miso4)
@BTLFX(BFX_NULL,BFX_PSI_FIRE_BETA)
@WI(28)
@SE(SE_se35_b_pk_fire2)
@WI(24)
@SE(SE_se34_b_pk_fire1)
@BTLFX(BFX_PSI_FIRE_M,BFX_NULL)
@WI(30)
@!

;◆ＰＫファイアγ
_PBFX_7;
@SE(SE_se33_b_pk_miso4)
@BTLFX(BFX_NULL,BFX_PSI_FIRE_GAMMA)
@WI(28)
@SE(SE_se35_b_pk_fire2)
@WI(24)
@SE(SE_se34_b_pk_fire1)
@BTLFX(BFX_PSI_FIRE_M,BFX_NULL)
@WI(35)
@!

;◆ＰＫファイアΩ
_PBFX_8;
@SE(SE_se33_b_pk_miso4)
@BTLFX(BFX_NULL,BFX_PSI_FIRE_OMEGA)
@WI(28)
@SE(SE_se35_b_pk_fire2)
@WI(29)
@SE(SE_se35_b_pk_fire2)

@WI(24)
@SE(SE_se35_b_pk_fire2)
@BTLFX(BFX_PSI_FIRE_M,BFX_NULL)
@WI(55)
@!

;◆ＰＫフリーズα
_PBFX_9;
@SE(SE_se38_b_pk_freeze1)
@BTLFX(BFX_NULL,BFX_PSI_FREEZE_ALFA)
@WI(30)
@SE(SE_se39_b_pk_freeze2)
@WI(20)
@BTLFX(BFX_PSI_FREEZE_M,BFX_NULL)
@WI(15)
;@SE(SE_se)
@WI(27)
@!

;◆ＰＫフリーズβ
_PBFX_10;
@SE(SE_se38_b_pk_freeze1)
@BTLFX(BFX_NULL,BFX_PSI_FREEZE_BETA)
@WI(34)
@SE(SE_se39_b_pk_freeze2)
@WI(20)
@BTLFX(BFX_PSI_FREEZE_M,BFX_NULL)
@WI(15)
;@SE(SE_se)
@WI(27)
@!

;◆ＰＫフリーズγ
_PBFX_11;
@SE(SE_se38_b_pk_freeze1)
@BTLFX(BFX_NULL,BFX_PSI_FREEZE_GAMMA)
@WI(38)
@SE(SE_se39_b_pk_freeze2)
@WI(11)
@BTLFX(BFX_PSI_FREEZE_M,BFX_NULL)
@WI(27)
@SE(SE_se3a_b_pk_freeze3)
@WI(42)
@!

;◆ＰＫフリーズΩ
_PBFX_12;
@SE(SE_se38_b_pk_freeze1)
@BTLFX(BFX_NULL,BFX_PSI_FREEZE_OMEGA)
@WI(54)
@SE(SE_se39_b_pk_freeze2)
@WI(5)
@BTLFX(BFX_PSI_FREEZE_M,BFX_NULL)
@WI(31)
@SE(SE_se3a_b_pk_freeze3)
@WI(27)
@SE(SE_se3a_b_pk_freeze3)
@WI(20)
@!

;◆ＰＫサンダーα
_PBFX_13;
;◆ＰＫサンダーβ
_PBFX_14;
;◆ＰＫサンダーγ
_PBFX_15;
;◆ＰＫサンダーΩ
_PBFX_16;
@!

;ＰＫサンダー用の小さい稲妻
MSG_BTL_THUNDER_SMALL;
@SE(SE_se3d_b_pk_thunder2)
@BTLFX(BFX_PSI_THUNDER_M,BFX_PSI_THUNDER_SMALL)
@WI(22)
@SE(SE_se3f_b_pk_thunder4)
@WI(30)
@!

;ＰＫサンダー用の大きい稲妻
MSG_BTL_THUNDER_LARGE;
@SE(SE_se3e_b_pk_thunder3)
@BTLFX(BFX_PSI_THUNDER_M,BFX_PSI_THUNDER_LARGE)
@WI(22)
@SE(SE_se3f_b_pk_thunder4)
@WI(23)
@SE(SE_se3f_b_pk_thunder4)
@WI(30)
@!

;ＰＫサンダー用のハズレ稲妻
MSG_BTL_THUNDER_MISS_SE;
@SE(SE_se3c_b_pk_thunder1)
@WI(60)
@!

;◆ＰＫフラッシュα
_PBFX_17;
@SE(SE_se41_b_pk_starstorm2)
@BTLFX(BFX_PSI_FLASH_M,BFX_PSI_FLASH_ALFA)
@WI(30)
@!

;◆ＰＫフラッシュβ
_PBFX_18;
@SE(SE_se41_b_pk_starstorm2)
@BTLFX(BFX_PSI_FLASH_M,BFX_PSI_FLASH_BETA)
@WI(30)
@!

;◆ＰＫフラッシュγ
_PBFX_19;
@SE(SE_se43_b_pk_starstorm4)
@WI(10)
@BTLFX(BFX_NULL,BFX_PSI_FLASH_GAMMA)
@WI(20)
@BTLFX(BFX_PSI_FLASH_M,BFX_NULL)
@WI(19)
@SE(SE_se42_b_pk_starstorm3)
@WI(26)
@!

;◆ＰＫフラッシュΩ
_PBFX_20;
@SE(SE_se43_b_pk_starstorm4)
@BTLFX(BFX_NULL,BFX_PSI_FLASH_OMEGA)
@WI(17)
@BTLFX(BFX_PSI_FLASH_M,BFX_NULL)
@WI(50)
@SE(SE_se42_b_pk_starstorm3)
@WI(5)
@SE(SE_se42_b_pk_starstorm3)
@WI(14)
@!

;◆ＰＫスターストームα
_PBFX_21;
@BTLFX(BFX_NULL,BFX_PSI_STARSTORM_ALFA)
@WI(10)
@SE(SE_se40_b_pk_starstorm1)
@WI(50)
@BTLFX(BFX_PSI_STARSTORM_M,BFX_NULL)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(15)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@WI(7)
@SE(SE_se5b)
@!

;◆ＰＫスターストームΩ
_PBFX_22;
@BTLFX(BFX_NULL,BFX_PSI_STARSTORM_OMEGA)
@WI(20)
@SE(SE_se40_b_pk_starstorm1)
@WI(40)
@BTLFX(BFX_PSI_STARSTORM_M,BFX_NULL)
@WI(24)
@SE(SE_se40_b_pk_starstorm1)
@SE(SE_se5b)
@WI(19)
@SE(SE_se5b)
@WI(15)
@SE(SE_se5b)
@WI(15)
@SE(SE_se5b)
@WI(11)
@SE(SE_se5b)
@WI(4)
@SE(SE_se5b)
@!

;◆ライフアップα
_PBFX_23;
;◆ライフアップβ
_PBFX_24;
;◆ライフアップγ
_PBFX_25;
;◆ライフアップΩ
_PBFX_26;
;◆ヒーリングα
_PBFX_27;
;◆ヒーリングβ
_PBFX_28;
;◆ヒーリングγ
_PBFX_29;
;◆ヒーリングΩ
_PBFX_30;
;◆オフェンスアップα
_PBFX_39;
;◆オフェンスアップβ
_PBFX_40;
@WI(30)
@!

;◆シールドα
_PBFX_31;
@SE(SE_se26_b_shield)
@BTLFX(BFX_PSI_SHIELD,BFX_NULL)
@WI(1)
@!

;◆シールドΣ
_PBFX_32;
@SE(SE_se26_b_shield)
@BTLFX(BFX_PSI_SHIELD,BFX_NULL)
@WI(1)
@!

;◆シールドβ
_PBFX_33;
@SE(SE_se26_b_shield)
@BTLFX(BFX_PSI_POWER_SHIELD,BFX_NULL)
@WI(1)
@!

;◆シールドΩ
_PBFX_34;
@SE(SE_se26_b_shield)
@BTLFX(BFX_PSI_POWER_SHIELD,BFX_NULL)
@WI(1)
@!

;◆サイコシールドα
_PBFX_35;
@SE(SE_se27_b_psychoshield)
@BTLFX(BFX_PSI_P_SHIELD,BFX_NULL)
@WI(1)
@!

;◆サイコシールドΣ
_PBFX_36;
@SE(SE_se27_b_psychoshield)
@BTLFX(BFX_PSI_P_SHIELD,BFX_NULL)
@WI(1)
@!

;◆サイコシールドβ
_PBFX_37;
@SE(SE_se27_b_psychoshield)
@BTLFX(BFX_PSI_P_POWER_SHIELD,BFX_NULL)
@WI(1)
@!

;◆サイコシールドΩ
_PBFX_38;
@SE(SE_se27_b_psychoshield)
@BTLFX(BFX_PSI_P_POWER_SHIELD,BFX_NULL)
@WI(1)
@!

;◆ディフェンスダウンα
_PBFX_41;
@SE(SE_se2c_b_pararaisis)
;@SE(SE_se29_b_defense_down)
@BTLFX(BFX_NULL,BFX_PSI_DEFENSE_DOWN_ALFA)
@WI(40)
@BTLFX(BFX_PSI_DEFENSE_DOWN_M,BFX_NULL)
@WI(100)
@!

;◆ディフェンスダウンβ
_PBFX_42;
@SE(SE_se4f_foe_needle)
;@SE(SE_se29_b_defense_down)
@BTLFX(BFX_NULL,BFX_PSI_DEFENSE_DOWN_OMEGA)
@WI(40)
@BTLFX(BFX_PSI_DEFENSE_DOWN_M,BFX_NULL)
@WI(125)
@!

;◆さいみんじゅつα
_PBFX_43;
@SE(SE_se2a_b_hypnosis)
@BTLFX(BFX_NULL,BFX_PSI_SAIMIN_ALFA)
@WI(25)
@BTLFX(BFX_SHAKE_LONG_SIDE,BFX_NULL)
@WI(30)
@!

;◆さいみんじゅつβ
_PBFX_44;
@SE(SE_se2a_b_hypnosis)
@BTLFX(BFX_NULL,BFX_PSI_SAIMIN_OMEGA)
@WI(55)
@BTLFX(BFX_SHAKE_LONG_SIDE,BFX_NULL)
@WI(30)
@!

;◆サイマグネットα
_PBFX_45;
@SE(SE_se2b_b_psymagnet)
@BTLFX(BFX_NULL,BFX_PSI_P_MAGNET_ALFA)
@WI(45)
@BTLFX(BFX_PSI_P_MAGNET_M,BFX_NULL)
@WI(57)
@!

;◆サイマグネットβ
_PBFX_46;
@SE(SE_se4c_foe_lock_light)
@BTLFX(BFX_NULL,BFX_PSI_P_MAGNET_OMEGA)
@WI(45)
@BTLFX(BFX_PSI_P_MAGNET_M,BFX_NULL)
@WI(33)
@!

;◆パラライシスα
_PBFX_47;
@SE(SE_se2c_b_pararaisis)
@BTLFX(BFX_NULL,BFX_PSI_PARALYSIS_ALFA)
@WI(60)
@BTLFX(BFX_PSI_PARALYSIS_M,BFX_NULL)
@WI(70)
@!

;◆パラライシスβ
_PBFX_48;
@SE(SE_se4f_foe_needle)
@BTLFX(BFX_NULL,BFX_PSI_PARALYSIS_OMEGA)
@WI(60)
@BTLFX(BFX_PSI_PARALYSIS_M,BFX_NULL)
@WI(70)
@!

;◆ブレインショックα
_PBFX_49;
@WI(20)
@SE(SE_se2d_b_brainshock)
@BTLFX(BFX_NULL,BFX_PSI_BRAIN_SHOCK_ALFA)
@WI(20)
@BTLFX(BFX_SHAKE_LONG_SIDE,BFX_NULL)
@WI(76)
@!

;◆ブレインショックβ
_PBFX_50;
@WI(20)
@SE(SE_se50_foe_kiss)
@BTLFX(BFX_NULL,BFX_PSI_BRAIN_SHOCK_OMEGA)
@WI(40)
@BTLFX(BFX_SHAKE_LONG_SIDE,BFX_NULL)
@WI(128)
@!
;------- ここまで -------

;#「いのる」
MSG_BTL_INORU;
←
@SE(SE_se1c_b_my_pray)
◆@DSP_ACTOR()　ｐｒａｙｅｄ↓
　　ｗｉｔｈ　ｈｅｒ　ｗｈｏｌｅ　ｈｅａｒｔ！
;jpn:　@DSP_ACTOR()は↓
;jpn:　こころをこめて　いのった！
@KEY()
@!

