;/////////////////////////バトル用ローカルサブルーチン/////////////////////
;#「それぞれ」の表示
_SUB_SOREZORE;
@Q_MEMBER(2)
@TRUE_GOTO(_SOREZORE_END)
@GET_ORDER_PLAYER(2)
@Q_SPECIAL(0,1,2)
@TRUE_GOTO(_SOREZORE_END)
　ｅａｃｈ
;jpn:それぞれ
_SOREZORE_END;
@!


MSG_FMON_MOON_A;
;◆いかりのプラグでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_MOON_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_MOONSIDE_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_MOON_A_DISAPPEAR)
@WI(1)
;@REMOVE_CHAR(PRSN_MNSD_HOTEL_1_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_MOON_B;
;◆ロボ・ガロンです。
;@KEYNP()
@CHKFGOTO(FLG_FMON_MOON_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_MOONSIDE_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_MOON_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MNSD_BORGES_E,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_MOON_B_2;
;◆ロボ・ガロンです。
;@KEYNP()
@CHKFGOTO(FLG_FMON_MOON_B_2_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_MOONSIDE_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_MOON_B_2_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MNSD_MUSEUM_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_MOON_C;
;◆なぞのゲージュツです。
;@KEYNP()
@CHKFGOTO(FLG_FMON_MOON_C_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_MOONSIDE_C)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_MOON_C_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MNSD_HOSP_FRONT_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_A;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_1_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_B;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_2_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_C;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_C_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_C_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_3_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_D;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_D_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_D_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_4_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_E;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_E_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_E_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_5_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_F;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_F_DISAPPEAR,MSG_SYS_HANASU_NG)
;@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_F_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_5_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_G;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_G_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_G_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_6_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_H;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_H_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_H_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_8_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_I;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_I_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_I_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_9_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_J;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_J_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_J_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_B_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_K;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_K_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_K_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_C_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_L;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_L_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_L_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_D_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_M;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_M_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_M_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_E_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_N;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_N_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_N_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_F_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_O;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_O_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_O_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_G_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_P;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_P_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_P_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_G_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_A_Q;
;◆のろいのえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_A_Q_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_A_Q_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_G_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_A;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_4_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_B;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_4_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_C;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_C_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_C_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_6_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_D;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_D_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_D_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_8_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_E;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_E_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_E_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_A_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_F;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_F_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_F_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_D_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_G;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_G_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_G_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_F_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_H;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_H_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_H_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_G_D,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_PYRA_B_I;
;◆スネークえもじでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_PYRA_B_I_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_PYRAMID_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_B_I_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_G_E,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_A_A;
;◆つっぱりダックでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_A_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_A_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_A_B;
;◆つっぱりダックでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_A_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_A)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_A_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_B_A;
;◆オレナンカドーセでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_B_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_B_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_B_B;
;◆オレナンカドーセでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_B_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_B)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_B_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_D,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_C_A;
;◆ぐれたネズミでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_C_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_C)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_C_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_E,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BRICK_C_B;
;◆ぐれたネズミでーす。
;@KEYNP()
@CHKFGOTO(FLG_FMON_BRICK_C_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BRICK_C)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_BRICK_C_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_BRICK_F,ANIM_BLINK_SUICIDE)
@!

;ストーンヘンジのボス
MSG_FMON_STONE_BOSS;
@CHKFGOTO(FLG_FMON_STONE_BOSS_DISAPPEAR,MSG_SYS_HANASU_NG)
;-----
@GOSUB(MSG_WINS_STARMAN)
;-----
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_STONEHENGE)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_STONE_BOSS_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_WINS_STONE_B_A,ANIM_BLINK_SUICIDE)
@GOSUB(MSG_READ_WINS_MACHINE);基地停止
@!

;ピラミッドのボス
MSG_FMON_PYRA_BOSS;
@CHKFGOTO(FLG_FMON_PYRA_BOSS_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_PYRAMID)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_PYRA_BOSS_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SCRB_PYRAMID_A_B,ANIM_BLINK_SUICIDE)
@!

;エデンのクラーケン
MSG_FMON_KRAKEN2_A;
@CHKFGOTO(FLG_FMON_KRAKEN2_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_SEA_ROUTE)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_KRAKEN2_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MGCT_EDEN_A,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_KRAKEN2_B;
@CHKFGOTO(FLG_FMON_KRAKEN2_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_SEA_ROUTE)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_KRAKEN2_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MGCT_EDEN_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_KRAKEN2_C;
@CHKFGOTO(FLG_FMON_KRAKEN2_C_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_SEA_ROUTE)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_KRAKEN2_C_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_MGCT_EDEN_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_HIEROGLYPH_A;
@CHKFGOTO(FLG_FMON_HIEROGLYPH_A_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_HIEROGLYPH)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_HIEROGLYPH_A_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SUMS_HIERO_EXHI2_B,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_HIEROGLYPH_B;
@CHKFGOTO(FLG_FMON_HIEROGLYPH_B_DISAPPEAR,MSG_SYS_HANASU_NG)
@CLOSEALL()
@BATTLE(MSET_FIX_HIEROGLYPH)
@TRUE_GOTO(MSG_BTL_NULL)
@SETF(FLG_FMON_HIEROGLYPH_B_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_SUMS_HIERO_EXHI2_C,ANIM_BLINK_SUICIDE)
@!

MSG_FMON_BOSS_GRAVE;
@CHKFGOTO(FLG_FMON_BOSS_GRAVE_DISAPPEAR,MSG_SYS_HANASU_NG)
;-----
@OPEN(1)
@GOSUB(MSG_THRK_BOSS_GRAVE)
;-----
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_GRAVEYARD)
@TRUE_GOTO(MSG_BTL_NULL)
;-----
@GOSUB(MSG_THRK_BOSS_GRAVE_DIE)
;-----
@SETF(FLG_FMON_BOSS_GRAVE_DISAPPEAR)
@WI(1)
@REMOVE_CHAR(PRSN_THRK_CATA_6_A,ANIM_BLINK_SUICIDE)
@!

