;////////////////////////////////その他///////////////////////////////////

MSG_BTL_NAKAMA_KITA;
←
◆@DSP_OBJECT()　ｊｏｉｎｅｄ↓
　　ｔｈｅ　ｂａｔｔｌｅ．
;jpn:　@DSP_OBJECT()が↓
;jpn:　たたかいに　さんかした！
@KEY()
@!

MSG_BTL_TANEMAKI_HAETA;
←
◆@DSP_OBJECT()　ｓｔａｒｔｅｄ↓
　　ｔｏ　ｇｒｏｗ．
;jpn:　@DSP_OBJECT()が↓
;jpn:　はえてきた！
@KEY()
@!

MSG_BTL_NAKAMA_NO;
←
◆Ｂｕｔ　ｎｏ　ｏｎｅ　ｃａｍｅ．
;jpn:　しかし↓
;jpn:　だれも　きてくれなかった。
@KEY()
@!

MSG_BTL_TANEMAKI_NO;
←
◆Ｂｕｔ，　ｔｈｅ　ｓｅｅｄ　ｄｉｄｎ’ｔ　ｓｐｒｏｕｔ．
;jpn:　しかし↓
;jpn:　めは　でなかった。
@KEY()
@!

MSG_BTL_TIMESTOP_RET;
@BGMSTART(0,BGM_hen3)
←
◆Ｔｉｍｅ　ｓｔａｒｔｅｄ　ａｇａｉｎ．
;jpn:　じかんは↓
;jpn:　ふたたび　うごきはじめた！
@KEY()
@!
;		バトル用メッセージスクリプト（バトル終了時）

;//////////////////////////バトル開始////////////////////////////////////

;#モンスター出現
MSG_BTL_AP_OSOWARETA;＠
MSG_BTL_APPEAR;
←
◆@GOSUB(_SUB_GACTOR_1)　ａｔｔａｃｋｅｄ！
;jpn:　@DSP_ACTOR()に↓
;jpn:　おそわれた！
@KEY()
@!

MSG_BTL_AP_FUSAGARETA;＠
←
◆@GOSUB(_SUB_GACTOR_1)　ｂｌｏｃｋｅｄ　ｔｈｅ　ｗａｙ！
;jpn:　@DSP_ACTOR()に↓
;jpn:　ゆくてを　ふさがれた！
@KEY()
@!

MSG_BTL_AP_ATTESHIMATTA;＠
←
◆@GOSUB(_SUB_GACTOR_1)　ｃａｍｅ↓
　　ａｆｔｅｒ　ｙｏｕ！
;jpn:　@DSP_ACTOR()に↓
;jpn:　あってしまった！
@KEY()
@!

MSG_BTL_AP_TSUKAMATTA;＠
←
◆@GOSUB(_SUB_GACTOR_1)
　　ｔｒａｐｐｅｄ　ｙｏｕ！
;jpn:　@DSP_ACTOR()に↓
;jpn:　つかまった！
@KEY()
@!

;#先制攻撃（プレーヤー側）
MSG_BTL_SENSEI_PC;
←
◆Ｈｅｒｅ　ｉｓ　ａ　ｃｈａｎｃｅ↓
　　ｆｏｒ　ａ　ｓｕｒｐｒｉｓｅ　ｏｐｅｎｉｎｇ　ａｔｔａｃｋ！
;jpn:　せんせいこうげきの　チャンスだ！
@KEY()
@!

;#先制攻撃（モンスター側）
MSG_BTL_SENSEI_MON;
←
◆Ｈｅｒｅ　ｉｓ　@GOSUB(_SUB_GACTOR_1)’ｓ　ｓｕｒｐｒｉｓｅ　ｏｐｅｎｉｎｇ　ａｔｔａｃｋ！
;jpn:　@DSP_ACTOR()の↓
;jpn:　せんせいこうげき！
@KEY()
@!

_SUB_GACTOR_1;
@GET_ACTOR(2)
@ONGOTO(_GACTOR_11,_GACTOR_12,_GACTOR_13)
@DSP_ACTOR()　ａｎｄ　ｉｔ’ｓ　ｃｏｈｏｒｔｓ
@!
_GACTOR_11;
@DSP_ACTOR()
@!
_GACTOR_12;
@DSP_ACTOR()　ａｎｄ　ｉｔ’ｓ　ｃｏｈｏｒｔ
@!
_GACTOR_13;
@DSP_ACTOR()　ａｎｄ　ｉｔ’ｓ　ｃｏｈｏｒｔｓ
@!

;///////////////////////////バトル終了///////////////////////////////////

;#プレーヤー側勝利
MSG_BTL_PLAYER_WIN;
@CLS()
@BGMSTART(0,BGM_fanfare)
↓
　　　　　　　　　　　　@KMOJI(2)
@WI(120)
_BTL_PLAYER_WIN_2;
@FUNC(17)
@TRUE_GOTO(_BTL_PLAYER_WIN_HOMESICK)
_BTL_PLAYER_WIN_3;
@KEY()↓
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｇａｉｎｅｄ　@DSP_CNUM()　ｅｘｐ
@GOSUB(_SUB_SOREZORE)．
;jpn:　@DSP_LCNAME()は@GOSUB(_SUB_SOREZORE)↓
;jpn:　@DSP_CNUM()の　けいけんちをえた。
@FKEY()
@!
_BTL_PLAYER_WIN_HOMESICK;
@SET_SPECIAL(PC_NESS,6,2)
@GOTO(_BTL_PLAYER_WIN_3)


;#中ボス勝利
MSG_BTL_PLAYER_WIN_BOSS;
@CLS()
@BGMSTART(0,BGM_mm06)
↓
　　　　　　　　　　　　@KMOJI(2)
@WI(120)
@GOTO(_BTL_PLAYER_WIN_2)

;#無条件勝利
MSG_BTL_PLAYER_WIN_FORCE;
@CLS()
↓
　　　　　　　　　　　　@KMOJI(2)
@WI(90)
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｇａｉｎｅｄ　@DSP_CNUM()　ｅｘｐ．
;jpn:　@DSP_LCNAME()は@GOSUB(_SUB_SOREZORE)↓
;jpn:　@DSP_CNUM()の　けいけんちをえた。
@FKEY()
@!

;#モンスター側勝利（プレーヤー全滅）
MSG_BTL_MONSTER_WIN;
←
@WI(10)
@BGMSTART(0,BGM_deth)
◆@GOSUB(MSG_ESUB_DSP_PARTY)　ｌｏｓｔ　ｔｈｅ　ｂａｔｔｌｅ．．．．@FKEY()
;　@DSP_LCNAME()は↓
;jpn:　たたかいに　やぶれた‥‥@FKEY()
@!


MSG_BTL_LEVEL_UP;●(akm0616 w/itoi)
←
◆@DSP_OBJECT()’ｓ　ｌｅｖｅｌ　ｉｓ↓
　　ｎｏｗ　@DSP_CNUM()！
;jpn:　@DSP_OBJECT()の　レベルが　@DSP_CNUM()になった！
@FKEY()
@!

MSG_BTL_LV_OFFENSE_UP;
←
;オフェンスが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｏｆｆｅｎｓｅ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　オフェンスが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_DEFENSE_UP;
←
;ディフェンスが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｄｅｆｅｎｓｅ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　ディフェンスが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_SPEED_UP;
←
;スピードが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｓｐｅｅｄ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　スピードが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_GUTS_UP;
←
;ガッツが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｇｕｔｓ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　ガッツが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_VITA_UP;
←
;バイタリティが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｖｉｔａｌｉｔｙ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　バイタリティが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_IQ_UP;
←
;ＩＱが上がっていれば
◆@GOSUB(_SUB_NANTO3)
ＩＱ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　ＩＱが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_LUCK_UP;
←
;ラックが上がっていれば
◆@GOSUB(_SUB_NANTO3)
Ｌｕｃｋ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　ラックが　
;@GOSUB(_SUB_NANTO3)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_MAXHP_UP;
←
◆@GOSUB(_SUB_NANTO1)
Ｍａｘｉｍｕｍ　ＨＰ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　さいだいＨＰが　
;@GOSUB(_SUB_NANTO1)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LV_MAXPP_UP;
←
◆@GOSUB(_SUB_NANTO2)
Ｍａｘｉｍｕｍ　ＰＰ　ｗｅｎｔ　ｕｐ　ｂｙ　@DSP_CNUM()！
;;jpn:　さいだいＰＰが　
;@GOSUB(_SUB_NANTO2)
;@DSP_CNUM()　ＵＰ！
@FKEY()
@!

MSG_BTL_LEARN_PSI;
←
;PSIを覚えれば
@SE(SE_se67_elevator_stop)
;◆@DSP_PSI(0)　ｗａｓ　ｌｅａｒｎｅｄ↓
;　　ｄｕｒｉｎｇ　ｔｈｅ　ｂａｔｔｌｅ！
◆@DSP_OBJECT()　ｒｅａｌｉｚｅｄ　ｔｈｅ　ｐｏｗｅｒ　ｏｆ↓
@GET_CITEM()
@XCHG()
　　@DSP_PSI(0)．
;jpn:　そして　たたかいのなかで↓
;jpn:　@DSP_PSI(0)を　おぼえた！
@FKEY()
@!

_SUB_NANTO1;
@SAVE_REG()
@GET_CNUM()
@CMP(20,0)
@FALSE_GOTO(_NANTO1_END)
;at a stretch
Ｓｗｅｅｔ！↓　　
;*akimiura
;jpn:いっきに
_NANTO1_END;
@LOAD_REG()
@!

_SUB_NANTO2;
@SAVE_REG()
@GET_CNUM()
@CMP(8,0)
@FALSE_GOTO(_NANTO2_END)
;at a stretch
Ｔｈａｔ　ｒｏｃｋｓ！↓　　
;*akimiura
;jpn:いっきに
_NANTO2_END;
@LOAD_REG()
@!

_SUB_NANTO3;
@SAVE_REG()
@GET_CNUM()
@CMP(3,0)
@FALSE_GOTO(_NANTO3_END)
Ｂａｂｙ！↓　　
;*akimiura
;（＊－ｃａｎｎｏｔｔｒａｎｓｌａｔｅ．ｔｏｏ　ｓｈｏｒｔ：ｙｕｋａ）
;jpn:なんと
_NANTO3_END;
@LOAD_REG()
@!


;#プレゼントボックス入手
MSG_BTL_PRESENT;
←
◆Ｔｈｅ　ｅｎｅｍｙ　ｌｅｆｔ　ａ　ｐｒｅｓｅｎｔ！
;jpn:　てきは↓
;jpn:　プレゼントのはこを　おいていった！
@FKEY()↓
@SE(SE_se10_present_open)
@WI(1)
◆Ｉｎｓｉｄｅ　ｔｈｅ　ｐｒｅｓｅｎｔ，↓
;jpn:　プレゼントのなかみは↓
@GET_CITEM()
@XCHG()
　　ｔｈｅｒｅ　ｗａｓ　ａ　@DSP_GOODS(0)！
;jpn:　@DSP_GOODS(0)だった！
@FKEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_BTL_PRESENT_FULL)
@SAVE_REG()
@GOSUB(MSG_SUB_Q_DEAD_GOODS)
@TRUE_GOTO(_BTL_PRESENT_DEAD)
@LOAD_REG()
@XCHG()

◆@DSP_NAME(0)
;jpn:@DSP_NAME(0)は↓
@XCHG()
　ｔｏｏｋ　ｉｔ．
;　　ｔｈｅ　@DSP_GOODS(0)！
;jpn:@DSP_GOODS(0)を　てにいれた！
@GOODSIN_PLAYER(0,0)
@SE(SE_se74_my_get)
@FKEY()
@!

_BTL_PRESENT_DEAD;レジスタ用法不明（三浦）<-修正しました（松井）
@GET_ORDER_PLAYER(1)
@XCHG()
←
◆@DSP_NAME(0)　ａｄｄｅｄ
@LOAD_REG()
　ｔｈｅ　@DSP_GOODS(0)　ｔｏ↓
　　@XCHG()@DSP_NAME(0)’ｓ　ｓｔｕｆｆ．
;;jpn:◆@DSP_NAME(0)は
;@LOAD_REG()
;@XCHG()
;;jpn:　@DSP_NAME(0)のもちものに↓
;@XCHG()
;;jpn:@DSP_GOODS(0)を　くわえた。
@XCHG()
@GOODSIN_PLAYER(0,0)
@SE(SE_se74_my_get)
@FKEY()
@!

_BTL_PRESENT_FULL;
◆Ｂｕｔ，　@GOSUB(MSG_ESUB_DSP_PARTY)　ｃａｎｎｏｔ　ｃａｒｒｙ　ａｎｙｍｏｒｅ　ｓｔｕｆｆ．
;jpn:　しかし　@DSP_LCNAME()は↓
;jpn:　これいじょう　グッズを　もてない。
@FKEY()↓

_BTL_PRESENT_FULL_B;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ？↓
<Ｙｅｓ>　　<Ｎｏ>
;jpn:　なにか　すてますか？↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_BTL_PRESENT_DROP,_BTL_PRESENT_ABANDON)

_BTL_PRESENT_ABANDON;
;jpn:　では
@FKEY()↓
@GET_CITEM()
@XCHG()
◆Ｔｈｅｎ，　ｗｉｌｌ　ｙｏｕ　ｌｅａｖｅ↓
　　ｔｈｅ　@DSP_GOODS(0)　ｂｅｈｉｎｄ？@KEY()↓
<Ｙｅｓ>
<Ｎｏ>
;jpn:　@DSP_GOODS(0)を　あきらめますか？↓
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@SELGOTO(_BTL_PRESENT_ABANDON_C,_BTL_PRESENT_ABANDON_B)

_BTL_PRESENT_ABANDON_B;
◆Ｔｈｅｎ，
;jpn:　では
@FKEY()↓
@GOTO(_BTL_PRESENT_FULL_B)

_BTL_PRESENT_ABANDON_C;
◆@GOSUB(MSG_ESUB_DSP_PARTY_SREG)　ａｂａｎｄｏｎｅｄ↓
　　ｔｈｅ　@DSP_GOODS(0)．
;jpn:　@DSP_LCNAME()は↓
;jpn:　@DSP_GOODS(0)を　あきらめた。
@FKEY()
@!

_BTL_PRESENT_DROP;
←
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｈｒｏｗ　ａｗａｙ？
;jpn:　なにを　すてますか？
@FKEY()
@GOSUB(MSG_SEL_GOODS_B)
←
@FALSE_GOTO(_BTL_PRESENT_ABANDON)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_BTL_PRESENT_DROP_NG)
@LOAD_REG)
@GET_PLAYER_GOODS(0,0)
;@Is it alright to throw away ｿDSP_GOODS(0)?↓
◆Ｓｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｈｒｏｗ　ａｗａｙ　ｔｈｅ　@DSP_GOODS(0)？@FKEY()↓
<Ｔｈｒｏｗ　ａｗａｙ>
<Ｄｏｎ’ｔ　ｄｏ　ｉｔ>
;jpn:　@DSP_GOODS(0)を　すてていいですか？↓
;jpn:<すてる>
;jpn:<すてない>
@DSP_ITEM(2)
@SELGOTO(_BTL_PRESENT_DROP_B,_BTL_PRESENT_ABANDON)
@GOTO(_BTL_PRESENT_ABANDON)

_BTL_PRESENT_DROP_B;
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@XCHG()
◆@DSP_NAME(0)
;jpn:　@DSP_NAME(0)は
@XCHG()
　ｔｈｒｅｗ　ｔｈｅ　@DSP_GOODS(0)　ａｗａｙ
;jpn:　@DSP_GOODS(0)をすて
@KEY()↓
@XCHG()
@GET_CITEM()
@XCHG()
　ａｎｄ　ｔｏｏｋ　ｔｈｅ　@DSP_GOODS(0)．
;jpn:　@DSP_GOODS(0)を　てにいれた！
@GOODSIN_PLAYER(0,0)
@SE(SE_se74_my_get)
@WI(1)
@KEY()
@!

_BTL_PRESENT_DROP_NG;
◆Ｄｏ　ｎｏｔ　ｔｈｒｏｗ　ｔｈｅ　@DSP_GOODS(0)　ａｗａｙ．
;jpn:　@DSP_GOODS(0)は　すてないでください。
@FKEY()
@GOTO(_BTL_PRESENT_DROP)

MSG_BTL_CHECK_PRESENT_GET;●(akm0616 w/itoi)
←
◆@DSP_ACTOR()　ｓａｗ↓
　　ａ　ｐｒｅｓｅｎｔ　ｂｅｈｉｎｄ　ｔｈｅ　ｅｎｅｍｙ．
;jpn:　@DSP_ACTOR()は　てきのかげに↓
;jpn:　プレゼントのはこがあるのを　みつけた！
@KEY()↓
@SE(SE_se10_present_open)
◆Ｉｎｓｉｄｅ　ｔｈｅ　ｐｒｅｓｅｎｔ，↓
;jpn:　プレゼントのなかみは↓
@GET_CITEM()
@XCHG()
　　ｔｈｅｒｅ　ｗａｓ　ａ　@DSP_GOODS(0)．
;jpn:　@DSP_GOODS(0)だった！
@KEY()↓
◆@DSP_NAME(PC_JEFF)　ｔａｋｅｓ　ｉｔ．
;jpn:@DSP_NAME(PC_JEFF)は↓
;jpn:@DSP_GOODS(0)を　てにいれた！
@GOODSIN_PLAYER(PC_JEFF,0)
@SE(SE_se74_my_get)
@KEY()
@!
