;---------------------------------------------------------------------------
;
;		ÉfÉoÉbÉOópÉÅÉbÉZÅ[ÉWÉXÉNÉäÉvÉg
;
;---------------------------------------------------------------------------

MSG_DEBUG_00;
@OPEN(1)
Å©
ÅüÇmÇmÇvÅ@ÇrÇlÇrÇjÅH
@SAVE_WIN()
@DSP_PL()
@WINR_MONEY()
@OPEN(2)
<ÇoÅ|ÇsÇâÇmÇrÇîÇsÇh>
<ÇfÇîÇyÇrÇîÇsÇh>
<ÇsÇjÇrÇôÇyÇôÇtÇsÇh>
<ÇhÇcÇt>
<ÇnÇjÇmÇmÇrÇîÇsÇh>
<ÇqÇaÇqÇ`ÇîÇo>
<ÇlÇrÇxÇtÇmÇrÇjÇqÇoÇs>
<ÇhÇaÇmÇs>
<ÇgÇmÇsÇx>
<ÇrÇtÇmÇc>
<ÇrÇsÇlÇh>
<ÇsÇqÇoÅ|Çs>
<ÇgÇmÇsÇsÇy>
@DSP_ITEML(2)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@CLRLINE()
Å©
@LOAD_GLOBAL_REG()
@ONGOTO(_DBG_MAKEPARTY,_DBG_GOODS,_DBG_SPECIAL,_DBG_WARP,_DBG_MONEY,_DBG_LEVELUP,_DBG_SCRIPT,_DBG_EVENT_START,_DBG_HINT,_DBG_SOUND,_DBG_EXPL,_DBG_TLPT,_DBG_HINTMAP)
ÅüÇxÇlÇlÇrÇsÅD@KEYNP()
@!

_DBG_HINTMAP;
Å©
ÅüÇgÇmÇsÇxÇvÅ´
Å@ÇsÇyÇmÇmÇrÇlÇr@KEY()Å´
@SETF(FLG_GM_ONET_HINT)
@SETF(FLG_GM_TWOSON_HINT)
@SETF(FLG_GM_THREEK_HINT)
@SETF(FLG_GM_FOURSIDE_HINT)
@SETF(FLG_GM_SUMMERS_HINT)
@SETF(FLG_GM_SCARABI_HINT)
@GOTO(MSG_DEBUG_00)

_DBG_MAKEPARTY;
ÅüÇmÇmÇvÅ@ÇrÇlÇrÇjÅHÅ´
<ÇjÇvÇdÇq>
<ÇgÇyÇr>
@DSP_ITEM(2)
@SELGOTO(_MKP_ADD,_MKP_DEL)
@GOTO(MSG_DEBUG_00)

_MKP_ADD;
_DBG_MP05;
@DSP_PL()
ÅüÇjÇvÇdÇqÅ@ÇoÇqÅ|ÇxÅ|ÇvÅ´
Å@ÇdÇqÇmÇcÇjÇcÇrÇhÅD
_DBG_MP10;
@OPEN(8)
<ÇmÇr>
<ÇoÅ|Çq>
<ÇyÇÖÇe>
<ÇoÅ|>
<ÇoÅ|ÇjÅ|>
<ÇoÇîÇjÅ|>
<ÇhÇm>
<ÇsÇmÅ|>
<ÇaÇqÅ|ÇmÇlÇmÇjÅ|>
<ÇcÇmÇyÇôÇmÇlÇm>
<ÇeÇqÇhÇmÇfÇlÇmÇP>
<ÇeÇqÇhÇmÇfÇlÇmÇQ>
<ÇeÇqÇhÇmÇfÇlÇmÇR>
<ÇeÇqÇhÇmÇfÇlÇmÇS>
<ÇeÇqÇhÇmÇfÇlÇmÇT>
@DSP_ITEML(3)
@SELQ()
@SAVE_GLOBAL_REG()
@RESITEM()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@FALSE_GOTO(_MAKEPARTY_END)
@XCHG()
@ADD_PARTY(0)
@DSP_PL()
@GOTO(_DBG_MP10)
_MAKEPARTY_END;
@CLOSE()
@GOTO(MSG_DEBUG_00)

_MKP_DEL;
@GET_ORDER_PLAYER(2)
@FALSE_GOTO(_MKP_DEL_UNABLE)
ÅüÇgÇyÇrÇoÇqÅ|ÇxÅ|ÇmÇhÇsÇvÅ´
Å@ÇmÇôÇtÇqÇôÇjÇrÇsÇjÇcÇrÇhÅDÅ´
_MKP_DEL10;
@GET_ORDER_PLAYER(2)
@FALSE_GOTO(_MKP_DEL_END)
Å@Å@@INPUT(1)
@FALSE_GOTO(_MKP_DEL_END)
@CLRLINE()
@XCHG()
@GET_ORDER_PLAYER(0)
@FALSE_GOTO(_MKP_DEL10)
@XCHG()
@DEL_PARTY(0)
Åü@DSP_NAME(0)ÇvÅ@ÇgÇyÇrÇlÇrÅDÅ´
@GOTO(_MKP_DEL10)
_MKP_DEL_END;
@GOTO(MSG_DEBUG_00)

_MKP_DEL_UNABLE;
ÅüÇOÇmÇmÇmÇgÇcÇjÇlÇrÇmÅD@KEYNP()
@GOTO(MSG_DEBUG_00)

_DBG_GOODS;
Å©
ÅüÇfÇîÇyÇmÇrÇîÇsÇhÇvÇrÇlÇrÅD
@SAVE_WIN()
@DSP_PL()
@WINR_MONEY()
@OPEN(7)
<ÇfÇîÇyÇjÇvÇdÇq>
<ÇyÇôÇtÇxÇtÇfÇîÇy>
<ÇfÇîÇyÇlÇmÇsÇm>
<ÇfÇîÇyÇrÇjÇyÇô>
<Ç`ÇyÇjÇqÇrÇôÇlÇmÇsÇm>
<Ç`ÇyÇjÇqÇrÇôÇjÇq>
<ÇrÇhÇjÇôÇtÇaÇj>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@RESITEM()
@SELECT_WIN(1)
Å©
@LOAD_GLOBAL_REG()
@ONGOTO(_DBG_GETGOODS,_DBG_GETGOODS_A,_DBG_GOODSFULL,_DBG_DELGOODS,_DBG_TRACYFULL,_DBG_TRACYEMP,_DBG_WEAPON)
@GOTO(MSG_DEBUG_00)

_DBG_GETGOODS;
_DBG_GG10;
ÅüÇfÇîÇyÇhÇcÇvÅ@ÇmÇôÇtÇqÇôÇjÅ´
Å@Å@Å@@INPUT(3)
@CLRLINE()
@FALSE_GOTO(_GETGOODS_END)
@XCHG()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DBG_GG100)
@SAVE_REG()
Åü@DSP_GOODS(0)ÇcÇrÅDÅ´
Å@ÇcÇqÇmÇrÇlÇrÇjÅH
@GOSUB(MSG_SEL_GOODSIN)
Å´
@FALSE_GOTO(_DBG_GG10)
@GOODSIN_PLAYER(0,0)
Å©
ÅüÇfÇîÇyÇqÇmÇmÅ@ÇjÇvÇdÇlÇrÇsÅD@KEY()Å´
@GOTO(_DBG_GG10)

_DBG_GG100;
ÅüÇlÇsÇlÇmÇhÇîÇoÇhÇcÇrÅD
_GETGOODS_END;
@GOTO(MSG_DEBUG_00)

_DBG_GETGOODS_A;
@SAVE_WIN()
@OPEN(12)
<ÇsÇaÇfÇxÇmÇjÇf>
<ÇyÇôÇrÇmÇcÇmÇv>
<ÇsÇjÇjÇrÇlÇrÇm>
<ÇeÇqÇmÇjÇqÇmÇaÇîÇy>
<ÇqÇtÇxÇmÇjÇf>
<ÇrÇsÇsÇa>
<ÇsÇôÇîÇsÇjÇfÇlÇrÇm>
<ÇyÇmÇaÇgÇhÇgÇh>
<ÇcÇhÇxÇlÇmÇc>
<ÇfÇqÇlÇcÇtÇeÇlÇrÇm>
<ÇgÇdÇqÇfÇqÇeÇmÇjÇoÅ|>
<ÇsÇjÇmÇl>
<ÇeÅ|ÇrÇmÇfÇl>
<ÇlÇjÇsÇvÇmÇnÇrÇgÇm>
<ÇaÇîÇrÇsÇwÇxÇy>
<ÇrÇhÇmÇhÇqÇaÇmÇm>
<ÇjÇjÇrÇjÇrÇlÇrÇm>
<ÇfÇlÇcÇqÇ`Çm>
<ÇtÇrÇfÇfÇmÇlÇmÇmÇyÇm>

@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@RESITEM()
@SELECT_WIN(1)
Å©
@LOAD_GLOBAL_REG()
@FALSE_GOTO(_GETGOODS_END)
@XCHG()
ÅüÇcÇqÇmÇrÇlÇrÇjÅD
@GOSUB(MSG_SEL_GOODSIN)
@FALSE_GOTO(_DBG_GETGOODS_A)
@XCHG()
@ONGOSUB(_GDS_01,_GDS_02,_GDS_03,_GDS_04,_GDS_05,_GDS_06,_GDS_07,_GDS_08,_GDS_09,_GDS_10,_GDS_11,_GDS_12,_GDS_13,_GDS_14,_GDS_15,_GDS_16,_GDS_17,_GDS_18,_GDS_19)
@GOTO(_DBG_GETGOODS_A)

_GDS_01;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TABIGOYA)
@!

_GDS_02;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_PHONE_RECEIVER)
@!

_GDS_03;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TAKOKESHI)
@!

_GDS_04;
@XCHG()
@GOODSIN_PLAYER(0,GDS_HAVE_FRANKLIN_BADGE)
@!

_GDS_05;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_PRISON)
@!

_GDS_06;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_SATSUTABA)
@!

_GDS_07;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_CHOTTO)
@!

_GDS_08;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_ZOMBI_HOIHOI)
@!

_GDS_09;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_DIAMOND)
@!

_GDS_10;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_ICHIGO_TOFU)
@!

_GDS_11;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_HIEROGLYPH_COPY)
@!

_GDS_12;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_EAGLE_EYE)
@!

_GDS_13;
@XCHG()
@GOODSIN_PLAYER(0,GDS_FOOD_BUBBLE_GUM)
@!

_GDS_14;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_BOOK_CHAT)
@!

_GDS_15;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_OBJECT_XYZ)
@!

_GDS_16;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_BANANA_SIGNED)
@!

_GDS_17;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_KOKESHIKESHI)
@!

_GDS_18;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_GUMIDORIAN)
@!

_GDS_19;
@XCHG()
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_CARROT)
@!

_DBG_GOODSFULL;
ÅüÇfÇîÇyÇqÇmÇvÇlÇmÇsÇmÇmÇrÇlÇrÅD@KEY()Å´
@GOSUB(_DBG_GFULL_2)
@GOTO(MSG_DEBUG_00)

_DBG_GFULL_2;
_DBG_GFULL_LOOP;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DBG_GFULL_2_END)
@GOODSIN_PLAYER(0,GDS_FOOD_SKIP_SAND_SP)
@GOTO(_DBG_GFULL_LOOP)
_DBG_GFULL_2_END;
@!

_DBG_DELGOODS;
ÅüÇfÇîÇyÇvÇrÇjÇyÇôÇrÇlÇrÅDÅ´
<ÇyÇmÇa>
<ÇrÇmÇsÇj>
@DSP_ITEM(2)
@SELGOTO(_DBG_GG50,_DBG_GG60)
@GOTO(_GETGOODS_END)
_DBG_GOODSEMPTY_ALL;
_DBG_GG50;
@SET_LOOPREG(1)
_DBG_GG51;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_DBG_GG59)
@GET_ORDER_PLAYER(0)
_DBG_GG52;
@GET_PLAYER_GOODS(0,1)
@XCHG()
@FALSE_GOTO(_DBG_GG53)
@XCHG()
@GOODSOUT_PLAYER(0,1)
@GOTO(_DBG_GG52)
_DBG_GG53;
@INC()
@GOTO(_DBG_GG51)
_DBG_GG59;
@!
_DBG_GG60;
@DSP_PL()
_DBG_GG61;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_DBG_GG69)
@GOODSOUT_PLAYER(0,0)
@GOTO(_DBG_GG61)
_DBG_GG69;
@!

_DBG_TRACYFULL;
ÅüÇ`ÇyÇjÇqÇrÇôÇvÅ´
Å@ÇhÇîÇoÇhÇmÅ@ÇrÇlÇrÅD
@SET_LOOPREG(20)
_TFULL_LOOP;
@SET_REG(1)
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_TFULL_END)
@TRACY_IN(0)
@INC()
@GOTO(_TFULL_LOOP)
_TFULL_END;
@KEYNP()
@GOTO(MSG_DEBUG_00)

_DBG_TRACYEMP;
ÅüÇ`ÇyÇjÇqÇyÇôÇvÅ@ÇjÇqÇmÇrÇlÇrÅD
_TEMPTY_LOOP;
@GET_TRACY_GOODS(1)
@FALSE_GOTO(_TEMPTY_END)
@SET_TRANS_GOODS(255,1)
@GOTO(_TEMPTY_LOOP)
_TEMPTY_END;
@KEYNP()
@GOTO(MSG_DEBUG_00)

_DBG_WEAPON;
ÅüÇrÇhÇjÇôÇtÇmÇaÇjÇvÅ´
Å@ÇjÇvÇdÇlÇrÅD@KEY()
@GOSUB(_SUB_DBG_WEAPON)
@GOTO(MSG_DEBUG_00)

_SUB_DBG_WEAPON;
@SET_LOOPREG(1)
_DBGWEA_LOOP;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_DBGWEA_END)
@GET_ORDER_PLAYER(0)
_DBGWEA_LOOP2;
@GET_PLAYER_GOODS(0,7)
@XCHG()
@FALSE_GOTO(_DBGWEA_02)
@XCHG()
@GOODSOUT_PLAYER(0,7)
@GOTO(_DBGWEA_LOOP2)
_DBGWEA_02;
@XCHG()
@ONGOSUB(_DBGWEA_NESS,_DBGWEA_PAULA,_DBGWEA_JEFF,_DBGWEA_POO)
@INC()
@GOTO(_DBGWEA_LOOP)
_DBGWEA_END;
@!

_DBGWEA_NESS;
@GOODSIN_PLAYER(PC_NESS,GDS_EQUIP_BAT_DENSETSU)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_NESS,GDS_EQUIP_PENDANT_UMI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_NESS,GDS_EQUIP_BRACELET_MEGAMI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_NESS,GDS_EQUIP_COIN_CHISANA)
@EQUIP_PLAYER_GOODS(0,0)
@!

_DBGWEA_PAULA;
@GOODSIN_PLAYER(PC_PAULA,GDS_EQUIP_FLYPAN_TENSHI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_PAULA,GDS_EQUIP_PENDANT_DAICHI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_PAULA,GDS_EQUIP_BRACELET_TENSHI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_PAULA,GDS_EQUIP_RIBBON_DOSEI)
@EQUIP_PLAYER_GOODS(0,0)
@!

_DBGWEA_JEFF;
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_BEAM_MOON)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_PENDANT_YAMI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_BRACELET_YOUSEI)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_COIN_KAGAYAKI)
@EQUIP_PLAYER_GOODS(0,0)
@!

_DBGWEA_POO;
@GOODSIN_PLAYER(PC_POO,GDS_EQUIP_CLOAK_KING)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_POO,GDS_EQUIP_BRACELET_KING)
@EQUIP_PLAYER_GOODS(0,0)
@GOODSIN_PLAYER(PC_POO,GDS_EQUIP_BANDANNA_KING)
@EQUIP_PLAYER_GOODS(0,0)
@!

;/////////////////////////////

_DBG_SPECIAL;
Å©
ÅüÇcÇqÇmÇrÇlÇrÇjÅH
@SEL_PQ(0,0,0,0,1)
@FALSE_GOTO(_SPECIAL_END)
@SAVE_REG()
Å´
ÅüÇcÇqÇmÇrÇqÅHÅ´
@SAVE_WIN()
@OPEN(12)
<ÇjÇmÇjÇt>
<ÇjÇyÇs>
<ÇcÇhÇx>
<ÇrÇaÇq>
<ÇgÇjÇj>
<ÇlÇtÇcÇj>
<ÇmÇîÇrÇôÇaÇôÇt>
<ÇjÇy>
<ÇjÇmÇj>
<ÇsÇqÇsÇj>
<ÇgÅ|ÇlÇrÇîÇj>
<ÇgÇoÇgÇqÇr>
<ÇoÇoÇgÇqÇr>
@DSP_ITEML(2)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@ONGOTO(_SP_GOOD,_SP1_1,_SP1_2,_SP1_3,_SP1_4,_SP1_5,_SP1_6,_SP1_7,_SP2_1,_SP2_2,_SP2_3,_SP3_1,_SP3_2)
@GOTO(_DBG_SPECIAL)
_SPECIAL_END;
@GOTO(MSG_DEBUG_00)

_SP_GOOD;
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@SET_SPECIAL(0,2,1)
@SET_SPECIAL(0,6,1)
@XCHG()
@HP_UP(0,100)
@PP_UP(0,100)
@GOTO(_DBG_SPECIAL)

_SP1_1;
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@SET_SPECIAL(0,1,2)
@XCHG()
@HP_DOWN(0,100)
@PP_DOWN(0,100)
@GOTO(_DBG_SPECIAL)
@!

_SP1_2;
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@SET_SPECIAL(0,1,3)
@GOTO(_DBG_SPECIAL)
@!

_SP1_3;
@LOAD_REG()
@SET_SPECIAL(0,1,4)
@GOTO(_DBG_SPECIAL)
@!

_SP1_4;
@LOAD_REG()
@SET_SPECIAL(0,1,5)
@GOTO(_DBG_SPECIAL)
@!

_SP1_5;
@LOAD_REG()
@SET_SPECIAL(0,1,6)
@GOTO(_DBG_SPECIAL)
@!

_SP1_6;
@LOAD_REG()
@SET_SPECIAL(0,1,7)
@GOTO(_DBG_SPECIAL)
@!

_SP1_7;
@LOAD_REG()
@SET_SPECIAL(0,1,8)
@GOTO(_DBG_SPECIAL)
@!

_SP2_1;
@LOAD_REG()
@SET_SPECIAL(0,2,2)
@GOTO(_DBG_SPECIAL)
@!

_SP2_2;
@LOAD_REG()
@SET_SPECIAL(0,2,3)
@GOTO(_DBG_SPECIAL)
@!

_SP2_3;
@LOAD_REG()
@SET_SPECIAL(0,6,2)
@GOTO(_DBG_SPECIAL)
@!

_SP3_1;
@LOAD_REG()
@XCHG()
@HP_UP(0,100)
@HP_DOWN(0,94)
@GOTO(_DBG_SPECIAL)
@!

_SP3_2;
@LOAD_REG()
@XCHG()
@PP_UP(0,100)
@PP_DOWN(0,99)
@GOTO(_DBG_SPECIAL)
@!


;/////////////////////////////////

_DBG_WARP;
ÅüÇcÇjÇmÅ@ÇhÇcÇtÇrÇlÇrÇjÅH
@OPEN(8)
<ÇnÇmÇîÇs>
<ÇsÅ|ÇrÇm>
<ÇgÇgÇlÇq>
<ÇfÇeÇqÇcÇîÇc>
<ÇrÇqÅ|Çj>
<ÇtÇâÇmÇsÅ|Çy>
<ÇrÇsÅ|ÇmÇaÇqÅ|>
<ÇgÇlÇsÇjÇs>
<ÇcÇjÇcÇjÇrÇaÇj>
<ÇeÇèÅ|ÇrÇhÇc>
<ÇlÅ|ÇmÇrÇhÇc>
<ÇrÇlÅ|Çy>
<ÇqÇmÇl>
<ÇrÇjÇqÇa>
<ÇlÇjÇôÇt>
<ÇfÇl>
<ÇsÇsÇhÇsÇhÇqÇj>
<ÇlÇyÇjÇmÇs>
<ÇfÇmÇyÇhÇrÇhÇsÇh>
<ÇjÇjÇrÇhÇsÇhÇjÇj>
@DSP_ITEML(3)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
Å©
@LOAD_GLOBAL_REG()
@ONGOTO(_WP_ONET,_WP_TWSN,_WP_HH,_WP_GRFD,_WP_THRK,_WP_WINS,_WP_DOSEI,_WP_SECLET,_WP_DSRT,_WP_FOUR,_WP_MOON,_WP_SUMS,_WP_RAMA,_WP_SKRB,_WP_MAKYO,_WP_GUMI,_WP_DKFD,_WP_MGKT,_WP_SAITEI,_WP_PAST)
@GOTO(MSG_DEBUG_00)

_WP_ONET;
@WARP(WARP_DEBUG_ONET)
@!

_WP_TWSN;
@WARP(WARP_DEBUG_TWSN)
@!

_WP_HH;
@WARP(WARP_DEBUG_HH)
@!

_WP_GRFD;
@WARP(WARP_DEBUG_GRFD)
@!

_WP_THRK;
@WARP(WARP_DEBUG_THRK)
@!

_WP_WINS;
@WARP(WARP_DEBUG_WINS)
@!

_WP_DOSEI;
@WARP(WARP_DBGEVT_30)
@!

_WP_SECLET;
@WARP(WARP_GPFT_FIELD_GEPPU)
@!

_WP_DSRT;
@WARP(WARP_DBGEVT_32)
@!

_WP_FOUR;
@WARP(WARP_DEBUG_FOUR)
@!

_WP_MOON;
@WARP(WARP_DEBUG_MOON)
@!

_WP_SUMS;
@WARP(WARP_DEBUG_SUMS)
@!

_WP_RAMA;
@WARP(WARP_DEBUG_RAMA)
@!

_WP_SKRB;
@WARP(WARP_DEBUG_SKRB)
@!

_WP_MAKYO;
@WARP(WARP_DBGEVT_45)
@!

_WP_GUMI;
@WARP(WARP_DEBUG_GUMI)
@!

_WP_SAITEI;
@WARP(WARP_DBGEVT_33)
@!

_WP_PAST;
@WARP(WARP_DEBUG_PAST)
@!

_WP_DKFD;
@WARP(WARP_DEBUG_DKFD)
@!

_WP_MGKT;
@WARP(WARP_DEBUG_MGKT)
@!

;////////////////////////////

_DBG_LEVELUP;
ÅüÇcÇqÇmÇrÇlÇrÇjÅHÅ´
<ÇyÇmÇhÇm>
<ÇgÇsÇq>
@DSP_ITEM(2)
@SELGOTO(_LVUP_ALL,_LVUP_ONE)
@GOTO(MSG_DEBUG_00)

_LVUP_ALL;
@GOSUB(_SUB_LEVELUP)
@FALSE_GOTO(_LVUP_ALL_END)
@XCHG()
_LVUPA_LOOP;
@SET_LEVEL(PC_NESS,0)
@SET_LEVEL(PC_PAULA,0)
@SET_LEVEL(PC_JEFF,0)
@SET_LEVEL(PC_POO,0)
_LVUP_ALL_OK;
ÅüÇqÇaÇqÇvÇrÇîÇsÇhÇrÇlÇrÇsÅD@KEYNP()
_LVUP_ALL_END;
@GOTO(MSG_DEBUG_00)
@!

_LVUP_ONE;
Å©
ÅüÇoÇqÅ|ÇxÅ|ÇvÇrÇmÇsÇjÇrÇsÇjÇcÇrÇhÅD
@SEL_PQ(0,0,0,0,1)
@FALSE_GOTO(_LVUP_ONE_END)
@XCHG()
@GOSUB(_SUB_LEVELUP)
@FALSE_GOTO(_LVUP_ONE_END)
@XCHG()
@SET_LEVEL(0,0)
@GOTO(_LVUP_ONE)
_LVUP_ONE_END;
@GOTO(MSG_DEBUG_00)
@!

_SUB_LEVELUP;
Å©
ÅüÇqÇaÇqÇvÅ@ÇmÇôÇtÇqÇôÇjÅ´
Å@ÇrÇsÇjÇcÇrÇhÅDÅ´
Å@Å@Å@@INPUT(2)
@CLRLINE()
@!

;///////////////////
_DBG_MONEY;
Å©
ÅüÇnÇjÇmÇmÅ@ÇrÇtÇrÇvÅ@ÇrÇlÇrÅD
@SAVE_WIN()
@DSP_PL()
@WINR_MONEY()
@OPEN(7)
<ÇfÇmÇjÇtÅ@Å@ÇlÇmÇsÇm>
<ÇrÇôÇyÇjÇmÅ@ÇlÇmÇsÇm>
<ÇrÇôÇyÇjÇmÅ@ÇrÇîÇsÇh>
<ÇrÇôÇyÇjÇmÅ@ÇOÇcÇq>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
Å©
@ONGOTO(_BANK_FULL,_MONEY_FULL,_SET_MONEY,_ZERO_MONEY)
@GOTO(MSG_DEBUG_00)

_BANK_FULL;
ÅüÇfÇmÇjÇtÇxÇjÇmÇvÅ´
Å@ÇXÇXÇXÇXÇXÇXÇXÇcÇqÇmÇrÇlÇrÅD@KEYNP()
@SET_LOOPREG(1)
_OT05_LOOP;
@SET_REG(1)
@XCHG()
@EQ(200)
@TRUE_GOTO(_OT05_END)
@DEPOSIT_MONEY_BANK(50000)
@INC()
@GOTO(_OT05_LOOP)
_OT05_END;
@DEPOSIT_MONEY_BANK(49999)
@GOTO(MSG_DEBUG_00)
@!

_MONEY_FULL;
ÅüÇrÇôÇyÇjÇmÇvÅ´
Å@ÇXÇXÇXÇXÇXÇcÇqÇmÇrÇlÇrÅD@KEYNP()
@MONEYIN(60000)
@MONEYIN(40000)
@WINR_MONEY()
@GOTO(MSG_DEBUG_00)
@!

_SET_MONEY;
ÅüÇjÇmÇfÇjÇvÅ@ÇrÇîÇsÇhÇrÇsÅ´
Å@ÇjÇcÇrÇhÅ´
@LOC(4,10)
Åï
@LOC(4,2)
Åê@INPUT(5)
@CLRLINE()
@FALSE_GOTO(_SETMONEY_END)
@SAVE_REG()
_SMONEY_OUT_LOOP;
@GOSUB(_SUB_MONEY_ZERO)
@LOAD_REG()
@XCHG()
@MONEYIN(0)
@WINR_MONEY()
ÅüÇoÇqÅ|ÇxÅ|ÇmÇrÇôÇyÇjÇmÇvÅ´
Å@@DSP_NUM(0)ÇcÇqÇmÅ@ÇrÇlÇrÇsÅD@KEYNP()
_SETMONEY_END;
@GOTO(MSG_DEBUG_00)
@!

_ZERO_MONEY;
@GOSUB(_SUB_MONEY_ZERO)
ÅüÇoÇqÅ|ÇxÅ|ÇmÇrÇôÇyÇjÇmÇvÅ´
Å@ÇOÇcÇqÇmÅ@ÇrÇlÇrÇsÅD@KEYNP()
@GOTO(MSG_DEBUG_00)
@!

_SUB_MONEY_ZERO;
_ZERO_MONEY_A;
@MONEYOUT(10000)
@FALSE_GOTO(_ZERO_MONEY_A)
_ZERO_MONEY_B;
@MONEYOUT(1000)
@FALSE_GOTO(_ZERO_MONEY_B)
_ZERO_MONEY_C;
@MONEYOUT(100)
@FALSE_GOTO(_ZERO_MONEY_C)
_ZERO_MONEY_D;
@MONEYOUT(10)
@FALSE_GOTO(_ZERO_MONEY_D)
_ZERO_MONEY_E;
@MONEYOUT(1)
@FALSE_GOTO(_ZERO_MONEY_E)
@!

;///////////////////

_DBG_SCRIPT;
ÅüÇlÇrÇxÇtÇmÅ@ÇrÇjÇqÇoÇsÇvÅ´
Å@ÇgÇîÇrÇhÇrÇrÇlÇrÅD
@SAVE_WIN()
@DSP_PL()
@WINR_MONEY()
@OPEN(7)
<ÇdÇrÇjÇqÇfÅ@ÇnÇsÇcÇj>
<ÇdÇrÇjÇqÇfÅ@Ç`ÇyÇjÇq>
<ÇlÇîÇgÇoÇyÅ@ÇnÇsÇcÇj>
<ÇxÇlÇcÇqÇx>
<ÇdÅ|ÇfÅ@ÇrÇsÇîÇj>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
Å©
@LOAD_GLOBAL_REG()
@ONGOSUB(MSG_UNSOU_SEND,MSG_UNSOU_LEAVE,MSG_PIZZA_SEND,MSG_SUB_MAKYO_CDMAN,MSG_SUB_DKFD_EGO)
@!


_DBG_SOUND;
@SAVE_WIN()
@DSP_PL()
@WINR_MONEY()
@OPEN(37)
<ÇaÇfÇl>
<ÇrÇd>
<ÇdÇeÇeÇdÇbÇs>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@ONGOTO(_DBG_BGM,_DBG_SE,_DBG_EFFECT)
@GOTO(MSG_DEBUG_00)

_DBG_BGM;
Å©
ÅüÇaÇfÇlÇvÇrÇmÇsÇjÇrÇsÇjÇcÇrÇhÅDÅ´
_BGM_SEL;
Å@Å@Å@Å@@INPUT(3)
@CLRLINE()
@FALSE_GOTO(MSG_DEBUG_00)
@XCHG()
@BGMSTART(0,0)
@GOTO(_BGM_SEL)

_DBG_SE;
Å©
ÅüÇrÇdÇvÇrÇmÇsÇjÇrÇsÇjÇcÇrÇhÅ´
_SE_SEL;
Å@Å@Å@Å@Å@@INPUT(3)
@CLRLINE()
@FALSE_GOTO(MSG_DEBUG_00)
@XCHG()
@SE(0)
@GOTO(_SE_SEL)

_DBG_EFFECT;
Å©
ÅüÇdÇeÇÖÇjÇsÇvÇrÇmÇsÇjÇrÇsÇjÇcÇrÇhÅ´
_EFFECT_SEL;
Å@Å@Å@Å@Å@@INPUT(2)
@CLRLINE()
@FALSE_GOTO(MSG_DEBUG_00)
@XCHG()
@BGM_EFFECT(0)
@GOTO(_EFFECT_SEL)


MSG_DEBUG_02;
ÅüÇlÇîÇoÇlÇmÇrÇsÅ|ÇmÇrÇîÇsÇhÅ´
<ÇcÇr>
<ÇjÇr>
@DSP_ITEM(2)
@SELGOTO(_DBG_MNS_ON,_DBG_MNS_OFF)
ÅüÇlÇsÇmÇlÇlÇcÇrÅD
@!

_DBG_MNS_ON;
ÅüÇlÇmÇrÇsÅ|ÇvÇcÇrÇlÇrÅD@KEYNP()
@CLRF(FLG_SYS_MONSTER_OFF)
@!

_DBG_MNS_OFF;
ÅüÇlÇmÇrÇsÅ|ÇvÇjÇrÇlÇrÅD@KEYNP()
@SETF(FLG_SYS_MONSTER_OFF)
@!

_DBG_HINT;
ÅüÇgÇmÇsÇxÇmÇlÇîÇrÅ|ÇyÇcÇrÅDÅ´
Å@ÇrÇtÇsÇvÅ@ÇmÇôÇtÇqÇôÇjÇrÇsÅ´
_DBG_HINT_001;
Å@Å@Å@Å@Å@@INPUT(2)
@CLRLINE()
@TRUE_GOTO(_DBG_HINT_2)
ÅüÇxÇlÇlÇrÇs@KEY()Å´
@GOTO(MSG_DEBUG_00)
_DBG_HINT_2;
@SET_REG(0)
Åü@DSP_NUM(0)ÇaÇmÇmÇlÇîÇrÅ|ÇyÇvÅ´
Å@ÇgÇôÇtÇyÇrÇlÇrÅ´
@KEY()Å´
@GOSUB(MSG_DBG_HINT)
Å´
@GOTO(_DBG_HINT_001)

_DBG_TLPT;
ÅüÇsÇqÇoÅ|ÇsÇmÇsÇrÇsÇvÇrÇlÇrÅ´
Å@Å@@INPUT(1)
@CLRLINE()
@ONGOTO(_DTLPT_1,_DTLPT_2,_DTLPT_3,_DTLPT_4)
@GOTO(MSG_DEBUG_00)

_DTLPT_1;
@CLOSEALL()
@TELEPORT(TLPT_DOSEIDANI,TLPTFX_NORMAL)
@!
_DTLPT_2;
@CLOSEALL()
@TELEPORT(TLPT_DOSEIDANI,TLPTFX_TORNADO)
@!
_DTLPT_3;
@CLOSEALL()
@TELEPORT(TLPT_DOSEIDANI,TLPTFX_GOODS)
@!
_DTLPT_4;
@CLOSEALL()
@TELEPORT(TLPT_DOSEIDANI,TLPTFX_EVENT)
@!

MSG_ADD_SKIP;
ÅüÇrÇjÇîÇoÇrÇmÇcÇvÇjÇvÇdÇlÇrÅD@KEYNP()
@GOSUB(_DBG_GFULL_2)
@!
MSG_DEBUG_01;
ÅüÇmÇmÇlÇcÇjÇlÇrÇmÅD
@KEYNP()
@!
;ÅüÇ«Ç±Ç‹Ç≈Ç∑Ç∑ÇﬂÇ‹Ç∑Ç©ÅBÅ´
@SAVE_WIN()
@OPEN(7)
;ÅüÅ@ÉGÉäÉAÅ´
;<ÉIÉlÉbÉg>
;<ÉcÅ[É\Éì>
;<ÉXÉäÅ[ÉN>
;<ÉtÉHÅ[ÉTÉCÉh>
;<ÉTÉ}Å[ÉYÅEÉXÉJÉâÉr>
;<ÇÃÇ±ÇË>
@DSP_ITEML(1)
@SELQ()
@ONGOTO(_DBG_AREA1,_DBG_AREA2,_DBG_AREA3,_DBG_AREA4,_DBG_AREA5,_DBG_AREA6)
@CLOSE()
@SELECT_WIN(1)
Å©
;ÅüÇ‚ÇﬂÇ‹ÇµÇΩ@KEYNP()
@!

MSG_DEBUG03;
_DBG_AREA1;
@OPEN(7)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@É|Å[ÉLÅ[Ç»Ç©Ç‹Ç…>
;<ÇQÅ@ÉuÉìÉuÅ[ÉìÇ†ÇÁÇÌÇÈ>
;<ÇRÅ@ÉuÉìÉuÅ[ÉìÇµÇ∑>
;<ÇSÅ@ÉtÉâÉìÉNÇΩÇ®Ç∑>
;<ÇTÅ@ÉIÉlÉbÉgÉNÉäÉA>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE11,_DBG_SCENE12,_DBG_SCENE13,_DBG_SCENE14,_DBG_SCENE15)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_SCENEEND;
Å©
;ÅüÇ‚ÇﬂÇ‹ÇµÇΩ@KEYNP()
@!

_DBG_AREA2;
@OPEN(6)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@É|Å[ÉâÇ‰Ç§Ç©Ç¢>
;<ÇQÅ@ÉtÉâÉoÉbÉWÇ‡ÇÁÇ§>
;<ÇRÅ@É|Å[ÉâÇ´Ç„Ç§ÇµÇ„Ç¬>
;<ÇSÅ@ÉcÅ[É\ÉìÉNÉäÉA>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE21,_DBG_SCENE22,_DBG_SCENE23,_DBG_SCENE24)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_AREA3;
@OPEN(6)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@É]ÉìÉrÇ…Ç¬Ç©Ç‹ÇÈ>
;<ÇQÅ@É^ÉXÇ±ÇÃÉ^ÉbÉVÅ[>
;<ÇRÅ@ÉAÉìÉhÉiÇÕÇ©Çπ>
;<ÇSÅ@ÉWÉFÉtÇ»Ç©Ç‹Ç…>
;<ÇTÅ@É]ÉìÉrÇ∫ÇÒÇﬂÇ¬>
;<ÇUÅ@ÉXÉäÅ[ÉNÉNÉäÉA>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE31,_DBG_SCENE32,_DBG_SCENE33,_DBG_SCENE34,_DBG_SCENE35,_DBG_SCENE36)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_AREA4;
@OPEN(6)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@ÉÇÉbÉ`Å[Ç®Ç®Ç†Ç»>
;<ÇQÅ@ÉgÉìÉYÉâÇ©Ç¢ÇŸÇ§>
;<ÇRÅ@Ç∆ÇÒÇøÇ´ÇµÇ∑>
;<ÇSÅ@É}ÉjÉ}ÉjÇΩÇ®Ç∑>
;<ÇTÅ@ÉtÉHÅ[ÉTÉCÉhÉNÉäÉA>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE41,_DBG_SCENE42,_DBG_SCENE43,_DBG_SCENE44,_DBG_SCENE45)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_AREA5;
@OPEN(6)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@É}ÉbÉTÅ[ÉWÇ≈ÉâÉìÉ}>
;<ÇQÅ@ÉsÉìÉNÇ∆É}ÉOÉl>
;<ÇRÅ@ÉXÉgÉwÉìÇ≈ÉXÉJÉâÉr>
;<ÇSÅ@É_ÉìÉWÉáÉìÇ®Ç∆Ç±>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE51,_DBG_SCENE52,_DBG_SCENE53,_DBG_SCENE54)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_AREA6;
@OPEN(6)
;ÅüÅ@ÉVÅ[ÉìÅ´
;<ÇPÅ@ÉQÉçÉbÉvÇ≈ÉvÅ[>
;<ÇQÅ@ÉãÉ~ÉlÉzÅ[Éã>
;<ÇRÅ@ÉTÉEÉìÉhÇªÇÎÇ§>
;<ÇSÅ@É}ÉWÉJÉìÉg>
;<ÇTÅ@Ç≥Ç¢Ç≤>
@DSP_ITEML(1)
@GOSUB(_SUB_SELWIN)
@FALSE_GOTO(_DBG_SCENEEND)
@ONGOSUB(_DBG_SCENE61,_DBG_SCENE62,_DBG_SCENE63,_DBG_SCENE64,_DBG_SCENE65)
@GOSUB(MSG_DEBUG_FLG)
@!

_DBG_SCENE11;
@SET_LOOPREG(10)
@!

_DBG_SCENE12;
@SET_LOOPREG(11)
@!

_DBG_SCENE13;
@SET_LOOPREG(12)
@!

_DBG_SCENE14;
@SET_LOOPREG(13)
@!

_DBG_SCENE15;
@SET_LOOPREG(14)
@!

_DBG_SCENE21;
@SET_LOOPREG(20)
@!

_DBG_SCENE22;
@SET_LOOPREG(21)
@!

_DBG_SCENE23;
@SET_LOOPREG(22)
@!

_DBG_SCENE24;
@SET_LOOPREG(23)
@!

_DBG_SCENE31;
@SET_LOOPREG(30)
@!

_DBG_SCENE32;
@SET_LOOPREG(31)
@!

_DBG_SCENE33;
@SET_LOOPREG(32)
@!

_DBG_SCENE34;
@SET_LOOPREG(33)
@!

_DBG_SCENE35;
@SET_LOOPREG(34)
@!

_DBG_SCENE36;
@SET_LOOPREG(35)
@!

_DBG_SCENE41;
@SET_LOOPREG(40)
@!

_DBG_SCENE42;
@SET_LOOPREG(41)
@!

_DBG_SCENE43;
@SET_LOOPREG(42)
@!

_DBG_SCENE44;
@SET_LOOPREG(43)
@!

_DBG_SCENE45;
@SET_LOOPREG(44)
@!

_DBG_SCENE51;
@SET_LOOPREG(50)
@!

_DBG_SCENE52;
@SET_LOOPREG(51)
@!

_DBG_SCENE53;
@SET_LOOPREG(52)
@!

_DBG_SCENE54;
@SET_LOOPREG(53)
@!

_DBG_SCENE61;
@SET_LOOPREG(60)
@!

_DBG_SCENE62;
@SET_LOOPREG(61)
@!

_DBG_SCENE63;
@SET_LOOPREG(62)
@!

_DBG_SCENE64;
@SET_LOOPREG(63)
@!

_DBG_SCENE65;
@SET_LOOPREG(64)
@!




_SUB_SELWIN;
@SELQ()
@SET_LOOPREG(1)
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(7)
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@!
MSG_DEBUG_FLG;
@FUNC(15)
_SCENE_FLG010;			;É|Å[ÉLÅ[íáä‘Ç…
@CMP(010,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_BGM_INSEKI_FALL_A)
@SETF(FLG_MYHOME_START)
@CLRF(FLG_BGM_INSEKI_FALL_A)
@SETF(FLG_INSEKI_STOPPER_APPEAR)
@SETF(FLG_MYHOME_SLEEPNES_APPEAR)
@CLRF(FLG_MYHOME_SLEEPNES_APPEAR)
@SETF(FLG_MYHOME_2F_1F)
@SETF(FLG_BGM_INSEKI_FALL_B)
@SETF(FLG_MYHOME_LIGHT_ON)
@SETF(FLG_YAZIUMA_TRACY)
@SETF(FLG_YAZIUMA_MAMA)
@SETF(FLG_YAZIUMA_POKEY)
@CLRF(FLG_BGM_INSEKI_FALL_B)
@SETF(FLG_GENKAN_MAMA_APPEAR)
@CLRF(FLG_GENKAN_MAMA_APPEAR)
@SETF(FLG_MYHOME_TRACY_DISAPPEAR)
@SETF(FLG_MYHOME_NES_CHANGE)
@CLRF(FLG_MYHOME_NES_CHANGE)
@SETF(FLG_MYHOME_KNOCK_APPEAR)
@SETF(FLG_YAZIUMA_DISAPPEAR)
@SETF(FLG_KAIDAN_TRACY_APPEAR)
@SETF(FLG_ONET_POKEY_DOOR_CLOSE)
@SETF(FLG_MYHOME_SLEEPNES_APPEAR)
@CLRF(FLG_MYHOME_SLEEPNES_APPEAR)
@CLRF(FLG_MYHOME_KNOCK_APPEAR)
@CLRF(FLG_KAIDAN_TRACY_APPEAR)
@SETF(FLG_MYHOME_POKEY_ENTER)
@SETF(FLG_MYHOME_DOOR_CLOSE)
@SETF(FLG_MYHOME_POKEY_APPEAR)
@SETF(FLG_MYHOME_1F_TRACY_APPEAR)
@SETF(FLG_MYHOME_POKEY)
@SETF(FLG_MYHOME_MAMA_YEAH)
@SETF(FLG_DOG)
@SETF(FLG_ITEM_TRACY)
@SETF(FLG_MYHOME_POKEY2_APPEAR)
@CLRF(FLG_MYHOME_POKEY_APPEAR)
@CLRF(FLG_MYHOME_POKEY2_APPEAR)
@SETF(FLG_INSEKI_PICKEY_APPEAR)
@SETF(FLG_POKEY)
@CLRF(FLG_MYHOME_TRACY_DISAPPEAR)
@CLRF(FLG_MYHOME_1F_TRACY_APPEAR)
@SETF(FLG_MYHOME_POKEY_DISAPPEAR)
@SETF(FLG_MYHOME_PHONE)
@SETF(FLG_PAPA_MYHOME)
@CLRF(FLG_MYHOME_PHONE)
@CLRF(FLG_MYHOME_DOOR_CLOSE)
@SETF(FLG_SYS_PHONE_PAPA)
@SETF(FLG_SYS_PHONE_MYHOME)
@SETF(FLG_SYS_PHONE_MYHOME2)
@SETF(FLG_TLPT_ONET)
@SETF(FLG_STEP_ONET)

_SCENE_FLG011;			;ÉsÉbÉLÅ[ã~èo
@CMP(011,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_DOG_LATER_APPEAR)
@SETF(FLG_INSEKI)
@SETF(FLG_PICKEY)
@CLRF(FLG_INSEKI_PICKEY_APPEAR)
@CLRF(FLG_ONET_POKEY_DOOR_CLOSE)
@SETF(FLG_ONET_LARDNA_APPEAR)
@SETF(FLG_INSEKI_HITMAN_APPEAR)
@CLRF(FLG_INSEKI_HITMAN_APPEAR)
@SETF(FLG_BUNBUN)
@SETF(FLG_ONET_MINCES_APPEAR)

_SCENE_FLG012;			;ÉuÉìÉuÅ[ÉìéÄÇ∑
@CMP(012,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_ONET_2FPOKEY_APPEAR)
@SETF(FLG_ONET_2FPICKEY_APPEAR)
@CLRF(FLG_POKEY)
@CLRF(FLG_PICKEY)
@SETF(FLG_ONET_AMBRAMI)
@CLRF(FLG_BUNBUN)
@SETF(FLG_ONET_MYHOME_BUNBUN_APPEAR)
@CLRF(FLG_ONET_MYHOME_BUNBUN_APPEAR)
@SETF(FLG_ONET_LARDNA)
@SETF(FLG_ONET_MIZUNO_DOOR_OPEN)
@SETF(FLG_1FMIZUNO_APPEAR)
@SETF(FLG_ONET_DAYBREAK)
@CLRF(FLG_ONET_LARDNA)

_SCENE_FLG013;			;ÉtÉâÉìÉNì|Ç∑
@CMP(013,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_MYHOME_PHONE_TRACY)
@SETF(FLG_ITEM_MAP)
@SETF(FLG_ONET_GUARDSHARK_DISAPPEAR)
@SETF(FLG_WIN_FRANK)
@SETF(FLG_KEY_TABIGOYA)
@SETF(FLG_OPEN_TABIGOYA)
@SETF(FLG_ONET_SHARK_2F_DISAPPEAR)
@SETF(FLG_ONET_SHARK_A_DISAPPEAR)
@SETF(FLG_ONET_SHARK_B_DISAPPEAR)
@SETF(FLG_ONET_SHARK_C_DISAPPEAR)

_SCENE_FLG014;			;ÉIÉlÉbÉgÉNÉäÉA
@CMP(014,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WIN_GIAN_BOSS)
@SETF(FLG_POWR_GIAN)
@SETF(FLG_ONET_POLA_TELEPATHY)
@CLRF(FLG_ONET_POLA_TELEPATHY)
@SETF(FLG_POLICE_STRONG_DISAPPEAR)
@SETF(FLG_POLICE_STRONG_B_APPEAR)
@SETF(FLG_ONET_KANBANCOP_APPEAR)
@CLRF(FLG_ONET_KANBANCOP_APPEAR)
@SETF(FLG_POLICE_KANBANCOP_HEAR)
@SETF(FLG_POLICE_KANBANCOP_APPEAR)
@CLRF(FLG_POLICE_STRONG_B_APPEAR)
@SETF(FLG_POLICE_5COP_APPEAR)
@SETF(FLG_ONET_COPA_DISAPPEAR)
@SETF(FLG_ONET_COPB_DISAPPEAR)
@SETF(FLG_ONET_COPC_DISAPPEAR)
@SETF(FLG_ONET_COPD_DISAPPEAR)
@SETF(FLG_ONET_COPE_DISAPPEAR)
@CLRF(FLG_POLICE_5COP_APPEAR)
@CLRF(FLG_POLICE_KANBANCOP_APPEAR)
@SETF(FLG_ONET_GATEOPEN)
@CLRF(FLG_POLICE_STRONG_DISAPPEAR)
@CLRF(FLG_ONET_2FPOKEY_APPEAR)
@CLRF(FLG_ONET_MINCES_APPEAR)
@CLRF(FLG_ONET_LARDNA_APPEAR)

_SCENE_FLG020;			;É|Å[ÉâóUâ˚
@CMP(020,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TLPT_TWSN)
@SETF(FLG_TWSN_PAUL)
@SETF(FLG_TWSN_POLA_TELEPATHY)
@CLRF(FLG_TWSN_POLA_TELEPATHY)
@SETF(FLG_TWSN_PAUL_UPSET)
@SETF(FLG_TWSN_INFO_TONCHIKI)
@SETF(FLG_TWSN_TONCHIKI_R_DISAPPEAR)
@SETF(FLG_TWSN_TONCHIKI_APPEAR)
@SETF(FLG_TWSN_WIN_TONCHIKI)
@SETF(FLG_TWSN_APPLE_THANKS)
@SETF(FLG_WARP_APPLE_TWSN)
@SETF(FLG_TWSN_ORANGE_THANKS)
@SETF(FLG_ITEM_PHONE)
@CLRF(FLG_WARP_APPLE_TWSN)

_SCENE_FLG021;			;ÇgÇgÇﬁÇÁÇ÷
@CMP(021,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TWSN_TACO_DISCOVER)
@SETF(FLG_TWSN_INFO_TACO)
@SETF(FLG_TWSN_CHAOSAPPLE_APPEAR)
@SETF(FLG_HAPPY_SWITCH)
@SETF(FLG_ITEM_TACO_ERASER)
@SETF(FLG_TWSN_APPLE_DISAPPEAR)
@CLRF(FLG_TWSN_CHAOSAPPLE_APPEAR)
@SETF(FLG_GRFD_LLPT_TACO_DISAPPEAR)
@SETF(FLG_STEP_HAPPY)
@SETF(FLG_ITEM_FRANKLINBADGE)
@SETF(FLG_GRFD_POKEY_APPEAR)
@CLRF(FLG_GRFD_POKEY_APPEAR)

_SCENE_FLG022;			;É|Å[Éâã~èo
@CMP(022,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WIN_CARPAINTER)
@SETF(FLG_HAPPY_UPRIGHT_1_DISAPPEAR)
@SETF(FLG_HAPPY_UPRIGHT_2_DISAPPEAR)
@SETF(FLG_HAPPY_UPRIGHT_3_DISAPPEAR)
@SETF(FLG_HAPPY_UPRIGHT_4_DISAPPEAR)
@SETF(FLG_HAPPY_UPRIGHT_5_DISAPPEAR)
@SETF(FLG_HAPPY_UPRIGHT_6_DISAPPEAR)
@CLRF(FLG_HAPPY_SWITCH)
@SETF(FLG_HAPPY_POKEY_APPEAR)
@CLRF(FLG_HAPPY_POKEY_APPEAR)
@SETF(FLG_WARP_GRFD_YAMAGOYA)
@SETF(FLG_POLA_GRFD)
@CLRF(FLG_TWSN_PAUL_UPSET)
@SETF(FLG_WIN_LLPT_BOSS)
@SETF(FLG_POWR_LLPT)
@SETF(FLG_POLA)
@SETF(FLG_TWSN_MESSENGER_APPEAR)
@CLRF(FLG_TWSN_MESSENGER_APPEAR)

_SCENE_FLG023;			;ÉcÅ[É\ÉìÉNÉäÉA
@CMP(023,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TWSN_ITEM_TONCHIKI)
@SETF(FLG_ITEM_TICKET)
@SETF(FLG_TWSN_FIELD_TONZ_DISAPPEAR)
@SETF(FLG_TWSN_MICHIKO_APPEAR)
@CLRF(FLG_TWSN_MICHIKO_APPEAR)
@SETF(FLG_TWSN_CHAOS_STAGE_START)
@SETF(FLG_TWSN_MICHIKO_THANKYOU)
@SETF(FLG_TWSN_TONZURA_FREE)
@CLRF(FLG_TWSN_TONCHIKI_APPEAR)
@SETF(FLG_TWSN_TONZURABUS_APPEAR)
@SETF(FLG_BGM_TBUS)
@SETF(FLG_TUNNEL_TWSN_THRK_TR)
@CLRF(FLG_TUNNEL_TWSN_THRK_TR)
@CLRF(FLG_BGM_TBUS)
@CLRF(FLG_TWSN_TONZURABUS_APPEAR)

_SCENE_FLG030;			;É]ÉìÉrÇ…ïﬂÇ‹ÇÈÅBÉWÉFÉtÉXÉ^Å[Ég
@CMP(030,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TLPT_THRK)
@SETF(FLG_THRK_BIKINIZOMBI_APPEAR)
@SETF(FLG_THRK_HOTELMAN_DISAPPEAR)
@SETF(FLG_THRK_INFO_D_DISAPPEAR)
@CLRF(FLG_THRK_BIKINIZOMBI_APPEAR)
@SETF(FLG_THRK_BIKINIZOMBI_F_APPEAR)
@CLRF(FLG_THRK_BIKINIZOMBI_F_APPEAR)
@SETF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
@CLRF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
@SETF(FLG_THRK_HOTELZOMBI_APPEAR)
@CLRF(FLG_THRK_HOTELZOMBI_APPEAR)
@CLRF(FLG_THRK_HOTELMAN_DISAPPEAR)
@SETF(FLG_WINS_POLA_TELEPATHY)
@CLRF(FLG_WINS_POLA_TELEPATHY)
@SETF(FLG_TLPT_WINS)
@SETF(FLG_WINS_START)

_SCENE_FLG031;			;É^ÉbÉVÅ[ÉeÉìÉgÇ…
@CMP(031,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WINS_TONY)
@SETF(FLG_ITEM_KEY_LOCKER)
@SETF(FLG_WINS_LOCKER_FAILED)
@SETF(FLG_ITEM_GAUS)
@SETF(FLG_WINS_TONY_CROUCH_APPEAR)
@CLRF(FLG_WINS_TONY_CROUCH_APPEAR)
@SETF(FLG_BGM_WINT1)
@SETF(FLG_ITEM_BUBBLE_GUM)
@SETF(FLG_WINS_BMONKEY_DISAPPEAR)
@SETF(FLG_BALLOONMONKEY)
@SETF(FLG_WINS_DAYBREAK)
@SETF(FLG_WINS_JEFF_REPAIR)

_SCENE_FLG032;			;ÉAÉìÉhÅ[ÉiÉbÉcëO
@CMP(032,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WINS_TASCO_ACROSS)
@SETF(FLG_WINS_BRICK_BARKER_DISAPPEAR)
@SETF(FLG_FMON_BRICK_A_A_DISAPPEAR)
@SETF(FLG_FMON_BRICK_A_B_DISAPPEAR)
@SETF(FLG_FMON_BRICK_B_A_DISAPPEAR)
@SETF(FLG_FMON_BRICK_B_B_DISAPPEAR)
@SETF(FLG_FMON_BRICK_C_A_DISAPPEAR)
@SETF(FLG_FMON_BRICK_C_B_DISAPPEAR)
@SETF(FLG_WINS_BRICK_THANKS_APPEAR)
@CLRF(FLG_WINS_BRICK_THANKS_APPEAR)
@SETF(FLG_WINS_ROPE_SWITCH)
@CLRF(FLG_BALLOONMONKEY)

_SCENE_FLG033;			;ÉWÉFÉtÇíáä‘Ç…
@CMP(033,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WINS_ANDONUT)
@SETF(FLG_WINS_SKYW_DISAPPEAR)
@SETF(FLG_JEFF)
@SETF(FLG_THRK_ESCAPER_APPEAR)
@CLRF(FLG_THRK_ESCAPER_APPEAR)
@SETF(FLG_THRK_BROKEN_SKYW_APPEAR)
@SETF(FLG_WINS_KANAI_APPEAR)
@SETF(FLG_THRK_HOTEL_BOY_APPEAR)
@SETF(FLG_THRK_MATENT_APPEAR)
@SETF(FLG_THRK_PRISON_OPEN)

_SCENE_FLG034;			;É]ÉìÉrëﬁé°
@CMP(034,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WIN_MATENT)
@CLRF(FLG_THRK_MATENT_APPEAR)
@SETF(FLG_BOX_THRK_MATENT)
@SETF(FLG_ITEM_HOIHOI)
@SETF(FLG_BOX_THRK_MATENT)
@SETF(FLG_ITEM_HAEMITU)
@SETF(FLG_PUT_ZOMBI_HOIHOI)
@CLRF(FLG_PUT_ZOMBI_HOIHOI)
@SETF(FLG_THRK_ZOMBI_CAPTURED)
@SETF(FLG_THRK_OZISAN_D_DISAPPEAR)
@SETF(FLG_THRK_GRAVEZOMBI_DISAPPEAR)

_SCENE_FLG035;			;ÉQÉbÉvÅ[ì|Ç∑
@CMP(035,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_FMON_BOSS_GRAVE_DISAPPEAR)
@SETF(FLG_TLPT_BAKA)
@SETF(FLG_DOSEI_SECRETCODE)
@SETF(FLG_GPFT_PASSWORD_OK)
@SETF(FLG_WIN_GEPPU)
@CLRF(FLG_THRK_OZISAN_D_DISAPPEAR)
@SETF(FLG_DOSEI_ONSEN_GERO)
@SETF(FLG_THRK_PEOPLE_APPEAR)
@SETF(FLG_THRK_BUIL_B_MAN_APPEAR)
@CLRF(FLG_THRK_BUIL_B_MAN_APPEAR)
@SETF(FLG_ONET_DAYBREAK)
@CLRF(FLG_THRK_ZOMBI_CAPTURED)
@CLRF(FLG_DOSEI_ONSEN_GERO)
@SETF(FLG_WIN_MLKY_BOSS)
@SETF(FLG_POWR_MLKY)

_SCENE_FLG040;			;ÉVÉáÅ[ÉWÇ…Ç†Ç§
@CMP(040,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_STEP_DSRT)
@SETF(FLG_TLPT_DSRT)
@SETF(FLG_DSRT_SYOZI_1)
@SETF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_DSRT_SYOZI_DUNGEON_APPEAR)
@SETF(FLG_DSRT_CLEAR)
@SETF(FLG_TLPT_FOUR)
@CLRF(FLG_THRK_HOTEL_BOY_APPEAR)
@CLRF(FLG_THRK_PEOPLE_APPEAR)
@SETF(FLG_FOUR_MISSFAKE)
@SETF(FLG_DSRT_SWITCH_BEFORE)
@SETF(FLG_DSRT_SWITCH)

_SCENE_FLG041;			;çªîôÉNÉäÉAÅAÉgÉìÉYÉââï˙
@CMP(041,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WIN_DSRT_BOSS_A)
@SETF(FLG_WIN_DSRT_BOSS_B)
@SETF(FLG_WIN_DSRT_BOSS_C)
@SETF(FLG_WIN_DSRT_BOSS_D)
@SETF(FLG_WIN_DSRT_BOSS_E)
@SETF(FLG_DSRT_BOSS_1)
@SETF(FLG_DSRT_BOSS_2)
@SETF(FLG_DSRT_BOSS_3)
@SETF(FLG_DSRT_BOSS_4)
@SETF(FLG_WIN_DSRT_BOSS)
@CLRF(FLG_DSRT_SYOZI_DUNGEON_APPEAR)
@CLRF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_DSRT_YUMBO_B_APPEAR)
@SETF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_DSRT_DUNGEON_OK)
@SETF(FLG_DSRT_YUMBO_SHIGE_APPEAR)
@CLRF(FLG_DSRT_YUMBO_SHIGE_APPEAR)
@CLRF(FLG_DSRT_SYOZI_DISAPPEAR)
@SETF(FLG_DSRT_ITEM_DIA)
@SETF(FLG_FOUR_TONZURA_FREE)
@SETF(FLG_FOUR_TONZURA_THANKS)

_SCENE_FLG042;			;É|Å[ÉâóUâ˚ÅAÉgÉìÉ`ÉLéÄÇ∑
@CMP(042,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_FOUR_INFO_D_APPEAR)
@SETF(FLG_GLOBAL_POLA_KIDNAPPED)
@SETF(FLG_FOUR_DEPT_BOSS_APPEAR)
@CLRF(FLG_FOUR_INFO_D_APPEAR)
@SETF(FLG_FOUR_DEPT_SWITCH)
@SETF(FLG_FOUR_DEPT_OK)
@CLRF(FLG_FOUR_DEPT_SWITCH)
@SETF(FLG_FOUR_DEPT_MSGCHG)
@CLRF(FLG_FOUR_DEPT_BOSS_APPEAR)
@SETF(FLG_FOUR_TONCHIKI_APPEAR)
@SETF(FLG_FOUR_TONCHIKI)
@CLRF(FLG_FOUR_TONCHIKI_APPEAR)

_SCENE_FLG043;			;É}ÉjÉ}ÉjîjâÛ
@CMP(043,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_MOON_R_DISAPPEAR)
@SETF(FLG_MOON_WARP_X)
@SETF(FLG_MOON_INVISIBLEMAN)
@SETF(FLG_MOON_INVISIBLE_1)
@SETF(FLG_MOON_INVISIBLE_2)
@SETF(FLG_MOON_INVISIBLE_3)
@SETF(FLG_MOON_INVISIBLE_4)
@CLRF(FLG_MOON_INVISIBLE_5)
@CLRF(FLG_MOON_INVISIBLE_1)
@CLRF(FLG_MOON_INVISIBLE_2)
@CLRF(FLG_MOON_INVISIBLE_3)
@CLRF(FLG_MOON_INVISIBLE_4)
@CLRF(FLG_MOON_INVISIBLE_5)
@SETF(FLG_MOON_R_DISAPPEAR)
@SETF(FLG_MOON_MONOTOLY_DISAPPEAR)
@SETF(FLG_WIN_MANIMANI)
@SETF(FLG_PHONE_FOUR_APPLE_ICHIGO)
@SETF(FLG_FOUR_SARU_B_APPEAR)
@CLRF(FLG_FOUR_SARU_B_APPEAR)
@SETF(FLG_FOUR_MAID_APPEAR)
@SETF(FLG_DSRT_TJAB_MOVE)

_SCENE_FLG044;			;É|Å[Éâã~èoÅAÉtÉHÅ[ÉTÉCÉhÉNÉäÉA
@CMP(044,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_SARUDUNGEON_A_OK)
@SETF(FLG_SARUDUNGEON_B_OK)
@SETF(FLG_SARUDUNGEON_C_OK)
@SETF(FLG_SARUDUNGEON_D_OK)
@SETF(FLG_SARUDUNGEON_E_OK)
@SETF(FLG_SARUDUNGEON_F_OK)
@SETF(FLG_SARUDUNGEON_G_OK)
@SETF(FLG_SARUDUNGEON_H_OK)
@SETF(FLG_SARUDUNGEON_I_OK)
@SETF(FLG_SARUDUNGEON_J_OK)
@SETF(FLG_SARUDUNGEON_L_OK)
@SETF(FLG_SARUDUNGEON_M_OK)
@SETF(FLG_SARUDUNGEON_N_OK)
@SETF(FLG_SARUDUNGEON_O_OK)
@SETF(FLG_DSRT_SARU_TACO_DISAPPEAR)
@SETF(FLG_ITEM_TOFU)
@SETF(FLG_DSRT_TSARU_DISAPPEAR)
@SETF(FLG_DSRT_TSARU_A_APPEAR)
@CLRF(FLG_DSRT_TSARU_A_APPEAR)
@SETF(FLG_DSRT_TSARU_B_APPEAR)
@CLRF(FLG_DSRT_TSARU_B_APPEAR)
@CLRF(FLG_DSRT_TSARU_DISAPPEAR)
@SETF(FLG_MASTER_TLPT)
@CLRF(FLG_FOUR_MAID_APPEAR)
@SETF(FLG_FOUR_MAID_THANKS)
@SETF(FLG_FOUR_GUARDROBOT_A_DISAPPEAR)
@SETF(FLG_FOUR_MIHARI_1_DISAPPEAR)
@SETF(FLG_FOUR_MIHARI_2_DISAPPEAR)
@SETF(FLG_FOUR_MIHARI_3_DISAPPEAR)
@SETF(FLG_FOUR_MIHARI_4_DISAPPEAR)
@SETF(FLG_FOUR_MIHARI_5_DISAPPEAR)
@SETF(FLG_FOUR_YUDANROBO_DISAPPEAR)
@SETF(FLG_FOUR_BLDG_TONZURA_APPEAR)
@CLRF(FLG_FOUR_BLDG_TONZURA_APPEAR)
@CLRF(FLG_GLOBAL_POLA_KIDNAPPED)
@SETF(FLG_POLA_1)
@SETF(FLG_FOUR_STAIRWAY_APPEAR)
@SETF(FLG_FOUR_MONOTOLY_APPEAR)
@SETF(FLG_FOUR_HELI_DISAPPEAR)
@SETF(FLG_FOUR_OK)
@SETF(FLG_PHONE_FOUR_APPLE_MONO)
@SETF(FLG_PHONE_FOUR_ORANGE_MONO)
@SETF(FLG_FOUR_TONZURABUS_APPEAR)
@CLRF(FLG_FOUR_TONZURABUS_APPEAR)
@CLRF(FLG_THRK_BROKEN_SKYW_APPEAR)
@SETF(FLG_THRK_FIXED_SKYW_APPEAR)
@SETF(FLG_THRK_OZISAN_D_DISAPPEAR)
@CLRF(FLG_THRK_FIXED_SKYW_APPEAR)
@CLRF(FLG_THRK_OZISAN_D_DISAPPEAR)

_SCENE_FLG045;			;
@CMP(045,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_WINS_LABO_MONKEY_APPEAR)
@CLRF(FLG_WINS_LABO_MONKEY_APPEAR)
@CLRF(FLG_WINS_SKYW_DISAPPEAR)
@SETF(FLG_WINS_TASS_BMONKEY_APPEAR)
@SETF(FLG_WINS_TACO_DISAPPEAR)
@SETF(FLG_WIN_RAIN_BOSS)
@SETF(FLG_POWR_RAIN)
@SETF(FLG_WINS_SKYW_DISAPPEAR)
@SETF(FLG_TLPT_SUMS)

_SCENE_FLG050;			;ÉâÉìÉ}ÉXÉ^Å[Ég
@CMP(050,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_SYS_PHONE_STOIC)
@SETF(FLG_SYS_INPUT_PLAYER_NAME)
@SETF(FLG_SUMS_STOIC_RESERVED)
@SETF(FLG_SUMS_STOIC_WIFE_DISAPPEAR)
@SETF(FLG_SUMS_MASSAGE_APPEAR)
@CLRF(FLG_SUMS_MASSAGE_APPEAR)
@SETF(FLG_SUMS_RAMMA_START)
@SETF(FLG_TLPT_RAMA)
@SETF(FLG_RAMA_258_DISAPPEAR)

_SCENE_FLG051;			;ÉvÅ[íáä‘Ç…ÅAÉ}ÉOÉlÉbÉgÅAÉsÉìÉNÉNÉäÉA
@CMP(051,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_RAMA_MASTER)
@SETF(FLG_RAMA_OK)
@SETF(FLG_PU)
@SETF(FLG_SUMS_OMAR_B_APPEAR)
@SETF(FLG_FMON_HIEROGLYPH_A_DISAPPEAR)
@SETF(FLG_FMON_HIEROGLYPH_B_DISAPPEAR)
@SETF(FLG_SUMS_HIEROGLYPH)
@SETF(FLG_ITEM_HIEROGLYPH)
@SETF(FLG_SUMS_MUSEUM_PHONE_RING)
@CLRF(FLG_SUMS_MUSEUM_PHONE_RING)
@SETF(FLG_FOUR_KOMORITA)
@SETF(FLG_ITEM_BANANA)
@SETF(FLG_FOUR_KOMORITA_APPEAR)
@SETF(FLG_WIN_MGNT_BOSS)
@SETF(FLG_POWR_MGNT)
@SETF(FLG_RAMA_RABBIT_DISAPPEAR)
@SETF(FLG_WIN_PINK_BOSS)
@SETF(FLG_POWR_PINK)

_SCENE_FLG052;			;ÉXÉJÉâÉrÇ÷
@CMP(052,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_DSRT_SYOZI_DISAPPEAR)

_SCENE_FLG053;			;ÉvÅ[ï ÇÍÇÈÅAÉ_ÉìÉWÉáÉìíjÇ∆ñÇã´Ç÷
@CMP(053,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TOTO_SAILOR_MSGCHG)
@SETF(FLG_TLPT_SKRB)
@SETF(FLG_SPHINX)
@SETF(FLG_SPHINX_OK)
@SETF(FLG_FMON_PYRA_BOSS_DISAPPEAR)
@SETF(FLG_SKRB_PYRAMID_OK)
@SETF(FLG_ITEM_TAKANOME)
@SETF(FLG_WIN_PYRAMID_BOSS)
@SETF(FLG_FMON_PYRA_A_A_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_B_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_C_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_D_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_E_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_F_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_G_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_H_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_I_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_J_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_K_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_L_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_M_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_N_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_O_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_P_DISAPPEAR)
@SETF(FLG_FMON_PYRA_A_Q_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_A_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_B_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_C_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_D_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_E_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_F_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_G_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_H_DISAPPEAR)
@SETF(FLG_FMON_PYRA_B_I_DISAPPEAR)
@SETF(FLG_PU_0)

_SCENE_FLG054;			;
@CMP(054,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_ITEM_KEY_PUPUKA)
@SETF(FLG_SKRB_DUNGEONMAN_OPEN)
@SETF(FLG_BRICKROAD)
@SETF(FLG_SKRB_BRICKROAD_DISAPPEAR)
@SETF(FLG_SKRB_BRICKROAD_MAKYO_APPEAR)
@SETF(FLG_SKRB_YARIMAN_B_APPEAR)
@SETF(FLG_SKRB_YARIMAN)
@SETF(FLG_DSRT_KANBAN_44_MOVE)

_SCENE_FLG060;			;ÉvÅ[ïúäà
@CMP(060,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TLPT_MAKY)
@SETF(FLG_MAKYO_USE_TAKANOME)
@SETF(FLG_WIN_GEROPP)

_SCENE_FLG061;			;ÉOÉ~ÅEÉãÉ~Él
@CMP(061,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TLPT_GUMI)
@SETF(FLG_GUMI_INFO_MUKUCHI)
@SETF(FLG_PHONE_GUMI_APPLE)
@SETF(FLG_PHONE_GUMI_ORANGE)
@SETF(FLG_SEBASTIAN_DISAPPEAR)
@SETF(FLG_WINS_LABO_MOUSE_APPEAR)
@SETF(FLG_ITEM_KOKESHI)
@CLRF(FLG_WINS_LABO_MOUSE_APPEAR)
@SETF(FLG_WINS_STONE_TACO_DISAPPEAR)
@SETF(FLG_WINS_KOKESHI_DISAPPEAR)
@SETF(FLG_FMON_STONE_BOSS_DISAPPEAR)
@SETF(FLG_WIN_GANSEKIMAN)
@SETF(FLG_CAPSULE_OK)
@SETF(FLG_WINS_CAPSULE_PEOPLE_APPEAR)
@CLRF(FLG_WINS_CAPSULE_PEOPLE_APPEAR)
@SETF(FLG_LIBRARY_INFO_MUKUCHI)
@SETF(FLG_ITEM_MUKUCHI)
@SETF(FLG_GUMI_USEBOOK)
@SETF(FLG_SYS_INPUT_NAME_KANA)
@SETF(FLG_GUMI_CAVEOPEN)
@SETF(FLG_GUMI_TALKERSTONE)
@SETF(FLG_DOSEI_ANDONUT)
@SETF(FLG_DOSEI_APPLE_APPEAR)
@SETF(FLG_DKFD_ROCK_A)
@SETF(FLG_DKFD_ROCK_B)
@SETF(FLG_DKFD_ROCK_C)
@SETF(FLG_WIN_LUMI_BOSS)
@SETF(FLG_POWR_LUMI)

_SCENE_FLG062;			;ÉtÉ@ÉCÉA
@CMP(062,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TLPT_DKFD)
@CLRF(FLG_SEBASTIAN_DISAPPEAR)
@SETF(FLG_DKFD_DOOR_DISAPPEAR)
@SETF(FLG_INFO_POWR)
@SETF(FLG_DKFD_GUMI_BOSS)
@SETF(FLG_WIN_FIRE_BOSS)
@SETF(FLG_POWR_FIRE)
@CLRF(FLG_POWR_GIAN)
@CLRF(FLG_POWR_LLPT)
@CLRF(FLG_POWR_RAIN)
@CLRF(FLG_POWR_MLKY)
@CLRF(FLG_POWR_MGNT)
@CLRF(FLG_POWR_PINK)
@CLRF(FLG_POWR_LUMI)
@CLRF(FLG_POWR_FIRE)
@SETF(FLG_POWR_ALL)

_SCENE_FLG063;			;É}ÉWÉJÉìÉg
@CMP(063,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_STEP_MGKT)
@SETF(FLG_MGKT_TOMB6)
@SETF(FLG_FMON_KRAKEN2_A_DISAPPEAR)
@SETF(FLG_FMON_KRAKEN2_B_DISAPPEAR)
@SETF(FLG_FMON_KRAKEN2_C_DISAPPEAR)
@SETF(FLG_WIN_OSCAR)
@SETF(FLG_DKFD_DOSEI_ST1_APPEAR)
@CLRF(FLG_INSEKI_STOPPER_APPEAR)
@SETF(FLG_FIRE_PARTY_APPEAR)
@CLRF(FLG_FIRE_PARTY_APPEAR)

_SCENE_FLG064;			;ÉâÉXÉg
@CMP(064,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_INFO_XYZ)
@CLRF(FLG_ONET_DAYBREAK)
@SETF(FLG_ONET_DOOR_CLOSE)
@CLRF(FLG_ONET_MIZUNO_DOOR_OPEN)
@CLRF(FLG_MYHOME_LIGHT_ON)
@SETF(FLG_ITEM_XYZ)
@SETF(FLG_XYZ_OK)

_SCENE_FLG65;			;
@CMP(65,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_SPACETUNNEL2_START)
@SETF(FLG_DKFD_ST2_APPEAR)
@SETF(FLG_DKFD_ANDONUT_A_APPEAR)
@SETF(FLG_DKFD_APPLE_A_APPEAR)
@SETF(FLG_DKFD_DOSEI_A_APPEAR)
@CLRF(FLG_DKFD_ANDONUT_A_APPEAR)
@SETF(FLG_DKFD_ANDONUT_B_APPEAR)
@SETF(FLG_DKFD_ST3_APPEAR)
@SETF(FLG_DKFD_END_GET_READY)
@CLRF(FLG_DKFD_DOSEI_ST1_APPEAR)
@SETF(FLG_SUMS_STOIC_RESERVED)
@SETF(FLG_STEP_PAST)

_SCENE_FLG66;			;
@CMP(66,2)
@FALSE_GOTO(_DBGFLG_END)
@CLRF(FLG_STEP_PAST)
@SETF(FLG_WIN_GIEGU)
@SETF(FLG_ONET_LARDNA_APPEAR)
@SETF(FLG_FOUR_MONOTOLY_APPEAR)
@SETF(FLG_ONET_DAYBREAK)
@CLRF(FLG_ONET_DOOR_CLOSE)
@SETF(FLG_DOSEI_PU_BOX_APPEAR)
@SETF(FLG_ONET_MIZUNO_DOOR_OPEN)
@SETF(FLG_MYHOME_LIGHT_ON)
@SETF(FLG_RAMA_PU_APPEAR)

_SCENE_FLG67;			;
@CMP(67,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_TWSN_POLA_APPEAR)
@SETF(FLG_ITEM_LETTER_1)
@SETF(FLG_ITEM_LETTER_2)
@SETF(FLG_ITEM_LETTER_3)
@SETF(FLG_GUMI_OLDMAN_END)
@SETF(FLG_MYHOME_TRACY_FINAL)
@SETF(FLG_ONET_MYHOME_END_MAMA)
@SETF(FLG_PHONE_PAPA_FINAL)
@SETF(FLG_PHONE_PIZZA_FINAL)
@SETF(FLG_PHONE_ESCARGO_FINAL)
@SETF(FLG_MYHOME_TRACY_FINAL)

_SCENE_FLG68;			;
@CMP(68,2)
@FALSE_GOTO(_DBGFLG_END)
@SETF(FLG_MYHOME_TO_BE)
()

_DBGFLG_END;
@!
_DBG_EVENT_START;
ÅüÇrÇtÇsÇvÅ@ÇmÇôÇtÇrÇôÇjÇrÇsÅ´
Å@Å@@INPUT(2)
Å©
@ONGOTO(_DEVT_01,_DEVT_02,_DEVT_03,_DEVT_04,_DEVT_05,_DEVT_06,_DEVT_07,_DEVT_08,_DEVT_09,_DEVT_10,_DEVT_11,_DEVT_12,_DEVT_13,_DEVT_14,_DEVT_15,_DEVT_16,_DEVT_17,_DEVT_18,_DEVT_19,_DEVT_20,_DEVT_21,_DEVT_22,_DEVT_23,_DEVT_24,_DEVT_25,_DEVT_26,_DEVT_27,_DEVT_28,_DEVT_29,_DEVT_30,_DEVT_31,_DEVT_32,_DEVT_33,_DEVT_34,_DEVT_35,_DEVT_36,_DEVT_37,_DEVT_38,_DEVT_39,_DEVT_40,_DEVT_41,_DEVT_42,_DEVT_43,_DEVT_44,_DEVT_45,_DEVT_46,_DEVT_47,_DEVT_48,_DEVT_49,_DEVT_50,_DEVT_51,_DEVT_52,_DEVT_53,_DEVT_54,_DEVT_55,_DEVT_56,_DEVT_57,_DEVT_58,_DEVT_59,_DEVT_60,_DEVT_61,_DEVT_62,_DEVT_63,_DEVT_64,_DEVT_65,_DEVT_66,_DEVT_67,_DEVT_68,_DEVT_69,_DEVT_70)
ÅüÇxÇlÇlÇrÇsÅD
@GOTO(MSG_DEBUG_00)


_DEVT_01;
Å@ÇhÇaÇmÇsÅ´
Å@ÇaÇmÇaÅ|ÇmÇvÇmÇjÇlÇmÇrÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(10)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_POKEY)
@ADD_PARTY(PC_MYHOMEDOG)
@WARP(WARP_DBGEVT_01)
@!


_DEVT_02;
Å@ÇhÇaÇmÇsÅ´
Å@ÇaÇmÇaÅ|ÇmÇmÇrÇhÇf
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(11)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_POKEY)
@ADD_PARTY(PC_PICKEY)
@WARP(WARP_DBGEVT_02)
@!

_DEVT_03;
Å@ÇhÇaÇmÇsÅ´
Å@ÇjÇhÇjÇmÇTÇmÇmÇmÇjÅ´
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(13)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_WIN_GIAN_BOSS)
@SETF(FLG_POWR_GIAN)
@SETF(FLG_POLICE_STRONG_DISAPPEAR)
@SETF(FLG_POLICE_STRONG_B_APPEAR)
@SETF(FLG_POLICE_KANBANCOP_APPEAR)
@WARP(WARP_DBGEVT_03)
@!

_DEVT_04;
Å@ÇhÇaÇmÇsÅ´
Å@ÇxÇtÇqÇhÇaÇr
;Å@ÉXÉäÅ[ÉNÇ¢Ç´ÇÃÉoÉXÅ´
;Å@Ç∆Ç¢ÇÎÇ¢ÇÎÇ◊ÇÒÇË
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(14)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_TLPT_TWSN)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_BICYCLE)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_BOOK_CHAT)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_NOSE_PIG)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_ESCAPE_MOUSE)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_TOWN_MAP)
;@GOODSIN_PLAYER(PC_NESS,)
@SETF(FLG_ITEM_ESCAPE_MOUSE)
@WARP(WARP_DEBUG_TWSN)
@!

_DEVT_05;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇmÇyÇqÇrÇsÅ|ÇyÅ´
Å@ÅiÇjÇnÇrÇfÇjÇyÇôÇtÅj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(22)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_TWSN_ITEM_TONCHIKI)
@SETF(FLG_ITEM_TICKET)
@SETF(FLG_TWSN_FIELD_TONZ_DISAPPEAR)
@SETF(FLG_TWSN_MICHIKO_APPEAR)
@WARP(WARP_DBGEVT_05)
@!

_DEVT_06;
Å@ÇhÇaÇmÇsÅ´
Å@ÇjÅ|ÇoÇhÇmÇsÅ|ÇmÅ´
Å@ÇjÇlÇmÇqÇvÅ@ÇnÇsÇrÇqÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(20)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_HAPPY_SWITCH)
@WARP(WARP_DBGEVT_06)
@!

_DEVT_07;
Å@ÇhÇaÇmÇsÅ´
Å@ÇoÅ|ÇqÇmÇjÇôÇtÇrÇôÇsÅ´
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(21)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_WIN_CARPAINTER)
@CLRF(FLG_HAPPY_SWITCH)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_KEY_PRISON)
@WARP(WARP_DBGEVT_07)
@!

_DEVT_08;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇmÇyÇqÇjÇhÇgÇtÅ´
Å@ÅiÇjÇnÇrÇfÇjÇyÇôÇtÅj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(22)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_SATSUTABA)
@SETF(FLG_TWSN_CHAOS_STAGE_START)
@WARP(WARP_DBGEVT_08)
@!

_DEVT_09;
Å@ÇhÇaÇmÇsÅ´
Å@ÇyÇmÇaÇmÇsÇjÇlÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(23)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
@ADD_PARTY(PC_PAULA)
@WARP(WARP_DBGEVT_09)
@!

_DEVT_10;
Å@ÇhÇaÇmÇsÅ´
Å@ÇaÇqÅ|ÇmÇlÇmÇjÅ|ÇmÅ´
Å@ÇjÇtÇsÇôÇtÇxÇtÇdÇh
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(30)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@DEL_PARTY(PC_NESS)
@SETF(FLG_ITEM_BUBBLE_GUM)
@GOODSIN_PLAYER(PC_JEFF,GDS_FOOD_BUBBLE_GUM)
@WARP(WARP_DBGEVT_10)
@!

_DEVT_11;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇrÇjÇmÇsÇîÇrÅ|
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(31)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@DEL_PARTY(PC_NESS)
@ADD_PARTY(PC_BALLOONMONKEY)
@GOODSIN_PLAYER(PC_JEFF,GDS_FOOD_BUBBLE_GUM)
@SETF(FLG_WINS_TASSI_ENTER)
@SETF(FLG_WINS_JEFF_REPAIR)
@WARP(WARP_WINS_TENT_TASSI)
@SET_HIT_RECT(1,HRECT_WINS_TASSI_OFF,MSG_WINS_TASSI_OFF);ÉeÉìÉgÇ©ÇÁâìÇ¥Ç©Ç¡ÇΩéû
@SET_HIT_RECT(2,HRECT_WINS_GUM,MSG_WINS_MONKEY_GUM);ì¸ÇËç]ÇÃìÀí[Ç…ì¸ÇÈÇ∆
@!

_DEVT_12;
Å@ÇhÇaÇmÇsÅ´
Å@Ç`ÇmÇcÅ|ÇmÇîÇsÇgÇjÇr
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(32)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@DEL_PARTY(PC_NESS)
@WARP(WARP_DBGEVT_12)
@!

_DEVT_13;
Å@ÇhÇaÇmÇsÅ´
Å@ÇaÅ|ÇmÇrÅEÇsÇmÇyÇqÇrÇsÅ|Çy
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(40)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DBGEVT_13)
@!

_DEVT_14;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇfÇsÇôÇmÇsÇtÇyÇôÇt
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(40)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_WIN_DSRT_BOSS_A)
@SETF(FLG_WIN_DSRT_BOSS_B)
@SETF(FLG_WIN_DSRT_BOSS_C)
@SETF(FLG_WIN_DSRT_BOSS_D)
@SETF(FLG_WIN_DSRT_BOSS_E)
@SETF(FLG_WIN_DSRT_BOSS)
@CLRF(FLG_DSRT_SYOZI_DUNGEON_APPEAR)
@SETF(FLG_DSRT_DUNGEON_OK)
@SETF(FLG_DSRT_YUMBO_SHIGE_APPEAR)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DBGEVT_14)
@!

_DEVT_15;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇmÇyÇqÇrÇhÇfÇmÇrÇsÅ|Çy
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(41)
@GOSUB(MSG_SUB_PREEVENT)
@CLRF(FLG_FOUR_TONZURA_FREE)
@CLRF(FLG_FOUR_TONZURA_THANKS)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_DIAMOND)
@WARP(WARP_DBGEVT_15)
@!

_DEVT_16;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇmÇsÇqÅ|
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_FOUR_MAID_THANKS)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DBGEVT_16)
@!

_DEVT_17;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇmÇyÇqÇaÇrÅ´
Å@ÅiÇeÇèÅ|ÇrÇhÇcÅj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_FOUR_TONZURABUS_APPEAR)
@SETF(FLG_FOUR_MAID_THANKS)
@SETF(FLG_FOUR_OK)
@ADD_PARTY(PC_JEFF)
@ADD_PARTY(PC_PAULA)
@WARP(WARP_DBGEVT_17)
@!

_DEVT_18;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇjÇhÇtÇèÅ|ÇjÅ|ÇQ
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(44)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_THRK_FIXED_SKYW_APPEAR)
@ADD_PARTY(PC_JEFF)
@ADD_PARTY(PC_PAULA)
@WARP(WARP_DBGEVT_18)
@!

_DEVT_19;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇlÅ|ÇyÇmÇlÇyÇîÇjÇjÅ|Çj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(44)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_SYS_PHONE_STOIC)
@SETF(FLG_SUMS_STOIC_WIFE_DISAPPEAR)
@SETF(FLG_SUMS_MASSAGE_APPEAR)
@ADD_PARTY(PC_JEFF)
@ADD_PARTY(PC_PAULA)
@WARP(WARP_DBGEVT_19)
@!

_DEVT_20;
Å@ÇhÇaÇmÇsÅ´
Å@ÇoÅ|Å@ÇlÇmÇrÇôÇfÇôÇt
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(50)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_POO)
@DEL_PARTY(PC_NESS)
@SET_HIT_RECT(1,HRECT_RAMA_MU_A,MSG_EVT_79_MU)
@WARP(WARP_DBGEVT_20)
@!

_DEVT_21;
Å@ÇhÇaÇmÇsÅ´
Å@ÇaÅ|ÇmÇrÇrÇsÅ|ÇyÇrÇmÇQ
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(50)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_RAMA_MASTER)
@SETF(FLG_RAMA_OK)
@SETF(FLG_PU)
@SETF(FLG_FOUR_KOMORITA)
@SETF(FLG_SEBASTIAN_DISAPPEAR)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_21)
@!

_DEVT_22;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇîÇrÅ|ÇrÇmÇQ
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(51)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_22)
@!

_DEVT_23;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇsÅ|ÇmÇgÇmÇy
;Å@ÅiÇµÇ„Ç§ÇπÇ¢ÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(51)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_WINS_STONE_TACO_DISAPPEAR)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_23)
@!

_DEVT_24;
Å@ÇhÇaÇmÇsÅ´
Å@ÇtÇlÇmÇjÇtÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(52)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_24)
@!

_DEVT_25;
Å@ÇhÇaÇmÇsÅ´
Å@ÇfÇlÇsÇfÇlÇcÇqÇ`Çm
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(61)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DEBUG_DKFD)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_KEY_GUMIDORIAN)
@!

_DEVT_26;
Å@ÇhÇaÇmÇsÅ´
Å@ÇoÇqÇlÇîÇcÇmÇnÇcÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(52)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_26)
@!

_DEVT_27;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇaÇlÇqÇm
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(54)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@SETF(FLG_SKRB_BRICKROAD_MAKYO_APPEAR)
@WARP(WARP_DBGEVT_27)
@!

_DEVT_28;
Å@ÇhÇaÇmÇsÅ´
Å@ÇgÇjÇqÇfÇj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(60)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_WIN_LUMI_BOSS)
@WARP(WARP_DBGEVT_28)
@!

_DEVT_29;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇrÇtÇmÇc
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(61)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_WIN_FIRE_BOSS)
@WARP(WARP_DBGEVT_29)
@!

_DEVT_30;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇoÅ|ÇrÇsÇmÇmÇqÇPÅEÇT
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(63)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_30)
@!

_DEVT_31;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇoÅ|ÇrÇsÇmÇmÇqÇQÇsÇR
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(63)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_ITEM_XYZ)
@SETF(FLG_XYZ_OK)
@SETF(FLG_SPACETUNNEL2_START)
@SETF(FLG_DKFD_DOSEI_ST1_APPEAR)
@WARP(WARP_DBGEVT_30)
@!

_DEVT_32;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇqÇcÇmÇyÇôÇm
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
;@GOSUB(_DBG_GOODSEMPTY_ALL)
;@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_CASHCARD)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_SKIP_SAND)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_LUNCH)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_HAMBURGER)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_HAMBURGER)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_HAMBURGER_DOUBLE)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_PIZZA)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_PIZZA)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_PIZZA_LARGE)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_WET_TOWEL)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_DRINK_ADULT)
@GOODSIN_PLAYER(PC_NESS,GDS_FOOD_EGG_RAW)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_MONOSASHI)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_KEY_TAKOKESHI)
@SETF(FLG_FOUR_MAID_APPEAR)
@SETF(FLG_DSRT_TJAB_MOVE)
@WARP(WARP_DBGEVT_32)
@!

_DEVT_33;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇaÇqÇrÇqÇtÇyÇmÅ@ÇrÇhÇsÇhÇjÇj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_INFO_XYZ)
@SETF(FLG_DKFD_DOSEI_ST1_APPEAR)
@SET_HIT_RECT(1,HRECT_DKFD_ST3_A,MSG_DKFD_HRECT_ST3_A)
@SET_HIT_RECT(2,HRECT_MABOROSHI_2,MSG_DKFD_OLDMAN)
@WARP(WARP_DBGEVT_33)
@!

_DEVT_34;
Å@ÇhÇaÇmÇsÅ´
Å@ÇoÅ|ÇqÇmÇnÇxÇy
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(14)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_TLPT_TWSN)
@WARP(WARP_DBGEVT_34)
@!

_DEVT_35;
Å@ÇhÇaÇmÇsÅ´
Å@Ç`ÇîÇoÇqÇjÇîÇc
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(14)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_TLPT_TWSN)
@GOODSIN_PLAYER(PC_NESS,90)
@WARP(WARP_DBGEVT_35)
@!

_DEVT_36;
Å@ÇhÇaÇmÇsÅ´
Å@ÇhÇmÇsÇîÇjÅ|ÇeÇcÇtÇrÇm
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(12)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_GOT_CAPEESTATE)
@WARP(WARP_DBGEVT_36)
@!

_DEVT_37;
Å@ÇhÇaÇmÇsÅ´
Å@ÇnÇmÇîÇsÇmÇsÇhÇqÇnÇsÇj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(12)
@GOSUB(MSG_SUB_PREEVENT)
@WARP(WARP_DBGEVT_37)
@!

_DEVT_38;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇaÇqÇrÇqÇtÇyÇmÅ@ÇoÇqÇlÇîÇc
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(52)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_TLPT_SKRB)
@SET_HIT_RECT(1,HRECT_SKRB_MABOROSHI,MSG_EVT_88_MABOROSHI)
@GOODSIN_PLAYER(PC_POO,GDS_TOOL_EAGLE_EYE)
@WARP(WARP_DBGEVT_38)
@!

_DEVT_39;
Å@ÇhÇaÇmÇsÅ´
Å@ÇdÇcÇmÇmÇtÇl
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(62)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_MGKT_BACK_FIRE)
@WARP(WARP_DBGEVT_39)
@!

_DEVT_40;
Å@ÇhÇaÇmÇsÅ´
Å@ÇjÅ|ÇoÇhÇmÇsÅ|ÇrÇmÅ´
Å@ÇgÇmÇsÇtÇmÇsÇsÇjÇh
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(21)
@GOSUB(MSG_SUB_PREEVENT)
@GOODSIN_PLAYER(PC_NESS,1)
@WARP(WARP_DBGEVT_06)
@!

_DEVT_41;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇmÇsÇjÇrÇr
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(41)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_FOUR_DEPT_OK)
@SETF(FLG_FOUR_TONCHIKI_APPEAR)
@ADD_PARTY(PC_JEFF)
@GOODSIN_PLAYER(PC_NESS,90)
@WARP(WARP_DBGEVT_41)
@!

_DEVT_42;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇhÇcÇsÇfÇqÇlÇcÇtÇe
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_ICHIGO_TOFU)
@WARP(WARP_DBGEVT_42)
@!

_DEVT_43;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇmÇhÇqÇaÇmÇmÇmÇjÇv
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(50)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_BANANA_SIGNED)
@SETF(FLG_RAMA_MASTER)
@SETF(FLG_RAMA_OK)
@SETF(FLG_PU)
@SETF(FLG_FOUR_KOMORITA)
@SETF(FLG_ITEM_BANANA)
@WARP(WARP_DBGEVT_43)
@!

_DEVT_44;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇjÇôÇtÇmÇsÇjÇmÇl
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(53)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_EAGLE_EYE)
@SETF(FLG_TLPT_MAKY)
@WARP(WARP_DBGEVT_44)
@!

_DEVT_45;
Å@ÇhÇaÇmÇsÅ´
Å@ÇfÇqÇlÇcÇtÇeÇmÇgÇhÇsÇs
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(42)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_FOUR_MAID_APPEAR)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_FOUR_BRGS_WAREHOUSE)
@!

_DEVT_46;
;Å@ÉCÉxÉìÉgÅ´
;Å@Ç≥Ç≠Ç∂ÇÂÇµÇ‹ÇµÇΩ
;Å@ÇµÇ·ÇµÇÒÇ‚ÅiÉtÉâÉìÉNÇ÷ÇÒÅj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(12)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_WIN_FRANK)
@SETF(FLG_TEMP_1)
@SET_HIT_RECT(2,HRECT_PHOTO_2_FRANK,MSG_GLOBAL_PHOTO_2)
@WARP(WARP_DBGEVT_46)
@!

_DEVT_47;
Å@ÇhÇaÇmÇsÅ´
Å@ÇyÇÖÇeÇcÇîÇrÇt
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(30)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@DEL_PARTY(PC_NESS)
@ADD_PARTY(PC_TONY)
@SETF(FLG_TLPT_WINS)
@SETF(FLG_WINS_TONY)
@SETF(FLG_ITEM_GAUS)
@SETF(FLG_WINS_START)
@GOODSIN_PLAYER(PC_JEFF,GDS_TOOL_KEY_CHOTTO)
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_GUN_BANBAN)
@GOODSIN_PLAYER(PC_JEFF,GDS_EQUIP_CAP_HOLMES)
@WARP(WARP_DBGEVT_47)
@!

_DEVT_48;
Å@ÇhÇaÇmÇsÅ´
Å@ÇgÇhÇsÇsÇjÇmÇjÇh
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(51)
@GOSUB(MSG_SUB_PREEVENT)
@SETF(FLG_SYS_PHONE_MYHOME2)
@SETF(FLG_SYS_PHONE_PIZZA)
@GOSUB(_SUB_PCALL)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_SIGNBOARD_PAWNSHOP)
@WARP(WARP_DBGEVT_09)
@!

_DEVT_49;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇôÇfÇl
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(60)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_TLPT_GUMI)
@SETF(FLG_GUMI_INFO_MUKUCHI)
@SETF(FLG_LIBRARY_INFO_MUKUCHI)
@SETF(FLG_ITEM_MUKUCHI)
@SETF(FLG_GUMI_USEBOOK)
@SETF(FLG_GUMI_7_BOOK)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_BOOK_CHAT)
@WARP(WARP_DEBUG_GUMI)
@!

_DEVT_50;
Å@ÇhÇaÇmÇsÅ´
Å@ÇjÅ|ÇgÅ|ÇcÇrÇh
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(35)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DBGEVT_30)
@!

_DEVT_51;
Å@ÇhÇaÇmÇsÅ´
Å@ÇyÇÖÇeÇmÇxÇmÇa
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(60)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@GOODSIN_PLAYER(PC_JEFF,GDS_HAVE_BROKEN_GADGET)
@GOODSIN_PLAYER(PC_JEFF,GDS_HAVE_BROKEN_MECHANISM)
@GOODSIN_PLAYER(PC_JEFF,GDS_HAVE_BROKEN_AIRGUN)
@GOODSIN_PLAYER(PC_JEFF,GDS_HAVE_BROKEN_SPRAY)
@GOODSIN_PLAYER(PC_JEFF,GDS_TOOL_SPRAY_DEFENCE)
@WARP(WARP_DBGEVT_25)
@!

_DEVT_52;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇrÇôÇtÇrÇmÇsÇt
@KEYNP()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@GOSUB(_SUB_DBG_WEAPON)
@SET_LEVEL(PC_NESS,90)
@SET_LEVEL(PC_PAULA,70)
@SET_LEVEL(PC_JEFF,70)
@SET_LEVEL(PC_POO,65)
@WARP(WARP_PAST_RETURN)
@!


_DEVT_53;
Å@ÇhÇaÇmÇsÅ´
Å@ÇyÇmÇaÇgÇhÇgÇh
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(33)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@SETF(FLG_WIN_MATENT)
@CLRF(FLG_THRK_MATENT_APPEAR)
@SETF(FLG_ITEM_HAEMITU)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_ZOMBI_HOIHOI)
@WARP(WARP_DEBUG_THRK)
@!
_DEVT_54;
Å@ÇhÇaÇmÇsÅ´
Å@ÇlÇsÇmÇs
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(33)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DEBUG_THRK)
@!

_DEVT_55;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇsÇhÇsÇhÇqÇjÇmÇnÇsÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(61)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@WARP(WARP_DBGEVT_55)
@!

_DEVT_56;
Å@ÇhÇaÇmÇsÅ´
Å@ÇsÇqÇoÅ|ÇsÇyÇqÅ´
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(43)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@SETF(FLG_ITEM_TOFU)
@SETF(FLG_DSRT_TSARU_DISAPPEAR)
@SETF(FLG_DSRT_TSARU_A_APPEAR)
@WARP(WARP_DBGEVT_32)
@!

_DEVT_57;
Å@ÇhÇaÇmÇsÅ´
Å@ÇcÇmÇyÇôÇmÇlÇm
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(53)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@SETF(FLG_BRICKROAD)
@WARP(WARP_SKRB_DMAN_BODY)
@SET_HIT_RECT(1,HRECT_SKRB_DM_HAMARI,MSG_EVT_90_DM_HAMARI)
@!

_DEVT_58;
Å@ÇhÇaÇmÇsÅ´
Å@ÇoÅ|ÇqÇrÇqÇvÇqÇq
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(41)
@GOSUB(MSG_SUB_PREEVENT)
@GOODSIN_PLAYER(PC_PAULA,GDS_TOOL_KEY_TAKOKESHI)
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@WARP(WARP_DBGEVT_58)
@SET_HIT_RECT(1,HRECT_FOUR_DEPT_2,MSG_EVT_71_SET_HRECT_1)
@!

_DEVT_59;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇPÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_1_NES_MAMA)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_60;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇQÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_2_TONZURA)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_61;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇRÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_3_PAULA_PAPA)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_62;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇSÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_4_TONY)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_63;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇTÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_5_RAMA)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_64;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇUÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_6_FRANK)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_65;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇhÇfÇmÇhÇmÇqÇrÇmÇVÅ´
;Å@ÅiÉeÉXÉgÇøÇ„Ç§Åj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(65)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_STEP_PAST)
@GOSUB(MSG_EVT_PRAY_7_DOSEI)
@FRESH_PLAYER(PC_ALL)
@!

_DEVT_66;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇjÇhÇtÇèÅ|ÇjÅ|ÇR
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(44)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_JEFF)
@ADD_PARTY(PC_PAULA)
@SETF(FLG_POWR_RAIN)
@CLRF(FLG_WINS_SKYW_DISAPPEAR)
@WARP(WARP_DBGEVT_12)
@!

_DEVT_67;
Å@ÇhÇaÇmÇsÅ´
Å@ÇgÇjÇaÇsÇjÇm
;Å@Ç‡Ç¨ÇËÇ™Ç©ÇË
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(50)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(_SUB_PCALL)
@SETF(FLG_RAMA_MASTER)
@SETF(FLG_RAMA_OK)
@SETF(FLG_PU)
@WARP(WARP_DEBUG_SUMS)
@!

_DEVT_68;
Å@ÇhÇaÇmÇsÅ´
Å@ÇrÇsÅ|ÇlÇmÇmÇlÇrÇj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(11)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_POKEY)
@ADD_PARTY(PC_PICKEY)
@WARP(WARP_DBGEVT_01)
@SET_HIT_RECT(1,HRECT_INSEKI_STARMAN,MSG_INSEKI_STARMAN)
@!

_DEVT_69;
Å@ÇhÇaÇmÇsÅ´
Å@ÇRÇgÇsÇcÇj
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(11)
@GOSUB(MSG_SUB_PREEVENT)
@GOSUB(MSG_EVT_TO_BE_CONTINUED)
@!

_DEVT_70;
Å@ÇhÇaÇmÇsÅ´
Å@ÇfÅ|ÇfÇvÇsÇnÇrÇsÇ`Çs
@KEYNP()
@CLOSEALL()
@SET_LOOPREG(66)
@GOSUB(MSG_SUB_PREEVENT)
@ADD_PARTY(PC_PAULA)
@WARP(WARP_DOSE_RETURN)
@!

MSG_SUB_PREEVENT;
@FUNC(15)
@GOSUB(MSG_DEBUG_FLG)
@GOSUB(MSG_SUB_PARTY_ONLYNESS)
@SETF(FLG_SYS_MONSTER_OFF)
@GOSUB(_DBG_GOODSEMPTY_ALL)
@GOODSIN_PLAYER(PC_NESS,GDS_TOOL_CASHCARD)
@MONEYIN(1000)
@!

MSG_SUB_PARTY_ONLYNESS;
@ADD_PARTY(PC_NESS)
@GOSUB(MSG_SUB_ZENKAI)
_ONLYNESS_LOOP;
@GET_ORDER_PLAYER(2)
@FALSE_GOTO(_ONLYNESS_END)
@XCHG()
@DEL_PARTY(0)
@GOTO(_ONLYNESS_LOOP)
_ONLYNESS_END;
@!

_SUB_PCALL;
@ADD_PARTY(PC_PAULA)
@ADD_PARTY(PC_JEFF)
@ADD_PARTY(PC_POO)
@!

;
;#55	É]ÉìÉrÉzÉCÉzÉCégóp
;Å@ÅöÉ]ÉìÉrÉzÉCÉzÉCÇÃì¸éËÇ…å¿Ç¡Çƒê›íËÅB
;Å@Åö
;Å¶Ç¢Ç¬î≠ê∂Ç≥ÇπÇÈÅHÅiÇ∆ÇËÇ†Ç¶Ç∏ñÇÉeÉìÉgÇì|ÇµÇΩå„Ç©ÇÁÅAÇ…ÇµÇƒÇ¢Ç‹Ç∑Ç™Åj
;Å¶ÉOÉbÉYóìÇ¢Ç¡ÇœÇ¢ÇÃéûÇÃèàóù
;

MSG_DEBUG_EVENT_55;
MSG_DEBUG_SCENE_13;
@CHKFGOTO(FLG_PUT_ZOMBI_HOIHOI,_SCENE_END)
@OPEN(1)
@SETF(FLG_ITEM_HOIHOI)
;ÅüÉCÉxÉìÉgÇTÇTÅ´
;Å@ÉAÉbÉvÉãÉLÉbÉhÇ©ÇÁÅ´
;Å@Ç≈ÇÒÇÌÇ™Å@Ç©Ç©Ç¡ÇƒÇ´Ç‹Ç∑@KEY()Å´
;Å@ÉAÉbÉvÉãÉLÉbÉhÇ©ÇÁÅ´
;Å@É]ÉìÉrÉzÉCÉzÉCÇ™Å´
;Å@Ç®Ç≠ÇÁÇÍÇƒÇ´Ç‹Ç∑@KEY()Å´
;Å@ÅiÉCÉxÉìÉgÇπÇ¢Ç≥Ç≠ÇøÇ„Ç§ÅIÅj@KEYNP()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_EVENT_55_GOODSFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_ZOMBI_HOIHOI)
@CLOSE()
@!
_EVENT_55_GOODSFULL;
;ÅüÇ‡ÇøÇ‡ÇÃÇ™Å@Ç¢Ç¡ÇœÇ¢Ç»ÇÃÇ≈Å´
;Å@Ç»ÇÒÇ©Ç∑ÇƒÇƒÇ≠ÇæÇ≥Ç¢ÅBÅ´
;Å@ÅiÇŸÇÒÇŒÇÒÇÕÇ«Ç§Ç»ÇÈÇ©Ç”ÇﬂÇ¢Åj
_EVT_55_SEL_DROP;
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_EVT_55_SEL_DROP)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_EVT_55_DROP_NG)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@GOODSIN_PLAYER(0,GDS_TOOL_ZOMBI_HOIHOI)
@!

_EVT_55_DROP_NG;
Å©
;ÅüÇªÇÍÇÕÇ∑ÇƒÇÁÇÍÇ‹ÇπÇÒÅB@KEY()
@GOTO(_EVT_55_SEL_DROP)
_SCENE_END;
@!


MSG_DEBUG_ENTER_DUNGEONMAN;
@OPEN(1)
;ÅüÉ_ÉìÉWÉáÉìÇ®Ç∆Ç±ÇÃÅ´
;Å@Ç»Ç©Ç…Å@ÇÕÇ¢ÇËÇ‹Ç∑@KEY()Å´
;Å@ÅiÉCÉxÉìÉgÇπÇ¢Ç≥Ç≠ÇøÇ„Ç§ÅIÅj@KEYNP()
;@WARP(WARP_DEBUG_37_DMAN)
@CLOSE()
@!

_DBG_EXPL;
ÅüÇfÇîÇyÇhÇcÇvÇmÇôÇtÇqÇôÇjÅ´
Å@Å@Å@@INPUT(3)
@CLRLINE()
@FALSE_GOTO(MSG_DEBUG_00)
@XCHG()
Åü@DSP_GOODS(0)ÇmÅ´
Å@ÇrÇsÇlÇhÇcÇrÅD@KEY()@CLS()
@CMP(0,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_BOR)
@CMP(1,1)
@ONGOSUB(MSG_EXPL_GDS_FRANKLIN_BADGE)
@CMP(2,1)
@ONGOSUB(MSG_EXPL_GDS_NUIGURUMI)
@CMP(3,1)
@ONGOSUB(MSG_EXPL_GDS_NUIGURUMI_SUPER)
@CMP(4,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_GADGET)
@CMP(5,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_MECHANISM)
@CMP(6,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_AIRGUN)
@CMP(7,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_SPRAY)
@CMP(8,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_LASER)
@CMP(9,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_GARAKUTA)
@CMP(10,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_KINZOKUBO)
@CMP(11,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_BEAM)
@CMP(12,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_TSUTSU)
@CMP(13,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_BAZOOKA)
@CMP(14,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_RAPPA)
@CMP(15,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_TESUKZ)
@CMP(16,1)
@ONGOSUB(MSG_EXPL_GDS_BROKEN_PARABPLA)
@CMP(17,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_BOR)
@CMP(18,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_FUTSU)
@CMP(19,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_YOI)
@CMP(20,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_TOTEMO)
@CMP(21,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_MISTER)
@CMP(22,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_KOUKYU)
@CMP(23,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_SAIKO)
@CMP(24,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_MAGICANT)
@CMP(25,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_DENSETSU)
@CMP(26,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_GUTS)
@CMP(27,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_KARBURI)
@CMP(28,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN)
@CMP(29,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_ATSUME)
@CMP(30,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_YOI)
@CMP(31,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_CHEF)
@CMP(32,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_SUTEKI)
@CMP(33,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_FUSHIG)
@CMP(34,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_TENSHI)
@CMP(35,1)
@ONGOSUB(MSG_EXPL_GDS_SWORD_KING)
@CMP(36,1)
@ONGOSUB(MSG_EXPL_GDS_GUN_BANBAN)
@CMP(37,1)
@ONGOSUB(MSG_EXPL_GDS_GUN_SHOCK)
@CMP(38,1)
@ONGOSUB(MSG_EXPL_GDS_GUN_AIR)
@CMP(39,1)
@ONGOSUB(MSG_EXPL_GDS_GUN_AIR_SUPER)
@CMP(40,1)
@ONGOSUB(MSG_EXPL_GDS_GUN_DESTROYER)
@CMP(41,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_LASER)
@CMP(42,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_HYPER)
@CMP(43,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_CRASH)
@CMP(44,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_NIJIIRO)
@CMP(45,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_DEATH)
@CMP(46,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_SAIAKU)
@CMP(47,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_MOON)
@CMP(48,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_GAIA)
@CMP(49,1)
@ONGOSUB(MSG_EXPL_GDS_EQUIP_YOYO)
@CMP(50,1)
@ONGOSUB(MSG_EXPL_GDS_EQUIP_SLING)
@CMP(51,1)
@ONGOSUB(MSG_EXPL_GDS_EQUIP_SLING_SUPER)
@CMP(52,1)
@ONGOSUB(MSG_EXPL_GDS_EQUIP_YOYO_SUPER)
@CMP(53,1)
@ONGOSUB(MSG_EXPL_GDS_EQUIP_KILLER)
@CMP(54,1)
@ONGOSUB(MSG_EXPL_GDS_AMULET_ABI)
@CMP(55,1)
@ONGOSUB(MSG_EXPL_GDS_AMULET_OOKINA)
@CMP(56,1)
@ONGOSUB(MSG_EXPL_GDS_AMULET_KAGAYAKU)
@CMP(57,1)
@ONGOSUB(MSG_EXPL_GDS_AMULET_USAGI)
@CMP(58,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_HONOO)
@CMP(59,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_SHIZUKU)
@CMP(60,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_YAMI)
@CMP(61,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_UMI)
@CMP(62,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_HOSHI)
@CMP(63,1)
@ONGOSUB(MSG_EXPL_GDS_CLOAK_KING)
@CMP(64,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_YASUMONO)
@CMP(65,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_COPPER)
@CMP(66,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_SILVER)
@CMP(67,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_GOLD)
@CMP(68,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_PLATINUM)
@CMP(69,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_DIAMOND)
@CMP(70,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_YOUSEI)
@CMP(71,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_ENSHI)
@CMP(72,1)
@ONGOSUB(MSG_EXPL_GDS_BLACELET_MEGAMI)
@CMP(73,1)
@ONGOSUB(MSG_EXPL_GDS_BRACERET_KING)
@CMP(74,1)
@ONGOSUB(MSG_EXPL_GDS_CAP_YAKYU)
@CMP(75,1)
@ONGOSUB(MSG_EXPL_GDS_CAP_HOLMS)
@CMP(76,1)
@ONGOSUB(MSG_EXPL_GDS_CAP_MISTER)
@CMP(77,1)
@ONGOSUB(MSG_EXPL_GDS_CAP_NANIRO)
@CMP(78,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON)
@CMP(79,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_RED)
@CMP(80,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_MEGAMI)
@CMP(81,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_YASURAGI)
@CMP(82,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_MAORI)
@CMP(83,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_MAYOKE)
@CMP(84,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_MAFUJI)
@CMP(85,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_KAGAYAKI)
@CMP(86,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_CHISAN)
@CMP(87,1)
@ONGOSUB(MSG_EXPL_GDS_BANDANNA_KING)
@CMP(88,1)
@ONGOSUB(MSG_EXPL_GDS_COOKIE)
@CMP(89,1)
@ONGOSUB(MSG_EXPL_GDS_POTATO_FRIED)
@CMP(90,1)
@ONGOSUB(MSG_EXPL_GDS_HAMBURGER)
@CMP(91,1)
@ONGOSUB(MSG_EXPL_GDS_EGG_BOILD)
@CMP(92,1)
@ONGOSUB(MSG_EXPL_GDS_EGG_RAW)
@CMP(93,1)
@ONGOSUB(MSG_EXPL_GDS_LUNCH)
@CMP(94,1)
@ONGOSUB(MSG_EXPL_GDS_PASTA_SUMMERS)
@CMP(95,1)
@ONGOSUB(MSG_EXPL_GDS_PIZZA)
@CMP(96,1)
@ONGOSUB(MSG_EXPL_GDS_VOUCHED_CHEF)
@CMP(97,1)
@ONGOSUB(MSG_EXPL_GDS_PIZZA_LARGE)
@CMP(98,1)
@ONGOSUB(MSG_EXPL_GDS_PSYCHO_CARAMEL)
@CMP(99,1)
@ONGOSUB(MSG_EXPL_GDS_MAGIC_TRUFFLE)
@CMP(100,1)
@ONGOSUB(MSG_EXPL_GDS_LUNCH_KING)
@CMP(101,1)
@ONGOSUB(MSG_EXPL_GDS_MYSTIC_ANDY)
@CMP(102,1)
@ONGOSUB(MSG_EXPL_GDS_BREAD_UGLY)
@CMP(103,1)
@ONGOSUB(MSG_EXPL_GDS_BREAD)
@CMP(104,1)
@ONGOSUB(MSG_EXPL_GDS_BUBBLE_GUM)
@CMP(105,1)
@ONGOSUB(MSG_EXPL_GDS_HAEMITSU)
@CMP(106,1)
@ONGOSUB(MSG_EXPL_GDS_JUICE_ORANGE)
@CMP(107,1)
@ONGOSUB(MSG_EXPL_GDS_ICE_TEA)
@CMP(108,1)
@ONGOSUB(MSG_EXPL_GDS_DRINK_ADULT)
@CMP(109,1)
@ONGOSUB(MSG_EXPL_GDS_SOUP_KRAKEN)
@CMP(110,1)
@ONGOSUB(MSG_EXPL_GDS_WATER)
@CMP(111,1)
@ONGOSUB(MSG_EXPL_GDS_COLD_PILL)
@CMP(112,1)
@ONGOSUB(MSG_EXPL_GDS_SERUM)
@CMP(113,1)
@ONGOSUB(MSG_EXPL_GDS_CAPSULE_IQ)
@CMP(114,1)
@ONGOSUB(MSG_EXPL_GDS_CAPSULE_GUTS)
@CMP(115,1)
@ONGOSUB(MSG_EXPL_GDS_CAPSULE_SPEED)
@CMP(116,1)
@ONGOSUB(MSG_EXPL_GDS_CAPSULE_VITAL)
@CMP(117,1)
@ONGOSUB(MSG_EXPL_GDS_CAPSULE_LUCK)
@CMP(118,1)
@ONGOSUB(MSG_EXPL_GDS_KETCHUP)
@CMP(119,1)
@ONGOSUB(MSG_EXPL_GDS_MUSTARD)
@CMP(120,1)
@ONGOSUB(MSG_EXPL_GDS_SOURCE)
@CMP(121,1)
@ONGOSUB(MSG_EXPL_GDS_SOY)
@CMP(122,1)
@ONGOSUB(MSG_EXPL_GDS_SHICHIMI)
@CMP(123,1)
@ONGOSUB(MSG_EXPL_GDS_TABASCO)
@CMP(124,1)
@ONGOSUB(MSG_EXPL_GDS_GOMASHIO)
@CMP(125,1)
@ONGOSUB(MSG_EXPL_GDS_BACKSTAGE_PASS)
@CMP(126,1)
@ONGOSUB(MSG_EXPL_GDS_TOPPING_KING)
@CMP(127,1)
@ONGOSUB(MSG_EXPL_GDS_WET_TOWEL)
@CMP(128,1)
@ONGOSUB(MSG_EXPL_GDS_ANGEL_SEED)
@CMP(129,1)
@ONGOSUB(MSG_EXPL_GDS_DIAMOND_CRASHER)
@CMP(130,1)
@ONGOSUB(MSG_EXPL_GDS_LIFE_HORN)
@CMP(131,1)
@ONGOSUB(MSG_EXPL_GDS_ANTI_PSI)
@CMP(132,1)
@ONGOSUB(MSG_EXPL_GDS_SHIELD_KILLER)
@CMP(133,1)
@ONGOSUB(MSG_EXPL_GDS_BAZOOKA)
@CMP(134,1)
@ONGOSUB(MSG_EXPL_GDS__BAZOOKA_SUPER)
@CMP(135,1)
@ONGOSUB(MSG_EXPL_GDS_SUCK)
@CMP(136,1)
@ONGOSUB(MSG_EXPL_GDS_SUCK_SUPER)
@CMP(137,1)
@ONGOSUB(MSG_EXPL_GDS_SPRAY_SUPER)
@CMP(138,1)
@ONGOSUB(MSG_EXPL_GDS_NEBANEBA_MACHINE)
@CMP(139,1)
@ONGOSUB(MSG_EXPL_GDS_TOOL_ICHIGO_TOFU)
@CMP(140,1)
@ONGOSUB(MSG_EXPL_GDS_MONSASHI)
@CMP(141,1)
@ONGOSUB(MSG_EXPL_GDS_SNAKE_BAG)
@CMP(142,1)
@ONGOSUB(MSG_EXPL_GDS_BANDAGE_MUMMY)
@CMP(143,1)
@ONGOSUB(MSG_EXPL_GDS_BUNDOKI)
@CMP(144,1)
@ONGOSUB(MSG_EXPL_GDS_PENCIL_ROCKET)
@CMP(145,1)
@ONGOSUB(MSG_EXPL_GDS_PENCIL_ROCKET5)
@CMP(146,1)
@ONGOSUB(MSG_EXPL_GDS_PENCIL_ROCKET20)
@CMP(147,1)
@ONGOSUB(MSG_EXPL_GDS_BOMB)
@CMP(148,1)
@ONGOSUB(MSG_EXPL_GDS_BOMB_SUPER)
@CMP(149,1)
@ONGOSUB(MSG_EXPL_GDS_SPRAY)
@CMP(150,1)
@ONGOSUB(MSG_EXPL_GDS_ORIGIN_RUST)
@CMP(151,1)
@ONGOSUB(MSG_EXPL_GDS_ORIGIN_RUST_SUPER)
@CMP(152,1)
@ONGOSUB(MSG_EXPL_GDS_SOCKS_STINK)
@CMP(153,1)
@ONGOSUB(MSG_EXPL_GDS_KUWAGT)
@CMP(154,1)
@ONGOSUB(MSG_EXPL_GDS_TOOTHBRUSH)
@CMP(155,1)
@ONGOSUB(MSG_EXPL_GDS_BELT_HANDBAG)
@CMP(156,1)
@ONGOSUB(MSG_EXPL_GDS_CURSE_PHARAOH)
@CMP(157,1)
@ONGOSUB(MSG_EXPL_GDS__SHOWER_DEFNCE)
@CMP(158,1)
@ONGOSUB(MSG_EXPL_GDS_LETTER_MAMA)
@CMP(159,1)
@ONGOSUB(MSG_EXPL_GDS_DOUBLE_GUTS)
@CMP(160,1)
@ONGOSUB(MSG_EXPL_GDS_DRAGON_POWDER)
@CMP(161,1)
@ONGOSUB(MSG_EXPL_GDS_SPRAY_DEFNCE)
@CMP(162,1)
@ONGOSUB(MSG_EXPL_GDS_NOSE_PIG)
@CMP(163,1)
@ONGOSUB(MSG_EXPL_GDS_SIGNBOARD_PAWNSHOP)
@CMP(164,1)
@ONGOSUB(MSG_EXPL_GDS_BOOK_CHAT)
@CMP(165,1)
@ONGOSUB(MSG_EXPL_GDS_POSTCARD)
@CMP(166,1)
@ONGOSUB(MSG_EXPL_GDS_DRY_MEAT_SPECIAL)
@CMP(167,1)
@ONGOSUB(MSG_EXPL_GDS_LETTER_TONY)
@CMP(168,1)
@ONGOSUB(MSG_EXPL_GDS_HIYOK)
@CMP(169,1)
@ONGOSUB(MSG_EXPL_GDS_NIWATORI)
@CMP(170,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_TABIGOYA)
@CMP(171,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_PRISON)
@CMP(172,1)
@ONGOSUB(MSG_EXPL_GDS_CHOTTO)
@CMP(173,1)
@ONGOSUB(MSG_EXPL_GDS_MONTLY)
@CMP(174,1)
@ONGOSUB(MSG_EXPL_GDS_ZOMBIE_HOIHOI)
@CMP(175,1)
@ONGOSUB(MSG_EXPL_GDS_EAGLE_EYE)
@CMP(176,1)
@ONGOSUB(MSG_EXPL_GDS_BICYCLE)
@CMP(177,1)
@ONGOSUB(MSG_EXPL_GDS_CASHCARD)
@CMP(178,1)
@ONGOSUB(MSG_EXPL_GDS_THEATER_TICKET)
@CMP(179,1)
@ONGOSUB(MSG_EXPL_GDS_LETTER_CHILD)
@CMP(180,1)
@ONGOSUB(MSG_EXPL_GDS_SATSUTABA)
@CMP(181,1)
@ONGOSUB(MSG_EXPL_GDS_PHONE_RECIVER)
@CMP(182,1)
@ONGOSUB(MSG_EXPL_GDS_DIAMOND)
@CMP(183,1)
@ONGOSUB(MSG_EXPL_GDS_BANN_SIGNED)
@CMP(184,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_TAKOKESHI)
@CMP(185,1)
@ONGOSUB(MSG_EXPL_GDS_HIEROGLYPH_COPY)
@CMP(186,1)
@ONGOSUB(MSG_EXPL_GDS_PRECIOUS_METAL_B)
@CMP(187,1)
@ONGOSUB(MSG_EXPL_GDS_CONTACT_LENS)
@CMP(188,1)
@ONGOSUB(MSG_EXPL_GDS_HAND_AID)
@CMP(189,1)
@ONGOSUB(MSG_EXPL_GDS_ICHIGO_TOFU)
@CMP(190,1)
@ONGOSUB(MSG_EXPL_GDS_BANN)
@CMP(191,1)
@ONGOSUB(MSG_EXPL_GDS_CALORIE_BLOCK)
@CMP(192,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_DUNGEONMAN)
@CMP(193,1)
@ONGOSUB(MSG_EXPL_GDS_OBJECT_XYZ)
@CMP(194,1)
@ONGOSUB(MSG_EXPL_GDS_PENDANT_DAICHI)
@CMP(195,1)
@ONGOSUB(MSG_EXPL_GDS_NEUTRALIZER)
@CMP(196,1)
@ONGOSUB(MSG_EXPL_GDS_SOUND_STONE)
@CMP(197,1)
@ONGOSUB(MSG_EXPL_GDS_ESCAPE_MOUSE)
@CMP(198,1)
@ONGOSUB(MSG_EXPL_GDS_ICE_CANDY)
@CMP(199,1)
@ONGOSUB(MSG_EXPL_GDS_SNAKE)
@CMP(200,1)
@ONGOSUB(MSG_EXPL_GDS_SNAKE_POISON)
@CMP(201,1)
@ONGOSUB(MSG_EXPL_GDS_FUUIN_STONE)
@CMP(202,1)
@ONGOSUB(MSG_EXPL_GDS_TOWN_MAP)
@CMP(203,1)
@ONGOSUB(MSG_EXPL_GDS_VIDEO_DRUG)
@CMP(204,1)
@ONGOSUB(MSG_EXPL_GDS_GREORE_MACHINE)
@CMP(205,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_LOCKER)
@CMP(206,1)
@ONGOSUB(MSG_EXPL_GDS_NOT_SO_GOOD)
@CMP(207,1)
@ONGOSUB(MSG_EXPL_GDS_MAGIC_TORTE)
@CMP(208,1)
@ONGOSUB(MSG_EXPL_GDS_TINY_RUBY)
@CMP(209,1)
@ONGOSUB(MSG_EXPL_GDS_MONKY_MIND)
@CMP(210,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_KOKESHIKESHI)
@CMP(211,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_GUMIDORIAN)
@CMP(212,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_GODZILLA)
@CMP(213,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_KOUKYU_E)
@CMP(214,1)
@ONGOSUB(MSG_EXPL_GDS_BAT_MAMMOTH)
@CMP(215,1)
@ONGOSUB(MSG_EXPL_GDS_BEAM_STRONG)
@CMP(216,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_PLATINUM_E)
@CMP(217,1)
@ONGOSUB(MSG_EXPL_GDS_BRACELET_DIAMOND)
@CMP(218,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_MAMORI)
@CMP(219,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_MAFUJI)
@CMP(220,1)
@ONGOSUB(MSG_EXPL_GDS_RIBBON_DOSEI)
@CMP(221,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_MIZUUMI)
@CMP(222,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_MAYOKE_E)
@CMP(223,1)
@ONGOSUB(MSG_EXPL_GDS_CUP_RAMEN)
@CMP(224,1)
@ONGOSUB(MSG_EXPL_GDS_SKIP_SAND)
@CMP(225,1)
@ONGOSUB(MSG_EXPL_GDS_SKIP_SAND_SP)
@CMP(226,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_A)
@CMP(227,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_B)
@CMP(228,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_C)
@CMP(229,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_D)
@CMP(230,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_E)
@CMP(231,1)
@ONGOSUB(MSG_EXPL_GDS_FOOD_LUCKY_SAND_F)
@CMP(232,1)
@ONGOSUB(MSG_EXPL_GDS_COFFEE)
@CMP(233,1)
@ONGOSUB(MSG_EXPL_GDS_HAMBURGER_DOUBLE)
@CMP(234,1)
@ONGOSUB(MSG_EXPL_GDS_CANDY_SOUR)
@CMP(235,1)
@ONGOSUB(MSG_EXPL_GDS_CANDY_BITTER)
@CMP(236,1)
@ONGOSUB(MSG_EXPL_GDS_OKAYU)
@CMP(237,1)
@ONGOSUB(MSG_EXPL_GDS_BEANS_CROQUETTE)
@CMP(238,1)
@ONGOSUB(MSG_EXPL_GDS_MOLOKHEIYA_SOUP)
@CMP(239,1)
@ONGOSUB(MSG_EXPL_GDS_GUMI_BREAD)
@CMP(240,1)
@ONGOSUB(MSG_EXPL_GDS_MUTTON_ON_SKEWERS)
@CMP(241,1)
@ONGOSUB(MSG_EXPL_GDS_GUMI_YOGURT)
@CMP(242,1)
@ONGOSUB(MSG_EXPL_GDS_DRY_MEAT)
@CMP(243,1)
@ONGOSUB(MSG_EXPL_GDS_HAMBURGER_MAMMOTH)
@CMP(244,1)
@ONGOSUB(MSG_EXPL_GDS_DRY_MEAT_GREAT)
@CMP(245,1)
@ONGOSUB(MSG_EXPL_GDS_DRY_MEAT_SP)
@CMP(246,1)
@ONGOSUB(MSG_EXPL_GDS_WATER_HI)
@CMP(247,1)
@ONGOSUB(MSG_EXPL_GDS_MAGIC_PUDDING)
@CMP(248,1)
@ONGOSUB(MSG_EXPL_GDS_FLYPAN_OOKINA)
@CMP(249,1)
@ONGOSUB(MSG_EXPL_GDS_COIN_DOSEI)
@CMP(250,1)
@ONGOSUB(MSG_EXPL_GDS_PRECIOUS_METAL)
@CMP(251,1)
@ONGOSUB(MSG_EXPL_GDS_ICE_CANDY_E)
@CMP(252,1)
@ONGOSUB(MSG_EXPL_GDS_LIFE_HORN_E)
@CMP(253,1)
@ONGOSUB(MSG_EXPL_GDS_KEY_CARROT)
Å´
@CMP(254,1)
@FALSE_GOTO(_DBG_EXPL)
ÅüÇfÇîÇyÇmÇrÇhÇcÇhÇsÇgÅ´
Å@@DSP_NUM(253)ÇcÇrÅD@KEY()
@GOTO(_DBG_EXPL)
