;---------------------------------------------


;#25	スリーク行のバスに乗る	2.8	T

;★バス停に到着したバスに（手前側から）近寄ると、
;窓から運転手が顔を出して（顔だけのオブジェ有り）
;MSG_TWSN_BUSDRIVER を発行。

;★_TWSN_BUSDRIVER_YES 、_TWSN_BUSDRIVER_LATER_YES の後で
;プレイヤーパーティーを消してバス出発。

MSG_EVT_BUS_START;
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TO_THRK)
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SETF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_basu)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

MSG_EVT_RIDE_BUS_TWSN_THRK;バスに近付くと呼ばれるメッセージ
MSG_TWSN_BUSDRIVER;
;バスの運転手
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
@CHKFGOTO(FLG_WIN_GEPPU,_TWSN_BUSDRIVER_LATER)
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｙｅｐ，　ｔｈｉｓ　ｉｓ　ｔｈｅ　ｂｕｓ　ｔｏ　Ｔｈｒｅｅｄ，@KEY()↓
◆ｂｕｔ，．．．Ｉ’ｍ　ｎｏｔ　ｓｕｒｅ　ｉｆ　ｗｅ　ｃａｎ　ｇｅｔ　ｔｈｅｒｅ　ｏｒ　ｎｏｔ．@KEY()↓
◆Ｔｈｅ　ｆａｒｅ　ｉｓ　＄@DSP_NUM(0)．@KEY()↓
◆．．．ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆スリークゆきのバスだども↓
;jpn:　いけるかどうかは　わがんねっす。↓
;jpn:　んでも　りょうきん@DSP_NUM(0)ドルす。@KEY()↓
;jpn:◆いぐか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@WINR_MONEY()
@SELGOTO(_TWSN_BUSDRIVER_YES,_TWSN_BUSDRIVER_NO)

_TWSN_BUSDRIVER_NO;
◆．．．Ｙｅｐ，　Ｉ　ｐｅｒｓｏｎａｌｌｙ　ｔｈｉｎｋ　ｉｔ’ｓ　ｂｅｔｔｅｒ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｇｏ．@KEY()↓
◆．．．Ｉ’ｍ　ａｌｓｏ　ｎｏｔ　ｒｅａｌ　ｃｏｎｆｉｄｅｎｔ　ａｂｏｕｔ　ｇｅｔｔｉｎｇ　ｔｈｅｒｅ．
;jpn:◆いがねぇほうが　いいだ。↓
;jpn:　おらも　じしんがねぇし。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
』

_TWSN_BUSDRIVER_YES;
@Q_MONEY(0)
@TRUE_GOTO(_TWSN_BUSDRIVER_NOMONEY)
@SE(SE_se76_my_give)
@WI(1)
@MONEYOUT(0)
@WINR_MONEY()
◆Ｏｋａｙ．　　Ｌｅｔ’ｓ　ｇｉｖｅ　ｉｔ　ａ　ｓｈｏｔ．@KEY()↓
◆．．．Ｉ　ｈａｖｅ　ａ　ｆｅｅｌｉｎｇ　ｔｈｉｓ　ｃｏｕｌｄ　ｇｅｔ　ｕｇｌｙ，　ｔｈｏｕｇｈ．
;jpn:◆じゃ　いってみるべ。↓
;jpn:　おっがねぇけどもな。
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@GOTO(MSG_EVT_BUS_START)

_TWSN_BUSDRIVER_NOMONEY;
◆．．．Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｏｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ．
;jpn:◆かね　はらえねぇんじゃ↓
;jpn:　だめだべ。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
』

_TWSN_BUSDRIVER_LATER;
@MUL_ACTIVE_PLAYER(2)
@XCHG()
;jpn:◆このバスは　スリークをとおって↓
;jpn:　フォーサイドに　いぐけんども
;@KEY()↓
;@GOSUB(MSG_EVT_BUS_MES_B)		;メッセージのサブルーチンへ
◆．．．Ｔｈｉｓ　ｂｕｓ　ｇｏｅｓ　ｔｏ　Ｆｏｕｒｓｉｄｅ　ｖｉａ　Ｔｈｒｅｅｄ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｆａｒｅ，　Ｉ　ｃａｎ’ｔ　ｔａｋｅ　ｙｏｕ　ｔｈｅｒｅ．@KEY()↓
◆．．．Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆@DSP_NUM(0)ドルはらわねぇやつは↓
;jpn:　のせてやらねぇだよ。@KEY()↓
;jpn:◆いぐか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@WINR_MONEY()
@SELGOTO(_TWSN_BUSDRIVER_LATER_YES,_TWSN_BUSDRIVER_LATER_NO)

_TWSN_BUSDRIVER_LATER_NO;
◆．．．Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｙｏｕ　ｓｈｏｕｌｄ　ｓｔｒｏｌｌ　ａｒｏｕｎｄ．@KEY()↓
◆Ｂｅｓｉｄｅｓ，　ｗａｌｋｉｎｇ　ｉｓ　ｇｏｏｄ　ｆｏｒ　ｙｏｕ．．．
;jpn:◆かねが　ねぇんだったら↓
;jpn:　エッチラ　オッチラ↓
;jpn:　あるいていくが　いいだよ。@KEY()↓
;jpn:◆けんこうにも　いいし。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
』

_TWSN_BUSDRIVER_LATER_YES;
@Q_MONEY(0)
@TRUE_GOTO(_TWSN_BUSDRIVER_LATER_NOMONEY)
@SE(SE_se76_my_give)
@MONEYOUT(0)
@WINR_MONEY()
◆．．．Ｗｅｌｌ，　ｈｏｐ　ａｂｏａｒｄ　ｔｈｅｎ！
;jpn:◆んじゃ　いってみるべ！
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@GOTO(MSG_EVT_BUS_START)
;@FALSE_GOTO(MSG_EVT_BUS_START)
@!

_TWSN_BUSDRIVER_LATER_NOMONEY;
◆．．．Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｙｏｕ　ｓｈｏｕｌｄ　ｓｔｒｏｌｌ　ａｒｏｕｎｄ．@KEY()↓
◆Ｂｅｓｉｄｅｓ，　ｗａｌｋｉｎｇ　ｉｓ　ｇｏｏｄ　ｆｏｒ　ｙｏｕ．．．
;jpn:◆かねが　ねぇんだったら↓
;jpn:　エッチラ　オッチラ↓
;jpn:　あるいていくが　いいだよ。@KEY()↓
;jpn:◆けんこうにも　いいし。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
』

MSG_EVT_BUS_TO_THRK_TUNNEL;ツーソンからトンネルへ
@SETF(FLG_TUNNEL_TWSN_THRK_BR)
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TWSN_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TWSN_TUNNEL)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

MSG_EVT_BUS_RETURN_TWSN;トンネルからツーソンに戻された
@SET_CAMERA_PARTY()
;------
@BGM_EFFECT(5)
@WI(30)
;------
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_RETURN_TWSN,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_TWSN)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@CLRF(FLG_TUNNEL_TWSN_THRK_BR)
』

MSG_EVT_BUS_INTO_THRK;トンネルからスリークへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_INTO_THRK,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_THRK_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@CLRF(FLG_TUNNEL_TWSN_THRK_BR)
』

;スリークについた
MSG_EVT_TOUCH_THRK;
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_R,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆．．．Ｔｈｉｓ　ｂｕｓ　ｃｏｎｔｉｎｕｅｓ　ｏｎ　ｔｏ　Ｆｏｕｒｓｉｄｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｈｅｒｅ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆このバスは　フォーサイドまで↓
;jpn:　いぐけんども　ここでおりるか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THROUGH_THRK_TO_FOUR_YES,_THROUGH_THRK_TO_FOUR_NO)
_THROUGH_THRK_TO_FOUR_NO;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@COLD_GOM_CHAR(GOM_BUS)
@CLRF(FLG_WIN_GEPPU)		;バスが出ない様に
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_THRK_TO_DSRT);バス乗車
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

_THROUGH_THRK_TO_FOUR_YES;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_L,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_threek)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@CLRF(FLG_SYS_MONSTER_OFF)
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』

;ツーソンに戻ってきたバスはバス停まで戻ってきた
MSG_EVT_BUS_RETURN_TWSN_B;
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_L,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_twoson)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@CLRF(FLG_SYS_MONSTER_OFF)
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』

;ツーソンに戻ってきたバスがある位置についた
MSG_EVT_BUS_RETURN_TWSN_A;
MSG_TWSN_GHOSTTUNNEL;
;バスでスリークへ行けなかった
@OPEN(1)
◆（Ｆｏｒ　ｓｏｍｅ　ｒｅａｓｏｎ，　ｔｈｅ　ｂｕｓ　ｒｅｔｕｒｎｅｄ　ｔｏ　Ｔｗｏｓｏｎ．）
;jpn:◆（バスはなぜかツーソンに↓
;jpn:　もどってしまった）
@KEY()
@CLOSEALL()
@WI(30)
MSG_TWSN_GHOSTTUNNEL_BUSDRIVER;
←
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆．．．Ｙｅｐ！　　Ｊｕｓｔ　ｌｉｋｅ　Ｉ　ｔｈｏｕｇｈｔ．．．@KEY()↓
◆．．．Ｏｋａｙ，　Ｉ’ｍ　ｓｔａｒｔｉｎｇ　ｔｏ　ｇｅｔ　ｔｈｅ　ｃｒｅｅｐｓ．．．@KEY()↓
◆Ｗｅ’ｒｅ　ｇｏｉｎｇ　ｂａｃｋ　ｔｏ　ｔｈｅ　ｂｕｓ　ｓｔａｔｉｏｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｈｅｒｅ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆やっぱり　おらが↓
;jpn:　いったとおりだ。@KEY()↓
;jpn:◆‥‥おら　ぶきみわりぃだよ。@KEY()↓
;jpn:◆バスは　バスステーションまで↓
;jpn:　もどるけんども　ここでおりるか？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(MSG_EVT_BUS_RETURN_TWSN_A_YES,MSG_EVT_BUS_RETURN_TWSN_A_NO)

MSG_EVT_BUS_RETURN_TWSN_A_NO;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	　;運転手
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_RETURN_TWSN_B)
』
MSG_EVT_BUS_RETURN_TWSN_A_YES;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	　;運転手
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_L,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_twoson)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@CLRF(FLG_SYS_MONSTER_OFF)
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』


;	ツーソン行きのバス

MSG_EVT_RIDE_BUS_THRK_TWSN;
MSG_THRK_HIGHWAYBUS_HURRY_T;
;ハイウェイバスの運転手（ハリー）
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
@CHKFGOTO(FLG_TLPT_SUMS,_EVT_RIDE_BUS_THRK_TWSN_LATER)
◆Ｆｉｎａｌｌｙ，　ｔｈｅ　ｂｕｓ　ｃａｎ　ｍａｋｅ　ｉｔｓ　ｆｕｌｌ　ｒｕｎ．
;jpn:◆やっと　ハイウェイバスが↓
;jpn:　とおれるように　なったんだ。
@KEY()↓
_EVT_RIDE_BUS_THRK_TWSN_LATER;松（ＮＯＡのコメント）
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｔｏ　Ｔｗｏｓｏｎ，　ｉｔ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃｏｓｔ　＄@DSP_NUM(0)．@KEY()↓
◆（ｆｏｒ　ｔｈｅ　ｌｏｔ　ｏｆ　ｙｏｕ）．@KEY()↓
;◆Ｍｏｓｈｉ_ｐａｒｔｙ_ｇａ_ｆｕｔａｒｉ_ｉｚｙｏｕ_ｄａｔｔａｒａ_ｋｏｎｏ_ｇｙｏｕｗｏ_ｔａｓｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆ツーソンゆきは↓		
;jpn:　みんなで@DSP_NUM(0)ドルになるけど↓
;jpn:　のってくかい？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_THRK_HIGHWAYBUS_HURRY_T_YES,_THRK_HIGHWAYBUS_HURRY_T_NO)
@GOTO(_THRK_HIGHWAYBUS_HURRY_T_NO)
_THRK_HIGHWAYBUS_HURRY_T_YES;@MiuraAppended
@Q_MONEY(0)
@TRUE_GOTO(_THRK_HIGHWAYBUS_HURRY_T_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
◆Ｏｋ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)						;運転手消す
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE);乗車する透明人間
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
_FOUR_THRK_TWSN;フォーサイドからのバスはココにつながる
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TO_THRK_TUNNEL);バス乗車
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SETF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_basu);虫を無視
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』
_THRK_HIGHWAYBUS_HURRY_T_NOMONEY;
◆Ｉ　ｃａｎ’ｔ　ｄｏ　ｍｕｃｈ　ｆｏｒ　ｙｏｕ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ．．．
;jpn:◆おかねがないんじゃ↓
;jpn:　しょうがないなぁ。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)						;運転手消す
@!

;スリークからトンネルへ
MSG_EVT_BUS_THRK_TUNNEL;
@SETF(FLG_TUNNEL_THRK_TWSN_BL)
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_THRK_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_THRK_TUNNEL_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;トンネルからツーソンへ
MSG_EVT_BUS_TUNNEL_TWSN;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_TWSN,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_TWSN)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@CLRF(FLG_TUNNEL_THRK_TWSN_BL)
』

;ツーソンへついた
MSG_EVT_BUS_TOUCH_TWSN;
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_L,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_twoson)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@CLRF(FLG_SYS_MONSTER_OFF)
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』


MSG_DSRT_BUSSTOP_NG;
◆（Ｄｕｅ　ｔｏ　ｔｒａｆｆｉｃ　ｊａｍｓ，@KEY()↓
◆ｂｕｓ　ｓｅｒｖｉｃｅ　ｈａｓ　ｂｅｅｎ　ｔｅｍｐｏｒａｒｉｌｙ　ｓｕｓｐｅｎｄｅｄ．）
;jpn:◆（じゅうたい　はっせいちゅう！@WI(30)↓
;jpn:　グレイハンドバスの　うんこうは↓
;jpn:　いちじ　おやすみします）
@KEYNP()
』


;	ドコドコ砂漠からスリーク行きのバス	taku append

;バス停チェックで以下を発行
MSG_DSRT_BUSSTOP_THRK
@CHKF(FLG_DSRT_CLEAR)
@FALSE_GOTO(MSG_DSRT_BUSSTOP_NG);渋滞が終わるまではバスに乗れない。
@GOSUB(MSG_SUB_BSTOP_DSRT_THRK_DIR)
@TRUE_GOTO(MSG_BUSSTOP_DANGER)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆（@DSP_NAME(0)　ｃｈｅｃｋｅｄ　ｔｈｅ　ｂｕｓ　ｓｃｈｅｄｕｌｅ．
;jpn:◆@DSP_NAME(0)は　バスの↓
;jpn:　じこくひょうを　しらべた。
@KEY()↓
@CHKFGOTO(FLG_TEMP_9,MSG_TWSN_BUSSTOP_TEMP)
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｔｈｅ　ｎｅｘｔ　ｂｕｓ　ｗｉｌｌ　ｃｏｍｅ　ｐｒｅｔｔｙ　ｓｏｏｎ．）
;jpn:◆バスは　もうすぐ　くるようだ。
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_THRK_IN,OBJFX_SHOW_NONE)		;バス登場
@WAITSYS()	　　;停留所につくまで待つ
@SETF(FLG_TEMP_9)
』

MSG_EVT_RIDE_BUS_DSRT_THRK;松（ＮＯＡのコメント）
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｔｏ　Ｔｈｒｅｅｄ，　ｉｔ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃｏｓｔ　＄@DSP_NUM(0)．@KEY()↓
◆（ｆｏｒ　ｔｈｅ　ｌｏｔ　ｏｆ　ｙｏｕ．）@KEY()↓
;◆Ｍｏｓｈｉ_ｐａｒｔｙ_ｇａ_ｆｕｔａｒｉ_ｉｚｙｏｕ_ｄａｔｔａｒａ_ｋｏｎｏ_ｇｙｏｕｗｏ_ｔａｓｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆スリークゆきは↓		
@MUL_ACTIVE_PLAYER(2)
@XCHG()
;jpn:　みんなで@DSP_NUM(0)ドルになるけど↓
;jpn:　のってくかい？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_DSRT_THRK_HIGHWAYBUS_HURRY_YES,_DSRT_THRK_HIGHWAYBUS_HURRY_NO)
@GOTO(_DSRT_THRK_HIGHWAYBUS_HURRY_NO)

_DSRT_THRK_HIGHWAYBUS_HURRY_YES
@Q_MONEY(0)
@TRUE_GOTO(_THRK_HIGHWAYBUS_HURRY_T_NOMONEY)
@MONEYOUT(0)
@SE(SE_se76_my_give)
@WINR_MONEY()
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
◆Ｏｋａｙ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE);乗車する透明人間
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
_FOUR_DSRT_THRK;
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_TO_THRK);バス乗車
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SETF(FLG_BGM_BUS)
@MUSISTART()
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』



;	ドコドコ砂漠からフォーサイド行きのバス	taku append

;バス停チェックで以下を発行
MSG_DSRT_BUSSTOP_FOUR
@CHKF(FLG_DSRT_CLEAR)
@FALSE_GOTO(MSG_DSRT_BUSSTOP_NG);渋滞が終わるまではバスに乗れない。
@GOSUB(MSG_SUB_BSTOP_DSRT_FOUR_DIR)
@TRUE_GOTO(MSG_BUSSTOP_DANGER)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆（@DSP_NAME(0)　ｃｈｅｃｋｅｄ　ｔｈｅ　ｂｕｓ　ｓｃｈｅｄｕｌｅ．
;jpn:◆@DSP_NAME(0)は　バスの↓
;jpn:　じこくひょうを　しらべた。
@KEY()↓
@CHKFGOTO(FLG_TEMP_9,MSG_TWSN_BUSSTOP_TEMP)
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｔｈｅ　ｎｅｘｔ　ｂｕｓ　ｗｉｌｌ　ｃｏｍｅ　ｐｒｅｔｔｙ　ｓｏｏｎ．）
;jpn:◆バスは　もうすぐ　くるようだ。
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_FOUR_IN,OBJFX_SHOW_NONE)		;バス登場
@WAITSYS()	　　;停留所につくまで待つ
@SETF(FLG_TEMP_9)
』

MSG_EVT_RIDE_BUS_DSRT_FOUR
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_R,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｔｈｉｓ　ｂｕｓ　ｇｏｅｓ　ｔｏ　Ｆｏｕｒｓｉｄｅ．
;jpn:◆このバスは↓
;jpn:　フォーサイドに　いぐけんども
@KEY()↓
;@GOSUB(MSG_EVT_BUS_MES_B)		;メッセージのサブルーチンへ
◆Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｏｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｆａｒｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
;jpn:◆@DSP_NUM(0)ドルはらわねぇやつは↓
;jpn:　のせてやらねぇだよ。@KEY()↓
;jpn:◆いぐか？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_DSRT_FOUR_HIGHWAYBUS_HURRY_YES,_TWSN_BUSDRIVER_LATER_NO)
@GOTO(_TWSN_BUSDRIVER_LATER_NO)
;
_DSRT_FOUR_HIGHWAYBUS_HURRY_YES
@Q_MONEY(0)
@TRUE_GOTO(_TWSN_BUSDRIVER_LATER_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
◆Ｏｋ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消;す
;@TRUE_GOTO(MSG_END)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE);乗車する透明人間
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
_THRK_DSRT_FOUR;スリークからのバスはココにつながる
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_TO_FOUR);バス出発
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SETF(FLG_BGM_BUS)
@MUSISTART()
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』



;	フォーサイド行きのバス

MSG_EVT_RIDE_BUS_THRK_DSRT;
MSG_THRK_HIGHWAYBUS_HURRY;
;ハイウェイバスの運転手（ハリー）
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_R,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｔｈｉｓ　ｂｕｓ　ｇｏｅｓ　ｔｏ　Ｆｏｕｒｓｉｄｅ．
;jpn:◆このバスは↓
;jpn:　フォーサイドに　いぐけんども
@KEY()↓
◆Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｏｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｆａｒｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
;jpn:◆@DSP_NUM(0)ドルはらわねぇやつは↓
;jpn:　のせてやらねぇだよ。@KEY()↓
;jpn:◆いぐか？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_THRK_HIGHWAYBUS_HURRY_YES,_TWSN_BUSDRIVER_LATER_NO)
@GOTO(_TWSN_BUSDRIVER_LATER_NO)
_THRK_HIGHWAYBUS_HURRY_YES;@MiuraAppended
@Q_MONEY(0)
@TRUE_GOTO(_TWSN_BUSDRIVER_LATER_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｏｋ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
;@TRUE_GOTO(MSG_END)
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE);乗車する透明人間
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_WIN_GEPPU)		;バスが出ない様に
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_THRK_TO_DSRT);バス乗車
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SETF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_basu)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

_DSRT_THRK_HIGHWAYBUS_HURRY_NO;
_DSRT_FOUR_HIGHWAYBUS_HURRY_NO;
_THRK_HIGHWAYBUS_HURRY_NO;
_THRK_HIGHWAYBUS_HURRY_T_NO;
_FOUR_HIGHWAYBUS_HURRY_NO;
◆Ｏｈ．．．ｏｋａｙ．．．ｓｅｅ　ｙｏｕ！
;jpn:◆あ　そう。
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
』


;スリークからトンネルへ
MSG_EVT_BUS_THRK_TUNNEL_R;
@SETF(FLG_WIN_GEPPU)		;フラグを戻す
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_THRK_TUNNEL_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_THRK_TUNNEL_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;トンネルからハイウェイへ
MSG_EVT_BUS_TUNNEL_HWAY_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_HWAY_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_HWAY_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;ハイウェイからトンネルへ
MSG_EVT_BUS_HWAY_TUNNEL_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_HWAY_TUNNEL_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_HWAY_TUNNEL_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;トンネルから砂漠へ
MSG_EVT_BUS_TUNNEL_DSRT_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_DSRT_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_DSRT_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@WAITSYS()
; バス停
@COLD_GOM_CHAR(GOM_BUS)						　;バス停止
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_R,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆Ｔｈｉｓ　ｂｕｓ　ｇｏｅｓ　ｔｏ　Ｆｏｕｒｓｉｄｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｈｅｒｅ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆このバスは　フォーサイドまで↓
;jpn:　いくけんども　ここでおりるか？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THROUGH_DSRT_TO_FOUR_YES,_THROUGH_DSRT_TO_FOUR_NO)
_THROUGH_DSRT_TO_FOUR_NO
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@GOTO(_THRK_DSRT_FOUR)

_THROUGH_DSRT_TO_FOUR_YES
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@CLRF(FLG_BGM_BUS)
@MUSISTART()
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_R,OBJFX_SHOW_NONE)	;降りる人
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)				;バスははける
@WAITSYS()
@RESF(FLG_SYS_MONSTER_OFF)				;モンスター出る
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』

;砂漠からトンネルへ
MSG_EVT_BUS_DSRT_TUNNEL_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_TUNNEL_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_DSRT_TUNNEL_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;トンネルから橋へ
MSG_EVT_BUS_TUNNEL_BRDG_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_BRDG_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_BRDG_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;橋からトンネルへ
MSG_EVT_BUS_BRDG_TUNNEL_R;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_BRDG_TUNNEL_R,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_BRDG_TUNNEL_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;トンネルからフォーサイド
MSG_EVT_BUS_TUNNEL_FOUR;
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_FOUR,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_FOUR)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

;フォーサイドへついた
MSG_EVT_BUS_TOUCH_FOUR;
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_R,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_fors)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@GOSUB(MSG_WARP_STEP_FOUR)
@CLRF(FLG_SYS_MONSTER_OFF)
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
@SETF(FLG_TLPT_FOUR)
;@CLRF(FLG_THRK_HOTEL_BOY_APPEAR);セリフ後消えるに変更
@CLRF(FLG_THRK_PEOPLE_APPEAR);感謝するスリークの人消える
』


;フォーサイド発スリーク行きの路線バス

;バス停チェックで以下を発行
MSG_FOUR_BUSSTOP_THRK;
@GOSUB(MSG_SUB_BSTOP_FOUR_THRK_DIR)
@TRUE_GOTO(MSG_BUSSTOP_DANGER)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆（@DSP_NAME(0)　ｃｈｅｃｋｅｄ　ｔｈｅ　ｂｕｓ　ｓｃｈｅｄｕｌｅ．
;jpn:◆@DSP_NAME(0)は　バスの↓
;jpn:　じこくひょうを　しらべた。
@KEY()↓
@CHKFGOTO(FLG_TEMP_9,MSG_TWSN_BUSSTOP_TEMP)
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｔｈｅ　ｎｅｘｔ　ｂｕｓ　ｗｉｌｌ　ｃｏｍｅ　ｓｏｏｎ．）
;jpn:◆バスは　もうすぐ　くるようだ。
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_FOUR_THRK_IN,OBJFX_SHOW_NONE)		;バス登場
@WAITSYS()	　　;停留所につくまで待つ
@SETF(FLG_TEMP_9)
』

MSG_EVT_RIDE_BUS_FOUR_DSRT;
MSG_FOUR_HIGHWAYBUS_HURRY;松（ＮＯＡのコメント）
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆Ｔｈｉｓ　ｂｕｓ　ｇｏｅｓ　ｔｏ　Ｔｗｏｓｏｎ　ｖｉａ　Ｔｈｒｅｅｄ．
;jpn:◆このバスは　スリークけいゆ↓
;jpn:　ツーソンゆきだよ。
@KEY()↓
@MUL_ACTIVE_PLAYER(2)
@XCHG()
◆Ｉｔ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃｏｓｔ　＄@DSP_NUM(0)．@KEY()↓
◆（ｆｏｒ　ｔｈｅ　ｌｏｔ　ｏｆ　ｙｏｕ）．@KEY()↓
;◆Ｍｏｓｈｉ_ｐａｒｔｙ_ｇａ_ｆｕｔａｒｉ_ｉｚｙｏｕ_ｄａｔｔａｒａ_ｋｏｎｏ_ｇｙｏｕｗｏ_ｔａｓｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
;jpn:◆みんなで@DSP_NUM(0)ドルになるけど↓
;jpn:　のってくかい？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_FOUR_HIGHWAYBUS_HURRY_YES,_FOUR_HIGHWAYBUS_HURRY_NO)
@GOTO(_FOUR_HIGHWAYBUS_HURRY_NO)

_FOUR_HIGHWAYBUS_HURRY_YES;
@Q_MONEY(0)
@TRUE_GOTO(_THRK_HIGHWAYBUS_HURRY_T_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｏｋ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
;
@SETF(FLG_SYS_MONSTER_OFF)							　　;モンスター出さない
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
;
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_BUS,OBJFX_SHOW_NONE)	;乗車する透明人間
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()											　　;乗車するまで待つ
@SETF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_basu);虫を無視
@REMOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_FOUR_THRK_GO)		　;バス発車
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@WAITSYS()									　　;トンネルまで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; トンネルへ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_FOUR_TUNNEL,OBJFX_AFTER_WARP)　;トンネル内のバス
@WARP(WARP_BUS_FOUR_TUNNEL)					　;トンネル内へワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;トンネル出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; 橋へ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_BRDG_L,OBJFX_AFTER_WARP)　;橋のバス
@WARP(WARP_BUS_TUNNEL_BRDG_L)					　
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;橋出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; トンネルへ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_BRDG_TUNNEL_L,OBJFX_AFTER_WARP)　;トンネル内のバス
@WARP(WARP_BUS_BRDG_TUNNEL_L)					　
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;トンネル出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; 砂漠へ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_DSRT_L,OBJFX_AFTER_WARP)　;砂漠のバス
@WARP(WARP_BUS_TUNNEL_DSRT_L)				　　　;砂漠へワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;トンネルまで
@COLD_GOM_CHAR(GOM_BUS)
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆Ｔｈｉｓ　ｂｕｓ　ｃｏｎｔｉｎｕｅｓ　ｏｎ　ｔｏ　Ｔｗｏｓｏｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｈｅｒｅ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆このバスは　ツーソンまで↓
;jpn:　いくけど　ここでおりるかい？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THROUGH_DSRT_TO_THRK_YES,_THROUGH_DSRT_TO_THRK_NO)
_THROUGH_DSRT_TO_THRK_NO;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@GOTO(_FOUR_DSRT_THRK)

_THROUGH_DSRT_TO_THRK_YES;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@CLRF(FLG_BGM_BUS)
@MUSISTART()
@MOVE_GOM_CHAR(GOM_HIT_CHR, ANIM_OUT_BUS_R,OBJFX_SHOW_NONE)　　;降りる人
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)						;バスははける
@WAITSYS()
@RESF(FLG_SYS_MONSTER_OFF)							　　;モンスター出る
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』

; トンネルへ
MSG_EVT_BUS_TUNNEL_HWAY_L
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_DSRT_TUNNEL_L,OBJFX_AFTER_WARP)　;トンネルのバス
@WARP(WARP_BUS_DSRT_TUNNEL_L)				　　　;トンネルへワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;トンネル出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; 高速へ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_HWAY_L,OBJFX_AFTER_WARP)　;トンネルのバス
@WARP(WARP_BUS_TUNNEL_HWAY_L)				　　　;高速へワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;高速出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; トンネルへ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_HWAY_TUNNEL_L,OBJFX_AFTER_WARP)　;トンネルのバス
@WARP(WARP_BUS_HWAY_TUNNEL_L)				　　　;トンネルへワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;トンネル出口まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; スリークへ
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_THRK_L,OBJFX_AFTER_WARP)　;スリークのバス
@WARP(WARP_BUS_TUNNEL_THRK_L)				　　　;スリークへワープ
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()									　　;バス停まで
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
; バス停
@COLD_GOM_CHAR(GOM_BUS)						　;バス停止
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_L,OBJFX_SHOW_NONE)	　;運転手
@OPEN(1)
◆Ｔｈｉｓ　ｂｕｓ　ｃｏｎｔｉｎｕｅｓ　ｏｎ　ｔｏ　Ｔｗｏｓｏｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｈｅｒｅ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆このバスは　ツーソンまで↓
;jpn:　いくけど　ここでおりるかい？@KEY()↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THROUGH_THRK_TO_TWSN_YES,_THROUGH_THRK_TO_TWSN_NO)
_THROUGH_THRK_TO_TWSN_NO;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@GOTO(_FOUR_THRK_TWSN)

_THROUGH_THRK_TO_TWSN_YES;
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)					　　　;運転手消す
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_threek)
@MOVE_GOM_CHAR(GOM_HIT_CHR, ANIM_OUT_BUS_R,OBJFX_SHOW_NONE)　　;降りる人
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)						;バスははける
@WAITSYS()
;
@RESF(FLG_SYS_MONSTER_OFF)							　　;モンスター出る
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
;
』

MSG_EVT_BUS_MES_A;
◆Ｉｔ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃｏｓｔ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｌｏｔ　ｏｆ　ｙｏｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
;jpn:　みんなで@DSP_NUM(0)ドルになるけど↓
;jpn:　のってくかい？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_BUS_MES_A_YES,_BUS_MES_A_NO)
_BUS_MES_A_NO;
◆Ｏｈ．．．ｏｋａｙ．．．ｓｅｅ　ｙｏｕ！
;jpn:◆あ　そう。
_BUS_MES_A_NO_2;
@KEYNP()
@SET_LOOPREG(1)
@SET_REG(1)
@XCHG()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@!
_BUS_MES_A_YES;
@Q_MONEY(0)
@TRUE_GOTO(_BUS_MES_A_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
◆Ｏｋ，　ｗｅ’ｒｅ　ｏｆｆ！
;jpn:◆しゅっぱーつ！
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@!
_BUS_MES_A_NOMONEY;
◆Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｏｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ．
;jpn:◆おかねがないんじゃ↓
;jpn:　しょうがないなぁ。
@GOTO(_BUS_MES_A_NO_2)


MSG_EVT_BUS_MES_B;
◆Ｉ　ｃａｎ’ｔ　ｌｅｔ　ｙｏｕ　ｏｎ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｐａｙ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｆａｒｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｏ？↓
;jpn:◆@DSP_NUM(0)ドルはらわねぇやつは↓
;jpn:　のせてやらねぇだよ。@KEY()↓
;jpn:◆いぐか？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_BUS_MES_B_YES,_BUS_MES_B_NO)
_BUS_MES_B_NO;
◆Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｙｏｕ　ｓｈｏｕｌｄ　ｊｕｓｔ　ｓｔｒｏｌｌ　ａｒｏｕｎｄ．@KEY()↓
◆Ｂｅｓｉｄｅｓ，　ｗａｌｋｉｎｇ　ｉｓ　ｇｏｏｄ　ｆｏｒ　ｙｏｕ．
;jpn:◆かねが　ねぇんだったら↓
;jpn:　エッチラ　オッチラ↓
;jpn:　あるいていくが　いいだよ。@KEY()↓
;jpn:◆けんこうにも　いいし。
@SET_LOOPREG(1)
@SET_REG(1)
@XCHG()
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@!
_BUS_MES_B_YES;
@Q_MONEY(0)
@TRUE_GOTO(_BUS_MES_B_NO)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｏｋａｙ，　ｌｅｔ’ｓ　ｇｉｖｅ　ｉｔ　ａ　ｓｈｏｔ！
;jpn:◆んじゃ　いってみるべ！
@KEYNP()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)	;運転手消す
@SET_LOOPREG(0)
@SET_REG(1)
@XCHG()
@!

;-------------------------------------------------


;#26	ゴーストトンネル（バスor自転車or歩き）	ゝ

;★ツーソンとスリーク、スリークとドコドコ砂漠を結ぶトンネルには、
;グレープフルーツの滝の秘密基地のボス「ゲップー」を倒すまでは
;ゴーストたちが道を塞いでいる。
;★バスでも自転車でも徒歩でも、ゴーストは接近してきて
;MSG_TWSN_TUNNELGHOST を発行してプレイヤーをトンネル入り口にワープさせる。

;★バスの場合は、ワープ後そのままツーソンのバス停まで走り、停止して
;MSG_TWSN_GHOSTTUNNEL を表示し、プレイヤーキャラをバスの手前に出現させて
;運転手の顔を窓から出して MSG_TWSN_GHOSTTUNNEL_BUSDRIVER を発行。
;★メッセージ表示後、バスは道に沿って走り去る。

MSG_EVT_GHOST_1;
@OPEN(1)
@SE(SE_se60_monster_appear)
◆Ｗｏｏｏｏ！　Ｗｏｏｏ！　Ｗｏｏｏｏｏｏｏ！@KEY()↓
◆（Ｇｏ　ｂａｃｋ！　　Ｇｏ　ｂａｃｋ！）
;jpn:◆ケケケケケ。↓
;jpn:　（も～どれ～～。も～どれ～）
@KEY()
@CLOSEALL()
』

MSG_EVT_GHOST_WARP;
@OPEN(1)
@SE(SE_se60_monster_appear)
◆Ｗｏｏｏ！　Ｗｏｏｏ！　Ｗｏｏｏｏｏｏ！@KEY()↓
◆（Ｇｏ　ｂａｃｋ！　　Ｇｏ　ｂａｃｋ！）
;jpn:◆ケケケケケ。↓
;jpn:　（も～どれ～～。も～どれ～）
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_GHOST_PLUS1,OBJFX_SHOW_NONE);二匹追加
@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_GHOST_PLUS2,OBJFX_SHOW_NONE)
@WAITSYS()
@CHKFGOTO(FLG_TUNNEL_TWSN_THRK_WR,_EVT_26_WR)
@WARP(WARP_THRK_GHOSTTUNNEL_L);スリークから歩きで行った場合
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_RET_GHOSTTUNNEL,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_CAMERA_PARTY()
@CLRF(FLG_TUNNEL_THRK_TWSN_WL)
』

_EVT_26_WR;ツーソンから歩きで行った場合
@WARP(WARP_TWSN_GHOSTTUNNEL)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_RET_GHOSTTUNNEL,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_CAMERA_PARTY()
@CLRF(FLG_TUNNEL_TWSN_THRK_WR)
』

;----------------------------------------
;砂漠のトンネルからスリークに戻される

MSG_EVT_GHOST_WARP_THRK;
@OPEN(1)
@SE(SE_se60_monster_appear)
◆Ｗｏｏｏ！　　Ｗｏｏｏ！　　Ｗｏｏｏｏｏｏ！@KEY()↓
◆（Ｇｏ　ｂａｃｋ！　　Ｇｏ　ｂａｃｋ！）
;jpn:◆ケケケケケ。↓
;jpn:　（も～どれ～～。も～どれ～）
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_GHOST_THRK_PLUS1,OBJFX_SHOW_NONE);２匹追加
@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_GHOST_THRK_PLUS2,OBJFX_SHOW_NONE)
@WAITSYS()
@WARP(WARP_THRK_GHOSTTUNNEL_R)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_RET_GHOSTTUNNEL,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_CHAR(PC_ALL)
@WAITSYS()
@SET_CAMERA_PARTY()
』

;----------------------------------------

;#27	受信電話をくれるマウス	2.5	T	こまわり君シート対応

;★アップルキッドに食べ物をあげて FLG_TWSN_APPLE_THANKS が ON に
;なったらマウスをドアの前に移動させる。
;（フラグを見て自分で移動するのか、強制的に移動させるのかどちらがよいの？）
;●答え：この場合は強制的に移動させるのがよい。
;　　　　ダイレクトに命令を下せる場合は、命令する原則でいこう。
;★マウスはネスに話し掛けられたら MSG_TWSN_MOUSE_0 を発行する。

;★有望青年Ｂの家からツーソンフィールドへのワープポイントに
;検査フラグ FLG_WARP_APPLE_TWSN を設定。
;★FLG_WARP_APPLE_TWSN /ON の時はワープ禁止。
;（アップルに食べ物をあげたら、マウスと話すまでは外に出られない。）

MSG_EVT_27_APPLE;マウスはドアへ
@REMOVE_CHAR(PRSN_TWSN_APPLE_B,ANIM_MOUSE_DOOR)
@WAITSYS()
@SETF(FLG_TEMP_3);マウスはドアにいる
』

MSG_EVT_27_MOUSE;マウスはササッと移動
@REMOVE_CHAR(PRSN_TWSN_APPLE_B,ANIM_APPLEMOUSE_STEPBACK)
』

;-------------------------------------------------------------------------


;#28	ポーラを呼びに行く父	2.3	T

;★ポーラ父のセリフ MSG_TWSN_PAUL を中断し、ポーラ父を扉に移動して消し、
;数秒後に再び扉から登場させ元の位置に戻して
;メッセージの続きを表示する。

MSG_EVT_28_PAUL;
@CLOSEALL()
@REMOVE_CHAR(PRSN_TWSN_POLA_FRONT_A,ANIM_FATHER_CALL_PAULA);呼びに行く
@WAITSYS()
@COLD_CHAR(PRSN_TWSN_POLA_FRONT_A)
@GET_ORDER_PLAYER(1)
@GET_PLAYER_DIR(0,2,PRSN_TWSN_POLA_FRONT_A)
@SET_PLAYER_DIR(0,0)
@OPEN(1)
』

;----------------------------------------------------------------------


;#29	つきまとう寄付屋	3.1	T

;★ハッピーハッピー村の寄付屋で寄付を拒否すると
;プレイヤーキャラの後を（少し離れて）追いかけさせる。

MSG_EVT_KIFUYA;
@SHOW_MANPU_CHAR(PRSN_HAPY_FIELD_L,MANPU_BIKKURI)
@WI(60)
@HIDE_MANPU_CHAR(PRSN_HAPY_FIELD_L)
@FRESH_CHAR( PRSN_HAPY_FIELD_L );プレイヤーに近づく
@WAITSYS()
@COLD_CHAR( PRSN_HAPY_FIELD_L )
@OPEN(1)
@GOTO(MSG_HAPPY_KIFU)
@CLOSEALL()
』

MSG_EVT_29_KIFU;寄付したら
@REMOVE_CHAR(PRSN_HAPY_FIELD_L,ANIM_PEOPLEWALK1)
』

MSG_EVT_29_KIFU_X;寄付しなかったら
@REMOVE_CHAR(PRSN_HAPY_FIELD_L,ANIM_KIFUYA_TUKIMATOU)
』

;-----------------------------------------------------


;#30	電話が掛かってくる（最初）	こまわり君シート対応

;★リリパットステップのダンジョンで通路を塞いでいる
;「てつのタコ」がプレイヤーキャラを発見したら FLG_TWSN_TACO_DISCOVER
;を on にする。

;★リリパットステップからフィールドへのワープメッセージで
;プレイヤーが「受信専用電話」を獲得しているかを調べて、さらに
;FLG_TWSN_TACO_DISCOVER が on であったら
;アップルキッドから電話が掛かってくる。
;★まず電話呼出音の曲に切り替え（トゥルルル‥‥）、
;キー入力があったら MSG_PHONE_TACO_ERASER を表示する。

;★メッセージ後、音楽は元の曲に戻す。

;鉄のタコ
;Ｇフルデッド、ウィンターズ、ドコドコ砂漠に存在する

MSG_GRFD_LLPT_TACO;
MSG_WINS_TACO;
MSG_DSRT_SARUDUNGEON_TACO;
MSG_GRFD_TACO_ERASER;
◆（Ｆｏｒ　ｓｏｍｅ　ｗｅｉｒｄ　ｒｅａｓｏｎ，@KEY()↓
◆ａｎ　ｐｅｎｃｉｌ－ｓｈａｐｅｄ　ｉｒｏｎ　ｓｔａｔｕｅ　ｉｓ　ｂｌｏｃｋｉｎｇ　ｔｈｅ　ｐａｔｈ．）

;jpn:◆（なぜか　タコのかたちをした↓
;jpn:　てつのかたまりが↓
;jpn:　みちを　ふさいでいる）
@KEYNP()
』

;タコ消しマシン
MSG_GRFD_LLPT_TACO_RECEIVE;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG_HERE)
@GOSUB(_SUB_TACO_ERASE)
@HIDE_CHAR(PRSN_GRFD_FIELD_3B,OBJFX_HIDE_DOTS)
;@WI(60)
@CLOSEALL()
@SETF(FLG_GRFD_LLPT_TACO_DISAPPEAR)
@SETF(FLG_PHOTO_RIVER);撮り頃フラグ
』

MSG_DSRT_SARUD_TACO_RECEIVE;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG_HERE)
@GOSUB(_SUB_TACO_ERASE)
@HIDE_CHAR(PRSN_DEST_MONKEY_L_3A,OBJFX_HIDE_DOTS)
;@WI(60)
@CLOSEALL()
@SETF(FLG_DSRT_SARU_TACO_DISAPPEAR)
』

MSG_WINS_TACO_RECEIVE;
@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG_HERE)
@GOSUB(_SUB_TACO_ERASE)
@HIDE_CHAR(PRSN_WINS_FIELD_3D,OBJFX_HIDE_DOTS)
;@WI(60)
@CLOSEALL()
@SETF(FLG_WINS_TACO_DISAPPEAR)
』

_SUB_TACO_ERASE;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0)　ｕｓｅｄ　ｔｈｅ　Ｐｅｎｃｉｌ　Ｅｒａｓｅｒ．@KEY()↓
;jpn:◆@DSP_NAME(0)は↓
;jpn:　タコけしマシンを　つかった！@KEY()↓
;jpn:◆なぜか　てつのタコは↓
;jpn:　いっしゅんのうちに↓
;jpn:　きえさった！
@KEYNP()
@SE(SE_se21_b_foe_down)
@!

@GOSUB(MSG_SUB_GOODS_PRE)
@EQ(GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG_HERE)
@SE(SE_se64_taco)
@LOAD_REG()
@GOSUB(MSG_SUB_GOODS_TUKATTA)
←
◆Ｆｏｒ　ｓｏｍｅ　ｗｅｉｒｄ　ｒｅａｓｏｎ，　ｔｈｅ　ｉｒｏｎ　ｐｅｎｃｉｌ　ｓｔａｔｕｅ　ｗａｓ　ｅｒａｓｅｄ！
;jpn:◆なぜか　てつのタコは↓
;jpn:　いっしゅんのうちに↓
;jpn:　きえさった！
@KEYNP()
@WI(1)

MSG_PHONE_TACO_ERASER;
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0)
@SE(SE_se0b_tel_put)
@OPEN(1)
◆Ｈｅｌｌｏ．．．ｔｈｉｓ　ｉｓ　ｔｈｅ　Ａｐｐｌｅ　Ｋｉｄ．@KEY()↓
◆Ｉ’ｖｅ　ｊｕｓｔ　ｆｉｎｉｓｈｅｄ　ｗｏｒｋ　ｏｎ　ｔｈｉｓ　ｇｒｅａｔ　ｉｎｖｅｎｔｉｏｎ！@KEY()↓
◆Ｇｅｔ　ｏｖｅｒ　ｈｅｒｅ　ａｓ　ｆａｓｔ　ａｓ　ｙｏｕ　ｃａｎ！@KEY()↓
◆Ｔｈｉｓ　ｔｈｉｎｇ　ｉｓ　ｓｏｏｏｏ　ｃｏｏｌ！@KEY()↓
◆Ｓｅｅ　ｙｏｕ　ｓｏｏｎ！@KEY()↓
◆Ｓｌａｍ！　　Ｂｅｅｅｅｐ．．．
;jpn:◆もしもし‥‥アップルキッドです。↓
;jpn:　ブリリアントなアイテムが↓
;jpn:　ついに　かんせいしました。@KEY()↓
;jpn:◆すぐに　とりにきてください。↓
;jpn:　すっごいんです！↓
;jpn:　じゃ！　ガチャン！@KEY()↓
;jpn:◆ツーツーツー
@KEYNP()
@CLOSEALL()
@SE(SE_se0b_tel_put)
@SETF(FLG_TWSN_CHAOSAPPLE_APPEAR)
@SETF(FLG_TWSN_APPLE_DISAPPEAR)
@SETF(FLG_TWSN_INFO_TACO)
@MUSISTART()
』

;-------------------------------------------------


;#31	カオス劇場入場	2.6	こまわり君シート対応

;★カオス劇場チケットもぎり嬢にチケット（GDS_TOOL_THEATER_TICKET）を
;「つかう」と、（MSG_TWSN_CARROT_RECEIVE）により
;もぎり嬢は東に2キャラ移動して劇場ホールへ続く通路をあける。

MSG_EVT_31_CARROT_R;
@REMOVE_CHAR(PRSN_TWSN_CHAOS_FRONT_A,ANIM_MOGIRI_TO_RIGHT)
@WAITSYS()
』

;★（劇場に入った後）チケットもぎり嬢に話し掛けた場合
;（下以外の方向から話し掛けた場合）は、
;もぎり嬢はカウンターの外側に移動して出口への通路をあける。

MSG_EVT_31_CARROT_D;
@REMOVE_CHAR(PRSN_TWSN_CHAOS_FRONT_A,ANIM_MOGIRI_TO_DOWN);外側へ移動
@WAITSYS()
』

;-------------------------------------------------------------------------


;#32	トンズラステージ

;★観客のメッセージをトリガーに舞台の袖から登場。
;専用の音楽に併せてアニメーション。踊る。
;演奏が終わったら舞台の袖に引っ込む。
;★プレイヤーパーティーは演奏中移動することは出来ない。

;楽屋からホールへのワープで以下発行
MSG_EVT_32_TONZURASTAGE;
@COLD_PLAYER(PC_ALL)
@BGM_EFFECT(3)
@CLOSEALL()
;-----
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_FADEOUT,OBJFX_SHOW_NONE)
@WAITSYS()
@GOSUB(MSG_EVT_CHAOS_TONZURA_MC);カオスステージ開始のアナウンス
;-----
@MOVE_GOM_CHAR(GOM_TEN,ANIM_TSTAGE1_SCR_1,OBJFX_SHOW_NONE);暗転、スクロール
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_PARTY,OBJFX_SHOW_NONE)　;固まるプレーヤー
@SET_GOM_CHAR_DIR(GOM_HIT_CHR,DIR_M_UP_RIGHT);（ステージの方を向く）
;@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
;パーティーを GOM で表示する。気絶状態などのチェックが必要。
;@GET_ORDER_PLAYER(1)
;@EQ(PC_NESS)
;@FALSE_GOTO(_MSG_EVT_32_NESS_DEAD)
;@MOVE_GOM_CHAR(GOM_NES,ANIM_TSTAGE1_NESS_LOOK_STAGE,OBJFX_SHOW_NONE)
;@GOTO(_MSG_EVT_32_CONT)
;_MSG_EVT_32_NESS_DEAD
;@MOVE_GOM_CHAR(GOM_POLA,ANIM_TSTAGE1_NESS_LOOK_STAGE,OBJFX_SHOW_NONE)
;_MSG_EVT_32_CONT
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE1_MIKE_L,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE1_MIKE_R,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE1_THANK,OBJFX_SHOW_NONE)　;サンキュー
@MOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE1_OK,OBJFX_SHOW_NONE)　　　　　　　;オーケー
@MOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE1_NICE,OBJFX_SHOW_NONE)　　　;ナイス
@MOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE1_GROOVE,OBJFX_SHOW_NONE)　　　　　　　;グルービー
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@WI(1)
』

MSG_EVT_TSTAGE1_A
@BGMSTART(0,BGM_tonz1)
@FRESH_PLAYER(PC_ALL)
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE1_FLIP)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE1_FLIP)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE1_FLIP)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE1_FLIP_TURN)
@WI(80)
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE1_GORGEOUS,OBJFX_SHOW_NONE)　　　;ゴージャス
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE1_LUCKY,OBJFX_SHOW_NONE)　;ラッキー
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE1_GORGEOUS_DANCE,OBJFX_SHOW_NONE)　;ゴージャス
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE1_LUCKY_DANCE,OBJFX_SHOW_NONE)　;ラッキー
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;ステージ終了待ち
@REMOVE_GOM_CHAR(GOM_TEN,ANIM_TSTAGE1_SCR_2);スクロール、明
;@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TSTAGE1_SCR_2,OBJFX_SHOW_NONE);スクロール、明
@MUSISTART();ここで曲スタート？
』

MSG_EVT_TSTAGE1_B
@SET_CAMERA_PARTY()
;
;@HIDE_GOM_CHAR(GOM_NES,OBJFX_HIDE_NONE)
;@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
;
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_KEYBOARD,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_OK,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_NICE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_GROOVE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;1
@WI(1)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;2
;-----
@CLRF(FLG_TWSN_CHAOS_ONSTAGE)	;演奏終了客出現
@WARP(WARP_TWSN_CHAOS_HALL)	;暗転で　　↑
@WI(1)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_B,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_C,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_D,ANIM_MAPOBJTBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_E,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_G,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_H,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_I,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_J,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_K,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_N,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_O,ANIM_PEOPLE_TBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_P,ANIM_MAPOBJTBACK,OBJFX_SHOW_NONE)
;@MOVE_CHAR(PRSN_TWSN_CHAOS_HALL_Q,ANIM_MAPOBJTBACK,OBJFX_SHOW_NONE)
』

MSG_EVT_CHAOS_TONZURA_MC;カオスステージ開始のアナウンス
@OPEN(1)
◆Ｙｅａｈ！　　Ｔｈａｔ’ｓ　ｒｉｇｈｔ！@KEY()↓
◆Ｔｏｎｉｇｈｔ，　ｙｏｕ　ｇｏｔ　ｔｈｅ　Ｃｈａｏｓ　Ｔｈｅａｔｅｒ’ｓ　Ｓｏｕｌ　Ｍｅｎ　ｃｏｍｉｎ’　ａｔ　ｙａ！@KEY()↓
◆Ｒｏｃｋｉｎ’　ａｎｄ　ｒｏｌｌｉｎ’　ｌｉｖｅ　ｏｎ　ｔｈｉｓ　ｈｅｒｅ　ｓｔａｇｅ　ｆｏｒ　ａ　ｌｉｍｉｔｅｄ　ｔｉｍｅ　ｏｎｌｙ！@KEY()↓
◆Ｔｈｅ　ｗｏｒｌｄ’ｓ　ｇｒｅａｔｅｓｔ　Ｂｌｕｅｓｍｅｎ，@KEY()↓
◆ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ！　　Ａｎｄ　ｈｅｒｅ　ｔｈｅｙ　ｃｏｍｅ！@KEY()↓
◆Ｏｈ　ｙｅａｈ！　　Ｂａｂｙ！
;jpn:◆イエーイ！↓
;jpn:　カオスげきじょうの↓
;jpn:　ソウルメーーーン！！@KEY()↓
;jpn:◆セクシーで　エキサイティング！↓
;jpn:　ダイナマイトな　ステージ！@KEY()↓
;jpn:◆カモーン！@WI(20)↓
;jpn:　グレイティスト　ブルースメン‥‥@KEY()↓
;jpn:◆トンズラブラザーズバーンド！！@WI(20)↓
;jpn:　ヒア　ウィー　カム！@WI(15)↓
;jpn:　ガッチャ！　ガッチャ！
@KEY()
@CLOSEALL()
』

MSG_TWSN_CHAOS_MOHIKAN;モヒカン
◆Ａ　ｙｏｕｎｇ　ｆａｎ　ｌｉｋｅ　ｙｏｕ　ｒｅａｌｌｙ　ｇｅｔｓ　ｉｎｔｏ　ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ’ｓ　ｍｕｓｉｃ？@KEY()↓
◆Ｗｏｗ，　Ｉ’ｍ　ｉｍｐｒｅｓｓｅｄ！
;jpn:◆わかいのにトンズラの↓
;jpn:　ブルースのこころが↓
;jpn:　わかるなんて‥‥@KEY()↓
;jpn:◆みあげたもんだ。
@KEYNP()
』

MSG_TWSN_CHAOS_HALL_E;
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_CHAOS_HALL_E_TEMP)
◆Ｓｅｅｉｎｇ　ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ　ｏｎ　ｓｔａｇｅ　ｉｓ　ｍｙ　ｌｉｆｅ．．．
;jpn:◆わたしトンズラの↓
;jpn:　ステージだけが↓
;jpn:　じんせいの　いきがいなの！
@KEYNP()
』
_TWSN_CHAOS_HALL_E_TEMP;
◆Ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ　ａｒｅ　ｓｏ　ｓｅｘｙ！@KEY()↓
◆Ｍｙ　ｈｕｓｂａｎｄ　ｄｅｆｉｎｉｔｅｌｙ　ｉｓ@KEY()↓
◆ｉｎ　ｎｅｅｄ　ｏｆ　ｓｏｍｅ　ｈｅｌｐ　ｉｎ　ｔｈａｔ　ａｒｅａ！
;jpn:◆うちの　しゅじんも↓
;jpn:　トンズラみたいに↓
;jpn:　セクシー@KEY()↓
;jpn:◆‥‥ならねぇ。
@KEYNP()
』

MSG_TWSN_CHAOS_HALL_F;
@CHKFGOTO(FLG_TWSN_CHAOS_STAGE_START,_TWSN_CHAOS_HALL_F_TEMP)
◆Ｗｈｅｎ　Ｉ　ｓｉｔ　ｃｌｏｓｅ　ｔｏ　ｔｈｅ　ｓｔａｇｅ，@KEY()↓
◆ｓｏｍｅｔｉｍｅｓ　Ｉ　ｇｅｔ　ｓｗｅａｔ　ｏｒ　ｓｐｉｔ　ｏｎ　ｍｅ　ｆｒｏｍ　ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ．
;jpn:◆ステージの　まえのほうでみてると↓
;jpn:　トンズラの　アセやツバが↓
;jpn:　とんでくるようなきがして@KEY()↓
;jpn:◆たまんないのよ。↓
;jpn:　オホホホホホ！
@KEYNP()
』
_TWSN_CHAOS_HALL_F_TEMP;
◆Ｏｈ，　ｔｈａｔ　ｗａｓ　ａｌｍｏｓｔ　ｔｏｏ　ｍｕｃｈ！
;jpn:◆あー　こうふんした！
@KEYNP()
』

;--------------------------------------------------------
;#33	●ハッピー教団本部完成（青い村に変化）	3.1	T
;--------------------------------------------------------


;#34	雷を落とされる（外に飛ばされる）

;●ハッピー村／ＨＨ教団の館／祭壇の間のカーペインターと話した時、
;プレイヤーパーティーが「フランクリンバッジ」を所持していなかったら
;_BATTLE_CARPAINTER_NOTHAVE が呼ばれる。
;★ここで雷を落とされた効果
;（画面のフラッシュと効果音の組み合わせ。詳細は未定）
;を挿入して、プレイヤーパーティーを人間ダンジョンの間にワープさせる。

;--------------------------------------------------------------------
;#35	●フランクリンバッジを渡すポーラ	4.2	T


;山小屋を出るとポーキーの部下とバトル

;ポーキーがサーチしていて以下を発行
MSG_EVT_KOYA_POKEY_BATTLE
@RESF(FLG_TEMP_1)
@RESF(FLG_TEMP_2)
;ポーキー接近
@FRESH_CHAR(PRSN_GRFD_FIELD_A)
@WAITSYS()
;
@COLD_CHAR( PRSN_GRFD_FIELD_A )
@OPEN(1)
MSG_GRFD_POKEY;
◆Ｈｅｙ　@DSP_NAME(PC_NESS)！@KEY()↓
◆Ｙｏｕ’ｒｅ　ｊｕｓｔ　ｈｅｒｅ　ｔｏ　ｂｏｔｈｅｒ　ｍｅ，↓
　　ａｒｅｎ’ｔ　ｙｏｕ．@KEY()↓
◆Ｙｏｕ　ｃａｎ　ｃａｌｌ　ｍｅ　Ｍａｓｔｅｒ　Ｐｏｋｅｙ，@KEY()↓
◆ｓｉｎｃｅ　Ｍｒ．　Ｃａｒｐａｉｎｔｅｒ　ｍａｄｅ　ｍｅ　ａｎ　ｉｍｐｏｒｔａｎｔ　ｐｅｒｓｏｎ　ｉｎ　Ｈａｐｐｙ－Ｈａｐｐｙｉｓｍ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｊｏｉｎ　ｕｓ，　ｂｕｔ　Ｉ　ｋｎｏｗ　ｙｏｕ　ｗｏｎ’ｔ．．．Ｉ’ｍ　ｇｌａｄ　Ｉ　ｊｏｉｎｅｄ．．．@KEY()↓
◆Ｉ’ｍ　ｎｏｔ　ｇｏｉｎｇ　ｔｏ　ｆｉｇｈｔ　ｙｏｕ，@KEY()↓
◆ｂｕｔ　ｔｈｅｓｅ　ｇｕｙｓ　ｗｉｌｌ．．．Ｌａｔｅｒ　ｐｏｔａｔｅｒ．．．
;jpn:◆やい！　@DSP_STS(STS_PC_NAME_NES)！@WI(15)↓
;jpn:　どうして　このポーキーさまの↓
;jpn:　じゃまを　しにきたんだよー。@KEY()↓
;jpn:◆カーペインターさまの　おかげで↓
;jpn:　ハッピーハッピーきょうの↓
;jpn:　えらいひとに　なれそうなのに‥。@KEY()↓
;jpn:◆おまえも　なかまに　なれよー！@KEY()↓
;jpn:◆‥‥ならないんだよな@WI(15)　きっと。↓
;jpn:　じゃ@WI(15)　おれは　やるぜ！！@KEY()↓
;jpn:◆でも　ぼくは　たたかわないよ。↓
;jpn:　かわりに　こいつらがいくぜい！@WI(15)↓
;jpn:　あばよ！
@KEY()
@CLOSEALL()
@CLRF(FLG_SYS_MONSTER_OFF)	;モンスター出現許可（勝っても負けても）
@CLRF(FLG_GRFD_POKEY_APPEAR)	;ポーキー＆手下出現禁止
;ポーキー去る
@FRESH_CHAR( PRSN_GRFD_FIELD_A )
@WAITSYS()
;手下がネスに近寄る
@REMOVE_CHAR(PRSN_GRFD_FIELD_B,ANIM_KOYA_HH1)
@REMOVE_CHAR(PRSN_GRFD_FIELD_C,ANIM_KOYA_HH2)
@REMOVE_CHAR(PRSN_GRFD_FIELD_D,ANIM_KOYA_KARASU)
@WAITSYS()
@COLD_CHAR( PRSN_GRFD_FIELD_B )
@COLD_CHAR( PRSN_GRFD_FIELD_C )
@COLD_CHAR( PRSN_GRFD_FIELD_D )
MSG_EVT_BATTLE_HH12KARASU;教徒1,2,カラスのいずれかと接触すると以下を発行
@GOSUB(MSG_BATTLE_POKEYBOYS)
@TRUE_GOTO(_EVT_KOYA_POKEY_LOSE)
@WI(1)
@REMOVE_CHAR(PRSN_GRFD_FIELD_B,ANIM_BLINK_SUICIDE)
@REMOVE_CHAR(PRSN_GRFD_FIELD_C,ANIM_BLINK_SUICIDE)
@REMOVE_CHAR(PRSN_GRFD_FIELD_D,ANIM_BLINK_SUICIDE)
@WI(60)	;ポーキーが去るのを待つ（手抜き）
@FUNC(6)			;マップ上での全滅許可
』
_EVT_KOYA_POKEY_LOSE;
@FUNC(6)			;マップ上での全滅許可
』
;--------------------------------------------------------


;#36	雷を受け止めるフランクリンバッジ	3.2	T

;★雷を受け止める効果
;（画面のフラッシュと効果音の組み合わせ。詳細は未定）を挿入する。
;トリガーは _BATTLE_CARPAINTER_HAVE。

;--------------------------------------------------------


;#37	●ポーラ救出（ポーラを仲間にする）	4.3	T

MSG_GRFD_YAMAGOYA_RECEIVE;牢屋の扉に山小屋のカギを使った時のメッセージ
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_KEY_PRISON)
@FALSE_GOTO(_GRFD_YAMAGOYA_RECEIVE_X)
@GOODSOUT(PC_ALL,GDS_TOOL_KEY_PRISON)
◆（@GOSUB(MSG_ESUB_DSP_PARTY_SREG)　ｕｓｅｄ　ｔｈｅ　ｊａｉｌ　ｋｅｙ．）
;jpn:◆（@DSP_LCNAME()は↓
;jpn:　ろうやのカギを　つかった）
@KEY()↓
@CLOSEALL()
@SE(SE_se77_my_open_locker)
@HIDE_CHAR(PRSN_GRFD_CABIN_WATCH_3A,OBJFX_HIDE_NONE)
@WI( 60 )
@OPEN( 1 )
MSG_GRFD_POLA_LATER_USEKEY;
;牢内のポーラ
◆Ｔｈａｎｋ　ｙｏｕ，　@DSP_NAME(PC_NESS)！@KEY()↓
◆Ｙｏｕ’ｒｅ　ｊｕｓｔ　ｌｉｋｅ　Ｉ　ｉｍａｇｉｎｅｄ　ｙｏｕ　ｗｏｕｌｄ　ｂｅ．．．@KEY()↓
◆Ｉ’ｍ　ｓｕｒｅ　ｔｈａｔ　ｓｏｍｅ　ｐｅｏｐｌｅ　ｉｎ　Ｔｗｏｓｏｎ　ａｒｅ　ｗｏｒｒｉｅｄ　ａｂｏｕｔ　ｍｅ．．．@KEY()↓
◆Ｇｅｔｔｉｎｇ　ｂａｃｋ　ｔｈｅｒｅ　ｍａｙ　ｂｅ　ｄａｎｇｅｒｏｕｓ，@KEY()↓
◆ｂｕｔ　ｗｅ　ｃａｎ　ｄｏ　ｉｔ　ｉｆ　ｗｅ　ｃｏｍｂｉｎｅ　ｏｕｒ　ｓｔｒｅｎｇｔｈ．@KEY()↓
◆Ｉ’ｍ　ａｂｌｅ　ｔｏ　ｕｓｅ　ａ　ｌｉｔｔｌｅ　ｐｓｙｃｈｉｃ　ｐｏｗｅｒ　ｔｈａｔ　ｉｓ　ａｃｔｕａｌｌｙ　ｐｒｅｔｔｙ　ｄｅａｄｌｙ．．．@KEY()↓
◆Ｌｅｔ’ｓ　ｈｅａｄ　ｂａｃｋ　ｔｏ　Ｔｗｏｓｏｎ！
;jpn:◆ありがとう　@DSP_STS(STS_PC_NAME_NES)！↓
;jpn:　わたしのおもったとおりの↓
;jpn:　ひとだったわ！@KEY()↓
;jpn:◆ほんとに　ありがとう。@WI(30)↓
;jpn:　ツーソンのひとたちが　きっと↓
;jpn:　しんぱいしてるとおもうの。@KEY()↓
;jpn:◆かえりみちも↓
;jpn:　きっと　あぶないけれど@KEY()↓
;jpn:◆ふたりで　ちからをあわせて↓
;jpn:　なんとか　もどりましょう。@KEY()↓
;jpn:◆‥‥わたし　ちょっとくらいなら↓
;jpn:　アブナイちょうのうりょくを↓
;jpn:　つかえるのよ。@KEY()↓
;jpn:◆がんばって　ツーソンまで↓
;jpn:　かえりましょうね。
@KEY()
@CLOSEALL()
@REMOVE_CHAR(PRSN_GRFD_CABIN_WATCH_A,ANIM_GRFD_POLA_ADD_PARTY);ポーラ仲間に
@WAITSYS()
;ぬいぐるみ消す
@HIDE_CHAR( PRSN_GRFD_CABIN_WATCH_B, OBJFX_HIDE_NONE )
@WAITSYS()
;ポーラを仲間に
@HIDE_CHAR( PRSN_GRFD_CABIN_WATCH_A, OBJFX_HIDE_NONE )
@ADD_PARTY( PC_PAULA )
@BGMSTART(0,BGM_friend)
@WI(120)
@WI(120)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_child)
@OPEN(1)
◆@DSP_NAME(PC_PAULA)　ｊｏｉｎｅｄ　ｙｏｕ．
;jpn:◆（@DSP_STS(STS_PC_NAME_PAULA)が↓
;jpn:　なかまになった）
@KEY()
@CLOSEALL()
@SETF(FLG_POLA_GRFD)
@SETF(FLG_WARP_GRFD_YAMAGOYA)
@CLRF(FLG_TWSN_PAUL_UPSET)
@SETF(FLG_TWSN_INFO_TONCHIKI);慌てポーラ父にあっていない場合、この台詞を聞いてもトンチキに会える
@SETF(FLG_MYHOME_PHONE_PAULA);ママの電話メッセージ切り替え用
@SETF(FLG_PHOTO_CABIN);撮り頃フラグ
』

_GRFD_YAMAGOYA_RECEIVE_X;
◆（Ｙｏｕ　ｍｕｓｔ　ｕｓｅ　ｔｈｅ　Ｍｏｕｎｔａｉｎ　Ｃａｂｉｎ　Ｋｅｙ　ｔｏ　ｏｐｅｎ　ｔｈｉｓ．）
;jpn:◆（ろうやのカギ　でないと↓
;jpn:　ここは　あかない）
@KEYNP()
@CLOSEALL()
』

;--------------------------------------------------------


;#38	ポーラ父との別れ	2.9	T

;★ポーラ父のセリフ _TWSN_PAUL_OK でポーラを仲間にした後、
;ポーラの父が未練がましくポーラを手放したがらない様子を演出したい。
;★「ぬいぐるみ」を所持しているときのように、移動するとポーラの父が
;ずるずるとついてくる。数歩移動したら切り離して、MSG_TWSN_PAUL_OK1 を発行。

MSG_EVT_PAURA_FATHER_WAKARE;
@COLD_CHAR(PRSN_TWSN_POLA_FRONT_A)
MSG_TWSN_PAUL_OK;
@SET_LOOPREG(PC_PAULA)			;ポーラのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_EVT_PAURA_FATHER_WAKARE_DEAD)
@OPEN(1)
◆Ｏｈ　@DSP_NAME(PC_PAULA)！
;jpn:◆おお！@WI(20)　@DSP_STS(STS_PC_NAME_PAULA)！
@KEY()
@CLOSEALL()
@GET_PLAYER_DIR(PC_NESS,2,PRSN_TWSN_POLA_FRONT_A)
@SET_PLAYER_DIR(0,0)
@GET_PLAYER_DIR(PC_PAULA,2,PRSN_TWSN_POLA_FRONT_A)
@SET_PLAYER_DIR(0,0)
@FRESH_CHAR(PRSN_TWSN_POLA_FRONT_A)
@WAITSYS()
@COLD_CHAR( PRSN_TWSN_POLA_FRONT_A )
@SET_CHAR_DIR(PRSN_TWSN_POLA_FRONT_A,DIR_M_RIGHT)	;追加・上野(Jul.15,1994)
@OPEN(1)
@SET_LOOPREG(PC_NESS)			;ネスのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_EVT_PAURA_FATHER_NES_DEAD)
◆@DSP_NAME(PC_NESS)，　ｔｈａｎｋ　ｙｏｕ　ｓｏ　ｍｕｃｈ！@KEY()↓
◆Ｙｏｕ　ｍｕｓｔ　ｂｅ　ｔｈｅ　ｂｏｙ　ｗｈｏ　ｗｉｌｌ　ｓａｖｅ　ｔｈｅ　ｗｏｒｌｄ，　ｌｉｋｅ　ｉｎ　@DSP_NAME(PC_PAULA)’ｓ　ｄｒｅａｍ．@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)くん↓
;jpn:　ありがとうよ。@KEY()↓
;jpn:◆たしかに　きみは↓
;jpn:　@DSP_STS(STS_PC_NAME_PAULA)が　ゆめでみたとおりの@KEY()↓
;jpn:◆せかいをすくう　しょうねんかも↓
;jpn:　しれないぞ。@KEY()↓
_TWSN_PAULA_PAPA_WAKARE_MAIN;
◆@DSP_NAME(PC_PAULA)，　Ｉ’ｍ　ｓｕｒｅ　ｙｏｕ’ｄ　ｂｅ　ａ　ｂｉｇ　ｈｅｌｐ　ｔｏ　@DSP_NAME(PC_NESS)．@KEY()↓
◆Ｉｔ’ｓ　ｎｏｔ　ｅｖｅｒｙ　ｄａｙ　ａ　ｆａｔｈｅｒ　ｌｅｔｓ　ｈｉｓ　ｄａｕｇｈｔｅｒ　ｅｍｂａｒｋ　ｏｎ　ａ　ｊｏｕｒｎｅｙ　ｔｏ　ｓａｖｅ　ｔｈｅ　ｗｏｒｌｄ！
;jpn:◆@DSP_STS(STS_PC_NAME_PAULA)@WI(20)　@DSP_STS(STS_PC_NAME_NES)くんの↓
;jpn:　ちからになって　あげなさい。@KEY()↓
;jpn:◆パパは　よろこんで　おまえを↓
;jpn:　たびに　だすつもりだ。
@KEY()
@CLOSEALL()
;@SE(SE_se10_present_open)
@SETF(FLG_POLA)
;
;父との別れの時のポーラのセリフ
@GET_PLAYER_DIR(PC_PAULA,2,PRSN_TWSN_POLA_FRONT_A)
@SET_PLAYER_DIR(PC_PAULA,0)
@SHOW_MANPU_PLAYER( PC_PAULA, MANPU_SURPRISE )
@WI(60)
@HIDE_MANPU_PLAYER( PC_PAULA )
@OPEN(1)
◆Ｄａｄ，　ｄｏｎ’ｔ　ｗｏｒｒｙ　ａｂｏｕｔ　ｍｅ．@KEY()↓
◆@DSP_NAME(PC_NESS)　ａｎｄ　Ｉ　ｗｉｌｌ　ｂｅ　ａｂｌｅ　ｔｏ　ｔａｋｅ　ｃａｒｅ　ｏｆ　ｏｕｒｓｅｌｖｅｓ．@KEY()↓
◆Ｉｎ　Ｔｈｒｅｅｄ，　ｔｈｅ　ｎｅｘｔ　ｔｏｗｎ，　ｗｅ’ｌｌ　ｍｅｅｔ　ａｎｏｔｈｅｒ　ｆｒｉｅｎｄ．@KEY()↓
◆Ｉｆ　ｔｈｅ　ｔｈｒｅｅ　ｏｆ　ｕｓ　ｃａｎ　ｃｏｍｂｉｎｅ　ｏｕｒ　ｐｏｗｅｒ，　ｎｏ　ｏｎｅ　ｃａｎ　ｂｅａｔ　ｕｓ．@KEY()↓
◆Ｎｏｗ　ｗｉｐｅ　ｙｏｕｒ　ｅｙｅｓ，　ｂｌｏｗ　ｙｏｕｒ　ｎｏｓｅ，　ａｎｄ　ｓｍｉｌｅ　ｂｅｆｏｒｅ　ｗｅ　ｔａｋｅ　ｏｆｆ．
;jpn:◆パパ　しんぱいしないでね。@WI(20)↓
;jpn:　わたしだけじゃなくて↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)も　ついているし@KEY()↓
;jpn:◆たぶん　つぎのスリークのまちで↓
;jpn:　もうひとりの　なかまにも↓
;jpn:　あえるはずよ。@KEY()↓
;jpn:◆この　３にんで↓
;jpn:　ちからを　あわせれば@KEY()↓
;jpn:◆きっと　どんなことにも↓
;jpn:　まけないわ。@KEY()↓
;jpn:◆‥‥ね。@KEY()↓
;jpn:◆だから　はなみずをふいて↓
;jpn:　わらって　おくってちょうだい。
@KEY()
@CLOSEALL()
@SETF(FLG_TWSN_MESSENGER_APPEAR);チンピラメッセンジャー出現
@FUNC(5)			;毒死配達禁止
@WI(10)
MSG_TWSN_PAUL_OK1;
@OPEN(1)
◆Ｇｏｏｄｂｙｅ　@DSP_NAME(PC_PAULA)．@KEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｒｙ，　Ｉ　ｗｏｎ’ｔ　ｃｒｙ　ａｎｙｍｏｒｅ．．．
;jpn:◆さらば　@DSP_STS(STS_PC_NAME_PAULA)！↓
;jpn:　パパ@WI(20)　ないてなんかいないぞ。
@KEYNP()
@CLOSEALL()
;２度話したらパパをうろうろ動きに（ハマり防止）
@CHKFGOTO( FLG_TEMP_0, _TWSN_PAUL_OK1_2ND )
_TWSN_PAUL_OK1_1ST
@SETF( FLG_TEMP_0 )
』
_TWSN_PAUL_OK1_2ND
@REMOVE_CHAR( PRSN_TWSN_POLA_FRONT_A, ANIM_PEOPLEWALK1_LIVE )
』

_EVT_PAURA_FATHER_WAKARE_DEAD;
@OPEN(1)
◆Ｏｈ，　@DSP_NAME(PC_PAULA)！@KEY()↓
◆．．．@KEY()↓
◆Ａｍ　Ｉ　ｄｒｅａｍｉｎｇ？↓
　　Ｉ　ｆｅｅｌ　ｌｉｋｅ　ｓｈｅ　ｊｕｓｔ　ｃａｍｅ　ｈｏｍｅ．．．
;jpn:◆おお　@DSP_STS(STS_PC_NAME_PAULA)！@KEY()↓
;jpn:◆‥‥‥。@KEY()↓
;jpn:◆きのせいだったのか‥‥。@WI(60)↓
@SET_CHAR_DIR(PRSN_TWSN_POLA_FRONT_A,DIR_M_RIGHT)
;jpn:　いま　@DSP_STS(STS_PC_NAME_PAULA)が↓
;jpn:　かえってきたようなきがしたが‥‥
@KEY()
@SE(SE_se08_door_in)
@CLOSEALL()
@WI(20)
@SE(SE_se09_door_out)
@HIDE_CHAR(PRSN_TWSN_POLA_FRONT_A,OBJFX_HIDE_NONE)
』;駆け込んできて、セリフ後石になり、とぼとぼ出て行く

_EVT_PAURA_FATHER_NES_DEAD;ネス気絶時
◆Ｗｈｅｒｅ’ｓ　@DSP_NAME(PC_NESS)？@KEY()↓
◆Ｈｅ　ｉｓｎ’ｔ　ｈｅｒｅ？↓
　　Ｉ　ｊｕｓｔ　ｗａｎｔｅｄ　ｔｏ　ｔｈａｎｋ　ｈｉｍ．@KEY()↓
◆Ｙｏｕ　ｋｎｏｗ，　Ｉ　ｂｅｔ　ｈｅ’ｓ　ｔｈｅ　ｂｏｙ　ｙｏｕ　ｄｒｅａｍｔ　ｗｏｕｌｄ　ｓａｖｅ　ｔｈｅ　ｗｏｒｌｄ．．．
;jpn:◆@DSP_STS(STS_PC_NAME_NES)くん‥‥は↓
;jpn:　いないのか‥‥？@KEY()↓
;jpn:◆いや@WI(10)　かれに　かんしゃしたいと↓
;jpn:　おもったんだが。@KEY()↓
;jpn:◆‥‥たしかに　あのコは↓
;jpn:　おまえが　ゆめでみたという@KEY()↓
;jpn:◆せかいをすくう　しょうねんかも↓
;jpn:　しれないな。
@KEY()↓
@GOTO(_TWSN_PAULA_PAPA_WAKARE_MAIN)

;----------------------------------------------------------------------


;#39	ミチコと楽屋潜入

;★カオス劇場／ホールの「ミーハーのミチコ」のセリフ（MSG_TWSN_MICHIKO）
;「一緒に来てくれる？」でプレイヤーキャラを牽引してホールから楽屋に移動する。

MSG_EVT_39_MICHIKO;
;（ホール）ミチコは楽屋へのドアへ
@FUNC(5)			;毒死配達禁止
@REMOVE_CHAR(PRSN_TWSN_CHAOS_HALL_A,ANIM_MICHIKO_INTO_ROOM);ミチコはドアへ
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_FOLLOW_TO_MICHIKO,OBJFX_SHOW_NONE);ついてく人
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI(1)
...;@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
...;@FRESH_PLAYER(PC_ALL)
...;@WAITSYS()			;ドアに入るのを待つ
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER(PC_ALL)
;（楽屋）ミチコは部屋の中央へ
@MOVE_GOM_CHAR( GOM_GIRL_A, ANIM_MICHIKO_INTO_ROOM_B, OBJFX_AFTER_WARP )
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_FOLLOW_TO_MICHIKO_B,OBJFX_AFTER_WARP);ついてく人
@WARP(WARP_TWSN_CHAOS_HALL_BACKS)
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI(1)
...;@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
...;@FRESH_PLAYER(PC_ALL)
...;@WAITSYS()			;中央に行くのを待つ
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER(PC_ALL)
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
;ミチコをうろうろ動作に
@HIDE_GOM_CHAR( GOM_GIRL_A, OBJFX_HIDE_NONE )
@MOVE_CHAR( PRSN_TWSN_CHAOS_BACKS_A, ANIM_PEOPLEWALK1, OBJFX_SHOW_NONE )
@FUNC(6)			;毒死配達許可
』

;-------------------------------------------------


;#40	トンズラの解放

;★カオス劇場／支配人の部屋の「劇場支配人ドッグフード氏」に
;「さつたば」を「つかう」と _TWSN_CHAOS_RECEIVE_SATUTABA をきっかけに
;トンズラブラザーズが入り口から登場する（ＢＧＭも切り替える）。
;★ゴージャス、ラッキー、ナイス、オッケー、
;グルービー（MSG_TWSN_TONZURA_GROOVY）の順にプレイヤーキャラに近づいて
;以下のオートメッセージを発行し、また扉から出て行く。

MSG_EVT_40_DOGFOOD;さつたばつかうのあと
@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを消す
@FUNC(5)			;配達禁止
@SETF(FLG_BGM_TONZURA_FREE)
@MUSISTART()
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_GORGEOUS_FREE,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_LUCKY_FREE,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_NICE,ANIM_NICE_FREE,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_OK,ANIM_OK_FREE,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GROOVE,ANIM_GROOVE_FREE,OBJFX_SHOW_NONE)
@CLOSEALL()
@RESF(FLG_TEMP_1)
@RESF(FLG_TEMP_2)
@RESF(FLG_TEMP_3)
@RESF(FLG_TEMP_4)
@RESF(FLG_TEMP_5)
;ゴージャスがネスに近づくまで待つ
@WAITSYS()
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_GORGEOUS_LATER)
@CLOSEALL()
@RESF(FLG_TEMP_1)
;ゴージャスが退出してラッキーが近づくまで待つ
@WAITSYS()
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_LUCKY_LATER)
@CLOSEALL()
@RESF(FLG_TEMP_2)
;ラッキーが退出してナイスが近づくまで待つ
@WAITSYS()
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_NICE_LATER)
@CLOSEALL()
@RESF(FLG_TEMP_3)
;ナイスが退出してオッケーが近づくまで待つ
@WAITSYS()
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_OKEY_LATER)
@CLOSEALL()
@RESF(FLG_TEMP_4)
;オッケーが退出してグルービーが近づくまで待つ
@WAITSYS()
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_GROOVY)
@CLOSEALL()
@RESF(FLG_TEMP_5)
;グルービーが退出するまで待つ
@WAITSYS()
』

MSG_TWSN_TONZURA_GORGEOUS_LATER;
◆Ｗｅｌｌ，　ｗｈａｔ　ｄｏ　ｙｏｕ　ｋｎｏｗ？@KEY()↓
◆Ｔｈｉｓ　ｌｉｔｔｌｅ　ｎｉｐｐｅｒ　ｔｏｏｋ　ｕｓ　ｆｒｏｍ　ａ　ｎｉｇｈｔｍａｒｅ　ｔｏ　ａ　ｄｒｅａｍ．．．
;jpn:◆なんてこったい。↓
;jpn:　こんなチビスケのおかげで↓
;jpn:　じごくから　てんごくだ。
@KEY()
』

MSG_TWSN_TONZURA_LUCKY_LATER;
◆Ｏｗ！↓
　　Ｔｈｉｓ　ｍｅａｎｓ　ｗｅ　ｃａｎ　ｇｅｔ　ｏｕｔ　ｏｆ　ｔｈｉｓ　ｄｕｍｐ！
;jpn:◆ブラボー！↓
;jpn:　このまちを　でられる。
@KEY()
』

MSG_TWSN_TONZURA_NICE_LATER;
◆Ｉ’ｍ　ａ　ｇｏｏｄ　ｄｒｉｖｅｒ．@KEY()↓
◆Ｃ’ｍｏｎ，　ｌｅｔ　ｍｅ　ｄｒｉｖｅ．
;jpn:◆わし　くるまのうんてん↓
;jpn:　とくいじゃけん。↓
;jpn:　まかせてくれんかのう。
@KEY()
』

MSG_TWSN_TONZURA_OKEY_LATER;
◆Ａｌｌ　ｒｉｇｈｔ，　ｌｅｔ’ｓ　ｍｏｖｅ　ｏｎ　ｔｏ　ｔｈｅ　ｎｅｘｔ　ｔｏｗｎ．@KEY()↓
◆Ｉ’ｍ　ｓｕｒｅ　ｔｈｉｓ　ｏｌ’　ｈｕｎｋ　ｏ’　ｊｕｎｋ　ｗｉｌｌ　ｇｅｔ　ｕｓ　ｔｈｅｒｅ．．．
;jpn:◆つぎのまちへ　レッツゴー！↓
;jpn:　さぁ　オンボロぐるまで　いこう。
@KEY()
』

;----------------------------------------


;#41	トンズラバスに乗る		T

;★トンズラを開放してカオス劇場からツーソンフィールドにワープすると
;劇場前の道路には黒塗りのトンズラバスが横付けされている。
;★列になったトンズラブラザーズが丁度
;バスに乗り込んでいる（バスに接触したら消去する）。
;jpn::★ラッキーだけが乗らずに、バスの前でプレイヤーキャラの接近するのを待つ。
;★プレイヤーキャラが接触したら、MSG_TWSN_TONZURA_NICE_LATER2 を
;発行して、プレイヤーを消し、ラッキー自身もバスに乗り（消えて）、
;バスは音楽とともに移動を開始する。

MSG_EVT_41_TONZURABUS_GORGEOUS;包囲網ににかかったら以下を発行
@SHOW_MANPU_CHAR(PRSN_TWSN_FIELD_S,MANPU_BIKKURI)
@WI(5)
@HIDE_MANPU_CHAR(PRSN_TWSN_FIELD_S)
@WI(5)
@SHOW_MANPU_CHAR(PRSN_TWSN_FIELD_S,MANPU_BIKKURI)
@WI(50)
@HIDE_MANPU_CHAR(PRSN_TWSN_FIELD_S)
@REMOVE_CHAR(PRSN_TWSN_FIELD_S,ANIM_GORGEOUS_CHAOUS)
@WAITSYS()
@COLD_CHAR(PRSN_TWSN_FIELD_S)
@GET_ORDER_PLAYER(1)
@GET_PLAYER_DIR(0,2,PRSN_TWSN_FIELD_S)
@SET_PLAYER_DIR(0,0)
@OPEN(1)
;MSG_TWSN_TONZURA_NICE_LATER2;
◆Ｈｕｒｒｙ　ａｎｄ　ｇｅｔ　ｏｎ！@KEY()↓
◆Ｏｕｒ　ｔｏｕｒ　ｂｕｓ　ｉｓ　ｔｏｏ　ｌｏｕｄ　ｆｏｒ　ｔｈｅ　ｇｈｏｓｔｓ！
;jpn:◆はやく　のらんかい。@KEY()↓
;jpn:◆わしらのトラベリンバスには↓
;jpn:　おばけとやらも↓
;jpn:　うるそうて　でるまくが　ないわ。
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TO_GORGEOUS_CHAOUS,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@FRESH_CHAR(PRSN_TWSN_FIELD_S)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@SET_CAMERA_PARTY()
@SET_HIT_RECT(1,HRECT_TWSN_TONZURABUS,MSG_EVT_41_TONZURABUS_GORGEOUS)
』

MSG_EVT_RIDE_TONZURABUS_CHAOUS;トンズラバスに近づくと以下を発行
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
@FUNC(5)			;配達禁止
@SETF(FLG_TWSN_TONZURA_GO)	;トンズラバスに乗ったフラグ（トンネル通行可）
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_TONZURABUS_CHAOUS,OBJFX_SHOW_NONE);乗車する透明人間
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@CLRF(FLG_BGM_TONZURA_FREE)
@SETF(FLG_BGM_TBUS)
@MUSISTART()
;@BGMSTART(0,BGM_tonz2)
@COLD_PLAYER(PC_ALL)
@REMOVE_CHAR(PRSN_TWSN_FIELD_S,ANIM_GORGEOUS_CHAOUS_RIDE)
@WAITSYS()
@CLRF(FLG_TWSN_TONZURABUS_APPEAR);トンズラバスを消す
@OPEN(1)
@GOSUB(MSG_TWSN_TONZURA_NICE_LETSGO)
@CLOSEALL()
@REMOVE_CHAR(PRSN_TWSN_FIELD_4B,ANIM_TONZURABUS_TO_THRK)
@WI(60)
@SET_CAMERA_CHAR(PRSN_TWSN_FIELD_4B)
@FRESH_PLAYER(PC_ALL)
@RES_HIT_RECT(1)
』

MSG_TWSN_TONZURA_NICE_LETSGO;
◆Ｏｋａｙ，　ｇｕｙｓ　ｈｅｒｅ　ｗｅ　ｇｏ！
;jpn:◆さぁ　ノリノリで　いくぜい！
@KEY()
』

MSG_EVT_TONZURABUS_CHAOUS;
@OPEN(1)
◆Ｈｅｙ，　ｓｉｄｅｗａｌｋ！　Ｇｅｔ　ｏｕｔ　ｏｆ　ｍｙ　ｗａｙ！
;jpn:◆じゃまな　ほどうじゃのう！
@KEY()
@CLOSEALL()
』

MSG_EVT_TBUS_TO_THRK_TUNNEL;トンネルへ
@SET_CAMERA_PARTY()
@SETF(FLG_TUNNEL_TWSN_THRK_TR);トンネルゴースト管理用フラグのセット
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TO_THRK_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TWSN_TUNNEL)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

;MSG_EVT_TBUS_TUNNEL_HWAY_R;トンネルからハイウェイへ
;@SET_CAMERA_PARTY()
;@WARP(WARP_BUS_TUNNEL_HWAY_R)
;@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TUNNEL_HWAY_R,OBJFX_SHOW_NONE)
;@WI(1)
;@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
;』

;MSG_EVT_TBUS_HWAY_TUNNEL_R;ハイウェイからトンネルへ
;@SET_CAMERA_PARTY()
;@WARP(WARP_BUS_HWAY_TUNNEL_R)
;@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_HWAY_TUNNEL_R,OBJFX_SHOW_NONE)
;@WI(1)
;@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
;』

MSG_EVT_TBUS_INTO_THRK;トンネルからスリークへ
@SET_CAMERA_PARTY()
@CLRF(FLG_TUNNEL_TWSN_THRK_TR);トンネルゴースト管理用のフラグ解除
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_INTO_THRK,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_THRK_R)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TOUCH_THRK;スリークについた
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_TBUS_R,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_PLAYER_DIR(PC_NESS,DIR_M_DOWN)
@SET_PLAYER_DIR(PC_PAULA,DIR_M_DOWN)
@CLRF(FLG_BGM_TBUS)
@MUSISTART()
;@BGMSTART(0,BGM_kowa4)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
;ゴージャスを登場させる処理
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_OUT_TBUS_GORGEOUS,OBJFX_SHOW_NONE)	;バスから降りて
@WAITSYS()
;@SET_PLAYER_DIR(PC_NESS,DIR_M_RIGHT)
;@SET_PLAYER_DIR(PC_PAULA,DIR_M_RIGHT)
@WI(30)
;@SHOW_MANPU_GOM_CHAR(GOM_GORGEOUS,MANPU_SURPRISE)
@GOSUB(MSG_THRK_TONZURA_GORGEOUS)
;@HIDE_MANPU_GOM_CHAR(GOM_GORGEOUS)
@WI(20)
@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_INTO_TBUS_GORGEOUS)			;バスに乗り込む
@WAITSYS()
@WI(30)
;ナイス顔だけ
@SHOW_MANPU_GOM_CHAR(GOM_TONZURABUS,MANPU_NICE_RIGHT)
@WI(30)
@SET_PLAYER_DIR(PC_NESS,DIR_M_UP)
@SET_PLAYER_DIR(PC_PAULA,DIR_M_UP)
@WI(30)
@GOSUB(MSG_THRK_TONZURA_NICE)
@WI(30)
@HIDE_MANPU_GOM_CHAR(GOM_TONZURABUS)
@WI(30)
;トンズラバス発進
@FRESH_GOM_CHAR(GOM_TONZURABUS)
@WAITSYS()
@RES_HIT_RECT(1)
;@GOTO(MSG_GLOBAL_POWERSAVE_THRK)
@SET_COMEBACK_POS(TLPT_THREEK)
@SETF(FLG_TLPT_THRK)
@SETF(FLG_THRK_TUNNEL_CLOSE);ゲップ倒すまでスリークから出さない
@CLRF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させる
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』

;----------------------------------------


;#42	トンズラと別れる	5.1	T

;★スリークにバスが到着したら
;ゴージャスを外に出現させてから、プレイヤーキャラたちを外に出現させる。
;★ゴージャスはオートメッセージ MSG_THRK_TONZURA_GORGEOUS を発行して、
;再びバスに乗る（消去する）。その後、
;★バスの窓から「顔だけのナイス」を出現させて、MSG_THRK_TONZURA_NICE を発行。
;★バスは道路に沿ってフォーサイドの方向の画面外に消える。

;@Habitat:◆トンズラバス
;@Person:お別れゴージャス
;@Figure:ゴージャス
;@AppearanceKey:0
;@ActionScript:◆演出コンテ#5.1
;@Message:MSG_THRK_TONZURA_GORGEOUS
MSG_THRK_TONZURA_GORGEOUS;
@OPEN(1)
;トンズラのゴージャス
◆Ｌｏｏｋｓ　ｌｉｋｅ　ｗｅ　ｈａｖｅ　ｔｏ　ｓａｙ　ｇｏｏｄｂｙｅ　ｆｏｒ　ｎｏｗ．@KEY()↓
◆Ｔｈｉｓ　ｔｏｗｎ　ｓｅｅｍｓ　ｐｒｅｔｔｙ　ｇｌｏｏｍｙ，@KEY()↓
◆ｂｕｔ　Ｉ’ｍ　ｓｕｒｅ　ｙｏｕ　ｃａｎ　ｌｉｇｈｔ　ｕｐ　ｔｈｅ　ｐｌａｃｅ　ｗｉｔｈ　ｙｏｕｒ　ｏｗｎ　ｌｉｔｔｌｅ　ｂｒａｎｄ　ｏｆ　ｓｕｎｌｉｇｈｔ．．．
;jpn:◆とりあえずは　ここでおわかれだ。↓
;jpn:　このまちは　くらいムードだけど↓
;jpn:　あかるいきもちで　がんばれよ。
@KEY()
@CLOSEALL()
』


;@Habitat:◆トンズラバス
;@Person:お別れナイス
;@Figure:ナイス
;@AppearanceKey:0
;@ActionScript:◆演出コンテ#5.1
;@Message:MSG_THRK_TONZRA_NICE
MSG_THRK_TONZURA_NICE;
;トンズラのナイス
@OPEN(1)
◆Ｈｏｐｅ　ｔｏ　ｓｅｅ　ｙｏｕ　ａｇａｉｎ　ｓｏｍｅｔｉｍｅ．@KEY()↓
◆Ｌｏｏｋ　ｆｏｒ　ｕｓ　ｔｏ　ｂｅ　ｓｉｎｇｉｎｇ　ａｔ　ｓｏｍｅ　ｔｈｅａｔｅｒ　ｉｎ　Ｆｏｕｒｓｉｄｅ．．．
;jpn:◆またどこかで　あえると↓
;jpn:　ええのう。@KEY()↓
;jpn:◆わしらは　フォーサイドのまちの↓
;jpn:　どこかのげきじょうで↓
;jpn:　うたっとるはずじゃ‥‥。
@KEY()
;@ANIM(ANIM_START_TONZURABUS)
@CLOSEALL()
』

;----------------------------------------


;#43	ゾンビに捕まり気絶		T	こまわり君参照

;●スリークの墓場の地下ダンジョンへの道を塞いでいるゾンビと話すと
;ホテル前に「ビキニゾンビ」が出現する。
;★プレイヤーキャラが近づくとビキニゾンビは
;ホテルの入り口に移動し消える（MSG_EVT_BIKINI_X_NEAR_2）。

MSG_EVT_BIKINI_X_NEAR;入り口前へ移動開始
@FRESH_CHAR(PRSN_THRK_FIELD_X)
@WAITSYS()
』

MSG_EVT_BIKINI_X_NEAR_2;ホテル内へ
@FRESH_CHAR(PRSN_THRK_FIELD_X)
@WAITSYS()
@CLRF(FLG_THRK_BIKINIZOMBI_APPEAR)
@SETF(FLG_THRK_BIKINIZOMBI_F_APPEAR)
』

;★（後を追って）ホテルに入ると、フロントにいたビキニゾンビは
;廊下の入り口に移動して、消える（MSG_EVT_BIKINIZOMBI_F）。

MSG_EVT_BIKINIZOMBI_F;
;ネスが近づいたら左のドアに消える
@CLRF(FLG_THRK_BIKINIZOMBI_F_APPEAR)
@SETF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
』
;★（後を追って）廊下に移動すると、
;廊下にいたビキニゾンビは部屋１入り口に移動して消える。

MSG_EVT_BIKINIZOMBI_P;
;ネスが近づいたら左のドアに消える
@CLRF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
@SETF(FLG_THRK_HOTELZOMBI_APPEAR)
』
;★その後プレイヤーキャラが部屋１に入ったら、
;フラグ FLG_THRK_HOTELZOMBI_APPEAR によりゾンビたち出現し、
;（ワープメッセージ中の予約でプレイヤーに驚きの漫符を表示する。）
;ゾンビ、接近しながら暗転。効果音「ポカッ！」で
;MSG_THRK_FADEOUT を発行する。
;暗転後、ゾンビに連行されて墓地の地下牢に連れていかれるネス達。
;→ウィンタースのジェフ編スタート

MSG_EVT_HOTELZOMBI;ワープポイントで予約されたメッセージ（ワープ直後に起動）
@COLD_PLAYER(PC_ALL)
;プレイヤーに漫符表示他
@FUNC(5)			;配達禁止
@GET_ORDER_PLAYER(1)
@SHOW_MANPU_PLAYER(0,MANPU_BIKKURI)
@WI(60)
@HIDE_MANPU_PLAYER(0)
@FRESH_CHAR(PRSN_THRK_HOTEL_1_B)
@FRESH_CHAR(PRSN_THRK_HOTEL_1_C)
@FRESH_CHAR(PRSN_THRK_HOTEL_1_D)
@FRESH_CHAR(PRSN_THRK_HOTEL_1_E)
@BGM_EFFECT( 2 )	;フェードアウト
@WI(10)
;★BGM_cheng の合わせてフェードアウトする。暗くなると「ポカッ！」
@BGMSTART( 0, BGM_cheng )
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_STRIKE_NESS, OBJFX_SHOW_NONE )
@WAITSYS()
@WI( 120 )
MSG_THRK_FADEOUT;
@OPEN(1)
◆（Ｏｈ，　ｏｈ．．．ｙｏｕ’ｒｅ　ｌｏｓｉｎｇ　ｃｏｎｓｃｉｏｕｓｎｅｓｓ．．．@KEY()↓
◆Ｗｈａｔ　ｃｏｕｌｄ　ｂｅ　ｔｈｅ　ｆａｔｅ　ｏｆ　@DSP_NAME(PC_NESS)　ａｎｄ　ｈｉｓ　ｆｒｉｅｎｄｓ？）
;jpn:◆あー‥‥‥@WI(20)↓
;jpn:　いしきが　とおざかって　いく‥。@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)たちのうんめいや↓
;jpn:　いかに？！
@KEYNP()
@CLOSEALL()
;-----
@GOSUB(MSG_SUB_ALLHEAL_POWR)		;全回復しておく
@GOSUB(MSG_GLOBAL_DELIVERY_RESET)	;場面転換時に配達を中止
@SETF( FLG_SYS_MONSTER_OFF )		;ワンダリングモンスター出現禁止
;-----
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
;-----以降設定変更（連行イベントカット）
;
;; ホテルの外を連行されるネス達
;;-----
;;通行人を消しておく為の設定（すぐに戻す）
;@SETF(FLG_THRK_PEOPLE_DISAPPEAR)
;@SETF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
;@SETF(FLG_TLPT_FOUR)
;;-----
;@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_TAKE_NESS_KATACOMB_1A,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_TAKE_NESS_KATACOMB_1B,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_TAKE_NESS_KATACOMB_1C,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_BIKINI_B,ANIM_BIKINI_LOOK_NESS,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_NES_DOWN2,ANIM_NESS_FOLLOW_ZOMBI_1,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_POLA_DOWN2,ANIM_PAULA_FOLLOW_ZOMBI_1,OBJFX_AFTER_WARP)
;@WARP(WARP_THRK_HOTEL_OUTSIDE)
;;@WI(1)
;;@HIDE_CHAR(PRSN_THRK_FIELD_F, OBJFX_HIDE_NONE);GOM_BOY_A
;;@HIDE_CHAR(PRSN_THRK_FIELD_H, OBJFX_HIDE_NONE);GOM_CAP
;;@HIDE_CHAR(PRSN_THRK_FIELD_K, OBJFX_HIDE_NONE);GOM_OLDWOMAN
;;@HIDE_CHAR(PRSN_THRK_FIELD_C, OBJFX_HIDE_NONE);GOM_BOY_B
;; ぬいぐるみチェック
;;Q_HAVE(-1,)
;;
;;@WI(1)
;@SET_CAMERA_GOM_CHAR(GOM_NES_DOWN2)
;;@FRESH_PLAYER(PC_ALL)
;@WAITSYS()
;@SET_CAMERA_PARTY()
;;-----
;;通行人を消しておく為の設定解除
;@CLRF(FLG_THRK_PEOPLE_DISAPPEAR)
;@CLRF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
;@CLRF(FLG_TLPT_FOUR)
;;-----
;; 墓地の中を連行されるネス達
;@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_TAKE_NESS_KATACOMB_2A,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_TAKE_NESS_KATACOMB_2B,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_ZOMBIGHOST,ANIM_TAKE_NESS_KATACOMB_2C,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_NES_DOWN2,ANIM_NESS_FOLLOW_ZOMBI_2,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_POLA_DOWN2,ANIM_PAULA_FOLLOW_ZOMBI_2,OBJFX_AFTER_WARP)
;@WARP(WARP_THRK_KATACOMB)
;;@WI(1)
;;@SET_PALLETSET(31,0,1);真っ暗
;; ぬいぐるみチェック
;;Q_HAVE(-1,)
;;
;;@WI(1)
;@SET_CAMERA_GOM_CHAR(GOM_NES_DOWN2)
;;@FRESH_PLAYER(PC_ALL)
;@WAITSYS()
;@SET_CAMERA_PARTY()
;
;;-----以上カット
; 牢屋
;@DIS_BGMCHG();虫を無視
;@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_NES_DOWN,ANIM_NESS_STILL,OBJFX_AFTER_WARP)
@MOVE_GOM_CHAR(GOM_POLA_DOWN,ANIM_PAULA_STILL,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_THRK_KATACOMB)
@COLD_PLAYER(PC_ALL)
@WI(240)
@HIDE_GOM_CHAR(GOM_NES_DOWN,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_NESS,OBJFX_SHOW_NONE);ネス起き上がる
@WI(30)
@GET_PLAYER_DIR(PC_NESS,3,GOM_POLA_DOWN);ポーラを見る
@SET_PLAYER_DIR(PC_NESS,0)
@WI(20)
@HIDE_GOM_CHAR(GOM_POLA_DOWN,OBJFX_HIDE_NONE);ポーラ目覚める
@MOVE_GOM_CHAR(GOM_POLA,ANIM_MAPOBJSTILL,OBJFX_SHOW_NONE)
@WI(60)
@REMOVE_GOM_CHAR(GOM_POLA,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_POLA,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
』

MSG_EVT_PAULA_TELEPATHY_PRISON;牢屋の扉出ようとしたら‥‥ジェフに祈りを
;牢内で配達を呼んでも無駄
@GOSUB(MSG_GLOBAL_DELIVERY_RESET)	;場面転換時に配達を中止
@WI(60)
@SET_PLAYER_DIR(PC_PAULA,DIR_M_DOWN)
@WI(60)
;---------
@BGM_EFFECT(3)
;---------
;パーティ以外暗くする
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_EVT_FEEL_DIGGY, OBJFX_SHOW_NONE )
@WAITSYS()
@COLD_GOM_CHAR( GOM_HIT_CHR )
@WI(120)
@OPEN(1)
◆Ｉ’ｍ　ｃａｌｌｉｎｇ　ｏｕｔ　ｔｏ　ｙｏｕ　ｗｈｏ　Ｉ’ｖｅ　ｎｅｖｅｒ　ｍｅｔ．．．@KEY()↓
◆Ｉ’ｍ　ｃａｌｌｉｎｇ　ｏｕｒ　ｆｒｉｅｎｄ　ｗｈｏ　ｗｅ’ｖｅ　ｎｅｖｅｒ　ｍｅｔ．．．@KEY()↓
◆@DSP_NAME(PC_JEFF)！　@DSP_NAME(PC_JEFF)！↓
　　Ｗｅ　ｎｅｅｄ　ｙｏｕｒ　ｈｅｌｐ！@KEY()↓
◆Ｉ　ａｍ　@DSP_NAME(PC_PAULA)　ａｎｄ　Ｉ　ａｍ　ｗｉｔｈ　ａｎｏｔｈｅｒ　ｆｒｉｅｎｄ，　@DSP_NAME(PC_NESS)．．．@KEY()↓
◆Ｗｅ　ａｒｅ　ｔｒｙｉｎｇ　ｔｏ　ｃｏｎｔａｃｔ　ｙｏｕ．．．
;jpn:◆まだ　あったことのない↓
;jpn:　なかまに　よびかけます。@KEY()↓
;jpn:◆まだ　あったことのない↓
;jpn:　わたしたちのなかまに↓
;jpn:　よびかけます！@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)！@DSP_STS(STS_PC_NAME_JEFF)！↓
;jpn:　あなたの　たすけが　ほしい‥‥。@KEY()↓
;jpn:◆わたしは　@DSP_STS(STS_PC_NAME_PAULA)@WI(20)↓
;jpn:　そして　もうひとり　@DSP_STS(STS_PC_NAME_NES)‥‥@WI(20)↓
;jpn:　あなたに　よびかけています。
@KEYNP()@WI(30)
@CLOSEALL()
@WI(1)
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
;
;前準備
@HIDE_PLAYER( PC_ALL, OBJFX_HIDE_NONE )	;パーティ消す
;ウィンタース南のパンニングへ
@WARP( WARP_WINS_PANNING1 )
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_PANNING_WINTERS_1, OBJFX_SHOW_NONE )
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI( 1 )
...;@SET_CAMERA_GOM_CHAR( GOM_HIT_CHR )
...;@FRESH_PLAYER( PC_ALL )
...;@WAITSYS()
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER( PC_ALL )

;寄宿舎のパンニングへ
@WARP( WARP_WINS_PANNING2 )
@MOVE_GOM_CHAR( GOM_HIT_CHR ,ANIM_PANNING_WINTERS_2, OBJFX_SHOW_NONE )
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI( 1 )
...;@SET_CAMERA_GOM_CHAR( GOM_HIT_CHR )
...;@FRESH_PLAYER( PC_ALL )
...;@WAITSYS()
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER( PC_ALL )

;後処理
@CLRF( FLG_SYS_MONSTER_OFF )		;ワンダリングモンスター出現許可
@FUNC(6)			;配達許可
@GOTO(MSG_WINS_POLANESS)
』

;----------------------------------------


;#44	寄宿舎の部屋（夜）	8.1	T

;★スリークでビキニゾンビの罠にはまったら、プレイヤーキャラを
;ウィンタースのジェフに交代する。
;★ウィンタース／寄宿舎／ジェフの部屋からスタート。
;★まず、MSG_WINS_POLANESS を発行。ジェフとトニーはベッドで寝ている。

;★MSG_WINS_POLANESS が終わった後で（FLG_WINS_START/on）
;キー入力があったら、ジェフはベッドを出て立ち上がる（寝ているジェフを消す）。

;★ジェフの部屋から外に出ようとすると（ワープ時メッセージで）
;MSG_WINS_TONY_WAKEUP を発行。その後
;★トニーを扉の前のプレイヤーキャラの前に移動させて、
;セリフ MSG_WINS_TONY を発行。

MSG_WINS_POLANESS;
;ジェフの寝室へ
@WARP(WARP_WINS_JEFF_START)
@COLD_PLAYER( PC_ALL )
@SAVE_STORY()
;ジェフのストーリーへ移行する為の処理
@ADD_PARTY(PC_JEFF)		;ジェフ加入
@MONEYIN( 2 )			;２ドル持たせる
@DEL_PARTY(PC_NESS)		;ネス脱退
@DEL_PARTY(PC_PAULA)		;ポーラ脱退
@CLRF(FLG_THRK_HOTELZOMBI_APPEAR)
@CLRF(FLG_THRK_HOTELMAN_DISAPPEAR)	;ホテルマンを出現させる
@SETF(FLG_WINS_POLA_TELEPATHY)		;ポーラのテレパシーセット
@WI( 180 )
;ポーラとネスの声
@OPEN(1)
;◆まだ　あったことのない↓
;　なかまに　よびかけます。@KEY()↓
;◆まだ　あったことのない↓
;　わたしたちのなかまに↓
;　よびかけます！@KEY()↓
;◆@DSP_STS(STS_PC_NAME_JEFF)！@DSP_STS(STS_PC_NAME_JEFF)！↓
;　あなたの　たすけが　ほしい‥‥。@KEY()↓
◆Ｉ　ａｍ　@DSP_NAME(PC_PAULA)，　ａｎｄ　Ｉ　ａｍ　ｗｉｔｈ　ａｎｏｔｈｅｒ　ｆｒｉｅｎｄ，　@DSP_NAME(PC_NESS)．．．@KEY()↓
◆Ｗｅ　ａｒｅ　ｔｒｙｉｎｇ　ｔｏ　ｃｏｎｔａｃｔ　ｙｏｕ．．．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｈｅａｒ　ｍｅ，　ｐｌｅａｓｅ　ｗａｋｅ　ｕｐ　ａｎｄ．．．@KEY()↓
◆ｈｅａｄ　ｓｏｕｔｈ！@KEY()↓
◆Ｏｎｌｙ　ｙｏｕ，　ｔｈｏｕｇｈ　ｆａｒ　ａｗａｙ，　ｃａｎ　ｓａｖｅ　ｕｓ，↓
　　@DSP_NAME(PC_JEFF)．．．@KEY()↓
◆Ｐｌｅａｓｅ　ｈｅａｒ　ｍｙ　ｃａｌｌ　ａｎｄ　ｂｅｇｉｎ　ｈｅａｄｉｎｇ　ｓｏｕｔｈ．．．@KEY()↓
◆@DSP_NAME(PC_JEFF)！　　Ｙｏｕ　ａｒｅ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　ｗｅ’ｖｅ　ｎｅｖｅｒ　ｍｅｔ．．．@KEY()↓
◆Ｂｕｔ　ｙｏｕ　ａｒｅ　ｏｕｒ　ｏｎｅ　ａｎｄ　ｏｎｌｙ　ｈｏｐｅ！．．．
;jpn:◆わたしは　@DSP_STS(STS_PC_NAME_PAULA)@WI(20)↓
;jpn:　そして　もうひとり　@DSP_STS(STS_PC_NAME_NES)‥‥@WI(20)↓
;jpn:　あなたに　よびかけています。@KEY()↓
;jpn:◆このよびかけが　きこえたら↓
;jpn:　めを　あけて！@KEY()↓
;jpn:◆そして‥‥@WI(20)↓
;jpn:　みなみに　むかって↓
;jpn:　しゅっぱつして　ください。@KEY()↓
;jpn:◆とおくにいる　あなただけが↓
;jpn:　わたしたちを　すくえるのよ。↓
;jpn:　@DSP_STS(STS_PC_NAME_JEFF)！@KEY()↓
;jpn:◆このこえを　しんじて↓
;jpn:　おきあがって　あるきだして！↓
;jpn:　みなみにむかって‥‥@WI(20)すぐに！@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)　おねがい！↓
;jpn:　まだ　あったことのない‥‥@WI(20)↓
;jpn:　かけがえのない‥‥@WI(20)なかま！
@KEY()
@CLOSEALL()
;---------
@BGM_EFFECT(3)		;ＢＧＭフェードアウト長め
@WI( 120 )
;---------
@WI( 180 )
@HIDE_CHAR(PRSN_WINS_DORM_JEFF_B,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@SETF(FLG_WINS_START)
@SET_COMEBACK_POS(TLPT_WINTERS)
@CLRF(FLG_THRK_BIKINIZOMBI_P_APPEAR)
@CLRF(FLG_SYS_MONSTER_OFF)
@SETF(FLG_TLPT_WINS)
』

MSG_EVT_WAKEUP_TONY;
MSG_WINS_TONY_WAKEUP;
;ポーラのよびかけに応えてジェフが出かけようと
;すると、ドアの前に急に立ちふさがる（ジェフが一歩
;あるくと、目ざめて先回りする感じ）。ホモっぽいやつさ。
@SHOW_MANPU_CHAR( PRSN_WINS_DORM_JEFF_A, MANPU_BIKKURI )
@WI( 60 )
@HIDE_MANPU_CHAR( PRSN_WINS_DORM_JEFF_A )
@WI( 30 )
@HIDE_CHAR(PRSN_WINS_DORM_JEFF_A,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_TONY,ANIM_WAKEUP_TONY,OBJFX_SHOW_NONE)
@WI(1)
@COLD_GOM_CHAR(GOM_TONY)
@OPEN(1)
◆@DSP_NAME(PC_JEFF)，　ｗｈｅｒｅ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｉｎ　ｔｈｅ　ｍｉｄｄｌｅ　ｏｆ　ｔｈｅ　ｎｉｇｈｔ？
;jpn:◆@DSP_STS(STS_PC_NAME_JEFF)！　こんなよなかに↓
;jpn:　どこへいくんだい？
@KEY()↓
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_TONY)
@WAITSYS()
@COLD_GOM_CHAR(GOM_TONY)
MSG_WINS_TONY;
@OPEN(1)
◆Ｙｏｕ　ｋｎｏｗ　ｔｈｅ　ｄｏｒｍ　ｒｕｌｅｓ，　ｒｉｇｈｔ？@KEY()↓
◆Ｉｆ　ｙｏｕ　ｇｅｔ　ｃａｕｇｈｔ，　ｙｏｕ’ｌｌ　ｇｅｔ　ｐｕｎｉｓｈｅｄ　ｂｉｇ　ｔｉｍｅ．．．@KEY()↓
◆Ｗ．．．ｗｈａｔ’ｓ　ｗｒｏｎｇ，　@DSP_NAME(PC_JEFF)．
;jpn:◆このきしゅくしゃのルールは↓
;jpn:　しってるはずだろう？↓
;jpn:　みつかったら　しりたたきだよ。@KEY()↓
;jpn:◆‥‥どうしたのさ　@DSP_STS(STS_PC_NAME_JEFF)！
@KEY()↓
@GET_PLAYER_DIR(PC_JEFF,3,GOM_TONY);ジェフ、トニーの方を向く
@SET_PLAYER_DIR(PC_JEFF,0)
◆．．．Ａｌｌ　ｒｉｇｈｔ．@KEY()↓
◆Ｔｈｅｒｅ　ｍｕｓｔ　ｂｅ　ｓｏｍｅ　ｒｅａｓｏｎ　ｔｈａｔ　Ｉ　ｄｏｎ’ｔ　ｕｎｄｅｒｓｔａｎｄ．@KEY()↓
◆Ｉ　ｗｏｎ’ｔ　ｓｔｏｐ　ｙｏｕ．@KEY()↓
◆Ｂｕｔ　ｉｔ’ｓ　ｄａｎｇｅｒｏｕｓ　ｔｏ　ｌｅａｖｅ　ｗｉｔｈｏｕｔ　ｔａｋｉｎｇ　ａｎｙｔｈｉｎｇ　ａｌｏｎｇ．@KEY()↓
◆Ｈｅｙ，　Ｉ　ｔｈｉｎｋ　ｔｈｅｒｅ’ｓ　ｓｏｍｅ　ｓｔｕｆｆ　ｉｎ　ｔｈｅ　ｌｏｃｋｅｒ　ｒｏｏｍ　ｔｈａｔ　ｙｏｕ　ｓｈｏｕｌｄ　ｇｅｔ．@KEY()↓
◆Ｉ’ｌｌ　ｈｅｌｐ　ｙｏｕ　ｇｅｔ　ｏｕｔ　ｏｆ　ｈｅｒｅ．．．
;jpn:◆‥‥@KEY()↓
;jpn:◆わかったよ。↓
;jpn:　ぼくにはわからない　りゆうが↓
;jpn:　あるんだろうね。@KEY()↓
;jpn:◆とめないことにするよ。@KEY()↓
;jpn:◆でも　なんにせよ　まよなかに↓
;jpn:　むぼうびで　でかけるのは↓
;jpn:　きけんだよ。@KEY()↓
;jpn:◆みをまもるどうぐを↓
;jpn:　もっていくほうがいい。@KEY()↓
;jpn:◆ロッカールームに↓
;jpn:　なにかあると　おもうから↓
;jpn:　よっていくといいよ。@KEY()↓
;jpn:◆いっしょに　いってあげるよ。
@KEY()
@CLOSEALL()
@ADD_PARTY(PC_TONY)
@HIDE_PLAYER(PC_TONY,OBJFX_HIDE_NONE)
@REMOVE_GOM_CHAR(GOM_TONY,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_TONY,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_TONY,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
;@MUSISTART()			;ウィンドウ閉じるまでは無音
;@BGMSTART(0,BGM_msc7)
@OPEN(1)
◆（Ｔｏｎｙ　ｊｏｉｎｅｄ　ｙｏｕ．）
;jpn:◆（トニーが　なかまになった）
@KEY()
@CLOSEALL()
@SETF(FLG_WINS_TONY)
;
@MUSISTART()
』

;------------------------------------------


;#45	寄宿舎を脱出（フェンス越え）

;★プレイヤーキャラが寄宿舎の（唯一の出口となる）フェンスに近づくと
;MSG_WINS_TONY_WALLを発行（ジェフにトニーの方向を向かせる）。
;★_WINS_TONY_WALL_GO でトニーを踏み台にして、フェンスを越える。
;フェンスを越える演出の詳細は未定。


MSG_WINS_TONY_WALL;包囲網に触れたら
;学校からの出口となる壁に近づくと
@Q_HAVE(PC_ALL,GDS_EQUIP_GUN_BANBAN)
@TRUE_GOTO(_WINS_TONY_WALL_TONY)
@SET_PLAYER_DIR(PC_TONY,DIR_M_DOWN)
@GET_PLAYER_DIR(PC_JEFF,1,PC_TONY)
@SET_PLAYER_DIR(PC_JEFF,0)
@OPEN(1)
◆Ｉ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｇｅｔ　ｏｕｔ　ｂｙ　ｇｏｉｎｇ　ｏｖｅｒ　ｔｈｅ　ｇａｔｅ．．．@KEY()↓
◆Ｂｕｔ　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｇｅｔ　ｓｏｍｅ　ｓｔｕｆｆ　ｔｏ　ｔａｋｅ　ｗｉｔｈ　ｙｏｕ．
;jpn:◆あのフェンスから　そとに↓
;jpn:　でられそうだけどなぁ‥‥。@KEY()↓
;jpn:◆でも　そのまえに↓
;jpn:　なにか　みをまもるものを↓
;jpn:　とってこなくちゃ。
@KEYNP()
@CLOSEALL()
』

_WINS_TONY_WALL_TONY;
@GOSUB(MSG_REMOVE_TONY);トニーを仲間から外す
@MOVE_GOM_CHAR(GOM_TONY,ANIM_DASH_TONY,OBJFX_SHOW_NONE)	;走るトニー
@WAITSYS()	;フェンスに到達待ち
@HIDE_GOM_CHAR(GOM_TONY,OBJFX_HIDE_NONE)
@MOVE_CHAR(PRSN_WINS_FIELD_J,ANIM_MAPOBJSTILL,OBJFX_SHOW_NONE)
@SETF(FLG_WINS_TONY_CROUCH_APPEAR)
』

MSG_WINS_TONY_WALL_GO;
◆Ｏｋａｙ，　ｎｏｗ　ｕｓｅ　ｍｅ　ａｓ　ａ　ｓｔｅｐ　ａｎｄ　ｃｌｉｍｂ　ｏｖｅｒ　ｔｈｅ　ｇａｔｅ．
;jpn:◆さぁ　ぼくをふみだいにして↓
;jpn:　このフェンスを　よじのぼるんだ。
@KEY()
@CLOSEALL()
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)	;ジェフ表示消す
@MOVE_GOM_CHAR(GOM_JEF_FALL,ANIM_JUMP_JEF,OBJFX_SHOW_NONE)　;ジャンプジェフ追加
@MOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_JUMP_JEF_S,OBJFX_SHOW_NONE);ジャンプジェフの影
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SHADOW_FALL)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()	;トニーの上に乗るのを待つ
@COLD_GOM_CHAR(GOM_JEF_FALL)
@COLD_GOM_CHAR(GOM_SHADOW_FALL)
@OPEN(1)
◆Ｗｅｌｌ．．．Ｉ’ｌｌ　ｓａｙ　ｇｏｏｄｂｙｅ　ｆｏｒ　ｎｏｗ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈｅｒｅ　ｙｏｕ’ｒｅ　ｇｏｉｎｇ　ｏｒ　ｗｈｙ，@KEY()↓
◆ｂｕｔ　ｒｅｍｅｍｂｅｒ，　ｗｅ　ａｒｅ　ｂｅｓｔ　ｆｒｉｅｎｄｓ　ｆｏｒｅｖｅｒ．
;jpn:◆とりあえず‥‥さよなら。@KEY()↓
;jpn:◆きみが　どこへいくのか↓
;jpn:　なにをしにいくのか　しらないけど↓
;jpn:　ぼくら　ずっと　しんゆうだぜ！
@KEY()
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_JEF_FALL)	;ジェフジャンプ
@FRESH_GOM_CHAR(GOM_SHADOW_FALL)	;ジェフジャンプの影
@WAITSYS()	;着地待ち
@SET_CAMERA_PARTY()
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)	;ジェフ表示戻す
@HIDE_CHAR(PRSN_WINS_FIELD_J,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_TONY,ANIM_OUT_TONY,OBJFX_SHOW_NONE)
@RES_HIT_RECT(1)
@SET_COMEBACK_POS(TLPT_WINTERS)
@CLRF(FLG_WINS_TONY_CROUCH_APPEAR)
;------------
@BGM_EFFECT(3)
@WI(120)
@SETF(FLG_BGM_WINT1)
@MUSISTART();ここからウィンターズの曲
;------------
@CLRF(FLG_SYS_MONSTER_OFF)
』

;------------------------------------------------
