
;#46	バルーンモンキー空中浮遊	8.3	T

;★「フーセンガム」GDS_FOOD_BUBBLE_GUM を「つかう」で
;呼び出されるスクリプトで、バルーンモンキーを空中に浮かべる。
;（バルーンモンキーのグラフィックをフーセンを膨らましているものに
;切り替え、縦方向に数キャラ程度移動させて、数秒後元に戻す。）
;★浮遊中は、地面に影のオブジェクトを置く必要があると思われる。

;「ガム」「つかう」で…

MSG_EVT_46_51_BALLOON;
@CHKF(FLG_BALLOONMONKEY)
@FALSE_GOTO(MSG_EVT_BALLOON_NG)
◆（Ｔｈｅ　ｂｕｂｂｌｅ　ｍｏｎｋｅｙ　ｔｏｏｋ　ａ　ｐｉｅｃｅ　ｏｆ　ｂｕｂｂｌｅ　ｇｕｍ，@KEY()↓
◆ｃｈｅｗｅｄ　ｉｔ　ａｎｄ　ｓｔａｒｔｅｄ　ｂｌｏｗｉｎｇ．）
;jpn:◆（バルーンモンキーは↓
;jpn:　フーセンガムを　いちまい↓
;jpn:　うばいとって　ふくらませた）
@KEY()
@CLOSEALL()
;@CHKFGOTO(FLG_BMONKEY_TASS,MSG_EVT_47_BMONKEY_FLOAT);タッシー渦出てる（ＨＲＥＣＴ化により不用）
@CHKFGOTO(FLG_BMONKEY_ROPE,MSG_EVT_51_BMONKEY_FLOAT);ロープの近くにいる
MSG_EVT_46_BMONKEY_FLOAT;
@HIDE_PLAYER(PC_BALLOONMONKEY,OBJFX_HIDE_NONE)	;バルモン表示だけ消す
@MOVE_GOM_CHAR(GOM_BMONKEY_GUM,ANIM_BMONKEY_GUM1,OBJFX_SHOW_NONE)
@WAITSYS()
@SE(SE_se0e_bmonky_up)
@HIDE_GOM_CHAR(GOM_BMONKEY_GUM,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_FLY,ANIM_BMONKEY_FLY,OBJFX_SHOW_NONE)	;浮遊猿
@MOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_BMONKEY_FLY_S,OBJFX_SHOW_NONE);浮遊猿の影
@WAITSYS()	;浮遊終了を待つ
@HIDE_GOM_CHAR(GOM_BMONKEY_FLY,OBJFX_HIDE_NONE)	;浮遊猿
@HIDE_GOM_CHAR(GOM_SHADOW_FALL,OBJFX_HIDE_NONE)	;浮遊猿の影
@SHOW_PLAYER(PC_BALLOONMONKEY,OBJFX_SHOW_NONE)
』
MSG_EVT_BALLOON_NG;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0)　ｃｈｅｗｅｄ　ａ　ｐｉｅｃｅ　ｏｆ　ｂｕｂｂｌｅ　ｇｕｍ，@KEY()↓
◆ｂｕｔ　ｉｔ　ｗａｓｎ’ｔ　ａｓ　ｓａｔｉｓｆｙｉｎｇ　ａｓ　ｆｏｏｄ．
;jpn:◆@DSP_NAME(0)は↓
;jpn:　フーセンガムを↓
;jpn:　いちまい　たべた。@KEY()↓
;jpn:◆しかし↓
;jpn:　フーセンガムは↓
;jpn:　はらの　たしにならなかった。
@KEYNP()
』
;初めてバルモンが浮遊する
;PARTY に加わっていないので別処理
MSG_EVT_46_BMONKEY_FLOAT_FIRST;
@ADD_PARTY(PC_BALLOONMONKEY)
@HIDE_PLAYER(PC_BALLOONMONKEY,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_WINS_DRUGSTORE_D,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_GUM,ANIM_BMONKEY_GUM,OBJFX_SHOW_NONE)
@WAITSYS()
@SE(SE_se0e_bmonky_up)
@HIDE_GOM_CHAR(GOM_BMONKEY_GUM,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_FLY,ANIM_BMONKEY_FLY,OBJFX_SHOW_NONE)	;浮遊猿
@MOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_BMONKEY_FLY_S,OBJFX_SHOW_NONE);浮遊猿の影
@WAITSYS()	;浮遊終了を待つ
@HIDE_GOM_CHAR(GOM_SHADOW_FALL,OBJFX_HIDE_NONE)	;浮遊猿の影
@HIDE_GOM_CHAR(GOM_BMONKEY_FLY,OBJFX_HIDE_NONE)	;浮遊猿
@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_ADDPARTY_BMONKEY,OBJFX_SHOW_NONE)
;@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_ADDPARTY,OBJFX_SHOW_NONE)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_BALLOONMONKEY,OBJFX_SHOW_NONE)
』

;-------------------------------------------------------------


;#47	タッシー登場

;★ウィンタース／フィールド／タッシー隊テントＡから外に出ると
;タッシーが水中から？登場する。
;●フラグで曲切り替え。

;タッシーに乗ってる時の曲@BGMSTART(0,BGM_tasy)乗った瞬間から
;
;岬の先端に近付くと MSG_WINS_MONKEY_GUM から発行
MSG_EVT_47_BMONKEY_FLOAT;
@RES_HIT_RECT(2)		;ガムくれサルの長方形消し
@SETF(FLG_SYS_MONSTER_OFF)
@FUNC(5)		;マップ上での全滅・配達禁止
@FRESH_CHAR(PRSN_WINS_FIELD_4A)
@FRESH_CHAR(PRSN_WINS_FIELD_4B)
;@HIDE_PLAYER(PC_BALLOONMONKEY,OBJFX_HIDE_NONE)       ;バルモン表示消す
@HIDE_GOM_CHAR(GOM_BMONKEY,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_GUM,ANIM_BMONKEY_GUM,OBJFX_SHOW_NONE)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY_GUM,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_FLY,ANIM_BMONKEY_TASSI_1A,OBJFX_SHOW_NONE);浮遊猿
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;移動待ち
@MOVE_GOM_CHAR(GOM_TACY_2,ANIM_TASSI_1,OBJFX_SHOW_NONE)　　　　　　;タッシー登場
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;浮き待ち
@RESF(FLG_TEMP_1)
@HIDE_GOM_CHAR(GOM_BMONKEY_FLY,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_BMONKEY_TASSI_1B,OBJFX_SHOW_NONE);猿はタッシーの頭に
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;さらに浮き待ち
@COLD_GOM_CHAR(GOM_TACY_2)
@COLD_GOM_CHAR(GOM_BMONKEY)
;
@RESF(FLG_WINS_TASSI_ENTER)　　　　　;画面外に出たうずが再度発生しないように
                                ;かつ、木の葉を消すため
@HIDE_CHAR(PRSN_WINS_FIELD_3A,OBJFX_HIDE_NONE)		;タッシーのマスク消し
@HIDE_CHAR(PRSN_WINS_FIELD_3B,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_WINS_FIELD_3C,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_WINS_FIELD_3M,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_WINS_FIELD_4A,ANIM_UZU_1_TASSI_BYE)
@REMOVE_CHAR(PRSN_WINS_FIELD_4B,ANIM_UZU_2_TASSI_BYE)
@WI(120)
;
@FRESH_GOM_CHAR(GOM_BMONKEY)
@FRESH_GOM_CHAR(GOM_TACY_2)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;タッシー岸に近づき右キー入力待つ
@COLD_GOM_CHAR(GOM_TACY_2)
@SETF(FLG_BGM_TASSY)
@MUSISTART()
;@BGMSTART(0,BGM_tasy)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_RIDE_TASSI_1,OBJFX_SHOW_NONE);タッシーに乗る人
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;乗り込み待ち
;
@SETF(FLG_TEMP_1)　　　　　　　　　　　　　　　　　　　　　　　;バルモンが前を向くフラグ設定
@WI(60)
@FRESH_GOM_CHAR(GOM_TACY_2)　　　　　　　　　　　　　;タッシー出発
@COLD_PLAYER(PC_JEFF)
;
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;タッシー岸に近づき左キー入力待つ
@COLD_GOM_CHAR(GOM_TACY_2)
@REMOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_TASSI_1)　　;タッシーから降りる人
@FRESH_PLAYER(PC_JEFF)
@RESF(FLG_TEMP_1)　　　　　　　　　　　　　　　　　　　　　　　;バルモンのアニメ変更
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@REMOVE_GOM_CHAR(GOM_BMONKEY,ANIM_BMONKEY_TASSI_1C)　　　　　;バルモンも降りる
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_BALLOONMONKEY,OBJFX_SHOW_NONE)
@WI(60)
;
@FRESH_GOM_CHAR(GOM_TACY_2)　　　　　　　　　　　　　;タッシー離れる
@WAITSYS()
;@MOVE_GOM_CHAR(GOM_UZU_1,ANIM_UZU_1_TASSI_BYE,OBJFX_SHOW_NONE)       ;うず
;@MOVE_GOM_CHAR(GOM_UZU_2,ANIM_UZU_2_TASSI_BYE,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_UZU_3,ANIM_UZU_3_TASSI_BYE_U,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_UZU_3,ANIM_UZU_3_TASSI_BYE_L,OBJFX_SHOW_NONE)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;沈み待ち
;
@HIDE_GOM_CHAR(GOM_TACY_2,OBJFX_HIDE_NONE)
;@HIDE_GOM_CHAR(GOM_UZU_1,OBJFX_HIDE_NONE)                    ;うず消す
;@HIDE_GOM_CHAR(GOM_UZU_2,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_WINS_FIELD_4A,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_WINS_FIELD_4B,OBJFX_HIDE_NONE)
;
@RESF(FLG_BMONKEY_TASS)
@RESF(FLG_SYS_MONSTER_OFF)
@GOSUB( MSG_SUB_BGM_FADEOUT_LONG )
@CLRF(FLG_BGM_TASSY)
@MUSISTART()
@SET_COMEBACK_POS(TLPT_WINTERS);タス湖を渡ったら死んでも戻らない
@SETF(FLG_WINS_TASCO_ACROSS);タス湖を渡ったフラグ
@FUNC(6)		;マップ上での全滅・配達許可
』

;-------------------------------
;#48	タッシーに乗りタス湖縦断

;★タッシーが登場している時に
;タッシー隊セバスチャンと会話 MSG_WINS_WATCHERS_GUM すると
;バルーンモンキーは空中に浮遊後移動してタッシーの頭に乗り
;MSG_WINS_BALLOONMONKEY_TASSIE を発行。
;★その後タッシーは岸に近づいてくる。
;（湖岸のタッシーに接した所に移動すると、プレイヤーパーティーは
;タッシーに乗ることができる。）
;★プレイヤーが岸に近づいたタッシーから遠ざかろうとしたら
;MSG_WINS_BALLOONMONKEY_COMEON を発行して妨げる。

;★プレイヤーパーティーがタッシーに乗ったらタッシーは
;オートで対岸まで移動して、プレイヤーパーティーを岸に降ろす。
;-------------------------------
;#49	タッシー帰る
;★登場した時と同様に、音楽と共に（水中に？）消える。
;---------------------------------------------------


;#50	バルーンモンキー拾い食い（バナナなど）

;★路上にバナナやリンゴが落ちていると、バルーンモンキーは
;勝手に近寄り（ということが可能でしょうか？）食べてしまう。

;-----------------------------------------------------------


;#51	バルーンモンキーロープを降ろす	8.6	T

;★ウィンタース／レイニーサークルのダンジョンの行き止まりで
;「フーセンガム」を「つかう」とバルーンモンキーは空中に浮遊して
;歩いては行けなかった２階部分に降りて、
;そこからロープを降ろす（ＢＧ書換？）。

;「ガム」「つかう」で以下を実行
MSG_EVT_51_BMONKEY_FLOAT;
@HIDE_PLAYER(PC_BALLOONMONKEY,OBJFX_HIDE_NONE)	;バルモン表示消す
@MOVE_GOM_CHAR(GOM_BMONKEY_GUM,ANIM_BMONKEY_GUM1,OBJFX_SHOW_NONE)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY_GUM,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_FLY,ANIM_BMONKEY_ROPE,OBJFX_SHOW_NONE)	;浮遊猿
@MOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_BMONKEY_FLY_S,OBJFX_SHOW_NONE)　;浮遊猿の影
@WAITSYS()	;浮ききるまで待つ
@REMOVE_GOM_CHAR(GOM_SHADOW_FALL,ANIM_BMONKEY_ROPE_S)　;影移動
@WAITSYS()	;移動終了待ち
@HIDE_GOM_CHAR(GOM_BMONKEY_FLY,OBJFX_HIDE_NONE)	;浮遊終了
@HIDE_GOM_CHAR(GOM_SHADOW_FALL,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_BMONKEY_ROPE_OROSU,OBJFX_SHOW_NONE)　;バルモンロープおろす
@WAITSYS()	;まって
@HIDE_CHAR(PRSN_WINS_RAINY_1_3A,OBJFX_HIDE_NONE)	;ロープオブジェ消す
@WAITSYS()	;移動待ち
@HIDE_GOM_CHAR(GOM_BMONKEY,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY_CLIMBR,ANIM_BMONKEY_ROPE_DOWN,OBJFX_SHOW_NONE);ロープで降りる
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY_CLIMBR,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_BMONKEY_ROPE_GOOD,OBJFX_SHOW_NONE)	;もとの位置へ
@WAITSYS()
@HIDE_GOM_CHAR(GOM_BMONKEY,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_BALLOONMONKEY,OBJFX_SHOW_NONE)
@RESF(FLG_BMONKEY_ROPE)
@SETF(FLG_WINS_ROPE_SWITCH)
』

;--------------------------------------------------------


;#52	バルーンモンキー雌サルを追って消える	8.7	-

;★レイニーサークルのダンジョンを抜けてフィールドに出た所に
;雌ザルがいる。雌ザルはプレイヤーパーティーが近づくと逃げて
;進入不可能な崖の上などに移動する。
;★そこでバルーンモンキーはセリフ MSG_WINS_BALLOONMONKEY_BYE
;を発行して、パーティーを離れる。
;★雌ザルの後を追って、バルーンモンキーは画面外に消える。

MSG_EVT_52_BMONKEY_BYE;
;@RESF(FLG_TEMP_1)
;@REMOVE_CHAR(PRSN_WINS_FIELD_H,ANIM_KANOJO);彼女移動
@COLD_CHAR( PRSN_WINS_FIELD_H )　;「彼女逃げる」凍結
;サルを南向け、「！」漫符出す
@SET_PLAYER_DIR( PC_BALLOONMONKEY, DIR_M_DOWN )
@SHOW_MANPU_PLAYER( PC_BALLOONMONKEY, MANPU_BIKKURI )
@WI( 60 )
@HIDE_MANPU_PLAYER( PC_BALLOONMONKEY )
@OPEN(1)
◆Ｋｙｅ　ｕｋｉ　ｋｕｋｙｉ　（Ｎｏｗ　ｓｈｅ’ｓ　ｍｙ　ｔｙｐｅ．．．）@KEY()↓
◆Ｋｉ　ｋｕｋｋｙｏ　ｕｋｅ　（Ｉ　ｔｈｉｎｋ　Ｉ’ｌｌ　ａｓｋ　ｈｅｒ　ｆｏｒ　ａ　ｄａｔｅ！）
;jpn:◆キャッ　キャッキャ。↓
;jpn:　（すきなタイプのコだ！）@KEY()↓
;jpn:◆キャキャキャキャ　キャ！↓
;jpn:　（ナンパしちゃおう！）
@KEY()
@CLOSEALL()
@DEL_PARTY(PC_BALLOONMONKEY)
@MOVE_GOM_CHAR(GOM_BMONKEY,ANIM_BMONKEY_BYE,OBJFX_SHOW_NONE);Ｂモンキー移動
@WI( 4 )
@FRESH_CHAR( PRSN_WINS_FIELD_H )　;「彼女逃げる」
@WAITSYS()
@CLRF(FLG_BALLOONMONKEY)
』

;--------------------------------------------------------


;#53	スカイウォーカー発進！～飛行～墜落	8.8	T

;★アンドーナツ博士のセリフ MSG_WINS_ANDONUT を聞いた後で
;スカイウォーカーと接触するとプレイヤーキャラは消える（乗る）。
;★その後、決定ボタンが押されたらスカイウォーカー発進。
;（振動して画面上方向に消える。）
;★スカイウォーカーに乗り込んで５秒経過しても決定ボタンが押されなかったら
;メッセージ MSG_WINS_ANDONUT_GO を表示する。

;★スカイウォーカーがアンドーナツ博士の研究所内から
;画面外に移動してしまったら、画面はフィールドのマップに切り替わり、
;以降、スカイウォーカーを画面の中心として、スリークまで移動する様子を
;見せる。
;（飛行コースはほぼ決定していますが、マップとマップのつなぎに
;雲の上を飛行しているシーンを挿入する予定。）

;★スリークに到着したら、しばらく街の上を旋回した後、
;墓場に墜落して大穴を開ける。地表面を突き抜けて地下室に不時着するという設定。
;（破片を飛び散らしたり効果音を当てたりの演出が必要ですが詳細は未定。）
;★墜落後、暗転すると、ネスとポーラが捕らえられていた地下室の檻の近くに、
;壊れたスカイウォーカーがある。画面の中心は囚われのネス。
;中からジェフが出て来て（その場に出現して）
;ブルブルブルッと身を震わせて（すばやく左右反転）MSG_THRK_JEFF を発行。
;★メッセージの途中、オートで檻の扉に移動して、
;オートメッセージで「ちょっとカギマシン」を使い檻のカギを開けて
;ネスたちに接触してメッセージ MSG_THRK_JEFF を再開。
;（以降、プレイヤーキャラは再びネスとなる。）
;
;スカイウォーカーに乗船する。2度目は自動発進。
;ANIM_SW_WINS から起動
MSG_EVT_RIDE_SW_WINS;
;-----
@SETF(FLG_SYS_MONSTER_OFF)		;ワンダリングモンスター出さない
@FUNC(5)				;配達毒死禁止
@GOSUB(MSG_GLOBAL_DELIVERY_RESET)	;場面転換時に配達を中止
;-----
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_SW_WINS,OBJFX_SHOW_NONE);乗船する透明人間
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS();乗車するまで待つ
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
;------------
@GOSUB( MSG_SUB_BGM_FADEOUT_LONG )
@SETF(FLG_BGM_SW)
@MUSISTART()
;------------
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
;@COLD_CHAR(PRSN_WINS_LABO_1F_A);
@REMOVE_CHAR(PRSN_WINS_LABO_1F_A,ANIM_NEAR_ANDOUGHNUT);博士近付く
@WAITSYS()
@CHKFGOTO(FLG_POWR_RAIN,MSG_EVT_RIDE_SW_WINS_AFTER)
@CLRF(FLG_TEMP_8)					;ボタンを押したフラグ
@REMOVE_CHAR(PRSN_WINS_LABO_1F_A,ANIM_ANDOUGHNUT_MESSAGE);博士
@WAITSYS()
@CHKFGOTO(FLG_TEMP_8,MSG_EVT_RIDE_SW_WINS_AFTER)
@GOSUB(MSG_WINS_ANDONUT_GO)
MSG_EVT_RIDE_SW_WINS_AFTER;
』
;
;
MSG_EVT_RIDE_SW_WINS_LAUNCH;
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
;発進の効果？
@FRESH_CHAR(PRSN_WINS_LABO_1F_4A);発進
@WAITSYS();上昇を待つ
@WI(30)
@HIDE_CHAR(PRSN_WINS_LABO_1F_3B,OBJFX_HIDE_NONE);影を消す
@WAITSYS()
;飛行シーン
;@GOTO(_THRK_DEBUG_DENPA)
;
; 研究所上空
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_WINS_A,OBJFX_AFTER_WARP)
;@MOVE_GOM_CHAR(GOM_SHADOW,ANIM_SW_WINS_SHADOW_A,OBJFX_SHOW_NONE)
@WARP(WARP_SKYW_WINS_A)
;@SET_CAMERA_GOM_CHAR(GOM_SHADOW)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; 雲
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_SKY_A,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_SKY_B)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SKYWALKER)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; フォーサイド
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_FOUR_A,OBJFX_AFTER_WARP)
@MOVE_GOM_CHAR(GOM_SHADOW,ANIM_SW_FOUR_SHADOW_A,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_FOUR_A)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SHADOW)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; 雲
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_SKY_B,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_SKY_B)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SKYWALKER)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; ドコドコ砂漠
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_DSRT_A,OBJFX_AFTER_WARP)
@MOVE_GOM_CHAR(GOM_SHADOW,ANIM_SW_DSRT_SHADOW_A,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_DSRT_A)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SHADOW)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; 雲
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_SKY_C,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_SKY_B)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SKYWALKER)
@FRESH_PLAYER(PC_ALL)
@WI(1)
@WAITSYS()
@SET_CAMERA_PARTY()
; スリーク東
_THRK_DEBUG_DENPA;
@MOVE_GOM_CHAR(GOM_SKYWALKER,ANIM_SW_THRK_A,OBJFX_AFTER_WARP)
@MOVE_GOM_CHAR(GOM_SHADOW,ANIM_SW_THRK_SHADOW_A,OBJFX_AFTER_WARP)
@WARP(WARP_SKYW_THRK_A)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_SHADOW)
@WAITSYS()
;発見電波
@COLD_GOM_CHAR( GOM_SKYWALKER )
@COLD_GOM_CHAR( GOM_SHADOW )
@GOSUB( MSG_EVT_SW_CATCH_DENPA )
@WI(15)
@GOSUB( MSG_EVT_SW_CATCH_DENPA )
@FRESH_GOM_CHAR( GOM_SKYWALKER )
@FRESH_GOM_CHAR( GOM_SHADOW )
@WAITSYS()
;落ちるす
@COLD_GOM_CHAR( GOM_SKYWALKER )
@COLD_GOM_CHAR( GOM_SHADOW )
@CLRF(FLG_BGM_SW)
@BGMSTART(0,BGM_skex2)
@FRESH_PLAYER(PC_ALL)
@FRESH_GOM_CHAR( GOM_SKYWALKER )
@FRESH_GOM_CHAR( GOM_SHADOW )
@WAITSYS()
MSG_EVT_SW_TO_KATACOMB;
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@ADD_PARTY(PC_NESS);シーン替えの設定各種
@ADD_PARTY(PC_PAULA)
@DEL_PARTY(PC_JEFF)
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
;@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@SETF(FLG_THRK_BROKEN_SKYW_APPEAR)
; 墓地下
@MOVE_GOM_CHAR(GOM_PLAYER_KUROKOGE,ANIM_KUROKOGE_JEFF,OBJFX_AFTER_WARP);黒こげ表示
@WARP(WARP_SKYW_THRK_KATACOMB)
@MUSISTART()
;----------
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_ODOROKI_NES_POLA,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@HIDE_GOM_CHAR(GOM_PLAYER_KUROKOGE,OBJFX_HIDE_NONE);黒こげジェフ消す
@MOVE_GOM_CHAR(GOM_JEF,ANIM_JEFF_ADD_PARTY,OBJFX_SHOW_NONE)
@WI(1)
@COLD_GOM_CHAR(GOM_JEF)
@OPEN(1)
MSG_THRK_JEFF;
;ジェフ
;スカイウォーカー墜落直後
◆Ｍａｎ，　ｏｈ，　ｍａｎ，　ｄｉｄ　ｔｈａｔ　ｅｖｅｒ　ｓｃａｒｅ　ｍｅ！．．．@KEY()↓
◆Ｔｈｅ　Ｓｋｙ　Ｒｕｎｎｅｒ．．．@KEY()↓
◆Ｉ　ｇｕｅｓｓ　ｉｔ　ｔｏｏｋ　ａ　ｌｉｔｔｌｅ　ｄａｍａｇｅ　ｗｈｉｌｅ　ｌａｎｄｉｎｇ．．．@KEY()↓
◆Ｏｈ　ｗｅｌｌ．．．
;jpn:◆ああ　ビックリした。↓
;jpn:　スカイウォーカーのやつ‥‥@KEY()↓
;jpn:◆ちゃくりくしたのか↓
;jpn:　ついらくしたのか？↓
;jpn:　フーッ！
@KEY()
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_JEF);近づく
@WAITSYS()
;檻に移動してカギをあける
@OPEN(1)
←
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｔｏ　ｅｘｐｌａｉｎ　ａ　ｔｈｉｎｇ．．．Ｉ’ｍ　@DSP_NAME(PC_JEFF)．@KEY()↓
◆Ｉ　ｃａｍｅ　ｂｅｃａｕｓｅ　ｙｏｕ　ｃａｌｌｅｄ　ｍｅ．@KEY()↓
◆Ｉ’ｍ　ｎｏｔ　ｖｅｒｙ　ｓｔｒｏｎｇ，　ｒｅａｌｌｙ　ｎｅａｒ－ｓｉｇｈｔｅｄ，@KEY()↓
◆ｋｉｎｄ　ｏｆ　ｓｈｙ，　ａｎｄ　Ｉ　ｔｅｎｄ　ｔｏ　ｂｅ　ａ　ｌｉｔｔｌｅ　ｒｅｃｋｌｅｓｓ．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ｊｕｓｔ　ｔｈｅ　ｗａｙ　Ｉ　ａｍ．．．@KEY()↓
◆Ｉ　ｈｏｐｅ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｂｅ　ｙｏｕｒ　ｆｒｉｅｎｄ．．．ｏｋａｙ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆せつめいは　いらないよ。↓
;jpn:　ぼくは@DSP_STS(STS_PC_NAME_JEFF)↓
;jpn:　きみたちに　よばれてきたんだ。@KEY()↓
;jpn:◆ちからは　よわい。↓
;jpn:　めは　きょうどの　きんし。↓
;jpn:　こわがりで　むてっぽう。@KEY()↓
;jpn:◆こんなぼくだけど↓
;jpn:　なかまに　いれてくれるかな？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THRK_JEFF_YES,_THRK_JEFF_NO)

_THRK_JEFF_NO;
◆．．．Ｓｏ　ｗｈｙ　ｄｉｄ　ｙｏｕ　ｃａｌｌ　ｍｅ？@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｊｕｓｔ　ｍａｋｉｎｇ　ｆｕｎ　ｏｆ　ｍｅ？@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ｊｕｓｔ　ｔｈｅ　ｗａｙ　Ｉ　ａｍ．．．@KEY()↓
◆Ｉ　ｈｏｐｅ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｂｅ　ｙｏｕｒ　ｆｒｉｅｎｄ．．．ｏｋａｙ？↓
<Ｙｅｓ>　<Ｎｏ>
;jpn:◆‥‥なんのために↓
;jpn:　‥‥ぼくを　よんだんだ？！↓
;jpn:　からかわないでくれよ。@KEY()↓
;jpn:◆こんなぼくだけど↓
;jpn:　なかまに　いれてくれるかな？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_THRK_JEFF_YES,_THRK_JEFF_NO)
@GOTO(_THRK_JEFF_NO)

_THRK_JEFF_YES;
◆Ａｌｌ　ｒｉｇｈｔ！　　Ｌｅｔ’ｓ　ｇｅｔ　ｂａｃｋ　ｔｏ　ｔｈｅ　ｊｏｕｒｎｅｙ，　ｔｈｅｎ！
;jpn:◆ＯＫ！@WI(20)　じゃ　さっそく↓
;jpn:　ぼうけんのつづきだ！@WI(20)↓
;jpn:　いこうぜ！
@KEY()
@CLOSEALL()
@WI(1)

@ADD_PARTY(PC_JEFF)
@HIDE_PLAYER(PC_JEFF,OBJFX_HIDE_NONE)
@REMOVE_GOM_CHAR(GOM_JEF,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_JEF,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_JEFF,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_friend)
@WI(120)
@WI(120)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_hakaba)
@OPEN(1)
◆@DSP_NAME(PC_JEFF)　ｊｏｉｎｅｄ　ｙｏｕ．
;jpn:◆（@DSP_STS(STS_PC_NAME_JEFF)が↓
;jpn:　なかまになった）
@KEY()
@CLOSEALL()
@WI(1)

@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
@SETF(FLG_JEFF)
@SETF(FLG_THRK_MATENT_APPEAR)
@SETF(FLG_THRK_HOTEL_BOY_APPEAR)
@SETF(FLG_THRK_ESCAPER_APPEAR)	;テントに逃げ込む人出現
@SETF(FLG_WINS_KANAI_APPEAR)	;ウィンターズにカナイが出現
@SETF(FLG_WINS_SKYW_DISAPPEAR)	;研究所スカイウォーカー消滅
@CLRF(FLG_WINS_BRICK_THANKS_APPEAR);ブリックロードさん消える
@CLRF(FLG_WINS_POLA_TELEPATHY)
@SET_COMEBACK_POS(TLPT_THREEK)
@CLRF(FLG_SYS_MONSTER_OFF)		;ワンダリングモンスター出さない
@FUNC(6)			;配達毒死許可
@LOAD_STORY()
』


MSG_EVT_SW_CATCH_DENPA;
@SE( SE_se49_foe_time_stop )
@SHOW_MANPU_GOM_CHAR(GOM_SKYWALKER,MANPU_DENPA)
@WI(10)
@HIDE_MANPU_GOM_CHAR(GOM_SKYWALKER)
@WI(3)
@SHOW_MANPU_GOM_CHAR(GOM_SKYWALKER,MANPU_DENPA)
@WI(10)
@HIDE_MANPU_GOM_CHAR(GOM_SKYWALKER)
@WI(60)
』

;---------------------------------

MSG_EVT_ESCAPE_TENT;	←現在恐らく呼ばれていない
;@REMOVE_CHAR(,ANIM_ESCAPE_TENT);テントに逃げ込む
;@REMOVE_CHAR(,ANIM_ESCAPE_TENT)
@CLRF(FLG_THRK_ESCAPER_APPEAR)		;アニメ内で消している(malta)
』
;---------------------------------

MSG_WINS_ANDONUT_GO;
@OPEN(1)
◆Ｗｈａｔ　ｈａｐｐｅｎｅｄ？　　Ｉｔ’ｓ　ｎｏｔ　ｍｏｖｉｎｇ！@KEY()↓
◆Ｈｅｙ！　　Ｗｈｙ　ｄｏｎ’ｔ　ｙｏｕ　ｔｒｙ　ｐｒｅｓｓｉｎｇ　ｔｈｅ　ｂｕｔｔｏｎ　ｏｎ　ｔｈｅ　ｃｏｎｔｒｏｌｌｅｒ！
;jpn:◆どうした？　うごかないのか。↓
;jpn:　コントローラーのボタンを↓;Ａを削除
;jpn:　おしてごらん。
@KEY()
@CLOSEALL()
』
;---------------------------------
;#54	●魔テント消える

MSG_EVT_THRK_FIGHT_MATENT;魔テントの顔のアニメーションから起動される。
;---------------テスト
@GOSUB( MSG_SUB_BGM_FADEOUT_SHORT )
@SE(SE_se60_monster_appear)
;@SE(SE_se78_my_open_rock)
@BGMSTART(0,BGM_msc24)
;@WI(60)
;---------------
@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出さない
@REMOVE_CHAR(PRSN_THRK_FIELD_Q,ANIM_BILLBOARD)
@REMOVE_CHAR(PRSN_THRK_FIELD_R,ANIM_BILLBOARD)
@REMOVE_CHAR(PRSN_THRK_FIELD_S,ANIM_BILLBOARD)
;@FRESH_CHAR(PRSN_THRK_FIELD_Q)
;@FRESH_CHAR(PRSN_THRK_FIELD_R)
;@FRESH_CHAR(PRSN_THRK_FIELD_S)
@WI(120)
@GOTO(MSG_THRK_MATENT_GAO)

; 魔テントが負けて逃げていくゾンビ
MSG_EVT_THRK_WIN_MATENT;
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_MATENT_AWAY_ZOMBI1,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_MATENT_AWAY_ZOMBI2,OBJFX_SHOW_NONE)
;@WAITSYS()
@WI(120)
』

;---------------------------------


;#55	ゾンビホイホイ使用	ゝ

;★スリーク／対策本部のテントでグッズ「ゾンビホイホイ」使用し
;ホテルに宿泊すると、テントの檻にゾンビが捕まる。
;★ホテルでの宿泊中に、ゾンビがゾロゾロ集まってくるシーンを数カット挿入したい。
;（この夜のシーン以外は、通常のフラグによるオブジェクトの出現／消去で可能。）

;宿屋のメッセージ中に以下を追加
MSG_EVT_55_HOIHOI;
@CLOSEALL()
@BGMSTART(0,BGM_kowa4)
@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを消す
@FUNC(5)			;配達禁止
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_A,OBJFX_AFTER_WARP)　　　　　;ゾンビＡ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_B,OBJFX_AFTER_WARP)　　　　　;ゾンビＢ
@WARP(WARP_THRK_ZOMBI_A)
@COLD_PLAYER(PC_ALL)
@WI(120)
@WI(120)
@WI(30)
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_C,OBJFX_AFTER_WARP)　　　　　;ゾンビＣ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_D,OBJFX_AFTER_WARP)　　　　　;ゾンビＤ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_E,OBJFX_AFTER_WARP)　　　　　;ゾンビＥ
@WARP(WARP_THRK_ZOMBI_B)
@COLD_PLAYER(PC_ALL)
@HIDE_CHAR(PRSN_THRK_FIELD_V, OBJFX_HIDE_NONE);GOM_WEAPON
@WI(30)
@WI(30)
@WI(120)
@WARP(WARP_THRK_ZOMBI_C)
@COLD_PLAYER(PC_ALL)
@WI(1)
;@SET_PALLETSET(31,0,1);真っ暗
@REMOVE_CHAR(PRSN_THRK_FIELD_T,ANIM_HOIHOI_F)　　　　　　　;ゾンビＦ
@REMOVE_CHAR(PRSN_THRK_FIELD_U,ANIM_HOIHOI_G)　　　　　　　;ゾンビＧ
@WI(120)
@WI(45)
;-----
;通行人を消しておく為の設定（すぐに戻す）
@SETF(FLG_THRK_PEOPLE_DISAPPEAR)
@SETF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
@SETF(FLG_TLPT_FOUR)
;-----
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_H,OBJFX_AFTER_WARP)　　　　　;ゾンビＨ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_I,OBJFX_AFTER_WARP)　　　　　;ゾンビＩ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_J,OBJFX_AFTER_WARP)　　　　　;ゾンビＪ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_K,OBJFX_AFTER_WARP)　　　　　;ゾンビＫ
@MOVE_GOM_CHAR(GOM_ZOMBIDOG,ANIM_HOIHOI_L,OBJFX_AFTER_WARP)　　　　　;ゾンビＬ
@MOVE_GOM_CHAR(GOM_ZOMBI,ANIM_HOIHOI_M,OBJFX_AFTER_WARP)　　　　　;ゾンビＭ
@WARP(WARP_THRK_ZOMBI_D)
@COLD_PLAYER(PC_ALL)
;@HIDE_CHAR(PRSN_THRK_FIELD_F, OBJFX_HIDE_NONE);GOM_BOY_A
;@HIDE_CHAR(PRSN_THRK_FIELD_H, OBJFX_HIDE_NONE);GOM_CAP
;@HIDE_CHAR(PRSN_THRK_FIELD_D, OBJFX_HIDE_NONE);GOM_GIRL_D
;@HIDE_CHAR(PRSN_THRK_FIELD_K, OBJFX_HIDE_NONE);GOM_OLDWOMAN
@WI(120)
@WI(120)
@WI(30)
;-----
;通行人を消しておく為の設定解除
@CLRF(FLG_THRK_PEOPLE_DISAPPEAR)
@CLRF(FLG_GPFT_MINIGEPPU_A_DISAPPEAR)
@CLRF(FLG_TLPT_FOUR)
;-----
@WARP(WARP_THRK_ZOMBI_E)
;@WI(1)
;@SET_PALLETSET(20,1,0);昼
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@SETF(FLG_THRK_GRAVEZOMBI_DISAPPEAR)
@CLRF(FLG_PUT_ZOMBI_HOIHOI)
@SETF(FLG_THRK_ZOMBI_CAPTURED)
@SETF(FLG_THRK_OZISAN_D_DISAPPEAR)	;テントの人消える
@SETF(FLG_THRK_URBAN_ZOMBI_GONE)	;ワンダリングモンスター制御用
@CLRF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出す
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
@FRESH_PLAYER(PC_ALL)
』

;-----------------------------------------------------------------------------


;#56	秘密基地に入る

;★グレープフルーツの滝の根元にセットしたワープ時のメッセージ
;MSG_EXAMINE_GEPPU_PASSWORD を聞いた後、
;３分間キー入力がなかったら MSG_GPFT_PASSWORD_LATER を発行する。

MSG_GPFT_PASSWORD;
@CHKFGOTO(FLG_DOSEI_SECRETCODE,_GPFT_PASSWORD_AFTER)
◆．．．．．．．．
;jpn:◆‥‥‥。
@KEYNP()
』

_GPFT_PASSWORD_AFTER;
;「ANIM_GEPPU_PASS」
;３分間キーを見続け、キー入力があれば自殺。３分たてば、メッセージ発行
◆Ｓａｙ　ｔｈｅ　ｐａｓｓｗｏｒｄ！
;jpn:◆あいことばを　いえ！
@WI(120)
@WI(60)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_GEPPU_PASS,OBJFX_SHOW_NONE)
』

MSG_GPFT_PASSWORD_LATER;
;基地入口３分後
@OPEN(1)
◆Ｏｋａｙ．．．ｙｏｕ　ｍａｙ　ｅｎｔｅｒ．
;jpn:◆よーし　はいれ！
@KEY()
@CLOSEALL()
@WI(1)
@WARP(WARP_GPFT_FIELD_GEPPU)
@SETF(FLG_GPFT_PASSWORD_OK)
@GOSUB(MSG_SAVE_MOUSE)
』

;--------------------------------------------------------------


;#57	●ゲップーの特殊攻撃	ゝ

;★ゲップーはバトルに入る前に、ゲロの海をつくって（沼属性）
;プレイヤーの行く手を阻むという設定があったのですが、
;実現が困難だろうということでヤメになっています。

;---------------------------------------------------------


;#58	コーヒータイム	-	-

;★糸井さんからプレイヤーに向けてのねぎらいの言葉。
;土星さんのセリフ _GPFT_DOSEICAFE_YES がきっかけ。
;★オートの縦スクロールでメッセージを表示。かな漢字混じり。
;専用音楽有り。背景は地味なカラーサイクル。

;@BGMSTART(0,BGM_time)

;---------------------------------------------------------


;#59	●明るくなったスリーク

;★大山氏の意向で、スリークでは事件解決後もパレットチェンジは
;行わないこととなりました。

;------------------------------------------------------------


;#60	大渋滞	9.1	T

;★ドコドコ砂漠を一回目は歩いて横断してもらう為に、
;はじめは自動車などのオブジェクトで道路を封鎖しています。
;★プレイヤーキャラが砂漠の出口付近まで移動したら、
;「見えないキャラ」にチェックさせて（未設定）
;フラグを立てて渋滞を終了させます。

;------------------------------------------------


;#61	バスから降りる（大渋滞）	9.2	T

;★絵コンテ通り。「運転手の顔」をバスに表示して
;セリフ MSG_DSRT_HIGHWAYBUS_HURRY を発行して
;プレイヤーキャラたちを出現させる。
;★バスは来た道を画面外に消える。

MSG_EVT_BUS_TUNNEL_DSRT_R_JYUUTAI;
;FLG_DSRT_CLEAR が OFF の時は以下がバスから発行される
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_BUS,ANIM_BUS_TUNNEL_DSRT_R_J,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_DSRT_R)
@SET_CAMERA_GOM_CHAR(GOM_BUS)
』

MSG_EVT_BUS_TOUCH_DSRT;
@CLRF(FLG_BGM_BUS)
@MUSISTART()
;@BGMSTART(0,BGM_doko)
@MOVE_GOM_CHAR(GOM_BUS_DRIVER,ANIM_BUS_DRIVER_R,OBJFX_SHOW_NONE)　　　　　;運転手
@OPEN(1)
MSG_DSRT_HIGHWAYBUS_HURRY;ハイウェイバスの運転手（ハリー）
◆Ｍａｎ！　　Ｉｔ’ｓ　ｂｕｍｐｅｒ　ｔｏ　ｂｕｍｐｅｒ！@KEY()↓
◆Ｍｙ　ｊｏｂ　ｉｓ　ｔｏ　ｄｒｉｖｅ，　ｓｏ　Ｉ　ｃａｎ’ｔ　ｇｅｔ　ｏｆｆ　ｔｈｅ　ｂｕｓ．．．@KEY()↓
◆Ｉｔ’ｓ　ｕｐ　ｔｏ　ｙｏｕ　ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｏｆｆ　ｔｈｅ　ｂｕｓ　ａｎｄ　ｗａｌｋ　ａｒｏｕｎｄ　ｉｎ　ｔｈｅ　ｄｅｓｅｒｔ．．．@KEY()↓
◆Ｈｅｙ，　ｉｔ’ｓ　ａ　ｆｒｅｅ　ｃｏｕｎｔｒｙ．
;jpn:◆いやぁ　こんでる　こんでる。↓
;jpn:　おれは　うんてんがしごとだし↓
;jpn:　おりるわけにゃ　いかねぇけど@KEY()↓
;jpn:◆あんたらが　おりちまって↓
;jpn:　さばくを　あるいていくのは↓
;jpn:　じゆうだ。@KEY()↓
;jpn:◆ここは　じゆうの　くにさ。
@KEY()
@CLOSEALL()
@HIDE_GOM_CHAR(GOM_BUS_DRIVER,OBJFX_HIDE_NONE)			;運転手消す
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_BUS_L,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
@FRESH_GOM_CHAR(GOM_BUS)
@WAITSYS()
@SET_HIT_RECT(1,HRECT_DSRT_CLEAR,MSG_DSRT_CLEAR)
@CLRF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させる
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
@SETF(FLG_STEP_DSRT)
』

;----------------------------------------


;#62	●トポロ劇場に入場	-	-

MSG_EVT_62_CARROT_R;
@REMOVE_CHAR(PRSN_FRSD_TOPOLLO_FRONT_B,ANIM_MOGIRI_TO_RIGHT)
@WAITSYS()
』

MSG_EVT_62_CARROT_D;
@REMOVE_CHAR(PRSN_FRSD_TOPOLLO_FRONT_B,ANIM_MOGIRI_TO_DOWN);外側へ移動
@WAITSYS()
』

;----------------------------------------


;#63	ビーナスのステージ（１回目）

;★トポロ劇場／ホールに入るといつもビーナスがステージに立って
;歌っている。（曲もビーナスの曲）
;★一曲歌い終わったら舞台の袖に引っ込む。

;@BGMSTART(0,BGM_vins1);なってる
;@BGMSTART(0,BGM_vins2);フルバージョン

MSG_EVT_63_VENUS;予約メッセージで以下を実行
MSG_EVT_81_VENUS_2;
@COLD_PLAYER(PC_ALL)
@CLOSEALL()
;フェードアウトしながら暗転
@BGM_EFFECT(3)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_FADEOUT,OBJFX_SHOW_NONE)
@WAITSYS()
@GOSUB(MSG_EVT_TOPOLO_VENUS_MC)		;ビーナスのステージ（のアナウンス）
;-----
@MOVE_GOM_CHAR(GOM_TEN,ANIM_VSTAGE1_SCR_1,OBJFX_SHOW_NONE)　　　;既に暗転、スクロール
@MOVE_GOM_CHAR(GOM_VENUS,ANIM_VSTAGE1_VENUS_STILL,OBJFX_SHOW_NONE)　;ビーナス
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_PARTY,OBJFX_SHOW_NONE)　;固まる透明人間
;@SET_GOM_CHAR_DIR(GOM_HIT_CHR,DIR_M_UP_LEFT);GOM_HIT_CHRの向き設定
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
』

MSG_EVT_VSTAGE1_A
@FRESH_PLAYER(PC_ALL)　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;プレーヤーは固まってる
;@FRESH_GOM_CHAR(GOM_VENUS)                              ;歌うビーナス
@BGMSTART(0,BGM_vins2);なってる
@REMOVE_GOM_CHAR(GOM_VENUS,ANIM_VSTAGE1_VENUS)		;ビーナス
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LIGHT,ANIM_VSTAGE1_VENUS_LIGHT1,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_LIGHT,ANIM_VSTAGE1_VENUS_LIGHT2,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_KOMORITA,ANIM_VSTAGE1_KOMORITA_CROSS,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_KOMORITA,ANIM_VSTAGE1_KOMORITA_APPEAR,OBJFX_SHOW_NONE)
@WAITSYS()
@SHOW_MANPU_GOM_CHAR(GOM_VENUS,MANPU_BIKKURI)
@WI(31)
@HIDE_MANPU_GOM_CHAR(GOM_VENUS)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_BODYGUARD,ANIM_VSTAGE1_BODYGUARD_L,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_BODYGUARD,ANIM_VSTAGE1_BODYGUARD_R,OBJFX_SHOW_NONE)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;ステージ終了待ち
@HIDE_GOM_CHAR(GOM_LIGHT,OBJFX_HIDE_NONE)
@WI(1)
@HIDE_GOM_CHAR(GOM_LIGHT,OBJFX_HIDE_NONE)
@WI(94)
@WI(94)
@MUSISTART()
;@BGMSTART(0,BGM_topolo);ここでよいかな？
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_VSTAGE1_SCR_2,OBJFX_SHOW_NONE);スクロール、明転
』

MSG_EVT_VSTAGE1_B
@SET_CAMERA_PARTY()
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)　　　　　　　　　　　　　　　　　　;固まる透明人間消す
』

MSG_EVT_TOPOLO_VENUS_MC;ビーナスのステージ
@OPEN(1)
◆Ｏｈ，　ｂａｂｙ　ｂａｂｙ　ｂａａａｂｙｙｙ！@KEY()↓
◆Ｄｏｎ’ｔ　ｍａｋｅ　ｍｅ　ｈｕｒｔ　ｓｏ　ｂａｄ！@KEY()↓
◆Ｔｈｅｓｅ　ｇｕｙｓ　ａｒｅ　ａｌｌ　ｓｔｏｎｅ　ｃｏｌｄ　ｇｏｎｅ　ｆｏｒ　ｙｏｕ．．．@KEY()↓
◆Ｏｗ！！．．．Ｙｏｕ　ｃｕｔｅ，　ｓｅｘｙ　ｔｈｉｎｇ，　ｙｏｕ！．．．@KEY()↓
◆Ｂａｂｙ，　ｓｉｎｇ　ｔｏ　ｍｅ！．．．Ｓｉｎｇ　ｔｏ　ｍｅ　ｏｎｌｙ！．．．@KEY()↓
◆Ｂａｂｙ！！　　Ｖｅｎｕｓ！@KEY()↓
◆Ｊｕｓｔ　ｓｉｎｇ　Ｉ　ｃａｎ　ｄｉｅ　ａ　ｈａｐｐｙ　ｍａｎ！．．．Ｂａｂｙ！！．．．@KEY()↓
◆Ｉ　ｗａｎｎａ　ｈｏｌｄ　ｙｏｕ　ｔｉｇｈｔ！．．．Ｖｅｎｕｓ！．．．Ｂａｂｙ！．．．@KEY()↓
◆＊Ｂｏｏ，　ｈｏｏ，　ｈｏｏ＊．．．Ｖｅｎｕｓ！．．．＊ｓｏｂ＊　＊ｓｏｂ＊
;jpn:◆オー　ベイビーベイビーベイビー！@WI(30)↓
;jpn:　おれを　そんなに↓
;jpn:　なかせないでくれよん。@KEY()↓
;jpn:◆キュートで　セクシーで↓
;jpn:　ノスタルジックな　きみに@WI(20)↓
;jpn:　おとこたちは　もうイチコロさ！@KEY()↓
;jpn:◆ベイビーおれのために　うたって！@WI(15)↓
;jpn:　ベイビー@WI(10)　ビー@WI(10)　ビー‥‥@WI(20)↓
;jpn:　ビーナス！@WI(30)　ビーナス！@KEY()↓
;jpn:◆うたって　ころして！！↓
;jpn:　だきしめたい！@WI(30)　ビーナス！！@WI(20)↓
;jpn:　！@WI(5)！@WI(5)！@WI(5)！@WI(5)！@WI(5)！@WI(5)！@WI(5)！@WI(5)！@WI(5)！
@KEY()
@CLOSEALL()
』
;------------------------------------------------------------


;#64	トンズラのステージ（２回目）

;       トンズラの解放その２


;グッズ－つかうで以下を実行
MSG_EVT_64_TONZURA_FREE_2;
@CLOSEALL()
@SETF(FLG_BGM_TONZURA_FREE)
@MUSISTART()
;@BGMSTART(0,BGM_tonz0)
;@DIS_BGMCHG();虫を無視
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_GORGEOUS_FREE_2A,OBJFX_SHOW_NONE)　　　;登場
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_LUCKY_FREE_2A,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_NICE,ANIM_NICE_FREE_2A,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_OK,ANIM_OK_FREE_2A,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GROOVE,ANIM_GROOVE_FREE_2A,OBJFX_SHOW_NONE)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;５人の正列待つ
;ここで５人の向きを北向きに
;
@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TONZURA_FREE_2B)　　　　　;机に移動
@WAITSYS()
@COLD_GOM_CHAR(GOM_GORGEOUS)
@OPEN(1)
◆Ｓｏｒｒｙ　ａｂｏｕｔ　ｂｅｉｎ’　ｓｕｃｈ　ｔｒｏｕｂｌｅｍａｋｅｒｓ！
;jpn:◆またまた　めいわくを↓
;jpn:　かけちまったなぁ。
@KEY()
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_GORGEOUS)　　　　　　　　　　　　　　　　　　　;ドアへ
@WAITSYS()
;
@REMOVE_GOM_CHAR(GOM_LUCKY,ANIM_TONZURA_FREE_2B)　　　　　　　　;机に移動
@WAITSYS()
@COLD_GOM_CHAR(GOM_LUCKY)
@OPEN(1)
;ラッキー
◆Ｗｅ　ｗｏｎ’ｔ　ｂｅ　ｓｏ　ｇｕｌｌｉｂｌｅ　ａｎｙｍｏｒｅ．．．@KEY()↓
◆Ｗｅｌｌ，　ｏｕｒ　ｆａｎｓ　ａｒｅ　ｗａｉｔｉｎ’，　ｂａｂｙ．．．
;jpn:◆でも　おれたちの　おひとよしも↓
;jpn:　これで　さいごにするけど‥‥@WI(20)↓
;jpn:　ファンが　まってるから
@KEY()↓
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_LUCKY)　　　　　　　　　　　　　　　　　　　　　　;ドアへ
@WAITSYS()
;
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TONZURA_FREE_2B)　;机に移動
@WAITSYS()
@COLD_GOM_CHAR(GOM_NICE)
@OPEN(1)
;ナイス
◆Ｌｅｔ’ｓ　ｊｕｓｔ　ｄｏ　ｔｈｉｓ　ｏｎｅ　ｌａｓｔ　ｓｈｏｗ　ａｎｄ　ｔｈｅｎ　ｇｅｔ　ｏｕｔｔａ　ｈｅｒｅ．．．
;jpn:◆もうワンステージだけ↓
;jpn:　うたってから↓
;jpn:　ここと　おさらばしよう。
@KEY()↓
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_NICE)　　　　　　　　　　　		;ドアへ
@WAITSYS()
;
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TONZURA_FREE_2B)　　　;机に移動
@WAITSYS()
@COLD_GOM_CHAR(GOM_OK)
@OPEN(1)
;オーケー
◆Ａｌｌ　ｒｉｇｈｔ！　　Ｔｈａｎｋｓ　ａｇａｉｎ！
;jpn:◆じゃ　いくぜ！　ありがとうよ！
@KEY()
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_OK)　　　　　　　　　　　　　　　　　;ドアへ
@WAITSYS()
;
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_GROOVE_FREE_2B)　　　　　　　　;机に移動
@WAITSYS()
@COLD_GOM_CHAR(GOM_GROOVE)
@OPEN(1)
;グルービー
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　Ｉ　ｗａｎｔ．@KEY()↓
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　ｉｓ　ｈｏｔ．@KEY()↓
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　Ｉ　ｗａｎｔ．@KEY()↓
◆Ｍｏｎｅｙ，　ｉｔ’ｓ　ｗｈａｔ　ｗｅ　ａｉｎ’ｔ　ｇｏｔ　’Ｃｅｐｔ　ｆｒｅｅｄｏｍ，　ｆｒｅｅｄｏｍ，@KEY()↓
◆ｆｒｅｅｄｏｍ　ｉｓ　ｗｈａｔ　ｗｅ’ｖｅ　ｒｅａｌｌｙ　ｓｏｕｇｈｔ！
;jpn:◆音かね　@WI(20)それは　ほしいもの@WI(20)↓
;jpn:　　かね　@WI(20)とても　ほしいもの@WI(20)↓
;jpn:　　かね　@WI(20)おれの　ほしいもの@KEY()↓
;jpn:◆音かね　@WI(20)みんな　ほしいもの@WI(20)↓
;jpn:　　だけど　じゆうは　もっとほしい@WI(20)
@KEY()↓
@CLOSEALL()
@FRESH_GOM_CHAR(GOM_GROOVE)　　　　　　　　　　　　　　　　　　　　　;回転
@WAITSYS()
@COLD_GOM_CHAR(GOM_GROOVE)
@OPEN(1)
;グルービー
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　Ｉ　ｗａｎｔ．@KEY()↓
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　ｉｓ　ｈｏｔ．@KEY()↓
◆Ｍｏｎｅｙ，　ｔｈａｔ’ｓ　ｗｈａｔ　Ｉ　ｗａｎｔ．．．
;jpn:◆音かね　@WI(20)それは　ほしいもの@WI(20)↓
;jpn:　　かね　@WI(20)とても　ほしいもの@WI(20)↓
;jpn:　　かね　@WI(20)おれの　ほしいもの‥‥
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_GORGEOUS_FREE_2C,OBJFX_SHOW_NONE)　　　;ゴージャス
@WAITSYS()
@FRESH_GOM_CHAR(GOM_GROOVE)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;２人ドアへ
』


;★基本的に一回目と同じ。その豪華版。


;メッセージ予約で以下を発行
MSG_EVT_64_TONZURA_2;
@COLD_PLAYER(PC_ALL)
@BGM_EFFECT(3)
@CLOSEALL()
;-----
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_FADEOUT,OBJFX_SHOW_NONE)
@WAITSYS()
@GOSUB(MSG_EVT_TOPOLO_TONZURA_MC);トポロのアナウンス（トンズラ）
;-----
@MOVE_GOM_CHAR(GOM_TEN,ANIM_TSTAGE2_SCR_1,OBJFX_SHOW_NONE);暗転、スクロール
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_PARTY,OBJFX_SHOW_NONE)　;固まるプレーヤー
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE2_MIKE_L,OBJFX_SHOW_NONE)　;マイク
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE2_MIKE_R,OBJFX_SHOW_NONE)　;マイク
@MOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE2_THANK,OBJFX_SHOW_NONE)　;サンキュー
@MOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE2_OK,OBJFX_SHOW_NONE)　　　　　　　;オーケー
@MOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE2_NICE,OBJFX_SHOW_NONE)　　　;ナイス
@MOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE2_GROOVE,OBJFX_SHOW_NONE)　　　　　　　;グルービー
@MOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_TSTAGE2_HIGHHAT,OBJFX_SHOW_NONE)　　　　　　　;ハイハット
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE2_GORGEOUS,OBJFX_SHOW_NONE)　　　;ゴージャス
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE2_LUCKY,OBJFX_SHOW_NONE)　;ラッキー
@WI(1)
;@SET_GOM_CHAR_DIR(GOM_HIT_CHR,DIR_M_UP_RIGHT);GOM_HIT_CHRの向き設定
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
』

MSG_EVT_TSTAGE2_A
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE2_SPOTINIT_PLAYER)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE2_PLAYER)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE2_PLAYER)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE2_PLAYER)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_TSTAGE2_PLAYER)
@WI(10)
@BGMSTART(0,BGM_tonzb);ここでよいのかな？
@FRESH_PLAYER(PC_ALL)
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE2_SPOTLIGHT)
@WI(30)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE2_SPOTLIGHT)
@WI(30)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE2_SPOTLIGHT)
@WI(30)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE2_SPOTLIGHT)
@WI(30)
@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE2_GORGEOUS_WALK)	;ゴージャス
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE2_SPOT_A,OBJFX_SHOW_NONE);SPOT A
@REMOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE2_LUCKY_WALK)		;ラッキー
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE2_SPOT_B,OBJFX_SHOW_NONE)	;SPOT B
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE2_GORGEOUS_DANCE,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE2_LUCKY_DANCE,OBJFX_SHOW_NONE)
@WAITSYS()
@SHOW_MANPU_GOM_CHAR(GOM_GORGEOUS,MANPU_BIKKURI)
@WI(30)
@HIDE_MANPU_GOM_CHAR(GOM_GORGEOUS)
@WAITSYS()
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE2_GROOVE_ADLIB)		;グルービー
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE2_LUCKY_DANCE_3,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE2_GORGEOUS_DANCE_3,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE2_LUCKY_DANCE_4,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE2_GORGEOUS_DANCE_4,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE2_LUCKY_DANCE_5,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE2_GORGEOUS_DANCE_5,OBJFX_SHOW_NONE)
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE2_LUCKY_DANCE_6,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE2_GORGEOUS_DANCE_6,OBJFX_SHOW_NONE)
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　;ステージ終了待ち
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_MAPOBJSTILL_LIVE)
@WI(30)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TSTAGE2_SCR_2,OBJFX_SHOW_NONE);スクロール、明
@MUSISTART();ここでよい？
』

MSG_EVT_TSTAGE2_B
@SET_CAMERA_PARTY()
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_KEYBOARD,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_OK,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_NICE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_GROOVE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_HIGHHAT,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_GORGEOUS_DANCE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_LUCKY_DANCE,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;1
@WI(1)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;2
』

MSG_EVT_TOPOLO_TONZURA_MC;トポロのアナウンス（トンズラ）
@OPEN(1)
@CHKFGOTO(FLG_BGM_TONZURA_FREE,_EVT_TOPOLO_TONZURA_MC2)
◆Ｈａｖｅ　Ｉ　ｇｏｔ　ａ　ｂｏｍｂｓｈｅｌｌ　ｆｏｒ　ｙｏｕ　ｔｏｎｉｇｈｔ，　ｋｉｄｓ！@KEY()↓
◆ａａａａａＡＡＡＡＡＨ！！！@KEY()↓
◆Ｋａ－Ｂｏｏｍ！！@KEY()↓
◆Ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ！！！　　Ｙｅａｈ！！
;jpn:◆ナイスな　くそったれどもに↓
;jpn:　さいこうの　ばくだんを↓
;jpn:　おみまいするぜい！@KEY()↓
;jpn:◆ンーーーーー！↓
;jpn:　ぶっとばしてくれい！↓
;jpn:　トンズラ　ブラザーズ　バーンド！
@KEY()↓
◆３・・@WI(30)２・・@WI(30)１・・@WI(30)ＧＯ！
@KEY()
@CLOSEALL()
』

_EVT_TOPOLO_TONZURA_MC2;トンズラ最後のステージ
◆ａａａａａＡＡＡＡＨ！@KEY()↓
◆Ｗｅ’ｖｅ　ｇｏｔ　ｈｕｇｅ　ｔａｌｅｎｔ　ｔｏｎｉｇｈｔ！@KEY()↓
◆Ｙｏｕ　ｇｅｔ　ａ　ｂｅａｕｔｉｆｕｌ　ｓｏｕｌ　ｓｈｏｗ！@KEY()↓
◆Ｓｈｏｗ　ｙｏｕｒ　ａｐｐｒｅｃｉａｔｉｏｎ　ｆｏｒ　ｔｈｅ　ｌａｓｔ　ｇｒｅａｔ　ｓｉｎｆｕｌ　ｐｌｅａｓｕｒｅ．．．@KEY()↓
◆Ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ！！！　　Ｂｒｉｎｇ　ｉｔ　ｏｎ！@KEY()↓
◆Ｙｅａｈ！
;jpn:◆ンーーーーー！@WI(20)↓
;jpn:　なみだ　ちょちょぎれる↓
;jpn:　ビューティフル　ソウルステージ！@KEY()↓
;jpn:◆ラスト　グレイト　エクスタシー↓
;jpn:　‥‥トンズラブラザーズバーンド！@KEY()↓
;jpn:◆カモーーーン@WI(20)　ブラザー！！
@KEY()
@CLOSEALL()
』
;----------------------------------------
;#65	●トポロ劇場楽屋の係員	10.2	T
;----------------------------------------
;#66	●埋蔵金発掘現場（セル替え大穴）
;----------------------------------------


;#67	発掘を開始するモッチーたち

;★ドコドコ砂漠のモッチーダンジョンクリア後のモッチーのセリフ
;_DSRT_SYOZI_2 でモッチーはユンボに飛び乗りダンジョン入り口に消える。

;MSG_EVT_67_SYOZI;
;モッチーとの話しの最後に以下を実行
;@REMOVE_CHAR(PRSN_DEST_FIELD_G,ANIM_MOCHI_1)    ;モッチーはユンボへ
;@WAITSYS()
;@REMOVE_CHAR(PRSN_DEST_FIELD_4A,ANIM_MOCHI_YUNBO)       ;ユンボ移動
;@WAITSYS()
;@WI(120)
;@WI(60)
;@MOVE_GOM_CHAR(GOM_YUNBOMAN_A,ANIM_MOCHI_2,OBJFX_SHOW_NONE)  ;モッチーは穴へ
;@WAITSYS()
;@SETF(FLG_DSRT_YUMBO_B_APPEAR)
@SETF(FLG_DSRT_SYOZI_DISAPPEAR);モッチー姿を消す
』

;-------------------------------------------------------------------


;#68	シゲちゃんユンボで登場	9.4	T

;★FLG_DSRT_YUMBO_SHIGE_APPEAR が ON の時。
;★絵コンテ参照。

MSG_YUNBO_APPEAR;潜んでいるユンボが以下を発行
@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを消す
@BGMSTART(0,BGM_unbo)
@WI( 120 )
@FRESH_CHAR(PRSN_DEST_FIELD_4C)	;ユンボ登場
@WAITSYS()
@MUSISTART()
@REMOVE_CHAR(PRSN_DEST_FIELD_Q,ANIM_SIGE_YUNBO_MOVE);シゲ登場
@WAITSYS()
@COLD_CHAR(PRSN_DEST_FIELD_Q)
@OPEN(1)
@GOTO(MSG_DSRT_SHIGE)
』

MSG_DSRT_SHIGE;ユンボの男Ｂ（シゲちゃん）
;フォーサイドへの橋を渡り終わったとたん、
;ユンボが追っかけてくる。ユンボからとびおりて
;話しかける。
;話しおわると、急いで去っていく。
@SET_LOOPREG(PC_NESS)			;ネスのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_DSRT_SHIGE_DEAD)
◆@DSP_NAME(PC_NESS)！　Ｇｒｅｅｔｉｎｇｓ！@KEY()↓
;jpn:◆@DSP_STS(STS_PC_NAME_NES)！@WI(30)　さん！@KEY()↓
_DSRT_SHIGE_MAIN;
◆Ｉ’ｍ　Ｇｅｏｒｇｅ，　Ｇｅｒａｒｄｏ　Ｍｏｎｔａｇｕｅ’ｓ　ｂｒｏｔｈｅｒ．@KEY()↓
◆Ｇｅｒａｒｄｏ　ｉｓ　ｉｎ　ｈｉｓ　ｍｉｎｅ，@KEY()↓
◆ｂｕｔ　ｈｅ　ｈａｓｎ’ｔ　ｆｏｕｎｄ　ａｎｙ　ｂｕｒｉｅｄ　ｔｒｅａｓｕｒｅ　ｙｅｔ．@KEY()↓
◆Ｗｅ　ｄｉｄ，　ｈｏｗｅｖｅｒ，　ｆｉｎｄ　ａ　Ｄｉａｍｏｎｄ　ｉｎｓｔｅａｄ．@KEY()↓
◆Ｇｅｒａｒｄｏ　ｔｏｌｄ　ｍｅ　ｔｏ　ｇｉｖｅ　ｉｔ　ｔｏ　@DSP_NAME(PC_NESS)．@KEY()↓
◆Ｈｅｒｅ　ｉｔ　ｉｓ．．．ｐｌｅａｓｅ　ｔａｋｅ　ｉｔ．
;jpn:◆おれ　あのはっくつげんばの↓
;jpn:　ショージ・モッチーの@KEY()↓
;jpn:◆おとうとの　チュージです。↓
;jpn:　まいぞうきんは‥‥↓
;jpn:　みつからなかった@KEY()↓
;jpn:◆んですけど　ダイヤモンドが↓
;jpn:　でてきたんで　@DSP_STS(STS_PC_NAME_NES)さんに↓
;jpn:　わたすようにって@KEY()↓
;jpn:◆ショージあにきに　たのまれまして↓
;jpn:　‥‥これ　たしかに　わたします。
@KEY()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DSRT_SHIGE_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_DIAMOND)
@GOSUB(MSG_SUB_GETGOODS_S)@KEY()↓
@SETF(FLG_DSRT_ITEM_DIA)
◆Ｗｅｌｌ，　Ｉ’ｖｅ　ｇｏｔ　ｔｏ　ｇｏ．．．@KEY()↓
◆Ｉ’ｍ　ｂｕｓｙ　ｗｏｒｋｉｎｇ　ａｔ　ｔｈｅ　ｏｔｈｅｒ　ｍｉｎｅ．．．ｂｕｓｙ，　ｂｕｓｙ，　ｂｕｓｙ！
;jpn:◆じゃ　おれ↓
;jpn:　ほかの　げんばが↓
;jpn:　いそがしいんで　かえります。@KEY()↓
;jpn:◆ゴゴゴーッ！
@KEY()
@CLOSEALL()
_DSRT_SHIGE_RESTART;		グッズフルのあとはここから
@CLRF(FLG_DSRT_YUMBO_SHIGE_APPEAR)
@FRESH_CHAR(PRSN_DEST_FIELD_Q);シゲ、ユンボの脇に
@WAITSYS()
;ユンボに乗り込むシゲ（いきなり@WAITSYSして大丈夫？）
@WAITSYS()	;この後シゲ自殺
@BGMSTART(0,BGM_unbo)
@REMOVE_CHAR(PRSN_DEST_FIELD_4C,ANIM_YUNBO_BACK);ユンボ帰る
@WAITSYS()
@MUSISTART()
;@BGMSTART(0,BGM_doko)
@CLRF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出す
@CLRF(FLG_DSRT_SYOZI_DISAPPEAR);モッチー砂漠に再登場
』

_DSRT_SHIGE_DEAD;
◆Ｇｒｅｅｔｉｎｇｓ，　@DSP_NAME(PC_NESS)！．．．Ｗｅｌｌ，@KEY()↓
◆ｇｒｅｅｔｉｎｇｓ　ｔｏ　ｙｏｕ　ｓｉｎｃｅ　@DSP_NAME(PC_NESS)　ｉｓｎ’ｔ　ｈｅｒｅ．．．
　　Ｏｒ　ｈｉｓ　ｆｒｉｅｎｄ！
;jpn:◆@DSP_STS(STS_PC_NAME_NES)！@WI(30)　さん！@WI(20)↓
;jpn:　もしくは　そのともだちさん！
@KEY()↓
@GOTO(_DSRT_SHIGE_MAIN)

_DSRT_SHIGE_ITEMFULL;
◆Ｈｅｙ！　　Ｙｏｕ’ｖｅ　ｇｏｔ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ｗｉｔｈ　ｙｏｕ．．．
;jpn:◆あれっ？！↓
;jpn:　にもつがいっぱいですね。
@KEY()↓
;　なんとかしてくださいな。@KEYNP()
;				変更
◆Ｗｅｌｌ，　Ｉ’ｖｅ　ｇｏｔ　ｔｏ　ｇｏ．．．Ｉ’ｍ　ｂｕｓｙ　ｗｏｒｋｉｎｇ　ａｔ　ｔｈｅ　ｏｔｈｅｒ　ｍｉｎｅ．．．@KEY()↓
◆Ｉ’ｌｌ　ｃｅｒｔａｉｎｌｙ　ｈａｎｇ　ｏｎ　ｔｏ　ｙｏｕｒ　Ｄｉａｍｏｎｄ．@KEY()↓
◆ｃｏｍｅ　ａｎｄ　ｇｅｔ　ｉｔ　ａｔ　ｔｈｅ　ｔｒｅａｓｕｒｅ　ｈｕｎｔｅｒ’ｓ　ｅｘｃａｖａｔｉｏｎ　ｏｆｆｉｃｅ．
;jpn:◆じゃ　おれ↓
;jpn:　ほかの　げんばが↓
;jpn:　いそがしいんで　かえります。@KEY()↓
;jpn:◆ダイヤは↓
;jpn:　しっかり　あずかっておきますから@KEY()↓
;jpn:◆まいぞうきん　はっくつほんぶに↓
;jpn:　とりにきてください。
@KEY()
@CLOSEALL()
@SETF(FLG_DSRT_DIA_RESERVE);		ダイア後からもらえるフラグ
@GOTO(_DSRT_SHIGE_RESTART);		グッズフルのあとはここから


;--------------------------------------


;#69	トンズラ最後のステージ（３回目）

;★基本的に一回目二回目と同じ。その豪華版。
;メッセージ予約で以下を発行

MSG_EVT_69_TONZURASTAGE_3;
@FUNC(6)			;マップ上全滅許可
@COLD_PLAYER(PC_ALL)
@CLOSEALL()
@BGM_EFFECT(3)
;暗転アニメ
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_FADEOUT,OBJFX_SHOW_NONE)
@WAITSYS()
@OPEN(1)
;ラッキー
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　ｆｉｎａｌ　Ｒｕｎａｗａｙ　Ｆｉｖｅ　ｐｅｒｆｏｒｍａｎｃｅ　ａｔ　ｔｈｅ　Ｔｏｐｏｌｌａ　Ｔｈｅａｔｅｒ！
;jpn:◆ウェルカム　トゥ　ザ↓
;jpn:　トンズラ　ラストライブ↓
;jpn:　イン　トポロ！
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_TEN,ANIM_TSTAGE3_SCR_1,OBJFX_SHOW_NONE);既に暗転、スクロール
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE3_MIKE_L,OBJFX_SHOW_NONE)	;マイク
@MOVE_GOM_CHAR(GOM_MIKE,ANIM_TSTAGE3_MIKE_R,OBJFX_SHOW_NONE)	;マイク
@MOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE3_THANK,OBJFX_SHOW_NONE)		;キーボード
@MOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE3_OK,OBJFX_SHOW_NONE)			;オーケー
@MOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE3_NICE,OBJFX_SHOW_NONE)		;ナイス
@MOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE3_GROOVE,OBJFX_SHOW_NONE)		;グルービー
@MOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_TSTAGE3_HIGHHAT,OBJFX_SHOW_NONE)　　　　　　　;ハイハット
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_PARTY,OBJFX_SHOW_NONE)　;固まるプレーヤー
;GOM_HIT_CHRの向き設定
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
』

MSG_EVT_TSTAGE3_A;
@FRESH_PLAYER(PC_ALL)
;@REMOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE3_LUCKY_2)        ;ラッキーにスポット
;@WAITSYS()
;@COLD_GOM_CHAR(GOM_GORGEOUS)
;@FRESH_GOM_CHAR(GOM_LUCKY)
;@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE3_GORGEOUS_2)  ;ゴージャスにスポット
;@WAITSYS()
;@COLD_GOM_CHAR(GOM_GORGEOUS)
@WI(60)
@OPEN(1)
;ゴージャス
◆Ｉｔ’ｓ　ｇｏｉｎｇ　ｔｏ　ｂｅ　ａ　ｇｒｅａｔ　ｓｈｏｗ！　　Ｗｅ’ｒｅ　ｓｏ　ｇｏｏｄ　ｉｔ　ｍａｋｅｓ　ｍｅ．．．@KEY()↓
◆ｔｈｉｎｋ　ｔｈａｔ　ｔｈｏｓｅ　ｋｉｄｓ　ｂｙ　ｔｈｅ　ｅｘｉｔ　ｗｉｌｌ　ｗｅｔ　ｔｈｅｉｒ　ｐａｎｔｓ！@KEY()↓
◆Ｔｈｏｓｅ　ｋｉｄｓ　ａｒｅ　ｈｉｐ，　ｂａｂｙ！
;jpn:◆おしっこ　ちびっちゃうような↓
;jpn:　ノリノリのステージを‥‥@KEY()↓
;jpn:◆いりぐちのちかくにいる↓
;jpn:　チビスケたちのために！
@KEYNP()
@CLOSEALL()
@WI(30)
;
@BGMSTART(0,BGM_tonz1)					;音楽スタート
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE3_THANK_3)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE3_OK_3)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE3_NICE_3)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE3_GROOVE_3)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_TSTAGE3_HIGHHAT_3)
@WI(80)
;@FRESH_GOM_CHAR(GOM_GORGEOUS)
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_TSTAGE3_GORGEOUS_1,OBJFX_SHOW_NONE)　;ゴージャス
@MOVE_GOM_CHAR(GOM_LUCKY,ANIM_TSTAGE3_LUCKY_1,OBJFX_SHOW_NONE)　　　　　　　;ラッキー
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_2,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_2,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_3,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_3,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_4,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_4,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_VENUS,ANIM_TSTAGE3_VENUS,OBJFX_SHOW_NONE)		　　　;ビーナス登場
@WI(90)
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_MAPOBJSTILL_LIVE)
@WAITSYS()
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_TSTAGE3_BAND)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_TSTAGE3_BAND)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_TSTAGE3_BAND)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_TSTAGE3_BAND)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_TSTAGE3_BAND)
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_5,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_5,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_6,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_7,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_6,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_8,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_7,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_8,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_9,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_9,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_9,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TSTAGE3_TBUS,OBJFX_SHOW_NONE)	　　　;バス
@WAITSYS()
@MOVE_GOM_CHAR(GOM_LUCKY_DANCE,ANIM_TSTAGE3_LUCKY_10,OBJFX_SHOW_NONE)　　　　　　　;ラッキーDANCE
@WAITSYS()
@MOVE_GOM_CHAR(GOM_GORGEOUS_DANCE,ANIM_TSTAGE3_GORGEOUS_10,OBJFX_SHOW_NONE)　;ゴージャスDANCE
@WAITSYS()
@REMOVE_GOM_CHAR(GOM_KEYBOARD,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_MAPOBJSTILL_LIVE)
@REMOVE_GOM_CHAR(GOM_HIGHHAT,ANIM_MAPOBJSTILL_LIVE)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TSTAGE2_SCR_2,OBJFX_SHOW_NONE);スクロール、明
;@CLRF(FLG_FOUR_TONZURA_THANKS)
@MUSISTART();ここでよい？
』

MSG_EVT_TSTAGE3_B
@SET_CAMERA_PARTY()
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;1
@WI(1)
@HIDE_GOM_CHAR(GOM_MIKE,OBJFX_HIDE_NONE)	;2
』

;       ビーナスステージ２

;@BGMSTART(0,BGM_vins2)
;予約メッセージで以下を実行
;@BGMSTOP(0)
;@CLOSEALL()
;@MOVE_GOM_CHAR(GOM_TEN,ANIM_VSTAGE1_SCR_1,OBJFX_SHOW_NONE)   ;既に暗転、スクロール
;@MOVE_GOM_CHAR(GOM_VENUS,ANIM_VSTAGE1_VENUS,OBJFX_SHOW_NONE) ;ビーナス
;@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_STAGE_PARTY,OBJFX_SHOW_NONE) ;固まる透明人間
;GOM_HIT_CHRの向き設定
;@WI(1)
;@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
;』

;MSG_EVT_VSTAGE2_A
;@FRESH_PLAYER(PC_ALL)                                   ;プレーヤーは固まってる
;@BGMSTART(0,BGM_vins2)				;ビーナスの曲スタート
;@FRESH_GOM_CHAR(GOM_VENUS)                              ;歌うビーナス
;@WAITSYS()                                              ;ステージ終了待ち
;@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_VSTAGE1_SCR_2,OBJFX_SHOW_NONE);スクロール、明転
;』

;MSG_EVT_VSTAGE2_B
;@SET_CAMERA_PARTY()
;@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)                  ;固まる透明人間消す
;』

;------------------------------------------------


;#70	ポーキーの子分に叩き出される	10.4	T

;★絵コンテの通り。

MSG_EVT_70_POKEY;
;ポーキーとの会話の最後で
@RESF(FLG_TEMP_1)
@RESF(FLG_TEMP_2)
@REMOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_B,ANIM_GUARD_A_1)　;用心棒Ａ
@REMOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_C,ANIM_GUARD_B_1)　;用心棒Ｂ
@WI(120)
@WI(60)
@SETF(FLG_TEMP_1)　　　　　　　　　　　　　　　　　　　　　　　;牽引開始
@SETF(FLG_TEMP_2)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TO_GUARD,OBJFX_SHOW_NONE)　　　　;ついてく
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI(1)
...;@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
...;@FRESH_PLAYER(PC_ALL)
...;@WAITSYS()
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER(PC_ALL)
@WARP(WARP_FOUR_47_POKEY_P)　　　　　　　　　　　　　;ワープ
@MOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_B,ANIM_GUARD_A_2,OBJFX_SHOW_NONE)
@MOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_C,ANIM_GUARD_B_2,OBJFX_SHOW_NONE)
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TO_GUARD,OBJFX_SHOW_NONE)　　　　;ついてく
@GOSUB( MSG_FOLLOW_GOM_HIT_CHR_SUBR )	;透明君について行く
...;@WI(1)
...;@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
...;@FRESH_PLAYER(PC_ALL)
...;@WAITSYS()
...;@SET_CAMERA_PARTY()
...;@COLD_PLAYER(PC_ALL)
@COLD_CHAR( PRSN_FRSD_BUIL_47F_POKEY_B )
@COLD_CHAR( PRSN_FRSD_BUIL_47F_POKEY_C )
@GOSUB(MSG_FOUR_POKEYGUARD)
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_B,ANIM_GUARD_3)　　　;用心棒Ａドアまで
@WAITSYS()　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　
@REMOVE_CHAR(PRSN_FRSD_BUIL_47F_POKEY_C,ANIM_GUARD_3)　　　;用心棒Ｂドアまで
@WAITSYS()
@SETF(FLG_FOUR_POKEY);ポーキーのメッセージ替え用
』
MSG_FOUR_POKEYGUARD;
@OPEN(1)
◆Ｙｏｕ　ｍｕｓｔ　ｎｅｖｅｒ　ｓｈｏｗ　ｙｏｕｒ　ｆａｃｅ　ａｒｏｕｎｄ　Ｍａｓｔｅｒ　Ｐｏｋｅｙ．　　Ｙｏｕ　ｇｏｔ　ｔｈａｔ？
;jpn:◆いいか？　２どと↓
;jpn:　ポーキーぼっちゃまのまえに↓
;jpn:　すがたを　みせるんじゃねぇぜ。
@KEY()
@CLOSEALL()
』

;------------------------------------------------

;突然サルダンジョンについて
;SE_se65_ape;サル移動の音

;------------------------------------------------


;#71	停電デパート	10.5	T

;★絵コンテ参照。デパート一階のネズミに近づくと停電。
;（プレイヤーキャラが接近したらネズミが MSG_FOUR_DEPT_MOUSE を発行。）
;★ネズミはヤメ。以下を修正します。

;★以下の MSG_FOUR_DEPT_ANNOUNCE_1 ～ 3 をエスカレータにセットする。
;（踏むと何度でも表示される）

;★デパート／４階・事務室の暗闇デパートのモンスターを倒す
;（FLG_FOUR_DEPT_BOSS_APPEAR /off）と、デパートは
;平常通りに戻る。（ポーラは帰ってこない。）

MSG_EVT_71_SET_HRECT_1;
@RES_HIT_RECT(1)
@SET_HIT_RECT(1,HRECT_FOUR_DEPT_1,MSG_EVT_71_DEPT_START)
』

MSG_EVT_71_DEPT_START;
@SET_LOOPREG(PC_NESS)			;ネスのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@FALSE_GOTO(_EVT_71_DEPT_START_PAULA)	;死んでなければよし
@SET_LOOPREG(PC_JEFF)			;ジェフのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(MSG_EVT_71_SET_HRECT_1)	;二人とも死んでたら再セット
;
_EVT_71_DEPT_START_PAULA;
@SET_LOOPREG(PC_PAULA)			;ポーラのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(MSG_EVT_71_SET_HRECT_1);ポーラが死んでいたら停電しないで再セット
;パレット切り替え（停電）
@BGM_EFFECT(2)
@WI(10)
@BGMSTOP(0)
@SET_PALLETSET(31,0,1);真っ暗
@WI(20)
@SET_PALLETSET(20,1,1);明るい
@WI(20)
@SET_PALLETSET(31,0,1);真っ暗
@WI(1)
@SET_PALLETSET(20,1,1);明るい
@WI(1)
@SET_PALLETSET(31,0,1);真っ暗
@WI(1)
@BGMSTART(0,BGM_poky0)
@WI(20)
@MOVE_GOM_CHAR(GOM_DOMOOK,ANIM_AYASII,OBJFX_SHOW_NONE);あやしいや｣
@WI(50)
@HIDE_PLAYER(PC_PAULA,OBJFX_HIDE_NONE)
@DEL_PARTY(PC_PAULA)
@SET_PALLETSET(20,1,1);明るい
@WI(20)
@SET_PALLETSET(31,0,1);真っ暗
@HIDE_CHAR(PRSN_FRSD_DEPT_A,OBJFX_HIDE_NONE);店員を消す
@HIDE_CHAR(PRSN_FRSD_DEPT_B,OBJFX_HIDE_NONE)
@HIDE_CHAR(PRSN_FRSD_DEPT_L,OBJFX_HIDE_NONE);ネズミを消す
;
@SETF(FLG_GLOBAL_POLA_KIDNAPPED);誘拐中
@SETF(FLG_FOUR_DEPT_BOSS_APPEAR)
@SETF(FLG_FOUR_DEPT_SWITCH)
@CLRF(FLG_FOUR_INFO_D_APPEAR);デパート開店情報の人消える
@WI(30)
@WI(60)
@GOSUB(MSG_SUB_BGM_CHANGE_1)
;@BGMSTART(0,BGM_fuan);ＢＧＭ切り替え
MSG_FOUR_DEPT_ANNOUNCE_1;
;デパートダンジョンの店内放送
@SE(SE_se72);あやしい音
@WI(180)
@OPEN(1)
◆Ｙｏｕｒ　ａｔｔｅｎｔｉｏｎ　ｐｌｅａｓｅ，@KEY()↓
◆ｗｏｕｌｄ　ｔｈｅ　ｃｕｓｔｏｍｅｒ　ｆｒｏｍ　Ｏｎｅｔｔ，　Ｍｒ．　@DSP_NAME(PC_NESS)，@KEY()↓
◆ｐｌｅａｓｅ　ｐｒｏｃｅｅｄ　ｔｏ　ｔｈｅ　ｏｆｆｉｃｅ　ｏｎ　ｔｈｅ　ｆｏｕｒｔｈ　ｆｌｏｏｒ．@KEY()↓
◆Ｔｈａｔ　ｗａｓ　ｃｕｓｔｏｍｅｒ　@DSP_NAME(PC_NESS)，　４ｔｈ　ｆｌｏｏｒ　ｏｆｆｉｃｅ．．．@KEY()↓
◆Ｇｗａａａａａａａａａｇｈ！
;jpn:◆およびだしを　もうしあげます。↓
;jpn:　オネットから　おこしの↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)さま‥‥@KEY()↓
;jpn:◆おともだちの@DSP_STS(STS_PC_NAME_PAULA)さまが↓
;jpn:　４かいのじむしょで↓
;jpn:　おまちです。‥‥クケッ。
@KEYNP()
@CLOSEALL()
@RES_HIT_RECT(1)
@SET_HIT_RECT(1,HRECT_FOUR_DEPT_3,MSG_FOUR_DEPT_ANNOUNCE_2)
;ポーラタコ消し検査
@Q_HAVE(PC_PAULA,GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_END)
@SETF(FLG_FOUR_PAULA_TAKOKESHI);ポーラがタコ消しを持っている
@GOODSOUT(PC_PAULA,GDS_TOOL_KEY_TAKOKESHI);ポーラのタコ消しは抜く
』

MSG_FOUR_DEPT_ANNOUNCE_2;
@SE(SE_se72);あやしい音
@WI(180)
@OPEN(1)
◆@DSP_NAME(PC_NESS)，　Ｃｕｓｔｏｍｅｒ　@DSP_NAME(PC_NESS)，　ｐｌｅａｓｅ　ｈｕｒｒｙ　ｔｏ　@DSP_NAME(PC_PAULA)．．．@KEY()↓
◆Ｇｗａａａａａａａｒｇｈ！
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さま　@DSP_STS(STS_PC_NAME_NES)さま↓
;jpn:　‥‥クケッ　クケッ　クケ↓
;jpn:　おはやく　@DSP_STS(STS_PC_NAME_PAULA)さまのところに@KEY()↓
;jpn:◆おいそぎください。↓
;jpn:　クケケケケケケ。
@KEYNP()
@CLOSEALL()
@RES_HIT_RECT(1)
@SET_HIT_RECT(1,HRECT_FOUR_DEPT_4,MSG_FOUR_DEPT_ANNOUNCE_3)
』

MSG_FOUR_DEPT_ANNOUNCE_3;
@SE(SE_se72);あやしい音
@WI(180)
@OPEN(1)
◆@DSP_NAME(PC_NESS)，　Ｃｕｓｔｏｍｅｒ　@DSP_NAME(PC_NESS)．．．@KEY()↓
◆Ｇｗａａｇｈ！　　Ｇｗａａｒｇｈ！！
;jpn:◆@DSP_STS(STS_PC_NAME_NES)さま↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)さま！↓
;jpn:　クケッ　クケッ‥‥
@KEYNP()
@CLOSEALL()
@RES_HIT_RECT(1)
』

MSG_FOUR_DEPT_MOUSE;
@CHKFGOTO(FLG_FOUR_DEPT_OK,_FOUR_DEPT_MOUSE)
@SET_LOOPREG(PC_PAULA)			;ポーラのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_FOUR_DEPT_MOUSE_DEAD)
@SET_LOOPREG(PC_NESS)			;ネスのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@FALSE_GOTO(_FOUR_DEPT_MOUSE_MAIN)
@SET_LOOPREG(PC_JEFF)			;ネスのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_FOUR_DEPT_MOUSE_DEAD)
_FOUR_DEPT_MOUSE_MAIN;
◆（Ｓｏｍｅｈｏｗ，　Ｉ　ｆｅｅｌ　ｌｉｋｅ　ｔｈｅ　ｌｉｇｈｔｓ　ｗｉｌｌ　ｇｅｔ　ｔｕｒｎｅｄ　ｏｆｆ　ｉｎ　ｔｈｅ　ｄｅｐａｒｔｍｅｎｔ　ｓｔｏｒｅ．@KEY()↓
◆Ｉ　ｇｕｅｓｓ　ｉｔ’ｓ　ｊｕｓｔ　ａ　ｍｏｕｓｅ’ｓ　ｓｉｘｔｈ　ｓｅｎｓｅ．．．）
;jpn:◆（なんか　このデパート↓
;jpn:　ていでんするような↓
;jpn:　きがする‥‥。@KEY()↓
;jpn:◆これは　ねずみの↓
;jpn:　ちょっかんです）
@KEYNP()
』
_FOUR_DEPT_MOUSE;松（思い出？）
◆（Ｓｏｍｅｈｏｗ，　Ｉ　ｆｅｌｔ　ｌｉｋｅ　ｔｈｅ　ｌｉｇｈｔｓ　ｗｏｕｌｄ　ｇｅｔ　ｔｕｒｎｅｄ　ｏｆｆ　ｉｎ　ｔｈｅ　ｄｅｐａｒｔｍｅｎｔ　ｓｔｏｒｅ．@KEY()↓
◆Ｉ　ｇｕｅｓｓ　ｉｔ’ｓ　ｊｕｓｔ　ａ　ｍｏｕｓｅ’ｓ　ｓｉｘｔｈ　ｓｅｎｓｅ．．．）
;jpn:◆（なんか　このデパート↓
;jpn:　ていでんしたような↓
;jpn:　きがする‥‥。@KEY()↓
;jpn:◆これは　ねずみの↓
;jpn:　おもいでです）
@KEYNP()
』

_FOUR_DEPT_MOUSE_DEAD;ポーラ死にのときにネズミがもう一匹出現する（のは無理）
◆（Ｈｅｙ　ｙｏｕ！　　Ｉ’ｖｅ　ｇｏｔ　ｔｈｉｓ　ｅｅｒｉｅ　ｆｅｅｌｉｎｇ．．．ｌｉｋｅ　ｔｈｅｒｅ’ｓ　ａ　ｇｈｏｓｔ　ｗａｌｋｉｎｇ　ａｌｏｎｇ　ｗｉｔｈ　ｙｏｕ．．．）
;jpn:◆（あんた　ユーレイと↓
;jpn:　あるいてるみたいで↓
;jpn:　かんじわるいよ）
@KEYNP()
』

;----------------------------------------


;#72	トンチキさんの最期	10.6	T

;★絵コンテ参照。
;★人だかりは、トンチキさんがいなくなるとランダム動きに変わる。
;（人だかりの出現を管理するシナリオフラグがクリアされるので、
;画面が書き変わると、もう人だかりはいない。）

MSG_EVT_72_BORO;
@CLOSEALL()
@REMOVE_CHAR(PRSN_FRSD_FIELD_O,ANIM_FRSD_FIELD_O);どく
@WAITSYS()
@REMOVE_CHAR(PRSN_FRSD_FIELD_O,ANIM_MAPOBJSTILL_LIVE);消えない
』

MSG_EVT_72_TONCHIKI;
@CLOSEALL()
@SETF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを消す
@HIDE_CHAR(PRSN_FRSD_FIELD_K,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_NUSUTTO_NUSI,ANIM_TONCHIKI,OBJFX_SHOW_NONE);ふらふらトンチキ
@RESF(FLG_TEMP_1);トンチキさん待機
@WI(40)
@REMOVE_CHAR(PRSN_FRSD_FIELD_L,ANIM_FRSD_FIELD_L);街の人退く
@REMOVE_CHAR(PRSN_FRSD_FIELD_M,ANIM_FRSD_FIELD_M)
@WI(94)
@SETF(FLG_TEMP_1);トンチキさん移動開始
@WAITSYS()
@REMOVE_CHAR(PRSN_FRSD_FIELD_P,ANIM_FRSD_FIELD_P);街の人さがる
@REMOVE_CHAR(PRSN_FRSD_FIELD_Q,ANIM_FRSD_FIELD_Q)
@WAITSYS()
@REMOVE_CHAR(PRSN_FRSD_FIELD_P,ANIM_PEOPLEWALK1);街の人散る
@REMOVE_CHAR(PRSN_FRSD_FIELD_Q,ANIM_PEOPLEWALK1)
@REMOVE_CHAR(PRSN_FRSD_FIELD_L,ANIM_PEOPLEWALK1)
@REMOVE_CHAR(PRSN_FRSD_FIELD_M,ANIM_PEOPLEWALK1)
@REMOVE_CHAR(PRSN_FRSD_FIELD_N,ANIM_PEOPLEWALK1)
@REMOVE_CHAR(PRSN_FRSD_FIELD_O,ANIM_PEOPLEWALK1)
@RESF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出す
@GOSUB(MSG_SUB_BGM_CHANGE_1);フォーサイドの曲に戻す
』

;-------------------------------------------------------------
;#73	●ムーンサイドに入る

;@SE(SE_se79_my_open_fanfare)

;--------------------------------


;#74	フォーサイドに戻る（倉庫）

;★ムーンサイドで幻影マシンを倒した時、このイベントを起動する。
;★幻覚からさめるという設定なので、それらしいサイケな演出をしてみたい。

;---------------------------------------------------------------------

MSG_FOUR_BLDG_GORGEOUS;ユダンロボを倒した後出現するトンズラたちのセリフ
◆Ｔｈｅ　ｒｏｏｍ　ｎｅｘｔ　ｄｏｏｒ　ｓｅｅｍｓ　ｓｕｓｐｉｃｉｏｕｓ　ｓｏｍｅｈｏｗ．．．
;jpn:◆となりのへやが↓
;jpn:　あやしいんじゃ。
@KEYNP()
』
MSG_FOUR_BLDG_LUCKY;
◆Ｉ　ｔｈｏｕｇｈｔ　ｔｈａｔ　Ｉ　ｈｅａｒｄ　ａ　ｇｉｒｌ’ｓ　ｖｏｉｃｅ．．．
;jpn:◆おんなのこの↓
;jpn:　こえがした　ようなきがする。
@KEYNP()
』
MSG_FOUR_BLDG_OKEY;
◆Ｗｅ　ｗｏｕｌｄ　ｌｉｋｅ　ｔｏ　ｐａｙ　ｙｏｕ　ｂａｃｋ．．．@KEY()↓
◆Ｗｅ’ｌｌ　ｈｅｌｐ　ｙｏｕ　ｉｎ　ｗｈａｔｅｖｅｒ　ｗａｙ　ｗｅ　ｃａｎ．．．
;jpn:◆オレたち↓
;jpn:　おまえらに↓
;jpn:　おれいがしたいんだ。@KEY()↓
;jpn:◆いくらでも↓
;jpn:　ちからになるぜ！
@KEYNP()
』
MSG_FOUR_BLDG_GROOVY;
◆Ｗｅ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ．．．ｗｅ　ａｒｅ　ｓｔｒｏｎｇ，　ｈｏｗｅｖｅｒ．．．
;jpn:◆かねはなくても↓
;jpn:　ちからは　あるんや。
@KEYNP()
』
MSG_FOUR_BLDG_NICE;
◆Ｌｅｔ’ｓ　ｂｒｅａｋ　ｉｎｔｏ　ｔｈｅ　ｒｏｏｍ　ｎｅｘｔ　ｄｏｏｒ．．．@KEY()↓
◆’Ｃｅｐｔ　Ｉ　ｎｅｅｄ　ｔｏ　ｇｏ　ｔｏ　ｔｈｅ　ｂａｔｈｒｏｏｍ　ｆｉｒｓｔ．．．
;jpn:◆さあ　となりのへやに↓
;jpn:　ふみこもうぜ。@KEY()↓
;jpn:◆そのまえに　オレは↓
;jpn:　ちょっと↓
;jpn:　トイレにいってくる。
@KEYNP()
』

;#75	モノトリー氏の部屋

;★部屋に一歩入ったらオートメッセージで MSG_FOUR_MONOTOLY を表示。
;★モノトリーはブルブル震えている。

;★モノトリーのセリフを聞くこと、ポーラと話して再び仲間にすること
;の２点がクリアされるまでは、プレイヤーキャラを部屋の外に出さない。
;（ワープメッセージ MSG_WARP_FOUR_MONOROOM_OUT で設定。
;外に出ようとするとポーラが駆け寄ってきてセリフ。）

;★ポーラを再び仲間にして、モノトリーの話を聞いたら
;部屋の外に出ようとするとジェフがしゃべりだす。（MSG_FOUR_JEFF_MONOTOLY）

MSG_FOUR_MONOTOLY;
;モノトリーに近寄るとアニメ側から発行
@FUNC(5)				;トンズラバスでスリーク行くまで
					;マップ上での全滅防ぐ
@COLD_CHAR( PRSN_FRSD_BUIL_48F_MONO_A )	;モノトリー凍結
@OPEN( 1 )
◆Ｓｔｏｐ！　　Ｔｈａｔ’ｓ　ｅｎｏｕｇｈ！　　Ｐｌｅａｓｅ　ｓｔｏｐ！@KEY()↓
◆Ｉ　ｇｉｖｅ　ｕｐ！　　Ｉ　ｒｅａｌｌｙ　ｄｏ！
@KEY()
@GOSUB(MSG_SUB_ALLHEAL_POWR)	;全回復しておく
@SE(SE_se25_b_healing)
@WI(90)
@CLOSEALL()
@MUSISTART()	;無音から幼稚園曲に
@FRESH_CHAR( PRSN_FRSD_BUIL_48F_MONO_A )	;モノトリー放つ
@WI( 30 )	;追い付けない間
』


MSG_FOUR_PAULA_MONOROOM;
;くらくらしたポーラのセリフ
;ポーラのモノローグ
@SHOW_MANPU_PLAYER( PC_PAULA, MANPU_BIKKURI )
@WI(15)
@GET_PLAYER_DIR( PC_NESS, 1, PC_PAULA )	;ポーラの方を
@SET_PLAYER_DIR( PC_NESS, 0 )		;　ネスが向く
@GET_PLAYER_DIR( PC_JEFF, 1, PC_PAULA )	;ポーラの方を
@SET_PLAYER_DIR( PC_JEFF, 0 )		;　ジェフが向く
@WI(45)
@BGM_EFFECT( 3 )	;フェードアウト長め
@HIDE_MANPU_PLAYER( PC_PAULA )
;パーティ以外暗くする
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_EVT_FEEL_DIGGY, OBJFX_SHOW_NONE )
@WAITSYS()
@COLD_GOM_CHAR( GOM_HIT_CHR )
;ポーラ以外を消す
@HIDE_PLAYER( PC_NESS, OBJFX_HIDE_NONE )
@HIDE_PLAYER( PC_JEFF, OBJFX_HIDE_NONE )
@WI( 180 )	;ＯＢＪＦＸの間含む
@OPEN(1)
◆．．．．．
;jpn:◆‥‥‥。
@KEYNP()
@CLOSEALL()
@WI( 60 )
;ポーラ以外のパーティを表示
@SHOW_PLAYER( PC_NESS, OBJFX_SHOW_NONE )
@SHOW_PLAYER( PC_JEFF, OBJFX_SHOW_NONE )
@WI( 180 )	;ＯＢＪＦＸの間含む
;また元の明るさに
@FRESH_GOM_CHAR( GOM_HIT_CHR )
@WAITSYS()
@MUSISTART()
@OPEN(1)
◆Ｏｏｏｈ．．．Ｉ　ｗａｓ　ａ　ｌｉｔｔｌｅ　ｄｉｚｚｙ，　ｂｕｔ　ｎｏｗ　Ｉ’ｍ　ｏｋａｙ．@KEY()↓
◆．．．ｔｏ　ｇｅｔ　ｔｏ　Ｓｕｍｍｅｒｓ．．．ｗｅ　ｎｅｅｄ　ｔｏ　ｇｏ　ｂａｃｋ　ｔｏ　Ｔｈｒｅｅｄ．@KEY()↓
◆Ｙｅｐ，　ｓｏｍｅｈｏｗ　Ｉ　ｋｎｏｗ　ｔｈａｔ’ｓ　ｗｈｅｒｅ　ｗｅ　ｍｕｓｔ　ｇｏ．．．
;jpn:◆ちょっと　めまいがしただけよ。↓
;jpn:　だいじょうぶ。@KEY()↓
;jpn:◆‥‥サマーズに↓
;jpn:　いくためには‥‥。@KEY()↓
;jpn:◆スリークに↓
;jpn:　もどるひつようがあるわ。@KEY()↓
;jpn:◆いま　つよく↓
;jpn:　それを　かんじたの。
@KEYNP()
@CLOSEALL()
;
@WI(60)
;;@CHKFGOTO(FLG_THRK_URBAN_ZOMBI_GONE,MSG_CES_SORRY);CES版用
;
@CLRF(FLG_THRK_BROKEN_SKYW_APPEAR)
@SETF(FLG_THRK_FIXED_SKYW_APPEAR)
@SETF(FLG_THRK_OZISAN_D_DISAPPEAR);テントの人消える
@SETF(FLG_FOUR_OK)
;@CLRF(FLG_FOUR_MAID_THANKS)	;後からも出ててよいので不用！
;@CLRF( FLG_SYS_DISTLPT )	;ヘリポートでのテレポート禁止を解除
@GOSUB(MSG_SUB_TLPTOK_OTHERDELIVERY)	;でれバリー中以外ならテレポート許可
;---------------
@SETF(FLG_BGM_TONZURA_FREE)	;トンズラ解放の曲設定
;---------------
』
;----------------------------------


;#76	トンズラバスに乗る（２回目）

;★モノトリーの部屋のイベント終了（ジェフのセリフを聞いた）後
;廊下の外に出ると、トンズラが待ち構えていて
;MSG_FOUR_TONZURA_MONOTOLY を発行して出口に消える。

;★一階に降りてモノトリービルの外に出ると、
;トンズラたちがバスに乗り込んでいる。（特殊イベント４１番と同様）
;プレイヤーキャラがバスに接触したらプレイヤーパーティーを順に消して出発！
;★到着したらゴージャスがまず出現して、順にプレイヤーパーティー出現。
;ゴージャスは MSG_THRK_TONZURA_GOODLUCK を発行し、再びバスに乗って消える。

MSG_EVT_76_TONZURA_WAITING;
@RESF(FLG_TEMP_1)
@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_MONOTORY_OUT_A_GORGEOUS);ムーブ命令を変更
@REMOVE_GOM_CHAR(GOM_LUCKY,ANIM_MONOTORY_OUT_A_LUCKY)
@REMOVE_GOM_CHAR(GOM_NICE,ANIM_MONOTORY_OUT_A_NICE)
@REMOVE_GOM_CHAR(GOM_OK,ANIM_MONOTORY_OUT_A_OK)
@REMOVE_GOM_CHAR(GOM_GROOVE,ANIM_MONOTORY_OUT_A_GROOVE)
@OPEN(1)
MSG_FOUR_TONZURA_MONOTOLY;
;トンズラのだれでも
;通路をふさいでて、必ずしゃべらせるようにする。
;しゃべりおわったら、ピューッと先に走って消える。
@OPEN(1)
◆Ｗｏｗ！　　Ｙｏｕ　ｇｕｙｓ　ｄｉｄ　ａ　ｌｏｔ　ｗｈｉｌｅ　Ｉ　ｗａｓ　ｉｎ　ｔｈｅ　ｂａｔｈｒｏｏｍ！@KEY()↓
◆Ｈａ　ｈａ　ｈａ　ｈａ．．．@KEY()↓
◆Ｙｏｕ　ｗａｎｔ　ｔｏ　ｇｅｔ　ｔｏ　Ｔｈｒｅｅｄ　ａｓ　ｓｏｏｎ　ａｓ　ｐｏｓｓｉｂｌｅ？@KEY()↓
◆Ｗｅ　ｃａｎ　ｔａｋｅ　ｙｏｕ　ｔｏ　Ｔｈｒｅｅｄ　ｉｎ　ｏｕｒ　ｔｏｕｒ　ｂｕｓ．@KEY()↓
◆Ｉ’ｌｌ　ｇｅｔ　ｔｈｅ　ｂｕｓ　ａｎｄ　ｗａｉｔ　ｆｏｒ　ｙｏｕ　ｊｕｓｔ　ｏｕｔｓｉｄｅ　ｔｈｅ　ｂｕｉｌｄｉｎｇ．．．
;jpn:◆なーんだ↓
;jpn:　トイレにいってるあいだに↓
;jpn:　だいかつやく　しやがって！@KEY()↓
;jpn:◆ハハハ@KEY()↓
;jpn:◆なになに？　@DSP_STS(STS_PC_NAME_PAULA)ちゃん↓
;jpn:　いまから　スリークに↓
;jpn:　いきたいって？@KEY()↓
;jpn:◆ＯＫ！@KEY()↓
;jpn:◆おれたちの　トラベリング・バスで↓
;jpn:　スリークまで　おくるぜ。@KEY()↓
;jpn:◆ひとあしさきに↓
;jpn:　くるまを　まわしとく。@WI(20)↓
;jpn:　ビルの　そとで　まってるぜ！
@KEY()
@CLOSEALL()
@SETF(FLG_FOUR_TONZURABUS_APPEAR)
@CLRF(FLG_FOUR_BLDG_TONZURA_APPEAR)
@SETF(FLG_TEMP_1)
@WAITSYS()
@SET_HIT_RECT(1,HRECT_PHONE_MONO_A,MSG_FOUR_TELE_APPLEKID);アップルから電話
』

MSG_FOUR_TONZURABUS_GORGEOUS;
;@FUNC(6)				;マップ上での全滅許可（まだだめ）
@OPEN(1)
◆Ｏｋａｙ！　　Ｙｏｕ　ｃａｎ　ｇｅｔ　ｏｎ　ｔｈｅ　ｂｕｓ　ｎｏｗ．．．
;jpn:◆オーケー！↓
;jpn:　ノリノリで　バスにのれ！
@KEY()
@CLOSEALL()
』

MSG_EVT_76_GORGEOUS;
@FUNC(5)			;配達禁止
;-----
@SHOW_MANPU_CHAR(PRSN_FRSD_FIELD_T,MANPU_SURPRISE)
@WI(60)
@HIDE_MANPU_CHAR(PRSN_FRSD_FIELD_T)
@REMOVE_CHAR(PRSN_FRSD_FIELD_T,ANIM_GORGEOUS_MONO)
@WAITSYS()
@COLD_CHAR(PRSN_FRSD_FIELD_T)
@GET_PLAYER_DIR(PC_NESS,2,PRSN_FRSD_FIELD_T);ネスからゴージャスの方向を調べる
@SET_PLAYER_DIR(PC_NESS,0);ネスをその方向に向ける
@GET_PLAYER_DIR(PC_PAULA,2,PRSN_FRSD_FIELD_T);ポーラからゴージャスの方向を調べる
@SET_PLAYER_DIR(PC_PAULA,0);ポーラをその方向に向ける
@GET_PLAYER_DIR(PC_JEFF,2,PRSN_FRSD_FIELD_T);ジェフからゴージャスの方向を調べる
@SET_PLAYER_DIR(PC_JEFF,0);ジェフをその方向に向ける
@OPEN(1)
◆Ｈｅｈ　ｈｅｈ　ｈｅｈ．．．↓
　　Ｔｈｅｒｅ’ｓ　ｎｏ　ｎｅｅｄ　ｔｏ　ｗａｉｔ．．．
;jpn:◆カッカッカッ↓
;jpn:　えんりょは　いらんわい！
@KEY()
@CLOSEALL()
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_TBUS_RIDE_MONO,OBJFX_SHOW_NONE)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@FRESH_CHAR(PRSN_FRSD_FIELD_T)
@WAITSYS()
@WI(60)
@HIDE_GOM_CHAR(GOM_HIT_CHR,OBJFX_HIDE_NONE)
@SET_CAMERA_PARTY()
;そのまま乗車

MSG_EVT_RIDE_TONZURABUS_MONO;トンズラバスに近づくと以下を発行
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_FORBID_CONTROL, OBJFX_SHOW_NONE );入力禁止
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_INTO_TONZURABUS_MONO,OBJFX_SHOW_NONE);乗車する透明人間
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@HIDE_PLAYER(PC_ALL,OBJFX_HIDE_NONE)
@CLRF(FLG_BGM_TONZURA_FREE)
@SETF(FLG_BGM_TBUS)
@MUSISTART()
;@BGMSTART(0,BGM_tonz2)
;@DIS_BGMCHG();虫を無視
@COLD_PLAYER(PC_ALL)
@CLRF(FLG_FOUR_TONZURABUS_APPEAR)
@REMOVE_CHAR(PRSN_FRSD_FIELD_T,ANIM_GORGEOUS_MONO_RIDE)
@WAITSYS()
@OPEN(1)
;@GOSUB(MSG_FOUR_TONZURABUS_GORGEOUS)
◆Ａｌｌ　ｒｉｇｈｔ．．．ｏｎ　ｔｏ　Ｔｈｒｅｅｄ！
;jpn:◆さあ　スリークめざして↓
;jpn:　しゅっぱつだ！
@KEY()↓
@CLOSEALL()
@REMOVE_CHAR(PRSN_FRSD_FIELD_4A,ANIM_TBUS_TO_FOUR_TUNNEL)
@WI(60)
@SET_CAMERA_CHAR(PRSN_FRSD_FIELD_4A)
@FRESH_PLAYER(PC_ALL)
@RES_HIT_RECT(1)
』

MSG_EVT_TBUS_FOUR_TUNNEL;フォーサイドからトンネルへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_FOUR_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_FOUR_TUNNEL)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TUNNEL_BRDG;トンネルから橋へ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TUNNEL_BRDG,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_BRDG_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_BRDG_TUNNEL;橋からトンネルへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_BRDG_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_BRDG_TUNNEL_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TUNNEL_DSRT;トンネルから砂漠へ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TUNNEL_DSRT,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_DSRT_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』
MSG_EVT_TBUS_DSRT_TUNNEL;砂漠からトンネルへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_DSRT_TUNNEL,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_DSRT_TUNNEL_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TUNNEL_HWAY_L;トンネルからハイウェイへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TUNNEL_HWAY_L,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_HWAY_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_HWAY_TUNNEL_L;ハイウェイからトンネルへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_HWAY_TUNNEL_L,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_HWAY_TUNNEL_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TUNNEL_THRK_L;トンネルからスリークへ
@SET_CAMERA_PARTY()
@MOVE_GOM_CHAR(GOM_TONZURABUS,ANIM_TBUS_TUNNEL_THRK_L,OBJFX_AFTER_WARP)
@WARP(WARP_BUS_TUNNEL_THRK_L)
;@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_TONZURABUS)
』

MSG_EVT_TBUS_TOUCH_THRK_L;スリークに着いた
@BGM_EFFECT(3)
@WI(60)
@CLRF(FLG_BGM_TBUS)
@MUSISTART()
@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_OUT_TBUS_R,OBJFX_SHOW_NONE)
@WI(1)
@SET_CAMERA_GOM_CHAR(GOM_HIT_CHR)
@SHOW_PLAYER(PC_ALL,OBJFX_SHOW_NONE)
@FRESH_PLAYER(PC_ALL)
@WAITSYS()
@SET_PLAYER_DIR(PC_NESS,DIR_M_UP)
@SET_PLAYER_DIR(PC_PAULA,DIR_M_UP)
@SET_PLAYER_DIR(PC_JEFF,DIR_M_UP)
@SET_CAMERA_PARTY()
@COLD_PLAYER(PC_ALL)
;ゴージャスを登場させる処理
@MOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_OUT_TBUS_GORGEOUS,OBJFX_SHOW_NONE)	;バスから降りて
@WAITSYS()
@WI(30)
@COLD_GOM_CHAR(GOM_GORGEOUS)
;@SHOW_MANPU_GOM_CHAR(GOM_GORGEOUS,MANPU_SURPRISE)
@GOSUB(MSG_THRK_TONZURA_GOODLUCK)
;@HIDE_MANPU_GOM_CHAR(GOM_GORGEOUS)
@WI(20)
@REMOVE_GOM_CHAR(GOM_GORGEOUS,ANIM_INTO_TBUS_GORGEOUS)			;バスに乗り込む
@WAITSYS()
@WI(30)
;トンズラバス発進
@FRESH_GOM_CHAR(GOM_TONZURABUS)
@WAITSYS()
@RESF(FLG_SYS_MONSTER_OFF);ワンダリングモンスターを出現させる
@FUNC(6)			;配達許可
@MOVE_GOM_CHAR( GOM_HIT_CHR4, ANIM_PERMIT_CONTROL, OBJFX_SHOW_NONE );入力許可
』
MSG_THRK_TONZURA_GOODLUCK;
@GOSUB(MSG_SUB_TLPTOK_OTHERDELIVERY)	;でれバリー中以外ならテレポート許可
@OPEN(1)
◆Ａｌｌ　ｒｉｇｈｔ！　　Ｗｅ　ｍａｄｅ　ｉｔ！@KEY()↓
◆Ｉ’ｍ　ｓｏｒｒｙ　ｗｅ　ｃｏｕｌｄｎ’ｔ　ｄｏ　ｍｏｒｅ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｒｅｍｅｍｂｅｒ，　ｔｈｏｕｇｈ．．．ｗｅ’ｒｅ　ｏｎ　ｙｏｕｒ　ｓｉｄｅ．@KEY()↓
◆Ｗｈｅｎ　ｙｏｕ’ｒｅ　ｈａｖｉｎｇ　ａ　ｔｏｕｇｈ　ｔｉｍｅ，@KEY()↓
◆ｊｕｓｔ　ｔｈｉｎｋ　ｏｆ　ｏｕｒ　ｓｏｎｇｓ@KEY()↓
◆ａｎｄ　ｉｍａｇｉｎｅ　ｔｈｅ　Ｒｕｎａｗａｙ　Ｆｉｖｅ　ｓｉｎｇｉｎｇ　ｓｏｍｅｗｈｅｒｅ　ｆａｒ，@KEY()↓
◆ｆａｒ　ａｗａｙ．．．@KEY()↓
◆Ｂｙ　ｔｈｅ　ｗａｙ，↓
　　ｗｈｙ　ｄｉｄ　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｃｏｍｅ　ｂａｃｋ　ｈｅｒｅ？@KEY()↓
◆Ｙｏｕ　ｍｕｓｔ　ｈａｖｅ　ｆｏｒｇｏｔｔｅｎ　ｓｏｍｅ　ｖｅｒｙ　ｉｍｐｏｒｔａｎｔ　ｉｔｅｍ　ｏｒ　ｇａｄｇｅｔ　ｈｅｒｅ．．．@KEY()↓
◆Ｈｏｗ’ｓ　ｔｈａｔ　ｆｏｒ　ａ　ｇｕｅｓｓ？　　Ａｍ　Ｉ　ｃｌｏｓｅ？@KEY()↓
◆Ｗｅｌｌ，　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｔｏ　ｔｅｌｌ　ｍｅ．．．@KEY()↓
◆Ｓｅｅ　ｙｏｕ　ｌａｔｅｒ　ａｎｄ　ｇｏｏｄ　ｌｕｃｋ！
;jpn:◆ついたぜ！　イエイ↓
;jpn:　おれたち　たいしたことは↓
;jpn:　できなかったけど@KEY()↓
;jpn:◆おまえたちの　みかたさ。↓
;jpn:　くるしいときは　おれたちの↓
;jpn:　うたを　おもいだしてくれよ。@KEY()↓
;jpn:◆どっか　とおいそらのしたで↓
;jpn:　トンズラブラザーズが↓
;jpn:　コーラスを　つけてるとおもって。@KEY()↓
;jpn:◆‥‥ところで↓
;jpn:　どうして　このまちに↓
;jpn:　もどるひつようが　あったんだ？@KEY()↓
;jpn:◆なにか　このまちのどこかに↓
;jpn:　だいじなものを↓
;jpn:　おきわすれてきた‥‥@WI(50)どうだ？@KEY()↓
;jpn:◆おれのすいり　あたってるだろ？@KEY()↓
;jpn:◆オーケー　ブラザー！↓
;jpn:　こたえなくって　いいぜ！@KEY()↓
;jpn:◆じゃあな　グッドラック！
@KEY()
@CLOSEALL()
』

;----------------------------------
