
;PSI説明
;=======

;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;制限事項は以下のように記述してあります。(三浦兄95.03.17)
;___must be fit in 1 line___
;___must be fit in 2 line___
;___must be fit in 4 line___
;+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


; １ＰＫ（ひっさつ）α
;akm
MSG_EXPL_PSI_HISSATSU_ALFA;marcus
@GOSUB(_PSI_HISSATSU)
;akm◆Ｐｓｙｃｈｏｋｉｎｅｓｉｓ　ｗａｖｅ　ｂｙ　ｍｉｎｄ　ｃｏｎｓｅｎｔｒａｔｉｏｎ

;akm　　Ｅａｃｈ　ｅｎｅｍｙ　ｔｏｏｋ　ａｂｏｕｔ　５０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．　

　ｅａｃｈ　ｅｎｅｍｙ　ａｂｏｕｔ　５０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

;jpn:　てきぜんいんに↓
;jpn:　やく５０ポイントずつ　ダメージをあたえる。
@!

; ２ＰＫ（ひっさつ）β
;akm
MSG_EXPL_PSI_HISSATSU_BETA;marcus
@GOSUB(_PSI_HISSATSU)
;akm　Ｅａｃｈ　ｅｎｅｍｙ　ｔｏｏｋ　ａｂｏｕｔ　ａｂｏｕｔ　１８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ｅａｃｈ　ｅｎｅｍｙ　ａｂｏｕｔ　１８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

;jpn:  てきぜんいんに↓
;jpn:　やく１８０ポイントずつ　ダメージをあたえる。
@!

; ３ＰＫ（ひっさつ）γ
;akm
MSG_EXPL_PSI_HISSATSU_GAMMA;marcus
@GOSUB(_PSI_HISSATSU)
;akm　　Ｅａｃｈ　ｅｎｅｍｙ　ｔｏｏｋ　ａｂｏｕｔ　５０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ｅａｃｈ　ｅｎｅｍｙ　ａｂｏｕｔ　３２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

;jpn:　てきぜんいんに↓
;jpn:　やく３２０ポイントずつ　ダメージをあたえる。
@!

; ４ＰＫ（ひっさつ）Ω
;akm
MSG_EXPL_PSI_HISSATSU_OMEGA;marcus
@GOSUB(_PSI_HISSATSU)
;akm　　Ｅａｃｈ　ｅｎｅｍｙ　ｔｏｏｋ　ａｂｏｕｔ　６４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ｅａｃｈ　ｅｎｅｍｙ　ａｂｏｕｔ　６４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

;jpn:　てきぜんいんに↓
;jpn:　やく６４０ポイントずつ　ダメージをあたえる。
@!

; ５ＰＫファイアーα
;akm
MSG_EXPL_PSI_FIRE_ALFA;marcus 
@GOSUB(_PSI_FIRE)
;akm　　Ｅａｃｈ　ｔａｒｇｅｔ　ｔｏｏｋ　ａｂｏｕｔ　８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ａｂｏｕｔ　８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｅａｃｈ．

;jpn:　それぞれ　やく８０ポイントのダメージを　あたえる。
@!

; ６ＰＫファイアーβ
;akm
MSG_EXPL_PSI_FIRE_BETA;marcus 
@GOSUB(_PSI_FIRE)
;akm　　Ｇａｖｅ　ｅａｃｈ　ｔａｒｇｅｔ　ａｂｏｕｔ　８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ａｂｏｕｔ　１６０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｅａｃｈ．

;jpn:　それぞれ　やく１６０ポイントのダメージを　あたえる。
@!

; ７ＰＫファイアーγ
;akm
MSG_EXPL_PSI_FIRE_GAMMA;marcus
@GOSUB(_PSI_FIRE)
;akm　　Ｇａｖｅ　ｅａｃｈ　ｔａｒｇｅｔ　ａｂｏｕｔ　２４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ａｂｏｕｔ　２４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｅａｃｈ．

;jpn:　それぞれ　やく２４０ポイントのダメージを　あたえる。
@!

; ８ＰＫファイアーΩ
;akm
MSG_EXPL_PSI_FIRE_OMEGA;marcus
@GOSUB(_PSI_FIRE)
;akm　　Ｇａｖｅ　ｅａｃｈ　ｔａｒｇｅｔ　ａｂｏｕｔ　３２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．

　ａｂｏｕｔ　３２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｅａｃｈ．

;jpn:　それぞれ　やく３２０ポイントのダメージを　あたえる。
@!

; ９ＰＫフリーズα
;akm!
MSG_EXPL_PSI_FREEZ_ALFA; marcus
@GOSUB(_PSI_FREEZ)
;akm　　Ｉｎｆｌｉｃｔｅｄ　ａｂｏｕｔ　１８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

　ｉｎｆｌｉｃｔｉｎｇ　ａｂｏｕｔ　１８０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

;jpn:　やく１８０ポイントのダメージを　あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;10 ＰＫフリーズβ
;akm!
MSG_EXPL_PSI_FREEZ_BETA;marcus 
@GOSUB(_PSI_FREEZ)
;akm　　Ｉｎｆｌｉｃｔｅｄ　ａｂｏｕｔ　３６０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

　ｉｎｆｌｉｃｔｉｎｇ　ａｂｏｕｔ　３６０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

;jpn:　やく３６０ポイントのダメージを　あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;11 ＰＫフリーズγ
;akm!
MSG_EXPL_PSI_FREEZ_GAMMA;marcus
@GOSUB(_PSI_FREEZ)
;akm　　Ｉｎｆｌｉｃｔｅｄ　ａｂｏｕｔ　５４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

　ｉｎｆｌｉｃｔｉｎｇ　ａｂｏｕｔ　５４０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

;jpn:　やく５４０ポイントのダメージを　あたえる。↓
@GOSUB(_PSI_FREEZ_2)←
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!
　
;12 ＰＫフリーズΩ
;akm!
MSG_EXPL_PSI_FREEZ_OMEGA;marcus
@GOSUB(_PSI_FREEZ)
;akm　　Ｉｎｆｌｉｃｔｅｄ　ａｂｏｕｔ　７２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

　ｉｎｆｌｉｃｔｉｎｇ　ａｂｏｕｔ　７２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

;jpn:　やく７２０ポイントのダメージを　あたえる。↓
@GOSUB(_PSI_FREEZ_2)↓
@GOSUB(_PSI_NOT_EFFECTIVE_ON_SOME)
@!

;13 ＰＫサンダーα
;akm!
MSG_EXPL_PSI_THUNDER_ALFA;marcus
◆Ｔｈｅ　ｅｎｅｍｙ　ｉｓ　ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　１２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

;jpn:◆ダメージ　やく１２０ポイントの↓
;jpn:　かみなりを　おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;14 ＰＫサンダーβ
;akm!
MSG_EXPL_PSI_THUNDER_BETA;marcus
;akm◆Ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　１２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

◆Ｔｈｅ　ｅｎｅｍｙ　ｉｓ　ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　１２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｗｏ　ｓｅｐａｒａｔｅ　ｔｉｍｅｓ．↓

;jpn:◆ダメージ　やく１２０ポイントの↓
;jpn:　かみなりを　２はつ　おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;15 ＰＫサンダーγ
;akm!
MSG_EXPL_PSI_THUNDER_GAMMA;marcus
;akm◆The enemy is tｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　２００　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

◆Ｔｈｅ　ｅｎｅｍｙ　ｉｓ　ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　２００　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｈｒｅｅ　ｓｅｐａｒａｔｅ　ｔｉｍｅｓ．↓

;jpn:◆ダメージ　やく２００ポイントの↓
;jpn:　かみなりを　３ぱつ　おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;16 ＰＫサンダーΩ
;akm!
MSG_EXPL_PSI_THUNDER_OMEGA;
;akm◆Ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　２００　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ．↓

◆Ｔｈｅ　ｅｎｅｍｙ　ｉｓ　ｔｈｕｎｄｅｒ　ｓｔｒｕｃｋ　ｆｏｒ　ａｂｏｕｔ　２００　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｆｏｕｒ　ｓｅｐａｒａｔｅ　ｔｉｍｅｓ．↓

;jpn:◆ダメージ　やく２００ポイントの↓
;jpn:　かみなりを　４ぱつ　おとす。↓
@GOSUB(_PSI_THUNDER)
@!

;PKフラッシュ
;--------------------------------------------------------------
;アルファ                7/8 涙止まらず                  1/8 変
;ベータ  1/8 気絶        5/8 涙止まらず  1/8 しびれ      1/8 変
;ガンマ  2/8 気絶        4/8 涙止まらず  1/8 しびれ      1/8 変
;オメガ  3/8 気絶        3/8 涙止まらず  1/8 しびれ      1/8 変

;17 ＰＫフラッシュα
;akm!
MSG_EXPL_PSI_FLASH_ALFA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆Ｉｎ　ｃｅｒｔａｉｎ　ｃｉｒｃｕｍｓｔａｎｃｅｓ，　ｉｔ　ｍａｋｅｓ　ａｎ　ｏｂｊｅｃｔ　”ｕｎｕｓｕａｌ．”

，　ｉｎ　ｓｏｍｅ　ｃｉｒｃｕｍｓｔａｎｃｅｓ，　ｆｅｅｌ　ｓｔｒａｎｇｅ．

;jpn:◆「へん」にすることも　まれに　ある。
@!

;18 ＰＫフラッシュβ
;akm!
MSG_EXPL_PSI_FLASH_BETA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆Ｏｔｈｅｒｗｉｓｅ，　ｉｔ　ｍａｋｅｓ　ａｎ　ｏｂｊｅｃｔ　”ｕｎｕｓｕａｌ，”　”ｎｕｍｂｅｄ”　ｏｒ　ｄｅｓｔｒｏｙｓ　ｉｔ　ｗｉｔｈ　ａ　ｓｉｎｇｌｅ　ｓｔｒｉｋｅ．

，　ａｎｄ　ｉｎ　ｓｏｍｅ　ｃｉｒｃｕｍｓｔａｎｃｅｓ，　ｃａｎ　ｍａｋｅ　ｔｈｅ　ｅｎｅｍｙ　ｆｅｅｌ　ｓｔｒａｎｇｅ，　ｂｅｃｏｍｅ　ｎｕｍｂ，　ｏｒ　ｅｖｅｎ　ｂｅ　ｄｅｓｔｒｏｙｅｄ．

;jpn:◆そのほかにも　「へん」にしたり　「しびれ」させたり↓
;jpn:　いちげきで　たおすことも　ある。
@!

;19 ＰＫフラッシュγ
;akm!
MSG_EXPL_PSI_FLASH_GAMMA;marcus
@GOSUB(_PSI_FLUSH_1)
@GOSUB(_PSI_FLUSH_2)
;akm◆Ｏｆｔｅｎ，　ｉｔ　ｗｉｌｌ　ｄｅｓｔｒｏｙ　ａｎ　ｏｂｊｅｃｔ　ｗｉｔｈ　ａ　ｓｉｎｇｌｅ　ｓｔｒｉｋｅ．　

．↓
◆Ｏｆｔｅｎ，　ｉｔ　ｗｉｌｌ　ｄｅｓｔｒｏｙ　ａｎ　ｅｎｅｍｙ　ｉｎ　ａ　ｓｉｎｇｌｅ　ｓｔｒｉｋｅ．

;jpn:◆いちげきで　たおすことも　かなりある。
@!

;20 ＰＫフラッシュΩ
;akm!
MSG_EXPL_PSI_FLASH_OMEGA;marcus
◆Ｉｔ　ｇｅｎｅｒａｔｅｓ　ｇｌｏｒｉｏｕｓ　ｒａｙｓ　ｔｈａｔ　ｈａｖｅ　ａ　ｈｉｇｈ　ｐｒｏｂａｂｉｌｉｔｙ　ｏｆ　ｄｅｓｔｒｏｙｉｎｇ　ａｌｌ　ｔｈｅ　ｅｎｅｍｉｅｓ　ｏｎ　ｔｈｅ　ｓｃｅｎｅ　ｉｎ　ａ　ｓｉｎｇｌｅ　ｓｔｒｉｋｅ．

;jpn:◆はげしいひかりを　はなち↓
;jpn:　てきぜんいんを　かなりの　かくりつで↓
;jpn:　いちげきで　たおすことが　できる。
@!

;21 ＰＫスターストームα
;akm
MSG_EXPL_PSI_STARSTOM_ALFA;　marcus
@GOSUB(_PSI_STARSTORM_1)←
;akm◆It dｅａｌｓ　ａｂｏｕｔ　３６０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｏ　ｅａｃｈ　ｅｎｅｍｙ．

◆Ｉｔ　ｄｅａｌｓ　ａｂｏｕｔ　３６０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｏ　ｅａｃｈ　ｅｎｅｍｙ．

;jpn:◆てきぜんいんに↓
;jpn:　やく３６０ポイントずつ　ダメージをあたえる。
@!

;22 ＰＫスターストームΩ
;akm
MSG_EXPL_PSI_STARSTORM_OMEGA;marcus
@GOSUB(_PSI_STARSTORM_1)←
;akm◆Ｄｅａｌｓ　ａｂｏｕｔ　７２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｏ　ｅａｃｈ　ｅｎｅｍｙ．

◆Ｉｔ　ｄｅａｌｓ　ａｂｏｕｔ　７２０　ｐｏｉｎｔｓ　ｏｆ　ｄａｍａｇｅ　ｔｏ　ｅａｃｈ　ｅｎｅｍｙ．

;jpn:◆てきぜんいんに↓
;jpn:　やく７２０ポイントずつ　ダメージをあたえる。
@!

;23 ライフアップα
;akm
MSG_EXPL_PSI_LIFEUP_ALFA;
;akm◆Ｒｅｓｔｏｒｅｓ　１００　ＨＰ　ｆｏｒ　ａ　ｆｒｉｅｎｄ．

◆Ｒｅｓｔｏｒｅｓ　１００　ＨＰ　ｔｏ　ｏｎｅ　ｐｅｒｓｏｎ．

;jpn:◆なかまひとりのＨＰを↓
;jpn:　やく１００ポイント　かいふくする。
@!

;24 ライフアップβ
;akm
MSG_EXPL_PSI_LIFEUP_BETA;marcus
◆Ｒｅｓｔｏｒｅｓ　３００　ＨＰ　ｔｏ　ｏｎｅ　ｐｅｒｓｏｎ．

;jpn:◆なかまひとりのＨＰを↓
;jpn:　やく３００ポイント　かいふくする。
@!

;25 ライフアップγ
;akm
MSG_EXPL_PSI_LIFEUP_GAMMA;marcus
◆Ｃｏｍｐｌｅｔｅｌｙ　ｒｅｓｔｏｒｅｓ　ｔｈｅ　ＨＰ　ｏｆ　ｏｎｅ　ｐｅｒｓｏｎ．

;jpn:◆なかまひとりのＨＰを↓
;jpn:　かんぜんに　かいふくする。
@!

;26 ライフアップΩ
;akm
MSG_EXPL_PSI_LIFEUP_OMEGA;marcus
◆Ｒｅｓｔｏｒｅｓ　４００　ＨＰ　ｔｏ　ｅｖｅｒｙｏｎｅ．

;jpn:◆なかまぜんいんのＨＰを↓
;jpn:　やく４００ずつ　かいふくする。
@!

;27 ヒーリングα
;akm
MSG_EXPL_PSI_HEALING_ALFA;marcus
◆Ｃｕｒｅｓ　ａ　ｃｏｌｄ，　ｓｕｎｓｔｒｏｋｅ　ｏｒ　ｓｌｅｅｐ　ｃｏｎｄｉｔｉｏｎｓ．

;jpn:◆なかまの「かぜ」「にっしゃびょう」↓
;jpn:　「ねむり」じょうたいを　かいふくする。
@!

;28 ヒーリングβ
;akm
MSG_EXPL_PSI_HEALING_BETA;marcus
◆Ｉｎ　ａｄｄｉｔｉｏｎ　ｔｏ　ｔｈｅ　ｅｆｆｅｃｔｓ　ｏｆ　Ｈｅａｌｉｎｇ　α，　ｔｈｉｓ　ｃｕｒｅｓ　ｐｏｉｓｏｎｉｎｇｓ，　ｎａｕｓｅａ，　ｆｅｅｌｉｎｇ　ｓｔｒａｎｇｅ　ａｎｄ　ｕｎｃｏｎｔｒｏｌｌａｂｌｅ　ｃｒｙｉｎｇ．

;jpn:◆ヒーリングαのこうかにくわえ↓
;jpn:　「どく」「きもちわるい」「へん」↓
;jpn:　「なみだがとまらない」じょうたいを　かいふくする。
@!

;29 ヒーリングγ
;akm
MSG_EXPL_PSI_HEALING_GAMMA;marcus
◆Ｉｎ　ａｄｄｉｔｉｏｎ　ｔｏ　ｔｈｅ　ｅｆｆｅｃｔｓ　ｏｆ　Ｈｅａｌｉｎｇ　β，　ｔｈｉｓ　ｃｕｒｅｓ　ｂｅｉｎｇ　ｄｉａｍｏｎｄｉｚｅｄ　ａｎｄ　ｐａｒａｌｙｓｉｓ．↓
◆Ｉｔ　ａｌｓｏ　ｒｅｖｉｖｅｓ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　ｈａｓ　ｂｅｃｏｍｅ　ｕｎｃｏｎｓｃｉｏｕｓ，　ｔｈｏｕｇｈ　ＨＰ　ｉｓ　ｎｏｔ　ｍａｘｅｄ　ｏｕｔ．

;jpn:◆ヒーリングβのこうかにくわえ↓
;jpn:　「ダイヤ」「しびれ」じょうたいを　かいふくする。↓
;jpn:◆「きぜつ」しているなかまを　カムバックさせる↓
;jpn:　こともあるが　そのときＨＰは　まんタンに　ならない。
@!

;30 ヒーリングΩ
;akm
MSG_EXPL_PSI_HEALING_OMEGA;marcus
◆Ｉｎ　ａｄｄｉｔｉｏｎ　ｔｏ　ｔｈｅ　ｅｆｆｅｃｔｓ　ｏｆ　Ｈｅａｌｉｎｇ　γ，　ｔｈｉｓ　ｒｅｖｉｖｅｓ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　ｈａｓ　ｂｅｃｏｍｅ　ｕｎｃｏｎｓｃｉｏｕｓ，　ａｎｄ　ｉｔ　ｃｏｍｐｌｅｔｅｌｙ　ｍａｘｅｓ　ｏｕｔ　ｔｈａｔ　ｐｅｒｓｏｎ’ｓ　ＨＰ　ｗｈｅｎ　ｒｅｖｉｖｅｄ．

;jpn:◆ヒーリングγのこうかにくわえ↓
;jpn:　「きぜつ」しているなかまを　かくじつに↓
;jpn:　ＨＰまんタンで　カムバックさせる。
@!

;31 シールドα
;akm
MSG_EXPL_PSI_SHIELD_ALFA;marcus
◆Ｐｒｏｔｅｃｔ　ｏｎｅ　ｐｅｒｓｏｎ　ｗｉｔｈ　ｔｈｅ　ｓｈｉｅｌｄ　ｏｆ　ｌｉｇｈｔ．↓
◆Ｉｔ　ｒｅｄｕｃｅｓ　ｔｈｅ　ｄａｍａｇｅ　ｃａｕｓｅｄ　ｂｙ　ａｎ　ｅｎｅｍｙ’ｓ　ａｔｔａｃｋ　ｂｙ　５０％．↓
;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．↓

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．
 
;jpn:◆なかまひとりに「ひかりのシールド」をかける。↓
;jpn:◆てきからうける　だげきこうげきのダメージが↓
;jpn:　はんぶんになる。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆なかまひとりに「シールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE)
;@!

;33 シールドΣ
;akm
MSG_EXPL_PSI_SHIELD_SIGMA;marcus
◆Ｐｒｏｔｅｃｔ　ｅｖｅｒｙｏｎｅ　ｗｉｔｈ　ｔｈｅ　ｓｈｉｅｌｄ　ｏｆ　ｌｉｇｈｔ．↓
◆Ｉｔ　ｒｅｄｕｃｅｓ　ｔｈｅ　ｄａｍａｇｅ　ｃａｕｓｅｄ　ｂｙ　ａｎ　ｅｎｅｍｙ’ｓ　ａｔｔａｃｋ　ｂｙ　５０％．↓
;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．


;jpn:◆みかたぜんいんに「ひかりのシールド」をかける。↓
;jpn:◆てきからうける　だげきこうげきのダメージが↓
;jpn:　はんぶんになる。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたぜんいんに「シールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE)
;@!

;32 シールドβ
;akm
MSG_EXPL_PSI_SHIELD_BETA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｏｎｅ　ｐｅｒｓｏｎ　ｗｉｔｈ　ａ　ｐｏｗｅｒ　ｓｈｉｅｌｄ．↓

◆Ｃｕｔｓ　ｄａｍａｇｅ　ｉｎ　ｈａｌｆ　ａｎｄ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｂｌｏｃｋｅｄ　ｄａｍａｇｅ　ｉｓ　ｄｅａｌｔ　ｂａｃｋ　ｔｏ　ｔｈｅ　ｅｎｅｍｙ．↓

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．

;jpn:◆なかまひとりに「はんげきのシールド」をかける。↓
;jpn:◆だげきこうげきのダメージが↓
;jpn:　はんぶんになり　のこりを　はねかえす。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆なかまひとりに「パワーシールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE_REPEL)
;@!

;34 シールドΩ
;akm
MSG_EXPL_PSI_SHIELD_OMEGA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｅｖｅｒｙｏｎｅ　ｗｉｔｈ　ａ　ｐｏｗｅｒ　ｓｈｉｅｌｄ．↓

;akm◆Ｉｔ　ｒｅｄｕｃｅｓ　ｔｈｅ　ｄａｍａｇｅ　ｃａｕｓｅｄ　ｂｙ　ｔｈｅ　ｅｎｅｍｙ’ｓ　ａｔｔａｃｋ　ｂｙ　５０％　ａｎｄ　ｒｅｔｕｒｎｓ　ｔｈｅ　ｒｅｓｔ　ｔｏ　ａｔｔａｃｋｅｒ．↓

◆Ｃｕｔｓ　ｄａｍａｇｅ　ｉｎ　ｈａｌｆ　ａｎｄ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｂｌｏｃｋｅｄ　ｄａｍａｇｅ　ｉｓ　ｄｅａｌｔ　ｂａｃｋ　ｔｏ　ｔｈｅ　ｅｎｅｍｙ．↓

;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．


;jpn:◆みかたぜんいんに「はんげきのシールド」をかける。↓
;jpn:◆だげきこうげきのダメージが↓
;jpn:　はんぶんになり　のこりを　はねかえす。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたぜんいんに「パワーシールド」をかける。↓
;@GOSUB(_PSI_SHIELD_HALVE_REPEL)
;@!

;35 サイコシールドα
;akm
MSG_EXPL_PSI_P_SHIELD_ALFA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｏｎｅ　ｐｅｒｓｏｎ　ｗｉｔｈ　ａ　ｐｓｙｃｈｉｃ　ｓｈｉｅｌｄ．↓
◆Ｉｔ　ｂｌｏｃｋｓ　ａｎ　ｅｎｅｍｙ’ｓ　ＰＳＩ　ａｔｔａｃｋ．↓

;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．

;jpn:◆みかたひとりに「サイコシールド」をかける。↓
;jpn:◆てきからうける　ＰＳＩこうげきを↓
;jpn:　むこうにする。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたひとりに「サイコシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_HALVE)
;@!

;36 サイコシールドΣ
;akm
MSG_EXPL_PSI_P_SHIELD_SIGMA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｅｖｅｒｙｏｎｅ　ｗｉｔｈ　ａ　ｐｓｙｃｈｉｃ　ｓｈｉｅｌｄ．↓

◆Ｉｔ　ｂｌｏｃｋｓ　ａｎ　ｅｎｅｍｙ’ｓ　ＰＳＩ　ａｔｔａｃｋ．↓

;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．

;jpn:◆みかたぜんいんに「サイコシールド」をかける。↓
;jpn:◆てきからうける　ＰＳＩこうげきを↓
;jpn:　むこうにする。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたぜんいんに「サイコシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_HALVE)
;@!

;37 サイコシールドβ
;akm
MSG_EXPL_PSI_P_SHIELD_BETA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｏｎｅ　ｐｅｒｓｏｎ　ｗｉｔｈ　ａ　ｐｓｙｃｈｉｃ　ｐｏｗｅｒ　ｓｈｉｅｌｄ．↓
◆Ｉｔ　ｒｅｆｌｅｃｔｓ　ａｎ　ｅｎｅｍｙ’ｓ　ＰＳＩ　ａｔｔａｃｋ　ｂａｃｋ　ａｔ　ｔｈｅ　ａｔｔａｃｋｅｒ．↓
◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．

;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

;jpn:◆みかたひとりに「はんげきのサイコシールド」をかける。↓
;jpn:◆てきからうける　ＰＳＩこうげきを↓
;jpn:　そのままはねかえす。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたひとりに「サイパワーシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_REPEL)
;@!

;38 サイコシールドΩ
;akm
MSG_EXPL_PSI_P_SHIELD_OMEGA;marcus
◆Ｐｒｏｔｅｃｔｓ　ｅｖｅｒｙｏｎｅ　ｗｉｔｈ　ａ　ｐｓｙｃｈｉｃ　ｐｏｗｅｒ　ｓｈｉｅｌｄ．↓
◆Ｉｔ　ｒｅｆｌｅｃｔｓ　ａｎ　ｅｎｅｍｙ’ｓ　ＰＳＩ　ａｔｔａｃｋ　ｂａｃｋ　ａｔ　ｔｈｅ　ａｔｔａｃｋｅｒ．↓
◆Ｕｓｉｎｇ　ａ　ｄｉｆｆｅｒｅｎｔ　ｓｈｉｅｌｄ　ｗｉｌｌ　ｃａｎｃｅｌ　ｔｈｅｓｅ　ｅｆｆｅｃｔｓ．


;akm◆Ｈｏｗｅｖｅｒ，　ｔｈｅ　ｅｆｆｅｃｔ　ｗｉｌｌ　ｂｅ　ｌｏｓｔ　ｉｆ　ａｎｏｔｈｅｒ　ｓｈｉｅｌｄ　ｉｓ　ｐｕｔ　ｏｎ　ｏｖｅｒ　ｉｔ．

;jpn:◆みかたぜんいんに「はんげきのサイコシールド」をかける。↓
;jpn:◆てきからうける　ＰＳＩこうげきを↓
;jpn:　そのままはねかえす。↓
;jpn:◆べつのシールドをかけると　うちけされてしまう。
@!
;◆みかたぜんいんに「サイパワーシールド」をかける。↓
;@GOSUB(_PSI_PSI_SHIELD_REPEL)
;@!

;39 オフェンスアップα
;akm
MSG_EXPL_PSI_OFFENSE_UP_ALFA;marcus
◆Ｉｎｃｒｅａｓｅ　ｏｎｅ　ｐｅｒｓｏｎ’ｓ　Ｏｆｆｅｎｓｅ　ｆｏｒ　ｔｈｅ　ｄｕｒａｔｉｏｎ　ｏｆ　ｔｈｅ　ｃｕｒｒｅｎｔ　ｂａｔｔｌｅ．↓

;jpn:◆みかたひとりの　こうげきりょくを↓
;jpn:　せんとうじにかぎって　アップする。↓
@GOSUB(_PSI_USE_PILE)
@!

;40 オフェンスアップΩ
;akm
MSG_EXPL_PSI_OFFENSE_UP_OMEGA;marcus
◆Ｉｎｃｒｅａｓｅ　ｅｖｅｒｙｏｎｅ’ｓ　Ｏｆｆｅｎｓｅ　ｆｏｒ　ｔｈｅ　ｄｕｒａｔｉｏｎ　ｏｆ　ｔｈｅ　ｃｕｒｒｅｎｔ　ｂａｔｔｌｅ．↓

;jpn:◆みかたぜんいんの　こうげきりょくを↓
;jpn:　せんとうじにかぎって　アップする。↓
@GOSUB(_PSI_USE_PILE)
@!

;41 ディフェンスダウンα
;akm
MSG_EXPL_PSI_DEFENSE_DOWN_ALFA;marcus
◆Ｄｅｃｒｅａｓｅｓ　ｔｈｅ　Ｄｅｆｅｎｓｅ　ｏｆ　ｏｎｅ　ｅｎｅｍｙ　ｆｏｒ　ｔｈｅ　ｄｕｒａｔｉｏｎ　ｏｆ　ｔｈｅ　ｃｕｒｒｅｎｔ　ｂａｔｔｌｅ．↓

;jpn:◆てきひとりの　しゅびりょくを↓
;jpn:　せんとうじにかぎって　ダウンさせる。↓
@GOSUB(_PSI_USE_PILE)
@!

;42 ディフェンスダウンΩ
;akm
MSG_EXPL_PSI_DEFENSE_DOWN_OMEGA;
◆Ｄｅｃｒｅａｓｅｓ　ｔｈｅ　Ｄｅｆｅｎｓｅ　ｏｆ　ａｌｌ　ｅｎｅｍｉｅｓ　ｆｏｒ　ｔｈｅ　ｄｕｒａｔｉｏｎ　ｏｆ　ｔｈｅ　ｃｕｒｒｅｎｔ　ｂａｔｔｌｅ．↓

;jpn:◆てきぜんいんの　しゅびりょくを↓
;jpn:　せんとうじにかぎって　ダウンさせる。↓
@GOSUB(_PSI_USE_PILE)
@!

;43 さいみんじゅつα
;akm
MSG_EXPL_PSI_SAIMIN_ALFA;marcus
◆Ｐｕｔｓ　ｏｎｅ　ｅｎｅｍｙ　ｔｏ　ｓｌｅｅｐ．↓
 
;jpn:◆てきひとりを　ねむらせる。↓
@GOSUB(_PSI_SAIMIN_SUPPLEMENT)
@!

;44 さいみんじゅつΩ
;akm
MSG_EXPL_PSI_SAIMIN_OMEGA;
◆Ｐｕｔｓ　ａｌｌ　ｏｆ　ｔｈｅ　ｅｎｅｍｉｅｓ　ｔｏ　ｓｌｅｅｐ．↓

;jpn:◆てきぜんいんを　ねむらせる。↓
@GOSUB(_PSI_SAIMIN_SUPPLEMENT)
@!

;45 サイマグネットα
;akm
MSG_EXPL_PSI_P_MAGNET_ALFA;marcus
;akm◆Ｏｎｅ　ｏｆ　ｔｈｅ　ｅｎｅｍｙ’ｓ　ＰＰ

◆Ｇｒａｂｓ　２－８　ｐｏｉｎｔｓ　ｏｆ　ＰＰ　ｆｒｏｍ　ｏｎｅ　ｅｎｅｍｙ　ａｎｄ　ａｄｄｓ　ｉｔ　ｔｏ　ｙｏｕｒ　ｏｗｎ．

;jpn:◆てきひとりの　ＰＰを↓
;akm@GOSUB(_PSI_PSI_MAGNET_BASIC)
@!

;46 サイマグネットΩ
;akm
MSG_EXPL_PSI_P_MAGNET_OMEGA;marcus
;akm◆Ｅａｃｈ　ｅｎｅｍｙ’ｓ　ＰＰ　

◆Ｇｒａｂｓ　２－８　ｐｏｉｎｔｓ　ｏｆ　ＰＰ　ｆｒｏｍ　ｅａｃｈ　ｅｎｅｍｙ　ａｎｄ　ａｄｄｓ　ｉｔ　ｔｏ　ｙｏｕｒ　ｏｗｎ．

;jpn:◆てきぜんいんの　ＰＰを↓
;jpn:　それぞれ@GOSUB(_PSI_PSI_MAGNET_BASIC)
@!

;47 パラライシスα
;akm
MSG_EXPL_PSI_PARALYSIS_ALFA;marcus
◆Ｆｏｒｃｅｓ　ｏｎｅ　ｅｎｅｍｙ　ｉｎｔｏ
;jpn:◆てきひとりを↓
@GOSUB(_PSI_PARALYSIS_BASIC)
@!

;48 パラライシスΩ
;akm
MSG_EXPL_PSI_PARALYSIS_OMEGA;marcus
◆Ｆｏｒｃｅｓ　ａｌｌ　ｅｎｅｍｉｅｓ　ｉｎｔｏ
;jpn:◆てきぜんいんを↓
@GOSUB(_PSI_PARALYSIS_BASIC)
@!

;49 ブレインショックα
;akm
MSG_EXPL_PSI_BRAIN_SHOCK_ALFA;marcus
◆Ｍａｋｅｓ　ｏｎｅ　ｅｎｅｍｙ　ｆｅｅｌｓ　ｓｔｒａｎｇｅ．

;jpn:◆てきひとりを
;@GOSUB(_PSI_BRAIN_SHOCK_BASIC)
@!

;50 ブレインショックΩ
;akm
MSG_EXPL_PSI_BRAIN_SHOCK_OMEGA;marcus
◆Ｍａｋｅｓ　ａｌｌ　ｏｆ　ｔｈｅ　ｅｎｅｍｉｅｓ　ｆｅｅｌ　ｓｔｒａｎｇｅ．

;jpn:◆てきぜんいんを
;@GOSUB(_PSI_BRAIN_SHOCK_BASIC)
@!

;51 テレポートα
;akm
MSG_EXPL_PSI_TELEPORT_ALFA;marcus
@GOSUB(_PSI_TELEPORT_BASIC)←
◆Ｙｏｕ　ｎｅｅｄ　ａ　ｇｏｏｄ　ｒｕｎｎｉｎｇ　ａｐｐｒｏａｃｈ　ｆｏｒ　ｔｈｉｓ　ｔｏ　ｗｏｒｋ．

;jpn:◆ながいじょそうが　ひつようだ。
@!

;52 テレポートβ
;akm
MSG_EXPL_PSI_TELEPORT_BETA;
@GOSUB(_PSI_TELEPORT_BASIC)←
◆Ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ　ａ　ｒｕｎｎｉｎｇ　ａｐｐｒｏａｃｈ　ｔｏ　ｕｓｅ　ｔｈｉｓ．↓
◆Ｉｔ　ｉｓ　ａｌｓｏ　ｃａｌｌｅｄ　ｔｈｅ　”Ｔｏｒｎａｄｏ　Ｔｅｌｅｐｏｒｔ．”

;jpn:◆ながいじょそうは　いらない。↓
;jpn:◆「たつまきテレポート」ともいう。
@!


