;--------------------------------------------
;
;複数のファイルにまたがって使用されるものなど
;@GOSUBコマンドによって起動される。
;
;--------------------------------------------
MSG_GLOBAL_TELEPHONE_SUMS;
@SET_LOOPREG(TLPT_SUMMERS)
@GOSUB(MSG_GLOBAL_TELEPHONE)
@!

MSG_GLOBAL_TELEPHONE_SUMS_MUSEUM;
@SET_LOOPREG(TLPT_SUMMERS)
;-----
;ライスボウルから電話
@CHKFGOTO(FLG_SUMS_MUSEUM_PHONE_RING,MSG_SUMS_PHONE_RICEBOWL)
;-----
@GOTO(MSG_GLOBAL_TELEPHONE)
@!

MSG_GLOBAL_TELEPHONE_ONET;
MSG_GLOBAL_TELEPHONE_TWSN;
MSG_GLOBAL_TELEPHONE_THRK;
MSG_GLOBAL_TELEPHONE_DOSEI;
MSG_GLOBAL_TELEPHONE_FOUR;
MSG_GLOBAL_TELEPHONE_SKRB;
MSG_GLOBAL_TELEPHONE_RAMA;
MSG_GLOBAL_TELEPHONE_MAKYO;
MSG_GLOBAL_TELEPHONE_GUMI;
MSG_GLOBAL_TELEPHONE_DKFD;
MSG_GLOBAL_TELEPHONE;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0)　ｐｉｃｋｅｄ　ｕｐ　ｔｈｅ　ｒｅｃｅｉｖｅｒ．
;◆@DSP_NAME(0)は　じゅわきをとった。
@KEY()↓
@SE(SE_se0b_tel_put)
@GOSUB(MSG_TEL)
』

MSG_GLOBAL_TELEPHONE_ONET_2;
MSG_GLOBAL_TELEPHONE_TWSN_2;
MSG_GLOBAL_TELEPHONE_TWSN_3;
MSG_GLOBAL_TELEPHONE_THRK_2;
MSG_GLOBAL_TELEPHONE_WINS_2;
MSG_GLOBAL_TELEPHONE_FOUR_2;
MSG_GLOBAL_TELEPHONE_SUMS_2;
MSG_GLOBAL_TELEPHONE_SKRB_2;
MSG_GLOBAL_TELEPHONE_2;
@WINR_MONEY()
@Q_MONEY(1)
@TRUE_GOTO(_TEL_2_NOMONEY)
@GET_ORDER_PLAYER(1)
@XCHG()
◆@DSP_NAME(0)　ｐｉｃｋｅｄ　ｕｐ　ｔｈｅ　ｒｅｃｅｉｖｅｒ．
;jpn:◆@DSP_NAME(0)は　じゅわきをとった。
@KEY()↓
@MONEYOUT(1)
@WINR_MONEY()
@SE(SE_se0b_tel_put)
@GOSUB(MSG_TEL_2)
』
_TEL_2_NOMONEY;
◆（Ｔｈｅ　ｐａｙ　ｐｈｏｎｅ　ｃｏｓｔｓ　ｏｎｅ　ｄｏｌｌａｒ．）
;◆（こうしゅうでんわは↓
;　りょうきん　１ドルです）
@KEYNP()
@!

MSG_GLOBAL_TELEPHONE_WINS;
@CHKFGOTO(FLG_JEFF,_TEL_WINS_2)
@GOSUB(MSG_TEL_GAUS)
@!
_TEL_WINS_2;
@SET_LOOPREG(TLPT_WINTERS)
@GOSUB(MSG_GLOBAL_TELEPHONE)
@!

MSG_GLOBAL_TEL;
MSG_GLOBAL_CASHDISPENSER;
@Q_HAVE(PC_ALL,GDS_TOOL_CASHCARD)
@TRUE_GOTO(MSG_CD)
◆Ｐｌｅａｓｅ　ｉｎｓｅｒｔ　ｙｏｕｒ　ＡＴＭ　ｃａｒｄ．
;◆キャッシュカード　ヲ↓
;　イレテクダサイ
@KEYNP()
』

MSG_GLOBAL_CD_RECEIVE;
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_CASHCARD)
@TRUE_GOTO(_GLOBAL_CD_RECEIVE_GOODS)
◆Ｎｏｔｈｉｎｇ　ｈａｐｐｅｎｅｄ．
;◆なにも　おこらない。
@KEYNP()
』
_GLOBAL_CD_RECEIVE_GOODS
@GOSUB(MSG_CD)
』

MSG_GLOBAL_HOTEL;
;MSG_GLOBAL_MYHOME;
;@SETF(FLG_TEMP_8)
;@GOSUB(MSG_SUB_HOTEL_LIFEUP)
;』


MSG_GLOBAL_HOSPITAL;
@GOSUB(MSG_DOCTOR_ONET)
』

MSG_GLOBAL_COMEBACK;
@GOSUB(MSG_NURSE_ONET)
』

;----------------------

MSG_EVENT_ONET_SWITCH_DAYBREAK;
←
;◆（ここで　オネットに↓
;　あさが　くる。）@KEYNP()
』

MSG_EVENT_STAGE_TONZURA;@MiuraAppended
←
;◆（トンズラの　すばらしい↓
;　さいごの　ステージのシーン。）@KEYNP()
;@ANIM(ANIM_FOUR_TONZURA_FINALGIG)
』

;---------------------------------
MSG_ADD_DOG;
@CLOSEALL()
@CHKFGOTO(FLG_DOG_LATER_APPEAR,_ADD_DOG_LATER)

@HIDE_CHAR(PRSN_ONET_NES_1F_C,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_MYDOG,ANIM_ADDPARTY,OBJFX_SHOW_NONE)
@ADD_PARTY(PC_MYHOMEDOG)
@HIDE_PLAYER(PC_MYHOMEDOG,OBJFX_HIDE_NONE)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_MYDOG,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_MYHOMEDOG,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_home2)
@OPEN(1)
◆@DSP_STS(STS_PARTY_DOG_NAME)　ｊｏｉｎｓ　ｙｏｕ．
;◆（@DSP_STS(STS_PARTY_DOG_NAME)が↓
;　なかまになった）
@KEY()
@CLOSEALL()
@SETF(FLG_DOG)
』

_ADD_DOG_LATER;
@HIDE_CHAR(PRSN_ONET_NES_1F_E,OBJFX_HIDE_NONE)
@MOVE_GOM_CHAR(GOM_MYDOG,ANIM_ADDPARTY,OBJFX_SHOW_NONE)
@ADD_PARTY(PC_MYHOMEDOG)
@HIDE_PLAYER(PC_MYHOMEDOG,OBJFX_HIDE_NONE)
@WAITSYS()
@HIDE_GOM_CHAR(GOM_MYDOG,OBJFX_HIDE_NONE)
@SHOW_PLAYER(PC_MYHOMEDOG,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_home2)
@OPEN(1)
◆@DSP_STS(STS_PARTY_DOG_NAME)　ｊｏｉｎｓ　ｙｏｕ．
;◆（@DSP_STS(STS_PARTY_DOG_NAME)が↓
;　なかまになった）
@KEY()
@CLOSEALL()
』


MSG_ADD_POKEY;
@CLOSEALL()
@ADD_PARTY(PC_POKEY)
@HIDE_PLAYER(PC_POKEY,OBJFX_HIDE_NONE)
@CHKFGOTO(FLG_MYHOME_POKEY_APPEAR,_ADD_POKEY_D)

@REMOVE_CHAR(PRSN_ONET_NES_1F_F,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_ONET_NES_1F_F,OBJFX_HIDE_NONE);座りポーキーを消す
@SHOW_PLAYER(PC_POKEY,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_home2)
@OPEN(1)
◆（Ｐｏｋｅｙ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（ポーキーが　なかまになった）
@KEY()
@CLOSEALL()
』
_ADD_POKEY_D;
@REMOVE_CHAR(PRSN_ONET_NES_1F_D,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_ONET_NES_1F_D,OBJFX_HIDE_NONE);ドアを塞ぐポーキーを消す
@SHOW_PLAYER(PC_POKEY,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_home2)
@OPEN(1)
◆（Ｐｏｋｅｙ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（ポーキーが　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_REMOVE_POKEY;
←
@DEL_PARTY(PC_POKEY)
;◆（@DSP_LCNAME()は↓
;　ポーキーと　わかれた。）@KEY()
』

MSG_REMOVE_PICKEY;
←
@DEL_PARTY(PC_PICKEY)
;◆（@DSP_LCNAME()は↓
;　ピッキーと　わかれた。）@KEY()
』

MSG_ADD_PICKEY;
@CLOSEALL()
@ADD_PARTY(PC_PICKEY)
@HIDE_PLAYER(PC_PICKEY,OBJFX_HIDE_NONE)
@REMOVE_GOM_CHAR( GOM_PICKEY, ANIM_ADDPARTY_VIA_LEADER )
@WAITSYS()
@HIDE_GOM_CHAR(GOM_PICKEY,OBJFX_HIDE_NONE);隕石落下跡のピッキーを消す
@SHOW_PLAYER(PC_PICKEY,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_house4)
@OPEN(1)
◆（Ｐｉｃｋｅｙ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（ピッキーが　なかまになった）
@KEY()
@CLOSEALL()
』

;MSG_ADD_PAULA;
;←
;◆（ポーラが　なかまになった）@KEY()
;@BGMSTART(0,BGM_friend)
;@WI(1)
;@BGMSTART(0,BGM_child)
;@REMOVE_CHAR(PRSN_GRFD_CABIN_WATCH_A,ANIM_ADDPARTY)
;@WAITSYS()
;@HIDE_CHAR(PRSN_GRFD_CABIN_WATCH_A,OBJFX_HIDE_NONE);牢屋のポーラを消す
;@ADD_PARTY(PC_PAULA)
;』

MSG_ADD_MONKEY;
;@ADD_PARTY(PC_BALLOONMONKEY)
;@HIDE_PLAYER(PC_BALLOONMONKEY,OBJFX_HIDE_NONE)
;@REMOVE_CHAR(PRSN_WINS_DRUGSTORE_D,ANIM_ADDPARTY_BMONKEY)
;@WAITSYS()
;@HIDE_CHAR(PRSN_WINS_DRUGSTORE_D,OBJFX_HIDE_NONE);配置バルーンモンキーを消す
;@SHOW_PLAYER(PC_BALLOONMONKEY,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_shop)
@OPEN(1)
◆（Ｔｈｅ　Ｂｕｂｂｌｅ　Ｍｏｎｋｅｙ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（バルーンモンキーが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_ADD_PAULA_FOUR;
@CHKFGOTO(FLG_TEMP_9,_ADD_PAULA_FOUR_MAIN)
;ポーラのセリフ
@OPEN(1)
@GOSUB(MSG_FOUR_POLA)
@CLOSEALL()
;
_ADD_PAULA_FOUR_MAIN;
@ADD_PARTY(PC_PAULA)
@HIDE_PLAYER(PC_PAULA,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_FRSD_BUIL_48F_MONO_B,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_FRSD_BUIL_48F_MONO_B,OBJFX_HIDE_NONE);囚われのポーラを消す
@SHOW_PLAYER(PC_PAULA,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_friend)
@WI(120)
@WI(120)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_child)
@OPEN(1)
◆（@DSP_NAME(PC_PAULA)　ｊｏｉｎｓ　ｙｏｕ．）
;◆（@DSP_NAME(PC_PAULA)が　なかまになった）
@KEY()
@CLOSEALL()
』

;MSG_ADD_JEFF;
;←
;◆（ジェフが　なかまになった）@KEY()
;@ADD_PARTY(PC_JEFF)
;』

;MSG_ADD_POO;
;←
;◆（プーが　なかまになった）@KEY()
;@ADD_PARTY(PC_POO)
;』

MSG_ADD_FLYINGMAN1;
@CLOSEALL()
@ADD_PARTY(PC_FLYINGMAN1)
@HIDE_PLAYER(PC_FLYINGMAN1,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_MGCT_FLINGMAN_A,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_MGCT_FLINGMAN_A,OBJFX_HIDE_NONE);配置フライングマンを消す
@SHOW_PLAYER(PC_FLYINGMAN1,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_flyman)
@OPEN(1)
◆（Ｔｈｅ　Ｆｌｙｉｎｇ　Ｍａｎ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（フライングマンが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_ADD_FLYINGMAN2;
@CLOSEALL()
@ADD_PARTY(PC_FLYINGMAN2)
@HIDE_PLAYER(PC_FLYINGMAN2,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_MGCT_FLINGMAN_B,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_MGCT_FLINGMAN_B,OBJFX_HIDE_NONE);配置フライングマンを消す
@SHOW_PLAYER(PC_FLYINGMAN2,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_flyman)
@OPEN(1)
◆（Ｔｈｅ　Ｆｌｙｉｎｇ　Ｍａｎ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（フライングマンが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_ADD_FLYINGMAN3;
@CLOSEALL()
@ADD_PARTY(PC_FLYINGMAN3)
@HIDE_PLAYER(PC_FLYINGMAN3,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_MGCT_FLINGMAN_C,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_MGCT_FLINGMAN_C,OBJFX_HIDE_NONE);配置フライングマンを消す
@SHOW_PLAYER(PC_FLYINGMAN3,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_flyman)
@OPEN(1)
◆（Ｔｈｅ　Ｆｌｙｉｎｇ　Ｍａｎ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（フライングマンが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_ADD_FLYINGMAN4;
@CLOSEALL()
@ADD_PARTY(PC_FLYINGMAN4)
@HIDE_PLAYER(PC_FLYINGMAN4,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_MGCT_FLINGMAN_D,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_MGCT_FLINGMAN_D,OBJFX_HIDE_NONE);配置フライングマンを消す
@SHOW_PLAYER(PC_FLYINGMAN4,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_flyman)
@OPEN(1)
◆（Ｔｈｅ　Ｆｌｙｉｎｇ　Ｍａｎ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（フライングマンが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_ADD_FLYINGMAN5;
@CLOSEALL()
@ADD_PARTY(PC_FLYINGMAN5)
@HIDE_PLAYER(PC_FLYINGMAN5,OBJFX_HIDE_NONE)
@REMOVE_CHAR(PRSN_MGCT_FLINGMAN_E,ANIM_ADDPARTY)
@WAITSYS()
@HIDE_CHAR(PRSN_MGCT_FLINGMAN_E,OBJFX_HIDE_NONE);配置フライングマンを消す
@SHOW_PLAYER(PC_FLYINGMAN5,OBJFX_SHOW_NONE)
@BGMSTART(0,BGM_nakama)
@WI(120)
@WI(60)
@MUSISTART()
;@BGMSTART(0,BGM_flyman)
@OPEN(1)
◆（Ｔｈｅ　Ｆｌｙｉｎｇ　Ｍａｎ　ｊｏｉｎｓ　ｙｏｕ．）
;◆（フライングマンが↓
;　なかまになった）
@KEY()
@CLOSEALL()
』

MSG_REMOVE_DOG;
;◆（@DSP_LCNAME()は↓
;　@DSP_STS(STS_PARTY_DOG_NAME)と　わかれた。）@KEY()
@DEL_PARTY(PC_MYHOMEDOG)
』

MSG_REMOVE_TONY;
←
@DEL_PARTY(PC_TONY)
;◆（@DSP_LCNAME()は↓
;　トニーと　わかれた。）@KEY()
』

;MSG_REMOVE_MONKEY;
;←
;@DEL_PARTY(PC_BALLOONMONKEY)
;◆（@DSP_LCNAME()は↓
;　バルーンモンキーと　わかれた。）@KEY()
;』

;---------------------------------

MSG_BATTLE_LOSE;戦闘に負けた後、終了する為のメッセージ
』

MSG_BATTLE_SHARK_A;
←
;◆（シャークだんＡとの↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_SKATER)
』

MSG_BATTLE_SHARK_B;
←
;◆（シャークだんＢとの↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HOPPER)
』

MSG_BATTLE_SHARK_C;
←
;◆（シャークだんＣとの↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HOPPER)
』

MSG_BATTLE_SHARK_D;
←
;◆（シャークだんＤとの↓
;　たたかい！）@KEY()↓
;◆（ＹＯＵ　ＷＩＮ！）@KEY()↓
@CLOSEALL()
@BATTLE(MSET_FIX_HULAHOOPER)
』

MSG_BATTLE_FRANK;
←
;◆（シャークだんの　リーダー↓
;　フランク・フライとの↓
;　たたかい！）@KEY()↓
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_FRANK)
』

MSG_BATTLE_STEIN2;
←
;◆（フランキースタイン２との↓
;　たたかい！）@KEY()↓
@CLOSEALL()
@BATTLE(MSET_FIX_FRANKEE2)
』

MSG_BATTLE_GIAN_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_GIANT_STEP)
@!

MSG_BATTLE_LLPT_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_LILLIPUT_STEP)
@!

MSG_BATTLE_RAIN_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_RAINY_CIRCLE)
@!

MSG_BATTLE_MLKY_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MILKY_WELL)
@!

MSG_BATTLE_MGNT_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MAGNET_HILL)
@!

MSG_BATTLE_PINK_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_PINK_CLOUD)
@!

MSG_BATTLE_LUMI_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_LUMINE_HALL)
@!

MSG_BATTLE_FIRE_BOSS;
@CLOSEALL()
@BATTLE(MSET_FIX_FIRE_SPRING)
@!

MSG_BATTLE_5COPS_A;
@CLOSEALL()
@BATTLE(MSET_FIX_COP)
@!

MSG_BATTLE_5COPS_B;
@CLOSEALL()
@BATTLE(MSET_FIX_COP)
@!

MSG_BATTLE_5COPS_C;
@CLOSEALL()
@BATTLE(MSET_FIX_COP)
@!

MSG_BATTLE_5COPS_D;
@CLOSEALL()
@BATTLE(MSET_FIX_COP)
@!

MSG_BATTLE_5COPS_E;
@CLOSEALL()
@BATTLE(MSET_FIX_COP)
@!

MSG_BATTLE_5COPS_STRONG;
←
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_STRONG)
@!

MSG_BATTLE_TONCHIKI;
←
;◆（ヌスットひろばの　ヌシ↓
;　トンチキさんとの↓
;　たたかい！）@KEY()↓
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_TONCHIKI)
@!
』

MSG_BATTLE_YOWAOTOKO;
←
;◆（ツーソンいち↓
;　よわいおとこ　との↓
;　たたかい！）@KEY()↓
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_KANSHIIN)		;監視員
;@BATTLE(MSET_FIX_WEAKEST_MAN)
』

MSG_BATTLE_CARPAINTER;
←
;◆（カーぺインターとの↓
;　たたかい！）@KEY()↓
@Q_HAVE(PC_ALL,GDS_HAVE_FRANKLIN_BADGE)
@TRUE_GOTO(_BATTLE_CARPAINTER_HAVE)
;◆（フランクリンバッジを↓
;　もっていないので↓
;　へやのそとに　とばされる。）@KEY()
@CLOSEALL()
@WI(1)
@BGMSTART(0,BGM_msc6)
;稲妻ＢＧ３アニメ(１２０フレーム弱）
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_CARPAINTER_THUNDER, OBJFX_SHOW_NONE )
@WI( 80 )
@HIDE_PLAYER( PC_ALL, OBJFX_HIDE_NONE )	;←OBJFXを使わないこと！！
@WI( 70 )
@WARP( WARP_HAPY_USHI )	;ＨＨ村の牛の元にワープ
@SHOW_PLAYER( PC_ALL, OBJFX_SHOW_BLINK )
;@MUSISTART()
;@BGMSTART(0,BGM_hapy)
@SETF(FLG_TEMP_9)	;牛の「◆逆らいなすっただね？」用
』

_BATTLE_CARPAINTER_HAVE;
;フランクリンバッジを持っているので、稲妻を跳ね返す！
@CLOSEALL()
@WI(1)
@BGMSTART(0,BGM_msc6)
;稲妻落ちて跳ね返すＢＧ３アニメ
@MOVE_GOM_CHAR( GOM_HIT_CHR, ANIM_CARPAINTER_THUNDERHEAD, OBJFX_SHOW_NONE )
@WAITSYS()
@BGM_EFFECT( 2 )
@WAITSYS()
@OPEN(1)
@Q_HAVE(PC_PAULA,GDS_HAVE_FRANKLIN_BADGE)
@TRUE_GOTO(_CARPAINTER_HAVE_PAULA)
◆@DSP_STS(STS_PC_NAME_NES)’ｓ↓
;◆@DSP_STS(STS_PC_NAME_NES)のもっている↓
@GOTO(_CARPAINTER_HAVE_MAIN)

_CARPAINTER_HAVE_PAULA;松（つなげかたわかりません）
◆@DSP_STS(STS_PC_NAME_PAULA)’ｓ↓
;◆@DSP_STS(STS_PC_NAME_PAULA)のもっている↓

_CARPAINTER_HAVE_MAIN;
◆Ｃａｒｐａｉｎｔｅｒ’ｓ　ｌｉｇｈｔｎｉｎｇ　ｗａｓ　ｒｅｆｌｅｃｔｅｄ　ｂｙ　ｔｈｅ　Ｆｒａｎｋｌｉｎ　Ｂａｄｇｅ．
;　フランクリンバッジが@KEY()↓
;◆カーペインターの　カミナリを↓
;　そのまま　はねかえした！
@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_CARPAINTER)
』

MSG_BATTLE_BELIEVER_1;
←
;◆（ハッピーハッピーきょう↓
;　しんじゃ１　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_BELIEVER_2;
←
;◆（ハッピーハッピーきょう↓
;　しんじゃ２　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_BELIEVER_3;
←
;◆（ハッピーハッピーきょう↓
;　しんじゃ３　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_BELIEVER_4;
←
;◆（ハッピーハッピーきょう↓
;　しんじゃ４　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_BELIEVER_W1;
←
;◆（ハッピーハッピーきょう↓
;　うろつきしんじゃ１　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_BELIEVER_W2;
←
;◆（ハッピーハッピーきょう↓
;　うろつきしんじゃ２　との↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_HAPPYFREAK)
』

MSG_BATTLE_SHOPGUARD;
←
;◆（むじんはんばいしょの↓
;　かんしにん　との↓
;　たたかい！）@KEY()↓
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_KANSHIIN)
』

MSG_BATTLE_POKEYBOYS;
←
;◆（ポーキーのこぶん↓
;　との　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_YAMAGOYA)
』

MSG_BATTLE_MATENT;
←
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_TENT)
』

MSG_BATTLE_MINIGEPPU_A;
←
;◆（ゲップーのこぶんＡ↓
;　との　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_GEPPU_FOLLOWER)
』

MSG_BATTLE_MINIGEPPU_D;
←
;◆（ゲップーのこぶんＤ↓
;　との　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_GEPPU_FOLLOWER)
』

MSG_BATTLE_MINIGEPPU_E;
←
;◆（ゲップーのこぶんＥ↓
;　との　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_GEPPU_FOLLOWER)
』

MSG_BATTLE_GEPPU;
←
;◆（ゲップーとの　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_GEPPU)
』

MSG_BATTLE_DEPT_BOSS;
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_DEPARTMENT)
』

MSG_BATTLE_GUARDROBOT;
;（見張りロボ）
@CLOSEALL()
@BATTLE(MSET_FIX_MIHARIROBO)
』

MSG_BATTLE_YUDANROBOT;
←
;◆（ゆだんロボとの　たたかい！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_YUDANROBO)
』

MSG_BATTLE_GEROPP;
←
;◆（ゲロップとの　たたかい！）@KEY()↓
;◆（@DSP_STS(STS_PC_NAME_POO)が↓
;　ほしをおとすほうほう　を↓
;　おぼえて　かえってくる。）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_GEPPU_RETURNS)
』

MSG_BATTLE_FINAL;
;←
@BATTLE( MSET_BG_LAST_1 )
』

MSG_BATTLE_OSCAR;
←
;◆（おうごんのオスカーとの↓
;　たたかい！）@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MAGICANT)
』

MSG_BATTLE_MANIMANI;
←
;◆（げんえい　マシン↓
;　との　たたかい！@KEY()
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_MANI_MANI)
』

MSG_BATTLE_DSRT_BOSS_A;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MOCHY_DUNGEON)
』

MSG_BATTLE_DSRT_BOSS_B;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MOCHY_DUNGEON)
』

MSG_BATTLE_DSRT_BOSS_C;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MOCHY_DUNGEON)
』

MSG_BATTLE_DSRT_BOSS_D;
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MOCHY_DUNGEON)
』

MSG_BATTLE_DSRT_BOSS_E;
;◆（ＹＯＵ　ＷＩＮ！）@KEY()
@CLOSEALL()
@BATTLE(MSET_FIX_BOSS_MOCHY_DUNGEON)
』

MSG_BATTLE_SKRB_KRAKEN;クラーケンとのバトル
@CLOSEALL()
@BATTLE(MSET_FIX_SEA_ROUTE)
』

MSG_BATTLE_INSEKI_STARMAN;スターマンの息子（殺し屋）
@CLOSEALL()
@BATTLE(MSET_FIX_STARMAN_SON)
』
;--------------------------------------------

MSG_BOX_ITEMFULL;
;全プレゼントボックス共通のアイテムフルメッセージ
←
◆Ｂｕｔ，　ｙｏｕ　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ．
;◆しかし　これいじょう↓
;　ものを　もてない。
@KEYNP()
』

MSG_BOX_EMPTY;
;すでに　グッズをとっている場合共通
←
◆Ｂｕｔ，　ｉｔ　ｗａｓ　ｅｍｐｔｙ．
;◆しかし　からっぽだった。
@KEYNP()
;』

;----------------------------------------------


MSG_JEFF_YONABE;
@Q_SPECIAL(PC_JEFF,1,2)
@TRUE_GOTO(_YONABE_END)
@Q_SPECIAL(PC_JEFF,1,3)
@TRUE_GOTO(_YONABE_END)
;
@CHKFGOTO(FLG_WINS_JEFF_REPAIR,_JEFF_YONABE_SECOND)
@REPAIR(100)
_JEFF_YONABE_2;
@FALSE_GOTO(_YONABE_END)
@OPEN(1)
←
◆Ｗｏｒｋｉｎｇ　ｔｈｒｏｕｇｈ　ｔｈｅ　ｎｉｇｈｔ，　@DSP_NAME(PC_JEFF)　ｆｉｘｅｄ　ｔｈｅ　@DSP_GOODS(0)．
;◆@DSP_STS(STS_PC_NAME_JEFF)は　よなべをして↓
;　@DSP_GOODS(0)を↓
;;　なおしてくれた。@KEY()↓
;　なおした。
@KEY()↓
◆Ａｆｔｅｒ　ｂｅｉｎｇ　ｆｉｘｅｄ，　ｔｈｅ　@DSP_GOODS(0)　ｂｅｃａｍｅ　ｔｈｅ　
@XCHG()
@DSP_GOODS(0)．
;◆@DSP_GOODS(0)は↓
;@XCHG()
;　@DSP_GOODS(0)だった。
@KEY()
@SETF(FLG_WINS_JEFF_REPAIR)
@CLOSEALL()
_YONABE_END;
@!

_JEFF_YONABE_SECOND;
@REPAIR(25)
@GOTO(_JEFF_YONABE_2)

;----------------------------------------------

;強制セーブメッセージ
MSG_GLOBAL_POWERSAVE_THRK;
@SET_COMEBACK_POS(TLPT_THREEK)
@GOTO(MSG_GLOBAL_POWERSAVE_MAIN)
』

MSG_GLOBAL_POWERSAVE_SKRB;
@SET_COMEBACK_POS(TLPT_SCARABI)
@GOTO(MSG_GLOBAL_POWERSAVE_MAIN)
』

MSG_GLOBAL_POWERSAVE_MAIN;
@SAVE_GAME()
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0)
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@SE(SE_se0b_tel_put)
@MUSISTART()
;@BGMSTART(0,BGM_child)
@OPEN(1)
◆Ｈｅｌｌｏ，　ｉｔ’ｓ　ｍｅ．．．ｙｏｕｒ　ｄａｄ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｍｅａｎ　ｔｏ　ｂｕｔｔ　ｉｎ，　ｂｕｔ　ｄｏｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｙｏｕ　ｓｈｏｕｌｄ　ｔａｋｅ　ａ　ｂｒｅａｋ？@KEY()↓
<Ｙｅｓ>
<Ｎｏ>
;◆あ　パパだ。@KEY()↓
;◆おせっかいかもしれないが↓
;　ちょっと　きゅうけいしては↓
;　どうかね。@KEY()↓
;　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_GLOBAL_POWERSAVE_YES,_GLOBAL_POWERSAVE_NO)

_GLOBAL_POWERSAVE_NO;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆Ｌｉｋｅ　ｍｏｔｈｅｒ，　ｌｉｋｅ　ｓｏｎ．．．@KEY()↓
◆@DSP_NAME(PC_NESS)，　ｙｏｕ　ａｒｅ　ａ　ｈａｒｄ　ｗｏｒｋｅｒ．@KEY()↓
◆Ｉ’ｖｅ　ｍａｄｅ　ａ　ｒｅｃｏｒｄ　ｏｆ　ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ．@KEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｋ　ｔｏｏ　ｈａｒｄ，　ｔｈｏｕｇｈ．．．@KEY()↓
◆＊Ｃｌｉｃｋ！＊
;◆@DSP_NAME(0)も　ママににて↓
;　がんばりやだなあ。@KEY()↓
;◆ぼうけんのきろくは↓
;　つけておいたからね。@KEY()↓
;◆むりするなよ。@KEY()↓
;◆ガチャン　ツーツーツー
@KEYNP()
@CLOSEALL()
@SE(SE_se0b_tel_put)
』

_GLOBAL_POWERSAVE_YES;
◆Ｏｋａｙ．@KEY()↓
◆Ｙ’ｋｎｏｗ，　Ｉ’ｍ　ｆｅｅｌｉｎｇ　ｋｉｎｄ　ｏｆ　ｔｉｒｅｄ　ｍｙｓｅｌｆ．@KEY()↓
◆Ｉ　ｍａｄｅ　ａ　ｒｅｃｏｒｄ　ｏｆ　ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ．@KEY()↓
◆Ｎｏｗ　Ｉ’ｍ　ｇｏｎｎａ　ｈｉｔ　ｔｈｅ　ｓａｃｋ．@KEY()↓
◆Ｂｅ　ｓｕｒｅ　ｙｏｕ　ｇｅｔ　ｓｏｍｅ　ｒｅｓｔ．↓
<Ｃｏｎｔｉｎｕｅ>
<Ｑｕｉｔ>
;◆そうか。↓
;　パパも　もう　きょうは↓
;　やすもうと　おもってたところだ。@KEY()↓
;◆ぼうけんのきろくは↓
;　つけといたよ。@KEY()↓
;◆おやすみ‥‥@KEY()↓
;　　<つづける>　　<おわる>
@DSP_ITEM(2)
@SELGOTO(_POWERSAVE_CONTINUE,_POWERSAVE_END)

_POWERSAVE_CONTINUE;
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(0)，　ｙｏｕ’ｒｅ　ａ　ｈａｒｄ　ｗｏｒｋｅｒ，　ｊｕｓｔ　ｌｉｋｅ　ｙｏｕｒ　ｍｏｍ．@KEY()↓
◆Ｄｏｎ’ｔ　ｗｏｒｋ　ｔｏｏ　ｈａｒｄ，　ｔｈｏｕｇｈ．．．@KEY()↓
◆＊Ｃｌｉｃｋ＊
;◆@DSP_NAME(0)も　ママににて↓
;　がんばりやだなあ。@KEY()↓
;◆むりするなよ。@KEY()↓
;◆ガチャン　ツーツーツー
@KEYNP()
@CLOSEALL()
@SE(SE_se0b_tel_put)
』

_POWERSAVE_END;
◆Ｗｈａｔ　ａ　ｇｒｅａｔ　ａｄｖｅｎｔｕｒｅ　ｗｅ　ｈａｄ　ｔｏｇｅｔｈｅｒ．@KEY()↓
◆Ｐｌｅａｓｅ　ｔｕｒｎ　ｏｆｆ　ｔｈｅ　ｐｏｗｅｒ．
;◆おたがい　よくやったよな。@KEY()↓
;◆それじゃ　リセットボタンを↓
;　おさないで　でんげんを　ＯＦＦに↓
;　しなさい。　わかったね。
@DISKEY()
』

;----------------------------------------------

;写真屋登場！

MSG_GLOBAL_PHOTO_1;
@CLRF(FLG_PHOTO_MYHOME)
@TAKE_PHOTO(1)
@SETF(FLG_PHOTO_1)
』
MSG_GLOBAL_PHOTO_2;
@CLRF(FLG_PHOTO_ONETMISAKI)
@TAKE_PHOTO(2)
@SETF(FLG_PHOTO_2)
』
MSG_GLOBAL_PHOTO_3;
@CLRF(FLG_PHOTO_CYCLESHOP)
@TAKE_PHOTO(3)
@SETF(FLG_PHOTO_3)
』
MSG_GLOBAL_PHOTO_4;
@CLRF(FLG_PHOTO_RIVER)
@TAKE_PHOTO(4)
@SETF(FLG_PHOTO_4)
』
MSG_GLOBAL_PHOTO_5;
@CLRF(FLG_PHOTO_CABIN)
@TAKE_PHOTO(5)
@SETF(FLG_PHOTO_5)
』
MSG_GLOBAL_PHOTO_6
@CLRF(FLG_PHOTO_CHAOS)
@TAKE_PHOTO(6)
@SETF(FLG_PHOTO_6)
』
MSG_GLOBAL_PHOTO_7;
@CLRF(FLG_PHOTO_TACY)
@TAKE_PHOTO(7)
@SETF(FLG_PHOTO_7)
』
MSG_GLOBAL_PHOTO_8;
;@CLRF(FLG_PHOTO_MAZE)
@TAKE_PHOTO(8)
@SETF(FLG_PHOTO_8)
』
MSG_GLOBAL_PHOTO_9;
@CLRF(FLG_PHOTO_HAKABA)
@TAKE_PHOTO(9)
@SETF(FLG_PHOTO_9)
』
MSG_GLOBAL_PHOTO_10;
@CLRF(FLG_PHOTO_WATERFALL)
@TAKE_PHOTO(10)
@SETF(FLG_PHOTO_10)
』
MSG_GLOBAL_PHOTO_11;
@CLRF(FLG_PHOTO_ONSEN)
@TAKE_PHOTO(11)
@SETF(FLG_PHOTO_11)
』
MSG_GLOBAL_PHOTO_12;
@CLRF(FLG_PHOTO_TENTO)
@TAKE_PHOTO(12)
@SETF(FLG_PHOTO_12)
』
MSG_GLOBAL_PHOTO_13;
;@CLRF(FLG_PHOTO_BONE)
@TAKE_PHOTO(13)
@SETF(FLG_PHOTO_13)
』
MSG_GLOBAL_PHOTO_14;
@CLRF(FLG_PHOTO_EXCAVATION)
@TAKE_PHOTO(14)
@SETF(FLG_PHOTO_14)
』
MSG_GLOBAL_PHOTO_15;
@CLRF(FLG_PHOTO_BRIDGE)
@TAKE_PHOTO(15)
@SETF(FLG_PHOTO_15)
』
MSG_GLOBAL_PHOTO_16;
@CLRF(FLG_PHOTO_DINO_MUSEUM)
@TAKE_PHOTO(16)
@SETF(FLG_PHOTO_16)
』
MSG_GLOBAL_PHOTO_17;
@CLRF(FLG_PHOTO_DINOSOR)
@TAKE_PHOTO(17)
@SETF(FLG_PHOTO_17)
』
MSG_GLOBAL_PHOTO_18;
@CLRF(FLG_PHOTO_BUILDING)
@TAKE_PHOTO(18)
@SETF(FLG_PHOTO_18)
』
MSG_GLOBAL_PHOTO_19;
@CLRF(FLG_PHOTO_DEPT)
@TAKE_PHOTO(19)
@SETF(FLG_PHOTO_19)
』
MSG_GLOBAL_PHOTO_20;
@CLRF(FLG_PHOTO_RAMMA)
@TAKE_PHOTO(20)
@SETF(FLG_PHOTO_20)
』
MSG_GLOBAL_PHOTO_21;
@CLRF(FLG_PHOTO_RAMMA_FIELD)
@TAKE_PHOTO(21)
@SETF(FLG_PHOTO_21)
』
MSG_GLOBAL_PHOTO_22;
@CLRF(FLG_PHOTO_STONEHENGE)
@TAKE_PHOTO(22)
@SETF(FLG_PHOTO_22)
』
MSG_GLOBAL_PHOTO_23;
@CLRF(FLG_PHOTO_SUMS_HOTEL)
@TAKE_PHOTO(23)
@SETF(FLG_PHOTO_23)
』
MSG_GLOBAL_PHOTO_24;
@CLRF(FLG_PHOTO_SUMS_REST)
@TAKE_PHOTO(24)
@SETF(FLG_PHOTO_24)
』
MSG_GLOBAL_PHOTO_25;
@CLRF(FLG_PHOTO_SUMS_BEACH)
@TAKE_PHOTO(25)
@SETF(FLG_PHOTO_25)
』
MSG_GLOBAL_PHOTO_26;
@CLRF(FLG_PHOTO_TOTO)
@TAKE_PHOTO(26)
@SETF(FLG_PHOTO_26)
』
MSG_GLOBAL_PHOTO_27;
@CLRF(FLG_PHOTO_SKARABI)
@TAKE_PHOTO(27)
@SETF(FLG_PHOTO_27)
』
MSG_GLOBAL_PHOTO_28;
@CLRF(FLG_PHOTO_PYRAMID)
@TAKE_PHOTO(28)
@SETF(FLG_PHOTO_28)
』
MSG_GLOBAL_PHOTO_29;
@CLRF(FLG_PHOTO_DUNGEONMAN)
@TAKE_PHOTO(29)
@SETF(FLG_PHOTO_29)
』
MSG_GLOBAL_PHOTO_30;
@CLRF(FLG_PHOTO_MAKYOU)
@TAKE_PHOTO(30)
@SETF(FLG_PHOTO_30)
』
MSG_GLOBAL_PHOTO_31;
@TAKE_PHOTO(31)
@SETF(FLG_PHOTO_31)
@CLRF(FLG_PHOTO_GUMI);プラオリティー変更用？
』
MSG_GLOBAL_PHOTO_32;
@TAKE_PHOTO(32)
@CLRF(FLG_PHOTO_SATURN);演出変更用
@SETF(FLG_PHOTO_32)
』

;----------------------------------------------
;
;ヒント屋→SHOP.MSG
;
;MSG_HINT;
;@CHKFGOTO(FLG_TEMP_1,_HINT_YES_TEMP)
;@CHKFGOTO(FLG_ONET_GATEOPEN,MSG_TEMP_HINT)
;◆ちょっとまった！ヤングマン@KEY()↓
;◆たった５ドルで↓
;　すばらしいヒントを↓
;　あげよう。@KEY()↓
;◆ヒントが　ほしいだろう？↓
;　　<はい>　　<いいえ>
;@DSP_ITEM(2)
;@SELGOTO(MSG_HINT_YES,MSG_HINT_NO)
;MSG_HINT_NO;
;◆ヒントは　いらないって？@KEY()↓
;◆きがつよいのか↓
;　５ドルが　おしいのか@KEY()↓
;◆いまどき　めずらしい↓
;　わかものだ。@KEY()↓
;◆でぐちは↓
;　いりぐちと　おんなじだよ。@KEY()↓
;◆さようなら。@KEYNP()
;』
;MSG_HINT_NOMONEY;
;◆あらま　おかねがない。@WI(20)↓
;　でも　おじさんも↓
;　しょうばいだから@KEY()↓
;◆ただで　ヒントを↓
;　あげるわけには↓
;　いかないんだよ　ぼうや。@KEYNP()
;』
;MSG_HINT_YES;
;@Q_MONEY(5)
;@TRUE_GOTO(MSG_HINT_NOMONEY)
;@SE(SE_se76_my_give)
;@MONEYOUT(5)
;@WINR_MONEY()
;@SETF(FLG_TEMP_1)
;_HINT_YES_TEMP;
;@CHKFGOTO(FLG_WIN_GEPPU,_HINT_WIN_GEPPU)
;@CHKFGOTO(FLG_GPFT_PASSWORD_OK,_HINT_GPFT_PASSWORD_OK)
;@CHKFGOTO(FLG_DOSEI_SECRETCODE,_HINT_DOSEI_SECRETCODE)
;@CHKFGOTO(FLG_WIN_MATENT,_HINT_WIN_MATENT)
;@CHKFGOTO(FLG_JEFF,_HINT_JEFF)
;@CHKFGOTO(FLG_WINS_ROPE_SWITCH,_HINT_WINS_ROPE_SWITCH)
;@CHKFGOTO(FLG_WINS_TASCO_ACROSS,_HINT_WINS_TASCO_ACROSS)
;@CHKFGOTO(FLG_WINS_TASSI_ENTER,_HINT_WINS_TASSI_ENTER)
;@CHKFGOTO(FLG_WINS_BMONKEY_DISAPPEAR,_HINT_WINS_BMONKEY_DISAPPEAR)
;@CHKFGOTO(FLG_WINS_START,_HINT_WINS_START)
;@CHKFGOTO(FLG_THRK_BIKINIZOMBI_APPEAR,_HINT_THRK_BIKINIZOMBI_APPEAR)
;@CHKFGOTO(FLG_TLPT_THRK,_HINT_TLPT_THRK)
;@CHKFGOTO(FLG_TWSN_ITEM_TONCHIKI,_HINT_TWSN_ITEM_TONCHIKI)
;@CHKFGOTO(FLG_POLA,_HINT_POLA)
;@CHKFGOTO(FLG_POLA_GRFD,_HINT_POLA_GRFD)
;@CHKFGOTO(FLG_WIN_CARPAINTER,_HINT_WIN_CARPAINTER)
;@CHKFGOTO(FLG_ITEM_FRANKLINBADGE,_HINT_ITEM_FRANKLINBADGE)
;@CHKFGOTO(FLG_GRFD_LLPT_TACO_DISAPPEAR,_HINT_GRFD_LLPT_TACO_DISAPPEAR)
;@CHKFGOTO(FLG_ITEM_TACO_ERASER,_HINT_ITEM_TACO_ERASER)
;@CHKFGOTO(FLG_TWSN_TACO_DISCOVER,_HINT_TWSN_TACO_DISCOVER)
;@CHKFGOTO(FLG_TWSN_WIN_TONCHIKI,_HINT_TWSN_WIN_TONCHIKI)
;@CHKFGOTO(FLG_TWSN_PAUL_UPSET,_HINT_TWSN_WINS_UPSET)
;@CHKFGOTO(FLG_TWSN_PAUL,_HINT_TWSN_PAUL)
;@CHKFGOTO(FLG_TWSN_APPLE_THANKS,_HINT_TWSN_APPLE_THANKS)
;@CHKFGOTO(FLG_TLPT_TWSN,_HINT_TLPT_TWSN)
;@CHKFGOTO(FLG_ONET_GATEOPEN,_HINT_ONET_GATEOPEN)
;@CHKFGOTO(FLG_POWR_GIAN,_HINT_POWR_GIAN)
;@CHKFGOTO(FLG_OPEN_TABIGOYA,_HINT_OPEN_TABIGOYA)
;@CHKFGOTO(FLG_KEY_TABIGOYA,_HINT_KEY_TABIGOYA)
;@CHKFGOTO(FLG_WIN_FRANK,_HINT_WIN_FRANK)
;◆どうやら↓
;　オネットの　まちのひとは@KEY()↓
;◆シャークだん　とかいう↓
;　ふりょうグループに↓
;　めいわくしてるらしい。@KEY()↓
;◆あんたが　いって↓
;　フランクとかいうボスを↓
;　やっつけなはれ。@KEY()↓
;◆きょうは　ここまで。@KEYNP()
;』
;_HINT_WIN_GEPPU;
;◆ちょっとまった！ヤングマン@WI(20)↓
;　ヒントを　あげたいんだけど↓
;　まだ　おもいつかないんだ。@KEY()↓
;◆わるいね。@KEYNP()
;』
;_HINT_GPFT_PASSWORD_OK;
;_HINT_DOSEI_SECRETCODE;
;_HINT_WIN_MATENT;
;_HINT_JEFF;
;_HINT_WINS_ROPE_SWITCH;
;_HINT_WINS_TASCO_ACROSS;
;_HINT_WINS_TASSI_ENTER;
;_HINT_WINS_BMONKEY_DISAPPEAR;
;_HINT_WINS_START;
;_HINT_THRK_BIKINIZOMBI_APPEAR;
;_HINT_TLPT_THRK;
;_HINT_TWSN_ITEM_TONCHIKI;
;_HINT_POLA;
;_HINT_POLA_GRFD;
;_HINT_WIN_CARPAINTER;
;_HINT_ITEM_FRANKLINBADGE;
;_HINT_GRFD_LLPT_TACO_DISAPPEAR;
;_HINT_ITEM_TACO_ERASER;
;_HINT_TWSN_TACO_DISCOVER;
;_HINT_TWSN_WIN_TONCHIKI;
;_HINT_TWSN_WINS_UPSET;
;_HINT_TWSN_PAUL;
;_HINT_TWSN_APPLE_THANKS;
;_HINT_TLPT_TWSN;
;_HINT_ONET_GATEOPEN;
;◆となりまちツーソンの↓
;　ちょうのうりょく↓
;　しょうじょ‥‥@KEY()↓
;◆@DSP_STS(STS_PC_NAME_PAULA)の↓
;　うわさは　きいたかな？@KEY()↓
;◆まちの　みなみから↓
;　ツーソンに　いってみなさい。@KEY()↓
;◆きょうは　ここまで。@KEYNP()
;』
;_HINT_POWR_GIAN;
;_HINT_OPEN_TABIGOYA;
;◆ジャイアントステップに↓
;　ゆくんだろ？@KEY()↓
;◆だったら　けいかんを↓
;　しげきしないように↓
;　きを　つけるんだね。@KEY()↓
;◆きょうは　ここまで。@KEYNP()
;』
;_HINT_KEY_TABIGOYA;
;◆ほくせいに　すすみなさい。@KEY()↓
;◆たびげいにんが↓
;　カギが　あかないって↓
;　こまってたみたいだぞ。@KEY()↓
;◆きょうは　ここまで。@KEYNP()
;』
;_HINT_WIN_FRANK;
;◆オネットしちょうの↓
;　ゲー・ハー・ピカールには↓
;　あったかな？@KEY()↓
;◆ピカールしちょうは↓
;　しちょうしゃの↓
;　２かいにいるよ。@KEY()↓
;◆きょうは　ここまで。@KEYNP()
;』
;MSG_TEMP_HINT;仮
;◆ちょっとまった！ヤングマン@WI(20)↓
;　ヒントを　あげたいんだけど↓
;　まだ　おもいつかないんだ。@KEY()↓
;◆わるいね。@KEYNP()
;』
;--------------------------------------------------------

;プレイヤーの名前入力

MSG_SYS_INPUT_PLAYER_NAME;
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0)
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@SE(SE_se0b_tel_put)
;@MUSISTART()
@OPEN(1)
◆Ｈｅｌｌｏ，　@DSP_NAME(PC_JEFF)？@KEY()↓
◆Ｏｈ，　ｈａｐｐｙ　ｄａｙ！@KEY()↓
◆Ｉ　ｆｉｎａｌｌｙ　ｇｏｔ　ａ　ｈｏｌｄ　ｏｆ　ｙｏｕ．．．
;◆もしもし　@DSP_STS(STS_PC_NAME_JEFF)ー？↓
;　うれしい　やっとでんわが↓
;　つうじた！
@KEY()↓
@SET_LOOPREG(PC_JEFF)			;ジェフのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@TRUE_GOTO(_INPUT_PLAYER_NAME_JEFF_DEAD)
◆Ｏｈ，　@DSP_STS(STS_PC_NAME_JEFF)！
;◆あ@WI(15)　@DSP_STS(STS_PC_NAME_JEFF)！
@KEY()↓
@GOTO(_INPUT_PLAYER_NAME_MAIN)

_INPUT_PLAYER_NAME_JEFF_DEAD;ジェフいない時
◆Ｈｅｙ．．．@KEY()↓
◆Ｏｈ，　ｎｏ！@KEY()↓
◆Ｙｏｕ’ｒｅ　ｎｏｔ　@DSP_NAME(PC_JEFF)！@KEY()↓
◆Ｉ’ｖｅ　ｇｏｔ　ｔｏ　ｃｏｎｔａｃｔ　@DSP_NAME(PC_JEFF)！@KEY()↓
◆Ｉ　ｋｎｏｗ．．．ｊｕｓｔ　ｐｕｔ　ｔｈｅ　ｒｅｃｅｉｖｅｒ　ｃｌｏｓｅ　ｔｏ　ｈｉｓ　ｅａｒ，　ａｎｄ　ｈｅ’ｌｌ　ｈｅａｒ　ｍｅ．．．@KEY()↓
◆Ｉ　ｋｎｏｗ　ｈｅ　ｗｉｌｌ．
;◆もしもし‥‥@KEY()↓
;◆あ@WI(15)　@DSP_STS(STS_PC_NAME_JEFF)じゃないのか！@KEY()↓
;◆きぜつしている↓
;　@DSP_STS(STS_PC_NAME_JEFF)の　みみもとに@KEY()↓
;◆ぼくの　こえを↓
;　きかせてあげて　ください。@KEY()↓
;◆きっと　つうじるから‥‥
@KEY()↓

_INPUT_PLAYER_NAME_MAIN;
◆Ｈｉ，　ｉｔ’ｓ　ｍｅ－－Ｔｏｎｙ．@KEY()↓
◆Ｉ’ｍ　ｃｏｌｌｅｃｔｉｎｇ　ｐｌａｙｅｒ’ｓ　ｎａｍｅｓ　ｆｏｒ　ａ　ｓｃｈｏｏｌ　ｐｒｏｊｅｃｔ．@KEY()↓
◆Ｙｏｕ　ｋｎｏｗ，　ｐｌａｙｅｒｓ　ｊｕｓｔ　ｌｉｋｅ　ｙｏｕ！@KEY()↓
◆Ｔｈａｔ’ｓ　ｒｉｇｈｔ，　ｙｏｕ－－ｔｈｅ　ｏｎｅ　ｈｏｌｄｉｎｇ　ｔｈｅ　ｃｏｎｔｒｏｌｌｅｒ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｒｅｇｉｓｔｅｒ　ｙｏｕｒ　ｎａｍｅ，　ｐｌｅａｓｅ？@KEY()↓
◆Ｄｏｎ’ｔ　ｓｐｅｌｌ　ｙｏｕｒ　ｎａｍｅ　ｗｒｏｎｇ！
;◆ぼくだよ　トニーだよ！@KEY()↓
;◆がっこうの　しゅくだいで↓
;　このゲームの　プレイヤーの↓
;　なまえを　しらべてるんだ。@KEY()↓
;◆いま　コントローラーを↓
;　うごかしてるひとの　ことさ。@KEY()↓
;◆なまえを　にゅうりょく↓
;　してもらって　くれないか？@KEY()↓
;◆ローマじ　ひょうきだから↓
;　くれぐれも　まちがえないように↓
;　ちゅういしてね。
@KEY()
@CLOSEALL()
;--------------
@BGM_EFFECT(2)
@WI(30)
@BGMSTART(0,BGM_name)
;--------------
@FUNC(3);入力
@OPEN(1)
◆Ｔｈａｎｋｓ，　ｇａｍｅ　ｐｌａｙｅｒ！@KEY()↓
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ！@KEY()↓
◆Ｉｓ　ｔｈｉｓ　ｃｏｒｒｅｃｔ？
;◆プレイヤーのかた↓
;　どうも　ありがとうございます。@KEY()↓
;◆これで　まちがいないですか？
@KEY()
@CLOSEALL()
@FUNC(3);入力
;--------------
@BGM_EFFECT(2)
@WI(30)
;--------------
@OPEN(1)
◆Ｉ　ａｐｏｌｏｇｉｚｅ　ｆｏｒ　ａｎｙ　ｔｒｏｕｂｌｅ　ｔｈｉｓ　ｍａｙ　ｈａｖｅ　ｃａｕｓｅｄ　ｙｏｕ．@KEY()↓
◆Ｄｏｎ’ｔ　ｐｕｔ　ｍｙ　ｆｒｉｅｎｄ　@DSP_NAME(PC_JEFF)　ｉｎ　ａｎｙ　ｄａｎｇｅｒｏｕｓ　ｓｉｔｕａｔｉｏｎｓ，　ｏｋａｙ？@KEY()↓
◆Ｉ　ｗｏｒｒｙ　ａｂｏｕｔ　ｈｉｍ．@KEY()↓
◆Ｉ　ｒｅａｌｌｙ　ｄｏ．．．@KEY()↓
◆Ｗｅｌｌ，　ｔａｌｋ　ｔｏ　ｙｏｕ　ｌａｔｅｒ．．．@KEY()↓
◆．．．@DSP_NAME(PC_JEFF)．．．@KEY()↓
;◆おてすうかけて↓
;　すみませんでした。@KEY()↓
;◆ともだちの　@DSP_STS(STS_PC_NAME_JEFF)を↓
;　あんまり　あぶないめに↓
;　あわせないでくださいね。@KEY()↓
;◆ぼく　しんぱいで↓
;　しんぱいで‥‥@DSP_STS(STS_PC_NAME_JEFF)。@KEY()↓
;◆‥‥じゃあ@WI(20)　@DSP_STS(STS_PC_NAME_JEFF)↓
@SET_LOOPREG(PC_JEFF)			;ジェフのＩＤを主レジに格納
@GOSUB(MSG_SUB_Q_DEAD)			;気絶チェック
@FALSE_GOTO(_INPUT_PLAYER_NAME_JEFF_MAIN2)
◆Ｉｔ　ｓｅｅｍｓ　ｌｉｋｅ　ｙｏｕ’ｒｅ　ｎｏｔ　ｆｅｅｌｉｎｇ　ｗｅｌｌ．．．@KEY()↓
◆Ｇｅｔ　ｂｅｔｔｅｒ　ｓｏｏｎ．．．
;◆からだのぐあい↓↓
;　わるいみたいだけど↓
;　はやく　なおしてね。
@KEY()↓
_INPUT_PLAYER_NAME_JEFF_MAIN2;
◆Ｉ　ｈｏｐｅ　ｔｈａｔ　Ｉ　ｃａｎ　ｓｅｅ　ｙｏｕ　ａｇａｉｎ　ｗｈｅｎ　ｙｏｕ　ａｒｅ　ｆｅｅｌｉｎｇ　ｕｐ　ｔｏ　ｉｔ．．．@KEY()↓
◆Ｆｒｏｍ　Ｔ＊Ｏ＊Ｎ＊Ｙ＊．．．@KEY()↓
◆Ｙｏｕ　ｇｏｔ　ｔｈａｔ？@KEY()↓
◆Ｗｅｌｌ　Ｉ’ｖｅ　ｂｅｅｎ　ｏｎ　ｔｈｅ　ｐｈｏｎｅ　ｔｏｏ　ｌｏｎｇ．．．@KEY()↓
◆Ｇｏｔｔａ　ｇｏ．．．@KEY()↓
◆Ｇｏｏｄ　ｌｕｃｋ．．．@KEY()↓
◆Ｔａｋｅ　ｃａｒｅ．．．@KEY()↓
◆Ｓｏ　ｌｏｎｇ．．．@KEY()↓
◆Ｔｈｉｓ　ｔｉｍｅ，　Ｉ’ｍ　ｒｅａｌｌｙ　ｇｏｎｎａ　ｈａｎｇ　ｕｐ．@KEY()↓
◆Ｇｏｏｄｂｙｅ．@KEY()↓
◆＊Ｂｅｅｅｅｅｐ＊
;◆また　げんきなすがたの↓
;　きみに　あえることを@KEY()↓
;◆こころから↓
;　おいのりしているよ！@KEY()↓
;◆きみのともだち　ト@WI(10)ニ@WI(10)ー@WI(10)よ@WI(10)り@KEY()↓
;◆‥‥でした。@KEY()↓
;◆あ@WI(15)　でんわが↓
;　ながくなっちゃうから↓
;　もう　きるね。@KEY()↓
;◆さよなら。@KEY()↓
;◆がんばってね。@KEY()↓
;◆きを　つけてね。@KEY()↓
;◆ほんとに　きるからね。@KEY()↓
;◆バーイ‥‥@KEY()↓
;◆‥‥ツーツーツー
@KEYNP()
@CLOSEALL()
@SE(SE_se0b_tel_put)
@SETF(FLG_SYS_INPUT_PLAYER_NAME)
;-----------
@MUSISTART()
;-----------
@FUNC(6)			;毒死配達許可
』
;-------------------------------------------------

MSG_ONET_POLA_TELEPATHY;003_A
@OPEN(1)
◆．．．@KEY()↓
◆@DSP_NAME(PC_NESS)？@KEY()↓
◆．．．@KEY()↓
◆@DSP_NAME(PC_NESS)@KEY()↓
;◆‥‥‥@KEY()↓
;◆‥‥@DSP_STS(STS_PC_NAME_NES)@KEY()↓
@WI(60)↓
@WI(60)↓
◆．．．@DSP_NAME(PC_NESS)．．．@KEY()↓
◆Ｉ’ｍ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　ｙｏｕ　ｈａｖｅ　ｎｅｖｅｒ　ｍｅｔ　ｂｅｆｏｒｅ．．．@KEY()↓
◆Ｍｙ　ｎａｍｅ　ｉｓ　@DSP_NAME(PC_PAULA)．@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)‥‥。@KEY()↓
;◆まだ　あったことのない↓
;　わたしのともだち‥‥。@KEY()↓
;◆わたしは↓
;　@DSP_STS(STS_PC_NAME_PAULA)です。
@KEY()↓
@WI(60)↓
◆Ｃａｎ　ｙｏｕ　ｈｅａｒ　ｍｅ　ｃａｌｌｉｎｇ　ｙｏｕ？@KEY()↓
◆Ｉ　ａｍ　@DSP_NAME(PC_PAULA)．．．@KEY()↓
◆．．．
;◆わたしの　よびかけを↓
;　かんじますか？@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)　@DSP_STS(STS_PC_NAME_NES)↓
;　‥‥わたしは　@DSP_STS(STS_PC_NAME_PAULA)です。@KEY()↓
;◆‥‥‥
@KEY()↓
@WI(60)↓
@WI(60)↓
◆．．．
;◆‥‥
@KEYNP()
@CLOSEALL()
@WI(1)
@CLRF(FLG_ONET_POLA_TELEPATHY)
@GOTO(MSG_SUB_HOTEL_YES_CHKF)			;SHOP2の処理に帰る
』

MSG_TWSN_POLA_TELEPATHY;003_B
@OPEN(1)
◆．．．@KEY()↓
◆@DSP_NAME(PC_NESS)！@KEY()↓
◆Ｉ．．．@DSP_NAME(PC_PAULA)．．．@KEY()↓
◆Ｉ　ａｍ　@DSP_NAME(PC_PAULA)．．．@KEY()↓
◆Ｃａｎ　ｙｏｕ　ｈｅａｒ　ｍｅ　ｃａｌｌｉｎｇ　ｙｏｕ？@KEY()↓
◆Ｈｅｌｐ！@KEY()↓
◆Ｃｏｍｅ　ａｎｄ　ｈｅｌｐ　ｍｅ！@KEY()↓
◆Ｕｍ，　Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈｅｒｅ　Ｉ　ａｍ．．．@KEY()↓
◆Ｉ　ｃａｎ　ｈｅａｒ　ｗａｔｅｒ　ｒｕｎｎｉｎｇ　ｉｎ　ｔｈｅ　ｄｉｓｔａｎｃｅ．．．@KEY()↓
;◆‥‥しは　@DSP_STS(STS_PC_NAME_PAULA)↓
;　わたしは　@DSP_STS(STS_PC_NAME_PAULA)です。@KEY()↓
;◆わたしの　よびかけを↓
;　かんじますか？　@DSP_STS(STS_PC_NAME_NES)@KEY()↓
;◆たすけて！↓
;　たすけにきて！@KEY()↓
;◆ここが　どこなのか↓
;　わからない。@KEY()↓
;◆‥‥とおくから↓
;　みずの　ながれるおとが↓
;　きこえる‥‥。@KEY()↓
;◆@DSP_STS(STS_PC_NAME_NES)！
@WI(20)↓
@WI(60)↓
◆@DSP_NAME(PC_NESS)，　ｐｌｅａｓｅ　ｈｅｌｐ　ｍｅ！
;◆@DSP_STS(STS_PC_NAME_NES)　たすけにきて！
@KEYNP()
@CLOSEALL()
@WI(1)
@CLRF(FLG_TWSN_POLA_TELEPATHY)
@GOTO(MSG_SUB_HOTEL_YES_CHKF)			;SHOP2の処理に帰る
』

MSG_WINS_POLA_TELEPATHY;013_B
@OPEN(1)
◆Ｙｏｕ　ａｒｅ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　Ｉ　ｈａｖｅ　ｎｅｖｅｒ　ｍｅｔ　ｂｅｆｏｒｅ．．．@KEY()↓
◆@DSP_NAME(PC_JEFF)．．．@KEY()↓
◆Ｈｅａｄ　ｓｏｕｔｈ．．．@KEY()↓
◆Ｉ　ａｍ　@DSP_STS(STS_PC_NAME_PAULA)．．．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｈｅａｒ　ｔｈｉｓ　ｍｅｓｓａｇｅ，　ｇｏ　ｔｏ　ｔｈｅ　ｓｏｕｔｈ．．．
;◆まだ　あったことのない↓
;　わたしたちのなかま‥‥@DSP_STS(STS_PC_NAME_JEFF)！@KEY()↓
;◆とにかく　みなみに　むかって。↓
;　‥‥わたしは　@DSP_STS(STS_PC_NAME_PAULA)‥‥。@KEY()↓
;◆わたしの　こころを　かんじたら↓
;　みなみに　むかってください‥‥
@KEYNP()
@CLOSEALL()
@CLRF(FLG_WINS_POLA_TELEPATHY)
@GOTO(MSG_SUB_HOTEL_YES_CHKF)			;SHOP2の処理に帰る
』
;-------------------------------------------------

;ビキニゾンビの声

MSG_EVT_BIKINI_WHISPER_A;フィールドでホテルの扉前に移動し、くるりと振り返った時
@OPEN(1)
◆Ａｈｈｈｈｈ．
;◆アッハン。
@KEY()
@CLOSEALL()
』
MSG_EVT_BIKINI_WHISPER_B;フロントで
@OPEN(1)
◆Ｈｕｍｍｍｍｍｍ．
;◆ウッフン。
@KEY()
@CLOSEALL()
』
MSG_EVT_BIKINI_WHISPER_C;廊下で
@OPEN(1)
◆Ｈｅ　ｈｅ　ｈｅｈ．
;◆クックック。
@KEY()
@CLOSEALL()
』
;-------------------------------------------------

MSG_CHECK_WINS_BRICKROAD;ブリックロードのダンジョンの看板
◆（Ｔｈｉｓ　ｄｕｎｇｅｏｎ　ｈａｓ　ｎｏ　ｅｎｔｒａｎｃｅ　ｆｅｅ．@KEY()↓
◆Ｃｏｍｅ　ｏｎ　ｉｎ！）
;◆（このダンジョンは↓
;　にゅうじょうりょう↓
;　いりません。@WI(20)どうぞ　どうぞ）
@KEYNP()
』

;-------------------------------------------------

;ドムークの名
;「デパートのかいじん」
;-------------------------------------------------

;ヘリコプターのポーキー（S_EVENTに）
;◆とんまやろうの　@DSP_STS(STS_PC_NAME_NES)！↓
;　じたばたしても　おそいぜ！↓
;　バイバイ！@KEY()↓
;◆おひとよしに　もどっちまった↓
;　モノトリーじいさんには↓
;　もう　ようは　ないね。@KEY()↓
;◆おれ　ヘリコプターにのれて↓
;　うれしいぜ！@KEY()↓
;◆おしり　ペンペーン！@KEY()↓
;◆アッカン　ベロベロベー！@KEYNP()
;』

MSG_FOUR_CHECK_HELIDOOR;ヘリポートへのドア
◆（Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ａ　ｄｏｏｒｗａｙ．．．）
;◆（‥‥ドアがあるようなふんいき）
@KEYNP()
』
;-------------------------------------------------

MSG_SUMS_PHONE_RICEBOWL;博物館の電話（ライスボウル）
@SE(SE_se0b_tel_put)@WI(20)
@GOSUB(MSG_EVT_SUMS_RING_STOP);電話止む
◆Ｈｅｌｌｏ！@KEY()↓
◆Ｉｓ　ｔｈｉｓ　Ｍｒ．　Ｆｏｒｋ　ｏｆ　ｔｈｅ　Ｓｃａｒａｂａ　Ｃｕｌｔｕｒａｌ　Ｍｕｓｅｕｍ？．．．@KEY()↓
◆Ｉｔ　ｄｏｅｓｎ’ｔ　ｓｏｕｎｄ　ｌｉｋｅ　ｙｏｕ．．．@KEY()↓
◆Ｗｅｌｌ，　Ｉ’ｌｌ　ｑｕｉｃｋｌｙ　ｔｅｌｌ　ｙｏｕ　ｍｙ　ｓｔｏｒｙ，　’ｃａｕｓｅ　Ｉ’ｍ　ｂｕｓｙ，　ｂｕｓｙ，　ｂｕｓｙ！@KEY()↓
◆Ｉ　ｆｏｕｎｄ　ｓｏｍｅｔｈｉｎｇ　ｓｏ　ｅｘｔｒａｏｒｄｉｎａｒｙ　ｔｈａｔ　ｍｅｒｅ　ｗｏｒｄｓ　ｃｏｕｌｄ　ｎｏｔ　ｄｏ　ｉｔ　ｊｕｓｔｉｃｅ．@KEY()↓
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｍｅａｎ　”ｗｈｏ　ａｍ　Ｉ”？@KEY()↓
◆Ｄｏｎ’ｔ　ｙｏｕ　ｒｅｃｏｇｎｉｚｅ　ｍｙ　ｖｏｉｃｅ？@KEY()↓
◆Ｉｔ’ｓ　ｍｅ，　Ｍｒ．　Ｓｐｏｏｎ　ｆｒｏｍ　ｔｈｅ　Ｆｏｕｒｓｉｄｅ　Ｍｕｓｅｕｍ　ｏｆ　Ｎａｔｕｒａｌ　Ｈｉｓｔｏｒｙ！@KEY()↓
◆Ｌｏｏｋ　Ｍｒ．　Ｆｏｒｋ，　Ｉ’ｍ　ｎｏｔ　ｅｘａｇｇｅｒａｔｉｎｇ　ｔｈｉｓ　ｆｉｎｄ！@KEY()↓
◆Ｉ’ｍ　ｔｅｌｌｉｎｇ　ｙｏｕ．．．@KEY()↓
◆Ｉｔ’ｓ　ｆａｎｔａｓｔｉｃ！．．．．．@KEY()↓
◆Ｉｔ’ｓ　ｏｕｔｒａｇｅｏｕｓ！．．．@KEY()↓
◆＊Ｃｌｉｃｋ＊　　Ｂｅｅｅｅｅｐ
;◆もしもし！@WI(10)↓
;　「スカラビぶんかはくぶつかん」の↓
;　チャップスティックくんかい！？@KEY()↓
;◆‥‥ちょっと　こえが↓
;　ちがうみたいだけど@WI(15)↓
;　ま　いいや。@KEY()↓
;◆ぼくは　じぶんのようじだけ↓
;　いいます。@WI(15)↓
;　‥‥いそがしいから。@KEY()↓
;◆とにかく　くちでは↓
;　いえないくらい↓
;　たいへんなものを@KEY()↓
;◆はっけんしたんですよ！@KEY()↓
;◆‥‥だれって　わたしですよ！@WI(10)↓
;　「フォーサイド↓
;　しぜんはくぶつかん」の@KEY()↓
;◆ライスボウルですよ！@KEY()↓
;◆べつに　これは↓
;　じまんばなしじゃないんだよ。@KEY()↓
;◆でも　わたしは‥‥↓
;　ある「とんでもないもの」を↓
;　はっけんした！　と‥‥。@KEY()↓
;◆ガチャン！　ツーツーツー
@KEYNP()
@SE(SE_se0b_tel_put)
@CLRF(FLG_SUMS_MUSEUM_PHONE_RING)
』
;-------------------------------------------------

MSG_MANIMANI_RECEIVE;タコけしマシンを「マジカントのあくま」に使うと
@GET_PLAYER_GOODS(0,0)
@XCHG()
@SAVE_REG()
@EQ(GDS_TOOL_KEY_KOKESHIKESHI)
@TRUE_GOTO(_MANIMANI_RECEIVE_KOKESHI)
@LOAD_REG()
@EQ(GDS_TOOL_KEY_TAKOKESHI)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Ｄｏ　ｙｏｕ　ｒｅａｌｌｙ　ｔｈｉｎｋ　ｔｈｉｓ　ｌｏｏｋｓ　ｌｉｋｅ　ａ　ｐｅｎｃｉｌ？
;◆このてきの　どこが↓
;　タコに　にているというのだ？
@KEYNP()
』
_MANIMANI_RECEIVE_KOKESHI;
◆Ｉｔ　ｌｏｏｋｓ　ｓｏｒｔ　ｏｆ　ｌｉｋｅ　ｓｏｍｅ　ｐｒｉｍｉｔｉｖｅ　ｈｕｍａｎ　ｓｔａｔｕｅ@KEY()↓
◆ｉｆ　ｙｏｕ　ｌｏｏｋ　ａｔ　ｉｔ　ｆｒｏｍ　ｔｈｅ　ｒｉｇｈｔ　ａｎｇｌｅ．．．@KEY()↓
◆Ｂｕｔ　ｉｔ　ｄｅｆｉｎｉｔｅｌｙ　ｄｏｅｓｎ’ｔ　ｌｏｏｋ　ｌｉｋｅ　ａｎ　ｅｒａｓｅｒ．．．ｄｏｅｓ　ｉｔ？
;◆これは　みようによっては↓
;　こけしにも　にているが↓
;　こけしとは　いえない。
@KEYNP()
』

MSG_HAPPY_USHI_RECEIVE;うしに「ニンジン」
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_KEY_CARROT)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
◆Ｃｏｗｓ　ａｎｄ　ｃａｒｒｏｔｓ？．．．@KEY()↓
◆Ｔｈａｔ’ｓ　ａ　ｎｕｔｔｙ　ｃｏｍｂｉｎａｔｉｏｎ！
;◆ウシには　ニンジンは↓
;　にあわない‥‥だろう？
@KEYNP()
』
;-------------------------------------------------

MSG_DOSEI_JEFF_RECEIVE;上の手紙をもらったジェフのセリフ
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_LETTER_TONY)
@FALSE_GOTO(MSG_SYS_GOODS_USE_NG)
@GET_CHAR_DIR(PRSN_DOSE_FIELD_V,1,PC_NESS);ネスの方を向く
@SET_CHAR_DIR(PRSN_DOSE_FIELD_V,0)
◆Ａｈ，　@DSP_NAME(PC_NESS)．．．ｙｏｕ’ｖｅ　ｒｅａｄ　ｉｔ　ａｌｒｅａｄｙ．@KEY()↓
◆．．．Ｔｈａｔ　Ｔｏｎｙ　ｈａｓ　ａ　ｈｅａｒｔ　ｏｆ　ｇｏｌｄ．．．
;◆あ‥‥@WI(20)@DSP_STS(STS_PC_NAME_NES)↓
;　きみ@WI(15)　これ　よんじゃったね。@KEY()↓
;◆‥‥トニーって↓
;　ねは　いいやつなんだよ。
@KEYNP()
』
;-------------------------------------------------

;デリバリーフラグを降ろすサブルーチン
MSG_GLOBAL_DELIVERY_RESET;（場面転換時に配達を中止）
@CLRF(FLG_DELIVERY_PIZZA)
@CLRF(FLG_DELIVERY_UNSOU)
@CLRF(FLG_DELIVERY_UNSOU_B)
@CLRF(FLG_DELIVERY_CUSTOMER)
@CLRF(FLG_DELIVERY_CUSTOMER_B)
@CLRF(FLG_DELIVERY_CUSTOMER_C)
@CLRF(FLG_DELIVERY_CUSTOMER_D)
@CLRF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@CLRF(FLG_DELIVERY_UNSOU_TAKANOME)
@GOSUB(MSG_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLRF(FLG_SYS_DISTLPT);テレポート許可
』
;------------------------------------------------------------

MSG_GLOBAL_BOSS_NG;対ガーディアン時ネス死にの場合共通
◆Ｏｎｌｙ　@DSP_NAME(PC_NESS)　ｃａｎ　ａｂｓｏｒｂ　ｔｈｅ　ｐｏｗｅｒ　ｏｆ　ｔｈｉｓ　ｐｌａｃｅ．
;◆@DSP_STS(STS_PC_NAME_NES)いがいの　ものには↓;ネスじゃない時のセリフ
;　このばしょの　パワーを↓
;　ひきだすことができない。
@KEYNP()
』
;------------------------------------------------------------

;追加メッセージ
MSG_SUMS_OPENCAR;
◆Ｈｅｙ，　ｈｅｙ！！@KEY()↓
◆Ｓｔｏｐ　ｐｕｔｔｉｎｇ　ｙｏｕｒ　ｇｒｉｍｙ　ｆｉｎｇｅｒｐｒｉｎｔｓ　ａｌｌ　ｏｖｅｒ　ｍｙ　ｃａｒ，　ｙｏｕ　ｌｉｔｔｌｅ　ｐｕｎｋ！
;◆おいおい！@WI(20)　オレのクルマに↓
;　べたべたべったべた　しもん↓
;　つけんじゃねえっての！
@KEYNP()
』

MSG_DSRT_HIGHWAY_E;			;added 0717
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　ｖｅｒｙ　ｅｎｄ　ｏｆ　ｔｈｅ　ｗｏｒｌｄ’ｓ　ｌｏｎｇｅｓｔ　ｔｒａｆｆｉｃ　ｊａｍ！
;◆じゅうたいのケツへ　ヨーコソ！
@KEYNP()
@!

MSG_TWSN_HOTEL_A;
@CHKFGOTO(FLG_TWSN_HOTEL_A_END,_TWSN_HOTEL_A_END)
@CHKFGOTO(FLG_TWSN_HOTEL_A,_TWSN_HOTEL_A_9)
@CHKFGOTO(FLG_TEMP_8,_TWSN_HOTEL_A_8)
@CHKFGOTO(FLG_TEMP_7,_TWSN_HOTEL_A_7)
@CHKFGOTO(FLG_TEMP_6,_TWSN_HOTEL_A_6)
@CHKFGOTO(FLG_TEMP_5,_TWSN_HOTEL_A_5)
@CHKFGOTO(FLG_TEMP_4,_TWSN_HOTEL_A_4)
@CHKFGOTO(FLG_TEMP_3,_TWSN_HOTEL_A_3)
@CHKFGOTO(FLG_TEMP_2,_TWSN_HOTEL_A_2)
@CHKFGOTO(FLG_TEMP_1,_TWSN_HOTEL_A_1)
◆Ｗｈａｔ？
;◆なに？
@KEYNP()
@SETF(FLG_TEMP_1)
』
_TWSN_HOTEL_A_1;
◆Ｓｏ．．．ｗｈａｔ？
;◆だから@WI(20)　なに？
@KEYNP()
@SETF(FLG_TEMP_2)
』
_TWSN_HOTEL_A_2;
◆Ｈｕｈ？
;◆えっ？
@KEYNP()
@SETF(FLG_TEMP_3)
』
_TWSN_HOTEL_A_3;
◆Ｐａｒｄｏｎ？
;◆なんだあ？
@KEYNP()
@SETF(FLG_TEMP_4)
』
_TWSN_HOTEL_A_4;
◆Ｇｅｅｚ．．．
;◆ちっ。
@KEYNP()
@SETF(FLG_TEMP_5)
』
_TWSN_HOTEL_A_5;
◆Ｍｍｍ？
;◆あ～ん？
@KEYNP()
@SETF(FLG_TEMP_6)
』
_TWSN_HOTEL_A_6;
◆Ｙｏｕ’ｒｅ　ａｎｎｏｙｉｎｇ！
;◆しつこいぞ。
@KEYNP()
@SETF(FLG_TEMP_7)
』
_TWSN_HOTEL_A_7;
◆Ｄａｎｇ　ｍｅ！
;◆ったく。
@KEYNP()
@SETF(FLG_TEMP_8)
』
_TWSN_HOTEL_A_8;
◆Ｙｅａｈ，　ｙｅａｈ！
;◆はいはい。
@KEYNP()
@SETF(FLG_TWSN_HOTEL_A)
@CLRF(FLG_TEMP_1)
@CLRF(FLG_TEMP_2)
@CLRF(FLG_TEMP_3)
@CLRF(FLG_TEMP_4)
@CLRF(FLG_TEMP_5)
@CLRF(FLG_TEMP_6)
@CLRF(FLG_TEMP_7)
@CLRF(FLG_TEMP_8)
』
_TWSN_HOTEL_A_9;
@CHKFGOTO(FLG_TEMP_7,_TWSN_HOTEL_A_16)
@CHKFGOTO(FLG_TEMP_6,_TWSN_HOTEL_A_15)
@CHKFGOTO(FLG_TEMP_5,_TWSN_HOTEL_A_14)
@CHKFGOTO(FLG_TEMP_4,_TWSN_HOTEL_A_13)
@CHKFGOTO(FLG_TEMP_3,_TWSN_HOTEL_A_12)
@CHKFGOTO(FLG_TEMP_2,_TWSN_HOTEL_A_11)
@CHKFGOTO(FLG_TEMP_1,_TWSN_HOTEL_A_10)
◆Ａｈ，　ｈａ　ｈａ！
;◆あはは。
@KEYNP()
@SETF(FLG_TEMP_1)
』
_TWSN_HOTEL_A_10;
◆Ｈｅｙ，　ｙｏｕ！
;◆こらっ！
@KEYNP()
@SETF(FLG_TEMP_2)
』
_TWSN_HOTEL_A_11;
◆Ｌａｔｅｒ　ｄａｙｓ，　ｐａｌ！
;jpn:◆ばいばい@WI(20)　ね。
@KEYNP()
@SETF(FLG_TEMP_3)
』
_TWSN_HOTEL_A_12;
◆Ａｈ！　　Ｈａｈ　Ｈａｈｈｈｈ．．．
;◆あはははは！
@KEYNP()
@SETF(FLG_TEMP_4)
』
_TWSN_HOTEL_A_13;
◆Ｉｔ’ｓ　ｓｏｏｏ　ｈｏｔ　ｔｏｄａｙ．@KEY()↓
◆Ｉｔ　ｒｏｃｋｓ！
;◆きょうは　あついな。
@KEYNP()
@SETF(FLG_TEMP_5)
』
_TWSN_HOTEL_A_14;
◆Ｉｓ　ｉｔ　ｃｏｌｄ　ｔｏｄａｙ？
;◆きょうは　さむいか？
@KEYNP()
@SETF(FLG_TEMP_6)
』
_TWSN_HOTEL_A_15;
◆Ｏｈ　ｈｏ　ｈｏ！@KEY()↓
◆Ｓｅｅ　ｙａ！
;◆あはは@WI(30)　じゃあな。
@KEYNP()
@SETF(FLG_TEMP_7)
』
_TWSN_HOTEL_A_16;
◆Ｈｅｒｅ，　ｇｅｔ　ｙｏｕｒｓｅｌｆ　ａ　ｊｕｉｃｅ　ｏｒ　ｓｏｍｅｔｈｉｎｇ．．．@KEY()↓
◆＊Ｋａ－ｃｈｉｎｇ＊
;◆これで@WI(20)（ジャラジャラ）@WI(20)↓
;　ジュースでもかいなよ。
@KEY()↓
@MONEYIN(50)
@SE(SE_se74_my_get)
@WINR_MONEY()
@WI(60)
@GET_ORDER_PLAYER(1)
@SET_REG(0)
◆@DSP_NAME(PC_NESS)　ｇｏｔ　５０　ｄｏｌｌａｒｓ．
;◆（@DSP_NAME(0)は↓
;　５０ドル　もらった）
@KEYNP()
@SETF(FLG_TWSN_HOTEL_A_END)
』
_TWSN_HOTEL_A_END;
◆Ｇｏｏｄ　ｌｕｃｋ，　ｏｋ？
;◆がんばれ@WI(20)　な。
@KEYNP()
』
;------------------------------------------------------------

MSG_GLOBAL_PHONE_TRACY_LOSTITEM;
@BGMSTART(0,BGM_msc1)
@WI(60)
@KEYNP()
@BGMSTOP(0)
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
@SE(SE_se0b_tel_put)
@OPEN(1)
◆Ｓｏｒｒｙ　ｔｏ　ｂｏｔｈｅｒ　ｙｏｕ，　ｂｉｇ　ｂｒｏ．．．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆Ｉ　ｈａｄ　ａ　ｐｈｏｎｅ　ｃａｌｌ　ｆｒｏｍ　ａ　ｆｒｉｅｎｄ　ｏｆ　ｙｏｕｒｓ　ｒｅｃｅｎｔｌｙ　ｃａｌｌｅｄ．@KEY()↓
@CHKFGOTO(FLG_SKRB_PU_TAKANOME,_PHONE_TRACY_LOSTITEM_PU)
◆Ｓｈｅ　ａｓｋｅｄ　ｍｅ　ｔｏ　ｈｏｌｄ　ｏｎｔｏ　ｔｈｅ　Ｐｅｎｃｉｌ　Ｅｒａｓｅｒ　ｍａｃｈｉｎｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｋｎｏｗ　ａｎｙｔｈｉｎｇ　ａｂｏｕｔ　ｔｈｉｓ？
;◆いそがしいところに↓
;　でんわして　ごめんね。@WI(20)↓
;　エスカルゴうんそうでーす。@KEY()↓
;◆さっき　おにいちゃんの↓
;　ともだちっていう↓
;@CHKFGOTO(FLG_SKRB_PU_TAKANOME,_PHONE_TRACY_LOSTITEM_PU)
;　おんなのこから　でんわがあって@KEY()↓
;◆「タコけしマシン」ってのを↓
@SETF(FLG_GLOBAL_LOST_TAKOKESHI)
@GOTO(_PHONE_TRACY_LOSTITEM_MAIN)

_PHONE_TRACY_LOSTITEM_PU;
◆Ｈｅ　ａｓｋｅｄ　ｍｅ　ｔｏ　ｈｏｌｄ　ｏｎｔｏ　ｔｈｅ　Ｈａｗｋ　Ｅｙｅ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｋｎｏｗ　ａｎｙｔｈｉｎｇ　ａｂｏｕｔ　ｔｈｉｓ？
;jpn:　ひとから　でんわがあって@KEY()↓
;jpn:◆「タカのめ」ってのを↓
@SETF(FLG_GLOBAL_LOST_TAKANOME)

_PHONE_TRACY_LOSTITEM_MAIN;
◆Ｗｅｌｌ，　ｓｉｎｃｅ　ｙｏｕ　ｋｎｏｗ　ａｂｏｕｔ　ｔｈｅ　ｉｔｅｍ，　Ｉ’ｌｌ　ｈｏｌｄ　ｏｎｔｏ　ｉｔ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｎｅｅｄ　ｉｔ，　Ｉ’ｌｌ　ｄｅｌｉｖｅｒ　ｉｔ　ｔｏ　ｙｏｕ　ａｎｙｔｉｍｅ　ｙｏｕ　ｗａｎｔ．@KEY()↓
◆Ｏｈ　ｙｅａｈ，　ｂｉｇ　ｂｒｏ．．．@KEY()↓
◆Ｉ’ｍ　ｇｌａｄ　ｔｈａｔ　Ｉ　ｃｏｕｌｄ　ｈｅｌｐ　ｏｕｔ　ｙｏｕ　ａｎｄ　ｙｏｕｒ　ｆｒｉｅｎｄｓ．@KEY()↓
◆＊Ｃｌｉｃｋ＊
;　あずかったんだけど‥‥↓
;　いたずらかなぁと　おもって。@KEY()↓
;◆もし　ほんとなら↓
;　わたしがあずかってるから@KEY()↓
;◆ひつようなときは↓
;　いつでも　おとどけするわ。@KEY()↓
;◆‥‥やっぱり↓
;　いたずらじゃなかったのかぁ。@KEY()↓
;◆ガチャン　ツーツーツー
@KEYNP()
@CLOSEALL()
@SE(SE_se0b_tel_put)
@MUSISTART()
@CLRF(FLG_FOUR_PAULA_TAKOKESHI)
@CLRF(FLG_SKRB_PU_TAKANOME)
』
;-------------------------------------------------

MSG_GLOBAL_DELIVERY_TACO;
;遺失物配達
@OPEN(1)
◆Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ！@KEY()↓
◆”Ｗｅ　ｔｒｅａｔ　ｙｏｕｒ　ｐａｃｋａｇｅ　ｌｉｋｅ　ｉｔ　ｗａｓ　ｏｕｒ　ｏｎｌｙ　ｃｈｉｌｄ”．．．@KEY()↓
◆Ｉ’ｍ　ｈｅｒｅ　ｗｉｔｈ　ｙｏｕｒ　Ｐｅｎｃｉｌ　Ｅｒａｓｅｒ．
;◆エスカルゴうんそう↓
;　しっかりたっきゅうびん↓
;　でーっす！@KEY()↓
;◆「タコけしマシン」を↓
;　だいしきゅう↓
;　おとどけに　まいりましたー。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DELIVERY_TACO_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_KEY_TAKOKESHI)
@SE(SE_se76_my_give)
◆Ｈｅｒｅ　ｙｏｕ　ａｒｅ．@KEY()↓
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ！
;◆ハイ　たしかに。@WI(20)↓
;　ありやと　やんしたー。
@KEYNP()
@CLRF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@CLRF(FLG_GLOBAL_LOST_TAKOKESHI)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
』

_DELIVERY_TACO_ITEMFULL;
◆Ｙｏｕ’ｖｅ　ｒｅａｌｌｙ　ｇｏｔ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｈｏｐｅ　Ｉ　ｃａｎ　ｄｅｌｉｖｅｒ　ｔｈｉｓ　ｔｏ　ｙｏｕ　ｓｏｏｎ！
;◆あれ　にもつが↓
;　いっぱいですね。@WI(20)↓
;　じゃ　また　よろしく。
@KEY()
@CLOSEALL()
@CLRF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@GOSUB(MSG_SUB_DELIVERY_BYE)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
』
;--------------------------------

MSG_GLOBAL_DELIVERY_TAKA;
;遺失物配達
@OPEN(1)
◆Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆”Ｗｅ　ｔｒｅａｔ　ｙｏｕｒ　ｐａｃｋａｇｅ　ｌｉｋｅ　ｉｔ　ｗａｓ　ｏｕｒ　ｏｎｌｙ　ｃｈｉｌｄ”．．．@KEY()↓
◆Ｉ’ｍ　ｈｅｒｅ　ｔｏ　ｄｅｌｉｖｅｒ　ｔｈｅ　Ｈａｗｋ　Ｅｙｅ．
;◆エスカルゴうんそう↓
;　しっかりたっきゅうびん↓
;　でーっす！@KEY()↓
;◆「タカのめ」を↓
;　おとどけに　まいりましたー。
@KEY()↓
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_DELIVERY_TAKA_ITEMFULL)
@GOODSIN_PLAYER(0,GDS_TOOL_EAGLE_EYE)
@SE(SE_se76_my_give)
◆Ｈｅｒｅ　ｙｏｕ　ａｒｅ．@KEY()↓
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ！
;◆ハイ　たしかに。@WI(20)↓
;　ありやと　やんしたー。
@KEYNP()
@CLOSEALL()
@CLRF(FLG_DELIVERY_UNSOU_TAKANOME)
@CLRF(FLG_GLOBAL_LOST_TAKANOME)
@GOSUB(MSG_SUB_DELIVERY_BYE)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
』

_DELIVERY_TAKA_ITEMFULL;
◆Ｙｏｕ’ｖｅ　ｒｅａｌｌｙ　ｇｏｔ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｈｏｐｅ　Ｉ　ｃａｎ　ｄｅｌｉｖｅｒ　ｔｈｉｓ　ｔｏ　ｙｏｕ　ｓｏｏｎ！
;◆あれ　にもつが↓
;　いっぱいですね。@WI(20)↓
;　じゃ　また　よろしく。
@KEY()
@CLOSEALL()
@CLRF(FLG_DELIVERY_UNSOU_TAKANOME)
@GOSUB(MSG_SUB_DELIVERY_BYE)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
』
;-------------------------------------------------
MSG_TAKOKESHI_RETRY_OVER;＄
@CLRF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@CLRF(FLG_SYS_DISTLPT);テレポート許可
』

MSG_TAKANOME_RETRY_OVER;＄
@CLRF(FLG_DELIVERY_UNSOU_TAKANOME)
@CLRF(FLG_SYS_DISTLPT);テレポート許可
』
;-------------------------------------------------

MSG_GLOBAL_CHECK_HOMESICK;ホームシック検査
@GET_ORDER_PLAYER(1)
@SET_REG(0)
@EQ(PC_NESS)
@FALSE_GOTO(MSG_END)
@Q_SPECIAL(PC_NESS,6,2);ホームシック？
@FALSE_GOTO(MSG_END)
@GOSUB(MSG_SYS_RECOVER_HOMESICK);ホームシック状態回復のナレーション
』
;-------------------------------------------------

;仮設定

;`````````````````````````````````````````````````````````````````````````

;【回復グッズ・移動スピードが一定時間早くなるものについて・スキップサンド】

;配置場所：ツーソンデパート・パン売り場近く（並んでいる感じ）
;配置オブジェ：（女の子）

MSG_TWSN_SYSINFO_SKIP;
◆Ｙｕｍ　ｙｕｍ．．．ｍｍｍ．．．Ｉ’ｍ　ｅａｔｉｎｇ　ａ　ｓｋｉｐ　ｓａｎｄｗｉｃｈ．@KEY()↓
◆Ｉｔ　ｍａｋｅｓ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｔａｒｔ　ｓｋｉｐｐｉｎｇ！@KEY()↓
◆Ｉ　ｓａｗ　ｉｔ　ｏｎ　ａ　ＴＶ　ａｄ，　ａｎｄ　Ｉ　ｊｕｓｔ　ｈａｄ　ｔｏ　ｔｒｙ　ｏｎｅ．@KEY()↓
◆Ｉ’ｌｌ　ｂｅｔ　Ｉ　ｃａｎ　ｒｅａｌｌｙ　ｍｏｖｅ　ａｆｔｅｒ　ｅａｔｉｎｇ　ｔｈｉｓ．．．
;◆はしりだしたくなる　おいしさ！@WI(20)↓
;　すきすき　スキップサンド！@KEY()↓
;◆‥‥っていうコマーシャルに↓
;　のせられて　スキップサンドを↓
;　かいにきたのよ　わたし。@KEY()↓
;◆ほんとに　あしがはやくなったら↓
;　いいのにね。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【回復グッズ・ラッキーサンドについて】

;配置場所：オネット・パン屋（あるいはツーソン）
;配置オブジェ：（女性＆男性）

MSG_ONET_SYSINFO_LUCKY;
◆Ｉｔ　ｓｅｅｍｓ　ｌｉｋｅ　ｅｖｅｒｙ　ｂａｋｅｒｙ　ｈａｓ　ｂｅｅｎ　ｍａｋｉｎｇ　ｌｕｃｋｙ　ｓａｎｄｗｉｃｈｅｓ　ｔｈｅｓｅ　ｄａｙｓ．@KEY()↓
◆Ｔｈｅｙ’ｒｅ　ｋｉｎｄ　ｏｆ　ｌｉｋｅ　ｆｏｒｔｕｎｅ　ｃｏｏｋｉｅｓ，　ｅｘｃｅｐｔ　ｙｏｕ　ｃａｎ　ｗｉｎ　ｓｔｕｆｆ．@KEY()↓
◆Ｏｈ　ｙｅａｈ，　ａｎｄ　ｉｔ’ｓ　ａ　ｓａｎｄｗｉｃｈ．@KEY()↓
◆Ｏｋａｙ，　ｓｏ　ｍａｙｂｅ　ｉｔ’ｓ　ｎｏｔ　ｌｉｋｅ　ａ　ｆｏｒｔｕｎｅ　ｃｏｏｋｉｅ．@KEY()↓
◆Ａｎｙｗａｙ，　ｔｈｅ　ｂｅｓｔ　ｔｈｉｎｇ　ｔｈａｔ　ｃａｎ　ｈａｐｐｅｎ　ｉｓ　”ｒｅｃｏｖｅｒ　ＰＰ．”@KEY()↓
◆Ｉ　ｊｕｓｔ　ｗｉｓｈ　Ｉ　ｋｎｅｗ　ｗｈａｔ　”ＰＰ”　ｗａｓ．．．
;◆さいきん　どこのパンやでも↓
;　ラッキーサンドを↓
;　おいてるみたいだけど@KEY()↓
;◆あたりはずれのある↓
;　まるで　おみくじみたいな↓
;　サンドイッチなんだってね。@KEY()↓
;◆おおあたりが↓
;　「ＰＰ　かいふく」ってことだけど↓
;　「ＰＰ」って‥‥なに？？
@KEYNP()
』

;【たべものは基本的に値段の高いものほど良く回復する、と覚えておけば良いことの説明】

;配置場所：オネット・ハンバーガー屋
;配置オブジェ：（キャップ）

MSG_ONET_SYSINFO_PRICE;
;１２３４５６７８９０１２３４５６７８９
◆Ｄｏｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｙｏｕ　ｇｅｔ　ｍｏｒｅ　ｆｏｏｄ　ｖａｌｕｅ　ｏｕｔ　ｏｆ　１４　ｂｕｃｋｓ　ｗｏｒｔｈ　ｏｆ　ｂｕｒｇｅｒｓ@KEY()↓
◆ｔｈａｎ　８　ｂｕｃｋｓ　ｗｏｒｔｈ　ｏｆ　ｆｒｅｎｃｈ　ｆｒｉｅｓ？@KEY()↓
◆Ｙｏｕ’ｌｌ　ｆｅｅｌ　ｂｅｔｔｅｒ　ａｎｄ　ｍｏｒｅ　ｅｎｅｒｇｅｔｉｃ　ｉｆ　ｙｏｕ　ｅａｔ　ｂｅｔｔｅｒ　ｆｏｏｄｓ．@KEY()↓
◆Ｙｏｕ　ｋｎｏｗ－－ｙｏｕ’ｌｌ　ｒｅｃｏｖｅｒ　ｍｏｒｅ　ｈｅａｌｔｈ　ｉｆ　ｙｏｕ　ｅａｔ　ｍｏｒｅ　ｅｘｐｅｎｓｉｖｅ　ｆｏｏｄ．
;◆８ドルのポテトフライより↓
;　１４ドルのハンバーガーのほうが↓
;　たべたきに　なるわよね。@KEY()↓
;◆そのぶんだけ　たくさんげんきに↓
;　なるってことかな。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【すっきりハーブの説明】

;配置場所：ＨＰ村のドラッグストア
;配置オブジェ：（ビーナスの母）

MSG_HAPPY_SYSINFO_HERB;
◆Ｔｈｅ　ｉｎｆｏｒｍａｔｉｏｎ　ｏｎ　ｔｈｅ　ｂａｃｋ　ｏｆ　ｔｈｅ　”ｒｅｆｒｅｓｈｉｎｇ　ｈｅｒｂ”　ｒｅａｄｓ　ａｓ　ｆｏｌｌｏｗｓ：@KEY()↓
◆Ｉｆ　ｙｏｕ　ｃａｔｃｈ　ａ　ｃｏｌｄ，　ｉｆ　ｙｏｕ’ｒｅ　ｉｌｌ，　ｏｒ　ｉｆ　ｙｏｕ　ｃａｎ’ｔ　ｓｅｅｍ　ｔｏ　ｈｅａｌ，@KEY()↓
◆ｉｆ　ｙｏｕ’ｒｅ　ｐｏｉｓｏｎｅｄ，　ｉｆ　ｙｏｕ’ｒｅ　ｄｅｐｒｅｓｓｅｄ，　ａ　ｒｅｆｒｅｓｈｉｎｇ　ｈｅｒｂ　ｉｓ　ｔｈｅ　ｒｅａｌ　ｄｅａｌ．@KEY()↓
◆Ｉ　ｋｎｏｗ，　ｉｔ　ｓｅｅｍｓ　ｐｒｅｔｔｙ　ｉｆｆｙ，　ｂｕｔ　ｙｏｕ　ｓｈｏｕｌｄ　ｇｉｖｅ　ｉｔ　ａ　ｔｒｙ！
;◆すっきりハーブの↓
;　パッケージのうらに↓
;　こんなこと　かいてあるのよ‥‥@KEY()↓
;◆「かぜぎみの　あなた！@WI(20)↓
;　きぶんのわるい　あなたや↓
;　なみだがとまらない　あなた！@KEY()↓
;◆どくをくらっている　あなた！↓
;　そのほか　いろいろなあなた！↓
;　ぜひ　いちどおためしあれ」@KEY()↓
;◆そんなに「あなたあなた」って↓
;　どなられてもねぇ‥‥。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【うらカンポー＆いのちのつのぶえの説明】

;配置場所：土星谷のドラッグストア下の洞窟内
;配置オブジェ：（土星さん）

MSG_DOSEI_SYSMSG_COMEBACKITEM;＠
@FONTBAKA()
◆Ｓｏ　Ｂｏｉｎｇ！　　Ｙｏｕ　ｈａｖｅ　３８０　ｄｏｌｌａｒｓ，　ｗｅ　ｔｒａｄｅ　”@DSP_GOODS(GDS_TOOL_DIAMOND_CRASHER)．”
;◆３８０　どる　あったら↓		;どせいさん数字
;　うらカンポー↓
;　かえるのになー。
@KEY()↓
◆Ｓｏ　Ｂｏｉｎｇ！　　Ｙｏｕ　ｈａｖｅ　１７８０　ｄｏｌｌａｒｓ，　ｗｅ　ｔｒａｄｅ　”@DSP_GOODS(GDS_TOOL_LIFE_HORN)．”
;◆１７８０　どる　あったら↓		;どせいさん数字
;　いのちのつのぶえ↓
;　かえるのになー。
@KEYNP()
@FONTSTD()
』

;`````````````````````````````````````````````````````````````````````````

;【ぬいぐるみが魅力的なグッズであること】

;配置場所：ツーソン・デパート
;配置オブジェ：（ボロ）

MSG_TWSN_SYSMSG_NUIGURUMI;
◆Ｔｈａｔ　ｔｅｄｄｙ　ｂｅａｒ　ｔｈｅｙ　ｓｅｌｌ　ｏｖｅｒ　ｔｈｅｒｅ．．．Ｉ　ｈｅａｒｄ　ｉｔ　ｈｅｌｐｓ　ｉｎ　ｂａｔｔｌｅ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈａｔ　ｔｈｅｙ’ｒｅ　ｔａｌｋｉｎｇ　ａｂｏｕｔ．@KEY()↓
◆Ｉｔ’ｓ　ｊｕｓｔ　ａ　ｐｌａｉｎ　ｏｌ’　ｔｅｄｄｙ　ｂｅａｒ　ｔｏ　ｍｅ．．．

;◆そこで　うっている↓
;　ぬいぐるみ‥‥@KEY()↓
;◆「バトルにやくにたつ」って↓
;　わけのわからない　ことを↓
;　いわれたんだけど‥‥@KEY()↓
;◆かわいいだけじゃ　ないのかなぁ。@WI(20)↓
;　かってみようかなー。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【装備系グッズの装備時のドラムの点滅の説明】

;配置場所：オネットのドラッグストア
;配置オブジェ：（イヌ）

MSG_ONET_SYSMSG_EQUIP;
@CHKFGOTO(FLG_WIN_GIEGU,_ONET_SYSMSG_EQUIP_END)
◆Ｗｏｏｆ！　Ｗｏｏｆ！@KEY()↓
◆Ｉ’ｍ　Ｒｕｆｆｉｎｉ　ｔｈｅ　ｄｏｇ．@KEY()↓
◆Ｉ’ｍ　ｂｅｉｎｇ　ｐｏｓｓｅｓｓｅｄ　ｂｙ　ｔｈｅ　ｓｐｉｒｉｔ　ｏｆ　ｔｈｅ　ｇａｍｅ　ｄｅｓｉｇｎｅｒ．．．（ＲＵＦＦ！）@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｅｅ　ｔｈｅ　ｗｉｎｄｏｗ　ｓｈｏｗｉｎｇ　ＨＰ　ａｎｄ　ＰＰ　ａｔ　ｔｈｅ　ｂｏｔｔｏｍ　ｏｆ　ｔｈｅ　ｓｃｒｅｅｎ？@KEY()↓
◆Ｗｈｅｎ　ｙｏｕ　ｇｏ　ｔｏ　ａ　ｓｔｏｒｅ　ｔｈａｔ　ｈａｓ　ｅｑｕｉｐｐａｂｌｅ　ｉｔｅｍｓ，@KEY()↓
◆ｔｈｉｓ　ｗｉｎｄｏｗ　ｗｉｌｌ　ｅｉｔｈｅｒ　ｆｌａｓｈ，　ｌｏｏｋ　ｎｏｒｍａｌ　ｏｒ　ｂｅｃｏｍｅ　ｂｌａｃｋ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ａｒｅ　ａｌｌｏｗｅｄ　ｔｏ　ｅｑｕｉｐ　ａｎ　ｉｔｅｍ，　ａｎｄ　ｉｔ　ｉｓ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　ｙｏｕ　ｃｕｒｒｅｎｔ　ｉｔｅｍ，@KEY()↓
◆ｔｈｅ　ｗｉｎｄｏｗ　ｗｉｌｌ　ｆｌａｓｈ．@KEY()↓
◆Ｉｆ　ｔｈｅ　ｉｔｅｍ’ｓ　ｐｏｗｅｒ　ｉｓ　ｅｑｕａｌ　ｔｏ，　ｏｒ　ｌｅｓｓ　ｔｈａｎ　ｙｏｕ　ｃｕｒｒｅｎｔ　ｅｑｕｉｐｐｅｄ　ｉｔｅｍ，@KEY()↓
◆ｔｈｅ　ｗｉｎｄｏｗ　ｌｏｏｋｓ　ｎｏｒｍａｌ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｃａｎ’ｔ　ｅｑｕｉｐ　ａｎ　ｉｔｅｍ，　ｔｈｅ　ｗｉｎｄｏｗ　ｉｓ　ｂｌａｃｋ．@KEY()↓
◆＊Ｒｕｆｆ＊　　Ｉ　ｔｈｏｕｇｈｔ　ｙｏｕ’ｄ　ｌｉｋｅ　ｔｏ　ｋｎｏｗ．@KEY()↓
◆Ｎｏｗ　ｉｔ’ｓ　ｔｉｍｅ　ｔｏ　ｂｅｃｏｍｅ　ａ　ｒｅｇｕｌａｒ　ｄｏｇ　ａｇａｉｎ．．．）
;◆（う　う　わしは‥‥@WI(20)↓
;　イタコ・ドッグじゃ。@KEY()↓
;◆いま　あるゲームデザイナーの↓
;　れいが　ひょういしておる‥‥@WI(30)↓
;　ゴホン　ゴホン‥‥@KEY()↓
;◆「‥‥がめんの　したのほうに↓
;　ＨＰとか　ＰＰとか‥‥が↓
;　ひょうじされたパネルがあるだろ？@KEY()↓
;◆おみせで　そうびグッズを↓
;　かうときは‥‥そのパネルを↓
;　みるといいんだ。@KEY()↓
;◆そのグッズが↓
;　そうびできるときには‥‥↓
;　パネルが　あかるくなる。@KEY()↓
;◆そのグッズを　そうびして↓
;　パワーアップするときには↓
;　パネルは‥‥ピカピカする！@KEY()↓
;◆そうびできないばあいには‥‥↓
;　パネルは　くらくなる。@KEY()↓
;◆‥‥このことを　ぜひ↓
;　つたえておきたくてね‥‥」@KEY()↓
;◆ワワワワワン！！@KEY()↓
;◆ハッ　わしは‥‥いま↓
;　なにやら　わからぬことを↓
;　しゃべっておった。@KEY()↓
;◆もとのイヌに　もどろう）
@KEYNP()
』
_ONET_SYSMSG_EQUIP_END;＆
◆Ｗｏｏｆ！　Ｗｏｏｆ！@KEY()↓
◆Ｉ’ｍ　Ｒｕｆｆｉｎｉ　ｔｈｅ　ｄｏｇ．@KEY()↓
◆Ｈｅｒｅ　ｃｏｍｅｓ　ｔｈｅ　ｓｐｉｒｉｔ　ｏｆ　ｔｈｅ　ｇａｍｅ　ｄｅｓｉｇｎｅｒ　ａｇａｉｎ．．．@KEY()↓
◆Ｒｕｆｆ！@KEY()↓
◆Ｙｏｕ’ｒｅ　ｆｉｎａｌｌｙ　ａｌｍｏｓｔ　ｔｏ　ｔｈｅ　ｅｎｄ　ｏｆ　ｔｈｅ　ｇａｍｅ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｅｌｌ　ｍｅ　ｙｏｕｒ　ｃｏｍｅｎｔｓ　ｏｎ　ｔｈｉｓ　ｇａｍｅ，@KEY()↓
◆ｙｏｕ　ｍａｙ　ｗｒｉｔｅ　ｔｏ　ｍｅ　ｕｓｉｎｇ　Ｎｉｎｔｅｎｄｏ’ｓ　ａｄｄｒｅｓｓ　ｏｎ　ｔｈｅ　ｂｏｘ．@KEY()↓
◆Ｓｅｎｄ　ｙｏｕｒ　ｃｏｍｍｅｎｔｓ　ａｔｔｅｎｔｉｏｎ　ＥａｒｔｈＢｏｕｎｄ，　Ｒｕｆｆｉｎｉ　ｔｈｅ　ｄｏｇ．@KEY()↓
◆Ｎｏｗ，　ｇｅｔ　ｒｅａｄｙ　ｆｏｒ　ｔｈｅ　ｅｎｄｉｎｇ！@KEY()↓
◆Ｉｔ’ｓ　ａｌｌ　ｔｈａｔ’ｓ　ｌｅｆｔ．．．ｅｎｊｏｙ　ｉｔ！@KEY()↓
◆Ｂｏｗ　ｗｏｏｗ　ｗｏｗ！@KEY()↓
◆Ｗｅｌｌ，　Ｉ　ｔｏｌｄ　ｙｏｕ　ｓｏｍｅ　ｓｔｒａｎｇｅ　ｉｎｆｏ　ａｇａｉｎ．．．@KEY()↓
◆Ｉ’ｌｌ　ｇｏ　ｂａｃｋ　ｔｏ　ｂｅｉｎｇ　ａ　ｎｏｒｍａｌ　ｄｏｇ　ｎｏｗ．．．@KEY()↓
◆Ｗｏｏｆ！
;◆（う　う　わしは‥‥@WI(20)↓
;　イタコ・ドッグじゃ。@KEY()↓
;◆また‥‥あるゲームデザイナーの↓
;　れいが　ひょういしておる‥‥@WI(30)↓
;　ゴホン　ゴホン‥‥@KEY()↓
;◆「とうとうゲームしゅうりょうが↓
;　ちかづきましたね。@WI(20)↓
;　もし　よろしかったら‥‥@KEY()↓
;◆かんそうを　およせください。@KEY()↓
;◆パッケージに↓
;　じゅうしょのかいてある↓
;　にんてんどう　の@KEY()↓
;◆マザー２　イタコ・ドッグがかりに↓
;　おくってくださいね。@KEY()↓
;◆さあ　あとはエンディングを↓
;　みるばかりですね。@WI(20)↓
;　ごゆっくり　おたのしみください」@KEY()↓
;◆ワワワワワン！！@KEY()↓
;◆ハッ　わしは‥‥いま↓
;　なにやら　わからぬことを↓
;　しゃべっておった。@KEY()↓
;◆もとのイヌに　もどろう）
@KEYNP()
』
;◆（おみせで　そうびグッズを↓
;　かうときには　ＨＰメーターに↓
;　ちゅうもくすると　いい。@KEY()↓
;◆そのグッズが　そうびできて↓
;　なおかつ　そうびしたことで↓
;　いまよりパワーアップするばあい@KEY()↓
;◆メーターのわくがピカピカする。@KEY()↓
;◆また　そうびできないばあいは↓
;　メーターぜんたいが　くらくなる。@KEY()↓
;◆‥‥どうぶつのぼくには↓
;　むずかしめのセリフを↓
;　しゃべってみました）@KEYNP()
;』

;`````````````````````````````````````````````````````````````````````````

;【復活後はＰＰが０になっていることの説明】

;配置場所：図書館の客
;配置オブジェ：（ＯＬ＿Ｆ）

MSG_LIBRARY_SYSMSG_PP_0;
◆Ｉ’ｍ　ｃｒａｍｍｉｎｇ　ｆｏｒ　ｔｈｅ　ｂｉｇ　ｔｅｓｔ　ｔｏｍｏｒｒｏｗ．@KEY()↓
◆Ｉｔ’ｓ　ａｂｏｕｔ　ｇａｍｅｓ．@KEY()↓
◆”Ｈｏｔｅｌ　Ｒｕｌｅ”．．．ｉｆ　ｙｏｕ　ｓｔａｙ　ａｔ　ａ　ｈｏｔｅｌ，　ｙｏｕ’ｌｌ　ｗａｋｅ　ｕｐ　ｗｉｔｈ　ｆｕｌｌ　ＨＰ　ａｎｄ　ＰＰ．@KEY()↓
◆”Ｌｉｆｅ　Ｒｅｃｏｖｅｒｙ　Ｒｕｌｅ”@KEY()↓
◆．．．ｒｅｃｏｖｅｒｉｎｇ　ｙｏｕｒ　ｌｉｆｅ　ｗｉｌｌ　ｇｉｖｅ　ｙｏｕ　ｆｕｌｌ　ＨＰ，　ｂｕｔ　ｚｅｒｏ　ＰＰ．@KEY()↓
◆．．．Ｈｍｍｍ．．．Ｉ　ｂｅｔ　ｔｈｉｓ　ｓｔｕｆｆ　ｗｉｌｌ　ｂｅ　ｏｎ　ｔｈｅ　ｔｅｓｔ．．．
;◆あした　ゲームのしけんがあって↓
;　いっしょけんめい↓
;　あんきしている　ところなの。@KEY()↓
;◆「ホテルのほうそく」↓
;　‥‥ホテルだいを　はらえば↓
;　ＨＰ　ＰＰともにまんたんである。@KEY()↓
;◆「カムバックのほうそく」↓
;　‥‥カムバックは　むりょうだが↓
;　ＰＰは０である。@KEY()↓
;◆‥‥うーん　カムバックの　あと↓
;　ＰＰが０　ってところが↓
;　しけんにでそうね。
@KEYNP()
』
;`````````````````````````````````````````````````````````````````````````

;【ＣＤ設置場所の説明】

;配置場所：図書館の客
;配置オブジェ：（少年Ａ）

MSG_LIBRARY_SYSMSG_CD_PLACE;
◆Ｉ　ｒｅｃｅｎｔｌｙ　ｒｅａｄ　ａ　ｂｏｏｋ　ｔｉｔｌｅｄ　”Ｏｕｒ　Ｃｏｎｖｅｎｉｅｎｔ　Ｓｏｃｉｅｔｙ．”@KEY()↓
◆Ｉｔ　ｓａｉｄ　ｔｈａｔ　ｏｕｒ　ｍｏｄｅｒｎ　ｓｏｃｉｅｔｙ　ｄｅｍａｎｄｓ@KEY()↓
◆ｔｈａｔ　ｔｈｅｒｅ　ａｌｗａｙｓ　ｂｅ　ａｎ　ＡＴＭ　ｉｎ　ｈｏｔｅｌｓ　ａｎｄ　ｄｒｕｇｓｔｏｒｅｓ．@KEY()↓
◆Ｊｕｓｔ　ｋｎｏｗｉｎｇ　ｔｈａｔ　ｉｓ　ｃｏｎｖｅｎｉｅｎｔ！@KEY()↓
◆Ｉ’ｍ　ｇｌａｄ　Ｉ　ｒｅａｄ　ｔｈａｔ．．．@KEY()↓
◆Ｉ　ｃａｎ’ｔ　ｂｅｌｉｅｖｅ　Ｉ　ｄｉｄｎ’ｔ　ｋｎｏｗ　ｔｈａｔ．@KEY()↓
◆Ｉ’ｌｌ　ｃｈｅｃｋ　ｗｈｅｔｈｅｒ　ｏｒ　ｎｏｔ　ｗｅ　ｈａｖｅ　ａｎ　ＡＴＭ　ｉｎ　ｏｕｒ　ｄｒｕｇｓｔｏｒｅ．．．
;◆「べんりなよのなか」って↓
;　ほんを　よんでたんだけど@KEY()↓
;◆ホテルや　ドラッグストアには↓
;　キャッシュディスペンサーが↓
;　かならず　あるんだって‥‥。@KEY()↓
;◆こういうことを　しっておくと↓
;　いろいろと　べんりだよね。@WI(15)↓
;　よんで　よかったよ　このほん。@KEY()↓
;◆ぼく　かんどうしちゃったなぁ。@WI(20)↓
;　こんどドラッグストアにいったら↓
;　しらべてみよっと。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【電話の説明】

;配置場所：図書館の客
;配置オブジェ：（少女Ａ差し替え）

MSG_LIBRARY_SYSMSG_TEL_PLACE;
◆Ｉ　ｒｅａｄ　ｔｈｅ　ｂｏｏｋ　ｃａｌｌｅｄ　”Ｏｕｒ　Ｓｏｃｉｅｔｙ　ｉｓ　Ｃｏｎｖｅｎｉｅｎｔ．”@KEY()↓
◆Ｉｔ　ｓａｉｄ　ｔｈａｔ　ｔｈｅｓｅ　ｄａｙｓ，　ｔｈｅｒｅ　ａｒｅ　ａｌｗａｙｓ　ｔｅｌｅｐｈｏｎｅｓ　ｉｎ　ｈｏｔｅｌｓ　ａｎｄ　ｄｒｕｇｓｔｏｒｅｓ．@KEY()↓
◆Ｉ　ａｌｓｏ　ｌｅａｒｎｅｄ　ｔｈａｔ　ｔｏ　ｕｓｅ　ａ　ｇｒｅｅｎ　ｐａｙ　ｐｈｏｎｅ　ｃｏｓｔｓ　ａ　ｄｏｌｌａｒ，@KEY()↓
◆ｗｈｉｌｅ　ｔｈｅ　ｂｌａｃｋ　ｐｈｏｎｅｓ　ａｒｅ　ｆｒｅｅ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗｅｒｅｎ’ｔ　ａｗａｒｅ　ｏｆ　ｔｈｉｓ，@KEY()↓
◆ａｌｌ　ｙｏｕｒ　ｍｏｎｅｙ　ｃｏｕｌｄ　ｇｅｔ　ｅａｔｅｎ　ｕｐ　ｂｙ　ｙｏｕｒ　ｐｈｏｎｅ　ｃａｌｌｓ．@KEY()↓
◆Ｉ’ｍ　ｇｌａｄ　Ｉ　ｒｅａｄ　ｔｈａｔ　ｂｏｏｋ．．．
;◆「よのなかのべんり」って↓
;　ごほんを　よんでたの。@KEY()↓
;◆ホテルや　ドラッグストアには↓
;　でんわが　かならずあるって↓
;　かいてあったわ。@KEY()↓
;◆それに　みどりいろの↓
;　こうしゅうでんわは↓
;　１ドルかかるけど@KEY()↓
;◆そのほかの　くろでんわとかは↓
;　おかねが　かからないって。@KEY()↓
;◆このことを　しらなかったら↓
;　みどりいろの　こうしゅうでんわを↓
;　かけまくって‥‥@KEY()↓
;◆おおぞんしてたかも↓
;　しれないわよね。@WI(20)↓
;　‥‥よんで　よかったぁ。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【マジックバタフライの説明】

;配置場所：図書館の２階窓際の客
;配置オブジェ：（サラリーマンＤ）

MSG_LIBRARY_SYSMSG_BUTTERFLY;
◆Ｉ　ｃａｎ’ｔ　ｂｅｌｉｅｖｅ　Ｉ　ｓａｗ　ｉｔ　ｗｉｔｈ　ｍｙ　ｏｗｎ　ｅｙｅｓ．@KEY()↓
◆Ｉ　ｗａｓ　ｓｔａｒｉｎｇ　ｏｕｔ　ｔｈｅ　ｗｉｎｄｏｗ　ａｎｄ　ｔｈｅｒｅ　ｉｔ　ｗａｓ，　ｊｕｓｔ　ｆｌｕｔｔｅｒｉｎｇ　ｔｈｅｒｅ．．．@KEY()↓
◆Ｉ’ｄ　ｏｎｌｙ　ｓｅｅｎ　ｉｔ　ｉｎ　ｔｈｅ　ｅｎｃｙｃｌｏｐｅｄｉａ　ｂｅｆｏｒｅ．@KEY()↓
◆Ｗｈａｔ　ｗａｓ　ｉｔ？@KEY()↓
◆Ａ　ｍａｇｉｃ　ｂｕｔｔｅｒｆｌｙ！@KEY()↓
◆Ｉｆ　ｙｏｕ　ｇｅｔ　ｃｌｏｓｅ　ｔｏ　ａ　Ｍａｇｉｃ　Ｂｕｔｔｅｒｆｌｙ，　ａｌｌ　ｙｏｕｒ　ｃａｒｅｓ　ｆｌｙ　ａｗａｙ，@KEY()↓
◆ｊｕｓｔ　ｌｉｋｅ　ａ　ｆｌｕｔｔｅｒｉｎｇ　ｂｕｔｔｅｒｆｌｙ．@KEY()↓
◆Ｙｅｐ，　ｙｅｐ！@KEY()↓
◆Ｔｈａｔ’ｓ　ｔｈｅ　ｅｆｆｅｃｔ　ｏｆ　ｔｈｅ　ｌｅｇｅｎｄａｒｙ　ｍａｇｉｃ　ｂｕｔｔｅｒｆｌｙ．@KEY()↓
◆Ｉ　ｌｏｖｅ　ｔａｌｋｉｎｇ　ａｂｏｕｔ　ｉｔ！@KEY()↓
◆Ｏｏｏｐｓ！@KEY()↓
◆Ｓｏｒｒｙ　ａｂｏｕｔ　ｔｈｅ　ｏｕｔｂｕｒｓｔ．．．@KEY()↓
◆Ｉ　ｇｏｔ　ｃａｒｒｉｅｄ　ａｗａｙ　ｗｉｔｈ　ａｌｌ　ｔｈｅ　ｔａｌｋ　ａｂｏｕｔ　ｌｏｖｅｌｙ　ｂｕｔｔｅｒｆｌｉｅｓ．．．
;◆ぼくは　このめで　みた！@KEY()↓
;◆まどから　なにげなく↓
;　そとを　ながめていたら↓
;　ひらひら　とんでいたんだ！@KEY()↓
;◆ずかんでしか　みたことなかった↓
;　あの　マジックバタフライが！@KEY()↓
;◆ちかづいたものに↓
;;ちょいと変更/上野;OK!
;;　ひらひらと　サイコパワーを↓
;　ひらひらと　やすらぎを↓
;　あたえてくれる‥‥@KEY()↓
;◆あの　まぼろしの↓
;　ちょうちょのことだよ！@KEY()↓
;◆‥‥あ@WI(15)　すいません。@WI(30)↓
;　としょかんで　さわいじゃって。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【敵との接触の向きによって有利不利があることの説明（緑色と赤色の意味）】

;配置場所：オネット
;配置オブジェ：現状のホリー（現状のセリフはツーソン入ってスグのホリーに移植）

MSG_ONET_SYSMSG_ENCOUNTER;
◆（Ｉ　ａｍ　ｎｏｔ　ｙｏｕｒ　ｅｎｅｍｙ．@KEY()↓
◆Ｉ　ａｍ　ｓｉｍｐｌｙ　ｙｏｕｒ　ａｖｅｒａｇｅ　ｒｕｎ－ｏｆ－ｔｈｅ－ｍｉｌｌ　ｍｏｌｅ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｓｏｍｅ　ｈｉｎｔｓ　ｏｎ　ｆｉｇｈｔｉｎｇ　ｅｎｅｍｉｅｓ？）↓
<Ｙｅｓ>
<Ｎｏ>
;◆（おれは　てきじゃない。↓
;　ただの　もぐらさ。@KEY()↓
;◆てきと　たたかうときの↓
;　コツを　おしえようか？↓
;　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_SYSMSG_ENCOUNTER_YES,_SYSMSG_ENCOUNTER_NO)
_SYSMSG_ENCOUNTER_NO;
◆Ａｈ，　Ｉ　ｓｅｅ．．．@KEY()↓
◆Ｙｏｕ’ｖｅ　ａｌｒｅａｄｙ　ｇｏｔ　ａ　ｇｏｏｄ　ｇｒａｓｐ　ｏｆ　ｈｏｗ　ｔｏ　ｆｉｇｈｔ　ｅｆｆｅｃｔｉｖｅｌｙ．
;◆（なるほど。@WI(20)↓
;　きみはもう　たたかいのコツを↓
;　つかんでいるんだね）
@KEYNP()
』
_SYSMSG_ENCOUNTER_YES;
◆Ｌｉｓｔｅｎ　ｃａｒｅｆｕｌｌｙ．@KEY()↓
◆Ｍｙ　ｈｉｎｔ　ｉｎｖｏｌｖｅｓ　ｗｈｉｃｈ　ｗａｙ　ｙｏｕ　ａｒｅ　ｆａｃｉｎｇ　ｗｈｅｎ　ａ　ｂａｔｔｌｅ　ｗｉｔｈ　ａｎ　ｅｎｅｍｙ　ｏｃｃｕｒｓ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ａｌｌｏｗ　ｅｎｅｍｉｅｓ　ｔｏ　ａｐｐｒｏａｃｈ　ｙｏｕ　ｆｒｏｍ　ｙｏｕｒ　ｂａｃｋ　ｏｒ　ｓｉｄｅ，@KEY()↓
◆ｔｈｅｙ　ｇｅｔ　ａ　ｓｕｒｐｒｉｓｅ　ｏｐｅｎｉｎｇ　ａｔｔａｃｋ．@KEY()↓
◆Ｗｈｅｎ　ｔｈｅｙ　ａｐｐｒｏａｃｈ　ｙｏｕ　ｔｈｉｓ　ｗａｙ，　ｙｏｕｒ　ＴＶ　ｓｃｒｅｅｎ，　ｎｏ．．．ｎｏ．．．@KEY()↓
◆Ｉ　ｍｅａｎ　ｔｈｅ　ｗｏｒｌｄ　ｉｎ　ｆｒｏｎｔ　ｏｆ　ｙｏｕ　ｗｉｌｌ　ｓｈｏｗ　ａ　ｒｅｄ　ｓｗｉｒｌ　ｆｏｒ　ａ　ｓｅｃｏｎｄ．@KEY()↓
◆Ｏｎ　ｔｈｅ　ｏｔｈｅｒ　ｈａｎｄ，　ｉｆ　ｙｏｕ　ａｐｐｒｏａｃｈ　ａｎ　ｅｎｅｍｙ　ｆｒｏｍ　ｔｈｅ　ｂａｃｋ　ｏｒ　ｓｉｄｅ，@KEY()↓
◆ｙｏｕ　ｇｅｔ　ａ　ｓｕｒｐｒｉｓｅ　ｏｐｅｎｉｎｇ　ａｔｔａｃｋ．@KEY()↓
◆Ｉｎ　ｔｈａｔ　ｃａｓｅ，　ｙｏｕｒ　ＴＶ．．．Ｏｏｐｓ　ａｇａｉｎ！@KEY()↓
◆．．．Ｔｈｅ　ｗｏｒｌｄ　ｉｎ　ｆｒｏｎｔ　ｏｆ　ｙｏｕ　ｓｈｏｗｓ　ａ　ｇｒｅｅｎ　ｓｗｉｒｌ．@KEY()↓
◆Ｔｈｅ　ｐｏｉｎｔ　ｉｓ，　ｔｒｙ　ｔｏ　ｆｉｇｈｔ　ｓｏ　ｔｈａｔ　ｙｏｕ　ａｌｗａｙｓ　ｈａｖｅ　ｔｈｅ　ａｄｖａｎｔａｇｅ．
;◆（いいかい？　ポイントは↓
;　たたかいに　はいるまえの↓
;　からだのむきだ。@KEY()↓
;◆じぶんのせなかや　よこを↓
;　てきにタッチされると@KEY()↓
;◆せんせいこうげきを↓
;　ゆるすことになる。@KEY()↓
;◆そういうときは　テレビがめんが↓
;　‥‥あ　いやいや　めのまえが↓
;　いっしゅんあかく　なるはずだ。@KEY()↓
;◆ぎゃくに↓
;　てきのせなかや　よこを↓
;　うまく　タッチすれば@KEY()↓
;◆かならず　こちらが↓
;　せんせいこうげき　できる。@KEY()↓
;◆そんなときは　テレビがめんが↓
;　‥‥あ　いやいや　めのまえが↓
;　みどりいろに　なるからね。@KEY()↓
;◆ま　ようするに‥‥↓
;　まえむきに↓
;　たたかおうってことさ）
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【レベル差がついたときの無条件勝ちの説明】

;配置場所：ＨＰ村入ってすぐ
;配置オブジェ：ホリー

MSG_HAPPY_SYSMSG_EASY_BATTLE;
◆Ｉ　ａｍ　ｎｏｔ　ｙｏｕｒ　ｅｎｅｍｙ．@KEY()↓
◆Ｉ　ａｍ　ｊｕｓｔ　ａ　ｐｌａｉｎ　ｏｌ’　ｍｏｌｅ．@KEY()↓
◆Ｙｏｕ　ａｒｅ　ｃｅｒｔａｉｎｌｙ　ｓｔｒｏｎｇｅｒ　ｔｈａｎ　ｙｏｕ　ｗｅｒｅ　ｗｈｉｌｅ　ｗａｎｄｅｒｉｎｇ　ａｒｏｕｎｄ　Ｏｎｅｔｔ．@KEY()↓
◆Ｈａｖｅ　ｙｏｕ　ｅｖｅｒ　ｓｕｄｄｅｎｌｙ　ｇｏｔｔｅｎ　ｔｈｅ　”Ｙｏｕ　Ｗｏｎ”　ｍｅｓｓａｇｅ@KEY()↓
◆ｗｈｅｎ　ｙｏｕ　ｍｅｔ　ａ　ｗｅａｋ　ｅｎｅｍｙ？@KEY()↓
◆Ｔｈａｔ’ｓ　ｓｕｒｅ－ｆｉｒｅ　ｐｒｏｏｆ　ｔｈａｔ　ｙｏｕ’ｖｅ　ｂｅｃｏｍｅ　ｓｔｒｏｎｇｅｒ．@KEY()↓
◆Ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｗａｓｔｅ　ｙｏｕｒ　ｔｉｍｅ　ｆｉｇｈｔｉｎｇ　ｗｉｍｐｙ　ｅｎｅｍｉｅｓ，　ｄｏ　ｙｏｕ？
;◆（おれは　てきじゃない。↓
;　ただの　もぐらさ。@KEY()↓
;◆おまえ　オネットをうろうろ↓
;　してたときにくらべて↓
;　ずいぶん　つよくなっただろ。@KEY()↓
;◆よわい　てきにあったとき↓
;　いきなり　ＹＯＵ　ＷＩＮって↓
;　ふんいきに　なったことないか？@KEY()↓
;◆それは　おまえがつよくなった↓
;　なによりのしょうこなんだぜ。@KEY()↓
;◆あまりに　よわい　ザコと↓
;　かったるく　たたかってなんて↓
;　いられないだろ？！）
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【ヒーラーと医者の違いの説明】

;配置場所：オネット病院
;配置オブジェ：ボルヘスママ

MSG_ONET_SYSMSG_HEALER;
◆Ｈｅｌｌｏ．．．ａｎｄ　ｙｏｕ　ａｒｅ．．．？@KEY()↓
◆Ｓａｙ，　ｈａｖｅ　ｙｏｕ　ｅｖｅｒ　ｓｕｆｆｅｒｅｄ　ｆｒｏｍ　ｓｏｍｅ　ｔｙｐｅ　ｏｆ　ｓｉｃｋｎｅｓｓ　ｏｒ　ｃｏｎｄｉｔｉｏｎ@KEY()↓
◆ｔｈａｔ　ｙｏｕ　ｃｏｕｌｄｎ’ｔ　ｇｅｔ　ｃｕｒｅｄ　ａｔ　ａ　ｈｏｓｐｉｔａｌ？@KEY()↓
◆Ｆｏｒ　ｅｘａｍｐｌｅ，　ｂｅｉｎｇ　”Ｄｉａｍｏｎｄｉｚｅｄ，”　ｗｈｅｒｅ　ｙｏｕｒ　ｈｅａｄ　ｇｅｔｓ　ａｓ　ｈａｒｄ　ａｓ　ａ　ｄｉａｍｏｎｄ．．．@KEY()↓
◆Ｏｒ．．．　”Ｍｕｓｈｒｏｏｍｉｚｅｄ，”　ｗｈｅｒｅ　ｙｏｕ　ｈａｖｅ　ａ　ｍｕｓｈｒｏｏｍ　ｏｎ　ｙｏｕｒ　ｈｅａｄ．．．@KEY()↓
◆Ｉｆ　ｙｏｕ’ｒｅ　ｅｖｅｒ　ｓｔｕｃｋ　ｗｉｔｈ　ｔｈｅｓｅ　ｔｙｐｅｓ　ｏｆ　ｅｍｂａｒｒａｓｓｉｎｇ　ｃｏｎｄｉｔｉｏｎｓ，@KEY()↓
◆ｗｅ　ｏｆ　ｔｈｅ　ｍａｇｉｃ　ｈｅａｌｉｎｇ　ｓｈｒｉｎｅ　ａｒｅ　ｈｅｒｅ　ｔｏ　ｅａｓｅ　ｙｏｕｒ　ｐａｉｎ．@KEY()↓
◆Ｗｅ’ｒｅ　ｒｅａｄｙ　ａｎｄ　ｗａｉｔｉｎｇ．．．@KEY()↓
◆ｉｎ　ｔｈｅ　ｌｏｂｂｙ　ｏｆ　ｈｏｓｐｉｔａｌｓ　ａｌｌ　ｏｖｅｒ　ｔｈｅ　ｗｏｒｌｄ．@KEY()↓
◆Ｔｈｅ　ｐｅｒｓｏｎ　ｎｅｘｔ　ｔｏ　ｍｅ　ｉｓ　ｔｈｅ　ｇｒｅａｔ　ｔｅａｃｈｅｒ　ｏｆ　ｍａｇｉｃ　ｈｅａｌｉｎｇ．
;◆もしもし　あなたは‥‥@KEY()↓
;◆びょういんで　なおせない↓
;　さまざまな　おなやみを↓
;　かかえては　おられませんか？@KEY()↓
;◆たとえば　ダイヤみたいに↓
;　かたくなっちゃったとか‥‥@KEY()↓
;◆たとえば！@WI(20)　あたまにキノコが↓
;　はえちゃったとか‥‥@KEY()↓
;◆そういう　ハズカシイなやみを↓
;　おもちの　かたがたに@KEY()↓
;◆わたくしども↓
;　マジックヒーリングきょうかいは↓
;　あいのてを　さしのべています。@KEY()↓
;◆ぜんこくの　びょういんの↓
;　かたすみで　あなたを↓
;　おまちしておりますわ。@KEY()↓
;◆わたくしの　となりが↓
;　マジックヒーラーの↓
;　だいせんせいです。
@KEYNP()
』

;◆わたし　となりにいるおじさんに
;　おいしゃさまでは
;　なおせない　ことを‥‥
;◆いろいろ　なおしてもらってるの。
;　‥‥いやーねぇ！
;　こいのやまい　じゃないわよ。
;』

;◆おおきなこえじゃ↓
;　いえないけどね‥‥@KEY()↓
;◆わたしの　となりにいるひと↓
;　ヒーラーなのよ。@KEY()↓
;◆ヒーローじゃないわよ↓
;　ヒーラーよ！@KEY()↓
;◆なにも　びょういんで↓
;　しょうばいしなくっても↓
;　いいとおもうけど@KEY()↓
;◆でも　@WI(15)びょういんにくれば↓
;　なんでも　なおるんだから↓
;　べんりはべんりだわよねえ。@KEYNP()
;』

;`````````````````````````````````````````````````````````````````````````

;【プーにのみ効果的・非効果的なグッズがあることの説明】

;配置場所：ランマのショップ
;配置オブジェ：（女）

MSG_RAMA_SYSMSG_PU_ITEM;
◆Ｉ　ｗｉｓｈ　Ｉ　ｃｏｕｌｄ　ｒｅｃｏｖｅｒ　ｍｙ　ＰＰ　ｊｕｓｔ　ｂｙ　ｄｒｉｎｋｉｎｇ　ｗａｔｅｒ．．．@KEY()↓
◆Ｅｖｅｎ　ｔｈｏｕｇｈ　Ｉ　ｈａｖｅ　ｎｅｖｅｒ　ｓｅｅｎ　ｈｉｍ　ｂｅｆｏｒｅ，　Ｉ　ｈｅａｒｄ　ｔｈａｔ　ｔｈｅ　ｐｒｉｎｃｅ　ｃａｎ　ｄｏ　ｔｈａｔ．
◆Ｉ　ｇｕｅｓｓ　Ｉ　ｎｅｅｄ　ｍｏｒｅ　ｔｒａｉｎｉｎｇ．．．@KEY()↓
◆Ｂｙ　ｔｈｅ　ｗａｙ，　ｊｕｓｔ　ｗｈａｔ　ｉｓ　ＰＰ　ａｎｙｗａｙ？．．．
;◆わたしも　しゅぎょうをつんで↓
;　@DSP_STS(STS_PC_NAME_POO)おうじさまのように‥‥@KEY()↓
;◆「みず」をのむだけで↓
;　ＰＰをかいふくできるように↓
;　なりたいと　おもっています。@KEY()↓
;◆それはともかく↓
;　ぴいぴいって‥‥@WI(40)なにかしら？？
@KEYNP()
』
;◆わたしも　しゅぎょうをつんで↓
;　みずだけで　いきられるように↓
;　なりたいと　おもっています。@KEY()↓
;◆@DSP_STS(STS_PC_NAME_POO)おうじさまのように。@KEYNP()
;』

;`````````````````````````````````````````````````````````````````````````

;【ふりかけシステムの説明】

;配置場所：ヌスット広場のふりかけ屋（ふりかけ屋のお兄さんと向き合う）
;配置オブジェ：（女）

MSG_TWSN_SYSMSG_FURIKAKE;
◆Ｉ　ｃａｍｅ　ｔｏ　ｂｕｙ　ｃｏｎｄｉｍｅｎｔｓ．．．@KEY()↓
◆Ｉ　ｗｏｎｄｅｒ　ｗｈａｔ　ｗｏｕｌｄ　ｂｅ　ｇｏｏｄ．．．@KEY()↓
◆Ｔｈｅ　ｒｉｇｈｔ　ｃｏｎｄｉｍｅｎｔ　ｍａｋｅｓ　ａ　ｄｉｓｈ　ｔａｓｔｅ　ｂｅｔｔｅｒ，@KEY()↓
◆ｗｈｉｌｅ　ｔｈｅ　ｗｒｏｎｇ　ｏｎｅ　ｍａｋｅｓ　ｉｔ　ｔａｓｔｅ　ｗｏｒｓｅ．@KEY()↓
◆Ｉｆ　ｔｈｅ　ｃｏｎｄｉｍｅｎｔ　ｍａｔｃｈｅｓ　ｔｈｅ　ｆｏｏｄ，@KEY()↓
◆ｙｏｕ　ｗｉｌｌ　ｇｅｔ　ｍｏｒｅ　ｐｏｗｅｒ　ｔｈａｎ　ｉｆ　ｙｏｕ　ａｔｅ　ｔｈｅ　ｆｏｏｄ　ｉｔｅｍ　ｐｌａｉｎ．
;◆あじつけ　こもの↓
;　かいにきたんだけど↓
;　なににしようか　まよっちゃう。@KEY()↓
;◆こんだてによって　ふりかけて↓
;　おいしいものと↓
;　おいしくないものがあって@KEY()↓
;◆ふりかけの　くみあわせが↓
;　うまくいくと@KEY()↓
;◆おなじたべものでも↓
;　グンと　パワーがアップするのよ。
@KEYNP()
』

;`````````````````````````````````````````````````````````````````````````

;【あなぬけねずみの説明】

;配置場所：オネットの穴抜けねずみの家
;配置オブジェ：（ボロ）

MSG_ONET_SYSMSG_ESCAPE_MOUSE;
◆Ｉ　ｌｉｖｅ　ｒｅｎｔ－ｆｒｅｅ　ｉｎ　ｔｈｅ　ｍｏｕｓｅ’ｓ　ｈｏｕｓｅ．@KEY()↓
◆Ｔｈｅ　ｍｉｃｅ　ａｒｅ　ｋｎｏｗｎ　ａｓ　”Ｅｘｉｔ　Ｍｉｃｅ．”@KEY()↓
◆Ｔｈｅｙ　ａｒｅ　ｖｅｒｙ　ｋｉｎｄ，　ａｎｄ　ｂｏｙ　ａｒｅ　ｔｈｅｙ　ｆａｓｔ！@KEY()↓
◆Ｉ　ｒｅａｌｌｙ　ｌｏｖｅ　ｔｈｅｓｅ　ｇｕｙｓ！
;◆ネズミのいえに↓
;　いそうろうさせて↓
;　もらってるんだ　おれ。@KEY()↓
;◆しんせつなかれらは↓
;　「あなぬけネズミ」っていう↓
;　しゅるいなんだ。@KEY()↓
;◆とにかく　しんせつで↓
;　すばしこくて↓
;　さいこうの　ともだちさ！
@KEYNP()
』
;-------------------------------------------------

;【ホームシックの説明２】追加

;配置場所：ツーソンバスステーション電話のそば
;配置オブジェ：（ツッパリ）


MSG_TWSN_SYSINFO_HOMESICK;
◆Ｉ　ａｌｗａｙｓ　ｆｅｅｌ　ｍｕｃｈ　ｂｅｔｔｅｒ　ａｆｔｅｒ　ｈｅａｒｉｎｇ　ｍｙ　ｍｏｍ’ｓ　ｖｏｉｃｅ　ｏｖｅｒ　ｔｈｅ　ｐｈｏｎｅ．@KEY()↓
◆Ｉ　ｗａｓ　ｒｅａｌｌｙ　ｈｏｍｅｓｉｃｋ　ｒｅｃｅｎｔｌｙ，　ａｎｄ　ｍｙ　ｍｏｍ　ｃｈｅｅｒｅｄ　ｍｅ　ｒｉｇｈｔ　ｕｐ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｃａｌｌ　ｙｏｕｒ　ｍｏｍ　ｓｏｍｅｔｉｍｅ．@KEY()↓
◆Ｂｅｌｉｅｖｅ　ｍｅ，　ｔｈｏｓｅ　ｍｅｌａｎｃｈｏｌｙ　ｆｅｅｌｉｎｇｓ　ｗｉｌｌ　ｂｅ　ｇｏｎｅ　ｂｅｆｏｒｅ　ｙｏｕ　ｋｎｏｗ　ｉｔ．
;◆でんわの　おふくろのこえ@WI(20)↓
;　げんきで　あんしんしたなあ。@KEY()↓
;◆このところ　おれ↓
;　ホームシックぎみだったけど@KEY()↓
;◆ぎゃくに　おふくろに↓
;　げんきづけられちゃったよ。@KEY()↓
;◆おまえも　たまには↓
;　でんわでも　してみろよ。@WI(20)↓
;　さみしさなんて　ぶっとぶぜ！
@KEYNP()
』
;　げんきでるぜ　おたがい。@KEYNP()
;』

;```````````````````````````````````````````````````````````````````
;【ガラクタと修理の関係のヒント】追加

;配置場所：ツーソン・猫しかいない家
;配置オブジェ：（男）


MSG_TWSN_SYSINFO_REPAIR;
◆Ｉ　ｈａｖｅ　ａ　ｌｏｔ　ｏｆ　ｏｌｄ，　ｂｒｏｋｅｎ　ｊｕｎｋ，　ｂｕｔ　Ｉ　ｈａｔｅ　ｔｏ　ｔｈｒｏｗ　ａｎｙｔｈｉｎｇ　ａｗａｙ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｈａｖｅ　ａ　ｆｒｉｅｎｄ　ｗｈｏ　ｉｓ　ｋｎｏｗｌｅｄｇｅａｂｌｅ　ａｂｏｕｔ　ｍｅｃｈａｎｉｃｓ，@KEY()↓
◆ｔｈａｔ　ｐｅｒｓｏｎ　ｍｉｇｈｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｆｉｘ　ｓｏｍｅｔｈｉｎｇ　ｆｏｒ　ｙｏｕ　ｏｖｅｒｎｉｇｈｔ．．．@KEY()↓
◆Ｍａｎ，　ａ　ｆｒｉｅｎｄ　ｌｉｋｅ　ｔｈａｔ　ｗｏｕｌｄ　ｂｅ　ｓｏ　ｈａｎｄｙ．．．
;◆ガラクタが↓
;　たまっちゃったんだけど↓
;　すてられなくてねぇ。@KEY()↓
;◆メカにつよい　ともだちでもいたら↓
;　ひとばんで　チャッチャカチャと↓
;　なおしてくれるだろうに‥‥。@KEY()↓
;◆おまえも　そういうともだちを↓
;　もってると　いいぞ。
@KEYNP()
』
;◆ガラクタや　こわれたものって↓
;　すてるに　すてられないんだ。@KEY()↓
;◆おれは　ぶきっちょだけど↓
;　いつか　きようなともだちが↓
;　できないとも　かぎらないし。@KEY()↓
;◆そいつが　てつやして↓
;　バッチリしゅうりして↓
;　くれないとも　かぎらないし。@KEYNP()
;』

;```````````````````````````````````````````````````````````````````
;【シャーク団が強いなーと思ったらドラッグストアで買い物をしろ」と言う人】追加（丸ちゃん）

;配置場所：ゲーセン２階
;配置オブジェ：（シャーク団）
;検査フラグ：FLG_ONET_SHARK_2F_DISAPPEAR /OFF

MSG_ONET_SHARK_SYSINFO_BTL;
@OPEN(1)
◆Ｗｈｅｎ　ｙｏｕ　ｂｕｙ　ａｎ　ｉｔｅｍ　ｔｈａｔ　ｓｈｏｕｌｄ　ｂｅ　ｅｑｕｉｐｐｅｄ，@KEY()↓
◆ｄｏ　ｙｏｕ　ｂｏｔｈｅｒ　ｔｏ　ａｃｔｕａｌｌｙ　ｅｑｕｉｐ　ｉｔ？@KEY()↓
◆Ｈｅｈ　ｅｈ，　Ｉ　ｇａｖｅ　ａ　ｈｉｎｔ　ｔｏ　ｍｙ　ｏｗｎ　ｅｎｅｍｙ．．．@KEY()↓
◆Ｉ’ｍ　ｓｕｃｈ　ａ　ｒｏｃｋｉｎ’　ｄｕｄｅ！@KEY()↓
◆Ｉ　ｏｂｖｉｏｕｓｌｙ　ｈａｖｅ　ｔｏｔａｌ　ｃｏｎｆｉｄｅｎｃｅ　ｉｎ　ｍｙ　ｏｗｎ　ａｂｉｌｉｔｉｅｓ．@KEY()↓
◆Ｓｏ．．．ａｒｅ　ｙｏｕ　ｒｅａｄｙ　ｔｏ　ｇｅｔ　ｉｔ　ｏｎ，　Ｓｐａｎｋｙ？
;◆おまえ　ドラッグストアで↓
;　ぶきとか　ぼうぐをかったとき↓
;　ちゃんと「そうび」してるのか？@KEY()↓
;◆‥‥なんてぐあいに↓
;　てきにヒントをあげちゃう↓
;　よゆうのボクちゃん。@KEY()↓
;◆‥‥じゃ↓
;　たたかおうか！
@KEY()
@CLOSEALL()
@GOSUB(MSG_BATTLE_SHARK_A);バトルへ
@TRUE_GOTO(MSG_BATTLE_LOSE)
@HIDE_CHAR(PRSN_ONET_GAME_2F_D,OBJFX_HIDE_NONE)
@SETF(FLG_ONET_SHARK_2F_DISAPPEAR)
@CLOSEALL()
』

;```````````````````````````````````````````````````````````````````

MSG_BUTTERFLY_HIT;
;ANIM_MAGIC_BUTTERFLY(通常飛行用)から呼ばれる
@MOVE_GOM_CHAR(GOM_BUTTERFLY,ANIM_MAGIC_BUTTERFLY_APPROACH,OBJFX_SHOW_NONE)
@WAITSYS()				;待機
@OPEN(1)
←
◆Ｔｈｅ　ｍａｇｉｃ　ｂｕｔｔｅｒｆｌｙ　ｍａｄｅ　@GOSUB(MSG_ESUB_DSP_PARTY)　ｒｅｌａｘ．
;◆マジックバタフライの　おかげで↓
;　@DSP_LCNAME()は↓
;　とても　リラックスできた。
@KEYNP()
@CLOSEALL()
@REMOVE_GOM_CHAR(GOM_BUTTERFLY,ANIM_MAGIC_BUTTERFLY_OUT)
;@WAITSYS()
@!
;-------------------------------------------------
MSG_ONET_CHECK_HOTEL_KANBAN;
◆”Ｈｏｔｅｌ　Ｏｎｅｔｔ”@KEY()↓
◆３５　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「ホテルオネット」↓
;　ごしゅくはく↓
;　おひとり　３５ドル
@KEYNP()
』
MSG_TWSN_CHECK_HOTEL_KANBAN;
◆”Ｔｗｏｓｏｎ　Ｈｏｔｅｌ”@KEY()↓
◆５０　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「ツーソンホテル」↓
;　ごしゅくはく↓
;　おひとり　５０ドル
@KEYNP()
』
MSG_THRK_CHECK_HOTEL_KANBAN;
◆”Ｔｈｒｅｅｄ　Ｓｕｎｓｅｔ　Ｈｏｔｅｌ”@KEY()↓
◆６０　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「スリーク・サンセットホテル」↓
;　ごしゅくはく↓
;　おひとり　６０ドル
@KEYNP()
』
MSG_SUMS_CHECK_HOTEL_KANBAN;
◆”Ｌ’ｈｏｔｅｌ　ｄｕ　Ｓｕｍｍｅｒ”@KEY()↓
◆１５０　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「オテル・ド・サマーズ」↓
;　ごしゅくはく↓
;　おひとり　１５０ドル
@KEYNP()
』
MSG_FOUR_CHECK_HOTEL_KANBAN;
@CHKFGOTO(FLG_WIN_GIEGU,_FOUR_HOTEL_KANBAN_LATER)
◆”Ｍｏｎｏｔｏｌｙ　Ｇｒａｎｄ　Ｈｏｔｅｌ”@KEY()↓
◆７５　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「モノトリーグランドホテル」↓
;　ごしゅくはく↓
;　おひとり　７５ドル
@KEYNP()
』
_FOUR_HOTEL_KANBAN_LATER;
◆”Ｅｎｒｉｃｈ　Ｇｒａｎｄ　Ｈｏｔｅｌ”@KEY()↓
◆７５　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「エンリッチ・グランドホテル」↓
;　ごしゅくはく↓
;　おひとり　７５ドル
@KEYNP()
』

MSG_MOON_CHECK_HOTEL_KANBAN;
◆”Ｈｏｔｅｌ　Ｄａｒｋ　Ｍｏｏｎ”@KEY()↓
◆７５　ｄｏｌｌａｒｓ　ｆｏｒ　ｏｎｅ　ｓｌｅｅｐ　ｐｅｒｉｏｄ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「ホテル・ダークムーン」↓
;　ひとねむり↓
;　おひとり　７５ドル
@KEYNP()
』
MSG_SKRB_CHECK_HOTEL_KANBAN;
◆”Ｇｒｅａｔ　Ｓｏｕｔｈｅｒｎ　Ｉｎｔｅｒｎａｔｉｏｎａｌ　Ｒｅｓｏｒｔ　Ｈｏｔｅｌ”@KEY()↓
◆１００　ｄｏｌｌａｒｓ　ｐｅｒ　ｎｉｇｈｔ　ｆｏｒ　ａ　ｓｉｎｇｌｅ　ｒｏｏｍ．
;◆「グレート・サザーン・↓
;　こくさい・かんこうホテル」↓@KEY()
;◆ごしゅくはく↓
;　おひとり　１００ドル
@KEYNP()
』
;-------------------------------------------------


MSG_GPFT_DOSEI_C;
@FONTBAKA()
◆Ｉ　ｅｓｃａｐｅｄ．@KEY()↓
◆Ｚｏｏｍ！@KEY()↓
◆Ｂｕｕｒｐ！@KEY()↓
◆Ｂｏｉｎｇ！@KEY()↓
◆Ｇｏｏｄｙ！@KEY()↓
◆Ｂｕｕｕｒｐ！
;◆にげてったよ↓
;　げっぷー。@KEY()↓
;◆よかった↓
;　ぽえーん。
@KEYNP()
@FONTSTD()
』
MSG_DOSEI_KANBAN_MILKY;
@FONTBAKA()
◆Ｈｏｌｅ　”Ｍｉｌｋｙ　Ｗｅｌｌ”．@KEY()↓
◆Ｗｈａｔ　ｔｈｉｓ．．．Ｄｉｎｇ！@KEY()↓
◆Ｄｉｎｇ！
;◆こっちのあな↓
;　「みるきーうぇる」↓
;　なんだろう？？？
@KEYNP()
@FONTSTD()
』
MSG_FOUR_HOSP_CAP;
◆Ｇｒａｎｄｍａ’ｓ　ｇｏｎｎａ　ｇｅｔ　ｂｅｔｔｅｒ，　ｈｕｈ．
;◆おばあちゃん↓
;　げんきになるかなぁ。
@KEYNP()
』
;◆ぼくは「おばあちゃんを↓
;　おみまいにきた　まご」っていう↓
;　せっていなんだ。@KEY()↓
;◆この　だいとかいには↓
;　ちょっと　めずらしい↓
;　シチュエーションでしょ？@KEYNP()
;』
MSG_FOUR_HOSP_OLDWOMAN;
◆Ｉ’ｍ　ｊｕｓｔ　ｅｎｊｏｙｉｎｇ　ｂｅｉｎｇ　ｗｉｔｈ　ｍｙ　ｇｒａｎｄｃｈｉｌｄｒｅｎ．@KEY()↓
◆Ｉ’ｌｌ　ｂｅ　ｂｅｔｔｅｒ　ｓｏｏｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ｇｒａｎｄｃｈｉｌｄｒｅｎ？↓
<Ｙｅｓ>
<Ｎｏ>
;◆まごのかおを　みるだけで↓
;　なんだか　げんきになるんですよ。@KEY()↓
;◆あなたには　おまごさん↓
;　いらっしゃるのかしら？↓
;　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_FOUR_HOSP_OLDWOMAN_YES,_FOUR_HOSP_OLDWOMAN_NO)
_FOUR_HOSP_OLDWOMAN_NO;
◆Ｙｅｓ，　ｙｅｓ．．．ｙｏｕ　ｓｅｅｍ　　ａ　ｌｉｔｔｌｅ　ｙｏｕｎｇ　ｆｏｒ　ｔｈａｔ．．．
;◆まだ　おわかいようですもんね。
@KEYNP()
』
_FOUR_HOSP_OLDWOMAN_YES;
◆Ｏｈ？@KEY()↓
◆Ａｔ　ｙｏｕｒ　ａｇｅ？@KEY()↓
◆Ｏｈ．．．ｔｈｅ　ｙｏｕｔｈ　ｏｆ　ｔｏｄａｙ　ｓｈｏｃｋ　ｍｅ．．．@KEY()↓
◆Ｍｙ　ｌａｎｄｓ．．．
;◆あらまぁ　びっくり。
@KEYNP()
』
;-------------------------------------------------
;■デモ版につき、あしからずメッセージ
;未完成の部分に進もうとした場合のメッセージです。
;内容は、以下にこだわらなくてもかまいません。
;CES会場での表示に適当なように。
;Apology(because of Demo version)
;This message appears when the player tries to enter the area that is not ready 
;to play in the CES version.  You can change whatever it fits better for the CES
;version.
;MSG_CES_SORRY;デモ版につきあしからず（新規）
;@OPEN(1)
;◆Ｔｈｉｓ　ｉｓ　ａｓ　ｆａｒ　ａｓ　ｙｏｕ　ｃａｎ　ｇｏ　ｉｎ　ｔｈｉｓ　ｖｅｒｓｉｏｎ．@KEY()↓
;◆Ｌｏｏｋ　ｆｏｒ　ｔｈｅ　ｆｉｎａｌ　ｖｅｒｓｉｏｎ　ｉｎ　Ｓｐｒｉｎｇ　ｏｆ　１９９５！@KEYNP()
;@WI(20)
;@CLOSEALL()
;@MOVE_GOM_CHAR(GOM_HIT_CHR,ANIM_SoftReset,OBJFX_SHOW_NONE);リセット
;』
;jpn:◆ここからさきは　いまは
;jpn:　あそべません。おたのしみに。

;-------------------------------------------------

;■ＰＳＩの説明メッセージ（EXPL.MSG）
;とりあえず、EXPL.MSGがいただけるまでは
;どのＰＳＩを選択しても同じ説明が出るようにしたいと思います
;PSI Explanation Message
;23 ライフアップα
;akm
;Until "EXPL.MSG" is ready, we want to have the same message appear on the screen
;when the player selects any PSI.
;23 Life-Up SYMBOL 97 \f "Symbol"

;MSG_CES_PSI_SORRY;ＣＥＳ版ＰＳＩ説明（新規）
;MSG_EXPL_PSI_LIFEUP_ALFA;
;◆Ｏｎｅ　ｏｆ　ｙｏｕｒ　ｆｒｉｅｎｄｓ　ｒｅｃｏｖｅｒｅｄ　ａｂｏｕｔ　１００　ＨＰ！
;jpn:◆なかまひとりのＨＰを↓
;jpn:　やく１００ポイント　かいふくする。
;@!

;------------------------------------------------

;■グッズの説明メッセージ
;これも同様に、とりあえず同じメッセージを出しておくつもりです。
;もしも、「制作中につきあしからず」のようなメッセージの方がよければ
;そうしてください。
;Goods Explanation Message
;As same as above, we will show the same message as any item is chosen.
;If you want to show the message like "Demo Only" or "Still Under Development",
;please do so.

;MSG_CES_GDS_EXP_SORRY;ＣＥＳ版グッズ説明（新規）
;◆@DSP_STS(STS_PC_NAME_NES)　ｃａｎ　ｅｑｕｉｐ　ｔｈｉｓ　ｉｔｅｍ，　ｂｕｔ　ｉｔ　ｍａｙ　ｎｏｔ　ｗｏｒｋ　ｉｎ　ｔｈｅ　ＣＥＳ　ｖｅｒｓｉｏｎ．@KEYNP()
;』
;jpn:◆（ネス）が　そうびできる
;jpn:　ぶき。
;------------------------------------------------

;■ヒント屋のヒントなしメッセージ
;MSG_CES_HINT;
;◆Ｈａｎｇ　ｏｎ　ｊｕｓｔ　ａ　ｓｅｃｏｎｄ，　ｙｏｕｎｇ　ｍａｎ！@WI(20)　　Ｉ　ｗａｎｔ　ｔｏ　ｇｉｖｅ　ｙｏｕ　ａ　ｈｉｎｔ．@KEY()↓
;◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｈｏｗ　ｔｏ　ｓａｙ　ｔｈｉｓ．．．@WI(20)　　Ｐｌｅａｓｅ　ｄｏｎ’ｔ　ｈａｔｅ　ｍｅ．
;◆ちょっとまった！ヤングマン@WI(20)↓
;　ヒントを　あげたいんだけど↓
;　まだ　おもいつかないんだ。@KEY()↓
;◆わるいね。
;@KEYNP()
;』
;------------------------------------------------
