;==============================================================================
;
;キャッシュディスペンサー
;

MSG_CD;
;
@SET_LOOPREG(0)
@SET_REG(1)
;
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　Ａｕｔｏｍａｔｉｃ　Ｔｅｌｌｅｒ　Ｍａｃｈｉｎｅ．@KEY()↓
◆Ｐｌｅａｓｅ　ｓｅｌｅｃｔ　ａ　ｔｒａｎｓａｃｔｉｏｎ：↓

;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<Ｗｉｔｈｄｒａｗａｌ>
<Ｄｅｐｏｓｉｔ>
@DSP_ITEM(2)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(_CD_HIKIDASHI,_CD_OAZUKE)
@SELGOTO(_CD_HIKIDASHI,_CD_OAZUKE)

;jpn:◆イラッシャイマセ↓
;jpn:<ヒキダス>
;jpn:<アズケル>
;@DSP_ITEM(2)
_CD_NO;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆アリガトウゴザイマシタ
_CD_END;
@KEYNP()
@!

_CD_OAZUKE;
;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_CD_OA_FULL)
@GOSUB(_CD_INPUT_B)
@FALSE_GOTO(_CD_NO)
@SET_REG(0)
@Q_MONEY(0)
@TRUE_GOTO(_CD_OA_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆Ｙｏｕｒ　ａｃｃｏｕｎｔ　ｗｉｌｌ　ｂｅ　ｃｒｅｄｉｔｅｄ↓
　　＄@DSP_NUM(0)．@KEY()↓
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;◆＄@DSP_NUM(0)↓
;jpn:　オアズカリシマシタ@KEY()↓
;jpn:◆アリガトウゴザイマシタ
@GOTO(_CD_END)

_CD_OA_NOMONEY;				;所持金　＜　入力した金額
◆Ｉｎｖａｌｉｄ　ｉｎｓｔｒｕｃｔｉｏｎ　ｉｎｐｕｔ．　　Ｐｌｅａｓｅ　ｔｒｙ　ａｇａｉｎ．@KEY()↓

;jpn:◆ニュウリョク　ミス！↓
;jpn:　ニュウリョク↓
;jpn:　シナオシテクダサイ@KEY()↓
@GOTO(_CD_OAZUKE)

_CD_OA_OVER;				;銀行預金限界越える（未使用）
◆Ｙｏｕ　ｄｏ　ｎｏｔ　ｈａｖｅ　ｔｈａｔ
　　ｍｕｃｈ　ｍｏｎｅｙ　ｆｏｒ　ａ　ｄｅｐｏｓｉｔ．@KEY()↓

;jpn:◆ソンナニ　アズカレマセン@KEY()↓
@GOTO(_CD_OAZUKE)

_CD_OA_FULL;				;銀行預金MAX
◆Ｔｈｉｓ　ｍａｃｈｉｎｅ　ｃａｎｎｏｔ　ａｃｃｅｐｔ　ａ　ｄｅｐｏｓｉｔ　ｇｒｅａｔｅｒ　ｔｈａｎ↓
　　＄９，９９９，９９９．@KEY()↓
 
;◆＄９９９９９９９↓
;jpn:　ヲコエテハ↓
;jpn:　アズカレナイキマリデス@KEY()↓
@GOTO(_CD_NO)

_CD_HIKIDASHI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_CD_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_CD_HIKI_MAX)
@GOSUB(_CD_INPUT)
@FALSE_GOTO(_CD_NO)
@SET_REG(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CD_HIKI_NOMONEY)
@SAVE_REG()
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@Q_MONEY(100000)			;バグ？
@FALSE_GOTO(_CD_HIKI_OVER)		;機能していない（バグ？）
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Ｙｏｕｒ　ａｃｃｏｕｎｔ　ｈａｓ　ｂｅｅｎ　ｄｅｂｉｔｅｄ↓
　　＄@DSP_NUM(0)．@KEY()↓
◆Ｐｌｅａｓｅ　ｔａｋｅ　ｙｏｕｒ　ｃａｓｈ．

;jpn:◆＄@DSP_NUM(0)　ノ↓
;jpn:　オヒキダシデスネ@KEY()↓
;jpn:◆アリガトウゴザイマシタ
@GOTO(_CD_END)

_CD_HIKI_NOMONEY;			;銀行預金　＜　入力した金額
◆Ｔｈｅ　ｒｅｑｕｅｓｔｅｄ　ａｍｏｕｎｔ　ｉｓ　ｉｎ　ｅｘｃｅｓｓ　ｏｆ　ｙｏｕｒ　ａｃｃｏｕｎｔ　ｂａｌａｎｃｅ．@KEY()↓

;jpn:◆オアズカリキンガクヲ↓
;jpn:　コエテイマス@KEY()↓
@GOTO(_CD_HIKIDASHI)

_CD_HIKI_OVER;				;所持金限界越える
@LOAD_REG()
@DEPOSIT_MONEY_BANK(0)
◆Ｙｏｕ　ａｒｅ　ｎｏｔ　ａｌｌｏｗｅｄ　ｔｏ　ｃａｒｒｙ　ｍｏｒｅ　ｔｈａｎ↓
　　＄９９，９９９．@KEY()↓

;◆＄９９９９９↓
;jpn:　イジョウノモチアルキハ↓
;jpn:　キンジラレテイマス@KEY()↓
@GOTO(_CD_HIKIDASHI)

_CD_HIKI_EMPTY;				;銀行預金$0
◆Ｙｏｕｒ　ａｃｃｏｕｎｔ　ｉｓ　ｃｕｒｒｅｎｔｌｙ　ｓｈｏｗｉｎｇ　ａ　ｚｅｒｏ　ｂａｌａｎｃｅ．@KEY()↓

;jpn:◆ゲンザイ　オアズカリキンハ↓
;jpn:　アリマセン@KEY()↓
@GOTO(_CD_NO)

_CD_HIKI_MAX;				;所持金MAX
◆Ｙｏｕ　ａｒｅ　ｎｏｔ　ａｌｌｏｗｅｄ　ｔｏ　ｃａｒｒｙ　ｍｏｒｅ　ｔｈａｎ↓
　　＄９９，９９９．@KEY()↓

;◆＄９９９９９↓
;jpn:　イジョウノモチアルキハ↓
;jpn:　キンジラレテイマス@KEY()↓
@GOTO(_CD_NO)

_CD_INPUT;
@GOSUB(_CD_NOWMONEY)
◆Ｐｌｅａｓｅ　ｅｎｔｅｒ　ｔｈｅ　ａｍｏｕｎｔ　ｏｆ　ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ．↓

;jpn:◆オヒキダシ　キンガクハ？↓
_CD_INPUT_2;
@WINR_MONEY()
_CD_HOWMUCH;
@LOC(10,2)
＆
@LOC(4,2)
＄@INPUT(5)
@CLRLINE()
@!

_CD_INPUT_B;
@GOSUB(_CD_NOWMONEY)
◆Ｐｌｅａｓｅ　ｅｎｔｅｒ　ｔｈｅ　ａｍｏｕｎｔ　ｏｆ　ｙｏｕｒ　ｄｅｐｏｓｉｔ．↓

;jpn:◆オアズケ　キンガクハ？↓
@GOTO(_CD_INPUT_2)

_CD_NOWMONEY;
◆Ｙｏｕｒ　ａｃｃｏｕｎｔ　ｃｕｒｒｅｎｔｌｙ　ｓｈｏｗｓ　ａ　ｂａｌａｎｃｅ　ｏｆ↓
　　＄@DSP_STS(STS_PARTY_BANK_MONEY)．@KEY()↓

;jpn:◆ゲンザイノ↓
;jpn:　オアズカリキンガクハ↓
;jpn:　＄@DSP_STS(STS_PARTY_BANK_MONEY)デス@KEY()↓
@!

;
;電話
;

MSG_TEL;@Miura
@SEL_TEL_GOSUB()
@TRUE_GOTO(_TEL_END)
←
_TEL_END;
@!

MSG_TEL_2;
@SEL_TEL_GOSUB()
@TRUE_GOTO(_TEL_2END)
←
@MONEYIN(1)
@WINR_MONEY()
_TEL_2END;
@!

;
;スペーストンネル
;

MSG_SPACETNL;
◆ＩＮＰＵＴ　ＹＯＵＲ　ＣＯＭＭＡＮＤ．↓
;@SAVE_WIN()
@DSP_PL()
;@OPEN(37)
@CHKFGOTO(FLG_STEP_PAST,_SPACE_01)
<Ｌｉｆｅ－ｕｐ>
<Ｃｏｍｍｕｎｉｃａｔｅ>

;jpn:◆こまんどヲ　ニュウリョクセヨ↓
;jpn:<カイフク>
;jpn:<ツウシン>
@DSP_ITEM(2)

;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
_SPACE_02;
;@ONGOTO(MSG_SUB_SPACE_KAIHUKU,_SPACE_MUSEN)
@SELGOTO(MSG_SUB_SPACE_KAIHUKU,_SPACE_MUSEN)
@!

_SPACE_01;
<Ｒｅｐａｉｒ>
<Ｃｏｍｍｕｎｉｃａｔｅ>

;jpn:<シュウリ>
;jpn:<ツウシン>
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
@DSP_ITEM(2)
@GOTO(_SPACE_02)

_SPACE_MUSEN;
@GOSUB(MSG_PAPA)			;サブルーチン「電話（テレパパ？）」
					;に飛ぶ。
@!

;
;テレパパ
;

MSG_TEL_GAUS;
@CHKFGOTO(FLG_ITEM_GAUS,_GAUS_AFTER)
◆（Ｂｅｅｐ－ｂｅｅｐ－ｂｅｅｐ．．．）

;jpn:◆ツーツーツー↓
;jpn:　ツーツーツー
@KEYNP()
@!
_GAUS_AFTER;
@SET_REG(1)
@SAVE_GLOBAL_REG()
◆Ｈｅｌｌｏ！　　Ｈｅｌｌｏ！↓
　　Ｍａｘｗｅｌｌ　Ｌａｂｓ　ｈｅｒｅ．@KEY()↓
◆Ｏｈ，　ｈｅｌｌｏ　@DSP_STS(STS_PC_NAME_JEFF)！@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｍｅ　ｔｏ　ｋｅｅｐ　ａ　ｒｅｃｏｒｄ　ｏｆ　ｙｏｕｒ　ｊｏｕｒｎｅｙ？↓

;jpn:◆はい　はい↓
;jpn:　ガウスの　けんきゅうしつ。@KEY()↓
;jpn:◆なんだ　@DSP_STS(STS_PC_NAME_JEFF)か。@KEY()↓
;jpn:◆ぼうけんのきろくを↓
;jpn:　つけてほしいんだな？@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_GAUS_SAVE,_GAUS_BYE)
_GAUS_BYE;
◆Ｙｏｕ　ｊｕｓｔ　ｗａｎｔｅｄ　ｔｏ　ｈｅａｒ　ｍｙ　ｖｏｉｃｅ？↓
　　Ｇｗａｈａｈａｈａｈａｈａｈａｈ！@KEY()↓

;jpn:◆おれのこえが↓
;jpn:　ききたかったってか‥‥↓
;jpn:　ガハハハハハ！@KEY()↓
_GAUS_HANGUP;
@GOTO(_PAPA_HANGUP)
@!

_GAUS_SAVE;
@LOAD_GLOBAL_REG()
@SET_COMEBACK_POS(0)
@CHKFGOTO(FLG_THRK_URBAN_ZOMBI_GONE,_GAUS_SAVE_B)	;ＣＥＳ用セーブ禁止
@SAVE_GAME()
_GAUS_SAVE_B;
◆Ａｌｌ　ｒｉｇｈｔ，　Ｉ　ｈａｖｅ　ｅｖｅｒｙｔｈｉｎｇ　ｗｒｉｔｔｅｎ　ｄｏｗｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔａｋｅ　ａ　ｂｒｅａｋ　ｎｏｗ？↓
<Ｃｏｎｔｉｎｕｅ>
<Ｅｎｄ>
;jpn:◆よし　つけたぞ。@KEY()↓
;jpn:◆もう　やすむのか？↓
;jpn:<つづける>
;jpn:<おわる>
@DSP_ITEM(2)
@SELGOTO(_GAUS_GOON,_GAUS_END)
_GAUS_GOON;
◆Ｙｏｕ’ｖｅ　ｂｅｃｏｍｅ　ｓｕｃｈ　ａ　ｈａｒｄ　ｗｏｒｋｅｒ！@KEY()↓
◆Ｉ’ｖｅ　ｇｏｔ　ｔｏ　ｇｅｔ　ｂａｃｋ　ｔｏ　ｗｏｒｋ　ｍｙｓｅｌｆ！@KEY()↓
◆Ｇｏ　ｆｏｒ　ｉｔ，　ｂａｄ　ｂｏｙ！@KEY()↓
  
;jpn:◆おまえ　ずいぶん↓
;jpn:　がんばりやになったなぁ。@KEY()↓
;jpn:◆おれも　もうすこし↓
;jpn:　がんばってみるよ。@KEY()↓
;jpn:◆ファイト！@KEY()↓
@GOTO(_GAUS_HANGUP)

_GAUS_END;
◆Ｉ　ｄｏｎ’ｔ　ｋｎｏｗ　ｗｈｅｒｅ　ｙｏｕ　ａｒｅ　ｐｌａｎｎｉｎｇ　ｏｎ　ｓｌｅｅｐｉｎｇ，　ｂｕｔ　ｈａｖｅ　ａ　ｇｏｏｄ　ｒｅｓｔ！@KEY()↓
◆Ｇｏ　ａｈｅａｄ　ａｎｄ　ｔｕｒｎ　ｔｈｅ　ｐｏｗｅｒ　ＯＦＦ，　ａｎｄ　ｈａｖｅ　ａ　ｇｏｏｄ　ｎｉｇｈｔ．

;jpn:◆どこでねるのか　しらないが↓
;jpn:　ゆっくり　からだを↓
;jpn:　やすめろよ。@KEY()↓
;jpn:◆それじゃ　でんげんを↓
;jpn:　ＯＦＦにして　おやすみ‥‥。
@DISKEY()
@KEYNP()
@!

MSG_PAPA;
@CHKFGOTO(FLG_PHONE_PAPA_FINAL,MSG_GLOBAL_PHONE_NG)
@CHKFGOTO(FLG_WIN_GIEGU,_PAPA_PHONE_END)
@SET_REG(1)
@SAVE_GLOBAL_REG()
←
@GET_ORDER_PLAYER(1)
@EQ(PC_NESS)
@TRUE_GOTO(_PAPA_NESS)
◆Ｈｅｌｌｏ？@KEY()↓
◆．．．Ｉｓ　ｔｈａｔ　ｙｏｕ，　@DSP_STS(STS_PC_NAME_NES)@WI(10)？@KEY()↓
◆Ｗｈｙ　ａｒｅ　ｙｏｕ　ｄｉｓｇｕｉｓｉｎｇ　ｙｏｕｒ　ｖｏｉｃｅ　ｌｉｋｅ　ｔｈａｔ？@KEY()↓
◆Ｗｈｏ　ａｒｅ　ｙｏｕ　ｐｒｅｔｅｎｄｉｎｇ　ｔｏ　ｂｅ？@KEY()↓
◆Ｏｈ，　ｗｅｌｌ．　　Ｉｔ’ｓ　ｎｏｔ　ａ　ｂｉｇ　ｄｅａｌ．@KEY()↓
◆Ｉ　ｓｕｐｐｏｓｅ　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｈａｖｅ　ａ　ｓｅｎｓｅ　ｏｆ　ｈｕｍｏｒ↓　ａｔ　ａ　ｔｉｍｅ　ｌｉｋｅ　ｔｈｉｓ．@KEY()↓
;◆Ｏｋａｙ，　ｅｖｅｎ　ｔｈｏｕｇｈ　Ｉ’ｍ　ｎｏｔ　ｓｕｒｅ　ｗｈｏ　ｔｈｉｓ　ｉｓ，　ｂｕｔ　ｉｆ　ｙｏｕ’ｒｅ　ｃａｌｌｉｎｇ　ｍｅ@KEY()↓
;◆ａｂｏｕｔ　ｋｅｅｐｉｎｇ　ａ　ｒｅｃｏｒｄ　ｏｆ　ｙｏｕｒ　ｊｏｕｒｎｅｙ，　Ｉ’ｌｌ　ｇｌａｄｌｙ　ｄｏ　ｉｔ　ｆｏｒ　ｙｏｕ．@KEY()↓ 
;jpn:◆もしもし‥‥。@KEY()↓
;jpn:◆‥‥おいおい　@DSP_STS(STS_PC_NAME_NES)@WI(10)↓
;jpn:　そんなこえを　だして↓
;jpn:　いったい　だれのモノマネだ？@KEY()↓
;jpn:◆‥‥ま　そのままつづけなさい。@WI(15)↓
;jpn:　こんなときこそ↓
;jpn:　ユーモアは　だいじだからな。@KEY()↓
;◆もしもし。@KEY()↓
;◆どなたかぞんじませんが↓
;　ぼうけんのきろくでしたら↓
;　わたしが　つけておきましょう。@KEY()↓
@GOTO(_PAPA_BANK)
_PAPA_NESS;
◆@DSP_NAME(PC_NESS)？　　Ｉｔ’ｓ　ｙｏｕｒ　ｄａｄ．@KEY()↓
;jpn:◆あ　パパだ。@KEY()↓
@CHKF(FLG_STEP_PAST)			;ロボ状態だったら
@ONGOSUB(_PAPA_ROBO)			;「風邪か?」メッセージ
_PAPA_BANK;
@Q_FIGHT_MONEY(1)
@FALSE_GOTO(_PAPA_LEVEL)
@XCHG()
◆Ｉ　ｄｅｐｏｓｉｔｅｄ　＄@DSP_NUM(0)↓
　　ｉｎｔｏ　ｙｏｕｒ　ｂａｎｋ　ａｃｃｏｕｎｔ．@KEY()↓
◆Ｔａｋｉｎｇ　ａｗａｙ　ｗｈａｔ　ｙｏｕ’ｖｅ　ｓｐｅｎｔ，　ｙｏｕ　ｓｈｏｕｌｄ　ｎｏｗ　ｈａｖｅ@KEY()↓
◆＄@DSP_STS(STS_PARTY_BANK_MONEY)　ｉｎ　ｔｈｅ　ｂａｎｋ．@KEY()↓

;jpn:◆おまえの　ぎんこうこうざに↓
;jpn:　@DSP_NUM(0)ドル↓
;jpn:　ふりこんでおいたからね。@KEY()↓
;jpn:◆つかったぶんと　さしひきで↓
;jpn:　@DSP_STS(STS_PARTY_BANK_MONEY)ドル↓
;jpn:　ぎんこうに　はいっているはずだ。@KEY()↓
@Q_FIGHT_MONEY(2)
_PAPA_LEVEL;
@SET_LOOPREG(1)				;全プレーヤーの次のレベルまでの	loopR <- 1
◆Ｗｅｌｌ，　ｔｏ　ｇｅｔ　ｔｏ　ｎｅｘｔ　ｌｅｖｅｌ，@KEY()

;jpn:◆えーと　つぎのレベルまで‥‥
_PAPA_NEXT;				;経験値表示
@SET_REG(1)				;subR <- loopR
@Q_MEMBER(0)				;compare party(without npc) with subR
@TRUE_GOTO(_PAPA_SEL)			;全プレーヤーでループさせる。if party < subR goto _papa_sel
@GET_ORDER_PLAYER(0)			;mainR <- playerId[subR]
@FALSE_GOTO(_PAPA_SEL)			;if !mainR goto _papa_sel
@SET_REG(0)				;subR <- mainR
@GET_NEXTLEVEL(0)			;mainR <- nextLevel[subR] 
@FALSE_GOTO(_PAPA_LEVEL_MAX)		;if !nextLevel[subR] _papa_next_inc
					;この時点で、mainRには次のレベルに必要な経験値が
					;subRにはプレイヤーIDが入っている
;@XCHG()				;いらない！削除
←
◆@DSP_NAME(0)．．．．

;jpn:◆@DSP_NAME(0)は　
@XCHG()					;xchg subR,mainR
@DSP_NUM(0)．@KEY()
;jpn:@DSP_NUM(0)。@KEY()
_PAPA_NEXT_INC;
@INC()					;loopR++
@GOTO(_PAPA_NEXT)			;goto _papa_next

_PAPA_LEVEL_MAX;
←
◆@DSP_NAME(0)．．．↓
　　ｈａｓ　ａｌｒｅａｄｙ　ｒｅａｃｈｅｄ　（ｈｉｓ／ｈｅｒ）　ｍａｘｉｍｕｍ　ｌｅｖｅｌ．@KEY()↓
◆Ｔｈａｔ’ｓ　ｊｕｓｔ　ｆｉｎｅ，　ｂｕｔ．．．@KEY()↓

;jpn:◆@DSP_NAME(0)は‥‥
@KEY()↓
;jpn:◆もうすでに↓
;jpn:　いきつくところまで↓
;jpn:　いってしまったみたいだな。
@KEY()↓
;jpn:◆それは　それで↓
;jpn:　@WI(20)ま　@WI(20)いいとして‥‥
;@KEY()↓
@GOTO(_PAPA_NEXT_INC)

_PAPA_SEL;
←
◆Ａｎｙｗａｙ，　ｗｈａｔ　ｄｏ　ｙｏｕ　ｎｅｅｄ　ｆｒｏｍ　ｍｅ？↓
;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<Ｒｅｃｏｒｄ>
<Ｎｏｔｈｉｎｇ，　ｒｅａｌｌｙ>

;jpn:◆それはそうと　なんのようだい？↓
;jpn:<きろくする>
;jpn:<とくにない>
@DSP_ITEM(2)
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(_PAPA_SAVE,_PAPA_CANCEL)
@SELGOTO(_PAPA_SAVE,_PAPA_CANCEL)

_PAPA_CANCEL;				;キャンセル
◆Ｇｏｏｄ　ｌｕｃｋ！@KEY()↓

;jpn:◆がんばれよ。@KEY()↓
@GOTO(_PAPA_HANGUP)

_PAPA_SAVE;				;記録する。
@LOAD_GLOBAL_REG()
@SET_COMEBACK_POS(0)
;@CHKFGOTO(FLG_THRK_URBAN_ZOMBI_GONE,_PAPA_SAVE_B)	;ＣＥＳ用セーブ禁止（解除）
@SAVE_GAME()
_PAPA_SAVE_B;
◆Ａｌｌ　ｄｏｎｅ．@KEY()↓
◆Ｙｏｕｒ　ｄｅａｒ　ｏｌｄ　ｄａｄ　ｗａｓ　ａｌｓｏ　ｔｈｉｎｋｉｎｇ　ａｂｏｕｔ　ｈｉｔｔｉｎｇ　ｔｈｅ　ｈａｙ　ｆｏｒ　ｔｈｅ　ｎｉｇｈｔ．@KEY()↓
◆Ｉ　ｈａｖｅ　ｃｒｅａｔｅｄ　ａ　ｒｅｃｏｒｄ　ｏｆ　ｙｏｕｒ　ａｄｖｅｎｔｕｒｅ　ｔｏ　ｔｈｉｓ　ｐｏｉｎｔ．@KEY()↓
◆Ｇｏｏｄ　ｎｉｇｈｔ，　ｓｌｅｅｐ　ｔｉｇｈｔ．↓

;jpn:◆そうか。↓
;jpn:　パパも　もう　きょうは↓
;jpn:　やすもうと　おもってたところだ。@KEY()↓
;jpn:◆ぼうけんのきろくは↓
;jpn:　つけといたよ。@KEY()↓
;jpn:◆おやすみ‥‥↓
@GET_ORDER_PLAYER(1)			;先頭プレイヤーがネスじゃなければ
@EQ(PC_NESS)
@FALSE_GOTO(_PAPA_SEL_CONT)		;風邪直せ云々言わない
@CHKF(FLG_STEP_PAST)
@ONGOSUB(_PAPA_ROBO_2)			;ロボなら「風邪直せよ」。ホームシック直す。
_PAPA_SEL_CONT;
<Ｃｏｎｔｉｎｕｅ>
<Ｅｎｄ>

;jpn:<つづける>
;jpn:<おわる>
@DSP_ITEM(2)
@SELGOTO(_PAPA_GOON,_PAPA_END)

_PAPA_GOON;				;続ける。
◆@DSP_STS(STS_PC_NAME_NES)，　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｗｏｒｋ　ｈａｒｄ，　ｊｕｓｔ　ｌｉｋｅ　ｙｏｕｒ　ｍｏｔｈｅｒ．@KEY()↓
◆Ｂｕｔ，　Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｉｔ’ｓ　ｇｏｏｄ　ｔｏ　ｗｏｒｋ　ｔｏｏ　ｈａｒｄ．@KEY()↓

;jpn:◆@DSP_STS(STS_PC_NAME_NES)も　ママににて↓
;jpn:　がんばりやだなあ。@KEY()↓
;jpn:◆むりするなよ。@KEY()↓

_PAPA_HANGUP;
←
@SE(SE_se0b_tel_put)
◆（Ｃｌｉｃｋ！　　Ｂｅｅｐ－ｂｅｅｐ－ｂｅｅｐ．．．）

;jpn:◆ガチャン　ツーツーツー
@KEYNP()
@!

_PAPA_END;				;ゲーム終了
◆Ｗｅ’ｒｅ　ａ　ｇｒｅａｔ　ｔｅａｍ，　ａｒｅｎ’ｔ　ｗｅ？@KEY()↓
◆Ｗｅｌｌ，　ｙｏｕ　ｓｈｏｕｌｄ　ｔｕｒｎ　ｔｈｅ　ｐｏｗｅｒ　ＯＦＦ　ｉｎｓｔｅａｄ　ｏｆ　ｊｕｓｔ　ｐｒｅｓｓｉｎｇ　ＲＥＳＥＴ．@KEY()↓
◆Ａｌｌ　ｒｉｇｈｔ？

;jpn:◆おたがい　よくやったよな。@KEY()↓
;jpn:◆それじゃ　リセットボタンを↓
;jpn:　おさないで　でんげんを　ＯＦＦに↓
;jpn:　しなさい。　わかったね。
@DISKEY()
@KEYNP()
@!

_PAPA_ROBO;
◆Ｗｈｏ　ｉｓ　ｔｈｉｓ？！　　@DSP_STS(STS_PC_NAME_NES)？！↓
　　Ｄｏ　ｙｏｕ　ｈａｖｅ　ａ　ｃｏｌｄ　ｏｒ　ｓｏｍｅｔｈｉｎｇ？@KEY()↓
◆Ｙｏｕｒ　ｖｏｉｃｅ　ｓｏｕｎｄｓ　ｋｉｎｄ　ｏｆ　ｆｕｎｎｙ．@KEY()↓
◆Ｏｈ，　ｗｅｌｌ．　　Ｔｈａｔ’ｓ　ＯＫ．@KEY()↓

;jpn:◆あれ！？　@DSP_STS(STS_PC_NAME_NES)！？↓
;jpn:　カゼでもひいてるのか。↓
;jpn:　こえが　へんだぞ@KEY()↓
;jpn:◆ま　いいか@KEY()↓
@!

;以下、ネスが先頭でない場合は呼ばれないようにした(上野)
_PAPA_ROBO_2;
◆Ｉ　ｈｏｐｅ　ｙｏｕ　ｇｅｔ　ｏｖｅｒ　ｙｏｕｒ　ｃｏｌｄ　ｓｏｏｎ．
;jpn:　はやくかぜをなおせよ。↓
@Q_SPECIAL(PC_NESS,6,2);ホームシック？
@TRUE_GOTO(_PAPA_ROBO_HOMESICK)
@!
_PAPA_ROBO_HOMESICK;
;以下、;は話の流れ上おかしくなるので削除(上野)
;@CLOSEALL()
;@WI(30)
;@OPEN(1)
;◆@DSP_STS(STS_PC_NAME_NES)は↓
;　ホームシックを　こくふくした。
@SET_SPECIAL(PC_NESS,6,1);ホームシック解除
@SE(SE_se25_b_healing)
;@KEY()↓
@!

_PAPA_PHONE_END;
◆Ｈｉ，　ｉｔ’ｓ　ｙｏｕｒ　ｄａｄ！↓
　　Ｔｏ　ｇｅｔ　ｔｏ　ｔｈｅ　ｎｅｘｔ　ｌｅｖｅｌ．．．@KEY()↓
◆Ｈａ　ｈａｈ　ｈａ　ｈａｈ！↓
　　Ｉ　ｇｕｅｓｓ　Ｉ　ｄｏｎ’ｔ　ｎｅｅｄ　ｔｏ　ｔｅｌｌ　ｙｏｕ　ｔｈｉｓ　ａｎｙ　ｍｏｒｅ！@KEY()↓
◆．．．　Ｎｅｘｔ　ｗｅｅｋ　ｗｉｌｌ　ｂｅ　ｙｏｕｒ　ｂｉｒｔｈｄａｙ，　@DSP_STS(STS_PC_NAME_NES)．@KEY()↓
◆Ｉ’ｍ　ｔｒｙｉｎｇ　ｖｅｒｙ　ｈａｒｄ　ｔｏ　ｂｅ　ｈｏｍｅ　ｆｏｒ　ｔｈａｔ　ｂｉｇ　ｄａｙ！@KEY()↓
◆Ｉ’ｌｌ　ｂｅ　ｓｕｒｅ　ｔｏ　ｇｅｔ　ｙｏｕ　ａ　ｇｏｏｄ　ｐｒｅｓｅｎｔ！@KEY()↓
◆Ｉ’ｖｅ　ｂｅｅｎ　ｆｏｌｌｏｗｉｎｇ　ｙｏｕｒ　ａｄｖｅｎｔｕｒｅｓ　ｃｌｏｓｅｌｙ，@KEY()↓
◆ｂｕｔ　Ｉ　ｗａｎｔ　ｔｏ　ｈｅａｒ　ａｂｏｕｔ　ｔｈｅｍ　ｆｒｏｍ　ｙｏｕ，　ｉｎ　ｐｅｒｓｏｎ．@KEY()↓
◆Ｙｏｕ　ｓｏｕｎｄ　ａ　ｌｏｔ　ｍｏｒｅ．．．　ｍａｔｕｒｅ　ｏｖｅｒ　ｔｈｅ　ｐｈｏｎｅ．@KEY()↓
◆．．．Ｗｅｌｌ，　Ｉ’ｌｌ　ｓｅｅ　ｙｏｕ　ａｔ　ｈｏｍｅ，　ｔｈｅｎ．@KEY()↓
◆Ｂｙｅ！↓
  
;jpn:◆あ　パパだ。↓
;jpn:　つぎの　レベルまで‥‥@KEY()↓
;jpn:◆ハハハハハ！@WI(20)↓
;jpn:　もう　そんなことをいう↓
;jpn:　ひつようも　ないな。@KEY()↓
;jpn:◆‥‥らいしゅうは　たしか↓
;jpn:　@DSP_STS(STS_PC_NAME_NES)の↓
;jpn:　たんじょうび　だったろう？@KEY()↓
;jpn:◆なんとか　パパも↓
;jpn:　それに　まにあうように↓
;jpn:　かえるから。@KEY()↓
;jpn:◆おみやげを　たのしみに↓
;jpn:　まっていておくれ。@KEY()↓
;jpn:◆いつも　ぼうけんのきろくを↓
;jpn:　つけていたけれど@KEY()↓
;jpn:◆おまえに　ちょくせつ↓
;jpn:　いろんなはなしを　ききたいよ。@KEY()↓
;jpn:◆でんわのこえも　ちょっと↓
;jpn:　おとなっぽくなったけど‥‥@KEY()↓
;jpn:◆きっと↓
;jpn:　おおきくなったんだろうなぁ。@KEY()↓
;jpn:◆‥‥じゃ　こんどは↓
;jpn:　いえで　ゆっくりな。@KEY()↓
;jpn:◆バーイ！@WI(20)↓
@SE(SE_se0b_tel_put)
　　（Ｃｌｉｃｋ！↓
　　Ｂｅｅｐ－ｂｅｅｐ－ｂｅｅｐ．．．）

;jpn:　ガチャン　ツーツーツー
@KEYNP()
@SETF(FLG_PHONE_PAPA_FINAL)
』

;
;エスカルゴ運送（電話）
;

MSG_UNSOU_TEL;
@CHKFGOTO(FLG_PHONE_ESCARGO_FINAL,MSG_GLOBAL_PHONE_NG);ツーツーツーのみ
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_1B);最終戦闘後
@CHKFGOTO(FLG_DELIVERY_UNSOU,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_B,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKOKESHI,_UNSOU_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_UNSOU_TAKANOME,_UNSOU_NOW_DELIVERY)
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(_UNSOU_NOW_DELIVERY)
;-----
;遺失物検査
@CHKFGOTO(FLG_GLOBAL_LOST_TAKOKESHI,MSG_UNSOU_TEL_TACO)
@CHKFGOTO(FLG_GLOBAL_LOST_TAKANOME,MSG_UNSOU_TEL_TAKA)
;-----
@GOSUB(_UNSOU_TEL_MES_1)
_UNSOU_TEL_SEL_MAIN;			;要件？
@GOSUB(_UNSOU_TEL_MES_2)
<Ｐｉｃｋ－ｕｐ>
<Ｄｅｌｉｖｅｒｙ>

;jpn:<おあずかり>
;jpn:<おとどけ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_LEAVE,_UNSOU_TEL_SEND)

_UNSOU_TEL_BYE;				;要件キャンセル
@GOSUB(_UNSOU_TEL_MES_3)
@GOSUB(_SUB_HANGUP_MES)
@!

_UNSOU_TEL_LEAVE;			;あずける選択
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_TEL_LEAVE_FULL)
_UNSOU_TEL_LEAVE_OK;
@GOSUB(_UNSOU_TEL_MES_4)
@SETF(FLG_DELIVERY_UNSOU_B)
@DELIVERY(DELIVERY_UNSOU_PICKUP)
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!

_UNSOU_TEL_LEAVE_FULL;			;預かれない。
@GOSUB(_UNSOU_TEL_MES_5)
@GOTO(_UNSOU_TEL_BYE)

_UNSOU_TEL_SEND;			;届ける選択。
@SET_LOOPREG(1)				
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY)		;空？
@GOSUB(_UNSOU_TEL_MES_6)
_UNSOU_TEL_SEND_1;
@SAVE_WIN()
@SEL_TRACY_OUT()			;主レ=選択された預り所のグッズの位置
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_BYE)
@XCHG()
@SAVE_REG()				;副レ=選択された預り所のグッズの位置
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)？↓
　　Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆@DSP_GOODS(0)ですね。↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)
;jpn:　ほかにまだありますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_2,_UNSOU_TEL_Q_OK)
@GOTO(_UNSOU_TEL_Q_OK)
_UNSOU_TEL_SEND_2;
@SET_LOOPREG(1)
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY_2)
◆Ｓｅｌｅｃｔ　ａｎ　ｉｔｅｍ．@KEY()

;jpn:◆では　グッズを↓
;jpn:　せんたくしてください。@KEY()
@SAVE_WIN()
@SEL_TRACY_OUT()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_Q_OK)
@XCHG()
@SAVE_REG()
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)？↓
　Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓
 
;jpn:◆@DSP_GOODS(0)ですね。↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)
;jpn:　ほかに　ありますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_3,_UNSOU_TEL_Q_OK)
@GOTO(_UNSOU_TEL_Q_OK)
_UNSOU_TEL_SEND_3;
@SET_LOOPREG(1)
@GET_TRACY()
@FALSE_GOTO(_UNSOU_TEL_EMPTY_2)
◆Ｓｅｌｅｃｔ　ａｎ　ｉｔｅｍ．@KEY()

;jpn:◆では　グッズを↓
;jpn:　せんたくしてください。@KEY()
@SAVE_WIN()
@SEL_TRACY_OUT()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
←
@FALSE_GOTO(_UNSOU_TEL_Q_OK)
@XCHG()
@SAVE_REG()
@GET_TRACY_GOODS(0)
@XCHG()
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@LOAD_REG()
@SET_TRANS_GOODS(255,0)

_UNSOU_TEL_Q_OK;			
◆Ｊｕｓｔ　ｔｏ　ｃｏｎｆｉｒｍ，　ｙｏｕ’ｒｅ　ｅｘｐｅｃｔｉｎｇ　ｄｅｌｉｖｅｒｙ　ｏｆ　ｔｈｅ@KEY()↓
 
;jpn:◆かくにんします。↓
;jpn:　おとどけするのは@KEY()↓
@GET_TRANS_GOODS(1,0)
◆@DSP_GOODS(0)
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_TEL_Q_OK_2)
↓
　　@DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_TEL_Q_OK_2)
↓
　　ａｎｄ　@DSP_GOODS(0)．
;jpn:　あと　@DSP_GOODS(0)
_UNSOU_TEL_Q_OK_2;
@KEY()
←
◆Ｉｓ　ｔｈａｔ　ｃｏｒｒｅｃｔ？↓

;jpn:◆いじょうで　よろしいでしょうか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_TEL_SEND_OK,_UNSOU_TEL_SEND_ONEMORE)
@GOTO(_UNSOU_TEL_SEND_ONEMORE)

_UNSOU_TEL_SEND_OK;			;届けにくる。（バッファに保存）
@GOSUB(_UNSOU_TEL_MES_7)
@SETF(FLG_DELIVERY_UNSOU)
@DELIVERY(DELIVERY_UNSOU_DELIVER)
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
@!

_UNSOU_TEL_EMPTY;				;預り所カラ（終了へ）
@GOSUB(_UNSOU_TEL_MES_8)
@GOTO(_UNSOU_TEL_BYE)

_UNSOU_TEL_EMPTY_2;				;預り所カラ（確認へ）
@GET_ORDER_PLAYER(1)
@XCHG()
◆Ｗｅ’ｒｅ　ｎｏｔ　ｓｔｏｒｉｎｇ　ａｎｙ　ｏｆ　@DSP_NAME(0)’ｓ　ｓｔｕｆｆ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓
;jpn:◆げんざい　@DSP_NAME(0)さまからは↓
;jpn:　これいじょう　おにもつを↓
;jpn:　あずかっておりません。@KEY()↓
@GOTO(_UNSOU_TEL_Q_OK)

_UNSOU_TEL_SEND_ONEMORE;			;やり直し（バッファをクリア）
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
◆Ｗｅｌｌ，　ｐｌｅａｓｅ　ｓｔａｒｔ　ｏｖｅｒ　ａｇａｉｎ．@KEY()↓

;jpn:◆では　もういちど↓
;jpn:　あらためて　おねがいします。@KEY()↓
@GOTO(_UNSOU_TEL_SEND_1)

_UNSOU_NOW_DELIVERY;
@GOSUB(_UNSOU_TEL_MES_9)
@GOSUB(_SUB_HANGUP_MES)
@!

;

_UNSOU_TEL_MES_1;
◆Ｈｅｌｌｏ！　　Ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓

;jpn:◆こんにちは↓
;jpn:　エスカルゴうんそうでーす。@KEY()
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_MES_1_END)
←
◆Ｏｈ，　ｉｓ　ｔｈａｔ　ｙｏｕ，　@DSP_STS(STS_PC_NAME_NES)？↓
　　Ｂｉｇ　Ｂｒｏ！@KEY()↓
◆Ｉｔ’ｓ　ｍｅ，　Ｔｒａｃｙ．@KEY()↓
◆Ｉ’ｍ　ｗｏｒｋｉｎｇ　ｐａｒｔ－ｔｉｍｅ　ｆｏｒ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓

;jpn:◆あ@WI(10)　@DSP_STS(STS_PC_NAME_NES)おにいちゃん？@KEY()↓
;jpn:◆わたしよ　トレーシーよ。@KEY()↓
;jpn:◆エスカルゴうんそうで↓
;jpn:　アルバイトしてるの。@KEY()
_UNSOU_TEL_MES_1_END;
@!
_UNSOU_TEL_MES_1B;最終戦闘後
◆Ｈｅｌｌｏ！　Ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆Ｔｒａｃｙ　ｄｏｅｓｎ’ｔ　ｗｏｒｋ　ｈｅｒｅ　ａｎｙ　ｍｏｒｅ．　　Ｙｅａｈ，　ｓｈｅ　ｕｓｅｄ　ｔｏ　ｗｏｒｋ　ｈｅｒｅ，　ｐａｒｔ－ｔｉｍｅ．@KEY()↓
◆Ｈｕｎｈ？　　Ｔｈｉｓ　ｉｓ　@DSP_STS(STS_PC_NAME_NES)？↓
　　Ｔｒａｃｙ’ｓ　ｂｉｇ　ｂｒｏｔｈｅｒ？@KEY()↓
◆Ｉ’ｖｅ　ｈｅａｒｄ　ａｂｏｕｔ　ｔｈｅ　ｇｒｅａｔ　ｗｏｒｋ　ｙｏｕ’ｒｅ　ｄｏｉｎｇ．@KEY()↓
◆Ｉｔ’ｓ　ａｎ　ｈｏｎｏｒ　ｔｏ　ｔａｌｋ　ｔｏ　ｙｏｕ，　ｓｉｒ！@KEY()↓
◆Ｏｈ，　ｙｏｕ’ｒｅ　ｃａｌｌｉｎｇ　ｆｏｒ　ａ　ｄｅｌｉｖｅｒｙ？↓
　　Ｉ’ｍ　ｖｅｒｙ　ｓｏｒｒｙ．@KEY()↓
◆Ｍｙ　ｗｉｆｅ　ｉｓ　ｏｕｔ　ｏｎ　ｍａｔｅｒｎｉｔｙ　ｌｅａｖｅ，　ｓｏ　Ｉ’ｍ　ｔａｋｉｎｇ　ｃａｒｅ　ｏｆ　ｍｙ　ｏｔｈｅｒ　ｋｉｄ．@KEY()↓
◆Ｉ　ｄｅｃｉｄｅｄ　ｔｏ　ｔａｋｅ　ｓｏｍｅ　ｔｉｍｅ　ｏｆｆ　ｆｒｏｍ　ｔｈｅ　ｄｅｌｉｖｅｒｙ　ｂｕｓｉｎｅｓｓ．@KEY()↓
◆Ｉｔ’ｓ　ｒｉｇｈｔ　ｎｅｘｔ　ｔｏ　ｔｈｅ　ｆｒｉｄｇｅ！　　Ｐｕｔ　ｉｔ　ｉｎｔｏ　ｔｈｅ　ｍｉｃｒｏｗａｖｅ．．．　　．．．ｔｈａｔ’ｓ　ｉｔ．@KEY()↓
◆．．．Ｓｏｒｒｙ　ａｂｏｕｔ　ｔｈａｔ．@KEY()↓
◆Ｉ’ｍ　ａ　ｌｉｔｔｌｅ　ｂｕｓｙ　ｒｉｇｈｔ　ｎｏｗ，　ａｓ　ｙｏｕ　ｈｅａｒｄ．@KEY()↓
◆Ｉ　ｒｅａｌｌｙ　ｗｏｕｌｄ　ｌｉｋｅ　ｔｏ　ｈｅａｒ　ｓｏｍｅ　ｏｆ　ｙｏｕｒ　ｓｔｏｒｉｅｓ．@KEY()↓
◆Ｚｏｉｃｋｓ！　　Ｔｈａｔ　ｗａｓ　ｔｈｅ　ｄｏｇ’ｓ　ｆｏｏｄ！@KEY()↓
◆＊Ｃｒａｓｈ！＊　Ｈｅｙ，　ｈｅｙ！　　Ｎｏｗ　ｌｏｏｋ　ｗｈａｔ　ｙｏｕ’ｖｅ　ｄｏｎｅ！@KEY()↓
◆．．．Ｉ’ｍ　ｓｏｒｒｙ．↓
　　Ｉ　ｈａｖｅ　ｔｏ　ｇｏ．　　Ｇｏｏｄ　ｂｙｅ．↓
;jpn:◆はい@WI(20)　エスカルゴうんそうでーす！@WI(30)↓
;jpn:　アルバイトのトレーシーちゃんなら↓
;jpn:　もう　やめましたよ。@KEY()↓
;jpn:◆えっ？@WI(15)　あんた　@DSP_STS(STS_PC_NAME_NES)とかって↓
;jpn:　トレーシーのおにいさん？@KEY()↓
;jpn:◆なんだか　たいそう↓
;jpn:　ごりっぱな　かつやくをした↓
;jpn:　そうじゃないか。@KEY()↓
;jpn:◆わざわざ↓
;jpn:　でんわもらっちゃうなんて↓
;jpn:　こうえいだなぁ。@KEY()↓
;jpn:◆えっ　はいたつですか？@WI(20)↓
;jpn:　いやぁ@WI(15)　ざんねんだなあ。@KEY()↓
;jpn:◆にょうぼが　しゅっさんで↓
;jpn:　さとがえりしましてね。@KEY()↓
;jpn:◆うえのコの　めんどうを↓
;jpn:　みなきゃならないんで@KEY()↓
;jpn:◆しばらく　やすみを↓
;jpn:　とることにしたんですよ。@KEY()↓
;jpn:◆そこの　れいぞうこの↓
;jpn:　よこに　あるから！↓
;jpn:　チンして‥‥@WI(15)そうそう。@KEY()↓
;jpn:◆‥‥あ@WI(15)　しつれいしました。@WI(20)↓
;jpn:　というふうに↓
;jpn:　いそがしいんですよ。@KEY()↓
;jpn:◆また　ゆっくり↓
;jpn:　おはなしきかせてください。@KEY()↓
;jpn:◆そりゃ↓
;jpn:　イヌのメシだってーの！@WI(20)↓
;jpn:　（ガチャン）オラオラ！@KEY()↓
;jpn:◆‥‥じゃ　すいません↓
;jpn:　しつれいします。@WI(20)↓
@SE(SE_se0b_tel_put)
　　（Ｃｌｉｃｋ！）
;jpn:　ガチャン　ツーツーツー
@KEYNP()
@SETF(FLG_PHONE_ESCARGO_FINAL)
』
;◆あんただったら　タダでいいよ。@KEY()
;@!

_UNSOU_TEL_MES_2;
←
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_2B)
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｄｏ　ｆｏｒ　ｙｏｕ？↓

;jpn:◆どんなごようけんでしょうか？↓
@!
_UNSOU_TEL_MES_2B;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｎｅｅｄ？↓

;jpn:◆ごようけんは？↓
@!
_UNSOU_TEL_MES_3;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_3B)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_BYE_NESS_DEAD)
◆Ｃｏｍｅ　ａｇａｉｎ．@KEY()

;jpn:◆また　よろしくね。@KEY()
@!
_UNSOU_TEL_BYE_NESS_DEAD;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()

;jpn:◆また　よろしくおねがいします。@KEY()
@!
_UNSOU_TEL_MES_3B;
◆Ｗｅｌｌ，　ｃｏｍｅ　ａｇａｉｎ．@KEY()

;jpn:◆じゃ@WI(15)　また　よろしく。@KEY()
@!

_UNSOU_TEL_MES_4;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_4B)
◆Ｙｏｕ　ｗａｎｔ　ｕｓ　ｔｏ　ｓｔｏｒｅ　ｓｏｍｅｔｈｉｎｇ　ｆｏｒ　ｙｏｕ？@KEY()↓
◆Ｗｅ’ｌｌ　ｓｅｎｄ　ｓｏｍｅｏｎｅ　ｏｖｅｒ　ｉｍｍｅｄｉａｔｅｌｙ　ｔｏ　ｐｉｃｋ　ｉｔ　ｕｐ．@KEY()

;jpn:◆おあずかりですね。↓
;jpn:　かかりのものが　すぐ↓
;jpn:　そちらに　まいりまーす。@KEY()
@!
_UNSOU_TEL_MES_4B;
◆Ｗｅｌｌ，　Ｉ’ｌｌ　ｐｉｃｋ　ｉｔ　ｕｐ　ｐｅｒｓｏｎａｌｌｙ．↓
　　Ｗｈｏ　ａｍ　Ｉ？↓
　　Ｉ’ｍ　ｔｈｅ　ｐｒｅｓｉｄｅｎｔ！@KEY()
 
;jpn:◆じゃ@WI(20)　しゃちょうのわたしが↓
;jpn:　ちょくせつ　とりにいきましょう！@KEY()
@!

_UNSOU_TEL_MES_5;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_5B)
◆Ｉ’ｍ　ｖｅｒｙ　ｓｏｒｒｙ．↓
　　Ｏｕｒ　ｓｔｏｒａｇｅ　ｌｏｃｋｅｒｓ　ａｒｅ　ａｌｌ　ｆｕｌｌ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓

;jpn:◆もうしわけありません。↓
;jpn:　ただいまロッカールームが↓
;jpn:　いっぱいなんです。@KEY()↓
@!
_UNSOU_TEL_MES_5B;
◆Ｉ’ｍ　ｓｏｒｒｙ．↓
　　Ｏｕｒ　ｓｔｏｒａｇｅ　ｌｏｃｋｅｒｓ　ａｒｅ　ａｌｌ　ｆｕｌｌ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓

;jpn:◆もうしわけありませんね。↓
;jpn:　いまロッカールームが↓
;jpn:　いっぱいなんですよ。@KEY()↓
@!

_UNSOU_TEL_MES_6;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_6B)
◆Ｙｏｕ　ｗｏｕｌｄ　ｌｉｋｅ　ｕｓ　ｔｏ　ｄｅｌｉｖｅｒ　ｓｏｍｅｔｈｉｎｇ？　　Ｗｅ　ｃａｎ　ｄｅｌｉｖｅｒ　ｕｐ　ｔｏ　ｔｈｒｅｅ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｐｌｅａｓｅ　ｓｅｌｅｃｔ　ｔｈｅ　ｇｏｏｄｓ　ｙｏｕ　ｗａｎｔ．@KEY()
  
;jpn:◆おとどけですね↓
;jpn:　３つまで　おとどけできます。@KEY()↓
;jpn:◆では　グッズを↓
;jpn:　せんたくしてください。@KEY()
@!
_UNSOU_TEL_MES_6B;
◆Ｙｏｕ　ｗｏｕｌｄ　ｌｉｋｅ　ｕｓ　ｔｏ　ｄｅｌｉｖｅｒ　ｓｏｍｅｔｈｉｎｇ？　　Ｗｅ　ｃａｎ　ｄｅｌｉｖｅｒ　ｕｐ　ｔｏ　ｔｈｒｅｅ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｐｌｅａｓｅ　ｓｅｌｅｃｔ　ｔｈｅ　ｇｏｏｄｓ　ｙｏｕ　ｗａｎｔ．@KEY()

;jpn:◆おとどけですね↓
;jpn:　３つまで　おとどけできますよ。@KEY()↓
;jpn:◆さっそく　グッズを↓
;jpn:　せんたくしてください。@KEY()
@!

_UNSOU_TEL_MES_7;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_7B)
◆Ｗｅ’ｌｌ　ｓｅｎｄ　ｓｏｍｅｏｎｅ　ｏｖｅｒ　ｒｉｇｈｔ　ａｗａｙ！@KEY()
 
;jpn:◆かかりのものが↓
;jpn:　すぐ　うかがいます。@KEY()
@!
_UNSOU_TEL_MES_7B;
◆Ｉ’ｌｌ　ｃｏｍｅ　ａｎｄ　ｈｅｌｐ　ｙｏｕ　ｐｅｒｓｏｎａｌｌｙ！@KEY()↓

;jpn:◆わたくし　みずから↓
;jpn:　うかがいます！@KEY()↓
@!

_UNSOU_TEL_MES_8;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_8B)
@SET_LOOPREG(PC_NESS)
@GOSUB(MSG_SUB_Q_DEAD)
@TRUE_GOTO(_UNSOU_TEL_EMPTY_NESS_DEAD)
◆Ｈｅｙ　ｂｉｇ　ｂｒｏｔｈｅｒ　@DSP_STS(STS_PC_NAME_NES)，↓
　　ｗｅ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｏｆ　ｙｏｕｒ　ｓｔｕｆｆ　ｉｎ　ｓｔｏｒａｇｅ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓

;jpn:◆@DSP_STS(STS_PC_NAME_NES)おにいちゃん↓
;jpn:　にもつなんか↓
;jpn:　あずかってないわよ。@KEY()↓
@!
_UNSOU_TEL_EMPTY_NESS_DEAD;
@GET_ORDER_PLAYER(1)
@XCHG()
;＠ポーラだったらマアム？
◆Ｓｉｒ，　ｗｅ　ｄｏ　ｎｏｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｓｔｏｒｅｄ　ｆｏｒ　ａ　ａ　ｓｏｍｅｏｎｅ@KEY()↓
◆ｂｙ　ｔｈｅ　ｎａｍｅ　ｏｆ　@DSP_NAME(0)．@KEY()↓

;jpn:◆げんざい　@DSP_NAME(0)さまからは↓
;jpn:　おにもつを↓
;jpn:　あずかっておりませんが。@KEY()↓
@!
_UNSOU_TEL_MES_8B;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｗｅ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｏｆ　ｙｏｕｒｓ　ｉｎ　ｓｔｏｒａｇｅ．@KEY()↓

;jpn:◆どうも　おたくのにもつは↓
;jpn:　あずかってないようですねぇ。@KEY()↓
@!

_UNSOU_TEL_MES_9;
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_TEL_MES_9B)
◆Ｈｅｌｌｏ！↓
　　Ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆Ｉ’ｍ　ｖｅｒｙ　ｓｏｒｒｙ，　ｂｕｔ　ａｌｌ　ｏｕｒ　ｄｅｌｉｖｅｒｙ　ｐｅｏｐｌｅ　ａｒｅ　ｏｕｔ，　ｓｅｒｖｉｎｇ　ｏｔｈｅｒ　ｃｕｓｔｏｍｅｒｓ．@KEY()↓
◆Ｗｅ　ｃａｎ’ｔ　ｔａｋｅ　ａｎｙ　ｄｅｌｉｖｅｒｙ　ｏｒｄｅｒｓ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓
◆Ｐｌｅａｓｅ　ｃａｌｌ　ｂａｃｋ　ａ　ｌｉｔｔｌｅ　ｌａｔｅｒ．@KEY()

;jpn:◆こんにちは↓
;jpn:　エスカルゴうんそうでーす。@KEY()↓
;jpn:◆もうしわけありませんが‥‥@KEY()↓
;jpn:◆ただいま　はいたついんが↓
;jpn:　ではらっておりますので↓
;jpn:　うけつけられないんです。@KEY()↓
;jpn:◆また　おかけなおしください。@KEY()
@!
_UNSOU_TEL_MES_9B;
◆Ｈｅｌｌｏ，　ｙｏｕ　ｈａｖｅ　ｒｅａｃｈｅｄ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆Ａｌｌ　ｏｆ　ｏｕｒ　ｓｔａｆｆ　ｍｅｍｂｅｒｓ　ａｒｅ　ｃｕｒｒｅｎｔｌｙ　ｏｕｔ　ｏｆ　ｔｈｅ　ｏｆｆｉｃｅ．@KEY()↓
◆Ｐｌｅａｓｅ　ｃａｌｌ　ａｇａｉｎ．↓
　　Ｔｈｉｓ　ｉｓ　ａ　ｒｅｃｏｒｄｉｎｇ．@KEY()
 
;jpn:◆こちらは↓
;jpn:　エスカルゴうんそうです。@KEY()↓
;jpn:◆このでんわは↓
;jpn:　るすばんでんわです。@KEY()↓
;jpn:◆げんざい　しゃいんぜんいん↓
;jpn:　がいしゅつしておりますので↓
;jpn:　あらためておかけなおしください。@KEY()
@!

;
;エスカルゴ運送＿預かり
;

MSG_UNSOU_LEAVE;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_UNSOU_B)
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL)
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_LEAVE_WINGIEGU)	;ギーグに勝った後
◆Ｈｅｌｌｏ，　ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ！@KEY()↓
◆Ｙｏｕｒ　ｄｅｌｉｖｅｒｙ　ｃｈａｒｇｅ　ｉｓ　＄１８．@KEY()↓
◆Ｙｏｕ　ｃａｎ　ｃｏｖｅｒ　ｔｈｅ　ｂｉｌｌ，　ｒｉｇｈｔ？↓

;jpn:◆エスカルゴうんそうでーす！↓
;jpn:　おあずかりりょうきんは↓
;jpn:　１８ドルです。@KEY()↓
;jpn:◆おかね　もってますよね？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_UNSOU_LEAVE_MONEY_CHK,_UNSOU_LEAVE_NO)
_UNSOU_LEAVE_NO;
◆Ｏｈ，　Ｉ　ｓｅｅ．↓
　　Ｐｌｅａｓｅ　ｔｒｙ　ｕｓ　ａｇａｉｎ．

;jpn:◆そうですか。↓
;jpn:　また　よろしく。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_WINGIEGU;
◆Ｈｉ，　Ｉ’ｍ　ｆｒｏｍ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．@KEY()↓
◆Ｉ’ｍ　ｈｅｒｅ　ｔｏ　ｐｉｃｋ　ｕｐ　ｙｏｕｒ　ｓｔｕｆｆ．@KEY()↓

;jpn:◆エスカルゴうんそうでーす！↓
;jpn:　にもつをうけとりにきました。@KEY()↓
@GOTO(_UNSOU_LEAVE_SEL)

_UNSOU_LEAVE_MONEY_CHK;
@Q_MONEY(18)
@TRUE_GOTO(_UNSOU_LEAVE_NOMONEY)
_UNSOU_LEAVE_SEL;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔａｋｅ？@KEY()↓
◆Ｉ　ｃａｎ　ｔａｋｅ　ｕｐ　ｔｏ　ｔｈｒｅｅ　ｔｈｉｎｇｓ．@KEY()

;jpn:◆どれをおあずかりしましょう？↓
;jpn:　３つまでならＯＫですよ。@KEY()
@DSP_PL()
_UNSOU_LEAVE_SEL_1;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_NO)	;キャンセル？
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_1)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(1,0)
◆@DSP_GOODS(0)？
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
←
　　Ｗｉｌｌ　ｔｈｅｒｅ　ｂｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆@DSP_GOODS(0)ですね。
;@Q_TRACY(PC_NESS,1)
;@CMP(2,0)
;@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
;←
;jpn:　まだ　ほかに　ありますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_SEL_2,_UNSOU_LEAVE_Q_OK)
@GOTO(_UNSOU_LEAVE_Q_OK)
_UNSOU_LEAVE_SEL_2;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔａｋｅ？↓

;jpn:◆どれをおあずかりしましょう？↓
_UNSOU_LEAVE_SEL_2B;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK)	;キャンセル？
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_2)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(2,0)
◆@DSP_GOODS(0)？↓
@Q_TRACY(PC_NESS,1)
@CMP(2,0)
@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
←
　　Ｗｉｌｌ　ｔｈｅｒｅ　ｂｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆@DSP_GOODS(0)ですね。
;@Q_TRACY(PC_NESS,1)
;@CMP(2,0)
;@TRUE_GOTO(_UNSOU_LEAVE_GOODSFULL_2)
;←
;jpn:　まだ　ほかに　ありますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_SEL_3,_UNSOU_LEAVE_Q_OK)
@GOTO(_UNSOU_LEAVE_Q_OK)
_UNSOU_LEAVE_SEL_3;
◆Ｗｈｉｃｈ　ｏｎｅ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔａｋｅ？↓

;jpn:◆どれをおあずかりしましょう？↓
_UNSOU_LEAVE_SEL_3B;
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK)	;キャンセル？
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_UNSOU_LEAVE_UNABLE_3)
@LOAD_REG()
@SET_TRANS_GOODS(0,0)
@GET_TRANS_GOODS(3,0)
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
_UNSOU_LEAVE_Q_OK;
◆Ｌｅｔ　ｍｅ　ｊｕｓｔ　ｃｏｎｆｉｒｍ　ｙｏｕｒ　ｒｅｑｕｅｓｔ．　　Ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔａｋｅ@KEY()↓
;◆@DSP_GOODS(0)
;　　@DSP_GOODS(0)
;　　ａｎｄ　　@DSP_GOODS(0)．
;◆Ｉｓ　ｔｈｉｓ　ｃｏｒｒｅｃｔ？　

;jpn:◆かくにんします↓
;jpn:　おあずかりするのは@KEY()↓
@GET_TRANS_GOODS(1,0)
◆ｔｈｅ　@DSP_GOODS(0)
;◆@DSP_GOODS(0)，
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK_2)
↓
　　ｔｈｅ　@DSP_GOODS(0)
;　@DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_LEAVE_Q_OK_2)
↓
;jpn:　あと　@DSP_GOODS(0)
　　ａｎｄ　ｔｈｅ　@DSP_GOODS(0)．
_UNSOU_LEAVE_Q_OK_2;
@KEY()↓
◆Ｉｓ　ｔｈｉｓ　ｃｏｒｒｅｃｔ？↓

;jpn:◆いじょうで　よろしいですか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_LEAVE_OK,_UNSOU_LEAVE_ONEMORE)
@GOTO(_UNSOU_LEAVE_ONEMORE)
_UNSOU_LEAVE_OK;
@MONEYOUT(18)
@CHKF(FLG_WIN_GIEGU)
@ONGOSUB(_UNSOU_OK_WINGIEGU)	;ギーグ倒した後
@WINR_MONEY()
@SE(SE_se76_my_give)
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
◆Ａｌｌ　ｒｉｇｈｔ，　ｃｅｒｔａｉｎｌｙ，↓
　　ｔｈａｎｋｓ　ａ　ｌｏｔ！

;jpn:◆はい　たしかに↓
;jpn:　ありやと　あんしたー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_ONEMORE;
@GET_TRANS_GOODS(1,1)
@GOODSIN_PLAYER(0,0)
@GET_TRANS_GOODS(2,1)
@FALSE_GOTO(_UNSOU_LEAVE_ONEMORE_2)
@GOODSIN_PLAYER(0,0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_UNSOU_LEAVE_ONEMORE_2)
@GOODSIN_PLAYER(0,0)
_UNSOU_LEAVE_ONEMORE_2;
◆Ｗｅｌｌ，　ｌｅｔ’ｓ　ｓｔａｒｔ　ａｇａｉｎ，　ｓｈａｌｌ　ｗｅ？@KEY()

;jpn:◆では　もういっぺん↓
;jpn:　おねがいします。@KEY()
@GOTO(_UNSOU_LEAVE_SEL_1)

_UNSOU_LEAVE_UNABLE_1;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_1)

_UNSOU_LEAVE_UNABLE_2;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_2B)

_UNSOU_LEAVE_UNABLE_3;
@GOSUB(_SUB_UNSOU_LEAVE_UNABLE_MES)
@GOTO(_UNSOU_LEAVE_SEL_3B)

_UNSOU_LEAVE_GOODSFULL;
◆Ｅｘｃｕｓｅ　ｍｅ．@KEY()↓
◆Ｗｅ　ｃｈｅｃｋｅｄ　ｙｏｕｒ　ｒｅｃｏｒｄｓ　ａｎｄ　ｆｏｕｎｄ@KEY()↓
◆ｔｈａｔ　ｗｅ　ａｒｅ　ａｌｒｅａｄｙ　ｓｔｏｒｉｎｇ　ｔｏｏ　ｍａｎｙ　ｏｆ　ｙｏｕｒ　ｉｔｅｍｓ．@KEY()↓
◆Ｗｅ　ｃａｎｎｏｔ　ａｃｃｅｐｔ　ａｎｙ　ｍｏｒｅ　ｇｏｏｄｓ　ｆｒｏｍ　ｙｏｕ　ａｔ　ｔｈｉｓ　ｔｉｍｅ．@KEY()↓
◆Ｐｌｅａｓｅ　ｃｏｎｔａｃｔ　ｕｓ　ｌａｔｅｒ　ｗｈｅｎ　ｗｅ　ｍａｙ　ｈａｖｅ　ｓｐａｃｅ　ｆｏｒ　ｙｏｕｒ　ｉｔｅｍｓ．

;jpn:◆すいません。↓
;jpn:　あずかりしょを　しらべなおしたら↓
;jpn:　いっぱいでした。@KEY()↓
;jpn:◆じゃ　また　よろしくー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_LEAVE_GOODSFULL_2;
@KEY()↓
◆Ｗｅ’ｒｅ　ｓｏｒｒｙ，　ｗｅ　ｃａｎｎｏｔ　ｃａｒｒｙ　ｍｏｒｅ　ｔｈａｎ　ｔｈｒｅｅ　ｉｔｅｍｓ．@KEY()↓
◆Ｐｌｅａｓｅ　ｕｎｄｅｒｓｔａｎｄ　ｏｕｒ　ｐｏｌｉｃｙ．@KEY()↓
;jpn:◆あ　もうこれいじょう↓
;jpn:　あずかれないんで↓
;jpn:　ここまでにしてください。@KEY()↓
@GOTO(_UNSOU_LEAVE_Q_OK)

_UNSOU_LEAVE_NOMONEY;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓
◆Ｃａｌｌ　ｕｓ　ａｔ　ａｎｏｔｈｅｒ　ｔｉｍｅ．
;jpn:◆おかね　たりないですね。↓
;jpn:　また　よろしく。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

;
;エスカルゴ運送＿お届け
;

MSG_UNSOU_SEND;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_UNSOU)
◆Ｉ’ｍ　ｆｒｏｍ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ！！@KEY()↓
;jpn:◆エスカルゴうんそうでーっす！@KEY()↓
◆Ｉ’ｍ　ｈｅｒｅ　ｔｏ　ｄｅｌｉｖｅｒ　ｙｏｕｒ@KEY()↓
@GET_TRANS_GOODS(1,0)
;　　@DSP_GOODS(0)，
;　　@DSP_GOODS(0)，　
;　　ａｎｄ　@DSP_GOODS(0)．

◆@DSP_GOODS(0)，
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_SEND_2)
;jpn:と↓
↓
　　@DSP_GOODS(0)，

;　@DSP_GOODS(0)
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_SEND_2)
↓
;jpn:　あと　@DSP_GOODS(0)
　　ａｎｄ　@DSP_GOODS(0)
_UNSOU_SEND_2;
．@KEY()↓
;jpn:◆いじょうを↓
;jpn:　おとどけに　まいりましたー。@KEY()↓
@CHKFGOTO(FLG_WIN_GIEGU,_UNSOU_SEND_GOODS_1)	;ギーグ倒した後
◆Ｙｏｕｒ　ｃｈａｒｇｅ　ｉｓ　＄１８．↓
　　Ｙｏｕ　ｃａｎ　ｐａｙ　ｆｏｒ　ｔｈｉｓ，　ｒｉｇｈｔ？@KEY()↓

;jpn:◆りょうきんは　１８ドルです。↓
;jpn:　おかね　もってますよね？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_UNSOU_SEND_YES,_UNSOU_SEND_NO_1)
_UNSOU_SEND_NO_1;			;キャンセル
◆Ｗｅｌｌ，　Ｉ　ｎｅｅｄ　ｔｏ　ｔａｋｅ　ｔｈｅｓｅ　ｔｈｉｎｇｓ　ｂａｃｋ　ｔｈｅｎ．@KEY()↓
◆Ｉｓ　ｔｈａｔ　ＯＫ？↓

;jpn:◆じゃ　にもつは↓
;jpn:　もってかえりますけど@KEY()↓
;jpn:◆いいすか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_SEND_BYE,_UNSOU_SEND_NO_2)
_UNSOU_SEND_NO_2;
◆Ｈｍｍｍ，　ｗｈａｔ　ｓｈｏｕｌｄ　Ｉ　ｄｏ？@KEY()↓
◆Ｙｏｕ　ａｃｔｕａｌｌｙ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｒｉｇｈｔ？↓

;jpn:◆こまったなー。@KEY()↓
;jpn:◆おかね　ほんとは↓
;jpn:　あるんでしょ？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_UNSOU_SEND_YES,_UNSOU_SEND_NO_1)
@GOTO(_UNSOU_SEND_NO_1)
_UNSOU_SEND_BYE;
◆Ｏｋａｙ．↓
　　Ｃａｌｌ　ｕｓ　ａｇａｉｎ　ｌａｔｅｒ．

;jpn:◆そうですか。↓
;jpn:　また　よろしくー。
@KEYNP()
_UNSOU_SEND_END;
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_SEND_YES;
@Q_MONEY(18)
@TRUE_GOTO(_UNSOU_SEND_NOMONEY)
@GET_TRANS_GOODS(1,0)
_UNSOU_SEND_GOODS_1;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL)
@GOODSIN_PLAYER(0,0)
@MONEYOUT(18)
_UNSOU_SEND_GOODS_2;
@GET_TRANS_GOODS(2,0)
@FALSE_GOTO(_UNSOU_SEND_ALLOK)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL_2)
@GOODSIN_PLAYER(0,0)
_UNSOU_SEND_GOODS_3;
@GET_TRANS_GOODS(3,0)
@FALSE_GOTO(_UNSOU_SEND_ALLOK)
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_UNSOU_SEND_GOODSFULL_3)
@GOODSIN_PLAYER(0,0)
_UNSOU_SEND_ALLOK;
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(1,1)
@GET_TRANS_GOODS(2,1)
@GET_TRANS_GOODS(3,1)
@!

_UNSOU_SEND_GOODSFULL;			;グッズ欄いっぱい
◆Ｏｈ，　ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．↓
　　Ｐｌｅａｓｅ　ｃａｌｌ　ｕｓ　ａｇａｉｎ　ｌａｔｅｒ．

;jpn:◆あれ　にもつが↓
;jpn:　いっぱいですね。↓
;jpn:　じゃ　また　よろしくー。
@KEYNP()
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_UNSOU_SEND_GOODSFULL_2;		;グッズ欄いっぱい
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ　ｅｖｅｒｙｔｈｉｎｇ．@KEY()↓

;jpn:◆あれ　ぜんぶは↓
;jpn:　もてないみたいですね。@KEY()↓
@GET_TRANS_GOODS(1,1)
◆Ｗｅｌｌ，　　Ｉ’ｌｌ　ｌｅａｖｅ　ｊｕｓｔ↓
　　ｔｈｅ　@DSP_GOODS(0)．@KEY()↓

;jpn:◆じゃ　@DSP_GOODS(0)だけ↓
;jpn:　おわたししておきます。@KEY()↓
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(2,1)
@TRACY_IN(0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_SUB_UNSOU_GOODSFULL_2_END)
@TRACY_IN(0)
_SUB_UNSOU_GOODSFULL_2_END;
@!

_UNSOU_SEND_GOODSFULL_3;		;グッズ欄いっぱい
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ　ｅｖｅｒｙｔｈｉｎｇ．@KEY()↓

;jpn:◆あれ　ぜんぶは↓
;jpn:　もてないみたいですね。@KEY()↓
@GET_TRANS_GOODS(1,1)
◆Ｗｅｌｌ，　Ｉ’ｌｌ　ｌｅａｖｅ　ｊｕｓｔ↓
　　ｔｈｅ　@DSP_GOODS(0)↓
　　ａｎｄ
@GET_TRANS_GOODS(2,1)
　ｔｈｅ　@DSP_GOODS(0)．@KEY()↓

;jpn:◆じゃ　@DSP_GOODS(0)と↓
;@GET_TRANS_GOODS(2,1)
;jpn:　@DSP_GOODS(0)だけ↓
;jpn:　おわたししておきます。@KEY()↓
@GOSUB(_SUB_UNSOU_SEND_OK_MES)
@GET_TRANS_GOODS(3,1)
@TRACY_IN(0)
@!

_UNSOU_SEND_NOMONEY;			;お金足りない。
◆Ａｈ，　Ｉ　ｓｅｅ．．．Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．↓
　　Ｃａｌｌ　ｕｓ　ａｇａｉｎ　ｌａｔｅｒ．
@KEYNP()
;jpn:◆あれ？　おかね　たりないですね。↓
;jpn:　じゃ　また　よろしく。
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

MSG_UNSOU_SEND_RETRY_OVER;
@GOSUB(_SUB_UNSOU_TRANS_RETURN_TRACY)
MSG_UNSOU_LEAVE_RETRY_OVER;
@CLRF(FLG_DELIVERY_UNSOU)
@CLRF(FLG_DELIVERY_UNSOU_B)
@GOSUB(MSG_SUB_ZYUSHIN_CALL)
@OPEN(1)
◆Ｈｅｌｌｏ！↓
　　Ｔｈｉｓ　ｉｓ　Ｅｓｃａｒｇｏ　Ｅｘｐｒｅｓｓ．↓
　（ｈｅｅ，ｈａ，ｈｅ，ｈａ）@KEY()↓
◆Ｉ　ｊｕｓｔ　（ｈｅｅ，ｈａ，ｈｅ，ｈａ）ｃｏｕｌｄｎ’ｔ　ｆｉｎｄ　ｙｏｕｒ　ｌｏｃａｔｉｏｎ．．．@KEY()↓
◆．．．Ｙｏｕ　ｍｕｓｔ　ｂｅ　ｓｏｍｅｗｈｅｒｅ　ｒｅａｌｌｙ　ｓｔｒａｎｇｅ．（ｈｅｅ，ｈａ，ｈｅ，ｈａ）@KEY()↓
◆Ｉ’ｖｅ　ｄｅｃｉｄｅｄ，　ｈｏｎｅｓｔｌｙ，　ｔｈａｔ．．．Ｉ　ｓｈｏｕｌｄ　ｇｉｖｅ　ｕｐ．@KEY()↓
◆Ｉ’ｍ　ｏｕｔｔａ　ｈｅｒｅ．（ｈｅｅ，ｈａ，ｈｅ，ｈａ）@KEY()↓
◆Ｓｏｍｅｔｉｍｅｓ　ｃｒａｐ　ｌｉｋｅ　ｔｈｉｓ　ｈａｐｐｅｎｓ，　ｙｏｕ　ｋｎｏｗ？@KEY()
;jpn:◆もしもーし↓
;jpn:　エスカルゴうんそうでーす。@WI(20)↓
;jpn:　（ハアハア）@KEY()↓
;jpn:◆おたくさまが（ハアハア）↓
;jpn:　おいでになるばしょが@WI(15)↓
;jpn:　みつからなくて‥‥@KEY()↓
;jpn:◆‥‥きっと　へんなところに↓
;jpn:　いるんでしょうねぇ。@WI(20)↓
;jpn:　（ハアハア）@KEY()↓
;jpn:◆わたし　もう　まごころこめて↓
;jpn:　‥‥あきらめましたから。@WI(20)↓
;jpn:　かえります。（ハアハア）@KEY()↓
;jpn:◆こういうことも↓
;jpn:　たまには　あるんですねぇ。@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!

_SUB_HANGUP_MES;
←
@SE(SE_se0b_tel_put)
◆（Ｃｌｉｃｋ！）

;jpn:◆ガチャン　ツーツーツー。
@KEYNP()
@!

_SUB_UNSOU_SEND_OK_MES;
@CHKF(FLG_WIN_GIEGU)
@ONGOSUB(_UNSOU_OK_WINGIEGU)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆ＯＫ，　ｈｅｒｅ　ｗｅ　ａｒｅ．↓
　　Ｔｈａｎｋ　ｙｏｕ！

;jpn:◆ハイ　たしかに。↓
;jpn:　ありやと　やんしたー。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!
_UNSOU_OK_WINGIEGU;
@MONEYIN(18)
@!

_SUB_UNSOU_LEAVE_UNABLE_MES;
◆Ｉ　ｔｈｉｎｋ　ｙｏｕ　ｓｈｏｕｌｄ　ｋｅｅｐ　ｉｔ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｔａｋｅ？@KEY()

;jpn:◆それは　もっていたほうが↓
;jpn:　いいと　おもいますが。↓
;jpn:　ほかに　ありますか。@KEY()
@!

MSG_SUB_UNSOU_TRANS_RETURN_TRACY;
_SUB_UNSOU_TRANS_RETURN_TRACY;
@GET_TRANS_GOODS(1,1)
@TRACY_IN(0)
@GET_TRANS_GOODS(2,1)
@FALSE_GOTO(_TRANS_RETRA_END)
@TRACY_IN(0)
@GET_TRANS_GOODS(3,1)
@FALSE_GOTO(_TRANS_RETRA_END)
@TRACY_IN(0)
_TRANS_RETRA_END;
@!

;
;トレーシー
;

MSG_TRACY;
◆Ｏｈ，　ｉｔ’ｓ　ｍｙ　ｌｉｎｅ　ｎｏｗ？　Ｏｏｏｐｓ！↓

;jpn:◆あ　わたしの　でばんね？↓
MSG_TRACY_GLOBAL_START;汎用のトレーシー呼び出し（三浦）
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_TRACY_YES,_TRACY_NO)
_TRACY_NO;
◆Ｗｈａｔ　ｔｈｅ　ｈｅｙ？↓
　　Ｗｅｌｌ，　ｓｅｅ　ｙｏｕ！
;jpn:◆なーんだ。@WI(15)↓
;jpn:　じゃ　またね！
@KEYNP()
』
MSG_TRACY_GLOBAL_START2;最終戦闘後
_TRACY_YES;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｄｏ？↓

;jpn:◆ごようは　なーに？↓
_TRACY_SEL;
;@SAVE_WIN()
;@DSP_PL()
;@OPEN(37)
<ｓｔｏｒｅ>
<ｃｈｅｃｋ　ｏｕｔ>
;jpn:<あずける>
;jpn:<もちだす>
@DSP_ITEM(2)
;@DSP_ITEML(1)
;@SELQ()
;@SAVE_GLOBAL_REG()
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@ONGOTO(MSG_TRACY_AZUKERU,_TRACY_MOTIDASU)
@SELGOTO(MSG_TRACY_AZUKERU,_TRACY_MOTIDASU)

_TRACY_END;
@CHKFGOTO(FLG_WIN_GIEGU,_TRACY_END_FINAL)
◆Ｗｅｌｌ，　ｔａｋｅ　ｃａｒｅ　ａｎｄ　Ｉ’ｌｌ　ｔａｌｋ　ｔｏ　ｙｏｕ　ｌａｔｅｒ！

;jpn:◆じゃ　きをつけてね！
@KEYNP()
@!
_TRACY_END_FINAL;最終戦闘後
◆Ｗｅｌｌ，　ｔａｋｅ　ｃａｒｅ　ａｎｄ　ｔａｌｋ　ｔｏ　ｙｏｕ　ｌａｔｅｒ！@KEY()↓
◆Ｏｈ，　Ｉ　ｓａｉｄ　”ｔａｋｅ　ｃａｒｅ”！@KEY()↓
◆Ｉｔ　ｊｕｓｔ　ｓｌｉｐｐｅｄ　ｏｕｔ　ｏｆ　ｍｙ　ｍｏｕｔｈ，@KEY()↓
◆ｊｕｓｔ　ｌｉｋｅ　Ｉ　ｗａｓ　ｔａｌｋｉｎｇ　ｔｏ　ｙｏｕ　ｗｈｅｎ　ｙｏｕ　ｗｅｒｅ　ｇｏｎｅ．．．
;jpn:◆じゃ　きをつけてね！@KEY()↓
;jpn:◆あら@WI(10)　いままでのくせで↓
;jpn:　きをつけてね‥‥@WI(15)なんて↓
;jpn:　いっちゃった。
@KEYNP()
』

MSG_TRACY_AZUKERU;				;預ける
@GOSUB(MSG_SUB_Q_GOODSEMPTY)
@FALSE_GOTO(_TRACY_GDSEMP)
@Q_TRACY(PC_NESS,1)			;預り所チェック
@CMP(2,0)
@TRUE_GOTO(_TRACY_TRACYFULL)		;預り所いっぱい？
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｔｏｒｅ？@KEY()

;jpn:◆なにを　あずける？@KEY()
@DSP_PL()
@GOSUB(MSG_SEL_GOODS)			;グッズ選択
←
@FALSE_GOTO(_TRACY_OTHER)		;キャンセル？
_TRACY_AZUKERU_OK;
@SAVE_REG()
@Q_TRACY(0,0)
@TRUE_GOTO(_TRACY_AZU_UNABLE)
@LOAD_REG()
@GET_PLAYER_GOODS(0,0)
@SE(SE_se76_my_give)
←
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｄｏｎ’ｔ　ｗｏｒｒｙ，　Ｉ’ｌｌ　ｋｅｅｐ　ｉｔ　ｓａｆｅ．@KEY()↓
 
;jpn:◆@DSP_GOODS(0)ね。↓
;jpn:　だいじに　しまっとくわ。@WI(15)@KEY()↓
@LOAD_REG()				;主レ=PLAYER_ID:副レ=GOODSの位置
@TRACY_IN_GOODS(0,0)			;預ける。

_TRACY_AZUKERU_NEXT;
←
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｔｈａｔ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｓｔｏｒｅ？↓
<ｙｅｓ>
<ｎｏ>

;jpn:◆ほかに　あずけるものは　ある？↓
;jpn:<ある>
;jpn:<ない>
@DSP_ITEM(2)
@SELGOTO(MSG_TRACY_AZUKERU,_TRACY_OTHER)
@GOTO(_TRACY_OTHER)

_TRACY_TRACYFULL;			;預り所いっぱい
←
◆Ｉ’ｍ　ｓｏｒｒｙ．↓
　　Ｍｙ　ｌｏｃｋｅｒ　ｉｓ　ｆｕｌｌ．@KEY()

;jpn:◆ごめんなさい。@WI(15)↓
;jpn:　ロッカールームが↓
;jpn:　いっぱいになっちゃったの。@KEY()
@GOTO(_TRACY_OTHER)

_TRACY_GDSEMP;
←
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｔｏｒｅ．@KEY()

;jpn:◆あずけるものが　ないみたい。@KEY()
@GOTO(_TRACY_OTHER)

_TRACY_AZU_UNABLE;
←
◆Ｉ　ｔｈｉｎｋ　ｙｏｕ　ｓｈｏｕｌｄ　ｈａｎｇ　ｏｎ　ｔｏ　ｔｈａｔ．@KEY()↓
;jpn:◆それは　もっていたほうが↓
;jpn:　いいと　おもうわ。@KEY()↓
@GOTO(_TRACY_AZUKERU_NEXT)

_TRACY_MOTIDASU;			;もちだす。
@SET_LOOPREG(1)				;空チェック
@GET_TRACY()
@FALSE_GOTO(_TRACY_EMPTY)		;空？
@Q_GOODSFULL(PC_ALL)			;全員のグッズ欄チェック。
@FALSE_GOTO(_TRACY_GOODSFULL)		;全員グッズ欄いっぱい？
←
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ↓
　　ｒｅｔｕｒｎｅｄ？@KEY()

;jpn:◆なにを　もっていくの？@KEY()
_TRACY_MOTIDASU_SEL;
;グッズ選択
@DSP_PL()
@SAVE_WIN()
;@SEL_TRACY_OUT()
_TRACY_MOTIDASU_SELB;
@SEL_TRACY_OUT()
←
@FALSE_GOTO(_TRACY_OTHER_PRE)
;プレーヤー選択
@XCHG()
@SAVE_REG()
@SAVE_WIN()
@GOSUB(MSG_SEL_GOODSIN_T)
@FALSE_GOTO(_TRACY_MOTIDASU_SEL_2)
;グッズ選択→プレーヤー選択した
@SAVE_GLOBAL_REG()
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@SE(SE_se74_my_get)
@TRACY_OUT_GOODS(0,0)
@GET_PLAYER_GOODS(0,0)
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｔａｋｅ　ｇｏｏｄ　ｃａｒｅ　ｏｆ　ｉｔ．@KEY()↓

;jpn:◆@DSP_GOODS(0)ね。@WI(15)↓
;jpn:　だいじに　してね。@WI(15)@KEY()↓
_TRACY_MOTIDASU_OTHER;
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｙｏｕ　ｗａｎｔ　ｒｅｔｕｒｎｅｄ？↓
<ｙｅｓ>
<ｎｏ>

;jpn:◆ほかに　もっていくものは　ある？↓
;jpn:<ある>
;jpn:<ない>
@DSP_ITEM(2)
@SELGOTO(_TRACY_MOTIDASU,_TRACY_OTHER)
@GOTO(_TRACY_OTHER)

_TRACY_MOTIDASU_SEL_2;
@XCHG()
@DSP_PL()
;@WIN_SEL_ITEMQ(13)
@GOTO(_TRACY_MOTIDASU_SELB)

_TRACY_EMPTY;
←
◆Ｉ’ｍ　ｎｏｔ　ｓｔｏｒｉｎｇ　ａｎｙ　ｏｆ　ｙｏｕｒ　ｓｔｕｆｆ．@KEY()↓

;jpn:◆なにも　あずかってないわよ。@KEY()↓
@GOTO(_TRACY_OTHER)			;キャンセル？

_TRACY_GOODSFULL;			;もちものいっぱい
←
◆Ｉ　ｔｈｉｎｋ　ｙｏｕ　ａｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓

;jpn:◆もちものが　いっぱいみたいね。@KEY()↓
@GOTO(_TRACY_OTHER)

_TRACY_OTHER_PRE;
@SELECT_WIN(13)
@CLOSE()
@SELECT_WIN(1)
_TRACY_OTHER;				;他の用事ある？
←
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｆｒｏｍ　ｍｅ？↓

;jpn:◆ほかにも　ようじはある？↓
@GOTO(_TRACY_SEL)

_TRACY_SELPLAYER_GOODSFULL;
←
◆Ｉ　ｔｈｉｎｋ　@DSP_NAME(0)　ｉｓ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　もちものが　いっぱいみたいよ。@KEY()
@!

;-------------------------------------------------
MSG_UNSOU_TEL_TACO;
◆Ａｒｅ　ｙｏｕ　ｃａｌｌｉｎｇ　ａｂｏｕｔ　ｔｈｅ　ｄｅｌｉｖｅｒｙ　ｏｆ　ｔｈｅ　”Ｐｅｎｃｉｌ　Ｅｒａｓｅｒ”？↓
<ｙｅｓ>
<ｎｏ>

;jpn:◆あ　「タコけしマシン」の↓
;jpn:　おとどけね？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_TACO_YES,_UNSOU_TEL_TACO_NO)
_UNSOU_TEL_TACO_NO;
◆Ｏｈ，　ｔｈａｔ’ｓ　ｎｏｔ　ｗｈａｔ　ｙｏｕ　ｗａｎｔ？@KEY()↓

;jpn:◆あら　ちがうの？@KEY()↓
@GOTO(_UNSOU_TEL_SEL_MAIN)

_UNSOU_TEL_TACO_YES;
◆Ｗｅ’ｌｌ　ｓｅｎｄ　ｓｏｍｅｏｎｅ　ｒｉｇｈｔ　ａｗａｙ．@KEY()↓

;jpn:◆それでは　かかりのものが↓
;jpn:　すぐ　うかがいまーす。@KEY()↓
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_DELIVERY_UNSOU_TAKOKESHI)
@DELIVERY(DELIVERY_UNSOU_TAKOKESHI)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
』

MSG_UNSOU_TEL_TAKA;
◆Ｔｈｉｓ　ｉｓ　ａｂｏｕｔ　ｔｈｅ　ｄｅｌｉｖｅｒｙ　ｏｆ　ｔｈｅ　”Ｈａｗｋ　Ｅｙｅ”？↓
<ｙｅｓ>
<ｎｏ>

;jpn:◆あ　「タカのめ」の↓
;jpn:　おとどけね？↓
;jpn:　　<はい>　　<いいえ>
@DSP_ITEM(2)
@SELGOTO(_UNSOU_TEL_TAKA_YES,_UNSOU_TEL_TAKA_NO)
_UNSOU_TEL_TAKA_NO;
◆Ｏｈ，　ｔｈａｔ’ｓ　ｎｏｔ　ｗｈａｔ　ｙｏｕ　ｗａｎｔ？@KEY()↓

;jpn:◆あら　ちがうの？@KEY()↓
@GOTO(_UNSOU_TEL_SEL_MAIN)

_UNSOU_TEL_TAKA_YES;
◆Ｗｅ’ｌｌ　ｓｅｎｄ　ｓｏｍｅｏｎｅ　ｒｉｇｈｔ　ａｗａｙ．@KEY()↓

;jpn:◆それでは　かかりのものが↓
;jpn:　すぐ　うかがいまーす。@KEY()↓
@GOSUB(_SUB_HANGUP_MES)
@SETF(FLG_DELIVERY_UNSOU_TAKANOME)
@DELIVERY(DELIVERY_UNSOU_TAKANOME)
@SETF(FLG_SYS_DISTLPT);テレポート禁止
』
;-------------------------------------------------
;
;マッハピザ（電話）
;

MSG_TEL_PIZZA;
◆Ｈｅｌｌｏ！　Ｔｈｉｓ　ｉｓ　Ｍａｃｈ　Ｐｉｚｚａ！

;jpn:◆マッハピザでーす。
@CHKFGOTO(FLG_WIN_GIEGU,_PIZZA_PHONE_END)
@GOSUB(MSG_SUB_Q_NOW_DELIVERY)
@TRUE_GOTO(_PIZZA_NOW_DELIVERY)
@CHKFGOTO(FLG_DELIVERY_PIZZA,_PIZZA_NOW_DELIVERY)

_TEL_PIZZA_ORDER
　　Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｏｒｄｅｒ？@KEY()↓
←
;jpn:　ごちゅうもんは？@KEY()↓
@SAVE_WIN()
@OPEN(37)
<ｓｍａｌｌ>
<ｍｅｄｉｕｍ>
<ｌａｒｇｅ>

;jpn:<スモール>
;jpn:<ミディアム>
;jpn:<ラージ>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@ONGOTO(_TEL_PIZZA_SMALL,_TEL_PIZZA_MED,_TEL_PIZZA_LARGE)

_PIZZA_NO;				;キャンセル
◆Ｃａｌｌ　ａｇａｉｎ！@KEY()↓

;jpn:◆また↓
;jpn:　おねがいしまーす。@KEY()↓
@GOTO(_TEL_PIZZA_END)

_TEL_PIZZA_MED;				;ミディアム（売り切れ）
◆Ｓｏｒｒｙ，　ｔｈｅｙ　ａｒｅ　ａｌｌ　ｓｏｌｄ　ｏｕｔ．↓

;jpn:◆すいません。↓
;jpn:　いま　うりきれなんです。↓
@GOTO(_TEL_PIZZA_ORDER)

_TEL_PIZZA_SMALL;			;スモール
◆Ｙｏｕ　ｗａｎｔ　ｏｎｅ　ｓｍａｌｌ　ｐｉｚｚａ？↓

;jpn:◆スモールサイズひとつですね。↓
@GOTO(_TEL_PIZZA_BYE)

_TEL_PIZZA_LARGE;			;ラージ
◆Ｙｏｕ　ｗａｎｔ　ｏｎｅ　ｌａｒｇｅ　ｐｉｚｚａ？↓

;jpn:◆ラージサイズひとつですね。↓
@SETF(FLG_PIZZA_SIZE)

_TEL_PIZZA_BYE;
@SET_REG(0)				;副レジ=GOODS_ID
　　Ｗｅ’ｌｌ　ｄｅｌｉｖｅｒ　ｉｔ　ｗｉｔｈｉｎ　３　ｍｉｎｕｔｅｓ．@KEY()↓

;jpn:　３ぷんいないに　おとどけに↓
;jpn:　あがりまーす。@KEY()↓
@SETF(FLG_DELIVERY_PIZZA)
@DELIVERY(DELIVERY_PIZZA)
@SETF(FLG_SYS_DISTLPT);テレポート禁止

_TEL_PIZZA_END;				;終了
@SE(SE_se0b_tel_put)
◆（Ｃｌｉｃｋ！）

;jpn:◆ガチャン　ツー　ツー　ツー
@KEYNP()
@!

_PIZZA_NOW_DELIVERY;
@KEY()↓
◆Ｏｕｒ　ｄｅｌｉｖｅｒｌｙｍｅｎ　ａｒｅ　ｎｏｔ　ａｖａｉｌａｂｌｅ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓
◆Ｗｅ　ｃａｎ’ｔ　ｄｅｌｉｖｅｒ　ａｎｙ　ｐｉｚｚａ　ｆｏｒ　ｔｈｅ　ｔｉｍｅ　ｂｅｉｎｇ．@KEY()↓

;jpn:◆ただいま　じゅうぎょういんが↓
;jpn:　ではらって　おりますので↓
;jpn:　はいたつが　できないんですよ。@KEY()↓
@GOTO(_PIZZA_NO)

_PIZZA_PHONE_END;
@KEY()↓
◆Ｏｕｒ　ｄｅｌｉｖｅｒｙ　ｍｅｎ　ｇｏｔ　ｔｉｒｅｄ　ａｎｄ　ｑｕｉｔ．@KEY()↓
◆Ｓｏ，　ｗｅ　ｄｅｃｉｄｅｄ　ｔｏ　ｃｌｏｓｅ　ｔｈｅ　ｓｈｏｐ．@KEY()↓
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｃｏｎｓｉｓｔｅｎｔｌｙ　ｕｓｉｎｇ　ｕｓ　ｆｏｒ　ａｌｌ　ｏｆ　ｙｏｕｒ　ｐｉｚｚａ　ｎｅｅｄｓ．@KEY()↓

;jpn:◆はいたつがかりが↓
;jpn:　つかれちゃって↓
;jpn:　やめちゃいましてね。@KEY()↓
;jpn:◆いっそ　みせを↓
;jpn:　たたむことに　したんですよ。@KEY()↓
;jpn:◆ながいあいだ↓
;jpn:　ありがとうございました。@WI(20)↓
@SE(SE_se0b_tel_put)
　　（Ｃｌｉｃｋ！）

;jpn:　ガチャン　ツーツーツー
@KEYNP()
』
;
;マッハピザ（届け屋）
;

MSG_PIZZA_SEND;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@RESF(FLG_DELIVERY_PIZZA)
◆Ｈｅｌｌｏ！　Ｍａｃｈ　Ｐｉｚｚａ　ｄｅｌｉｖｅｒｙ！↓
　　Ｈｅｒｅ　ｉｓ　ｙｏｕｒ　ｐｉｚｚａ　ｐｉｅ，　ｓｉｒ．@KEY()↓

;jpn:◆マッハピザでーす。↓
;jpn:　ピザを　とどけにきました。@KEY()↓

_PIZZA_CHK_GOODSFULL;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_PIZZA_GOODSFULL)
@SET_REG(0)
@SAVE_REG()				;副レジ=PLAYER_ID
@CHKFGOTO(FLG_PIZZA_SIZE,_PIZZA_LARGE)
@SET_LOOPREG(GDS_FOOD_PIZZA)
_PIZZA_MONEY;
@SET_REG(1)
@GOODS_TAKE_MONEY(0)			;主レジ=GOODSの値段:副レジ=GOODS_ID
@XCHG()
◆Ｔｈａｔ’ｌｌ　ｂｅ　＄@DSP_NUM(0)．↓
　　Ｙｏｕ　ｈａｖｅ　ｔｈｅ　ｍｏｎｅｙ，ｄｏｎ’ｔ　ｙｏｕ？↓

;jpn:◆@DSP_NUM(0)ドルです。↓
@SAVE_REG()
;jpn:　おかね　もってますよね？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_PIZZA_MONEY_YES,_PIZZA_MONEY_NO)
_PIZZA_MONEY_NO;				;キャンセル
◆Ｉ　ｓｅｅ．↓
　　Ｃａｌｌ　ｕｓ　ａｇａｉｎ．

;jpn:◆そうですか。↓
;jpn:　じゃ　また　よろしくー。
_PIZZA_END;				;終了。
@KEYNP()
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_PIZZA_LARGE;				;ラージサイズ時の処理
@CLRF(FLG_PIZZA_SIZE)			;フラグリセット
@SET_LOOPREG(GDS_FOOD_PIZZA_LARGE)
@GOTO(_PIZZA_MONEY)

_PIZZA_MONEY_YES;
_PIZZA_CHK;
@Q_MONEY(0)
@TRUE_GOTO(_PIZZA_NOMONEY)		;所持金足りる？
@LOAD_REG()
@XCHG()
@Q_GOODSFULL(PC_ALL)			;持ち物いっぱい？
@FALSE_GOTO(_PIZZA_GOODSFULL)
@GOODSIN_PLAYER(0,0)			;グッズ欄に
@LOAD_REG()
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．
 
;jpn:◆はい　たしかに。↓
;jpn:　ありやと　やんしたー。
@GOTO(_PIZZA_END)

_PIZZA_GOODSFULL;			;持ち物いっぱい。
@CLRF(FLG_PIZZA_SIZE)			;フラグリセット
◆Ｏｈ，　ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｃａｎ　ｎｏｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．↓
　　Ｃａｌｌ　ｕｓ　ａｇａｉｎ　ｓｏｍｅ　ｏｔｈｅｒ　ｔｉｍｅ．

;jpn:◆あれっ　にもつが　いっぱい↓
;jpn:　みたいですね。↓
;jpn:　じゃ　また　よろしくー。
@GOTO(_PIZZA_END)

_PIZZA_NOMONEY;				;所持金不足。
◆Ｏｈ？　Ｙｏｕ　ａｒｅ　ａ　ｌｉｔｔｌｅ　ｓｈｏｒｔ　ｏｆ　ｃａｓｈ．　　Ｗｅｌｌ，　ｃａｌｌ　ｕｓ　ａｇａｉｎ　ｓｏｍｅ　ｏｔｈｅｒ　ｔｉｍｅ．
  
;jpn:◆あれ？　たりないですね。↓
;jpn:　じゃ　また　よろしくー。
@GOTO(_PIZZA_END)

MSG_PIZZA_SEND_RETRY_OVER;
@CLRF(FLG_DELIVERY_PIZZA)
@CLRF(FLG_PIZZA_SIZE)
@GOSUB(MSG_SUB_ZYUSHIN_CALL)
@OPEN(1)
◆Ｈｅｌｌｏ！↓
　　Ｔｈｉｓ　ｉｓ　Ｍａｃｈ　Ｐｉｚｚａ．↓
　（ｈｅｅ，ｈａ，ｈｅ，ｈａ）@KEY()↓
◆．．．．Ｙｏｕ　ｍｕｓｔ　ｂｅ　ａｔ　ｓｏｍｅｗｈｅｒｅ　ｒｅａｌｌｙ　ｓｔｒａｎｇｅ，（ｈｅｅ，ｈａ，ｈｅ，ｈａ）．．．@KEY()↓
◆Ｉ　ｃｏｕｌｄｎ’ｔ　ｄｅｌｉｖｅｒ　ｔｈｅ　ｐｉｚｚａ．↓
　　Ｔｈｅ　ｐｉｚｚａ　ｇｏｔ　ｒｅａｌｌｙ　ｃｏｌｄ　ａｎｄ　ｈａｒｄ，　ａｎｄ　ｍｙ　ｌｅｇｓ　ａｒｅ　ｔｉｒｅｄ．．．@KEY()↓
◆Ｉ　ａｍ　ｇｏｉｎｇ　ｔｏ　ｇｉｖｅ　ｕｐ　ａｎｄ　ｇｏ　ｂａｃｋ．@KEY()↓
◆．．．Ｉ　ｈｏｐｅ　Ｉ　ｃａｎ　ｆｉｎｄ　ｔｈｅ　ｗａｙ　ｈｏｍｅ．．．↓
　（ｈｅｅ，ｈａ，ｈｅ，ｈａ）@KEY()
;jpn:◆もしもーし！↓
;jpn:　マッハピザでーす。（ハアハア）@KEY()↓
;jpn:◆どうやら　おきゃくさまが↓
;jpn:　とんでもない　ところに↓
;jpn:　いらっしゃるらしくて（ハアハア）@KEY()↓
;jpn:◆はいたつできませんでした。↓
;jpn:　ピザは　かちかちになっちゃうし↓
;jpn:　あしは　くたびれるし‥‥@KEY()↓
;jpn:◆こんかいは　あきらめて↓
;jpn:　かえらせていただきます。@KEY()↓
;jpn:◆‥‥か　かえれるかなぁ。↓
;jpn:　（ハアハア）@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!

;
;デパート＿返品
;

MSG_DP_HENPIN;
←
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｒｅｔｕｒｎ　ｓｏｍｅｔｈｉｎｇ？↓

;jpn:◆ごへんぴんですか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_YES,_DP_HENPIN_NO1)

_DP_HENPIN_NO1;				;返品しない。
◆Ｏｈ，　ｔｈａｔ’ｓ　ｇｏｏｄ．@KEY()↓

;jpn:◆ああ　よかった。@KEY()↓
_DP_HENPIN_NO2;
◆Ｐｌｅａｓｅ　ｓｔｏｐ　ｂｙ　ａｇａｉｎ．

;jpn:◆これからも　とうデパートを↓
;jpn:　よろしくおひきたて↓
;jpn:　くださいませね。@KEY()↓
;jpn:◆うっふん。
_DP_HENPIN_END;				;終了。
@KEYNP()
@!

_DP_HENPIN_YES;				;返品する。
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｒｅｔｕｒｎ？

;jpn:◆なにを　へんぴん？
_DP_HENPIN_SEL;
@KEY()
@WINR_MONEY()
@GOSUB(MSG_SEL_GOODS)			;グッ選択
↓
@FALSE_GOTO(_DP_HENPIN_NO1)		;キャンセル？
@SAVE_REG()				;主レジ=PLAYER_ID・副レ=GOODSの位置
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)			;主レジ=GOODS_IDの金額
@FALSE_GOTO(_DP_HENPIN_UNABLE)
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｗｅ　ｃａｎ　ｇｉｖｅ　ｙｏｕ
　　ｂａｃｋ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｄｏ　ｔｈａｔ？↓

;jpn:◆@DSP_GOODS(0)ですね。↓		;グッズ名表示
;@XCHG()					;副レジ=GOODS_IDの金額
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　おひきとりしますが‥‥
;@KEY()↓				;売り値表示
;jpn:◆よろしゅうございますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_MONEY_YES,_DP_HENPIN_MONEY_NO)

_DP_HENPIN_MONEY_NO;			;売らない。
@GOTO(_DP_HENPIN_OTHER)

_DP_HENPIN_MONEY_YES;			;売る。
@MONEYIN(0)				;所持金に入金
@WINR_MONEY()
@SE(SE_se76_my_give)
@LOAD_REG()				;主レ=PLAYER_ID・副レ=GOODSの位置
@GOODSOUT_PLAYER(0,0)			;アイテム欄から削除。
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓

_DP_HENPIN_OTHER;			;他に返品は？
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかにも　ございますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_DP_HENPIN_YES,_DP_HENPIN_NO2)
@GOTO(_DP_HENPIN_NO2)

_DP_HENPIN_UNABLE;				;売ることができない。
◆Ｗｅ’ｒｅ　ｖｅｒｙ　ｓｏｒｒｙ，ｂｕｔ　ｗｅ　ｄｏｎ’ｔ　ｄｅａｌ　ｗｉｔｈ　ｔｈａｔ　ｐｒｏｄｕｃｔ．@KEY()↓

;jpn:◆おそれいります。↓
;jpn:　とうてんでは↓
;jpn:　あつかっておりません。@KEY()↓
@GOTO(_DP_HENPIN_OTHER)


;
;ハッピー村／フィールド／無人販売所
;

MSG_SHOP_HAPPY_AUTOSHOP;
◆（Ｗｅ　ｔｒｕｓｔ　ｙｏｕ．Ｆｅｅｌ　ｆｒｅｅ　ｔｏ　ｓｈｏｐ　ｈｅｒｅ．）@KEY()↓
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｂｕｙ？@KEY()

;jpn:◆（あなたを　しんようします。@WI(20)↓
;jpn:　ごじゆうに　おかいもの↓
;jpn:　してください）@KEY()↓
;jpn:◆なにをかう？@KEY()
@WINR_MONEY()
@DSP_PL()
@SEL_SHOP_TAKE(SHOP_HAPPY_AUTOSHOP)
←
@FALSE_GOTO(_AUTO_NOTTAKE)
@XCHG()
_AUTO_X;
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_AUTO_GOODSFULL)
@SAVE_REG()
◆Ｈｏｗ　ｍｕｃｈ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｐａｙ？↓

;jpn:◆いくらしはらう？↓
@LOC(9,2)
＆
@LOC(4,2)
＄@INPUT(4)
@CLRLINE()
@XCHG()					;主レ=GOODS_ID:副レ=支払い額
@FALSE_GOTO(_AUTO_NOTTAKE)
@SAVE_REG()
@Q_MONEY(0)
@TRUE_GOTO(_AUTO_NOMONEY)
@LOAD_REG()
@XCHG()
@FALSE_GOTO(_AUTO_PAY0)
@XCHG()
@EQ(GDS_FOOD_BANANA)
@TRUE_GOTO(_AUTO_2)
_AUTO_1;
@CMP(12,1)
@FALSE_GOTO(_AUTO_FOUL)
@GOTO(_AUTO_PAY)
_AUTO_2;
@CMP(5,1)
@FALSE_GOTO(_AUTO_FOUL)
_AUTO_PAY;
@LOAD_REG()
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆@DSP_NAME(PC_NESS)　ｐａｉｄ　＄@DSP_NUM(0)　ａｔ　ｔｈｅ　ｓｅｌｆ－ｓｅｒｖｉｃｅ　ｓｔａｎｄ．

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn:　むじんはんばいじょに↓
;jpn:　@DSP_NUM(0)ドルしはらった。
@KEYNP()
_AUTO_GOODSIN;
@LOAD_REG()
@XCHG()
@GOODSIN_PLAYER(PC_NESS,0)
@SETF(FLG_HAPPY_AUTOSHOP)
_AUTO_CHK;
@!

_AUTO_FOUL;
@SETF(FLG_HAPPY_AUTOSHOP_FOUL)
@GOTO(_AUTO_PAY)


_AUTO_NOTTAKE;
◆@DSP_NAME(PC_NESS)　ｄｅｃｉｄｅｄ　ｎｏｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ．

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn:　かうのをやめた。
@KEYNP()
@!

_AUTO_PAY0;
◆@DSP_NAME(PC_NESS)　ｄｉｄ　ｎｏｔ　ｐａｙ．

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn:　おかねを　はらわなかった。
@KEYNP()
@SETF(FLG_HAPPY_AUTOSHOP_FOUL)
@GOTO(_AUTO_GOODSIN)

_AUTO_GOODSFULL;
◆@DSP_NAME(PC_NESS)　ｃｏｕｌｄ　ｎｏｔ
　　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｓｔｕｆｆ．

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn:　もちものがいっぱいだった。
@KEYNP()
@!

_AUTO_NOMONEY;
◆@DSP_NAME(PC_NESS)　ｄｉｄ　ｎｏｔ　ｈａｖｅ
　　ｔｈａｔ　ｍｕｃｈ　ｍｏｎｅｙ．

;jpn:◆@DSP_NAME(PC_NESS)は↓
;jpn:　そんなにおかねを↓
;jpn:　もっていなかった。
@KEYNP()
@!


;
;アイス売り
;

MSG_SUMS_ICE;
@GOSUB(MSG_SHOP_SUMS_ICE)
@!

;
;水売り
;

MSG_SKRB_WATER;
@GOSUB(MSG_SHOP_SKRB_WATER)
@!

MSG_SUMS_WIFE;
MSG_SUMS_MAZICTORTE;
@GOSUB(MSG_SHOP_SUMS_WIFE)
@!

MSG_HAPPY_DRUGSTORE;
@GOSUB(MSG_SHOP_HAPPY_DRUGSTORE)
@!
MSG_SHOP_DOSEI_BAKA3;
@GOSUB(MSG_SHOP_SHOP_DOSEI_BAKA3)
@!
MSG_DSRT_SHOP2;
@GOSUB(MSG_SHOP_DSRT_SHOP2)
@!
MSG_TWSN_FURIKAKE;
@GOSUB(MSG_SHOP_SKRB_FURIKAKE)
@!
MSG_SKRB_FURIKAKE;
@GOSUB(MSG_SHOP_SKRB_FURIKAKE)
@!
MSG_SKRB_BAZAR_B;
@GOSUB(MSG_SHOP_SKRB_BAZAR_B)
@!
MSG_DSRT_BENTOU;
@GOSUB(MSG_SHOP_DSRT_BENTOU)
@!
MSG_RAMA_OKAYU;
@GOSUB(MSG_SHOP_RAMA_OKAYU)
@!
MSG_WINS_STONEHENGE_B;
@GOSUB(MSG_SHOP_WINS_STONEHENGE_B)
@!

MSG_HOTEL_MOON_SHOP;
@GOSUB(MSG_SHOP_HOTEL_MOON_SHOP)
@!

MSG_SUMS_MAGICCAKE_WAGON;
MSG_SUMS_HOTDOG_WAGON;
MSG_DSRT_BENTOU_WAGON;
@GOSUB(MSG_SYS_NOPROBLEM)
@!

;
;グミの物々交換
;


MSG_SUB_GUMI_BUTUBUTU;
@CHKFGOTO(FLG_GUMI_7_BOOK,_BUTUBUTU_AFTER)
◆Ｉ　ｗｏｕｌｄ　ｌｉｋｅ　ｔｈｅ　@DSP_GOODS(GDS_TOOL_LIFE_HORN)．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｇｉｖｅ　ｍｅ↓
　　ｔｈｅ　@DSP_GOODS(GDS_TOOL_LIFE_HORN)，@KEY()↓
◆Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　ｓｏｍｅｔｈｉｎｇ　ｉｎ　ｒｅｔｕｒｎ．@KEY()↓
◆Ｌｏｏｋ　ａｔ　ｍｙ　ｌｉｓｔ．
;　<ｐｏｏｒ　ｑｕａｌｉｔｉｙ　ｂｒｅａｄ>
;　<ｓｉｍｐｌｅ　ｙｏｇｕｌｔ>
;　<ｐｏｏｒ　ｑｕａｌｉｔｉｙ　ｂｒｅａｄ>
;　<ｓｐｉｃｙ　ｊｅｒｋｅｙ>
;　<ｄｒａｇｏｎ　ｐｏｗｄｅｒ>
;　<ｍａｇｉｃａｌ　ｐｏｗｅｒ　ｓｅａｌｉｎｇ　ｃｏｉｎ>
;　　ｎｏｔｅ：　ｔｈｉｓ　ｉｓ　ｏｎｅ　ｏｆ　ｔｈｅ　ｄｅｆｅｎｓｅ　ｇｏｏｄｓ．
;　<ｔｈｅ　ｂｅｓｔ　ｂａｔ>
 
;jpn:◆おれ↓
　@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn:　ほしい。@KEY()↓
◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn:　くれれば@KEY()↓
;jpn:◆おれいに　ものやる。@KEY()↓
;jpn:◆やるもの　リスト
;jpn:　みろ。@KEY()
@OPEN(7)
@CHKFGOTO(FLG_GUMI_1_BOOK,_BUTUBUTU_GOODS2)
<Ｐｌａｉｎ　ｒｏｌｌ>

;jpn:<そまつなパン>
_BUTUBUTU_GOODS2;
@CHKFGOTO(FLG_GUMI_2_BOOK,_BUTUBUTU_GOODS3)
<Ｐｌａｉｎ　ｙｏｇｕｒｔ>

;jpn:<そぼくなヨーグルト>
_BUTUBUTU_GOODS3;
@CHKFGOTO(FLG_GUMI_3_BOOK,_BUTUBUTU_GOODS4)
<Ｐｌａｉｎ　ｒｏｌｌ>

;jpn:<そまつなパン>
_BUTUBUTU_GOODS4;
@CHKFGOTO(FLG_GUMI_4_BOOK,_BUTUBUTU_GOODS5)
<ｓｐｉｃｙ　ｊｅｒｋｙ>

;jpn:<スパイシーなほしにく>
_BUTUBUTU_GOODS5;
@CHKFGOTO(FLG_GUMI_5_BOOK,_BUTUBUTU_GOODS6)
<Ｄｒａｇｏｎ　Ｐｏｗｄｅｒ>

;jpn:<ドラゴンパウダー>
_BUTUBUTU_GOODS6;
@CHKFGOTO(FLG_GUMI_6_BOOK,_BUTUBUTU_GOODS7)
<Ｔａｌｉｓｍａｎ　ｃｏｉｎ>

;jpn:<まふうじのコイン>
_BUTUBUTU_GOODS7;
<Ａｌｌ－Ｓｔａｒ　ｂａｔ>

;jpn:<さいこうのバット>
@DSP_ITEML(1)
@KEYNP()
@CLOSE()
@SELECT_WIN(1)
←
◆Ｗｉｌｌ　ｙｏｕ　ｇｉｖｅ　ｍｅ↓
　　ｔｈｅ　@DSP_GOODS(GDS_TOOL_LIFE_HORN)？@KEY()

;◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn:　くれるか？@KEY()
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_BUTUBUTU_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@XCHG()
@EQ(GDS_TOOL_LIFE_HORN)
@FALSE_GOTO(_BUTUBUTU_MISS)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@GOSUB(_SUB_BUTUBUTU_SELGOODS)
@SET_REG(1)
←
◆Ｏｋａｙ．↓
　　Ｉ　ｇｉｖｅ　ｙｏｕ　ｔｈｅ　@DSP_GOODS(0)．@KEY()↓
◆Ｙｏｕ　ｈａｐｐｙ．↓
　　Ｉ　ｈａｐｐｙ．@KEY()
 
;jpn:◆よし。↓
;jpn:　@DSP_GOODS(0)やる。@KEY()↓
;jpn:◆うれしい　おまえ。↓
;jpn:　うれしい　おれ。@KEY()
←
@Q_GOODSFULL(PC_ALL)
@SAVE_REG()
@GOODSIN_PLAYER(0,0)
@GOSUB(MSG_SUB_GETGOODS)
@KEYNP()
@!
_BUTUBUTU_NO;
←
◆Ｙｏｕ　ｎｏｔ　ｗａｎｔ？　Ｉｔ　Ｏｋａｙ．↓
　　Ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆いやなら　いいんだ。↓
;jpn:　またこい。
@KEYNP()
@!
_BUTUBUTU_MISS;
←
◆Ｔｈａｔ　ｎｏｔ　ｔｈｅ　ｏｎｅ．
 
;jpn:◆それ　ちがう。
@KEYNP()
@!
_BUTUBUTU_AFTER;
◆Ｍｏｒｅ　@DSP_GOODS(GDS_TOOL_LIFE_HORN)？@KEY()↓
◆Ｉ　ｓａｔｉｓｆｉｅｄ．@KEY()↓
◆Ｓｅｅ　ｙａ！
 
;◆@DSP_GOODS(GDS_TOOL_LIFE_HORN)↓
;jpn:　たまった。@KEY()↓
;jpn:◆まんぞくした　おれ。@KEY()↓
;jpn:◆じゃあな。
@KEYNP()
@!

_SUB_BUTUBUTU_SELGOODS;
@CHKFGOTO(FLG_GUMI_6_BOOK,_BUTUBUTU_SELGOODS_7)
@CHKFGOTO(FLG_GUMI_5_BOOK,_BUTUBUTU_SELGOODS_6)
@CHKFGOTO(FLG_GUMI_4_BOOK,_BUTUBUTU_SELGOODS_5)
@CHKFGOTO(FLG_GUMI_3_BOOK,_BUTUBUTU_SELGOODS_4)
@CHKFGOTO(FLG_GUMI_2_BOOK,_BUTUBUTU_SELGOODS_3)
@CHKFGOTO(FLG_GUMI_1_BOOK,_BUTUBUTU_SELGOODS_2)
_BUTUBUTU_SELGOODS_1;
@SET_LOOPREG(GDS_FOOD_GUMI_BREAD)
@SETF(FLG_GUMI_1_BOOK)
@!
_BUTUBUTU_SELGOODS_2;
@SET_LOOPREG(GDS_FOOD_GUMI_YOGURT)
@SETF(FLG_GUMI_2_BOOK)
@!
_BUTUBUTU_SELGOODS_3;
@SET_LOOPREG(GDS_FOOD_GUMI_BREAD)
@SETF(FLG_GUMI_3_BOOK)
@!
_BUTUBUTU_SELGOODS_4;
@SET_LOOPREG(GDS_FOOD_DRY_MEAT_GREAT)
@SETF(FLG_GUMI_4_BOOK)
@!
_BUTUBUTU_SELGOODS_5;
@SET_LOOPREG(GDS_TOOL_DRAGON_POWDER)
@SETF(FLG_GUMI_5_BOOK)
@!
_BUTUBUTU_SELGOODS_6;
@SET_LOOPREG(GDS_EQUIP_COIN_MAFUJI)
@SETF(FLG_GUMI_6_BOOK)
@!
_BUTUBUTU_SELGOODS_7;
@SET_LOOPREG(GDS_EQUIP_BAT_SAIKO)
@SETF(FLG_GUMI_7_BOOK)
@!

;魔境のキャッシュディスペンサー男
MSG_SUB_MAKYO_CDMAN;
◆Ｓｈｈｈｈｈ！　Ｂｅ　ｑｕｉｅｔ！↓
　　Ｉ　ｌｏｏｋ　ｖｅｒｙ　ｉｍｐｏｒｔａｎｔ，　ｂｕｔ　Ｉ’ｍ　ｎｏｔ　ｒｅａｌｌｙ．．．．．．．@KEY()↓
◆Ｉ’ｍ　ａ　ｃａｓｈ　ｄｉｓｐｅｎｓｅｒ　ｍａｎ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｗｉｔｈｄｒａｗ　ｃａｓｈ．．．．．@KEY()↓
◆Ｉ’ｌｌ　ｃｈａｒｇｅ　ｙｏｕ　ａ　ｈａｎｄｌｉｎｇ　ｆｅｅ，@KEY()↓
◆ｗｈｉｃｈ　ｉｓ　ｔｈｅ　ｓａｍｅ　ａｍｏｕｎｔ　ａｓ　ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ．@KEY()↓
◆Ｓｏ，　ｄｏ　ｙｏｕ　ｗａｎｔ　ａ　ｗｉｔｈｄｒａｗａｌ？↓
;jpn:◆しっ！　しずかに！@WI(20)↓
;jpn:　わたしは　じゅうようそうだけど↓
;jpn:　そうでもない‥‥@KEY()↓
;jpn:◆キャッシュディスペンサーおとこ↓
;jpn:　‥‥です。@KEY()↓
;jpn:◆‥‥ひきだすばあい↓
;jpn:　あつかいきんがくと@KEY()↓
;jpn:◆どうがくの↓
;jpn:　てすうりょうを↓
;jpn:　いただきますが‥‥@KEY()↓
;jpn:◆ごりように　なりますか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_CDMAN_YES,_CDMAN_NO)
_CDMAN_NO;
←
◆．．．．Ｉ’ｌｌ　ｂｅ　ｈｅｒｅ，　ｓｏ．．．↓
　　Ｃｏｍｅ　ｂａｃｋ　ａｎｙ　ｔｉｍｅ．

;jpn:◆‥‥わたしは　いつも↓
;jpn:　ここにいますから‥‥@WI(15)↓
;jpn:　いつでも　どうぞ。
@KEYNP()
@!
_CDMAN_YES;
◆Ｙｏｕ　ｈａｖｅ　＄@DSP_STS(STS_PARTY_BANK_MONEY)　ｉｎ　ｙｏｕｒ　ａｃｃｏｕｎｔ　ｎｏｗ．↓
<Ｗｉｔｈｄｒａｗａｌ>
<Ｄｅｐｏｓｉｔ>

;jpn:◆いま　ぎんこうよきんは↓
;jpn:　@DSP_STS(STS_PARTY_BANK_MONEY)ドルです。↓
;jpn:<ひきだす>
;jpn:<あずける>
@DSP_ITEM(2)
@SELGOTO(_CDMAN_HIKI,_CDMAN_AZU)
@GOTO(_CDMAN_NO)
_CDMAN_AZU;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_CDMAN_AZU_FULL)
@GOSUB(_CDMAN_AZU_INPUT)
@FALSE_GOTO(_CDMAN_NO)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_CDMAN_AZU_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆Ｉ　ｈａｖｅ　ｒｅｇｉｓｔｅｒｅｄ　ｙｏｕｒ　ｄｅｐｏｓｉｔ↓
　　ｏｆ　＄@DSP_NUM(0)．@KEY()↓

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn:　たしかにおあずかりしました。
;@KEY()↓
@GOTO(_CDMAN_THANKS)

_CDMAN_HIKI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_CDMAN_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_CDMAN_HIKI_MAX)
@GOSUB(_CDMAN_HIKI_INPUT)
@FALSE_GOTO(_CDMAN_NO)
@XCHG()
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CDMAN_HIKI_NOMONEY)
@DRAW_MONEY_BANK(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_CDMAN_HIKI_NOMONEY_2)
◆Ｙｏｕｒ　ｃａｓｈ　ｗｉｔｈｄｒａｗａｌ↓
　　ｉｓ　＄@DSP_NUM(0)，@KEY()↓
◆ａｎｄ　ｔｈｅ　ｈａｎｄｌｉｎｇ　ｃｈａｒｇｅ↓
　　ｉｓ　＄@DSP_NUM(0)．@KEY()↓
◆Ｉ　ｗｉｌｌ　ｓｕｂｔｒａｃｔ　ｔｈｉｓ　ａｍｏｕｎｔ　ｆｒｏｍ　ｙｏｕｒ　ａｃｃｏｕｎｔ．@KEY()↓
◆Ｉｓ　ｔｈａｔ　ｏｋａｙ　ｗｉｔｈ　ｙｏｕ？↓
;jpn:◆おわたしするぶんが↓
;jpn:　　@DSP_NUM(0)ドル@KEY()↓
;jpn:◆てすうりょうが↓
;jpn:　　@DSP_NUM(0)ドル@KEY()↓
;jpn:◆これだけ　ひきだしますが↓
;jpn:　よろしいですか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_CDMAN_HIKI_YES,_CDMAN_HIKI_NO)
_CDMAN_HIKI_NO;
@DEPOSIT_MONEY_BANK(0)
@GOTO(_CDMAN_NO)

_CDMAN_HIKI_YES;
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ↓
　　ｉｓ　＄@DSP_NUM(0)．@KEY()

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn:　たしかにおひきだししました。
;@KEY()↓
@GOTO(_CDMAN_THANKS)


_CDMAN_THANKS;
←
◆Ｏｋａｙ．．．@KEY()↓
◆Ｐｌｅａｓｅ　ｄｏｎ’ｔ　ｂｏｔｈｅｒ　ｙｏｕｒｓｅｌｆ　ｗｉｔｈ　ｍｅ．．．ｙｏｕ　ｓｈｏｕｌｄ　ｃｏｎｔｉｎｕｅ　ｙｏｕｒ　ｊｏｕｒｎｅｙ．

;jpn:◆じゃ‥‥↓
;jpn:　わたしのことは　わすれて↓
;jpn:　たびを　おつづけください。
@KEYNP()
@!

_CDMAN_AZU_FULL;
←
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｄｅｐｏｓｉｔ　ａｎｙ　ｍｏｒｅ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆これいじょうは↓
;jpn:　おかねを　あずけられない↓
;jpn:　みたいですね。@KEY()↓
@GOTO(_CDMAN_NO)
_CDMAN_AZU_NOMONEY;
←
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ｔｈａｔ　ｍｕｃｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あなたは　そんなに↓
;jpn:　おかねを　もっていない↓
;jpn:　みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_AZU)
_CDMAN_HIKI_EMPTY;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ａｎｙ　ｓａｖｉｎｇｓ　ｉｎ　ｔｈｅ　ｂａｎｋ．@KEY()

;jpn:◆あなたは　ぎんこうに↓
;jpn:　よきんをして　おられない↓
;jpn:　みたいですが‥‥@KEY()
@GOTO(_CDMAN_NO)
_CDMAN_HIKI_MAX;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｗｉｔｈｄｒａｗ　ａｎｙ　ｍｏｒｅ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あなたは　これいじょう↓
;jpn:　おかねをひきだせない↓
;jpn:　みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_NO)
_CDMAN_HIKI_NOMONEY;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ｔｈａｔ　ｍｕｃｈ　ｍｏｎｅｙ　ｉｎ　ｙｏｕｒ　ａｃｃｏｕｎｔ．@KEY()↓

;jpn:◆あなたは　そんなに↓
;jpn:　ぎんこうに　あずけておられない↓
;jpn:　みたいですが‥‥@KEY()↓
@GOTO(_CDMAN_HIKI)
_CDMAN_HIKI_NOMONEY_2;
@DEPOSIT_MONEY_BANK(0)
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ　ｆｏｒ　ｍｙ　ｈａｎｄｌｉｎｇ　ｆｅｅ．@KEY()↓

;jpn:◆わたしのぶんが↓
;jpn:　たりないみたい↓
;jpn:　なんですが‥‥@KEY()↓
@GOTO(_CDMAN_HIKI)


_CDMAN_AZU_INPUT;
←
◆Ｈｏｗ　ｍｕｃｈ　ｗｉｌｌ　ｙｏｕ　ｄｅｐｏｓｉｔ？↓

;jpn:◆いくらあずけますか？↓
@GOSUB(_CD_INPUT_2)
@!
_CDMAN_HIKI_INPUT;
←
◆Ｈｏｗ　ｍｕｃｈ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｗｉｔｈｄｒａｗ？↓

;jpn:◆いくらひきだしますか？↓
@GOSUB(_CD_INPUT_2)
@!
　　

;キャッシュディスペンサー機能の地底グミ
;外国留学経験者？
MSG_SUB_DKFD_EGO;
@CHKFGOTO(FLG_TEMP_1,_EGO_TMP)
@SETF(FLG_TEMP_1)
◆Ｙｏｕ’ｒｅ　ａ　ｆｏｒｅｉｇｎｅｒ，　ａｒｅｎ’ｔ　ｙｏｕ？@KEY()↓
◆Ｉ　ａｍ　ａ　ｗｏｒｌｄ－ｗｉｓｅ　Ｔｅｎｄａ．@KEY()↓
◆Ｉ　ｗａｓ　ａｎ　ｅｘｃｈａｎｇｅ　ｓｔｕｄｅｎｔ　ｗｈｏ　ｔｒａｖｅｌｅｄ　ｔｏ　ａ　ｃｏｕｎｔｒｙ@KEY()↓
◆ｔｈａｔ　ｉｓ　ｋｎｏｗｎ　ａｓ　ａｎ　ｅｃｏｎｏｍｉｃ　ｓｕｐｅｒｐｏｗｅｒ．@KEY()↓
◆Ｍｙ　ｎａｍｅ　ｉｓ　Ａｙ－ｇｏ　Ｓｔｉｋｋｅ．@KEY()↓
◆Ｌｅｔ　ｍｅ　ｋｎｏｗ　ｉｆ　Ｉ　ｃａｎ　ｄｏ　ａｎｙｔｈｉｎｇ　ｆｏｒ　ｙｏｕ．@KEY()↓

;jpn:◆がいこくの　かたですね？@KEY()↓
;jpn:◆ボクは　あるけいざいたいこくに↓
;jpn:　りゅうがく　けいけんのある↓
;jpn:　はなしのわかる　グミです。@KEY()↓
;jpn:◆なまえは　エーゴ・ステッキです。@KEY()↓
;jpn:◆おやくにたてることが　あったら↓
;jpn:　いつでも　いってください。@KEY()↓
_EGO_1;
◆Ｓｈａｌｌ　Ｉ　ｌｏａｎ　ｙｏｕ　ｓｏｍｅ　ｍｏｎｅｙ？↓

;jpn:◆おかねを↓
;jpn:　ごようだて　しましょうか？@KEY()↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_YES_1,_EGO_NO_1)
_EGO_NO_1;
◆Ｉ　ｄｏｎ’ｔ　ｆｅｅｌ　ｓｔｒａｎｇｅ　ａｂｏｕｔ　ｉｔ　ａｔ　ａｌｌ．↓
　　Ｐｌｅａｓｅ　ａｓｋ　ｍｅ　ａｎｙ　ｔｉｍｅ．

;jpn:◆わたしは↓
;jpn:　きをわるくしたりなんかしません。@WI(20)↓
;jpn:　また　いつでも　どうぞ。
@KEYNP()
@!
_EGO_YES_1;
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｗｉｔｈｄｒａｗ．．．．．@KEY()↓
◆Ｉ　ｗｉｌｌ　ｃｈａｒｇｅ　ｙｏｕ　ａ　ｈａｎｄｌｉｎｇ　ｆｅｅ@KEY()↓
◆ｔｈａｔ　ｉｓ　ｅｑｕａｌ　ｔｏ　ｔｈｅ　ａｍｏｕｎｔ　ｏｆ　ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ．@KEY()↓
◆Ｉｓ　ｔｈａｔ　ｏｋａｙ　ｗｉｔｈ　ｙｏｕ？↓
;jpn:◆おかねのおひきだしには↓
;jpn:　あつかいきんがくと　どうがくの↓
;jpn:　てすうりょうを　いただきますが@KEY()↓
;jpn:◆よろしいですね？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_YES_2,_EGO_NO_2)
_EGO_NO_2;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ’ｖｅ　ｅｖｅｒ　ｒｅａｌｌｙ　ｇｏｔｔｅｎ　ｉｎｔｏ　ｂａｄ　ｔｒｏｕｂｌｅ．

;jpn:◆まだ　ほんとうに　このせかいで↓
;jpn:　こまっては　いないようですね。
@KEYNP()
@!
_EGO_YES_2;
◆Ｙｏｕ　ｈａｖｅ　＄@DSP_STS(STS_PARTY_BANK_MONEY)　ｉｎ　ｙｏｕｒ　ａｃｃｏｕｎｔ　ｎｏｗ．↓
<Ｗｉｔｈｄｒａｗａｌ>
<Ｄｅｐｏｓｉｔ>

;jpn:◆あなたのぎんこうよきんは↓
;jpn:　いま@DSP_STS(STS_PARTY_BANK_MONEY)ドルです。↓
;jpn:<ひきだす>
;jpn:<あずける>
@DSP_ITEM(2)
@SELGOTO(_EGO_HIKI,_EGO_AZU)
@GOTO(_EGO_NO_1)

_EGO_AZU;
@Q_BANK_MONEY(9999999)
@FALSE_GOTO(_EGO_AZU_FULL)
@GOSUB(_EGO_AZU_INPUT)
@FALSE_GOTO(_EGO_NO_1)
@XCHG()
@Q_MONEY(0)
@TRUE_GOTO(_EGO_AZU_NOMONEY)
@MONEYOUT(0)
@DEPOSIT_MONEY_BANK(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@WI(10)
◆Ｉ　ｈａｖｅ　ｒｅｇｉｓｔｅｒｅｄ　ｙｏｕｒ　ｄｅｐｏｓｉｔ↓
　　ｏｆ　＄@DSP_NUM(0)．@KEY()↓
    
;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn:　たしかにおあずかりしました。
;@KEY()↓
@GOTO(_EGO_THANKS)

_EGO_HIKI;
@Q_BANK_MONEY(1)
@TRUE_GOTO(_EGO_HIKI_EMPTY)
@Q_MONEY(99999)
@FALSE_GOTO(_EGO_HIKI_MAX)
@GOSUB(_EGO_HIKI_INPUT)
@FALSE_GOTO(_EGO_NO_1)
@XCHG()
@Q_BANK_MONEY(0)
@TRUE_GOTO(_EGO_HIKI_NOMONEY)
@DRAW_MONEY_BANK(0)
@Q_BANK_MONEY(0)
@TRUE_GOTO(_EGO_HIKI_NOMONEY_2)
◆Ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ↓
　　ｉｓ　＄@DSP_NUM(0)，@KEY()↓
◆ａｎｄ　ｔｈｅ　ｈａｎｄｌｉｎｇ　ｆｅｅ↓
　　ｉｓ　＄@DSP_NUM(0)．@KEY()↓
◆Ｉｓ　ｉｔ　ｏｋａｙ　ｉｆ　Ｉ　ｓｕｂｔｒａｃｔ　ｔｈｉｓ　ａｍｏｕｎｔ　ｆｒｏｍ　ｙｏｕｒ　ａｃｃｏｕｎｔ？↓

;jpn:◆おわたしするぶんが↓
;jpn:　　@DSP_NUM(0)ドル@KEY()↓
;jpn:◆てすうりょうが↓
;jpn:　　@DSP_NUM(0)ドル@KEY()↓
;jpn:◆これだけ　ひきだしますが↓
;jpn:　いいですか？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_EGO_HIKI_YES,_EGO_HIKI_NO)
_EGO_HIKI_NO;
@DEPOSIT_MONEY_BANK(0)
@GOTO(_EGO_NO_2)

_EGO_HIKI_YES;
@DRAW_MONEY_BANK(0)
@MONEYIN(0)
@WINR_MONEY()
@SE(SE_se74_my_get)
@WI(10)
◆Ｙｏｕｒ　ｗｉｔｈｄｒａｗａｌ↓
　ｉｓ　＄@DSP_NUM(0)．@KEY()↓

;jpn:◆@DSP_NUM(0)ドルですね。↓
;jpn:　たしかにおひきだししました。
;@KEY()↓
@GOTO(_EGO_THANKS)

_EGO_THANKS;
←
◆Ｉｔ　ｗａｓ　ａ　ｖｅｒｙ　ｇｏｏｄ　ｏｐｐｏｒｔｕｎｉｔｙ　ｆｏｒ　ｔｈｅ　ｂｏｔｈ　ｏｆ　ｕｓ．↓
　　Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆おたがいに　とてもいい↓
;jpn:　チャンスでしたね。@WI(20)↓
;jpn:　また　よろしく　おねがいします。
@KEYNP()
』

_EGO_AZU_FULL;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｄｅｐｏｓｉｔ　ａｎｙ　ｍｏｒｅ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆これいじょう↓
;jpn:　あずけられないみたいですね。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_AZU_NOMONEY;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ｔｈａｔ　ｍｕｃｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あなたは　そんなに↓
;jpn:　おかねを　もっていませんよ。@KEY()↓
@GOTO(_EGO_AZU)
_EGO_HIKI_EMPTY;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ　ｉｎ　ｙｏｕｒ　ａｃｃｏｕｎｔ．@KEY()↓

;jpn:◆あなたは　まったく↓
;jpn:　ちょきんをしていませんね。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_HIKI_MAX;
◆Ｉ　ｔｈｉｎｋ　ｉｔ’ｓ　ｉｍｐｏｓｓｉｂｌｅ　ｆｏｒ　ｙｏｕ　ｔｏ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あなたは　これいじょう↓
;jpn:　おかねをもっていても↓
;jpn:　しょうがないですよ。@KEY()↓
@GOTO(_EGO_NO_1)
_EGO_HIKI_NOMONEY;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｔｈａｔ　ｍｕｃｈ　ｍｏｎｅｙ　ｉｎ　ｙｏｕｒ　ａｃｃｏｕｎｔ．@KEY()↓

;jpn:◆あなたは　そんなに↓
;jpn:　ちょきんをしていませんね。@KEY()↓
@GOTO(_EGO_HIKI)
_EGO_HIKI_NOMONEY_2;
@DEPOSIT_MONEY_BANK(0)
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃｏｖｅｒ　ｍｙ　ｈａｎｄｌｉｎｇ　ｃｈａｒｇｅ．@KEY()↓

;jpn:◆わたしのてすうりょうが↓
;jpn:　もらえないみたいてす。@KEY()↓
@GOTO(_EGO_HIKI)

_EGO_TMP;
◆Ｈｉ！　　Ｉ’ｍ　Ａｙ－ｇｏ．@KEY()↓

;jpn:◆ハーイ！　エーゴです。@KEY()↓
@GOTO(_EGO_1)
_EGO_AZU_INPUT;
←
◆Ｈｏｗ　ｍｕｃｈ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｄｅｐｏｓｉｔ？↓

;jpn:◆いくらあずけますか？↓
@GOSUB(_CD_INPUT_2)
@!
_EGO_HIKI_INPUT;
←
◆Ｈｏｗ　ｍｕｃｈ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｗｉｔｈｄｒａｗ？↓

;jpn:◆いくらひきだしますか？↓
@GOSUB(_CD_INPUT_2)
@!

MSG_SUB_BGM_PIZZASTART;
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
;@FUNC(18)		;自転車から降りる
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
;@BGMSTART(0,BGM_piza)
@OPEN(1)
@!
MSG_SUB_BGM_PIZZAEND;
;@GOSUB(MSG_SUB_BGM_FADEOUT_05SECOND)
;@MUSISTART()
@!
