MSG_SUB_SHOPMES_1;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_1)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_1)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_1)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_1)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_1)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_1)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_1)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_1)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_1)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_1)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_1)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_1)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_1)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_1)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_1)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_1)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_1)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_1)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_1)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_1)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_1)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_1)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_1)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_1)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_1)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_1)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_1)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_1)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_1)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_1)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_1)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_1)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_1)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_1)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_1)
@!
MSG_SUB_SHOPMES_2;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_2)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_2)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_2)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_2)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_2)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_2)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_2)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_2)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_2)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_2)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_2)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_2)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_2)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_2)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_2)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_2)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_2)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_2)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_2)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_2)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_2)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_2)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_2)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_2)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_2)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_2)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_2)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_2)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_2)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_2)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_2)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_2)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_2)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_2)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_2)
@!
MSG_SUB_SHOPMES_3;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_3)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_3)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_3)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_3)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_3)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_3)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_3)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_3)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_3)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_3)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_3)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_3)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_3)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_3)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_3)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_3)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_3)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_3)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_3)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_3)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_3)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_3)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_3)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_3)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_3)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_3)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_3)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_3)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_3)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_3)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_3)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_3)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_3)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_3)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_3)
@!
MSG_SUB_SHOPMES_4;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_4)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_4)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_4)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_4)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_4)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_4)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_4)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_4)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_4)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_4)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_4)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_4)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_4)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_4)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_4)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_4)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_4)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_4)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_4)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_4)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_4)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_4)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_4)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_4)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_4)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_4)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_4)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_4)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_4)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_4)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_4)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_4)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_4)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_4)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_4)
@!
MSG_SUB_SHOPMES_5;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_5)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_5)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_5)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_5)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_5)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_5)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_5)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_5)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_5)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_5)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_5)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_5)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_5)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_5)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_5)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_5)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_5)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_5)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_5)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_5)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_5)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_5)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_5)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_5)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_5)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_5)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_5)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_5)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_5)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_5)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_5)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_5)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_5)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_5)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_5)
@!
MSG_SUB_SHOPMES_6;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_6)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_6)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_6)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_6)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_6)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_6)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_6)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_6)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_6)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_6)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_6)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_6)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_6)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_6)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_6)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_6)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_6)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_6)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_6)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_6)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_6)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_6)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_6)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_6)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_6)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_6)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_6)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_6)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_6)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_6)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_6)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_6)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_6)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_6)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_6)
@!
MSG_SUB_SHOPMES_7;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_7)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_7)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_7)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_7)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_7)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_7)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_7)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_7)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_7)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_7)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_7)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_7)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_7)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_7)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_7)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_7)
@!
MSG_SUB_SHOPMES_8;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_8)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_8)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_8)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_8)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_8)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_8)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_8)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_8)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_8)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_8)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_8)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_8)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_8)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_8)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_8)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_8)
@!
MSG_SUB_SHOPMES_9;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_9)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_9)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_9)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_9)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_9)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_9)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_9)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_9)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_9)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_9)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_9)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_9)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_9)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_9)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_9)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_9)
@!
MSG_SUB_SHOPMES_10;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_10)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_10)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_10)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_10)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_10)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_10)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_10)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_10)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_10)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_10)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_10)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_10)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_10)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_10)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_10)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_10)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_10)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_10)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_10)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_10)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_10)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_10)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_10)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_10)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_10)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_10)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_10)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_10)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_10)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_10)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_10)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_10)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_10)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_10)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_10)
@!
MSG_SUB_SHOPMES_11;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_11)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_11)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_11)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_11)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_11)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_11)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_11)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_11)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_11)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_11)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_11)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_11)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_11)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_11)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_11)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_11)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_11)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_11)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_11)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_11)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_11)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_11)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_11)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_11)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_11)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_11)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_11)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_11)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_11)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_11)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_11)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_11)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_11)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_11)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_11)
@!
MSG_SUB_SHOPMES_12;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_12)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_12)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_12)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_12)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_12)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_12)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_12)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_12)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_12)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_12)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_12)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_12)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_12)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_12)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_12)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_12)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_12)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_12)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_12)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_12)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_12)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_12)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_12)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_12)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_12)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_12)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_12)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_12)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_12)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_12)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_12)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_12)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_12)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_12)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_12)
@!
MSG_SUB_SHOPMES_13;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_13)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_13)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_13)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_13)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_13)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_13)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_13)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_13)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_13)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_13)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_13)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_13)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_13)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_13)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_13)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_13)
@!
MSG_SUB_SHOPMES_14;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_14)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_14)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_14)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_14)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_14)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_14)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_14)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_14)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_14)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_14)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_14)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_14)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_14)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_14)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_14)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_14)
@!
MSG_SUB_SHOPMES_15;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_15)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_15)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_15)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_15)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_15)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_15)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_15)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_15)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_15)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_15)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_15)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_15)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_15)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_15)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_15)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_15)
@!
MSG_SUB_SHOPMES_16;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_16)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_16)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_16)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_16)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_16)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_16)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_16)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_16)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_16)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_16)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_16)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_16)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_16)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_16)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_16)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_16)
@!
MSG_SUB_SHOPMES_17;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_17)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_17)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_17)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_17)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_17)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_17)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_17)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_17)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_17)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_17)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_17)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_17)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_17)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_17)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_17)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_17)
@!
MSG_SUB_SHOPMES_18;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_18)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_18)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_18)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_18)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_18)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_18)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_18)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_18)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_18)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_18)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_18)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_18)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_18)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_18)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_18)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_18)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_18)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_18)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_18)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_18)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_18)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_18)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_18)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_18)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_18)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_18)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_18)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_18)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_18)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_18)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_18)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_18)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_18)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_18)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_18)
@!
MSG_SUB_SHOPMES_20;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_20)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_20)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_20)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_20)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_20)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_20)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_20)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_20)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_20)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_20)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_20)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_20)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_20)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_20)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_20)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_20)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_20)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_20)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_20)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_20)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_20)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_20)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_20)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_20)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_20)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_20)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_20)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_20)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_20)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_20)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_20)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_20)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_20)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_20)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_20)
@!
MSG_SUB_SHOPMES_21;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_21)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_21)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_21)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_21)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_21)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_21)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_21)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_21)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_21)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_21)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_21)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_21)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_21)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_21)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_21)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_21)
@!
MSG_SUB_SHOPMES_22;
←
@CHKFGOTO(FLG_SHOP_01,MSG_SUB_SHOPMES_DRUG2_22)
@CHKFGOTO(FLG_SHOP_02,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_03,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_04,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_05,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_06,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_07,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_08,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_09,MSG_SUB_SHOPMES_DRUG4_22)
@CHKFGOTO(FLG_SHOP_10,MSG_SUB_SHOPMES_JUNK1_22)
@CHKFGOTO(FLG_SHOP_11,MSG_SUB_SHOPMES_BAKERY2_22)
@CHKFGOTO(FLG_SHOP_12,MSG_SUB_SHOPMES_FURI1_22)
@CHKFGOTO(FLG_SHOP_13,MSG_SUB_SHOPMES_BANANA_22)
@CHKFGOTO(FLG_SHOP_14,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_15,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_16,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_17,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_18,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_19,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_20,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_21,MSG_SUB_SHOPMES_GORI_22)
@CHKFGOTO(FLG_SHOP_22,MSG_SUB_SHOPMES_GRAVE_22)
@CHKFGOTO(FLG_SHOP_23,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_24,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_25,MSG_SUB_SHOPMES_DOSEI_22)
@CHKFGOTO(FLG_SHOP_26,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_27,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_28,MSG_SUB_SHOPMES_BENTO_22)
@CHKFGOTO(FLG_SHOP_29,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_30,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_31,MSG_SUB_SHOPMES_DRUG4_22)
@CHKFGOTO(FLG_SHOP_32,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_33,MSG_SUB_SHOPMES_BAKERY1_22)
@CHKFGOTO(FLG_SHOP_34,MSG_SUB_SHOPMES_TOYSHOP_22)
@CHKFGOTO(FLG_SHOP_35,MSG_SUB_SHOPMES_DRUG3_22)
@CHKFGOTO(FLG_SHOP_36,MSG_SUB_SHOPMES_BURGER_22)
@CHKFGOTO(FLG_SHOP_37,MSG_SUB_SHOPMES_FURI2_22)
@CHKFGOTO(FLG_SHOP_38,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_39,MSG_SUB_SHOPMES_JUNK2_22)
@CHKFGOTO(FLG_SHOP_40,MSG_SUB_SHOPMES_DRUG5_22)
@CHKFGOTO(FLG_SHOP_41,MSG_SUB_SHOPMES_REST_22)
@CHKFGOTO(FLG_SHOP_42,MSG_SUB_SHOPMES_DRUG6_22)
@CHKFGOTO(FLG_SHOP_43,MSG_SUB_SHOPMES_HISYO_22)
@CHKFGOTO(FLG_SHOP_44,MSG_SUB_SHOPMES_WIFE_22)
@CHKFGOTO(FLG_SHOP_45,MSG_SUB_SHOPMES_OKAYU_22)
@CHKFGOTO(FLG_SHOP_46,MSG_SUB_SHOPMES_DRUG7_22)
@CHKFGOTO(FLG_SHOP_47,MSG_SUB_SHOPMES_SNAKE_22)
@CHKFGOTO(FLG_SHOP_48,MSG_SUB_SHOPMES_DRUG8_22)
@CHKFGOTO(FLG_SHOP_49,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_50,MSG_SUB_SHOPMES_FURI1_22)
@CHKFGOTO(FLG_SHOP_51,MSG_SUB_SHOPMES_SKFOOD_22)
@CHKFGOTO(FLG_SHOP_52,MSG_SUB_SHOPMES_WATER_22)
@CHKFGOTO(FLG_SHOP_53,MSG_SUB_SHOPMES_MITUBAI_22)
@CHKFGOTO(FLG_SHOP_54,MSG_SUB_SHOPMES_DRUG1_22)
@CHKFGOTO(FLG_SHOP_55,MSG_SUB_SHOPMES_WEAPON_22)
@CHKFGOTO(FLG_SHOP_56,MSG_SUB_SHOPMES_GUMI_22)
@CHKFGOTO(FLG_SHOP_57,MSG_SUB_SHOPMES_RABBIT_22)
@CHKFGOTO(FLG_SHOP_58,MSG_SUB_SHOPMES_MOON_22)
@!
;
;ショップタイプＡのメッセージ
;
;男子店員（ｍａｌｅ ｃｌｅｒｋ）
MSG_SUB_SHOPMES_DRUG1_1;
MSG_SUB_SHOPMES_TOYSHOP_1;
◆Ｈｅｌｌｏ　ｔｈｅｒｅ！↓
　　Ｈｏｗ　ｍａｙ　Ｉ　ｈｅｌｐ　ｙｏｕ？↓

;jpn:◆いらっしゃいませ。@KEY()↓
;jpn:◆ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG1_2;
MSG_SUB_SHOPMES_TOYSHOP_2;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆どうもありがとうございました。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG1_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆またよろしくおねがいします。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG1_4;
MSG_SUB_SHOPMES_TOYSHOP_4;
◆Ｃａｎ　Ｉ　ｇｅｔ　ｙｏｕ↓
　　ａｎｙｔｈｉｎｇ？
;jpn:◆なにを　おかいもとめですか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_5;
MSG_SUB_SHOPMES_TOYSHOP_5;
◆@DSP_GOODS(0)？↓
　　Ａｌｌ　ｒｉｇｈｔ．

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_6;
MSG_SUB_SHOPMES_TOYSHOP_6;
◆Ｗｈｉｃｈ　ｏｆ　ｙｏｕ　ｗｉｌｌ　ｃａｒｒｙ　ｔｈｉｓ？

;jpn:◆どなたが　おもちになりますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_7;
MSG_SUB_SHOPMES_TOYSHOP_7;
◆Ｔｈａｎｋ　ｙｏｕ．　　Ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓

;jpn:◆ありがとうございます。↓
;jpn:　ここで　そうびしてみますか？↓
@!
MSG_SUB_SHOPMES_DRUG1_8;
MSG_SUB_SHOPMES_TOYSHOP_8;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｍｅ　ｔｏ　ｂｕｙ↓
　　ｔｈｅ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かいあげましょうか？↓
@!
MSG_SUB_SHOPMES_DRUG1_9;
MSG_SUB_SHOPMES_TOYSHOP_9;
◆@DSP_NAME(0)　ｃａｎｎｏｔ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは　これを↓
;jpn:　そうびできませんが@KEY()↓
;jpn:◆それでも　かいますか？↓
@!
MSG_SUB_SHOPMES_DRUG1_10;
MSG_SUB_SHOPMES_TOYSHOP_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆またよろしくおねがいします。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_11;
MSG_SUB_SHOPMES_TOYSHOP_11;
◆Ｅｘｃｕｓｅ　ｍｅ，　ｕｈｈｈ．．．　　ｙｏｕ　ｄｏｎ’ｔ　ｓｅｅｍ　ｔｏ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆しつれいですが‥‥↓
;jpn:　おかねが　たりないみたいですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_12;
MSG_SUB_SHOPMES_TOYSHOP_12;
◆Ｉ’ｍ　ａｆｒａｉｄ　ｙｏｕ　ｃａｎｎｏｔ　ｃａｒｒｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ｓｏｍｅ　ｔｈｉｎｇｓ　ｔｈａｔ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ？↓

;jpn:◆あいにくですが↓
;jpn:　それいじょう　にもつを↓
;jpn:　もてないようですよ。@KEY()↓
;jpn:◆いらないにもつを　うりますか？↓
@!
MSG_SUB_SHOPMES_DRUG1_13;
MSG_SUB_SHOPMES_TOYSHOP_13;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ？

;jpn:◆なにを　おうりになりますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG1_14;
MSG_SUB_SHOPMES_TOYSHOP_14;
◆@DSP_GOODS(0)？↓
　　Ｉ　ｃａｎ　ｂｕｙ　ｉｔ↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｄｏ　ｔｈａｔ？↓

;jpn:◆@DSP_GOODS(0)ですね。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　おひきとりしますが。@KEY()↓
;jpn:◆よろしいですか？↓
@!
MSG_SUB_SHOPMES_DRUG1_15;
MSG_SUB_SHOPMES_TOYSHOP_15;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　よろしくおねがいします。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_16;
MSG_SUB_SHOPMES_TOYSHOP_16;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ａｎｙ　ｔｈｉｎｇ　ｔｈａｔ　ｙｏｕ　ｃａｎ　ｓｅｌｌ．

;jpn:◆おうりになるものが↓
;jpn:　ないようですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_17;
MSG_SUB_SHOPMES_TOYSHOP_17;
◆Ｉ　ａｍ　ｓｏｒｒｙ，ｂｕｔ　ｗｅ　ｃａｎｎｏｔ　ｂｕｙ　ｔｈｅ　@DSP_GOODS(0)．
;jpn:◆あいにくですが↓
;jpn:　@DSP_GOODS(0)は↓
;jpn:　おひきとりできかねます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_18;
MSG_SUB_SHOPMES_TOYSHOP_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆ありがとうございました。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_19;
MSG_SUB_SHOPMES_TOYSHOP_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｓｈｏｐｐｉｎｇ　ｈｅｒｅ．

;jpn:◆まいど　ありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG1_20;
MSG_SUB_SHOPMES_TOYSHOP_20;
◆Ｃａｎ　Ｉ　ｇｅｔ　ｙｏｕ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓
;jpn:◆ほかに　ごようはございますか？↓
@!
MSG_SUB_SHOPMES_DRUG1_21;
MSG_SUB_SHOPMES_TOYSHOP_21;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｇｅｔ　ｎｅｘｔ？↓
;jpn:◆こんどの　ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG1_22;
MSG_SUB_SHOPMES_TOYSHOP_22;
◆Ｉｔ　ｌｏｏｋｅ　ｌｉｋｅ　@DSP_NAME(0)　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｓｔｕｆｆ．@KEY()↓
◆Ｗｏｕｌｄ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｌｉｋｅ　ｔｏ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつがいっぱいみたいですよ。@KEY()↓
;jpn:◆ほかのひとが　もちますか？↓
@!
;オカマ（ｅｆｆｅｍｉｎａｔｅ）
MSG_SUB_SHOPMES_DRUG2_1;
◆Ｈｉ，　ｃｏｍｅ　ｉｎ，　ｃｏｍｅ　ｉｎ！
@KEY()↓
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｄｏ　ｆｏｒ　ｙｏｕ　ｔｏｄａｙ？↓
;jpn:◆いらっしゃーい。@KEY()↓
;jpn:◆どんなごようかしら？↓
@!
MSG_SUB_SHOPMES_DRUG2_2;
◆Ｔｈａｎｋｓ　ａ　ｂｕｎｃｈ！

;jpn:◆どうも　ありがとッ！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG2_3;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｆｒｏｍ　ｍｅ？@KEY()↓
◆Ｏｈ，　ｙｏｕ　ｈｕｒｔ　ｍｙ　ｆｅｅｌｉｎｇｓ．
;jpn:◆わたしからは↓
;jpn:　かいたくないのね。@KEY()↓
;jpn:◆サミシイッ！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG2_4;
◆Ｃａｎ　Ｉ　ｈｅｌｐ　ｙｏｕ　ｆｉｎｄ　ｓｏｍｅｔｈｉｎｇ？
;jpn:◆なにを　おかいもとめかしら？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_5;
◆@DSP_GOODS(0)？
;jpn:◆@DSP_GOODS(0)ね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_6;
◆Ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？
;jpn:◆どなたが　おもちになるの？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_7;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ，　ｌｉｋｅ，　”ｅｑｕｉｐ”　ｉｔ　ｈｅｒｅ？↓
;jpn:◆ここで↓
;jpn:　「そうび」とか　してみる？↓
@!
MSG_SUB_SHOPMES_DRUG2_8;
◆Ｉ　ｃａｎ　ｂｕｙ　ｙｏｕｒ↓
　　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かってあげるけど？↓
@!
MSG_SUB_SHOPMES_DRUG2_9;
◆@DSP_NAME(0)　　ｃａｎ’ｔ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)さんは
;jpn:　これって↓
;jpn:　そうびできないけど@KEY()↓
;jpn:◆それでも↓
;jpn:　かったりするー？↓
@!
MSG_SUB_SHOPMES_DRUG2_10;
◆Ｓｏ，　ｙｏｕ　ｓａｙ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｉｔ．．．　Ｈｍｍｍｍ．．．

;jpn:◆かわないわけね。↓
;jpn:　フン。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_11;
◆Ｏｈ　ｎｏ！↓
　　Ｄｏｎ’ｔ　ｔｅｌｌ　ｍｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ！！

;jpn:◆うっそー！@WI(10)↓
;jpn:　おかねが　たりないじゃないのー！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_12;
◆Ｏｈ，　ｍｙ！@KEY()↓
◆Ｉ　ｊｕｓｔ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｔｈａｎ　ｗｈａｔ　ｙｏｕ　ａｌｒｅａｄｙ　ｈａｖｅ．@KEY()↓
◆Ｂｕｔ　ｙｏｕ　ｋｎｏｗ，　Ｉ　ｍｉｇｈｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｂｕｙ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｓｔｕｆｆ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ．@KEY()↓
;jpn:◆まあ@WI(10)↓
;jpn:　それいじょう　にもつを↓
;jpn:　もてないみたいよー。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとるけど？↓
@!
MSG_SUB_SHOPMES_DRUG2_13;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ？

;jpn:◆なにを　うりたいわけー？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG2_14;
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｂｕｙ　ｉｔ　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｎａ　ｓｅｌｌ　ｉｔ？↓
;jpn:◆@DSP_GOODS(0)ね。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで　ひきとるわよ。@KEY()↓
;jpn:◆いいかしら？↓
@!
MSG_SUB_SHOPMES_DRUG2_15;
◆Ｏｈ，　ｓｏ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｄｏ　ｔｈａｔ？↓
　　Ｗｅｌｌ，　ａｌｌ　ｒｉｇｈｔ．

;jpn:◆あ@WI(10)　そう。↓
;jpn:　やめるのね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_16;
◆Ｗｅｌｌ，　ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ　ｔｏ　ｕｓ．
;jpn:◆だって　うるものが↓
;jpn:　ないじゃない。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_17;
◆Ｏｈ，ｎｏ！↓
　　Ｙｏｕ　ｃａｎ’ｔ　ｓｅｌｌ　ｔｈａｔ　ｈｅｒｅ．

;jpn:◆イヤだーッ↓
;jpn:　それって　うちじゃ↓
;jpn:　かえないわよ‥‥。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_18;
◆Ｔｈａｎｋｓ　ａ　ｂｕｎｃｈ！

;jpn:◆どうも　ア・リ・ガ・トッ！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_19;
◆Ｔｈａｎｋｓ　ａｇａｉｎ．

;jpn:◆いつも　アリガトッ！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG2_20;
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｆｒｏｍ　ｍｅ？↓
;jpn:◆ほかに↓
;jpn:　なにかようかしら？↓
@!
MSG_SUB_SHOPMES_DRUG2_21;
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｄｏ　ｆｏｒ　ｙｏｕ？↓
;jpn:◆どんな　ごようかしら？↓
@!
MSG_SUB_SHOPMES_DRUG2_22;
◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｄｏｅｓ　ａｎｙｏｎｅ　ｅｌｓｅ　ｗａｎｔ　ｔｏ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)ちゃんは↓
;jpn:　にもついっぱいね。@KEY()↓
;jpn:◆ほかのひとが↓
;jpn:　もったりなんかするぅ？↓
@!
;スポーツ若者（ｊｏｃｋ）
MSG_SUB_SHOPMES_DRUG3_1;
◆Ｈｅｙ　ｄｕｄｅｓ！　　Ｉｔ’ｓ　ｓｕｍｍｅｒ！↓
　　Ｉｔ’ｓ　ｔｈｅ　ｍａｎｌｙ　ｔｉｍｅ　ｏｆ　ｙｅａｒ！↓
　　Ｔｉｍｅ　ｆｏｒ　ｓｐｏｒｔｓ，　ｇｕｙｓ！@KEY()↓
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｄｏ　ｙｏｕ　ｆｏｒ？↓
;jpn:◆なつだ！↓
;jpn:　わかものだ！↓
;jpn:　スポーツだ！@KEY()↓
;jpn:◆ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG3_2;
◆Ｈｅｙ　ｂｕｄｄｙ，　ｔｈａｎｋｓ！@KEY()↓
◆Ｓｅｅ　ｙｏｕ　ａｒｏｕｎｄ！

;jpn:◆どうもありがとう！↓
;jpn:　また　こいよ！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG3_3;
◆Ｉｆ　ｙｏｕ　ｅｖｅｒ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ，　ｃｏｍｅ　ｂａｃｋ　ｈｅｒｅ，　ａｎｄ　Ｉ’ｌｌ　ｓｅｔ　ｙｏｕ　ｕｐ！

;jpn:◆ようがあったら↓
;jpn:　いつでも　おいで！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG3_4;
◆Ｓｏ　ｗｈａｔ’ｌｌ　ｉｔ　ｂｅ　ｔｏｄａｙ？

;jpn:◆なにを　かうんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_5;
◆@DSP_GOODS(0)？
;jpn:◆@DSP_GOODS(0)だね！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_6;
◆Ｗｈｉｃｈ　ｏｆ　ｙｏｕ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？
;jpn:◆だれが　もつんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_7;
◆Ｓｏ，　ｍａｎ，　ａｒｅ　ｙｏｕ　ｇｏｎｎａ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓
;jpn:◆ここで　そうびしてみるかい？↓
@!
MSG_SUB_SHOPMES_DRUG3_8;
◆Ｃａｎ　Ｉ　ｂｕｙ　ｙｏｕｒ↓
　　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでかいあげようか？↓
@!
MSG_SUB_SHOPMES_DRUG3_9;
◆@DSP_NAME(0)　ｃａｎ’ｔ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ｄｏ　ｙａ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)くんは↓
;@XCHG()
;jpn:　@DSP_GOODS(0)を↓
;jpn:　そうびできないけれど@KEY()↓
;jpn:◆それでも　かうのかい？↓
@!
MSG_SUB_SHOPMES_DRUG3_10;
◆Ｃａｔｃｈ　ｙａ　ｌａｔｅｒ！

;jpn:◆また　よろしく！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_11;
◆Ｏｈ，　ｍｏｓｔ　ｈｅｉｎｏｕｓ！↓
　　Ｙｏｕ　ｄｕｄｅｓ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ　ｆｏｒ　ｔｈｉｓ．

;jpn:◆だめだ！↓
;jpn:　おかねがたりないようだよ！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_12;
◆Ｄｕｄｅｓ！↓
　　Ｙｏｕ　ｓｉｍｐｌｙ　ｈａｖｅ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ｉｎ　ｙｏｕｒ　ｋｉｔ！
@KEY()↓
◆Ｂｕｔ　ｄｏｎ’ｔ　ｓｗｅａｔ　ｉｔ，　Ｉ　ｃａｎ　ｂｕｙ　ｓｏｍｅ　ｓｔｕｆｆ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ．↓
;jpn:◆だめだ！↓
;jpn:　もちものがいっぱいだよ！@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かってあげよう！↓
@!
MSG_SUB_SHOPMES_DRUG3_13;
◆Ｎｏｗ，　ｙｏｕ’ｒｅ　ｓｕｒｅ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ｔｈｉｓ　ｔｏ　ｍｅ．．．

;jpn:◆なにをうるんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG3_14;
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｂｕｙ　ｉｔ　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｙｏｕ　ｐｏｓｉｔｉｖｅ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ｉｔ？↓
;jpn:◆@DSP_GOODS(0)だねー！@KEY()↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　ひきとるよ。@KEY()↓
;jpn:◆いいかい？↓
@!
MSG_SUB_SHOPMES_DRUG3_15;
◆ＯＫ．

;jpn:◆そうかい。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_16;
◆Ｍａｎ，　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ　ｍｅ！

;jpn:◆きみはうるものを↓
;jpn:　もってないじゃないか！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_17;
◆Ｓｏｒｒｙ　ｄｕｄｅ，　ｂｕｔ　Ｉ　ｃａｎ’ｔ　ｂｕｙ　ｔｈａｔ．

;jpn:◆わるいけど↓
;jpn:　それは　かえないよ！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_18;
◆Ｔｈａｎｋｓ！

;jpn:◆ありがとう！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_19;
◆Ｔｈａｎｋｓ，　ｂｕｄｄｙ！

;jpn:◆ありがとう！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG3_20;
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　Ｉ　ｃａｎ　ｄｏ　ｆｏｒ　ｙｏｕ？↓
;jpn:◆ほかになにか↓
;jpn:　ようはあるかい？↓
@!
MSG_SUB_SHOPMES_DRUG3_21;
◆Ｗｈａｔ　ｉｓ　ｉｔ？↓
;jpn:◆ようはなんだい？↓
@!
MSG_SUB_SHOPMES_DRUG3_22;
◆@DSP_NAME(0)　ｈａｓ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｄｏｅｓ　ｓｏｍｅｂｏｄｙ　ｅｌｓｅ　ｗａｎｔ　ｔｏ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)くんは↓
;jpn:　にもつがいっぱいだよ！@KEY()↓
;jpn:◆ほかのひとが　もつかい？↓
@!
;女子店員（ｓａｌｅｓ ｇｉｒｌ）
MSG_SUB_SHOPMES_DRUG4_1;
◆Ｈｉ！@KEY()↓
◆Ｃａｎ　Ｉ　ｈｅｌｐ　ｙｏｕ？↓
;jpn:◆いらっしゃーい。@KEY()↓
;jpn:◆どんなごようかしら？↓
@!
MSG_SUB_SHOPMES_DRUG4_2;
◆Ｔｈａｎｋｓ　ｓｏ　ｍｕｃｈ！
;jpn:◆ありがとうございましたー。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG4_3;
◆Ａｒｅ　ｙｏｕ　ｈｅｒｅ　ｊｕｓｔ　ｔｏ　ｓａｙ　”Ｈｉ”？　　Ｗｈａｔ　ａ　ｌｏｓｅｒ！

;jpn:◆ようもないのに↓
;jpn:　こえをかけたのね。@KEY()↓
;jpn:◆ひどいひと！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG4_4;
◆Ｓｏ，　ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ？

;jpn:◆なにを　かうのかしら？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)ね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_6;
◆Ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？

;jpn:◆だれが　もちますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_7;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓
;jpn:◆ここで　そうびしてみる？↓
@!
MSG_SUB_SHOPMES_DRUG4_8;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かいあげましょうか？↓
@!
MSG_SUB_SHOPMES_DRUG4_9;
◆Ｅｖｅｎ　ｔｈｏｕｇｈ　@DSP_NAME(0)　ｃａｎ’ｔ　ｅｑｕｉｐ　ｔｈｉｓ，　ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｐｕｒｃｈａｓｅ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)くんはこれを↓
;jpn:　そうびできませんが@KEY()↓
;jpn:◆それでも　かいますか？↓
@!
MSG_SUB_SHOPMES_DRUG4_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　よろしくね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_11;
◆Ｉ’ｍ　ｓｏｒｒｙ，　ｂｕｔ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆わるいけど↓
;jpn:　おかねが　たりないみたいね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_12;
◆Ｏｈ，　ｈｏｗ　ａｒｅ　ｙｏｕ　ｐｌａｎｎｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？　　Ｙｏｕ’ｖｅ　ｇｏｔ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ！@KEY()↓
◆Ｗｅｌｌ，　Ｉ　ｇｕｅｓｓ　Ｉ　ｃｏｕｌｄ　ｂｕｙ　ｔｈｅ　ｓｔｕｆｆ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ａｎｙｔｈｉｎｇ？↓
;jpn:◆あら↓
;jpn:　にもつが　いっぱいだわ。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとるけど　いい？↓
@!
MSG_SUB_SHOPMES_DRUG4_13;
◆Ｗｈａｔ　ｃａｎ　ｙｏｕ　ｓｅｌｌ　ｍｅ？

;jpn:◆なにを　うってくれるの？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG4_14;
◆@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｐａｙ　@XCHG()＄@DSP_NUM(0)　ｆｏｒ　ｉｔ．@KEY()↓
◆Ｉｓ　ｔｈａｔ　ｏｋａｙ？↓
;jpn:◆@DSP_GOODS(0)ね。@KEY()↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　ひきとるわ。@KEY()↓
;jpn:◆それでいい？↓
@!
MSG_SUB_SHOPMES_DRUG4_15;
◆Ｈｕｍｍｍ．　　Ｉｓ　ｔｈａｔ　ｓｏ？

;jpn:◆ふーん　そうなの。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_16;
◆Ｏｈ，　ｓｏ　ｙｏｕ　ｄｏｎ’ｔ　ｒｅａｌｌｙ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ？

;jpn:◆あら　あなた↓
;jpn:　うるものが　ないわよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_17;
◆Ｉ’ｍ　ｓｏｒｒｙ，ｂｕｔ　Ｉ　ｃａｎ’ｔ　ｂｕｙ　ｔｈａｔ．

;jpn:◆あら　わるいけど↓
;jpn:　そのしなものはひきとれないわ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆ありがとうございましたー。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_19;
◆Ｔｈａｎｋ　ｙｏｕ．

;jpn:◆どうもありがとう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG4_20;
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　Ｉ　ｃａｎ　ｄｏ　ｆｏｒ　ｙｏｕ？↓
;jpn:◆ほかに　ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG4_21;
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｄｏ　ｆｏｒ　ｙｏｕ　ｎｏｗ？↓
;jpn:◆こんどのごようは？↓
@!
MSG_SUB_SHOPMES_DRUG4_22;
◆@DSP_NAME(0)　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｗｉｌｌ　ａｎｏｔｈｅｒ　ｏｎｅ　ｏｆ　ｙｏｕ　ｔａｋｅ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつが　いっぱいね。@KEY()↓
;jpn:◆ほかのひとが　もちますか？↓
@!
;グラサン（ｇｕｙ ｗｉｔｈ ｓｕｎｇｌａｓｓｅｓ）
MSG_SUB_SHOPMES_DRUG5_1;
◆Ｈｉ！　　Ｗｅｌｃｏｍｅ　ｔｏ　ｍｙ　ｓｔｏｒｅ．@KEY()↓
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｎｅｅｄ？↓
;jpn:◆ハーイ　イラッシャーイ@KEY()↓
;jpn:◆ようは　なんだい？↓
@!
MSG_SUB_SHOPMES_DRUG5_2;
◆Ｔｈａｎｋ　ｙｏｕ！

;jpn:◆どうもありがとう！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG5_3;
◆Ｔｈｉｓ　ｐｌａｃｅ　ｉｓｎ’ｔ　ｆｏｒ　ｌｏｏｋｙ　ｌｏｏｓ．　　Ｉｆ　ｙｏｕ’ｒｅ　ｎｏｔ　ｂｕｙｉｎｇ，　ｇｅｔ　ｏｕｔ！

;jpn:◆ひやかしなら↓
;jpn:　とっととかえんな！
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG5_4;
◆Ｓｏ，　ｙｏｕ’ｒｅ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ　ｓｏｍｅｔｈｉｎｇ，　ｅｈ？

;jpn:◆なにを　かうんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)だね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_6;
◆Ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？

;jpn:◆だれが　もつ？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_7;
◆Ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓
;jpn:◆ここで　そうびしてみるかい？↓
@!
MSG_SUB_SHOPMES_DRUG5_8;
◆Ｉ’ｌｌ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．↓
;jpn:◆@DSP_GOODS(0)なら↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでひきとるけど？↓
@!
MSG_SUB_SHOPMES_DRUG5_9;
◆Ｅｖｅｎ　ｔｈｏｕｇｈ　@DSP_NAME(0)　ｃａｎ’ｔ　ｐｕｔ　ｔｈｉｓ　ｏｎ，　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？@KEY()↓
◆Ｗｅｌｌ，　ｉｔ’ｓ　ｙｏｕｒ　ｍｏｎｅｙ．．．↓
;jpn:◆@DSP_NAME(0)は　これを↓
;jpn:　そうびできないけど@KEY()↓
;jpn:◆それでも　かうのかい？↓
@!
MSG_SUB_SHOPMES_DRUG5_10;
◆Ｈｕｒｒｙ　ｂａｃｋ　ｎｏｗ．

;jpn:◆また　よろしくな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_11;
◆Ｈｅｙ！　　Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｔｒｙｉｎｇ　ｔｏ　ｐｕｌｌ？！　　Ｙｏｕ　ｈａｖｅｎ’ｔ　ｇｏｔ　ｅｎｏｕｇｈ　ｍｏｎｅｙ！！

;jpn:◆おい！　おれをなめてんのか！↓
;jpn:　かねが　たりないじゃないか！
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_12;
◆Ｈｅｙ！　　Ｙｏｕ’ｖｅ　ａｌｒｅａｄｙ　ｈａｖｅ　ｇｏｔ　ｅｎｏｕｇｈ　ｊｕｎｋ！@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ｍｅ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｊｕｎｋ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ？↓
;jpn:◆おい！↓
;jpn:　にもつが　いっぱいだぞ！@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとってやろうか？↓
@!
MSG_SUB_SHOPMES_DRUG5_13;
◆Ｗｈａｔ　ｃａｎ　ｙｏｕ　ｓｅｌｌ　ｍｅ？

;jpn:◆なにを　うってくれるんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG5_14;
◆@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｈｏｗ　ｗｏｕｌｄ　ｔｈａｔ　ｂｅ？↓
;jpn:◆@DSP_GOODS(0)か‥‥@KEY()↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルだな。@KEY()↓
;jpn:◆それでいいかい？↓
@!
MSG_SUB_SHOPMES_DRUG5_15;
◆Ｈｕｒｒｍ．　　Ｃｈａｎｇｅｄ　ｙｏｕｒ　ｍｉｎｄ，　ｅｈ？

;jpn:◆ふん　そうかい。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_16;
◆Ｃ’ｍｏｎ！↓
　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ，　ｄｏ　ｙｏｕ？！
;jpn:◆なんだよ！↓
;jpn:　うるものが　ないじゃないか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_17;
◆Ｓｏｒｒｙ，　ｂｕｔ　Ｉ　ｈａｖｅ　ｎｏ　ｕｓｅ　ｆｏｒ　ｔｈａｔ．

;jpn:◆わりいな　そいつは↓
;jpn:　ひきとれないんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_18;
◆Ｈｅｙ，　ｉｔ　ｗａｓ　ｎｉｃｅ　ｄｏｉｎｇ　ｂｕｓｉｎｅｓｓ　ｗｉｔｈ　ｙｏｕ．

;jpn:◆ありがとよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_19;
◆Ｔｈａｎｋｓ．

;jpn:◆まいどありー。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG5_20;
◆Ｗｉｌｌ　ｔｈｅｒｅ　ｂｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓
;jpn:◆ほかに　なんか　よう？↓
@!
MSG_SUB_SHOPMES_DRUG5_21;
◆Ｗｈａｔ　ｅｌｓｅ　ｄｏ　ｙｏｕ　ｗａｎｔ？↓
;jpn:◆こんどの　ようは？↓
@!
MSG_SUB_SHOPMES_DRUG5_22;
◆@DSP_NAME(0)　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙｍｏｒｅ　ｓｔｕｆｆ．@KEY()↓
◆Ｃａｎ　ｏｎｅ　ｏｆ　ｙｏｕ　ｏｔｈｅｒｓ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつが　いっぱいじゃないか！@KEY()↓
;jpn:◆ほかのやつが　もつか？↓
@!
;海の男（ｍａｎ ｏｆ ｏｃｅａｎ）

MSG_SUB_SHOPMES_DRUG6_1;
◆Ｉｆ　ｙｅ　ｂｅ　ｈｅａｄｉｎ’　ｔｏ　Ｓｃａｒａｂａ，　ｙｅ　ｏｕｇｈｔ　ｔｏ　ｓｈｏｐ　ｈｅｒｅ．@KEY()↓
◆Ｔｈｉｎｇｓ’ｒｅ　ｅｘｐｅｎｓｉｖｅ　ｄｏｗｎ　ｔｈｅｒｅ．．．@KEY()↓
◆Ｓｏ，　ｗｈａｔ’ｒｅ　ｙｅ　ｌｏｏｋｉｎ’　ｆｅｒ？↓
;jpn:◆スカラビにゆくんだったら↓
;jpn:　かっていきなよ。　あそこは↓
;jpn:　もののねだんが　たかいから。@KEY()↓
;jpn:◆ようは　なんだい？↓
@!
MSG_SUB_SHOPMES_DRUG6_2;
◆Ｔｈａｎｋｓ　ｍｕｃｈ．@KEY()↓
◆Ｉｆ’ｎ　ｙｅｒ　ｇｏｉｎｇ　ｔｏ　Ｓｃａｒａｂａ，　ｔａｋｅ　ｃａｒｅ　ｏｆ　ｙｅｒｓｅｌｆ．
;jpn:◆ありがとう。↓
;jpn:　スカラビにいくんだったら↓
;jpn:　きをつけてな。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG6_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ！

;jpn:◆また　きておくれよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG6_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｅ　ｌｉｋｅ，　ｔｈｅｎ？
;jpn:◆なににする？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)だね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_6;

◆Ｗｈｉｃｈ　ｏｆ　ｙｅ　ｉｓ　ｇｏｉｎ’　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？

;jpn:◆だれが　もつんだい？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_7;
◆Ｗｏｕｌｄ　ｙｅ　ｌｉｋｅ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ，　ｔｈｅｎ？↓
;jpn:◆ここでそうび↓
;jpn:　してみるかい？↓
@!
MSG_SUB_SHOPMES_DRUG6_8;
◆Ｗｏｕｌｄ　ｙｅ　ｌｉｋｅ　ｉｔ　ｉｆ　Ｉ　ｂｏｕｇｈｔ　ｙｅｒ↓
　　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでひきとろうか？↓
@!
MSG_SUB_SHOPMES_DRUG6_9;
◆@DSP_NAME(0)　ｃａｎｎｏｔ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ｄｏ　ｙｅ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？↓
;jpn:◆これは↓
;jpn:　@DSP_NAME(0)くんには↓
;jpn:　そうびできないけれど@KEY()↓
;jpn:◆それでも　かうのかい？↓
@!
MSG_SUB_SHOPMES_DRUG6_10;
◆Ｙｅｒ　ｎｏｔ　ｇｏｉｎ’　ｔｏ　ｂｕｙ　ｔｈｉｓ　ｔｈｉｎｇ？　　Ａｌｌ　ｒｉｇｈｔｙ　ｔｈｅｎ．

;jpn:◆そうか　やめるか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_11;
◆Ｂｅｇｇｉｎ’　ｙｅｒ　ｐａｒｄｏｎ，　ｂｕｔ　ｉｔ　ａｐｐｅａｒｓ　ｙｅ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．．．

;jpn:◆おかねがたりないようだよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_12;
◆Ｙｏｕ’ｖｅ　ｇｏｔ　ｅｎｔｉｒｅｌｙ　ｔｏｏ　ｍａｎｙ　ｇｏｏｄｉｅｓ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｅ　ｌｉｋｅ　ｍｅ　ｔｏ　ｔａｋｅ　ｓｏｍｅ　ｏｆ　ｔｈｏｓｅ　ｔｈｉｎｇｓ　ｏｆｆ　ｙｅｒ　ｈａｎｄｓ？@KEY()↓
◆Ｉ　ｃａｎ　ｂｕｙ　ｔｈｅ　ｏｎｅｓ　ｙｅ　ｄｏｎ’ｔ　ｎｅｅｄ，　ｉｆ　ｙｅ　ｗａｎｔ．↓
;jpn:◆もちものが　いっぱいだな。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとってあげようか？↓
@!
MSG_SUB_SHOPMES_DRUG6_13;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｅ　ｌｉｋｅ　ｔｏ　ｓｅｌｌ　ｍｅ，　ｔｈｅｎ？

;jpn:◆なにを　うってくれるんだい。
@KEY()
@!
MSG_SUB_SHOPMES_DRUG6_14;
◆@DSP_GOODS(0)？
　　Ｉ　ｗｏｕｌｄ　ｐａｙ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ａｒｅ　ｙｅ　ｈａｐｐｙ　ｗｉｔｈ　ｍｙ　ｏｆｆｅｒ？↓
;jpn:◆@DSP_GOODS(0)か。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルだな。@KEY()↓
;jpn:◆このねだんで　いいかい？↓
@!
MSG_SUB_SHOPMES_DRUG6_15;
◆Ｏｈ，　ｉｔ’ｓ　ｎｏｔ　ｑｕｉｔｅ　ｗｈａｔ　ｙｅ　ｅｘｐｅｃｔｅｄ？　　Ｗｅｌｌ，　ａｌｌ　ｒｉｇｈｔｙ　ｔｈｅｎ．

;jpn:◆そうか　やめるか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_16;
◆Ｏｈ？　　Ｗｅｌｌ，　ｉｔ　ａｐｐｅａｒｓ　ｔｏ　ｍｅ　ｔｈａｔ　ｙｅ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ．

;jpn:◆おや？↓
;jpn:　うるものが　ないようだね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_17;
◆Ｂｅｇｇｉｎ’　ｙｅｒ　ｐａｒｄｏｎ，　ｂｕｔ　Ｉ　ｃａｎ’ｔ　ｂｕｙ　ｔｈａｔ．

;jpn:◆それは　ちょっと↓
;jpn:　ひきとれないんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_18;
◆Ｈｅｒｅ　ｙｅ　ｇｏ．　　Ｔｈａｎｋ　ｙｅ．

;jpn:◆はい　ありがとう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_19;
◆Ｔｈａｎｋ　ｙｅ　ｋｉｎｄｌｙ．

;jpn:◆はい　まいどあり
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG6_20;
◆Ｗｉｌｌ　ｙｅ　ｂｅ　ｎｅｅｄｉｎ’　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓
;jpn:◆ほかにようはあるかい？↓
@!
MSG_SUB_SHOPMES_DRUG6_21;
◆Ｗｈａｔ　ｄｏ　ｙｅ　ｎｅｅｄ　ｎｏｗ？↓
;jpn:◆こんどのごようは？↓
@!
MSG_SUB_SHOPMES_DRUG6_22;
◆Ｉｔ　ａｐｐｅａｒｓ　@DSP_NAME(0)　ｈａｓ　ａ　ｆｕｌｌ　ｌｏａｄ．@KEY()↓
◆Ｗｉｌｌ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｔａｋｅ　ｔｈｉｓ　ｉｎｓｔｅａｄ？↓
;jpn:◆@DSP_NAME(0)くんは↓
;jpn:　にもつが　いっぱいだね。@KEY()↓
;jpn:◆べつのひとが　もつかい？↓
@!
;ターバン（ｍａｎ ｗｉｔｈ ｔｕｒｂａｎ）

MSG_SUB_SHOPMES_DRUG7_1;
◆Ｗｅｌｃｏｍｅ，　ｗｅｌｃｏｍｅ！　　Ａｃｈ，　ｔｈｅ　ｈｅａｔ！　　Ｉｓ　ｙｏｕｒ　ｂｏｄｙ　ｏｋａｙ？@KEY()↓
◆Ｃａｎ　Ｉ　ｉｎｔｅｒｅｓｔ　ｙｏｕ　ｉｎ　ｓｏｍｅ　ｏｆ　ｍｙ　ｍｅｒｃｈａｎｄｉｓｅ？↓
;jpn:◆そとは　あついね。↓
;jpn:　カラダ　だいじょうぶ？@KEY()↓
;jpn:◆ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG7_2;
◆Ｏｈｈ，　ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．　　Ｍａｙ　ｙｏｕ　ｎｅｖｅｒ　ｆｉｎｄ　ｒｏｃｋｓ　ｉｎ　ｙｏｕｒ　ｓａｎｄａｌｓ．

;jpn:◆どうもありがとう。↓
;jpn:　カラダ　きをつけてね。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG7_3;
◆Ｗｈｙ　ｄｏｎ’ｔ　ｙｏｕ　ｂｕｙ　ｓｏｍｅｔｈｉｎｇ？　　Ｉ’ｖｅ　ｇｏｔ　ａ　ｆａｍｉｌｙ　ｔｏ　ｆｅｅｄ！

;jpn:◆なんか　かえばいいのに。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG7_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？

;jpn:◆なんにしますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)ですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_6;
◆Ｓｏ，　ｗｈｉｃｈ　ｏｆ　ｙｏｕ　ｗｉｌｌ　ｔａｋｅ　ｔｈｉｓ　ｗｏｎｄｅｒｆｕｌ　ｉｔｅｍ？

;jpn:◆だれがもちますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_7;
◆Ｗｉｌｌ　ｙｏｕ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓
;jpn:◆ここでそうびしてみますか？↓
@!
MSG_SUB_SHOPMES_DRUG7_8;
◆Ｗｏｕｌｄ　ｙｏｕ　ｂｅ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ｓｅｌｌｉｎｇ　ｙｏｕｒ　@DSP_GOODS(0)@KEY()↓
◆ｆｏｒ　@XCHG()＄@DSP_NUM(0)？↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　かいあげましょうか？↓
@!
MSG_SUB_SHOPMES_DRUG7_9;
◆@DSP_NAME(0)　ｗｉｌｌ　ｈａｖｅ　ｎｏ　ｕｓｅ　ｆｏｒ　ｔｈｉｓ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｔｈｉｓ　ｍａｒｖｅｌｏｕｓ　ｔｈｉｎｇ？↓
;jpn:◆@DSP_NAME(0)さんには↓
;jpn:　そうびできないけれど@KEY()↓
;jpn:◆それでも　かいますか？↓
@!
MSG_SUB_SHOPMES_DRUG7_10;
◆Ｖｅｒｙ　ｗｅｌｌ　ｔｈｅｎ．

;jpn:◆そうですか。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_11;
◆Ａ　ｔｈｏｕｓａｎｄ　ｐａｒｄｏｎｓ，　ｂｕｔ　ｙｏｕ　ｄｏ　ｎｏｔ　ｓｅｅｍ　ｔｏ　ｈａｖｅ　ｔｈｅ　ｍｏｎｅｙ　ｒｅｑｕｉｒｅｄ　ｔｏ　ｍａｋｅ　ｔｈｉｓ　ｐｕｒｃｈａｓｅ．

;jpn:◆おかね　たりないみたいですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_12;
◆Ａｈｈ，　Ｉ　ｃａｎ　ｓｅｅ　ｔｈａｔ　ｙｏｕｒ　ｃａｒａｖａｎ　ｉｓ　ｏｖｅｒｌｏａｄｅｄ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｅｌｌ　ｓｏｍｅ　ｏｆ　ｙｏｕｒ　ｅｘｔｒａ　ｉｔｅｍｓ　ｔｏ　ｍｅ？↓
;jpn:◆もちものが　いっぱいですね。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとりましょうか？↓
@!
MSG_SUB_SHOPMES_DRUG7_13;
◆Ｖｅｒｙ　ｗｅｌｌ　ｔｈｅｎ，　ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｅｌｌ？

;jpn:◆なにを　うってくれますか？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG7_14;
◆@DSP_GOODS(0)？↓
　　Ａｈｈｈ，　Ｉ　ｗｏｕｌｄ　ｐａｙ　ｙｏｕ．．．↓
　　@XCHG()＄@DSP_NUM(0)　ｆｏｒ　ｔｈａｔ．@KEY()↓
◆Ａ　ｔｒｉｆｌｅ，　Ｉ　ｒｅａｌｉｚｅ，　ｂｕｔ　ｄｏ　ｙｏｕ　ａｃｃｅｐｔ？↓
;jpn:◆@DSP_GOODS(0)ですね。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで↓
;jpn:　おひきとりしますが。@KEY()↓
;jpn:◆それでいいですか？↓
@!
MSG_SUB_SHOPMES_DRUG7_15;
◆Ｖｅｒｙ　ｗｅｌｌ　ｔｈｅｎ．

;jpn:◆わかりました。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_16;
◆Ｆｒｏｍ　ｍｙ　ｈｕｍｂｌｅ　ｖａｎｔａｇｅ　ｐｏｉｎｔ，　ｉｔ　ａｐｐｅａｒｓ　ｙｏｕ　ｈａｖｅ　ｎｏｔｈｉｎｇ　ｔｏ　ｓｅｌｌ．

;jpn:◆うるものがないようですね。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_17;
◆Ａ　ｔｈｏｕｓａｎｄ　ｐａｒｄｏｎｓ．　　Ｗｅ　ｄｏ　ｎｏｔ　ｃａｒｒｙ　ｔｈａｔ　ｉｔｅｍ　ｈｅｒｅ．

;jpn:◆すいません。↓
;jpn:　そのしなものは↓
;jpn:　あつかって　ないんですよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_18;
◆Ａｈｈ，　ｙｏｕ　ａｒｅ　ｍｏｓｔ　ｇｒａｃｉｏｕｓ　ａｎｄ　ｋｉｎｄ．

;jpn:◆ありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｖｉｓｉｔｉｎｇ　ｍｙ　ｐｏｏｒ　ｓｈｏｐ．

;jpn:◆まいどありがとうございます。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG7_20;
◆Ｉｆ　ｔｈｅｒｅ　ｉｓ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　Ｉ　ｃａｎ　ｄｏ　ｆｏｒ　ｙｏｕ，
ｐｌｅａｓｅ，　ｄｏ　ｎｏｔ　ｈｅｓｉｔａｔｅ　ｔｏ　ａｓｋ．↓
;jpn:◆ほかに　ごようは？↓
@!
MSG_SUB_SHOPMES_DRUG7_21;
◆Ｓｏ，　ｗｈａｔ　ｍｏｒｅ　ｃａｎ　Ｉ　ｄｏ　ｆｏｒ　ｙｏｕ？↓
;jpn:◆こんどのごようは？↓
@!
MSG_SUB_SHOPMES_DRUG7_22;
◆@DSP_NAME(0)　ｓｉｍｐｌｙ　ｃａｎｎｏｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｇｏｏｄｓ．@KEY()↓
◆Ｐｅｒｈａｐｓ　ａｎｏｔｈｅｒ　ｏｆ　ｙｏｕｒ　ｐａｒｔｙ　ｃｏｕｌｄ　ｂｅａｒ　ｔｈｉｓ　ｌｏａｄ？↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつが　いっぱいですね。@KEY()↓
;jpn:◆ほかのひとが　もちますか？↓
@!
;ブタのハナ売り（ｐｉｇ－ｋａｎｓａｉｂｅｎ）

MSG_SUB_SHOPMES_DRUG8_1;

;◆めずらしいもの↓
;　いろいろありまっせ。@KEY()↓

◆Ｉｆ　ｙｏｕ’ｖｅ　ａｌｒｅａｄｙ　ｇｏｔ　ｗｈａｔ　ｙｏｕ　ｎｅｅｄ，　ｇｒｅａｔ！@KEY()↓
◆Ｂｕｔ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ，　ｗｅｌｌ，　ｔｈａｔ　ｗｏｕｌｄ　ｂｅ　ａ　ｒｅａｌ　ｓｈａｍｅ．@KEY()↓
◆Ｔａｋｅ　ａ　ｇｏｏｄ　ｌｏｏｋ　ａｔ　ｍｙ　ｍｅｎｕ　ａｎｄ　ｄｅｃｉｄｅ．@KEY()↓
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｌｉｓｔｅｄ　ｔｈａｔ　ｙｏｕ　ｍｉｇｈｔ　ｗａｎｔ？↓
;jpn:◆あったらべんり↓
;jpn:　なければ　たいへん！↓
;jpn:　メニューみて　きめなはれ。@KEY()↓
;jpn:◆ごようは　なんでっしゃろ？↓
@!
MSG_SUB_SHOPMES_DRUG8_2;
◆Ｉｆ　ｙｏｕ　ｄｏ　ｄｅｃｉｄｅ　ｔｈａｔ　ｙｏｕ　ｎｅｅｄ　ａｎｙ　ｏｆ　ｍｙ　ｇｏｏｄｉｅｓ，　ｙｏｕ　ｊｕｓｔ　ｈｕｒｒｙ　ｏｎ　ｂａｃｋ　ｎｏｗ，　ｙ’ｈｅａｒ？

;jpn:◆ようができたら↓
;jpn:　また　きなはれ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG8_3;
◆Ｃｏｍｅ　ｂａｃｋ　ａｎｙ　ｔｉｍｅ，　ｉｆ　ｄｏ　ｎｅｅｄ　ａｎｙ　ｏｆ　ｍｙ　ｇｏｏｄｓ．

;jpn:◆ようができたら↓
;jpn:　また　きなはれ。
@KEYNP()
@!
MSG_SUB_SHOPMES_DRUG8_4;
◆Ｗｈａｔ’ｌｌ　ｉｔ　ｂｅ？

;jpn:◆なにが　ええの？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_5;
◆Ｔｈｅ　@DSP_GOODS(0)，　ｙｏｕ　ｓａｙ？

;jpn:◆@DSP_GOODS(0)ですな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_6;
◆Ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？

;jpn:◆だれがもつの？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_7;
◆Ｗｉｌｌ　ｙｏｕ　ｂｅ　ｅｑｕｉｐｐｉｎｇ　ｔｈａｔ　ｈｅｒｅ？↓
;jpn:◆ここで　そうびしはる？↓
@!
MSG_SUB_SHOPMES_DRUG8_8;
◆Ｉ　ｃａｎ　ｂｕｙ　ｙｏｕｒ↓
　　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでかいあげましょか？↓
@!
MSG_SUB_SHOPMES_DRUG8_9;
◆@DSP_NAME(0)　ｗｏｎ’ｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｓｕｒｅ　ｙｏｕ　ｒｅａｌｌｙ　ｎｅｅｄ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　これをそうびでけへんけど@KEY()↓
;jpn:◆それでも　かいますか？↓
@!
MSG_SUB_SHOPMES_DRUG8_10;
◆Ｏｈ？　　Ｄｅｃｉｄｅｄ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ，　ｈｕｈ？

;jpn:◆あら@WI(10)↓
;jpn:　かわへんの？
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_11;
◆Ｈｍｍｍ．．．　Ｈａｔｅ　ｔｏ　ｂｒｅａｋ　ｔｈｉｓ　ｔｏ　ｙｏｕ，　ｂｕｔ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆あら@WI(10)↓
;jpn:　ゼニがたらんようですな。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_12;
◆Ｏｈ．．．　ｕｈ．．．　ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ’ｖｅ　ｇｏｔ　ｔｏｏ　ｍａｎｙ　ｇｏｏｄｓ　ｔｏ　ｃａｒｒｙ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｂｅ　ｗｉｌｌｉｎｇ　ｔｏ　ｓｅｌｌ　ｍｅ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｇｏｏｄｓ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ？↓
;jpn:◆あら@WI(10)↓
;jpn:　にもつがいっぱいですな。@KEY()↓
;jpn:◆いらんにもつを↓
;jpn:　かいとりましょか？↓
@!
MSG_SUB_SHOPMES_DRUG8_13;
◆Ｆａｎｔａｓｔｉｃ！　　Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｎａ　ｓｅｌｌ？

;jpn:◆なにをうるの？
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_14;
◆@DSP_GOODS(0)？↓
　　Ｉ’ｄ　ｓａｙ　ｉｔ’ｓ　ｗｏｒｔｈ　ａｂｏｕｔ．．．↓
　　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｗｈａｄｄｙａ　ｓａｙ，　ｐａｒｔｎｅｒ？↓
;jpn:◆@DSP_GOODS(0)でっか↓
;@XCHG()
;jpn:　それなら@DSP_NUM(0)ドルで↓
;jpn:　おひきとりしまっせ。@KEY()↓
;jpn:◆よろしゅうおまっか？↓
@!
MSG_SUB_SHOPMES_DRUG8_15;
◆ＯＫ，　Ｉ　ｓｅｅ．　　Ｙ’ａｌｌ　ｃｏｍｅ　ｂａｃｋ　ｎｏｗ，　ｈｅａｒ？

;jpn:◆そうでっか↓
;jpn:　また　よろしゅう。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_16;
◆Ｗｈａｔ　ｇｉｖｅｓ？　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ．

;jpn:◆なんや@WI(10)　うるものが↓
;jpn:　おまへんがな。
@KEY()
@!
MSG_SUB_SHOPMES_DRUG8_17;
◆Ｌｏｏｋ，　Ｉ’ｍ　ｒｅａｌｌｙ　ｓｏｒｒｙ，　ｂｕｔ　ｗｅ　ｃａｎ’ｔ　ｂｕｙ　ｔｈａｔ．

;jpn:◆すいません　おきゃくさん↓
;jpn:　かんべんしてください。@KEY()↓
;jpn:◆それは　うちでは↓
;jpn:　ひきとれまへんのや。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_18;
◆Ｔｈａｎｋｓ　ａ　ｍｉｌｌｉｏｎ！

;jpn:◆まいど　おおきに。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_19;
◆Ｔｈａｎｋｓ　ａ　ｂｕｎｃｈ！

;jpn:◆まいど　おおきに。
@KEY()↓
@!
MSG_SUB_SHOPMES_DRUG8_20;
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　Ｉ　ｃａｎ　ｇｅｔ　ｆｏｒ　ｙｏｕ　ｗｈｉｌｅ　ｙｏｕ’ｒｅ　ｈｅｒｅ？↓
;jpn:◆ほかにも　ごようは↓
;jpn:　ありまっか？↓
@!
MSG_SUB_SHOPMES_DRUG8_21;
◆Ｗｈａｔ’ｌｌ　ｉｔ　ｂｅ？↓
;jpn:◆ごようは　なんでっしゃろ？↓
@!
MSG_SUB_SHOPMES_DRUG8_22;
◆Ｓａｋｅｓ　ａｌｉｖｅ！　@DSP_NAME(0)　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｏｔｈｅｒ　ｔｈｉｎｇ．@KEY()↓
◆Ｍａｙｂｅ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｎ　ｃａｒｒｙ　ｉｔ．↓
;jpn:◆あらま↓
;jpn:　@DSP_NAME(0)さん↓
;jpn:　にもつが　いっぱいやね。@KEY()↓
;jpn:◆ほかのひとに↓
;jpn:　もってもらったら？↓
@!
;おもちゃ屋（ｔｏｙ ｓｔｏｒｅ）

MSG_SUB_SHOPMES_TOYSHOP_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆またよろしくね。
@KEYNP()
@!
;武器男（ｗｅａｐｏｎ ｓｅｌｌｅｒ）
MSG_SUB_SHOPMES_WEAPON_1;
◆Ｓｓｓｓｈｈｈ！↓
　　Ｄｏｎ’ｔ　ｒａｉｓｅ　ｙｏｕｒ　ｖｏｉｃｅ　ｗｉｔｈ　ｍｅ！@KEY()↓

;jpn:◆しーっ！@WI(60)↓
;jpn:　おおきなこえをだすな！@KEY()↓
;@CHKFGOTO(FLG_??,_SHOPMES_WEAPON_1_B)
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ？↓
;jpn:◆なんのようだ？↓
@!
_SHOPMES_WEAPON_1_B;
◆．．．ｙｏｕ　ａｇａｉｎ？！↓
　　Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｎｏｗ？↓
;jpn:◆‥‥またあんたか。@WI(20)↓
;jpn:　なんのようだ？↓
@!
MSG_SUB_SHOPMES_WEAPON_2;
◆Ｗｉｌｌ　ｔｈａｔ　ｂｅ　ａｌｌ？↓
　　Ｇｏｏｄ　ｌｕｃｋ，　ｂｕｄｄｙ！

;jpn:◆じゃあな。@WI(20)↓
;jpn:　しっかりやれよ　あいぼう！
@KEYNP()
@!
MSG_SUB_SHOPMES_WEAPON_3;
◆Ｓｏ　ｔｈａｔ’ｓ　ｅｖｅｒｙｔｈｉｎｇ？↓
　　Ｋｅｅｐ　ｏｎ　ｔｈｅ　ｗａｔｃｈ　ｆｏｒ　ｂａｄ　ｇｕｙｓ．

;jpn:◆じゃあな。@WI(20)↓
;jpn:　わるいやつに　きをつけろよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_WEAPON_4;
◆Ｉ’ｖｅ　ｇｏｔ　ｗｈａｔ　ｙｏｕ　ｎｅｅｄ．

;jpn:◆なんでも　そろってるぜ。
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)だな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_6;
◆Ｗｈｏ’ｓ　ｇｏｎｎａ　ｌｕｇ　ｔｈｉｓ　ａｒｏｕｎｄ？

;jpn:◆だれが　はこぶ？
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_7;
◆ＯＫ．　　Ｉ　ｓｕｐｐｏｓｅ　ｙｏｕ’ｒｅ　ｇｏｉｎｇ　ｔｏ　ｗａｎｔ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓
;jpn:◆オーケイ@WI(20)↓
;jpn:　ここで　そうびしてみるかい？↓
@!
MSG_SUB_SHOPMES_WEAPON_8;
◆Ｔｈｅ　@DSP_GOODS(0)．．．．？↓
　　Ｉ’ｄ　ｓａｙ　ａｂｏｕｔ　@XCHG()＄@DSP_NUM(0)．↓
　　Ｔａｋｅ　ｉｔ　ｏｒ　ｌｅａｖｅ　ｉｔ．@KEY()↓
;jpn:◆@DSP_GOODS(0)か‥‥↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで　いいか？↓
@!
MSG_SUB_SHOPMES_WEAPON_9;
◆@DSP_NAME(0)　ｗｏｎ’ｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｉｎｔｅｎｔ　ｏｎ　ｐｕｒｃｈａｓｉｎｇ　ｉｔ　ａｎｙｗａｙ？↓
;jpn:◆@DSP_NAME(0)には　これは↓
;jpn:　そうびできないぜ。@KEY()↓
;jpn:◆それでもいいかい？↓
@!
MSG_SUB_SHOPMES_WEAPON_10;
◆Ｗｅｌｌ，　ｔｈａｔ’ｓ　ｓｈｏｗｉｎｇ　ｇｏｏｄ　ｓｅｎｓｅ．　　Ｙｏｕ　ｓｈｏｕｌｄｎ’ｔ　ｓｔｒａｉｎ　ｙｏｕｒｓｅｌｆ　ｔｏｏ　ｍｕｃｈ．

;jpn:◆そうだな。@WI(20)↓
;jpn:　むりは　きんもつだよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_11;
◆Ｈｏｌｄ　ｉｔ　ｊｕｓｔ　ａ　ｓｅｃｏｎｄ！　　Ｙｏｕ　ｈａｖｅｎ’ｔ　ｇｏｔ　ｅｎｏｕｇｈ　ｍｏｎｅｙ！

;jpn:◆ちょっとまった@WI(20)↓
;jpn:　かねが　たりないぜ！
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_12;
◆Ｙｏｕ　ａｒｅｎ’ｔ　ｇｏｉｎｇ　ｔｏ　ｂｅ　ａｂｌｅ　ｔｏ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｓｔｕｆｆ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｄｒａｇｇｉｎｇ　ａｒｏｕｎｄ　ａｌｌ　ｔｈａｔ　ｊｕｎｋ．．．@KEY()↓
◆Ｉ　ｇｕｅｓｓ　Ｉ　ｃｏｕｌｄ　ｈｅｌｐ　ｙｏｕ　ｏｕｔ　ｂｙ　ｂｕｙｉｎｇ　ｓｏｍｅ　ｔｈｉｎｇｓ　ｔｈａｔ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ．．．@KEY()↓
;jpn:◆おっと↓
;jpn:　それいじょうは　ヤバイぜ。@WI(15)↓
;jpn:　にもつが　いっぱいだ。@KEY()↓
;jpn:◆いらないにもつが　あるなら↓
;jpn:　ひきとってやるぜ。↓
@!
MSG_SUB_SHOPMES_WEAPON_13;
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｐａｗｎ　ｏｆｆ　ｏｎ　ｍｅ？

;jpn:◆ブツは　なんだい？
@KEY()
@!
MSG_SUB_SHOPMES_WEAPON_14;
◆@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　@XCHG()＄@DSP_NUM(0)，　ａｎｄ　ｎｏｔ　ａ　ｐｅｎｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｔａｋｅ　ｉｔ　ｏｒ　ｌｅａｖｅ　ｉｔ．↓
;jpn:◆@DSP_GOODS(0)か。@WI(20)↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで　ひきとろう。@KEY()↓
;jpn:◆それでいいか？↓
@!
MSG_SUB_SHOPMES_WEAPON_15;
◆．．．Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ’ｌｌ　ｆｉｎｄ　ａ　ｂｅｔｔｅｒ　ｐｒｉｃｅ　ａｎｙｗｈｅｒｅ　ｅｌｓｅ．

;jpn:◆‥‥こうかいするぜ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_16;
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｔｒｙｉｎｇ　ｔｏ　ｐｕｌｌ，　ａｎｙｗａｙ？@KEY()↓
◆Ｙｏｕ　ｓａｙ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ，　ｂｕｔ　ｙｏｕ　ｈａｖｅ　ｎｏｔｈｉｎｇ　ｔｏ　ｏｆｆｅｒ？！@KEY()↓
◆Ｙｏｕ’ｖｅ　ｇｏｔ　ｓｏｍｅ　ｎｅｒｖｅ，　ｋｉｄ！

;jpn:◆ブツもなしに↓
;jpn:　カネだけ↓
;jpn:　ほしいっていうのか？@KEY()↓
;jpn:◆たいした　どきょうだな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_17;
◆Ｆｏｒｇｅｔ　ｉｔ！↓
　　Ｉ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｔｈａｔ　ｊｕｎｋ！

;jpn:◆おっと@WI(15)　そんなヤバイ↓
;jpn:　とりひきは　ごめんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_18;
◆Ｅｘｃｅｌｌｅｎｔ．↓
　　Ｇｌａｄ　ｗｅ　ｃｏｕｌｄ　ｗｏｒｋ　ｓｏｍｅｔｈｉｎｇ　ｏｕｔ．

;jpn:◆ありがとよ。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_19;
◆Ｔｈａｎｋ　ｙｏｕ．@WI(20)　　Ｔｈｉｎｇｓ　ｍｕｓｔ　ｂｅ　ｐｒｅｔｔｙ　ｔｏｕｇｈ，　ｅｓｐｅｃｉａｌｌｙ　ｆｏｒ　ａ　ｋｉｄ　ｌｉｋｅ　ｙｏｕ．
;jpn:◆ありがとよ。@WI(20)↓
;jpn:　こどもなのに　たいへんだな。
@KEY()↓
@!
MSG_SUB_SHOPMES_WEAPON_20;
◆Ｓｏ，　ｗｉｌｌ　ｔｈｅｒｅ　ｂｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓
;jpn:◆まだ　ようじはあるか？↓
@!
MSG_SUB_SHOPMES_WEAPON_21;
◆Ｗｈａｔ　ｉｓ　ｉｔ　ｎｏｗ？↓
;jpn:◆なんのようだ？↓
@!
MSG_SUB_SHOPMES_WEAPON_22;
◆@DSP_NAME(0)　　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｉｓ　ａｎｙｏｎｅ　ｅｌｓｅ　ｗｉｌｌｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつがいっぱいだぜ。@KEY()↓
;jpn:◆ほかのやつが　もつか？↓
@!
;土星さん（Ｓａｔｕｒｎ－ｓａｎ）

MSG_SUB_SHOPMES_DOSEI_1;
@FONTBAKA()
;akimiura
◆Ｈｉ　Ｈｉ　Ｈｉ．↓
　　Ｙｏｕ　ｃｏｍｅ↓
　　ｂｕｙｉｎｇ？@KEY()↓
◆Ｙｏｕ　ｃａｎ　ｓｅｌｌ，↓
　　ｔｏｏ．@KEY()↓
◆Ｉ，　Ｍｒ．　Ｓａｔｕｒｎ，　ｂｏｉｎｇ@KEY()↓
◆ｃａｎ　ｄｏ　ａｌｌ　ｆｏｒ　ｙｏｕ．@KEY()↓
◆Ｗｈａｔ　ｄｏ　ｙｏｕ↓
　　ｗａｎｔ　ｚｏｏｍ？↓
;jpn:◆できるます。@WI(10)↓
;jpn:　うったり　かったり↓
;jpn:　どせいさんです。@KEY()↓
;jpn:◆どんな　よう？↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_2;
@FONTBAKA()
◆Ｏｈ，↓
　　ｙｏｕ　ｔｈａｎｋ！

;jpn:◆ありがと。
@KEYNP()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_3;
@FONTBAKA()
◆Ｔｈａｎｋ　ｙｏｕ．↓
　　Ｂｏｉｎｇ！

;jpn:◆ありがと。@WI(10)↓
;jpn:　ぷうー
@KEYNP()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_4;
@FONTBAKA()
;akimiura
◆Ｗｈａｔ　ｙｏｕ↓
　　ｂｕｙｉｎｇ　ｚｏｏｍ？

;jpn:◆なにを　かう？
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_5;
@FONTBAKA()
◆Ｔｈｅ　@DSP_GOODS(0)？

;◆@DSP_GOODS(0)↓
;jpn:　ですね。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_6;
@FONTBAKA()
;akimiura
◆Ｗｈｉｃｈ↓
　　ｙｏｕ　ｃａｒｒｙ↓
　　ｔｈｉｓ　ｂｕｒｄｅｎ？

;jpn:◆だれが　もつ？
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_7;
@FONTBAKA()
◆Ｅｑｕｉｐ↓
　　ｈｅｒｅ？↓
;jpn:◆ここで↓
;jpn:　そうび　する？↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_8;
@FONTBAKA()
;akimiura
◆@DSP_GOODS(0)？@KEY()↓
◆Ｕｈｈ，↓
　　ｔｈａｔ　ｏｎｅ　ｉｓ↓
　　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｗｈａｔ　ｔｈｉｎｋ　ｙｏｕ　ａｂｏｕｔ@KEY()↓
◆ｔｈａｔ　ｐｒｉｃｅ．．．ｚｏｏｍ？↓
;◆@DSP_GOODS(0)↓
;@XCHG()
;jpn:　なら　@DSP_NUM(0)　ドル@KEY()↓	;どせいさん数字
;jpn:◆このきんがくで‥‥↓
;jpn:　いいのかな？↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_9;
@FONTBAKA()
;akimiura
◆@DSP_NAME(0)　ｉｓ　ｎｏｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｅｑｕｉｐ　ｔｈｉｓ．@KEY()↓
◆Ｂｏｉｎｇ！@KEY()↓
◆Ｓｔｉｌｌ　ｗａｎｎａ↓
　　ｂｕｙ？↓
;jpn:◆@DSP_NAME(0)には↓
;jpn:　そうびできない。@KEY()↓
;jpn:◆それでもかう？↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_10;
@FONTBAKA()
;akimiura
◆Ｉｆ　ｙｏｕ　ｎｏｔ↓
　　ｇｏｎｎａ　ｂｕｙ，@KEY()↓
◆ｄｏｎ’ｔ↓
　　ｂｕｙ　ｚｏｏｍ！

;jpn:◆やめたいとき↓
;jpn:　やめるといい。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_11;
@FONTBAKA()
◆Ｕｈｈ，@KEY()↓
◆ａｔ　ａ　ｌｏｏｋｉｎｇ　ｂｏｉｎｇ　ｇｌａｎｃｅ，↓
　　ｎｏ　ｃｈａｎｃｅ．@KEY()↓
◆Ｎｏ↓
　　ｅｎｏｕｇｈ@KEY()↓
◆ｃａｓｈｏｏｏｏｏｏｌａ．↓
Ｚｏｉｃｋｓ！

;jpn:◆ぜんたいてきに↓
;jpn:　おかねが↓
;jpn:　たりない。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_12;松（このあとに「いらない荷物を買い取ろうか？」といれてほしい
@FONTBAKA()
;akimiura
◆Ｗｈａｔ　ａ　ｈａｐｐｙ　ｈａｐｐｙ@KEY↓
◆ｓｕｒｐｒｉｓｅ．↓
　　Ｚｏｏｍ．．．@KEY()↓
◆Ｙｏｕ　ｈａｖｅ↓
　　ｍｕｃｈ↓
　　ｊｕｎｋ．
;jpn:◆はあ　びっくり@WI(10)↓
;jpn:　にもつがいっぱいです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_13;
@FONTBAKA()
◆Ｙｏｕ　ｗａｎｔ　ｔｏ↓
　　ｓｅｌｌ　ｍｅ↓
　　ｔｈｉｎｇｓ@KEY()↓
◆ａｔ　ｍｅ　ｂｏｉｎｇ？

;jpn:◆なにを　うる？
@KEY()
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_14;
@FONTBAKA()
◆@DSP_GOODS(0)？@KEY()↓

;◆@DSP_GOODS(0)↓
;jpn:　ですね。@KEY()↓
;@XCHG()
;akimiura
◆Ｔｈｅ　ｍｏｓｔ↓
　　ｕｓ　ｐａｙ　ｔｈａｔ↓
　　ｉｓ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｔｈａｔ　ｋａｙ－ｏ↓
　　ｏｎ　ｙｏｕ？@KEY()↓
◆Ｄｉｎｇ！　Ｄｉｎｇ！↓

;jpn:◆@DSP_NUM(0)　ドルで↓			;どせいさん数字
;jpn:　ひきとる。@KEY()↓
;jpn:◆それで　いいかな？↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_15;
@FONTBAKA()
◆Ｏｈ　Ｊｏｙ！　Ｚｏｏｏｏｏｍ！

;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_16;
@FONTBAKA()
;akimiura
◆Ａｈ－ｃｈｏｏ！　　Ｈｉ　Ｈｉ　Ｈｉ！@KEY()↓
◆ｔｒｙ　ｏｆ↓
　　ｔｒｉｃｋｉｎｇ　ｂｏｉｎｇ？@KEY()↓
◆’Ｃａｕｓｅ　ｙｏｕ↓
　　ｈａｖｅ　ｎｏ↓
　　ａｎｙｔｈｉｎｇ@KEY()↓
◆　ｓｅｌｌｉｎｇ．　　Ｄｉｎｇ　Ｄｉｎｇ！
;jpn:◆ヘックション！@WI(10)↓
;jpn:　うるもの↓
;jpn:　ないみたいです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_17;
@FONTBAKA()
◆Ｄｅａｒ，　ｄｅａｒ，　ｄｅａｒ．．．Ｂｏｉｎｇ！@KEY()↓
◆Ｎｏ　ｃａｎ↓
　　ｂｕｙ　ｔｈａｔ．
;jpn:◆ごめんなさい。@KEY()↓
;jpn:◆それは　うちでは↓
;jpn:　ひきとれないです。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_18;
@FONTBAKA()
◆Ｏｈ，↓
　　ｙｏｕ　ｔｈａｎｋ．

;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_19;
@FONTBAKA()
◆Ｔｈａｎｋｓ！　　Ｄｉｎｇ　Ｚｏｏｍ！
;jpn:◆ありがと。
@KEY()↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_20;
@FONTBAKA()
;akimiura
◆Ｉｓ　ｔｈｅｒｅ
　　ａｎｙｔｈｉｎｇ
　　Ｚｏｏｍ@KEY()↓
◆ｅｌｓｅ　ｎｅｅｄ？@KEY()
;jpn:◆ほかに　なにか↓
;jpn:　ようありますか？
↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_21;
@FONTBAKA()
◆Ｗｈａｔ　ｎｅｘｔ，　Ｂｏｉｎｇ？

;jpn:◆こんどのようは？
↓
@FONTSTD()
@!
MSG_SUB_SHOPMES_DOSEI_22;
@FONTBAKA()
;akimiura
◆@DSP_NAME(0)　ｈａｓ↓
　　ｋｏｏｋｉｅ　ｍｕｃｈ↓
　　ｊｕｎｋ？@KEY()↓
◆Ｄｏｅｓ　ａｎｙｏｎｅ↓
　　ｗａｎｔ　ｈｅｌｐ↓
　　Ｚｏｏｍ？@KEY()
;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつ　もちすぎ。@KEY()↓
;jpn:◆ほかのひとが↓
;jpn:　もちますか？
↓
@FONTSTD()
@!
;グミ族（Ｇｕｍｉ ｔｒｉｂｅ）

MSG_SUB_SHOPMES_GUMI_1;
;akimiua
◆Ｌｅｔ’ｓ　ｐｌａｙ　ｓｔｏｒｅ．　　Ｍｙ　ｆｒｉｅｎｄ　Ａｙ－ｇｏ　ｌｏｖｅｓ　ｔｈｉｓ　ｇａｍｅ．　　Ｓｏ．．．@KEY()↓
◆Ｈｉ！　　Ｍａｙ　Ｉ　ｈｅｌｐ　ｙｏｕ？
;jpn:◆ともだちの　エーゴに↓
;jpn:　たのまれて↓
;jpn:　おみせやさんゴッコをしてるだよ。@KEY()↓
;jpn:◆いらっしゃいませ。↓
;jpn:　ごようは？
↓
@!
MSG_SUB_SHOPMES_GUMI_2;
;◆あんたから　もらった↓
;　えはがき　みてぇなもの↓
;　（おさつのことらしい）は@KEY()↓
;◆エーゴに　わたしとくだよ。@KEY()↓

◆Ｂｙｅ　ｂｙｅ！↓
　　Ｌｅｔ’ｓ　ｐｌａｙ　ａｇａｉｎ　ｓｏｍｅ　ｔｉｍｅ！

;jpn:◆じゃーな。@WI(20)↓
;jpn:　また　あそぼうぜ。
@KEYNP()
@!
MSG_SUB_SHOPMES_GUMI_3;
◆Ｂｙｅ　ｂｙｅ！↓
　　Ｌｅｔ’ｓ　ｐｌａｙ　ａｇａｉｎ　ｓｏｍｅ　ｔｉｍｅ！

;jpn:◆じゃーな。@WI(10)↓
;jpn:　またあそぼうぜ。
@KEYNP()
@!
MSG_SUB_SHOPMES_GUMI_4;
◆Ａｒｅ　ｙｏｕ　ｌｏｏｋｉｎｇ　ｆｏｒ　ａｎｙｔｈｉｎｇ　ｉｎ　ｐａｒｔｉｃｕｌａｒ？

;jpn:◆なにを　かうだね？
@KEY()
@!
MSG_SUB_SHOPMES_GUMI_5;
◆@DSP_GOODS(0)？

;jpn:◆@DSP_GOODS(0)だな。
@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？

;jpn:◆だれが　もちますか？
@KEY()
@!
MSG_SUB_SHOPMES_GUMI_7
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｔｒｙ　ｅｑｕｉｐｐｉｎｇ　ｉｔ　ｈｅｒｅ？

;jpn:◆ここでそうびしてみっか？
↓
@!
MSG_SUB_SHOPMES_GUMI_8;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｂｕｙ
　　ｙｏｕｒ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？↓

;jpn:◆@DSP_GOODS(0)を↓			;7/26に修正
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでかったろうか？
↓
@!
MSG_SUB_SHOPMES_GUMI_9;
◆Ｄｉｄ　ｙｏｕ　ｒｅａｌｉｚｅ　ｔｈａｔ　@DSP_NAME(0)　ｃａｎ’ｔ　ｅｑｕｉｐ　ｔｈｉｓ？@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｐｕｒｃｈａｓｅ　ｉｔ？

;jpn:◆@DSP_NAME(0)には↓
;jpn:　そうびできないものだが@KEY()↓
;jpn:◆それでもかうか？
↓
@!
MSG_SUB_SHOPMES_GUMI_10;
◆Ｗｅｌｌ，　ｔｈｅ　ｃｕｓｔｏｍｅｒ　ｉｓ　ａｌｗａｙｓ　ｒｉｇｈｔ．

;jpn:◆そうかい。
@KEY()↓
@!
;※
MSG_SUB_SHOPMES_GUMI_11;＠
◆（Ｓｉｒ／Ｍａ’ａｍ），　ｉｔ　ａｐｐｅａｒｓ　ｙｏｕ　ｄｏ　ｎｏｔ　ｈａｖｅ　ｔｈｅ　ｍｏｎｅｙ　ｎｅｃｅｓｓａｒｙ　ｆｏｒ　ｔｈｉｓ　ｔｒａｎｓａｃｔｉｏｎ．@KEY()↓
;jpn:◆おかね　たりないだよ。@KEY()↓
;◆えはがきみてぇなの↓
;　（おさつのことらしい）が↓
;　たりねぇと@KEY()↓
;◆エーゴに　おこられちまうだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_12;松
◆Ｉ　ｒｅａｌｌｙ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ　ｐｕｒｃｈａｓｅｓ．@KEY()↓
◆Ｙｏｕ　ｃａｎ　ｃｏｍｅ　ａｇａｉｎ　ａｆｔｅｒ　ｙｏｕ　ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，@KEY()↓
◆ｏｒ　ｙｏｕ　ｃａｎ　ｓｉｍｐｌｙ　ｄｉｓｃａｒｄ　ａｎ　ｉｔｅｍ　ｔｏ　ｌｉｇｈｔｅｎ　ｙｏｕｒ　ｌｏａｄ．@KEY()↓
◆Ｏｒ，　ｙｏｕ　ｍｉｇｈｔ　ｗａｎｔ　ｔｏ　ｓｅｌｌ　ｔｈｅ　ｔｈｉｎｇｓ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ　ｈｅｒｅ！@KEY()↓

;jpn:◆にもつ　もちすぎだーよ。↓
;jpn:　うるか　すてるかして↓
;jpn:　また　きてな。@KEY()↓
;jpn:◆それとも　ここで↓
;jpn:　いらない　にもつを@KEY()↓
;jpn:◆うっちまうかね？↓
;◆にもつが　いっぺぇで↓
;　わたせねぇだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_13;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｅｌｌ？@KEY()

;jpn:◆なにを↓
;jpn:　うってくれるんだい？@KEY()
@!
MSG_SUB_SHOPMES_GUMI_14;
◆@DSP_GOODS(0)？↓
　　Ｉ’ｍ　ａｕｔｈｏｒｉｚｅｄ　ｔｏ　ｐａｙ　ｕｐ　ｔｏ　@XCHG()＄@DSP_NUM(0)　ｆｏｒ　ｔｈａｔ．@KEY()↓
◆Ｈｏｗ　ａｂｏｕｔ　ｉｔ？↓

;jpn:◆@DSP_GOODS(0)だな。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでどうだね？↓
@!
MSG_SUB_SHOPMES_GUMI_15;
◆Ｔｈａｔ’ｓ　ｆｉｎｅ．　　Ｉｔ’ｓ　ｔｈｅ　ｃｕｓｔｏｍｅｒ’ｓ　ｐｒｅｒｏｇａｔｉｖｅ　ｔｏ　ｃｈａｎｇｅ　ｈｉｓ　ｏｒ　ｈｅｒ　ｍｉｎｄ．
@KEY()↓
;jpn:◆そうかい。やめるかい。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_16;
◆Ｔｈｏｕｇｈ　Ｉ　ｒｅａｌｌｙ　ｗｏｕｌｄ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ｓｏｍｅｔｈｉｎｇ　ｆｒｏｍ　ｙｏｕ，　ｙｏｕ　ｈａｖｅ　ｎｏｔｈｉｎｇ　ｔｏ　ｏｆｆｅｒ．@KEY()↓

;jpn:◆うるもの↓
;jpn:　もっとらんようだね。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_17;
◆Ｓｏｒｒｙ，　Ｉ’ｍ　ｎｏｔ　ａｕｔｈｏｒｉｚｅｄ　ｔｏ　ｂｕｙ　ｔｈａｔ．@KEY()↓

;jpn:◆わりいね。↓
;jpn:　それは　ひきとれないんだーよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_18;＠三浦
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ，　ｓｉｒ．@KEY()↓

;jpn:◆ありがとな。@KEY()↓
;◆あんたらからもらった↓
;　えはがきみたいなもの↓
;　（おさつのことらしい）は@KEY()↓
;◆エーゴにわたしとくだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_19;
◆Ｉ’ｌｌ　ｇｉｖｅ　Ａｙ－ｇｏ　ｔｈｅｓｅ　ｃｏｌｏｒｆｕｌ　ｐａｐｅｒｓ　ｙｏｕ　ｇａｖｅ　ｍｅ．@KEY()↓

;jpn:◆あんたらからもらった↓
;jpn:　えはがきみたいなもの↓
;jpn:　（おさつのことらしい）は@KEY()↓
;jpn:◆エーゴにわたしとくだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GUMI_20;
◆Ｗｉｌｌ　ｔｈｅｒｅ　ｂｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｔｏｄａｙ？↓

;jpn:◆ほかにも↓
;jpn:　なんかようはあるかい？↓
@!
MSG_SUB_SHOPMES_GUMI_21;
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｄｏ　ｎｏｗ？↓

;jpn:◆どうするだね？↓
@!
MSG_SUB_SHOPMES_GUMI_22;
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　@DSP_NAME(0)　ｉｓ　ｏｖｅｒｌｏａｄｅｄ　ｗｉｔｈ　ｉｔｅｍｓ．@KEY()↓
◆Ｙｏｕ　ｗａｎｔ　ｔｏ　ｈａｖｅ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｆｒｉｅｎｄｓ　ｃａｒｒｙ　ｉｔ？↓
;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつもちすぎだーよ。@KEY()↓
;jpn:◆ほかのともだちが↓
;jpn:　もつようにするかね？↓
@!
