;
;================================　医者　======================================
;

;オネット
MSG_DOCTOR_ONET;
@SET_LOOPREG(20)
@GOSUB(_SUB_DOCTOR_1)
@!
;ツーソン
MSG_DOCTOR_TWSN;
@SET_LOOPREG(30)
@GOSUB(_SUB_DOCTOR_1)
@!
;ＨＨ村
MSG_HAPPY_HOSPITAL_DOCTOR;
@SET_LOOPREG(35)
@CHKFGOTO(FLG_WIN_CARPAINTER,_HH_DOCTOR_B)
◆Ｂｌｕｅ．．．　ｂｌｕｅ．@KEY()↓

;jpn:◆ブルーブルー。@KEY()↓
_HH_DOCTOR_B;
@GOSUB(_SUB_DOCTOR_1)
@!
;スリーク
MSG_DOCTOR_THRK;
@SET_LOOPREG(40)
@GOSUB(_SUB_DOCTOR_1)
@!
;ドコドコ砂漠
MSG_DSRT_HOSPITAL_DOCTOR;
@SET_LOOPREG(45)
◆Ｉ’ｍ　ａ　ｒｏａｍｉｎｇ　ｄｏｃｔｏｒ．↓
　　Ｌｅｔ　ｍｅ　ｋｎｏｗ　ｉｆ　ｙｏｕ’ｒｅ　ｎｏｔ　ｆｅｅｌｉｎｇ　ｗｅｌｌ．@KEY()↓

;jpn:◆わたしは　さすらいのドクター。↓
;jpn:　わるいところがあったら↓
;jpn:　えんりょなく　いってごらん。@KEY()↓
@GOSUB(_SUB_DOCTOR_1)
@!

;フォーサイド
MSG_DOCTOR_FOUR;
@SET_LOOPREG(60)
@GOSUB(_SUB_DOCTOR_1)
@!
;サマーズ
MSG_DOCTOR_SUMS;
@SET_LOOPREG(70)
@GOSUB(_SUB_DOCTOR_1)
@!
;スカラビ
MSG_DOCTOR_SKRB;
@SET_LOOPREG(80)
@GOSUB(_SUB_DOCTOR_1)
@!
;ムーンサイド
MSG_DOCTOR_MOON;
@SET_LOOPREG(60)
@SETF(FLG_SHOPTEMP_4)
@GOSUB(_SUB_DOCTOR_1)
@CLRF(FLG_SHOPTEMP_4)
@!
;
;================================　看護婦　==================================
;

;オネット
MSG_NURSE_ONET;
@SET_LOOPREG(50)
@GOSUB(_SUB_NURSE)
@!
;ツーソン
MSG_NURSE_TWSN;
@SET_LOOPREG(100)	
@GOSUB(_SUB_NURSE)
@!
;ＨＨ村
MSG_HAPPY_HOSPITAL_USHER;
@SETF(FLG_TEMP_9)
@SET_LOOPREG(110)	
@CHKFGOTO(FLG_WIN_CARPAINTER,_HH_NURSE_B)
◆Ｂｌｕｅ．．．　ｂｌｕｅ．．．@KEY()↓

;jpn:◆ブルーブルー。@KEY()↓
_HH_NURSE_B;
@GOSUB(_SUB_NURSE)
@!
;スリーク
MSG_NURSE_THRK;
@SET_LOOPREG(120)	
@GOSUB(_SUB_NURSE)
@!
;ドコドコ砂漠
MSG_DSRT_HOSPITAL_NURSE;
@SET_LOOPREG(135)	
@GOSUB(_SUB_NURSE)
@!
;フォーサイド
MSG_NURSE_FOUR;
@SET_LOOPREG(150)	
@GOSUB(_SUB_NURSE)
@!
;サマーズ
MSG_NURSE_SUMS;
@SET_LOOPREG(180)	
@GOSUB(_SUB_NURSE)
@!
;スカラビ
MSG_NURSE_SKRB;
@SETF(FLG_TEMP_9)
@SET_LOOPREG(200)	
@GOSUB(_SUB_NURSE)
@!
;ムーンサイド
MSG_NURSE_MOON;
@SETF(FLG_TEMP_9)
@SETF(FLG_SHOPTEMP_4)
@SET_LOOPREG(150)	
@GOSUB(_SUB_NURSE)
@CLRF(FLG_SHOPTEMP_4)
@!

;================================　特殊回復　================================

;
;Ｇフルデッドのキノコ少女
;

MSG_SUB_GRFD_KINOKOGIRL;
◆　Ｈｕｍｍ　ｄｅｅ　ｄｕｍ　ｄｕｍ　ｄｕｍ．↓
　　Ｉ’ｍ　ｈｕｎｔｉｎｇ　ｆｏｒ　ｍｕｓｈｒｏｏｍｓ！@KEY()↓
 
;jpn:◆ランラン音@WI(30)↓
;jpn:　わたし　キノコがりにきてるの。@KEY()↓
@GOSUB(_SUB_KINOKO_CHK)
@FALSE_GOTO(_KINOKOGIRL_KENKO)
◆Ｈｅｙ！　　Ｗｏｕｌｄ　ｙｏｕ　ｂｅ　ｗｉｌｌｉｎｇ　ｔｏ　ｓｅｌｌ　ｔｈａｔ　ｍｕｓｈｒｏｏｍ　ｏｎ　ｙｏｕｒ　ｈｅａｄ　ｆｏｒ　＄５０？@KEY()↓

;jpn:◆あなたの　あたまにのってるキノコ↓
;jpn:　５０ドルで　ゆずって？@WI(30)↓
@GOSUB(MSG_SUB_YESNO_MONEY_PANEL)
@SELGOTO(_KINOKOGIRL_YES,_KINOKOGIRL_NO)
_KINOKOGIRL_NO;
◆Ｏｈｈｈ．．．↓
　　Ｉｔ’ｓ　ｙｏｕｒ　ｓｐｅｃｉａｌ　ｍｕｓｈｒｏｏｍ．

;jpn:◆そう‥‥。@WI(30)↓
;jpn:　だいじにしてるのね。
@KEYNP()
@!
_KINOKOGIRL_YES;
@GOSUB(_SUB_HEAL_KINOKO)
←
◆Ｔｈａｎｋ　ｙｏｕ．↓
　　Ｓｕｃｈ　ａ　ｇｒｅａｔ　ｍｕｓｈｒｏｏｍ．↓
　　Ｉ’ｍ　ｓｏ　ｈａｐｐｙ　Ｉ　ｇｏｔ　ｉｔ．

;jpn:◆ありがとう。@WI(30)↓
;jpn:　こんなりっぱなキノコ‥‥↓
;jpn:　ほんとに　うれしいわ。
@KEYNP()
@!
_KINOKOGIRL_KENKO;
◆Ｉ’ｍ　ｇｏｉｎｇ　ｔｏ　ｃｏｌｌｅｃｔ　ａ　ｔｏｎ　ｏｆ　ｍｕｓｈｒｏｏｍｓ！

;jpn:◆いっぱいキノコを　あつめるわ！
@KEYNP()
@!

;
;土星医者
MSG_DOCTOR_DOSEI;
←
@FONTBAKA()
@CHKFGOTO(FLG_TEMP_1,_DOCTOR_DOSEI_AFTER)
◆Ｉ’ｍ↓
　　Ｄｒ．　Ｓａｔｕｒｎ．　　Ｚｏｏｍ！@KEY()↓
◆ａｎｄ　Ｉ　ｃａｎ↓
　　ｒｅｐａｉｒ↓
　　ｙｏｕｒ　ｂｏｄｙ．@KEY()↓
◆Ｂｏｉｎｇ！@KEY()↓
◆Ｄｏ　ｙｏｕ↓
　　ｗａｎｔ　ｍｅ@KEY()↓
◆ｔｏ　ｏｐｅｒａｔｅ↓
　　ｏｎ　ｙｏｕ？↓
　　Ｄｉｎｇ？@KEY()↓

;jpn:◆からだをなおす。@KEY()↓
;jpn:◆どせいさんです。@KEY()↓
;jpn:◆からだ↓
;jpn:　なおされますか？↓
@FONTSTD()
;@GOSUB(MSG_SUB_YESNO)
<Ｙｅｓ>
<Ｎｏ>
@DSP_ITEM(2)
@SELGOTO(_DOCTOR_DOSEI_YES,_DOCTOR_DOSEI_NO)
_DOCTOR_DOSEI_NO;
@FONTBAKA()
◆Ａｒｅ　ｙｏｕ　ｋａｙ－ｏ？@KEY()↓
◆Ｉｆ　ｙｏｕ↓
　　ａｌｌ　ｒｉｇｈｔ，↓
　　ｔｈａｔ’ｓ　ｇｒｅａｔ．@KEY()↓
◆ｚｏｏｍｅｒ！
 
;jpn:◆だいじょぶか。↓
;jpn:　だいじょぶならいい。
@KEYNP()
@FONTSTD()
@!

_DOCTOR_DOSEI_YES;
@GOSUB(_SUB_ZENKAI)
@FONTBAKA()
◆Ｙｏｕ　ａａａａａａａｌｌ↓
　　ｆｉｘｅｄ　ｕｐ．@KEY()↓
◆Ｇｏｏｄｙ！　　Ｂｏｉｎｇ！
 
;jpn:◆なおった。なおった。@KEY()↓
;jpn:◆よかったー。
@KEYNP()
@FONTSTD()
@SETF(FLG_TEMP_1)
@!
;◆ほかのひとも
;◆なおされますか？
;（はい　いいえ）

_DOCTOR_DOSEI_AFTER;
◆Ｈｅａｌｔｈｙ，↓
　　ｈｅａｌｔｈｙ．

;jpn:◆げんき　げんき。
@KEYNP()
@FONTSTD()
@!

;
;回復ベンチ
;
MSG_BENCH_LIFEUP;
◆”Ｇｏｏｄｎｉｇｈｔ　Ｂｅｎｃｈ”@KEY()↓
◆Ｙｏｕｒ　ｆａｔｉｇｕｅ　ｗｉｌｌ　ｌｅａｖｅ　ｙｏｕ，　ａｎｄ　ｙｏｕｒ　ｅｎｅｒｇｙ　ａｎｄ　ｐｏｗｅｒ　ｗｉｌｌ　ｒｅｔｕｒｎ．
 
;jpn:◆「おやすみベンチ」↓
;jpn:　つかれが　すっかりとれ@KEY()↓
;jpn:◆きりょく　たいりょくが↓
;jpn:　かいふくします。
@KEYNP()
@GOSUB(MSG_GLOBAL_MYHOME)
;@MOVE_GOM_CHAR( GOM_HIT_CHR,ANIM_INTO_NIGHT,OBJFX_SHOW_NONE )
@!
;
;回復グミ
;

MSG_GUMI_HEAL;
◆Ｈｉ！　　Ｈｏｗ　ａｒｅ　ｙｏｕ　ｔｏｄａｙ？↓
　　Ｏｈ，　ｙｏｕ’ｒｅ　ｎｏｔ　ｆｅｅｌｉｎｇ　ｗｅｌｌ？↓
　　Ｂｅ　ｈｅａｌｔｈｙ！

;jpn:◆やあ　げんきか↓
;jpn:　そうでもないか。@WI(20)↓
;jpn:　げんきになれ。
@KEYNP()
@!

;地底大陸の岩 

MSG_DKFD_HEALSTONE;
◆（Ｔｈｉｓ　ｉｓ　ａ　＄ｈｅａｌｓｔｏｎｅ．）

;jpn:◆（＄かいふくいわです。）
@KEYNP()
@GOSUB(MSG_SPACE_KAIHUKU)
@!


;================================　ホテル　==================================


;オネット
MSG_HOTEL_ONET;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_ONET_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(35)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｈｏｔｅｌ　Ｏｎｅｔｔ．@KEY()↓

;jpn:◆ホテルオネットに　ようこそ。@KEY()↓
@GOSUB(_SUB_HOTEL_SELECT)
@SELGOTO(_ONET_HOTEL_YES,_ONET_HOTEL_NO)
_ONET_HOTEL_NO;
@GOSUB(_SUB_HOTEL_NO)
@!
_ONET_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_ONET_HOTEL_NOMONEY)
@GOSUB(_SUB_HOTEL_YES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_ONET_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)		;挿入してください。
@!
_ONET_HOTEL_NOMONEY;
@GOSUB(_SUB_HOTEL_NOMONEY)
@!
_ONET_HOTEL_MORNING;
@GOSUB(_SUB_HOTEL_MORNING)
@!
;ツーソン
MSG_HOTEL_TWSN;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_TWSN_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(50)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｗｅｌｃｏｍｅ　ｔｏ　Ｈｏｔｅｌ　Ｔｗｏｓｏｎ．@KEY()↓

;jpn:◆ツーソンホテルに　ようこそ。@KEY()↓
@GOSUB(_SUB_HOTEL_SELECT)
@SELGOTO(_TWSN_HOTEL_YES,_TWSN_HOTEL_NO)
_TWSN_HOTEL_NO;
@GOSUB(_SUB_HOTEL_NO)
@!
_TWSN_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_TWSN_HOTEL_NOMONEY)
@GOSUB(_SUB_HOTEL_YES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_TWSN_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_TWSN_HOTEL_NOMONEY;
@GOSUB(_SUB_HOTEL_NOMONEY)
@!
_TWSN_HOTEL_MORNING;
@GOSUB(_SUB_HOTEL_MORNING)
@!
;ＨＨ村
MSG_HOTEL_HAPPY;
@MUL_ACTIVE_PLAYER(50)
@XCHG()
@CHKFGOTO(FLG_WIN_CARPAINTER,_HOTEL_HAPPY_LATER)
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_HOTEL_HAPPY_MORNING)
◆Ｗｅ’ｒｅ　ａｌｌ　ｌｉｋｅ　ｏｎｅ　ｂｉｇ，　ｈａｐｐｙ　ｆａｍｉｌｙ　ｈｅｒｅ　ｉｎ　Ｈａｐｐｙ　Ｈａｐｐｙ　Ｖｉｌｌａｇｅ！@KEY()↓
◆Ｂａｓｉｃａｌｌｙ，　ｏｕｒ　ｐｏｌｉｃｙ　ｉｓ　ｔｏ　ｏｎｌｙ　ａｌｌｏｗ　ｆａｍｉｌｙ　ｍｅｍｂｅｒｓ　ｔｏ　ｓｔａｙ　ｈｅｒｅ　ｉｎ　ｔｈｅ　ｖｉｌｌａｇｅ．@KEY()↓
◆Ｈｏｗｅｖｅｒ，　ｉｆ　ｙｏｕ　ａｒｅ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ｌｅａｒｎｉｎｇ　ａｂｏｕｔ　Ｈａｐｐｙ　Ｈａｐｐｙｉｓｍ，@KEY()↓
◆ｗｅ　ｍａｙ　ｍａｋｅ　ａｎ　ｅｘｃｅｐｔｉｏｎ　ａｎｄ　ｌｅｔ　ｙｏｕ　ｓｔａｙ　ｆｏｒ　＄@DSP_NUM(0)．↓ 
;jpn:◆ハッピーハッピーむらは↓
;jpn:　みんな　ひとつの↓
;jpn:　かぞくみたいなものなんだ。@KEY()↓
;jpn:◆かぞくいがいは↓
;jpn:　とめたくないんだが‥‥@KEY()↓
;jpn:◆これから　じょじょに↓
;jpn:　ハッピーハッピーきょうについて↓
;jpn:　まなんでいくと　いうなら‥‥@KEY()↓
;jpn:◆@DSP_NUM(0)ドルで　とくべつに↓
;jpn:　とめてあげよう。↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_HOTEL_HAPPY_YES,_HOTEL_HAPPY_NO)
_HOTEL_HAPPY_NO;
◆Ｎｅｖｅｒ　ｈａｖｅ　Ｉ　ｈｅａｒｄ　ｓｕｃｈ　ｄｉｓｒｅｓｐｅｃｔ！↓
　　Ｇｅｔ　ｏｕｔ　ａｎｄ　ｓｔａｙ　ｏｕｔ！
 
;jpn:◆ふしんじんものめ！↓
;jpn:　もうくるな！
@KEYNP()
@!
_HOTEL_HAPPY_YES;
;体力回復（暗転ワープあり、ＢＧＭあり、夜鍋あり、セリフ替えあり）
@Q_MONEY(0)
@TRUE_GOTO(_HOTEL_HAPPY_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｖｅｒｙ　ｗｅｌｌ．．．　ｂｅ　ｓｕｒｅ　ｔｏ　ｄｏ　ｙｏｕｒ　”ｂｌｕｅ．．．　ｂｌｕｅ．．．”↓
　　ｃｈａｎｔ　ｂｅｆｏｒｅ　ｂｅｄ　ｔｉｍｅ．

;jpn:◆じゃ　ねるまえに↓
;jpn:　ブルーブルーを　おいのりしてね。
@KEYNP()
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_HAPPY_BED)
@!

_HOTEL_HAPPY_NOMONEY;
◆Ｎｏ　ｆａｉｔｈ．．．↓
　　Ｎｏ　ｍｏｎｅｙ．．．↓
　　Ｙｏｕ　ａｒｅ　ａ　ｈｏｐｅｌｅｓｓ　ｃａｓｅ．

;jpn:◆しんこうは　ない‥‥↓
;jpn:　かねは　ない‥‥@WI(15)か。↓
;jpn:　すくわれない　やつだ。
@KEYNP()
@!

_HOTEL_HAPPY_MORNING;
◆Ａｒｅ　ｙｏｕ　ｐｒｅｐａｒｅｄ　ｔｏ　ｓｈｏｗ　ｔｈｅ　ｐｒｏｐｅｒ　ｒｅｓｐｅｃｔ　ｔｏ　Ｍｒ．　Ｃａｒｐａｉｎｔｅｒ　ｎｏｗ？@KEY()↓
◆Ｂｌｕｅ．．．　ｂｌｕｅ．．．

;jpn:◆すこしは↓
;jpn:　カーペインターさんを‥‥@KEY()↓
;jpn:◆そんけいできるように↓
;jpn:　なったかな？　ブルーブルー。
@KEYNP()
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!

_HOTEL_HAPPY_LATER;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_HOTEL_HAPPY_AFTER_MORNING)
@GET_ORDER_PLAYER(1)
@XCHG()
◆Ｇｒｅｅｔｉｎｇｓ，　@DSP_NAME(0)．↓
　　Ｐｌｅａｓｅ　ｆｏｒｇｉｖｅ　ｍｙ　ｌｅｃｔｕｒｅ　ｅａｒｌｉｅｒ．@KEY()↓
◆Ｙｏｕ　ａｒｅ　ｎｏｗ　ｗｅｌｃｏｍｅ　ｔｏ　ｓｔａｙ　ｆｒｅｅ　ｏｆ　ｃｈａｒｇｅ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｔａｙ？↓
 
;jpn:◆やあ　@DSP_NAME(0)くん↓
;jpn:　いつぞやは　せっきょうして↓
;jpn:　すまなかったね。@KEY()↓
;jpn:◆これからは　むりょうで↓
;jpn:　しゅくはくしても　いいよ。@KEY()↓
;jpn:◆とまっていくかね？↓
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_HOTEL_HAPPY_AFTER_YES,_HOTEL_HAPPY_AFTER_NO)
_HOTEL_HAPPY_AFTER_NO;
◆Ｖｅｒｙ　ｗｅｌｌ．　　Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ，　ａｎｙ　ｔｉｍｅ．

;jpn:◆そうかい　また　いつでもおいで。
@KEYNP()
@!
_HOTEL_HAPPY_AFTER_YES;
◆Ｅｘｃｅｌｌｅｎｔ．　　Ｐｌｅａｓｅ　ｍａｋｅ　ｙｏｕｒｓｅｌｆ　ｃｏｍｆｏｒｔａｂｌｅ，　ｏｎ　ｙｏｕｒ　ｂｌｕｅ　ｓｈｅｅｔｓ．．．@KEY()↓
◆Ｎｏ，　ｎｏ，　Ｉ’ｍ　ｊｕｓｔ　ｋｉｄｄｉｎｇ！　　Ｈａ　ｈａ　ｈａｈ！

;jpn:◆じゃ　ごゆっくり。↓
;jpn:　シーツはブルー‥‥@WI(30)じゃないよ。↓
;jpn:　ハハハハ。↓
@KEYNP()
;体力回復（暗転ワープあり、ＢＧＭ２、夜鍋あり、セリフ替えなし）
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_HAPPY_BED)
@!
_HOTEL_HAPPY_AFTER_MORNING;
◆Ｇｏｏｄ　ｍｏｒｎｉｎｇ．↓
　　Ｔａｋｅ　ｃａｒｅ　ａｎｄ　ｇｏｏｄ　ｌｕｃｋ．

;jpn:◆グッドモーニング。↓
;jpn:　げんきでいっといで。
@KEYNP()
@!

;スリーク
MSG_HOTEL_THRK;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_THRK_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(60)
@XCHG()
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　Ｔｈｒｅｅｄ　Ｓｕｎｓｅｔ　Ｈｏｔｅｌ．@KEY()↓

;jpn:◆スリークサンセットホテルに↓
;jpn:　ようこそ。@KEY()↓
@GOSUB(_SUB_HOTEL_SELECT)
@SELGOTO(_THRK_HOTEL_YES,_THRK_HOTEL_NO)
_THRK_HOTEL_NO;
@GOSUB(_SUB_HOTEL_NO)
@!
_THRK_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_THRK_HOTEL_NOMONEY)
@GOSUB(_SUB_HOTEL_YES)
@CHKFGOTO(FLG_PUT_ZOMBI_HOIHOI,_THRK_HOTEL_ZOMBI)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_THRK_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_THRK_HOTEL_NOMONEY;
@GOSUB(_SUB_HOTEL_NOMONEY)
@KEYNP()
@!
_THRK_HOTEL_MORNING;
@GOSUB(_SUB_HOTEL_MORNING)
@!

_THRK_HOTEL_ZOMBI;
;ゾンビホイホイをセットした
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@GOTO(MSG_EVT_55_HOIHOI)
@!
;ドコドコ砂漠
MSG_HOTEL_DSRT;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_HOTEL_DSRT_MORNING)
@MUL_ACTIVE_PLAYER(70)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｗｅ　ａｒｅ　ａｌｓｏ　ｒｕｎｎｉｎｇ　ａｎ　ｉｎｎ，　ｍｉｓｔｅｒ．@KEY()↓
◆Ｉｔ’ｓ　＄@DSP_NUM(0)　ａ　ｎｉｇｈｔ　ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｔａｙ　ｈｅｒｅ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｔａｙ？↓
 
;jpn:◆うちは　やどやも↓
;jpn:　やってるんですけどねぇ↓
;jpn:　おきゃくさん。@KEY()↓
;jpn:◆とまっていくなら↓
;jpn:　ひとばん@DSP_NUM(0)ドルです。@KEY()↓
;jpn:◆とまりますか？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_DSRT_HOTEL_YES,_DSRT_HOTEL_NO)
_DSRT_HOTEL_NO;
◆Ｔｈａｔ’ｓ　ｐｒｏｂａｂｌｙ　ｆｏｒ　ｔｈｅ　ｂｅｓｔ．@KEY()↓
◆Ｙｏｕ　ｓｅｅ．．．　ｏｕｒ　ｂｅｄｓ　ａｒｅ　ｒｅａｌｌｙ　ｏｌｄ　ａｎｄ　ｄｕｓｔｙ．

;jpn:◆そうですね。↓
;jpn:　それが　いいでしょう。↓
;jpn:　‥‥ベッドもボロだし。
@KEYNP()
@!
_DSRT_HOTEL_YES;
;体力回復（暗転ワープあり、ＢＧＭ２、夜鍋あり、セリフ替えなし）
@Q_MONEY(0)
@TRUE_GOTO(_DSRT_HOTEL_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｗｅｌｌ，　ｈａｖｅ　ａ　ｇｏｏｄ　ｒｅｓｔ．　　Ｙｏｕ’ｌｌ　ｗａｋｅ　ｕｐ　ｒｅｆｒｅｓｈｅｄ！

;jpn:◆じゃあ　ゆっくりやすんで↓
;jpn:　つかれを　いやしてください。
@KEYNP()
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_YADOYA_DSRT)
@!
_DSRT_HOTEL_NOMONEY;
◆Ｙｏｕ．．．．ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆おかね‥‥もってないんですね。
@KEYNP()
@!
_HOTEL_DSRT_MORNING;＠ｗｅｔ　ｗａｓｈ　ｃｌｏｔｈ三浦
;◆そとは　あついですから
;　きをつけて。
◆Ｗｈｅｎ　ｙｏｕ　ｔｒａｖｅｌ　ｔｈｏｕｇｈ　ｔｈｅ　ｄｅｓｅｒｔ，　ｙｏｕ　ｍａｙ　ｂｅ　ｈｉｔ　ｂｙ　ｓｕｎｓｔｒｏｋｅ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｓｅｅ　ｆｌａｓｈｉｎｇ　ｌｉｇｈｔｓ　ｂｅｆｏｒｅ　ｙｏｕｒ　ｅｙｅｓ，　ｙｏｕ　ｍａｙ　ｈａｖｅ　ｓｕｎｓｔｒｏｋｅ！@KEY()↓
◆Ｂｕｔ　ｄｏｎ’ｔ　ｗｏｒｒｙ　ｔｏｏ　ｍｕｃｈ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｈａｖｅ　ａ　Ｗｅｔ　Ｔｏｗｅｌ，　ｙｏｕ’ｌｌ　ｂｅ　ａｌｌ　ｒｉｇｈｔ．
 ;jpn:◆さばくを　あるいてると↓
;jpn:　にっしゃびょうに↓
;jpn:　かかることが　あるですよ。@KEY()↓
;jpn:◆めのまえが　@WI(20)ピカッ　@WI(20)ピカッ↓
;jpn:　@WI(30)‥‥なんて↓
;jpn:　ひかるようにかんじたら@KEY()↓
;jpn:◆そうですね　@WI(30)それ　おそらく↓
;jpn:　にっしゃびょうですね。@KEY()↓
;jpn:◆でも　しんぱいないですよ↓
;jpn:　ぜんぜん　ほんとに。↓
;jpn:　@WI(40)ぬれタオル　もってさえいれば。@KEYNP()
@KEYNP()
@!

;フォーサイド
MSG_HOTEL_FOUR;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_FOUR_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(75)
@XCHG()
@CHKFGOTO(FLG_WIN_GIEGU,_HOTEL_FOUR_LATER)
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　Ｍｏｎｏｔｏｌｉ　Ｇｒａｎｄ　Ｈｏｔｅｌ．@KEY()↓

;jpn:◆モノトリーグランドホテルに↓
;jpn:　ようこそ。@KEY()↓
_HOTEL_FOUR_MAIN;
@GOSUB(_SUB_HOTEL_SELECT)
@SELGOTO(_FOUR_HOTEL_YES,_FOUR_HOTEL_NO)
_FOUR_HOTEL_NO;
@GOSUB(_SUB_HOTEL_NO)
@!
_HOTEL_FOUR_LATER;最終戦闘後は
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　Ｅｎｒｉｃｈ　Ｇｒａｎｄ　Ｈｏｔｅｌ．@KEY()↓

;jpn:◆エンリッチ・グランドホテルに↓
;jpn:　ようこそ。@KEY()↓
@GOTO(_HOTEL_FOUR_MAIN)

_FOUR_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_FOUR_HOTEL_NOMONEY)
@GOSUB(_SUB_HOTEL_YES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_FOUR_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_FOUR_HOTEL_NOMONEY;
@GOSUB(_SUB_HOTEL_NOMONEY)
@!
_FOUR_HOTEL_MORNING;
@GOSUB(_SUB_HOTEL_MORNING)
@!
;サマーズ
MSG_HOTEL_SUMS;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_SUMS_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(150)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｗｅｌｃｏｍｅ　ｔｏ↓
　　Ｌ’ｈｏｔｅｌ　ｄｅ　Ｓｕｍｍｅｒｓ．@KEY()↓
◆Ｍｙ　ｎａｍｅ　ｉｓ↓
　　Ｒｉｓｏｓｈａ　Ｒｉｃｈｍｏｎｄｅ，@KEY()↓
◆ａｎｄ　Ｉ　ａｍ　ｔｈｅ　ａｓｓｉｓｔａｎｔ　ｍａｎａｇｅｒ．@KEY()↓
◆Ｉ’ｍ　ｓｏｒｒｙ　@GET_ORDER_PLAYER(1)@GOSUB(MSG_ESUB_SIR_MAAM)，　ｂｕｔ　Ｉ’ｍ　ａｆｒａｉｄ↓
　　ｔｈａｔ　ｗｅ　ｄｏ　ｎｏｔ　ｈａｖｅ　ａｎｙ　ｒｅｓｅｒｖａｔｉｏｎ　ｕｎｄｅｒ　ｙｏｕｒ　ｎａｍｅ．@KEY()↓
◆Ｈｏｗｅｖｅｒ，　ｗｅ　ｃａｎ　ｏｆｆｅｒ　ｙｏｕ　ａ　ｒｏｏｍ　ａｔ　＄@DSP_NUM(0)　ａ　ｎｉｇｈｔ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｂｅ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ａ　ｒｏｏｍ？↓

;jpn:◆オテル@WI(5)・ド@WI(5)・サマーズに↓
;jpn:　ようこそいらっしゃいました。@KEY()↓
;jpn:◆わたくしが↓
;jpn:　しはいにんだいりの‥‥@KEY()@WI(10)↓
;jpn:◆リゾッチャ@WI(5)・リッチモンド↓
;jpn:　でございます。@KEY()↓
;jpn:◆おきゃくさま@WI(5)↓
;jpn:　ごよやくは　ございませんね。@KEY()↓
;jpn:◆@DSP_NUM(0)ドルのおへやが↓
;jpn:　ごよういできますが@KEY()↓
;jpn:◆おとまりになりますか？↓
@GOSUB(_SUB_HOTEL_SELECT_NOMES)
@SELGOTO(_SUMS_HOTEL_YES,_SUMS_HOTEL_NO)
_SUMS_HOTEL_NO;
◆Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ，　@GET_ORDER_PLAYER(1)@GOSUB(MSG_ESUB_SIR_MAAM)．@KEY()↓
◆Ｐｌｅａｓｅ　ｋｅｅｐ　ｕｓ　ｉｎ　ｍｉｎｄ　ｔｈｅ　ｎｅｘｔ　ｔｉｍｅ　ｙｏｕ　ｃｏｍｅ　ｈｅｒｅ　ｏｎ　ｙｏｕｒ　ｈｏｌｉｄａｙ．

;jpn:◆それは↓
;jpn:　ざんねんでございます。@KEY()↓
;jpn:◆こんどの↓
;jpn:　おやすみのときには@KEY()↓
;jpn:◆ぜひ　ごゆっくり↓
;jpn:　おこしください。
@KEYNP()
@!
_SUMS_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_SUMS_HOTEL_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｅｘｃｅｌｌｅｎｔ　ｃｈｏｉｃｅ，　@GET_ORDER_PLAYER(1)@GOSUB(MSG_ESUB_SIR_MAAM)！@KEY()↓
◆Ｗｅ　ｈｏｐｅ　ｙｏｕ　ｅｎｊｏｙ　ｏｕｒ　ｗｏｎｄｅｒｆｕｌ　ｏｃｅａｎ　ｖｉｅｗ．

;jpn:◆おきゃくさま↓
;jpn:　ラッキーでございます。@KEY()↓
;jpn:◆すばらしい↓
;jpn:　オーシャンビューを↓
;jpn:　おたのしみください。
@KEYNP()
@GOSUB(_SUB_HOTEL_YES_NOMES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_SUMS_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_SUMS_HOTEL_NOMONEY;
◆Ｉｆ　ｙｏｕ　ｄｏ　ｎｏｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｃａｓｈ　ｗｉｔｈ　ｙｏｕ，@KEY()↓
◆ｐｌｅａｓｅ　ｆｅｅｌ　ｆｒｅｅ　ｔｏ　ｕｓｅ　ｔｈｅ　ＡＴＭ　ｊｕｓｔ　ｏｖｅｒ　ｔｈｅｒｅ．

;jpn:◆おきゃくさま　キャッシュを↓
;jpn:　おもちでないようで↓
;jpn:　ございましたら@KEY()↓
;jpn:◆あちらの↓
;jpn:　キャッシュディスペンサーを↓
;jpn:　ごりようくださいませ。
@KEYNP()
@!
_SUMS_HOTEL_MORNING;
◆Ｄｉｄ　ｙｏｕ　ｈａｖｅ　ａ　ｒｅｌａｘｉｎｇ　ｓｌｅｅｐ？@KEY()↓
◆Ｔｈｅ　ｓｏｕｎｄ　ｏｆ　ｔｈｅ　ｏｃｅａｎ　ｗａｖｅｓ　ｄｉｄｎ’ｔ　ｄｉｓｔｕｒｂ　ｙｏｕ，　Ｉ　ｔｒｕｓｔ．

;jpn:◆ゆっくりおやすみに↓
;jpn:　なられましたか？@KEY()↓
;jpn:◆うみのおとが↓
;jpn:　うるさくは↓
;jpn:　ございませんでしたか？
@KEYNP()
@!
;スカラビ
MSG_HOTEL_SKRB;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_SKRB_HOTEL_MORNING)
◆Ｗｅｌｃｏｍｅ　ｔｏ　ｔｈｅ　”Ｇｒｅａｔ　Ｓｏｕｔｈｅｒｎ　Ｉｎｔｅｒｎａｔｉｏｎａｌ　Ｒｅｓｏｒｔ　Ｈｏｔｅｌ．”@KEY()↓
◆Ｏｕｒ　ｒｏｏｍｓ　ｒａｎｇｅ　ｉｎ　ｐｒｉｃｅ↓
　　ｆｒｏｍ
@MUL_ACTIVE_PLAYER(15)
@XCHG()
　　＄@DSP_NUM(0)
@MUL_ACTIVE_PLAYER(100)			;一人分の宿泊費を記入してください。
@XCHG()
　ｔｏ　＄@DSP_NUM(0)↓
　　ａ　ｎｉｇｈｔ．@KEY()↓
◆Ｒｉｇｈｔ　ｎｏｗ，　ｔｈｏｕｇｈ，　ｗｅ　ｏｎｌｙ　ｈａｖｅ　ｏｕｒ　ｓｕｐｅｒ　ｄｅｌｕｘｅ　ｓｕｉｔｅ　ａｖａｉｌａｂｌｅ．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｔａｙ？↓
 
;jpn:◆「グレート・サザーン・↓
;jpn:　こくさい・かんこうホテル」へ↓
;jpn:　ようこそ！@KEY()↓
;jpn:◆ひとばん↓
;@MUL_ACTIVE_PLAYER(15)
;@XCHG()
;jpn:　@DSP_NUM(0)ドルから↓
;@MUL_ACTIVE_PLAYER(100)			;一人分の宿泊費を記入してください。
;@XCHG()
;jpn:　@DSP_NUM(0)ドルですが@KEY()↓
;jpn:◆ただいま　@DSP_NUM(0)ドルの↓
;jpn:　スーパーデラックスルームしか↓
;jpn:　ごよういできません。@KEY()↓
;jpn:◆おとまりになりますか？↓
@GOSUB(_SUB_HOTEL_SELECT_NOMES)
@SELGOTO(_SKRB_HOTEL_YES,_SKRB_HOTEL_NO)
_SKRB_HOTEL_NO;
◆Ｗｅ　ａｒｅ　ｖｅｒｙ　ｓｏｒｒｙ@KEY()↓
◆ｔｈａｔ　ｗｅ　ｄｏ　ｎｏｔ　ｈａｖｅ　ａｎｙ　ｏｆ　ｏｕｒ　ｌｅｓｓ　ｅｘｐｅｎｓｉｖｅ　ｒｏｏｍｓ　ａｖａｉｌａｂｌｅ　ａｔ　ｔｈｉｓ　ｔｉｍｅ．

;jpn:◆あなたむけの↓
;jpn:　やすい　おへやがあいてなくて↓
;jpn:　しつれいしました。
@KEYNP()
@!

_SKRB_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_SKRB_HOTEL_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｐｌｅａｓｅ　ｌｅｔ　ｕｓ　ｋｎｏｗ　ｉｆ　ｙｏｕ　ｆｉｎｄ　ａｎｙ　ｓｃｏｒｐｉｏｎｓ．．．@KEY()↓
◆Ｉｔ’ｓ　ｖｅｒｙ　ｕｎｌｉｋｅｌｙ　ｔｈａｔ　ｔｈｅｙ　ｗｉｌｌ　ｃｏｍｅ　ｏｕｔ，　ｂｕｔ　ｙｏｕ　ｎｅｖｅｒ　ｃａｎ　ｔｅｌｌ．．．

;jpn:◆サソリがでたら↓
;jpn:　おしらせください。@KEY()↓
;jpn:◆たぶんでないとおもいますが。
@KEYNP()
@CLOSEALL()
@WI(1)
;@CHKF(FLG_PU)
;@FALSE_GOTO(_SKRB_HOTEL_RAMA)
@GOSUB(_SUB_HOTEL_YES_NOMES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_SKRB_HOTEL)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_SKRB_HOTEL_NOMONEY;
@GOSUB(_SKRB_HOTEL_NO)
@!
_SKRB_HOTEL_MORNING;
◆Ｇｏｏｄ　ｍｏｒｎｉｎｇ！@KEY()↓
◆Ｔｈｉｓ　ｓｕｒｅ　ｉｓ　ｓｏｍｅ　ｎｉｃｅ　ｗｅａｔｈｅｒ　ｗｅ’ｒｅ　ｈａｖｉｎｇ　ｉｎ　Ｓｃａｒａｂａ　ｌａｔｅｌｙ．

;jpn:◆おはようございます。@KEY()↓
;jpn:◆スカラビは　きょうも↓
;jpn:　いいてんきでございます。
@KEYNP()
』
;ムーンサイド
MSG_HOTEL_MOON;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_MOON_HOTEL_MORNING)
@MUL_ACTIVE_PLAYER(75)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｔｈｉｓ　ｉｓ　ｔｈｅ　Ｄａｒｋ　Ｍｏｏｎ　Ｈｏｔｅｌ．@KEY()↓
◆Ｏｎｅ　ｓｌｅｅｐ　ｐｅｒｉｏｄ　ｉｓ　＄@DSP_NUM(0)．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｌｅｅｐ？↓
;jpn:◆ホテル・ダークムーンです。@KEY()↓
;jpn:◆ひとねむり@WI(10)　@DSP_NUM(0)ドルです。@KEY()↓
;jpn:◆ねむりますか？↓
@GOSUB(_SUB_HOTEL_SELECT_NOMES)
@SELGOTO(_MOON_HOTEL_NO,_MOON_HOTEL_YES)
@GOTO(_MOON_HOTEL_YES)
_MOON_HOTEL_NO;
◆Ｙｏｕ’ｒｅ　ａｃｔｕａｌｌｙ　ｇｏｉｎｇ　ｔｏ　ｔｒｙ　ｔｏ　ｓｔａｙ　ｕｐ．．．？　　Ｈａｈ　ｈａｈ　ｈａｈ！
 
;jpn:◆ずっと　おきているんですね。↓
;jpn:　ホッホッホ！
@KEYNP()
@!
_MOON_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_MOON_HOTEL_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ａｌｌ　ｒｉｇｈｔ．　　Ｈｅｒｅ　ｗｅ　ｇｏ！

;jpn:◆それじゃ　どうぞ。
@KEYNP()
@GOSUB(_SUB_HOTEL_YES_NOMES)
@MUSISTART()				;曲変更のタイミングを合わせる
@WARP(WARP_MOON_HOTEL)			;ワープ先を記入してください。
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
_MOON_HOTEL_NOMONEY;
◆Ｍｏｎｅｙ　ｒｕｌｅｓ　ｈｅｒｅ　ｉｎ　Ｍｏｏｎｓｉｄｅ，　ｔｏｏ．@KEY()↓
◆Ａｎｄ　ｙｏｕ　ｄｏ　ｎｏｔ　ｓｅｅｍ　ｔｏ　ｈａｖｅ　ａｎｙ　ａｔ　ｔｈｉｓ　ｍｏｍｅｎｔ．

;jpn:◆ムーンサイドも↓
;jpn:　かねしだい‥‥。@KEY()↓
;jpn:◆おかねが↓
;jpn:　ないみたいですね。
@KEYNP()
@!
_MOON_HOTEL_MORNING;
◆Ｔｈａｎｋｓ．

;jpn:◆どうも
@KEYNP()
@!

;魔境のおサル
MSG_HOTEL_MAKYO;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_HOTEL_MAKYO_MORNING)
◆Ｔｈｅ　ｍｏｎｋｅｙｓ　ｒｕｎ　ａｎ　ｉｎｎ　ｉｎ　ｔｈｅ　ｆｏｒｅｓｔ．　　Ｙｏｕ　ｃａｎ　ｓｔａｙ　ｔｈｅｒｅ　ｆｏｒ　ｆｒｅｅ！@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｐｅｎｄ　ｔｈｅ　ｎｉｇｈｔ？↓

;jpn:◆この　もりのなかに↓
;jpn:　おサルのやどが　あるんだ。↓
;jpn:　ただで　とまれるよ。@KEY()↓
;jpn:◆とまってくかい？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_HOTEL_MAKYO_YES,_HOTEL_MAKYO_NO)
_HOTEL_MAKYO_NO;
;イイエの場合
◆Ｉ　ｓｗｅａｒ，　ｉｔ　ｄｏｅｓｎ’ｔ　ｓｍｅｌｌ　ｌｉｋｅ　ｍｏｎｋｅｙｓ．

;jpn:◆べつに　おサルくさくないよ。
@KEYNP()
@!
_HOTEL_MAKYO_YES;
;体力回復（暗転ワープあり、ＢＧＭ２、夜鍋あり、セリフ替えなし）
◆Ｙｏｕ’ｒｅ　ｓｕｒｅ　ｔｏ　ｈａｖｅ　ｆｏｎｄ　ｍｅｍｏｒｉｅｓ　ｏｆ　ｔｈｅ　ｍｏｎｋｅｙ’ｓ　ｉｎｎ　ａｆｔｅｒ　ｙｏｕｒ　ｔｒｉｐ．．．

;jpn:◆たびの　おもいでに‥‥↓
;jpn:　おさるのやどやも　いいもんだよ。
@KEYNP()
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_YADOYA_MAKYO)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
;@!

_HOTEL_MAKYO_MORNING;
;ハイの場合、宿泊後
@COLD_PLAYER(PC_ALL)
@OPEN(1)
◆Ｄｉｄｎ’ｔ　ｙｏｕ　ｔｈｉｎｋ　ｉｔ　ｗａｓ　ｃｏｍｆｏｒｔａｂｌｅ？　　Ｔａｋｅ　ｃａｒｅ　ａｎｄ　ｇｏｏｄ　ｂｙｅ．

;jpn:◆あんがい　かいてきだったろう？↓
;jpn:　じゃ　きをつけて↓
;jpn:　いってらっしゃーい。
@KEYNP()
@CLOSEALL()
@FRESH_PLAYER(PC_ALL)
』


;グミの村
MSG_HOTEL_GUMI;
@CHKFGOTO(FLG_HOTEL_PAPERBOY_APPEAR,_HOTEL_GUMI_MORNING)
◆Ｉｎ　ｔｈｅ　ｈｏｌｅ，　ｉｎｎ　ｗｅ　ｈａｖｅ．@KEY()↓
◆Ｆｒｅｅ．　Ｓｔａｙ？↓

;jpn:◆あなの　なか　この↓
;jpn:　ある　やどや。@KEY()↓
;jpn:◆タダ。　やすむか？↓
@GOSUB(MSG_SUB_YESNO_MONEY)
@SELGOTO(_HOTEL_GUMI_YES,_HOTEL_GUMI_NO)
_HOTEL_GUMI_NO;
◆．．．．．

;jpn:◆‥‥‥。
@KEYNP()
』
_HOTEL_GUMI_YES;
;体力回復（暗転ワープあり、ＢＧＭ２、夜鍋あり、セリフ替えなし）
◆Ｏｋａｙ．　Ｙｏｕ　ｓｔａｙ．

;jpn:◆じゃ　やすめ。
@KEYNP()
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_YADOYA_GUMI)
@!

;ハイの時、宿泊後
_HOTEL_GUMI_MORNING;
◆Ｎｉｃｅ　ｓｔａｙ？

;jpn:◆やすんだ。　おまえ。
@KEYNP()
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
』

;地底大陸のグミの村
MSG_DKFD_GUMI_HOTEL;
@MUL_ACTIVE_PLAYER(100)			;一人分の宿泊費を記入してください。
@XCHG()
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｃｏｍｉｎｇ　ａｌｌ　ｔｈｅ　ｗａｙ　ｉｎｔｏ　ｔｈｉｓ　ｐｒｉｍｉｔｉｖｅ　ｃｏｕｎｔｒｙ．@KEY()↓
◆Ｙｏｕ　ｍｕｓｔ　ｂｅ　ｔｉｒｅｄ．↓
　　Ｔｏ　ｓｔａｙ，↓
　　ｉｔ’ｌｌ　ｒｕｎ　ｙｏｕ　＄@DSP_NUM(0)．@KEY()↓
◆Ｙｏｕ　ａｒｅ　ｇｏｉｎｇ　ｔｏ　ｓｔａｙ，ａｒｅｎ’ｔ　ｙｏｕ？↓

;jpn:◆こんな　いなかまで↓
;jpn:　よくきてくれましたね。@KEY()↓
;jpn:◆おつかれでしょ？↓
;jpn:　おとまりなら　@DSP_NUM(0)ドルですがぁ@KEYNP()↓
;jpn:◆とまりますよね？↓
@GOSUB(_SUB_HOTEL_SELECT_NOMES)
@SELGOTO(_DKFD_HOTEL_YES,_DKFD_HOTEL_NO)
_DKFD_HOTEL_NO;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．．．↓
　　Ｍｒ．　Ｔｒａｖｅｌｅｒ．

;jpn:◆また　ぜひ　きてくださいね↓
;jpn:　‥‥たびのかた。
@KEYNP()
@!

_DKFD_HOTEL_YES;
@Q_MONEY(0)
@TRUE_GOTO(_DKFD_HOTEL_NOMONEY)
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｗｅｌｌ，　ｍａｋｅ　ｙｏｕｒｓｅｌｆ　ｃｏｍｆｏｒｔａｂｌｅ．

;jpn:◆それじゃあ　ごゆっくり。
@KEYNP()
@CLOSEALL()
;体力回復（暗転ワープあり、ＢＧＭ２、夜鍋あり、セリフ替えあり）
@GOSUB(MSG_GLOBAL_MYHOME)
@WARP(WARP_YADOYA_DKFD)
@CLRF(FLG_HOTEL_PAPERBOY_APPEAR)
@!
_DKFD_HOTEL_NOMONEY;
◆Ｍｏｎｅｙ　ｒｕｌｅｓ　ｅｖｅｎ　ａｔ　ｔｈｅ　ｅｎｄ　ｏｆ　ｔｈｅ　ｗｏｒｌｄ．@KEY()↓
◆Ｗｅ　ｃａｎｎｏｔ　ａｃｃｅｐｔ　ａ　ｇｕｅｓｔ　ｗｈｏ　ｈａｓ　ｎｏ　ｍｏｎｅｙ．
;jpn:◆いなかのはても　かねしだいと↓
;jpn:　もうしましてね‥‥↓
;jpn:　おかねのないかたは　どうも‥‥。
@KEYNP()
@!

;ホテル用サブルーチン
;金額表示と選択
_SUB_HOTEL_SELECT;
◆Ａ　ｏｎｅ　ｎｉｇｈｔ　ｓｔａｙ　ｗｉｌｌ　ｃｏｓｔ　ｙｏｕ　＄@DSP_NUM(0)．@KEY()↓
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｓｔａｙ？↓
 
;jpn:◆ごしゅくはくは↓
;jpn:　@DSP_NUM(0)ドルです。@KEY()↓
;jpn:◆おとまりになりますか？↓
_SUB_HOTEL_SELECT_NOMES;
@GOSUB(MSG_SUB_YESNO_MONEY)
@!

;ホテルに宿泊（お金支払う、フェードアウト、ＢＧＭ変更、ジェフの夜なべ）
_SUB_HOTEL_YES;
@MONEYOUT(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
◆Ｈａｖｅ　ａ　ｎｉｃｅ　ｓｔａｙ．

;jpn:◆では　ごゆっくりどうぞ。
@KEYNP()
MSG_SUB_SYUKUHAKU;
_SUB_HOTEL_YES_NOMES;
@CLOSEALL()
@WI(1)
@SETF(FLG_HOTEL_PAPERBOY_APPEAR)
@BGM_EFFECT(3)
@MOVE_GOM_CHAR( GOM_HIT_CHR,ANIM_INTO_NIGHT,OBJFX_SHOW_NONE )	;フェードアウト
@WAITSYS()
;
MSG_SUB_HOTEL_YES_CHKF;フラグチェック部分
@CHKFGOTO(FLG_ONET_POLA_TELEPATHY,MSG_ONET_POLA_TELEPATHY);ポーラのメッセージ検査
@CHKFGOTO(FLG_TWSN_POLA_TELEPATHY,MSG_TWSN_POLA_TELEPATHY);ポーラのメッセージ検査
@CHKFGOTO(FLG_WINS_POLA_TELEPATHY,MSG_WINS_POLA_TELEPATHY);ポーラのメッセージ検査
@CHKFGOTO(FLG_PUT_ZOMBI_HOIHOI,_SUB_HOTEL_YES_END)	;ゾンビホイホイ検査
@GOSUB(MSG_JEFF_YONABE)
_SUB_HOTEL_YES_END;
@!

;宿泊しない
_SUB_HOTEL_NO;
◆Ｓｅｅ　ｙｏｕ　ｎｅｘｔ　ｔｉｍｅ．

;jpn:◆では　またのきかいに。
@KEYNP()
@!

;お金がない。
_SUB_HOTEL_NOMONEY;
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ↓
　　＄@DSP_NUM(0)．．．

;jpn:◆@DSP_NUM(0)ドル↓
;jpn:　おもちになって↓
;jpn:　おられないようですが‥‥。
@KEYNP()
@!

;宿泊後のメッセージ
_SUB_HOTEL_MORNING;
◆Ｇｏｏｄ　ｍｏｒｎｉｎｇ．↓
　　Ｄｉｄ　ｙｏｕ　ｓｌｅｅｐ　ｗｅｌｌ？

;jpn:◆おはようございます。@WI(10)↓
;jpn:　よくおやすみに↓
;jpn:　なれましたか？
@KEYNP()
@!

;--------------------------------------------------------------------------
;
;		医者用サブルーチン
;			_SUB_DOCTOR_1
;
;--------------------------------------------------------------------------


_SUB_DOCTOR_1;
@SET_REG(1)
@SAVE_REG()
◆Ｉ　ｃａｎ　ｅｘａｍｉｎｅ　ｅａｃｈ　ｏｎｅ　ｏｆ　ｙｏｕ　ｆｏｒ　＄@DSP_NUM(0)．↓
@SAVE_WIN()
@DSP_PL()
@OPEN(37)
@WINR_MONEY()
@DSP_PL()
<ｙｅｓ，　ｐｌｅａｓｅ>
<ｎｏ，　ｔｈａｎｋｓ>

;jpn:◆はい　ひとり@DSP_NUM(0)ドルで↓
;jpn:　みてあげるよ。↓
;jpn:<みてもらう>
;jpn:<いらない>
;@DSP_ITEM(2)
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
;@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_DCTR_YES,_DCTR_NO)

_DCTR_NO;				;キャンセル
◆Ｙｏｕ　ｒｅａｌｌｙ　ｄｏｎ’ｔ　ｎｅｅｄ　ａｎｙ　ｔｒｅａｔｍｅｎｔ？↓
　　Ａｌｌ　ｒｉｇｈｔ．

;jpn:◆ほんとに　ちりょうは　いらない？↓
;jpn:　あっそ。
_DCTR_END;				;終了
@GOSUB(_DCTR_HOMESICK)
@KEYNP()
@!


_DCTR_YES;
@Q_MONEY(0)				;お金足りる？
@TRUE_GOTO(_DCTR_NOMONEY)

_DCTR_WHO;
@Q_MEMBER(2)			;パーティーは何人？
@TRUE_GOTO(_DCTR_ONE)		;一人なら「だれが・・・」をとばす。

◆Ｗｈｏ　ｉｓ　ｓｉｃｋ？

;jpn:◆どなたが　おわるいんですか？
@DSP_PL()
@SEL_PQ(0,0,0,0,1)			;診てもらいたいキャラ選択。
↓
@FALSE_GOTO(_DCTR_NO)			;キャンセル？
_DCTR_OK;
@SAVE_REG()
@GET_SPECIAL(0,1)			;特殊状態＃１のIDを得る。
@ONGOTO(_DCTR_NEXTCHK,_DCTR_KIZETSU,_DCTR_DAIYA,_DCTR_SIBIRE,_DCTR_KIMO,_DCTR_POISON,_DCTR_NISSYA,_DCTR_KAZE)

_DCTR_ONE;				;一人パーティーの処理。
@GET_ORDER_PLAYER(1)
@GOTO(_DCTR_OK)

_DCTR_NOMONEY;			；お金足りない。
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．↓
　　Ｇｏ　ｈｏｍｅ，　ａｎｄ　ｔｈｅｎ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆おかねが　たりないな。↓
;jpn:　でなおして　くるんだな。
@GOTO(_DCTR_END)

_DCTR_NEXTCHK;
@LOAD_REG()
@GET_SPECIAL(0,2)
@ONGOTO(_DCTR_NOPROBLEM,_DCTR_KINOKO,_DCTR_TORITSUKI)

_DCTR_NOPROBLEM;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｔｈｅｒｅ　ｉｓ　ａｎｙｔｈｉｎｇ　ｗｒｏｎｇ　ｗｉｔｈ　ｙｏｕ．

;jpn:◆わたしのみたてでは↓
;jpn:　どこも　わるくないようだよ。
@GOTO(_DCTR_END)

_DCTR_KIZETSU;
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ａｎｙｏｎｅ　ｈａｓ　ａｎｙｔｈｉｎｇ　ｌｉｋｅ　ｔｈａｔ．@KEY()↓
◆Ｏｒ　Ｉｓ　ｉｔ　ｊｕｓｔ　ｍｙ　ｍｉｓｕｎｄｅｒｓｔａｎｄｉｎｇ？

;jpn:◆そんなひと　いないみたいだけど↓
;jpn:　わたしのおもいちがいかなあ‥‥。
@GOTO(_DCTR_END)

_DCTR_DAIYA;
_DCTR_SIBIRE;
_DCTR_KINOKO;
_DCTR_TORITSUKI;
◆Ｉ　ｃａｎ　ｏｎｌｙ　ｔｒｅａｔ　ａｎ　ｉｌｌｎｅｓｓ．↓
　　Ｓｏｒｒｙ．

;jpn:◆うちじゃ　びょうきしか↓
;jpn:　なおせないんだよ。↓
;jpn:　わるいね。
@GOSUB(_DCTR_END)

_DCTR_HOMESICK;
@Q_SPECIAL(PC_NESS,6,2)
@FALSE_GOTO(_DCTR_HOMESICK_END)
@KEY()↓
;jpn:
◆@WI(15)．．．．．@WI(15)ｂｙ　ｔｈｅ　ｗａｙ，@KEY()↓
◆Ｗｈａｔ　ａ　ｓａｄ　ｌｏｏｋ　ｉｎ　ｙｏｕｒ　ｅｙｅｓ．．．　　ｙｏｕ，　ｔｈｅ　ｂｏｙ　ｉｎ　ａ　ｒｅｄ　ｃａｐ．@KEY()↓
◆Ｙｏｕ　ｍｕｓｔ　ｂｅ　ｈｏｍｅｓｉｃｋ．@KEY()↓
◆Ｔｈａｔ’ｓ　ｎｏｔｈｉｎｇ　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｂｅ　ａｓｈａｍｅｄ　ｏｆ．@KEY()↓
◆Ａｎｙｂｏｄｙ　ｗｈｏ　ｉｓ　ｏｎ　ａ　ｌｏｎｇ　ｔｒｉｐ　ｗｉｌｌ　ｍｉｓｓ　ｈｏｍｅ．@KEY()↓
◆Ｉｎ　ｔｈｉｓ　ｃａｓｅ，@KEY()↓
◆ｔｈｅ　ｂｅｓｔ　ｔｈｉｎｇ　ｔｏ　ｄｏ　ｉｓ　ｔｏ　ｃａｌｌ　ｈｏｍｅ　ａｎｄ　ｈｅａｒ　ｙｏｕｒ　ｍｏｍ’ｓ　ｖｏｉｃｅ．@KEYNP()
;jpn:◆@WI(15)‥‥@WI(15)ところで@WI(30)↓
;jpn:　あかいぼうしのきみの↓
;jpn:　そのさみしげな　まなざし。@KEY()↓
;jpn:◆どうやら　ホームシックに↓
;jpn:　かかってしまったようだね。@KEY()↓
;jpn:◆はずかしいことじゃない。↓
;jpn:　だれだって　ながたびにでれば↓
;jpn:　いえがこいしくなるもんだ。@KEY()↓
;jpn:◆こういうばあい↓
;jpn:　ママのこえを　きくのが↓
;jpn:　いちばんのくすりだよ。
_DCTR_HOMESICK_END;
@!

_DCTR_KAZE;
◆Ｙｏｕ　ｈａｖｅ　ａ　ｃｏｌｄ．

;jpn:◆カゼだね。
@GOTO(_DCTR_CURE)

_DCTR_NISSYA;
◆Ｙｏｕ　ｈａｖｅ　ｓｕｎｓｔｒｏｋｅ．

;jpn:◆にっしゃびょうだね。
@GOTO(_DCTR_CURE)

_DCTR_POISON;
◆Ｙｏｕ’ｖｅ　ｂｅｅｎ　ｐｏｉｓｏｎｅｄ．
;jpn:◆どくにやられたんだね。
@GOTO(_DCTR_CURE)

_DCTR_KIMO;
◆Ｙｏｕ　ｍｕｓｔ　ｆｅｅｌ　ｎａｕｓｅｏｕｓ．

;jpn:◆きぶんが　わるかったんだね。
@GOTO(_DCTR_CURE)

_DCTR_CURE;				;治療する。
@LOAD_REG()				;主レ=PLAYER_ID
@SET_SPECIAL(0,1,1)			;特殊状態回復する。
@LOAD_REG()
@MONEYOUT(0)				;治療費払う。
@WINR_MONEY()
@SE(SE_se25_b_healing)
@WI(50)
@KEY()↓
◆Ｙｏｕ’ｒｅ　ａｌｌ　ｗｅｌｌ　ｎｏｗ．↓
　　Ｗｈａｔ　ａ　ｇｒｅａｔ　ｄｏｃｔｏｒ　ａｍ　Ｉ！

;jpn:　はい　すっかりよくなったよ。↓
;jpn:　わたしって　エライ！
@GOTO(_DCTR_END)

;--------------------------------------------------------------------------
;
;		看護婦用のサブルーチン
;			_SUB_NURSE
;
;--------------------------------------------------------------------------

_SUB_NURSE;
@SET_REG(1)
@GOSUB(_NURSE_Q_ALLLIVING)
@FALSE_GOTO(_NURSE_ADVICE)
◆Ｗｈｏ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｅ？

;jpn:◆どなたに　ごめんかいですか？
@DSP_PL()
@SEL_PQ(0,0,0,0,1)			;誰に面会かを選択。
↓
@FALSE_GOTO(_NURSE_KANZYA)
@SAVE_REG()				;主レ=PLAYER_ID:副レ=治療費を保存
@Q_SPECIAL(0,1,2)
@FALSE_GOTO(_NURSE_NOPLAYER)		

_NURSE_SEL_CURE;
@LOAD_REG()				;主レ=PLAYER_ID:副レ=治療費
@XCHG()
◆@DSP_NAME(0)　ｗａｓ　ｊｕｓｔ　ｂｒｏｕｇｈｔ　ｉｎ，　ａｎｄ　ｉｓ　ｓｔｉｌｌ　ｕｎｃｏｎｓｃｉｏｕｓ．@KEY()↓

;jpn:◆@DSP_NAME(0)さんなら　さきほど↓
;jpn:　はこびこまれました↓
;jpn:　いしきが　もどらないんですが。@KEY()↓
@XCHG()
◆Ｐｌｅａｓｅ　ｐａｙ　＄@DSP_NUM(0)　ｆｏｒ　ｔｈｅ　ｄｏｃｔｏｒ’ｓ　ｆｅｅ．↓
<Ｙｅｓ>
<Ｎｏ>

;jpn:◆ちりょうひを　@DSP_NUM(0)ドル↓
;jpn:　おしはらいください。↓
@WINR_MONEY()
;jpn:<はい>
;jpn:<いいえ>
@DSP_ITEM(2)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_NURSE_CURE_YES,_NURSE_CURE_NO);お金払う？
_NURSE_CURE_NO;
◆Ｙｏｕｒ　ｆｒｉｅｎｄ，ｒｉｇｈｔ？．．．　　Ｉｔ’ｓ　ｖｅｒｙ　ｓｅｒｉｏｕｓ．

;jpn:◆あなたの　おともだちでしょ↓
;jpn:　しんじゃいますよ。
@KEYNP()
@!

_NURSE_CURE_YES;			;お金払う。
@Q_MONEY(0)
@TRUE_GOTO(_NURSE_NOMONEY)		;お金足りる？
@MONEYOUT(0)
@WINR_MONEY()				;金額書換
@LOAD_REG()				;主レ=PLAYER_ID
@SET_SPECIAL(0,1,1)			;気絶回復。
@LOAD_REG()
@SET_SPECIAL(0,2,1)
@LOAD_REG()
@SET_SPECIAL(0,6,1)
@LOAD_REG()
@XCHG()
@HP_UP(0,100)				;HP100%回復？（PLAYER_ID=副レジスタ）
@PP_UP(0,100)				;HP100%回復？（PLAYER_ID=副レジスタ）
@SE(SE_se25_b_healing)
@WI(50)
◆Ｉ’ｍ　ｓｏ　ｇｌａｄ　ｔｈａｔ　ｙｏｕ　ｒｅｃｏｖｅｒｅｄ，　@DSP_NAME(0)．@KEY()↓
◆Ｃｏｍｅ　ｂａｃｋ　ａｎｙ　ｔｉｍｅ　ｙｏｕ　ｎｅｅｄ．

;jpn:◆@DSP_NAME(0)さん↓
;jpn:　げんきになって↓
;jpn:　よかったわね。@KEY()↓
;jpn:◆また　いつでもどうぞ。
@KEYNP()
@!

_NURSE_NOPLAYER;			;気絶していない。
@LOAD_REG()
@XCHG()
◆Ｗｅ　ｄｏｎ’ｔ　ｈａｖｅ　ａ　ｐｅｒｓｏｎ　ｌｉｋｅ　ｔｈａｔ　ｉｎ　ｏｕｒ　ｈｏｓｐｉｔａｌ．

;jpn:◆そういうかたは↓
;jpn:　にゅういん　なさってません。
@KEYNP()
@!

_NURSE_NOMONEY;				;お金が足りない。
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．．．？↓
　　Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ．

;jpn:◆おかねが　たりないんですか‥‥↓
;jpn:　そうですか‥‥。
@KEYNP()
@!

_NURSE_KANZYA;
@CHKFGOTO(FLG_TEMP_9,_NURSE_KANZYA_B)
◆Ｉｆ　ｙｏｕ　ａｒｅ　ｔｈｅ　ｐａｔｉｅｎｔ，　ｃｏｍｅ　ｉｎｔｏ　ｔｈｅ　ｂａｃｋ　ｒｏｏｍ．

;jpn:◆かんじゃさんなら↓
;jpn:　おくのへやに　どうぞ。
@KEYNP()
@!
_NURSE_KANZYA_B;
◆Ｙｏｕ　ｎｅｅｄ　ｔｏ　ｂｅ　ｅｘａｍｉｎｅｄ？↓
　　Ｔｈｅｎ，　ｙｏｕ　ｎｅｅｄ　ｔｏ　ｓｅｅ　ｔｈｅ　ｄｏｃｔｏｒ．．．　　ｎｏｔ　ｍｅ．

;jpn:◆しんさつですか？↓
;jpn:　でしたら　わたしじゃなくて↓
;jpn:　センセイに　みてもらいなさいね。
@KEYNP()
@!
_NURSE_ADVICE;
◆Ｉ’ｍ　ｎｏｔ　ｂｕｓｙ　ｒｉｇｈｔ　ｎｏｗ．@KEY()↓
◆Ｓｈａｌｌ　Ｉ　ｅｘｐｌａｉｎ　ａｂｏｕｔ　ｔｈｅ　ｈｏｓｐｉｔａｌ　ｓｙｓｔｅｍ？↓

;jpn:◆わたしも　ひまだから@KEY()↓
;jpn:◆びょういんの　システムでも↓
;jpn:　せつめいしましょうか？↓
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_NURSE_ADVICE_YES,_NURSE_ADVICE_NO)
_NURSE_ADVICE_NO;
◆Ｙｅａｈ，　ｗｅｌｌ，　Ｉ　ａｍ　ａｃｔｕａｌｌｙ　ｐｒｅｔｔｙ　ｂｕｓｙ．

;jpn:◆そういえば　わたしも↓
;jpn:　ひまなんかじゃ　なかったわ。
@KEYNP()
@!
_NURSE_ADVICE_YES;
◆Ｉｆ　ａ　ｇｏｏｄ　ｆｒｉｅｎｄ　ｏｆ　ｙｏｕｒｓ　ｂｅｃｏｍｅｓ　ｕｎｃｏｎｓｃｉｏｕｓ，@KEY()↓
◆ｃｏｍｅ　ｔｏ　ｔｈｅ　ｈｏｓｐｉｔａｌ　ｒｉｇｈｔ　ａｗａｙ．@KEY()↓
◆Ａｓ　ｌｏｎｇ　ａｓ　ｙｏｕ　ｈａｖｅ　ｍｏｎｅｙ　ｆｏｒ　ｔｈｅ　ｄｏｃｔｏｒ’ｓ　ｆｅｅ，@KEY()↓
◆ｙｏｕ’ｌｌ　ｂｅ　ａｂｌｅ　ｔｏ　ｓｅｅ　ｙｏｕｒ　ｆｒｉｅｎｄ　ｃｏｍｐｌｅｔｅｌｙ　ｒｅｃｏｖｅｒｅｄ　ｉｎ　ｎｏ　ｔｉｍｅ．@KEY()↓
◆Ｂｅｓｉｄｅｓ　ｂｅｉｎｇ　ｕｎｃｏｎｓｃｉｏｕｓ，　ｗｈｅｎｅｖｅｒ@KEY()↓
◆ｙｏｕ　ｄｏｎ’ｔ　ｆｅｅｌ　ｓｏ　ｗｅｌｌ，　ｃｏｍｅ　ａｎｄ　ｔａｌｋ　ｔｏ　ａ　ｄｏｃｔｏｒ．@KEY()↓
◆Ｅｖｅｒｙｔｈｉｎｇ　Ｉ　ｊｕｓｔ　ｔｏｌｄ　ｙｏｕ　ａｐｐｌｉｅｓ　ｔｏ　ｈｏｓｐｉｔａｌｓ　ａｌｌ　ｏｖｅｒ　ｔｈｅ　ｗｏｒｌｄ．
;jpn:◆だいじな　おともだちが↓
;jpn:　きぜつしちゃったときには@KEY()↓
;jpn:◆とにかく　びょういんに↓
;jpn:　いらっしゃい。@KEY()↓
;jpn:◆ちりょうひさえあれば↓
;jpn:　きっと　げんきなおともだちと↓
;jpn:　さいかいできるわよ。@KEY()↓
;jpn:◆きぜついがいにも↓
;jpn:　からだの　ぐあいが↓
;jpn:　おかしいなって　おもったら@KEY()↓
;jpn:◆とにかく　せんせいに↓
;jpn:　そうだんしてみることね。@KEY()↓
;jpn:◆いま　おはなししたことって↓
;jpn:　このびょういんだけじゃなく↓
;jpn:　せかい　きょうつうなのよ。
@KEYNP()
@!

_NURSE_Q_ALLLIVING;
@Q_SPECIAL(PC_NESS,1,2)
@TRUE_GOTO(_ALLLIVING_END)
@Q_SPECIAL(PC_PAULA,1,2)
@TRUE_GOTO(_ALLLIVING_END)
@Q_SPECIAL(PC_JEFF,1,2)
@TRUE_GOTO(_ALLLIVING_END)
@Q_SPECIAL(PC_POO,1,2)
_ALLLIVING_END;
@!

;-------------------------------------------------------------------------
;
;		宿泊のサブルーチン
;		MSG_SUB_HOTEL_LIFEUP
;
;-------------------------------------------------------------------------
;ホテル回復（ＨＰ回復、ＢＧＭ変更なし）
MSG_SUB_HOTEL_LIFEUP;
@SET_LOOPREG(1)
_TEST_HOTEL_LOOP;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_TEST_HOTEL_LOOPEND)
@GET_ORDER_PLAYER(0)
@SAVE_REG()
@Q_SPECIAL(0,1,2)
@TRUE_GOTO(_TEST_HOTEL_LOOPNEXT)
@LOAD_REG()
@Q_SPECIAL(0,1,3)
@TRUE_GOTO(_TEST_HOTEL_LOOPNEXT)
@LOAD_REG()
@XCHG()
@HP_UP(0,100)				;ＨＰ・ＰＰ全回復
@PP_UP(0,100)				
_TEST_HOTEL_LOOPNEXT;
@INC()
@GOTO(_TEST_HOTEL_LOOP)
_TEST_HOTEL_LOOPEND;
@GOSUB(_HOTEL_FOREVENT)
@CLRF(FLG_DAY_AFTER)
@!

_HOTEL_FOREVENT;
@CHKFGOTO(FLG_DSRT_SWITCH_BEFORE,_HTL_FOREVENT_2)
@!
_HTL_FOREVENT_2;
@SETF(FLG_DSRT_SWITCH)
@CLRF(FLG_DSRT_SWITCH_BEFORE)
@!

MSG_SUB_BGM_LIFEUP;
MSG_SUB_SE_LIFEUP;
@BGMSTART(0,BGM_lifeup)
@WI(200)
@MUSISTART();コメントアウトを外した（三浦）
@WI(1);同上
@!

;スペーストンネル回復（ＨＰ回復、全特殊状態治療、ＢＧＭ変更あり、夜鍋なし）
MSG_SUB_SPACE_KAIHUKU;
MSG_SPACE_KAIHUKU;
;@GOSUB(MSG_JEFF_YONABE)
@GOSUB(MSG_SUB_ALLHEAL_POWR)
@GOSUB(MSG_SUB_SE_LIFEUP)
@GOSUB(_HOTEL_FOREVENT)
@CLRF(FLG_DAY_AFTER)
@!

;ＰＳ回復（ＨＰ回復、全特殊状態治療、ＢＧＭ変更なし、夜鍋なし）
MSG_SUB_ALLHEAL_POWR;
@SET_LOOPREG(1)
_ALLH_POWR_LOOP;
@SET_REG(1)
@XCHG()
@SAVE_REG()
@EQ(5)
@TRUE_GOTO(_ALLH_END)
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@FALSE_GOTO(_ALLHEAL_INC)	;7/26に挿入
@SET_SPECIAL(0,2,1)
@SET_SPECIAL(0,6,1)
@XCHG()
@HP_UP(0,100)
@PP_UP(0,100)
_ALLHEAL_INC;			;7/26に挿入
@INC()
@GOTO(_ALLH_POWR_LOOP)
_ALLH_END;
@!

;土星医者回復（全特殊状態回復、気絶時のみＨＰＰＰ回復、ＳＥならす）
MSG_SUB_ZENKAI;
_SUB_ZENKAI;
@SET_LOOPREG(1)			;loopR = 1
_ZENKAI_LOOP;
@SET_REG(1)			;subR = loopR
@Q_MEMBER(0)			;if(partyMem < subR){mainR = 1} else {mainR = 0}
@TRUE_GOTO(_ZENKAI_END)		;if(mainR == 1) goto _ZENKAI_END 全プレーヤーでループさせる。
@GET_ORDER_PLAYER(0)		;mainR = playerId[subR]
@SAVE_REG()			;push mainR,subR,loopR
@Q_SPECIAL(0,1,2)		;mainR = specialId[subR,1,気絶]
@FALSE_GOTO(_ZENKAI_2)		;if(!気絶)goto _ZENKAI_2
@LOAD_REG()			;pop mainR,subR,loopR
@SET_SPECIAL(0,1,1)		;気絶直す
@XCHG()				;xchg subR,mainR(→subR=気絶状態,mainR=playerId)
@HP_UP(0,100)			;ＨＰ・ＰＰ全回復
@PP_UP(0,100)			;全特殊状態が通常に。
_ZENKAI_2;			;生きてるときはここに来る
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@SET_SPECIAL(0,2,1)
@SET_SPECIAL(0,6,1)
@SE(SE_se25_b_healing)
@INC()
@GOTO(_ZENKAI_LOOP)
_ZENKAI_END;
@!

;タライ・ジャブ回復（一人だけＨＰＰＰ回復、全特殊状態治療、ＢＧＭなし）
MSG_SUB_ALLHEAL_ONE;
@SET_REG(1)
@XCHG()
@SET_SPECIAL(0,1,1)
@SET_SPECIAL(0,2,1)
@SET_SPECIAL(0,6,1)
@XCHG()
@HP_UP(0,100)
@PP_UP(0,100)
@!



;マイホーム回復（体力回復、暗転ワープあり、ＢＧＭあり、夜鍋あり、この後ワープ）
MSG_GLOBAL_MYHOME;
@GOSUB(MSG_SUB_SYUKUHAKU)
@GOSUB(MSG_SUB_BGM_LIFEUP)
@GOSUB(MSG_SUB_HOTEL_LIFEUP)
@!
;=============================== ヒーラー ====================================
MSG_HEALER_ONET;
@SETF(FLG_SHOP_01)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_01)
@!

MSG_HEALER_TWSN;
@SETF(FLG_SHOP_02)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_02)
@!

MSG_HEALER_THRK;
@SETF(FLG_SHOP_03)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_03)
@!

MSG_HEALER_DSRT;
@SETF(FLG_SHOP_04)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_04)
@!

MSG_HEALER_FOUR;
@SETF(FLG_SHOP_05)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_05)
@!

MSG_HEALER_SUMS;
@SETF(FLG_SHOP_06)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_06)
@!

MSG_HEALER_SKRB;
@SETF(FLG_SHOP_07)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_07)
@!

MSG_HEALER_MOON;
@SETF(FLG_SHOP_08)
@SETF(FLG_SHOPTEMP_4)
@GOSUB(MSG_SUB_HEALER)
@CLRF(FLG_SHOP_08)
@CLRF(FLG_SHOPTEMP_4)
@!

_HEALER_SEL_DIA;
@SETF(FLG_HEAL_DIA)
@CHKFGOTO(FLG_SHOP_01,_HEAL_DIA_MONEY_01)
@CHKFGOTO(FLG_SHOP_02,_HEAL_DIA_MONEY_02)
@CHKFGOTO(FLG_SHOP_03,_HEAL_DIA_MONEY_03)
@CHKFGOTO(FLG_SHOP_04,_HEAL_DIA_MONEY_04)
@CHKFGOTO(FLG_SHOP_05,_HEAL_DIA_MONEY_05)
@CHKFGOTO(FLG_SHOP_06,_HEAL_DIA_MONEY_06)
@CHKFGOTO(FLG_SHOP_07,_HEAL_DIA_MONEY_07)
@CHKFGOTO(FLG_SHOP_08,_HEAL_DIA_MONEY_08)
@!
_HEAL_DIA_MONEY_01;
@SET_LOOPREG(70)
@!
_HEAL_DIA_MONEY_02;
@SET_LOOPREG(80)
@!
_HEAL_DIA_MONEY_03;
@SET_LOOPREG(90)
@!
_HEAL_DIA_MONEY_04;
@SET_LOOPREG(100)
@!
_HEAL_DIA_MONEY_05;
@SET_LOOPREG(100)
@!
_HEAL_DIA_MONEY_06;
@SET_LOOPREG(120)
@!
_HEAL_DIA_MONEY_07;
@SET_LOOPREG(150)
@!
_HEAL_DIA_MONEY_08;
@SET_LOOPREG(100)
@!
_HEALER_SEL_SIBIRE;
@SETF(FLG_HEAL_SIBIRE)
@CHKFGOTO(FLG_SHOP_01,_HEAL_SIBIRE_MONEY_01)
@CHKFGOTO(FLG_SHOP_02,_HEAL_SIBIRE_MONEY_02)
@CHKFGOTO(FLG_SHOP_03,_HEAL_SIBIRE_MONEY_03)
@CHKFGOTO(FLG_SHOP_04,_HEAL_SIBIRE_MONEY_04)
@CHKFGOTO(FLG_SHOP_05,_HEAL_SIBIRE_MONEY_05)
@CHKFGOTO(FLG_SHOP_06,_HEAL_SIBIRE_MONEY_06)
@CHKFGOTO(FLG_SHOP_07,_HEAL_SIBIRE_MONEY_07)
@CHKFGOTO(FLG_SHOP_08,_HEAL_SIBIRE_MONEY_08)
@!
_HEAL_SIBIRE_MONEY_01;
@SET_LOOPREG(60)
@!
_HEAL_SIBIRE_MONEY_02;
@SET_LOOPREG(70)
@!
_HEAL_SIBIRE_MONEY_03;
@SET_LOOPREG(80)
@!
_HEAL_SIBIRE_MONEY_04;
@SET_LOOPREG(90)
@!
_HEAL_SIBIRE_MONEY_05;
@SET_LOOPREG(90)
@!
_HEAL_SIBIRE_MONEY_06;
@SET_LOOPREG(110)
@!
_HEAL_SIBIRE_MONEY_07;
@SET_LOOPREG(140)
@!
_HEAL_SIBIRE_MONEY_08;
@SET_LOOPREG(90)
@!
_HEALER_SEL_OHARAI;
@SETF(FLG_HEAL_OHARAI)
@CHKFGOTO(FLG_SHOP_01,_HEAL_OHARAI_MONEY_01)
@CHKFGOTO(FLG_SHOP_02,_HEAL_OHARAI_MONEY_02)
@CHKFGOTO(FLG_SHOP_03,_HEAL_OHARAI_MONEY_03)
@CHKFGOTO(FLG_SHOP_04,_HEAL_OHARAI_MONEY_04)
@CHKFGOTO(FLG_SHOP_05,_HEAL_OHARAI_MONEY_05)
@CHKFGOTO(FLG_SHOP_06,_HEAL_OHARAI_MONEY_06)
@CHKFGOTO(FLG_SHOP_07,_HEAL_OHARAI_MONEY_07)
@CHKFGOTO(FLG_SHOP_08,_HEAL_OHARAI_MONEY_08)
@!
_HEAL_OHARAI_MONEY_01;
@SET_LOOPREG(50)
@!
_HEAL_OHARAI_MONEY_02;
@SET_LOOPREG(60)
@!
_HEAL_OHARAI_MONEY_03;
@SET_LOOPREG(70)
@!
_HEAL_OHARAI_MONEY_04;
@SET_LOOPREG(80)
@!
_HEAL_OHARAI_MONEY_05;
@SET_LOOPREG(80)
@!
_HEAL_OHARAI_MONEY_06;
@SET_LOOPREG(100)
@!
_HEAL_OHARAI_MONEY_07;
@SET_LOOPREG(130)
@!
_HEAL_OHARAI_MONEY_08;
@SET_LOOPREG(80)
@!
MSG_SUB_HEALER;
@GOSUB(_SUB_HEALMES_1)
@GOSUB(_SUB_KINOKO_CHK)
@FALSE_GOTO(_HEALER_SEL2)
@GOSUB(_SUB_HEALER_KINOKO)
@GOSUB(_SUB_HEALMES_2)
_HEALER_SEL;
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_HEALER_0_YES,_HEALER_NO)
@GOTO(_HEALER_NO)
_HEALER_0_YES;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｍｅ　ｔｏ　ｄｏ？↓

;jpn:◆どうしてほしい？↓
@SAVE_WIN()
@DSP_PL()
@OPEN(37)
<Ｓｏｆｔｅｎ>
<Ｒｅｓｔｏｒｅ　ｆｅｅｌｉｎｇ>
<Ｐｕｒｉｆｙ>

;jpn:<やわらかくする>
;jpn:<ビリビリをとる>
;jpn:<おはらいをする>
@DSP_ITEML(1)
@SELQ()
@SAVE_GLOBAL_REG()
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@FALSE_GOTO(_HEALER_NO)
@ONGOSUB(_HEALER_SEL_DIA,_HEALER_SEL_SIBIRE,_HEALER_SEL_OHARAI)
@SET_REG(1)
◆Ｉ　ｎｅｅｄ　ｔｏ　ｃｈａｒｇｅ　ｙｏｕ　＄@DSP_NUM(0)．↓

;jpn:◆@DSP_NUM(0)ドル　いただいて↓
;jpn:　おこうか。↓
@GOSUB(MSG_SUB_YESNO_MONEY)
;
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_HEALER_SEL_MONEY_YES,_HEALER_SEL_MONEY_NO)
;
_HEALER_SEL_MONEY_NO;
←
◆Ｍｍｍ，　ｃｏｍｅ　ｂａｃｋ　ｗｈｅｎ　ｎｅｃｅｓｓａｒｙ．
;jpn:◆おお　そうか　そうしなさい。
@KEYNP()
@GOSUB(_SUB_HEALER_FLG_CLR)
@!

_HEALER_SEL_MONEY_YES;
@Q_MONEY(0)
@TRUE_GOTO(_HEALER_NOMONEY)
@Q_MEMBER(2)
@FALSE_GOTO(_HEALER_WHO)
@GET_ORDER_PLAYER(1)
@GOTO(_HEALER_WHO2)
_HEALER_WHO;
◆Ｗｈｏ　ｎｅｅｄｓ　ｈｅａｌｉｎｇ？

;jpn:◆だれを　ヒーリングする？
_HEALER_WHO_SEL;
@SEL_PQ(0,0,0,0,1)
@FALSE_GOTO(_HEALER_SEL_MONEY_NO)
_HEALER_WHO2;
@SAVE_REG()
@CHKFGOTO(FLG_HEAL_OHARAI,_HEALER_HEAL_OHARAI)
@CHKFGOTO(FLG_HEAL_SIBIRE,_HEALER_HEAL_SIBIRE)
@CHKFGOTO(FLG_HEAL_DIA,_HEALER_HEAL_DIA)
@!

_HEALER_HEAL_DIA;				;ダイヤ処理
@Q_SPECIAL(0,1,3)
@FALSE_GOTO(_HEALER_DIA_NO)
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@GOSUB(_SUB_HEALER_HEAL)
@!
_HEALER_HEAL_SIBIRE;				;しびれ処理
@Q_SPECIAL(0,1,4)
@FALSE_GOTO(_HEALER_SIBIRE_NO)
@LOAD_REG()
@SET_SPECIAL(0,1,1)
@GOSUB(_SUB_HEALER_HEAL)
@!
_HEALER_HEAL_OHARAI;				;とりつき処理
@Q_SPECIAL(0,2,3)
@FALSE_GOTO(_HEALER_OHARAI_NO)
@LOAD_REG()
@SET_SPECIAL(0,2,1)
@GOSUB(_SUB_HEALER_HEAL)
@!

_HEALER_DIA_NO;
@LOAD_REG()
@XCHG()
←
◆@DSP_NAME(0)　ｉｓｎ’ｔ　ｈａｒｄ　ｌｉｋｅ　ａ　ｄｉａｍｏｎｄ．
 
;jpn:◆@DSP_NAME(0)は↓
;jpn:　ダイヤじょうたいじゃないな。
@GOTO(_HEALER_Q_NEXT)

_HEALER_SIBIRE_NO;
@LOAD_REG()
@XCHG()
←
◆@DSP_NAME(0)　ｉｓｎ’ｔ　ｎｕｍｂ．

;jpn:◆@DSP_NAME(0)は↓
;jpn:　しびれておらんぞ。
@GOTO(_HEALER_Q_NEXT)

_HEALER_OHARAI_NO;
@LOAD_REG()
@XCHG()
←
◆@DSP_NAME(0)　ｉｓｎ’ｔ　ｐｏｓｓｅｓｓｅｄ．
  
;jpn:◆@DSP_NAME(0)は↓
;jpn:　とりつかれては　おらんぞ。
@GOTO(_HEALER_Q_NEXT)

_HEALER_Q_NEXT;
@XCHG()
@Q_MEMBER(2)
@TRUE_GOTO(_HEALER_Q_NEXT_END)
←
　　Ｗｈｏ　ｎｅｅｄｓ　ｔｏ　ｂｅ　ｈｅａｌｅｄ？

;jpn:　だれを　ヒーリングする？
@GOTO(_HEALER_WHO_SEL)
_HEALER_Q_NEXT_END;
@KEYNP()
@GOSUB(_SUB_HEALER_FLG_CLR)
@!

_HEALER_NO;
◆Ｍｍｍ，　ｃｏｍｅ　ｂａｃｋ　ｗｈｅｎ　ｎｅｃｅｓｓａｒｙ．
;jpn:◆おお　そうか　そうしなさい。
@KEYNP()
@GOSUB(_SUB_HEALER_FLG_CLR)
@!

_HEALER_NOMONEY;
←
◆Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｍｏｎｅｙ，　ｙｏｕ’ｌｌ　ｊｕｓｔ　ｈａｖｅ　ｔｏ　ｋｅｅｐ　ｏｎ　ｇｏｉｎｇ　ｉｎ　ｙｏｕｒ　ｃｕｒｒｅｎｔ　ｓｔａｔｅ．

;jpn:◆おかねが　ないなら↓
;jpn:　そのまま　いきなさい。
@KEYNP()
@GOSUB(_SUB_HEALER_FLG_CLR)
@!

_HEALER_SEL2;
@GOSUB(_SUB_HEALMES_3)
@GOTO(_HEALER_SEL)

_SUB_HEALER_HEAL;
@MONEYOUT(0)
@WINR_MONEY()
@LOAD_REG()
@SE(SE_se25_b_healing)
@WI(30)
@XCHG()
←
◆Ｈｅｙ！　　Ｙｏｕ’ｒｅ　ａｌｒｅａｄｙ　ｈｅａｌｅｄ！↓
　　Ｃａｎ　Ｉ　ｄｏ　ｍｙ　ｊｏｂ　ｗｅｌｌ，　ｏｒ　ｗｈａｔ！

;jpn:◆っはい！　もうなおってる。↓
;jpn:　わたしって　スゴイ！
@KEYNP()
@GOSUB(_SUB_HEALER_FLG_CLR)
@!

_SUB_KINOKO_CHK;
@GET_MEMBERS()
@SET_LOOPREG(1)				;（キノコの状態のプレーヤーの合計を
_KINOKO_CHK_LOOP;			;求める）
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_KINOKO_CHK_END2)		;全プレーヤーでループさせる。
@GET_ORDER_PLAYER(0)
@FALSE_GOTO(_KINOKO_CHK_END)		;プレーヤー未だいる？
@Q_SPECIAL(0,2,2)			;キノコチェック。
@TRUE_GOTO(_KINOKO_CHK_END)		;キノコ？
@INC()
@GOTO(_KINOKO_CHK_LOOP)
_KINOKO_CHK_END;
@!
_KINOKO_CHK_END2;
@EQ(0)
@!

_SUB_HEALER_KINOKO;
◆Ｈｅｙ，　ｎｏｗ　ｔｈａｔ　Ｉ　ｎｏｔｉｃｅ，@KEY()↓
◆ｃｏｕｌｄ　ｙｏｕ　ｓｅｌｌ　ｍｅ　ｔｈｅ　ｍｕｓｈｒｏｏｍ　ｇｒｏｗｉｎｇ　ｏｎ　ｔｏｐ　ｏｆ　ｙｏｕｒ　ｈｅａｄ？@KEY()↓
◆Ｃｏｍｅ　ｏｎ，　ｌｅｔ’ｓ　ｍａｋｅ　ａ　ｄｅａｌ．@KEY()↓
<Ｓｅｌｌ>
<Ｎｏ>
;jpn:◆おっ　そこのきみ。↓
;jpn:　その　あたまのうえに　はえてる↓
;jpn:　キノコを　うってくれないか。@KEY()↓
;jpn:◆はなしは　それからね。↓
@WINR_MONEY()
;jpn:<うる>
;jpn:<うらない>
@DSP_ITEM(2)
@SELGOTO(_HEALER_KINOKO_YES,_HEALER_KINOKO_NO)
_HEALER_KINOKO_NO;
◆Ｈｍｍｍｍｍ．．．．．．．↓
　　Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ．@KEY()
;jpn:◆そうか‥‥↓
;jpn:　それは　ざんねん@KEY()
@!
_HEALER_KINOKO_YES;５００→５０ドルに修正
◆Ｔｈａｎｋｓ．↓
　　Ｉ’ｌｌ　ｐａｙ　ｙｏｕ　＄５０　ｆｏｒ　ｅａｃｈ　ｍｕｓｈｒｏｏｍ．@KEY()↓
◆Ａｌｌ　ｒｉｇｈｔ，　ｌｅｔ’ｓ　ｄｏ　ｉｔ！@KEY()
;jpn:◆ありがとう。↓
;jpn:　じゃ　ひとつ５０ドルで　かうよ。↓
;jpn:　そらっ。@KEY()
@GOSUB(_SUB_HEAL_KINOKO)
@!

_SUB_HEAL_KINOKO;
@SET_LOOPREG(1)
_HEAL_KINOKO_LOOP;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_SUB_HEAL_KINOKO_END)
@GET_ORDER_PLAYER(0)
@SAVE_REG()
@FALSE_GOTO(_SUB_HEAL_KINOKO_END)
@Q_SPECIAL(0,2,2)
@FALSE_GOTO(_HEAL_KINOKO_INC)
@LOAD_REG()
@SET_SPECIAL(0,2,1)
@SET_REG(0)
@MONEYIN(50)
@WINR_MONEY()
@SE(SE_se25_b_healing)
@WI(30)
_HEAL_KINOKO_INC;
@INC()
@GOTO(_HEAL_KINOKO_LOOP)
_SUB_HEAL_KINOKO_END;
←
@!

_SUB_HEALER_FLG_CLR;
@RESF(FLG_HEAL_DIA)
@RESF(FLG_HEAL_SIBIRE)
@RESF(FLG_HEAL_OHARAI)
@!

_SUB_HEALMES_1;
◆Ｔｈｏｕｇｈ　ｙｏｕ　ｍａｙ　ｎｏｔ　ｂｅｌｉｅｖｅ　ｉｔ，　Ｉ’ｍ　ａ　ｈｅａｌｅｒ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｈａｖｅ　ｓｏｍｅ　ｉｌｌｎｅｓｓ　ｔｈａｔ　ｃａｎ　ｎｏｔ　ｂｅ　ｔｒｅａｔｅｄ　ａｔ　ｔｈｅ　ｈｏｓｐｉｔａｌ，@KEY()↓
◆ｉｔ’ｓ　ｍｙ　ｊｏｂ　ｔｏ　ｃｕｒｅ　ｙｏｕ．@KEY()↓
  
;jpn:◆しんじようが　しんじまいが↓
;jpn:　わたしは　ヒーラー。@KEY()↓
;jpn:◆びょういんで　なおせない↓
;jpn:　びょうきなら　わしのでばんじゃ。@KEY()↓
@!

_SUB_HEALMES_1B;
←
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙ　ｈｅｌｐ？↓

;jpn:◆たすけが　ひつようか？↓
@!

_SUB_HEALMES_2;
←
◆Ｂｙ　ｔｈｅ　ｗａｙ，　ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙ　ｈｅｌｐ？↓

;jpn:◆ところで　たすけがひつようか？↓
;◆ところで　どうしたい？↓
@!
_SUB_HEALMES_3;
←
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ｓｏｍｅ　ｈｅｌｐ？↓

;jpn:◆たすけがひつようか？↓
;◆どうしてほしい？↓
@!
