;スカラビ南部のオアシスの武器密売人
;（ｗｅａｐｏｎ　ｓｍｕｇｇｌｅｒ　ｉｎ　ｔｈｅ　ｏａｓｉｓ　ａｔ
;　　ｓｏｕｔｈ　ｏｆ　Ｓｃａｒａｂｉ）
MSG_SUB_SHOPMES_MITUBAI_1;
◆Ｓｉｎｃｅ　Ｉ’ｍ　ｄｅａｌｉｎｇ　ｉｎ　ｓｏｍｅ　ｐｒｅｔｔｙ　ｒｏｕｇｈ　ｓｔｕｆｆ，@KEY()↓
◆Ｉ　ｃａｎ’ｔ　ｒｕｎ　ｍｙ　ｂｕｓｉｎｅｓｓ　ｉｎ　ｔｏｗｎ．
;jpn:◆ヤバイものあつかってるから↓
;jpn:　まちじゃ↓
;jpn:　しょうばいできないんだ。
@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_2;
◆Ｓｅｅ　ｙｏｕ　ｌａｔｅｒ．

;jpn:◆それじゃあな。
@KEYNP()
@!
MSG_SUB_SHOPMES_MITUBAI_3;
◆Ｓｅｅ　ｙｏｕ．．．　ｌａｔｅｒ．

;jpn:◆それじゃあな。
@KEYNP()
@!
MSG_SUB_SHOPMES_MITUBAI_4;
◆Ｉ’ｖｅ　ｇｏｔ　ａ　ｗｉｄｅ　ｓｅｌｅｃｔｉｏｎ．　　Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｌｏｏｋｉｎｇ　ｆｏｒ？

;jpn:◆いろいろあるよ↓
;jpn:　なんにする？
@KEY()
@!
MSG_SUB_SHOPMES_MITUBAI_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_6;

◆Ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｇｅｔ　ｔｈｉｓ？
@KEY()

;jpn:◆だれが　もつんだい？@KEY()
@!
MSG_SUB_SHOPMES_MITUBAI_7;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｈｅｒｅ？↓

;jpn:◆そいつを↓
;jpn:　ここでそうびするかい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_8;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｍｅ　ｔｏ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)@KEY()↓
◆ｆｏｒ　@XCHG()＄@DSP_NUM(0)？↓
 
;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでかいあげようか？↓
@!
MSG_SUB_SHOPMES_MITUBAI_9;
◆@DSP_NAME(0)　　ｃａｎ’ｔ　ｅｑｕｉｐ　ｔｈｉｓ．
@KEY()↓
◆Ａｒｅ　ｙｏｕ　ｓｔｉｌｌ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ｂｕｙｉｎｇ　ｉｔ？↓
 
;jpn:◆@DSP_NAME(0)には↓
;jpn:　そうびできないけど↓
;jpn:◆それでもかうかい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_10;
◆Ａｉｎ’ｔ　ｔｈａｔ　ｔｈｅ　ｐｉｔｓ．．．@KEY()↓
◆Ｉ’ｍ　ａｃｔｕａｌｌｙ　ｇｏｎｎａ　ｈａｖｅ　ｔｏ　ｗａｉｔ　ｆｏｒ　ａｎｏｔｈｅｒ　ｃｕｓｔｏｍｅｒ　ｉｎ　ｔｈｉｓ　ｃｒａｚｙ　ｈｅａｔ？@KEY()↓
◆Ｔｈａｔ’ｓ　ｈａｒｓｈ．．．
@KEY()↓

;jpn:◆なんだ‥‥↓
;jpn:　このくそあついなか@KEY()↓
;jpn:◆つぎのきゃくをまたなけりゃ↓
;jpn:　いけないのか。↓
;jpn:　つらいなー。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_11;
◆Ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ，@KEY()↓
◆ｉｔ’ｓ　ａ　ｗａｓｔｅ　ｏｆ　ｍｙ　ｔｉｍｅ　ｔｏ　ｅｖｅｎ　ｔａｌｋ　ａｂｏｕｔ　ｄｅａｌｉｎｇ　ｗｉｔｈ　ｙｏｕ．
@KEY()↓

;jpn:◆おかねもってなけりゃ↓
;jpn:　はなしになんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_12;
◆Ｙｏｕ　ｇｕｙｓ　ａｒｅ　ｃｏｍｐｌｅｔｅｌｙ　ｏｖｅｒｌｏａｄｅｄ．
@KEY()↓
◆Ｈｏｗｅｖｅｒ，　Ｉ　ｃａｎ　ｂｕｙ　ｔｈｅ　ｓｔｕｆｆ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ．
@KEY()↓
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｄｏ？↓
 
;jpn:◆にもつがいっぱいだよ。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとってもいいぜ。@KEY()↓
;jpn:◆どうする？↓
@!
MSG_SUB_SHOPMES_MITUBAI_13;
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｓｅｌｌ　ｍｅ？↓

;jpn:◆なにを↓
;jpn:　うってくれるんだい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_14;
◆@DSP_GOODS(0)？↓
　　Ｌｅｔ’ｓ　ｓｅｅ．．．@KEY()↓
◆Ｈｏｗ　ａｂｏｕｔ　@XCHG()＄@DSP_NUM(0)？↓

;jpn:◆@DSP_GOODS(0)だね。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでどうだい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_15;
◆ＯＫ．　　Ｉ　ｔｈｏｕｇｈｔ　ｍｙ　ｏｆｆｅｒ　ｗａｓ　ｍｏｒｅ　ｔｈａｎ　ｆａｉｒ．
@KEY()↓

;jpn:◆そうか。↓
;jpn:　そんなら　そうしな。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_16;
◆Ａｒｅ　ｙｏｕ　ｔｒｙｉｎｇ　ｔｏ　ｃｏｎ　ｍｅ？　　Ｙｏｕ’ｖｅ　ｇｏｔ　ｎｏｔｈｉｎｇ　ｔｏ　ｓｅｌｌ！！
@KEY()↓
;jpn:◆なんだ　うるもの↓
;jpn:　もってないじゃないか。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_17;
◆Ｓｏｒｒｙ，　ｔｈａｔ　ｉｓ　ａｎ　ｉｔｅｍ　Ｉ　ｊｕｓｔ　ｄｏｎ’ｔ　ｄｅａｌ　ｉｎ．
@KEY()↓
 
;jpn:◆わるいな。↓
;jpn:　そいつは　うちじゃ↓
;jpn:　あつかってないんだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_18;
◆Ｈｅｙ，　ｔｈａｎｋｓ！@KEY()↓

;jpn:◆ありがとよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_19;
◆Ｈｅｙ，ｔｈａｎｋｓ！@KEY()↓

;jpn:◆ありがとよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MITUBAI_20
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｙｏｕ　ｎｅｅｄ？↓

;jpn:◆ほかにも↓
;jpn:　なにかようはあるかい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_21;
◆Ｓｏ　ｗｈａｔ’ｓ　ｔｈｅ　ｄｅａｌ？↓

;jpn:◆どうしたいんだい？↓
@!
MSG_SUB_SHOPMES_MITUBAI_22;
◆@DSP_NAME(0)　ｈａｓ　ｗａｙ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ａｎｄ　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつがいっぱいで↓
;jpn:　もてないよ。@KEY()↓
;jpn:◆ほかのやつが　もつかい？↓
@!
;レゲエジャンク（ｒｅｇｇａｅ ｊｕｎｋ）

MSG_SUB_SHOPMES_JUNK1_1;
◆Ｈｅｙ　ｍｏｎ！　　Ｙｏｕ　ｇｏｔ　ｔｏ　ｅｘｐａｎｄ　ｙｏｕｒ　ｍｉｎｄ　ａｎ’　ｕｓｅ　ｔｈｉｓ　ｓｔｕｆｆ　ｃｒｅａｔｉｖｅｌｙ．@KEY()↓
◆Ｃ’ｍｏｎ，　ｂｕｙ　ｓｏｍｅ　ｏｆ　ｍｙ　ｊｕｎｋ！↓

;jpn:◆なんにつかえるかは↓
;jpn:　あなたのくふうしだい。@KEY()↓
;jpn:◆ガラクタを　かってってくれ。↓
@!
MSG_SUB_SHOPMES_JUNK1_2;
◆Ｔａｋｅ　ｃａｒｅ，　ｍｏｎ！

;jpn:◆またな！
@KEYNP()
@!
MSG_SUB_SHOPMES_JUNK1_3;
◆Ａ　ｓｃｉｅｎｔｉｆｉｃ　ｍｏｎ　ｍｉｇｈｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｍａｋｅ　ｇｏｏｄ　ａ　ｕｓｅ　ｏｆ　ｔｈｉｓ　ｈｅｒｅ　ｔｈｉｎｇ．．．

;jpn:◆サイエンスかんけいにつよい↓
;jpn:　ひとだったら↓
;jpn:　やくにたてられるんだけどなぁ。
@KEYNP()
@!
MSG_SUB_SHOPMES_JUNK1_4;
◆Ｓｏ，　ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ，　ｍｏｎ？@KEY()
 
;jpn:◆なんにする？@KEY()
@!
MSG_SUB_SHOPMES_JUNK1_5;

◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_6;
◆Ｗｈｏ’ｓ　ｇｏｉｎ’　ｔｏ　ｔａｋｅ　ｉｔ？@KEY()

;jpn:◆だれがもつんだい？@KEY()
@!
MSG_SUB_SHOPMES_JUNK1_7;
◆Ｔｈａｎｋ　ｙｏｕ，　ｍｏｎ．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｅｑｕｉｐ　ｔｈａｔ　ｈｅｒｅ　ｔｈｅｎ？↓

;jpn:◆ありがとう。@KEY()↓
;jpn:◆ここでそうびするかい？↓
@!
MSG_SUB_SHOPMES_JUNK1_8;
◆Ｗｏｕｌｄ　ｙｏｕ　ｂｅ　ｌｉｋｉｎｇ　ｍｅ　ｔｏ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで　かおうか？↓
@!
MSG_SUB_SHOPMES_JUNK1_9;
◆@DSP_NAME(0)　ｃａｎｎｏｔ　ｅｑｕｉｐ　ｔｈｉｓ　ｈｅｒｅ　ｔｈｉｎｇ．　　Ａｒｅ　ｙｏｕ　ｓｔｉｌｌ　ｗｉｌｌｉｎｇ　ｔｏ　ｂｕｙ　ｉｔ？↓
 
;jpn:◆@DSP_NAME(0)にはそうび↓
;jpn:　できないけど　それでもかう？↓
@!
MSG_SUB_SHOPMES_JUNK1_10;
◆Ａｈ，　Ｉ　ｓｅｅ　ｍｏｎ．　　Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ．@KEY()↓

;jpn:◆そうかい　ざんねんだなぁ。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_11;
◆Ａｈ，　ｍｏｎ，　ｙｏｕ　ａｒｅ　ｓｈｏｒｔ　ｏｆ　ｔｈｅ　ｇｒｅｅｎ　ｓｔｕｆｆ，　ｉｆ　ｙｏｕ　ｋｎｏｗ　ｗｈａｔ　Ｉ　ｍｅａｎ，　ｍｏｎ．@KEY()↓

;jpn:◆おかねが　たんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_12;
◆Ｗｅｌｌ，　ｙｏｕ’ｒｅ　ｓｔｒａｉｎｉｎｇ　ｗｉｔｈ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ｎｏｗ．@KEY()↓
◆Ｉ’ｌｌ　ｂｕｙ　ｔｈｅ　ｔｈｉｎｇｓ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ，　ｍｏｎ．↓

;jpn:◆もちものが　いっぱいだよ。@KEY()↓
;jpn:◆いらないにもつを↓
;jpn:　かいとってやろうか？↓
@!
MSG_SUB_SHOPMES_JUNK1_13;
◆Ｗｈａｔ　ｉｓ　ｉｔ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ？@KEY()
;jpn:◆なにを　うるんだい？@KEY()
@!
MSG_SUB_SHOPMES_JUNK1_14;
◆@DSP_GOODS(0)？↓
　　Ｏｈ，　Ｉ　ｃａｎ　ｇｉｖｅ　ｙｏｕ↓
　　ａｂｏｕｔ　@XCHG()＄@DSP_NUM(0)，　ＯＫ？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルでどうだ？↓
@!
MSG_SUB_SHOPMES_JUNK1_15;
◆Ｎｏｔ　ｇｏｉｎ’　ｔｏ　ｇｏ　ｆｏｒ　ｉｔ，　ｅｈ　ｍｏｎ？　　Ｎｏ　ｐｒｏｂｌｅｍ．
@KEY()↓

;jpn:◆そうかい　やめるかい。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_16;
◆Ｂｕｔ　ｌｏｏｋ，　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙ　ｔｈｉｎｇｓ　ｔｏ　ｓｅｌｌ！@KEY()↓

;jpn:◆なんだ　うるものが↓
;jpn:　ないじゃないか。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_17;
◆Ｈｏｌｄ　ｏｎ，　ｍｏｎ．　　Ｗｅ　ｄｏｎ’ｔ　ｃａｒｒｙ　ｔｈａｔ　ｋｉｎｄ　ｏｆ　ｓｔｕｆｆ．@KEY()↓

;jpn:◆おっと　そいつは↓
;jpn:　ひきとれないんだ。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_18;
◆Ｔｈａｎｋｓ　ａ　ｌｏｔ，　ｍｏｎ．@KEY()↓

;jpn:◆ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_19;
◆Ｔｈｅｒｅ　ｙｏｕ　ｇｏ．↓
　　Ｔｈａｎｋｓ　ａ　ｌｏｔ，　ｍｏｎ．@KEY()↓
 
;jpn:◆はい　ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK1_20;
◆Ｉｓ　ｔｈｅｒｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｙｏｕ　ｎｅｅｄ，　ｍｏｎ？↓

;jpn:◆ほかにようじはあるかい？↓
@!
MSG_SUB_SHOPMES_JUNK1_21;
◆Ｌａｙ　ｉｔ　ｏｎ　ｍｅ．↓

;jpn:◆ようはなんだい？↓
@!
MSG_SUB_SHOPMES_JUNK1_22;
◆Ｏｈ，　@DSP_NAME(0)　ｈａｓ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｗｏｎ’ｔ　ｏｎｅ　ｏｆ　ｙｏｕｒ　ｆｒｉｅｎｄｓ　ｃａｒｒｙ　（ｉｔ／ｔｈｅｍ）　ｆｏｒ　ｙｏｕ？↓
 
;jpn:◆あらま　@DSP_NAME(0)は↓
;jpn:　にもつが　いっぱいだよ。@KEY()↓
;jpn:◆ほかのひとが　もつかい？↓
@!
;マジカントの黒ウサギ（ｂｌａｃｋ ｒａｂｂｉｔ ｉｎ Ｍａｇｉｃａｎｔ）
MSG_SUB_SHOPMES_RABBIT_1;
◆Ｈｉ！　　Ｔｈｉｓ　ｓｈｏｐ　ｓｐｅｃｉａｌｉｚｅｓ　ｉｎ　ｐｕｄｄｉｎｇｓ　ａｎｄ　ｐｅｎｄａｎｔｓ！@KEY()↓
◆Ｙｏｕ’ｄ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ｓｏｍｅ，　ｗｏｕｌｄｎ’ｔ　ｙｏｕ？↓
  
;jpn:◆こんにちは↓
;jpn:　プリンとペンダントの↓
;jpn:　おみせだよ。@KEY()↓
;jpn:◆どうするつもり？↓
@!
MSG_SUB_SHOPMES_RABBIT_2;
◆Ｔｈａｎｋ　ｙｏｕ　ｓｏ　ｍｕｃｈ！

;jpn:◆どうもありがとう。
@KEYNP()
@!
MSG_SUB_SHOPMES_RABBIT_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ｂａｃｋ　ｓｏｏｎ！

;jpn:◆またよろしく。
@KEYNP()
@!
MSG_SUB_SHOPMES_RABBIT_4;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｂｕｙ？！@KEY()↓

;jpn:◆なにを　かう？@KEY()
@!
MSG_SUB_SHOPMES_RABBIT_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_6;
◆ＯＫ，　ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？！@KEY()

;jpn:◆だれが　もつんだい？@KEY()
@!
MSG_SUB_SHOPMES_RABBIT_7;
◆Ｏｈ，　ｔｈａｎｋ　ｙｏｕ！　　Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｅｑｕｉｐ　ｉｔ　ｉｎ　ｔｈｅ　ｓｔｏｒｅ？！↓

;jpn:◆ありがとう↓
;jpn:　ここで　そうびしてみる？↓
@!
MSG_SUB_SHOPMES_RABBIT_8;
◆Ｓｈａｌｌ　Ｉ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)を↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで@KEY()↓
;jpn:◆かいあげようか？↓
@!
MSG_SUB_SHOPMES_RABBIT_9;
◆Ｂｕｔ　@DSP_NAME(0)　ｗｉｌｌ　ｎｏｔ　ｂｅ　ａｂｌｅ　ｔｏ　ｅｑｕｉｐ　ｔｈｉｓ？！@KEY()↓
◆Ｄｏ　ｙｏｕ　ｓｔｉｌｌ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｉｔ？！↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　そうびできないけど@KEY()↓
;jpn:◆それでもかいますか？↓
@!
MSG_SUB_SHOPMES_RABBIT_10;
◆Ｐｌｅａｓｅ　ｈｕｒｒｙ　ｂａｃｋ！@KEY()↓

;jpn:◆またよろしくね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_11;
◆Ｓｈａｍｅ　ｏｎ　ｙｏｕ！　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ！@KEY()↓
 
;jpn:◆おかねが　たりないみたいだね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_12;

◆Ｙｏｕ’ｖｅ　ｇｏｔ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ａｌｒｅａｄｙ！@KEY()↓
◆Ｈｏｗ　ａｂｏｕｔ　ｓｅｌｌｉｎｇ　ｍｅ　ｓｏｍｅ　ｏｆ　ｔｈｅ　ｔｈｉｎｇｓ　ｙｏｕ　ｄｏｎ’ｔ　ｎｅｅｄ？！↓

;jpn:◆にもつがいっぱいだね。@KEY()↓
;jpn:◆いらないにもつを　うる？↓
@!
MSG_SUB_SHOPMES_RABBIT_13;
◆ＯＫ，　ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ？！@KEY()

;jpn:◆なにを　うる？@KEY()
@!
MSG_SUB_SHOPMES_RABBIT_14;
◆@DSP_GOODS(0)？@KEY()↓
◆Ｉ　ｃａｎ　ｂｕｙ　ｔｈａｔ↓
　　ｆｏｒ　@XCHG()＄@DSP_NUM(0)．↓
　　Ｉｓ　ｉｔ　ａ　ｄｅａｌ？！@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
;@XCHG()
;jpn:◆@DSP_NUM(0)ドルで↓
;jpn:　かってあげるけど　いいかな？↓
@!
MSG_SUB_SHOPMES_RABBIT_15;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ！@KEY()↓

;jpn:◆また　よろしくね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_16;
◆Ｕｈｈｈ，　ｗｈａｔ’ｓ　ｔｈｅ　ｄｅａｌ？！↓
　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｔｏ　ｓｅｌｌ！@KEY()↓

;jpn:◆うるものが　ないみたいだね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_17;
◆Ｄｏｎ’ｔ　ｍｅａｎ　ｔｏ　ｒａｉｎ　ｏｎ　ｙｏｕｒ　ｐａｒａｄｅ，@KEY()↓
◆ｂｕｔ　ｔｈｅｒｅ’ｓ　ｎｏ　ｐｏｓｓｉｂｌｅ　ｗａｙ　Ｉ　ｃａｎ　ｂｕｙ↓
　　ｙｏｕｒ　@DSP_GOODS(0)！@KEY()↓
 
;jpn:◆わるいけど↓
;jpn:　@DSP_GOODS(0)は↓
;jpn:　ひきとれないんだ。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_18;
◆Ｔｈａｎｋ　ｙｏｕ！@KEY()↓

;jpn:◆ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_19;
◆Ｔｈａｎｋ　ｙｏｕ！@KEY()↓
;jpn:◆ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_RABBIT_20;
◆Ｃａｎ　Ｉ　ｄｏ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｆｏｒ　ｙｏｕ？↓

;jpn:◆ほかにも　ようはある？↓
@!
MSG_SUB_SHOPMES_RABBIT_21;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｄｏ　ｎｏｗ？！↓

;jpn:◆こんどのようは　なに？↓
@!
MSG_SUB_SHOPMES_RABBIT_22;
◆@DSP_NAME(0)　　ｈａｓ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ！@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつが　いっぱいだよ。@KEY()↓
;jpn:◆ほかのひとが　もつかい？↓
@!
;
;ショップタイプＢのメッセージ
;(1,2,3,4,5,6,10,11,12,18,19,20)
;
;パン屋（ｂａｋｅｒｙ）
MSG_SUB_SHOPMES_BAKERY1_1;
◆Ｈｅｌｌｏ．　Ｍａｙ　Ｉ　ｈｅｌｐ　ｙｏｕ？@KEY()↓

;jpn:◆いらっしゃいませ。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_2;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆ありがとうございました。
@KEYNP()
@!
MSG_SUB_SHOPMES_BAKERY1_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　よろしく。
@KEYNP()
@!
MSG_SUB_SHOPMES_BAKERY1_4;
◆Ｗｈａｔ　ｓｈａｌｌ　Ｉ　ｇｅｔ　ｙｏｕ？@KEY()

;jpn:◆なにに　しますか？@KEY()
@!
MSG_SUB_SHOPMES_BAKERY1_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()↓

;jpn:◆どなたが　おもちになりますか？@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆また　よろしく。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_11;
◆Ｉｔ　ｓｅｅｍｓ　ｌｉｋｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかねたりないようですよ。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_12;
◆Ｙｏｕ　ｈａｖｅ　ｓｏ　ｍａｎｙ　ｂｅｌｏｎｇｉｎｇｓ．．．　　Ｙｏｕ　ｊｕｓｔ　ｃａｎ’ｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ！

;jpn:◆にもつ‥‥↓
;jpn:　いっぱいですよ。
@KEYNP()↓
@!
MSG_SUB_SHOPMES_BAKERY1_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_19;

◆Ｔｈａｎｋ　ｙｏｕ　ｓｏ　ｍｕｃｈ．@KEY()↓

;jpn:◆まいどあり！@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY1_20;
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙ　ｏｔｈｅｒ　ｏｒｄｅｒｓ？↓

;jpn:◆ほかに　ごちゅうもんは？↓
@!
MSG_SUB_SHOPMES_BAKERY1_22;
◆@DSP_NAME(0)　ｄｏｅｓｎ’ｔ　ｓｅｅｍ　ｔｏ　ｂｅ　ａｂｌｅ　ｔｏ　ａｃｃｅｐｔ　ａｎｙ　ｍｏｒｅ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは　これいじょう↓
;jpn:　にもつがもてないようです。@KEY()↓
;jpn:◆ほかのかたが↓
;jpn:　おもちに　なりますか？↓
@!
;ハンバーガー店員（ｈｕｍｂｅｒｇｅｒ ｓｈｏｐ）

MSG_SUB_SHOPMES_BURGER_1;
◆Ｈｅｌｌｏ，　ｍａｙ　Ｉ　ｔａｋｅ　ｙｏｕｒ　ｏｒｄｅｒ？↓
　　（ｓｍｉｌｅ，　ｓｍｉｌｅ）@KEY()↓

;jpn:◆いらっしゃいませ。↓
;jpn:　　（ニコニコ）@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_2;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．↓
　　（ｓｍｉｌｅ，　ｓｍｉｌｅ）

;jpn:◆ありがとうございました。↓
;jpn:　　（ニコニコ）
@KEYNP()
@!
MSG_SUB_SHOPMES_BURGER_3;
◆Ｈａｖｅ　ａ　ｎｉｃｅ　ｄａｙ！↓
　　（ｓｍｉｌｅ，　ｓｍｉｌｅ）

;jpn:◆また　よろしくおねがいしまーす。↓
;jpn:　　（ニコニコ）
@KEYNP()
@!
MSG_SUB_SHOPMES_BURGER_4;
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｇｅｔ　ｆｏｒ　ｙｏｕ？@KEY()↓

;jpn:◆なにに　いたしましょうか？@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｔａｋｅ　ｔｈｉｓ？@KEY()↓

;jpn:◆どなたが　おもちになりますか？@KEY()
@!
MSG_SUB_SHOPMES_BURGER_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆またよろしくおねがいします。@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_11;
◆Ｗｈｏｏｐｓ！　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あっ↓
;jpn:　おかねがたりないですね。@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_12;
◆Ｏｏｏｐｓ！　Ｙｏｕ　ａｌｒｅａｄｙ　ｈａｖｅ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．
 
;jpn:◆あっ　おにもつがいっぱいですね。
@KEYNP()
@!
MSG_SUB_SHOPMES_BURGER_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｓｈｏｐｐｉｎ　ｈｅｒｅ．@KEY()↓

;jpn:◆いつも　ありがとうございます！@KEY()↓
@!
MSG_SUB_SHOPMES_BURGER_20;
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙ　ｏｔｈｅｒ　ｏｒｄｅｒｓ？↓

;jpn:◆ほかに　ごちゅうもんは↓
;jpn:　ございますか？↓
@!
MSG_SUB_SHOPMES_BURGER_22;
◆@DSP_NAME(0)　ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｄｏｅｓ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｗａｎｔ　ｔｏ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつがいっぱいのようですね。@KEY()↓
;jpn:◆ほかのひとが↓
;jpn:　おもちになりますか？↓
@!
;アカンベーカリー（Ａｋａｎ－ｂｅ［ｍａｋｉｎｇ ｆａｃｅ］－ｋｅｒｙ）
MSG_SUB_SHOPMES_BAKERY2_1;
◆Ｉ　ｌｉｋｅ　ｔｏ　ｓｅｌｌ　ｍｙ　ｇｏｏｄｉｅｓ　ｏｎ　ｔｈｅ　ｓｔｒｅｅｔ．@KEY()↓
◆Ｓｕｒｅ，　ｆｌｉｅｓ　ｌａｎｄ　ｏｎ　ｔｈｅｍ，　ｂｕｔ　ｉｎ　ｍｙ　ｏｐｉｎｉｏｎ，　ｉｔ　ｍａｋｅｓ　ｔｈｅｍ　ｔａｓｔｅ　ｅｖｅｎ　ｂｅｔｔｅｒ！@KEY()↓
;jpn:◆ろじょうはんばいなので↓
;jpn:　ハエもたかったりして↓
;jpn:　いいあじに　しあがってるよ。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_2;
◆Ｔｈａｎｋｓ　ａ　ｌｏｔ．

;jpn:◆まいどありー。
@KEYNP()
@!
MSG_SUB_SHOPMES_BAKERY2_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆またよろしくね。
@KEYNP()
@!
MSG_SUB_SHOPMES_BAKERY2_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？@KEY()

;jpn:◆なんにしますか？@KEY()
@!
MSG_SUB_SHOPMES_BAKERY2_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？@KEY()↓

;jpn:◆だれがもちますか？@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆またよろしくね。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_11;
◆Ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかねが↓
;jpn:　たりないみたいですよ。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_12;
◆Ｙｏｕ　ａｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｓｅｌｌ　ｓｏｍｅ　ｔｈｉｎｇｓ，　ｏｒ　ｔｈｒｏｗ　ｔｈｅｍ　ａｗａｙ，　ｏｒ　ｊｕｓｔ　ｌｅａｖｅ　ｔｈｅｍ　ｓｏｍｅｗｈｅｒｅ．
 
;jpn:◆にもつがいっぱいですよ。@KEY()↓
;jpn:◆どこかでうるか↓
;jpn:　すてるか　あずけるか↓
;jpn:　してくださいよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_BAKERY2_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆どうもありがとう。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_19;
◆Ｔｈａｎｋｓ．@KEY()↓

;jpn:◆まいどありー。@KEY()↓
@!
MSG_SUB_SHOPMES_BAKERY2_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに　なにか↓
;jpn:　かいますか？↓
@!
MSG_SUB_SHOPMES_BAKERY2_22;
◆@DSP_NAME(0)　ｉｓ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｃａｎ　ａｎｙｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ　ｆｏｒ　ｈｉｍ？↓

;jpn:◆@DSP_NAME(0)くんは↓
;jpn:　にもつがいっぱいですね。@KEY()↓
;jpn:◆ほかのひとが　もちますか？↓
@!
;サマーズレストラン（Ｓｕｍｍｅｒ’ｓ ｒｅｓｔａｕｒａｎｔ）

MSG_SUB_SHOPMES_REST_1;
◆Ｓｏ，　ｗｈｅｒｅ’ｓ　ｙｏｕｒ　ｍｏｍ　ａｎｄ　ｄａｄ？@KEY()↓
◆Ｙｏｕ　ｍｅａｎ　ｙｏｕ　ｋｉｄｓ　ｃａｍｅ　ｉｎ　ｈｅｒｅ　ａｌｌ　ｂｙ　ｙｏｕｒｓｅｌｖｅｓ．．．？@KEY()↓
◆Ｗｅｌｌ，　Ｉ　ｃａｎ　ｍａｋｅ　ｙｏｕｒ　ｏｒｄｅｒ　ｔｏ　ｇｏ．@KEY()↓

;jpn:◆あれ　パパかママは↓
;jpn:　いっしょじゃないのかな？@KEY()↓
;jpn:◆こどもだけで　きたのか‥‥。@WI(20)↓
;jpn:　じゃ　テイクアウトに↓
;jpn:　してあげようね。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_2;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓
◆Ｂｅ　ｃａｒｅｆｕｌ　ｎｏｔ　ｔｏ　ｄｒｏｐ　ｏｒ　ｓｐｉｌｌ　ｉｔ．

;jpn:◆どうもありがとう。@KEY()↓
;jpn:◆おとしたり↓
;jpn:　こぼしたりしないように↓
;jpn:　きをつけるんだよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_REST_3;
◆Ｗｅ　ａｒｅ　ｌｏｏｋｉｎｇ　ｆｏｒｗａｒｄ　ｔｏ　ｓｅｅｉｎｇ　ｙｏｕ　ａｇａｉｎ．

;jpn:◆またの　ごらいてんを↓
;jpn:　おまちしております。
@KEYNP()
@!
MSG_SUB_SHOPMES_REST_4;
◆Ｗｈａｔ　ｃａｎ　Ｉ　ｇｅｔ　ｆｏｒ　ｙｏｕ？@KEY()

;jpn:◆なんにしますか？@KEY()
@!
MSG_SUB_SHOPMES_REST_5;
◆Ｙｏｕ　ｗａｎｔ↓
　　ａ　@DSP_GOODS(0)？@KEY()↓

;◆@DSP_GOODS(0)↓
;jpn:　にするんだね。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_6;
◆Ｗｈｏｓｅ　ｏｒｄｅｒ　ｉｓ　ｔｈｉｓ？@KEY()

;jpn:◆だれの↓
;jpn:　ちゅうもんかな？@KEY()
@!
MSG_SUB_SHOPMES_REST_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆また　よろしくね。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_11;
◆Ｓｏｒｒｙ，　ｂｕｔ　ｙｏｕ　ｈａｖｅｎ’ｔ　ｇｏｔ　ｅｎｏｕｇｈｔ　ｔｏ　ｃｏｖｅｒ　ｔｈｅ　ｃｈｅｃｋ．@KEY()↓

;jpn:◆おかねが↓
;jpn:　たりないみたいだよ。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_12;
◆Ｙｏｕ　ａｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｙｏｕ　ｃａｎ　ｓｅｌｌ　ｙｏｕｒ　ｓｔｕｆｆ，　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ，　ｏｒ　ｊｕｓｔ　ａｂａｎｄｏｎ　ｉｔ．@KEY()↓
◆Ｔｈｅｎ，　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆にもつがいっぱいだね。@KEY()↓
;jpn:◆どこかで　うるか↓
;jpn:　すてるか　あずけるか↓
;jpn:　してから　またおいで。
@KEYNP()
@!
MSG_SUB_SHOPMES_REST_18;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとう。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_19;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとう。@KEY()↓
@!
MSG_SUB_SHOPMES_REST_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｏｒｄｅｒ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかにちゅうもんは↓
;jpn:　あるかな？↓
@!
MSG_SUB_SHOPMES_REST_22;
◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　（ｉｔ／ｔｈｅｍ）　ｆｏｒ　ｈｉｍ？↓

;jpn:◆@DSP_NAME(0)くんは↓
;jpn:　にもつがいっぱいだね。@KEY()↓
;jpn:◆ほかのひとが　もつかい？↓
@!
;フリカケ売り（ｓｅａｓｏｎｉｎｇ ｓｈｏｐ）
MSG_SUB_SHOPMES_FURI1_1;
◆Ｈｅｌｌｏ！　　Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｓｏｍｅ　ｓｅａｓｏｎｉｎｇｓ　ｔｏ　ａｄｄ　ｔｏ　ｙｏｕｒ　ｆｏｏｄｓ　ａｔ　ｍｅａｌ　ｔｉｍｅ？@KEY()↓
◆Ｔｈｅｙ　ａｒｅ　ｒｅａｌｌｙ　ｑｕｉｔｅ　ｍｉｒａｃｕｌｏｕｓ！@KEY()↓
◆Ｗｈｅｎｅｖｅｒ　ｙｏｕ　ｅａｔ　ｓｏｍｅｔｈｉｎｇ，　ｔｈｅ　ｓｅａｓｏｎｉｎｇｓ　ｗｉｌｌ　ｓｐｒｉｎｋｌｅ　ａｕｔｏｍａｔｉｃａｌｌｙ．@KEY()↓
◆Ｔｈｅｙ　ｃｏｍｅ　ｉｎ　ｔｈｅｓｅ　ｃｕｔｅ　ｌｉｔｔｌｅ　ｐａｃｋｅｔｓ　ａｎｄ　ｊａｒｓ．@KEY()↓
  
;jpn:◆こんにちわ！@KEY()↓
;jpn:◆しょくじには　かかせない↓
;jpn:　あじつけ　こもの↓
;jpn:　いかがですか。@KEY()↓
;jpn:◆あらふしぎ！@KEY()↓
;jpn:◆なにかを　たべようとすると↓
;jpn:　じどうてきに　ふりかけちゃう↓
;jpn:　ふしぎなこびんに　はいってるよ。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_2;
◆Ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　こいよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI1_3;
◆Ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　こいよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI1_4;
◆Ｗｈａｔ　ｋｉｎｄ　ｄｏ　ｙｏｕ　ｌｉｋｅ？@KEY()

;jpn:◆なんにする？@KEY()
@!
MSG_SUB_SHOPMES_FURI1_5;
◆Ｙｏｕ　ｗａｎｔ↓
　　ｔｈｅ　@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｔａｋｅ　ｉｔ？@KEY()↓

;jpn:◆だれが　もつんだい？@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_10;
◆Ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆また　こいよ。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_11;
◆Ｏｈ，ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あれ　おかねが↓
;jpn:　たんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_12;
◆Ｙｏｕ　ａｌｒｅａｄｙ　ｈａｖｅ　ｔｈｅ　ｍａｘｉｍｕｍ　ｎｕｍｂｅｒ　ｏｆ　ｔｈｉｎｇｓ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ．@KEY()↓
◆Ｙｏｕ’ｒｅ　ｇｏｉｎｇ　ｔｏ　ｈａｖｅ　ｔｏ　ｓｅｌｌ　ｓｏｍｅ　ｔｈｉｎｇｓ，　ｏｒ　ｊｕｓｔ　ｔｈｒｏｗ　ｔｈｅｍ　ａｗａｙ．@KEY()↓
◆Ｔｈｅｎ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆にもつが　いっぱいだね。@KEY()↓
;jpn:◆どこかで　うるか↓
;jpn:　すてるか　あずけるかして↓
;jpn:　また　こいよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI1_18;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_19;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとうね。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI1_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに↓
;jpn:　なにか　かうかい？↓
@!
MSG_SUB_SHOPMES_FURI1_22;

◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつが　いっぱいで↓
;jpn:　もてないようだね。@KEY()↓
;jpn:◆ほかのひとが　もつかい？↓
@!
;レッドスネーク（ｒｅｄ ｓｎａｋｅ）

MSG_SUB_SHOPMES_SNAKE_1;
◆Ｈｉｓｓｓｓ，　Ｉ’ｍ　Ｒｅｄ　Ｓｎａｋｅ．．．　ｃｏｍｅ　ｏｎ　ｉｎ！@KEY()↓
◆Ｋｉｓｓｓｓ　ｏｆ　Ｆｉｒｅ！　Ａｒｍｐｉｔ　ｈａｉｒ　ｆｅｒｔｉｌｉｚｅｒ！↓
　　Ｙｅｓｓｓｓｓｓｓ！@KEY()↓

;jpn:◆ハイ　レッドスネーク　カモン！↓
;jpn:　キッス　オブ　ファイア↓
;jpn:　わきげのエサ‥‥はくしゅー！@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_2;
◆Ｙｅｓｓｓｓｓ，　ｙｏｕ　ｇｏｔ　ｓｓｓｓｏｍｅ　ｇｏｏｄ　ｓｓｓｓｔｕｆｆ！

;jpn:◆おきゃくさん↓
;jpn:　いいものかったね。
@KEYNP()
@!
MSG_SUB_SHOPMES_SNAKE_3;
◆Ｏｈ，　ｎｏ．．．@KEY()↓
◆Ｙｏｕ　ｄｉｓｓｓｓａｐｐｏｉｎｔ　ｍｅ．．．

;jpn:◆おきゃくさん‥‥↓
;jpn:　がっかりだな‥‥。
@KEYNP()
@!
MSG_SUB_SHOPMES_SNAKE_4;
◆Ｗｈａｔ　ｉｓｓｓｓ　ｉｔ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ？@KEY()

;jpn:◆おきゃくさん　なにをかう？@KEY()
@!
MSG_SUB_SHOPMES_SNAKE_5;
◆Ｈｉｓｓｓｓｓ，　ｈｅｒｅ　ｉｓｓｓｓｓ↓
　　ｙｏｕｒ　@DSP_GOODS(0)！@KEY()↓

;jpn:◆はいよ！↓
;jpn:　@DSP_GOODS(0)いっちょう！@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_6;
◆Ｗｈｏ　ｉｓｓｓｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓｓｓｓｓ？@KEY()

;jpn:◆だれがもつんだい？@KEY()
@!
MSG_SUB_SHOPMES_SNAKE_10;
◆Ｏｈ，　ｎｏ．．．@KEY()↓
◆Ｙｏｕ　ｄｉｓｓｓｓａｐｐｏｉｎｔ　ｍｅ．．．@KEY()↓

;jpn:◆おきゃくさん‥‥↓
;jpn:　がっかりだな‥‥。@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_11;
◆Ｏｈ，　ｎｏ．．．@KEY()↓
◆Ｙｏｕ　ｄｉｓｓｓｓａｐｐｏｉｎｔ　ｍｅ．．．　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．．．@KEY()↓
 
;jpn:◆おきゃくさん‥‥↓
;jpn:　がっかりだな‥‥↓
;jpn:　おかねがたりないですよ。@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_12;
◆Ｙｏｕ　ａｒｅ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｓｓｓｓｔｕｆｆ@KEY()↓
◆Ｓｓｓｓｅｌｌ　ｉｔ，　ｏｒ　ｔｏｓｓｓｓ　ｉｔ，　ａｎｄ　ｃｏｍｅ　ａｇａｉｎ！

;jpn:◆うーん↓
;jpn:　にもつがいっぱいだね。@KEY()↓
;jpn:◆どこかで　うるか↓
;jpn:　すてるか　あずけるかして↓
;jpn:　またきてちょー。
@KEYNP()
@!
MSG_SUB_SHOPMES_SNAKE_18;
◆Ｔｈａｎｋｓｓｓｓｓｓ！@KEY()↓

;jpn:◆まいどありっ！@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_19;
◆Ｔｈａｎｋｓｓｓｓｓ！@KEY()↓

;jpn:◆まいどありっ！@KEY()↓
@!
MSG_SUB_SHOPMES_SNAKE_20;
◆Ｃａｎ　Ｉ　ｄｏ　ａｎｙｔｈｉｎｇ　ｅｌｓｓｓｓｅ　ｆｏｒ　ｙｏｕ？↓

;jpn:◆ほかにごようは？↓
@!
MSG_SUB_SHOPMES_SNAKE_22;
◆Ｙｏｕ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓｓｓｓ　ｔｏ　ｃａｒｒｙ．@KEY()↓
◆Ｃａｎ　ａｎｙｏｎｅ　ｅｌｓｓｓｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆おきゃくさん↓
;jpn:　もちものがいっぱいだよ。@KEY()↓
;jpn:◆ほかのひとがもつかい？↓
@!
;パンクジャンク（ｐｕｎｋ ｊｕｎｋ）

MSG_SUB_SHOPMES_JUNK2_1;
◆Ｃ’ｍｏｎ　ｉｎ！↓
　　Ｗｅ’ｖｅ　ｇｏｔ　ｔｈｅ　ｇｏｏｄｓ，　ｇ！@KEY()↓

;jpn:◆オーケー　ウェルカム！↓
;jpn:　いいものあるよ。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_2;
◆Ｔｈａｎｋｓ　ａ　ｌｏｔ，　ｂｒｏ！

;jpn:◆センキュー　センキュー↓
;jpn:　ありがとよっ。
@KEYNP()
@!
MSG_SUB_SHOPMES_JUNK2_3;
◆Ｍｏｄ－ｂｏｙ　Ｊｅｒｋ！↓
　　Ｙｏｕ　ｃａｎ’ｔ　ｄｏ　ｍｅ　ｌｉｋｅ　ｔｈａｔ！
  
;jpn:◆ガッデム！↓
;jpn:　そりゃあないぜ　あんちゃん！
@KEYNP()
@!
MSG_SUB_SHOPMES_JUNK2_4;
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｌｏｏｋｉｎｇ　ｆｏｒ？！@KEY()↓

;jpn:◆ワット　ドゥー　ユー　ウォント↓
;jpn:　なんに　するんだ　あんちゃん？@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_5;
◆Ｏｋａｙ，　ｍａｎ．　　Ｙｏｕ　ｗａｎｔ↓
　　ｔｈｅ　@DSP_GOODS(0)？@KEY()↓

;jpn:◆オーケー　オーケー↓
;jpn:　@DSP_GOODS(0)だな。@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_6;
◆Ｈｅｙ　ｇｕｙｓ，　ｗｈｏ’ｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？@KEY()↓

;jpn:◆ヘイ　ボーイズ！↓
;jpn:　だれが　もつんだい？@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_10;
◆Ｉ’ｍ　ｗｉｔｈ　ｙｏｕ．↓
　　Ｌｏｏｋｉｎ’　ｆｏｒ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？@KEY()↓

;jpn:◆オーケー　わかった↓
;jpn:　ほかに　ようはあるかい？@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_11;
◆Ｈｅｙ　ｈｏｍｉｅｅ！↓
　　Ｙｏｕ　ａｉｎ’ｔ　ｇｏｔ　ｔｈｅ　ｄｏｕｇｈ　ｆｏｒ　ｔｈｉｓ　ｐｕｒｃｈａｓｅ！@KEY()

;jpn:◆オウ　マイ　ゴッド！↓
;jpn:　マネー　たんないよ。@KEY()
@!
MSG_SUB_SHOPMES_JUNK2_12;
◆Ｍｏｓｔ　ｕｎｆｏｒｔｕｎａｔｅｌｙ　ｆｏｒ　ｙｏｕ，↓
　　ｙｏｕ’ｒｅ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．

;jpn:◆オウ　なんてこったい！↓
;jpn:　にもつ　もちすぎだぜ。
@KEYNP()
@!
MSG_SUB_SHOPMES_JUNK2_18;
◆Ｔｈａｎｋ　ｙｏｕ，ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆センキュー　センキュー↓
;jpn:　ありがとよ！@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_19;
◆Ｔｈａｎｋ　ｙｏｕ，ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆センキュー　センキュー↓
;jpn:　まいどあり！@KEY()↓
@!
MSG_SUB_SHOPMES_JUNK2_20;
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかにも　ようはあるかい？↓
@!
MSG_SUB_SHOPMES_JUNK2_22;
◆Ｓｏｒｒｙ，　ｂｕｄｄｙ！↓
　　@DSP_NAME(0)　ｈａｓ　ｇｏｔ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｏｎｅ　ｏｆ　ｙｏｕ　ｏｔｈｅｒ　ｇｕｙｓ　ｗａｎｔ　ｔｏ　ｈａｕｌ　ｉｔ　ｆｏｒ　ｈｉｍ？↓

;jpn:◆オウ　ノー！↓
;jpn:　@DSP_NAME(0)は↓
;jpn:　にもつが　いっぱいだぜ。@KEY()↓
;jpn:◆ほかのやつが　もつかい？↓
@!
;墓守（ｇｒａｖｅ ｙａｒｄ ｋｅｅｐｅｒ）

MSG_SUB_SHOPMES_GRAVE_1;
;◆あんたたち　おハカのしたを↓
;　ぬけてきたのか？！@KEY()↓
;◆むてっぽうなことするねぇ。@WI(20)↓
;　‥‥ハラもへったことだろう。↓
;◆あ@WI(15)　ちょうどいい。@WI(20)↓
;　おじさん　たべものをもってたよ。@KEY()↓

◆Ｙｏｕ　ｍｕｓｔ　ｈａｖｅ　ａ　ｌｏｎｇ，　ｔｏｕｇｈ　ｒｏａｄ　ａｈｅａｄ　ｏｆ　ｙｏｕ，　ｄｏ　ｙｏｕ　ｎｏｔ？@KEY()↓
◆Ｎｏ，　ｔｈｅｒｅ　ｉｓ　ｎｏ　ｎｅｅｄ　ｔｏ　ｅｘｐｌａｉｎ．　　Ｉ　ａｌｒｅａｄｙ　ｋｎｏｗ．．．　ｙｏｕ　ｍｕｓｔ　ｂｅ　ｈｕｎｇｒｙ．@KEY()↓
◆Ｔｈｉｓ　ｉｓ　ｇｏｏｄ　ｔｉｍｉｎｇ　ｆｏｒ　ｙｏｕ．　　Ｉ　ｈａｐｐｅｎ　ｔｏ　ｂｅ　ｃａｒｒｙｉｎｇ　ｓｏｍｅｔｈｉｎｇ　ｔｏ　ｅａｔ．@KEY()↓

;jpn:◆あんたたち　いろいろ↓
;jpn:　たいへんみたいだね。@KEY()↓
;jpn:◆いや　いわなくてもわかる。↓
;jpn:　‥‥ハラもへったことだろう。@KEY()↓
;jpn:◆あ　ちょうどいい。↓
;jpn:　おじさん　たべものをもってたよ。@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_2;
◆Ｉｆ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｆｕｌｌｙ　ｒｅｃｏｖｅｒ，　ｔｈｅｒｅ　ｉｓ　ａ　ｖｉｌｌａｇｅ　ｆｕｌｌ　ｏｆ．．．@KEY()↓
◆ｉｎｔｅｒｅｓｔｉｎｇ　ｐｅｏｐｌｅ．．．　ｊｕｓｔ　ａｈｅａｄ．　　Ｇｏ　ｔｈｅｒｅ　ａｎｄ　ｔａｋｅ　ａ　ｇｏｏｄ　ｒｅｓｔ．@KEY()↓
◆Ｉ　ｈａｖｅ　ｈｅａｒｄ　ｔｈａｔ　ｔｈｅ　ｎａｍｅ　ｏｆ　ｔｈｉｓ　ｖｉｌｌａｇｅ　ｉｓ　Ｓａｔｕｒｎ　Ｖａｌｌｅｙ，↓
◆ｂｕｔ　ｉｔ　ｃａｎｎｏｔ　ｂｅ　ｆｏｕｎｄ　ｏｎ　ａｎｙ　ｍａｐ．@KEY()↓
◆Ｉ　ｅｎｊｏｙ　ｈｅｌｐｉｎｇ　ｔｈｏｓｅ　ｗｈｏ　ａｒｅ　ｉｎ　ｔｒｏｕｂｌｅ．@KEY()↓
◆．．．ｔｈｏｕｇｈ　Ｉ　ｃｈａｒｇｅ　ｔｈｅｍ　ｆｏｒ　ｍｙ　ｔｒｏｕｂｌｅ．

;jpn:◆ぜんめんてきに↓
;jpn:　つかれを　いやしたいなら@KEY()↓
;jpn:◆このさきに　おもろいひとたちの↓
;jpn:　むらがあるから↓
;jpn:　そっちで　やすめばいい。@KEY()↓
;jpn:◆そのむらのなまえは↓
;jpn:　サターンバレーというらしいけど↓
;jpn:　ちずには　のっていないんだよ。@KEY()↓
;jpn:◆おじさんは↓
;jpn:　こまったひとたちを　たすけるのが↓
;jpn:　ほんとに　すきなんだ。@KEY()↓
;jpn:◆‥‥おかねは　とるけどね。
@KEYNP()
@!
MSG_SUB_SHOPMES_GRAVE_3;
◆Ｐｌｅａｓｅ，　ｂｙ　ａｌｌ　ｍｅａｎｓ，　ｃｏｍｅ　ａｇａｉｎ．　　．．．　Ａｈ，　Ｉ　ｊｕｓｔ　ｒｅｍｅｍｂｅｒｅｄ．．．@KEY()↓
◆Ｔｈｅｒｅ　ｉｓ　ａ　ｖｉｌｌａｇｅ　ｗｉｔｈ　ｍａｎｙ．．．　ｉｎｔｅｒｅｓｔｉｎｇ　ｐｅｏｐｌｅ．．．　ｊｕｓｔ　ａｈｅａｄ．@KEY()↓
◆Ｙｏｕ　ｓｈｏｕｌｄ　ｇｏ　ｔｈｅｒｅ　ａｎｄ　ｖｉｓｉｔ．@KEY()↓
◆Ｉ　ｈｅａｒｄ　ｔｈａｔ　ｔｈｅ　ｎａｍｅ　ｏｆ　ｔｈｅ　ｖｉｌｌａｇｅ　ｉｓ　Ｓａｔｕｒｎ　Ｖａｌｌｅｙ，@KEY()↓
◆ｂｕｔ　ｉｔ　ｃａｎｎｏｔ　ｂｅ　ｆｏｕｎｄ　ｏｎ　ａｎｙ　ｍａｐ．
  
;jpn:◆また　よろしくね。↓
;jpn:　‥‥あ　そうそう@KEY()↓
;jpn:◆このさきに　おもろいひとたちの↓
;jpn:　むらがあるから↓
;jpn:　たずねてみると　いい。@KEY()↓
;jpn:◆そのむらのなまえは↓
;jpn:　サターンバレーというらしいけど↓
;jpn:　ちずには　のっていないんだよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_GRAVE_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？@KEY()

;jpn:◆なんにする？@KEY()
@!
MSG_SUB_SHOPMES_GRAVE_5;
◆Ｙｏｕ　ｗａｎｔ↓
　　ｔｈｅ　@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_6;

◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？@KEY()↓

;jpn:◆だれがもつんだい？@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_10;

◆Ｉ　ｓｅｅ．　Ｔｈａｔ’ｓ．．．　ｔｏｏ　ｂａｄ．@KEY()

;jpn:◆そうかい　ざんねんだな。@KEY()
@!
MSG_SUB_SHOPMES_GRAVE_11;
◆Ｙｏｕ．．．ｄｏ　ｎｏ　ｓｅｅｍ　ｔｏ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかね‥‥↓
;jpn:　ないみたいだね。@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_12;
◆Ｙｏｕ’ｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，　ｏｒ　ｊｕｓｔ　ａｂａｎｄｏｎ　ｓｏｍｅｔｈｉｎｇ，　ａｎｄ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆きみたちは　にもつが↓
;jpn:　いっぱいだね。@KEY()↓
;jpn:◆どこかで　うるか↓
;jpn:　すてるか　あずけるかして↓
;jpn:　また　きてね。
@KEYNP()
@!
MSG_SUB_SHOPMES_GRAVE_18;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとね。@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_19;
◆Ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとね。@KEY()↓
@!
MSG_SUB_SHOPMES_GRAVE_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに↓
;jpn:　なんか　かう？↓
@!
MSG_SUB_SHOPMES_GRAVE_22;
◆@DSP_NAME(0)　ｈａｓ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｃａｎ　ａｎｙｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)ちゃんは↓
;jpn:　にもつが　いっぱいだね。@KEY()↓
;jpn:◆ほかの　だれかが　もつかい？↓
@!
;スカラビ食品（Ｓｃａｒａｂｉ ｇｒｏｃｅｒ）
MSG_SUB_SHOPMES_SKFOOD_1;
◆Ｈｅｌｌｏ　ｔｈｅｒｅ！　　Ｗｅｌｃｏｍｅ　ｔｏ　ｍｙ　ｈｕｍｂｌｅ　ｓｈｏｐ！@KEY()↓
◆Ｈｏｗ　ａｂｏｕｔ　ｓｏｍｅ　ｏｆ　ｏｕｒ　ｆａｍｏｕｓ　Ｓｃａｒａｂａ　ｄｅｌｉｃａｃｉｅｓ？@KEY()↓

;jpn:◆はい　いらっしゃい！↓
;jpn:　とうてんじまんの↓
;jpn:　スカラビちんみ！@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_2;
◆Ｏｈ　ｗｅｌｌ，　ｐｌｅａｓｅ　ｆｉｎｄ　ａ　ｗａｙ　ｔｏ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆じゃあ　おげんきでー。
@KEYNP()
@!
MSG_SUB_SHOPMES_SKFOOD_3;
◆Ｔｈｅ　ｓｕｎ　ｉｓ　ｍｅｒｃｉｌｅｓｓ　ｔｏｄａｙ，　ｓｏ　ｐｌｅａｓｅ　ｔａｋｅ　ｃａｒｅ　ｏｆ　ｙｏｕｒｓｅｌｆ．
 
;jpn:◆ひざしがきついから↓
;jpn:　カラダにきをつけてな。
@KEYNP()
@!
MSG_SUB_SHOPMES_SKFOOD_4;
◆Ｗｅ　ｃａｒｒｙ　ａ　ｖａｒｉｅｔｙ　ｏｆ　ｔｈｉｎｇｓ．　　Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？@KEY()

;jpn:◆いろいろあるよ↓
;jpn:　なんにする？@KEY()
@!
MSG_SUB_SHOPMES_SKFOOD_5;
◆Ｈｅｒｅ　ｙｏｕ　ｇｏ！↓
　　Ｙｏｕｒ　@DSP_GOODS(0)！@KEY()↓
 
;jpn:◆@DSP_GOODS(0)いっちょう！@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｔｈｉｓ？@KEY()

;jpn:◆だれが　もつんだい？@KEY()
@!
MSG_SUB_SHOPMES_SKFOOD_10;
◆Ｏｈ？　　Ｙｏｕ’ｒｅ　ｎｏｔ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ　ａｆｔｅｒ　ａｌｌ？　　Ｉｓ　ｔｈａｔ　ｒｉｇｈｔ？@KEY()↓

;jpn:◆えっ　やめんの？↓
;jpn:　やめんのかー。@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_11;
◆Ｏｈ，　ｍｙ！　　Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓
 
;jpn:◆あらら↓
;jpn:　おかねがたんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_12;
◆Ｆｏｒ　ｈｅａｖｅｎ’ｓ　ｓａｋｅ！　　Ｙｏｕ’ｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，　ｏｒ　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ，　ａｎｄ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆ガガーン！↓
;jpn:　にもつがいっぱいだよ。@KEY()↓
;jpn:◆うるか　すてるか↓
;jpn:　あずけるかして↓
;jpn:　また　きてよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_SKFOOD_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ，　ｖｅｒｙ　ｍｕｃｈ！@KEY()↓
;jpn:◆あーりがーとさーん。@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_19;
◆Ｔｈａｎｋｓ　ｆｏｒ　ｓｈｏｐｐｉｎｇ　ｈｅｒｅ！@KEY()↓

;jpn:◆まいどありー。@KEY()↓
@!
MSG_SUB_SHOPMES_SKFOOD_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに　なんか　かうかい？↓
@!
MSG_SUB_SHOPMES_SKFOOD_22;
◆Ｆｏｒ　ｈｅａｖｅｎ’ｓ　ｓａｋｅ！↓
　　@DSP_NAME(0)　ａｌｒｅａｄｙ　ｈａｓ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ！@KEY()↓
◆Ｃａｎ　ａｎｙｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆ガガーン！↓
;jpn:　@DSP_NAME(0)ちゃんは↓
;jpn:　にもつもちきれないみたいだよ。@KEY()↓
;jpn:◆ほかのだれかが　もつかい？↓
@!
;ドコドコ砂漠の弁当売り（ｂｅｎｔｏ ｖｅｎｄｏｒ ｉｎ Ｄｏｋｏ Ｄｏｋｏ　ｄｅｓｅｒｔ）
MSG_SUB_SHOPMES_BENTO_1
◆Ｏｕｔ　ｗａｌｋｉｎｇ　ｉｎ　ｔｈｅ　ｄｅｓｅｒｔ　ｍｕｓｔ　ｍａｋｅ　ｙｏｕ　ｖｅｒｙ　ｈｕｎｇｒｙ　ａｎｄ　ｔｈｉｒｓｔｙ！@KEY()↓
  
;jpn:◆さばくを　あるいて↓
;jpn:　おなかも　へったろ？↓
;jpn:　のども　かわいたろ？@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_2;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．

;jpn:◆ありがとうございました。
@KEYNP()
@!
MSG_SUB_SHOPMES_BENTO_3;
◆Ｓｏ，　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ？　

;jpn:◆なんだ　ひやかしかい。
@KEYNP()
@!
MSG_SUB_SHOPMES_BENTO_4;
◆Ｗｈａｔ　ｄｏ　ｙｏｕ　ｗａｎｔ？@KEY()↓

;jpn:◆なんにするんだい？@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_5;
◆Ｙｏｕ　ｗａｎｔ↓
　　ｔｈｅ　@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)だね。@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれが　もつ？@KEY()
@!
MSG_SUB_SHOPMES_BENTO_10;
◆Ｏｈ？　　Ｓｏ　ｙｏｕ　ｃｈａｎｇｅｄ　ｙｏｕｒ　ｍｉｎｄ　ａｎｄ　ｄｏｎ’ｔ　ｗａｎｔ　ａｎｙｔｈｉｎｇ　ａｆｔｅｒ　ａｌｌ？@KEY()↓

;jpn:◆なあんだ。↓
;jpn:　かうのをやめるのかい。@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_11;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかね　たんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_12;
◆Ｙｏｕ’ｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍｕｃｈ　ｓｔｕｆｆ．@KEY()↓
◆Ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，　ｏｒ　ｊｕｓｔ　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ，　ａｎｄ　ｔｈｅｎ　ｃｏｍｅ　ｂａｃｋ　ｔｏ　ｓｅｅ　ｍｅ．

;jpn:◆にもつがいっぱいだよ。↓
;jpn:　うるか　すてるか↓
;jpn:　あずけるかしてきなよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_BENTO_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございました。@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_19;
◆Ｔｈａｎｋｓ　ａ　ｌｏｔ．@KEY()↓

;jpn:◆まいど　あり。@KEY()↓
@!
MSG_SUB_SHOPMES_BENTO_20;
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに　ようはあるかい？↓
@!
MSG_SUB_SHOPMES_BENTO_22;
◆@DSP_NAME(0)　ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｈｅ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓　

;jpn:◆@DSP_NAME(0)くんは↓
;jpn:　にもつがいっぱいで↓
;jpn:　もてないみたいだよ。@KEY()↓
;jpn:◆ほかのだれかが　もつかい？↓
@!
;ランマのお粥専門店
;（Ｒａｎｍａ’ｓ　ｒｉｃｅ　ｇｒｕｅｌ　ｓｐｅｃｉａｌｉｔｙ　ｓｈｏｐ）
MSG_SUB_SHOPMES_OKAYU_1
◆Ｗｅ　ｓｅｒｖｅ　ｗａｔｅｒ，　ｒｉｃｅ　ｇｒｕｅｌ　ａｎｄ　ｔｈｏｓｅ　ｓｏｒｔｓ　ｏｆ　ｔｈｉｎｇｓ．@KEY()↓

;jpn:◆みずとか　おかゆなどが↓
;jpn:　あります。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_2;
◆Ｇｏｏｄ－ｂｙｅ．

;jpn:◆さようなら。
@KEYNP()
@!
MSG_SUB_SHOPMES_OKAYU_3;
◆Ｇｏｏｄ－ｂｙｅ．　　Ｐｌｅａｓｅ　ｔａｋｅ　ｃａｒｅ．

;jpn:◆さようなら↓
;jpn:　おきをつけて。
@KEYNP()
@!
MSG_SUB_SHOPMES_OKAYU_4
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｄｏ？@KEY()

;jpn:◆どうしますか？@KEY()
@!
MSG_SUB_SHOPMES_OKAYU_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_6;
◆Ｗｈｏ　ｉｓ　　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれが　おもちになりますか？@KEY()
@!
MSG_SUB_SHOPMES_OKAYU_10;
◆Ｙｏｕ　ａｒｅ　ｎｏｔ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ｏｕｒ　ｍｅｎｕ？　　Ｉ　ｓｅｅ．@KEY()↓

;jpn:◆そうですか。↓
;jpn:　かうのをやめますか。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_11;
◆Ｙｏｕ　ｄｏ　ｎｏｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかねがたりませんね。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_12;
◆Ｙｏｕ’ｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，　ｏｒ　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ，@KEY()↓
◆ｏｒ　ｊｕｓｔ　ｌｅａｖｅ　ｓｏｍｅｔｈｉｎｇ　ｓｏｍｅｗｈｅｒｅ，　ａｎｄ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆にもつがいっぱいです。@KEY()↓
;jpn:◆うるか　すてるか↓
;jpn:　あずけるかして↓
;jpn:　また　きてください。
@KEYNP()
@!
MSG_SUB_SHOPMES_OKAYU_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございました。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございました。@KEY()↓
@!
MSG_SUB_SHOPMES_OKAYU_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかにも↓
;jpn:　なにかかいますか？↓
@!
MSG_SUB_SHOPMES_OKAYU_22;
◆@DSP_NAME(0)　ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｈｅ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつがいっぱいで↓
;jpn:　もてないみたいですね。@KEY()↓
;jpn:◆ほかのだれかが　もちますか？↓
@!
;ホテル・ダークムーンの回復グッズ売り
;（Ｒｅｃｏｖｅｒｙ　ｇｏｏｄｓ　ｖｅｎｄｏｒ　ｉｎ　Ｈｏｔｅｌ　Ｄａｒｋ↓
;　　Ｍｏｏｎ）

MSG_SUB_SHOPMES_MOON_1;
◆Ｈｉ，　ｈｏｗ　ａｒｅ　ｙｏｕ　ｄｏｉｎｇ？　　Ｆｒｏｍ　ｔｈｅ　ｌｏｏｋ　ｏｆ　ｔｈｉｎｇｓ，@KEY()↓
◆Ｉ　ｗｏｕｌｄ　ｓａｙ，　ｎｏｔ　ｓｏ　ｇｏｏｄ．@KEY()↓

;jpn:◆どうだい　ちょうしは？↓
;jpn:　よくは　なさそうだな。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_2;
◆Ｓｅｅ　ｙａ！

;jpn:◆じゃあな。
@KEYNP()
@!
MSG_SUB_SHOPMES_MOON_3;
◆Ｓｅｅ　ｙａ！

;jpn:◆じゃあな。
@KEYNP()
@!
MSG_SUB_SHOPMES_MOON_4;
◆Ｄｏ　ｙｏｕ　ｎｅｅｄ　ａｎｙｔｈｉｎｇ？@KEY()

;jpn:◆なにか　いるかい？@KEY()
@!
MSG_SUB_SHOPMES_MOON_5;
◆Ｔｈｅ　@DSP_GOODS(0)．．．．．？@KEY()↓

;jpn:◆@DSP_GOODS(0)‥‥ね。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれが　もつんだい？@KEY()
@!
MSG_SUB_SHOPMES_MOON_10;
◆Ｓｏ　ｙｏｕ’ｒｅ　ｓａｙｉｎｇ　ｙｏｕ　ｄｏｎ’ｔ　ｗａｎｔ　ｉｔ　ａｆｔｅｒ　ａｌｌ．．．？@KEY()↓

;jpn:◆‥‥いらないわけね。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_11;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆おかねがたんないよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_12;
◆Ｙｏｕ’ｒｅ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．

;jpn:◆にもつがいっぱいだよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_MOON_18;
◆Ｔｈａｎｋｓ．@KEY()↓

;jpn:◆ありがとよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_19;
◆Ｔｈａｎｋｓ．@KEY()↓

;jpn:◆ありがとよ。@KEY()↓
@!
MSG_SUB_SHOPMES_MOON_20;
◆Ａｒｅ　ｙｏｕ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに　なんか　かうわけ？↓
@!
MSG_SUB_SHOPMES_MOON_22;
◆@DSP_NAME(0)ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｈｅ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつがいっぱいで↓
;jpn:　もてないよ。@KEY()↓
;jpn:◆ほかのだれかが　もつかい？↓
@!
;サマーズのマジックタルト売り（Ｍａｇｉｇ ｔａｒｔ ｖｅｎｄｏｒ ｉｎ 
;Ｓｕｍｍｅｒｓ）
MSG_SUB_SHOPMES_WIFE_1;
◆Ｉ　ｃａｎ　ｎｏ　ｌｏｎｇｅｒ　ｍａｋｅ　Ｍａｇｉｃ　Ｃａｋｅｓ．．．@KEY()↓
◆Ｂｕｔ　ｉｔ　ｄｏｅｓｎ’ｔ　ｍａｔｔｅｒ　ｂｅｃａｕｓｅ　ｎｏｗ　Ｉ’ｍ　ｓｅｌｌｉｎｇ　Ｍａｇｉｃ　Ｔａｒｔｓ，@KEY()↓
◆ｗｈｉｃｈ　ｔａｓｔｅ　ｅｖｅｎ　ｂｅｔｔｅｒ　ｔｈａｎ　Ｍａｇｉｃ　Ｃａｋｅｓ！@KEY()↓

;jpn:◆マジックケーキは↓
;jpn:　もうつくれないけど↓
;jpn:　おいしさなら　それいじょうの‥‥@KEY()↓
;jpn:◆「マジックタルト」を↓
;jpn:　うってるわ。@KEY()↓
@!
MSG_SUB_SHOPMES_WIFE_2;
◆Ｙｏｕ　ｒｅｍｉｎｄｅｄ　ｍｅ　ｈｏｗ　ｍｕｃｈ　Ｉ　ｌｏｖｅ　ｔｈｉｓ　ｊｏｂ！

;jpn:◆しごとの　たのしさを↓
;jpn:　あんたたちが↓
;jpn:　おもいださせてくれたわ。
@KEYNP()
@!
MSG_SUB_SHOPMES_WIFE_3;
◆Ｙｏｕ　ｒｅｍｉｎｄｅｄ　ｍｅ　ｈｏｗ　ｍｕｃｈ　Ｉ　ｌｏｖｅ　ｔｈｉｓ　ｊｏｂ！

;jpn:◆しごとの　たのしさを↓
;jpn:　あんたたちが↓
;jpn:　おもいださせてくれたわ。
@KEYNP()
@!
MSG_SUB_SHOPMES_WIFE_4;
◆Ｉ　ｏｎｌｙ　ｈａｖｅ　ｔｈｉｓ．．．．．．．．@KEY()↓

;jpn:◆これしかうってないけれど‥‥。@KEY()↓
@!
MSG_SUB_SHOPMES_WIFE_5;
◆Ｙｏｕ　ａｒｅ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ↓
　　ｍｙ　@DSP_GOODS(0)？@KEY()↓

;◆@DSP_GOODS(0)↓
;jpn:　かってくれるのね。@KEY()↓
@!
MSG_SUB_SHOPMES_WIFE_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆どなたが　おもちになるの？@KEY()
@!
MSG_SUB_SHOPMES_WIFE_10;
◆Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ．

;jpn:◆それは　ざんねんだわ‥‥。
@KEYNP()
@!
MSG_SUB_SHOPMES_WIFE_11;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆おかねが　たりないわね。
@KEYNP()
@!
MSG_SUB_SHOPMES_WIFE_12;
◆Ｙｏｕ　ａｒｅ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃｏｍｅ　ａｇａｉｎ　ｗｈｅｎ　ｙｏｕ　ｒｅｄｕｃｅ　ｔｈｅ　ｎｕｍｂｅｒ　ｏｆ　ｔｈｉｎｇｓ　ｙｏｕ　ａｒｅ　ｃａｒｒｉｎｇ．
 
;jpn:◆もちものが　いっぱいよ↓
;jpn:　にもつを　へらしてから↓
;jpn:　またきてね。
@KEYNP()
@!
MSG_SUB_SHOPMES_WIFE_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆どうも　ありがとう。@KEY()↓
@!
MSG_SUB_SHOPMES_WIFE_19;
◆Ｔｈａｎｋ　ｙｏｕ　ａｇａｉｎ．@KEY()↓

;jpn:◆いつも　ありがとう。@KEY()↓
@!
MSG_SUB_SHOPMES_WIFE_20;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかにも　なにかかう？↓
@!
MSG_SUB_SHOPMES_WIFE_22;
◆@DSP_NAME(0)ｓｅｅｍｓ　ｔｏ　ｈａｖｅ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｈｅ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　もちものが　いっぱいみたいよ。@KEY()↓
;jpn:◆ほかのだれかが　もつのかしら？↓
@!
;スカラビの水売り（ｗａｔｅｒ ｖｅｎｄｏｒ ｉｎ Ｓｃａｒａｂｉ）
MSG_SUB_SHOPMES_WATER_1;
◆Ｉ　ｓｅｌｌ　ｗａｔｅｒ　ｔｏ　ｔｈｏｓｅ　ｗｈｏ　ａｒｅ　ｔｈｉｒｓｔｙ．@KEY()↓

;jpn:◆のどの　かわいたたびびとに↓
;jpn:　みずを　うってあげましょう。@KEY()↓
@!
MSG_SUB_SHOPMES_WATER_2;
◆Ｔｈｅ　ｐｒｉｃｅ　ｏｆ　ｔｈｉｎｇｓ　ｉｓ　ｄｅｔｅｒｍｉｎｅｄ　ｂｙ　ｔｈｅ　ｒｅｌａｔｉｏｎｓｈｉｐ　ｂｅｔｗｅｅｎ　ｓｕｐｐｌｙ　ａｎｄ　ｄｅｍａｎｄ．@KEY()↓
◆Ｙｏｕ　ｋｉｄｓ　ａｒｅ　ｐｒｅｔｔｙ　ｓｈａｒｐ　ｔｏ　ｂｅ　ａｂｌｅ　ｔｏ　ｕｎｄｅｒｓｔａｎｄ　ｔｈｉｓ　ｔｈｅｏｒｙ　ｓｏ　ｗｅｌｌ！

;jpn:◆もののねだんというものは↓
;jpn:　じゅようと　きょうきゅうの↓
;jpn:　かんけいできまる。@KEY()↓
;jpn:◆そのことを　よくわかっている↓
;jpn:　ぼうやたちは　えらい！
@KEYNP()
@!
MSG_SUB_SHOPMES_WATER_3;
◆Ｗｅｌｌ，　ｙｏｕ’ｌｌ　ｄｉｅ　ｂｙ　ｄｅｈｙｄｒａｔｉｏｎ！　　Ｉ’ｍ　ｗａｒｎｉｎｇ　ｙｏｕ！

;jpn:◆ひからびちゃうよー。↓
;jpn:　しらないよー。
@KEYNP()
@!
MSG_SUB_SHOPMES_WATER_4;
◆Ｉｔ’ｓ　ｅｘｐｅｎｓｉｖｅ，　ｔｈｏｕｇｈ！@KEY()↓

;jpn:◆たかいよー。@KEY()
@!
MSG_SUB_SHOPMES_WATER_5;
◆Ｙｏｕ’ｖｅ　ｃｈａｎｇｅｄ　ｙｏｕｒ　ｍｉｎｄ　ａｎｄ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｓｏｍｅ↓
　　@DSP_GOODS(0)？@KEY()↓

;◆@DSP_GOODS(0)↓
;jpn:　かうきになったんだね。@KEY()↓
@!
MSG_SUB_SHOPMES_WATER_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれがもつんだい？@KEY()
@!
MSG_SUB_SHOPMES_WATER_10;
◆Ｙｏｕ’ｌｌ　ｂｅ　ｄｅａｄ　ｏｆ　ｄｅｈｙｄｒａｔｉｏｎ！　　Ｉ’ｍ　ｗａｒｎｉｎｇ　ｙｏｕ！

;jpn:◆ひからびちゃうよー。↓
;jpn:　しらないよー。
@KEYNP()
@!
MSG_SUB_SHOPMES_WATER_11;
◆Ｉｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆おかねが　たりないみたいだね。
@KEYNP()
@!
MSG_SUB_SHOPMES_WATER_12;
◆Ｙｏｕ　ｃａｎｎｏｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．

;jpn:◆にもつが　いっぱいだよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_WATER_18;
◆Ｉ　ｔｈｉｎｋ　ｉｔ　ｗａｓ　ａ　ｇｏｏｄ　ｂｕｙ！@KEY()↓

;jpn:◆おきゃくさん↓
;jpn:　いいかいものをしたねぇ。@KEY()↓
@!
MSG_SUB_SHOPMES_WATER_19;
◆Ｉ　ｔｈｉｎｋ　ｉｔ　ｗａｓ　ａ　ｇｏｏｄ　ｂｕｙ！@KEY()↓

;jpn:◆おきゃくさん↓
;jpn:　いいかいものをしたねぇ。@KEY()↓
@!
MSG_SUB_SHOPMES_WATER_20;
◆Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｓｏｍｅ　ｍｏｒｅ？↓

;jpn:◆もっとかう？↓
@!
MSG_SUB_SHOPMES_WATER_22;
◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　もちものが　いっぱいだよ。@KEY()↓
;jpn:◆ほかのだれかが　もつのかな？↓
@!
;バナナババア（ｏｌｄ ｗｏｍａｎ ｓｅｌｌｉｎｇ ｂａｎａｎａ） 
MSG_SUB_SHOPMES_BANANA_1;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｓｏｍｅ　ｂａｎａｎａｓ？@KEY()↓

;jpn:◆バナナいらんかえー。@KEY()↓
@!
MSG_SUB_SHOPMES_BANANA_2;
◆Ｔｈａｎｋ　ｙｏｕ．

;jpn:◆ありがとよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_BANANA_3;
◆Ｗｅｌｌ，　ｗｈｅｎ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｅａｔ　ｂａｎａｎａｓ，　Ｉ’ｌｌ　ｂｅ　ｈｅｒｅ，　ｓｅｌｌｉｎｇ　ｔｈｅｍ！

;jpn:◆それじゃあ↓
;jpn:　バナナがたべたくなったら↓
;jpn:　おいでなさい。
@KEYNP()
@!
MSG_SUB_SHOPMES_BANANA_4;
◆Ｈｅｙ　ｋｉｄ！↓
　　Ｄｏ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｂｕｙ　ｓｏｍｅ？@KEY()↓

;jpn:◆ぼうや　どうじゃ↓
;jpn:　かっていくかね？@KEY()
@!
MSG_SUB_SHOPMES_BANANA_5;
◆Ｙｏｕ　ｗａｎｔ↓
　　ｔｈｅ　@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)じゃな。@KEY()
@!
MSG_SUB_SHOPMES_BANANA_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれがもつのじゃ？@KEY()
@!
MSG_SUB_SHOPMES_BANANA_10;
◆Ｙｏｕ　ｄｏｎｔ’　ｗａｎｔ　ａｎｙ？　　Ｗｈａｔｅｖｅｒ　ｙｏｕ　ｓａｙ．

;jpn:◆そうか。↓
;jpn:　いらんのか‥‥。
@KEYNP()
@!
MSG_SUB_SHOPMES_BANANA_11;
@LOAD_REG()
◆Ｙｏｕ　ｃａｎ’ｔ　ｂｕｙ　ｔｈｅ　ｂａｎａｎａｓ　ｉｆ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆かねがないんじゃ↓
;jpn:　バナナはかえんぞ。
@KEYNP()
@!
MSG_SUB_SHOPMES_BANANA_12;
◆Ｙｏｕ　ｃａｎｎｏｔ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．

;jpn:◆にもつがいっぱいじゃな。
@KEYNP()
@!
MSG_SUB_SHOPMES_BANANA_18;
◆Ｔｈａｎｋ　ｙｏｕ，　ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとよ↓
;jpn:　ありがとよ。@KEY()↓
@!
MSG_SUB_SHOPMES_BANANA_19;
◆Ｔｈａｎｋ　ｙｏｕ，　ｔｈａｎｋ　ｙｏｕ．@KEY()↓

;jpn:◆ありがとよ↓
;jpn:　ありがとよ。@KEY()↓
;◆そうかそうか↓
;　むりには　すすめん。@KEY()↓
@!
MSG_SUB_SHOPMES_BANANA_20;
◆Ｉ　ｈａｖｅ　ｍｏｒｅ　ｂａｎａｎａｓ．．．　　Ｄｏ　ｙｏｕ　ｗａｎｔ　ｓｏｍｅ　ｍｏｒｅ？↓

;jpn:◆まだまだバナナは↓
;jpn:　あるんじゃが‥‥。@KEY()↓
;jpn:◆どうする？↓
@!
MSG_SUB_SHOPMES_BANANA_22;
◆@DSP_NAME(0)　ｈａｓ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ｔｏ　ｃａｒｒｙ　ａ　ｂａｎａｎａ．@KEY()↓
◆Ｗｉｌｌ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ　ｆｏｒ　ｈｉｍ？↓

;jpn:◆@DSP_NAME(0)は↓
;jpn:　にもつがいっぱいで↓
;jpn:　バナナがもてんな。@KEY()↓
;jpn:◆ほかのだれかが↓
;jpn:　もつのじゃな？↓
@!
;フリカケワゴン（ｓｅａｓｏｎｉｎｇ ｗａｇｏｎ）
MSG_SUB_SHOPMES_FURI2_1;
◆Ｈｅｌｌｏ　ｔｈｅｒｅ！@KEY()↓
◆Ｈｏｗ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ｓｏｍｅ　ｓｅａｓｏｎｉｎｇｓ@KEY()↓
◆ｔｈａｔ　ｇｏ　ｇｒｅａｔ　ｏｎ　ｙｏｕｒ　ｆｏｏｄ　ａｔ　ｍｅａｌ　ｔｉｍｅ？@KEY()↓
◆Ｔｈｅｓｅ　ａｒｅ　ｎｏｔ　ｊｕｓｔ　ｙｏｕｒ　ａｖｅｒａｇｅ　ｓｅａｓｏｎｉｎｇｓ！@KEY()↓
◆Ｗｈｅｎｅｖｅｒ　ｙｏｕ　ｔｒｙ　ｔｏ　ｅａｔ　ｓｏｍｅｔｈｉｎｇ，　ｔｈｅ　ｓｅａｓｏｎｉｎｇ　ｗｉｌｌ　ａｕｔｏｍａｔｉｃａｌｌｙ　ｓｐｒｉｎｋｌｅ@KEY()↓
◆ｏｎ　ｙｏｕｒ　ｆｏｏｄ．　　Ｉｔ’ｓ　ｒｅａｌｌｙ　ａｌｍｏｓｔ　ｍａｇｉｃａｌ！@KEY()↓

;jpn:◆いらっしゃいませ。↓
;jpn:　おしょくじには　かかせない。@KEY()↓
;jpn:◆あじつけ　こもの↓
;jpn:　いかがですか？@KEY()↓
;jpn:◆あらふしぎ！↓
;jpn:　なにかを　たべようとすると@KEY()↓
;jpn:◆じどうてきに　ふりかけちゃう↓
;jpn:　ふしぎな　こびんに↓
;jpn:　はいってまーす。@KEY()
@!
MSG_SUB_SHOPMES_FURI2_2;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　きてくださいね。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI2_3;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　きてくださいね。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI2_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？@KEY()↓

;jpn:◆なんに　なさいますか？@KEY()
@!
MSG_SUB_SHOPMES_FURI2_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI2_6;

◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆どなたがおもちになりますか？@KEY()
@!
MSG_SUB_SHOPMES_FURI2_10;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．@KEY()↓

;jpn:◆また　よろしくおねがいします。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI2_11;
◆Ｏｈ，　ｉｔ　ｌｏｏｋｓ　ｌｉｋｅ　ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．@KEY()↓

;jpn:◆あら　おかねが↓
;jpn:　たりないようですよ。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI2_12;
◆Ｏｈ，　Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｙｏｕ　ｃａｎ　ｃａｒｒｙ　ａｎｙ　ｍｏｒｅ．

;jpn:◆あら↓
;jpn:　もちものが　いっぱいで↓
;jpn:　もてないようですよ。
@KEYNP()
@!
MSG_SUB_SHOPMES_FURI2_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI2_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()↓

;jpn:◆ありがとうございます。@KEY()↓
@!
MSG_SUB_SHOPMES_FURI2_20;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？↓

;jpn:◆ほかに　なにか↓
;jpn:　おかいあげになりますか？↓
@!
MSG_SUB_SHOPMES_FURI2_22;
◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつがいっぱいですね。@KEY()↓
;jpn:◆ほかのひとがもちますか？↓
@!
;ひしょちのジェラート売り（ｇｅｌａｒｔ？ ｓｅｌｌｅｒ ｉｎ ｓｕｍｍｅｒ 
　ｒｅｓｏｒｔ）
MSG_SUB_SHOPMES_HISYO_1;
◆Ｗｅ’ｖｅ　ｇｏｔ　ｓｏｍｅ　ｒｅａｌｌｙ　ｓｐｅｃｔａｃｕｌａｒ　ｔｈｉｎｇｓ！@KEY()↓

;jpn:◆いいものありまーす。@KEY()↓
@!
MSG_SUB_SHOPMES_HISYO_2;
◆Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．

;jpn:◆また　よろしくね。
@KEYNP()
@!
MSG_SUB_SHOPMES_HISYO_3;
◆Ｙｏｕ　ｒｅａｌｌｙ　ｓｈｏｕｌｄ　ｅａｔ　ｈｅｒｅ！　

;jpn:◆たべていけばいいのに。
@KEYNP()
@!
MSG_SUB_SHOPMES_HISYO_4;
◆Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？@KEY()

;jpn:◆なんにしますか？@KEY()
@!
MSG_SUB_SHOPMES_HISYO_5;
◆@DSP_GOODS(0)？@KEY()↓

;jpn:◆@DSP_GOODS(0)ですね。@KEY()↓
@!
MSG_SUB_SHOPMES_HISYO_6;
◆Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？@KEY()

;jpn:◆だれがもちますか？@KEY()
@!
MSG_SUB_SHOPMES_HISYO_10;
◆Ｄｏ　ｙｏｕ　ｍｅａｎ　ｔｏ　ｔｅｌｌ　ｍｅ　ｙｏｕ　ａｒｅ　ｎｏｔ　ｇｏｉｎｇ　ｔｏ　ｂｕｙ　ａｎｙｔｈｉｎｇ．．．？

;jpn:◆やめるんですか‥‥。
@KEYNP()
@!
MSG_SUB_SHOPMES_HISYO_11;
◆Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．

;jpn:◆おかねが　たりないですね。
@KEYNP()
@!
MSG_SUB_SHOPMES_HISYO_12;
◆Ｙｏｕ　ａｒｅ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ　ａｌｒｅａｄｙ．@KEY()↓
◆Ｓｅｌｌ　ｓｏｍｅｔｈｉｎｇ，　ｏｒ　ｔｈｒｏｗ　ｓｏｍｅｔｈｉｎｇ　ａｗａｙ，　ａｎｄ　ｃｏｍｅ　ｂａｃｋ．

;jpn:◆もちものが　いっぱいですね。↓
;jpn:　うるかすてるかして↓
;jpn:　もういちど　きてね。
@KEYNP()
@!
MSG_SUB_SHOPMES_HISYO_18;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()

;jpn:◆ありがとうございます。@KEY()
@!
MSG_SUB_SHOPMES_HISYO_19;
◆Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．@KEY()

;jpn:◆まいどありがとうございます。@KEY()
@!
MSG_SUB_SHOPMES_HISYO_20;
◆Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ｔｏ　ｂｕｙ　ｏｎｅ　ｍｏｒｅ？↓

;jpn:◆もういっこ　かいますか？↓
@!
MSG_SUB_SHOPMES_HISYO_22;
◆@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｃａｒｒｙ　ｉｔ？↓

;jpn:◆@DSP_NAME(0)さんは↓
;jpn:　にもつが　いっぱいですね。@KEY()↓
;jpn:◆ほかのひとが　もちますか？↓
@!
;原人（ｐｒｉｍｉｔｉｖｅ ｍａｎ）
MSG_SUB_SHOPMES_GORI_1;
◆Ｏｏｏｇａ　ｂｏｏｏｇａ．↓
　　（Ｍａｙ　Ｉ　ｈｅｌｐ　ｙｏｕ？）@KEY()↓

;jpn:◆ウホウホ。↓
;jpn:　（いらっしゃいませ）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_2;
◆Ｕｎｇａｗａ　ｇｏｏｎｇａｌｏｏ！↓
　　（Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．）

;jpn:◆ウホホホ。↓
;jpn:　（ありがとうございました）
@KEYNP()
@!
MSG_SUB_SHOPMES_GORI_3;
◆Ｗｏｏｎｇｕ　Ｇｏｏｎｇａｒｅｅ！↓
　　（Ｐｌｅａｓｅ　ｃｏｍｅ　ａｇａｉｎ．）

;jpn:◆ウホウホホ。↓
;jpn:　（またよろしく）
@KEYNP()
@!
MSG_SUB_SHOPMES_GORI_4;
◆Ｗａｋｋａ　ｕｎｇａｗａ？↓
　　（Ｗｈａｔ　ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ？）@KEY()↓

;jpn:◆ウホ？↓
;jpn:　（なんにしますか？）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_5;
◆Ｗｕｎｇａ　Ｄｉｎ？↓
　　（@DSP_GOODS(0)？）@KEY()↓

;jpn:◆ウホー。↓
;jpn:　（@DSP_GOODS(0)ですね）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_6;
◆Ｓｐｏｏｎｇａｗａ　ｇｏｏｎｇａ　ｕｇｈ！？↓
　　（Ｗｈｏ　ｉｓ　ｇｏｉｎｇ　ｔｏ　ｃａｒｒｙ　ｉｔ？）@KEY()

;jpn:◆ウホホ？↓
;jpn:　（どなたがおもちになりますか？）@KEY()
@!
MSG_SUB_SHOPMES_GORI_10;
◆Ｇｏｏｎｇｏｏ，　ｗｏｏ　ｗｏｏ！↓
　　（Ｃｏｍｅ　ａｇａｉｎ．）@KEY()↓

;jpn:◆ウホウホホ。↓
;jpn:　（またよろしく）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_11;
◆Ｗｕｎｇａ　ｗｏｏ　ｇｕｎ　ｗｏｏｎｇａ　ｗａｋｋａ！！↓
　　（Ｙｏｕ　ｄｏｎ’ｔ　ｈａｖｅ　ｅｎｏｕｇｈ　ｍｏｎｅｙ．）@KEY()↓

;jpn:◆ウホ！↓
;jpn:　（おかねがたりません！）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_12;
◆Ｗｈｏａ！　　Ｗｏｏｎ　ｗｏｏｎｇａ　ｗａｋｋａ　ｗｏｏ！↓
　　（Ｙｏｕ　ａｒｅ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．）

;jpn:◆ウッホー！↓
;jpn:　（にもつがいっぱいです！）
@KEYNP()
@!
MSG_SUB_SHOPMES_GORI_18;
◆Ｕｎｇａａｈ，　ｇｏｏｎ　ｗａｋｋａｗｏｏ！↓
　　（Ｔｈａｎｋ　ｙｏｕ　ｖｅｒｙ　ｍｕｃｈ．）@KEY()↓

;jpn:◆ウホホホ。↓
;jpn:　（ありがとうございました）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_19;
◆Ｗａｎｇａ　ｗｏｏｎ　ｇａｗａ　ｄｉｎ　ｇｏｏ！↓
　　（Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｓｈｏｐｐｉｎｇ　ｈｅｒｅ．）@KEY()↓

;jpn:◆ウーホウホ。↓
;jpn:　（まいどあり）@KEY()↓
@!
MSG_SUB_SHOPMES_GORI_20;
◆Ｗａｋｋａ　ｇｏｗｏｏｎ　ｄｉｎ　ｗｏｏ？！↓
　　（Ｗｏｕｌｄ　ｙｏｕ　ｌｉｋｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？）↓

;jpn:◆ウホウホ？↓
;jpn:　（ほかに　ちゅうもんは？）↓
@!
MSG_SUB_SHOPMES_GORI_22;
◆Ｕｎｇａｗａ　ｕｎｇａｗａ　ｕｎｇａｗａ　ｗｏｏ！　　Ｗｏｎｇａ　ｗａｋｋａ　ｗｏｏｎｇａ！↓
　　（@DSP_NAME(0)　ｉｓ　ａｌｒｅａｄｙ　ｃａｒｒｙｉｎｇ　ｔｏｏ　ｍａｎｙ　ｔｈｉｎｇｓ．@KEY()↓
◆　　Ｃａｎ　ｓｏｍｅｏｎｅ　ｅｌｓｅ　ｈｅｌｐ　ｈｉｍ　ｏｕｔ？）↓

;jpn:◆ウホー！　ウホウホ？↓
;jpn:　（@DSP_NAME(0)さんはこれいじょう↓
;jpn:　にもつがもてません！@KEY()↓
;jpn:　ほかのひとが　もちますか？）↓
@!

;
;
;

MSG_SHOP_ONET_DRUG1;
@SETF(FLG_SHOP_01)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_01)
@!

MSG_SHOP_ONET_DRUG2;
@SETF(FLG_SHOP_02)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_02)
@!

MSG_SHOP_ONET_HAMBURGER;
@SETF(FLG_SHOP_03)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_03)
@!

MSG_SHOP_ONET_HAMBURGER_2;
@SETF(FLG_SHOP_04)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_04)
@!

MSG_SHOP_ONET_BAKERY;
@SETF(FLG_SHOP_05)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_05)
@!

MSG_SHOP_TWSN_HAMBURGER;
@SETF(FLG_SHOP_06)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_06)
@!

MSG_SHOP_TWSN_BAKERY;
@SETF(FLG_SHOP_07)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_07)
@!

MSG_SHOP_TWSN_DRUG1;
@SETF(FLG_SHOP_08)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_08)
@!

MSG_SHOP_TWSN_DRUG2;
@SETF(FLG_SHOP_09)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_09)
@!

MSG_SHOP_TWSN_GARAKUTA;
@SETF(FLG_SHOP_10)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_10)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_TWSN_AKANBAKERY;
@SETF(FLG_SHOP_11)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_11)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_TWSN_FURIKAKE;
@SETF(FLG_SHOP_12)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_12)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_TWSN_FRUIT;
@SETF(FLG_SHOP_13)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_C)
@CLRF(FLG_SHOP_13)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_HAPPY_DRUGSTORE;
@SETF(FLG_SHOP_14)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_14)
@!

MSG_SHOP_HAPPY_DRUG;
@SETF(FLG_SHOP_15)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_15)
@!

MSG_SHOP_THRK_DRUG1;
@SETF(FLG_SHOP_16)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_16)
@!

MSG_SHOP_THRK_DRUG2;
@SETF(FLG_SHOP_17)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_17)
@!

MSG_SHOP_THRK_WEAPON;
@SETF(FLG_SHOP_18)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_18)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_THRK_BAKERY;
@SETF(FLG_SHOP_19)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_19)
@!

MSG_SHOP_WINS_DRUG;
@SETF(FLG_SHOP_20)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_20)
@!

MSG_SHOP_WINS_STONEHENGE_B;
@SETF(FLG_SHOP_21)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_21)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_GPFT_GRAVEKEEPER;
@SETF(FLG_SHOP_22)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_22)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_DOSEI_BAKA;
@SETF(FLG_SHOP_23)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_23)
@!

MSG_SHOP_DOSEI_BAKA2;
@SETF(FLG_SHOP_24)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_24)
@!

MSG_SHOP_SHOP_DOSEI_BAKA3;
@SETF(FLG_SHOP_25)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_25)
@!

MSG_SHOP_DSRT_DRUG;
@SETF(FLG_SHOP_26)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_26)
@!

MSG_SHOP_DSRT_SHOP2;
@SETF(FLG_SHOP_27)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_27)
@!

MSG_SHOP_DSRT_BENTOU;
@SETF(FLG_SHOP_28)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_28)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_DSRT_WEAPON;
@SETF(FLG_SHOP_29)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_29)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_FOUR_BAKERY;
@SETF(FLG_SHOP_30)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_30)
@!

MSG_SHOP_FOUR_DRUG1;
@SETF(FLG_SHOP_31)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_31)
@!

MSG_SHOP_FOUR_DRUG2;
@SETF(FLG_SHOP_32)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_32)
@!

MSG_SHOP_FOUR_FOOD;
@SETF(FLG_SHOP_33)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_33)
@!

MSG_SHOP_FOUR_TOYSHOP;
@SETF(FLG_SHOP_34)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_34)
@!

MSG_SHOP_FOUR_SPORT;
@SETF(FLG_SHOP_35)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_35)
@!

MSG_SHOP_FOUR_HAMBURGER;
@SETF(FLG_SHOP_36)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_36)
@!

MSG_SHOP_FOUR_FURIKAKE;
@SETF(FLG_SHOP_37)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_37)
@!

MSG_SHOP_FOUR_WEAPON;
@SETF(FLG_SHOP_38)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_38)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_FOUR_JUNK;
@SETF(FLG_SHOP_39)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_39)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SUMS_DRUG;
@SETF(FLG_SHOP_40)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_40)
@!

MSG_SHOP_SUMS_DINER;
@SETF(FLG_SHOP_41)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_41)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SUMS_GROCER;
@SETF(FLG_SHOP_42)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_42)
@!

MSG_SHOP_SUMS_ICE;
@SETF(FLG_SHOP_43)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_C)
@CLRF(FLG_SHOP_43)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SUMS_WIFE;
@SETF(FLG_SHOP_44)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_C)
@CLRF(FLG_SHOP_44)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_RAMA_OKAYU;
@SETF(FLG_SHOP_45)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_45)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_DRUG;
@SETF(FLG_SHOP_46)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_46)
@!

MSG_SHOP_SKRB_SNAKE;
@SETF(FLG_SHOP_47)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_47)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_BAZAR;
@SETF(FLG_SHOP_48)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_48)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_WEAPON;
@SETF(FLG_SHOP_49)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_49)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_FURIKAKE;
@SETF(FLG_SHOP_50)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_50)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_BAZAR_B;
@SETF(FLG_SHOP_51)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_51)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_WATER;
@SETF(FLG_SHOP_52)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_C)
@CLRF(FLG_SHOP_52)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_SKRB_OASIS;
@SETF(FLG_SHOP_53)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_53)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_MAKYO_DRUG;
@SETF(FLG_SHOP_54)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_54)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_MAKYO_WEAPON;
@SETF(FLG_SHOP_55)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_55)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_GUMI_B_DRUG;
@SETF(FLG_SHOP_56)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_56)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_MGKT_FREE;
@SETF(FLG_SHOP_57)
@SETF(FLG_SHOPTEMP_1)
@GOSUB(MSG_SUB_SHOP_A)
@CLRF(FLG_SHOP_57)
@CLRF(FLG_SHOPTEMP_1)
@!

MSG_SHOP_HOTEL_MOON_SHOP;
@SETF(FLG_SHOP_58)
@SETF(FLG_SHOPTEMP_1)
@SETF(FLG_SHOPTEMP_4)
@GOSUB(MSG_SUB_SHOP_B)
@CLRF(FLG_SHOP_58)
@CLRF(FLG_SHOPTEMP_1)
@CLRF(FLG_SHOPTEMP_4)
@!

;ショップメニューの表示と選択

MSG_SUB_SHOP_MENU;
@CHKFGOTO(FLG_SHOP_01,_SHOP_SHOPTAKE_01)
@CHKFGOTO(FLG_SHOP_02,_SHOP_SHOPTAKE_02)
@CHKFGOTO(FLG_SHOP_03,_SHOP_SHOPTAKE_03)
@CHKFGOTO(FLG_SHOP_04,_SHOP_SHOPTAKE_04)
@CHKFGOTO(FLG_SHOP_05,_SHOP_SHOPTAKE_05)
@CHKFGOTO(FLG_SHOP_06,_SHOP_SHOPTAKE_06)
@CHKFGOTO(FLG_SHOP_07,_SHOP_SHOPTAKE_07)
@CHKFGOTO(FLG_SHOP_08,_SHOP_SHOPTAKE_08)
@CHKFGOTO(FLG_SHOP_09,_SHOP_SHOPTAKE_09)
@CHKFGOTO(FLG_SHOP_10,_SHOP_SHOPTAKE_10)
@CHKFGOTO(FLG_SHOP_11,_SHOP_SHOPTAKE_11)
@CHKFGOTO(FLG_SHOP_12,_SHOP_SHOPTAKE_12)
@CHKFGOTO(FLG_SHOP_13,_SHOP_SHOPTAKE_13)
@CHKFGOTO(FLG_SHOP_14,_SHOP_SHOPTAKE_14)
@CHKFGOTO(FLG_SHOP_15,_SHOP_SHOPTAKE_15)
@CHKFGOTO(FLG_SHOP_16,_SHOP_SHOPTAKE_16)
@CHKFGOTO(FLG_SHOP_17,_SHOP_SHOPTAKE_17)
@CHKFGOTO(FLG_SHOP_18,_SHOP_SHOPTAKE_18)
@CHKFGOTO(FLG_SHOP_19,_SHOP_SHOPTAKE_19)
@CHKFGOTO(FLG_SHOP_20,_SHOP_SHOPTAKE_20)
@CHKFGOTO(FLG_SHOP_21,_SHOP_SHOPTAKE_21)
@CHKFGOTO(FLG_SHOP_22,_SHOP_SHOPTAKE_22)
@CHKFGOTO(FLG_SHOP_23,_SHOP_SHOPTAKE_23)
@CHKFGOTO(FLG_SHOP_24,_SHOP_SHOPTAKE_24)
@CHKFGOTO(FLG_SHOP_25,_SHOP_SHOPTAKE_25)
@CHKFGOTO(FLG_SHOP_26,_SHOP_SHOPTAKE_26)
@CHKFGOTO(FLG_SHOP_27,_SHOP_SHOPTAKE_27)
@CHKFGOTO(FLG_SHOP_28,_SHOP_SHOPTAKE_28)
@CHKFGOTO(FLG_SHOP_29,_SHOP_SHOPTAKE_29)
@CHKFGOTO(FLG_SHOP_30,_SHOP_SHOPTAKE_30)
@CHKFGOTO(FLG_SHOP_31,_SHOP_SHOPTAKE_31)
@CHKFGOTO(FLG_SHOP_32,_SHOP_SHOPTAKE_32)
@CHKFGOTO(FLG_SHOP_33,_SHOP_SHOPTAKE_33)
@CHKFGOTO(FLG_SHOP_34,_SHOP_SHOPTAKE_34)
@CHKFGOTO(FLG_SHOP_35,_SHOP_SHOPTAKE_35)
@CHKFGOTO(FLG_SHOP_36,_SHOP_SHOPTAKE_36)
@CHKFGOTO(FLG_SHOP_37,_SHOP_SHOPTAKE_37)
@CHKFGOTO(FLG_SHOP_38,_SHOP_SHOPTAKE_38)
@CHKFGOTO(FLG_SHOP_39,_SHOP_SHOPTAKE_39)
@CHKFGOTO(FLG_SHOP_40,_SHOP_SHOPTAKE_40)
@CHKFGOTO(FLG_SHOP_41,_SHOP_SHOPTAKE_41)
@CHKFGOTO(FLG_SHOP_42,_SHOP_SHOPTAKE_42)
@CHKFGOTO(FLG_SHOP_43,_SHOP_SHOPTAKE_43)
@CHKFGOTO(FLG_SHOP_44,_SHOP_SHOPTAKE_44)
@CHKFGOTO(FLG_SHOP_45,_SHOP_SHOPTAKE_45)
@CHKFGOTO(FLG_SHOP_46,_SHOP_SHOPTAKE_46)
@CHKFGOTO(FLG_SHOP_47,_SHOP_SHOPTAKE_47)
@CHKFGOTO(FLG_SHOP_48,_SHOP_SHOPTAKE_48)
@CHKFGOTO(FLG_SHOP_49,_SHOP_SHOPTAKE_49)
@CHKFGOTO(FLG_SHOP_50,_SHOP_SHOPTAKE_50)
@CHKFGOTO(FLG_SHOP_51,_SHOP_SHOPTAKE_51)
@CHKFGOTO(FLG_SHOP_52,_SHOP_SHOPTAKE_52)
@CHKFGOTO(FLG_SHOP_53,_SHOP_SHOPTAKE_53)
@CHKFGOTO(FLG_SHOP_54,_SHOP_SHOPTAKE_54)
@CHKFGOTO(FLG_SHOP_55,_SHOP_SHOPTAKE_55)
@CHKFGOTO(FLG_SHOP_56,_SHOP_SHOPTAKE_56)
@CHKFGOTO(FLG_SHOP_57,_SHOP_SHOPTAKE_57)
@CHKFGOTO(FLG_SHOP_58,_SHOP_SHOPTAKE_58)
@!
_SHOP_SHOPTAKE_01;
@SEL_SHOP_TAKE(SHOP_ONET_DRUG1)
@!
_SHOP_SHOPTAKE_02;
@SEL_SHOP_TAKE(SHOP_ONET_DRUG2)
@!
_SHOP_SHOPTAKE_03;
@SEL_SHOP_TAKE(SHOP_ONET_HAMBURGER)
@!
_SHOP_SHOPTAKE_04;
@SEL_SHOP_TAKE(SHOP_ONET_HAMBURGER)
@!
_SHOP_SHOPTAKE_05;
@SEL_SHOP_TAKE(SHOP_ONET_BAKERY)
@!
_SHOP_SHOPTAKE_06;
@SEL_SHOP_TAKE(SHOP_TWSN_HAMBURGER)
@!
_SHOP_SHOPTAKE_07;
@SEL_SHOP_TAKE(SHOP_TWSN_BAKERY)
@!
_SHOP_SHOPTAKE_08;
@SEL_SHOP_TAKE(SHOP_TWSN_DRUG1)
@!
_SHOP_SHOPTAKE_09;
@SEL_SHOP_TAKE(SHOP_TWSN_DRUG2)
@!
_SHOP_SHOPTAKE_10;
@SEL_SHOP_TAKE(SHOP_TWSN_GARAKUTA)
@!
_SHOP_SHOPTAKE_11;
@SEL_SHOP_TAKE(SHOP_TWSN_AKANBAKERY)
@!
_SHOP_SHOPTAKE_12;
@SEL_SHOP_TAKE(SHOP_TWSN_FURIKAKE)
@!
_SHOP_SHOPTAKE_13;
@SEL_SHOP_TAKE(SHOP_TWSN_FRUIT)
@!
_SHOP_SHOPTAKE_14;
@SEL_SHOP_TAKE(SHOP_HAPPY_DRUG2)
@!
_SHOP_SHOPTAKE_15;
@SEL_SHOP_TAKE(SHOP_HAPPY_DRUG)
@!
_SHOP_SHOPTAKE_16;
@SEL_SHOP_TAKE(SHOP_THRK_DRUG1)
@!
_SHOP_SHOPTAKE_17;
@SEL_SHOP_TAKE(SHOP_THRK_DRUG2)
@!
_SHOP_SHOPTAKE_18;
@SEL_SHOP_TAKE(SHOP_THRK_WEAPON)
@!
_SHOP_SHOPTAKE_19;
@SEL_SHOP_TAKE(SHOP_THRK_BAKERY)
@!
_SHOP_SHOPTAKE_20;
@SEL_SHOP_TAKE(SHOP_WINS_DRUG)
@!
_SHOP_SHOPTAKE_21;
@CHKFGOTO(FLG_TLPT_SUMS,_SHOP_SHOPTAKE_21_B)
@SEL_SHOP_TAKE(SHOP_WINS_STOHEN)
@!
_SHOP_SHOPTAKE_21_B;
@SEL_SHOP_TAKE(SHOP_WINS_STOHEN_2)
@!
_SHOP_SHOPTAKE_22;
@SEL_SHOP_TAKE(SHOP_GPFT_GRAVEKEEPER)
@!
_SHOP_SHOPTAKE_23;
@SEL_SHOP_TAKE(SHOP_DOSEI_BAKA)
@!
_SHOP_SHOPTAKE_24;
@SEL_SHOP_TAKE(SHOP_DOSEI_BAKA2)
@!
_SHOP_SHOPTAKE_25;
@SEL_SHOP_TAKE(SHOP_DOSEI_BAKA3)
@!
_SHOP_SHOPTAKE_26;
@SEL_SHOP_TAKE(SHOP_DSRT_DRUG)
@!
_SHOP_SHOPTAKE_27;
@SEL_SHOP_TAKE(SHOP_DSRT_DRUG2)
@!
_SHOP_SHOPTAKE_28;
@SEL_SHOP_TAKE(SHOP_DSRT_BENTO)
@!
_SHOP_SHOPTAKE_29;
@SEL_SHOP_TAKE(SHOP_DSRT_WEAPON)
@!
_SHOP_SHOPTAKE_30;
@SEL_SHOP_TAKE(SHOP_FOUR_BAKERY)
@!
_SHOP_SHOPTAKE_31;
@SEL_SHOP_TAKE(SHOP_FOUR_DRUG1)
@!
_SHOP_SHOPTAKE_32;
@SEL_SHOP_TAKE(SHOP_FOUR_DRUG2)
@!
_SHOP_SHOPTAKE_33;
@SEL_SHOP_TAKE(SHOP_FOUR_FOOD)
@!
_SHOP_SHOPTAKE_34;
@SEL_SHOP_TAKE(SHOP_FOUR_TOYSHOP)
@!
_SHOP_SHOPTAKE_35;
@SEL_SHOP_TAKE(SHOP_FOUR_SPORT)
@!
_SHOP_SHOPTAKE_36;
@SEL_SHOP_TAKE(SHOP_FOUR_HAMBURGER)
@!
_SHOP_SHOPTAKE_37;
@SEL_SHOP_TAKE(SHOP_FOUR_FURIKAKE)
@!
_SHOP_SHOPTAKE_38;
@SEL_SHOP_TAKE(SHOP_FOUR_WEAPON)
@!
_SHOP_SHOPTAKE_39;
@SEL_SHOP_TAKE(SHOP_FOUR_JUNK)
@!
_SHOP_SHOPTAKE_40;
@SEL_SHOP_TAKE(SHOP_SUMS_DRUG)
@!
_SHOP_SHOPTAKE_41;
@SEL_SHOP_TAKE(SHOP_SUMS_DINER)
@!
_SHOP_SHOPTAKE_42;
@SEL_SHOP_TAKE(SHOP_SUMS_GROCER)
@!
_SHOP_SHOPTAKE_43;
@SEL_SHOP_TAKE(SHOP_SUMS_ICESHOP)
@!
_SHOP_SHOPTAKE_44;
@SEL_SHOP_TAKE(SHOP_SUMS_MAGICTORTE)
@!
_SHOP_SHOPTAKE_45;
@SEL_SHOP_TAKE(SHOP_RAMA_OKAYU)
@!
_SHOP_SHOPTAKE_46;
@SEL_SHOP_TAKE(SHOP_SKRB_DRUG)
@!
_SHOP_SHOPTAKE_47;
@SEL_SHOP_TAKE(SHOP_SKRB_SNAKE)
@!
_SHOP_SHOPTAKE_48;
@SEL_SHOP_TAKE(SHOP_SKRB_BAZAR)
@!
_SHOP_SHOPTAKE_49;
@SEL_SHOP_TAKE(SHOP_SKRB_WEAPON)
@!
_SHOP_SHOPTAKE_50;
@SEL_SHOP_TAKE(SHOP_SKRB_FURIKAKE)
@!
_SHOP_SHOPTAKE_51;
@SEL_SHOP_TAKE(SHOP_SKRB_BAZAR2)
@!
_SHOP_SHOPTAKE_52;
@SEL_SHOP_TAKE(SHOP_SKRB_WATER)
@!
_SHOP_SHOPTAKE_53;
@SEL_SHOP_TAKE(SHOP_SKRB_OASIS)
@!
_SHOP_SHOPTAKE_54;
@SEL_SHOP_TAKE(SHOP_MAKYO_DRUG)
@!
_SHOP_SHOPTAKE_55;
@SEL_SHOP_TAKE(SHOP_MAKYO_WEAPON)
@!
_SHOP_SHOPTAKE_56;
@SEL_SHOP_TAKE(SHOP_GUMI_B_DRUG)
@!
_SHOP_SHOPTAKE_57;
@SEL_SHOP_TAKE(SHOP_MGKT_MAGICPUDDING)
@!
_SHOP_SHOPTAKE_58;
@SEL_SHOP_TAKE(SHOP_MOON_HOTEL)
@!

;レジ音の選択

MSG_SUB_SHOP_SE;
@CHKFGOTO(FLG_SHOPTEMP_1,_SHOP_SE_B)
@SE(SE_se0c_regi)
@!
_SHOP_SE_B;
@SE(SE_se78_my_open_rock)
@!

;道具屋の客

MSG_CUSTOMER_A;
@CLRF(FLG_DELIVERY_CUSTOMER)
@SETF(FLG_SHOP_01)
@GOSUB(MSG_SUB_CUSTOMER)
@CLRF(FLG_SHOP_01)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!
MSG_CUSTOMER_B;
@CLRF(FLG_DELIVERY_CUSTOMER_B)
@SETF(FLG_SHOP_02)
@GOSUB(MSG_SUB_CUSTOMER)
@CLRF(FLG_SHOP_02)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!
MSG_CUSTOMER_C;
@CLRF(FLG_DELIVERY_CUSTOMER_C)
@SETF(FLG_SHOP_03)
@GOSUB(MSG_SUB_CUSTOMER)
@CLRF(FLG_SHOP_03)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!
MSG_CUSTOMER_D;
@CLRF(FLG_DELIVERY_CUSTOMER_D)
@SETF(FLG_SHOP_04)
@GOSUB(MSG_SUB_CUSTOMER)
@CLRF(FLG_SHOP_04)
;@CLRF(FLG_SYS_DISTLPT);テレポート許可
@GOSUB(MSG_SUB_TLPTOK_OTHEREVENT)	;イベント中以外ならテレポート許可
@!

MSG_SUB_CUSTOMER;
@GOSUB(MSG_SUB_BGM_PIZZASTART)
@GOSUB(MSG_SUB_CUSTMES_1)
_SUB_CUST_SEL;
;@WINR_MONEY()
@DSP_PL()
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_SUB_CUST_NO)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_SUB_CUST_UNABLE)
@GOSUB(MSG_SUB_CUSTMES_4)
@GOSUB(MSG_SUB_YESNO)
@SELGOTO(_SUB_CUST_MONEY_YES,_SUB_CUST_MONEY_NO)
_SUB_CUST_MONEY_NO;
@GOSUB(MSG_SUB_CUSTMES_5)
@GOTO(_SUB_CUST_SEL)

_SUB_CUST_MONEY_YES;
@MONEYIN(0)
@WINR_MONEY()
@SE(SE_se76_my_give)
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@GOSUB(MSG_SUB_CUSTMES_2)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

_SUB_CUST_UNABLE;
@GOSUB(MSG_SUB_CUSTMES_6)
@GOTO(_SUB_CUST_SEL)


_SUB_CUST_NO;
@GOSUB(MSG_SUB_CUSTMES_3)
@CLOSEALL()
@GOSUB(MSG_SUB_DELIVERY_BYE)
@GOSUB(MSG_SUB_BGM_PIZZAEND)
@!

MSG_SUB_CUSTMES_1;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_1)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_1)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_1)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_1)
@!
MSG_SUB_CUSTMES_2;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_2)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_2)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_2)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_2)
@!
MSG_SUB_CUSTMES_3;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_3)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_3)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_3)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_3)
@!
MSG_SUB_CUSTMES_4;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_4)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_4)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_4)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_4)
@!
MSG_SUB_CUSTMES_5;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_5)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_5)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_5)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_5)
@!
MSG_SUB_CUSTMES_6;
@SAVE_GLOBAL_REG()
@CHKFGOTO(FLG_SHOP_01,_SUB_CUSTMES_A_6)
@CHKFGOTO(FLG_SHOP_02,_SUB_CUSTMES_B_6)
@CHKFGOTO(FLG_SHOP_03,_SUB_CUSTMES_C_6)
@CHKFGOTO(FLG_SHOP_04,_SUB_CUSTMES_D_6)
@!

;看板の客（おじさん）（ｅｌｄｅｒｌｙ ｍａｍ）
_SUB_CUSTMES_A_1;
◆Ｈｕｆｆ，　ｐｕｆｆ，　ｈｕｆｆ．．．　　ｗｈｅｅｅｅｚｅ！　　Ｉ　ｒａｎ　ｈｅｒｅ　ａｓ　ｆａｓｔ　ａｓ　Ｉ　ｃｏｕｌｄ．@KEY()↓
◆Ｉ’ｍ　ｐｌｕｍ　ｔｕｃｋｅｒｅｄ　ｏｕｔ．@KEY()↓
◆Ｗｈａｔ　ｈａｖｅ　ｙｏｕ　ｇｏｔ　ｆｏｒ　ｓａｌｅ？@KEY()

;jpn:◆はあ　はあ　はあ↓
;jpn:　ぜんりょくで　はしって↓
;jpn:　きたんで　アセかいちゃったよ。@KEY()↓
;jpn:◆なにを　うってくれるのかね。@KEY()
@!
_SUB_CUSTMES_A_2;
◆Ｔｈａｎｋｓ，　ｓｏｎｎｙ．@KEY()↓
◆Ｙｏｕ　ｃｅｒｔａｉｎｌｙ　ｍａｄｅ　ｉｔ　ｗｏｒｔｈ　ｍｙ　ｗｈｉｌｅ　ｔｏ　ｃｏｍｅ　ａｌｌ　ｔｈｉｓ　ｗａｙ！

;jpn:◆ありがとう↓
;jpn:　とおくからきた↓
;jpn:　かいが　あったよ。
@KEYNP()
@!
_SUB_CUSTMES_A_3;
←
◆Ｏｈ，　ｓａｙ　ｉｔ　ａｉｎ’ｔ　ｓｏ！　　Ａｎｄ　ａｆｔｅｒ　Ｉ　ｒａｎ　ｈｅｒｅ　ａｓ　ｆａｓｔ　ａｓ　Ｉ　ｃｏｕｌｄ！

;jpn:◆せっかく　ぜんりょくで↓
;jpn:　はしってきたのに！
@KEYNP()
@!
_SUB_CUSTMES_A_4;
@LOAD_GLOBAL_REG()
←
◆@DSP_GOODS(0)？↓
　　Ｉ’ｌｌ　ｇｉｖｅ　ｙｏｕ　@XCHG()＄@DSP_NUM(0)．@KEY()↓
◆Ｈｏｗ’ｓ　ｔｈａｔ　ｆｏｒ　ａ　ｆａｉｒ　ｏｆｆｅｒ？↓

;◆@DSP_GOODS(0)？↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルで　どうかね？@KEY()↓
;jpn:◆それで　いいかね？↓
@!
_SUB_CUSTMES_A_5;
◆Ｔｈａｔ’ｓ　ｔｏｏ　ｂａｄ．．．@KEY()↓
◆Ｄｏ　ｙｏｕ　ｈａｖｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｙｏｕ　ｗａｎｔ　ｔｏ　ｓｅｌｌ？@KEY()

;jpn:◆それはざんねんだ‥‥↓
;jpn:　ほかになにか↓
;jpn:　うるものはあるのかね？@KEY()
@!
_SUB_CUSTMES_A_6;
←
◆Ｏｈ，　ｊｕｍｐｉｎ’　ｊｅｈｏｓａｐｈａｔ！　　Ｉ　ｄｏｎ’ｔ　ｔｈｉｎｋ　Ｉ　ｃａｎ　ｂｕｙ　ｔｈａｔ．@KEY()↓
◆Ｗｈａｔ　ｅｌｓｅ　ｃａｎ　ｙｏｕ　ｓｅｌｌ　ｍｅ？@KEY()

;jpn:◆あいたッ　それはちょっと↓
;jpn:　かえないねぇ。@KEY()↓
;jpn:◆なにを　うってくれるのかね。@KEY()
@!

;看板の客（おばさん）（ｅｌｄｅｒｌｙ ｌａｄｙ）
_SUB_CUSTMES_B_1;
◆Ｉ　ｓａｗ　ｙｏｕｒ　ｓｉｇｎ．　　Ｓｏ，　Ｉ　ｔｈｏｕｇｈｔ　Ｉ’ｄ　ｓｔｏｐ　ｂｙ．@KEY()↓
◆Ｗｈａｔ’ｒｅ　ｙｏｕ　ｐｅｄｄｌｉｎ’？@KEY()

;jpn:◆かんばんが　みえたから↓
;jpn:　ちょっと　よってみたの。@KEY()↓
;jpn:◆なにを　うってくれるの？@KEY()
@!
_SUB_CUSTMES_B_2;
←
◆Ｏｈ，　ｔｈａｎｋ　ｙｏｕ　ｓｏ　ｍｕｃｈ！　　Ｉｔ　ｗａｓ　ｗｅｌｌ　ｗｏｒｔｈ　ｔｈｅ　ｔｒｉｐ！

;jpn:◆サンキュー！↓
;jpn:　とおくからきた↓
;jpn:　かいが　あったわ。
@KEYNP()
@!
_SUB_CUSTMES_B_3;
←
◆Ｉ　ｃａｎ’ｔ　ｂｅｌｉｅｖｅ　ｉｔ！@KEY()↓
◆Ａｆｔｅｒ　Ｉ　ｔｏｏｋ　ａｌｌ　ｔｈｅ　ｔｒｏｕｂｌｅ　ｔｏ　ｇｅｔ　ｏｕｔ　ｈｅｒｅ！

;jpn:◆せっかくきたのに↓
;jpn:　ひどいわ！
@KEYNP()
@!
_SUB_CUSTMES_B_4;
@LOAD_GLOBAL_REG()
←
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｈｍｍｍ．．．　　Ｈｏｗ　ａｂｏｕｔ↓
　　@XCHG()＄@DSP_NUM(0)？@KEY()↓
◆Ｈｏｗ　ｄｏｅｓ　ｔｈａｔ　ｏｆｆｅｒ　ｓｔｒｉｋｅ　ｙｏｕ？↓

;◆@DSP_GOODS(0)？↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルね。@KEY()↓
;jpn:◆それで　いい？↓
@!
_SUB_CUSTMES_B_5;
←
◆Ｍｙ，　ｍｙ！↓
　　Ｙｏｕ　ｃａｎ’ｔ　ｄｏ　ｔｈａｔ　ｔｏ　ｍｅ！@KEY()↓
◆Ｗｅｌｌ，　ｈａｖｅ　ｙｏｕ　ｇｏｔ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｆｏｒ　ｓａｌｅ？@KEY()

;jpn:◆えーっ　こまったわ。↓
;jpn:　じゃあ　ほかにはなにか↓
;jpn:　うるものはあるの？@KEY()
@!
_SUB_CUSTMES_B_6;
←
◆Ａｌｒｅａｄｙ　ｇｏｔ　ｍｅ　ｏｎｅ　ｏｆ　ｔｈｏｓｅ．@KEY()↓
◆Ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｗｏｒｔｈｗｈｉｌｅ　ｆｏｒ　ｓａｌｅ？@KEY()

;jpn:◆それは　まにあってるわ！@KEY()↓
;jpn:◆なにを　うってくれるの？@KEY()
@!

;看板の客（子供）（ｋｉｄ）
_SUB_CUSTMES_C_1;
◆Ｈｉ！↓
　　Ｉｓ　ｔｈｉｓ　ａ　ｔｏｏｌ　ｓｈｏｐ？　　Ｃｏｏｌ！@KEY()↓
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｓｅｌｌｉｎｇ？@KEY()

;jpn:◆こんちわ！↓
;jpn:　どうぐやは　ここですよね。@KEY()↓
;jpn:◆なにを　うってくれますか？@KEY()
@!
_SUB_CUSTMES_C_2;
←
◆Ｔｈａｎｋｓ　ａ　ｌｏｔ！↓
　　Ｉｔ　ｓｕｒｅ　ｗａｓ　ｗｏｒｔｈ　ｉｔ　ｔｏ　ｃｏｍｅ　ａｌｌ　ｔｈｅ　ｗａｙ　ｏｕｔ　ｈｅｒｅ！

;jpn:◆ありがとうございます。↓
;jpn:　とおくからきた↓
;jpn:　かいが　ありました。
@KEYNP()
@!
_SUB_CUSTMES_C_3;
←
◆Ｏｈ，　ｃ’ｍｏｎ！@KEY()↓
◆Ｙｏｕ　ｈａｖｅ　ｎｏ　ｉｄｅａ　ｈｏｗ　ｍｕｃｈ　ｔｒｏｕｂｌｅ　ｉｔ　ｗａｓ　ｆｏｒ　ｍｅ　ｔｏ　ｇｅｔ　ｈｅｒｅ！

;jpn:◆せっかくきたのに↓
;jpn:　ひどいや！
@KEYNP()
@!
_SUB_CUSTMES_C_4;
@LOAD_GLOBAL_REG()
←
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｈｏｗ　ａｂｏｕｔ　@XCHG()＄@DSP_NUM(0)．．．@KEY()↓
◆Ｉｓ　ｔｈａｔ　ａ　ｆａｉｒ　ｔｒａｄｅ？↓

;jpn:◆@DSP_GOODS(0)ですか。↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルですね。@KEY()↓
;jpn:◆それで　いいですか？↓
@!
_SUB_CUSTMES_C_5;
←
◆Ｙｏｕ　ｄｏｎ’ｔ　ｔｈｉｎｋ　ｓｏ？　　ＯＫ，　ｈａｖｅ　ｙｏｕ　ｇｏｔ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ　ｔｈｅｎ？@KEY()

;jpn:◆ああ　そうですか。↓
;jpn:　ほかになにか↓
;jpn:　うるものはありますか？@KEY()
@!
_SUB_CUSTMES_C_6;
←
◆Ｕｈｈｈ，　Ｉ　ｃａｎ’ｔ　ｂｕｙ　ｔｈａｔ．．．@KEY()↓
◆Ｇｏｔ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？@KEY()

;jpn:◆それは　ぼくには↓
;jpn:　かえません！@KEY()↓
;jpn:◆なにを　うってくれますか？@KEY()
@!

;看板の客（江戸っ子）
_SUB_CUSTMES_D_1;
◆Ｈｉ，　ｈｏｗ　ａｒｅ　ｙａ？　　Ｉｓ　ｔｈｉｓ　ａ　ｔｏｏｌ　ｓｈｏｐ　ｏｒ　ｓｏｍｅｔｈｉｎｇ？@KEY()↓
◆Ｗｈａｔ　ａｒｅ　ｙｏｕ　ｓｅｌｌｉｎｇ，　ａｎｙｗａｙ？@KEY()

;jpn:◆ごめんよ！↓
;jpn:　どうぐやは　ここかい？@KEY()↓
;jpn:◆なにを　うってくれるんでい？@KEY()
@!
_SUB_CUSTMES_D_2;
←
◆Ｔｈａｎｋｓ！　　Ｉ　ｈａｖｅ　ｔｏ　ｓａｙ，　ｉｔ　ｗａｓ　ｗｅｌｌ　ｗｏｒｔｈ　ｍｙ　ｔｒｏｕｂｌｅ　ｔｏ　ｃｏｍｅ　ｏｕｔ　ｈｅｒｅ．

;jpn:◆ありがとよ！↓
;jpn:　とおくからきた↓
;jpn:　かいが　あったってぇもんだ。
@KEYNP()
@!
_SUB_CUSTMES_D_3;
←
◆Ｔｈａｔ’ｓ　ｊｕｓｔ　ｇｒｅａｔ！↓
　　Ｙｏｕ　ｃａｎ’ｔ　ｄｏ　ｔｈｉｓ　ｔｏ　ｍｅ！
;jpn:◆おっと　そいつは　あんまりだ！
@KEYNP()
@!
_SUB_CUSTMES_D_4;
@LOAD_GLOBAL_REG()
←
◆Ｔｈｅ　@DSP_GOODS(0)？↓
　　Ｉ’ｄ　ｏｆｆｅｒ　ａｂｏｕｔ↓
　　@XCHG()＄@DSP_NUM(0)　ｆｏｒ　ｔｈａｔ．@KEY()↓
◆Ｉｓ　ｉｔ　ａ　ｄｅａｌ？↓

;jpn:◆@DSP_GOODS(0)かい？↓
;@XCHG()
;jpn:　@DSP_NUM(0)ドルだな。@KEY()↓
;jpn:◆それで　いいかい？↓
@!
_SUB_CUSTMES_D_5;
←
◆Ｈａｖｅ　ｉｔ　ｙｏｕｒ　ｗａｙ．@KEY()↓
◆Ｄｉｄ　ｙｏｕ　ｓａｙ　ｙｏｕ　ｈａｖｅ　ｓｏｍｅ　ｏｔｈｅｒ　ｔｈｉｎｇｓ　ｆｏｒ　ｓａｌｅ？@KEY()

;jpn:◆ああ　そうかい。↓
;jpn:　そんなら　ほかになにか↓
;jpn:　うるものは　あるってぇのかい？@KEY()
@!
_SUB_CUSTMES_D_6;
←
◆Ｉ’ｍ　ｎｏｔ　ｉｎｔｅｒｅｓｔｅｄ　ｉｎ　ｏｎｅ　ｏｆ　ｔｈｏｓｅ．@KEY()↓
◆Ｃａｎ　ｙｏｕ　ｓｈｏｗ　ｍｅ　ａｎｙｔｈｉｎｇ　ｅｌｓｅ？@KEY()

;jpn:◆そいつぁ　かえねえな！@KEY()↓
;jpn:◆なにを　うってくれるんでい？@KEY()
@!

;タイムオーバー（ｔｉｍｅ ｏｖｅｒ）
MSG_CUSTOMER_RETRY_OVER;
@GOSUB(MSG_SUB_ZYUSHIN_CALL)
@CLRF(FLG_DELIVERY_CUSTOMER)
@CLRF(FLG_DELIVERY_CUSTOMER_B)
@CLRF(FLG_DELIVERY_CUSTOMER_C)
@CLRF(FLG_DELIVERY_CUSTOMER_D)
@OPEN(1)
◆Ｈｅｌｌｏ！↓
　　（ｇａｓｐ．．．　ｐａｎｔ．．．）@KEY()↓
◆Ｉ　ｓａｗ　ｙｏｕｒ　ｓｉｇｎ↓
　　（ｇａｓｐ．．．　ｐａｎｔ．．．），@KEY()↓
◆ａｎｄ　ｔｈｏｕｇｈｔ　Ｉ　ｓｈｏｕｌｄ　ｓｔｏｐ　ａｎｄ　ｂｕｙ　ｓｏｍｅｔｈｉｎｇ．@KEY()↓
◆Ｉ　ｔｒｉｅｄ　ａｎｄ　ｔｒｉｅｄ　ｔｏ　ｆｉｎｄ　ｉｔ↓
　　（ｇａｓｐ．．．　ｐａｎｔ．．．）↓
　　ｂｕｔ　ｎｏ　ｓｕｃｈ　ｌｕｃｋ．@KEY()↓
◆Ｉ　ｔｈｉｎｋ　ｙｏｕ　ｓｈｏｕｌｄ　ｇｉｖｅ　ｔｈｉｓ　ｕｐ　ａｎｄ　ｇｏ　ｈｏｍｅ．@KEY()↓
◆Ｉｆ　ｙｏｕ　ｔｏｏｋ　ｙｏｕｒ　ｂｕｓｉｎｅｓｓ　ｍｏｒｅ　ｓｅｒｉｏｕｓｌｙ，@KEY()↓
◆ｙｏｕ　ｗｏｕｌｄ　ｂｅ　ｍｏｒｅ　ｃｏｎｓｉｄｅｒａｔｅ　ｏｆ　ｙｏｕｒ　ｃｕｓｔｏｍｅｒｓ！@KEY()
@GOSUB(MSG_SUB_ZYUSHIN_PUT)
@CLRF(FLG_SYS_DISTLPT);テレポート許可
@!

;
;ショップＡ（売る、買う）
;

MSG_SUB_SHOP_A;
@CLRF(FLG_SHOPTEMP_2)
@GOSUB(MSG_SUB_SHOPMES_1)
;@WINR_MONEY()
_SHOP_A_MAIN;
<Ｂｕｙ>
<Ｓｅｌｌ>
;<かいにきた>
;<うりにきた>
@DSP_ITEM(2)
@SELGOTO(_SHOP_A_TAKE,_SHOP_A_SELL)
_SHOP_A_END;
@CHKFGOTO(FLG_SHOPTEMP_2,_SHOP_A_END2)
@GOSUB(MSG_SUB_SHOPMES_3)
@!
_SHOP_A_END2;
@GOSUB(MSG_SUB_SHOPMES_2)
;@SETF(FLG_SHOP_01)
@CLRF(FLG_SHOPTEMP_2)
@!

_SHOP_A_TAKE;
@GOSUB(MSG_SUB_SHOPMES_4)
;@WINR_MONEY()
@DSP_PL()
_SHOP_A_TAKE_SEL;
@GOSUB(MSG_SUB_SHOP_MENU)
@FALSE_GOTO(_SHOP_A_OTHER)
@GOSUB(_SUB_LUCKY_SAND)
@SAVE_REG()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SHOP_A_TAKE_ALLGOODSFULL)
@LOAD_REG()
@GOSUB(_SUB_GDS_TAKE)
@CHKFGOTO(FLG_SHOP_TOOK,_SHOP_A_THANKYOU)
@GOTO(_SHOP_A_OTHER)

_SHOP_A_SELL;
@GOSUB(MSG_SUB_Q_GOODSEMPTY)
@FALSE_GOTO(_SHOP_A_SELL_GDSEMP)
@GOSUB(_SUB_GDS_SELL)
@CHKFGOTO(FLG_SHOP_SOLD,_SHOP_A_THANKYOU)
@GOTO(_SHOP_A_OTHER)

_SHOP_A_THANKYOU;
;@CHKFGOTO(FLG_SHOP_ONET_DRUG1,_SHOP_A_THANKYOU2)
@GOSUB(MSG_SUB_SHOPMES_18)
;@GOTO(_SHOP_A_THANKYOU3)
;_SHOP_A_THANKYOU2;
;@GOSUB(MSG_SUB_SHOPMES_19)
;_SHOP_A_THANKYOU3;
@RESF(FLG_SHOP_TOOK)
@RESF(FLG_SHOP_SOLD)
_SHOP_A_OTHER;
@GOSUB(MSG_SUB_SHOPMES_20)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_SHOP_A_OTHER_YES,_SHOP_A_END)
@GOTO(_SHOP_A_END)
_SHOP_A_OTHER_YES;
@GOSUB(MSG_SUB_SHOPMES_21)
@GOTO(_SHOP_A_MAIN)

_SHOP_A_TAKE_ALLGOODSFULL;
@GOSUB(MSG_SUB_SHOPMES_12)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_SHOP_A_SELL,_SHOP_A_END)
@GOTO(_SHOP_A_END)

_SHOP_A_SELL_GDSEMP;
@GOSUB(MSG_SUB_SHOPMES_16)
@GOTO(_SHOP_A_OTHER)

;
;ショップＢ（売る）
;

MSG_SUB_SHOP_B;
@CLRF(FLG_SHOPTEMP_2)
_SHOP_B_TAKE;
←
@GOSUB(MSG_SUB_SHOPMES_1)
_SHOP_B_YES;
@GOSUB(MSG_SUB_SHOPMES_4)
;@WINR_MONEY()
@DSP_PL()
_SHOP_B_TAKE_SEL;
@GOSUB(MSG_SUB_SHOP_MENU)
@FALSE_GOTO(_SHOP_B_END)
@SAVE_REG()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SHOP_B_TAKE_ALLGOODSFULL)
@LOAD_REG()
@GOSUB(_SUB_LUCKY_SAND)
@GOSUB(_SUB_GDS_TAKE)
@CHKFGOTO(FLG_SHOP_TOOK,_SHOP_B_THANKYOU)
@GOTO(_SHOP_B_OTHER)
_SHOP_B_THANKYOU;
;@CHKFGOTO(FLG_SHOP_ONET_DRUG1,_SHOP_B_THANKYOU2)
@GOSUB(MSG_SUB_SHOPMES_18)
;@GOTO(_SHOP_B_THANKYOU3)
;_SHOP_B_THANKYOU2;
;@GOSUB(MSG_SUB_SHOPMES_19)
;_SHOP_B_THANKYOU3;
@RESF(FLG_SHOP_TOOK)
@RESF(FLG_SHOP_SOLD)
_SHOP_B_OTHER;
@GOSUB(MSG_SUB_SHOPMES_20)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_SHOP_B_YES,_SHOP_B_END)
_SHOP_B_END;
@CHKFGOTO(FLG_SHOPTEMP_2,_SHOP_B_END2)
@GOSUB(MSG_SUB_SHOPMES_3)
@!
_SHOP_B_END2;
;@SETF(FLG_SHOP_ONET_DRUG1)
@CLRF(FLG_SHOPTEMP_2)
@GOSUB(MSG_SUB_SHOPMES_2)
@!
_SHOP_B_TAKE_ALLGOODSFULL;
@GOSUB(MSG_SUB_SHOPMES_12)
@!

MSG_SUB_SHOP_C;
@CLRF(FLG_SHOPTEMP_2)
_SHOP_C_TAKE;
←
@GOSUB(MSG_SUB_SHOPMES_1)
_SHOP_C_YES;
@GOSUB(MSG_SUB_SHOPMES_4)
;@WINR_MONEY()
@DSP_PL()
_SHOP_C_TAKE_SEL;
@GOSUB(MSG_SUB_SHOP_MENU)
@FALSE_GOTO(_SHOP_C_END)
@SAVE_REG()
@Q_GOODSFULL(PC_ALL)
@FALSE_GOTO(_SHOP_C_TAKE_ALLGOODSFULL)
@LOAD_REG()
@GOSUB(_SUB_LUCKY_SAND)
@GOSUB(_SUB_GDS_TAKE)
@CHKFGOTO(FLG_SHOP_TOOK,_SHOP_C_THANKYOU)
@!
_SHOP_C_THANKYOU;
@GOSUB(MSG_SUB_SHOPMES_18)
@RESF(FLG_SHOP_TOOK)
@RESF(FLG_SHOP_SOLD)
_SHOP_C_OTHER;
@GOSUB(MSG_SUB_SHOPMES_20)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_SHOP_C_YES,_SHOP_C_END)
_SHOP_C_END;
@CHKFGOTO(FLG_SHOPTEMP_2,_SHOP_C_END2)
@GOSUB(MSG_SUB_SHOPMES_3)
@!
_SHOP_C_END2;
@CLRF(FLG_SHOPTEMP_2)
@GOSUB(MSG_SUB_SHOPMES_2)
@!
_SHOP_C_TAKE_ALLGOODSFULL;
@GOSUB(MSG_SUB_SHOPMES_12)
@!

;
;「かう」関係の一連の処理
;

_SUB_GDS_TAKE;
@GOSUB(_SUB_SHOP_PART_1)
@TRUE_GOTO(_GDS_TAKE_NOMONEY)
@LOAD_REG()
@GOSUB(MSG_SUB_SHOPMES_5)
@Q_MEMBER(2)
@FALSE_GOTO(_GDS_TAKE_WHO)
@GET_ORDER_PLAYER(1)
@GOTO(_GDS_TAKE_WHO2)
_GDS_TAKE_WHO;
@LOAD_REG()
@GOSUB(MSG_SUB_SHOPMES_6)
@GOSUB(MSG_SEL_GOODSIN)
@FALSE_GOTO(_GDS_TAKE_NO)
_GDS_TAKE_WHO2;
@SAVE_REG()
;
@XCHG()
@Q_GOODSFULL(0)
@FALSE_GOTO(_GDS_TAKE_SEL_GOODSFULL)
@LOAD_REG()
;
@GOODS_TYPE_P(TYPE_EQUIP)
@FALSE_GOTO(_GDS_TAKE_NONEQUIP)
@GOSUB(_SUB_SHOP_PART_1B)
@GOSUB(_SUB_SHOP_PART_2)
@FALSE_GOTO(_GDS_TAKE_UNEQUIP)
@LOAD_GLOBAL_REG()
@GOODSOUT_PLAYER(0,0)
@GOSUB(_SUB_GDS_TAKE_GOODSIN)
@GOSUB(MSG_SUB_SHOP_SE)
@SAVE_REG()		;%PLAYER_ID:%NOB
_GDS_TAKE_EQUIP;
@GOSUB(MSG_SUB_SHOPMES_7)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_GDS_TAKE_EQUIP_OK,_GDS_TAKE_END)
@GOTO(_GDS_TAKE_END)	
_GDS_TAKE_EQUIP_OK;
@SE(SE_se73_my_fitout)	
@GOSUB(_SUB_SHOP_PART_3)
@LOAD_REG()
@EQUIP_PLAYER_GOODS(0,0)
@SAVE_REG()
@GOSUB(_SUB_SHOP_PART_3B)
@LOAD_REG()
@XCHG()
@FALSE_GOTO(_GDS_TAKE_END)
@GOSUB(_SUB_SHOP_PART_4)
;
@FALSE_GOTO(_GDS_TAKE_END)
;
@GOSUB(MSG_SUB_SHOPMES_8)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_GDS_TAKE_SELL,_GDS_TAKE_END)
@GOTO(_GDS_TAKE_END)
_GDS_TAKE_SELL;
@GOSUB(MSG_SUB_SHOP_SE)
@GOSUB(_SUB_SHOP_PART_5)
_GDS_TAKE_OK;
@SETF(FLG_SHOP_TOOK)
_GDS_TAKE_END;
@CLRF(FLG_SHOPTEMP_3)
@!
_GDS_TAKE_UNEQUIP;
@GOSUB(_SUB_SHOP_PART_6)
@GOSUB(MSG_SUB_SHOPMES_9)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_GDS_TAKE_NONEQUIP,_GDS_TAKE_NO)
_GDS_TAKE_NO;
@GOSUB(MSG_SUB_SHOPMES_10)
@GOTO(_GDS_TAKE_END)

_GDS_TAKE_SEL_GOODSFULL;
←
;◆@DSP_NAME(0)はこれいじょう↓
;　にもつを　もてません。@KEY()↓;
;◆ほかのひとが　もちますか？↓
@GOSUB(MSG_SUB_SHOPMES_22)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_GDS_TAKE_WHO,_GDS_TAKE_NO)
@GOTO(_GDS_TAKE_NO)

_GDS_TAKE_NOMONEY;
@GOSUB(MSG_SUB_SHOPMES_11)
@GOTO(_GDS_TAKE_END)

_GDS_TAKE_NONEQUIP
@GOSUB(_SUB_GDS_TAKE_GOODSIN)
@GOSUB(MSG_SUB_SHOP_SE)
@GOTO(_GDS_TAKE_OK)

;
;ショップでの「うる」の全処理
;

_SUB_GDS_SELL;
_GDS_SELL;
@GOSUB(MSG_SUB_SHOPMES_13)
;@WINR_MONEY()
@GOSUB(MSG_SEL_GOODS)
@FALSE_GOTO(_GDS_SELL_END)
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@FALSE_GOTO(_GDS_SELL_UNABLE)
@GOSUB(MSG_SUB_SHOPMES_14)
@GOSUB(MSG_SUB_YESNO)
@GOSUB(MSG_SUB_SELQ_FORMOON)
@ONGOTO(_GDS_SELL_MONEY_YES,_GDS_SELL_MONEY_NO)
@GOTO(_GDS_SELL_MONEY_NO)

_GDS_SELL_MONEY_YES;
@GOSUB(_SUB_SHOP_PART_7)
@GOSUB(MSG_SUB_SHOP_SE)
_GDS_SELL_END;
@!

_GDS_SELL_MONEY_NO;
@GOSUB(MSG_SUB_SHOPMES_15)
@GOTO(_GDS_SELL_END)

_GDS_SELL_UNABLE;
@GOSUB(MSG_SUB_SHOPMES_17)
@GOTO(_GDS_SELL_END)

;
;サブルーチン（ローカル）
;

_SUB_SHOP_PART_1;
@XCHG()
@GOODS_TAKE_MONEY(0)
@SAVE_REG()
@XCHG()
@Q_MONEY(0)
@!

_SUB_SHOP_PART_1B;
@Q_EQUIP_ATTR(0)
@EQ(1)
@FALSE_GOTO(_PART_1B_END)
@SETF(FLG_SHOPTEMP_3)
_PART_1B_END;
@!

_SUB_SHOP_PART_2;
@LOAD_REG()
@GOODSIN_PLAYER(0,0)
@SAVE_GLOBAL_REG()
@Q_EQUIP_PLAYER_GOODS(0,0)
@!

_SUB_SHOP_PART_3;
@LOAD_REG()
@SET_REG(0)

◆（@DSP_NAME(0)’ｓ@CHKFGOTO(FLG_SHOPTEMP_3,_PART_3_2)

;jpn:◆（@DSP_NAME(0)の
@CHKFGOTO(FLG_SHOPTEMP_3,_PART_3_2)
　ｄｅｆｅｎｓｅ↓
　　ｃｈａｎｇｅｄ　
;jpn:しゅびりょくが↓

@ONGOTO(_PART_3_NESS,_PART_3_PAULA,_PART_3_JEFF,_PART_3_POO)
_PART_3_NESS;
　@DSP_STS(STS_PC_DEFENSE_NES)
@!
_PART_3_PAULA;
　@DSP_STS(STS_PC_DEFENSE_PAULA)
@!
_PART_3_JEFF;
　@DSP_STS(STS_PC_DEFENSE_JEFF)
@!
_PART_3_POO;
　@DSP_STS(STS_PC_DEFENSE_POO)
@!
_PART_3_2;
　ｏｆｆｅｎｓｅ↓
　　ｃｈａｎｇｅｄ　
;jpn:こうげきりょくが↓

@ONGOTO(_PART_3_2_NESS,_PART_3_2_PAULA,_PART_3_2_JEFF,_PART_3_2_POO)
_PART_3_2_NESS;
　@DSP_STS(STS_PC_OFFENSE_NES)
@!
_PART_3_2_PAULA;
　@DSP_STS(STS_PC_OFFENSE_PAULA)
@!
_PART_3_2_JEFF;
　@DSP_STS(STS_PC_OFFENSE_JEFF)
@!
_PART_3_2_POO;
　@DSP_STS(STS_PC_OFFENSE_POO)
@!

_SUB_SHOP_PART_3B;
　ｔｏ
;jpn:から
@SET_REG(0)
@CHKFGOTO(FLG_SHOPTEMP_3,_PART_3B_2)
@ONGOTO(_PART_3B_NESS,_PART_3B_PAULA,_PART_3B_JEFF,_PART_3B_POO)
_PART_3B_NESS;
　　@DSP_STS(STS_PC_DEFENSE_NES)）@KEY()↓
;jpn:@DSP_STS(STS_PC_DEFENSE_NES)になった。）@KEY()↓
@!
_PART_3B_PAULA;
　　@DSP_STS(STS_PC_DEFENSE_PAULA)）@KEY()↓
;jpn:@DSP_STS(STS_PC_DEFENSE_PAULA)になった。）@KEY()↓
@!
_PART_3B_JEFF;
　　@DSP_STS(STS_PC_DEFENSE_JEFF)）@KEY()↓
;jpn:@DSP_STS(STS_PC_DEFENSE_JEFF)になった。）@KEY()↓
@!
_PART_3B_POO;
　　@DSP_STS(STS_PC_DEFENSE_POO)）@KEY()↓
;jpn:@DSP_STS(STS_PC_DEFENSE_POO)になった。）@KEY()↓
@!

_PART_3B_2;
@ONGOTO(_PART_3B_2_NESS,_PART_3B_2_PAULA,_PART_3B_2_JEFF,_PART_3B_2_POO)
_PART_3B_2_NESS;
　　@DSP_STS(STS_PC_OFFENSE_NES)）@KEY()↓
;jpn:@DSP_STS(STS_PC_OFFENSE_NES)になった。）@KEY()↓
@!
_PART_3B_2_PAULA;
　　@DSP_STS(STS_PC_OFFENSE_PAULA)）@KEY()↓
;jpn:@DSP_STS(STS_PC_OFFENSE_PAULA)になった。）@KEY()↓
@!
_PART_3B_2_JEFF;
　　@DSP_STS(STS_PC_OFFENSE_JEFF)）@KEY()↓
;jpn:@DSP_STS(STS_PC_OFFENSE_JEFF)になった。）@KEY()↓
@!
_PART_3B_2_POO;
　　@DSP_STS(STS_PC_OFFENSE_POO)）@KEY()↓
;jpn:@DSP_STS(STS_PC_OFFENSE_POO)になった。）@KEY()↓
@!

_SUB_SHOP_PART_4;
@XCHG()
@SAVE_REG()
@GET_PLAYER_GOODS(0,0)
@GOODS_SELL_MONEY(0)
@!

_SUB_SHOP_PART_5;
@MONEYIN(0)
@WINR_MONEY()
@LOAD_REG()
@GOODSOUT_PLAYER(0,0)
@!

_SUB_SHOP_PART_6;
@LOAD_GLOBAL_REG()
@GOODSOUT_PLAYER(0,0)
@LOAD_REG()
@XCHG()
@!

_SUB_SHOP_PART_7;
@MONEYIN(0)		
@LOAD_REG()		
@GOODSOUT_PLAYER(0,0)	
@WINR_MONEY()
@SETF(FLG_SHOPTEMP_2)
@SETF(FLG_SHOP_SOLD)
@!

_SUB_GDS_TAKE_GOODSIN;
@LOAD_REG()
@GOODS_TAKE_MONEY(0)
@XCHG()
@MONEYOUT(0)
@WINR_MONEY()
@LOAD_REG()
@GOODSIN_PLAYER(0,0)
@SETF(FLG_SHOPTEMP_2)
@!

_SUB_LUCKY_SAND;
@SAVE_REG()
@EQ(GDS_FOOD_LUCKY_SAND_A)
@TRUE_GOTO(_LUCKY_SAND_00)
@LOAD_REG()
@!
_LUCKY_SAND_00;
@RAND(15)
@CMP(7,0)
@FALSE_GOTO(_LUCKY_SAND_A)
@RAND(8)
@CMP(4,0)
@FALSE_GOTO(_LUCKY_SAND_B)
@RAND(4)
@CMP(3,0)
@FALSE_GOTO(_LUCKY_SAND_C)
@RAND(1)
@FALSE_GOTO(_LUCKY_SAND_D)
@RAND(2)
@TRUE_GOTO(_LUCKY_SAND_E)
_LUCKY_SAND_F;
@SET_LOOPREG(GDS_FOOD_LUCKY_SAND_F)
@SET_REG(1)
@XCHG()
@!
_LUCKY_SAND_E;
@SET_LOOPREG(GDS_FOOD_LUCKY_SAND_E)
@SET_REG(1)
@XCHG()
@!
_LUCKY_SAND_D;
@SET_LOOPREG(GDS_FOOD_LUCKY_SAND_D)
@SET_REG(1)
@XCHG()
@!
_LUCKY_SAND_C;
@SET_LOOPREG(GDS_FOOD_LUCKY_SAND_C)
@SET_REG(1)
@XCHG()
@!
_LUCKY_SAND_B;
@SET_LOOPREG(GDS_FOOD_LUCKY_SAND_B)
@SET_REG(1)
@XCHG()
@!
_LUCKY_SAND_A;
@LOAD_REG()
@!

;
;サブルーチン（グローバル）
;

MSG_SUB_Q_GOODSEMPTY;
_SUB_Q_GOODSEMPTY;
@SET_LOOPREG(1)
_Q_GDSEMP_LOOP;
@SET_REG(1)
@Q_MEMBER(0)
@TRUE_GOTO(_Q_GDSEMP_END2)
@GET_ORDER_PLAYER(0)
@GET_PLAYER_GOODS(0,1)
@XCHG()
@TRUE_GOTO(_Q_GDSEMP_END)
@INC()
@GOTO(_Q_GDSEMP_LOOP)
_Q_GDSEMP_END2;
@EQ(0)
_Q_GDSEMP_END;
@!

MSG_SEL_GOODS;
@DSP_PL()
@Q_MEMBER(2)
@TRUE_GOTO(_SEL_GOODS_02)
@SEL_PQ(_SEL_GOODS1,_SEL_GOODS2,_SEL_GOODS3,_SEL_GOODS4,0)
@SET_REG(0)
@FALSE_GOTO(_SEL_GOODS_END)
@WIN_CHK_ITEM(2)
@FALSE_GOTO(MSG_SEL_GOODS)
@WIN_SEL_ITEMQ(2)
@FALSE_GOTO(MSG_SEL_GOODS)
_SEL_GOODS_END;
@SELECT_WIN(2)
@CLOSE()
@SELECT_WIN(1)
@XCHG()
@!
_SEL_GOODS_02;			;テスト05/25
@GET_ORDER_PLAYER(1)
@SET_REG(0)
@SAVE_GLOBAL_REG()
@SAVE_WIN()
@LOAD_GLOBAL_REG()
@DSP_PLAYER_GOODS(2,0)
@LOAD_GLOBAL_REG()
@WIN_SEL_ITEMQ(2)
@SAVE_GLOBAL_REG()
@SELECT_WIN(2)
@CLOSE()
@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
@FALSE_GOTO(_SEL_GOODS_02_CANCEL)
@XCHG()
@!
_SEL_GOODS_02_CANCEL;
@!

MSG_SEL_GOODS_B;		;バトル用
@Q_MEMBER(2)
@TRUE_GOTO(_SEL_GOODS_B_02)
@SEL_PQ(_SEL_GOODS1,_SEL_GOODS2,_SEL_GOODS3,_SEL_GOODS4,0)
@SET_REG(0)
@FALSE_GOTO(_SEL_GOODS_END_B)
@WIN_CHK_ITEM(2)
@FALSE_GOTO(MSG_SEL_GOODS_B)
@WIN_SEL_ITEMQ(2)
@FALSE_GOTO(MSG_SEL_GOODS_B)
_SEL_GOODS_END_B;
@SELECT_WIN(2)
@CLOSE()
@SELECT_WIN(14)
@XCHG()
@!
_SEL_GOODS_B_02;		;テスト05/25
@GET_ORDER_PLAYER(1)
@SET_REG(0)
@SAVE_GLOBAL_REG()
@SAVE_WIN()
@LOAD_GLOBAL_REG()
@DSP_PLAYER_GOODS(2,0)
@LOAD_GLOBAL_REG()
@WIN_SEL_ITEMQ(2)
@SAVE_GLOBAL_REG()
@SELECT_WIN(2)
@CLOSE()
@SELECT_WIN(14)
@LOAD_GLOBAL_REG()
@FALSE_GOTO(_SEL_GOODS_B_02_CANCEL)
@XCHG()
@!
_SEL_GOODS_B_02_CANCEL;
@!


;選択されキャラのグッズパネルの表示

MSG_SEL_GOODSIN;
;副=GOODS_ID
@SEL_PQ(_SEL_GOODS1,_SEL_GOODS2,_SEL_GOODS3,_SEL_GOODS4,2)
					;パネルでキャラ選択。
;@SAVE_GLOBAL_REG()
;@FALSE_GOTO(_SEL_GOODSIN_END)
;@XCHG()
;@Q_GOODSFULL(0)
;@TRUE_GOTO(_SEL_GOODSIN_END)
;テスト用スクリプト
;@SELECT_WIN(2)
;@CLOSE()
;@SELECT_WIN(1)
;@LOAD_GLOBAL_REG()
;@SAVE_GLOBAL_REG()
;@XCHG()
;←
;◆@DSP_NAME(0)はこれいじょう↓
;　にもつを　もてません。@KEY()↓;
;@XCHG()
;@GOTO(MSG_SEL_GOODSIN)

_SEL_GOODSIN_END;
;@LOAD_GLOBAL_REG()
@SELECT_WIN(2)
@CLOSE()
@SELECT_WIN(1)
@!

MSG_SEL_GOODSIN_T;
;副=GOODS_ID
@SEL_PQ(_SEL_GOODS1B,_SEL_GOODS2B,_SEL_GOODS3B,_SEL_GOODS4B,2)
					;パネルでキャラ選択。
@SAVE_GLOBAL_REG()
@FALSE_GOTO(_SEL_GOODSIN_T_END)
@XCHG()
@Q_GOODSFULL(0)
@TRUE_GOTO(_SEL_GOODSIN_T_END)
;テスト用スクリプト
;@SELECT_WIN(2)
;@CLOSE()
;@SELECT_WIN(1)
@LOAD_GLOBAL_REG()
;@SAVE_GLOBAL_REG()
@XCHG()
;◆@DSP_NAME(0)はこれいじょう↓
;　にもつを　もてません。@KEY()↓;
;@XCHG()
@GOTO(MSG_SEL_GOODSIN_T)

_SEL_GOODSIN_T_END;
@LOAD_GLOBAL_REG()
@SELECT_WIN(44)
@CLOSE()
@SELECT_WIN(1)
@!

_SEL_GOODS1;
@SAVE_WIN()
@DSP_PLAYER_GOODS(2,PC_NESS)
@!

_SEL_GOODS2;
@SAVE_WIN()
@DSP_PLAYER_GOODS(2,PC_PAULA)
@!

_SEL_GOODS3;
@SAVE_WIN()
@DSP_PLAYER_GOODS(2,PC_JEFF)
@!

_SEL_GOODS4;
@SAVE_WIN()
@DSP_PLAYER_GOODS(2,PC_POO)
@!

_SEL_GOODS1B;
@SAVE_WIN()
@DSP_PLAYER_GOODS(44,PC_NESS)
@!

_SEL_GOODS2B;
@SAVE_WIN()
@DSP_PLAYER_GOODS(44,PC_PAULA)
@!

_SEL_GOODS3B;
@SAVE_WIN()
@DSP_PLAYER_GOODS(44,PC_JEFF)
@!

_SEL_GOODS4B;
@SAVE_WIN()
@DSP_PLAYER_GOODS(44,PC_POO)
@!
