; EarthBound CC asset PSI_ARRANGEMENT_32.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cc-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CC:ED0E..CC:EEB4 AssetPsiArrangement32

; ---------------------------------------------------------------------------
; CC:EEB4

; AssetPsiArrangement32End
CCEEB4_AssetPsiArrangement32End:
