; EarthBound CC asset psianims/palettes/15.pal.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cc-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CC:F4F7..CC:F4FF AssetPsianimsPalettes15Pal

; ---------------------------------------------------------------------------
; CC:F4FF

; AssetPsianimsPalettes15PalEnd
CCF4FF_AssetPsianimsPalettes15PalEnd:
