; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/cc/asset_psianims_palettes_23_pal.asm

hirom
org $CCF537


; Original data gap before CCF53F_AssetPsianimsPalettes23PalEnd:
db $00,$00,$1C,$00,$8C,$02,$40,$72

CCF53F_AssetPsianimsPalettes23PalEnd:
