; EarthBound CC asset table data/psi_anim_cfg.asm.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cc-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CC:F04D..CC:F1E5 TablePsiAnimCfg

; ---------------------------------------------------------------------------
; CC:F1E5

; TablePsiAnimCfgEnd
CCF1E5_TablePsiAnimCfgEnd:
