; EarthBound D3 asset SPRITE_0496.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:6A80..D3:6B40 AssetSprite0496

; ---------------------------------------------------------------------------
; D3:6B40

; AssetSprite0496End
D36B40_AssetSprite0496End:
