; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0380.asm

hirom
org $D31380

!D31440_AssetSprite0380End = SPRITE_0381

; Original terminal data gap ending at $D31440
db $00,$00,$3F,$3F,$38,$3F,$38,$3F,$38,$3F,$3F,$38,$FF,$FF,$3D,$23
db $00,$00,$3F,$3F,$3F,$38,$3F,$38,$3F,$38,$20,$20,$FF,$FF,$22,$3C
db $00,$00,$F8,$F8,$38,$F8,$38,$F8,$38,$F8,$F8,$38,$FE,$FE,$58,$58
db $00,$00,$F8,$F8,$F8,$38,$F8,$38,$F8,$38,$08,$08,$FE,$FE,$A8,$A8
db $7C,$73,$5E,$7F,$FF,$B0,$FF,$B0,$5F,$51,$06,$2A,$42,$47,$20,$2C
db $72,$7C,$5F,$5E,$90,$DF,$B0,$FF,$61,$6F,$59,$55,$7C,$78,$33,$33
db $2C,$6C,$82,$AE,$82,$96,$82,$D6,$02,$56,$02,$A6,$04,$94,$08,$C8
db $94,$94,$D2,$D2,$EA,$EA,$AA,$AA,$AA,$AA,$5A,$5A,$6C,$6C,$38,$38
db $18,$1A,$3F,$3F,$3F,$3F,$1F,$1F,$0F,$0F,$07,$1F,$0B,$7F,$07,$1F
db $1D,$1D,$2F,$2F,$3F,$3F,$1F,$1F,$0F,$0F,$1F,$07,$7F,$0B,$1F,$07
db $3E,$FE,$FF,$FB,$F9,$F9,$FE,$FE,$FC,$FC,$F8,$F8,$F0,$FE,$F0,$F8
db $3E,$3E,$FB,$F9,$F9,$FF,$FE,$FE,$FC,$FC,$F8,$F8,$FE,$F0,$F8,$F0
