; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0567.asm

hirom
org $D39FC0

!D3A080_AssetSprite0567End = SPRITE_0568

; Original terminal data gap ending at $D3A080
db $01,$01,$0F,$0F,$1F,$1F,$3F,$3F,$FF,$FF,$3F,$3F,$7F,$7F,$FF,$FF
db $01,$01,$0F,$0F,$10,$10,$25,$25,$E9,$E9,$3F,$3F,$7F,$7F,$FF,$FF
db $00,$00,$E0,$E0,$F0,$F0,$F8,$F8,$FE,$FE,$F8,$F8,$FC,$FC,$FE,$FE
db $00,$00,$E0,$E0,$10,$10,$48,$48,$2E,$2E,$F8,$F8,$FC,$FC,$FE,$FE
db $BF,$BF,$BF,$BF,$7F,$7F,$6F,$6F,$D7,$D7,$F8,$F8,$87,$BF,$58,$7F
db $BF,$FF,$BF,$DF,$7F,$6F,$6F,$77,$D7,$B8,$F8,$9F,$BF,$C7,$67,$40
db $FA,$FA,$FA,$FA,$FC,$FC,$EC,$EC,$D2,$D2,$3A,$3A,$C2,$FA,$34,$FC
db $FA,$FE,$FA,$F6,$FC,$EC,$EC,$DC,$D2,$3E,$3A,$F6,$FA,$C6,$CC,$04
db $3E,$3F,$3E,$3F,$3F,$3F,$22,$3F,$7D,$7F,$43,$7F,$3C,$FF,$00,$7F
db $21,$20,$21,$20,$3A,$3A,$3D,$20,$5F,$5D,$5F,$43,$FF,$3C,$7F,$00
db $F8,$F8,$F8,$F8,$F0,$F8,$78,$F8,$B8,$F8,$8C,$FC,$84,$FF,$78,$FC
db $08,$08,$08,$08,$B8,$B0,$F8,$78,$88,$88,$74,$04,$FF,$84,$FC,$78
