; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0576.asm

hirom
org $D3A680

!D3A740_AssetSprite0576End = SPRITE_0577

; Original terminal data gap ending at $D3A740
db $00,$00,$0F,$0F,$34,$30,$55,$40,$40,$40,$52,$40,$32,$30,$3C,$3C
db $00,$00,$0F,$0F,$3F,$3F,$7F,$7F,$7F,$7F,$77,$7F,$33,$2F,$3D,$2B
db $00,$00,$70,$70,$88,$88,$14,$04,$A4,$04,$52,$02,$16,$02,$86,$82
db $00,$00,$70,$70,$F8,$F8,$FC,$FC,$FC,$FC,$FE,$FE,$FE,$FE,$FE,$FE
db $3E,$3E,$7F,$7F,$3F,$3C,$3F,$3C,$17,$17,$08,$08,$06,$06,$07,$07
db $3F,$29,$7F,$40,$3C,$23,$3C,$2B,$17,$18,$08,$0F,$06,$07,$07,$04
db $46,$42,$C4,$C4,$C4,$C4,$C8,$48,$90,$90,$20,$20,$C0,$C0,$A0,$A0
db $7E,$FE,$DC,$7C,$DC,$BC,$48,$B8,$90,$70,$20,$E0,$C0,$C0,$A0,$60
db $0F,$0F,$0E,$0E,$08,$08,$08,$0F,$04,$07,$07,$07,$0E,$7E,$07,$1F
db $0F,$08,$0E,$09,$08,$0F,$0F,$0F,$07,$07,$07,$06,$7A,$09,$1F,$07
db $D0,$D0,$F8,$D8,$68,$68,$30,$F0,$20,$E0,$40,$40,$40,$7E,$80,$F8
db $D0,$B0,$D8,$88,$68,$D8,$F0,$F0,$E0,$E0,$40,$C0,$7E,$C0,$F8,$80
