; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0635.asm

hirom
org $D3D2C0

!D3D380_AssetSprite0635End = SPRITE_0636

; Original terminal data gap ending at $D3D380
db $07,$07,$1C,$18,$13,$10,$3D,$29,$38,$30,$30,$20,$72,$50,$46,$44
db $07,$07,$1F,$1F,$1F,$1F,$3F,$3F,$3F,$3F,$3F,$3F,$7F,$7F,$7F,$7F
db $70,$70,$88,$88,$96,$06,$07,$01,$1B,$01,$15,$05,$63,$03,$21,$01
db $70,$70,$F8,$F8,$FE,$FE,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
db $48,$40,$44,$40,$FB,$C0,$7F,$7B,$07,$07,$0B,$0C,$10,$1F,$29,$3F
db $7F,$7F,$7F,$7F,$FF,$FF,$7F,$7F,$07,$07,$08,$0C,$10,$1F,$28,$3F
db $8F,$03,$97,$03,$EE,$06,$F8,$C8,$F0,$F0,$E8,$18,$04,$FC,$12,$FE
db $FF,$FF,$FF,$FF,$FE,$FE,$F8,$F8,$F0,$F0,$08,$18,$04,$FC,$12,$FE
db $38,$3F,$18,$1F,$0F,$0F,$07,$07,$04,$04,$07,$3F,$09,$FF,$1E,$3F
db $28,$3F,$18,$1F,$0F,$0F,$07,$07,$04,$07,$3F,$05,$F9,$0F,$3F,$1E
db $0F,$FF,$19,$F9,$FE,$FE,$E0,$E0,$A0,$A0,$90,$FC,$78,$FF,$00,$FC
db $0B,$FD,$09,$FF,$FE,$FE,$E0,$E0,$A0,$E0,$9C,$F0,$FF,$78,$FC,$00
