; EarthBound D3 asset SPRITE_0564.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:9D80..D3:9E40 AssetSprite0564

; ---------------------------------------------------------------------------
; D3:9E40

; AssetSprite0564End
D39E40_AssetSprite0564End:
