; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0399.asm

hirom
org $D321C0

!D32280_AssetSprite0399End = SPRITE_0400

; Original terminal data gap ending at $D32280
db $03,$03,$16,$15,$2E,$3D,$57,$6F,$57,$7F,$47,$7F,$6F,$7F,$3F,$3F
db $03,$03,$14,$15,$2C,$3D,$47,$6F,$57,$6F,$47,$7F,$6F,$7F,$3F,$3F
db $E0,$E0,$B4,$54,$BA,$5E,$F5,$FB,$F5,$FF,$F1,$FF,$FA,$FE,$FE,$FE
db $E0,$E0,$14,$54,$1A,$5E,$F1,$FB,$F5,$FB,$F1,$FF,$FA,$FE,$FE,$FE
db $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F,$3F,$3F,$3F,$3F,$1F,$1F,$2B,$37
db $7F,$7F,$7F,$7F,$7F,$7F,$7F,$7F,$3F,$3F,$3F,$3F,$1F,$1F,$23,$37
db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FE,$FE,$FE,$FC,$FC,$EA,$F6
db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$FE,$FE,$FE,$FC,$FC,$E2,$F6
db $6A,$6D,$77,$7F,$2A,$35,$1A,$1D,$0F,$0F,$17,$3F,$0E,$FF,$00,$3F
db $68,$5D,$77,$5F,$20,$35,$18,$1D,$0F,$0F,$31,$1F,$FF,$0E,$3F,$00
db $BD,$5D,$EE,$FE,$AC,$54,$B8,$78,$C8,$F8,$BC,$FC,$7C,$FF,$38,$FC
db $1D,$5B,$EE,$FE,$04,$54,$38,$78,$C8,$F8,$84,$FC,$C7,$7C,$FC,$38
