; EarthBound D3 asset SPRITE_0354.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:0000..D3:00C0 AssetSprite0354

; ---------------------------------------------------------------------------
; D3:00C0

; AssetSprite0354End
D300C0_AssetSprite0354End:
