; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0597.asm

hirom
org $D3B640

!D3B700_AssetSprite0597End = SPRITE_0598

; Original terminal data gap ending at $D3B700
db $FF,$FF,$BF,$FF,$67,$5F,$4C,$7F,$3F,$3F,$2F,$3F,$FE,$FF,$2F,$3F
db $FF,$FF,$FF,$FF,$5F,$47,$5F,$5C,$3F,$3F,$37,$27,$F8,$F8,$3F,$2F
db $80,$80,$F8,$F8,$FF,$FF,$37,$FF,$FE,$FE,$FA,$FE,$6E,$FE,$FE,$BE
db $80,$80,$F8,$F8,$FF,$FF,$FF,$37,$FE,$FE,$F6,$F2,$1E,$0E,$BE,$FE
db $7F,$58,$2F,$20,$3F,$3C,$1F,$16,$0B,$08,$07,$07,$0F,$0D,$1E,$1B
db $58,$7F,$20,$3F,$3C,$3F,$16,$1F,$08,$0F,$07,$07,$0D,$0D,$1B,$1B
db $FC,$7C,$F8,$38,$F8,$38,$D0,$10,$A0,$20,$E0,$60,$F0,$F0,$D0,$F0
db $7C,$FC,$38,$F8,$38,$F8,$10,$F0,$20,$E0,$60,$60,$F0,$F0,$F0,$D0
db $1F,$1F,$1F,$17,$1A,$1B,$7F,$7F,$7F,$7F,$2C,$7F,$18,$FF,$00,$3F
db $1F,$1F,$17,$13,$1B,$16,$7F,$7F,$5F,$5F,$7F,$2C,$FF,$18,$3F,$00
db $D8,$F8,$B8,$F8,$7C,$FC,$FC,$FC,$F4,$FC,$FC,$FE,$0C,$FF,$00,$FC
db $F8,$D8,$F8,$B8,$FC,$7C,$FC,$FC,$FC,$F4,$F6,$F4,$FF,$0C,$FC,$00
