; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0530.asm

hirom
org $D38400

!D384C0_AssetSprite0530End = SPRITE_0531

; Original terminal data gap ending at $D384C0
db $00,$00,$00,$00,$1F,$1F,$2F,$33,$7C,$7F,$5E,$7D,$3F,$2F,$3F,$32
db $00,$00,$00,$00,$1F,$1F,$23,$23,$4C,$4C,$50,$50,$2F,$2F,$32,$3F
db $00,$00,$00,$00,$FC,$FC,$C6,$3E,$FF,$FF,$B7,$7D,$FF,$FF,$FE,$26
db $00,$00,$00,$00,$FC,$FC,$02,$02,$FF,$FF,$05,$05,$F9,$F9,$26,$FE
db $7F,$4F,$3F,$27,$1F,$17,$0F,$0F,$07,$07,$0F,$0F,$1F,$1F,$3F,$3F
db $4F,$70,$27,$3A,$17,$19,$0F,$08,$07,$06,$0B,$0B,$13,$12,$21,$21
db $FF,$F9,$FE,$F2,$FC,$F4,$F8,$F8,$F0,$F0,$F8,$F8,$FC,$FC,$FE,$FE
db $F9,$07,$F2,$2E,$F4,$CC,$F8,$08,$F0,$30,$E8,$E8,$E4,$24,$C2,$42
db $77,$5F,$7F,$7F,$33,$3F,$1F,$1F,$17,$1F,$08,$3F,$17,$FF,$0E,$3F
db $48,$40,$78,$48,$3C,$30,$10,$10,$18,$10,$3F,$08,$F9,$11,$3F,$0E
db $F7,$FF,$FE,$FE,$FC,$FC,$E2,$DE,$C2,$FE,$C4,$FC,$48,$FF,$30,$FC
db $8F,$81,$9E,$9A,$24,$24,$5E,$42,$BE,$82,$BC,$84,$FF,$48,$FC,$30
