; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0416.asm

hirom
org $D32E80

!D32F40_AssetSprite0416End = SPRITE_0417

; Original terminal data gap ending at $D32F40
db $00,$00,$1F,$1F,$20,$3F,$24,$3F,$2F,$3F,$2F,$3F,$24,$3F,$20,$3F
db $00,$00,$1F,$1F,$20,$20,$24,$24,$2F,$2F,$2F,$2F,$24,$24,$20,$20
db $00,$00,$F0,$F0,$08,$F8,$08,$F8,$E8,$F8,$E8,$F8,$08,$F8,$08,$F8
db $00,$00,$F0,$F0,$08,$08,$08,$08,$E8,$E8,$E8,$E8,$08,$08,$08,$08
db $1F,$1F,$00,$00,$06,$06,$09,$09,$0B,$09,$06,$06,$0D,$0C,$13,$11
db $1F,$1F,$00,$00,$06,$06,$0F,$0F,$0F,$0F,$07,$07,$0F,$0F,$1F,$1F
db $F0,$F0,$80,$80,$F0,$F0,$C8,$88,$B8,$88,$F8,$08,$F0,$70,$60,$20
db $F0,$F0,$80,$80,$F0,$F0,$F8,$F8,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0
db $1F,$18,$1F,$12,$0F,$0C,$07,$05,$0F,$09,$07,$04,$0F,$7F,$00,$3F
db $1F,$1F,$1F,$1F,$0F,$0F,$07,$07,$0F,$0F,$07,$07,$7F,$0F,$3F,$00
db $E0,$20,$E4,$24,$C2,$42,$C4,$44,$78,$78,$C0,$C0,$80,$FC,$00,$F8
db $E0,$E0,$E4,$E4,$C2,$C2,$C4,$C4,$F8,$F8,$C0,$C0,$FC,$80,$F8,$00
