; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0555.asm

hirom
org $D396C0

!D39780_AssetSprite0555End = SPRITE_0556

; Original terminal data gap ending at $D39780
db $07,$07,$0D,$09,$11,$10,$33,$20,$28,$20,$51,$40,$64,$40,$20,$20
db $07,$07,$0F,$0F,$1F,$1F,$3E,$3E,$3F,$3F,$7F,$7F,$7F,$7F,$3F,$3F
db $70,$70,$88,$88,$24,$04,$D4,$04,$02,$02,$91,$01,$46,$02,$01,$01
db $70,$70,$F8,$F8,$FC,$FC,$3C,$3C,$FE,$FE,$FF,$FF,$FE,$FE,$FF,$FF
db $48,$40,$69,$40,$31,$20,$42,$40,$58,$40,$24,$24,$1F,$1F,$07,$07
db $7F,$7F,$7F,$7F,$3F,$3F,$7F,$7F,$7F,$7F,$3F,$3F,$1F,$1F,$07,$05
db $27,$01,$52,$02,$13,$01,$47,$01,$1A,$02,$96,$96,$F8,$F8,$F8,$F8
db $FF,$FF,$FE,$FE,$FF,$FF,$FF,$FF,$FE,$FE,$FE,$FE,$F8,$68,$F8,$E8
db $07,$07,$0F,$0F,$0F,$0F,$02,$02,$01,$01,$01,$1F,$03,$7F,$07,$1F
db $07,$06,$0F,$0B,$0F,$0F,$02,$03,$01,$01,$1F,$01,$7F,$03,$1F,$07
db $F8,$F8,$FC,$FC,$FC,$FC,$BC,$BC,$20,$60,$E0,$F8,$F0,$FE,$80,$F8
db $F8,$28,$FC,$EC,$FC,$F4,$BC,$FC,$60,$A0,$F8,$60,$FE,$F0,$F8,$80
