; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0600.asm

hirom
org $D3B880

!D3B940_AssetSprite0600End = SPRITE_0601

; Original terminal data gap ending at $D3B940
db $00,$00,$FF,$FF,$5F,$5F,$2F,$2F,$3F,$3F,$FF,$FF,$3F,$3F,$3F,$3F
db $00,$00,$FF,$FF,$7F,$7F,$3B,$3B,$3B,$3B,$FF,$FF,$37,$36,$3F,$3F
db $00,$00,$FF,$FF,$FF,$FF,$FC,$FC,$FC,$FC,$FE,$FE,$FC,$FC,$FC,$FC
db $00,$00,$FF,$FF,$FF,$FF,$FC,$FC,$FC,$FC,$FE,$FE,$FC,$7C,$FC,$BC
db $7F,$7F,$7F,$7F,$2F,$2C,$2F,$2C,$17,$17,$08,$08,$06,$06,$0F,$0D
db $7F,$58,$7F,$40,$2C,$33,$24,$3B,$17,$18,$08,$0F,$06,$07,$0D,$0D
db $BC,$BC,$EC,$EC,$E8,$E8,$C8,$C8,$90,$90,$20,$20,$E0,$E0,$F0,$F0
db $BC,$7C,$EC,$7C,$E8,$18,$C8,$38,$90,$70,$20,$E0,$E0,$E0,$F0,$F0
db $1D,$1B,$17,$1F,$1F,$1F,$09,$0F,$07,$07,$03,$03,$0D,$FF,$07,$7F
db $19,$19,$17,$17,$1F,$1F,$0F,$09,$07,$07,$03,$03,$FB,$09,$7F,$07
db $F8,$F8,$F8,$F8,$F8,$B8,$D0,$D0,$F0,$F0,$A0,$E0,$E0,$FE,$C0,$FC
db $F8,$F8,$F8,$F8,$B8,$98,$D0,$B0,$F0,$F0,$E0,$A0,$FE,$E0,$FC,$C0
