; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0428.asm

hirom
org $D33780

!D33840_AssetSprite0428End = SPRITE_0429

; Original terminal data gap ending at $D33840
db $00,$00,$00,$00,$0F,$0F,$30,$30,$40,$40,$A0,$80,$AA,$80,$AA,$80
db $00,$00,$00,$00,$0F,$0F,$3F,$3F,$7F,$7F,$FF,$FF,$FF,$FF,$FF,$FF
db $00,$00,$70,$70,$88,$F8,$54,$74,$22,$22,$12,$12,$1A,$12,$0D,$09
db $00,$00,$70,$70,$F8,$F8,$FC,$FC,$FE,$FE,$FE,$FE,$FE,$FE,$FF,$FF
db $FF,$80,$7F,$7D,$7F,$7F,$FF,$F3,$7F,$73,$36,$3E,$1D,$1C,$0D,$0D
db $FF,$FF,$7F,$53,$7F,$50,$F3,$8C,$73,$4D,$36,$29,$1D,$13,$0F,$0F
db $1D,$0D,$1B,$0B,$B8,$88,$F8,$88,$F0,$10,$E0,$20,$C0,$40,$80,$80
db $FF,$FF,$FB,$FB,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$80,$80
db $0F,$0B,$13,$13,$2B,$2B,$47,$41,$3F,$20,$1F,$1F,$1B,$F7,$0F,$3F
db $0F,$0C,$1F,$1C,$37,$3E,$7F,$7F,$3F,$3F,$1F,$18,$F0,$1F,$3F,$0F
db $C0,$40,$C0,$C0,$E0,$E0,$60,$60,$D0,$D0,$E0,$A0,$C0,$FC,$80,$F0
db $C0,$C0,$C0,$C0,$E0,$20,$60,$A0,$F0,$F0,$E0,$E0,$7C,$C0,$F0,$80
