; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0481.asm

hirom
org $D35F40

!D36000_AssetSprite0481End = SPRITE_0482

; Original terminal data gap ending at $D36000
db $0F,$0F,$34,$30,$55,$40,$40,$40,$52,$40,$32,$30,$3C,$3C,$3E,$3E
db $0F,$0F,$3F,$3F,$7F,$7F,$7F,$7F,$77,$7F,$33,$2F,$3D,$2B,$3F,$29
db $70,$70,$88,$88,$14,$04,$A4,$04,$52,$02,$16,$02,$C6,$C2,$46,$42
db $70,$70,$F8,$F8,$FC,$FC,$FC,$FC,$FE,$FE,$FE,$FE,$FE,$FE,$7E,$FE
db $7F,$7F,$3F,$3C,$3F,$3C,$17,$17,$08,$08,$04,$07,$07,$04,$0F,$0E
db $7F,$40,$3C,$23,$3C,$2B,$17,$18,$08,$0F,$04,$07,$04,$04,$0E,$0E
db $C6,$C6,$E4,$E4,$FC,$FC,$90,$90,$20,$20,$40,$C0,$20,$E0,$A0,$60
db $DE,$7E,$FC,$9C,$FC,$0C,$90,$70,$20,$E0,$40,$C0,$20,$20,$20,$20
db $0F,$0E,$1E,$17,$56,$5F,$E0,$FF,$B7,$FF,$48,$78,$28,$FF,$10,$3F
db $0E,$08,$16,$10,$56,$56,$BF,$A0,$DF,$97,$78,$48,$FF,$28,$3F,$10
db $F0,$50,$50,$F0,$8C,$FC,$0A,$FE,$CA,$FE,$36,$3E,$1C,$FF,$18,$FC
db $50,$50,$50,$50,$FC,$8C,$FE,$0A,$FE,$CA,$3A,$32,$F7,$14,$FC,$18
