; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0594.asm

hirom
org $D3B400

!D3B4C0_AssetSprite0594End = SPRITE_0595

; Original terminal data gap ending at $D3B4C0
db $07,$07,$1C,$1F,$65,$7E,$7C,$7F,$3F,$3F,$2E,$3F,$7F,$5F,$5D,$4F
db $07,$07,$1E,$1E,$7E,$66,$7F,$7F,$3F,$3F,$30,$20,$5F,$7F,$4B,$79
db $F0,$F0,$CC,$FC,$77,$FF,$7F,$FF,$FE,$FE,$6A,$FE,$FF,$FD,$DD,$F1
db $F0,$F0,$FC,$CC,$7F,$77,$FF,$FF,$FE,$FE,$16,$02,$FD,$FF,$B1,$9F
db $3F,$2F,$3F,$27,$3F,$2C,$1F,$13,$3F,$18,$7F,$7A,$7F,$7D,$F7,$BD
db $2F,$3E,$27,$3F,$2C,$3F,$13,$1F,$10,$17,$7A,$7B,$7D,$7D,$BD,$BD
db $FE,$B2,$F4,$C4,$74,$64,$FC,$8C,$FE,$1C,$FE,$5E,$FF,$BF,$EF,$7F
db $B2,$FE,$C4,$FC,$64,$FC,$84,$F4,$0C,$EC,$5E,$DE,$BF,$BF,$7F,$7F
db $FF,$BF,$9A,$9F,$7E,$7F,$12,$1F,$3F,$3F,$6E,$7F,$3E,$FF,$00,$7F
db $BF,$FF,$9B,$FA,$7F,$7E,$1F,$12,$3F,$3F,$5F,$4E,$FF,$3E,$7F,$00
db $FF,$FD,$FF,$FD,$FF,$FF,$C2,$FE,$BE,$FE,$A6,$FE,$7C,$FF,$78,$FE
db $FD,$FF,$FD,$FF,$FF,$FF,$FE,$C2,$FE,$BE,$FE,$A6,$FF,$7C,$FE,$78
