; EarthBound D3 asset SPRITE_0654.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:E100..D3:E1C0 AssetSprite0654

; ---------------------------------------------------------------------------
; D3:E1C0

; AssetSprite0654End
D3E1C0_AssetSprite0654End:
