; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0556.asm

hirom
org $D39780

!D39840_AssetSprite0556End = SPRITE_0557

; Original terminal data gap ending at $D39840
db $07,$07,$1A,$18,$2F,$20,$5A,$48,$4E,$44,$2E,$24,$1F,$1E,$1F,$1F
db $07,$07,$1F,$1F,$39,$39,$7F,$7F,$7F,$7F,$3F,$3F,$1F,$1B,$1F,$1F
db $C0,$C0,$30,$30,$C8,$08,$1A,$1A,$4C,$4C,$CA,$C2,$84,$04,$9A,$92
db $C0,$C0,$F0,$F0,$F8,$F8,$FA,$FA,$FC,$FC,$FE,$FE,$FC,$FC,$FE,$FE
db $1F,$1F,$3F,$3E,$1F,$1C,$03,$0B,$06,$06,$03,$03,$07,$07,$07,$07
db $1F,$18,$3E,$21,$1C,$13,$03,$0C,$06,$07,$03,$03,$07,$05,$07,$07
db $FE,$E2,$54,$D4,$DE,$C2,$44,$44,$E2,$E2,$DC,$DC,$40,$40,$40,$40
db $FE,$FE,$7C,$FC,$FE,$7E,$7C,$FC,$FE,$FE,$DC,$5C,$40,$C0,$40,$C0
db $07,$07,$02,$02,$03,$03,$02,$02,$03,$03,$03,$03,$07,$3F,$07,$0F
db $07,$07,$02,$03,$03,$03,$02,$03,$03,$02,$03,$02,$3F,$05,$0F,$07
db $20,$20,$A0,$A0,$A0,$A0,$E0,$E0,$80,$80,$80,$80,$80,$F8,$00,$E0
db $20,$E0,$A0,$E0,$A0,$E0,$E0,$E0,$80,$80,$80,$80,$F8,$80,$E0,$00
