; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0681.asm

hirom
org $D3F540

!D3F600_AssetSprite0681End = SPRITE_0682

; Original terminal data gap ending at $D3F600
db $0F,$0F,$6F,$7F,$70,$7F,$7F,$7F,$3F,$3F,$21,$21,$3F,$3E,$3F,$3E
db $0F,$0F,$7F,$6F,$7F,$70,$7F,$7F,$3F,$3F,$21,$3F,$3E,$28,$3E,$20
db $F0,$F0,$F8,$F8,$FB,$FF,$0F,$FF,$FE,$FE,$FE,$FE,$BF,$BF,$F9,$E7
db $F0,$F0,$F8,$F8,$FF,$FB,$FF,$0F,$FE,$FE,$FE,$FE,$A1,$E1,$E1,$A1
db $7F,$7F,$5F,$57,$3F,$23,$3F,$38,$17,$10,$0E,$0E,$0B,$0D,$1F,$17
db $7F,$40,$57,$70,$23,$20,$38,$3F,$10,$1F,$0E,$0F,$0C,$08,$16,$16
db $FD,$E3,$7A,$46,$B2,$AE,$FC,$1C,$D0,$10,$70,$70,$E0,$E0,$10,$F0
db $E1,$A1,$42,$C2,$82,$42,$0C,$EC,$10,$F0,$70,$F0,$20,$20,$F0,$10
db $2E,$3D,$2C,$3F,$3B,$3B,$7C,$7F,$6B,$7F,$24,$3F,$18,$FF,$00,$3F
db $3D,$2C,$3F,$20,$3B,$37,$6F,$6C,$57,$43,$3F,$24,$FF,$18,$3F,$00
db $50,$F0,$58,$F8,$84,$FC,$14,$FC,$14,$FC,$FC,$FC,$0C,$FF,$00,$FC
db $F0,$50,$F8,$58,$FC,$84,$EC,$04,$FC,$14,$F4,$F4,$FF,$0C,$FC,$00
