; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0452.asm

hirom
org $D34980

!D34A40_AssetSprite0452End = SPRITE_0453

; Original terminal data gap ending at $D34A40
db $00,$00,$07,$07,$08,$08,$30,$38,$40,$47,$30,$30,$3F,$3F,$3F,$3F
db $00,$00,$07,$07,$0F,$0F,$37,$3F,$78,$7F,$3F,$3F,$3F,$3F,$3F,$3B
db $00,$00,$F0,$F0,$08,$08,$06,$0E,$01,$F1,$06,$06,$FC,$FC,$FC,$FC
db $00,$00,$F0,$F0,$F8,$F8,$F6,$FE,$0F,$FF,$FE,$FE,$FC,$FC,$FC,$FC
db $3F,$3F,$3F,$3F,$7F,$7C,$3F,$3C,$1B,$1F,$0F,$0F,$07,$06,$0F,$08
db $3F,$28,$3F,$28,$7C,$43,$3C,$23,$1B,$14,$0F,$08,$06,$06,$08,$08
db $FC,$FC,$FC,$FC,$FC,$FC,$FC,$FC,$B4,$B4,$24,$24,$C4,$C4,$20,$E4
db $FC,$FC,$FC,$BC,$FC,$3C,$FC,$7C,$B4,$74,$24,$E4,$C4,$C4,$2A,$EE
db $08,$0F,$18,$17,$10,$1F,$20,$3F,$38,$3F,$0F,$0F,$0C,$7B,$07,$1F
db $08,$0F,$10,$1F,$10,$1F,$20,$3F,$38,$3F,$0F,$0F,$78,$0F,$1F,$07
db $14,$F4,$BC,$DC,$7C,$FC,$38,$F8,$30,$F0,$E0,$E0,$40,$FE,$80,$F8
db $14,$F4,$9C,$CC,$7C,$C4,$38,$E8,$30,$D0,$E0,$E0,$7E,$C0,$F8,$80
