; EarthBound D3 asset SPRITE_0673.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:EF40..D3:F000 AssetSprite0673

; ---------------------------------------------------------------------------
; D3:F000

; AssetSprite0673End
D3F000_AssetSprite0673End:
