; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0653.asm

hirom
org $D3E040

!D3E100_AssetSprite0653End = SPRITE_0654

; Original terminal data gap ending at $D3E100
db $1F,$1F,$77,$7F,$7F,$7F,$3F,$3F,$3F,$3F,$20,$3F,$30,$28,$3F,$2F
db $1F,$1F,$7F,$77,$7F,$7F,$3F,$3F,$3F,$23,$3F,$20,$28,$27,$2F,$20
db $E0,$E0,$B8,$F8,$FC,$FC,$FE,$FE,$FE,$FE,$7E,$FE,$BC,$FC,$FC,$FC
db $E0,$E0,$F8,$B8,$FC,$FC,$FE,$FE,$FE,$FE,$FE,$7E,$FC,$BC,$FC,$7C
db $7F,$7C,$3F,$3C,$3F,$3F,$17,$17,$08,$08,$07,$07,$07,$04,$03,$05
db $7C,$43,$3C,$23,$3F,$28,$17,$18,$08,$0F,$07,$06,$04,$04,$01,$05
db $B8,$B8,$F8,$F8,$D0,$D0,$A0,$A0,$40,$40,$C0,$C0,$E0,$E0,$E0,$E0
db $B8,$F8,$F8,$38,$D0,$30,$A0,$60,$40,$C0,$C0,$C0,$E0,$E0,$E0,$E0
db $0F,$0F,$09,$09,$2C,$2F,$7F,$7F,$4F,$7F,$38,$38,$18,$FF,$00,$1F
db $0F,$09,$09,$0F,$2F,$2C,$5F,$5F,$7F,$4F,$38,$38,$FF,$18,$1F,$00
db $B0,$F0,$B0,$F0,$78,$F8,$FC,$FC,$F4,$FC,$7C,$7C,$38,$FF,$30,$F8
db $F0,$B0,$F0,$B0,$F8,$78,$FC,$FC,$FC,$F4,$74,$74,$EF,$28,$F8,$30
