; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d3/asset_sprite_0472.asm

hirom
org $D35880

!D35940_AssetSprite0472End = SPRITE_0473

; Original terminal data gap ending at $D35940
db $00,$00,$1F,$1F,$3A,$3F,$17,$1F,$0F,$0F,$1F,$1F,$1F,$1F,$3F,$3F
db $00,$00,$1F,$1F,$21,$25,$18,$18,$0F,$0F,$1F,$1B,$1F,$11,$3F,$29
db $00,$00,$FC,$FC,$EE,$FE,$54,$FC,$F8,$F8,$FC,$FC,$FC,$FC,$FE,$FE
db $00,$00,$FC,$FC,$02,$12,$24,$AC,$F8,$F8,$FC,$FC,$FC,$FC,$FE,$FE
db $3F,$3F,$7F,$7F,$3F,$3C,$3F,$3C,$1F,$17,$08,$08,$06,$07,$05,$07
db $3F,$29,$7F,$40,$3C,$23,$3C,$2F,$17,$14,$08,$0F,$06,$07,$05,$07
db $FF,$FF,$FE,$FE,$FF,$FF,$FD,$FD,$94,$94,$36,$36,$5A,$DA,$28,$E8
db $FF,$3F,$FE,$7E,$FF,$FF,$FD,$3D,$94,$74,$36,$F6,$5A,$DA,$28,$E8
db $0E,$0F,$08,$0F,$0F,$0F,$0F,$0F,$07,$07,$07,$07,$0D,$7F,$07,$1F
db $0E,$0F,$08,$0F,$00,$0F,$08,$0F,$04,$07,$07,$07,$7B,$09,$1F,$07
db $90,$F0,$98,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$C0,$FE,$80,$F8
db $90,$F0,$98,$E8,$78,$C8,$10,$F0,$20,$E0,$C0,$C0,$FE,$C0,$F8,$80
