; Generated by tools/build_c3_event_script_source_pilot.py
; C3 event/actionscript source pilot: onett-townhall-movement-paths.
; This file is intentionally not wired into the bank C3 scaffold yet.
hirom

; External constants and action-script variable slots.
!ACTIONSCRIPT_ANIMATION_FRAME0 = $00
!ACTIONSCRIPT_ANIMATION_HIDDEN_OR_OFF = $FF
!ACTIONSCRIPT_FIELD2B32_STEP_0080 = $0080
!ACTIONSCRIPT_FIELD2B32_STEP_0140 = $0140
!ACTIONSCRIPT_FIELD2B32_STEP_0160 = $0160
!ACTIONSCRIPT_SOUND_EFFECT_EXIT_DOOR = $0009
!ACTIONSCRIPT_SURFACE_FLAGS_NONE = $00
!ACTIONSCRIPT_VARS_V0 = $00
!ACTIONSCRIPT_VARS_V1 = $01
!ACTIONSCRIPT_VARS_V2 = $02
!ACTIONSCRIPT_VARS_V3 = $03
!ACTIONSCRIPT_VARS_V4 = $04
!ACTIONSCRIPT_VARS_V5 = $05
!ACTIONSCRIPT_VARS_V6 = $06
!ACTIONSCRIPT_VARS_V7 = $07
!DisableCurrentSlotNeighborCache = $C0A82F
!FacePoseDescriptorSlotTowardCurrentSlot_ReadWord = $C0A959
!InitMovementPresetVar4Countdown = $AAAA
!RefreshCurrentSlotVisualProfile_Mode0 = $C0A4BF
!ReleaseCurrentVisualEntityAndEnd = $A204
!ReturnFromPhysicsCallback_NoMovement = $9FF0
!RunLeftRightFacingPulsePair = $7559
!Script_ApplyCurrentSlotVisualCountdownState = $C0AA6E
!Script_CopyPoseDescriptorSlotAnchorToCurrentSlot_ReadWord = $C0A86F
!Script_PlaySoundEffectParameter = $C0A841
!Script_SetCurrentSlotField2B32 = $C0A685
!Script_SetCurrentSlotSurfaceFlags = $C0A679
!SetYieldToTextLatch9641 = $C46E46
!WaitForActiveEntityMovementToFinish = $AB59

; Minimal macro vocabulary used by this source pilot.
macro EVENT_CALLROUTINE_0(target)
    db $42
    dl <target>
endmacro

macro EVENT_CALLROUTINE_FIELD2B32(target, field2b32_word)
    db $42
    dl <target>
    dw <field2b32_word>
endmacro

macro EVENT_CALLROUTINE_POSE_DESCRIPTOR_ID(target, pose_descriptor_id_word)
    db $42
    dl <target>
    dw <pose_descriptor_id_word>
endmacro

macro EVENT_CALLROUTINE_POSE_DESCRIPTOR_SLOT(target, pose_descriptor_slot_word)
    db $42
    dl <target>
    dw <pose_descriptor_slot_word>
endmacro

macro EVENT_CALLROUTINE_SOUND_EFFECT_ID(target, sound_effect_id_word)
    db $42
    dl <target>
    dw <sound_effect_id_word>
endmacro

macro EVENT_CALLROUTINE_SURFACE_FLAGS(target, surface_flags_byte)
    db $42
    dl <target>
    db <surface_flags_byte>
endmacro

macro EVENT_CALLROUTINE_VISUAL_STATE_COUNTDOWN(target, visual_state_byte, countdown_byte)
    db $42
    dl <target>
    db <visual_state_byte>
    db <countdown_byte>
endmacro

macro EVENT_END_LAST_TASK()
    db $13
endmacro

macro EVENT_HALT()
    db $09
endmacro

macro EVENT_LOOP(count)
    db $01, <count>
endmacro

macro EVENT_LOOP_END()
    db $02
endmacro

macro EVENT_PAUSE(frames)
    db $06, <frames>
endmacro

macro EVENT_SET_ANIMATION(animation)
    db $3B, <animation>
endmacro

macro EVENT_SET_PHYSICS_CALLBACK(target)
    db $25
    dw <target>
endmacro

macro EVENT_SET_PRIORITY(priority)
    db $43, <priority>
endmacro

macro EVENT_SET_VAR(var, value)
    db $0E, <var>
    dw <value>
endmacro

macro EVENT_SET_VELOCITIES_ZERO()
    db $39
endmacro

macro EVENT_SET_X(value)
    db $28
    dw <value>
endmacro

macro EVENT_SET_X_RELATIVE(value)
    db $2B
    dw <value>
endmacro

macro EVENT_SET_Y(value)
    db $29
    dw <value>
endmacro

macro EVENT_SET_Y_RELATIVE(value)
    db $2C
    dw <value>
endmacro

macro EVENT_SHORTCALL(target)
    db $1A
    dw <target>
endmacro

macro EVENT_SHORTJUMP(target)
    db $19
    dw <target>
endmacro

macro EVENT_START_TASK(target)
    db $07
    dw <target>
endmacro


org $C389BD
Event715_BlinkThenRelease:
    %EVENT_CALLROUTINE_0(!DisableCurrentSlotNeighborCache) ; C3:89BD  42 2F A8 C0
    %EVENT_SET_PRIORITY($03) ; C3:89C1  43 03
    %EVENT_SET_PHYSICS_CALLBACK(!ReturnFromPhysicsCallback_NoMovement) ; C3:89C3  25 F0 9F
    %EVENT_SET_ANIMATION(!ACTIONSCRIPT_ANIMATION_FRAME0) ; C3:89C6  3B 00
    %EVENT_SET_VELOCITIES_ZERO() ; C3:89C8  39
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:89C9  42 BF A4 C0
    %EVENT_PAUSE($20) ; C3:89CD  06 20
    %EVENT_LOOP($08) ; C3:89CF  01 08
    %EVENT_SET_ANIMATION(!ACTIONSCRIPT_ANIMATION_HIDDEN_OR_OFF) ; C3:89D1  3B FF
    %EVENT_PAUSE($01) ; C3:89D3  06 01
    %EVENT_SET_ANIMATION(!ACTIONSCRIPT_ANIMATION_FRAME0) ; C3:89D5  3B 00
    %EVENT_PAUSE($01) ; C3:89D7  06 01
    %EVENT_LOOP_END() ; C3:89D9  02
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:89DA  19 04 A2
Event716_OffsetPoseHalt:
    %EVENT_CALLROUTINE_POSE_DESCRIPTOR_SLOT(!Script_CopyPoseDescriptorSlotAnchorToCurrentSlot_ReadWord, $019A) ; C3:89DD  42 6F A8 C0 9A 01
    %EVENT_SET_X_RELATIVE($0015) ; C3:89E3  2B 15 00
    %EVENT_SET_Y_RELATIVE($FFF2) ; C3:89E6  2C F2 FF
    %EVENT_SET_PRIORITY($00) ; C3:89E9  43 00
    %EVENT_SET_PHYSICS_CALLBACK(!ReturnFromPhysicsCallback_NoMovement) ; C3:89EB  25 F0 9F
    %EVENT_SET_ANIMATION(!ACTIONSCRIPT_ANIMATION_FRAME0) ; C3:89EE  3B 00
    %EVENT_SET_VELOCITIES_ZERO() ; C3:89F0  39
    %EVENT_CALLROUTINE_SURFACE_FLAGS(!Script_SetCurrentSlotSurfaceFlags, !ACTIONSCRIPT_SURFACE_FLAGS_NONE) ; C3:89F1  42 79 A6 C0 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:89F6  42 BF A4 C0
    %EVENT_HALT() ; C3:89FA  09
Event717_OnettTownHallLongMovementPath:
    %EVENT_SET_X($0628) ; C3:89FB  28 28 06
    %EVENT_SET_Y($2250) ; C3:89FE  29 50 22
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:8A01  1A AA AA
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0011) ; C3:8A04  0E 04 11 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:8A08  42 BF A4 C0
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0080) ; C3:8A0C  42 85 A6 C0 80 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0001) ; C3:8A12  0E 05 01 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0640) ; C3:8A16  0E 06 40 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2250) ; C3:8A1A  0E 07 50 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A1E  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0650) ; C3:8A21  0E 06 50 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2260) ; C3:8A25  0E 07 60 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A29  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0698) ; C3:8A2C  0E 06 98 06
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A30  1A 59 AB
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:8A33  42 46 6E C4
    %EVENT_PAUSE($01) ; C3:8A37  06 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:8A39  0E 04 00 00
RunEvent717_LeftRightFacingPulse:
    %EVENT_SHORTCALL(!RunLeftRightFacingPulsePair) ; C3:8A3D  1A 59 75
    %EVENT_PAUSE($1E) ; C3:8A40  06 1E
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0008) ; C3:8A42  0E 04 08 00
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0160) ; C3:8A46  42 85 A6 C0 60 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:8A4C  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0660) ; C3:8A50  0E 06 60 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2260) ; C3:8A54  0E 07 60 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A58  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0658) ; C3:8A5B  0E 06 58 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2258) ; C3:8A5F  0E 07 58 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A63  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0658) ; C3:8A66  0E 06 58 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2248) ; C3:8A6A  0E 07 48 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A6E  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0670) ; C3:8A71  0E 06 70 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2240) ; C3:8A75  0E 07 40 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8A79  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:8A7C  0E 04 00 00
    %EVENT_CALLROUTINE_VISUAL_STATE_COUNTDOWN(!Script_ApplyCurrentSlotVisualCountdownState, $00, $00) ; C3:8A80  42 6E AA C0 00 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:8A86  42 46 6E C4
    %EVENT_PAUSE($01) ; C3:8A8A  06 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0010) ; C3:8A8C  0E 04 10 00
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0080) ; C3:8A90  42 85 A6 C0 80 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0001) ; C3:8A96  0E 05 01 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0650) ; C3:8A9A  0E 06 50 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2250) ; C3:8A9E  0E 07 50 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8AA2  1A 59 AB
    %EVENT_END_LAST_TASK() ; C3:8AA5  13
    %EVENT_CALLROUTINE_VISUAL_STATE_COUNTDOWN(!Script_ApplyCurrentSlotVisualCountdownState, $06, $00) ; C3:8AA6  42 6E AA C0 06 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:8AAC  42 46 6E C4
    %EVENT_HALT() ; C3:8AB0  09
Event718_OnettTownHallShortMovementHalt:
    %EVENT_SET_X($0628) ; C3:8AB1  28 28 06
    %EVENT_SET_Y($2250) ; C3:8AB4  29 50 22
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:8AB7  1A AA AA
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0008) ; C3:8ABA  0E 04 08 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:8ABE  42 BF A4 C0
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0160) ; C3:8AC2  42 85 A6 C0 60 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:8AC8  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0640) ; C3:8ACC  0E 06 40 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2250) ; C3:8AD0  0E 07 50 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8AD4  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:8AD7  0E 04 00 00
    %EVENT_HALT() ; C3:8ADB  09
Event719_OnettTownHallDoorMovementPath:
    %EVENT_SET_X($0778) ; C3:8ADC  28 78 07
    %EVENT_SET_Y($2268) ; C3:8ADF  29 68 22
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:8AE2  1A AA AA
    %EVENT_START_TASK(LoopEvent719_DoorSoundTask) ; C3:8AE5  07 29 8B
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0008) ; C3:8AE8  0E 04 08 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:8AEC  42 BF A4 C0
    %EVENT_CALLROUTINE_SOUND_EFFECT_ID(!Script_PlaySoundEffectParameter, !ACTIONSCRIPT_SOUND_EFFECT_EXIT_DOOR) ; C3:8AF0  42 41 A8 C0 09 00
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0140) ; C3:8AF6  42 85 A6 C0 40 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:8AFC  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0648) ; C3:8B00  0E 06 48 06
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2268) ; C3:8B04  0E 07 68 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8B08  1A 59 AB
    %EVENT_END_LAST_TASK() ; C3:8B0B  13
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $2258) ; C3:8B0C  0E 07 58 22
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8B10  1A 59 AB
    %EVENT_END_LAST_TASK() ; C3:8B13  13
    %EVENT_PAUSE($3C) ; C3:8B14  06 3C
    %EVENT_CALLROUTINE_VISUAL_STATE_COUNTDOWN(!Script_ApplyCurrentSlotVisualCountdownState, $06, $00) ; C3:8B16  42 6E AA C0 06 00
    %EVENT_PAUSE($0A) ; C3:8B1C  06 0A
    %EVENT_CALLROUTINE_VISUAL_STATE_COUNTDOWN(!Script_ApplyCurrentSlotVisualCountdownState, $04, $00) ; C3:8B1E  42 6E AA C0 04 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:8B24  42 46 6E C4
    %EVENT_HALT() ; C3:8B28  09
LoopEvent719_DoorSoundTask:
    %EVENT_CALLROUTINE_POSE_DESCRIPTOR_ID(!FacePoseDescriptorSlotTowardCurrentSlot_ReadWord, $0091) ; C3:8B29  42 59 A9 C0 91 00
    %EVENT_CALLROUTINE_POSE_DESCRIPTOR_ID(!FacePoseDescriptorSlotTowardCurrentSlot_ReadWord, $0092) ; C3:8B2F  42 59 A9 C0 92 00
    %EVENT_PAUSE($03) ; C3:8B35  06 03
    %EVENT_SHORTJUMP(LoopEvent719_DoorSoundTask) ; C3:8B37  19 29 8B
Event720_MovementPathRelease:
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:8B3A  1A AA AA
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $000A) ; C3:8B3D  0E 04 0A 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:8B41  42 BF A4 C0
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0140) ; C3:8B45  42 85 A6 C0 40 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:8B4B  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $15F0) ; C3:8B4F  0E 06 F0 15
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $0B08) ; C3:8B53  0E 07 08 0B
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8B57  1A 59 AB
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:8B5A  19 04 A2
Event721_MovementPathEndTaskHalt:
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:8B5D  1A AA AA
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0008) ; C3:8B60  0E 04 08 00
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:8B64  42 BF A4 C0
    %EVENT_CALLROUTINE_FIELD2B32(!Script_SetCurrentSlotField2B32, !ACTIONSCRIPT_FIELD2B32_STEP_0160) ; C3:8B68  42 85 A6 C0 60 01
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:8B6E  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1538) ; C3:8B72  0E 06 38 15
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $0AC8) ; C3:8B76  0E 07 C8 0A
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:8B7A  1A 59 AB
    %EVENT_END_LAST_TASK() ; C3:8B7D  13
    %EVENT_HALT() ; C3:8B7E  09
