; Generated by tools/build_c3_event_script_source_pilot.py
; C3 event/actionscript source pilot: position-door-close-helpers.
; This file is intentionally not wired into the bank C3 scaffold yet.
hirom

; External constants and action-script variable slots.
!ACTIONSCRIPT_VARS_V0 = $00
!ACTIONSCRIPT_VARS_V1 = $01
!ACTIONSCRIPT_VARS_V2 = $02
!ACTIONSCRIPT_VARS_V3 = $03
!ACTIONSCRIPT_VARS_V4 = $04
!ACTIONSCRIPT_VARS_V5 = $05
!ACTIONSCRIPT_VARS_V6 = $06
!ACTIONSCRIPT_VARS_V7 = $07
!ApplyTempDirectionAndRefreshMovementVector = $AA1E
!InitActionScriptMovementState = $AA38
!LoopMakePartyLookAtActiveEntity = $C227
!RefreshCurrentSlotVisualProfile_Mode0 = $C0A4BF
!Script_PlaySoundEffectParameter = $C0A841
!Script_SetCurrentSlotField2B32 = $C0A685
!SetCurrentSlotDirectionClassIfActive = $C0A65F
!WaitForActiveEntityMovementToFinish = $AB59

; Minimal macro vocabulary used by this source pilot.
macro EVENT_CALLROUTINE_0(target)
    db $42
    dl <target>
endmacro

macro EVENT_CALLROUTINE_2(target, arg0, arg1)
    db $42
    dl <target>
    db <arg0>, <arg1>
endmacro

macro EVENT_PAUSE(frames)
    db $06, <frames>
endmacro

macro EVENT_SET_VAR(var, value)
    db $0E, <var>
    dw <value>
endmacro

macro EVENT_SHORTCALL(target)
    db $1A
    dw <target>
endmacro

macro EVENT_SHORT_RETURN()
    db $1B
endmacro

macro EVENT_START_TASK(target)
    db $07
    dw <target>
endmacro

macro EVENT_WRITE_WORD_TEMPVAR(value)
    db $1D
    dw <value>
endmacro


org $C3C1E0
RunPositionDoorCloseOpeningPath:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:C1E0  1A 38 AA
    %EVENT_START_TASK(!LoopMakePartyLookAtActiveEntity) ; C3:C1E3  07 27 C2
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:C1E6  1D 00 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C1E9  1A 1E AA
    %EVENT_PAUSE($08) ; C3:C1EC  06 08
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0001) ; C3:C1EE  0E 05 01 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1160) ; C3:C1F2  0E 06 60 11
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $1360) ; C3:C1F6  0E 07 60 13
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:C1FA  42 85 A6 C0 00 01
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:C200  1A 59 AB
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:C203  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:C206  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:C20A  42 BF A4 C0
    %EVENT_SHORT_RETURN() ; C3:C20E  1B
RunPositionDoorCloseSoundPath:
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $11F0) ; C3:C20F  0E 06 F0 11
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $1368) ; C3:C213  0E 07 68 13
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:C217  42 85 A6 C0 00 01
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:C21D  1A 59 AB
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:C220  42 41 A8 C0 09 00
    %EVENT_SHORT_RETURN() ; C3:C226  1B
