; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c4/auto_sector_music_change_latch.asm

hirom
org $C4FD45

!EnableAutoSectorMusicChanges = $B549
SET_AUTO_SECTOR_MUSIC_CHANGES:
!C4FD45_SetAutoSectorMusicChanges = SET_AUTO_SECTOR_MUSIC_CHANGES
    rep #$31
    sta !EnableAutoSectorMusicChanges
    rtl
