; EarthBound C4 cast entity onscreen check helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:ECE7..C4:ED0E IsEntityStillOnCastScreen

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C4:ECE7

C4ECE7_IsEntityStillOnCastScreen:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$0000
    sta $0E
    lda $1A42
    asl A
    tax
    lda $003B
    sec
    sbc.w #$0008
    cmp $0BCA,X
    bcs C4ED0A_IsEntityStillOnCastScreen_LED0A
    lda.w #$0001
    sta $0E
C4ED0A_IsEntityStillOnCastScreen_LED0A:
    lda $0E
    pld
    rtl
