; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c4/cast_name_party_print_helpers.asm

hirom
org $C4EBAD

!CopyCastNameTilemap = $C4EA9C
!PrintCastName = $C4EB04
!CastNameE1PointerRecordBaseLow = $2EFA
!CastNameE1PointerRecordBank = $00E1
!CastNameE1PointerRecordStride = $0003
!CastNamePointerRecordBankByteMask = $00FF
PRINT_CAST_NAME:
!C4EBAD_PrintCastNameParty = PRINT_CAST_NAME
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sty $04
    pha
    lda $04
    sta $10
    pla
    stx $02
    sta $0E
    lda.w #!CastNameE1PointerRecordBaseLow
    sta $06
    lda.w #!CastNameE1PointerRecordBank
    sta $08
    lda $0E
    sta $04
    asl A
    adc $04
    clc
    adc $06
    sta $06
    sta $0A
    lda $08
    sta $0C
    inc $0A
    inc $0A
    ldy $02
    lda [$0A]
    and.w #!CastNamePointerRecordBankByteMask
    tax
    lda [$06]
    jsl !CopyCastNameTilemap
    lda [$0A]
    and.w #!CastNamePointerRecordBankByteMask
    tay
    lda $10
    sta $04
    ldx $04
    lda $02
    jsl !PrintCastName
    pld
    rtl
