; EarthBound C4 credits photograph flag counter.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:F433..C4:F46F CountPhotoFlags

; ---------------------------------------------------------------------------
; External contracts used by this module

Multiply16By8_ViaHardwareRegisters = $C08FF7
CheckEventFlagMaybe                = $C21628
CreditsPhotographTable             = $E12F8A

; ---------------------------------------------------------------------------
; C4:F433

C4F433_CountPhotoFlags:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldy.w #$0000
    sty $10
    tyx
    stx $0E
    bra C4F465_CountPhotoFlags_LF465
C4F445_CountPhotoFlags_LF445:
    txa
    ldy.w #$003E
    jsl Multiply16By8_ViaHardwareRegisters
    tax
    lda CreditsPhotographTable,X
    jsl CheckEventFlagMaybe
    cmp.w #$0000
    beq C4F460_CountPhotoFlags_LF460
    ldy $10
    iny
    sty $10
C4F460_CountPhotoFlags_LF460:
    ldx $0E
    inx
    stx $0E
C4F465_CountPhotoFlags_LF465:
    cpx.w #$0020
    bcc C4F445_CountPhotoFlags_LF445
    ldy $10
    tya
    pld
    rtl
