; EarthBound C4 music change and pack loader.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:FBBD..C4:FD18 ChangeMusic

; ---------------------------------------------------------------------------
; External contracts used by this module

CreditsPlaybackActive      = $B4B6
CurrentMusicTrack          = $B53B
CurrentPrimarySamplePack   = $B53D
CurrentSecondarySamplePack = $B53F
CurrentSequencePack        = $B541
Unknown7EB543              = $B543
SequencePackMask           = $B547
LoadSpc700Data             = $C0AB06
UnknownC0ABBD              = $C0ABBD
StopMusic                  = $C0ABC6
PlaySoundUnknown0          = $C0AC01
StopMusicTransitionMaybe   = $C0AC0C
MusicDatasetTable          = $C4F70A

; ---------------------------------------------------------------------------
; C4:FBBD

C4FBBD_ChangeMusic:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEC
    tcd
    pla
    tax
    stx $12
    cpx CurrentMusicTrack
    bne C4FBD2_ChangeMusic_LFBD2
    jmp.w C4FD16_ChangeMusic_LFD16
C4FBD2_ChangeMusic_LFBD2:
    lda CreditsPlaybackActive
    bne C4FBDB_ChangeMusic_LFBDB
    jsl PlaySoundUnknown0
C4FBDB_ChangeMusic_LFBDB:
    ldx $12
    cpx.w #$00A0
    bcc C4FBE9_ChangeMusic_LFBE9
    cpx.w #$00A7
    bcc C4FBF4_ChangeMusic_LFBF4
    beq C4FBF4_ChangeMusic_LFBF4
C4FBE9_ChangeMusic_LFBE9:
    lda.w #$0001
    jsl StopMusicTransitionMaybe
    jsl StopMusic
C4FBF4_ChangeMusic_LFBF4:
    ldx $12
    stx CurrentMusicTrack
    txy
    dey
    sty $10
    tya
    sta $04
    asl A
    adc $04
    tax
    lda MusicDatasetTable,X
    and.w #$00FF
    sta $0E
    cmp CurrentPrimarySamplePack
    beq C4FC54_ChangeMusic_LFC54
    cmp.w #$00FF
    beq C4FC54_ChangeMusic_LFC54
    sta CurrentPrimarySamplePack
    lda.w #$F947
    sta $06
    lda.w #$00C4
    sta $08
    lda $0E
    sta $04
    asl A
    adc $04
    sta $02
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    jsr $FB42
    tax
    lda $02
    inc A
    clc
    adc $06
    sta $06
    lda [$06]
    and SequencePackMask
    jsl LoadSpc700Data
C4FC54_ChangeMusic_LFC54:
    ldy $10
    tya
    sta $04
    asl A
    adc $04
    tax
    inx
    lda MusicDatasetTable,X
    and.w #$00FF
    sta $0E
    cmp CurrentSecondarySamplePack
    beq C4FCB3_ChangeMusic_LFCB3
    cmp.w #$00FF
    beq C4FCB3_ChangeMusic_LFCB3
    cmp Unknown7EB543
    beq C4FCB3_ChangeMusic_LFCB3
    sta CurrentSecondarySamplePack
    lda.w #$F947
    sta $06
    lda.w #$00C4
    sta $08
    lda $0E
    sta $04
    asl A
    adc $04
    sta $02
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    jsr $FB42
    tax
    lda $02
    inc A
    clc
    adc $06
    sta $06
    lda [$06]
    and SequencePackMask
    jsl LoadSpc700Data
C4FCB3_ChangeMusic_LFCB3:
    ldy $10
    tya
    sta $04
    asl A
    adc $04
    tax
    inx
    inx
    lda MusicDatasetTable,X
    and.w #$00FF
    sta $0E
    cmp CurrentSequencePack
    beq C4FD0E_ChangeMusic_LFD0E
    cmp.w #$00FF
    beq C4FD0E_ChangeMusic_LFD0E
    sta CurrentSequencePack
    lda.w #$F947
    sta $06
    lda.w #$00C4
    sta $08
    lda $0E
    sta $04
    asl A
    adc $04
    sta $02
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    jsr $FB42
    tax
    lda $02
    inc A
    clc
    adc $06
    sta $06
    lda [$06]
    and SequencePackMask
    jsl LoadSpc700Data
C4FD0E_ChangeMusic_LFD0E:
    ldy $10
    tya
    inc A
    jsl UnknownC0ABBD
C4FD16_ChangeMusic_LFD16:
    pld
    rtl
