; EarthBound C4 photo and new-entity preparation helpers.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:6D4B..C4:6EF8 PhotoAndNewEntityPreparationHelpers

; ---------------------------------------------------------------------------
; External contracts used by this module

C064E3_QueueDeferredPointerRecord  = $C064E3
C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C4:6D4B

C46D4B_PlaceCurrentSlotFromPhotoSceneRecord:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    ldy $9E35
    lda $1A42
    asl A
    tax
    lda.w #$2F8A
    sta $06
    lda.w #$00E1
    sta $08
    tya
    ldy.w #$003E
    jsl C08FF7_ResolveIndexedPointerOffset
    sta $0E
    clc
    adc.w #$000A
    ldy $06
    sty $0A
    ldy $08
    sty $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    asl A
    asl A
    asl A
    sta $0B8E,X
    lda $0E
    clc
    adc.w #$000C
    clc
    adc $06
    sta $06
    lda [$06]
    asl A
    asl A
    asl A
    sta $0BCA,X
    lda $1A42
    asl A
    tax
    stz $0C7E,X
    lda $1A42
    asl A
    tax
    stz $0C42,X
    pld
    rtl
C46DAD_StageNewEntityFromCurrentOrPlayerSlot:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    beq C46DC0_PhotoAndNewEntityPreparationHelpers_L6DC0
    cmp.w #$0001
    beq C46DC7_PhotoAndNewEntityPreparationHelpers_L6DC7
    bra C46DCC_PhotoAndNewEntityPreparationHelpers_L6DCC
C46DC0_PhotoAndNewEntityPreparationHelpers_L6DC0:
    ldx $1A42
    stx $0E
    bra C46DCC_PhotoAndNewEntityPreparationHelpers_L6DCC
C46DC7_PhotoAndNewEntityPreparationHelpers_L6DC7:
    ldx $9889
    stx $0E
C46DCC_PhotoAndNewEntityPreparationHelpers_L6DCC:
    ldx $0E
    txa
    asl A
    tax
    lda $0B8E,X
    sta $9E2D
    lda $0BCA,X
    sta $9E2F
    lda $2AF6,X
    sta $9E31
    pld
    rtl
C46DE5_StageNewEntityFromTeleportDestinationRecord:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF1
    tcd
    pla
    sep #$20
    sta $0E
    rep #$20
    lda.w #$EBAB
    sta $06
    lda.w #$00D5
    sta $08
    lda $0E
    and.w #$00FF
    asl A
    asl A
    asl A
    clc
    adc $06
    sta $06
    sta $0A
    lda $08
    sta $0C
    lda [$0A]
    asl A
    asl A
    asl A
    sta $9E2D
    ldy.w #$0002
    lda [$06],Y
    asl A
    asl A
    asl A
    sta $9E2F
    sep #$20
    ldy.w #$0004
    lda [$06],Y
    rep #$20
    and.w #$00FF
    dec A
    sta $9E31
    pld
    rtl
C46E37_StageNewEntityFromExplicitPositionAndFacing:
    rep #$31
    stx $9E2D
    sty $9E2F
    and.w #$00FF
    sta $9E31
    rtl
C46E46_SetYieldToTextLatch9641:
    rep #$31
    lda.w #$0001
    sta $9641
    rtl
C46E4F_QueueEventTextPointerRecord8:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEA
    tcd
    pla
    stx $14
    sta $12
    sta $06
    lda $14
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda.w #$0008
    jsl C064E3_QueueDeferredPointerRecord
    pld
    rtl
C46E74_CheckStagedPositionWithinPlayerProximityThreshold:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda $9F3F
    beq C46E86_PhotoAndNewEntityPreparationHelpers_L6E86
    lda.w #$0000
    bra C46EF6_PhotoAndNewEntityPreparationHelpers_L6EF6
C46E86_PhotoAndNewEntityPreparationHelpers_L6E86:
    ldy $1A42
    tya
    asl A
    tax
    lda $0E5E,X
    sec
    sbc $9877
    sta $10
    sta $02
    lda.w #$0000
    clc
    sbc $02
    bvc C46EA3_PhotoAndNewEntityPreparationHelpers_L6EA3
    bpl C46EAF_PhotoAndNewEntityPreparationHelpers_L6EAF
    bra C46EA5_PhotoAndNewEntityPreparationHelpers_L6EA5
C46EA3_PhotoAndNewEntityPreparationHelpers_L6EA3:
    bmi C46EAF_PhotoAndNewEntityPreparationHelpers_L6EAF
C46EA5_PhotoAndNewEntityPreparationHelpers_L6EA5:
    lda $10
    eor.w #$FFFF
    inc A
    sta $0E
    bra C46EB3_PhotoAndNewEntityPreparationHelpers_L6EB3
C46EAF_PhotoAndNewEntityPreparationHelpers_L6EAF:
    lda $10
    sta $0E
C46EB3_PhotoAndNewEntityPreparationHelpers_L6EB3:
    tya
    asl A
    tax
    lda $0E
    cmp $0ED6,X
    bcs C46EF3_PhotoAndNewEntityPreparationHelpers_L6EF3
    lda $0E9A,X
    sec
    sbc $987B
    sta $10
    sta $02
    lda.w #$0000
    clc
    sbc $02
    bvc C46ED4_PhotoAndNewEntityPreparationHelpers_L6ED4
    bpl C46EE0_PhotoAndNewEntityPreparationHelpers_L6EE0
    bra C46ED6_PhotoAndNewEntityPreparationHelpers_L6ED6
C46ED4_PhotoAndNewEntityPreparationHelpers_L6ED4:
    bmi C46EE0_PhotoAndNewEntityPreparationHelpers_L6EE0
C46ED6_PhotoAndNewEntityPreparationHelpers_L6ED6:
    lda $10
    eor.w #$FFFF
    inc A
    sta $10
    bra C46EE4_PhotoAndNewEntityPreparationHelpers_L6EE4
C46EE0_PhotoAndNewEntityPreparationHelpers_L6EE0:
    lda $10
    sta $10
C46EE4_PhotoAndNewEntityPreparationHelpers_L6EE4:
    tya
    asl A
    tax
    lda $10
    cmp $0F12,X
    bcs C46EF3_PhotoAndNewEntityPreparationHelpers_L6EF3
    lda.w #$0001
    bra C46EF6_PhotoAndNewEntityPreparationHelpers_L6EF6
C46EF3_PhotoAndNewEntityPreparationHelpers_L6EF3:
    lda.w #$0000
C46EF6_PhotoAndNewEntityPreparationHelpers_L6EF6:
    pld
    rtl
