; EarthBound C4 required experience remaining helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:599A..C4:5A27 RequiredExperienceRemainingHelper

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7
C09032_DivideUnsignedWordByIndex   = $C09032

; ---------------------------------------------------------------------------
; C4:599A

C4599A_StoreRequiredExperienceRemainingForCharacter:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    tay
    dey
    sty $10
    tya
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    lda $99D3,X
    and.w #$00FF
    sta $0E
    cmp.w #$0063
    bne C459CA_RequiredExperienceRemainingHelper_L59CA
    lda.w #$0000
    sta $06
    lda.w #$0000
    sta $08
    bra C45A1D_RequiredExperienceRemainingHelper_L5A1D
C459CA_RequiredExperienceRemainingHelper_L59CA:
    txa
    clc
    adc.w #$99D4
    tay
    lda $0000,Y
    sta $0A
    lda $0002,Y
    sta $0C
    lda.w #$8F49
    sta $06
    lda.w #$00D5
    sta $08
    lda $0E
    asl A
    asl A
    sta $02
    inc $02
    inc $02
    inc $02
    inc $02
    ldy $10
    tya
    ldy.w #$0190
    jsl C09032_DivideUnsignedWordByIndex
    clc
    adc $02
    clc
    adc $06
    sta $06
    ldy.w #$0002
    lda [$06],Y
    tay
    lda [$06]
    sta $06
    sty $08
    sec
    lda $06
    sbc $0A
    sta $06
    lda $08
    sbc $0C
    sta $08
C45A1D_RequiredExperienceRemainingHelper_L5A1D:
    lda $06
    sta $18
    lda $08
    sta $1A
    pld
    rtl
