; EarthBound C4 special cast palette upload helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:EC6E..C4:ECAD UploadSpecialCastPalette

; ---------------------------------------------------------------------------
; External contracts used by this module

QueueOrTransferDynamicTileBlock = $C08ED2

; ---------------------------------------------------------------------------
; C4:EC6E

C4EC6E_UploadSpecialCastPalette:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    asl A
    asl A
    asl A
    asl A
    asl A
    sta $06
    stz $08
    clc
    lda $06
    adc.w #$7000
    sta $06
    lda $08
    adc.w #$007F
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    ldx.w #$0020
    lda.w #$0380
    jsl QueueOrTransferDynamicTileBlock
    sep #$20
    lda.b #$10
    sta $0030
    rep #$20
    pld
    rtl
