; EarthBound C4 window graphics load and flyover undraw helpers.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:7C3F..C4:8037 WindowGfxLoadAndFlyoverUndrawHelpers

; ---------------------------------------------------------------------------
; External contracts used by this module

C0856B_WaitFramesOrTransitionDelay           = $C0856B
C08E1C_UpdateBg2ScreenBaseRegistersFromQueue = $C08E1C
C08ED2_QueueOrTransferDynamicTileBlock       = $C08ED2
C08EED_CopyToVramOrRendererBuffer            = $C08EED
C08EFC_CommitTileBufferToStaging             = $C08EFC
C08F15_ClearVramOrRendererBuffer             = $C08F15
C08FF7_ResolveIndexedPointerOffset           = $C08FF7
C09032_DivideUnsignedWordByIndex             = $C09032
C2038B_FlyoverTextCleanupCallee              = $C2038B
C41A9E_GraphicsDecompressionRoutines_Main    = $C41A9E
C44963_ResetActiveTextGlyphRun               = $C44963
C44B3A_MergeGlyphSpanIntoTileBuffer          = $C44B3A

; ---------------------------------------------------------------------------
; C4:7C3F

; ---------------------------------------------------------------------------
; WRAM / data contracts
;
; C4 owns the window-graphics rebuild choreography here: decompression into
; bank $7F work buffers, compact tile-state reconstruction through the shared
; $3492 glyph scratch rows, and local refresh of the palette block at $0200.
; The C0 helpers remain transfer/copy callees; avoid assigning their NMI-side
; behavior beyond the display-selector latch and queue values written here.

WindowGfxBaseSourceLow                       = $0000
WindowGfxBaseSourceBank                      = $00E0
WindowGfxWorkBank                            = $007F
WindowGfxDecompressBufferBase                = $0000
WindowGfxCopySourceBlock                     = $2000
WindowGfxCopyByteCount                       = $1000
WindowGfxStagedTileBlock                     = $2A00
WindowGfxTileStateWorkBlock                  = $3200
WindowGfxTileStateClearSize                  = $0600
WindowGfxGlyphScratchRowsBase                = $3492
WindowGfxGlyphBitCursor                      = $9E23
WindowGfxGlyphRowCursor                      = $9E25
WindowGfxVariantOffsetLowMirror              = $9652
WindowGfxVariantOffsetHighMirror             = $9654
WindowFlavourSelection                       = $99CD
WindowFlavourRecordTable                     = $E01FB9
WindowFlavourPaletteBaseLow                  = $1FC8
WindowFlavourLeadEntityOverridePaletteLow    = $2108
WindowFlavourPaletteQueueDest                = $0200
WindowFlavourPaletteQueueBytes               = $0040
WindowFlavourSuppressLeadOverride            = $B4B6
LeadPartySlotIndex                           = $98A4
PartyObjectRecordIndexTable                  = $9891
ObjectRecordPointerTable                     = $4DC8
TileWordRewritePatternPointer                = $C45A89
DisplaySelectorLatch30                       = $0030
FlyoverBg2ScreenBaseY                        = $6000
FlyoverBg2ScreenBaseX                        = $7C00
WindowGfxAltSourceLow                        = $0754
WindowGfxAltDecompressByteCount              = $0100
WindowGfxAltFlavourSelector                  = $0008
WindowGfxPaletteRefreshWaitFrames            = $0008
FlyoverGlyphRunIndex                         = $0002
WindowGfxDisplaySelector18                   = $18

; Rebuilds the active text-window graphics cache: decompresses the base E0
; graphics into $7F, stages/copies the 7F tile blocks, rebuilds compact tile
; rows through the shared $3492 glyph scratch contract, and refreshes the
; flavor-dependent palette/tile work used by later window draws.
LOAD_WINDOW_GFX:
C47C3F_LoadWindowGfxAndResetWindowTileState = LOAD_WINDOW_GFX
    rep #$31
    phd
    tdc
    adc.w #$FFD4
    tcd
    lda.w #WindowGfxBaseSourceLow
    sta $0E
    lda.w #WindowGfxBaseSourceBank
    sta $10
    lda.w #WindowGfxDecompressBufferBase
    sta $12
    lda.w #WindowGfxWorkBank
    sta $14
    jsl C41A9E_GraphicsDecompressionRoutines_Main
    lda.w #WindowGfxCopySourceBlock
    sta $0E
    lda.w #WindowGfxWorkBank
    sta $10
    lda.w #WindowGfxCopyByteCount
    sta $12
    lda.w #WindowGfxWorkBank
    sta $14
    lda.w #WindowGfxStagedTileBlock
    jsl C08EED_CopyToVramOrRendererBuffer
    lda.w #WindowGfxTileStateWorkBlock
    sta $0E
    lda.w #WindowGfxWorkBank
    sta $10
    ldx.w #WindowGfxTileStateClearSize
    sep #$20
    lda.b #$00
    jsl C08F15_ClearVramOrRendererBuffer
    lda WindowFlavourSelection
    and.w #$00FF
    dec A
    sta $04
    asl A
    adc $04
    tax
    inx
    inx
    lda WindowFlavourRecordTable,X
    and.w #$00FF
    cmp.w #WindowGfxAltFlavourSelector
    bne C47CC2_WindowGfxLoadAndFlyoverUndrawHelpers_L7CC2
    lda.w #WindowGfxAltSourceLow
    sta $0E
    lda.w #WindowGfxBaseSourceBank
    sta $10
    lda.w #WindowGfxAltDecompressByteCount
    sta $12
    lda.w #WindowGfxWorkBank
    sta $14
    jsl C41A9E_GraphicsDecompressionRoutines_Main
C47CC2_WindowGfxLoadAndFlyoverUndrawHelpers_L7CC2:
    lda.w #$F054
    sta $06
    lda.w #$00C3
    sta $08
    ldy.w #$0020
    lda [$06],Y
    sta $2A
    ldy.w #$0022
    lda [$06],Y
    sta $28
    lda.w #WindowGfxStagedTileBlock
    sta $24
    lda.w #WindowGfxWorkBank
    sta $26
    lda.w #$0006
    sta $22
    lda.w #$0000
    sta $04
    jmp.w C47E27_WindowGfxLoadAndFlyoverUndrawHelpers_L7E27
C47CF1_WindowGfxLoadAndFlyoverUndrawHelpers_L7CF1:
    stz WindowGfxGlyphRowCursor
    stz WindowGfxGlyphBitCursor
    sep #$20
    lda.b #$FF
    sta $0E
    ldx.w #$0340
    rep #$20
    lda.w #WindowGfxGlyphScratchRowsBase
    jsl C08EFC_CommitTileBufferToStaging
    stz WindowGfxVariantOffsetHighMirror
    stz WindowGfxVariantOffsetLowMirror
    lda $04
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99CE
    sta $0A
    phb
    sep #$20
    pla
    sta $0C
    stz $0D
    rep #$20
    lda.w #$0002
    sta WindowGfxGlyphBitCursor
    lda.w #$0000
    sta $02
    bra C47D69_WindowGfxLoadAndFlyoverUndrawHelpers_L7D69
C47D35_WindowGfxLoadAndFlyoverUndrawHelpers_L7D35:
    and.w #$00FF
    inc $0A
    sec
    sbc.w #$0050
    and.w #$007F
    tay
    lda $C3F070
    sta $06
    lda $C3F072
    sta $08
    lda $2A
    jsl C09032_DivideUnsignedWordByIndex
    clc
    adc $06
    sta $06
    sta $0E
    lda $08
    sta $10
    ldx $28
    lda $22
    jsl C44B3A_MergeGlyphSpanIntoTileBuffer
    inc $02
C47D69_WindowGfxLoadAndFlyoverUndrawHelpers_L7D69:
    lda [$0A]
    and.w #$00FF
    bne C47D35_WindowGfxLoadAndFlyoverUndrawHelpers_L7D35
    ldy.w #$0000
    sty $20
    jmp.w C47E1B_WindowGfxLoadAndFlyoverUndrawHelpers_L7E1B
C47D78_WindowGfxLoadAndFlyoverUndrawHelpers_L7D78:
    tya
    asl A
    asl A
    asl A
    asl A
    sta $02
    lda $04
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    stx $1E
    lda.w #WindowGfxGlyphScratchRowsBase
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $1A
    lda $08
    sta $1C
    tya
    asl A
    asl A
    asl A
    asl A
    asl A
    sta $02
    lda $24
    sta $06
    lda $26
    sta $08
    txa
    clc
    adc $06
    sta $06
    sta $0E
    lda $08
    sta $10
    lda $02
    ldx $1A
    stx $06
    ldx $1C
    stx $08
    clc
    adc $06
    sta $06
    sta $12
    lda $08
    sta $14
    lda.w #$0010
    jsl C08EED_CopyToVramOrRendererBuffer
    lda $24
    sta $06
    lda $26
    sta $08
    ldx $1E
    txa
    clc
    adc.w #$0100
    clc
    adc $06
    sta $06
    sta $0E
    lda $08
    sta $10
    lda $02
    clc
    adc.w #$0010
    ldx $1A
    stx $06
    ldx $1C
    stx $08
    clc
    adc $06
    sta $06
    sta $12
    lda $08
    sta $14
    lda.w #$0010
    jsl C08EED_CopyToVramOrRendererBuffer
    ldy $20
    iny
    sty $20
C47E1B_WindowGfxLoadAndFlyoverUndrawHelpers_L7E1B:
    cpy.w #$0004
    bcs C47E25_WindowGfxLoadAndFlyoverUndrawHelpers_L7E25
    beq C47E25_WindowGfxLoadAndFlyoverUndrawHelpers_L7E25
    jmp.w C47D78_WindowGfxLoadAndFlyoverUndrawHelpers_L7D78
C47E25_WindowGfxLoadAndFlyoverUndrawHelpers_L7E25:
    inc $04
C47E27_WindowGfxLoadAndFlyoverUndrawHelpers_L7E27:
    lda $04
    cmp.w #$0004
    bcs C47E33_WindowGfxLoadAndFlyoverUndrawHelpers_L7E33
    beq C47E33_WindowGfxLoadAndFlyoverUndrawHelpers_L7E33
    jmp.w C47CF1_WindowGfxLoadAndFlyoverUndrawHelpers_L7CF1
C47E33_WindowGfxLoadAndFlyoverUndrawHelpers_L7E33:
    ldy.w #$0000
    bra C47E9D_WindowGfxLoadAndFlyoverUndrawHelpers_L7E9D
C47E38_WindowGfxLoadAndFlyoverUndrawHelpers_L7E38:
    lda.w #$0070
    sta $06
    lda.w #$007F
    sta $08
    lda $06
    sta $1A
    lda $08
    sta $1C
    ldx.w #$0000
    bra C47E97_WindowGfxLoadAndFlyoverUndrawHelpers_L7E97
C47E4F_WindowGfxLoadAndFlyoverUndrawHelpers_L7E4F:
    lda [$24]
    sta $1E
    xba
    and.w #$00FF
    eor.w #$00FF
    sta $02
    lda [$06]
    and.w #$00FF
    sta $04
    lda $1E
    and.w #$FF00
    ora $04
    ora $02
    sta [$24]
    lda $24
    sta $06
    lda $26
    sta $08
    inc $06
    inc $06
    lda $06
    sta $24
    lda $08
    sta $26
    lda $1A
    sta $06
    lda $1C
    sta $08
    inc $06
    inc $06
    lda $06
    sta $1A
    lda $08
    sta $1C
    inx
C47E97_WindowGfxLoadAndFlyoverUndrawHelpers_L7E97:
    cpx.w #$0008
    bcc C47E4F_WindowGfxLoadAndFlyoverUndrawHelpers_L7E4F
    iny
C47E9D_WindowGfxLoadAndFlyoverUndrawHelpers_L7E9D:
    cpy.w #$0020
    bcc C47E38_WindowGfxLoadAndFlyoverUndrawHelpers_L7E38
    lda.w #$2C00
    sta $16
    lda.w #$007F
    sta $18
    lda.w #$5A89
    sta $24
    lda.w #$00C4
    sta $26
    jmp.w C47F7E_WindowGfxLoadAndFlyoverUndrawHelpers_L7F7E
C47EB9_WindowGfxLoadAndFlyoverUndrawHelpers_L7EB9:
    cmp.w #$0020
    bne C47EC1_WindowGfxLoadAndFlyoverUndrawHelpers_L7EC1
    jmp.w C47F6A_WindowGfxLoadAndFlyoverUndrawHelpers_L7F6A
C47EC1_WindowGfxLoadAndFlyoverUndrawHelpers_L7EC1:
    sta $02
    and.w #$FFF0
    clc
    adc $02
    asl A
    asl A
    asl A
    asl A
    sta $0A
    stz $0C
    clc
    lda $0A
    adc.w #$0000
    sta $0A
    lda $0C
    adc.w #$007F
    sta $0C
    lda.w #$0070
    sta $06
    lda.w #$007F
    sta $08
    lda $06
    sta $1A
    lda $08
    sta $1C
    ldx.w #$0000
    bra C47F65_WindowGfxLoadAndFlyoverUndrawHelpers_L7F65
C47EF7_WindowGfxLoadAndFlyoverUndrawHelpers_L7EF7:
    lda [$0A]
    sta $1E
    xba
    and.w #$00FF
    eor.w #$00FF
    sta $02
    lda [$06]
    and.w #$00FF
    sta $04
    lda $1E
    and.w #$FF00
    ora $04
    ora $02
    sta [$16]
    ldy.w #$0100
    lda [$0A],Y
    sta $1E
    xba
    and.w #$00FF
    eor.w #$00FF
    sta $02
    lda [$06],Y
    and.w #$00FF
    sta $04
    lda $1E
    and.w #$FF00
    ora $04
    ora $02
    sta [$16],Y
    lda $16
    sta $06
    lda $18
    sta $08
    inc $06
    inc $06
    lda $06
    sta $16
    lda $08
    sta $18
    inc $0A
    inc $0A
    lda $1A
    sta $06
    lda $1C
    sta $08
    inc $06
    inc $06
    lda $06
    sta $1A
    lda $08
    sta $1C
    inx
C47F65_WindowGfxLoadAndFlyoverUndrawHelpers_L7F65:
    cpx.w #$0008
    bcc C47EF7_WindowGfxLoadAndFlyoverUndrawHelpers_L7EF7
C47F6A_WindowGfxLoadAndFlyoverUndrawHelpers_L7F6A:
    lda $24
    sta $06
    lda $26
    sta $08
    inc $06
    inc $06
    lda $06
    sta $24
    lda $08
    sta $26
C47F7E_WindowGfxLoadAndFlyoverUndrawHelpers_L7F7E:
    lda [$24]
    beq C47F85_WindowGfxLoadAndFlyoverUndrawHelpers_L7F85
    jmp.w C47EB9_WindowGfxLoadAndFlyoverUndrawHelpers_L7EB9
C47F85_WindowGfxLoadAndFlyoverUndrawHelpers_L7F85:
    pld
    rtl
; Refreshes the palette work block for the current window flavour. The
; lead-entity override path uses E0:2108 unless $B4B6 suppresses it; otherwise
; $99CD selects a row from the E0:1FB9 flavour table.
C47F87_RefreshWindowFlavourPaletteBlock:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda LeadPartySlotIndex
    and.w #$00FF
    tax
    dex
    lda PartyObjectRecordIndexTable,X
    and.w #$00FF
    asl A
    tax
    lda ObjectRecordPointerTable,X
    tax
    lda $000E,X
    and.w #$00FF
    tax
    cpx.w #$0001
    beq C47FB4_WindowGfxLoadAndFlyoverUndrawHelpers_L7FB4
    cpx.w #$0002
    bne C47FCF_WindowGfxLoadAndFlyoverUndrawHelpers_L7FCF
C47FB4_WindowGfxLoadAndFlyoverUndrawHelpers_L7FB4:
    lda WindowFlavourSuppressLeadOverride
    bne C47FCF_WindowGfxLoadAndFlyoverUndrawHelpers_L7FCF
    lda.w #WindowFlavourLeadEntityOverridePaletteLow
    sta $0E
    lda.w #WindowGfxBaseSourceBank
    sta $10
    ldx.w #WindowFlavourPaletteQueueBytes
    lda.w #WindowFlavourPaletteQueueDest
    jsl C08ED2_QueueOrTransferDynamicTileBlock
    bra C47FFF_WindowGfxLoadAndFlyoverUndrawHelpers_L7FFF
C47FCF_WindowGfxLoadAndFlyoverUndrawHelpers_L7FCF:
    lda.w #WindowFlavourPaletteBaseLow
    sta $06
    lda.w #WindowGfxBaseSourceBank
    sta $08
    lda WindowFlavourSelection
    and.w #$00FF
    dec A
    sta $04
    asl A
    adc $04
    tax
    lda WindowFlavourRecordTable,X
    clc
    adc $06
    sta $06
    sta $0E
    lda $08
    sta $10
    ldx.w #WindowFlavourPaletteQueueBytes
    lda.w #WindowFlavourPaletteQueueDest
    jsl C08ED2_QueueOrTransferDynamicTileBlock
C47FFF_WindowGfxLoadAndFlyoverUndrawHelpers_L7FFF:
    stz WindowFlavourPaletteQueueDest
    lda.w #WindowGfxPaletteRefreshWaitFrames
    jsl C0856B_WaitFramesOrTransitionDelay
    pld
    rtl
; Restores the flyover text presentation back to the normal world/window
; display path: updates the BG2 screen-base queue, lets the C2-owned callee do
; its own cleanup, reloads window graphics, resets glyph run 2, refreshes the
; window-flavour palette block, and writes selector #$18 into the $0030
; display-selector latch. C0/NMI owns the later upload/refresh interpretation.
UNDRAW_FLYOVER_TEXT:
C4800B_UndrawFlyoverTextAndRestoreWorldDisplay = UNDRAW_FLYOVER_TEXT
    rep #$31
    ldy.w #FlyoverBg2ScreenBaseY
    ldx.w #FlyoverBg2ScreenBaseX
    lda.w #$0000
    jsl C08E1C_UpdateBg2ScreenBaseRegistersFromQueue
    ; C4 only sequences this C2 cleanup; C2 owns the cleanup side effects.
    jsl C2038B_FlyoverTextCleanupCallee
    jsl LOAD_WINDOW_GFX
    lda.w #FlyoverGlyphRunIndex
    jsl C44963_ResetActiveTextGlyphRun
    jsl C47F87_RefreshWindowFlavourPaletteBlock
    sep #$20
    lda.b #WindowGfxDisplaySelector18
    sta DisplaySelectorLatch30
    rep #$20
    rtl

; ---------------------------------------------------------------------------
; C4:8037

C48037_LumineHallAndEvent353TextPayload:
    ; Text payload bytes consumed by the adjacent Event 353/Lumine Hall reveal
    ; helpers; this module only preserves the C4-local payload island.
    ; data bytes: C4:8037..C4:810E
    db $79,$57,$9D,$50,$5E,$5E,$5E,$5E,$50,$50,$79,$A4,$57,$A3,$50,$92
    db $95,$95,$9E,$50,$91,$50,$9C,$9F,$9E,$97,$50,$A2,$9F,$91,$94,$50
    db $97,$95,$A4,$A4,$99,$9E,$97,$50,$98,$95,$A2,$95,$5E,$5E,$5E,$50
    db $50,$83,$9F,$9F,$9E,$5C,$50,$79,$57,$9C,$9C,$50,$92,$95,$5E,$5E
    db $5E,$50,$50,$83,$9F,$9F,$9E,$5C,$50,$79,$57,$9C,$9C,$50,$92,$95
    db $5E,$5E,$5E,$50,$50,$83,$9F,$9F,$9E,$5C,$50,$79,$57,$9C,$9C,$50
    db $92,$95,$5E,$5E,$5E,$50,$50,$87,$98,$91,$A4,$50,$A7,$99,$9C,$9C
    db $50,$98,$91,$A0,$A0,$95,$9E,$50,$A4,$9F,$50,$A5,$A3,$6F,$50,$50
    db $87,$5E,$5E,$5E,$A7,$98,$91,$A4,$57,$A3,$50,$98,$91,$A0,$A0,$95
    db $9E,$99,$9E,$97,$6F,$50,$50,$7D,$A9,$50,$A4,$98,$9F,$A5,$97,$98
    db $A4,$A3,$50,$91,$A2,$95,$50,$92,$95,$99,$9E,$97,$50,$A7,$A2,$99
    db $A4,$A4,$95,$9E,$50,$9F,$A5,$A4,$50,$9F,$9E,$50,$A4,$98,$95,$50
    db $A7,$91,$9C,$9C,$5E,$5E,$5E,$50,$50,$9F,$A2,$50,$91,$A2,$95,$50
    db $A4,$98,$95,$A9,$6F,$50,$50
