; EarthBound C4 Your Sanctuary location palette data preparation helper prototype.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:DEE9..C4:DF7D PrepareYourSanctuaryLocationPaletteData

; ---------------------------------------------------------------------------
; External contracts used by this module

C08ED2_QueueOrTransferDynamicTileBlock = $C08ED2
C08EED_CopyToVramOrRendererBuffer      = $C08EED
C09032_DivideUnsignedWordByIndex       = $C09032

; ---------------------------------------------------------------------------
; C4:DEE9

C4DEE9_PrepareYourSanctuaryLocationPaletteData:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE4
    tcd
    pla
    stx $02
    tay
    sty $1A
    jsl $C005E7
    lda.w #$0000
    sta $0E
    lda.w #$00C3
    sta $10
    ldx.w #$0100
    lda.w #$0300
    jsl C08ED2_QueueOrTransferDynamicTileBlock
    ldy $1A
    tya
    and.w #$0007
    tax
    tya
    lsr A
    lsr A
    lsr A
    jsl $C007B6
    jsl $C00480
    sep #$20
    stz $0030
    rep #$20
    lda.w #$0200
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $16
    lda $08
    sta $18
    lda.w #$007E
    sta $18
    lda.w #$4000
    sta $06
    lda.w #$007F
    sta $08
    ldy.w #$0200
    lda $02
    jsl C09032_DivideUnsignedWordByIndex
    clc
    adc $06
    sta $06
    sta $0E
    lda $08
    sta $10
    lda $16
    sta $06
    lda $18
    sta $08
    lda $06
    sta $12
    lda $08
    sta $14
    lda.w #$0100
    jsl C08EED_CopyToVramOrRendererBuffer
    pld
    rts
