; EarthBound C4 battle target validity helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:A1F5..C4:A228 CheckIfValidTarget

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C4:A1F5


; ---------------------------------------------------------------------------
; C4:A1F2

C4A1F2_BattleTargetValidityPadding:
    ; data bytes: C4:A1F2..C4:A1F5
    db $12,$0F,$30

C4A1F5_CheckIfValidTarget:
    rep #$31
    ldy.w #$004E
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    lda $9FB8,X
    and.w #$00FF
    beq C4A224_CheckIfValidTarget_LA224
    lda $9FBB,X
    and.w #$00FF
    bne C4A224_CheckIfValidTarget_LA224
    lda $9FC9,X
    and.w #$00FF
    cmp.w #$0001
    beq C4A224_CheckIfValidTarget_LA224
    cmp.w #$0002
    beq C4A224_CheckIfValidTarget_LA224
    lda.w #$0001
    bra C4A227_CheckIfValidTarget_LA227
C4A224_CheckIfValidTarget_LA224:
    lda.w #$0000
C4A227_CheckIfValidTarget_LA227:
    rtl
