; EarthBound C4 file-select pose entity script-list runner prototype.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C4:D830..C4:D8FA RunFileSelectPoseEntityScriptList

; ---------------------------------------------------------------------------
; External contracts used by this module

C093F9_RunEntityScriptRecordForSlot           = $C093F9
C1004E_WaitWhileFileSelectEntityScriptBusy    = $C1004E
C46028_FindEntitySlotByCachedPoseDescriptorId = $C46028

; ---------------------------------------------------------------------------
; C4:D830

C4D830_RunFileSelectPoseEntityScriptList:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEA
    tcd
    pla
    sta $14
    bra C4D842_RunFileSelectPoseEntityScriptList_LD842
C4D83E_RunFileSelectPoseEntityScriptList_LD83E:
    jsl C1004E_WaitWhileFileSelectEntityScriptBusy
C4D842_RunFileSelectPoseEntityScriptList_LD842:
    lda $B4B4
    bne C4D83E_RunFileSelectPoseEntityScriptList_LD83E
    lda.w #$FD49
    sta $0A
    lda.w #$00C3
    sta $0C
    lda $14
    asl A
    asl A
    clc
    adc $0A
    sta $0A
    ldy.w #$0002
    lda [$0A],Y
    tay
    lda [$0A]
    sta $06
    sty $08
    bra C4D8C9_RunFileSelectPoseEntityScriptList_LD8C9
C4D868_RunFileSelectPoseEntityScriptList_LD868:
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    inc $0A
    inc $0A
    jsl C46028_FindEntitySlotByCachedPoseDescriptorId
    tax
    cpx.w #$FFFF
    beq C4D8BD_RunFileSelectPoseEntityScriptList_LD8BD
    lda.w #$00D4
    sta $06
    lda.w #$00C4
    sta $08
    lda $06
    sta $10
    lda $08
    sta $12
    lda [$0A]
    sta $04
    asl A
    adc $04
    sta $0E
    inc A
    inc A
    clc
    adc $06
    sta $06
    lda [$06]
    and.w #$00FF
    tay
    lda $0E
    pha
    lda $10
    sta $06
    lda $12
    sta $08
    pla
    clc
    adc $06
    sta $06
    lda [$06]
    jsl C093F9_RunEntityScriptRecordForSlot
C4D8BD_RunFileSelectPoseEntityScriptList_LD8BD:
    lda $0A
    sta $06
    lda $0C
    sta $08
    inc $06
    inc $06
C4D8C9_RunFileSelectPoseEntityScriptList_LD8C9:
    lda [$06]
    bne C4D868_RunFileSelectPoseEntityScriptList_LD868
C4D8CD_RunFileSelectPoseEntityScriptList_LD8CD:
    ldy.w #$0A62
    lda.w #$FFFF
    sta $0E
    ldx.w #$0000
    bra C4D8E8_RunFileSelectPoseEntityScriptList_LD8E8
C4D8DA_RunFileSelectPoseEntityScriptList_LD8DA:
    lda $0000,Y
    sta $02
    lda $0E
    and $02
    sta $0E
    iny
    iny
    inx
C4D8E8_RunFileSelectPoseEntityScriptList_LD8E8:
    cpx.w #$0017
    bcc C4D8DA_RunFileSelectPoseEntityScriptList_LD8DA
    jsl C1004E_WaitWhileFileSelectEntityScriptBusy
    lda $0E
    cmp.w #$FFFF
    bne C4D8CD_RunFileSelectPoseEntityScriptList_LD8CD
    pld
    rtl
