; EarthBound C2 event flag bitfield set or clear helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:165E..C2:16AD SetOrClearEventFlag

; ---------------------------------------------------------------------------
; External contracts used by this module

C09231_ModuloIndexByY        = $C09231
C4562F_EventFlagBitMaskTable = $C4562F

; ---------------------------------------------------------------------------
; C2:165E

C2165E_SetOrClearEventFlag:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEC
    tcd
    pla
    txy
    sty $12
    tax
    dec A
    sta $10
    lsr A
    lsr A
    lsr A
    clc
    adc.w #$9C08
    tax
    stx $0E
    ldy.w #$0008
    lda $10
    jsl C09231_ModuloIndexByY
    tax
    sep #$20
    lda C4562F_EventFlagBitMaskTable,X
    ldy $12
    beq C21698_SetOrClearEventFlag_L1698
    sta $00
    ldx $0E
    lda $0000,X
    ora $00
    bra C216A3_SetOrClearEventFlag_L16A3
C21698_SetOrClearEventFlag_L1698:
    eor.b #$FF
    sta $00
    ldx $0E
    lda $0000,X
    and $00
C216A3_SetOrClearEventFlag_L16A3:
    sta $0000,X
    rep #$20
    and.w #$00FF
    pld
    rtl
