; EarthBound C2 stealable item candidate selector.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:4316..C2:4348 SelectStealableItemCandidate

; ---------------------------------------------------------------------------
; External contracts used by this module

C241DC_BuildStealableItemCandidateList = $41DC
C26A2D_GetRandomBelow                  = $6A2D
C08E9A_GetRandom16                     = $C08E9A

; ---------------------------------------------------------------------------
; C2:4316

C24316_SelectStealableItemCandidate:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    jsr C241DC_BuildStealableItemCandidateList
    tax
    stx $0E
    bne C2432B_SelectStealableItemCandidate_L432B
    lda.w #$0000
    bra C24346_SelectStealableItemCandidate_L4346
C2432B_SelectStealableItemCandidate_L432B:
    jsl C08E9A_GetRandom16
    and.w #$0080
    beq C24339_SelectStealableItemCandidate_L4339
    lda.w #$0000
    bra C24346_SelectStealableItemCandidate_L4346
C24339_SelectStealableItemCandidate_L4339:
    ldx $0E
    txa
    jsr C26A2D_GetRandomBelow
    tax
    lda $A9D4,X
    and.w #$00FF
C24346_SelectStealableItemCandidate_L4346:
    pld
    rtl
