; EarthBound C2 guts reduction action.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:8EAE..C2:8F21 RunGutsReductionAction

; ---------------------------------------------------------------------------
; External contracts used by this module

C27CFD_CheckSelectedBattlerDefaultTextBlocker = $7CFD
C1DC66_DisplayBattleTextWithNumber            = $C1DC66

; ---------------------------------------------------------------------------
; C2:8EAE

C28EAE_RunGutsReductionAction:
    rep #$31
    phd
    tdc
    adc.w #$FFE6
    tcd
    jsr C27CFD_CheckSelectedBattlerDefaultTextBlocker
    cmp.w #$0000
    bne C28F1F_RunGutsReductionAction_L8F1F
    lda $A972
    clc
    adc.w #$002C
    tax
    lda $0000,X
    tay
    sta $04
    asl A
    adc $04
    lsr A
    lsr A
    sta $0000,X
    lda $A972
    clc
    adc.w #$002C
    tax
    stx $18
    ldx $A972
    lda $0035,X
    and.w #$00FF
    pha
    asl A
    pla
    ror A
    sta $16
    sta $02
    ldx $18
    lda $0000,X
    cmp $02
    bcs C28EFD_RunGutsReductionAction_L8EFD
    lda $16
    sta $0000,X
C28EFD_RunGutsReductionAction_L8EFD:
    lda.w #$F7EE
    sta $0E
    lda.w #$00C8
    sta $10
    ldx $A972
    tya
    sec
    sbc $002C,X
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C1DC66_DisplayBattleTextWithNumber
C28F1F_RunGutsReductionAction_L8F1F:
    pld
    rtl
