; EarthBound C2 Run final prayer opening transition.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:C572..C2:C5D1 C2C572_RunFinalPrayerOpeningTransition

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C2:C572

C2C572_RunFinalPrayerOpeningTransition:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda.w #$BC96
    sta $0E
    lda.w #$00C7
    sta $10
    ldx.w #$00B9
    lda.w #$01DE
    jsr $C37A
    lda.w #$0078
    jsr $69BE
    lda.w #$0040
    jsl $C0ABE0
    lda.w #$001E
    jsr $69BE
    lda.w #$003C
    sta $AD8C
    lda.w #$000C
    sta $AD8E
    lda.w #$F86A
    sta $0E
    lda.w #$00C9
    sta $10
    jsl $C1DC1C
    lda.w #$0005
    sta $A97A
    lda.w #$00E5
    jsr $C32C
    ldx.w #$0000
    lda.w #$01DF
    jsr $C21F
    pld
    rtl
