; EarthBound C2 loaded battle background palette restore and upload.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:DE96..C2:DF2E RestoreLoadedBattleBgPalettesAndUpload

; ---------------------------------------------------------------------------
; External contracts used by this module

C08ED2_CopyMemoryBlock = $C08ED2

; ---------------------------------------------------------------------------
; C2:DE96

C2DE96_RestoreLoadedBattleBgPalettesAndUpload:
    rep #$31
    phd
    tdc
    adc.w #$FFEA
    tcd
    lda.w #$AE00
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $12
    lda $08
    sta $14
    lda $06
    sta $0E
    lda $08
    sta $10
    ldx.w #$0020
    lda.w #$ADE0
    jsl C08ED2_CopyMemoryBlock
    lda.w #$AE77
    sta $0A
    phb
    sep #$20
    pla
    sta $0C
    stz $0D
    rep #$20
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    ldx.w #$0020
    lda.w #$AE57
    jsl C08ED2_CopyMemoryBlock
    lda $12
    sta $06
    lda $14
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    ldx.w #$0020
    lda $AE20
    jsl C08ED2_CopyMemoryBlock
    lda $AE4B
    and.w #$00FF
    beq C2DF2C_RestoreLoadedBattleBgPalettesAndUpload_LDF2C
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    ldx.w #$0020
    lda $AE97
    jsl C08ED2_CopyMemoryBlock
C2DF2C_RestoreLoadedBattleBgPalettesAndUpload_LDF2C:
    pld
    rtl
