; EarthBound C2 battle sprite row render-order builder.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:F917..C2:FADE BuildBattleSpriteRowRenderOrder

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_Multiply16 = $C08FF7

; ---------------------------------------------------------------------------
; C2:F917

C2F917_BuildBattleSpriteRowRenderOrder:
    rep #$31
    phd
    tdc
    adc.w #$FFEC
    tcd
    stz $AD58
    stz $AD56
    lda.w #$0008
    sta $12
    bra C2F967_BuildBattleSpriteRowRenderOrder_LF967
C2F92C_BuildBattleSpriteRowRenderOrder_LF92C:
    ldy.w #$004E
    jsl C08FF7_Multiply16
    tax
    lda $9FB8,X
    and.w #$00FF
    beq C2F962_BuildBattleSpriteRowRenderOrder_LF962
    lda $9FC9,X
    and.w #$00FF
    cmp.w #$0001
    beq C2F962_BuildBattleSpriteRowRenderOrder_LF962
    lda $9FBA,X
    and.w #$00FF
    cmp.w #$0001
    bne C2F962_BuildBattleSpriteRowRenderOrder_LF962
    lda $9FBC,X
    and.w #$00FF
    beq C2F95F_BuildBattleSpriteRowRenderOrder_LF95F
    inc $AD58
    bra C2F962_BuildBattleSpriteRowRenderOrder_LF962
C2F95F_BuildBattleSpriteRowRenderOrder_LF95F:
    inc $AD56
C2F962_BuildBattleSpriteRowRenderOrder_LF962:
    lda $12
    inc A
    sta $12
C2F967_BuildBattleSpriteRowRenderOrder_LF967:
    cmp.w #$0020
    bcc C2F92C_BuildBattleSpriteRowRenderOrder_LF92C
    stz $10
    lda.w #$0000
    sta $02
    jmp.w C2FA12_BuildBattleSpriteRowRenderOrder_LFA12
C2F976_BuildBattleSpriteRowRenderOrder_LF976:
    lda.w #$FFFF
    sta $04
    ldy.w #$0008
    sty $12
    bra C2F9CE_BuildBattleSpriteRowRenderOrder_LF9CE
C2F982_BuildBattleSpriteRowRenderOrder_LF982:
    tya
    ldy.w #$004E
    jsl C08FF7_Multiply16
    tax
    lda $9FB8,X
    and.w #$00FF
    beq C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    lda $9FC9,X
    and.w #$00FF
    cmp.w #$0001
    beq C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    lda $9FBA,X
    and.w #$00FF
    cmp.w #$0001
    bne C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    lda $9FBC,X
    and.w #$00FF
    bne C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    lda $9FF0,X
    and.w #$00FF
    cmp $10
    bcc C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    beq C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
    cmp $04
    beq C2F9C3_BuildBattleSpriteRowRenderOrder_LF9C3
    bcs C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9
C2F9C3_BuildBattleSpriteRowRenderOrder_LF9C3:
    ldy $12
    sty $0E
    sta $04
C2F9C9_BuildBattleSpriteRowRenderOrder_LF9C9:
    ldy $12
    iny
    sty $12
C2F9CE_BuildBattleSpriteRowRenderOrder_LF9CE:
    cpy.w #$0020
    bcc C2F982_BuildBattleSpriteRowRenderOrder_LF982
    lda $0E
    sep #$20
    ldx $02
    sta $AD7A,X
    rep #$20
    lda $04
    lsr A
    lsr A
    lsr A
    sep #$20
    ldx $02
    sta $AD5A,X
    rep #$20
    lda $0E
    ldy.w #$004E
    jsl C08FF7_Multiply16
    tax
    lda $9FAE,X
    jsr $F04E
    sep #$20
    sta $00
    lda.b #$12
    sec
    sbc $00
    ldx $02
    sta $AD62,X
    rep #$20
    lda $04
    sta $10
    inc $02
C2FA12_BuildBattleSpriteRowRenderOrder_LFA12:
    lda $02
    cmp $AD56
    bcs C2FA1E_BuildBattleSpriteRowRenderOrder_LFA1E
    beq C2FA1E_BuildBattleSpriteRowRenderOrder_LFA1E
    jmp.w C2F976_BuildBattleSpriteRowRenderOrder_LF976
C2FA1E_BuildBattleSpriteRowRenderOrder_LFA1E:
    stz $10
    lda.w #$0000
    sta $02
    jmp.w C2FAC4_BuildBattleSpriteRowRenderOrder_LFAC4
C2FA28_BuildBattleSpriteRowRenderOrder_LFA28:
    lda.w #$FFFF
    sta $04
    ldy.w #$0008
    sty $12
    bra C2FA80_BuildBattleSpriteRowRenderOrder_LFA80
C2FA34_BuildBattleSpriteRowRenderOrder_LFA34:
    tya
    ldy.w #$004E
    jsl C08FF7_Multiply16
    tax
    lda $9FB8,X
    and.w #$00FF
    beq C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    lda $9FC9,X
    and.w #$00FF
    cmp.w #$0001
    beq C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    lda $9FBA,X
    and.w #$00FF
    cmp.w #$0001
    bne C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    lda $9FBC,X
    and.w #$00FF
    beq C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    lda $9FF0,X
    and.w #$00FF
    cmp $10
    bcc C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    beq C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
    cmp $04
    beq C2FA75_BuildBattleSpriteRowRenderOrder_LFA75
    bcs C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B
C2FA75_BuildBattleSpriteRowRenderOrder_LFA75:
    ldy $12
    sty $0E
    sta $04
C2FA7B_BuildBattleSpriteRowRenderOrder_LFA7B:
    ldy $12
    iny
    sty $12
C2FA80_BuildBattleSpriteRowRenderOrder_LFA80:
    cpy.w #$0020
    bcc C2FA34_BuildBattleSpriteRowRenderOrder_LFA34
    lda $0E
    sep #$20
    ldx $02
    sta $AD82,X
    rep #$20
    lda $04
    lsr A
    lsr A
    lsr A
    sep #$20
    ldx $02
    sta $AD6A,X
    rep #$20
    lda $0E
    ldy.w #$004E
    jsl C08FF7_Multiply16
    tax
    lda $9FAE,X
    jsr $F04E
    sep #$20
    sta $00
    lda.b #$10
    sec
    sbc $00
    ldx $02
    sta $AD72,X
    rep #$20
    lda $04
    sta $10
    inc $02
C2FAC4_BuildBattleSpriteRowRenderOrder_LFAC4:
    lda $02
    cmp $AD58
    bcs C2FAD0_BuildBattleSpriteRowRenderOrder_LFAD0
    beq C2FAD0_BuildBattleSpriteRowRenderOrder_LFAD0
    jmp.w C2FA28_BuildBattleSpriteRowRenderOrder_LFA28
C2FAD0_BuildBattleSpriteRowRenderOrder_LFAD0:
    pld
    rtl
    rep #$31
    lda.w #$0001
    rtl
    rep #$31
    sta $B37C
    rtl
