; EarthBound ED asset AUDIO_PACK_85.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ed-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - ED:AB12..ED:B136 AssetAudioPack85

; ---------------------------------------------------------------------------
; ED:B136

; AssetAudioPack85End
EDB136_AssetAudioPack85End:
