; EarthBound D1 asset SPRITE_0118.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d1-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D1:FC00..D1:FCC0 AssetSprite0118

; ---------------------------------------------------------------------------
; D1:FCC0

; AssetSprite0118End
D1FCC0_AssetSprite0118End:
