; EarthBound D1 asset SPRITE_0079.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d1-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D1:C240..D1:C300 AssetSprite0079

; ---------------------------------------------------------------------------
; D1:C300

; AssetSprite0079End
D1C300_AssetSprite0079End:
