; EarthBound D1 asset SPRITE_0024.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d1-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D1:6200..D1:6400 AssetSprite0024

; ---------------------------------------------------------------------------
; D1:6400

; AssetSprite0024End
D16400_AssetSprite0024End:
