; EarthBound C1 Timed-delivery callback and text-command 1E experience/stat boost leaves.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:7440..C1:7708 c1_7440_timed_delivery_row_selector_callback

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C1:7440

C17440_TimedDeliveryRowSelectorCallback:
    rep #$31
    txa
    jsl $EF0EAD
    lda.w #$0000
    rts
C1744B_GiveExperienceTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEC
    tcd
    pla
    txa
    sta $12
    lda.w #$0004
    clc
    sbc $97CA
    bvc C17465_c1_7440_timed_delivery_row_selector_callback_L7465
    bpl C1747C_c1_7440_timed_delivery_row_selector_callback_L747C
    bra C17467_c1_7440_timed_delivery_row_selector_callback_L7467
C17465_c1_7440_timed_delivery_row_selector_callback_L7465:
    bmi C1747C_c1_7440_timed_delivery_row_selector_callback_L747C
C17467_c1_7440_timed_delivery_row_selector_callback_L7467:
    lda $12
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$744B
    jmp.w C17521_c1_7440_timed_delivery_row_selector_callback_L7521
C1747C_c1_7440_timed_delivery_row_selector_callback_L747C:
    sep #$10
    ldy.b #$18
    lda $12
    sta $06
    stz $08
    jsl $C09246
    lda $08
    pha
    lda $06
    pha
    ldy.b #$10
    sep #$20
    lda $97BD
    sta $06
    stz $07
    stz $08
    stz $09
    rep #$20
    jsl $C09246
    lda $08
    pha
    lda $06
    pha
    ldy.b #$08
    sep #$20
    lda $97BC
    sta $06
    stz $07
    stz $08
    stz $09
    rep #$20
    jsl $C09246
    lda $06
    sta $0A
    lda $08
    sta $0C
    sep #$20
    lda $97BB
    sta $06
    stz $07
    stz $08
    stz $09
    rep #$20
    lda $06
    ora $0A
    sta $06
    lda $08
    ora $0C
    sta $08
    pla
    sta $0A
    pla
    sta $0C
    lda $06
    ora $0A
    sta $06
    lda $08
    ora $0C
    sta $08
    pla
    sta $0A
    pla
    sta $0C
    lda $06
    ora $0A
    sta $06
    lda $08
    ora $0C
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    rep #$10
    ldx.w #$0001
    lda $97BA
    and.w #$00FF
    jsl $C1D9E9
    lda.w #$0000
C17521_c1_7440_timed_delivery_row_selector_callback_L7521:
    pld
    rts
C17523_BoostIqTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txa
    sta $0E
    lda.w #$0001
    clc
    sbc $97CA
    bvc C1753D_c1_7440_timed_delivery_row_selector_callback_L753D
    bpl C17553_c1_7440_timed_delivery_row_selector_callback_L7553
    bra C1753F_c1_7440_timed_delivery_row_selector_callback_L753F
C1753D_c1_7440_timed_delivery_row_selector_callback_L753D:
    bmi C17553_c1_7440_timed_delivery_row_selector_callback_L7553
C1753F_c1_7440_timed_delivery_row_selector_callback_L753F:
    lda $0E
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$7523
    bra C17582_c1_7440_timed_delivery_row_selector_callback_L7582
C17553_c1_7440_timed_delivery_row_selector_callback_L7553:
    lda $97BA
    and.w #$00FF
    tax
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A28
    tay
    lda $0E
    sep #$20
    sta $00
    lda $0000,Y
    clc
    adc $00
    sta $0000,Y
    rep #$20
    txa
    jsl $C21D7D
    rep #$20
    lda.w #$0000
C17582_c1_7440_timed_delivery_row_selector_callback_L7582:
    pld
    rts
C17584_BoostGutsTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txa
    sta $0E
    lda.w #$0001
    clc
    sbc $97CA
    bvc C1759E_c1_7440_timed_delivery_row_selector_callback_L759E
    bpl C175B4_c1_7440_timed_delivery_row_selector_callback_L75B4
    bra C175A0_c1_7440_timed_delivery_row_selector_callback_L75A0
C1759E_c1_7440_timed_delivery_row_selector_callback_L759E:
    bmi C175B4_c1_7440_timed_delivery_row_selector_callback_L75B4
C175A0_c1_7440_timed_delivery_row_selector_callback_L75A0:
    lda $0E
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$7584
    bra C175E3_c1_7440_timed_delivery_row_selector_callback_L75E3
C175B4_c1_7440_timed_delivery_row_selector_callback_L75B4:
    lda $97BA
    and.w #$00FF
    tax
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A26
    tay
    lda $0E
    sep #$20
    sta $00
    lda $0000,Y
    clc
    adc $00
    sta $0000,Y
    rep #$20
    txa
    jsl $C21BA4
    rep #$20
    lda.w #$0000
C175E3_c1_7440_timed_delivery_row_selector_callback_L75E3:
    pld
    rts
C175E5_BoostSpeedTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txa
    sta $0E
    lda.w #$0001
    clc
    sbc $97CA
    bvc C175FF_c1_7440_timed_delivery_row_selector_callback_L75FF
    bpl C17615_c1_7440_timed_delivery_row_selector_callback_L7615
    bra C17601_c1_7440_timed_delivery_row_selector_callback_L7601
C175FF_c1_7440_timed_delivery_row_selector_callback_L75FF:
    bmi C17615_c1_7440_timed_delivery_row_selector_callback_L7615
C17601_c1_7440_timed_delivery_row_selector_callback_L7601:
    lda $0E
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$75E5
    bra C17644_c1_7440_timed_delivery_row_selector_callback_L7644
C17615_c1_7440_timed_delivery_row_selector_callback_L7615:
    lda $97BA
    and.w #$00FF
    tax
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A25
    tay
    lda $0E
    sep #$20
    sta $00
    lda $0000,Y
    clc
    adc $00
    sta $0000,Y
    rep #$20
    txa
    jsl $C21AEB
    rep #$20
    lda.w #$0000
C17644_c1_7440_timed_delivery_row_selector_callback_L7644:
    pld
    rts
C17646_BoostVitalityTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txa
    sta $0E
    lda.w #$0001
    clc
    sbc $97CA
    bvc C17660_c1_7440_timed_delivery_row_selector_callback_L7660
    bpl C17676_c1_7440_timed_delivery_row_selector_callback_L7676
    bra C17662_c1_7440_timed_delivery_row_selector_callback_L7662
C17660_c1_7440_timed_delivery_row_selector_callback_L7660:
    bmi C17676_c1_7440_timed_delivery_row_selector_callback_L7676
C17662_c1_7440_timed_delivery_row_selector_callback_L7662:
    lda $0E
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$7646
    bra C176A5_c1_7440_timed_delivery_row_selector_callback_L76A5
C17676_c1_7440_timed_delivery_row_selector_callback_L7676:
    lda $97BA
    and.w #$00FF
    tax
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A27
    tay
    lda $0E
    sep #$20
    sta $00
    lda $0000,Y
    clc
    adc $00
    sta $0000,Y
    rep #$20
    txa
    jsl $C21D65
    rep #$20
    lda.w #$0000
C176A5_c1_7440_timed_delivery_row_selector_callback_L76A5:
    pld
    rts
C176A7_BoostLuckTextCommand:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txa
    sta $0E
    lda.w #$0001
    clc
    sbc $97CA
    bvc C176C1_c1_7440_timed_delivery_row_selector_callback_L76C1
    bpl C176D7_c1_7440_timed_delivery_row_selector_callback_L76D7
    bra C176C3_c1_7440_timed_delivery_row_selector_callback_L76C3
C176C1_c1_7440_timed_delivery_row_selector_callback_L76C1:
    bmi C176D7_c1_7440_timed_delivery_row_selector_callback_L76D7
C176C3_c1_7440_timed_delivery_row_selector_callback_L76C3:
    lda $0E
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$76A7
    bra C17706_c1_7440_timed_delivery_row_selector_callback_L7706
C176D7_c1_7440_timed_delivery_row_selector_callback_L76D7:
    lda $97BA
    and.w #$00FF
    tax
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A29
    tay
    lda $0E
    sep #$20
    sta $00
    lda $0000,Y
    clc
    adc $00
    sta $0000,Y
    rep #$20
    txa
    jsl $C21C5D
    rep #$20
    lda.w #$0000
C17706_c1_7440_timed_delivery_row_selector_callback_L7706:
    pld
    rts
