; EarthBound C1 battle text one-byte substitution slot setter.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:ACF8..C1:AD02 StageBattleTextSubstitutionByte

; ---------------------------------------------------------------------------
; External contracts used by this module

BattleTextSubstitutionByte = $9D11

; ---------------------------------------------------------------------------
; C1:ACF8

C1ACF8_StageBattleTextSubstitutionByte:
    rep #$31
    sep #$20
    sta BattleTextSubstitutionByte
    rep #$20
    rts
