; EarthBound C1 battle text HP/PP hide-window redirect.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:DD41..C1:DD47 RedirectHideHpppWindows

; ---------------------------------------------------------------------------
; External contracts used by this module

C100A1D_HideHpppWindows_Internal = $0A1D

; ---------------------------------------------------------------------------
; C1:DD41

C1DD41_RedirectHideHpppWindows:
    rep #$31
    jsr C100A1D_HideHpppWindows_Internal
    rtl
