; EarthBound C1 Battle text mode-one and selection-menu redirect strip.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:DD9F..C1:E1A2 DisplayCurrentActionTableTextMode1

; ---------------------------------------------------------------------------
; External contracts used by this module

C10036_SetBattleTextDisplayMode    = $0036
C1003C_ClearBattleTextDisplayMode  = $003C
C08FF7_ResolveIndexedPointerOffset = $C08FF7
C09279_DispatchTextPointer         = $C09279
C186B1_PrintTextFromPointer        = $C186B1

; ---------------------------------------------------------------------------
; C1:DD9F

C1DD9F_DisplayCurrentActionTableTextMode1:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda $20
    sta $06
    lda $22
    sta $08
    lda.w #$0001
    jsr C10036_SetBattleTextDisplayMode
    lda $06
    sta $0E
    lda $08
    sta $10
    jsl C186B1_PrintTextFromPointer
    jsr C1003C_ClearBattleTextDisplayMode
    pld
    rtl
C1DDC6_RedirectRemoveItemFromInventory:
    rep #$31
    jsr $8C27
    rtl
C1DDCC_RedirectC43573Helper:
    rep #$31
    jsl $C43573
    rtl
C1DDD3_RedirectC3E6F8Helper:
    rep #$31
    jsl $C3E6F8
    rtl
C1DDDA_BuildSelectionMenuSetupAndRedirects:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE4
    tcd
    pla
    sta $1A
    lda $2E
    sta $06
    lda $30
    sta $08
    lda $06
    sta $16
    lda $08
    sta $18
    lda $2A
    sta $0A
    lda $2C
    sta $0C
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda $16
    sta $06
    lda $18
    sta $08
    lda $06
    sta $12
    lda $08
    sta $14
    lda $1A
    jsr $153B
    pld
    rtl
    rep #$31
    jsr $163C
    rtl
    rep #$31
    jsr $196A
    rtl
    rep #$31
    jsr $CFC6
    rtl
    rep #$31
    jsr $242E
    rtl
    rep #$31
    jsr $CBCD
    rtl
    rep #$31
    phd
    tdc
    adc.w #$FFE2
    tcd
    ldx $A970
    lda $0000,X
    sta $1C
    lda.w #$0001
    jsr C10036_SetBattleTextDisplayMode
    ldx $A970
    lda $0008,X
    and.w #$00FF
    tax
    lda $1C
    jsl $C3EE14
    cmp.w #$0000
    bne C1DE71_DisplayCurrentActionTableTextMode1_LDE71
    jmp.w C1DF13_DisplayCurrentActionTableTextMode1_LDF13
C1DE71_DisplayCurrentActionTableTextMode1_LDE71:
    lda $1C
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99CE
    tay
    sty $1A
    ldx $A970
    lda $0032,X
    and.w #$00FF
    sta $04
    ldx $A970
    lda $0026,X
    sec
    sbc $04
    sta $02
    sta $18
    ldx $A970
    lda $0035,X
    and.w #$00FF
    sta $02
    ldx $A970
    lda $002C,X
    sec
    sbc $02
    sta $04
    ldx $A970
    lda $0007,X
    and.w #$00FF
    tax
    lda $1C
    jsr $9066
    ldy $1A
    sep #$20
    lda $0015,Y
    ldx $A970
    sta $0032,X
    rep #$20
    lda $18
    sta $02
    ldx $A970
    lda $0032,X
    and.w #$00FF
    clc
    adc $02
    ldx $A970
    sta $0026,X
    sep #$20
    lda $0018,Y
    ldx $A970
    sta $0035,X
    ldx $A970
    rep #$20
    lda $0035,X
    and.w #$00FF
    clc
    adc $04
    ldx $A970
    sta $002C,X
    lda.w #$7E11
    sta $0E
    lda.w #$00C7
    sta $10
    jsl C186B1_PrintTextFromPointer
    bra C1DF21_DisplayCurrentActionTableTextMode1_LDF21
C1DF13_DisplayCurrentActionTableTextMode1_LDF13:
    lda.w #$7E33
    sta $0E
    lda.w #$00C7
    sta $10
    jsl C186B1_PrintTextFromPointer
C1DF21_DisplayCurrentActionTableTextMode1_LDF21:
    lda $1C
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    sta $16
    tax
    lda $99FF,X
    and.w #$00FF
    dec A
    sta $02
    lda $16
    clc
    adc.w #$99F1
    clc
    adc $02
    tax
    lda $0000,X
    and.w #$00FF
    beq C1DFB8_DisplayCurrentActionTableTextMode1_LDFB8
    ldy.w #$0027
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$0019
    tax
    lda $D55000,X
    and.w #$00FF
    and.w #$0003
    cmp.w #$0001
    bne C1DFB8_DisplayCurrentActionTableTextMode1_LDFB8
    lda.w #$7B68
    sta $06
    lda.w #$00D5
    sta $08
    lda $06
    sta $12
    lda $08
    sta $14
    ldy.w #$0040
    lda [$06],Y
    pha
    iny
    iny
    lda [$06],Y
    sta $08
    pla
    sta $06
    sta $0E
    lda $08
    sta $10
    jsl C186B1_PrintTextFromPointer
    lda $12
    sta $06
    lda $14
    sta $08
    ldy.w #$0044
    lda [$06],Y
    pha
    iny
    iny
    lda [$06],Y
    sta $08
    pla
    sta $06
    pha
    lda $06
    sta $00BC
    lda $08
    sta $00BE
    pla
    jsl C09279_DispatchTextPointer
    bra C1E00A_DisplayCurrentActionTableTextMode1_LE00A
C1DFB8_DisplayCurrentActionTableTextMode1_LDFB8:
    lda.w #$7B68
    sta $06
    lda.w #$00D5
    sta $08
    lda $06
    sta $12
    lda $08
    sta $14
    ldy.w #$0034
    lda [$06],Y
    pha
    iny
    iny
    lda [$06],Y
    sta $08
    pla
    sta $06
    sta $0E
    lda $08
    sta $10
    jsl C186B1_PrintTextFromPointer
    lda $12
    sta $06
    lda $14
    sta $08
    ldy.w #$0038
    lda [$06],Y
    pha
    iny
    iny
    lda [$06],Y
    sta $08
    pla
    sta $06
    pha
    lda $06
    sta $00BC
    lda $08
    sta $00BE
    pla
    jsl C09279_DispatchTextPointer
C1E00A_DisplayCurrentActionTableTextMode1_LE00A:
    jsr C1003C_ClearBattleTextDisplayMode
    pld
    rtl
    rep #$31
    phd
    tdc
    adc.w #$FFE4
    tcd
    lda.w #$0001
    jsr C10036_SetBattleTextDisplayMode
    ldx $A970
    lda $0008,X
    and.w #$00FF
    tax
    stx $1A
    ldx $A970
    lda $0000,X
    ldx $1A
    jsl $C3EE14
    cmp.w #$0000
    bne C1E03D_DisplayCurrentActionTableTextMode1_LE03D
    jmp.w C1E18F_DisplayCurrentActionTableTextMode1_LE18F
C1E03D_DisplayCurrentActionTableTextMode1_LE03D:
    ldx $A970
    lda $0010,X
    and.w #$00FF
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99CE
    tay
    sty $18
    ldx $A970
    lda $0033,X
    and.w #$00FF
    sta $04
    ldx $A970
    lda $0028,X
    sec
    sbc $04
    sta $02
    sta $16
    ldx $A970
    lda $0034,X
    and.w #$00FF
    sta $02
    ldx $A970
    lda $002A,X
    sec
    sbc $02
    sta $04
    ldx $A970
    lda C10036_SetBattleTextDisplayMode,X
    and.w #$00FF
    sta $02
    ldx $A970
    lda $002E,X
    sec
    sbc $02
    sta $14
    ldx $A970
    lda $0007,X
    and.w #$00FF
    tax
    stx $12
    ldx $A970
    lda $0000,X
    ldx $12
    jsr $9066
    lda.w #$7E11
    sta $0E
    lda.w #$00C7
    sta $10
    jsl C186B1_PrintTextFromPointer
    ldy $18
    sep #$20
    lda $0016,Y
    ldx $A970
    sta $0033,X
    rep #$20
    lda $16
    sta $02
    ldx $A970
    lda $0033,X
    and.w #$00FF
    clc
    adc $02
    ldx $A970
    sta $0028,X
    sep #$20
    lda $0017,Y
    ldx $A970
    sta $0034,X
    ldx $A970
    rep #$20
    lda $0034,X
    and.w #$00FF
    clc
    adc $04
    ldx $A970
    sta $002A,X
    sep #$20
    lda $0019,Y
    ldx $A970
    sta C10036_SetBattleTextDisplayMode,X
    ldx $A970
    rep #$20
    lda C10036_SetBattleTextDisplayMode,X
    and.w #$00FF
    clc
    adc $14
    ldx $A970
    sta $002E,X
    sep #$20
    lda $0052,Y
    jsl $C2B608
    ldx $A970
    sta $003A,X
    ldy $18
    lda $0053,Y
    jsl $C2B608
    ldx $A970
    sta $0038,X
    ldy $18
    lda $0054,Y
    jsl $C2B639
    ldx $A970
    sta $0039,X
    ldy $18
    lda $0055,Y
    jsl $C2B639
    ldx $A970
    sta $0037,X
    ldy $18
    rep #$20
    tya
    clc
    adc.w #$0056
    tax
    stx $14
    sep #$20
    lda $0000,X
    jsl $C2B639
    ldx $A970
    sta C1003C_ClearBattleTextDisplayMode,X
    ldx $14
    lda $0000,X
    sta $00
    lda.b #$03
    sec
    sbc $00
    jsl $C2B639
    ldx $A970
    sta $003B,X
    bra C1E19D_DisplayCurrentActionTableTextMode1_LE19D
C1E18F_DisplayCurrentActionTableTextMode1_LE18F:
    lda.b #$33
    ror $0E85,X
    lda.w #$00C7
    sta $10
    jsl C186B1_PrintTextFromPointer
C1E19D_DisplayCurrentActionTableTextMode1_LE19D:
    jsr C1003C_ClearBattleTextDisplayMode
    pld
    rtl
