; EarthBound CB asset BATTLE_BACKGROUND_ARR_91.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:BFEE..CB:C05E AssetBattleBackgroundArr91

; ---------------------------------------------------------------------------
; CB:C05E

; AssetBattleBackgroundArr91End
CBC05E_AssetBattleBackgroundArr91End:
