; EarthBound CB asset BATTLE_BACKGROUND_ARR_85.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:8816..CB:899D AssetBattleBackgroundArr85

; ---------------------------------------------------------------------------
; CB:899D

; AssetBattleBackgroundArr85End
CB899D_AssetBattleBackgroundArr85End:
