; EarthBound CB asset BATTLE_BACKGROUND_PALETTE_103.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:CD14..CB:CD34 AssetBattleBackgroundPalette103

; ---------------------------------------------------------------------------
; CB:CD34

; AssetBattleBackgroundPalette103End
CBCD34_AssetBattleBackgroundPalette103End:
