; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_0912_name_entry_grid_character_offset_table.asm

hirom
org $C20912

NAME_ENTRY_GRID_CHARACTER_OFFSET_TABLE:
!C20912_NameEntryGridCharacterOffsetTable = NAME_ENTRY_GRID_CHARACTER_OFFSET_TABLE
    db $05,$07,$09,$0B,$0D,$0F,$11,$13,$15,$FF,$FF,$1B,$1D,$FF
    db $23,$25,$27,$29,$2B,$2D,$2F,$31,$33,$FF,$FF,$39,$3B,$FF
    db $41,$43,$45,$47,$49,$4B,$4D,$4F,$51,$FF,$FF,$57,$59,$FF
    db $5F,$61,$63,$65,$67,$69,$6B,$6D,$6F,$71,$FF,$77,$79,$FF
    db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$7F,$81,$FF
C20958_NameEntryGridCharacterOffsetTable_End:
