; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_02ac_register_and_upload_window_title_buffer.asm

hirom
org $C202AC

!C08FF7_ResolveIndexedPointerOffset = $C08FF7
!C444FB_UploadWindowTitleGlyphTiles = $C444FB
!WindowRecordIndexTable = $88E4
!WindowRecordStride = $0052
!WindowRecordBase = $8650
!WindowRecordTitleUploadSlot = $003B
!WindowRecordTitleGlyphSource = $003C
!WindowTitleUploadSlotTable = $894E
!WindowTitleUploadSlotCount = $0005
!UnregisteredTitleUploadSlot = $FFFF
!FirstTitleUploadSlotIndex = $0000
!WindowTitleVramDestinationBase = $7700
C202AC_RegisterAndUploadWindowTitleBuffer:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sta $02
    asl A
    tax
    lda !WindowRecordIndexTable,X
    ldy.w #!WindowRecordStride
    jsl !C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #!WindowRecordBase
    tay
    clc
    adc.w #!WindowRecordTitleGlyphSource
    sta $04
    lda !WindowRecordTitleUploadSlot,Y
    and.w #$00FF
    bne C2030E_RegisterAndUploadWindowTitleBuffer_L030E
    lda.w #!FirstTitleUploadSlotIndex
    sta $10
    bra C202F3_RegisterAndUploadWindowTitleBuffer_L02F3
C202DE_RegisterAndUploadWindowTitleBuffer_L02DE:
    asl A
    clc
    adc.w #!WindowTitleUploadSlotTable
    tax
    stx $0E
    lda $0000,X
    cmp.w #!UnregisteredTitleUploadSlot
    beq C202FA_RegisterAndUploadWindowTitleBuffer_L02FA
    lda $10
    inc A
    sta $10
C202F3_RegisterAndUploadWindowTitleBuffer_L02F3:
    cmp.w #!WindowTitleUploadSlotCount
    bne C202DE_RegisterAndUploadWindowTitleBuffer_L02DE
    bra C20329_RegisterAndUploadWindowTitleBuffer_L0329
C202FA_RegisterAndUploadWindowTitleBuffer_L02FA:
    lda $02
    asl A
    tax
    lda !WindowRecordIndexTable,X
    ldx $0E
    sta $0000,X
    lda $10
    sep #$20
    inc A
    sta !WindowRecordTitleUploadSlot,Y
C2030E_RegisterAndUploadWindowTitleBuffer_L030E:
    rep #$20
    lda !WindowRecordTitleUploadSlot,Y
    and.w #$00FF
    dec A
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc.w #!WindowTitleVramDestinationBase
    tax
    lda $04
    jsl !C444FB_UploadWindowTitleGlyphTiles
C20329_RegisterAndUploadWindowTitleBuffer_L0329:
    pld
    rts
