; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_1628_test_event_flag.asm

hirom
org $C21628

!C09231_ModuloIndexByY = $C09231
!C4562F_EventFlagBitMaskTable = $C4562F
!EventFlagBitfieldBase = $9C08
!EventFlagBitsPerByte = $0008
!BoolFalse = $0000
!BoolTrue = $0001
GET_EVENT_FLAG:
!C21628_TestEventFlag = GET_EVENT_FLAG
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    dec A
    sta $0E
    lsr A
    lsr A
    lsr A
    pha
    ldy.w #!EventFlagBitsPerByte
    lda $0E
    jsl !C09231_ModuloIndexByY
    tax
    sep #$20
    lda !C4562F_EventFlagBitMaskTable,X
    plx
    and !EventFlagBitfieldBase,X
    rep #$20
    and.w #$00FF
    beq C21659_TestEventFlag_L1659
    lda.w #!BoolTrue
    bra C2165C_TestEventFlag_L165C
C21659_TestEventFlag_L1659:
    lda.w #!BoolFalse
C2165C_TestEventFlag_L165C:
    pld
    rtl
