; EarthBound C2 party status slot scanner.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:26F0..C2:272F FindFirstPartySlotWithStateOne

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

PlayerControlledPartyCount = $98A4
PartyStatusRegistry        = $988B
PartyCharacterRecordStride = $005F
PartyCharacterStateByte    = $99DC
PartyStateOne              = $0001

; ---------------------------------------------------------------------------
; C2:26F0

C226F0_FindFirstPartySlotWithStateOne:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$0000
    sta $0E
    bra C22702_FindFirstPartySlotWithStateOne_L2702
C226FF_FindFirstPartySlotWithStateOne_L26FF:
    inc A
    sta $0E
C22702_FindFirstPartySlotWithStateOne_L2702:
    tax
    lda PartyStatusRegistry,X
    and.w #$00FF
    dec A
    ldy.w #PartyCharacterRecordStride
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    lda PartyCharacterStateByte,X
    and.w #$00FF
    cmp.w #PartyStateOne
    beq C2272B_FindFirstPartySlotWithStateOne_L272B
    lda PlayerControlledPartyCount
    and.w #$00FF
    sta $02
    lda $0E
    cmp $02
    bcc C226FF_FindFirstPartySlotWithStateOne_L26FF
C2272B_FindFirstPartySlotWithStateOne_L272B:
    lda $0E
    pld
    rtl
