; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_3109_battle_start_ufo_present_fallback_table.asm

hirom
org $C23109

CONSOLATION_ITEM_TABLE:
!C23109_BattleStartUfoPresentFallbackTable = CONSOLATION_ITEM_TABLE
    db $84,$58,$59,$5A,$5B,$5C,$5D,$5F,$00
    db $85,$6A,$6B,$6C,$6D,$6E,$6F,$70,$00
!C2311B_BattleStartUfoPresentFallbackTable_End = BATTLE_SELECTION_MENU
