; EarthBound C2 mask-set active typed battler remover.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:6E77..C2:6EF8 MaskSet_RemoveActiveTypedBattlers

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

C4A279_OneHotTargetBitMaskTableLo = $A279
C4A279_OneHotTargetBitMaskTableBank = $00C4
BattlersTableBase = $9FAC
BattlerRowSize = $004E
BattlerConsciousnessByte = $000C
BattlerNpcIdByte = $000F
CurrentTargetMaskLo = $A96C
CurrentTargetMaskHi = $A96E
TargetBitIndex = $0E
OneHotMaskLo = $0A
OneHotMaskHi = $0C
WorkingMaskLo = $06
WorkingMaskHi = $08
TargetMaskBitLimit = $0020

; ---------------------------------------------------------------------------
; C2:6E77

REMOVE_NPC_TARGETTING:
C26E77_MaskSet_RemoveActiveNpcBattlers = REMOVE_NPC_TARGETTING
C26E77_MaskSet_RemoveActiveTypedCandidates = C26E77_MaskSet_RemoveActiveNpcBattlers
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    ldx.w #BattlersTableBase
    lda.w #$0000
    sta TargetBitIndex
    bra C26EF1_MaskSet_RemoveActiveTypedCandidates_L6EF1
C26E89_MaskSet_RemoveActiveTypedCandidates_L6E89:
    lda.w BattlerConsciousnessByte,X
    and.w #$00FF
    beq C26EE6_MaskSet_RemoveActiveTypedCandidates_L6EE6
    lda.w BattlerNpcIdByte,X
    and.w #$00FF
    beq C26EE6_MaskSet_RemoveActiveTypedCandidates_L6EE6
    lda.w #C4A279_OneHotTargetBitMaskTableLo
    sta WorkingMaskLo
    lda.w #C4A279_OneHotTargetBitMaskTableBank
    sta WorkingMaskHi
    lda TargetBitIndex
    asl A
    asl A
    clc
    adc WorkingMaskLo
    sta WorkingMaskLo
    ldy.w #$0002
    lda [WorkingMaskLo],Y
    tay
    lda [WorkingMaskLo]
    sta OneHotMaskLo
    sty OneHotMaskHi
    lda OneHotMaskLo
    eor.w #$FFFF
    sta OneHotMaskLo
    lda OneHotMaskHi
    eor.w #$FFFF
    sta OneHotMaskHi
    lda CurrentTargetMaskLo
    sta WorkingMaskLo
    lda CurrentTargetMaskHi
    sta WorkingMaskHi
    lda WorkingMaskLo
    and OneHotMaskLo
    sta WorkingMaskLo
    lda WorkingMaskHi
    and OneHotMaskHi
    sta WorkingMaskHi
    lda WorkingMaskLo
    sta CurrentTargetMaskLo
    lda WorkingMaskHi
    sta CurrentTargetMaskHi
C26EE6_MaskSet_RemoveActiveTypedCandidates_L6EE6:
    txa
    clc
    adc.w #BattlerRowSize
    tax
    lda TargetBitIndex
    inc A
    sta TargetBitIndex
C26EF1_MaskSet_RemoveActiveTypedCandidates_L6EF1:
    cmp.w #TargetMaskBitLimit
    bcc C26E89_MaskSet_RemoveActiveTypedCandidates_L6E89
    pld
    rtl
