; EarthBound C2 bounded offense decrease helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:7DDC..C2:7E33 ApplyBoundedOffenseDecrease

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C2:7DDC

C27DDC_ApplyBoundedOffenseDecrease:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sta $02
    clc
    adc.w #$0026
    tay
    lda $0000,Y
    lsr A
    lsr A
    lsr A
    lsr A
    beq C27DF9_ApplyBoundedOffenseDecrease_L7DF9
    tax
    bra C27DFC_ApplyBoundedOffenseDecrease_L7DFC
C27DF9_ApplyBoundedOffenseDecrease_L7DF9:
    ldx.w #$0001
C27DFC_ApplyBoundedOffenseDecrease_L7DFC:
    stx $04
    lda $0000,Y
    sec
    sbc $04
    sta $0000,Y
    lda $02
    clc
    adc.w #$0026
    tax
    stx $10
    ldx $02
    lda $0032,X
    and.w #$00FF
    sta $04
    asl A
    adc $04
    lsr A
    lsr A
    sta $0E
    sta $02
    ldx $10
    lda $0000,X
    cmp $02
    bcs C27E31_ApplyBoundedOffenseDecrease_L7E31
    lda $0E
    sta $0000,X
C27E31_ApplyBoundedOffenseDecrease_L7E31:
    pld
    rts
