; EarthBound C2 mask-set bit test helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:7029..C2:7089 MaskSet_TestBit

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

C4A279_OneHotTargetBitMaskTableLo = $A279
C4A279_OneHotTargetBitMaskTableBank = $00C4
CurrentTargetMaskLo = $A96C
CurrentTargetMaskHi = $A96E
MaskBitIndexArg = $0E
OneHotMaskLo = $0A
OneHotMaskHi = $0C
WorkingMaskLo = $06
WorkingMaskHi = $08
NullMaskWord = $0000
MaskBitAbsent = $0000
MaskBitPresent = $0001

; ---------------------------------------------------------------------------
; C2:7029

IS_CHAR_TARGETTED:
C27029_MaskSet_TestBit = IS_CHAR_TARGETTED
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sta MaskBitIndexArg
    ldx.w #MaskBitAbsent
    lda.w #C4A279_OneHotTargetBitMaskTableLo
    sta WorkingMaskLo
    lda.w #C4A279_OneHotTargetBitMaskTableBank
    sta WorkingMaskHi
    lda MaskBitIndexArg
    asl A
    asl A
    clc
    adc WorkingMaskLo
    sta WorkingMaskLo
    ldy.w #$0002
    lda [WorkingMaskLo],Y
    tay
    lda [WorkingMaskLo]
    sta OneHotMaskLo
    sty OneHotMaskHi
    lda CurrentTargetMaskLo
    sta WorkingMaskLo
    lda CurrentTargetMaskHi
    sta WorkingMaskHi
    lda WorkingMaskLo
    and OneHotMaskLo
    sta WorkingMaskLo
    lda WorkingMaskHi
    and OneHotMaskHi
    sta WorkingMaskHi
    lda.w #NullMaskWord
    sta OneHotMaskLo
    lda.w #NullMaskWord
    sta OneHotMaskHi
    lda WorkingMaskHi
    cmp OneHotMaskHi
    bne C27081_MaskSet_TestBit_L7081
    lda WorkingMaskLo
    cmp OneHotMaskLo
C27081_MaskSet_TestBit_L7081:
    beq C27086_MaskSet_TestBit_L7086
    ldx.w #MaskBitPresent
C27086_MaskSet_TestBit_L7086:
    txa
    pld
    rtl
