; EarthBound C2 PP reduction action.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:8E42..C2:8EAE RunPpReductionAction

; ---------------------------------------------------------------------------
; External contracts used by this module

C26A44_RollRandomAmount             = $6A44
C2721D_ReduceBattlerPpTarget        = $721D
C1DC1C_DisplayBattleTextFromPointer = $C1DC1C
C1DC66_DisplayBattleTextWithNumber  = $C1DC66

; ---------------------------------------------------------------------------
; C2:8E42

C28E42_RunPpReductionAction:
    rep #$31
    phd
    tdc
    adc.w #$FFE8
    tcd
    ldx $A972
    lda $0019,X
    bne C28E62_RunPpReductionAction_L8E62
    lda.w #$FB05
    sta $0E
    lda.w #$00C8
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C28EAC_RunPpReductionAction_L8EAC
C28E62_RunPpReductionAction_L8E62:
    ldx $A972
    lda $001B,X
    lsr A
    lsr A
    lsr A
    lsr A
    beq C28E9E_RunPpReductionAction_L8E9E
    jsr C26A44_RollRandomAmount
    tay
    sty $16
    tyx
    lda $A972
    jsr C2721D_ReduceBattlerPpTarget
    lda.w #$7755
    sta $0E
    lda.w #$00EF
    sta $10
    ldy $16
    tya
    sta $06
    stz $08
    bpl C28E90_RunPpReductionAction_L8E90
    dec $08
C28E90_RunPpReductionAction_L8E90:
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C1DC66_DisplayBattleTextWithNumber
    bra C28EAC_RunPpReductionAction_L8EAC
C28E9E_RunPpReductionAction_L8E9E:
    lda.w #$766E
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C28EAC_RunPpReductionAction_L8EAC:
    pld
    rtl
