; EarthBound C2 offense and defense reduction action.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:8F21..C2:8F97 RunOffenseDefenseReductionAction
;
; Runtime contract:
; - Selected row `$A972` supplies the target battler.
; - First pass snapshots row `+0x26` offense, applies `C2:7DDC`, and reports
;   the positive offense-loss delta through C8:F885.
; - Second pass snapshots row `+0x28` defense, applies `C2:7E33`, and reports
;   the positive defense-loss delta through C8:F8A2.

; ---------------------------------------------------------------------------
; External contracts used by this module

C27CFD_CheckSelectedBattlerDefaultTextBlocker = $7CFD
C27DDC_ApplyBoundedOffenseDecrease            = $7DDC
C27E33_ApplyBoundedDefenseDecrease            = $7E33
C1DC66_DisplayBattleTextWithSubstitutionPayload = $C1DC66
C8MSG_OffenseDecreaseAmount                   = $F885
C8MSG_DefenseDecreaseAmount                   = $F8A2

; ---------------------------------------------------------------------------
; C2:8F21

BTLACT_REDUCEOFFDEF:
C28F21_RunOffenseDefenseReductionAction = BTLACT_REDUCEOFFDEF
    rep #$31
    phd
    tdc
    adc.w #$FFE8
    tcd
    jsr FAIL_ATTACK_ON_NPCS
    cmp.w #$0000
    bne C28F95_RunOffenseDefenseReductionAction_L8F95
    ldx $A972
    ldy $0026,X
    sty $16
    lda $A972
    ; Row `+0x26` offense is lowered by the bounded offense helper.
    jsr HEXADECIMATE_OFFENSE
    lda.w #C8MSG_OffenseDecreaseAmount
    sta $0E
    lda.w #$00C8
    sta $10
    ldx $A972
    ldy $16
    tya
    sec
    ; Report old offense minus final offense.
    sbc $0026,X
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C1DC66_DisplayBattleTextWithSubstitutionPayload
    ldx $A972
    ldy $0028,X
    sty $16
    lda $A972
    ; Row `+0x28` defense is lowered by the bounded defense helper.
    jsr HEXADECIMATE_DEFENSE
    lda.w #C8MSG_DefenseDecreaseAmount
    sta $0E
    lda.w #$00C8
    sta $10
    ldx $A972
    ldy $16
    tya
    sec
    ; Report old defense minus final defense.
    sbc $0028,X
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C1DC66_DisplayBattleTextWithSubstitutionPayload
C28F95_RunOffenseDefenseReductionAction_L8F95:
    pld
    rtl
