; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_8f21_run_offense_defense_reduction_action.asm

hirom
org $C28F21

!C27CFD_CheckSelectedBattlerDefaultTextBlocker = $7CFD
!C27DDC_ApplyBoundedOffenseDecrease = $7DDC
!C27E33_ApplyBoundedDefenseDecrease = $7E33
!C1DC66_DisplayBattleTextWithSubstitutionPayload = $C1DC66
!C8MSG_OffenseDecreaseAmount = $F885
!C8MSG_DefenseDecreaseAmount = $F8A2
BTLACT_REDUCEOFFDEF:
!C28F21_RunOffenseDefenseReductionAction = BTLACT_REDUCEOFFDEF
    rep #$31
    phd
    tdc
    adc.w #$FFE8
    tcd
    jsr !C27CFD_CheckSelectedBattlerDefaultTextBlocker
    cmp.w #$0000
    bne C28F95_RunOffenseDefenseReductionAction_L8F95
    ldx $A972
    ldy $0026,X
    sty $16
    lda $A972
    jsr HEXADECIMATE_OFFENSE
    lda.w #!C8MSG_OffenseDecreaseAmount
    sta $0E
    lda.w #$00C8
    sta $10
    ldx $A972
    ldy $16
    tya
    sec
    sbc $0026,X
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl !C1DC66_DisplayBattleTextWithSubstitutionPayload
    ldx $A972
    ldy $0028,X
    sty $16
    lda $A972
    jsr HEXADECIMATE_DEFENSE
    lda.w #!C8MSG_DefenseDecreaseAmount
    sta $0E
    lda.w #$00C8
    sta $10
    ldx $A972
    ldy $16
    tya
    sec
    sbc $0028,X
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl !C1DC66_DisplayBattleTextWithSubstitutionPayload
C28F95_RunOffenseDefenseReductionAction_L8F95:
    pld
    rtl
