; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c2/c2_9051_queued_battler_stat_shield_normalization_callback.asm

hirom
org $C29051

!C1DC1C_DisplayBattleTextFromPointer = $C1DC1C
BTLACT_NEUTRALIZE:
!C29051_QueuedBattlerStatShieldNormalizationCallback = BTLACT_NEUTRALIZE
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldx $A972
    lda $0032,X
    and.w #$00FF
    ldx $A972
    sta $0026,X
    ldx $A972
    lda $0033,X
    and.w #$00FF
    ldx $A972
    sta $0028,X
    ldx $A972
    lda $0034,X
    and.w #$00FF
    ldx $A972
    sta $002A,X
    ldx $A972
    lda $0035,X
    and.w #$00FF
    ldx $A972
    sta $002C,X
    ldx $A972
    lda $0036,X
    and.w #$00FF
    ldx $A972
    sta $002E,X
    sep #$20
    lda.b #$00
    ldx $A972
    sta $0025,X
    ldx $A972
    sta $0023,X
    rep #$20
    lda.w #$7123
    sta $0E
    lda.w #$00EF
    sta $10
    jsl !C1DC1C_DisplayBattleTextFromPointer
    pld
    rtl
