; EarthBound C2 resist-checked asleep status action.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:9F06..C2:9F57 RunResistCheckedAsleepStatusAction

; ---------------------------------------------------------------------------
; External contracts used by this module

C26BB8_BuildCandidateMaskPhase                = $6BB8
C2724A_ApplyBattlerAfflictionSubgroupValue    = $724A
C27CFD_CheckSelectedBattlerDefaultTextBlocker = $7CFD
C1DC1C_DisplayBattleTextFromPointer           = $C1DC1C
EFMSG_AsleepInflicted                         = $6C55
EFMSG_StatusNoEffect                          = $766E

; ---------------------------------------------------------------------------
; C2:9F06

BTLACT_HYPNOSIS_A:
C29F06_RunResistCheckedAsleepStatusAction = BTLACT_HYPNOSIS_A
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    jsr FAIL_ATTACK_ON_NPCS
    cmp.w #$0000
    bne C29F55_RunResistCheckedAsleepStatusAction_L9F55
    ldx $A972
    sep #$20
    lda $003C,X
    jsr C26BB8_BuildCandidateMaskPhase
    cmp.w #$0000
    beq C29F47_RunResistCheckedAsleepStatusAction_L9F47
    ldy.w #$0001
    ldx.w #$0002
    lda $A972
    jsr INFLICT_STATUS_BATTLE
    cmp.w #$0000
    beq C29F47_RunResistCheckedAsleepStatusAction_L9F47
    ; Success/failure EF scripts both read the target-name battle text context.
    lda.w #EFMSG_AsleepInflicted
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29F55_RunResistCheckedAsleepStatusAction_L9F55
C29F47_RunResistCheckedAsleepStatusAction_L9F47:
    lda.w #EFMSG_StatusNoEffect
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29F55_RunResistCheckedAsleepStatusAction_L9F55:
    pld
    rtl
