; EarthBound C2 hard state recovery action family.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:9CB8..C2:9E38 TryRecoverSelectedBattlerHardState

; ---------------------------------------------------------------------------
; External contracts used by this module

C27397_InstallBattlerHeavyRecoveryReset          = $7397
C1DC1C_DisplayBattleTextFromPointer              = $C1DC1C
C29C2C_TryRecoverSelectedBattlerBroadAfflictions = $C29C2C

; ---------------------------------------------------------------------------
; C2:9CB8

C29CB8_TryRecoverSelectedBattlerHardState:
    rep #$31
    ldx $A972
    lda $001D,X
    and.w #$00FF
    cmp.w #$0001
    bne C29CD7_TryRecoverSelectedBattlerHardState_L9CD7
    ldx $A972
    lda $0015,X
    tax
    lda $A972
    jsr C27397_InstallBattlerHeavyRecoveryReset
    bra C29CDB_TryRecoverSelectedBattlerHardState_L9CDB
C29CD7_TryRecoverSelectedBattlerHardState_L9CD7:
    jsl C29C2C_TryRecoverSelectedBattlerBroadAfflictions
C29CDB_TryRecoverSelectedBattlerHardState_L9CDB:
    rtl
C29CDC_ApplyTimedSubstateOrRefreshShieldCounter:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txy
    sta $0E
    clc
    adc.w #$0023
    tax
    sty $02
    lda $0000,X
    and.w #$00FF
    cmp $02
    bne C29D2B_TryRecoverSelectedBattlerHardState_L9D2B
    lda $0E
    clc
    adc.w #$0025
    tax
    sep #$20
    lda $0000,X
    inc A
    inc A
    inc A
    sta $0000,X
    rep #$20
    and.w #$00FF
    clc
    sbc.w #$0008
    bvc C29D1B_TryRecoverSelectedBattlerHardState_L9D1B
    bpl C29D24_TryRecoverSelectedBattlerHardState_L9D24
    bra C29D1D_TryRecoverSelectedBattlerHardState_L9D1D
C29D1B_TryRecoverSelectedBattlerHardState_L9D1B:
    bmi C29D24_TryRecoverSelectedBattlerHardState_L9D24
C29D1D_TryRecoverSelectedBattlerHardState_L9D1D:
    sep #$20
    lda.b #$08
    sta $0000,X
C29D24_TryRecoverSelectedBattlerHardState_L9D24:
    rep #$20
    lda.w #$0001
    bra C29D42_TryRecoverSelectedBattlerHardState_L9D42
C29D2B_TryRecoverSelectedBattlerHardState_L9D2B:
    tya
    sep #$20
    sta $0000,X
    rep #$20
    lda $0E
    tax
    sep #$20
    lda.b #$03
    sta $0025,X
    rep #$20
    lda.w #$0000
C29D42_TryRecoverSelectedBattlerHardState_L9D42:
    pld
    rts
C29D44_RunTimedSubstateFourAction:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldx.w #$0004
    lda $A972
    jsr.w C29CDC_ApplyTimedSubstateOrRefreshShieldCounter
    cmp.w #$0000
    beq C29D6A_TryRecoverSelectedBattlerHardState_L9D6A
    lda.w #$6FBD
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29D78_TryRecoverSelectedBattlerHardState_L9D78
C29D6A_TryRecoverSelectedBattlerHardState_L9D6A:
    lda.w #$6F9A
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29D78_TryRecoverSelectedBattlerHardState_L9D78:
    pld
    rtl
C29D7A_RunTimedSubstateFourWrapper:
    rep #$31
    jsl C29D44_RunTimedSubstateFourAction
    rtl
C29D81_RunTimedSubstateThreeAction:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldx.w #$0003
    lda $A972
    jsr.w C29CDC_ApplyTimedSubstateOrRefreshShieldCounter
    cmp.w #$0000
    beq C29DA7_TryRecoverSelectedBattlerHardState_L9DA7
    lda.w #$6FF4
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29DB5_TryRecoverSelectedBattlerHardState_L9DB5
C29DA7_TryRecoverSelectedBattlerHardState_L9DA7:
    lda.w #$6FD3
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29DB5_TryRecoverSelectedBattlerHardState_L9DB5:
    pld
    rtl
C29DB7_RunTimedSubstateThreeWrapper:
    rep #$31
    jsl C29D81_RunTimedSubstateThreeAction
    rtl
C29DBE_RunTimedSubstateTwoAction:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldx.w #$0002
    lda $A972
    jsr.w C29CDC_ApplyTimedSubstateOrRefreshShieldCounter
    cmp.w #$0000
    beq C29DE4_TryRecoverSelectedBattlerHardState_L9DE4
    lda.w #$7032
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29DF2_TryRecoverSelectedBattlerHardState_L9DF2
C29DE4_TryRecoverSelectedBattlerHardState_L9DE4:
    lda.w #$700C
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29DF2_TryRecoverSelectedBattlerHardState_L9DF2:
    pld
    rtl
C29DF4_RunTimedSubstateTwoWrapper:
    rep #$31
    jsl C29DBE_RunTimedSubstateTwoAction
    rtl
C29DFB_RunTimedSubstateOneAction:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldx.w #$0001
    lda $A972
    jsr.w C29CDC_ApplyTimedSubstateOrRefreshShieldCounter
    cmp.w #$0000
    beq C29E21_TryRecoverSelectedBattlerHardState_L9E21
    lda.w #$707A
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29E2F_TryRecoverSelectedBattlerHardState_L9E2F
C29E21_TryRecoverSelectedBattlerHardState_L9E21:
    lda.w #$7050
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29E2F_TryRecoverSelectedBattlerHardState_L9E2F:
    pld
    rtl
C29E31_RunTimedSubstateOneWrapper:
    rep #$31
    jsl C29DFB_RunTimedSubstateOneAction
    rtl
