; EarthBound C2 selected battler timed substate blocker.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:941D..C2:94CE CheckSelectedBattlerTimedSubstateBlocker
;
; Runtime contract:
; - Shared PSI/action pre-hit blocker used by the early PSI common helpers.
; - Marks `$AA94 = 1`, emits the action presentation command from active row
;   `+0x08`, then reads the active `D5:7B68` action descriptor type byte.
; - Only descriptor type `3` enters the selected-row timed-substate handling.
; - Selected-row `+0x23 == 1` emits `EF:70D2`, sets reflected-hit marker
;   `$AA96 = 1`, and swaps attacker/target text contexts through `C2:7E8A`.
; - Selected-row `+0x23 == 2` emits `EF:70FA`, decrements row `+0x25`, and
;   when it expires clears `+0x23` and emits `EF:7099`.

; ---------------------------------------------------------------------------
; External contracts used by this module

C27E8A_SwapReflectedHitBattleTextContexts = $7E8A
C1DC1C_DisplayBattleTextFromPointer       = $C1DC1C
C1DD7C_RunBattlePresentationCommand       = $C1DD7C

; ---------------------------------------------------------------------------
; C2:941D

PSI_SHIELD_NULLIFY:
C2941D_CheckSelectedBattlerTimedSubstateBlocker = PSI_SHIELD_NULLIFY
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda.w #$0001
    sta $AA94
    ldx $A970
    sep #$20
    lda $0008,X
    jsl C1DD7C_RunBattlePresentationCommand
    ldx $A970
    lda $0004,X
    sta $04
    asl A
    adc $04
    asl A
    asl A
    tax
    inx
    inx
    lda $D57B68,X
    and.w #$00FF
    ; Only action descriptor type 3 participates in this substate blocker.
    cmp.w #$0003
    beq C29458_CheckSelectedBattlerTimedSubstateBlocker_L9458
    lda.w #$0000
    bra C294CC_CheckSelectedBattlerTimedSubstateBlocker_L94CC
C29458_CheckSelectedBattlerTimedSubstateBlocker_L9458:
    ldx $A972
    lda $0023,X
    and.w #$00FF
    ; Timed substate 1 redirects/reflection-swaps the active text context.
    cmp.w #$0001
    beq C2946D_CheckSelectedBattlerTimedSubstateBlocker_L946D
    cmp.w #$0002
    beq C29486_CheckSelectedBattlerTimedSubstateBlocker_L9486
    bra C294C9_CheckSelectedBattlerTimedSubstateBlocker_L94C9
C2946D_CheckSelectedBattlerTimedSubstateBlocker_L946D:
    lda.w #$70D2
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    lda.w #$0001
    sta $AA96
    jsr SWAP_ATTACKER_WITH_TARGET
    bra C294C9_CheckSelectedBattlerTimedSubstateBlocker_L94C9
C29486_CheckSelectedBattlerTimedSubstateBlocker_L9486:
    lda.w #$70FA
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    ; Timed substate 2 consumes row `+0x25` before clearing `+0x23`.
    lda $A972
    clc
    adc.w #$0025
    tax
    sep #$20
    lda $0000,X
    dec A
    sta $0000,X
    rep #$20
    and.w #$00FF
    bne C294C4_CheckSelectedBattlerTimedSubstateBlocker_L94C4
    ldx $A972
    sep #$20
    stz $0023,X
    rep #$20
    lda.w #$7099
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C294C4_CheckSelectedBattlerTimedSubstateBlocker_L94C4:
    lda.w #$0001
    bra C294CC_CheckSelectedBattlerTimedSubstateBlocker_L94CC
C294C9_CheckSelectedBattlerTimedSubstateBlocker_L94C9:
    lda.w #$0000
C294CC_CheckSelectedBattlerTimedSubstateBlocker_L94CC:
    pld
    rts
