; EarthBound C2 try apply strange status to selected battler.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:98DE..C2:9917 TryApplyStrangeStatusToSelectedBattler

; ---------------------------------------------------------------------------
; External contracts used by this module

C2724A_ApplyBattlerAfflictionSubgroupValue = $724A
C1DC1C_DisplayBattleTextFromPointer        = $C1DC1C

; ---------------------------------------------------------------------------
; C2:98DE

C298DE_TryApplyStrangeStatusToSelectedBattler:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldy.w #$0001
    ldx.w #$0003
    lda $A972
    jsr C2724A_ApplyBattlerAfflictionSubgroupValue
    cmp.w #$0000
    beq C29907_TryApplyStrangeStatusToSelectedBattler_L9907
    lda.w #$6C3A
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    bra C29915_TryApplyStrangeStatusToSelectedBattler_L9915
C29907_TryApplyStrangeStatusToSelectedBattler_L9907:
    lda.w #$766E
    sta $0E
    lda.w #$00EF
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C29915_TryApplyStrangeStatusToSelectedBattler_L9915:
    pld
    rts
