; EarthBound C2 poison-only recovery action.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:A39D..C2:A3D1 TryRecoverSelectedBattlerPoisonOnly
;
; Runtime contract:
; - Narrow item-side recovery helper.
; - If active row `+0x1D == 5`, clears poison and emits `EF:6E97`.
; - Otherwise returns without visible text.

; ---------------------------------------------------------------------------
; External contracts used by this module

C1DC1C_DisplayBattleTextFromPointer = $C1DC1C

SelectedRowPrimaryAfflictionByte   = $001D
PrimaryAfflictionPoisonValue       = $0005
ClearedAfflictionValue             = $00
EFMSG_PoisonRemoved                = $6E97
EF_BattleTextScriptBank            = $00EF

; ---------------------------------------------------------------------------
; C2:A39D

HEAL_POISON:
C2A39D_TryRecoverSelectedBattlerPoisonOnly = HEAL_POISON
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda $A972
    clc
    adc.w #SelectedRowPrimaryAfflictionByte
    tax
    lda $0000,X
    and.w #$00FF
    ; Main affliction byte value 5 = poison in this recovery family.
    cmp.w #PrimaryAfflictionPoisonValue
    bne C2A3CF_TryRecoverSelectedBattlerPoisonOnly_LA3CF
    sep #$20
    lda.b #ClearedAfflictionValue
    sta $0000,X
    rep #$20
    lda.w #EFMSG_PoisonRemoved
    sta $0E
    lda.w #EF_BattleTextScriptBank
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
C2A3CF_TryRecoverSelectedBattlerPoisonOnly_LA3CF:
    pld
    rtl
