; EarthBound C2 battle guts increase consequence.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:B43F..C2:B4A6 ApplyBattleGutsIncreaseConsequence

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C2:B43F

C2B43F_ApplyBattleGutsIncreaseConsequence:
    lda $A972
    clc
    adc.w #$002C
    pha
    ldy $16
    sty $02
    tax
    lda $0000,X
    clc
    adc $02
    plx
    sta $0000,X
    ldx $1C
    txa
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$9A26
    pha
    ldy $16
    sep #$10
    sty $00
    rep #$10
    tax
    sep #$20
    lda $0000,X
    clc
    adc $00
    plx
    sta $0000,X
    ldx $1C
    rep #$20
    txa
    jsl $C21BA4
    rep #$20
    lda.w #$F7D2
    sta $0E
    lda.w #$00C8
    sta $10
    ldy $16
    tya
    sta $06
    stz $08
    lda $06
    sta $12
    lda $08
    sta $14
    jsl $C1DC66
    jmp $B5E3
