; EarthBound C2 inactive candidate live-slot transient field clearer.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:BC5C..C2:BCB9 ClearInactiveCandidateLiveSlotTransientFields

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C2:BC5C

C2BC5C_ClearInactiveCandidateLiveSlotTransientFields:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$0000
    sta $0E
    bra C2BCB2_ClearInactiveCandidateLiveSlotTransientFields_LBCB2
C2BC6B_ClearInactiveCandidateLiveSlotTransientFields_LBC6B:
    ldy.w #$004E
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    lda $9FB8,X
    and.w #$00FF
    beq C2BCAB_ClearInactiveCandidateLiveSlotTransientFields_LBCAB
    lda $9FBA,X
    and.w #$00FF
    bne C2BCAB_ClearInactiveCandidateLiveSlotTransientFields_LBCAB
    lda $9FBB,X
    and.w #$00FF
    bne C2BCAB_ClearInactiveCandidateLiveSlotTransientFields_LBCAB
    lda $9FBC,X
    and.w #$00FF
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99CE
    tax
    sep #$20
    stz $0014,X
    stz $0012,X
    stz $0011,X
    stz $0010,X
C2BCAB_ClearInactiveCandidateLiveSlotTransientFields_LBCAB:
    rep #$20
    lda $0E
    inc A
    sta $0E
C2BCB2_ClearInactiveCandidateLiveSlotTransientFields_LBCB2:
    cmp.w #$0006
    bcc C2BC6B_ClearInactiveCandidateLiveSlotTransientFields_LBC6B
    pld
    rtl
