; EarthBound C2 Run final-prayer finale opening sequence.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:C6F0..C2:C8C8 BTLACT_GIYGAS_PRAYER_9
;
; Runtime contract:
; - Final Prayer action row 299 / phase 9 finale opening sequence.
; - Interleaves four late narrative text blocks through `C2:C41F` with four
;   doubled prayer damage calls through `C2:C3E2` (`0x0C80`, `0x1900`,
;   `0x3200`, `0x6400`).
; - Then drives the Sound Stone/noise sequence, layer distortion swaps, final
;   overlay wait, and handoff into the terminal battle visual state.

; ---------------------------------------------------------------------------
; External contracts used by this module

C0ABC6_ClearPresentationQueues = $C0ABC6
C1DC1C_DisplayBattleTextFromPointer = $C1DC1C
C4FBBD_PlaySoundStoneMelody    = $C4FBBD

C8_BattleTextScriptBank        = $00C8
C8MSG_PokeyRunAway             = $FF31
C9_BattleTextScriptBank        = $00C9
C9MSG_FinalPrayerBackToPc9     = $F70C
C9MSG_FinalPrayerFinale1       = $F7BB
C9MSG_FinalPrayerFinale2       = $F804
C9MSG_FinalPrayerFinale3       = $F84D

; ---------------------------------------------------------------------------
; C2:C6F0

C2C6F0_RunFinalPrayerFinaleOpeningSequence = BTLACT_GIYGAS_PRAYER_9
    rep #$31
    phd
    tdc
    adc.w #$FFE6
    tcd
    jsl $C20F9A
    lda.w #C9MSG_FinalPrayerBackToPc9
    sta $0E
    lda.w #C9_BattleTextScriptBank
    sta $10
    lda.w #$004A
    jsr $C41F
    lda.w #$0C80
    ; Finale damage tier: 3200.
    jsr $C3E2
    lda.w #C9MSG_FinalPrayerFinale1
    sta $0E
    lda.w #C9_BattleTextScriptBank
    sta $10
    lda.w #$004A
    jsr $C41F
    lda.w #$1900
    ; Finale damage tier: 6400.
    jsr $C3E2
    lda.w #C9MSG_FinalPrayerFinale2
    sta $0E
    lda.w #C9_BattleTextScriptBank
    sta $10
    lda.w #$004A
    jsr $C41F
    lda.w #$3200
    ; Finale damage tier: 12800.
    jsr $C3E2
    lda.w #C9MSG_FinalPrayerFinale3
    sta $0E
    lda.w #C9_BattleTextScriptBank
    sta $10
    lda.w #$004A
    jsr $C41F
    lda.w #$6400
    ; Finale damage tier: 25600.
    jsr $C3E2
    jsl $C1DD59
    stz $9643
    jsl $C1DD41
    lda.w #$0001
    sta $9643
    jsl $C12DD5
    lda.w #$FFFF
    sta $A97A
    lda.w #$00BE
    jsl C4FBBD_PlaySoundStoneMelody
    ldy.w #$0000
    sty $18
C2C77B_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC77B:
    ; Iterate the C4 finale sound/delay table until a zero delay terminator.
    lda.w #$A35D
    sta $06
    lda.w #$00C4
    sta $08
    ldy $18
    tya
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    tax
    iny
    sty $18
    txa
    jsl $C0ABE0
    ldy $18
    tya
    clc
    adc $06
    sta $06
    lda [$06]
    and.w #$00FF
    tax
    beq C2C7BC_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC7BC
    iny
    sty $18
    txa
    jsr $69BE
    bra C2C77B_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC77B
C2C7BC_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC7BC:
    lda.w #$004B
    jsl C4FBBD_PlaySoundStoneMelody
    stz $A97A
    lda.w #$01E0
    jsr $69BE
    ldx.w #$A276
    stx $16
    sep #$20
    lda.b #$01
    sta $0000,X
    jsl $C2F8F9
    lda.w #C8MSG_PokeyRunAway
    sta $0E
    lda.w #C8_BattleTextScriptBank
    sta $10
    jsl C1DC1C_DisplayBattleTextFromPointer
    sep #$20
    lda.b #$00
    ldx $16
    sta $0000,X
    jsl $C2F8F9
    lda.w #$003C
    jsr $69BE
    ldy.w #$0002
    sty $14
    tya
    sta $04
    lda.w #$002D
    sta $02
    lda.w #$003C
    sta $AD8C
    ldx.w #$0000
    stx $12
    bra C2C872_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC872
C2C817_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC817:
    lda.w #$0000
    sta $18
    bra C2C842_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC842
C2C81E_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC81E:
    jsl $C12DD5
    lda $04
    beq C2C83D_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC83D
    lda $02
    dec A
    sta $02
    bne C2C83D_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC83D
    lda $04
    dec A
    sta $04
    lda.w #$002D
    sta $02
    lda.w #$003C
    sta $AD8C
C2C83D_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC83D:
    lda $18
    inc A
    sta $18
C2C842_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC842:
    ldx $12
    txa
    asl A
    tax
    lda $18
    cmp $C4A331,X
    bcc C2C81E_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC81E
    ; Periodically swap layer-1 battle-bg distortion endpoints during finale.
    jsl $C2DAE3
    ldy $14
    tya
    jsl $C0AC3A
    ldy $14
    cpy.w #$0002
    bne C2C868_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC868
    ldy.w #$0001
    sty $14
    bra C2C86D_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC86D
C2C868_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC868:
    ldy.w #$0002
    sty $14
C2C86D_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC86D:
    ldx $12
    inx
    stx $12
C2C872_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC872:
    txa
    asl A
    tax
    lda $C4A331,X
    bne C2C817_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC817
    lda.w #$00B6
    jsl C4FBBD_PlaySoundStoneMelody
    lda.w #$0258
    jsr $69BE
    lda.w #$003F
    jsl $C0ABE0
    jsl C0ABC6_ClearPresentationQueues
    ldy.w #$0005
    ldx.w #$0000
    tya
    ; Start the final overlay and spin until the busy predicate clears.
    jsl $C2E8C4
    bra C2C8A4_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC8A4
C2C8A0_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC8A0:
    jsl $C12DD5
C2C8A4_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC8A4:
    jsl $C2E9C8
    cmp.w #$0000
    bne C2C8A0_C2C6F0_RunFinalPrayerFinaleOpeningSequence_LC8A0
    jsl C0ABC6_ClearPresentationQueues
    ldx.w #$0000
    lda.w #$01E3
    jsr $C21F
    lda.w #$01E0
    jsr $69BE
    lda.w #$0003
    sta $AA0E
    pld
    rtl
