; EarthBound C2 Load final-prayer finale tilemap state.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:C8C8..C2:C92D C2C8C8_LoadFinalPrayerFinaleTilemapState

; ---------------------------------------------------------------------------
; External contracts used by this module

C08616_QueueVramTransfer_FromDpSource        = $C08616
C08D79_UpdateBgModeRegisterFromQueue         = $C08D79
C08D92_UpdateObjSizeAndBaseRegister          = $C08D92
C08D9E_UpdateBg1ScreenBaseRegistersFromQueue = $C08D9E
C08E1C_UpdateBg2ScreenBaseRegistersFromQueue = $C08E1C

; ---------------------------------------------------------------------------
; C2:C8C8

C2C8C8_LoadFinalPrayerFinaleTilemapState:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda.w #$0009
    jsl C08D79_UpdateBgModeRegisterFromQueue
    ldy.w #$0000
    ldx.w #$5800
    tya
    jsl C08D9E_UpdateBg1ScreenBaseRegistersFromQueue
    ldy.w #$1000
    ldx.w #$5C00
    lda.w #$0000
    jsl $C08DDE
    ldy.w #$6000
    ldx.w #$7C00
    lda.w #$0000
    jsl C08E1C_UpdateBg2ScreenBaseRegistersFromQueue
    lda.w #$0061
    jsl C08D92_UpdateObjSizeAndBaseRegister
    lda.w #$8000
    sta $06
    lda.w #$007F
    sta $08
    sep #$20
    lda.b #$00
    sta [$06]
    rep #$20
    lda $06
    sta $0E
    lda $08
    sta $10
    ldy.w #$7C00
    ldx.w #$0800
    sep #$20
    lda.b #$03
    jsl C08616_QueueVramTransfer_FromDpSource
    pld
    rtl
