; EarthBound C2 battle swirl overlay and mode polling helpers.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:E8C4..C2:E9ED StartBattleSwirlOverlayAndRecordMode

; ---------------------------------------------------------------------------
; External contracts used by this module

C4FBBD_PlaySoundStoneMelody = $C4FBBD

; ---------------------------------------------------------------------------
; C2:E8C4

C2E8C4_StartBattleSwirlOverlayAndRecordMode:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF2
    tcd
    pla
    sty $02
    tay
    jsl $C4A67E
    lda $02
    sep #$20
    sta $AECA
    rep #$20
    pld
    rtl
    rep #$31
    phd
    tdc
    adc.w #$FFE8
    tcd
    lda.w #$0001
    sta $16
    lda.w #$0004
    sta $14
    sta $04
    ldy.w #$0000
    sty $12
    lda $4DBC
    beq C2E90A_StartBattleSwirlOverlayAndRecordMode_LE90A
    cmp.w #$0001
    beq C2E918_StartBattleSwirlOverlayAndRecordMode_LE918
    cmp.w #$0002
    beq C2E935_StartBattleSwirlOverlayAndRecordMode_LE935
    bra C2E94B_StartBattleSwirlOverlayAndRecordMode_LE94B
C2E90A_StartBattleSwirlOverlayAndRecordMode_LE90A:
    ldx.w #$00B0
    stx $10
    lda.w #$000E
    sta $02
    sta $0E
    bra C2E94B_StartBattleSwirlOverlayAndRecordMode_LE94B
C2E918_StartBattleSwirlOverlayAndRecordMode_LE918:
    ldx.w #$00B0
    stx $10
    lda.w #$001C
    sta $14
    lda.w #$0005
    sta $04
    ldy.w #$000C
    sty $12
    lda.w #$0006
    sta $02
    sta $0E
    bra C2E94B_StartBattleSwirlOverlayAndRecordMode_LE94B
C2E935_StartBattleSwirlOverlayAndRecordMode_LE935:
    ldx.w #$0009
    stx $10
    stz $14
    lda.w #$001F
    sta $04
    tay
    sty $12
    lda.w #$0006
    sta $02
    sta $0E
C2E94B_StartBattleSwirlOverlayAndRecordMode_LE94B:
    lda $4A8C
    cmp.w #$01C0
    bcc C2E964_StartBattleSwirlOverlayAndRecordMode_LE964
    lda.w #$0003
    sta $16
    lda.w #$000E
    sta $02
    sta $0E
    ldx.w #$0008
    stx $10
C2E964_StartBattleSwirlOverlayAndRecordMode_LE964:
    ldx $10
    txa
    jsl C4FBBD_PlaySoundStoneMelody
    jsl $C04F47
    lda $0E
    sta $02
    and.w #$0004
    beq C2E99F_StartBattleSwirlOverlayAndRecordMode_LE99F
    ldy $12
    ldx $04
    lda $14
    jsl $C0B01A
    lda $02
    and.w #$0008
    beq C2E995_StartBattleSwirlOverlayAndRecordMode_LE995
    ldx.w #$00FF
    lda.w #$0010
    jsl $C0B039
    bra C2E99F_StartBattleSwirlOverlayAndRecordMode_LE99F
C2E995_StartBattleSwirlOverlayAndRecordMode_LE995:
    ldx.w #$00BF
    lda.w #$0010
    jsl $C0B039
C2E99F_StartBattleSwirlOverlayAndRecordMode_LE99F:
    ldy.w #$001E
    ldx $02
    lda $16
    jsl C2E8C4_StartBattleSwirlOverlayAndRecordMode
    lda $02
    and.w #$0004
    beq C2E9BA_StartBattleSwirlOverlayAndRecordMode_LE9BA
    sep #$20
    lda.b #$20
    sta $AEC8
    bra C2E9C1_StartBattleSwirlOverlayAndRecordMode_LE9C1
C2E9BA_StartBattleSwirlOverlayAndRecordMode_LE9BA:
    sep #$20
    lda.b #$0F
    sta $AEC8
C2E9C1_StartBattleSwirlOverlayAndRecordMode_LE9C1:
    stz $AECB
    rep #$20
    pld
    rtl
    rep #$31
    lda $AEC2
    and.w #$00FF
    beq C2E9E9_StartBattleSwirlOverlayAndRecordMode_LE9E9
    lda $AECA
    and.w #$00FF
    clc
    sbc.w #$0004
    bvc C2E9E2_StartBattleSwirlOverlayAndRecordMode_LE9E2
    bpl C2E9E9_StartBattleSwirlOverlayAndRecordMode_LE9E9
    bra C2E9E4_StartBattleSwirlOverlayAndRecordMode_LE9E4
C2E9E2_StartBattleSwirlOverlayAndRecordMode_LE9E2:
    bmi C2E9E9_StartBattleSwirlOverlayAndRecordMode_LE9E9
C2E9E4_StartBattleSwirlOverlayAndRecordMode_LE9E4:
    lda.w #$0001
    bra C2E9EC_StartBattleSwirlOverlayAndRecordMode_LE9EC
C2E9E9_StartBattleSwirlOverlayAndRecordMode_LE9E9:
    lda.w #$0000
C2E9EC_StartBattleSwirlOverlayAndRecordMode_LE9EC:
    rtl
