; EarthBound C2 Enemy sprite color wave comparison helper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C2:FB35..C2:FCA6 C2FB35_EnemySpriteColorWaveComparisonHelper

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C2:FB35

C2FB35_EnemySpriteColorWaveComparisonHelper:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE4
    tcd
    pla
    sty $1A
    stx $04
    stx $18
    sta $16
    ldx $2A
    stx $14
    lsr A
    lsr A
    lsr A
    lsr A
    asl A
    tax
    lda $B37C
    sta $AEF4,X
    lda $16
    asl A
    tax
    lda $0380,X
    sta $12
    and.w #$001F
    sta $02
    lda $12
    lsr A
    lsr A
    lsr A
    lsr A
    lsr A
    and.w #$001F
    tax
    stx $10
    sep #$20
    lda.b #$0A
    sep #$10
    tay
    rep #$20
    lda $12
    jsl $C09251
    and.w #$001F
    sta $0E
    lda $04
    cmp $02
    bcc C2FBB0_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBB0
    beq C2FBB0_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBB0
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    sta $12
    lda $18
    sta $04
    sec
    sbc $02
    rep #$10
    ldy.w #$B1FC
    sta ($12),Y
    lda.w #$0001
    ldy.w #$AEFC
    sta ($12),Y
    bra C2FBE8_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBE8
C2FBB0_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBB0:
    lda $04
    cmp $02
    bne C2FBC6_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBC6
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    rep #$10
    tax
    stz $AEFC,X
    bra C2FBE8_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBE8
C2FBC6_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBC6:
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    sta $12
    lda $18
    sta $04
    lda $02
    sec
    sbc $04
    rep #$10
    ldy.w #$B1FC
    sta ($12),Y
    lda.w #$FFFF
    ldy.w #$AEFC
    sta ($12),Y
C2FBE8_C2FB35_EnemySpriteColorWaveComparisonHelper_LFBE8:
    ldx $10
    stx $02
    ldy $1A
    tya
    cmp $02
    bcc C2FC14_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC14
    beq C2FC14_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC14
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    sta $02
    stx $04
    tya
    sec
    sbc $04
    ldx $02
    sta $B1FE,X
    lda.w #$0020
    ldx $02
    sta $AEFE,X
    bra C2FC46_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC46
C2FC14_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC14:
    stx $02
    tya
    cmp $02
    bne C2FC29_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC29
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    tax
    stz $AEFE,X
    bra C2FC46_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC46
C2FC29_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC29:
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    sta $02
    sty $04
    txa
    sec
    sbc $04
    ldx $02
    sta $B1FE,X
    lda.w #$FFE0
    ldx $02
    sta $AEFE,X
C2FC46_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC46:
    lda $14
    cmp $0E
    bcc C2FC67_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC67
    beq C2FC67_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC67
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    tax
    lda $14
    sec
    sbc $0E
    sta $B200,X
    lda.w #$0400
    sta $AF00,X
    bra C2FC92_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC92
C2FC67_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC67:
    lda $14
    cmp $0E
    bne C2FC7B_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC7B
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    tax
    stz $AF00,X
    bra C2FC92_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC92
C2FC7B_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC7B:
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    tax
    lda $0E
    sec
    sbc $14
    sta $B200,X
    lda.w #$FC00
    sta $AF00,X
C2FC92_C2FB35_EnemySpriteColorWaveComparisonHelper_LFC92:
    lda $16
    sta $04
    asl A
    adc $04
    asl A
    tax
    stz $B080,X
    stz $B07E,X
    stz $B07C,X
    pld
    rtl
