; EarthBound C0 Rewrite Visual Memory Reservations4 A00.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:1C11..C0:1C52 Rewrite_VisualMemoryReservations4A00

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:1C11

C01C11_Rewrite_VisualMemoryReservations4A00:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txy
    sta $0E
    ldx.w #$0000
    bra C01C49_Rewrite_VisualMemoryReservations4A00_L1C49
C01C23_Rewrite_VisualMemoryReservations4A00_L1C23:
    rep #$20
    lda $0E
    rep #$20
    and.w #$00FF
    ora.w #$0080
    sta $02
    lda $4A00,X
    and.w #$00FF
    cmp $02
    beq C01C42_Rewrite_VisualMemoryReservations4A00_L1C42
    lda $0E
    cmp.w #$8000
    bne C01C48_Rewrite_VisualMemoryReservations4A00_L1C48
C01C42_Rewrite_VisualMemoryReservations4A00_L1C42:
    tya
    sep #$20
    sta $4A00,X
C01C48_Rewrite_VisualMemoryReservations4A00_L1C48:
    inx
C01C49_Rewrite_VisualMemoryReservations4A00_L1C49:
    cpx.w #$0058
    bcc C01C23_Rewrite_VisualMemoryReservations4A00_L1C23
    rep #$20
    pld
    rtl
