; EarthBound C0 Build Entity Visual Records467 E.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:1D38..C0:1DED Build_EntityVisualRecords467E

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:1D38

C01D38_Build_EntityVisualRecords467E:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE6
    tcd
    pla
    sty $18
    stx $04
    tax
    lda $28
    sta $06
    lda $2A
    sta $08
    lda [$06]
    and.w #$00FF
    sta $02
    sta $16
    inc $06
    inc $06
    ldy.w #$0000
    sty $14
    jmp.w C01DE1_Build_EntityVisualRecords467E_L1DE1
C01D64_Build_EntityVisualRecords467E_L1D64:
    lda.w #$0000
    sta $12
    bra C01DD4_Build_EntityVisualRecords467E_L1DD4
C01D6B_Build_EntityVisualRecords467E_L1D6B:
    sep #$20
    lda [$06]
    sta $467E,X
    inx
    stx $10
    rep #$20
    lda $12
    sta $02
    lda $04
    clc
    adc $02
    asl A
    tax
    lda $C4303C,X
    sta $0E
    sep #$20
    ldx $10
    sta $467E,X
    inx
    rep #$20
    lda $0E
    xba
    and.w #$00FF
    sep #$20
    sta $00
    rep #$20
    lda $18
    sep #$20
    sta $01
    ldy.w #$0002
    lda [$06],Y
    and.b #$FE
    ora $01
    ora $00
    sta $467E,X
    inx
    ldy.w #$0003
    lda [$06],Y
    sta $467E,X
    inx
    ldy.w #$0004
    lda [$06],Y
    sta $467E,X
    inx
    rep #$20
    lda.w #$0005
    clc
    adc $06
    sta $06
    lda $12
    inc A
    sta $12
C01DD4_Build_EntityVisualRecords467E_L1DD4:
    ldy $16
    sty $02
    cmp $02
    bcc C01D6B_Build_EntityVisualRecords467E_L1D6B
    ldy $14
    iny
    sty $14
C01DE1_Build_EntityVisualRecords467E_L1DE1:
    cpy.w #$0002
    bcs C01DEB_Build_EntityVisualRecords467E_L1DEB
    beq C01DEB_Build_EntityVisualRecords467E_L1DEB
    jmp.w C01D64_Build_EntityVisualRecords467E_L1D64
C01DEB_Build_EntityVisualRecords467E_L1DEB:
    pld
    rts
