; EarthBound C0 Measure Previous Registry Order Delta.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:3E9D..C0:3EC3 Measure_PreviousRegistryOrderDelta

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:3E9D

C03E9D_Measure_PreviousRegistryOrderDelta:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    jsr $3E5A
    sta $0E
    ldx $4DC6
    lda $003D,X
    sta $02
    lda $0E
    cmp $02
    bcs C03EBE_Measure_PreviousRegistryOrderDelta_L3EBE
    clc
    adc.w #$0100
C03EBE_Measure_PreviousRegistryOrderDelta_L3EBE:
    sec
    sbc $02
    pld
    rtl
