; EarthBound C0 Sum Active Party Levels.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:546B..C0:54C9 Sum_ActivePartyLevels

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C0:546B

C0546B_Sum_ActivePartyLevels:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    ldy.w #$0000
    sty $10
    tya
    sta $0E
    bra C054B8_Sum_ActivePartyLevels_L54B8
C0547D_Sum_ActivePartyLevels_L547D:
    clc
    adc.w #$97F5
    tax
    lda $0096,X
    and.w #$00FF
    clc
    sbc.w #$0004
    bvs C05492_Sum_ActivePartyLevels_L5492
    bpl C054B3_Sum_ActivePartyLevels_L54B3
    bra C05494_Sum_ActivePartyLevels_L5494
C05492_Sum_ActivePartyLevels_L5492:
    bmi C054B3_Sum_ActivePartyLevels_L54B3
C05494_Sum_ActivePartyLevels_L5494:
    lda $009C,X
    and.w #$00FF
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    lda $99D3,X
    and.w #$00FF
    sta $02
    ldy $10
    tya
    clc
    adc $02
    tay
    sty $10
C054B3_Sum_ActivePartyLevels_L54B3:
    lda $0E
    inc A
    sta $0E
C054B8_Sum_ActivePartyLevels_L54B8:
    lda $98A3
    and.w #$00FF
    sta $02
    lda $0E
    cmp $02
    bne C0547D_Sum_ActivePartyLevels_L547D
    tya
    pld
    rtl
