; EarthBound C0 Probe Type6 Door Candidate.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:65C2..C0:69F7 Probe_Type6DoorCandidate

; ---------------------------------------------------------------------------
; External contracts used by this module

C0856B_WaitFramesOrTransitionDelay            = $C0856B
C08726_BlankWaitAndDisableHdma                = $C08726
C08756_WaitOneFrameAndPollInput               = $C08756
C0886C_SetDisplayTransitionState              = $C0886C
C088B1_ResetRendererFrameState                = $C088B1
C08B26_FlushQueuedSpriteOrTileWork            = $C08B26
C08EFC_CommitTileBufferToStaging              = $C08EFC
C0915B_DivideUnsignedWordByY                  = $C0915B
C0943C_SaveCurrentCoordinateState             = $C0943C
C09451_RestoreSavedCoordinateState            = $C09451
C09466_RefreshActiveEntitySpriteState         = $C09466
C0AC0C_QueuePresentationSfxOrCounter          = $C0AC0C
C21628_CheckEventFlag                         = $C21628
C2EAAA_FinishBattleSwirlOverlay               = $C2EAAA
C426ED_ApplyPaletteComponentInterpolationStep = $C426ED
C4954C_SeedPaletteFadeWorkBuffer              = $C4954C
C496E7_StartPaletteFadeFromWorkBuffer         = $C496E7
C49740_FinishPaletteFadeWorkBuffer            = $C49740
C4A7B0_StepBattleOverlayScriptState           = $C4A7B0
C4FBBD_PlaySoundStoneMelody                   = $C4FBBD

; ---------------------------------------------------------------------------
; C0:65C2

C065C2_Probe_Type6DoorCandidate:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sta $10
    asl A
    tax
    lda $9877
    lsr A
    lsr A
    lsr A
    clc
    adc $C3E230,X
    tay
    sty $0E
    lda $987B
    lsr A
    lsr A
    lsr A
    clc
    adc $C3E240,X
    sta $02
    lda $10
    cmp.w #$0006
    bne C065F5_Probe_Type6DoorCandidate_L65F5
    dey
    sty $0E
C065F5_Probe_Type6DoorCandidate_L65F5:
    ldx $02
    tya
    jsl $C07477
    rep #$20
    and.w #$00FF
    tax
    cpx.w #$00FF
    bne C06617_Probe_Type6DoorCandidate_L6617
    ldx $02
    ldy $0E
    tya
    inc A
    jsl $C07477
    rep #$20
    and.w #$00FF
    tax
C06617_Probe_Type6DoorCandidate_L6617:
    cpx.w #$00FF
    beq C06660_Probe_Type6DoorCandidate_L6660
    cpx.w #$0006
    bne C06660_Probe_Type6DoorCandidate_L6660
    lda.w #$0000
    sta $06
    lda.w #$00CF
    sta $08
    lda $5DBC
    and.w #$7FFF
    clc
    adc $06
    sta $06
    lda $5DBE
    sta $5DDC
    lda $06
    sta $0A
    lda $08
    sta $0C
    ldy.w #$0002
    lda [$0A],Y
    tay
    lda [$0A]
    sta $06
    sty $08
    lda $06
    sta $5DDE
    lda $08
    sta $5DE0
    lda.w #$FFFE
    sta $5D62
C06660_Probe_Type6DoorCandidate_L6660:
    pld
    rtl
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFDF
    tcd
    pla
    txy
    sty $1F
    sta $1D
    lda.w #$1400
    sta $06
    lda.w #$00D0
    sta $08
    lda $1D
    sta $04
    asl A
    adc $04
    asl A
    asl A
    clc
    adc $06
    sta $06
    sta $19
    lda $08
    sta $1B
    lda $06
    sta $0A
    lda $08
    sta $0C
    lda [$0A]
    and.w #$00FF
    sta $02
    cmp.w #$00FF
    bne C066A8_Probe_Type6DoorCandidate_L66A8
    lda.w #$0384
    sta $02
C066A8_Probe_Type6DoorCandidate_L66A8:
    sep #$20
    ldy.w #$0004
    lda [$06],Y
    rep #$20
    and.w #$00FF
    asl A
    asl A
    tax
    ldy.w #$0005
    lda [$06],Y
    jsl $C42631
    ldy $1F
    cpy.w #$0001
    beq C066CA_Probe_Type6DoorCandidate_L66CA
    jmp.w C067D2_Probe_Type6DoorCandidate_L67D2
C066CA_Probe_Type6DoorCandidate_L66CA:
    jsl C0943C_SaveCurrentCoordinateState
    lda.w #$0002
    jsl $C0DD2C
    sep #$20
    ldy.w #$0001
    lda [$06],Y
    sta $18
    rep #$20
    and.w #$00FF
    beq C066FD_Probe_Type6DoorCandidate_L66FD
    sep #$20
    ldy.w #$0002
    lda [$06],Y
    rep #$20
    and.w #$00FF
    tax
    inx
    inx
    lda $18
    and.w #$00FF
    jsl $C4A67E
C066FD_Probe_Type6DoorCandidate_L66FD:
    lda.w #$0200
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $12
    lda $08
    sta $14
    lda.w #$007E
    sta $14
    lda $12
    sta $06
    lda $14
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda $19
    sta $06
    lda $1B
    sta $08
    sep #$20
    ldy.w #$0003
    lda [$06],Y
    rep #$20
    and.w #$00FF
    jsl C4954C_SeedPaletteFadeWorkBuffer
    ldx.w #$FFFF
    lda $02
    jsl C496E7_StartPaletteFadeFromWorkBuffer
    lda.w #$0000
    sta $16
    bra C06782_Probe_Type6DoorCandidate_L6782
C06751_Probe_Type6DoorCandidate_L6751:
    lda $0030
    and.w #$00FF
    beq C0675D_Probe_Type6DoorCandidate_L675D
    jsl C08756_WaitOneFrameAndPollInput
C0675D_Probe_Type6DoorCandidate_L675D:
    jsl C426ED_ApplyPaletteComponentInterpolationStep
    jsl C088B1_ResetRendererFrameState
    jsl $C4268A
    jsl $C426C7
    jsl C09466_RefreshActiveEntitySpriteState
    jsl C08B26_FlushQueuedSpriteOrTileWork
    jsl C4A7B0_StepBattleOverlayScriptState
    jsl C08756_WaitOneFrameAndPollInput
    lda $16
    inc A
    sta $16
C06782_Probe_Type6DoorCandidate_L6782:
    cmp $02
    bcc C06751_Probe_Type6DoorCandidate_L6751
    sep #$20
    ldy.w #$0003
    lda [$06],Y
    rep #$20
    and.w #$00FF
    sta $02
    lda.w #$0032
    clc
    sbc $02
    bvc C067A0_Probe_Type6DoorCandidate_L67A0
    bpl C067A8_Probe_Type6DoorCandidate_L67A8
    bra C067A2_Probe_Type6DoorCandidate_L67A2
C067A0_Probe_Type6DoorCandidate_L67A0:
    bmi C067A8_Probe_Type6DoorCandidate_L67A8
C067A2_Probe_Type6DoorCandidate_L67A2:
    jsl C08726_BlankWaitAndDisableHdma
    bra C067CB_Probe_Type6DoorCandidate_L67CB
C067A8_Probe_Type6DoorCandidate_L67A8:
    sep #$20
    lda.b #$FF
    sta $0E
    ldx.w #$0200
    rep #$20
    lda.w #$0200
    jsl C08EFC_CommitTileBufferToStaging
    lda.w #$0018
    jsl C0856B_WaitFramesOrTransitionDelay
    jsl C08756_WaitOneFrameAndPollInput
    lda.w #$0001
    sta $4676
C067CB_Probe_Type6DoorCandidate_L67CB:
    jsl C09451_RestoreSavedCoordinateState
    jmp.w C06897_Probe_Type6DoorCandidate_L6897
C067D2_Probe_Type6DoorCandidate_L67D2:
    ldx.w #$0000
    sep #$20
    ldy.w #$0003
    lda [$06],Y
    rep #$20
    and.w #$00FF
    sta $02
    lda.w #$0032
    clc
    sbc $02
    bvc C067EF_Probe_Type6DoorCandidate_L67EF
    bpl C067F4_Probe_Type6DoorCandidate_L67F4
    bra C067F1_Probe_Type6DoorCandidate_L67F1
C067EF_Probe_Type6DoorCandidate_L67EF:
    bmi C067F4_Probe_Type6DoorCandidate_L67F4
C067F1_Probe_Type6DoorCandidate_L67F1:
    ldx.w #$0001
C067F4_Probe_Type6DoorCandidate_L67F4:
    txy
    sty $1D
    beq C06803_Probe_Type6DoorCandidate_L6803
    ldx.w #$0001
    txa
    jsl C0886C_SetDisplayTransitionState
    bra C06816_Probe_Type6DoorCandidate_L6816
C06803_Probe_Type6DoorCandidate_L6803:
    ldx.w #$FFFF
    sep #$20
    ldy.w #$0008
    lda [$06],Y
    rep #$20
    and.w #$00FF
    jsl C496E7_StartPaletteFadeFromWorkBuffer
C06816_Probe_Type6DoorCandidate_L6816:
    sep #$20
    ldy.w #$0009
    lda [$06],Y
    sta $18
    rep #$20
    and.w #$00FF
    beq C0683C_Probe_Type6DoorCandidate_L683C
    sep #$20
    ldy.w #$000A
    lda [$06],Y
    rep #$20
    and.w #$00FF
    tax
    lda $18
    and.w #$00FF
    jsl $C4A67E
C0683C_Probe_Type6DoorCandidate_L683C:
    lda.w #$0000
    sta $16
    bra C0687B_Probe_Type6DoorCandidate_L687B
C06843_Probe_Type6DoorCandidate_L6843:
    ldy $1D
    bne C06857_Probe_Type6DoorCandidate_L6857
    lda $0030
    and.w #$00FF
    beq C06853_Probe_Type6DoorCandidate_L6853
    jsl C08756_WaitOneFrameAndPollInput
C06853_Probe_Type6DoorCandidate_L6853:
    jsl C426ED_ApplyPaletteComponentInterpolationStep
C06857_Probe_Type6DoorCandidate_L6857:
    jsl C088B1_ResetRendererFrameState
    jsl C09466_RefreshActiveEntitySpriteState
    jsl C4A7B0_StepBattleOverlayScriptState
    jsl C08B26_FlushQueuedSpriteOrTileWork
    jsl C08756_WaitOneFrameAndPollInput
    lda $16
    cmp.w #$0001
    bne C06876_Probe_Type6DoorCandidate_L6876
    jsl C0943C_SaveCurrentCoordinateState
C06876_Probe_Type6DoorCandidate_L6876:
    lda $16
    inc A
    sta $16
C0687B_Probe_Type6DoorCandidate_L687B:
    sep #$20
    ldy.w #$0008
    lda [$06],Y
    rep #$20
    and.w #$00FF
    sta $02
    lda $16
    cmp $02
    bcc C06843_Probe_Type6DoorCandidate_L6843
    ldy $1D
    bne C06897_Probe_Type6DoorCandidate_L6897
    jsl C49740_FinishPaletteFadeWorkBuffer
C06897_Probe_Type6DoorCandidate_L6897:
    lda $A97A
    cmp.w #$0004
    bcs C068A3_Probe_Type6DoorCandidate_L68A3
    jsl C2EAAA_FinishBattleSwirlOverlay
C068A3_Probe_Type6DoorCandidate_L68A3:
    jsl C09451_RestoreSavedCoordinateState
    stz $5DAA
    stz $5DA8
    pld
    rtl
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sta $0E
    lda.w #$1400
    sta $06
    lda.w #$00D0
    sta $08
    lda $0E
    sta $04
    asl A
    adc $04
    asl A
    asl A
    clc
    adc $06
    sta $06
    cpx.w #$0000
    bne C068E6_Probe_Type6DoorCandidate_L68E6
    sep #$20
    ldy.w #$000B
    lda [$06],Y
    rep #$20
    and.w #$00FF
    bra C068F2_Probe_Type6DoorCandidate_L68F2
C068E6_Probe_Type6DoorCandidate_L68E6:
    sep #$20
    ldy.w #$0007
    lda [$06],Y
    rep #$20
    and.w #$00FF
C068F2_Probe_Type6DoorCandidate_L68F2:
    pld
    rtl
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sta $10
    lda $5DD8
    beq C06908_Probe_Type6DoorCandidate_L6908
    jmp.w C069AD_Probe_Type6DoorCandidate_L69AD
C06908_Probe_Type6DoorCandidate_L6908:
    lda $10
    xba
    and.w #$00FF
    sta $02
    ldy.w #$0080
    txa
    jsl C0915B_DivideUnsignedWordByY
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    lda $DCD637,X
    and.w #$00FF
    sta $10
    lda.w #$0000
    sta $0A
    lda.w #$00CF
    sta $0C
    lda $10
    asl A
    tax
    lda $CF58EF,X
    and.w #$7FFF
    clc
    adc $0A
    sta $0A
C06944_Probe_Type6DoorCandidate_L6944:
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda [$06]
    beq C0697A_Probe_Type6DoorCandidate_L697A
    and.w #$7FFF
    jsl C21628_CheckEventFlag
    sta $0E
    ldx.w #$0000
    lda [$06]
    cmp.w #$8000
    bcc C06968_Probe_Type6DoorCandidate_L6968
    beq C06968_Probe_Type6DoorCandidate_L6968
    ldx.w #$0001
C06968_Probe_Type6DoorCandidate_L6968:
    stx $02
    lda $0E
    cmp $02
    beq C0697A_Probe_Type6DoorCandidate_L697A
    lda.w #$0004
    clc
    adc $0A
    sta $0A
    bra C06944_Probe_Type6DoorCandidate_L6944
C0697A_Probe_Type6DoorCandidate_L697A:
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda $06
    sta $5E38
    lda $08
    sta $5E3A
    sep #$20
    ldy.w #$0002
    lda [$0A],Y
    rep #$20
    and.w #$00FF
    tax
    stx $5DD6
    lda $5DDA
    bne C069AD_Probe_Type6DoorCandidate_L69AD
    cpx $5DD4
    beq C069AD_Probe_Type6DoorCandidate_L69AD
    lda.w #$0002
    jsl C0AC0C_QueuePresentationSfxOrCounter
C069AD_Probe_Type6DoorCandidate_L69AD:
    pld
    rtl
    rep #$31
    phd
    tdc
    adc.w #$FFF2
    tcd
    lda $5DD8
    bne C069EB_Probe_Type6DoorCandidate_L69EB
    lda $5E38
    sta $06
    lda $5E3A
    sta $08
    lda $5DD6
    cmp $5DD4
    beq C069EB_Probe_Type6DoorCandidate_L69EB
    lda $5DD6
    sta $5DD4
    lda $5DD6
    jsl C4FBBD_PlaySoundStoneMelody
    sep #$20
    ldy.w #$0003
    lda [$06],Y
    rep #$20
    and.w #$00FF
    jsl C0AC0C_QueuePresentationSfxOrCounter
C069EB_Probe_Type6DoorCandidate_L69EB:
    pld
    rtl
    rep #$31
    lda $5DD6
    jsl C4FBBD_PlaySoundStoneMelody
    rtl
