; EarthBound C0 Wait One Frame And Poll Input.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:8756..C0:878B Wait_OneFrameAndPollInput

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:8756

C08756_Wait_OneFrameAndPollInput:
    sep #$20
    lda $001E
    and.b #$B0
    beq C08769_Wait_OneFrameAndPollInput_L8769
C0875F_Wait_OneFrameAndPollInput_L875F:
    lda $002B
    beq C0875F_Wait_OneFrameAndPollInput_L875F
    stz $002B
    bra C08775_Wait_OneFrameAndPollInput_L8775
C08769_Wait_OneFrameAndPollInput_L8769:
    lda $004212
    bmi C08769_Wait_OneFrameAndPollInput_L8769
C0876F_Wait_OneFrameAndPollInput_L876F:
    lda $004212
    bpl C0876F_Wait_OneFrameAndPollInput_L876F
C08775_Wait_OneFrameAndPollInput_L8775:
    stz $002B
    phd
    pea $0000
    pld
    phb
    pea $0000
    plb
    plb
    jsr $8496
    plb
    pld
    rep #$20
    rtl
