; EarthBound C0 Publish Runtime Scroll Shadows To Nmi Buffers.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:8B20..C0:8B8E PublishRuntimeScrollShadowsToNmiBuffers

; ---------------------------------------------------------------------------
; External contracts used by this module

C088B1_ResetRendererFrameState = $C088B1

; ---------------------------------------------------------------------------
; C0:8B20

C08B20_PublishRuntimeScrollShadowsToNmiBuffers:
    rep #$20
    jsl C088B1_ResetRendererFrameState
    rep #$30
    jsr $8B8E
    sep #$20
    phb
    pla
    cmp.b #$FF
    bne C08B35_PublishRuntimeScrollShadowsToNmiBuffers_L8B35
C08B33_PublishRuntimeScrollShadowsToNmiBuffers_L8B33:
    bra C08B33_PublishRuntimeScrollShadowsToNmiBuffers_L8B33
C08B35_PublishRuntimeScrollShadowsToNmiBuffers_L8B35:
    lda $000A
    cmp.b #$80
    beq C08B40_PublishRuntimeScrollShadowsToNmiBuffers_L8B40
C08B3C_PublishRuntimeScrollShadowsToNmiBuffers_L8B3C:
    lsr A
    lsr A
    bcc C08B3C_PublishRuntimeScrollShadowsToNmiBuffers_L8B3C
C08B40_PublishRuntimeScrollShadowsToNmiBuffers_L8B40:
    ldx $0007
    sta $0000,X
    rep #$30
    lda $002E
    dec A
    asl A
    tax
    lda $0031
    sta $0041,X
    lda $0033
    sta $0045,X
    lda $0035
    sta $0049,X
    lda $0037
    sta $004D,X
    lda $0039
    sta $0051,X
    lda $003B
    sta $0055,X
    lda $003D
    sta $0059,X
    lda $003F
    sta $005D,X
    sep #$20
    lda $002E
    sta $002C
    eor.b #$03
    sta $002E
    rep #$30
    rtl
