; EarthBound C0 Advance Input Playback Stream.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:841B..C0:8456 Advance_InputPlaybackStream

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:841B

C0841B_Advance_InputPlaybackStream:
    rep #$30
    lda $7B
    beq C0844B_Advance_InputPlaybackStream_L844B
    and.w #$4000
    beq C0844B_Advance_InputPlaybackStream_L844B
    dec $81
    bne C08455_Advance_InputPlaybackStream_L8455
    inc $7D
    inc $7D
    inc $7D
    lda [$7D]
    and.w #$00FF
    beq C08444_Advance_InputPlaybackStream_L8444
    sta $81
    ldy.w #$0001
    lda [$7D],Y
    sta $77
    sta $79
    bra C08455_Advance_InputPlaybackStream_L8455
C08444_Advance_InputPlaybackStream_L8444:
    lda $7B
    and.w #$BFFF
    sta $7B
C0844B_Advance_InputPlaybackStream_L844B:
    lda $421A
    sta $79
    lda $4218
    sta $77
C08455_Advance_InputPlaybackStream_L8455:
    rts
