; EarthBound C0 Nmi Service Audio Queue.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:8501..C0:8518 Nmi_ServiceAudioQueue

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:8501

C08501_Nmi_ServiceAudioQueue:
    sep #$30
    ldx $CB
    cpx $CA
    beq C08515_Nmi_ServiceAudioQueue_L8515
    lda $1AC2,X
    sta $2143
    txa
    inc A
    and.b #$07
    sta $CB
C08515_Nmi_ServiceAudioQueue_L8515:
    rep #$30
    rts
