; EarthBound C0 Action Script Prepare New Entity.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A912..C0:A92D ActionScript_PrepareNewEntity

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A912

C0A912_ActionScript_PrepareNewEntity:
    jsl $C09D94
    sty $94
    pha
    jsl $C09D94
    sty $94
    pha
    jsl $C09D86
    sty $94
    ply
    plx
    jsl $C46E37
    rtl
