; EarthBound C0 Refresh Slot Visual Profile By Index.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A48F..C0:A4A8 RefreshSlotVisualProfileByIndex

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A48F

C0A48F_RefreshSlotVisualProfileByIndex:
    rep #$20
    phd
    pha
    tdc
    sec
    sbc.w #$0006
    tcd
    pla
    asl A
    tay
    lda $10F2,Y
    sta $2892
    jsl $C0A4C4
    pld
    rtl
