; EarthBound C0 Get Direction From Player To Entity.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:C4F7..C0:C524 GetDirectionFromPlayerToEntity

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:C4F7

C0C4F7_GetDirectionFromPlayerToEntity:
    rep #$31
    phd
    tdc
    adc.w #$FFEC
    tcd
    lda $1A42
    asl A
    sta $12
    lda $987B
    sta $0E
    ldy $9877
    lda $12
    tax
    lda $0BCA,X
    tax
    stx $10
    lda $12
    tax
    lda $0B8E,X
    ldx $10
    jsl $C45FA8
    pld
    rtl
