; EarthBound C0 Run Intro Timed Palette Fade Tail.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:F1D2..C0:F21E RunIntroTimedPaletteFadeTail

; ---------------------------------------------------------------------------
; External contracts used by this module

C4954C_SeedPaletteFadeWorkBuffer      = $C4954C
C496E7_StartPaletteFadeFromWorkBuffer = $C496E7

; ---------------------------------------------------------------------------
; C0:F1D2

C0F1D2_RunIntroTimedPaletteFadeTail:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE8
    tcd
    pla
    tay
    sty $16
    lda.w #$0200
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $12
    lda $08
    sta $14
    lda.w #$007E
    sta $14
    lda $12
    sta $06
    lda $14
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda.w #$0064
    jsl C4954C_SeedPaletteFadeWorkBuffer
    ldx.w #$FFFF
    ldy $16
    tya
    jsl C496E7_StartPaletteFadeFromWorkBuffer
    pld
    rts
