; EarthBound C6 text segment E10FOUR0.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/c6-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - C6:D19C..C6:F8D9 TextSegmentE10four0

; ---------------------------------------------------------------------------
; C6:F8D9

; TextSegmentE10four0End
C6F8D9_TextSegmentE10four0End:
