; EarthBound D5 asset SPRITE_1112.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d5-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D5:34C0..D5:3540 AssetSprite1112

; ---------------------------------------------------------------------------
; D5:3540

; AssetSprite1112End
D53540_AssetSprite1112End:
