#!/usr/bin/env python3
"""Build the durable audio backend adapter contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from audio_renderers import describe_renderer_backends


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_JSON = ROOT / "manifests" / "audio-backend-contract.json"
DEFAULT_MARKDOWN = ROOT / "notes" / "audio-backend-contract.md"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the audio backend adapter contract.")
    parser.add_argument("--json", default=str(DEFAULT_JSON), help="JSON output path.")
    parser.add_argument("--markdown", default=str(DEFAULT_MARKDOWN), help="Markdown output path.")
    return parser.parse_args()


def build_contract() -> dict[str, Any]:
    return {
        "schema": "earthbound-decomp.audio-backend-contract.v1",
        "status": "adapter_contract_ready_fused_snapshot_playback_export_implemented_oracle_comparison_pending",
        "source_policy": {
            "requires_user_supplied_rom": True,
            "do_not_commit_generated_outputs": True,
            "generated_audio_output_root": "build/audio",
        },
        "backend_selection": {
            "default_accuracy_backend": "ares",
            "default_lightweight_backend": "snes_spc_after_complete_spc_snapshots_exist",
            "reference_backends": ["bsnes_higan", "mesen2", "mednafen"],
            "policy": "Use an external harness first. Do not vendor or carve emulator code until the prototype proves which pieces are necessary.",
        },
        "input_artifacts": [
            {
                "name": "renderer_fixture",
                "schema": "earthbound-decomp.audio-renderer-fixture.v1",
                "path_pattern": "build/audio/renderer-fixtures/track-###-name.renderer-fixture.json",
                "contains_rom_derived_bytes": False,
                "references_rom_derived_bytes": True,
                "purpose": "Points to the generated APU RAM seed and records the exact pack load transcript.",
            },
            {
                "name": "apu_ram_seed",
                "schema": "raw_65536_byte_apu_ram_image",
                "path_pattern": "build/audio/renderer-fixtures/track-###-name.apu-ram.bin",
                "contains_rom_derived_bytes": True,
                "purpose": "Diagnostic state seed after applying EarthBound audio load streams.",
            },
            {
                "name": "backend_job",
                "schema": "earthbound-decomp.audio-backend-job-index.v1/jobs[]",
                "path_pattern": "build/audio/backend-jobs/<job-id>/job.json",
                "contains_rom_derived_bytes": False,
                "references_rom_derived_bytes": True,
                "purpose": "Per-track render/capture request consumed by an external backend harness.",
            },
        ],
        "job_schema": {
            "required_fields": [
                "job_id",
                "backend_id",
                "fixture_path",
                "output_dir",
                "render_options",
                "expected_outputs",
                "track_id",
                "track_name",
                "input_apu_ram_sha1",
                "result_schema",
                "job_path",
                "result_path",
            ],
            "render_options": ["seconds", "fade_seconds", "sample_rate", "channels", "output_format"],
            "expected_output_kinds": [
                "state_capture_json",
                "complete_spc_snapshot",
                "rendered_wav",
                "rendered_pcm",
                "render_hash_json",
                "reference_capture_json",
            ],
        },
        "result_schema": {
            "schema": "earthbound-decomp.audio-backend-result.v1",
            "required_fields": [
                "job_id",
                "backend_id",
                "backend_version",
                "status",
                "input_fixture_path",
                "input_apu_ram_sha1",
                "outputs",
                "diagnostics",
            ],
            "status_values": ["ok", "failed", "unsupported", "mismatch"],
            "output_record_fields": ["kind", "path", "sha1", "bytes"],
            "diagnostic_expectations": [
                "Report whether the backend ran the real SNES/APU boot and load protocol or consumed a completed snapshot.",
                "Report whether CPU/APU port handshakes were executed or mocked.",
                "Report capture/render timing in frames, samples, or cycles.",
            ],
            "output_validation": [
                "rendered_wav outputs must have a RIFF/WAVE header.",
                "playback/export WAV outputs must be 16-bit PCM stereo at the declared sample rate with data samples matching render metrics.",
                "complete_spc_snapshot outputs must include the SNES-SPC700 signature.",
                "JSON/PCM/hash outputs must be non-empty and match their declared SHA-1.",
            ],
        },
        "backend_catalog": describe_renderer_backends(),
        "native_ares_harness": {
            "source": "tools/ares_audio_harness",
            "build_dir": "build/audio/ares-audio-harness-msvc",
            "executable": "build/audio/ares-audio-harness-msvc/RelWithDebInfo/earthbound_ares_audio_harness.exe",
            "current_capability": "Consumes backend job JSON, verifies the generated APU RAM seed SHA-1, imports it into ares::SuperFamicom::dsp.apuram, captures public register preflight state, probes the $0500 driver entry with ares' SPC700 disassembler, runs an ares::SPC700 RAM/IO shim with rough timer0 progress, injects the diagnostic APUIO0 track command after timer enable or on the driver's first APUIO0 read, advances into track-specific driver update code, emits state_capture_json plus diagnostic complete_spc_snapshot outputs, records a real last-key-on SPC snapshot when the probe writes a nonzero DSP KON value, and records instruction/sequence evidence for IO, DSP writes, command injection, command first-read events, an ordered command mailbox IO window, and last-key-on timing. A separate ares SMP mailbox smoke now uses real ares SuperFamicom::smp, SuperFamicom::cpu, SuperFamicom::dsp, and WDC65816 instruction execution, delivers the command through smp.portWrite, CPU-side writeAPU($2140, track), a modeled C0:ABBD sep/sta.l $002140 prefix, the full modeled C0:ABBD sep/sta.l/rep/rtl routine, direct ROM-derived C0:ABBD bytes, a modeled JSL into ROM-derived C0:ABBD, the ROM-derived CHANGE_MUSIC tail, the full ROM-derived CHANGE_MUSIC body under a documented pre-satisfied pack state, the full ROM-derived CHANGE_MUSIC body with real pack-decision branches and stubbed LOAD_SPC700_DATA calls, or the full ROM-derived CHANGE_MUSIC body starting from bootstrap APU RAM and applying selected LOAD_SPC700_DATA payload streams at the $062A command-read boundary, writes key-on SPC snapshots, and feeds them to the same libgme render pipeline. A focused C0:AB06 loader harness now executes the ROM-derived LOAD_SPC700_DATA routine bytes against a modeled APUIO receiver and checks the selected pack stream byte/block/terminal counts.",
            "current_result_status": "unsupported",
            "why_not_ok_yet": "The SPC snapshot is structurally valid but diagnostic: the harness uses diagnostic command delivery instead of the real CPU/APU track-start handshake, does not use the full SMP scheduler/DSP timing path, does not finalize port state at a stable render boundary, and does not render PCM/WAV.",
        },
        "libgme_harness": {
            "source": "tools/libgme_audio_harness",
            "external_checkout": "<local libgme checkout outside this repository>",
            "observed_commit": "dd3182a8",
            "build_dir": "build/audio/libgme-audio-harness-msvc",
            "executable": "build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe",
            "linked_library": "<local libgme build>/gme/RelWithDebInfo/gme.lib",
            "current_capability": "Consumes snes_spc backend job JSON, opens the matching fused CHANGE_MUSIC/key-on SPC snapshot through libgme, honors the job's seconds/sample-rate/channel render options, emits WAV/render metrics, and writes a schema-valid ok result.",
            "current_result_status": "ok_for_fused_snapshot_playback_export",
            "why_not_final": "The renderer path works across the all-track fused CHANGE_MUSIC/key-on corpus, but release-quality confidence still needs an emulator-captured oracle comparison and any loop/fade/export policy decisions.",
        },
        "validation_tools": [
            "tools/build_audio_renderer_fixtures.py",
            "tools/validate_audio_renderer_fixtures.py",
            "tools/build_audio_backend_jobs.py",
            "tools/validate_audio_backend_jobs.py",
            "tools/run_audio_backend_job.py",
            "tools/run_audio_backend_batch.py",
            "tools/audio_backend_stub_harness.py",
            "tools/ares_audio_harness/CMakeLists.txt",
            "tools/libgme_audio_harness/CMakeLists.txt",
            "tools/collect_audio_backend_results.py",
            "tools/validate_audio_backend_result_summary.py",
            "tools/collect_audio_diagnostic_spc_snapshots.py",
            "tools/validate_audio_diagnostic_spc_snapshots.py",
            "tools/collect_audio_capture_metrics.py",
            "tools/validate_audio_capture_metrics.py",
            "tools/collect_audio_render_metrics.py",
            "tools/validate_audio_render_metrics.py",
            "tools/build_audio_keyon_primed_spc_experiment.py",
            "tools/validate_audio_keyon_primed_spc_experiment.py",
            "tools/build_audio_last_keyon_spc_experiment.py",
            "tools/validate_audio_last_keyon_spc_experiment.py",
            "tools/build_audio_cpu_mailbox_contract.py",
            "tools/validate_audio_cpu_mailbox_contract.py",
            "tools/build_audio_cpu_routine_fixtures.py",
            "tools/validate_audio_cpu_routine_fixtures.py",
            "tools/build_audio_bootstrap_snapshot_corpus.py",
            "tools/collect_audio_change_music_load_stub_metrics.py",
            "tools/validate_audio_change_music_load_stub_metrics.py",
            "tools/collect_audio_load_stream_transfer_metrics.py",
            "tools/validate_audio_load_stream_transfer_metrics.py",
            "tools/collect_audio_c0ab06_loader_contract.py",
            "tools/validate_audio_c0ab06_loader_contract.py",
            "tools/ares_c0ab06_loader_handshake/CMakeLists.txt",
            "tools/run_audio_c0ab06_loader_handshake_corpus.py",
            "tools/validate_audio_c0ab06_loader_handshake_corpus.py",
            "tools/collect_audio_c0ab06_real_ipl_frontier.py",
            "tools/validate_audio_c0ab06_real_ipl_frontier.py",
            "tools/collect_audio_c0ab06_post_bootstrap_frontier.py",
            "tools/validate_audio_c0ab06_post_bootstrap_frontier.py",
            "tools/collect_audio_c0ab06_continuous_track_load_frontier.py",
            "tools/validate_audio_c0ab06_continuous_track_load_frontier.py",
            "tools/collect_audio_change_music_continuous_sequence_contract.py",
            "tools/validate_audio_change_music_continuous_sequence_contract.py",
            "tools/collect_audio_c0ab06_change_music_fusion_frontier.py",
            "tools/validate_audio_c0ab06_change_music_fusion_frontier.py",
            "tools/build_audio_c0ab06_change_music_fusion_spc_index.py",
            "tools/build_audio_backend_jobs_from_spc_index.py",
            "tools/collect_audio_fusion_timing_metrics.py",
            "tools/validate_audio_fusion_timing_metrics.py",
            "tools/build_audio_playback_export_manifest.py",
            "tools/validate_audio_playback_export_manifest.py",
            "tools/build_audio_export_duration_policy.py",
            "tools/validate_audio_export_duration_policy.py",
            "tools/collect_audio_export_duration_measurements.py",
            "tools/validate_audio_export_duration_measurements.py",
            "tools/build_audio_export_plan.py",
            "tools/validate_audio_export_plan.py",
            "tools/build_audio_sequence_semantics_frontier.py",
            "tools/validate_audio_sequence_semantics_frontier.py",
            "tools/build_audio_sequence_control_flow_frontier.py",
            "tools/validate_audio_sequence_control_flow_frontier.py",
            "tools/build_audio_sequence_walk_frontier.py",
            "tools/validate_audio_sequence_walk_frontier.py",
            "tools/build_audio_exact_duration_triage.py",
            "tools/validate_audio_exact_duration_triage.py",
            "tools/build_audio_ebdecompile_ref_alignment.py",
            "tools/validate_audio_ebdecompile_ref_alignment.py",
            "tools/build_audio_oracle_comparison_plan.py",
            "tools/validate_audio_oracle_comparison_plan.py",
            "tools/import_audio_oracle_reference_capture.py",
            "tools/populate_audio_oracle_self_reference.py",
            "tools/import_audio_oracle_references_from_backend_summary.py",
            "tools/collect_audio_oracle_comparison_results.py",
            "tools/validate_audio_oracle_comparison_summary.py",
            "tools/build_audio_oracle_verification_report.py",
            "tools/validate_audio_oracle_verification_report.py",
            "tools/build_audio_dependency_policy.py",
            "tools/validate_audio_dependency_policy.py",
            "tools/ares_smp_mailbox_smoke/CMakeLists.txt",
            "tools/run_audio_ares_smp_mailbox_smoke.py",
            "tools/validate_audio_ares_smp_mailbox_smoke.py",
            "tools/build_audio_ares_smp_mailbox_spc_index.py",
            "tools/validate_audio_ares_smp_mailbox_spc_index.py",
            "tools/run_audio_last_keyon_experiment.py",
            "tools/collect_audio_runtime_frontier.py",
            "tools/validate_audio_runtime_frontier.py",
            "tools/run_audio_ares_no_command_experiment.py",
            "tools/collect_audio_no_command_frontier.py",
            "tools/validate_audio_no_command_frontier.py",
            "tools/run_audio_ares_command_timing_experiment.py",
            "tools/collect_audio_command_timing_frontier.py",
            "tools/validate_audio_command_timing_frontier.py",
            "tools/collect_audio_mailbox_frontier.py",
            "tools/validate_audio_mailbox_frontier.py",
            "tools/compare_audio_render_metrics.py",
            "tools/validate_audio_render_metrics_comparison.py",
            "tools/snes_spc_diagnostic_harness.py",
            "tools/check_ares_backend_prereq.py",
            "tools/ares_link_smoke/CMakeLists.txt",
            "tools/build_audio_backend_result_stub.py",
            "tools/validate_audio_backend_result.py",
        ],
    }


def render_markdown(contract: dict[str, Any]) -> str:
    input_rows = [
        "| `{name}` | `{schema}` | `{path}` | {rom} | {purpose} |".format(
            name=item["name"],
            schema=item["schema"],
            path=item["path_pattern"],
            rom="yes" if item.get("contains_rom_derived_bytes") else "no",
            purpose=item["purpose"],
        )
        for item in contract["input_artifacts"]
    ]
    backend_rows = [
        "| `{id}` | {license} | {policy} | {implemented} | {stage} |".format(
            id=backend["id"],
            license=backend["license_policy"],
            policy=backend["execution_policy"],
            implemented=backend["implemented"],
            stage=backend.get("implementation_stage", "not specified"),
        )
        for backend in contract["backend_catalog"]
    ]
    return "\n".join(
        [
            "# Audio Backend Contract",
            "",
            "Status: adapter contract ready; all-track fused snapshot playback/export implemented; emulator-oracle comparison and export policy polish still pending.",
            "",
            "This contract keeps ares, snes_spc, and optional reference renderers outside the core project until a prototype proves the exact integration path. The repo owns the input fixtures and result schema; backend harnesses own emulation, state capture, and PCM/WAV rendering.",
            "",
            "## Backend Selection",
            "",
            f"- default accuracy backend: `{contract['backend_selection']['default_accuracy_backend']}`",
            f"- default lightweight backend: `{contract['backend_selection']['default_lightweight_backend']}`",
            f"- reference backends: `{contract['backend_selection']['reference_backends']}`",
            f"- policy: {contract['backend_selection']['policy']}",
            "",
            "## Input Artifacts",
            "",
            "| Artifact | Schema | Path pattern | Contains ROM-derived bytes | Purpose |",
            "| --- | --- | --- | --- | --- |",
            *input_rows,
            "",
            "## Job Schema",
            "",
            f"- required fields: `{contract['job_schema']['required_fields']}`",
            f"- render options: `{contract['job_schema']['render_options']}`",
            f"- expected output kinds: `{contract['job_schema']['expected_output_kinds']}`",
            "- each generated job also has a per-job `job.json` so external harnesses can consume one track at a time.",
            "- dry-run or dispatch one job with `python tools/run_audio_backend_job.py ares-track-046-onett`.",
            "- dry-run or dispatch pending jobs in batch with `python tools/run_audio_backend_batch.py --limit 2`.",
            "- external harness shape check: `python tools/run_audio_backend_job.py ares-track-046-onett --mode external --external python tools/audio_backend_stub_harness.py --job \"{job}\" --result \"{result}\"`.",
            "- native ares diagnostic run: `python tools/run_audio_backend_job.py ares-track-046-onett --mode native-ares`.",
            "- native ares diagnostic corpus: `python tools/run_audio_backend_batch.py --mode native-ares --force`.",
            "- snes_spc diagnostic job queue: `python tools/build_audio_backend_jobs.py --backend snes_spc`.",
            "- snes_spc diagnostic adapter corpus: `python tools/run_audio_backend_batch.py --jobs build/audio/backend-jobs/snes_spc-jobs.json --summary build/audio/backend-jobs/snes_spc-result-summary.json --mode external --force --external python tools/snes_spc_diagnostic_harness.py --job \"{job}\" --result \"{result}\"`.",
            "- libgme diagnostic renderer build: `cmake -S tools/libgme_audio_harness -B build/audio/libgme-audio-harness-msvc -G \"Visual Studio 17 2022\" -DLIBGME_ROOT=<local-libgme-checkout>` then `cmake --build build/audio/libgme-audio-harness-msvc --config RelWithDebInfo`.",
            "- libgme diagnostic render corpus: `python tools/run_audio_backend_batch.py --jobs build/audio/backend-jobs/snes_spc-jobs.json --summary build/audio/backend-jobs/snes_spc-result-summary.json --mode external --force --external build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe --job \"{job}\" --result \"{result}\"`.",
            "- ares diagnostic capture metrics: `python tools/collect_audio_capture_metrics.py` then `python tools/validate_audio_capture_metrics.py`.",
            "- libgme diagnostic render metrics: `python tools/collect_audio_render_metrics.py` then `python tools/validate_audio_render_metrics.py`.",
            "- key-on primed SPC experiment: `python tools/build_audio_keyon_primed_spc_experiment.py` then `python tools/validate_audio_keyon_primed_spc_experiment.py`.",
            "- key-on primed render corpus: `python tools/run_audio_backend_batch.py --jobs build/audio/keyon-primed-jobs/snes_spc-jobs.json --summary build/audio/keyon-primed-jobs/snes_spc-result-summary.json --mode external --force --external build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe --job \"{job}\" --result \"{result}\" --snapshot-index build/audio/keyon-primed-spc/keyon-primed-spc-snapshots.json`.",
            "- last-key-on SPC experiment: `python tools/build_audio_last_keyon_spc_experiment.py` then `python tools/validate_audio_last_keyon_spc_experiment.py`.",
            "- full last-key-on render experiment: `python tools/run_audio_last_keyon_experiment.py`.",
            "- last-key-on render corpus: `python tools/build_audio_backend_jobs.py --backend snes_spc --out build/audio/last-keyon-jobs` then `python tools/run_audio_backend_batch.py --jobs build/audio/last-keyon-jobs/snes_spc-jobs.json --summary build/audio/last-keyon-jobs/snes_spc-result-summary.json --mode external --force --external build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe --job \"{job}\" --result \"{result}\" --snapshot-index build/audio/last-keyon-spc/last-keyon-spc-snapshots.json`.",
            "- audio runtime frontier report: `python tools/collect_audio_runtime_frontier.py` then `python tools/validate_audio_runtime_frontier.py`.",
            "- no-command negative-control experiment: `python tools/run_audio_ares_no_command_experiment.py`.",
            "- key-on comparison: `python tools/compare_audio_render_metrics.py` then `python tools/validate_audio_render_metrics_comparison.py`.",
            "- ares SMP mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-smp-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_smp_portwrite_on_pc_062a`.",
            "- ares SMP mailbox SPC index: `python tools/build_audio_ares_smp_mailbox_spc_index.py` then `python tools/validate_audio_ares_smp_mailbox_spc_index.py build/audio/ares-smp-mailbox-spc/ares-smp-mailbox-spc-snapshots.json`.",
            "- ares SMP mailbox render corpus: `python tools/build_audio_backend_jobs.py --backend snes_spc --out build/audio/ares-smp-mailbox-render-jobs` then `python tools/run_audio_backend_batch.py --jobs build/audio/ares-smp-mailbox-render-jobs/snes_spc-jobs.json --summary build/audio/ares-smp-mailbox-render-jobs/snes_spc-result-summary.json --mode external --force --external build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe --job \"{job}\" --result \"{result}\" --snapshot-index build/audio/ares-smp-mailbox-spc/ares-smp-mailbox-spc-snapshots.json`.",
            "- CPU-side writeAPU mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery cpu_writeapu --out build/audio/ares-cpu-writeapu-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-cpu-writeapu-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_cpu_writeapu_2140_on_pc_062a`.",
            "- WDC65816 STA $2140 mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_sta2140 --out build/audio/ares-wdc65816-sta2140-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-sta2140-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_sta_2140_on_pc_062a`.",
            "- full C0:ABBD mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_c0abbd --out build/audio/ares-wdc65816-c0abbd-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-c0abbd-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_full_c0abbd_on_pc_062a`.",
            "- ROM-derived C0:ABBD fixture: `python tools/build_audio_cpu_routine_fixtures.py` then `python tools/validate_audio_cpu_routine_fixtures.py`.",
            "- ROM-derived C0:ABBD mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_rom_c0abbd --out build/audio/ares-wdc65816-rom-c0abbd-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-rom-c0abbd-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_rom_c0abbd_on_pc_062a`.",
            "- ROM-derived C0:ABBD JSL-call mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_rom_c0abbd_jsl --out build/audio/ares-wdc65816-rom-c0abbd-jsl-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-rom-c0abbd-jsl-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_rom_c0abbd_jsl_on_pc_062a`.",
            "- CHANGE_MUSIC tail mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_change_music_tail --out build/audio/ares-wdc65816-change-music-tail-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-change-music-tail-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_change_music_tail_on_pc_062a`.",
            "- full CHANGE_MUSIC pre-satisfied-pack mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_full_change_music --out build/audio/ares-wdc65816-full-change-music-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-full-change-music-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_full_change_music_on_pc_062a`.",
            "- full CHANGE_MUSIC load-path-stub mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_full_change_music_load_stub --out build/audio/ares-wdc65816-full-change-music-load-stub-mailbox-smoke-jobs`, then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-full-change-music-load-stub-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_full_change_music_load_stub_on_pc_062a`, then `python tools/collect_audio_change_music_load_stub_metrics.py` and `python tools/validate_audio_change_music_load_stub_metrics.py`.",
            "- bootstrap APU RAM corpus: `python tools/build_audio_bootstrap_snapshot_corpus.py` then `python tools/validate_audio_snapshot_corpus.py build/audio/bootstrap-corpus/audio-bootstrap-snapshot-corpus.json`.",
            "- full CHANGE_MUSIC load-apply mailbox smoke: `python tools/run_audio_ares_smp_mailbox_smoke.py --delivery wdc65816_full_change_music_load_apply --out build/audio/ares-wdc65816-full-change-music-load-apply-mailbox-smoke-jobs` then `python tools/validate_audio_ares_smp_mailbox_smoke.py build/audio/ares-wdc65816-full-change-music-load-apply-mailbox-smoke-jobs/smp-mailbox-smoke-summary.json --require-delivery-mode ares_wdc65816_full_change_music_load_apply_on_pc_062a`.",
            "- semantic LOAD_SPC700_DATA transfer proof: `python tools/collect_audio_load_stream_transfer_metrics.py` then `python tools/validate_audio_load_stream_transfer_metrics.py`.",
            "- C0:AB06 loader contract proof: `python tools/collect_audio_c0ab06_loader_contract.py` then `python tools/validate_audio_c0ab06_loader_contract.py`.",
            "- C0:AB06 loader byte-handshake corpus: `cmake -S tools/ares_c0ab06_loader_handshake -B build/audio/ares-c0ab06-loader-handshake-msvc -G \"Visual Studio 17 2022\" -DARES_ROOT=<local-ares-checkout>`, then `cmake --build build/audio/ares-c0ab06-loader-handshake-msvc --config RelWithDebInfo`, then `python tools/run_audio_c0ab06_loader_handshake_corpus.py` and `python tools/validate_audio_c0ab06_loader_handshake_corpus.py`.",
            "- C0:AB06 real ares SMP IPL receiver frontier: `python tools/collect_audio_c0ab06_real_ipl_frontier.py` then `python tools/validate_audio_c0ab06_real_ipl_frontier.py`.",
            "- C0:AB06 post-bootstrap game-driver reload frontier: `python tools/collect_audio_c0ab06_post_bootstrap_frontier.py` then `python tools/validate_audio_c0ab06_post_bootstrap_frontier.py`.",
            "- C0:AB06 continuous representative track load frontier: `python tools/collect_audio_c0ab06_continuous_track_load_frontier.py` then `python tools/validate_audio_c0ab06_continuous_track_load_frontier.py`.",
            "- CHANGE_MUSIC-to-continuous-load sequence contract: `python tools/collect_audio_change_music_continuous_sequence_contract.py` then `python tools/validate_audio_change_music_continuous_sequence_contract.py`.",
            "- full CHANGE_MUSIC/real-C0:AB06 fusion frontier: `python tools/collect_audio_c0ab06_change_music_fusion_frontier.py` then `python tools/validate_audio_c0ab06_change_music_fusion_frontier.py`.",
            "- fused CHANGE_MUSIC/C0:AB06 SPC index: `python tools/build_audio_c0ab06_change_music_fusion_spc_index.py` then `python tools/validate_audio_ares_smp_mailbox_spc_index.py build/audio/c0ab06-change-music-fusion-spc/c0ab06-change-music-fusion-spc-snapshots.json`.",
            "- fused CHANGE_MUSIC/C0:AB06 libgme render corpus: `python tools/build_audio_backend_jobs.py --backend snes_spc --out build/audio/c0ab06-change-music-fusion-render-jobs`, then `python tools/run_audio_backend_batch.py --jobs build/audio/c0ab06-change-music-fusion-render-jobs/snes_spc-jobs.json --summary build/audio/c0ab06-change-music-fusion-render-jobs/snes_spc-result-summary.json --mode external --force --external build/audio/libgme-audio-harness-msvc/RelWithDebInfo/earthbound_libgme_audio_harness.exe --job \"{job}\" --result \"{result}\" --snapshot-index build/audio/c0ab06-change-music-fusion-spc/c0ab06-change-music-fusion-spc-snapshots.json`, then `python tools/collect_audio_render_metrics.py --jobs build/audio/c0ab06-change-music-fusion-render-jobs/snes_spc-jobs.json --output build/audio/c0ab06-change-music-fusion-render-jobs/libgme-render-metrics.json`.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 frontier: `python tools/collect_audio_c0ab06_change_music_fusion_frontier.py --all-tracks --output build/audio/c0ab06-change-music-fusion-frontier-all/c0ab06-change-music-fusion-frontier-all.json` then `python tools/validate_audio_c0ab06_change_music_fusion_frontier.py build/audio/c0ab06-change-music-fusion-frontier-all/c0ab06-change-music-fusion-frontier-all.json`.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 SPC/render corpus: `python tools/build_audio_c0ab06_change_music_fusion_spc_index.py --frontier build/audio/c0ab06-change-music-fusion-frontier-all/c0ab06-change-music-fusion-frontier-all.json --output build/audio/c0ab06-change-music-fusion-spc-all/c0ab06-change-music-fusion-spc-all-snapshots.json`, then `python tools/build_audio_backend_jobs_from_spc_index.py --snapshot-index build/audio/c0ab06-change-music-fusion-spc-all/c0ab06-change-music-fusion-spc-all-snapshots.json --out build/audio/c0ab06-change-music-fusion-render-jobs-all`, then render through the libgme external harness with that all-track snapshot index.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 timing metrics: `python tools/collect_audio_fusion_timing_metrics.py` then `python tools/validate_audio_fusion_timing_metrics.py`.",
            "- all-track playback/export handoff: `python tools/build_audio_playback_export_manifest.py` then `python tools/validate_audio_playback_export_manifest.py`.",
            "- audio export duration policy: `python tools/build_audio_export_duration_policy.py` then `python tools/validate_audio_export_duration_policy.py`.",
            "- audio export duration measurements: `python tools/collect_audio_export_duration_measurements.py` then `python tools/validate_audio_export_duration_measurements.py`.",
            "- audio export plan: `python tools/build_audio_export_plan.py` then `python tools/validate_audio_export_plan.py`.",
            "- audio sequence semantics frontier: `python tools/build_audio_sequence_semantics_frontier.py` then `python tools/validate_audio_sequence_semantics_frontier.py`.",
            "- audio sequence control-flow frontier: `python tools/build_audio_sequence_control_flow_frontier.py` then `python tools/validate_audio_sequence_control_flow_frontier.py`.",
            "- audio sequence walk frontier: `python tools/build_audio_sequence_walk_frontier.py` then `python tools/validate_audio_sequence_walk_frontier.py`.",
            "- audio exact-duration triage: `python tools/build_audio_exact_duration_triage.py` then `python tools/validate_audio_exact_duration_triage.py`.",
            "- audio FF terminator review: `python tools/build_audio_ff_terminator_review.py` then `python tools/validate_audio_ff_terminator_review.py`.",
            "- eb-decompile audio reference alignment: `python tools/build_audio_ebdecompile_ref_alignment.py` then `python tools/validate_audio_ebdecompile_ref_alignment.py`.",
            "- audio oracle comparison plan: `python tools/build_audio_oracle_comparison_plan.py` then `python tools/validate_audio_oracle_comparison_plan.py`.",
            "- all-track oracle comparison plan: `python tools/build_audio_oracle_comparison_plan.py --all-tracks --json manifests/audio-oracle-comparison-plan-all-tracks.json --markdown notes/audio-oracle-comparison-plan-all-tracks.md` then `python tools/validate_audio_oracle_comparison_plan.py manifests/audio-oracle-comparison-plan-all-tracks.json`.",
            "- import one reference capture: `python tools/import_audio_oracle_reference_capture.py --track-id 46 --spc <capture.spc> --wav <capture.wav> --oracle-id <emulator>`.",
            "- oracle comparator self-check: `python tools/populate_audio_oracle_self_reference.py --overwrite` then `python tools/collect_audio_oracle_comparison_results.py` and `python tools/validate_audio_oracle_comparison_summary.py --require-compared`.",
            "- import backend-result references: `python tools/import_audio_oracle_references_from_backend_summary.py --summary <snes_spc-result-summary.json> --oracle-id <name> --overwrite`.",
            "- audio oracle comparison collector: `python tools/collect_audio_oracle_comparison_results.py` then `python tools/validate_audio_oracle_comparison_summary.py`.",
            "- audio oracle verification report: `python tools/build_audio_oracle_verification_report.py` then `python tools/validate_audio_oracle_verification_report.py --require-representative-pass`.",
            "- all-track audio oracle verification report: `python tools/build_audio_oracle_verification_report.py --summary build/audio/oracle-comparison-all-tracks/oracle-comparison-summary.json --json manifests/audio-oracle-verification-report-all-tracks.json --markdown notes/audio-oracle-verification-report-all-tracks.md` then `python tools/validate_audio_oracle_verification_report.py manifests/audio-oracle-verification-report-all-tracks.json --require-representative-pass`.",
            "- audio dependency policy: `python tools/build_audio_dependency_policy.py` then `python tools/validate_audio_dependency_policy.py`.",
            "- local ares prerequisite check: `python tools/check_ares_backend_prereq.py`.",
            "- ares link smoke: `cmake -S tools/ares_link_smoke -B build/audio/ares-link-smoke-msvc -G \"Visual Studio 17 2022\" -DARES_ROOT=<local-ares-checkout>` then `cmake --build build/audio/ares-link-smoke-msvc --config RelWithDebInfo`.",
            "- ares audio harness build: `cmake -S tools/ares_audio_harness -B build/audio/ares-audio-harness-msvc -G \"Visual Studio 17 2022\" -DARES_ROOT=<local-ares-checkout>` then `cmake --build build/audio/ares-audio-harness-msvc --config RelWithDebInfo`.",
            "",
            "## Native ares Harness",
            "",
            f"- source: `{contract['native_ares_harness']['source']}`",
            f"- executable: `{contract['native_ares_harness']['executable']}`",
            f"- current capability: {contract['native_ares_harness']['current_capability']}",
            f"- current result status: `{contract['native_ares_harness']['current_result_status']}`",
            f"- not `ok` yet because: {contract['native_ares_harness']['why_not_ok_yet']}",
            "- current ONETT entry probe begins `clp`, `ldx #$cf`, `txs`, clears direct-page RAM through `$00DF`, then `jsr $16a5`.",
            "- current ONETT execution probe uses a rough timer0 progress shim plus diagnostic APUIO0 command `0x2E`, escapes the old `$0579/$057C` timer wait, reaches track-specific driver update code, and records `5729` APU IO reads, `5019` APU IO writes, `2402` DSP writes, and `288` `$FD` timer-output reads under the 200,000-instruction diagnostic limit.",
            "- each native ares result now includes a schema-valid diagnostic `complete_spc_snapshot` generated from the probe's APU RAM, SPC700 registers, and DSP registers.",
            "- the current corpus boundary is now full scheduler/render fidelity, not pack loading, timer wait, command recognition, or SPC container shape: all 20 representative jobs validate, reach track-specific PCs/counts, emit diagnostic SPC snapshots, and still return `unsupported` until the harness drives a real track-start command/render boundary.",
            "- current capture metrics show `20 / 20` tracks issue DSP key-on writes during the probe, while final diagnostic SPC headers still have `KON=$00`; the harness now also writes real last-key-on snapshots at `diagnostic-last-keyon-state.spc`.",
            "- runtime frontier validation now also confirms `20 / 20` diagnostic command injections, `20 / 20` command first reads, all command reads after injection, and all last-key-on snapshots after the command read.",
            "- no-command negative-control result: with diagnostic APUIO0 preseed disabled, `20 / 20` captures still validate, all stop at final PC `$055A`, and `0 / 20` reach DSP key-on; this pins the CPU/APU track-start command as the gate to audible state.",
            "- command-timing result: injecting the diagnostic APUIO0 track command exactly when the driver first reads port 0 still yields `20 / 20` valid captures, `20 / 20` key-on events after command read, and `20 / 20` audible libgme renders; compared with the earlier last-key-on corpus, all `20` tracks are unchanged and `0` worsen.",
            "- mailbox frontier result: the command-window transcript now validates `20 / 20` command reads at APUIO0, `20 / 20` command bytes matching track ids, `20 / 20` immediate zero APUIO0 acknowledgement writes, and `20 / 20` key-on-after-command-read ordering.",
            "- ares SMP mailbox result: timed delivery through real `ares::SuperFamicom::smp.portWrite` at `$062A` reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks; the generated key-on SPC snapshots render `20 / 20` audible tracks through libgme, are unchanged versus the custom last-key-on render corpus, and improve all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- CPU-side writeAPU result: timed delivery through `ares::SuperFamicom::cpu.writeAPU($2140, track)` at `$062A` reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks; the generated key-on SPC snapshots render `20 / 20` audible tracks through libgme, are unchanged versus direct `smp.portWrite`, and improve all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- WDC65816 instruction result: executing the modeled C0:ABBD `sep #$20; sta.l $002140` prefix at `$062A` writes exactly once to `$2140` for `20 / 20` representative tracks, reaches command read, zero acknowledgement, and key-on, renders `20 / 20` audible tracks through libgme, is unchanged versus CPU-side `writeAPU`, and improves all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- full C0:ABBD result: executing modeled WDC65816 bytes for `sep #$20; sta.l $002140; rep #$30; rtl` at `$062A` writes exactly once to `$2140` for `20 / 20` representative tracks, returns to the synthetic caller, reaches command read, zero acknowledgement, and key-on, renders `20 / 20` audible tracks through libgme, is unchanged versus the STA-prefix probe, and improves all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- ROM-derived C0:ABBD result: extracting bytes from the user-provided ROM proves the real opcode is `STA long $002140` (`E2 20 8F 40 21 00 C2 30 6B`), not absolute `STA $2140`; executing those bytes at `$062A` reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks, renders `20 / 20` audible tracks through libgme, is unchanged versus the modeled full routine, and improves all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- ROM-derived C0:ABBD JSL-call result: executing a modeled `JSL $C0ABBD` caller with ROM-derived C0:ABBD bytes mapped at their real CPU address returns through `RTL` to `$008004`, writes exactly once to `$2140`, reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks, renders `20 / 20` audible tracks through libgme, is unchanged versus direct ROM-derived C0:ABBD, and improves all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- CHANGE_MUSIC tail result: executing ROM-derived bytes for `C4:FD0E` (`LDY $10; TYA; INC; JSL C0:ABBD; PLD; RTL`) with direct-page `$10` seeded to the zero-based track index computes the one-based command, writes exactly once to `$2140`, returns through both `RTL`s to `$008004`, reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks, renders `20 / 20` audible tracks through libgme, is unchanged versus the ROM-derived C0:ABBD JSL-call corpus, and improves all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- full CHANGE_MUSIC result: executing ROM-derived bytes for `C4:FBBD..FD17` under a pre-satisfied pack state lets the real routine normalize the requested track, read the real ROM-derived `MusicDatasetTable`, skip already-satisfied pack loads, compute the one-based command, call ROM-derived C0:ABBD, return to `$008004`, reach command read, zero acknowledgement, and key-on for `20 / 20` representative tracks; the snapshots render `20 / 20` audible tracks through libgme, are unchanged versus the CHANGE_MUSIC tail corpus, and improve all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- full CHANGE_MUSIC load-path-stub result: executing ROM-derived bytes for `C4:FBBD..FD17` with current pack state intentionally unsatisfied makes the real routine run pack-decision branches, read ROM-derived `MusicDatasetTable` and `MusicPackPointerTable` fixtures, call a stubbed `LOAD_SPC700_DATA` for each required pack, compute the one-based command, call ROM-derived C0:ABBD, return to `$008004`, reach command read, zero acknowledgement, and key-on for `20 / 20` representative tracks; loader metrics show `0` mismatches against the ROM tables with call-count distribution `2:2, 3:18`, the snapshots render `20 / 20` audible tracks through libgme, are unchanged versus the pre-satisfied full CHANGE_MUSIC corpus, and improve all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- semantic LOAD_SPC700_DATA transfer result: replaying the cold-start pack streams selected by the contract reproduces the existing APU RAM corpus for `20 / 20` representative tracks, and the CHANGE_MUSIC load-stub A/X call arguments match each track's table-derived pack order for `20 / 20`; destination-role coverage is 156 high/sample payload blocks, 57 sequence/runtime-table blocks, 34 music-sequence/sample-directory blocks, and 21 driver/overlay blocks.",
            "- C0:AB06 loader contract result: the ROM-derived `C0:AB06..ABA7` loader fixture is byte-checked with SHA-1 `e0cfb01348233939a0c4d98c42a0d8350f0ce6d9`; its selected streams match the load-apply probe for `20 / 20` jobs, covering 58 streams, 188 payload blocks, and 531593 bytes with 0 mismatches.",
            "- C0:AB06 byte-handshake result: executing the ROM-derived loader fixture through ares' WDC65816 core against a modeled APUIO receiver validates all `58 / 58` selected stream occurrences and executes `33` unique pack streams, matching expected payload-byte, payload-write, block-token, terminal-token, return-PC, per-block final-region hash, and full 64 KiB APU RAM reconstruction evidence.",
            "- C0:AB06 real-IPL receiver result: executing the ROM-derived loader fixture through ares' WDC65816 core against the real ares SMP IPL receiver validates payload-region equality for `33 / 33` unique selected pack streams; pack 1 also completes the terminal handoff and returns the CPU loader to `$008004`.",
            "- C0:AB06 post-bootstrap reload result: booting pack 1 through the real ares SMP IPL receiver and then loading later target packs through the running game driver validates payload-region equality for `32 / 32` non-bootstrap selected unique pack streams.",
            "- C0:AB06 continuous track-load result: booting pack 1 once and then loading each representative track's full selected pack sequence through the running driver validates stable payload-region equality for `20 / 20` tracks; mutable live driver/overlay regions are explicitly identified instead of treated as static payload.",
            "- CHANGE_MUSIC-to-continuous-load contract result: real `CHANGE_MUSIC` load-stub call order, byte-checked C0:AB06 loader-contract stream order, and continuous real-driver C0:AB06 sequence order match for `20 / 20` representative tracks.",
            "- full CHANGE_MUSIC/real-C0:AB06 fusion result: booting pack 1 through the real IPL, executing full ROM-derived `CHANGE_MUSIC`, letting its real `JSL C0:AB06` calls stream through the running game driver, then sending the final C0:ABBD track command validates `20 / 20` representative runs and `20 / 20` stable payload-region matches.",
            "- fused CHANGE_MUSIC/C0:AB06 render result: the fusion frontier now emits `20 / 20` valid key-on SPC snapshots, libgme renders `20 / 20` backend jobs successfully, and render metrics classify `20 / 20` as audible.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 result: the broad corpus validates `191 / 191` load paths and `191 / 191` stable payload-region matches; `190 / 191` entries reach key-on and emit snapshots, with track `4` (`NONE2`) explicitly classified as load-ok/no-key-on.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 render result: the all-track snapshot-backed corpus renders `190 / 190` libgme backend jobs successfully, validates `190 / 190` results, and classifies `190 / 190` renders as audible; the only non-rendered table entry remains the intentional `NONE2` no-key-on case.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 timing result: the final C0:ABBD command write now uses `0` immediate SMP burst instructions; across `191 / 191` load paths, command-read/zero-ack occurs after `4055..8240` observed SMP instructions and the `190` key-on tracks reach key-on after `22245..134926` further observed SMP instructions.",
            "- all-track playback/export manifest result: the local handoff validates `190` rendered tracks, `190` audible classifications, and `1` skipped table entry (`NONE2`) with ROM-derived SPC/WAV outputs kept under ignored `build/audio`.",
            "- audio export duration policy result: exact finite lengths and loop points are now a first-class release gate; current `30` second WAVs are explicitly diagnostic previews until sequence/runtime duration evidence is measured per track.",
            "- audio export duration measurement result: the current diagnostic preview corpus measures `190` rendered WAVs, observes sustained-tail-silence finite-end candidates for `20` name-based finite tracks, leaves `9` finite-name candidates active through the 30-second preview, and keeps release exact-length readiness at `0` until sequence/runtime or oracle evidence confirms the boundaries.",
            "- audio export plan result: public/export behavior is now machine-readable for `192` table entries: `20` finite trim candidates, `63` loop-or-held preview candidates, `27` finite/transition review candidates, `80` unknown active previews, `1` no-audio skip, and `1` unmeasured entry; the nine finite-name candidates that stayed active at 30 seconds also stayed active through a targeted 120-second probe.",
            "- audio sequence semantics frontier result: the next exact-duration lane is now bounded as `119` sequence packs and `170` payload blocks, with pointer-prefix candidates and all `32` high-byte command candidates inventoried for driver-backed opcode naming.",
            "- audio sequence control-flow frontier result: `102` sequence packs contain `2281` EF/FD/FE/FF candidates after pointer-table exclusion; `EF` has `2045 / 2057` same-block next-word pointer operands, while `FD`, `FE`, and `FF` remain dispatch/sequence-walker questions rather than promoted exact-loop/end commands.",
            "- audio sequence walk frontier result: a provisional pointer-root walker covers `119` sequence packs, records `2007` EF call edges, reaches `159` FF terminator candidates, and narrows unpromoted exact-duration blockers to `8` FD and `34` FE encounters plus `15` tracked EF-like out-of-block uncertainties under the provisional width table.",
            "- audio exact-duration triage result: the `119` walked sequence packs now split into `92` FF-terminator review candidates, `22` FD/FE-blocked packs, `4` loop/fallthrough semantics packs, and `1` no-action pack; pack `25` remains FE-blocked despite strong EF and reference evidence.",
            "- audio FF terminator review result: the no-FD/FE FF lane now covers `92` candidate packs and `123` tracks, splitting them into `2` existing finite-trim confirmation packs, `7` finite/transition review packs, `34` loop-metadata packs, `47` dispatch-only packs, and `2` fallthrough-root packs pending SPC700 FF dispatch corroboration.",
            "- eb-decompile audio reference alignment result: `169 / 171` direct extracted `.ebm` song files match this project's contract blocks by payload hash, count, destination, and sequence pack; the two unmatched direct files are both pack 1 Gas Station sub-song/runtime cases, alongside `15` in-engine entries and `5` song-reference entries that need sub-song/reuse handling.",
            "- audio oracle comparison plan result: the first oracle gate is pinned as `20` representative jobs with source SPC/WAV evidence, ignored reference-capture output locations, SPC/header/RAM/DSP/PCM comparison levels, and promotion criteria for an all-track run.",
            "- all-track oracle comparison plan result: the next oracle gate is staged as a separate `190` job plan at `manifests/audio-oracle-comparison-plan-all-tracks.json`, preserving the imported representative references while giving the full playback corpus a ready comparison contract.",
            "- audio oracle comparison collector result: the ares-managed full CHANGE_MUSIC/load-apply near-oracle captures classify `20 / 20` representative jobs as `audio_equivalent_state_delta`: PCM output matches exactly with zero offset, header/DSP state matches, and full APU RAM differs only outside the current audio-equivalence gate.",
            "- audio oracle verification report result: the representative near-oracle gate passes with `20 / 20` byte-exact WAV matches, `20 / 20` header/DSP register matches, `20 / 20` sequence/sample-region matches, and `0 / 20` full-APU-RAM matches; release-quality playback remains unclaimed until independent external-emulator and all-track oracle gates pass.",
            "- all-track audio oracle verification result: the all-track near-oracle gate passes with `190 / 190` byte-exact WAV matches, `190 / 190` header/DSP register matches, `190 / 190` sequence/sample-region matches, and `0 / 190` full-APU-RAM matches; release-quality playback remains unclaimed only because the independent external-emulator gate is still open.",
            "- audio oracle self-reference result: copying current fused playback/export artifacts into the planned reference slots validates the comparator fast path and exact-match logic with `20 / 20` representative jobs classified as `pass`.",
            "- audio dependency policy result: ares (`6f6786e0`) remains the permissive accuracy-first external checkout, libgme (`dd3182a8`) remains the LGPL snapshot renderer path, and GPL/reference emulators remain optional out-of-process oracles rather than core dependencies.",
            "- full CHANGE_MUSIC load-apply result: starting from bootstrap-only APU RAM, executing ROM-derived `CHANGE_MUSIC` with real pack-decision branches applies 58 selected LOAD_SPC700_DATA streams, 188 payload blocks, and 531593 bytes into ares APU RAM with 0 apply errors, then sends the track command, reaches command read, zero acknowledgement, and key-on for `20 / 20` representative tracks; snapshots render `20 / 20` audible, are unchanged versus the load-stub corpus, and improve all `20` tracks versus baseline final-state diagnostic snapshots.",
            "- key-on priming experiment result: setting diagnostic SPC `KON` to the last observed key-on byte and clearing `KOF` improves `14` tracks, leaves `6` unchanged, and worsens `0`; render classes move from `12` silent / `3` trace / `5` very quiet / `0` audible to `3` silent / `1` trace / `3` very quiet / `13` audible.",
            "- real last-key-on snapshot experiment result: `20 / 20` snapshots validate and render as audible through libgme; compared with the baseline diagnostic snapshots, all `20` tracks improve and none worsen; compared with the non-faithful key-on priming experiment, `7` improve, `13` are unchanged, and `0` worsen.",
            "",
            "## libgme / snes_spc Harness",
            "",
            f"- source: `{contract['libgme_harness']['source']}`",
            f"- external checkout: `{contract['libgme_harness']['external_checkout']}`",
            f"- observed commit: `{contract['libgme_harness']['observed_commit']}`",
            f"- executable: `{contract['libgme_harness']['executable']}`",
            f"- linked library: `{contract['libgme_harness']['linked_library']}`",
            f"- current capability: {contract['libgme_harness']['current_capability']}",
            f"- current result status: `{contract['libgme_harness']['current_result_status']}`",
            f"- not final because: {contract['libgme_harness']['why_not_final']}",
            "- current representative corpus result: `20 / 20` snes_spc jobs render valid diagnostic WAV outputs through libgme.",
            "- current render-quality baseline: `12` silent, `3` click/trace, `5` very quiet, `0` confidently audible. This confirms the renderer path works but the diagnostic source snapshots are not a musically useful capture boundary yet.",
            "- last-key-on source snapshots render `20 / 20` tracks as audible through the same libgme harness, proving that source capture timing/state, not WAV renderer plumbing, was the limiting factor for the baseline corpus.",
            "- ares SMP mailbox snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the last-key-on result while replacing the custom CPU input shortcut with real ares SMP mailbox delivery at the command-read boundary.",
            "- CPU-side writeAPU snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the SMP mailbox result while moving command delivery to the CPU-facing `$2140` bridge.",
            "- modeled WDC65816 STA $2140 snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the CPU writeAPU result while proving the command can be delivered by decoded 65816 write semantics from C0:ABBD's prefix.",
            "- modeled full C0:ABBD snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the STA-prefix result while proving the whole tiny sender routine can execute in the probe.",
            "- ROM-derived C0:ABBD snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the modeled full routine result while verifying the executable bytes against the supplied ROM.",
            "- ROM-derived C0:ABBD JSL-call snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the direct ROM-derived result while replacing the fake preloaded return address with a real JSL/RTL stack round trip.",
            "- CHANGE_MUSIC tail snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the C0:ABBD JSL-call result while moving command computation back into the real `CHANGE_MUSIC` tail instructions.",
            "- full CHANGE_MUSIC pre-satisfied-pack snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the tail result while moving command computation and branch flow back to the start of the real `CHANGE_MUSIC` body.",
            "- full CHANGE_MUSIC load-path-stub snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the pre-satisfied result while replacing the pack-current shortcut with real pack-decision branches and table-derived loader-call arguments.",
            "- full CHANGE_MUSIC load-apply snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the load-stub result while replacing prebuilt track APU RAM with bootstrap APU RAM plus semantic stream application from ROM bytes.",
            "- fused CHANGE_MUSIC/C0:AB06 snapshots also render `20 / 20` tracks as audible through the same libgme harness, keeping the load-apply result while replacing semantic stream application with real C0:AB06 loader execution against the live driver.",
            "- all-track fused CHANGE_MUSIC/C0:AB06 snapshots render `190 / 190` snapshot-backed tracks as audible through the same libgme harness; track `4` (`NONE2`) remains load-ok/no-key-on and is skipped by the render job builder.",
            "",
            "## Result Schema",
            "",
            f"- schema: `{contract['result_schema']['schema']}`",
            f"- required fields: `{contract['result_schema']['required_fields']}`",
            f"- status values: `{contract['result_schema']['status_values']}`",
            f"- output record fields: `{contract['result_schema']['output_record_fields']}`",
            f"- output validation: `{contract['result_schema']['output_validation']}`",
            "- successful results must include diagnostics for `execution_mode`, `handshake_policy`, and `timing_basis`.",
            "- dry-run plumbing check: `python tools/build_audio_backend_result_stub.py --job-id ares-track-046-onett`.",
            "- validate one result with `python tools/validate_audio_backend_result.py <result.json> --job build/audio/backend-jobs/ares-jobs.json`.",
            "- summarize corpus results with `python tools/collect_audio_backend_results.py`.",
            "- validate the collected summary with `python tools/validate_audio_backend_result_summary.py`.",
            "",
            "## Backend Catalog",
            "",
            "| Backend | License policy | Execution policy | Implemented | Stage |",
            "| --- | --- | --- | --- | --- |",
            *backend_rows,
            "",
        ]
    )


def main() -> int:
    args = parse_args()
    contract = build_contract()
    json_path = Path(args.json)
    markdown_path = Path(args.markdown)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(contract), encoding="utf-8")
    print(f"Built audio backend contract -> {json_path}")
    print(f"Wrote {markdown_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
