; EarthBound D3 asset SPRITE_0555.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:96C0..D3:9780 AssetSprite0555

; ---------------------------------------------------------------------------
; D3:9780

; AssetSprite0555End
D39780_AssetSprite0555End:
