; EarthBound D3 asset SPRITE_0613.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:C240..D3:C300 AssetSprite0613

; ---------------------------------------------------------------------------
; D3:C300

; AssetSprite0613End
D3C300_AssetSprite0613End:
