; EarthBound D3 asset SPRITE_0552.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:9480..D3:9540 AssetSprite0552

; ---------------------------------------------------------------------------
; D3:9540

; AssetSprite0552End
D39540_AssetSprite0552End:
