; EarthBound D3 asset SPRITE_0567.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d3-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D3:9FC0..D3:A080 AssetSprite0567

; ---------------------------------------------------------------------------
; D3:A080

; AssetSprite0567End
D3A080_AssetSprite0567End:
