; EarthBound DA asset MAP_DATA_PALETTE_1.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/da-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - DA:7FA7..DA:81E7 AssetMapDataPalette1

; ---------------------------------------------------------------------------
; DA:81E7

; AssetMapDataPalette1End
DA81E7_AssetMapDataPalette1End:
