; EarthBound DA asset MAP_DATA_PALETTE_30.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/da-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - DA:F267..DA:F4A7 AssetMapDataPalette30

; ---------------------------------------------------------------------------
; DA:F4A7

; AssetMapDataPalette30End
DAF4A7_AssetMapDataPalette30End:
