; EarthBound DA asset MAP_DATA_PALETTE_11.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/da-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - DA:9CE7..DA:A2E7 AssetMapDataPalette11

; ---------------------------------------------------------------------------
; DA:A2E7

; AssetMapDataPalette11End
DAA2E7_AssetMapDataPalette11End:
