; EarthBound D2 asset SPRITE_0321.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:E780..D2:E840 AssetSprite0321

; ---------------------------------------------------------------------------
; D2:E840

; AssetSprite0321End
D2E840_AssetSprite0321End:
