; EarthBound D2 asset SPRITE_0215.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:7F40..D2:8000 AssetSprite0215

; ---------------------------------------------------------------------------
; D2:8000

; AssetSprite0215End
D28000_AssetSprite0215End:
