; EarthBound D2 asset SPRITE_0147.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:1200..D2:1680 AssetSprite0147

; ---------------------------------------------------------------------------
; D2:1680

; AssetSprite0147End
D21680_AssetSprite0147End:
