; EarthBound D2 asset SPRITE_0319.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:E600..D2:E6C0 AssetSprite0319

; ---------------------------------------------------------------------------
; D2:E6C0

; AssetSprite0319End
D2E6C0_AssetSprite0319End:
