; EarthBound D2 asset SPRITE_0167.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d2-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D2:3700..D2:3900 AssetSprite0167

; ---------------------------------------------------------------------------
; D2:3900

; AssetSprite0167End
D23900_AssetSprite0167End:
