; EarthBound ED asset AUDIO_PACK_19.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/ed-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - ED:CF55..ED:D539 AssetAudioPack19

; ---------------------------------------------------------------------------
; ED:D539

; AssetAudioPack19End
EDD539_AssetAudioPack19End:
