; EarthBound C0 Refresh Post Transition Entity Placement.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:3FA9..C0:402B Refresh_PostTransitionEntityPlacement

; ---------------------------------------------------------------------------
; External contracts used by this module

C07B52_RebuildPartyRecordsOrEntityState = $C07B52
C21628_CheckEventFlag                   = $C21628

; ---------------------------------------------------------------------------
; C0:3FA9

C03FA9_Refresh_PostTransitionEntityPlacement:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sty $02
    sta $0E
    sta $9877
    stx $987B
    lda $02
    sta $987F
    ldy $9889
    lda $0E
    jsl $C05F33
    sta $9881
    lda $02
    jsl $C03A94
    jsl $C03F1E
    lda.w #$0000
    sta $0E
    bra C03FEC_Refresh_PostTransitionEntityPlacement_L3FEC
C03FDF_Refresh_PostTransitionEntityPlacement_L3FDF:
    asl A
    tax
    lda.w #$FFFF
    sta $3486,X
    lda $0E
    inc A
    sta $0E
C03FEC_Refresh_PostTransitionEntityPlacement_L3FEC:
    cmp.w #$0006
    bcc C03FDF_Refresh_PostTransitionEntityPlacement_L3FDF
    lda.w #$FFFF
    sta $9F6B
    stz $438C
    stz $438A
    lda $C30186
    jsl C21628_CheckEventFlag
    sta $9F71
    jsl C07B52_RebuildPartyRecordsOrEntityState
    pld
    rtl
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sta $0E
    txa
    sec
    sbc.w #$0070
    tax
    lda $0E
    sec
    sbc.w #$0080
    jsr $1558
    pld
    rtl
