; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:3E5A..C0:3E9D Get_PreviousRegistryObjectOrderByte
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:3E5A

C03E5A_Get_PreviousRegistryObjectOrderByte:

; ---------------------------------------------------------------------------
; C0:3E9D

C03E9D_Get_PreviousRegistryObjectOrderByte_End:
