; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_5503_or_collision_horizontal_edge_a.asm

hirom
org $C05503

C05503_OR_CollisionHorizontalEdgeA:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEA
    tcd
    pla
    tay
    lda $5DA4
    sta $14
    txa
    asl A
    tax
    lda $C42AA7,X
    sta $12
    lda $5DAE
    lsr A
    lsr A
    lsr A
    sta $04
    tya
    lsr A
    lsr A
    lsr A
    and.w #$003F
    sta $02
    lda $04
    and.w #$003F
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    lda $E000,X
    and.w #$00FF
    sta $02
    lda $14
    ora $02
    sta $02
    sta $10
    tya
    clc
    adc.w #$0007
    lsr A
    lsr A
    lsr A
    tax
    stx $14
    lda.w #$0000
    sta $0E
    bra C05591_OR_CollisionHorizontalEdgeA_L5591
C0555E_OR_CollisionHorizontalEdgeA_L555E:
    txa
    and.w #$003F
    sta $02
    lda $04
    and.w #$003F
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    lda $E000,X
    and.w #$00FF
    pha
    lda $10
    sta $02
    ply
    sty $02
    ora $02
    sta $02
    sta $10
    ldx $14
    inx
    stx $14
    lda $0E
    inc A
    sta $0E
C05591_OR_CollisionHorizontalEdgeA_L5591:
    cmp $12
    bcc C0555E_OR_CollisionHorizontalEdgeA_L555E
    lda $02
    sta $5DA4
    pld
    rts
