; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_5639_or_collision_vertical_edge_a.asm

hirom
org $C05639

C05639_OR_CollisionVerticalEdgeA:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEA
    tcd
    pla
    tay
    txa
    asl A
    tax
    lda $C42AC9,X
    sta $14
    lda $5DA4
    sta $12
    lda $5DAC
    lsr A
    lsr A
    lsr A
    sta $04
    and.w #$003F
    sta $02
    tya
    lsr A
    lsr A
    lsr A
    and.w #$003F
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    lda $E000,X
    and.w #$00FF
    sta $02
    lda $12
    ora $02
    sta $02
    sta $10
    tya
    clc
    adc.w #$0007
    lsr A
    lsr A
    lsr A
    tax
    stx $12
    lda.w #$0000
    sta $0E
    bra C056C5_OR_CollisionVerticalEdgeA_L56C5
C05692_OR_CollisionVerticalEdgeA_L5692:
    lda $04
    and.w #$003F
    sta $02
    txa
    and.w #$003F
    asl A
    asl A
    asl A
    asl A
    asl A
    asl A
    clc
    adc $02
    tax
    lda $E000,X
    and.w #$00FF
    pha
    lda $10
    sta $02
    ply
    sty $02
    ora $02
    sta $02
    sta $10
    ldx $12
    inx
    stx $12
    lda $0E
    inc A
    sta $0E
C056C5_OR_CollisionVerticalEdgeA_L56C5:
    cmp $14
    bcc C05692_OR_CollisionVerticalEdgeA_L5692
    lda $02
    sta $5DA4
    pld
    rts
