; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:6E6E..C0:6F68 MovementTriggerType3_QueueOffsetStep
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:6E6E

C06E6E_MovementTriggerType3_QueueOffsetStep:

; ---------------------------------------------------------------------------
; C0:6F68

C06F68_MovementTriggerType3_QueueOffsetStep_End:
