; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_6a8e_movement_trigger_type6_no_op.asm

hirom
org $C06A8E

C06A8E_MovementTriggerType6_NoOp:
    rep #$31
    rts
