; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_6f68_arm_staged_movement_timer_from_table48_d58.asm

hirom
org $C06F68

C06F68_Arm_StagedMovementTimerFromTable48D58:
    jsl $C0DBE6
    jsl $C48E95
    lda $04
    sta $5DD0
    lda $12
    sta $5DD2
    lda.w #$FFFF
    sta $5DC4
    pld
    rts
