; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_8dde_update_bg2_screen_base_registers_from_queue.asm

hirom
org $C08DDE

SET_BG2_VRAM_LOCATION:
!C08DDE_Update_Bg2ScreenBaseRegistersFromQueue = SET_BG2_VRAM_LOCATION
    php
    sep #$20
    rep #$10
    and.b #$03
    sta $0012
    rep #$20
    txa
    xba
    sep #$20
    and.b #$FC
    ora $0012
    sta $0012
    sta $002108
    lda $0015
    and.b #$0F
    sta $0015
    rep #$20
    stz $0035
    stz $0037
    tya
    xba
    sep #$20
    and.b #$F0
    ora $0015
    sta $0015
    sta $00210B
    plp
    rtl
