; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_8c54_enqueue_display_record_far_wrapper.asm

hirom
org $C08C54

REDIRECT_C08C58:
!C08C54_Enqueue_DisplayRecord_FarWrapper = REDIRECT_C08C58
    jsr $8C58
    rtl
