; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:886C..C0:887A Set_DisplayWaitCounter
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:886C

C0886C_Set_DisplayWaitCounter:

; ---------------------------------------------------------------------------
; C0:887A

C0887A_Set_DisplayWaitCounter_End:
