; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:9032..C0:915B Multiply16By16_ViaHardwareRegisters
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:9032

C09032_Multiply16By16_ViaHardwareRegisters:

; ---------------------------------------------------------------------------
; C0:915B

C0915B_Multiply16By16_ViaHardwareRegisters_End:
