; EarthBound C0 Restore Task Record Chain.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:9C99..C0:9CD7 Restore_TaskRecordChain

; ---------------------------------------------------------------------------
; External contracts used by this module

; Restores the task-record chain owned by slot X to the free-record list rooted
; at `$0A54`. The local C0:9CB5 helper below finds a slot predecessor in the
; active chain.

; ---------------------------------------------------------------------------
; C0:9C99

C09C99_Restore_TaskRecordChain:
    lda $0ADA,X
    bmi C09CB4_Restore_TaskRecordChain_L9CB4
    phx
    lda $0A54
    pha
    lda $0ADA,X
    ; Slot-owned record chain becomes the new free-record head.
    sta $0A54
C09CA9_Restore_TaskRecordChain_L9CA9:
    tax
    lda $125A,X
    bpl C09CA9_Restore_TaskRecordChain_L9CA9
    pla
    ; Link old free-record head to the tail of the restored chain.
    sta $125A,X
    plx
C09CB4_Restore_TaskRecordChain_L9CB4:
    rts
    rep #$20
    phd
    pha
    tdc
    sec
    sbc.w #$0002
    tcd
    pla
    stx $00
    ldy.w #$FFFF
    ldx $0A50
C09CC8_Restore_TaskRecordChain_L9CC8:
    cpx $00
    beq C09CD3_Restore_TaskRecordChain_L9CD3
    txy
    lda $0A9E,X
    tax
    bra C09CC8_Restore_TaskRecordChain_L9CC8
C09CD3_Restore_TaskRecordChain_L9CD3:
    ldx $00
    pld
    rts
