; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_9cd7_compact_task_slot_free_list.asm

hirom
org $C09CD7

C09CD7_Compact_TaskSlotFreeList:
    lda.w #$8000
    ldx $0A52
    bra C09CE6_Compact_TaskSlotFreeList_L9CE6
C09CDF_Compact_TaskSlotFreeList_L9CDF:
    ldy $0A9E,X
    sta $0A9E,X
    tyx
C09CE6_Compact_TaskSlotFreeList_L9CE6:
    bpl C09CDF_Compact_TaskSlotFreeList_L9CDF
    ldx.w #$003A
    ldy.w #$FFFF
C09CEE_Compact_TaskSlotFreeList_L9CEE:
    lda $0A9E,X
    cmp.w #$8000
    bne C09CFB_Compact_TaskSlotFreeList_L9CFB
    tya
    sta $0A9E,X
    txy
C09CFB_Compact_TaskSlotFreeList_L9CFB:
    dex
    dex
    bpl C09CEE_Compact_TaskSlotFreeList_L9CEE
    sty $0A52
    rtl
