; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:9B91..C0:9BA9 ScriptOp_LoadScratchFromEntityVar
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:9B91

C09B91_ScriptOp_LoadScratchFromEntityVar:

; ---------------------------------------------------------------------------
; C0:9BA9

C09BA9_ScriptOp_LoadScratchFromEntityVar_End:
