; EarthBound C0 Script Op Install Task Callback11 E2.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:9BE4..C0:9BEE ScriptOp_InstallTaskCallback11E2

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:9BE4

C09BE4_ScriptOp_InstallTaskCallback11E2:
    lda [$80],Y
    ldx $88
    sta $11E2,X
    iny
    iny
    rts
