; EarthBound C0 Compact Task Slot Free List.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:9CD7..C0:9D03 Compact_TaskSlotFreeList

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:9CD7

C09CD7_Compact_TaskSlotFreeList:
    lda.w #$8000
    ldx $0A52
    bra C09CE6_Compact_TaskSlotFreeList_L9CE6
C09CDF_Compact_TaskSlotFreeList_L9CDF:
    ldy $0A9E,X
    sta $0A9E,X
    tyx
C09CE6_Compact_TaskSlotFreeList_L9CE6:
    bpl C09CDF_Compact_TaskSlotFreeList_L9CDF
    ldx.w #$003A
    ldy.w #$FFFF
C09CEE_Compact_TaskSlotFreeList_L9CEE:
    lda $0A9E,X
    cmp.w #$8000
    bne C09CFB_Compact_TaskSlotFreeList_L9CFB
    tya
    sta $0A9E,X
    txy
C09CFB_Compact_TaskSlotFreeList_L9CFB:
    dex
    dex
    bpl C09CEE_Compact_TaskSlotFreeList_L9CEE
    sty $0A52
    rtl
