; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:9F43..C0:9F71 Freeze_AllActiveTasksExceptA
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:9F43

C09F43_Freeze_AllActiveTasksExceptA:

; ---------------------------------------------------------------------------
; C0:9F71

C09F71_Freeze_AllActiveTasksExceptA_End:
