; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_9d1f_unlink_task_record_from_slot_chain.asm

hirom
org $C09D1F

C09D1F_Unlink_TaskRecordFromSlotChain:
    phx
    jsr $9D3E
    lda $125A,Y
    cpx.w #$FFFF
    beq C09D31_Unlink_TaskRecordFromSlotChain_L9D31
    sta $125A,X
    plx
    bra C09D35_Unlink_TaskRecordFromSlotChain_L9D35
C09D31_Unlink_TaskRecordFromSlotChain_L9D31:
    plx
    sta $0ADA,X
C09D35_Unlink_TaskRecordFromSlotChain_L9D35:
    cpy $0A58
    bne C09D3D_Unlink_TaskRecordFromSlotChain_L9D3D
    sta $0A58
C09D3D_Unlink_TaskRecordFromSlotChain_L9D3D:
    rts
