; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_9b79_script_op_store_scratch_to_entity_var.asm

hirom
org $C09B79

MOVEMENT_CODE_1F:
!C09B79_ScriptOp_StoreScratchToEntityVar = MOVEMENT_CODE_1F
    lda [$80],Y
    and.w #$00FF
    asl A
    tax
    lda $C09AF9,X
    adc $88
    sta $8C
    ldx $8A
    lda $1516,X
    sta ($8C)
    iny
    rts
