; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_9ad3_script_op_mutate_target_add.asm

hirom
org $C09AD3

C09AD3_ScriptOp_MutateTarget_ADD:
    lda ($8C)
    clc
    adc $90
    sta ($8C)
    rts
