; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:9C57..C0:9C73 Link_TaskSlotIntoActiveList
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:9C57

C09C57_Link_TaskSlotIntoActiveList:

; ---------------------------------------------------------------------------
; C0:9C73

C09C73_Link_TaskSlotIntoActiveList_End:
