; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a87a_script_wrapper_c46_cf5_read_byte.asm

hirom
org $C0A87A

C0A87A_ScriptWrapper_C46CF5_ReadByte:
    jsl $C09D94
    pha
    sty $94
    jsl $C09D94
    sty $94
    plx
    jsl $C46CF5
    rtl
