; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_ac20_read_apu_port0_byte.asm

hirom
org $C0AC20

C0AC20_ReadApuPort0Byte:
    sep #$20
    lda $002140
    rep #$30
    and.w #$00FF
    rtl
    ora ($00,X)
    and ($04),Y
    brk #$00
    brk #$01
    brk #$31
    tsb $01
    brk #$00
