; EarthBound C0 Script Set Movement State CBD3.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A6AD..C0:A6B8 Script_SetMovementStateCBD3

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A6AD

C0A6AD_Script_SetMovementStateCBD3:
    jsl $C09D94
    sty $94
    jsl $C0CBD3
    rtl
