; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:A1CE..C0:A1D0 SelectPackedMapPropertyBits0
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:A1CE

C0A1CE_SelectPackedMapPropertyBits0:

; ---------------------------------------------------------------------------
; C0:A1D0

C0A1D0_SelectPackedMapPropertyBits0_End:
