; EarthBound C0 Select Packed Map Property Bits3.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A1D4..C0:A1F2 SelectPackedMapPropertyBits3

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A1D4

C0A1D4_SelectPackedMapPropertyBits3:
    and.w #$0003
    xba
    sta $08
    lda $C42F64,X
    sta $04
    lda $C42F66,X
    sta $06
    lda [$04],Y
    and.w #$00FF
    ora $08
    sta $288C
    pld
    rts
