; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:A1F2..C0:A20C Copy_MapBufferPageToWorkBuffer
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:A1F2

C0A1F2_Copy_MapBufferPageToWorkBuffer:

; ---------------------------------------------------------------------------
; C0:A20C

C0A20C_Copy_MapBufferPageToWorkBuffer_End:
