; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a912_action_script_prepare_new_entity.asm

hirom
org $C0A912

ACTIONSCRIPT_PREPARE_NEW_ENTITY:
!C0A912_ActionScript_PrepareNewEntity = ACTIONSCRIPT_PREPARE_NEW_ENTITY
    jsl $C09D94
    sty $94
    pha
    jsl $C09D94
    sty $94
    pha
    jsl $C09D86
    sty $94
    ply
    plx
    jsl $C46E37
    rtl
