; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_aaac_script_refresh_current_slot_visual_profile.asm

hirom
org $C0AAAC

C0AAAC_Script_RefreshCurrentSlotVisualProfile:
    ldx $88
    stx $2896
