; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a21c_find_active_task_by_field2_c9_a.asm

hirom
org $C0A21C

C0A21C_FindActiveTaskByField2C9A:
    ldy $0A50
    bmi C0A22C_FindActiveTaskByField2C9A_LA22C
C0A221_FindActiveTaskByField2C9A_LA221:
    tyx
    cmp $2C9A,X
    beq C0A22F_FindActiveTaskByField2C9A_LA22F
    ldy $0A9E,X
    bpl C0A221_FindActiveTaskByField2C9A_LA221
C0A22C_FindActiveTaskByField2C9A_LA22C:
    lda.w #$0000
C0A22F_FindActiveTaskByField2C9A_LA22F:
    rtl
