; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:AAFD..C0:AB06 Script_ClearFrameCountdown
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:AAFD

C0AAFD_Script_ClearFrameCountdown:

; ---------------------------------------------------------------------------
; C0:AB06

C0AB06_Script_ClearFrameCountdown_End:
