; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_aad1_return_x0004.asm

hirom
org $C0AAD1

C0AAD1_ReturnX0004:
    ldx.w #$0004
    rtl
