; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a8ff_action_script_prepare_new_entity_at_party_leader.asm

hirom
org $C0A8FF

ACTIONSCRIPT_PREPARE_NEW_ENTITY_AT_PARTY_LEADER:
!C0A8FF_ActionScript_PrepareNewEntityAtPartyLeader = ACTIONSCRIPT_PREPARE_NEW_ENTITY_AT_PARTY_LEADER
    lda.w #$0001
    jsl $C46DAD
    rtl
