; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:AD9F..C0:ADB2 WriteVramAddressFrom3B3C
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:AD9F

C0AD9F_WriteVramAddressFrom3B3C:

; ---------------------------------------------------------------------------
; C0:ADB2

C0ADB2_WriteVramAddressFrom3B3C_End:
