; EarthBound C0 Script Wrapper C46 BBB Read Word.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A938..C0:A943 ScriptWrapper_C46BBB_ReadWord

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A938

C0A938_ScriptWrapper_C46BBB_ReadWord:
    jsl $C09D94
    sty $94
    jsl $C46BBB
    rtl
