; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a0fa_draw_task_data_record_at_index.asm

hirom
org $C0A0FA

C0A0FA_Draw_TaskDataRecordAtIndex:
    asl A
    tay
    sep #$20
    lda $8E
    sta $000B
    rep #$20
    lda [$8C],Y
    sta $96
    lda $103E,X
    sta $2400
    ldy $0BCA,X
    lda $0B8E,X
    tax
    lda $96
    jmp $8C58
    rts
    sep #$20
    lda.b #$30
    sta $307FF0
    inc A
    sta $317FF0
    cmp $307FF0
    beq C0A13B_Draw_TaskDataRecordAtIndex_LA13B
    rep #$20
    pla
    tsc
    sbc.w #$0100
    tcd
    jml $C30100
C0A13B_Draw_TaskDataRecordAtIndex_LA13B:
    lda $00213F
    and.w #$F010
    tsb $20C2
    pla
    tsc
    sbc.w #$0100
    tcd
    jml $C30142
    rep #$20
    rtl
