; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_a92d_script_wrapper_c46_b8_d_read_word.asm

hirom
org $C0A92D

C0A92D_ScriptWrapper_C46B8D_ReadWord:
    jsl $C09D94
    sty $94
    jsl $C46B8D
    rtl
