; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:AE1D..C0:AE26 BattleBgDmaBbusRegisterTable
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:AE1D

C0AE1D_BattleBgDmaBbusRegisterTable:

; ---------------------------------------------------------------------------
; C0:AE26

C0AE26_BattleBgDmaBbusRegisterTable_End:
