; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:A4A8..C0:A4B2 RefreshCurrentSlotVisualProfile_Mode0IfAligned
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:A4A8

C0A4A8_RefreshCurrentSlotVisualProfile_Mode0IfAligned:

; ---------------------------------------------------------------------------
; C0:A4B2

C0A4B2_RefreshCurrentSlotVisualProfile_Mode0IfAligned_End:
