; EarthBound C0 Try Saved Coordinate Reload Landing.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:B967..C0:B9BC TrySavedCoordinateReloadLanding

; ---------------------------------------------------------------------------
; External contracts used by this module

C08756_WaitOneFrameAndPollInput = $C08756

; ---------------------------------------------------------------------------
; C0:B967

C0B967_TrySavedCoordinateReloadLanding:
    jsl $C4C718
    cmp.w #$0000
    beq C0B97A_TrySavedCoordinateReloadLanding_LB97A
    ldx.w #$0000
    lda.w #$0A20
    jsl $C08F68
C0B97A_TrySavedCoordinateReloadLanding_LB97A:
    lda $436C
    bne C0B982_TrySavedCoordinateReloadLanding_LB982
    jmp $B814
C0B982_TrySavedCoordinateReloadLanding_LB982:
    lda $0065
    and.w #$1000
    bne C0B98D_TrySavedCoordinateReloadLanding_LB98D
    jmp $B814
C0B98D_TrySavedCoordinateReloadLanding_LB98D:
    lda $0065
    and.w #$2000
    bne C0B998_TrySavedCoordinateReloadLanding_LB998
    jmp $B814
C0B998_TrySavedCoordinateReloadLanding_LB998:
    pld
    rtl
    rep #$31
    jsl $EF0B9E
    jsl $C4FB58
    jsl $C08715
    jsl $C0A11C
    jsl C08756_WaitOneFrameAndPollInput
    jsl C08756_WaitOneFrameAndPollInput
    stz $436C
    jsl $C0B7D8
    rts
