; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:C7AC..C0:C7DB RefreshCurrentSlotFootprintMaskFromCachedPosition
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:C7AC

C0C7AC_RefreshCurrentSlotFootprintMaskFromCachedPosition:

; ---------------------------------------------------------------------------
; C0:C7DB

C0C7DB_RefreshCurrentSlotFootprintMaskFromCachedPosition_End:
