; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:C363..C0:C3F9 GetPlayerDistanceBucketWide
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:C363

C0C363_GetPlayerDistanceBucketWide:

; ---------------------------------------------------------------------------
; C0:C3F9

C0C3F9_GetPlayerDistanceBucketWide_End:
