; EarthBound C0 Update Current Slot Footprint Mask With Height Offset.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:C808..C0:C83B UpdateCurrentSlotFootprintMaskWithHeightOffset

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:C808

C0C808_UpdateCurrentSlotFootprintMaskWithHeightOffset:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda $1A42
    sta $10
    asl A
    sta $02
    lda $10
    tay
    ldx $02
    lda $0BCA,X
    ldx $02
    sec
    sbc $0C06,X
    tax
    stx $0E
    ldx $02
    lda $0B8E,X
    ldx $0E
    jsl $C05F33
    ldx $02
    sta $2BAA,X
    pld
    rtl
