; EarthBound C0 Check Direction Adjusted Grid Alignment.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:C760..C0:C7AC CheckDirectionAdjustedGridAlignment

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:C760

C0C760_CheckDirectionAdjustedGridAlignment:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    stx $10
    sta $0E
    tya
    asl A
    tay
    tyx
    lda $0E
    sec
    sbc $C42A1F,X
    sta $02
    ldx $10
    txa
    tyx
    sec
    sbc $C42A41,X
    sta $0E
    ldx $10
    txa
    clc
    adc.w #$0008
    sta $04
    lda $0E
    pha
    lda $02
    ora $02
    ply
    sty $02
    ora $02
    ora $04
    and.w #$FF00
    beq C0C7A7_CheckDirectionAdjustedGridAlignment_LC7A7
    lda.w #$0000
    bra C0C7AA_CheckDirectionAdjustedGridAlignment_LC7AA
C0C7A7_CheckDirectionAdjustedGridAlignment_LC7A7:
    lda.w #$FFFF
C0C7AA_CheckDirectionAdjustedGridAlignment_LC7AA:
    pld
    rtl
