; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:D7F7..C0:D98F Consume_CurrentSlotAttentionPath
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:D7F7

C0D7F7_Consume_CurrentSlotAttentionPath:

; ---------------------------------------------------------------------------
; C0:D98F

C0D98F_Consume_CurrentSlotAttentionPath_End:
