; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c0/c0_d195_return_false_movement_predicate.asm

hirom
org $C0D195

C0D195_ReturnFalse_MovementPredicate:
    rep #$31
    lda.w #$0000
    rtl
