; EarthBound C0 Unfreeze Teleport Transition Objects.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:DE7C..C0:DED9 UnfreezeTeleportTransitionObjects

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:DE7C

C0DE7C_UnfreezeTeleportTransitionObjects:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$99CE
    sta $4DC6
    ldy.w #$0018
    bra C0DECE_UnfreezeTeleportTransitionObjects_LDECE
C0DE8F_UnfreezeTeleportTransitionObjects_LDE8F:
    tya
    asl A
    sta $0E
    tax
    lda.w #$0008
    sta $0F12,X
    lda $0E
    clc
    adc.w #$1002
    tax
    lda $0000,X
    and.w #$F7FF
    sta $0000,X
    lda $0E
    clc
    adc.w #$289E
    tax
    lda $0000,X
    and.w #$7FFF
    sta $0000,X
    lda.w #$FFFF
    ldx $4DC6
    sta $0037,X
    lda $4DC6
    clc
    adc.w #$005F
    sta $4DC6
    iny
C0DECE_UnfreezeTeleportTransitionObjects_LDECE:
    cpy.w #$001E
    bcc C0DE8F_UnfreezeTeleportTransitionObjects_LDE8F
    jsl $C069ED
    pld
    rts
