; EarthBound C0 Wait Frames With Intro Cancel.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:EFE1..C0:F1D2 WaitFramesWithIntroCancel

; ---------------------------------------------------------------------------
; External contracts used by this module

C08616_QueueVramTransfer_FromDpSource     = $C08616
C08756_WaitOneFrameAndPollInput           = $C08756
C08814_SetDisplayTransitionMode           = $C08814
C08EFC_CommitTileBufferToStaging          = $C08EFC
C08F15_ClearVramOrRendererBuffer          = $C08F15
C41A9E_GraphicsDecompressionRoutines_Main = $C41A9E
C496E7_StartPaletteFadeFromWorkBuffer     = $C496E7

; ---------------------------------------------------------------------------
; C0:EFE1

C0EFE1_WaitFramesWithIntroCancel:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sta $0E
    bra C0F002_WaitFramesWithIntroCancel_LF002
C0EFEF_WaitFramesWithIntroCancel_LEFEF:
    lda $006D
    beq C0EFF9_WaitFramesWithIntroCancel_LEFF9
    lda.w #$0001
    bra C0F007_WaitFramesWithIntroCancel_LF007
C0EFF9_WaitFramesWithIntroCancel_LEFF9:
    jsl C08756_WaitOneFrameAndPollInput
    lda $0E
    dec A
    sta $0E
C0F002_WaitFramesWithIntroCancel_LF002:
    bne C0EFEF_WaitFramesWithIntroCancel_LEFEF
    lda.w #$0000
C0F007_WaitFramesWithIntroCancel_LF007:
    pld
    rts
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$0000
    jsr $EE68
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl $C087CE
    lda $436C
    beq C0F031_WaitFramesWithIntroCancel_LF031
    lda.w #$00B4
    jsr.w C0EFE1_WaitFramesWithIntroCancel
    bra C0F046_WaitFramesWithIntroCancel_LF046
C0F031_WaitFramesWithIntroCancel_LF031:
    ldx.w #$0000
    stx $0E
    bra C0F041_WaitFramesWithIntroCancel_LF041
C0F038_WaitFramesWithIntroCancel_LF038:
    jsl C08756_WaitOneFrameAndPollInput
    ldx $0E
    inx
    stx $0E
C0F041_WaitFramesWithIntroCancel_LF041:
    cpx.w #$00B4
    bcc C0F038_WaitFramesWithIntroCancel_LF038
C0F046_WaitFramesWithIntroCancel_LF046:
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl C08814_SetDisplayTransitionMode
    lda.w #$0001
    jsr $EE68
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl $C087CE
    lda.w #$0078
    jsr.w C0EFE1_WaitFramesWithIntroCancel
    cmp.w #$0000
    beq C0F083_WaitFramesWithIntroCancel_LF083
    ldy.w #$0000
    ldx.w #$0001
    lda.w #$0002
    jsl C08814_SetDisplayTransitionMode
    lda.w #$0001
    bra C0F0D0_WaitFramesWithIntroCancel_LF0D0
C0F083_WaitFramesWithIntroCancel_LF083:
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl C08814_SetDisplayTransitionMode
    lda.w #$0002
    jsr $EE68
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl $C087CE
    lda.w #$0078
    jsr.w C0EFE1_WaitFramesWithIntroCancel
    cmp.w #$0000
    beq C0F0C0_WaitFramesWithIntroCancel_LF0C0
    ldy.w #$0000
    ldx.w #$0001
    lda.w #$0002
    jsl C08814_SetDisplayTransitionMode
    lda.w #$0001
    bra C0F0D0_WaitFramesWithIntroCancel_LF0D0
C0F0C0_WaitFramesWithIntroCancel_LF0C0:
    ldy.w #$0000
    ldx.w #$0002
    lda.w #$0001
    jsl C08814_SetDisplayTransitionMode
    lda.w #$0000
C0F0D0_WaitFramesWithIntroCancel_LF0D0:
    pld
    rtl
    rep #$31
    phd
    tdc
    adc.w #$FFEA
    tcd
    stz $0037
    stz $0035
    stz $0033
    stz $0031
    lda.w #$0000
    sta $06
    lda.w #$007F
    sta $08
    lda.w #$5B33
    sta $0E
    lda.w #$00E1
    sta $10
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C41A9E_GraphicsDecompressionRoutines_Main
    lda $06
    sta $0E
    lda $08
    sta $10
    ldy.w #$0000
    ldx.w #$C000
    sep #$20
    tya
    jsl C08616_QueueVramTransfer_FromDpSource
    lda.b #$D3
    eor $85,X
    asl $E1A9
    brk #$85
    db $10, $A5
    asl $85
    ora ($A5)
    php
    sta $14
    jsl C41A9E_GraphicsDecompressionRoutines_Main
    lda $06
    sta $0E
    lda $08
    sta $10
    ldy.w #$7800
    ldx.w #$0800
    sep #$20
    lda.b #$00
    jsl C08616_QueueVramTransfer_FromDpSource
    lda.b #$B7
    lda.b #$85
    asl $E1A9
    brk #$85
    db $10, $A9
    brk #$02
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    rep #$20
    lda $06
    sta $12
    lda $08
    sta $14
    jsl C41A9E_GraphicsDecompressionRoutines_Main
    jsl $C4A377
    jsl $C496F9
    lda.w #$0040
    sta $0E
    lda.w #$007F
    sta $10
    ldx.w #$0020
    sep #$20
    lda.b #$00
    jsl C08F15_ClearVramOrRendererBuffer
    sep #$20
    stz $0E
    ldx.w #$0040
    rep #$20
    lda.w #$0200
    jsl C08EFC_CommitTileBufferToStaging
    sep #$20
    stz $0E
    ldx.w #$01A0
    rep #$20
    lda.w #$0260
    jsl C08EFC_CommitTileBufferToStaging
    ldx.w #$FFFF
    lda.w #$01E0
    jsl C496E7_StartPaletteFadeFromWorkBuffer
    sep #$20
    lda.b #$01
    sta $001A
    lda.b #$02
    sta $001B
    sta $002130
    lda.b #$03
    sta $002131
    lda.b #$18
    sta $0030
    rep #$20
    pld
    rts
