; EarthBound C0 working-name anchored byte corridor.
;
; Source-emission status:
; - Prototype level: build-candidate byte corridor.
; - Generated by tools/promote_working_names_to_source_scaffold.py.
; - The current scaffold preserves ROM bytes exactly as data before the
;   terminal label. Replace this corridor with decoded source when the
;   routine/data contract is promoted.
;
; Source unit covered:
; - C0:ECB7..C0:ED14 Load_TitleScreenBackgroundPalettes
;
; Aliases at the same address:
; - none

; ---------------------------------------------------------------------------
; C0:ECB7

C0ECB7_Load_TitleScreenBackgroundPalettes:

; ---------------------------------------------------------------------------
; C0:ED14

C0ED14_Load_TitleScreenBackgroundPalettes_End:
