; Generated by tools/build_source_bank_scaffold.py
; Durable CD helper source scaffold for byte-equivalence validation.
;
; This file is generated from the ca65-like source modules listed in
; build/cd-build-candidate-ranges.json. Rebuild with:
;   python tools/build_source_bank_scaffold.py --bank CD

; Source: src/cd/asset_battle_sprite_107.asm
incsrc "asset_battle_sprite_107.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_64.asm
incsrc "asset_battle_sprite_64.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_40.asm
incsrc "asset_battle_sprite_40.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_97.asm
incsrc "asset_battle_sprite_97.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_41.asm
incsrc "asset_battle_sprite_41.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_86.asm
incsrc "asset_battle_sprite_86.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_39.asm
incsrc "asset_battle_sprite_39.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_38.asm
incsrc "asset_battle_sprite_38.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_56.asm
incsrc "asset_battle_sprite_56.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_100.asm
incsrc "asset_battle_sprite_100.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_96.asm
incsrc "asset_battle_sprite_96.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_36.asm
incsrc "asset_battle_sprite_36.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_73.asm
incsrc "asset_battle_sprite_73.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_75.asm
incsrc "asset_battle_sprite_75.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_35.asm
incsrc "asset_battle_sprite_35.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_74.asm
incsrc "asset_battle_sprite_74.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_101.asm
incsrc "asset_battle_sprite_101.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_94.asm
incsrc "asset_battle_sprite_94.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_37.asm
incsrc "asset_battle_sprite_37.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_87.asm
incsrc "asset_battle_sprite_87.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_13.asm
incsrc "asset_battle_sprite_13.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_104.asm
incsrc "asset_battle_sprite_104.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_99.asm
incsrc "asset_battle_sprite_99.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_55.asm
incsrc "asset_battle_sprite_55.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_95.asm
incsrc "asset_battle_sprite_95.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_105.asm
incsrc "asset_battle_sprite_105.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_72.asm
incsrc "asset_battle_sprite_72.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_51.asm
incsrc "asset_battle_sprite_51.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_22.asm
incsrc "asset_battle_sprite_22.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_102.asm
incsrc "asset_battle_sprite_102.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_84.asm
incsrc "asset_battle_sprite_84.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_67.asm
incsrc "asset_battle_sprite_67.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_63.asm
incsrc "asset_battle_sprite_63.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_11.asm
incsrc "asset_battle_sprite_11.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_106.asm
incsrc "asset_battle_sprite_106.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_54.asm
incsrc "asset_battle_sprite_54.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_14.asm
incsrc "asset_battle_sprite_14.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_32.asm
incsrc "asset_battle_sprite_32.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_81.asm
incsrc "asset_battle_sprite_81.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_62.asm
incsrc "asset_battle_sprite_62.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_93.asm
incsrc "asset_battle_sprite_93.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_83.asm
incsrc "asset_battle_sprite_83.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_34.asm
incsrc "asset_battle_sprite_34.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_12.asm
incsrc "asset_battle_sprite_12.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_60.asm
incsrc "asset_battle_sprite_60.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_71.asm
incsrc "asset_battle_sprite_71.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_10.asm
incsrc "asset_battle_sprite_10.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_9.asm
incsrc "asset_battle_sprite_9.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_28.asm
incsrc "asset_battle_sprite_28.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_108.asm
incsrc "asset_battle_sprite_108.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_79.asm
incsrc "asset_battle_sprite_79.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_27.asm
incsrc "asset_battle_sprite_27.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_78.asm
incsrc "asset_battle_sprite_78.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_30.asm
incsrc "asset_battle_sprite_30.bytes.asar.asm"

; Source: src/cd/asset_battle_sprite_23.asm
incsrc "asset_battle_sprite_23.bytes.asar.asm"
