; EarthBound C1 EarthBound C1 active text entry selection by Y.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:181B..C1:1887 SelectActiveTextEntryByY

; ---------------------------------------------------------------------------
; External contracts used by this module
; - Selects an entry from the active $89D4 chain by ordinal in Y after running
;   the C4:51FA layout helper.
; - FFFF skips selection update. Otherwise descriptor +2F receives the ordinal
;   and descriptor +33 receives the selected record's +06 row/page field.

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C1:181B

C1181B_C1181B_SelectActiveTextEntryByY:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    sty $02
    txy
    ldx.w #$0000
    jsl $C451FA
    lda $02
    cmp.w #$FFFF
    beq C11882_SelectActiveTextEntryByY_L1882
    ; Resolve active descriptor and walk descriptor +2B through record +02.
    lda $8958
    asl A
    tax
    lda $88E4,X
    ldy.w #$0052
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$8650
    tay
    sty $0E
    lda $02
    sta $002F,Y
    lda $002B,Y
    ldy.w #$002D
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$89D4
    tax
    bra C11876_SelectActiveTextEntryByY_L1876
C11862_SelectActiveTextEntryByY_L1862:
    lda $02
    dec A
    sta $02
    lda $0002,X
    ldy.w #$002D
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$89D4
    tax
C11876_SelectActiveTextEntryByY_L1876:
    lda $02
    bne C11862_SelectActiveTextEntryByY_L1862
    lda $0006,X
    ldy $0E
    ; Copy selected record row/page/group field into descriptor +33.
    sta $0033,Y
C11882_SelectActiveTextEntryByY_L1882:
    jsr $163C
    pld
    rts
