; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c1/c1_180d_layout_active_text_entries_and_refresh.asm

hirom
org $C1180D

!C1163C_RefreshTextEntryChainState = $163C
!C451FA_LayoutActiveTextEntryChain = $C451FA
!InitialEntryChainIndex = $0000
C1180D_LayoutActiveTextEntriesAndRefresh:
    rep #$31
    txy
    ldx.w #!InitialEntryChainIndex
    jsl !C451FA_LayoutActiveTextEntryChain
    jsr !C1163C_RefreshTextEntryChainState
    rts
