; EarthBound C1 EarthBound C1 party inventory room text-command wrapper.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:4CEE..C1:4D93 FindPartyMemberWithInventoryRoomForTextCommand

; ---------------------------------------------------------------------------
; External contracts used by this module

C103DC_ReadTextCommandArgumentWord = $03DC
C1040A_LoadPrimaryInteractionContextPointer = $040A
C1045D_InstallPrimaryInteractionContextPointer = $045D
C3E9F7_CheckEquippedInventoryItemPresence = $C3E9F7
C4572B_FindPartyMemberWithInventoryRoomWildcard = $C4572B

; ---------------------------------------------------------------------------
; C1:4CEE

CC_1D_03:
C14CEE_FindPartyMemberWithInventoryRoomForTextCommand = CC_1D_03
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    cpx.w #$0000
    beq C14D00_FindPartyMemberWithInventoryRoomForTextCommand_L4D00
    txa
    bra C14D05_FindPartyMemberWithInventoryRoomForTextCommand_L4D05
C14D00_FindPartyMemberWithInventoryRoomForTextCommand_L4D00:
    jsr C103DC_ReadTextCommandArgumentWord
    lda $06
C14D05_FindPartyMemberWithInventoryRoomForTextCommand_L4D05:
    jsl C4572B_FindPartyMemberWithInventoryRoomWildcard
    cmp.w #$0000
    sta $06
    stz $08
    bpl C14D14_FindPartyMemberWithInventoryRoomForTextCommand_L4D14
    dec $08
C14D14_FindPartyMemberWithInventoryRoomForTextCommand_L4D14:
    lda $06
    sta $0E
    lda $08
    sta $10
    jsr C1045D_InstallPrimaryInteractionContextPointer
    lda.w #$0000
    pld
    rts
CC_1D_04:
C14D24_FindPartyMemberWithoutItemForTextCommand = CC_1D_04
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEA
    tcd
    pla
    lda.w #$0001
    clc
    sbc $97CA
    bvc C14D3B_FindPartyMemberWithInventoryRoomForTextCommand_L4D3B
    bpl C14D50_FindPartyMemberWithInventoryRoomForTextCommand_L4D50
    bra C14D3D_FindPartyMemberWithInventoryRoomForTextCommand_L4D3D
C14D3B_FindPartyMemberWithInventoryRoomForTextCommand_L4D3B:
    bmi C14D50_FindPartyMemberWithInventoryRoomForTextCommand_L4D50
C14D3D_FindPartyMemberWithInventoryRoomForTextCommand_L4D3D:
    txa
    sep #$20
    ldx $97CA
    sta $97BA,X
    rep #$20
    inc $97CA
    lda.w #$4D24
    bra C14D91_FindPartyMemberWithInventoryRoomForTextCommand_L4D91
C14D50_FindPartyMemberWithInventoryRoomForTextCommand_L4D50:
    lda $97BA
    and.w #$00FF
    sta $14
    cpx.w #$0000
    beq C14D61_FindPartyMemberWithInventoryRoomForTextCommand_L4D61
    stx $12
    bra C14D69_FindPartyMemberWithInventoryRoomForTextCommand_L4D69
C14D61_FindPartyMemberWithInventoryRoomForTextCommand_L4D61:
    jsr C103DC_ReadTextCommandArgumentWord
    lda $06
    tax
    stx $12
C14D69_FindPartyMemberWithInventoryRoomForTextCommand_L4D69:
    lda $14
    bne C14D72_FindPartyMemberWithInventoryRoomForTextCommand_L4D72
    jsr C1040A_LoadPrimaryInteractionContextPointer
    lda $06
C14D72_FindPartyMemberWithInventoryRoomForTextCommand_L4D72:
    ldx $12
    jsl C3E9F7_CheckEquippedInventoryItemPresence
    cmp.w #$0000
    sta $06
    stz $08
    bpl C14D83_FindPartyMemberWithInventoryRoomForTextCommand_L4D83
    dec $08
C14D83_FindPartyMemberWithInventoryRoomForTextCommand_L4D83:
    lda $06
    sta $0E
    lda $08
    sta $10
    jsr C1045D_InstallPrimaryInteractionContextPointer
    lda.w #$0000
C14D91_FindPartyMemberWithInventoryRoomForTextCommand_L4D91:
    pld
    rts
