; EarthBound C1 Insert item into first empty inventory slot.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:8B2C..C1:8BC6 c1_8b2c_insert_item_into_first_empty_inventory_slot

; ---------------------------------------------------------------------------
; External contracts used by this module

C08FF7_ResolveIndexedPointerOffset = $C08FF7

; ---------------------------------------------------------------------------
; C1:8B2C

C18B2C_InsertItemIntoFirstEmptyInventorySlot:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF0
    tcd
    pla
    txy
    sty $0E
    tax
    dec A
    sta $04
    lda.w #$0000
    sta $02
    bra C18BAF_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BAF
C18B44_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8B44:
    lda $04
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99F1
    clc
    adc $02
    tax
    lda $0000,X
    and.w #$00FF
    bne C18BAD_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BAD
    ldy $0E
    tya
    sep #$20
    sta $0000,X
    rep #$20
    tya
    ldy.w #$0027
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$0019
    tax
    lda $D55000,X
    and.w #$00FF
    cmp.w #$0004
    bne C18B84_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8B84
    jsl $C216DB
C18B84_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8B84:
    ldy $0E
    tya
    ldy.w #$0027
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$001C
    tax
    lda $D55000,X
    and.w #$00FF
    and.w #$0010
    beq C18BA8_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BA8
    ldy $0E
    tya
    sep #$20
    jsl $C3EAD0
C18BA8_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BA8:
    lda $04
    inc A
    bra C18BC4_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BC4
C18BAD_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BAD:
    inc $02
C18BAF_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BAF:
    lda.w #$000E
    clc
    sbc $02
    bvs C18BBC_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BBC
    bmi C18BC1_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BC1
    jmp.w C18B44_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8B44
C18BBC_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BBC:
    bpl C18BC1_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BC1
    jmp.w C18B44_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8B44
C18BC1_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BC1:
    lda.w #$0000
C18BC4_c1_8b2c_insert_item_into_first_empty_inventory_slot_L8BC4:
    pld
    rts
