; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c1/c1_86b1_execute_nested_text_pointer.asm

hirom
org $C186B1

!C14012_AdvanceNameEntryLetterBoxPointer = $4012
!C1866D_InitializeManagedTextEventSlotFront = $866D
!C445E1_PreflightTextParserWrapForActiveWindow = $C445E1
!NestedTextPointerDone = $8B2A
DISPLAY_TEXT:
!C186B1_ExecuteNestedTextPointer = DISPLAY_TEXT
    rep #$31
    phd
    tdc
    adc.w #$FFDC
    tcd
    lda $32
    sta $06
    lda $34
    sta $08
    lda $06
    sta $20
    lda $08
    sta $22
    ldy.w #$0000
    sty $1E
    lda.w #$550E
    sta $0A
    lda.w #$00C4
    sta $0C
    lda $0A
    sta $1A
    lda $0C
    sta $1C
    lda.w #$0000
    sta $06
    lda.w #$0000
    sta $08
    lda $06
    sta $16
    lda $08
    sta $18
    lda $06
    sta $0A
    lda $08
    sta $0C
    lda $20
    sta $06
    lda $22
    sta $08
    cmp $0C
    bne C1870A_ExecuteNestedTextPointer_L870A
    lda $06
    cmp $0A
C1870A_ExecuteNestedTextPointer_L870A:
    bne C1871F_ExecuteNestedTextPointer_L871F
    lda $20
    sta $06
    lda $22
    sta $08
    lda $06
    sta $2A
    lda $08
    sta $2C
    jmp !NestedTextPointerDone
C1871F_ExecuteNestedTextPointer_L871F:
    jsr !C14012_AdvanceNameEntryLetterBoxPointer
    sta $14
    lda $20
    sta $06
    lda $22
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda $14
    jsr !C1866D_InitializeManagedTextEventSlotFront
    sta $02
    sta $12
    lda $02
    bne C18754_ExecuteNestedTextPointer_L8754
    lda $16
    sta $06
    lda $18
    sta $08
    lda $06
    sta $2A
    lda $08
    sta $2C
    jmp !NestedTextPointerDone
C18754_ExecuteNestedTextPointer_L8754:
    lda $5E6E
    beq C18787_ExecuteNestedTextPointer_L8787
    ldy $1E
    bne C18787_ExecuteNestedTextPointer_L8787
    lda $9660
    bne C18784_ExecuteNestedTextPointer_L8784
    lda $1A
    sta $0A
    lda $1C
    sta $0C
    lda $0A
    sta $06
    lda $0C
    sta $08
    lda $06
    sta $0E
    lda $08
    sta $10
    lda $12
    sta $02
    jsl !C445E1_PreflightTextParserWrapForActiveWindow
    bra C18787_ExecuteNestedTextPointer_L8787
C18784_ExecuteNestedTextPointer_L8784:
    dec $9660
C18787_ExecuteNestedTextPointer_L8787:
    lda $1A
    sta $0A
    lda $1C
    sta $0C
    lda [$0A]
    and.w #$00FF
    beq C187A7_ExecuteNestedTextPointer_L87A7
    and.w #$00FF
    sta $14
    inc $0A
    lda $0A
    sta $1A
    lda $0C
    sta $1C
    db $80, $25
C187A7_ExecuteNestedTextPointer_L87A7:
    lda $12
    sta $02
    ldx $02
    txy
    lda $0000,Y
    sta $06
    lda $0002,Y
    sta $08
    lda [$06]
    and.w #$00FF
    sta $14
    inc $06
    txy
    lda $06
    sta $0000,Y
    lda $08
    sta $0002,Y
