; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c1/c1_9216_print_item_name_from_configuration_table.asm

hirom
org $C19216

!C08FF7_ResolveIndexedPointerOffset = $C08FF7
!C4487C_PrintSegmentedStringBufferWithWrapPreflight = $C4487C
!ItemConfigurationTableLo = $5000
!ItemConfigurationTableBank = $00D5
!ItemConfigurationRecordSize = $0027
!ItemNameByteCount = $0019
!ItemId = $12
!SourcePointerLo = $06
!SourcePointerBank = $08
!PrintPointerLo = $0E
!PrintPointerBank = $10
C19216_PrintItemNameFromConfigurationTable:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEC
    tcd
    pla
    sta !ItemId
    lda.w #!ItemConfigurationTableLo
    sta !SourcePointerLo
    lda.w #!ItemConfigurationTableBank
    sta !SourcePointerBank
    lda !ItemId
    ldy.w #!ItemConfigurationRecordSize
    jsl !C08FF7_ResolveIndexedPointerOffset
    clc
    adc !SourcePointerLo
    sta !SourcePointerLo
    sta !PrintPointerLo
    lda !SourcePointerBank
    sta !PrintPointerBank
    lda.w #!ItemNameByteCount
    jsl !C4487C_PrintSegmentedStringBufferWithWrapPreflight
    pld
    rts
