; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/c1/c1_ac4a_build_battle_attacker_name_buffer.asm

hirom
org $C1AC4A

!C08EED_CopyToVramOrRendererBuffer = $C08EED
!CopyByteCount = $18
!CallerSourcePointerLo = $16
!WorkPointerLo = $06
!WorkPointerBank = $08
!WorkPointerBankHi = $09
!DestinationPointerLo = $0E
!DestinationPointerBank = $10
!SourcePointerLo = $12
!SourcePointerBank = $14
!BattleAttackerNameBuffer = $9CD7
!BattleAttackerNameCacheState = $9658
C1AC4A_BuildBattleAttackerNameBuffer:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE6
    tcd
    pla
    stx !CopyByteCount
    sta !CallerSourcePointerLo
    lda.w #!BattleAttackerNameBuffer
    sta !WorkPointerLo
    phb
    sep #$20
    pla
    sta !WorkPointerBank
    stz !WorkPointerBankHi
    rep #$20
    lda !WorkPointerLo
    sta !DestinationPointerLo
    lda !WorkPointerBank
    sta !DestinationPointerBank
    lda !CallerSourcePointerLo
    sta !WorkPointerLo
    phb
    sep #$20
    pla
    sta !WorkPointerBank
    stz !WorkPointerBankHi
    rep #$20
    lda !WorkPointerLo
    sta !SourcePointerLo
    lda !WorkPointerBank
    sta !SourcePointerBank
    txa
    jsl !C08EED_CopyToVramOrRendererBuffer
    ldx !CopyByteCount
    sep #$20
    stz !BattleAttackerNameBuffer,X
    rep #$20
    lda.w #$FFFF
    sta !BattleAttackerNameCacheState
    pld
    rts
