; EarthBound C1 Text command 1F41 special-event dispatch.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:BEFC..C1:C046 DispatchTextCommand1F41SpecialEvent

; ---------------------------------------------------------------------------
; External contracts used by this module

C12D17_ToggleDebugMeterDisplayOverlay      = $2D17
C1BE4D_AttemptHomesicknessResult           = $BE4D
C03CFD_ExitBicycleMode                     = $C03CFD
C1EAA6_RunNameEntrySpecialEventPrelude     = $C1EAA6
C21628_CheckEventFlag                      = $C21628
C3F3C5_ShowTitleScreenStillImage           = $C3F3C5
C3FB09_CheckActionUserSide                 = $C3FB09
C43344_SetSpecialEventRestrictionLatch5d98 = $C43344
C49D6A_RunCoffeeOrTeaScene                 = $C49D6A
C4ACCE_RunSoundStoneScene                  = $C4ACCE
C4D681_DisplayCurrentPositionTownMap       = $C4D681
C4ED0E_RunCastScene                        = $C4ED0E
C4F554_RunCreditsOrPhotoScene              = $C4F554

; ---------------------------------------------------------------------------
; C1:BEFC

C1BEFC_DispatchTextCommand1F41SpecialEvent:
    rep #$31
    cmp.w #$0001
    bne C1BF06_DispatchTextCommand1F41SpecialEvent_LBF06
    jmp.w C1BF91_DispatchTextCommand1F41SpecialEvent_LBF91
C1BF06_DispatchTextCommand1F41SpecialEvent_LBF06:
    cmp.w #$0002
    bne C1BF0E_DispatchTextCommand1F41SpecialEvent_LBF0E
    jmp.w C1BF9B_DispatchTextCommand1F41SpecialEvent_LBF9B
C1BF0E_DispatchTextCommand1F41SpecialEvent_LBF0E:
    cmp.w #$0003
    bne C1BF16_DispatchTextCommand1F41SpecialEvent_LBF16
    jmp.w C1BFA5_DispatchTextCommand1F41SpecialEvent_LBFA5
C1BF16_DispatchTextCommand1F41SpecialEvent_LBF16:
    cmp.w #$0004
    bne C1BF1E_DispatchTextCommand1F41SpecialEvent_LBF1E
    jmp.w C1BFAF_DispatchTextCommand1F41SpecialEvent_LBFAF
C1BF1E_DispatchTextCommand1F41SpecialEvent_LBF1E:
    cmp.w #$0005
    bne C1BF26_DispatchTextCommand1F41SpecialEvent_LBF26
    jmp.w C1BFB9_DispatchTextCommand1F41SpecialEvent_LBFB9
C1BF26_DispatchTextCommand1F41SpecialEvent_LBF26:
    cmp.w #$0006
    bne C1BF2E_DispatchTextCommand1F41SpecialEvent_LBF2E
    jmp.w C1BFC3_DispatchTextCommand1F41SpecialEvent_LBFC3
C1BF2E_DispatchTextCommand1F41SpecialEvent_LBF2E:
    cmp.w #$0007
    bne C1BF36_DispatchTextCommand1F41SpecialEvent_LBF36
    jmp.w C1BFD0_DispatchTextCommand1F41SpecialEvent_LBFD0
C1BF36_DispatchTextCommand1F41SpecialEvent_LBF36:
    cmp.w #$0008
    bne C1BF3E_DispatchTextCommand1F41SpecialEvent_LBF3E
    jmp.w C1BFD6_DispatchTextCommand1F41SpecialEvent_LBFD6
C1BF3E_DispatchTextCommand1F41SpecialEvent_LBF3E:
    cmp.w #$0009
    bne C1BF46_DispatchTextCommand1F41SpecialEvent_LBF46
    jmp.w C1BFDC_DispatchTextCommand1F41SpecialEvent_LBFDC
C1BF46_DispatchTextCommand1F41SpecialEvent_LBF46:
    cmp.w #$000A
    bne C1BF4E_DispatchTextCommand1F41SpecialEvent_LBF4E
    jmp.w C1BFE5_DispatchTextCommand1F41SpecialEvent_LBFE5
C1BF4E_DispatchTextCommand1F41SpecialEvent_LBF4E:
    cmp.w #$000B
    bne C1BF56_DispatchTextCommand1F41SpecialEvent_LBF56
    jmp.w C1BFEE_DispatchTextCommand1F41SpecialEvent_LBFEE
C1BF56_DispatchTextCommand1F41SpecialEvent_LBF56:
    cmp.w #$000C
    bne C1BF5E_DispatchTextCommand1F41SpecialEvent_LBF5E
    jmp.w C1BFF4_DispatchTextCommand1F41SpecialEvent_LBFF4
C1BF5E_DispatchTextCommand1F41SpecialEvent_LBF5E:
    cmp.w #$000D
    bne C1BF66_DispatchTextCommand1F41SpecialEvent_LBF66
    jmp.w C1BFFA_DispatchTextCommand1F41SpecialEvent_LBFFA
C1BF66_DispatchTextCommand1F41SpecialEvent_LBF66:
    cmp.w #$000E
    bne C1BF6E_DispatchTextCommand1F41SpecialEvent_LBF6E
    jmp.w C1C002_DispatchTextCommand1F41SpecialEvent_LC002
C1BF6E_DispatchTextCommand1F41SpecialEvent_LBF6E:
    cmp.w #$000F
    bne C1BF76_DispatchTextCommand1F41SpecialEvent_LBF76
    jmp.w C1C00A_DispatchTextCommand1F41SpecialEvent_LC00A
C1BF76_DispatchTextCommand1F41SpecialEvent_LBF76:
    cmp.w #$0010
    bne C1BF7E_DispatchTextCommand1F41SpecialEvent_LBF7E
    jmp.w C1C01C_DispatchTextCommand1F41SpecialEvent_LC01C
C1BF7E_DispatchTextCommand1F41SpecialEvent_LBF7E:
    cmp.w #$0011
    bne C1BF86_DispatchTextCommand1F41SpecialEvent_LBF86
    jmp.w C1C025_DispatchTextCommand1F41SpecialEvent_LC025
C1BF86_DispatchTextCommand1F41SpecialEvent_LBF86:
    cmp.w #$0012
    bne C1BF8E_DispatchTextCommand1F41SpecialEvent_LBF8E
    jmp.w C1C02A_DispatchTextCommand1F41SpecialEvent_LC02A
C1BF8E_DispatchTextCommand1F41SpecialEvent_LBF8E:
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BF91_DispatchTextCommand1F41SpecialEvent_LBF91:
    lda.w #$0000
    jsl C49D6A_RunCoffeeOrTeaScene
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BF9B_DispatchTextCommand1F41SpecialEvent_LBF9B:
    lda.w #$0001
    jsl C49D6A_RunCoffeeOrTeaScene
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFA5_DispatchTextCommand1F41SpecialEvent_LBFA5:
    lda.w #$0000
    jsl C1EAA6_RunNameEntrySpecialEventPrelude
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFAF_DispatchTextCommand1F41SpecialEvent_LBFAF:
    lda.w #$0001
    jsl C1EAA6_RunNameEntrySpecialEventPrelude
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFB9_DispatchTextCommand1F41SpecialEvent_LBFB9:
    lda.w #$0001
    jsl C43344_SetSpecialEventRestrictionLatch5d98
    jmp.w C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFC3_DispatchTextCommand1F41SpecialEvent_LBFC3:
    lda.w #$0049
    jsl C21628_CheckEventFlag
    jsl C43344_SetSpecialEventRestrictionLatch5d98
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFD0_DispatchTextCommand1F41SpecialEvent_LBFD0:
    jsl C4D681_DisplayCurrentPositionTownMap
    bra C1C045_DispatchTextCommand1F41SpecialEvent_LC045
C1BFD6_DispatchTextCommand1F41SpecialEvent_LBFD6:
    jsl C3FB09_CheckActionUserSide
    bra C1C045_DispatchTextCommand1F41SpecialEvent_LC045
C1BFDC_DispatchTextCommand1F41SpecialEvent_LBFDC:
    lda.w #$0001
    jsl C4ACCE_RunSoundStoneScene
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFE5_DispatchTextCommand1F41SpecialEvent_LBFE5:
    lda.w #$0001
    jsl C3F3C5_ShowTitleScreenStillImage
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFEE_DispatchTextCommand1F41SpecialEvent_LBFEE:
    jsl C4ED0E_RunCastScene
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFF4_DispatchTextCommand1F41SpecialEvent_LBFF4:
    jsl C4F554_RunCreditsOrPhotoScene
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1BFFA_DispatchTextCommand1F41SpecialEvent_LBFFA:
    lda.w #$0001
    jsr C12D17_ToggleDebugMeterDisplayOverlay
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1C002_DispatchTextCommand1F41SpecialEvent_LC002:
    lda.w #$0000
    jsr C12D17_ToggleDebugMeterDisplayOverlay
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1C00A_DispatchTextCommand1F41SpecialEvent_LC00A:
    ldx.w #$0000
    bra C1C015_DispatchTextCommand1F41SpecialEvent_LC015
C1C00F_DispatchTextCommand1F41SpecialEvent_LC00F:
    sep #$20
    stz $9C08,X
    inx
C1C015_DispatchTextCommand1F41SpecialEvent_LC015:
    cpx.w #$0080
    bcc C1C00F_DispatchTextCommand1F41SpecialEvent_LC00F
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1C01C_DispatchTextCommand1F41SpecialEvent_LC01C:
    lda.w #$0000
    jsl C4ACCE_RunSoundStoneScene
    bra C1C040_DispatchTextCommand1F41SpecialEvent_LC040
C1C025_DispatchTextCommand1F41SpecialEvent_LC025:
    jsr C1BE4D_AttemptHomesicknessResult
    bra C1C045_DispatchTextCommand1F41SpecialEvent_LC045
C1C02A_DispatchTextCommand1F41SpecialEvent_LC02A:
    lda $9883
    cmp.w #$0003
    bne C1C03B_DispatchTextCommand1F41SpecialEvent_LC03B
    jsl C03CFD_ExitBicycleMode
    lda.w #$0001
    bra C1C045_DispatchTextCommand1F41SpecialEvent_LC045
C1C03B_DispatchTextCommand1F41SpecialEvent_LC03B:
    lda.w #$0000
    bra C1C045_DispatchTextCommand1F41SpecialEvent_LC045
C1C040_DispatchTextCommand1F41SpecialEvent_LC040:
    rep #$20
    lda.w #$0000
C1C045_DispatchTextCommand1F41SpecialEvent_LC045:
    rtl
