; EarthBound C1 Battle PSI table helper predicates.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:C165..C1:C452 CurrentCharacterKnowsPsi

; ---------------------------------------------------------------------------
; External contracts used by this module

C1C165_CurrentCharacterKnowsPsi    = $C165
C1C1BA_HasPsiEntryForCategoryMask  = $C1BA
C1C32A_CanCharacterOpenPsiLane     = $C32A
C08FF7_ResolveIndexedPointerOffset = $C08FF7
C447FB_PrintFavoriteThingText      = $C447FB

; ---------------------------------------------------------------------------
; C1:C165

C1C165_CurrentCharacterKnowsPsi:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFF2
    tcd
    pla
    dec A
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    clc
    adc.w #$99DC
    tay
    ldx.w #$0000
    bra C1C1B0_CurrentCharacterKnowsPsi_LC1B0
C1C181_CurrentCharacterKnowsPsi_LC181:
    lda $0000,Y
    and.w #$00FF
    beq C1C1AE_CurrentCharacterKnowsPsi_LC1AE
    and.w #$00FF
    dec A
    asl A
    sta $02
    txa
    sta $04
    asl A
    adc $04
    asl A
    adc $04
    asl A
    clc
    adc $02
    tax
    lda $C3F0B0,X
    beq C1C1A9_CurrentCharacterKnowsPsi_LC1A9
    lda.w #$0000
    bra C1C1B8_CurrentCharacterKnowsPsi_LC1B8
C1C1A9_CurrentCharacterKnowsPsi_LC1A9:
    lda.w #$0001
    bra C1C1B8_CurrentCharacterKnowsPsi_LC1B8
C1C1AE_CurrentCharacterKnowsPsi_LC1AE:
    inx
    iny
C1C1B0_CurrentCharacterKnowsPsi_LC1B0:
    cpx.w #$0007
    bcc C1C181_CurrentCharacterKnowsPsi_LC181
    lda.w #$0001
C1C1B8_CurrentCharacterKnowsPsi_LC1B8:
    pld
    rts
C1C1BA_HasPsiEntryForCategoryMask:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFE9
    tcd
    pla
    sty $04
    pha
    lda $04
    sta $15
    pla
    stx $02
    tax
    cpx.w #$0003
    bne C1C1DA_CurrentCharacterKnowsPsi_LC1DA
    lda.w #$0000
    jmp.w C1C328_CurrentCharacterKnowsPsi_LC328
C1C1DA_CurrentCharacterKnowsPsi_LC1DA:
    txy
    dey
    sty $13
    ldx.w #$0001
    stx $11
    jmp.w C1C2AB_CurrentCharacterKnowsPsi_LC2AB
C1C1E6_CurrentCharacterKnowsPsi_LC1E6:
    ldy $13
    tya
    beq C1C1F7_CurrentCharacterKnowsPsi_LC1F7
    cmp.w #$0001
    beq C1C20C_CurrentCharacterKnowsPsi_LC20C
    cmp.w #$0003
    beq C1C221_CurrentCharacterKnowsPsi_LC221
    bra C1C234_CurrentCharacterKnowsPsi_LC234
C1C1F7_CurrentCharacterKnowsPsi_LC1F7:
    lda $0E
    clc
    adc.w #$0006
    clc
    adc $06
    sta $06
    sep #$20
    lda [$06]
    sta $00
    sta $10
    bra C1C234_CurrentCharacterKnowsPsi_LC234
C1C20C_CurrentCharacterKnowsPsi_LC20C:
    lda $0E
    clc
    adc.w #$0007
    clc
    adc $06
    sta $06
    sep #$20
    lda [$06]
    sta $00
    sta $10
    bra C1C234_CurrentCharacterKnowsPsi_LC234
C1C221_CurrentCharacterKnowsPsi_LC221:
    lda $0E
    clc
    adc.w #$0008
    clc
    adc $06
    sta $06
    sep #$20
    lda [$06]
    sta $00
    sta $10
C1C234_CurrentCharacterKnowsPsi_LC234:
    sep #$20
    lda $10
    sta $00
    rep #$20
    lda $00
    and.w #$00FF
    beq C1C2A6_CurrentCharacterKnowsPsi_LC2A6
    lda.w #$8A50
    sta $06
    lda.w #$00D5
    sta $08
    txa
    sta $04
    asl A
    adc $04
    asl A
    adc $04
    asl A
    adc $04
    sta $0E
    inc A
    inc A
    inc A
    ldx $06
    stx $0A
    ldx $08
    stx $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    and $02
    beq C1C2A6_CurrentCharacterKnowsPsi_LC2A6
    tya
    ldy.w #$005F
    jsl C08FF7_ResolveIndexedPointerOffset
    tax
    sep #$20
    lda $00
    cmp $99D3,X
    beq C1C288_CurrentCharacterKnowsPsi_LC288
    bcs C1C2A6_CurrentCharacterKnowsPsi_LC2A6
C1C288_CurrentCharacterKnowsPsi_LC288:
    rep #$20
    lda $15
    sta $04
    lda $0E
    inc A
    inc A
    clc
    adc $06
    sta $06
    lda [$06]
    and.w #$00FF
    and $04
    beq C1C2A6_CurrentCharacterKnowsPsi_LC2A6
    lda.w #$0001
    jmp.w C1C328_CurrentCharacterKnowsPsi_LC328
C1C2A6_CurrentCharacterKnowsPsi_LC2A6:
    ldx $11
    inx
    stx $11
C1C2AB_CurrentCharacterKnowsPsi_LC2AB:
    rep #$20
    lda.w #$8A50
    sta $06
    lda.w #$00D5
    sta $08
    txa
    sta $04
    asl A
    adc $04
    asl A
    adc $04
    asl A
    adc $04
    sta $0E
    ldy $06
    sty $0A
    ldy $08
    sty $0C
    clc
    adc $0A
    sta $0A
    lda [$0A]
    and.w #$00FF
    beq C1C2DC_CurrentCharacterKnowsPsi_LC2DC
    jmp.w C1C1E6_CurrentCharacterKnowsPsi_LC1E6
C1C2DC_CurrentCharacterKnowsPsi_LC2DC:
    ldy $13
    bne C1C300_CurrentCharacterKnowsPsi_LC300
    lda $02
    and.w #$0001
    beq C1C300_CurrentCharacterKnowsPsi_LC300
    lda $9839
    and.w #$00FF
    and.w #$0001
    beq C1C300_CurrentCharacterKnowsPsi_LC300
    lda $15
    sta $04
    and.w #$0008
    beq C1C300_CurrentCharacterKnowsPsi_LC300
    lda.w #$0001
    bra C1C328_CurrentCharacterKnowsPsi_LC328
C1C300_CurrentCharacterKnowsPsi_LC300:
    cpy.w #$0003
    bne C1C325_CurrentCharacterKnowsPsi_LC325
    lda $02
    and.w #$0002
    beq C1C325_CurrentCharacterKnowsPsi_LC325
    lda $9839
    and.w #$00FF
    and.w #$0006
    beq C1C325_CurrentCharacterKnowsPsi_LC325
    lda $15
    sta $04
    and.w #$0001
    beq C1C325_CurrentCharacterKnowsPsi_LC325
    lda.w #$0001
    bra C1C328_CurrentCharacterKnowsPsi_LC328
C1C325_CurrentCharacterKnowsPsi_LC325:
    lda.w #$0000
C1C328_CurrentCharacterKnowsPsi_LC328:
    pld
    rts
C1C32A_CanCharacterOpenPsiLane:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEE
    tcd
    pla
    sty $10
    stx $0E
    sta $02
    lda.w #$0000
    sta $04
    lda $02
    cmp.w #$0003
    beq C1C363_CurrentCharacterKnowsPsi_LC363
    lda $02
    jsr.w C1C165_CurrentCharacterKnowsPsi
    cmp.w #$0000
    beq C1C363_CurrentCharacterKnowsPsi_LC363
    ldy $10
    ldx $0E
    lda $02
    jsr.w C1C1BA_HasPsiEntryForCategoryMask
    cmp.w #$0000
    beq C1C363_CurrentCharacterKnowsPsi_LC363
    lda.w #$0001
    sta $04
C1C363_CurrentCharacterKnowsPsi_LC363:
    lda $04
    pld
    rts
C1C367_CheckBattlePsiUserEligibility:
    rep #$31
    ldy.w #$000F
    ldx.w #$0001
    jsr.w C1C32A_CanCharacterOpenPsiLane
    rtl
C1C373_FindFirstEligibleBattlePsiUser:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda.w #$0000
    sta $02
    bra C1C3A3_CurrentCharacterKnowsPsi_LC3A3
C1C382_CurrentCharacterKnowsPsi_LC382:
    ldy.w #$000F
    ldx.w #$0001
    stx $0E
    ldx $02
    lda $986F,X
    and.w #$00FF
    ldx $0E
    jsr.w C1C32A_CanCharacterOpenPsiLane
    cmp.w #$0000
    beq C1C3A1_CurrentCharacterKnowsPsi_LC3A1
    lda $02
    inc A
    bra C1C3B4_CurrentCharacterKnowsPsi_LC3B4
C1C3A1_CurrentCharacterKnowsPsi_LC3A1:
    inc $02
C1C3A3_CurrentCharacterKnowsPsi_LC3A3:
    lda $98A4
    and.w #$00FF
    sta $04
    lda $02
    cmp $04
    bcc C1C382_CurrentCharacterKnowsPsi_LC382
    lda.w #$0000
C1C3B4_CurrentCharacterKnowsPsi_LC3B4:
    pld
    rts
C1C3B6_CountEligibleBattlePsiUsers:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda.w #$0000
    sta $04
    sta $02
    sta $10
    bra C1C3EF_CurrentCharacterKnowsPsi_LC3EF
C1C3C9_CurrentCharacterKnowsPsi_LC3C9:
    ldy.w #$000F
    ldx.w #$0001
    stx $0E
    lda $10
    sta $02
    ldx $02
    lda $986F,X
    and.w #$00FF
    ldx $0E
    jsr.w C1C32A_CanCharacterOpenPsiLane
    cmp.w #$0000
    beq C1C3E9_CurrentCharacterKnowsPsi_LC3E9
    inc $04
C1C3E9_CurrentCharacterKnowsPsi_LC3E9:
    inc $02
    lda $02
    sta $10
C1C3EF_CurrentCharacterKnowsPsi_LC3EF:
    lda $98A4
    and.w #$00FF
    pha
    lda $02
    ply
    sty $02
    cmp $02
    bcc C1C3C9_CurrentCharacterKnowsPsi_LC3C9
    lda $04
    pld
    rts
C1C403_PrintPsiFamilyName:
    rep #$31
    phd
    pha
    tdc
    adc.w #$FFEC
    tcd
    pla
    sta $12
    cmp.w #$0001
    bne C1C423_CurrentCharacterKnowsPsi_LC423
    lda.w #$9825
    sta $06
    phb
    sep #$20
    pla
    sta $08
    stz $09
    bra C1C43F_CurrentCharacterKnowsPsi_LC43F
C1C423_CurrentCharacterKnowsPsi_LC423:
    lda.b #$7A
    sta $0685
    lda.w #$00D5
    sta $08
    lda $12
    dec A
    sta $04
    asl A
    adc $04
    asl A
    asl A
    asl A
    adc $04
    clc
    adc $06
    sta $06
C1C43F_CurrentCharacterKnowsPsi_LC43F:
    rep #$20
    lda $06
    sta $0E
    lda $08
    sta $10
    lda.w #$FFFF
    jsl C447FB_PrintFavoriteThingText
    pld
    rts
