; EarthBound C1 battle text close-focus-window redirect.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C1:DD59..C1:DD5F RedirectCloseFocusWindow

; ---------------------------------------------------------------------------
; External contracts used by this module

C100084_CloseFocusWindow_Internal = $0084

; ---------------------------------------------------------------------------
; C1:DD59

C1DD59_RedirectCloseFocusWindow:
    rep #$31
    jsr C100084_CloseFocusWindow_Internal
    rtl
