; EarthBound C0 Restore Current Slot From Snapshot Record.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:4EF0..C0:4F60 Restore_CurrentSlotFromSnapshotRecord

; ---------------------------------------------------------------------------
; External contracts used by this module

C0856B_WaitFramesOrTransitionDelay = $C0856B

; ---------------------------------------------------------------------------
; C0:4EF0

C04EF0_Restore_CurrentSlotFromSnapshotRecord:
    rep #$31
    phd
    tdc
    adc.w #$FFF0
    tcd
    lda $1A42
    asl A
    tay
    lda $0E9A,Y
    asl A
    tax
    lda $4DC8,X
    tax
    stx $4DC6
    lda $003D,X
    sta $04
    asl A
    adc $04
    asl A
    asl A
    clc
    adc.w #$5156
    tax
    stx $0E
    lda $0008,X
    sta $2AF6,Y
    lda $1A42
    asl A
    pha
    lda $0004,X
    plx
    sta $2BAA,X
    ldy $1A42
    ldx $0E
    lda $0006,X
    tax
    stx $0E
    lda $1A42
    asl A
    tax
    lda $0E5E,X
    ldx $0E
    jsl $C07A56
    pld
    rtl
    rep #$31
    lda $5D72
    sta $0200
    sep #$20
    lda.b #$17
    sta $001A
    rep #$20
    lda.w #$0008
    jsl C0856B_WaitFramesOrTransitionDelay
    rtl
