; EarthBound C0 Update Current Slot Orbit Offset From Leader.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:778A..C0:780F Update_CurrentSlotOrbitOffsetFromLeader

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:778A

C0778A_Update_CurrentSlotOrbitOffsetFromLeader:
    rep #$31
    phd
    tdc
    adc.w #$FFEE
    tcd
    lda $9889
    asl A
    tax
    lda $10B6,X
    and.w #$C000
    beq C077AC_Update_CurrentSlotOrbitOffsetFromLeader_L77AC
    lda $1A42
    asl A
    tax
    lda.w #$FFFF
    sta $10F2,X
    bra C0780D_Update_CurrentSlotOrbitOffsetFromLeader_L780D
C077AC_Update_CurrentSlotOrbitOffsetFromLeader_L77AC:
    ldx.w #$3000
    lda $9F6D
    jsl $C41FFF
    lda $06
    sta $0E
    lda $08
    sta $10
    lda $1A42
    asl A
    tax
    lda $10
    and.w #$FF00
    xba
    bpl C077CE_Update_CurrentSlotOrbitOffsetFromLeader_L77CE
    ora.w #$FF00
C077CE_Update_CurrentSlotOrbitOffsetFromLeader_L77CE:
    clc
    adc $9877
    sta $0B8E,X
    lda $1A42
    asl A
    pha
    sep #$20
    lda.b #$0A
    sep #$10
    tay
    rep #$20
    lda $0E
    jsl $C0925B
    sta $02
    lda $987B
    sec
    sbc.w #$0008
    clc
    adc $02
    rep #$10
    plx
    sta $0BCA,X
    lda $9F6D
    clc
    adc.w #$0300
    sta $9F6D
    lda $1A42
    asl A
    tax
    stz $10F2,X
C0780D_Update_CurrentSlotOrbitOffsetFromLeader_L780D:
    pld
    rtl
