; EarthBound C0 Freeze All Active Tasks Except A.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:9F43..C0:9F71 Freeze_AllActiveTasksExceptA

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:9F43

C09F43_Freeze_AllActiveTasksExceptA:
    rep #$30
    pha
    ldx.w #$0000
C09F49_Freeze_AllActiveTasksExceptA_L9F49:
    lda $10B6,X
    sta $284C,X
    inx
    inx
    cpx.w #$003C
    bne C09F49_Freeze_AllActiveTasksExceptA_L9F49
    pla
    ldx $0A50
    bmi C09F70_Freeze_AllActiveTasksExceptA_L9F70
C09F5C_Freeze_AllActiveTasksExceptA_L9F5C:
    cpx $1A44
    beq C09F6A_Freeze_AllActiveTasksExceptA_L9F6A
    lda $10B6,X
    ora.w #$C000
    sta $10B6,X
C09F6A_Freeze_AllActiveTasksExceptA_L9F6A:
    lda $0A9E,X
    tax
    bpl C09F5C_Freeze_AllActiveTasksExceptA_L9F5C
C09F70_Freeze_AllActiveTasksExceptA_L9F70:
    rtl
