; EarthBound C0 Get Current Slot Direction Class.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A673..C0:A679 GetCurrentSlotDirectionClass

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A673

C0A673_GetCurrentSlotDirectionClass:
    ldx $88
    lda $2AF6,X
    rtl
