; EarthBound C0 Project World To Screen From Camera39.
;
; Source-emission status:
; - Prototype level: build-candidate
; - Generated by tools/emit_linear_source_module.py from a state-aware
;   linear ROM decode, then intended for byte-equivalence validation.
;
; Source units covered:
; - C0:A055..C0:A06C ProjectWorldToScreen_FromCamera39

; ---------------------------------------------------------------------------
; External contracts used by this module

; No named external contracts were supplied or recognized.

; ---------------------------------------------------------------------------
; C0:A055

C0A055_ProjectWorldToScreen_FromCamera39:
    ldx $88
    lda $0B8E,X
    sec
    sbc $0039
    sta $0B16,X
    lda $0BCA,X
    sec
    sbc $003B
    sta $0B52,X
    rts
