; EarthBound CC asset PSI_ARRANGEMENT_2.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cc-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CC:D820..CC:DB27 AssetPsiArrangement2

; ---------------------------------------------------------------------------
; CC:DB27

; AssetPsiArrangement2End
CCDB27_AssetPsiArrangement2End:
