; EarthBound D8 table split MAP_DATA_TILE_COLLISION_POINTERS_18.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d8-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D8:E8B4..D8:EC2E MapDataTileCollisionPointers18

; ---------------------------------------------------------------------------
; D8:EC2E

; MapDataTileCollisionPointers18End
D8EC2E_MapDataTileCollisionPointers18End:
