; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d1/asset_sprite_0076.asm

hirom
org $D1C000

!D1C0C0_AssetSprite0076End = SPRITE_0077

; Original terminal data gap ending at $D1C0C0
db $06,$06,$2B,$2B,$1F,$1F,$3F,$3F,$3F,$3F,$3A,$3A,$77,$77,$5D,$5F
db $06,$06,$2B,$2B,$1F,$1F,$3F,$3F,$3F,$3F,$3A,$3F,$77,$78,$5F,$70
db $50,$50,$BB,$BB,$FE,$FE,$FE,$FE,$FE,$FE,$EE,$EE,$37,$37,$DF,$FF
db $50,$50,$BB,$BB,$FE,$FE,$FE,$FE,$FE,$FE,$EE,$FE,$37,$CF,$FF,$05
db $7F,$7F,$2F,$23,$1F,$13,$0F,$0B,$05,$05,$0B,$0F,$1A,$15,$2A,$35
db $7F,$42,$23,$3C,$13,$1C,$0B,$0D,$05,$06,$0F,$0F,$15,$15,$35,$35
db $FD,$FD,$FA,$E2,$FC,$E4,$F8,$E8,$D0,$D0,$68,$78,$2C,$D4,$AA,$56
db $FD,$23,$E2,$1E,$E4,$1C,$E8,$D8,$D0,$30,$78,$F8,$D4,$D4,$56,$56
db $7A,$7D,$3A,$3D,$1F,$1F,$2F,$32,$23,$3D,$23,$3D,$11,$FF,$0E,$3F
db $7D,$4D,$3D,$2D,$1F,$1F,$32,$32,$3D,$3D,$3D,$3D,$FF,$1F,$3F,$0E
db $AF,$5D,$AF,$5F,$F6,$FE,$54,$AC,$D8,$B8,$FC,$FC,$82,$FF,$7C,$FC
db $5D,$59,$5F,$59,$FE,$FE,$AC,$AC,$B8,$B8,$FC,$CC,$FF,$FE,$FC,$7C
