; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d1/asset_sprite_0094.asm

hirom
org $D1CD80

!D1CE40_AssetSprite0094End = SPRITE_0095

; Original terminal data gap ending at $D1CE40
db $07,$07,$0B,$0F,$7B,$7F,$42,$7F,$20,$3F,$1F,$1F,$1F,$1F,$12,$1F
db $07,$07,$0B,$0D,$7B,$7E,$5E,$5F,$3F,$2F,$1B,$1B,$10,$10,$12,$12
db $F0,$F0,$FC,$FC,$12,$FE,$09,$FF,$09,$FF,$FE,$FE,$CC,$FC,$2C,$FC
db $F0,$F0,$FC,$6C,$12,$FE,$09,$FF,$89,$FF,$CE,$CE,$04,$04,$24,$24
db $10,$1F,$1F,$1F,$3F,$20,$3F,$3F,$68,$7F,$68,$7F,$69,$7F,$68,$7F
db $10,$10,$10,$10,$20,$20,$3F,$3F,$60,$60,$63,$60,$65,$61,$67,$60
db $0C,$FC,$FC,$FC,$FE,$02,$FE,$FE,$0B,$FF,$4B,$FF,$4D,$FF,$0F,$FF
db $04,$04,$04,$04,$02,$02,$FE,$FE,$03,$03,$E3,$43,$55,$45,$F7,$07
db $28,$3F,$28,$3F,$2F,$3F,$36,$3F,$1F,$1F,$15,$1F,$08,$FF,$07,$1F
db $20,$20,$20,$20,$2F,$2F,$38,$30,$1F,$1F,$1F,$15,$FF,$08,$1F,$07
db $0D,$FF,$0F,$FF,$07,$FF,$8E,$FE,$7E,$FE,$E8,$FC,$CC,$F7,$38,$FC
db $05,$05,$05,$05,$2B,$03,$82,$82,$7E,$7E,$4C,$48,$F7,$C4,$FC,$38
