; EarthBound D4 asset SPRITE_0949.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:CBE0..D4:CCA0 AssetSprite0949

; ---------------------------------------------------------------------------
; D4:CCA0

; AssetSprite0949End
D4CCA0_AssetSprite0949End:
