; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0797.asm

hirom
org $D45600

!D45680_AssetSprite0797End = SPRITE_0798

; Original terminal data gap ending at $D45680
db $00,$01,$1C,$33,$3B,$23,$75,$07,$4A,$7A,$A4,$A4,$88,$6B,$96,$7D
db $0E,$04,$0F,$3C,$5C,$7F,$F8,$FF,$85,$FF,$5B,$E7,$F7,$9C,$E3,$9E
db $40,$D0,$30,$D8,$E4,$14,$7A,$06,$3C,$00,$2C,$10,$00,$9C,$F2,$EC
db $20,$E0,$E0,$30,$F8,$EC,$FC,$FA,$FE,$FE,$FE,$EE,$FE,$62,$1E,$F2
db $80,$3F,$E5,$5B,$7B,$3F,$6C,$5F,$36,$2F,$3B,$37,$19,$19,$05,$07
db $E4,$DB,$A4,$E6,$40,$60,$20,$71,$11,$3A,$08,$3C,$06,$1F,$00,$07
db $12,$F8,$0C,$BC,$BE,$FA,$6E,$FA,$58,$F4,$B0,$D8,$20,$30,$C0,$C0
db $4E,$B6,$42,$4E,$04,$0E,$04,$1E,$88,$3C,$20,$78,$C0,$F0,$00,$C0
