; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0760.asm

hirom
org $D43240

!D43300_AssetSprite0760End = SPRITE_0761

; Original terminal data gap ending at $D43300
db $1F,$1F,$23,$20,$4F,$4F,$A7,$A0,$9F,$9F,$90,$94,$A0,$A1,$40,$6E
db $1F,$1F,$3C,$3C,$7F,$7F,$B8,$B8,$9F,$9F,$94,$90,$A1,$A0,$6E,$40
db $F0,$F0,$08,$08,$E4,$E4,$8A,$0A,$F2,$F2,$0A,$4A,$0A,$4A,$04,$E4
db $F0,$F0,$F8,$F8,$FC,$FC,$7A,$7A,$F2,$F2,$4A,$0A,$4A,$0A,$E4,$04
db $80,$A0,$84,$A4,$A4,$A4,$A0,$A0,$A0,$A0,$93,$93,$78,$78,$57,$77
db $A0,$80,$A4,$84,$A4,$A4,$A0,$A0,$A0,$A0,$93,$93,$78,$78,$57,$57
db $02,$12,$42,$52,$4A,$4A,$0A,$0A,$0A,$0A,$94,$94,$3C,$3C,$DA,$D6
db $12,$02,$52,$42,$4A,$4A,$0A,$0A,$0A,$0A,$94,$94,$3C,$3C,$D2,$D2
db $40,$40,$90,$90,$70,$74,$20,$23,$10,$10,$0F,$0F,$00,$00,$00,$1F
db $40,$40,$90,$90,$74,$70,$23,$20,$10,$10,$0F,$0F,$00,$00,$1F,$00
db $04,$04,$12,$12,$1C,$1C,$04,$84,$1C,$1C,$E0,$E0,$00,$00,$00,$F0
db $04,$04,$12,$12,$1C,$1C,$84,$04,$1C,$1C,$E0,$E0,$00,$00,$F0,$00
