; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0770.asm

hirom
org $D439C0

!D43A80_AssetSprite0770End = SPRITE_0771

; Original terminal data gap ending at $D43A80
db $00,$00,$0F,$0F,$3F,$3F,$7F,$7E,$7F,$7C,$7F,$72,$7F,$6C,$7F,$60
db $00,$00,$0F,$0F,$3F,$3F,$7E,$7F,$7C,$7F,$72,$7F,$6C,$7F,$60,$7E
db $00,$00,$E0,$E0,$F8,$F8,$FC,$FC,$FC,$7C,$FC,$9C,$FC,$6C,$FC,$0C
db $00,$00,$E0,$E0,$F8,$F8,$FC,$FC,$7C,$FC,$9C,$FC,$6C,$FC,$0C,$FC
db $7F,$44,$7F,$53,$2F,$38,$2F,$3B,$1F,$11,$37,$29,$77,$79,$71,$71
db $44,$7F,$53,$7F,$28,$3F,$2B,$3F,$11,$11,$2D,$25,$7F,$67,$7F,$7F
db $FC,$44,$FC,$94,$E8,$38,$E8,$B8,$F0,$10,$B8,$F8,$FC,$7C,$FC,$FC
db $44,$FC,$94,$FC,$28,$F8,$A8,$F8,$10,$F0,$B8,$B8,$7C,$7C,$FC,$FC
db $7F,$7F,$7F,$7F,$7F,$7F,$3F,$3F,$1F,$1F,$11,$3F,$2E,$FF,$1C,$3F
db $7F,$7F,$7F,$7F,$7F,$7F,$3F,$3F,$1F,$1F,$3F,$11,$F3,$22,$3F,$1C
db $FE,$F6,$FE,$FE,$FC,$FC,$F0,$F8,$F8,$F8,$C8,$FC,$F8,$FF,$70,$FC
db $F6,$F2,$FE,$F2,$FC,$FC,$F8,$F0,$F8,$F8,$FC,$C8,$8F,$88,$FC,$70
