; EarthBound D4 asset SPRITE_0734.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/d4-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - D4:1EC0..D4:1F80 AssetSprite0734

; ---------------------------------------------------------------------------
; D4:1F80

; AssetSprite0734End
D41F80_AssetSprite0734End:
