; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0740.asm

hirom
org $D42340

!D42400_AssetSprite0740End = SPRITE_0741

; Original terminal data gap ending at $D42400
db $00,$00,$03,$03,$05,$07,$05,$07,$0F,$0F,$1F,$1F,$2F,$3F,$3C,$3F
db $00,$00,$03,$03,$07,$05,$07,$05,$0F,$0F,$1F,$1F,$37,$27,$2B,$28
db $00,$00,$E0,$E0,$C0,$C0,$C0,$C0,$E0,$E0,$F0,$F0,$F0,$F0,$F8,$F8
db $00,$00,$E0,$E0,$C0,$C0,$C0,$C0,$E0,$E0,$F0,$F0,$F0,$F0,$F8,$F8
db $6F,$7F,$7F,$7F,$79,$7F,$25,$3F,$31,$3F,$13,$1F,$0F,$0F,$0F,$0F
db $77,$67,$7F,$7F,$79,$7F,$21,$3B,$21,$27,$13,$1F,$0F,$0F,$0B,$0B
db $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$E0,$E0
db $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$E0,$E0
db $0D,$0F,$19,$1F,$5E,$5F,$FF,$FF,$BF,$FF,$48,$78,$28,$FF,$10,$3F
db $0B,$09,$1F,$19,$5F,$5E,$BF,$BF,$DF,$9F,$78,$48,$FF,$28,$3F,$10
db $A0,$E0,$B0,$F0,$7C,$FC,$FA,$FE,$FA,$FE,$36,$3E,$1C,$FF,$18,$FC
db $E0,$A0,$F0,$B0,$FC,$7C,$FE,$FA,$FE,$FA,$3A,$32,$F7,$14,$FC,$18
