; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0693.asm

hirom
org $D40000

!D400C0_AssetSprite0693End = SPRITE_0694

; Original terminal data gap ending at $D400C0
db $1F,$1F,$24,$20,$4E,$40,$54,$40,$B6,$92,$F7,$B7,$7F,$7F,$FF,$FF
db $1F,$1F,$3B,$3B,$71,$71,$7F,$7F,$FF,$FF,$FF,$FD,$7F,$58,$FF,$81
db $70,$70,$CC,$8C,$22,$02,$66,$02,$B1,$91,$DD,$D9,$FE,$FE,$FF,$FF
db $70,$70,$BC,$BC,$FE,$FE,$FE,$FE,$FF,$FF,$FF,$7F,$FE,$36,$FF,$C1
db $FF,$FF,$BF,$8F,$5F,$47,$5D,$47,$26,$27,$50,$78,$6B,$7F,$F9,$BF
db $FF,$82,$8F,$F0,$47,$78,$45,$7A,$26,$39,$58,$77,$7F,$6B,$B8,$89
db $FF,$FF,$FD,$F1,$FE,$F2,$DE,$F2,$24,$E4,$0C,$1C,$A2,$FE,$29,$FF
db $FF,$21,$F1,$0F,$F2,$0E,$D2,$2E,$24,$DC,$1C,$EC,$F6,$AA,$3D,$29
db $A7,$AD,$E3,$EF,$81,$FF,$40,$7F,$30,$3F,$4F,$7F,$3C,$FF,$00,$1F
db $A4,$DD,$E6,$FB,$D5,$AB,$55,$6A,$3F,$30,$5F,$4F,$FF,$3C,$1F,$00
db $C5,$FD,$C5,$FD,$82,$FE,$1C,$FC,$62,$FE,$82,$FE,$8C,$FF,$70,$FC
db $55,$EF,$55,$EF,$DE,$A2,$7C,$9C,$E6,$62,$9E,$82,$FF,$8C,$FC,$70
