; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_1019.asm

hirom
org $D4F900

!D4FA00_AssetSprite1019End = SPRITE_1020

; Original terminal data gap ending at $D4FA00
db $00,$00,$3F,$3F,$7F,$40,$F9,$9F,$D5,$BF,$D9,$BF,$D5,$BF,$D9,$BF
db $00,$00,$3F,$3F,$7F,$7F,$E6,$F9,$EA,$D5,$E6,$D9,$EA,$D5,$E6,$D9
db $00,$00,$FC,$FC,$FE,$02,$5F,$FD,$53,$FD,$4B,$FD,$47,$FD,$DF,$FD
db $00,$00,$FC,$FC,$FE,$FE,$A3,$5F,$AF,$53,$B7,$4B,$BB,$47,$23,$DF
db $C0,$BF,$FF,$BF,$EA,$BF,$F2,$BF,$CA,$BF,$EA,$BF,$F2,$BF,$7F,$40
db $FF,$C0,$C0,$FF,$D5,$EA,$CD,$F2,$F5,$CA,$D5,$EA,$CD,$F2,$7F,$7F
db $03,$FD,$4F,$FD,$AB,$FF,$AB,$FF,$AF,$FD,$AB,$FD,$4F,$F9,$FE,$02
db $FF,$03,$B3,$4F,$55,$AB,$55,$AB,$53,$AF,$57,$AB,$B7,$4F,$FE,$FE
db $3F,$3F,$03,$03,$03,$03,$02,$03,$03,$02,$03,$02,$03,$02,$03,$02
db $3F,$3F,$02,$03,$02,$03,$02,$03,$02,$03,$02,$03,$02,$03,$02,$03
db $FC,$FC,$C0,$C0,$C0,$C0,$40,$C0,$40,$C0,$40,$C0,$40,$C0,$40,$C0
db $FC,$FC,$40,$C0,$40,$C0,$40,$C0,$40,$C0,$40,$C0,$40,$C0,$40,$C0
db $02,$03,$02,$03,$02,$03,$07,$07,$07,$06,$07,$06,$03,$07,$00,$03
db $02,$03,$02,$03,$02,$03,$04,$07,$04,$07,$04,$07,$03,$03,$00,$00
db $40,$C0,$40,$C0,$40,$FE,$E0,$FC,$60,$F8,$60,$F0,$C0,$E0,$00,$C0
db $40,$C0,$40,$C0,$40,$C0,$20,$E0,$20,$E0,$20,$E0,$C0,$C0,$00,$00
