; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0726.asm

hirom
org $D418C0

!D41980_AssetSprite0726End = SPRITE_0727

; Original terminal data gap ending at $D41980
db $06,$06,$17,$15,$1F,$1D,$1E,$16,$7C,$68,$39,$29,$19,$18,$18,$10
db $06,$06,$15,$17,$1D,$1E,$17,$1C,$6F,$70,$2F,$30,$1E,$11,$1F,$10
db $30,$30,$74,$54,$FC,$DC,$3C,$34,$1F,$0B,$4E,$0A,$0C,$0C,$2C,$24
db $30,$30,$54,$74,$DC,$BC,$F4,$1C,$FB,$07,$BA,$46,$FC,$04,$FC,$04
db $1B,$12,$1C,$10,$1F,$18,$2F,$2D,$5A,$4A,$3F,$20,$7C,$64,$7C,$60
db $1E,$11,$1F,$10,$1F,$18,$3F,$2D,$7F,$4A,$3F,$20,$7F,$40,$7B,$44
db $2C,$04,$1C,$04,$FC,$0C,$FA,$DA,$AD,$29,$7E,$02,$0E,$02,$6E,$42
db $DC,$24,$FC,$04,$FC,$0C,$FE,$DA,$FF,$29,$FE,$02,$F6,$0A,$DE,$22
db $39,$21,$3D,$20,$1E,$10,$1F,$10,$0B,$0C,$1F,$1F,$0E,$7F,$00,$1F
db $3F,$20,$3E,$21,$17,$18,$1F,$10,$0E,$09,$1F,$1F,$7F,$0E,$1F,$00
db $0F,$03,$1F,$03,$3F,$27,$FC,$04,$F8,$18,$E4,$E4,$38,$FF,$00,$FC
db $FF,$03,$FF,$01,$EF,$17,$FC,$04,$F8,$18,$E4,$FC,$FF,$38,$FC,$00
