; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0785.asm

hirom
org $D445C0

!D44680_AssetSprite0785End = SPRITE_0786

; Original terminal data gap ending at $D44680
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
db $01,$01,$00,$00,$3B,$3B,$27,$3F,$32,$3F,$6D,$6F,$47,$47,$83,$83
db $01,$01,$00,$00,$3B,$3B,$3F,$27,$3D,$30,$7E,$7C,$7F,$7F,$FF,$FF
db $40,$C0,$60,$E0,$C0,$C0,$E0,$E0,$70,$F0,$F0,$F0,$F8,$F8,$9C,$FC
db $C0,$40,$E0,$60,$C0,$C0,$20,$20,$F0,$70,$F0,$F0,$F8,$F8,$FC,$9C
db $83,$83,$A3,$A3,$8F,$8F,$B1,$BF,$CD,$CF,$17,$17,$0B,$7F,$00,$1E
db $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$CF,$CF,$1F,$1F,$7F,$0B,$1F,$01
db $7C,$FC,$FA,$FE,$7C,$FE,$BD,$FF,$BD,$FF,$DC,$FC,$20,$3F,$80,$FC
db $FC,$7C,$FE,$FA,$FE,$7C,$FF,$BD,$FF,$BD,$FC,$DC,$FF,$E0,$FC,$80
