; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0781.asm

hirom
org $D442C0

!D44380_AssetSprite0781End = SPRITE_0782

; Original terminal data gap ending at $D44380
db $6E,$6E,$FF,$F1,$DE,$E9,$FB,$E7,$76,$6F,$5D,$7D,$74,$74,$4F,$4F
db $6E,$6E,$B1,$B1,$C8,$C8,$A3,$A3,$66,$66,$7D,$5D,$74,$74,$7F,$7F
db $B0,$B0,$78,$F8,$78,$B8,$F4,$F4,$F4,$F4,$F4,$F4,$84,$A4,$E4,$E4
db $B0,$B0,$48,$48,$28,$28,$14,$14,$94,$94,$F4,$F4,$A4,$84,$E4,$E4
db $40,$40,$44,$40,$5E,$40,$7F,$75,$7F,$7F,$7F,$4F,$7F,$6F,$7F,$4F
db $7F,$7F,$7F,$7F,$70,$71,$75,$44,$7F,$40,$4F,$74,$6F,$77,$7F,$4C
db $14,$14,$54,$04,$E4,$04,$FC,$54,$FC,$FC,$FC,$E4,$FC,$EC,$E4,$E4
db $F4,$F4,$FC,$FC,$1C,$1C,$5C,$4C,$FC,$04,$E4,$5C,$EC,$DC,$E4,$64
db $FF,$D4,$FF,$EB,$DF,$C0,$70,$7F,$20,$3F,$7D,$7F,$3D,$3F,$1E,$FF
db $FF,$D4,$EB,$EB,$EA,$A0,$78,$57,$27,$38,$41,$7F,$21,$3F,$F3,$1E
db $F4,$54,$FC,$8C,$FE,$1A,$1E,$FE,$0C,$FC,$F0,$F0,$D0,$FC,$98,$FF
db $F4,$54,$AC,$8C,$BA,$12,$5E,$B2,$FC,$0C,$F0,$F0,$1C,$F0,$8F,$F8
