; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0739.asm

hirom
org $D42280

!D42340_AssetSprite0739End = SPRITE_0740

; Original terminal data gap ending at $D42340
db $03,$03,$05,$07,$05,$07,$0F,$0F,$1F,$1F,$2F,$3F,$3C,$3F,$6F,$7F
db $03,$03,$07,$05,$07,$05,$0F,$0F,$1F,$1F,$37,$27,$2B,$28,$77,$67
db $E0,$E0,$C0,$C0,$C0,$C0,$E0,$E0,$F0,$F0,$F0,$F0,$F8,$F8,$F8,$F8
db $E0,$E0,$C0,$C0,$C0,$C0,$E0,$E0,$F0,$F0,$F0,$F0,$F8,$F8,$F8,$F8
db $7F,$7F,$79,$7F,$25,$3F,$31,$3F,$13,$1F,$0F,$0F,$0F,$0F,$0F,$0F
db $7F,$7F,$79,$7F,$21,$3B,$21,$27,$13,$1F,$0F,$0F,$0B,$0B,$07,$07
db $F8,$F8,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$E0,$E0,$E0,$E0
db $F8,$F8,$F8,$F8,$F8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$E0,$E0,$E0,$E0
db $0B,$0F,$0B,$0F,$0F,$0F,$0F,$0F,$07,$07,$07,$07,$0C,$7F,$07,$1F
db $0F,$0B,$0F,$0B,$0F,$0F,$0F,$0F,$07,$07,$07,$07,$7B,$08,$1F,$07
db $F0,$F0,$E8,$F8,$C8,$F8,$F0,$F0,$E0,$E0,$C0,$C0,$40,$FE,$80,$F8
db $F0,$F0,$D8,$C8,$F8,$C8,$F0,$F0,$E0,$E0,$C0,$C0,$FE,$40,$F8,$80
