; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/d4/asset_sprite_0963.asm

hirom
org $D4D660

!D4D6E0_AssetSprite0963End = SPRITE_0964

; Original terminal data gap ending at $D4D6E0
db $00,$00,$00,$00,$00,$00,$00,$00,$14,$14,$2A,$2A,$2B,$2B,$62,$62
db $00,$00,$00,$00,$00,$00,$00,$00,$14,$14,$2A,$2A,$2B,$2B,$62,$62
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$80,$80,$40,$40
db $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$80,$80,$40,$40
db $80,$80,$71,$71,$0E,$0E,$00,$00,$01,$01,$07,$01,$1F,$00,$07,$00
db $80,$80,$71,$71,$0E,$0E,$00,$00,$01,$01,$01,$07,$00,$1F,$00,$07
db $2E,$2E,$29,$29,$A5,$A5,$AD,$AD,$31,$31,$06,$06,$FF,$F8,$FC,$00
db $2E,$2E,$29,$29,$A5,$A5,$AD,$AD,$31,$31,$06,$06,$F8,$FF,$00,$FC
