; Generated by tools/build_c3_event_script_source_pilot.py
; C3 event/actionscript source pilot: cast-screen-orbit-continuation.
; This file is intentionally not wired into the bank C3 scaffold yet.
hirom

; External constants and action-script variable slots.
!ACTIONSCRIPT_VARS_V0 = $00
!ACTIONSCRIPT_VARS_V1 = $01
!ACTIONSCRIPT_VARS_V2 = $02
!ACTIONSCRIPT_VARS_V3 = $03
!ACTIONSCRIPT_VARS_V4 = $04
!ACTIONSCRIPT_VARS_V5 = $05
!ACTIONSCRIPT_VARS_V6 = $06
!ACTIONSCRIPT_VARS_V7 = $07
!ApplyTempDirectionAndRefreshMovementVector = $AA1E
!DisableCurrentSlotNeighborCache = $C0A82F
!HalveCurrentSlot0d32PreserveSign = $C4730E
!InitFlatCastScreenActorWithRefreshTask = $5FB6
!Integrate_XYVelocityOnly = $9FC8
!IsEntityStillOnCastScreen = $C4ECE7
!LoopCastScreenActorRefreshGateTask = $5F8B
!LoopField2B32VerticalOscillation = $B0B6
!ProjectAngleIntoCurrentSlotVectorWords = $C47044
!ProjectWorldToScreen_FromCamera39 = $A055
!RefreshCurrentSlotVisualProfile_Mode0 = $C0A4BF
!ReleaseCurrentVisualEntityAndEnd = $A204
!RestoreCurrentSlotAnchorFromCachedTarget = $C46C87
!RoundAngleToWalkDirectionStep = $C46B51
!ScriptWrapper_C472A8_Mode0 = $C0A8E7
!Script_SetCurrentSlotField2B32 = $C0A685
!SetCurrentSlotDirectionClassIfActive = $C0A65F
!SnapshotCurrentSlotAnchorToStagedPosition = $C46C45
!SpawnEntityAtCurrentSlotAnchor_ReadTwoWords = $C0A98B

; Minimal macro vocabulary used by this source pilot.
macro EVENT_BINOP(var, op, value)
    db $14, <var>, <op>
    dw <value>
endmacro

macro EVENT_CALLROUTINE_0(target)
    db $42
    dl <target>
endmacro

macro EVENT_CALLROUTINE_2(target, arg0, arg1)
    db $42
    dl <target>
    db <arg0>, <arg1>
endmacro

macro EVENT_CALLROUTINE_4(target, arg0, arg1, arg2, arg3)
    db $42
    dl <target>
    db <arg0>, <arg1>, <arg2>, <arg3>
endmacro

macro EVENT_HALT()
    db $09
endmacro

macro EVENT_LOOP(count)
    db $01, <count>
endmacro

macro EVENT_LOOP_END()
    db $02
endmacro

macro EVENT_PAUSE(frames)
    db $06, <frames>
endmacro

macro EVENT_SET_ANIMATION(animation)
    db $3B, <animation>
endmacro

macro EVENT_SET_PHYSICS_CALLBACK(target)
    db $25
    dw <target>
endmacro

macro EVENT_SET_POSITION_CHANGE_CALLBACK(target)
    db $23
    dw <target>
endmacro

macro EVENT_SET_VAR(var, value)
    db $0E, <var>
    dw <value>
endmacro

macro EVENT_SET_VELOCITIES_ZERO()
    db $39
endmacro

macro EVENT_SET_X_VELOCITY(value)
    db $3F
    dw <value>
endmacro

macro EVENT_SET_Y_RELATIVE(value)
    db $2C
    dw <value>
endmacro

macro EVENT_SET_Y_VELOCITY(value)
    db $40
    dw <value>
endmacro

macro EVENT_SHORTCALL(target)
    db $1A
    dw <target>
endmacro

macro EVENT_SHORTCALL_CONDITIONAL_NOT(target)
    db $0B
    dw <target>
endmacro

macro EVENT_SHORTJUMP(target)
    db $19
    dw <target>
endmacro

macro EVENT_START_TASK(target)
    db $07
    dw <target>
endmacro

macro EVENT_WRITE_TEMPVAR_TO_VAR(var)
    db $1F, <var>
endmacro

macro EVENT_WRITE_VAR_TO_TEMPVAR(var)
    db $20, <var>
endmacro

macro EVENT_WRITE_WORD_TEMPVAR(value)
    db $1D
    dw <value>
endmacro


org $C36356
CastScreenOrbitVectorDampingLoop:
    %EVENT_SHORTCALL(!InitFlatCastScreenActorWithRefreshTask) ; C3:6356  1A B6 5F
    %EVENT_CALLROUTINE_0(!SnapshotCurrentSlotAnchorToStagedPosition) ; C3:6359  42 45 6C C4
    %EVENT_WRITE_VAR_TO_TEMPVAR(!ACTIONSCRIPT_VARS_V0) ; C3:635D  20 00
    %EVENT_WRITE_TEMPVAR_TO_VAR(!ACTIONSCRIPT_VARS_V6) ; C3:635F  1F 06
    %EVENT_WRITE_VAR_TO_TEMPVAR(!ACTIONSCRIPT_VARS_V1) ; C3:6361  20 01
    %EVENT_WRITE_TEMPVAR_TO_VAR(!ACTIONSCRIPT_VARS_V7) ; C3:6363  1F 07
    %EVENT_START_TASK(!LoopField2B32VerticalOscillation) ; C3:6365  07 B6 B0
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $00) ; C3:6368  42 85 A6 C0 00 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V0, $0000) ; C3:636E  0E 00 00 00
    %EVENT_WRITE_VAR_TO_TEMPVAR(!ACTIONSCRIPT_VARS_V0) ; C3:6372  20 00
    %EVENT_CALLROUTINE_0(!ProjectAngleIntoCurrentSlotVectorWords) ; C3:6374  42 44 70 C4
    %EVENT_CALLROUTINE_0(!RoundAngleToWalkDirectionStep) ; C3:6378  42 51 6B C4
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:637C  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:6380  42 BF A4 C0
LoopCastScreenOrbitDamping:
    %EVENT_PAUSE($01) ; C3:6384  06 01
    %EVENT_BINOP(!ACTIONSCRIPT_VARS_V0, $02, $0800) ; C3:6386  14 00 02 00 08
    %EVENT_CALLROUTINE_0(!RestoreCurrentSlotAnchorFromCachedTarget) ; C3:638B  42 87 6C C4
    %EVENT_CALLROUTINE_0(!ScriptWrapper_C472A8_Mode0) ; C3:638F  42 E7 A8 C0
    %EVENT_CALLROUTINE_0(!HalveCurrentSlot0d32PreserveSign) ; C3:6393  42 0E 73 C4
    %EVENT_CALLROUTINE_0(!DisableCurrentSlotNeighborCache) ; C3:6397  42 2F A8 C0
    %EVENT_SHORTJUMP(LoopCastScreenOrbitDamping) ; C3:639B  19 84 63
CastScreenFallRelease:
    %EVENT_SET_POSITION_CHANGE_CALLBACK(!ProjectWorldToScreen_FromCamera39) ; C3:639E  23 55 A0
    %EVENT_SET_PHYSICS_CALLBACK(!Integrate_XYVelocityOnly) ; C3:63A1  25 C8 9F
    %EVENT_SET_ANIMATION($00) ; C3:63A4  3B 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:63A6  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:63A9  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:63AD  42 BF A4 C0
    %EVENT_LOOP($0B) ; C3:63B1  01 0B
    %EVENT_PAUSE($14) ; C3:63B3  06 14
    %EVENT_LOOP_END() ; C3:63B5  02
    %EVENT_SET_Y_VELOCITY($0055) ; C3:63B6  40 55 00
    %EVENT_PAUSE($A8) ; C3:63B9  06 A8
    %EVENT_CALLROUTINE_4(!SpawnEntityAtCurrentSlotAnchor_ReadTwoWords, $2E, $00, $26, $03) ; C3:63BB  42 8B A9 C0 2E 00 26 03
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:63C3  19 04 A2
CastScreenFacingPulseUntilGone:
    %EVENT_SET_POSITION_CHANGE_CALLBACK(!ProjectWorldToScreen_FromCamera39) ; C3:63C6  23 55 A0
    %EVENT_SET_PHYSICS_CALLBACK(!Integrate_XYVelocityOnly) ; C3:63C9  25 C8 9F
    %EVENT_SET_ANIMATION($00) ; C3:63CC  3B 00
    %EVENT_SET_Y_RELATIVE($0003) ; C3:63CE  2C 03 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:63D1  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:63D4  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:63D8  42 BF A4 C0
LoopCastScreenFacingPulseUntilGone:
    %EVENT_PAUSE($3C) ; C3:63DC  06 3C
    %EVENT_LOOP($02) ; C3:63DE  01 02
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:63E0  1D 06 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:63E3  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:63E7  42 BF A4 C0
    %EVENT_PAUSE($08) ; C3:63EB  06 08
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:63ED  1D 02 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:63F0  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:63F4  42 BF A4 C0
    %EVENT_PAUSE($08) ; C3:63F8  06 08
    %EVENT_LOOP_END() ; C3:63FA  02
    %EVENT_CALLROUTINE_0(!IsEntityStillOnCastScreen) ; C3:63FB  42 E7 EC C4
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopCastScreenFacingPulseUntilGone) ; C3:63FF  0B DC 63
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:6402  19 04 A2
CastScreenHorizontalPatrolLoop:
    %EVENT_SHORTCALL(!InitFlatCastScreenActorWithRefreshTask) ; C3:6405  1A B6 5F
LoopCastScreenHorizontalPatrol:
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:6408  1D 06 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:640B  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:640F  42 BF A4 C0
    %EVENT_SET_X_VELOCITY($FFAB) ; C3:6413  3F AB FF
    %EVENT_PAUSE($60) ; C3:6416  06 60
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6418  39
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:6419  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:641C  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:6420  42 BF A4 C0
    %EVENT_PAUSE($14) ; C3:6424  06 14
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:6426  1D 02 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:6429  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:642D  42 BF A4 C0
    %EVENT_SET_X_VELOCITY($0055) ; C3:6431  3F 55 00
    %EVENT_PAUSE($60) ; C3:6434  06 60
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6436  39
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:6437  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:643A  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:643E  42 BF A4 C0
    %EVENT_PAUSE($14) ; C3:6442  06 14
    %EVENT_SHORTJUMP(LoopCastScreenHorizontalPatrol) ; C3:6444  19 08 64
CastScreenBlinkHalt:
    %EVENT_SET_POSITION_CHANGE_CALLBACK(!ProjectWorldToScreen_FromCamera39) ; C3:6447  23 55 A0
    %EVENT_SET_PHYSICS_CALLBACK(!Integrate_XYVelocityOnly) ; C3:644A  25 C8 9F
    %EVENT_SET_ANIMATION($00) ; C3:644D  3B 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V3, $0010) ; C3:644F  0E 03 10 00
    %EVENT_START_TASK(!LoopCastScreenActorRefreshGateTask) ; C3:6453  07 8B 5F
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6456  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:6457  0E 04 01 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:645B  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:645E  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:6462  42 BF A4 C0
    %EVENT_LOOP($03) ; C3:6466  01 03
    %EVENT_SET_ANIMATION($00) ; C3:6468  3B 00
    %EVENT_PAUSE($0A) ; C3:646A  06 0A
    %EVENT_SET_ANIMATION($FF) ; C3:646C  3B FF
    %EVENT_PAUSE($0A) ; C3:646E  06 0A
    %EVENT_LOOP_END() ; C3:6470  02
    %EVENT_SET_ANIMATION($00) ; C3:6471  3B 00
    %EVENT_HALT() ; C3:6473  09
CastScreenDirectionPulseHalt:
    %EVENT_SHORTCALL(!InitFlatCastScreenActorWithRefreshTask) ; C3:6474  1A B6 5F
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:6477  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:647A  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:647E  42 BF A4 C0
    %EVENT_PAUSE($8C) ; C3:6482  06 8C
    %EVENT_PAUSE($8C) ; C3:6484  06 8C
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:6486  1D 06 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:6489  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:648D  42 BF A4 C0
    %EVENT_PAUSE($0A) ; C3:6491  06 0A
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:6493  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:6496  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:649A  42 BF A4 C0
    %EVENT_PAUSE($32) ; C3:649E  06 32
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V3, $000C) ; C3:64A0  0E 03 0C 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:64A4  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:64AA  1D 02 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:64AD  1A 1E AA
    %EVENT_HALT() ; C3:64B0  09
CastScreenLeftStepCycleLoop:
    %EVENT_SHORTCALL(!InitFlatCastScreenActorWithRefreshTask) ; C3:64B1  1A B6 5F
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V3, $0008) ; C3:64B4  0E 03 08 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:64B8  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:64BB  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:64BF  42 BF A4 C0
LoopCastScreenLeftStepCycleA:
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:64C3  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:64C9  1D 02 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:64CC  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:64CF  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:64D1  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:64D2  0E 04 01 00
    %EVENT_PAUSE($3C) ; C3:64D6  06 3C
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:64D8  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:64DC  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:64E2  1D 04 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:64E5  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:64E8  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:64EA  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:64EB  0E 04 01 00
    %EVENT_PAUSE($1E) ; C3:64EF  06 1E
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:64F1  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:64F5  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:64FB  1D 00 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:64FE  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:6501  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6503  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:6504  0E 04 01 00
    %EVENT_PAUSE($3C) ; C3:6508  06 3C
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:650A  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:650E  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:6514  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:6517  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:651A  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:651C  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:651D  0E 04 01 00
    %EVENT_PAUSE($28) ; C3:6521  06 28
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:6523  0E 04 00 00
    %EVENT_SHORTJUMP(LoopCastScreenLeftStepCycleA) ; C3:6527  19 C3 64
CastScreenFacingStepCycleLoop:
    %EVENT_SHORTCALL(!InitFlatCastScreenActorWithRefreshTask) ; C3:652A  1A B6 5F
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V3, $0008) ; C3:652D  0E 03 08 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:6531  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:6534  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:6538  42 BF A4 C0
LoopCastScreenFacingStepCycleB:
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:653C  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:6542  1D 04 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:6545  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:6548  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:654A  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:654B  0E 04 01 00
    %EVENT_PAUSE($3C) ; C3:654F  06 3C
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:6551  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:6555  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:655B  1D 00 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:655E  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:6561  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6563  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:6564  0E 04 01 00
    %EVENT_PAUSE($1E) ; C3:6568  06 1E
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:656A  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:656E  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:6574  1D 02 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:6577  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:657A  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:657C  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:657D  0E 04 01 00
    %EVENT_PAUSE($3C) ; C3:6581  06 3C
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:6583  0E 04 00 00
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $01) ; C3:6587  42 85 A6 C0 80 01
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:658D  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:6590  1A 1E AA
    %EVENT_PAUSE($0A) ; C3:6593  06 0A
    %EVENT_SET_VELOCITIES_ZERO() ; C3:6595  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:6596  0E 04 01 00
    %EVENT_PAUSE($3C) ; C3:659A  06 3C
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:659C  0E 04 00 00
    %EVENT_SHORTJUMP(LoopCastScreenFacingStepCycleB) ; C3:65A0  19 3C 65
