; Generated by tools/build_c3_event_script_source_pilot.py
; C3 event/actionscript source pilot: early-turn-bias-and-coordinate-routes.
; This file is intentionally not wired into the bank C3 scaffold yet.
hirom

; External constants and action-script variable slots.
!ACTIONSCRIPT_VARS_V0 = $00
!ACTIONSCRIPT_VARS_V1 = $01
!ACTIONSCRIPT_VARS_V2 = $02
!ACTIONSCRIPT_VARS_V3 = $03
!ACTIONSCRIPT_VARS_V4 = $04
!ACTIONSCRIPT_VARS_V5 = $05
!ACTIONSCRIPT_VARS_V6 = $06
!ACTIONSCRIPT_VARS_V7 = $07
!ActionScript_GetPositionOfPartyMember = $C0A943
!ActionScript_QueueTextPointer = $C0A88D
!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode = $C0A857
!ActionScript_TestEventFlag_ReadWord = $C0A84C
!ApplyTempDirectionAndRefreshMovementVector = $AA1E
!DisableCurrentSlotNeighborCache = $C0A82F
!InitActionScriptMovementState = $AA38
!InitAlternatePhysicsVar4WalkPulse = $AB26
!InitMovementPresetVar4Countdown = $AAAA
!InstallScriptMovementVectorFromDirection = $C0C83B
!LoopPartyLooksAtActiveEntity = $AFA3
!MapPlayerDirection987fToTurnBias = $C46A6E
!RefreshCurrentSlotVisualProfile_Mode0 = $C0A4BF
!ReleaseCurrentVisualEntityAndEnd = $A204
!Script_CopyRegistrySlotAnchorToCurrentSlot_ReadByte = $C0A864
!Script_PlaySoundEffectParameter = $C0A841
!Script_SetCurrentSlotField2B32 = $C0A685
!SetCurrentSlotDirectionClassIfActive = $C0A65F
!SetYieldToTextLatch9641 = $C46E46
!SnapshotCurrentSlotAnchorToStagedPosition = $C46C45
!TrafficLightWaitUntilOffscreenAndRelease = $A2AA
!WaitForActiveEntityMovementToFinish = $AB59
!WaitUntilPlayerLeavesActiveArea = $AB8A

; Minimal macro vocabulary used by this source pilot.
macro EVENT_CALLROUTINE_0(target)
    db $42
    dl <target>
endmacro

macro EVENT_CALLROUTINE_1(target, arg0)
    db $42
    dl <target>
    db <arg0>
endmacro

macro EVENT_CALLROUTINE_2(target, arg0, arg1)
    db $42
    dl <target>
    db <arg0>, <arg1>
endmacro

macro EVENT_CALLROUTINE_4(target, arg0, arg1, arg2, arg3)
    db $42
    dl <target>
    db <arg0>, <arg1>, <arg2>, <arg3>
endmacro

macro EVENT_END_LAST_TASK()
    db $13
endmacro

macro EVENT_HALT()
    db $09
endmacro

macro EVENT_PAUSE(frames)
    db $06, <frames>
endmacro

macro EVENT_SET_ANIMATION(animation)
    db $3B, <animation>
endmacro

macro EVENT_SET_VAR(var, value)
    db $0E, <var>
    dw <value>
endmacro

macro EVENT_SET_VELOCITIES_ZERO()
    db $39
endmacro

macro EVENT_SET_X(value)
    db $28
    dw <value>
endmacro

macro EVENT_SET_Y(value)
    db $29
    dw <value>
endmacro

macro EVENT_SHORTCALL(target)
    db $1A
    dw <target>
endmacro

macro EVENT_SHORTCALL_CONDITIONAL(target)
    db $0A
    dw <target>
endmacro

macro EVENT_SHORTJUMP(target)
    db $19
    dw <target>
endmacro

macro EVENT_START_TASK(target)
    db $07
    dw <target>
endmacro

macro EVENT_WRITE_WORD_TEMPVAR(value)
    db $1D
    dw <value>
endmacro


org $C304FA
Event242_PlayerDirectionTurnBiasRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:04FA  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:04FD  42 85 A6 C0 80 00
    %EVENT_CALLROUTINE_0(!MapPlayerDirection987fToTurnBias) ; C3:0503  42 6E 6A C4
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:0507  1A 1E AA
    %EVENT_PAUSE($2C) ; C3:050A  06 2C
    %EVENT_SET_VELOCITIES_ZERO() ; C3:050C  39
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:050D  1D 02 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:0510  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:0514  42 BF A4 C0
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:0518  42 46 6E C4
    %EVENT_END_LAST_TASK() ; C3:051C  13
    %EVENT_SHORTJUMP(!TrafficLightWaitUntilOffscreenAndRelease) ; C3:051D  19 AA A2
Event243_ShortMovementRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:0520  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:0523  42 85 A6 C0 80 00
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:0529  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:052C  1A 1E AA
    %EVENT_PAUSE($20) ; C3:052F  06 20
    %EVENT_SET_VELOCITIES_ZERO() ; C3:0531  39
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:0532  42 46 6E C4
    %EVENT_END_LAST_TASK() ; C3:0536  13
    %EVENT_SHORTJUMP(!TrafficLightWaitUntilOffscreenAndRelease) ; C3:0537  19 AA A2
Event243_AlternateShortMovementRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:053A  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:053D  42 85 A6 C0 80 00
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:0543  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:0546  1A 1E AA
    %EVENT_PAUSE($20) ; C3:0549  06 20
    %EVENT_SET_VELOCITIES_ZERO() ; C3:054B  39
    %EVENT_END_LAST_TASK() ; C3:054C  13
    %EVENT_SHORTJUMP(!TrafficLightWaitUntilOffscreenAndRelease) ; C3:054D  19 AA A2
Event244_PairedMovementRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:0550  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:0553  42 85 A6 C0 80 00
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:0559  1D 04 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:055C  1A 1E AA
    %EVENT_PAUSE($20) ; C3:055F  06 20
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:0561  1D 02 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:0564  1A 1E AA
    %EVENT_PAUSE($20) ; C3:0567  06 20
    %EVENT_SET_VELOCITIES_ZERO() ; C3:0569  39
    %EVENT_END_LAST_TASK() ; C3:056A  13
    %EVENT_SHORTJUMP(!TrafficLightWaitUntilOffscreenAndRelease) ; C3:056B  19 AA A2
Event245_DirectionMovementRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:056E  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:0571  42 85 A6 C0 80 00
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:0577  1D 06 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:057A  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:057E  42 BF A4 C0
    %EVENT_WRITE_WORD_TEMPVAR($0002) ; C3:0582  1D 02 00
    %EVENT_CALLROUTINE_0(!InstallScriptMovementVectorFromDirection) ; C3:0585  42 3B C8 C0
    %EVENT_PAUSE($20) ; C3:0589  06 20
    %EVENT_SET_VELOCITIES_ZERO() ; C3:058B  39
    %EVENT_END_LAST_TASK() ; C3:058C  13
    %EVENT_SHORTJUMP(!TrafficLightWaitUntilOffscreenAndRelease) ; C3:058D  19 AA A2
Event246_MultiStepRouteRelease:
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:0590  1A 38 AA
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:0593  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:0596  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:059A  42 BF A4 C0
LoopEvent246_WaitForMovementGate:
    %EVENT_PAUSE($01) ; C3:059E  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $02, $00) ; C3:05A0  42 4C A8 C0 02 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent246_WaitForMovementGate) ; C3:05A6  0A 9E 05
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:05A9  42 85 A6 C0 80 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0001) ; C3:05AF  0E 05 01 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0A50) ; C3:05B3  0E 06 50 0A
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $0F58) ; C3:05B7  0E 07 58 0F
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:05BB  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0A20) ; C3:05BE  0E 06 20 0A
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:05C2  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0A18) ; C3:05C5  0E 06 18 0A
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $0F48) ; C3:05C9  0E 07 48 0F
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:05CD  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $0A30) ; C3:05D0  0E 06 30 0A
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:05D4  1A 59 AB
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:05D7  42 46 6E C4
    %EVENT_PAUSE($20) ; C3:05DB  06 20
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $09F0) ; C3:05DD  0E 06 F0 09
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $0F28) ; C3:05E1  0E 07 28 0F
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:05E5  1A 59 AB
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:05E8  42 46 6E C4
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:05EC  19 04 A2
Event247_CollisionDisabledPresetMovement:
    %EVENT_CALLROUTINE_0(!DisableCurrentSlotNeighborCache) ; C3:05EF  42 2F A8 C0
    %EVENT_SHORTCALL(!InitMovementPresetVar4Countdown) ; C3:05F3  1A AA AA
    %EVENT_SET_ANIMATION($FF) ; C3:05F6  3B FF
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:05F8  0E 04 00 00
    %EVENT_CALLROUTINE_0(!SnapshotCurrentSlotAnchorToStagedPosition) ; C3:05FC  42 45 6C C4
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V2, $0040) ; C3:0600  0E 02 40 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V3, $00A0) ; C3:0604  0E 03 A0 00
    %EVENT_SHORTCALL(!WaitUntilPlayerLeavesActiveArea) ; C3:0608  1A 8A AB
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $61, $00) ; C3:060B  42 41 A8 C0 61 00
    %EVENT_PAUSE($05) ; C3:0611  06 05
    %EVENT_SET_ANIMATION($00) ; C3:0613  3B 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0005) ; C3:0615  0E 04 05 00
    %EVENT_SET_X($1B10) ; C3:0619  28 10 1B
    %EVENT_SET_Y($02E8) ; C3:061C  29 E8 02
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $02) ; C3:061F  42 85 A6 C0 00 02
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:0625  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1B20) ; C3:0629  0E 06 20 1B
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $02E8) ; C3:062D  0E 07 E8 02
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:0631  1A 59 AB
    %EVENT_CALLROUTINE_4(!ActionScript_QueueTextPointer, $C5, $00, $50, $F6) ; C3:0634  42 8D A8 C0 C5 00 50 F6
    %EVENT_START_TASK(!LoopPartyLooksAtActiveEntity) ; C3:063C  07 A3 AF
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1BC0) ; C3:063F  0E 06 C0 1B
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:0643  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1BF0) ; C3:0646  0E 06 F0 1B
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $02B8) ; C3:064A  0E 07 B8 02
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:064E  1A 59 AB
    %EVENT_END_LAST_TASK() ; C3:0651  13
    %EVENT_END_LAST_TASK() ; C3:0652  13
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $08, $00) ; C3:0653  42 41 A8 C0 08 00
    %EVENT_PAUSE($0A) ; C3:0659  06 0A
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:065B  42 41 A8 C0 09 00
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:0661  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $67, $00) ; C3:0664  42 57 A8 C0 67 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:066A  42 46 6E C4
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:066E  19 04 A2
    %EVENT_CALLROUTINE_1(!Script_CopyRegistrySlotAnchorToCurrentSlot_ReadByte, $09) ; C3:0671  42 64 A8 C0 09
    %EVENT_SHORTCALL(!InitAlternatePhysicsVar4WalkPulse) ; C3:0676  1A 26 AB
    %EVENT_WRITE_WORD_TEMPVAR($0004) ; C3:0679  1D 04 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:067C  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:0680  42 BF A4 C0
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $80, $00) ; C3:0684  42 85 A6 C0 80 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0014) ; C3:068A  0E 05 14 00
    %EVENT_CALLROUTINE_1(!ActionScript_GetPositionOfPartyMember, $FF) ; C3:068E  42 43 A9 C0 FF
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:0693  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:0696  0E 04 01 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:069A  42 46 6E C4
    %EVENT_HALT() ; C3:069E  09
