; Generated by tools/build_c3_event_script_source_pilot.py
; C3 event/actionscript source pilot: temp-flag-door-close-paths.
; This file is intentionally not wired into the bank C3 scaffold yet.
hirom

; External constants and action-script variable slots.
!ACTIONSCRIPT_VARS_V0 = $00
!ACTIONSCRIPT_VARS_V1 = $01
!ACTIONSCRIPT_VARS_V2 = $02
!ACTIONSCRIPT_VARS_V3 = $03
!ACTIONSCRIPT_VARS_V4 = $04
!ACTIONSCRIPT_VARS_V5 = $05
!ACTIONSCRIPT_VARS_V6 = $06
!ACTIONSCRIPT_VARS_V7 = $07
!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode = $C0A857
!ActionScript_TestEventFlag_ReadWord = $C0A84C
!ApplyTempDirectionAndRefreshMovementVector = $AA1E
!FaceVisualTypeSlotTowardCurrentSlot_ReadWord = $C0A94E
!InitActionScriptMovementState = $AA38
!LoopMakePartyLookAtActiveEntity = $C227
!MakePartyLookAtActiveEntityCallback = $C48B3B
!RefreshCurrentSlotVisualProfile_Mode0 = $C0A4BF
!ReleaseCurrentVisualEntityAndEnd = $A204
!Script_ApplyCurrentSlotVisualCountdownState = $C0AA6E
!Script_PlaySoundEffectParameter = $C0A841
!Script_SetCurrentSlotField2B32 = $C0A685
!SetCurrentSlotDirectionClassIfActive = $C0A65F
!SetYieldToTextLatch9641 = $C46E46
!WaitForActiveEntityMovementToFinish = $AB59

; Minimal macro vocabulary used by this source pilot.
macro EVENT_CALLROUTINE_0(target)
    db $42
    dl <target>
endmacro

macro EVENT_CALLROUTINE_2(target, arg0, arg1)
    db $42
    dl <target>
    db <arg0>, <arg1>
endmacro

macro EVENT_HALT()
    db $09
endmacro

macro EVENT_PAUSE(frames)
    db $06, <frames>
endmacro

macro EVENT_SET_ANIMATION(animation)
    db $3B, <animation>
endmacro

macro EVENT_SET_VAR(var, value)
    db $0E, <var>
    dw <value>
endmacro

macro EVENT_SET_VELOCITIES_ZERO()
    db $39
endmacro

macro EVENT_SET_X(value)
    db $28
    dw <value>
endmacro

macro EVENT_SET_Y(value)
    db $29
    dw <value>
endmacro

macro EVENT_SHORTCALL(target)
    db $1A
    dw <target>
endmacro

macro EVENT_SHORTCALL_CONDITIONAL(target)
    db $0A
    dw <target>
endmacro

macro EVENT_SHORTCALL_CONDITIONAL_NOT(target)
    db $0B
    dw <target>
endmacro

macro EVENT_SHORTJUMP(target)
    db $19
    dw <target>
endmacro

macro EVENT_SHORT_RETURN()
    db $1B
endmacro

macro EVENT_START_TASK(target)
    db $07
    dw <target>
endmacro

macro EVENT_WRITE_TEMPVAR_TO_VAR(var)
    db $1F, <var>
endmacro

macro EVENT_WRITE_WORD_TEMPVAR(value)
    db $1D
    dw <value>
endmacro


org $C3BEA4
RunDoorCloseTempFlagTextHandoff:
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:BEA4  0E 04 00 00
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:BEA8  1D 00 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BEAB  1A 1E AA
    %EVENT_PAUSE($08) ; C3:BEAE  06 08
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0001) ; C3:BEB0  0E 05 01 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1DA8) ; C3:BEB4  0E 06 A8 1D
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $1DE0) ; C3:BEB8  0E 07 E0 1D
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:BEBC  42 85 A6 C0 00 01
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:BEC2  1A 59 AB
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:BEC5  0E 04 01 00
    %EVENT_CALLROUTINE_2(!Script_ApplyCurrentSlotVisualCountdownState, $00, $00) ; C3:BEC9  42 6E AA C0 00 00
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:BECF  42 46 6E C4
    %EVENT_SHORT_RETURN() ; C3:BED3  1B
RunDoorCloseTempFlagMovementReset:
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0000) ; C3:BED4  0E 04 00 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V5, $0002) ; C3:BED8  0E 05 02 00
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V6, $1DF0) ; C3:BEDC  0E 06 F0 1D
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V7, $1DE8) ; C3:BEE0  0E 07 E8 1D
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $40, $01) ; C3:BEE4  42 85 A6 C0 40 01
    %EVENT_SHORTCALL(!WaitForActiveEntityMovementToFinish) ; C3:BEEA  1A 59 AB
    %EVENT_SHORT_RETURN() ; C3:BEED  1B
Event115_TempFlag1DoorCloseSequence:
    %EVENT_SET_X($1DE8) ; C3:BEEE  28 E8 1D
    %EVENT_SET_Y($1DE8) ; C3:BEF1  29 E8 1D
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:BEF4  1A 38 AA
    %EVENT_START_TASK(LoopEvent115_119PartyLookTask) ; C3:BEF7  07 E4 C0
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:BEFA  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:BF00  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BF03  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:BF06  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:BF0C  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:BF0E  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BF11  1A 1E AA
    %EVENT_PAUSE($58) ; C3:BF14  06 58
    %EVENT_SET_VELOCITIES_ZERO() ; C3:BF16  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:BF17  0E 04 01 00
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:BF1B  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:BF1E  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:BF22  42 BF A4 C0
LoopEvent115_WaitTempFlag1Clear:
    %EVENT_PAUSE($01) ; C3:BF26  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $02, $00) ; C3:BF28  42 4C A8 C0 02 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent115_WaitTempFlag1Clear) ; C3:BF2E  0A 26 BF
    %EVENT_SHORTCALL(RunDoorCloseTempFlagTextHandoff) ; C3:BF31  1A A4 BE
LoopEvent115_WaitTempFlag1Set:
    %EVENT_PAUSE($01) ; C3:BF34  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $02, $00) ; C3:BF36  42 4C A8 C0 02 00
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopEvent115_WaitTempFlag1Set) ; C3:BF3C  0B 34 BF
    %EVENT_SHORTCALL(RunDoorCloseTempFlagMovementReset) ; C3:BF3F  1A D4 BE
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:BF42  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $03, $00) ; C3:BF45  42 57 A8 C0 03 00
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:BF4B  19 04 A2
Event116_TempFlag2DoorCloseSequence:
    %EVENT_SET_X($1DE8) ; C3:BF4E  28 E8 1D
    %EVENT_SET_Y($1DE8) ; C3:BF51  29 E8 1D
    %EVENT_SET_ANIMATION($FF) ; C3:BF54  3B FF
    %EVENT_PAUSE($12) ; C3:BF56  06 12
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:BF58  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:BF5B  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:BF61  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BF64  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:BF67  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:BF6D  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:BF6F  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BF72  1A 1E AA
    %EVENT_PAUSE($48) ; C3:BF75  06 48
    %EVENT_SET_VELOCITIES_ZERO() ; C3:BF77  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:BF78  0E 04 01 00
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:BF7C  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:BF7F  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:BF83  42 BF A4 C0
LoopEvent116_WaitTempFlag2Clear:
    %EVENT_PAUSE($01) ; C3:BF87  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $03, $00) ; C3:BF89  42 4C A8 C0 03 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent116_WaitTempFlag2Clear) ; C3:BF8F  0A 87 BF
    %EVENT_START_TASK(LoopEvent115_119PartyLookTask) ; C3:BF92  07 E4 C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagTextHandoff) ; C3:BF95  1A A4 BE
LoopEvent116_WaitTempFlag2Set:
    %EVENT_PAUSE($01) ; C3:BF98  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $03, $00) ; C3:BF9A  42 4C A8 C0 03 00
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopEvent116_WaitTempFlag2Set) ; C3:BFA0  0B 98 BF
    %EVENT_SHORTCALL(RunDoorCloseTempFlagMovementReset) ; C3:BFA3  1A D4 BE
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:BFA6  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $04, $00) ; C3:BFA9  42 57 A8 C0 04 00
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:BFAF  19 04 A2
Event117_TempFlag3DoorCloseSequence:
    %EVENT_SET_X($1DE8) ; C3:BFB2  28 E8 1D
    %EVENT_SET_Y($1DE8) ; C3:BFB5  29 E8 1D
    %EVENT_SET_ANIMATION($FF) ; C3:BFB8  3B FF
    %EVENT_PAUSE($24) ; C3:BFBA  06 24
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:BFBC  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:BFBF  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:BFC5  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BFC8  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:BFCB  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:BFD1  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:BFD3  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:BFD6  1A 1E AA
    %EVENT_PAUSE($38) ; C3:BFD9  06 38
    %EVENT_SET_VELOCITIES_ZERO() ; C3:BFDB  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:BFDC  0E 04 01 00
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:BFE0  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:BFE3  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:BFE7  42 BF A4 C0
LoopEvent117_WaitTempFlag3Clear:
    %EVENT_PAUSE($01) ; C3:BFEB  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $04, $00) ; C3:BFED  42 4C A8 C0 04 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent117_WaitTempFlag3Clear) ; C3:BFF3  0A EB BF
    %EVENT_START_TASK(LoopEvent115_119PartyLookTask) ; C3:BFF6  07 E4 C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagTextHandoff) ; C3:BFF9  1A A4 BE
LoopEvent117_WaitTempFlag3Set:
    %EVENT_PAUSE($01) ; C3:BFFC  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $04, $00) ; C3:BFFE  42 4C A8 C0 04 00
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopEvent117_WaitTempFlag3Set) ; C3:C004  0B FC BF
    %EVENT_SHORTCALL(RunDoorCloseTempFlagMovementReset) ; C3:C007  1A D4 BE
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:C00A  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $05, $00) ; C3:C00D  42 57 A8 C0 05 00
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:C013  19 04 A2
Event118_TempFlag4DoorCloseSequence:
    %EVENT_SET_X($1DE8) ; C3:C016  28 E8 1D
    %EVENT_SET_Y($1DE8) ; C3:C019  29 E8 1D
    %EVENT_SET_ANIMATION($FF) ; C3:C01C  3B FF
    %EVENT_PAUSE($36) ; C3:C01E  06 36
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:C020  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:C023  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:C029  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C02C  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:C02F  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:C035  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:C037  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C03A  1A 1E AA
    %EVENT_PAUSE($28) ; C3:C03D  06 28
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C03F  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C040  0E 04 01 00
    %EVENT_WRITE_TEMPVAR_TO_VAR(!ACTIONSCRIPT_VARS_V4) ; C3:C044  1F 04
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:C046  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:C049  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:C04D  42 BF A4 C0
LoopEvent118_WaitTempFlag4Clear:
    %EVENT_PAUSE($01) ; C3:C051  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $05, $00) ; C3:C053  42 4C A8 C0 05 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent118_WaitTempFlag4Clear) ; C3:C059  0A 51 C0
    %EVENT_START_TASK(LoopEvent115_119PartyLookTask) ; C3:C05C  07 E4 C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagTextHandoff) ; C3:C05F  1A A4 BE
LoopEvent118_WaitTempFlag4Set:
    %EVENT_PAUSE($01) ; C3:C062  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $05, $00) ; C3:C064  42 4C A8 C0 05 00
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopEvent118_WaitTempFlag4Set) ; C3:C06A  0B 62 C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagMovementReset) ; C3:C06D  1A D4 BE
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:C070  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $06, $00) ; C3:C073  42 57 A8 C0 06 00
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:C079  19 04 A2
Event119_TempFlag5DoorCloseSequence:
    %EVENT_SET_X($1DE8) ; C3:C07C  28 E8 1D
    %EVENT_SET_Y($1DE8) ; C3:C07F  29 E8 1D
    %EVENT_SET_ANIMATION($FF) ; C3:C082  3B FF
    %EVENT_PAUSE($48) ; C3:C084  06 48
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:C086  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:C089  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:C08F  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C092  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:C095  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:C09B  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:C09D  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C0A0  1A 1E AA
    %EVENT_PAUSE($18) ; C3:C0A3  06 18
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C0A5  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C0A6  0E 04 01 00
    %EVENT_WRITE_WORD_TEMPVAR($0000) ; C3:C0AA  1D 00 00
    %EVENT_CALLROUTINE_0(!SetCurrentSlotDirectionClassIfActive) ; C3:C0AD  42 5F A6 C0
    %EVENT_CALLROUTINE_0(!RefreshCurrentSlotVisualProfile_Mode0) ; C3:C0B1  42 BF A4 C0
    %EVENT_WRITE_WORD_TEMPVAR($0001) ; C3:C0B5  1D 01 00
    %EVENT_CALLROUTINE_2(!ActionScript_SetOrClearEventFlag_ReadWordPreserveMode, $02, $00) ; C3:C0B8  42 57 A8 C0 02 00
LoopEvent119_WaitTempFlag5Clear:
    %EVENT_PAUSE($01) ; C3:C0BE  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $06, $00) ; C3:C0C0  42 4C A8 C0 06 00
    %EVENT_SHORTCALL_CONDITIONAL(LoopEvent119_WaitTempFlag5Clear) ; C3:C0C6  0A BE C0
    %EVENT_START_TASK(LoopEvent115_119PartyLookTask) ; C3:C0C9  07 E4 C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagTextHandoff) ; C3:C0CC  1A A4 BE
LoopEvent119_WaitTempFlag5Set:
    %EVENT_PAUSE($01) ; C3:C0CF  06 01
    %EVENT_CALLROUTINE_2(!ActionScript_TestEventFlag_ReadWord, $06, $00) ; C3:C0D1  42 4C A8 C0 06 00
    %EVENT_SHORTCALL_CONDITIONAL_NOT(LoopEvent119_WaitTempFlag5Set) ; C3:C0D7  0B CF C0
    %EVENT_SHORTCALL(RunDoorCloseTempFlagMovementReset) ; C3:C0DA  1A D4 BE
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:C0DD  42 46 6E C4
    %EVENT_SHORTJUMP(!ReleaseCurrentVisualEntityAndEnd) ; C3:C0E1  19 04 A2
LoopEvent115_119PartyLookTask:
    %EVENT_CALLROUTINE_0(!MakePartyLookAtActiveEntityCallback) ; C3:C0E4  42 3B 8B C4
    %EVENT_CALLROUTINE_2(!FaceVisualTypeSlotTowardCurrentSlot_ReadWord, $FD, $00) ; C3:C0E8  42 4E A9 C0 FD 00
    %EVENT_PAUSE($03) ; C3:C0EE  06 03
    %EVENT_SHORTJUMP(LoopEvent115_119PartyLookTask) ; C3:C0F0  19 E4 C0
Event468_StaggeredDoorCloseHalt:
    %EVENT_START_TASK(!LoopMakePartyLookAtActiveEntity) ; C3:C0F3  07 27 C2
    %EVENT_SHORTCALL(RunStaggeredDoorCloseMovement) ; C3:C0F6  1A 43 C1
    %EVENT_PAUSE($98) ; C3:C0F9  06 98
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C0FB  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C0FC  0E 04 01 00
    %EVENT_HALT() ; C3:C100  09
Event469_StaggeredDoorCloseHalt:
    %EVENT_SET_ANIMATION($FF) ; C3:C101  3B FF
    %EVENT_PAUSE($12) ; C3:C103  06 12
    %EVENT_SHORTCALL(RunStaggeredDoorCloseMovement) ; C3:C105  1A 43 C1
    %EVENT_PAUSE($88) ; C3:C108  06 88
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C10A  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C10B  0E 04 01 00
    %EVENT_HALT() ; C3:C10F  09
Event470_StaggeredDoorCloseHalt:
    %EVENT_SET_ANIMATION($FF) ; C3:C110  3B FF
    %EVENT_PAUSE($24) ; C3:C112  06 24
    %EVENT_SHORTCALL(RunStaggeredDoorCloseMovement) ; C3:C114  1A 43 C1
    %EVENT_PAUSE($78) ; C3:C117  06 78
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C119  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C11A  0E 04 01 00
    %EVENT_HALT() ; C3:C11E  09
Event471_StaggeredDoorCloseHalt:
    %EVENT_SET_ANIMATION($FF) ; C3:C11F  3B FF
    %EVENT_PAUSE($36) ; C3:C121  06 36
    %EVENT_SHORTCALL(RunStaggeredDoorCloseMovement) ; C3:C123  1A 43 C1
    %EVENT_PAUSE($68) ; C3:C126  06 68
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C128  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C129  0E 04 01 00
    %EVENT_HALT() ; C3:C12D  09
Event472_StaggeredDoorCloseYieldHalt:
    %EVENT_SET_ANIMATION($FF) ; C3:C12E  3B FF
    %EVENT_PAUSE($48) ; C3:C130  06 48
    %EVENT_SHORTCALL(RunStaggeredDoorCloseMovement) ; C3:C132  1A 43 C1
    %EVENT_PAUSE($58) ; C3:C135  06 58
    %EVENT_SET_VELOCITIES_ZERO() ; C3:C137  39
    %EVENT_SET_VAR(!ACTIONSCRIPT_VARS_V4, $0001) ; C3:C138  0E 04 01 00
    %EVENT_PAUSE($1E) ; C3:C13C  06 1E
    %EVENT_CALLROUTINE_0(!SetYieldToTextLatch9641) ; C3:C13E  42 46 6E C4
    %EVENT_HALT() ; C3:C142  09
RunStaggeredDoorCloseMovement:
    %EVENT_SET_X($11F0) ; C3:C143  28 F0 11
    %EVENT_SET_Y($1368) ; C3:C146  29 68 13
    %EVENT_SHORTCALL(!InitActionScriptMovementState) ; C3:C149  1A 38 AA
    %EVENT_CALLROUTINE_2(!Script_SetCurrentSlotField2B32, $00, $01) ; C3:C14C  42 85 A6 C0 00 01
    %EVENT_WRITE_WORD_TEMPVAR($0005) ; C3:C152  1D 05 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C155  1A 1E AA
    %EVENT_CALLROUTINE_2(!Script_PlaySoundEffectParameter, $09, $00) ; C3:C158  42 41 A8 C0 09 00
    %EVENT_PAUSE($16) ; C3:C15E  06 16
    %EVENT_WRITE_WORD_TEMPVAR($0006) ; C3:C160  1D 06 00
    %EVENT_SHORTCALL(!ApplyTempDirectionAndRefreshMovementVector) ; C3:C163  1A 1E AA
    %EVENT_SHORT_RETURN() ; C3:C166  1B
