; EarthBound CB asset AUDIO_PACK_59.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/cb-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - CB:FEE2..CB:FFE4 AssetAudioPack59

; ---------------------------------------------------------------------------
; CB:FFE4

; AssetAudioPack59End
CBFFE4_AssetAudioPack59End:
