from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import rom_tools


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PROJECT_DIR = ROOT / "build" / "coilsnake" / "baseline-project"
DEFAULT_JSON_OUT = ROOT / "build" / "coilsnake" / "reports" / "coilsnake-project-inventory.json"
DEFAULT_MANIFEST_OUT = ROOT / "manifests" / "coilsnake-crosswalk.json"

SCHEMA = "earthbound-decomp.coilsnake-crosswalk.v1"

EVIDENCE_LEVELS = {
    "coilsnake-observed": "Generated by CoilSnake or present in a CoilSnake-style project, but not yet mapped back to local ROM ranges.",
    "local-range-confirmed": "Mapped to checked-in ranges, asset manifests, or contract notes in this repository.",
    "diff-confirmed": "A controlled CoilSnake edit/rebuild binary diff proves the changed byte span or repoint behavior.",
    "runtime-correlated": "Linked to local runtime consumers, WRAM fields, callers, or source/data contracts.",
}

FAMILIES: dict[str, dict[str, Any]] = {
    "battle_visual_assets": {
        "label": "Battle visual assets",
        "local_status": "contract-seeded",
        "related_local_docs": [
            "notes/battle-visual-asset-contracts.md",
            "notes/battle-background-scene-bundles.md",
            "notes/psi-animation-bundle-contracts.md",
            "notes/battle-sprite-bundle-contracts.md",
            "notes/swirl-sequence-bundle-contracts.md",
        ],
        "source_banks": ["CA", "CB", "CC", "CD", "CE"],
    },
    "overworld_sprites": {
        "label": "Overworld sprites",
        "local_status": "contract-backed",
        "related_local_docs": [
            "notes/overworld-sprite-group-contracts.md",
            "notes/overworld-sprite-frame-semantics.md",
            "notes/overworld-sprite-animation-roles.md",
            "notes/overworld-sprite-pointer-flag-semantics.md",
            "notes/secondary-visual-descriptor-contracts.md",
        ],
        "source_banks": ["D1", "D2", "D3", "D4", "D5"],
    },
    "map_tilesets_and_runtime_tables": {
        "label": "Map tilesets and runtime tables",
        "local_status": "contract-backed-with-known-followups",
        "related_local_docs": [
            "notes/map-milestone-closure.md",
            "notes/map-object-bundles.md",
            "notes/map-sector-bundles.md",
            "notes/map-tileset-bundles.md",
            "notes/map-fts-format-audit.md",
            "notes/map-collision-runtime-bit-contract.md",
            "notes/map-palette-descriptor-context.md",
            "notes/map-scene-composition-contract.md",
        ],
        "source_banks": ["D6", "D7", "D8", "D9", "DA", "DB", "DC", "DD", "DE", "DF"],
    },
    "ui_font_town_map_assets": {
        "label": "UI, fonts, logos, windows, and town maps",
        "local_status": "contract-seeded",
        "related_local_docs": [
            "notes/ui-font-town-map-asset-contracts.md",
            "notes/text-window-skin-bundle-contracts.md",
            "notes/font-bundle-contracts.md",
            "notes/intro-title-visual-bundle-contracts.md",
            "notes/title-screen-palette-animation-contracts.md",
            "notes/title-screen-letter-oam-contracts.md",
            "notes/landing-cast-visual-contracts.md",
            "notes/sram-template-contracts.md",
        ],
        "source_banks": ["E0", "E1"],
    },
    "text_script_authoring": {
        "label": "Text and CCScript authoring",
        "local_status": "semantic-frontier",
        "related_local_docs": [
            "notes/text-command-semantics-manifest.md",
            "notes/text-script-assets-frontier.md",
            "notes/text-vm-localization-semantics-closeout.md",
            "notes/localization-control-macro-lowering-profiles.md",
            "notes/localization-map-object-crosswalk.md",
            "notes/c3-actionscript-semantics-audit.md",
        ],
        "source_banks": ["C3", "C5", "C6", "C7", "C8", "C9", "EF"],
    },
    "gameplay_yaml_tables": {
        "label": "Gameplay YAML tables",
        "local_status": "mixed-contract-frontier",
        "related_local_docs": [
            "notes/c2-battle-contract-workahead.md",
            "notes/c3-battle-psi-menu-data-contracts.md",
            "notes/battle-psi-ability-table-d58a50.md",
            "notes/class2-d57b68-battle-action-table-match.md",
            "notes/asset-data-contract-frontier.md",
        ],
        "source_banks": ["C2", "C3", "D5", "EF"],
    },
    "mixed_asset_tables": {
        "label": "Mixed asset/table banks",
        "local_status": "manifest-backed",
        "related_local_docs": [
            "notes/bank-cf-asset-data-map.md",
            "notes/bank-d0-asset-data-map.md",
        ],
        "source_banks": ["CF", "D0"],
    },
    "audio_packs": {
        "label": "Audio packs",
        "local_status": "raw-pack-manifest",
        "related_local_docs": [
            "notes/audio-pack-format-and-renderer-frontier.md",
            "notes/audio-pack-contracts.md",
            "notes/audio-backend-contract.md",
            "notes/bank-e2-ee-audio-pack-run.md",
        ],
        "source_banks": ["E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "EA", "EB", "EC", "ED", "EE"],
    },
    "project_control": {
        "label": "CoilSnake project and compiler controls",
        "local_status": "oracle-control",
        "related_local_docs": [
            "notes/reference-first-workflow.md",
            "notes/asset-pipeline-plan.md",
        ],
        "source_banks": [],
    },
    "uncategorized": {
        "label": "Uncategorized CoilSnake output",
        "local_status": "needs-triage",
        "related_local_docs": [
            "notes/asset-data-contract-frontier.md",
        ],
        "source_banks": [],
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Inventory a local CoilSnake project and build a safe crosswalk manifest."
    )
    parser.add_argument(
        "--project-dir",
        default=str(DEFAULT_PROJECT_DIR),
        help="CoilSnake project directory to inventory.",
    )
    parser.add_argument("--rom", help="Optional explicit verified EarthBound ROM path.")
    parser.add_argument(
        "--coilsnake-version",
        default="4.2",
        help="Expected CoilSnake version used for the project.",
    )
    parser.add_argument(
        "--json-out",
        default=str(DEFAULT_JSON_OUT),
        help="Ignored detailed inventory report path.",
    )
    parser.add_argument(
        "--manifest-out",
        default=str(DEFAULT_MANIFEST_OUT),
        help="Tracked safe crosswalk manifest path.",
    )
    parser.add_argument(
        "--compare-rom",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Optional rebuilt or experiment ROM to diff against the verified base ROM.",
    )
    parser.add_argument(
        "--experiment-base-rom",
        help="Optional baseline rebuilt ROM used as the comparison base for controlled edit experiments.",
    )
    parser.add_argument(
        "--experiment-rom",
        action="append",
        default=[],
        metavar="LABEL=PATH",
        help="Optional controlled edit experiment ROM to diff against --experiment-base-rom.",
    )
    parser.add_argument(
        "--experiment-report",
        action="append",
        default=[],
        metavar="PATH",
        help="Optional ignored report from tools/run_coilsnake_edit_experiment.py.",
    )
    return parser.parse_args()


def rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def existing_docs(paths: list[str]) -> list[str]:
    return [path for path in paths if (ROOT / path).exists()]


def classify(path: Path, project_dir: Path) -> dict[str, str]:
    relative = path.relative_to(project_dir)
    parts = relative.parts
    top = parts[0] if parts else path.name
    top_lower = top.lower()
    name_lower = path.name.lower()
    suffix = path.suffix.lower()

    if name_lower == "project.snake":
        return type_record("project_control", "project_metadata")
    if name_lower in {"used_ranges.yml", "patches.yml"}:
        return type_record("project_control", "compiler_control_yml")
    if top_lower == "ccscript" or suffix == ".ccs":
        return type_record("text_script_authoring", "ccscript")
    if top_lower == "music":
        return type_record("audio_packs", "music_project_resource")
    if top_lower in {"battlebgs", "battlesprites", "swirls", "animations"}:
        return type_record("battle_visual_assets", top)
    if top_lower == "spritegroups" or name_lower in {
        "sprite_groups.yml",
        "sprite_group_palettes.yml",
        "playable_char_gfx_table.yml",
    }:
        return type_record("overworld_sprites", "sprite_group_resource")
    if top_lower == "tilesets" or name_lower.startswith("map_") or name_lower == "map_tiles.map":
        return type_record("map_tilesets_and_runtime_tables", "map_resource")
    if top_lower in {"fonts", "logos", "townmaps", "windowgraphics", "cast", "staff", "titlescreen"}:
        return type_record("ui_font_town_map_assets", top)
    if name_lower.startswith(("enemy_", "bg_", "battle_")):
        return type_record("battle_visual_assets", "battle_yaml_table")
    if name_lower.startswith(("npc_", "photographer_", "teleport_destination")):
        return type_record("map_tilesets_and_runtime_tables", "map_object_yaml_table")
    if name_lower.startswith(("item_", "psi_", "store_", "stats_", "exp_", "initial_", "condiment")):
        return type_record("gameplay_yaml_tables", "gameplay_yaml_table")
    if name_lower in {"text_misc.yml", "dont_care_names.yml", "naming_skip.yml", "telephone_contacts_table.yml"}:
        return type_record("text_script_authoring", "text_yaml_table")
    if name_lower == "window_configuration_table.yml":
        return type_record("ui_font_town_map_assets", "window_yaml_table")
    if suffix in {".yml", ".yaml"}:
        return type_record("gameplay_yaml_tables", "yaml_table")
    return type_record("uncategorized", "unclassified")


def type_record(family: str, resource_type: str) -> dict[str, str]:
    return {
        "resource_family": family,
        "resource_type": resource_type,
        "evidence_level": "coilsnake-observed",
    }


def collect_project_files(project_dir: Path) -> list[dict[str, Any]]:
    files: list[dict[str, Any]] = []
    for path in sorted(project_dir.rglob("*")):
        if not path.is_file():
            continue
        classification = classify(path, project_dir)
        files.append(
            {
                "path": path.relative_to(project_dir).as_posix(),
                "size": path.stat().st_size,
                "extension": path.suffix.lower() or "<none>",
                **classification,
            }
        )
    return files


def summarize_resources(files: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for file_entry in files:
        grouped[(file_entry["resource_family"], file_entry["resource_type"])].append(file_entry)

    summaries: list[dict[str, Any]] = []
    for (family_id, resource_type), entries in sorted(grouped.items()):
        extensions = Counter(str(entry["extension"]) for entry in entries)
        top_levels = Counter(str(entry["path"]).split("/", 1)[0] for entry in entries)
        family = FAMILIES[family_id]
        summaries.append(
            {
                "resource_family": family_id,
                "family_label": family["label"],
                "resource_type": resource_type,
                "evidence_level": "coilsnake-observed",
                "file_count": len(entries),
                "total_file_bytes": sum(int(entry["size"]) for entry in entries),
                "extensions": dict(sorted(extensions.items())),
                "project_path_roots": sorted(top_levels),
                "source_banks": family["source_banks"],
                "local_status": family["local_status"],
                "related_local_docs": existing_docs(family["related_local_docs"]),
                "editable_reinsert_status": "observed-only; run a controlled edit/rebuild diff before promoting constraints",
            }
        )
    return summaries


def summarize_families(resources: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for resource in resources:
        grouped[resource["resource_family"]].append(resource)

    summaries: list[dict[str, Any]] = []
    for family_id in sorted(FAMILIES):
        family = FAMILIES[family_id]
        entries = grouped.get(family_id, [])
        summaries.append(
            {
                "id": family_id,
                "label": family["label"],
                "evidence_level": "coilsnake-observed" if entries else "not-observed-in-project",
                "local_status": family["local_status"],
                "resource_type_count": len(entries),
                "file_count": sum(int(entry["file_count"]) for entry in entries),
                "total_file_bytes": sum(int(entry["total_file_bytes"]) for entry in entries),
                "source_banks": family["source_banks"],
                "related_local_docs": existing_docs(family["related_local_docs"]),
            }
        )
    return summaries


def parse_compare_roms(values: list[str]) -> list[tuple[str, Path]]:
    comparisons: list[tuple[str, Path]] = []
    for value in values:
        if "=" not in value:
            raise ValueError(f"--compare-rom must use LABEL=PATH, got: {value}")
        label, path_text = value.split("=", 1)
        label = label.strip()
        if not label:
            raise ValueError(f"--compare-rom label is empty: {value}")
        comparisons.append((label, Path(path_text).expanduser().resolve()))
    return comparisons


def parse_experiment_reports(values: list[str]) -> list[Path]:
    return [Path(value).expanduser().resolve() for value in values]


def evidence_from_diff(diff: dict[str, Any] | None) -> str:
    if diff and diff.get("status") == "different":
        return "diff-confirmed"
    return "coilsnake-observed"


def experiment_status(report: dict[str, Any]) -> str:
    if report.get("dry_run"):
        return "dry-run"
    compile_result = report.get("compile")
    if isinstance(compile_result, dict):
        if compile_result.get("timed_out"):
            return "compile-timeout"
        if compile_result.get("returncode") == 0:
            diff = report.get("diff")
            if isinstance(diff, dict):
                return "diffed" if diff.get("status") == "different" else "compiled-no-diff"
            return "compiled"
        return "compile-failed"
    return "reported"


def sanitized_experiment_report(path: Path) -> tuple[str, dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(f"Experiment report not found: {path}")
    report = json.loads(path.read_text(encoding="utf-8"))
    experiment_id = report.get("experiment_id")
    if not isinstance(experiment_id, str) or not experiment_id:
        raise ValueError(f"Experiment report missing experiment_id: {path}")

    diff = report.get("diff") if isinstance(report.get("diff"), dict) else None
    compile_result = report.get("compile") if isinstance(report.get("compile"), dict) else {}
    sanitized_compile = {
        "returncode": compile_result.get("returncode"),
        "timed_out": bool(compile_result.get("timed_out", False)),
    }
    if "timeout_seconds" in compile_result:
        sanitized_compile["timeout_seconds"] = compile_result["timeout_seconds"]

    return experiment_id, {
        "report": rel(path),
        "experiment_status": experiment_status(report),
        "comparison_base": report.get("comparison_base"),
        "resource_family": report.get("resource_family", "uncategorized"),
        "source_file": report.get("source_file"),
        "edit": report.get("edit", "Controlled edit metadata not registered."),
        "evidence_level": evidence_from_diff(diff),
        "project_copy": report.get("project_copy"),
        "rebuilt_rom": report.get("rebuilt_rom"),
        "dry_run": bool(report.get("dry_run", False)),
        "compile": sanitized_compile,
        "diff": diff,
    }


def diff_roms(base: bytes, other_path: Path) -> dict[str, Any]:
    if not other_path.is_file():
        return {
            "path": rel(other_path),
            "exists": False,
            "status": "missing",
        }
    other = other_path.read_bytes()
    limit = min(len(base), len(other))
    runs: list[dict[str, Any]] = []
    changed_bytes = 0
    run_start: int | None = None

    for offset in range(limit):
        if base[offset] != other[offset]:
            changed_bytes += 1
            if run_start is None:
                run_start = offset
        elif run_start is not None:
            runs.append({"start": run_start, "end_exclusive": offset, "length": offset - run_start})
            run_start = None

    if run_start is not None:
        runs.append({"start": run_start, "end_exclusive": limit, "length": limit - run_start})

    size_delta = len(other) - len(base)
    if size_delta:
        changed_bytes += abs(size_delta)
        runs.append(
            {
                "start": limit,
                "end_exclusive": max(len(base), len(other)),
                "length": abs(size_delta),
                "kind": "size-delta",
            }
        )

    return {
        "path": rel(other_path),
        "exists": True,
        "status": "identical" if changed_bytes == 0 else "different",
        "base_size": len(base),
        "other_size": len(other),
        "changed_bytes": changed_bytes,
        "contiguous_changed_runs": len(runs),
        "first_changed_offset": f"0x{runs[0]['start']:06X}" if runs else None,
        "last_changed_offset_exclusive": f"0x{runs[-1]['end_exclusive']:06X}" if runs else None,
        "sample_runs": [
            {
                "start": f"0x{run['start']:06X}",
                "end_exclusive": f"0x{run['end_exclusive']:06X}",
                "length": run["length"],
                **({"kind": run["kind"]} if "kind" in run else {}),
            }
            for run in runs[:20]
        ],
    }


EXPERIMENT_METADATA = {
    "item-cost-probe": {
        "resource_family": "gameplay_yaml_tables",
        "source_file": "item_configuration_table.yml",
        "edit": "Changed the first Teddy bear Cost field from 178 to 179.",
        "evidence_level": "diff-confirmed",
    },
    "text-menu-probe": {
        "resource_family": "text_script_authoring",
        "source_file": "text_misc.yml",
        "edit": "Changed Battle Menu / Auto Fight display text from Auto Fight to Auto Fighu.",
        "evidence_level": "diff-confirmed",
    },
    "map-palette-probe": {
        "resource_family": "map_tilesets_and_runtime_tables",
        "source_file": "map_palette_settings.yml",
        "edit": "Changed the first Sprite Palette value from 4 to 5.",
        "evidence_level": "diff-confirmed",
    },
}


def build_crosswalk(
    project_dir: Path,
    rom_path: Path,
    coilsnake_version: str,
    compare_roms: list[tuple[str, Path]],
    experiment_base_rom: Path | None,
    experiment_roms: list[tuple[str, Path]],
    experiment_report_paths: list[Path],
) -> tuple[dict[str, Any], dict[str, Any]]:
    info = rom_tools.read_rom_info(rom_path)
    problems = rom_tools.verify_earthbound_us(info)
    base_rom = rom_tools.load_rom(rom_path)
    files = collect_project_files(project_dir)
    resources = summarize_resources(files)
    family_summaries = summarize_families(resources)
    diff_reports = {
        label: diff_roms(base_rom, path)
        for label, path in compare_roms
    }
    experiment_reports: dict[str, Any] = {}
    if experiment_roms:
        if experiment_base_rom is None:
            raise ValueError("--experiment-rom requires --experiment-base-rom")
        if not experiment_base_rom.is_file():
            raise FileNotFoundError(f"Experiment base ROM not found: {experiment_base_rom}")
        experiment_base = experiment_base_rom.read_bytes()
        for label, path in experiment_roms:
            diff = diff_roms(experiment_base, path)
            metadata = EXPERIMENT_METADATA.get(
                label,
                {
                    "resource_family": "uncategorized",
                    "source_file": None,
                    "edit": "Controlled edit metadata not registered.",
                },
            )
            experiment_reports[label] = {
                "comparison_base": rel(experiment_base_rom),
                **metadata,
                "evidence_level": evidence_from_diff(diff),
                "diff": diff,
            }
    for path in experiment_report_paths:
        label, report = sanitized_experiment_report(path)
        experiment_reports[label] = report

    project_summary = {
        "project_dir": rel(project_dir),
        "file_count": len(files),
        "total_file_bytes": sum(int(entry["size"]) for entry in files),
        "top_level_entries": sorted({entry["path"].split("/", 1)[0] for entry in files}),
    }

    manifest = {
        "schema": SCHEMA,
        "generated_by": "tools/build_coilsnake_project_inventory.py",
        "coilsnake": {
            "expected_version": coilsnake_version,
            "role": "local-only resource schema and compiler oracle; not a replacement for runtime decomp evidence",
            "official_docs": [
                "https://pk-hack.github.io/CoilSnake/",
                "https://github.com/pk-hack/CoilSnake/wiki",
            ],
        },
        "rom": {
            "path": rel(rom_path),
            "size": info.size,
            "sha1": info.sha1.upper(),
            "verified": not problems,
            "verification_problems": problems,
        },
        "evidence_levels": EVIDENCE_LEVELS,
        "project_summary": project_summary,
        "families": family_summaries,
        "resources": resources,
        "rom_diffs": diff_reports,
        "controlled_experiments": experiment_reports,
        "promotion_policy": [
            "Do not promote CoilSnake names or schemas into source labels without local ROM/routine evidence.",
            "Keep generated CoilSnake project files, rebuilt ROMs, and edit experiments under ignored build/coilsnake.",
            "Upgrade resource evidence to diff-confirmed only after a minimal edit/rebuild experiment identifies changed spans.",
        ],
        "recommended_diff_experiments": [
            "item_configuration_table.yml single numeric field edit",
            "enemy_configuration_table.yml single numeric field edit",
            "ccscript minimal text label/body edit",
            "map_palette_settings.yml or map sector field edit",
            "BattleSprites or BattleBG metadata/resource edit",
            "window_configuration_table.yml or Fonts width edit",
        ],
    }

    detailed_report = {
        **manifest,
        "files": files,
        "safety_note": "This ignored report records paths, sizes, and classifications only; it intentionally omits file contents.",
    }
    return manifest, detailed_report


def main() -> int:
    args = parse_args()
    project_dir = Path(args.project_dir).expanduser().resolve()
    if not project_dir.is_dir():
        print(
            f"CoilSnake project directory not found: {project_dir}\n"
            "Run CoilSnake decompile into build/coilsnake/baseline-project first, "
            "or pass --project-dir to an existing local CoilSnake project.",
            file=sys.stderr,
        )
        return 2

    try:
        rom_path = rom_tools.find_rom(args.rom)
        compare_roms = parse_compare_roms(args.compare_rom)
        experiment_roms = parse_compare_roms(args.experiment_rom)
        experiment_report_paths = parse_experiment_reports(args.experiment_report)
        experiment_base_rom = (
            Path(args.experiment_base_rom).expanduser().resolve()
            if args.experiment_base_rom
            else None
        )
        manifest, report = build_crosswalk(
            project_dir=project_dir,
            rom_path=rom_path,
            coilsnake_version=args.coilsnake_version,
            compare_roms=compare_roms,
            experiment_base_rom=experiment_base_rom,
            experiment_roms=experiment_roms,
            experiment_report_paths=experiment_report_paths,
        )
    except (FileNotFoundError, ValueError) as exc:
        print(exc, file=sys.stderr)
        return 2

    json_out = Path(args.json_out)
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    manifest_out = Path(args.manifest_out)
    manifest_out.parent.mkdir(parents=True, exist_ok=True)
    manifest_out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    summary = manifest["project_summary"]
    print(
        "CoilSnake crosswalk: "
        f"{summary['file_count']} files, "
        f"{len(manifest['resources'])} resource groups -> {rel(manifest_out)}"
    )
    print(f"Detailed local report: {rel(json_out)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
