#!/usr/bin/env python3
"""Index the locally recovered EarthBound localization script source.

The recovered .MSG corpus lives under refs/ and is intentionally ignored by
Git. This tool records only structural metadata so tracked docs can point at
the reference without checking in script text.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_DIR = ROOT / "refs" / "earthbound-script-source-1995-03-25"
DEFAULT_ZIP = Path(os.environ.get("EARTHBOUND_SCRIPT_SOURCE_ZIP", ROOT / "refs" / "EarthBound_Script_Source_1995-03-25.zip"))
DEFAULT_JSON = ROOT / "build" / "localization-script-source-index.json"
DEFAULT_NOTE = ROOT / "notes" / "localization-script-source-index.md"

METADATA_KEYS = [
    "Habitat",
    "Person",
    "Figure",
    "AppearanceKey",
    "ActionScript",
    "GoodsMessage",
    "CheckMessage",
    "Message",
]

LABEL_RE = re.compile(r"(?m)^([A-Za-z_][A-Za-z0-9_]*);")
METADATA_RE = re.compile(r"(?m)^;@([A-Za-z]+):")
COMMAND_RE = re.compile(r"@!?[A-Z0-9_]+")


def read_msg(path: Path) -> str:
    return path.read_text(encoding="cp932", errors="replace")


def sha256(path: Path) -> str | None:
    if not path.exists():
        return None
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def collect(source_dir: Path, zip_path: Path | None) -> dict:
    files = sorted(source_dir.glob("*.MSG"))
    if not files:
        raise SystemExit(f"no .MSG files found under {source_dir}")

    total_labels = 0
    total_msg_labels = 0
    total_jpn_comments = 0
    metadata_counts: Counter[str] = Counter()
    command_counts: Counter[str] = Counter()
    file_rows = []

    for path in files:
        text = read_msg(path)
        labels = LABEL_RE.findall(text)
        msg_labels = [label for label in labels if label.startswith("MSG_")]
        metadata = METADATA_RE.findall(text)
        commands = COMMAND_RE.findall(text)
        jpn_comments = len(re.findall(r"(?m)^;jpn:", text))

        total_labels += len(labels)
        total_msg_labels += len(msg_labels)
        total_jpn_comments += jpn_comments
        metadata_counts.update(metadata)
        command_counts.update(commands)

        file_rows.append(
            {
                "file": path.name,
                "bytes": path.stat().st_size,
                "labels": len(labels),
                "msg_labels": len(msg_labels),
                "metadata_records": metadata.count("Message"),
                "jpn_comments": jpn_comments,
                "commands": len(commands),
            }
        )

    return {
        "source_dir": str(source_dir.relative_to(ROOT) if source_dir.is_relative_to(ROOT) else source_dir),
        "zip_path": str(zip_path) if zip_path else None,
        "zip_sha256": sha256(zip_path) if zip_path else None,
        "encoding": "cp932",
        "file_count": len(files),
        "total_bytes": sum(row["bytes"] for row in file_rows),
        "labels": total_labels,
        "msg_labels": total_msg_labels,
        "jpn_comments": total_jpn_comments,
        "metadata_counts": {key: metadata_counts.get(key, 0) for key in METADATA_KEYS},
        "top_commands": command_counts.most_common(40),
        "files": file_rows,
    }


def write_note(index: dict, note_path: Path) -> None:
    lines = [
        "# Localization script source index",
        "",
        "Generated by `tools/index_localization_script_source.py` from the ignored",
        "local recovered EarthBound localization script source. This note records",
        "structural metadata only; the script corpus itself is not checked in.",
        "",
        "## Summary",
        "",
        f"- Local source dir: `{index['source_dir']}`.",
        f"- Original zip path: `{index['zip_path']}`.",
        f"- Original zip SHA-256: `{index['zip_sha256']}`.",
        f"- Encoding: `{index['encoding']}`.",
        f"- `.MSG` files indexed: `{index['file_count']}`.",
        f"- Total extracted bytes: `{index['total_bytes']}`.",
        f"- Total labels: `{index['labels']}`.",
        f"- `MSG_*` labels: `{index['msg_labels']}`.",
        f"- `;jpn:` comments: `{index['jpn_comments']}`.",
        "",
        "## Metadata Field Counts",
        "",
        "| Field | Count |",
        "| --- | ---: |",
    ]
    for key, count in index["metadata_counts"].items():
        lines.append(f"| `;@{key}:` | {count} |")

    lines.extend(
        [
            "",
            "## Top Control Commands",
            "",
            "| Command | Count |",
            "| --- | ---: |",
        ]
    )
    for command, count in index["top_commands"][:25]:
        lines.append(f"| `{command}` | {count} |")

    lines.extend(
        [
            "",
            "## File Inventory",
            "",
            "| File | Bytes | Labels | `MSG_*` labels | Records | `;jpn:` comments | Commands |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )
    for row in index["files"]:
        lines.append(
            f"| `{row['file']}` | {row['bytes']} | {row['labels']} | "
            f"{row['msg_labels']} | {row['metadata_records']} | "
            f"{row['jpn_comments']} | {row['commands']} |"
        )

    lines.extend(
        [
            "",
            "## Use",
            "",
            "- Use this corpus as the primary authoring-format reference for text,",
            "  message labels, NPC metadata records, and control-command syntax.",
            "- Keep the recovered `.MSG` files under ignored `refs/`; do not promote",
            "  verbatim script text into tracked docs or public source.",
            "- For C3/map-object work, treat `;@ActionScript:` values as behavior-name",
            "  hints until joined to ROM-backed map-object/actionscript records.",
            "- For C1/C5-C9/EF text work, prefer this source over flattened dumps when",
            "  control commands or unused/debug labels matter.",
            "",
        ]
    )
    note_path.parent.mkdir(parents=True, exist_ok=True)
    note_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--zip-path", type=Path, default=DEFAULT_ZIP)
    parser.add_argument("--json", type=Path, default=DEFAULT_JSON)
    parser.add_argument("--note", type=Path, default=DEFAULT_NOTE)
    parser.add_argument("--no-note", action="store_true")
    args = parser.parse_args()

    zip_path = args.zip_path if args.zip_path.exists() else None
    index = collect(args.source_dir, zip_path)

    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(index, indent=2, sort_keys=True), encoding="utf-8")
    print(f"wrote {args.json}")

    if not args.no_note:
        write_note(index, args.note)
        print(f"wrote {args.note}")

    print(
        "files={file_count} labels={labels} msg_labels={msg_labels} records={records}".format(
            records=index["metadata_counts"].get("Message", 0),
            **index,
        )
    )


if __name__ == "__main__":
    main()
