#!/usr/bin/env python3
"""Dump sanitized battler-row state from local Mesen save states."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

import rom_tools


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_STATE_DIR = Path(r"F:\Mesen2\SaveStates")
DEFAULT_OUTPUT = ROOT / "manifests" / "c2-save-state-battler-scout.json"
DEFAULT_NOTE = ROOT / "notes" / "c2-save-state-battler-scout.md"
COMMON_MESEN_PATHS = [
    Path(os.environ.get("MESEN_EXE", "")) if os.environ.get("MESEN_EXE") else None,
    Path(os.environ.get("MESEN_PATH", "")) if os.environ.get("MESEN_PATH") else None,
    Path(r"F:\Mesen2\Mesen.exe"),
    Path(r"F:\Mesen\Mesen.exe"),
    Path(r"C:\Mesen\Mesen.exe"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--state", action="append", help="Specific .mss save state. May repeat.")
    parser.add_argument("--state-dir", default=str(DEFAULT_STATE_DIR), help="Directory to scan for .mss save states.")
    parser.add_argument("--mesen", help="Path to Mesen.exe.")
    parser.add_argument("--rom", help="Path to EarthBound (USA).sfc.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--notes", default=str(DEFAULT_NOTE))
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--keep-raw", action="store_true", help="Keep ignored raw trace output under build/c2/save-state-battler-scout.")
    return parser.parse_args()


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    if not path.is_file():
        return rows
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def manifest_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return str(path)


def sha256(path: Path | None) -> str | None:
    if path is None:
        return None
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def candidate_states(args: argparse.Namespace) -> list[Path]:
    if args.state:
        return [Path(item) for item in args.state]
    state_dir = Path(args.state_dir)
    return sorted(state_dir.glob("*.mss")) if state_dir.exists() else []


def resolve_mesen(explicit_path: str | None) -> Path:
    if explicit_path:
        path = Path(explicit_path)
        if not path.is_file():
            raise FileNotFoundError(f"Mesen executable not found: {path}")
        return path
    for candidate in COMMON_MESEN_PATHS:
        if candidate and candidate.is_file():
            return candidate
    found = shutil.which("Mesen.exe") or shutil.which("Mesen")
    if found:
        return Path(found)
    searched = "\n".join(f"- {path}" for path in COMMON_MESEN_PATHS if path)
    raise FileNotFoundError(f"Unable to find Mesen.exe. Searched:\n{searched}\nPass --mesen.")


def lua_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_lua(path: Path) -> None:
    write_text(
        path,
        "\n".join(
            [
                "-- Generated by tools/probe_c2_save_state_battler_rows.py",
                "local outPath = os.getenv(\"C2_BATTLER_SCOUT_TRACE_OUT\")",
                "local statePath = os.getenv(\"C2_BATTLER_SCOUT_STATE_PATH\")",
                "local out = assert(io.open(outPath, \"w\"))",
                "local wram = emu.memType.snesWorkRam",
                "local snesMemory = emu.memType.snesMemory",
                "local snesCpu = emu.cpuType.snes",
                "local loaded = false",
                "local loadRef = nil",
                "local function q(s) return '\"' .. tostring(s):gsub('\\\\', '\\\\\\\\'):gsub('\"', '\\\\\"') .. '\"' end",
                "local function writeJson(obj)",
                "  local first = true",
                "  out:write(\"{\")",
                "  for k, v in pairs(obj) do",
                "    if not first then out:write(\",\") end",
                "    first = false",
                "    out:write(q(k), \":\")",
                "    if v == nil then out:write(\"null\") elseif type(v) == \"string\" then out:write(q(v)) elseif type(v) == \"boolean\" then out:write(v and \"true\" or \"false\") else out:write(tostring(v)) end",
                "  end",
                "  out:write(\"}\\n\")",
                "  out:flush()",
                "end",
                "local function readFile(filePath) local f = assert(io.open(filePath, \"rb\")); local d = f:read(\"*a\"); f:close(); return d end",
                "local function rb(addr) return emu.read(addr, wram, false) end",
                "local function rw(addr) return rb(addr) + (rb(addr + 1) * 0x100) end",
                "local function hex16(n) return string.format(\"$%04X\", n % 0x10000) end",
                "local function readBytes(addr, count) local parts = {}; for i = 0, count - 1 do parts[#parts + 1] = string.format(\"%02X\", rb((addr + i) % 0x10000)) end; return table.concat(parts, \" \") end",
                "local function rowNonzero(addr, count) for i = 0, count - 1 do if rb((addr + i) % 0x10000) ~= 0 then return true end end; return false end",
                "local function emitRow(rootId, index, base, stride)",
                "  local hp = rw(base + 0x13)",
                "  local pp = rw(base + 0x19)",
                "  local maxPp = rw(base + 0x1B)",
                "  if rowNonzero(base, stride) or hp ~= 0 or pp ~= 0 or maxPp ~= 0 then",
                "    writeJson({ type = \"battler_row\", rootId = rootId, index = index, base = hex16(base), hp = hp, pp = pp, maxPp = maxPp, sideByte = rb(base + 0x0E), consciousness = rb(base + 0x0C), rowHex = readBytes(base, stride) })",
                "  end",
                "end",
                "local function emitDump()",
                "  writeJson({ type = \"scout_start\", statePath = statePath, activeAttackerPointer = hex16(rw(0xA970)), selectedTargetPointer = hex16(rw(0xA972)), candidateRowPointer = hex16(rw(0x9FAC)), battleId = rw(0x4A8C), battleFlag = rw(0x4DB6) })",
                "  for i = 0, 15 do emitRow(\"battle_candidates_9fac\", i, 0x9FAC + (i * 0x4E), 0x4E) end",
                "  writeJson({ type = \"scout_done\" })",
                "  out:close()",
                "  emu.stop(0)",
                "end",
                "local function loadStateAndDump()",
                "  if loaded then return end",
                "  loaded = true",
                "  local state = readFile(statePath)",
                "  local ok = emu.loadSavestate(state)",
                "  writeJson({ type = \"state_load\", ok = ok, bytes = #state })",
                "  if loadRef ~= nil then emu.removeMemoryCallback(loadRef, emu.callbackType.exec, 0x008000, 0xFFFFFF, snesCpu, snesMemory) end",
                "  emitDump()",
                "end",
                "loadRef = emu.addMemoryCallback(loadStateAndDump, emu.callbackType.exec, 0x008000, 0xFFFFFF, snesCpu, snesMemory)",
            ]
        )
        + "\n",
    )


def run_state(mesen: Path, rom: Path, state: Path, lua: Path, trace: Path, timeout: int) -> dict[str, Any]:
    trace.parent.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    env["C2_BATTLER_SCOUT_TRACE_OUT"] = str(trace)
    env["C2_BATTLER_SCOUT_STATE_PATH"] = str(state)
    command = [
        str(mesen),
        "--testRunner",
        "--enableStdout",
        "--doNotSaveSettings",
        "--debug.scriptWindow.allowIoOsAccess=true",
        str(lua),
        str(rom),
    ]
    result = subprocess.run(command, cwd=ROOT, env=env, text=True, capture_output=True, timeout=timeout, check=False)
    return {
        "returncode": result.returncode,
        "stdout_tail": result.stdout[-2000:],
        "stderr_tail": result.stderr[-2000:],
        "command": command,
    }


def row_summary(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "root_id": row.get("rootId"),
        "index": row.get("index"),
        "base": row.get("base"),
        "hp": row.get("hp"),
        "pp": row.get("pp"),
        "max_pp": row.get("maxPp"),
        "side_byte": row.get("sideByte"),
        "consciousness": row.get("consciousness"),
        "row_sha256": hashlib.sha256(str(row.get("rowHex", "")).encode("utf-8")).hexdigest(),
    }


def row_at_pointer(rows: list[dict[str, Any]], pointer: Any) -> dict[str, Any] | None:
    pointer_text = str(pointer or "")
    for row in rows:
        if str(row.get("base")) == pointer_text:
            return row
    return None


def summarize_state(state: Path, trace: Path, run: dict[str, Any]) -> dict[str, Any]:
    rows = load_jsonl(trace)
    start = next((row for row in rows if row.get("type") == "scout_start"), {})
    battlers = [row_summary(row) for row in rows if row.get("type") == "battler_row"]
    pp_rows = [row for row in battlers if int(row.get("pp") or 0) > 0 or int(row.get("max_pp") or 0) > 0]
    active_row = row_at_pointer(battlers, start.get("activeAttackerPointer"))
    target_row = row_at_pointer(battlers, start.get("selectedTargetPointer"))
    return {
        "state_basename": state.name,
        "state_sha256": sha256(state),
        "trace_path": manifest_path(trace),
        "returncode": run["returncode"],
        "active_attacker_pointer": start.get("activeAttackerPointer"),
        "selected_target_pointer": start.get("selectedTargetPointer"),
        "candidate_row_pointer": start.get("candidateRowPointer"),
        "battle_id": start.get("battleId"),
        "battle_flag": start.get("battleFlag"),
        "battler_rows_seen": len(battlers),
        "pp_rows_seen": len(pp_rows),
        "active_row": active_row,
        "selected_target_row": target_row,
        "selected_target_has_pp": bool(target_row and (int(target_row.get("pp") or 0) > 0 or int(target_row.get("max_pp") or 0) > 0)),
        "pp_rows": pp_rows,
        "source_promotion_allowed": False,
        "behavior_change_allowed": False,
    }


def render_note(data: dict[str, Any]) -> str:
    lines = [
        "# C2 Save-State Battler Scout",
        "",
        "Generated by `tools/probe_c2_save_state_battler_rows.py` through the same",
        "Mesen test-runner path used by the C2 trace oracles. This is a local",
        "save-state inventory: it helps choose runtime probes, but it is not proof",
        "of action semantics by itself.",
        "",
        "## Summary",
        "",
        f"- states: `{data['summary']['state_count']}`",
        f"- states with PP-bearing rows: `{data['summary']['states_with_pp_rows']}`",
        f"- total PP-bearing battler rows: `{data['summary']['pp_row_count']}`",
        f"- states whose selected target row has PP: `{data['summary']['states_with_selected_target_pp']}`",
        "- source promotion allowed: `False`",
        "",
        "## States",
        "",
        "| State | Battle id | Active | Target | Target PP | Rows | PP rows | PP row samples |",
        "| --- | ---: | --- | --- | --- | ---: | ---: | --- |",
    ]
    for state in data["states"]:
        samples = ", ".join(
            f"[{row['index']}] {row['base']} PP {row['pp']}/{row['max_pp']}"
            for row in state["pp_rows"][:6]
        )
        target = state.get("selected_target_row") or {}
        target_pp = f"{target.get('pp')}/{target.get('max_pp')}" if target else "-"
        lines.append(
            "| `{state}` | `{battle}` | `{active}` | `{target}` | `{target_pp}` | `{rows}` | `{pp_rows}` | {samples} |".format(
                state=state["state_basename"],
                battle=state.get("battle_id"),
                active=state.get("active_attacker_pointer"),
                target=state.get("selected_target_pointer"),
                target_pp=target_pp,
                rows=state.get("battler_rows_seen"),
                pp_rows=state.get("pp_rows_seen"),
                samples=samples or "-",
            )
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    states = candidate_states(args)
    if not states:
        raise FileNotFoundError("No save states found")
    mesen = resolve_mesen(args.mesen)
    rom = rom_tools.find_rom(args.rom)
    if args.keep_raw:
        raw_root = ROOT / "build" / "c2" / "save-state-battler-scout"
        raw_root.mkdir(parents=True, exist_ok=True)
        temp_context: tempfile.TemporaryDirectory[str] | None = None
    else:
        temp_context = tempfile.TemporaryDirectory(prefix="c2-save-state-battler-scout-")
        raw_root = Path(temp_context.name)
    try:
        lua = raw_root / "dump_battler_rows.lua"
        render_lua(lua)
        summaries: list[dict[str, Any]] = []
        for state in states:
            trace = raw_root / (state.stem.replace(" ", "_").replace("(", "").replace(")", "") + ".jsonl")
            run = run_state(mesen, Path(rom), state, lua, trace, args.timeout)
            summaries.append(summarize_state(state, trace, run))
        pp_row_count = sum(int(state["pp_rows_seen"]) for state in summaries)
        selected_target_pp_count = sum(1 for state in summaries if state["selected_target_has_pp"])
        data = {
            "schema": "earthbound-decomp.c2-save-state-battler-scout.v1",
            "status": "local_probe_inventory_only",
            "generated_by": "tools/probe_c2_save_state_battler_rows.py",
            "mesen_path": str(mesen),
            "rom_path": manifest_path(Path(rom)),
            "summary": {
                "state_count": len(summaries),
                "states_with_pp_rows": sum(1 for state in summaries if int(state["pp_rows_seen"]) > 0),
                "pp_row_count": pp_row_count,
                "states_with_selected_target_pp": selected_target_pp_count,
                "source_promotion_allowed": False,
                "behavior_change_allowed": False,
            },
            "states": summaries,
        }
        write_json(Path(args.output), data)
        write_text(Path(args.notes), render_note(data))
    finally:
        if temp_context is not None:
            temp_context.cleanup()
    print(f"Wrote {args.output}")
    print(f"Wrote {args.notes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
