; EarthBound C7 text segment EHINT.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/c7-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - C7:0000..C7:2709 TextSegmentEhint

; ---------------------------------------------------------------------------
; C7:2709

; TextSegmentEhintEnd
C72709_TextSegmentEhintEnd:
