; EarthBound E0 asset TOWN_MAP_SCARABA.
;
; Source-emission status:
; - Prototype level: build-candidate data corridor.
; - Generated by tools/promote_source_bank_data_range.py.
; - ROM bytes are preserved by build/e0-build-candidate-ranges.json
;   as one data gap before the terminal label below.
;
; Source units covered:
; - E0:ADB4..E0:C7F1 AssetTownMapScaraba

; ---------------------------------------------------------------------------
; E0:C7F1

; AssetTownMapScarabaEnd
E0C7F1_AssetTownMapScarabaEnd:
