; Generated by tools/build_source_bank_scaffold.py
; Byte-preserving Asar listing for this source unit.
; Source: src/ca/table_data_battle_backgrounds_arrangement_pointers_asm.asm

hirom
org $CAD93D

!CADAD9_TableArrangementPointersEnd = BATTLEBG_PALETTE_POINTERS

; Original terminal data gap ending at $CADAD9
db $71,$D8,$CB,$00,$9D,$89,$CB,$00,$6C,$55,$CB,$00,$2A,$B2,$CB,$00
db $8F,$49,$CB,$00,$11,$64,$CB,$00,$C1,$3F,$CB,$00,$B3,$4C,$CB,$00
db $9E,$52,$CB,$00,$A3,$31,$CB,$00,$08,$25,$CB,$00,$68,$C5,$CB,$00
db $01,$85,$CB,$00,$2D,$B6,$CB,$00,$BD,$A6,$CB,$00,$00,$A2,$CB,$00
db $84,$2D,$CB,$00,$65,$C2,$CB,$00,$B7,$BA,$CB,$00,$8F,$C3,$CB,$00
db $B9,$BC,$CB,$00,$0F,$C5,$CB,$00,$B2,$C4,$CB,$00,$A5,$B9,$CB,$00
db $3D,$BC,$CB,$00,$00,$C2,$CB,$00,$CC,$38,$CB,$00,$ED,$AF,$CB,$00
db $FA,$A3,$CB,$00,$33,$C1,$CB,$00,$32,$BD,$CB,$00,$6A,$A9,$CB,$00
db $C0,$BB,$CB,$00,$53,$C4,$CB,$00,$5D,$95,$CB,$00,$28,$80,$CB,$00
db $C9,$7C,$CB,$00,$92,$B0,$CA,$00,$1E,$BE,$CA,$00,$A1,$C4,$CA,$00
db $58,$29,$CB,$00,$95,$0B,$CB,$00,$09,$CB,$CA,$00,$00,$00,$CB,$00
db $AC,$96,$CB,$00,$93,$B3,$CB,$00,$F2,$C3,$CB,$00,$6C,$AE,$CB,$00
db $0A,$BF,$CB,$00,$8C,$86,$CB,$00,$71,$9A,$CB,$00,$27,$5D,$CB,$00
db $FF,$6F,$CB,$00,$D2,$61,$CB,$00,$8D,$B5,$CB,$00,$2D,$AF,$CB,$00
db $2B,$66,$CB,$00,$97,$BE,$CB,$00,$1A,$B9,$CB,$00,$3D,$6A,$CB,$00
db $F2,$05,$CB,$00,$10,$1C,$CB,$00,$21,$11,$CB,$00,$9F,$20,$CB,$00
db $91,$5F,$CB,$00,$9C,$AD,$CB,$00,$59,$3C,$CB,$00,$CA,$C0,$CB,$00
db $FF,$A2,$CB,$00,$ED,$B4,$CB,$00,$E1,$B2,$CB,$00,$6C,$D8,$CB,$00
db $67,$D8,$CB,$00,$62,$D8,$CB,$00,$5D,$D8,$CB,$00,$58,$D8,$CB,$00
db $53,$D8,$CB,$00,$4E,$D8,$CB,$00,$2A,$8E,$CB,$00,$49,$D8,$CB,$00
db $44,$D8,$CB,$00,$3F,$D8,$CB,$00,$6A,$83,$CB,$00,$3A,$D8,$CB,$00
db $28,$58,$CB,$00,$16,$88,$CB,$00,$A8,$5A,$CB,$00,$35,$D8,$CB,$00
db $21,$BE,$CB,$00,$2B,$6C,$CB,$00,$30,$D8,$CB,$00,$EE,$BF,$CB,$00
db $0B,$C7,$CB,$00,$3F,$68,$CB,$00,$4F,$79,$CB,$00,$81,$77,$CB,$00
db $A8,$8C,$CB,$00,$3F,$35,$CB,$00,$66,$46,$CB,$00,$24,$8B,$CB,$00
db $49,$D1,$CA,$00,$12,$7B,$CB,$00,$F0,$97,$CB,$00
